Fix: Refactor init mongodb flow to check and enable replica set for external mongodb
appsmithorg/appsmith pull request #10010
Opened 2021-12-27 10:04 UTC by geekup-legodevops

## Description
- Add flow to check if MongoDB URI pointing to local service or not. Perform local mongodb init as normal
- Remove unnecessary environment variables for MongoDB credentials and directly extract credentials from URI
- Add prefix /api/v1 in the API_BASE_URL 
- Add flow to check external MongoDB is set as replica set or not. If not, configure it as replica set.

Fixes # (issue)

[[Bug]: Using external MongoDB will still try to connect and configure local MongoDB](https://github.com/appsmithorg/appsmith/issues/9513)

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-01-06 12:44 UTC, sharat87 requested changes
In addition to these comments, I _think_ there's a conflict as well. Please merge release back into this branch just in case.

2022-01-06 12:44 UTC, sharat87 commented on deploy/docker/entrypoint.sh
> +  MONGODB_DATABASE=$(echo "$APPSMITH_MONGODB_URI" | grep -oP "\w+(?!\S)")
Can you confirm if this works when the URI has query params with `?authSource=admin` as well as when there are no query params at all?

2022-01-06 12:44 UTC, sharat87 commented on deploy/docker/entrypoint.sh
> +    okString='ok : 1'
I just ran this command and the output shows `ok: 1`, not `ok : 1`, is that okay? Will it still match?

2022-01-06 12:44 UTC, sharat87 commented on deploy/docker/entrypoint.sh
> +  if [[ "$APPSMITH_MONGODB_URI" = "mongodb://appsmith:$MONGODB_PASSWORD@$MONGODB_HOST/appsmith" && $isUriLocal -eq 0 ]]; then
Isn't checking `isUriLocal` enough here? In the first check, we are basically checking is username is `appsmith` and database name is `appsmith`. The other two things, password and host, are basically extracted from `APPSMITH_MONGODB_URI` only, so they'll anyway match.

2022-01-07 07:28 UTC, geekup-legodevops commented on deploy/docker/entrypoint.sh
> +    okString='ok : 1'
Hi @sharat87 have you run the whole command with the 'xargs' command ? Last time we checked, the 'xargs' command will make the `ok: 1` string to `ok : 1`

2022-01-07 07:30 UTC, sharat87 commented on deploy/docker/entrypoint.sh
> +    okString='ok : 1'
Oh I see, cool, thanks for confirming.

2022-02-07 07:55 UTC, sharat87 approved these changes

2022-02-09 09:02 UTC, merged

2022-02-27 16:52 UTC, MichaelLeeHobbs commented
#11418 Bug on line 125

```
  if [[ $isUriLocal -gt 0 ]]; then
```

Should be

```
  if [[ $isUriLocal -eq 0 ]]; then
```