fix: changed validation to FUNCTION for the default selected value RadioGroupWidget
appsmithorg/appsmith pull request #10020
Opened 2021-12-27 13:18 UTC by keyurparalkar

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.

## Description

> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change.

Fixes #9834 

> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-12-28 08:24 UTC, keyurparalkar commented
/ok-to-test sha=797e18b

2021-12-28 09:07 UTC, keyurparalkar commented
/ok-to-test sha=797e18b

2021-12-28 11:45 UTC, keyurparalkar commented
/ok-to-test sha=eda181a

2021-12-28 14:04 UTC, keyurparalkar commented
/ok-to-test sha=eda181a

2021-12-28 14:08 UTC, keyurparalkar commented
/ok-to-test sha=3b53fb4

2021-12-29 05:32 UTC, sbalaji1192 commented on app/client/src/widgets/RadioGroupWidget/widget/index.tsx
> +  if (typeof value === "number") {
use _.isNumber() here. Its more readeable.

2021-12-29 05:32 UTC, sbalaji1192 commented on app/client/src/widgets/RadioGroupWidget/widget/index.tsx
> +function defaultOptionValueValidation(value: unknown): ValidationResponse {
suggestion: `defaultOptionValidation` is more appropriate.

2021-12-29 05:32 UTC, sbalaji1192 commented on app/client/src/widgets/RadioGroupWidget/widget/index.tsx
> +  if (typeof value === "number") {
Why do we need this condition. it seems in all cases we're returning 
`return {
    isValid: true,
    parsed: value,
  };`

2021-12-29 05:32 UTC, sbalaji1192 commented on app/client/src/widgets/RadioGroupWidget/widget/index.tsx
> +    if (typeof this.props.options[0].value === "number") {
use _.isNumber here

2021-12-29 05:32 UTC, sbalaji1192 commented on app/client/src/widgets/RadioGroupWidget/widget/index.tsx
> +    if (typeof this.props.options[0].value === "number") {
if typeof `this.props.options[0].value` is already a number, why do we need to parseFloat it ?

2021-12-29 06:28 UTC, keyurparalkar commented on app/client/src/widgets/RadioGroupWidget/widget/index.tsx
> +    if (typeof this.props.options[0].value === "number") {
@sbalaji1192 the this.props.options[0].value is not number it depends on the value that is passed to it.

2021-12-29 06:42 UTC, sbalaji1192 commented on app/client/src/widgets/RadioGroupWidget/widget/index.tsx
> +    if (typeof this.props.options[0].value === "number") {
understood

2021-12-29 07:03 UTC, keyurparalkar commented on app/client/src/widgets/RadioGroupWidget/widget/index.tsx
> +function defaultOptionValueValidation(value: unknown): ValidationResponse {
Yes, I have changed the name of the functions as suggested

2021-12-29 07:03 UTC, keyurparalkar commented on app/client/src/widgets/RadioGroupWidget/widget/index.tsx
> +  if (typeof value === "number") {
Removed the condition, now directly returning the object

2021-12-29 09:01 UTC, sbalaji1192 approved these changes
LGTM. Good work!

2021-12-29 09:21 UTC, keyurparalkar commented
/ok-to-test sha=227038a

2021-12-30 05:50 UTC, YogeshJayaseelan commented
@keyurparalkar Verified this PR and now user will be able to pass integer in the default value of radio group with the following format {{1}}

Observed one issue 

Issue 1 - Since the default value structure is Sting | Number - The expected example should be abc | {{1}} instead of 1 | {{1}}

<img width="1680" alt="Screenshot 2021-12-30 at 11 17 16 AM" src="https://user-images.githubusercontent.com/35128442/147725180-2f1361d8-03b0-4160-8cd4-99f19ce92ffe.png">

2022-01-17 11:09 UTC, sbalaji1192 commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/RadioGroup_Int_Value_spec.js
> +    cy.validateCodeEditorContent(
remove validateCodeEditorContent

2022-01-17 11:09 UTC, sbalaji1192 commented on app/client/src/widgets/RadioGroupWidget/widget/propertyPaneConfig.test.ts
> +  // it("case: check the value returned by options property", () => {
Do we need this commented case?

2022-01-17 11:09 UTC, sbalaji1192 commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/RadioGroup_Int_Value_spec.js
> +    });
add a test case where default option and option value type don't match

2022-01-17 13:44 UTC, keyurparalkar commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/RadioGroup_Int_Value_spec.js
> +    });
For this, we have added a helper message in the expected section of the default selected value. So whenever the user needs default selected value as an integer they should bind it with `{{}}` or if its a string the they can type normally. This will make sure that the data type in the default selected value and the options value is similar. 
To satisfy this scenario we have the first test case.

2022-01-17 13:44 UTC, keyurparalkar commented on app/client/src/widgets/RadioGroupWidget/widget/index.tsx
> +        message = "path:value must be unique. Duplicate values found";
Done

2022-01-17 13:48 UTC, keyurparalkar commented on app/client/src/widgets/RadioGroupWidget/widget/index.tsx
> + * Validation requirement for the options property of this widget:
Done

2022-01-17 13:49 UTC, keyurparalkar commented on app/client/src/widgets/RadioGroupWidget/widget/index.tsx
> + * 3. The `value` property can accept strings or numbers.
3, 4, 6 removed. Validation rules updated.

2022-01-17 13:49 UTC, keyurparalkar commented on app/client/src/widgets/RadioGroupWidget/widget/index.tsx
> +        label === null ||
Replaced with `_.isNil()`

2022-01-17 13:49 UTC, keyurparalkar commented on app/client/src/widgets/RadioGroupWidget/widget/index.tsx
> +      if (!value && value !== "") {
Replaced with _.isNil()

2022-01-17 13:50 UTC, keyurparalkar commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/RadioGroup_Int_Value_spec.js
> +    cy.validateCodeEditorContent(
Removed

2022-01-17 13:50 UTC, keyurparalkar commented on app/client/src/widgets/RadioGroupWidget/widget/propertyPaneConfig.test.ts
> +  // it("case: check the value returned by options property", () => {
Removed this case

2022-01-20 11:57 UTC, sbalaji1192 commented on app/client/src/widgets/RadioGroupWidget/widget/index.tsx
> +        _.isNil(value) ||
was this supposed to be _.isNil(label)?

2022-01-20 11:57 UTC, sbalaji1192 commented on app/client/yarn.lock
>    dependencies:
do we need these changes?

2022-01-21 06:24 UTC, keyurparalkar commented on app/client/src/widgets/RadioGroupWidget/widget/index.tsx
> +        _.isNil(value) ||
Done

2022-01-21 06:25 UTC, keyurparalkar commented on app/client/yarn.lock
>    dependencies:
These changes were present in the previous release branch. Merging the new release branch resolved this

2022-01-21 06:37 UTC, sbalaji1192 requested changes

2022-01-21 06:37 UTC, sbalaji1192 commented on app/client/src/widgets/RadioGroupWidget/widget/index.tsx
> +
we should write a block for `{{true}}` as well

2022-01-21 06:53 UTC, keyurparalkar commented on app/client/src/widgets/RadioGroupWidget/widget/index.tsx
> +
Added the boolean block

2022-01-21 06:59 UTC, sbalaji1192 requested changes

2022-01-21 06:59 UTC, sbalaji1192 commented on app/client/src/widgets/RadioGroupWidget/widget/index.tsx
> +      parsed: JSON.stringify(value, null, 2),
we don't need to stringify it.

2022-01-21 07:23 UTC, sbalaji1192 approved these changes

2022-01-21 07:23 UTC, keyurparalkar commented
/ok-to-test sha=85494f4

2022-01-21 07:32 UTC, keyurparalkar commented
/ok-to-test sha=7e5a352

2022-01-21 11:22 UTC, keyurparalkar commented
/ok-to-test sha=7e5a352

2022-01-25 07:54 UTC, shwetha-ramesh commented
@keyurparalkar Tested this PR. DP looks good.
Moving to Done

2022-01-26 07:18 UTC, merged