Added check for duplicate values in dropdown
appsmithorg/appsmith pull request #1011
Opened 2020-10-05 20:37 UTC by Caitlin-Fotheringham

Added check for any duplicates, returning invalid if any are present.

Fixes appsmithorg/appsmith#655

2020-10-06 06:17 UTC, hetunandu requested changes
Great start @Caitlin-Fotheringham ! But we always want to return options even if one of them is invalid. That means that we need to make sure that even if there are duplicate `option.value` we will parse and return a unique list of options from here

2020-10-06 06:17 UTC, hetunandu commented on app/client/src/utils/Validators.ts
> +    if (!hasOptions || new Set(values).size !== values.length) {
can we instead use the unique function of lodash and return a parsed value what is always guaranteed to be unique

2020-10-06 08:15 UTC, Caitlin-Fotheringham commented on app/client/src/utils/Validators.ts
> +    if (!hasOptions || new Set(values).size !== values.length) {
I will work on this today! To clarify, if a duplicate is found do you want it to return as invalid or do you want to ensure parsed all has unique values, removing any duplicates, but returning as valid?

2020-10-06 08:18 UTC, hetunandu commented on app/client/src/utils/Validators.ts
> +    if (!hasOptions || new Set(values).size !== values.length) {
If duplicates are found, mark it as invalid but return unique options in `parsed`

2020-10-06 08:28 UTC, Caitlin-Fotheringham commented on app/client/src/utils/Validators.ts
> +    if (!hasOptions || new Set(values).size !== values.length) {
I see what you mean now, thank you

2020-10-06 12:23 UTC, hetunandu commented on app/client/src/utils/Validators.ts
> +    if (!hasOptions || _.uniq(values).length !== values.length) {
Why do we create a new values array over here? Can't we just compare the length of `parsed` and `_.uniq(parsed, 'value')`

2020-10-06 12:30 UTC, Caitlin-Fotheringham commented on app/client/src/utils/Validators.ts
> +    if (!hasOptions || _.uniq(values).length !== values.length) {
That is a very good point, I'll do that now

2020-10-07 07:12 UTC, hetunandu approved these changes

2020-10-07 07:13 UTC, merged

2020-10-07 07:21 UTC, hetunandu commented
Thanks for this @Caitlin-Fotheringham ! This was a good PR. 😃 Hope to see more contributions from you in the coming days