on pressing f2 widget title is focused
appsmithorg/appsmith pull request #10148
Opened 2022-01-04 11:40 UTC by ankurrsinghal

## Description

> Added a new property to store to manage whether Property Pane Widget Title is in editing state or not.

Enhancement #9413

## Type of change

- New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-01-04 12:26 UTC, aswathkk requested changes
@ankurrsinghal
Editing `ads/EditableText` component has cascading effects since this component is being used in other places such as JSEditor.
As you see, usage of `F2` is also working on JSEditor page as well. This shouldn't be happening.

Can you also add cypress tests for this PR?

2022-01-04 12:29 UTC, aswathkk commented on app/client/src/components/ads/EditableText.tsx
> +function useIsEditing(
Can we if moving this logic to `PropertyPaneTitle.tsx` is possible?

2022-01-07 11:37 UTC, marks0351 commented on app/client/src/components/ads/EditableText.tsx
> +  const [isEditing, setIsEditing] = useIsEditing(!!isEditingDefault);
continue keeping this as a state and add an effect with isEditingDefault as dependency and call setIsEditing when it changes. when f2 key is pressed get the event and update the props that are passed to the EditableText.tsx

2022-01-07 11:39 UTC, ankurrsinghal commented on app/client/src/components/ads/EditableText.tsx
> +  const [isEditing, setIsEditing] = useIsEditing(!!isEditingDefault);
_when f2 key is pressed get the event_
How will I bind to this event, since it's a Hotkey in GlobalHotKeys?

2022-01-07 11:42 UTC, marks0351 commented on app/client/src/components/ads/EditableText.tsx
> +  const [isEditing, setIsEditing] = useIsEditing(!!isEditingDefault);
try using react context. provide a callback to the context and call it from the global hotkeys callback.

2022-01-07 11:46 UTC, ankurrsinghal commented on app/client/src/components/ads/EditableText.tsx
> +  const [isEditing, setIsEditing] = useIsEditing(!!isEditingDefault);
Okay, that's what I was trying to avoid by directly adding a keydown handler in PropertyPaneTitle itself. I will try that.

2022-01-12 05:23 UTC, marks0351 requested changes

2022-01-12 05:23 UTC, marks0351 commented on app/client/src/pages/Editor/GlobalHotKeys.tsx
> +            this.props.focusWidgetTitle();
i suggest to trigger a context provided callback from property pane title instead of dispatching a redux state.

2022-01-12 05:23 UTC, marks0351 commented on app/client/src/reducers/uiReducers/propertyPaneReducer.tsx
> +  [ReduxActionTypes.FOCUS_WIDGET_TITLE]: (
if we use the callback we wont be needing an explicit state.

2022-01-12 05:23 UTC, marks0351 commented on app/client/src/components/ads/EditableText.tsx
> +function useIsEditing(
i agree with @aswathkk can we move this logic to PropertyPaneTitle and make EditableText change its edit mode by toggling its props.
EditableText wud have become editable and readable based on props supplied from PropertyPaneTitle.
PropertyPaneTitle wud provide a callback for the keydown.
context of PropertyPaneTitle will be used in GlobalHotkeys to trigger when f2 is pressed.
the callback when triggered will make sure to make property pane title editable only when it is being focused.

2022-01-31 16:42 UTC, closed without merging