Feature: Add Helm configMap to update application configuration
appsmithorg/appsmith pull request #10157
Opened 2022-01-05 03:29 UTC by geekup-legodevops

## Description
- Adding Helm ConfigMap for users who deploy Appsmith by Helm Chart to change application configuration
- Refactor the flow that being used to generate environment variables for supporting predefined environment variables when initializing the container
## Type of change

- New feature (non-breaking change which adds functionality)

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-01-10 13:15 UTC, sharat87 requested changes

2022-01-10 13:15 UTC, sharat87 commented on deploy/docker/templates/docker.env.sh
> +APPSMITH_SENTRY_DSN=${APPSMITH_SENTRY_DSN:-\$APPSMITH_SENTRY_DSN}
Do these values need to be wrapped in `"` characters? If the current value of this coming from ConfigMap contains a special character like `'` or a space character, does it not get interpreted differently here?

2022-01-10 13:15 UTC, sharat87 commented on deploy/docker/entrypoint.sh
> +      export APPSMITH_MONGODB_URI=mongodb://appsmith:$AUTO_GEN_MONGO_PASSWORD@localhost/appsmith
The password might contain special characters. Wrapping in `"` won't fix the case where the password contains `"` itself, but it solves 90% of the cases, including `'` or the space character.

```suggestion
      export APPSMITH_MONGODB_URI="mongodb://appsmith:$AUTO_GEN_MONGO_PASSWORD@localhost/appsmith"
```

2022-01-10 13:15 UTC, sharat87 commented on deploy/docker/entrypoint.sh
> +      export APPSMITH_ENCRYPTION_PASSWORD=$AUTO_GEN_ENCRYPTION_PASSWORD
Same thing as above.

```suggestion
      export APPSMITH_ENCRYPTION_PASSWORD="$AUTO_GEN_ENCRYPTION_PASSWORD"
```

2022-01-10 13:15 UTC, sharat87 commented on deploy/docker/entrypoint.sh
> +      export APPSMITH_ENCRYPTION_SALT=$AUTO_GEN_ENCRYPTION_SALT
Same thing as above.

```suggestion
      export APPSMITH_ENCRYPTION_SALT="$AUTO_GEN_ENCRYPTION_SALT"
```

2022-01-10 13:15 UTC, sharat87 commented on deploy/docker/templates/docker.env.sh
> +APPSMITH_SENTRY_DSN=${APPSMITH_SENTRY_DSN:-\$APPSMITH_SENTRY_DSN}
Also, isn't this the same as:

```sh
APPSMITH_SENTRY_DSN=${APPSMITH_SENTRY_DSN:-}
```

That is to say, if the variable isn't defined already, we set it to empty instead of the default value. But if the variable isn't set already, the currently value is also empty so this should behave the same, right?

2022-01-10 13:15 UTC, sharat87 commented on deploy/docker/entrypoint.sh
> +    cat "$TEMPLATES_PATH/docker.env.temp" | envsubst "$(printf '$%s,' $(env | grep -Eo '^APPSMITH_[A-Z0-9_]+'))" | sed -e 's|\$APPSMITH_[A-Z0-9_]*||g' > "$ENV_PATH"
Can you elaborate why we need to replace the env variable values into the `docker.env` file? Can we not have all the variables look like `APPSMITH_ENV_VAR="${APPSMITH_ENV_VAR:-}"`?

2022-01-10 13:15 UTC, sharat87 commented on deploy/helm/README.md
> +| `applicationConfig.APPSMITH_ALGOLIA_SEARCH_INDEX_NAME`	| `""`									|
Let's remove these from the docs. These are kinda internal variables.

2022-01-10 13:15 UTC, sharat87 commented on deploy/helm/README.md
> +| `applicationConfig.APPSMITH_SMART_LOOK_ID`							| `""`									|
Let's remove these, they are internal.

2022-01-10 13:15 UTC, sharat87 commented on deploy/helm/values.yaml
> +  APPSMITH_ALGOLIA_SEARCH_INDEX_NAME: ""
Let's remove internal variables here as well.

```suggestion
  APPSMITH_OAUTH2_GOOGLE_CLIENT_ID: ""
  APPSMITH_OAUTH2_GOOGLE_CLIENT_SECRET: ""
  APPSMITH_OAUTH2_GITHUB_CLIENT_ID: ""
  APPSMITH_OAUTH2_GITHUB_CLIENT_SECRET: ""
```

2022-01-25 13:24 UTC, sharat87 reviewed
Looks much better, thanks guys. Just a couple of minor questions, otherwise we are ready to merge this in!

2022-01-25 13:24 UTC, sharat87 commented on deploy/docker/entrypoint.sh
> +  printenv | grep -Eo '^APPSMITH_[A-Z0-9_]+=.*|^MONGO_[A-Z0-9_]+=.*' > "$TEMPLATES_PATH/pre-define.env"
```suggestion
  printenv | grep -E '^APPSMITH_|^MONGO_' > "$TEMPLATES_PATH/pre-define.env"
```

2022-01-25 13:24 UTC, sharat87 commented on deploy/docker/templates/docker.env.sh
> +APPSMITH_GOOGLE_MAPS_API_KEY=${APPSMITH_GOOGLE_MAPS_API_KEY:-}
Since we now have the `pre-define.env` file, do we still need this current value interpolation here? Like, can't we just have `APPSMITH_GOOGLE_MAPS_API_KEY=` instead?

2022-01-31 07:52 UTC, sharat87 approved these changes

2022-01-31 07:57 UTC, merged

2022-03-11 15:20 UTC, WernerDreierB commented on deploy/docker/entrypoint.sh
> +  . "$TEMPLATES_PATH/pre-define.env"
Hi all, 
seems to me, this line, does not work as expcected on our kubernetes 1.21 environment. 
only default-env-vars from $ENV_PATH are actually used within the script, following "pre-define.env"-files are not picked up, even though the file exists and contains values (e.g. for mongo-db). 

See attached screenshot, where I entered some debugging points to point out env-variables while running entrypoint.sh: 
![error_on_override](https://user-images.githubusercontent.com/15634299/157895863-8876401f-12cc-4fb8-ae04-aec0797c4a33.png)

2022-03-11 15:22 UTC, WernerDreierB commented on deploy/docker/entrypoint.sh
> +  . "$TEMPLATES_PATH/pre-define.env"
@sharat87 could you have a look at this?

2022-03-12 00:24 UTC, sharat87 commented on deploy/docker/entrypoint.sh
> +  . "$TEMPLATES_PATH/pre-define.env"
Hey, while I'm not sure of this without looking at the `entrypoint_wdr.sh` script, I think you are dealing with the issue fixed in this PR: https://github.com/appsmithorg/appsmith/pull/11799. We should be publishing it soon.

As a workaround in the meantime, could you try adding a backslash just before the `?` and see if that makes a difference?

2022-03-14 10:28 UTC, WernerDreierB commented on deploy/docker/entrypoint.sh
> +  . "$TEMPLATES_PATH/pre-define.env"
@sharat87 Thank you for pointing out https://github.com/appsmithorg/appsmith/pull/11799 to me. Actually escaping Question-Marks (?) and Ampersands (&) with a backslash (or in my case double back-slash to get it through our own scripting-pipeline) worked for me. Looking forward to the PR to be released, as other special-chars might be problematic as well (as described in the PR)
Thank you