chore: Make sure to keep forked application in valid state even if client exits the flow before server responds
appsmithorg/appsmith pull request #10220
Opened 2022-01-06 16:55 UTC by abhvsn

## Description

Fork application is currently a slow API because it needs to create an application, fork all the pages, and then copy all the actions and collections. This process may take time and the client may cancel the request. This leads to the flow getting stopped midway producing corrupted DB objects. The PR ensures that even though the client may have cancelled the flow, the forking of the application should proceed uninterrupted and whenever the user refreshes the page, the sane forked application is available.

Fixes #10184 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> JUnit TC
> Manual test

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-01-06 17:01 UTC, abhvsn commented
/ok-to-test sha=aa33018

2022-01-10 08:48 UTC, sharat87 requested changes

2022-01-10 08:48 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ApplicationForkingServiceCEImpl.java
> +        );
If the client _doesn't_ cancel the request, does it wait for the server to finish forking the application?

2022-01-10 09:01 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ApplicationForkingServiceCEImpl.java
> +        );
Yes that's correct. For reference you can check the `cloneApplication` implementation, from which I took the inspiration to implement MonoSink.

2022-01-10 09:08 UTC, sharat87 approved these changes

2022-01-11 10:50 UTC, merged