feat: Input, Phone no., Currency input widget
appsmithorg/appsmith pull request #10259
Opened 2022-01-10 05:28 UTC by sbalaji1192

## Description

- Now input values are read from the dom as datatypes based on the input type
- Have segregated currency and phone no. into its own widget.

Fixes #9119 

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-01-11 04:51 UTC, jsartisan commented on app/client/src/widgets/CurrencyInputWidget/widget/derived.js
> +        /*
not sure but it seems the comment is not closing as expected.

2022-01-12 00:07 UTC, riodeuno requested changes
Reviewed 20 odd files, I'll get back to reviewing the rest, after getting some rest.

2022-01-12 00:07 UTC, riodeuno commented on app/client/src/widgets/CurrencyInputWidget/component/utilities.ts
> +    .format(11111)
I don't understand the significance of the `11111`, please add a unit test as well as a function comment to help understand.

2022-01-12 00:07 UTC, riodeuno commented on app/client/src/widgets/CurrencyInputWidget/component/utilities.ts
> +      .replace(new RegExp("\\" + getLocaleThousandSeparator(), "g"), "")
Are these locale related functions, browser APIs? Can we add unit tests for these, by mocking them?

2022-01-12 00:07 UTC, riodeuno commented on app/client/src/widgets/CurrencyInputWidget/constants.ts
> +  CURRENCY: "CURRENCY",
We could use enums to make things easier.

2022-01-12 00:07 UTC, riodeuno commented on app/client/src/widgets/CurrencyInputWidget/widget/derived.test.ts
> +describe("Derived property - ", () => {
This is nice! Input widget should now be stable when dealing with values.

2022-01-12 00:07 UTC, riodeuno commented on app/client/src/widgets/CurrencyInputWidget/component/CurrencyCodeDropdown.tsx
> +        fill: ${Colors.GREY_10} !important;
Instead of using `!important` we can leverage specificity by adding `&&&.dropdown`. Can we try this and see if it works. Personally, I feel like `!important` is less flexible. :)

2022-01-12 00:09 UTC, riodeuno commented on app/client/src/icons/WidgetIcons.tsx
> +  INPUT_WIDGET_V2: (props: IconProps) => (
These are not required anymore. We have the icons in the widget configs. We should in fact, remove this file.

2022-01-12 11:09 UTC, riodeuno requested changes
The main requested change would be to add jest tests for any functions we've added, including the validation functions, either in this PR or in a subsequent PR.
We should also add cypress tests, if they do not already exist, for the new types of widgets.

The rest would be ideally verified visually in the deploy preview.

2022-01-13 05:47 UTC, sbalaji1192 commented on app/client/src/widgets/PhoneInputWidget/widget/index.tsx
> +export function defaultValueValidation(
Yeah. I have a commit that covers unit and cypress for all three widgets. will Address rest of the callouts.

2022-01-13 05:51 UTC, sbalaji1192 commented on app/client/src/widgets/CurrencyInputWidget/component/utilities.ts
> +    .format(11111)
We're tiring to identify the thousand separators used by the browser based on the locale. `en-US` uses `,`. but `hr-HR` uses `.`. So here we're formatting a random 4digit code to find whether its `,` or `.`.

2022-01-13 05:53 UTC, sbalaji1192 commented on app/client/src/widgets/CurrencyInputWidget/component/utilities.ts
> +      .replace(new RegExp("\\" + getLocaleThousandSeparator(), "g"), "")
We are converting a locale formatted string to Number
10,00.01 --> 1000.01 (en-US)
10.00,01 --> 1000.01 (hr-HR)

2022-01-13 05:55 UTC, sbalaji1192 commented on app/client/src/widgets/CurrencyInputWidget/component/CurrencyCodeDropdown.tsx
> +        fill: ${Colors.GREY_10} !important;
I totally agree with you. I did not touch the existing widget CSS, since we're reskinning the widgets soon.
I will try to remove this !important.

2022-01-13 09:41 UTC, sbalaji1192 commented on app/client/src/icons/WidgetIcons.tsx
> +  INPUT_WIDGET_V2: (props: IconProps) => (
This file is being used on the entity explorer.

2022-01-13 10:45 UTC, sbalaji1192 commented on app/client/src/widgets/CurrencyInputWidget/widget/derived.js
> +        /*
Good catch!!

2022-01-13 17:02 UTC, sbalaji1192 commented
/ok-to-test sha=25458b4

2022-01-13 17:18 UTC, sbalaji1192 commented
/ok-to-test sha=67a4905

2022-01-13 18:53 UTC, Aishwarya-U-R commented
/ok-to-test sha=67a4905

2022-01-14 17:36 UTC, sbalaji1192 commented
/ok-to-test sha=7931b32

2022-01-15 02:23 UTC, sbalaji1192 commented
/ok-to-test sha=7931b32

2022-01-17 04:48 UTC, sbalaji1192 commented
/ok-to-test sha=ece82ef

2022-01-17 05:32 UTC, sbalaji1192 commented
/ok-to-test sha=ece82ef

2022-01-17 09:20 UTC, riodeuno approved these changes

2022-01-18 07:52 UTC, merged

2022-01-18 07:53 UTC, somangshu commented
force Merged this with an unrelated failing test, requested by @sbalaji1192,

We have a QA and Reviewer sign off here