Feat: 5701 dynamic value fetch for forms
appsmithorg/appsmith pull request #10324
Opened 2022-01-11 17:49 UTC by ayushpahwa

## Description

Fixes #5701
Fixes #3951

## Type of change

- New feature (non-breaking change which adds functionality)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-01-11 17:52 UTC, ayushpahwa commented
/ok-to-test sha=87aeb04

2022-01-11 18:53 UTC, ayushpahwa commented
/ok-to-test sha=6907f58

2022-01-12 10:19 UTC, ApekshaBhosale requested changes

2022-01-12 10:19 UTC, ApekshaBhosale commented on app/client/src/pages/Editor/QueryEditor/EditorJSONtoForm.tsx
> +      modifiedSection = { ...modifiedSection, disabled: true };
why are you copying again and again?

2022-01-12 10:19 UTC, ApekshaBhosale commented on app/client/src/workers/formEval.ts
> +        ...conditionals,
don't need to use separator you can just add to the object

2022-01-12 19:41 UTC, ayushpahwa commented on app/client/src/pages/Editor/QueryEditor/EditorJSONtoForm.tsx
> +      modifiedSection = { ...modifiedSection, disabled: true };
Updated

2022-01-12 19:41 UTC, ayushpahwa commented on app/client/src/workers/formEval.ts
> +        ...conditionals,
Updated

2022-01-12 19:41 UTC, ayushpahwa commented
/ok-to-test sha=c5e6131

2022-01-13 08:07 UTC, ApekshaBhosale approved these changes

2022-01-13 08:07 UTC, merged