fix: currentItem showing error in debugger for list widgets
appsmithorg/appsmith pull request #10338
Opened 2022-01-12 08:42 UTC by ohansFavour

This PR introduces the concept of private widgets. To prevent wasted evaluations, these widgets do not get evaluated.
For example, for widget `Button1` in a List widget `List1`, `List1.template.Button1.text` gets evaluated, so there is no need to evaluate `Button1.text`. 

## Description

Fixes #8677

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manual

- Jest

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-01-12 09:31 UTC, ohansFavour commented
/ok-to-test sha=df47ea2

2022-01-13 05:17 UTC, Rishabh-Rathod commented on app/client/src/utils/DSLMigrations.ts
> +        "children.0.children.0.children.0.children",
Please add a comment for understanding why `children.0.children.0.children.0.children` is accessed.

2022-01-13 07:19 UTC, ohansFavour commented on app/client/src/utils/DSLMigrations.ts
> +        "children.0.children.0.children.0.children",
> Please add a comment for understanding why `children.0.children.0.children.0.children` is accessed.

Done

2022-01-13 07:21 UTC, ohansFavour commented
/ok-to-test sha=4256da5

2022-01-13 08:07 UTC, Rishabh-Rathod approved these changes
Looks good. 
Few nitpicks.

2022-01-13 08:07 UTC, Rishabh-Rathod commented on app/client/src/workers/DataTreeEvaluator.ts
> +  privateWidgets: Record<string, true> = {};
Can we create a type for privateWidget and add a comment there on what it means?
```js
/** 
these widgets do not get evaluated
*/
type PrivateWidgets = Record<string, true>;```

2022-01-13 08:14 UTC, Rishabh-Rathod reviewed
Also, can we add a test for privateWidgets specifically?  
1. `addPrivateWidgetsToAllListWidgets`
2. `isPrivateEntityPath`

2022-01-14 20:10 UTC, ohansFavour commented
> Also, can we add a test for privateWidgets specifically?
> 
> 1. `addPrivateWidgetsToAllListWidgets`
> 2. `isPrivateEntityPath`

Done

2022-01-18 12:59 UTC, ohansFavour commented
/ok-to-test sha=0d10484

2022-01-19 06:52 UTC, ohansFavour commented
/ok-to-test sha=0d10484

2022-01-19 08:11 UTC, ohansFavour commented
/ok-to-test sha=660d179

2022-01-19 14:13 UTC, Rishabh-Rathod requested changes
Need to re-review, not sure why the older review wasn't considered stale after the commit.

2022-01-19 16:42 UTC, ohansFavour commented
/ok-to-test sha=ed36a5c

2022-01-19 18:17 UTC, ohansFavour commented
/ok-to-test sha=1a499b2

2022-01-19 21:28 UTC, Rishabh-Rathod approved these changes
Looks good to me

2022-01-20 10:59 UTC, merged