fix: Select V2
appsmithorg/appsmith pull request #10359
Opened 2022-01-12 14:45 UTC by Tooluloope

## Description

Select and MultiSelect Version 2
Fixes Server Side issues

Fixes #7259

## Type of change

> Please delete options that are not relevant.

- Bugfix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-01-14 02:23 UTC, Tooluloope commented
/ok-to-test sha=ce074fb

2022-01-14 09:25 UTC, Tooluloope commented
/ok-to-test sha=629dffe

2022-01-14 18:21 UTC, Tooluloope commented
/ok-to-test sha=45a305a

2022-01-15 19:22 UTC, Tooluloope commented
/ok-to-test sha=985aa06

2022-01-15 20:43 UTC, Tooluloope commented
/ok-to-test sha=eeffb2a

2022-01-18 08:37 UTC, Tooluloope commented
/ok-to-test sha=6e7bd71

2022-01-18 21:23 UTC, Tooluloope commented
/ok-to-test sha=73ef69a

2022-01-18 23:09 UTC, Tooluloope commented
/ok-to-test sha=d4c92da

2022-01-20 17:14 UTC, sbalaji1192 requested changes

2022-01-24 08:11 UTC, Tooluloope commented on app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx
> +class MultiSelectWidget extends BaseWidget<
For now no.
I'm going to continue that in this issue https://github.com/appsmithorg/appsmith/issues/10575

2022-01-24 08:15 UTC, Tooluloope commented
/ok-to-test sha=35ebed2

2022-01-24 12:26 UTC, sbalaji1192 approved these changes

2022-01-24 12:26 UTC, sbalaji1192 commented on app/client/src/utils/autocomplete/EntityDefinitions.ts
> +      "Select is used to capture user input/s from a specified list of permitted inputs. A Select can capture a single choice as well as multiple choices",
Select widget can only capture single option, right?

2022-01-24 18:16 UTC, Tooluloope commented
/ok-to-test sha=7cd6f88

2022-01-27 07:47 UTC, vivekverma2312 commented
@Tooluloope After setting default option the search functionality stops working for select widget.
https://www.loom.com/share/7360a162ea7a438290e8dbb71e893aa5

2022-01-27 12:46 UTC, vivekverma2312 commented
@Tooluloope Tracking all the issues here.
1. Observed scroll issue on select widget
https://www.loom.com/share/598d283bdf4c4b93bdf7d250f571834f

2. Two options are showing as highlighted. After we close the drop-down options and open still it's displayed
https://www.loom.com/share/d68fdc23f61f42debb7b64975a7fdeba

3. Not able to see the drop-down options after we filter and navigate to query page and come back. After we clear the filter result also it do not populate. 
https://www.loom.com/share/24508625ada74cf291d7d82f37c68251

4. After setting default the search functionality stops working https://www.loom.com/share/7360a162ea7a438290e8dbb71e893aa5

2022-01-27 21:52 UTC, Tooluloope commented
@vivekverma2312 Fixed all

2022-01-28 07:00 UTC, vivekverma2312 commented
@Tooluloope 
1. Issue2 still exist for multi-select drop-down
2. Issue 3 is still reproducible (Now I do not have option to clear the filter)
3. Drop-down size of select and multi-select is not same.
<img width="436" alt="Screenshot 2022-01-28 at 12 26 44 PM" src="https://user-images.githubusercontent.com/83569920/151501974-7dd81f23-8407-492c-8775-d62ee39f1b04.png">
<img width="445" alt="Screenshot 2022-01-28 at 12 26 38 PM" src="https://user-images.githubusercontent.com/83569920/151501985-3376bac5-4661-45a9-8b86-bae723cbf09f.png">

2022-01-28 07:52 UTC, Tooluloope commented
Hi @vivekverma2312 
Concerning issue issue2, Unlike Select that has a single Option , MultiSelect has multiple options, Also the Library doesn't expose API to resume focus of the dropdown from the previously Select option. And I think it has a better UX like this compared to resuming from the Top
cc: @dilippitchika 

Issue 3 is now fixed.

Lastly, I've made the dropdown accommodate Equal number of items (8 options)

2022-01-28 07:55 UTC, Tooluloope commented
/ok-to-test sha=1ac55e7

2022-01-31 06:58 UTC, vivekverma2312 commented
@Tooluloope Observed that widget icon is not coming on Entity Explorer. Rest of the issues are tested and working fine
<img width="266" alt="Screenshot 2022-01-31 at 12 26 13 PM" src="https://user-images.githubusercontent.com/83569920/151751221-914fb6b3-71d8-4a51-b969-5e767d3027b6.png">
.

2022-01-31 07:33 UTC, Tooluloope commented
@vivekverma2312 Could you check again.
Just fixed this

2022-01-31 08:08 UTC, vivekverma2312 commented
Thanks @Tooluloope Tested and working fine now.

2022-01-31 08:11 UTC, Tooluloope commented
/ok-to-test sha=a0acf78

2022-02-02 06:37 UTC, Tooluloope commented
/ok-to-test sha=3c628f3

2022-02-02 07:53 UTC, Tooluloope commented
/ok-to-test sha=04a7045

2022-02-02 09:54 UTC, Tooluloope commented
/ok-to-test sha=b8392ec

2022-02-02 14:15 UTC, merged

2022-06-11 08:19 UTC, Rishabh-Rathod commented on app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx
> +      filterText: "",
Hey @Tooluloope, 

Could you help me understand why do we have  `filterText: "",` here. 
if `filterText` doesn't have a default property then according to my knowledge. It is fine to not add it in `getDefaultPropertiesMap`.

2022-06-14 21:49 UTC, Tooluloope commented on app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx
> +      filterText: "",
Yes, @Rishabh-Rathod its okay to remove it from the Map