fix: table column name migration update
appsmithorg/appsmith pull request #10383
Opened 2022-01-13 08:52 UTC by techbhavin

## Description

> remove label from table migration 

Fixes #6671

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-01-13 08:53 UTC, techbhavin commented
/ok-to-test sha=2c92d2e

2022-01-17 04:33 UTC, marks0351 requested changes

2022-01-17 04:33 UTC, marks0351 commented on app/client/yarn.lock
> +cypress-wait-until@^1.7.2:
are these yarn changes relevant?

2022-01-17 04:33 UTC, marks0351 commented
@techbhavin do we have test cases written for this migration?

2022-01-17 06:49 UTC, techbhavin commented
@marks0351  no we don’t have a test cases for this migration

2022-01-17 06:54 UTC, marks0351 commented
> @marks0351 no we don’t have a test cases for this migration

can u pls add test cases.

2022-01-17 07:27 UTC, sbalaji1192 requested changes

2022-01-17 07:27 UTC, sbalaji1192 commented on app/client/src/utils/migrations/TableWidget.ts
>              id: columnId,
Don't we need to change the label as well for the columns other than custom columns?

2022-01-17 07:27 UTC, sbalaji1192 commented on app/client/src/utils/DSLMigrations.ts
> +    currentDSL.version = 49;
We need to add a comment on DSL migration version 48, that the skipped migration is added as version 50. for future reference.

2022-01-18 09:55 UTC, techbhavin commented on app/client/src/utils/migrations/TableWidget.ts
>              id: columnId,
here we remove label properties  from migration, so will not change for any type of columns 

@sbalaji1192

2022-01-18 10:11 UTC, techbhavin commented
/ok-to-test sha=a92f8e6

2022-01-18 10:24 UTC, marks0351 reviewed
@techbhavin what will happen to these column bindings that might be used in other widgets.
Table1.selectedRow.1 will it be migrated to Table1.selectedRow._1 as well?
cc: @sbalaji1192

2022-01-18 10:31 UTC, marks0351 commented
@techbhavin also another case that i observed is, when data has a number column, then it creates a _ prefixed column name, but it is not restricted i can still change it to number. is this expected?

2022-01-18 15:14 UTC, techbhavin commented
> @techbhavin what will happen to these column bindings that might be used in other widgets. Table1.selectedRow.1 will it be migrated to Table1.selectedRow._1 as well? cc: @sbalaji1192

Before fixing this issue  `Table1.selectedRow.1` format was not accessible due to bad syntax. if still there is a way to bind this syntax. we have to handle it. 

cc: @marks0351

2022-01-18 15:22 UTC, techbhavin commented
> 



> @techbhavin also another case that I observed is when data have a number column, then it creates a _ prefixed column name, but it is not restricted I can still change it to number. is this expected?

@marks0351  here we are adding _prefixed in a column id property while generating a table column and the user doesn’t have control to modify it.  but users can change their label Property so I think we can’t restrict users to change column label

2022-01-20 05:54 UTC, marks0351 approved these changes
I am approving the changes but still looks a bit inconsistent experience coz we allow users to set a numeric label but the user has to use an _ if he wants to bind it in another widget.
cc: @techbhavin @sbalaji1192 @somangshu

2022-01-20 11:23 UTC, YogeshJayaseelan commented
@techbhavin Tested this PR and please find the status below,

Auto suggestion and the numeric bindings are working fine when the table data is binded with the google sheet api with numeric columns.

Issue 1 - Channing the column name manually to numeric and on binding with inout widget auto suggestion are not displayed for numeric columns

https://loom.com/share/5fa28ec46e6e445883a88a2fa4fd9615

2022-01-20 12:11 UTC, techbhavin commented
/ok-to-test sha=442e7f9

2022-01-20 13:49 UTC, sbalaji1192 approved these changes

2022-01-21 05:40 UTC, techbhavin commented
/ok-to-test sha=d3aa97f

2022-01-21 07:21 UTC, YogeshJayaseelan commented
@techbhavin Tested this PR and working as expected

2022-01-21 10:55 UTC, techbhavin commented
/ok-to-test sha=bb3dd77

2022-01-24 03:48 UTC, techbhavin commented
/ok-to-test sha=bb3dd77

2022-01-24 10:37 UTC, techbhavin commented
/ok-to-test sha=40b93bc

2022-01-25 04:50 UTC, techbhavin commented
/ok-to-test sha=e7e0401

2022-01-25 05:59 UTC, techbhavin commented
/ok-to-test sha=38615dd

2022-01-25 07:37 UTC, techbhavin commented
/ok-to-test sha=19487b3

2022-01-25 09:07 UTC, sbalaji1192 approved these changes

2022-01-25 09:07 UTC, sbalaji1192 commented on app/client/src/utils/migrations/TableWidget.test.ts
> +            "customColumn1",
Could we add one more custom column with a custom label and check the label is not lost during migration?

2022-01-25 09:27 UTC, techbhavin commented
/ok-to-test sha=b9f6617

2022-01-25 10:16 UTC, techbhavin commented
/ok-to-test sha=b9f6617

2022-01-25 13:54 UTC, merged