feat: Add keyboard navigation to multiselect dropdown
appsmithorg/appsmith pull request #10397
Opened 2022-01-13 14:19 UTC by aswathkk

## Description

Use `Tab` to focus the dropdown
`Enter` or `Space` to open dropdown
`Arrow Up` and `Arrow Down` keys to focus dropdown menu items
`Space` or `Enter` to select items
`Esc` to close dropdown menu

Fixes #10373 

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Manually tested and Jest tests added

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-01-14 07:24 UTC, SatishGandham commented on app/client/src/components/ads/MultiselectDropdown.tsx
> +      case "ArrowDown":
I think these values are browser specific, please check and cover all possible cases
https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key

2022-01-14 07:27 UTC, SatishGandham requested changes

2022-01-14 07:27 UTC, SatishGandham commented on app/client/src/components/ads/MultiselectDropdown.tsx
>    const optionClickHandler = (option: string) => {
Do we need useCallback here and at L235?

2022-01-14 07:40 UTC, aswathkk commented on app/client/src/components/ads/MultiselectDropdown.tsx
> +      case "ArrowDown":
Should we support browsers released before 2016?

2022-01-16 04:31 UTC, aswathkk commented
/ok-to-test sha=92f8ebb

2022-01-18 05:01 UTC, SatishGandham approved these changes

2022-01-18 06:25 UTC, vivekverma2312 commented
@aswathkk If we select any option using Enter/Space then we can not deselect it. If we deselect it then we can not select.
https://www.loom.com/share/3966f6f5fbbb4a9997395fd115decf5f

2022-01-21 06:12 UTC, vivekverma2312 commented
@aswathkk Now the focus of mouse click and Enter/Space is different. After I select any option using mouse the focus do not change.
https://www.loom.com/share/655fea8231e041b0a3319daae74b37ab

2022-01-25 06:47 UTC, vivekverma2312 commented
@aswathkk All issues are fixed and working fine now.

2022-01-25 09:37 UTC, aswathkk commented
/ok-to-test sha=11267b3

2022-01-25 11:00 UTC, merged