Feature: Refactor k8s installation to use fat container
appsmithorg/appsmith pull request #10467
Opened 2022-01-18 18:24 UTC by geekup-legodevops

## Description
- Remove unnecessary k8s templates (templates being used for multiple containers)
- Create new deployment template that use the fat container
- Refactor the k8s installation script to fetch the new template for fat container deployment on k8s
## Type of change
- New feature (non-breaking change which adds functionality)
## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-02-07 10:48 UTC, sharat87 requested changes

2022-02-07 10:48 UTC, sharat87 commented on deploy/k8s/scripts/appsmith-configmap.yaml.sh
> +  APPSMITH_SMART_LOOK_ID: ""
These are internal variables, not be configurable by the user.

```suggestion
```

2022-02-07 10:48 UTC, sharat87 commented on deploy/k8s/scripts/appsmith-configmap.yaml.sh
> +  APPSMITH_ALGOLIA_SEARCH_INDEX_NAME: ""
These are internal variables, not be configurable by the user.

```suggestion
```

2022-02-07 10:48 UTC, sharat87 commented on deploy/k8s/scripts/appsmith-configmap.yaml.sh
> +  APPSMITH_REDIS_URL: redis://127.0.0.1:6379
Let's wrap these in double-quotes as well.

```suggestion
  APPSMITH_MONGODB_URI: "$mongo_uri"
  APPSMITH_REDIS_URL: "redis://127.0.0.1:6379"
```

2022-02-07 10:48 UTC, sharat87 commented on deploy/k8s/scripts/appsmith-ingress.yaml.sh
> +                  number: 80
If a custom domain is configured, then Appsmith would be listening on 443 as well right? Shouldn't we route to that as well?

2022-02-07 10:48 UTC, sharat87 commented on deploy/k8s/templates/appsmith-template.yaml
> +        image: legodevops/appsmith:helm-20220105
Looks like a dev image? Can you check once?

2022-02-09 04:42 UTC, geekup-legodevops commented on deploy/k8s/scripts/appsmith-ingress.yaml.sh
> +                  number: 80
Hi @sharat87 , when user access to Appsmith deployed on the K8S, all requests will be routed to Ingress on HTTP or HTTPS connection. Then, these requests will be routed to internal services by the Ingress which not require a secure protocol like HTTPS (internal communication in K8S cluster). Therefore, we will only configure the ingress to route request to port 80 which is the default port of service (container)

2022-02-09 09:12 UTC, sharat87 commented on deploy/k8s/scripts/appsmith-ingress.yaml.sh
> +                  number: 80
So in that case if we configure the custom domain in `APPSMITH_CUSTOM_DOMAIN`, will Appsmith not attempt to provision its own certificate and start listening on port 443 if it successfully got a certificate? In that case port 80 will just be redirecting to the https server on port 80 no?

2022-02-14 04:57 UTC, geekup-legodevops commented on deploy/k8s/scripts/appsmith-ingress.yaml.sh
> +                  number: 80
Yes @sharat87 The context for the K8S is different from the Docker container. While user connects directly to the port 80 or 443 of the container when we start it with Docker, K8S exists with many other components and more like a whole system rather than a single running container. Therefore, in K8S, a request will need to go through another layer (ingress) instead of reaching the container port itself

2022-02-14 05:57 UTC, sharat87 commented on deploy/k8s/scripts/appsmith-ingress.yaml.sh
> +                  number: 80
I think we are talking about different things. Let me rephrase my question. After deploying Appsmith using this install script, if I go set the `APPSMITH_CUSTOM_DOMAIN` variable to `something.appsmith.com`, what will happen? Won't the entrypoint script attempt to provision an SSL certificate because this env variable is set?

2022-02-27 16:41 UTC, closed without merging