fix: 8878 Google Sheet Data filter and Float issue
appsmithorg/appsmith pull request #10465
Opened 2022-01-18 15:36 UTC by leotom2000

## Google Sheet Data filter and Float data processing issue

> Comma delimited Number with or without decimal places will work fine
> Larger data introduced down the row grid will work fine

Fixes #8878 #7794 #9667

## Type of change
- Bug fix (non-breaking change which fixes an issue) 
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?

> Manually tested
> Existing Testcases were checked to work fine

- Test A
- Test B

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-01-28 11:45 UTC, nidhi-nair commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/DataTypeStringUtils.java
> +            if (source != null && source.equals(GOOGLE_SHEET)) {
Instead of an if-else here can we improve the design to use a separate implementation on the basis of plugin? I say this because we should not be adding conditions for each plugin type in the utility function

2022-01-28 11:45 UTC, nidhi-nair requested changes
Needs a change in the implementation logic.

2022-02-02 08:31 UTC, leotom2000 commented on app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/services/GoogleSheetFilterDataService.java
> +     */
Method re-implemented here with changes specific to Google Sheet 
Original location: com.appsmith.external.helpers.DataTypeStringUtils

2022-02-02 08:35 UTC, leotom2000 commented on app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/services/GoogleSheetFilterDataService.java
> +     */
Method re-implemented here with changes specific to Google Sheet
Line 471 to 479 is the modified code, other lines are same

Original location: com.appsmith.external.services.ce.FilterDataServiceCE

2022-02-02 08:38 UTC, leotom2000 commented on app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/services/GoogleSheetFilterDataService.java
> +
No changes to the below method taken from com.appsmith.external.services.ce.FilterDataServiceCE

2022-02-02 08:39 UTC, leotom2000 commented on app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/services/GoogleSheetFilterDataService.java
> +
No changes to the below method taken from com.appsmith.external.services.ce.FilterDataServiceCE

2022-02-02 08:40 UTC, leotom2000 commented on app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/services/GoogleSheetFilterDataService.java
> +
No changes to the below method taken from com.appsmith.external.services.ce.FilterDataServiceCE

2022-02-02 08:40 UTC, leotom2000 commented on app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/services/GoogleSheetFilterDataService.java
> +
No changes to the below method taken from com.appsmith.external.services.ce.FilterDataServiceCE

2022-02-02 08:40 UTC, leotom2000 commented on app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/services/GoogleSheetFilterDataService.java
> +
No changes to the below method taken from com.appsmith.external.services.ce.FilterDataServiceCE

2022-02-02 08:40 UTC, leotom2000 commented on app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/services/GoogleSheetFilterDataService.java
> +
No changes to the below method taken from com.appsmith.external.services.ce.FilterDataServiceCE

2022-02-02 08:41 UTC, leotom2000 commented on app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/services/GoogleSheetFilterDataService.java
> +
No changes to the below method taken from com.appsmith.external.services.ce.FilterDataServiceCE

2022-02-02 08:48 UTC, leotom2000 commented on app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/GetValuesMethod.java
>  import com.external.domains.RowObject;
created and imported new method from Google-Sheet-Plugin package itself instead of making conditional GoogleSheet specific changes in the common Service.

2022-02-02 08:53 UTC, leotom2000 commented on app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/services/GoogleSheetFilterDataService.java
> +
Below are some private declarations re-declared from com.appsmith.external.services.ce.FilterDataServiceCE
public variables were reused from com.appsmith.external.services.ce.FilterDataServiceCE

2022-02-02 09:32 UTC, leotom2000 commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/DataTypeStringUtils.java
> +            if (source != null && source.equals(GOOGLE_SHEET)) {
Seems that is right, 
(1) Introduced two new  files within google-sheet-plugin module to handle this.
(2) Modified one existing file within google-sheet-plugin module
Total files for review is 3

Changes to the appsmith.external helpers and Services files were reverted.

2022-02-14 03:45 UTC, leotom2000 commented
Ready for review, some issues in test cases - resolved now

2022-02-15 05:29 UTC, nidhi-nair commented
@leotom2000 This seems to be the PR with the old implementation where the entire service as duplicated. Could you please verify and update the PR?

2022-02-15 05:29 UTC, nidhi-nair requested changes
Doesn't look like its updated

2022-02-16 11:09 UTC, leotom2000 commented
This issue is resolved by another PR 
https://github.com/appsmithorg/appsmith/pull/11207
So closing this PR without any merges

2022-02-16 11:09 UTC, closed without merging