feat: Add logic to sync the repo if the path is not updated in env file
appsmithorg/appsmith pull request #10478
Opened 2022-01-19 11:03 UTC by AnaghHegde

## Description

> 
1. At present, we are cloning the git repo the local file system and if this repo is deleted by the user(mostly on self-hosted) accidentally we don't have any mechanism to sync the repo again.  
2. Another issue is where if the user has not set the env variable `APPSMITH_GIT_ROOT` while configuring - on the container restart all the git related files are lost. 

This change set will address this issue by cloning the repo when the same is deleted from the local file system. This check is dynamic and user does not notice any difference from the UX point of view. 

Fixes #10469 

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Locally

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-01-19 11:04 UTC, AnaghHegde commented
/ok-to-test sha=c77a2bf

2022-01-20 06:09 UTC, AnaghHegde commented
/ok-to-test sha=dd111a9

2022-01-20 17:05 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java
> +                                List<String> branchList = gitBranchDTOList.stream().map(GitBranchDTO::getBranchName).collect(Collectors.toList());
Should we filter local branch, at this point I suppose only `default branch` will be present in local after the clone is successful. This way we can prevent 1 DB call 🙂

2022-01-20 17:08 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java
> +                                        .then(Mono.just(application));
Instead of sending a application can we send the `updatedBranchList`, this way we don't have to query again for the `branchList` in the upstream method.

2022-01-20 17:10 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java
> +                                                Mono<List<GitBranchDTO>> branchListMono = gitExecutor.listBranches(
If we get the updated branchList from `handleRepoNotFoundException` we can altogether avoid this call.

2022-01-20 17:24 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java
> +                                                    return createBranch(application.getId(), gitBranchDTO, gitApplicationMetadata.getDefaultBranchName());
Correct me if I'm wrong here but the branchName will have the prefix as `origin/` which is not allowed in current implementation of `createBranch` method. 

Also `createBranch` creates a branch from some `sourceBranch` but in this case, we need to create a branch from the local file system

2022-01-20 17:25 UTC, abhvsn requested changes
Added some comments please take a look, we might need to tackle some cases here

2022-01-20 17:36 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java
> +                                List<String> branchList = gitBranchDTOList.stream().map(GitBranchDTO::getBranchName).collect(Collectors.toList());
Good point :)

2022-01-20 17:48 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java
> +                                                    return createBranch(application.getId(), gitBranchDTO, gitApplicationMetadata.getDefaultBranchName());
I was thinking of removing the createBranch flow, because 
1. All the data in the db will be present. So it's just the git repo and anyway we are handling this case in `checkoutBranch` flow. 
2. And createBranch flow does not add any value here.

2022-01-21 05:49 UTC, AnaghHegde commented
/ok-to-test sha=5195f98

2022-01-22 13:20 UTC, AnaghHegde commented
/ok-to-test sha=4893a21

2022-01-24 05:06 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java
> +                                        .map(gitBranchDTO -> gitBranchDTO.getBranchName().replace("origin/", ""))
With this approach we may end up in a situation where we have some branches in local but not present in DB. Consider a situation: 
1. We have `master, F1` present in local along with there remote counterparts (both the branches will be present in local repo and DB)
2. We create another branch in remote through other Appsmith instance `F2`
3. Now we try to synch our first instance 
4. We will end up in having `master, F1 and F2` in local repo but only `master and F1` will be present in DB

2022-01-24 05:06 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java
> +                                branchList.remove(gitApplicationMetadata.getBranchName());
Any particular reason why we are removing the `defaultBranch`?

2022-01-24 09:27 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java
> +                                branchList.remove(gitApplicationMetadata.getBranchName());
Since the defaultBranch is already checked out in local, we are removing this from the list

2022-01-24 09:30 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java
> +                                        .map(gitBranchDTO -> gitBranchDTO.getBranchName().replace("origin/", ""))
@abhvsn We will not be ending up in this situation because before checking out a local branch we are first checking in the DB(Line No 1960-69), so the branch will be checked out only if it exists in DB.

2022-01-24 18:49 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java
> +                                                .onErrorResume(throwable -> Mono.empty()))
To avoid onErrorStates we can consider `findAllApplicationsByDefaultApplicationId` to find all the applications and then checking out in local if the branch is present in `branchList`

2022-01-24 18:50 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java
> +                                        .map(gitBranchDTO -> gitBranchDTO.getBranchName().replace("origin/", ""))
My bad you are correct!

2022-01-24 18:50 UTC, abhvsn approved these changes

2022-01-25 08:29 UTC, AnaghHegde commented
/ok-to-test sha=4893a21

2022-01-25 12:56 UTC, AnaghHegde commented
/ok-to-test sha=ea1ff49

2022-01-26 06:38 UTC, AnaghHegde commented
/ok-to-test sha=40a60a1

2022-01-26 07:25 UTC, merged