feat: Controls for labels in widgets to align the widgets in forms and other places
appsmithorg/appsmith pull request #10600
Opened 2022-01-24 15:22 UTC by wmdev0808

## Description
- Today the users have to manually align labels for the input fields they are working on. With the default settings we provide it’s hard for a user to keep aligning them manually. We wish to improve this experience by providing the user will controls for editing the label’s position, alignment and width.
- Enhanced widgets: Input, Date picker, Select/Multi select, Tree select/Multi tree select, Rich text editor, Checkbox group, Switch group, and Radio group. 

Fixes #7064 

## Type of change

- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?

- Test A
- Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-01-24 19:12 UTC, ohansFavour commented
/ok-to-test sha=ae33bed

2022-01-25 23:14 UTC, wmdev0808 commented
/ok-to-test sha=983dcb4

2022-01-26 07:00 UTC, wmdev0808 commented
/ok-to-test sha=5f20f8b

2022-01-26 09:00 UTC, wmdev0808 commented
/ok-to-test sha=19743f9

2022-01-26 10:25 UTC, wmdev0808 commented
/ok-to-test sha=1dab92f

2022-01-26 19:09 UTC, wmdev0808 commented
/ok-to-test sha=9e394db

2022-01-27 10:35 UTC, Tooluloope commented
/ok-to-test sha=31b05bf

2022-01-27 10:54 UTC, wmdev0808 commented
/ok-to-test sha=241d098

2022-01-28 07:08 UTC, shwetha-ramesh commented
**Generic Issues**
1.	What would be the general sequence of fields in property pane, since there is no regular pattern and every widget differs? 
 ![image](https://user-images.githubusercontent.com/92293815/151501995-5b03def0-eb73-428a-bc2f-69681d0c099f.png)
![image](https://user-images.githubusercontent.com/92293815/151502027-38fb2871-4a2c-4448-ac0e-df1bc460fa40.png)

2.     The field ```Position``` height and width does not match with other fields in the property pane.
![image](https://user-images.githubusercontent.com/92293815/151502075-21f8331c-76cc-4b1f-a539-8dd23734a674.png)

 3.	Without setting ```Width``` Alignment does not make any changes. 
https://loom.com/share/eb7a53de03d1466da2aa8cf510bfe256

4.	```Position``` and ```Alignment``` varies from Figma design
 ![image](https://user-images.githubusercontent.com/92293815/151502747-b2a64b53-5d37-4ae0-8a21-9d777d358695.png)

5.	When Position = Top is selected, Alignment  & Width options are not present.
![image](https://user-images.githubusercontent.com/92293815/151502844-ea96bcc5-cdb2-44d3-b9fa-5948592a49f6.png)


**### Input Widget**

1.	Bug #7064 – not fixed.
When a user adds 3 input widgets on a form, there is no definitive way to set the width for all the 3 widgets for it to match for the same length; it’s more of a trial and error approach to set the width. In the below video though the Width is set to 10 for all the 3 widgets it still looks misaligned. 

https://loom.com/share/e1ed7ae69b5a444abe5ad54366a27398

2.	Bug #9781 – fixed
3.	Bug #10119 – fixed
4.	Bug #7215 – 

5.	Text Size shows ‘No selection’ by default
 ![image](https://user-images.githubusercontent.com/92293815/151502928-64d7aaae-b33e-4030-a131-e24f0f32c084.png)

6.	When ```Data Type``` is set to Password and when the widget height is resized the icons remain in the original position where as the text moves as the widget is resized

https://loom.com/share/c5d5becd6645437b91aba096cfba4735
 
7.

2022-02-01 05:54 UTC, riodeuno commented
@wmdev0808 I am moving this PR to draft as there are QA comments from @shwetha-ramesh which need to be addressed.

2022-02-03 16:30 UTC, wmdev0808 commented
/ok-to-test sha=57b651d

2022-02-07 11:53 UTC, riodeuno requested changes
Some comments on the code.
@wmdev0808 We will want to add cypress tests for the new properties added to the widgets.

2022-02-07 11:53 UTC, riodeuno commented on app/client/src/components/propertyControls/LabelAlignmentOptionsControl.tsx
> +          onClick={() => this.handleAlign(Alignment.LEFT)}
Since we can't use `useCallback`, can we try this: 
`onClick = {this.handleAlign.bind(this, Alignment.LEFT)}`

2022-02-07 11:53 UTC, riodeuno commented on app/client/src/components/propertyControls/LabelAlignmentOptionsControl.tsx
> +          icon={<ControlIcons.RIGHT_ALIGN color="#979797" />}
Will we be getting anything for the colors in this control from the appsmith design system theme?
@jsartisan @albinAppsmith @sbalaji1192

2022-02-07 11:53 UTC, riodeuno commented on app/client/src/utils/DSLMigrations.ts
> +export const addPrivateWidgetsToAllListWidgets = (
@ohansFavour Did we revert this migration? If so, shall we remove this function?

2022-02-07 11:53 UTC, riodeuno commented on app/client/src/utils/DSLMigrationsUtils.test.ts
> +    const actualNextDsl = addPrivateWidgetsToAllListWidgets(currentDSL);
@ohansFavour Once again, did we revert this change? Is this update valid?

@wmdev0808 This is very important, we need confirmation from @ohansFavour before moving ahead with this change. This can potentially break applications.


I was also wondering if this change is necessary for your PR?

2022-02-07 11:53 UTC, riodeuno commented on app/client/src/utils/migrations/RadioGroupWidget.ts
> +      if (!("isInline" in child)) {
@wmdev0808 What do you think about `!child.hasOwnProperty("isInline")`? Is this more readable?

2022-02-07 11:53 UTC, riodeuno commented on app/client/src/utils/migrations/RadioGroupWidget.ts
> +      if (!("isInline" in child)) {
Also, does the radio group widget crash if it doesn't have these properties defined?

2022-02-07 11:53 UTC, riodeuno commented on app/client/src/utils/migrations/RadioGroupWidget.ts
> +export const migrateInlineAndAlignmentProperties = (currentDSL: DSLWidget) => {
Reviewer's understanding:
This function simple adds two new properties, `isInline` and `alignment` with default values  ( `false` and `Left` respectively) to all existing radio group widgets.

@wmdev0808 Let's add a simple jest test, which verifies that the DSL is correctly updated. Please make sure to use a fairly complex DSL as an input.

2022-02-07 11:53 UTC, riodeuno commented on app/client/src/widgets/BaseInputWidget/component/index.tsx
> +    props.labelPosition === LabelPositionTypes.Left
@wmdev0808 Let us avoid nested ternary operators. It will be difficult to maintain this code.
Let's use simple `if` and `else` clauses here.

2022-02-07 11:53 UTC, riodeuno commented on app/client/src/widgets/BaseInputWidget/component/index.tsx
> +        `.appsmith_widget_${this.props.widgetId} .bp3-button`,
@sbalaji1192  The selector used when adding event listeners was `.bp3-button-group`. Will this work and remove the appropriate listeners?

@sbalaji1192 Please review this particular file, as it seems to effect the Input Widget.

2022-02-07 11:53 UTC, riodeuno commented on app/client/src/widgets/BaseInputWidget/component/index.tsx
> +      const element: any = document.querySelector(
@sbalaji1192 We are using query selector here, is it possible to use React.ref? If we've made a decision to use query selectors, can we add an elaboration on the reason?

2022-02-07 11:54 UTC, riodeuno commented on app/client/src/utils/DSLMigrationsUtils.test.ts
> +    const actualNextDsl = addPrivateWidgetsToAllListWidgets(currentDSL);
I just noticed that we have a merge conflict with DSLMigrationsUtils. Maybe this is why we see reverted changes in this PR. Please verify.

2022-02-07 12:04 UTC, ohansFavour commented on app/client/src/utils/DSLMigrations.ts
> +export const addPrivateWidgetsToAllListWidgets = (
@riodeuno, we did not revert this Migration. This function is used in `DSLMigrations.test.ts` to unit test the privateWidgets Migration.

2022-02-07 12:06 UTC, ohansFavour commented on app/client/src/utils/DSLMigrationsUtils.test.ts
> +    const actualNextDsl = addPrivateWidgetsToAllListWidgets(currentDSL);
@wmdev0808 could you pull the latest release code?, these changes are no longer needed in your PR.

2022-02-07 12:13 UTC, wmdev0808 commented
/ok-to-test sha=0fdf620

2022-02-07 19:36 UTC, wmdev0808 commented on app/client/src/utils/migrations/RadioGroupWidget.ts
> +      if (!("isInline" in child)) {
> @wmdev0808 What do you think about `!child.hasOwnProperty("isInline")`? Is this more readable?

I agree with you, thank you

2022-02-07 19:39 UTC, wmdev0808 commented on app/client/src/utils/migrations/RadioGroupWidget.ts
> +      if (!("isInline" in child)) {
> Also, does the radio group widget crash if it doesn't have these properties defined?

No, it doesn't crash.
The purpose of this migration is just for consistency, for example, the similar widgets(checkbox group, switch group) have isInline property, of which default value is true

2022-02-10 05:59 UTC, riodeuno commented
@sbalaji1192 Could you review the input widget v2 files which have been updated?
@wmdev0808 Let's resolve the merge conflicts in this PR.

2022-02-10 07:31 UTC, wmdev0808 commented
/ok-to-test sha=36f832c

2022-02-10 18:00 UTC, sbalaji1192 reviewed
Reviewed the Input related files. added a few callouts. @wmdev0808 please check.

2022-02-10 21:45 UTC, wmdev0808 commented
/ok-to-test sha=2414d2d

2022-02-14 06:23 UTC, wmdev0808 commented
/ok-to-test sha=6e3ce7f

2022-02-17 07:49 UTC, riodeuno commented
@wmdev0808 The code looks good to me. If all the callouts by @sbalaji1192 have been resolved, we can move this back into the QA pipeline.

@shwetha-ramesh These changes, as you know, are related to all input type widgets and their property panes. As a result, this can effect our experience in a Form Widget as well.

2022-02-17 07:54 UTC, riodeuno commented on app/client/src/utils/DSLMigrationsUtils.test.ts
> +    const actualNextDsl = addPrivateWidgetsToAllListWidgets(currentDSL);
@wmdev0808 @ohansFavour Has this been updated. I can't tell. Could you let me know?

2022-02-17 08:07 UTC, albinAppsmith commented on app/client/src/components/propertyControls/LabelAlignmentOptionsControl.tsx
> +          icon={<ControlIcons.RIGHT_ALIGN color="#979797" />}
We should use colors from Colors.tsx for now

2022-02-17 08:20 UTC, ohansFavour commented on app/client/src/utils/DSLMigrationsUtils.test.ts
> +    const actualNextDsl = addPrivateWidgetsToAllListWidgets(currentDSL);
Yes, it has

2022-02-17 19:09 UTC, sbalaji1192 approved these changes
Input changes looks good to me. Just had one callout on the BaseInput widget.

2022-02-17 19:09 UTC, sbalaji1192 commented on app/client/src/widgets/BaseInputWidget/component/index.tsx
> +        `[class*=StyledNumericInput] .bp3-button`,
should be `.appsmith_widget_${this.props.widgetId} .bp3-button-group`

2022-02-18 14:17 UTC, wmdev0808 commented
/ok-to-test sha=7b5b67b

2022-02-18 18:00 UTC, wmdev0808 commented
/ok-to-test sha=e69052e

2022-02-18 19:25 UTC, wmdev0808 commented
/ok-to-test sha=e69052e

2022-02-23 08:59 UTC, wmdev0808 commented
/ok-to-test sha=beae871

2022-02-23 13:25 UTC, wmdev0808 commented
/ok-to-test sha=903c5e8

2022-02-23 23:26 UTC, Tooluloope commented
/ok-to-test sha=ced19a2

2022-03-01 19:37 UTC, wmdev0808 commented
/ok-to-test sha=5777a3c

2022-03-15 23:45 UTC, wmdev0808 commented
/ok-to-test sha=425370a

2022-03-23 08:41 UTC, Tooluloope commented
@dilippitchika @momcilo-appsmith 
Could you review the DP, it's really hard to know what is selected.
![Screenshot 2022-03-23 at 09 40 28](https://user-images.githubusercontent.com/31691737/159658258-2a2126a1-a5d2-4414-884c-efa55d611fdc.png)

2022-03-23 19:54 UTC, wmdev0808 commented
@Tooluloope ,
- Issue 1: The label is not centered.
When the input widget is not in compact mode, its underlying component is converted to textarea.
So from the UX favor, I've aligned the label to the top.
- Issue 2: Label alignment does not work
It's just because you are using long text(truncated by ellipsis), meaning labels with ellipsis cannot be aligned

2022-03-25 10:05 UTC, dilippitchika commented
Enhancements needed @wmdev0808 

1. Button group
    1. Selected color - Can you please use the same hover and selected colors from this field 
![Screenshot 2022-03-25 at 3 06 46 PM](https://user-images.githubusercontent.com/19730984/160096212-3c9e4b90-a55f-4d00-a8c6-405d7ef9fa9e.png)
    2. Font size - Can you please change the font size to be 14px
    3. Button size - Can you make the button normal height?
![Screenshot 2022-03-25 at 3 08 51 PM](https://user-images.githubusercontent.com/19730984/160096381-c0a24e2b-a7e5-471c-a0f4-f5af3cb3efce.png)

2. Width in columns in the label - Can you please add "(in columns)" in the width label
![Screenshot 2022-03-25 at 3 10 50 PM](https://user-images.githubusercontent.com/19730984/160096489-773d1345-1779-4f04-a1d3-0efaa2c86cf2.png)


3. Default values - Can you add the logic that for all new widgets being dragged, the default is set to these values
![Screenshot 2022-03-25 at 3 34 25 PM](https://user-images.githubusercontent.com/19730984/160099911-fb3e9385-8848-4a00-9820-859304d3f967.png)

2022-03-25 10:47 UTC, Tooluloope commented
@dilippitchika  @wmdev0808 

Is there a way to also align this vertically?

I feel it would be needed. 
![Screenshot 2022-03-25 at 11 45 59](https://user-images.githubusercontent.com/31691737/160106692-15c653b7-ba43-4d6f-b6aa-7efb4bcf70be.png)

2022-03-25 11:55 UTC, wmdev0808 commented
> @dilippitchika @wmdev0808
> 
> Is there a way to also align this vertically?
> 
> I feel it would be needed. It seems more needed than the left and right alignment ![Screenshot 2022-03-25 at 11 45 59](https://user-images.githubusercontent.com/31691737/160106692-15c653b7-ba43-4d6f-b6aa-7efb4bcf70be.png)

@Tooluloope ,
For that, you can use `Position`: `Top`

2022-03-25 12:01 UTC, Tooluloope commented
Using Top turns the Arrangement like this which isn't what I want.

![Screenshot 2022-03-25 at 13 00 48](https://user-images.githubusercontent.com/31691737/160117080-31d1292d-cc61-4221-81cf-1719c1eb0913.png)

2022-03-25 12:03 UTC, wmdev0808 commented
> Using Top turns the Arrangement like this which isn't what I want.
> 
> ![Screenshot 2022-03-25 at 13 00 48](https://user-images.githubusercontent.com/31691737/160117080-31d1292d-cc61-4221-81cf-1719c1eb0913.png)

Well, please add a screenshot for your desirable thing

2022-03-25 12:05 UTC, Tooluloope commented
This way,
It will be helpful if we could get it aligned this way

![Screenshot 2022-03-25 at 13 04 35](https://user-images.githubusercontent.com/31691737/160117638-2264469f-69aa-476e-abe3-7a12c4b845f5.png)

2022-03-25 12:19 UTC, wmdev0808 commented
> Enhancements needed @wmdev0808
> 
> 1. Button group
>    
>    1. Selected color - Can you please use the same hover and selected colors from this field
>       ![Screenshot 2022-03-25 at 3 06 46 PM](https://user-images.githubusercontent.com/19730984/160096212-3c9e4b90-a55f-4d00-a8c6-405d7ef9fa9e.png)
>    2. Font size - Can you please change the font size to be 14px
>    3. Button size - Can you make the button normal height?
>       ![Screenshot 2022-03-25 at 3 08 51 PM](https://user-images.githubusercontent.com/19730984/160096381-c0a24e2b-a7e5-471c-a0f4-f5af3cb3efce.png)
> 2. Width in columns in the label - Can you please add "(in columns)" in the width label
>    ![Screenshot 2022-03-25 at 3 10 50 PM](https://user-images.githubusercontent.com/19730984/160096489-773d1345-1779-4f04-a1d3-0efaa2c86cf2.png)
> 3. Default values - Can you add the logic that for all new widgets being dragged, the default is set to these values
>    ![Screenshot 2022-03-25 at 3 34 25 PM](https://user-images.githubusercontent.com/19730984/160099911-fb3e9385-8848-4a00-9820-859304d3f967.png)

@dilippitchika ,
Could you please add the resulting screenshot of `1. Button group`?
I can't fully understand 2, 3 there

2022-03-25 12:57 UTC, wmdev0808 commented
/ok-to-test sha=93eca09

2022-03-28 05:36 UTC, ashit-rath requested changes

2022-03-28 05:36 UTC, ashit-rath commented on app/client/src/widgets/MultiSelectWidget/component/index.tsx
> +      addLabelTooltipEventListeners(
A lot of code is being repeated everywhere, for example adding of listners/ useEffects/ defining mouseleave and enter functions across all components. This is getting repeated.
```

        <TextLabelWrapper
          alignment={labelAlignment}
          compactMode={compactMode}
          position={labelPosition}
          ref={labelRef}
          width={labelWidth}
        >
          <StyledTooltip
            content={labelText}
            hoverOpenDelay={200}
            isOpen={isLabelTooltipOpen}
            position={Position.TOP}
          >
```
If I were to create a new widget I would have to copy paste the entire logic from some other widget into this.
Every component should not be responsible for the rendering/handling of the label. There should just be 1 component as `Label` and it should deal with everything eg. the label wrapper, showing of tooltip, etc.

2022-03-28 05:36 UTC, ashit-rath commented on app/client/src/widgets/MultiSelectWidget/component/index.tsx
> +        `.appsmith_widget_${widgetId} .multiselect-label`,
Rather than passing class names and then using document.querySelector use refs.

2022-03-28 05:36 UTC, ashit-rath commented on app/client/src/widgets/MultiSelectWidget/component/index.tsx
> +      removeLabelTooltipEventListeners(
Is there any particular reason to use native event handlers rather than React's synthetic events like `onMouseEnter` etc?

2022-03-28 05:36 UTC, ashit-rath commented on app/client/src/widgets/SelectWidget/widget/index.tsx
> +        sectionName: "Label",
@riodeuno @wmdev0808 @sbalaji1192 
I think slowly we are moving towards the state where all of our widgets would have a bunch of common properties. Would this be the perfect opportunity to move these to a commonplace and not repeat it in every widget property config? 
If yes, then where should we keep this?

2022-03-28 06:35 UTC, Tooluloope requested changes

2022-03-28 06:35 UTC, Tooluloope commented on app/client/src/widgets/CheckboxGroupWidget/component/index.tsx
>  import { Classes } from "@blueprintjs/core";
`@blueprintjs/core"` is being repeated

2022-03-28 06:35 UTC, Tooluloope commented on app/client/src/widgets/CheckboxGroupWidget/component/index.tsx
> +export interface InputContainerProps {
Could we leave this as `CheckboxGroupContainerProps` and not Input

2022-03-28 06:35 UTC, Tooluloope commented on app/client/src/widgets/MultiSelectTreeWidget/component/index.tsx
> +              className={`multitree-select-label ${
It will be best to use Ref.

2022-03-28 06:35 UTC, Tooluloope commented on app/client/src/widgets/JSONFormWidget/fields/MultiSelectField.tsx
> +          labelText=""
@ashit-rath would you be able to confirm the JSONForm Changes?

2022-03-28 06:39 UTC, sbalaji1192 commented on app/client/src/widgets/BaseInputWidget/component/index.tsx
> +        isLoading ? Classes.SKELETON : Classes.TEXT_OVERFLOW_ELLIPSIS
@Tooluloope This got carried over from the Inputwidget v1. 
@dilippitchika can answer the question from a product perspective.

2022-03-28 07:56 UTC, riodeuno commented on app/client/src/widgets/SelectWidget/widget/index.tsx
> +        sectionName: "Label",
@ashit-rath Yes! This will really help out with re-usability. The onus on the implementation of these properties would still be on the widgets, so there is a concern there. 
We have something similar coming up for the dynamic height project. 

I would suggest we create a marker of some type, which when added to the property pane configuration, are automatically replaced with the full form property/properties. For example, `..., __section_Label__, ...`(just an example, not the exact type of marker) would be replaced by `..., { sectionName: "Label", ..other Label properties..}, ...`

2022-03-28 11:47 UTC, ashit-rath commented on app/client/src/widgets/BaseInputWidget/component/index.tsx
> +      const element: any = document.querySelector(
@sbalaji1192 Follow-up question: Out of curiosity; why do we need to handle step changes explicitly like this? I see that Currency Input uses the `onStep` but wouldn't the `onValueChange` method do the same thing if we remove the step-change implementation?

2022-03-28 11:53 UTC, ashit-rath commented on app/client/src/widgets/SelectWidget/widget/index.tsx
> +        sectionName: "Label",
@riodeuno That's a good idea. This seems like a bigger job and app theming is also introducing a bunch of common properties. Do you think we should take this up as a separate issue as more discussion is needed and it would just weigh down the timelines of this feature?
cc: @jsartisan @keyurparalkar

2022-03-28 11:54 UTC, ashit-rath commented on app/client/src/widgets/JSONFormWidget/fields/MultiSelectField.tsx
> +          labelText=""
@Tooluloope Yes, these changes are fine. JSONForm does not use component labels.

2022-03-28 13:50 UTC, wmdev0808 commented on app/client/src/components/propertyControls/LabelAlignmentOptionsControl.tsx
> +  onChange: (align: Alignment) => void;
Oh, it can be removed, thank you

2022-03-28 14:15 UTC, wmdev0808 commented on app/client/src/widgets/BaseInputWidget/component/index.tsx
> +      const element: any = document.querySelector(
> Could we avoid using `any`, lets be as strict as possible with our types

It was written by @sbalaji1192 , so we need to confirm with him

2022-03-28 14:18 UTC, wmdev0808 commented on app/client/src/widgets/CheckboxGroupWidget/component/index.tsx
> +export interface InputContainerProps {
Every widget consists of Label and Input section and CheckboxGroupContainerProps are whole container for the widget
So its name comes after that purpose

2022-03-28 18:33 UTC, sbalaji1192 commented on app/client/src/widgets/BaseInputWidget/component/index.tsx
> +      const element: any = document.querySelector(
@wmdev0808 Must be a mistake from my side. Agree with @Tooluloope

2022-03-29 05:48 UTC, ashit-rath commented on app/client/src/widgets/BaseInputWidget/component/index.tsx
> +      const element: any = document.querySelector(
@sbalaji1192 Got it, thanks for the detailed explanation.

2022-03-29 07:19 UTC, aswathkk requested changes
@wmdev0808 I see that you introduced new property controls.
Before adding new property controls, check whether you can re-use existing ones.
If you are introducing new ones, make sure to make them keyboard accessible.

2022-03-29 07:19 UTC, aswathkk commented on app/client/src/components/propertyControls/LabelPositionOptionsControl.tsx
> +  &.bp3-active {
I would suggest re-using ads/ButtonTabComponent instead. Because they are already made keyboard accessible.

2022-03-29 08:47 UTC, dilippitchika commented
@aswathkk this design was done as per the new designs for property pane. Something which you are yet to implement overall in the property pane. I don't know if we can add keyboard accessibility here directly unless we change the component itself. 
Please check the design here - 
https://www.figma.com/file/hlOcM5LasxcRqEwHPXe5lm/UI-%7C-Content-Property-Pane?node-id=2777%3A64824

@wmdev0808 please use the component @aswathkk suggested and update the DP once. Let's see how this looks like.

2022-03-29 12:33 UTC, dilippitchika commented
After discussion, @wmdev0808 please update the following
- Label position to use a "dropdown" component instead of the component you have used right now. Order of items in the dropdown is "Left, Top, Auto"
- Label alignment to use ads/ButtonTabComponent as suggested by Aswath. 


No changes to the label width component

2022-03-29 14:53 UTC, wmdev0808 commented
/ok-to-test sha=6477016

2022-03-30 05:14 UTC, ashit-rath commented on app/client/src/widgets/SwitchGroupWidget/index.ts
> +    rows: 4,
Why are we reducing the size of this widget?

2022-03-30 18:09 UTC, aswathkk reviewed
Changes to LabelAlignmentOptionsControl looks good to me.

2022-03-31 06:22 UTC, wmdev0808 commented on app/client/src/components/ads/LabelWithTooltip.tsx
> +      className="label-container"
It is currently used only for input widgets which need specific CSS rule, `flex-grow: 0;`

2022-03-31 06:23 UTC, wmdev0808 commented on app/client/src/components/ads/LabelWithTooltip.tsx
> +export interface StyledLabelProps {
Ok, thanks. I will

2022-03-31 06:32 UTC, wmdev0808 commented on app/client/src/components/propertyControls/LabelAlignmentOptionsControl.tsx
> +  constructor(props: LabelAlignmentOptionsControlProps) {
@ashit-rath ,
The comments from @riodeuno has already been fixed.
If you have any doubt, please specify here

2022-03-31 06:52 UTC, wmdev0808 commented on app/client/src/components/propertyControls/LabelPositionOptionsControl.tsx
> +class LabelPositionOptionsControl extends BaseControl<
According to @dilippitchika 's new requirements, we don't use this control.
There exists the underlying component for the purpose, `ButtonTabComponent`
For your requirements, we need to change this underlying component, but it is out of scope at the moment

2022-03-31 07:28 UTC, wmdev0808 commented on app/client/src/widgets/RadioGroupWidget/component/index.tsx
> +export const RadioGroupContainer = styled.div<RadioGroupContainerProps>`
I don't agree on your proposal.
> The reason:
- These container components are specific to the widget, not to label
- However, The common css part  can be extracted

2022-03-31 09:12 UTC, wmdev0808 commented on app/client/src/utils/migrations/RadioGroupWidget.ts
> +        child.alignment = Alignment.LEFT;
It is not for label alignment, it is another alignment for the radio group widget

2022-03-31 09:21 UTC, wmdev0808 commented on app/client/src/widgets/SwitchGroupWidget/index.ts
> +    rows: 4,
It was for showing the widget in compact mode for the first time

2022-03-31 09:26 UTC, wmdev0808 commented on app/client/src/widgets/SwitchGroupWidget/index.ts
> +    rows: 4,
I will just revert it at the moment

2022-03-31 09:48 UTC, wmdev0808 commented
/ok-to-test sha=9e67716

2022-03-31 10:43 UTC, aswathkk approved these changes

2022-03-31 11:32 UTC, wmdev0808 commented
/ok-to-test sha=071be15

2022-03-31 12:42 UTC, wmdev0808 commented
/ok-to-test sha=6eb44bf

2022-03-31 15:59 UTC, wmdev0808 commented
/ok-to-test sha=44769fe

2022-04-01 07:56 UTC, Tooluloope requested changes

2022-04-01 07:56 UTC, Tooluloope commented on app/client/src/components/propertyControls/LabelButton.tsx
> +`;
I don't think this is necessary anymore.

2022-04-01 07:56 UTC, Tooluloope commented on app/client/src/components/propertyControls/LabelPositionOptionsControl.tsx
> +export default LabelPositionOptionsControl;
I don't think this is necessary anymore.

2022-04-01 07:56 UTC, Tooluloope commented on app/client/src/components/propertyControls/NumericInputControl.tsx
> +  stepSize?: number;
Are these properties needed?

2022-04-01 07:56 UTC, Tooluloope commented on app/client/src/utils/DSLMigrations.ts
> +    currentDSL = migrateRadioGroupAlignmentProperty(currentDSL);
@wmdev0808 could you tell me what the migration / Alignment does for the RadioGroup Widget.

@somangshu @dilippitchika was there an agreed Migration

2022-04-01 08:07 UTC, wmdev0808 commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/Select_spec.js
> +});
Oh, it is unnecessary, I will remove it

2022-04-01 08:10 UTC, somangshu commented on app/client/src/utils/DSLMigrations.ts
> +    currentDSL = migrateRadioGroupAlignmentProperty(currentDSL);
not sure about this, I am not fully aware of the context, @dilippitchika might be able to answer

2022-04-01 08:16 UTC, wmdev0808 commented on app/client/src/components/propertyControls/NumericInputControl.tsx
> +  stepSize?: number;
Yes, These can be used if user configure them in property config.
Even though these props are not directly used in the current use for label width, it will be used for fine-grained control in the future.
So I think it is worth having these props, as well

2022-04-01 08:26 UTC, wmdev0808 commented on app/client/src/utils/DSLMigrations.ts
> +    currentDSL = migrateRadioGroupAlignmentProperty(currentDSL);
@Tooluloope ,
It is just for alignment of the indicator within container.
![alignment-left](https://user-images.githubusercontent.com/82799722/161225387-5372129b-1c36-441d-a579-556ac67ce65b.png)
![alignment-right](https://user-images.githubusercontent.com/82799722/161225405-db924a70-e666-4f5d-b1ed-54e883476770.png)

2022-04-01 08:36 UTC, somangshu commented on app/client/src/utils/DSLMigrations.ts
> +    currentDSL = migrateRadioGroupAlignmentProperty(currentDSL);
That looks straightforward, one more question, Is this JS convertible?

2022-04-01 08:37 UTC, wmdev0808 commented
/ok-to-test sha=9091f42

2022-04-01 08:43 UTC, wmdev0808 commented on app/client/src/utils/DSLMigrations.ts
> +    currentDSL = migrateRadioGroupAlignmentProperty(currentDSL);
No, it is a dropdown

2022-04-01 09:20 UTC, Tooluloope requested changes

2022-04-01 09:23 UTC, Tooluloope commented on app/client/src/utils/DSLMigrations.ts
> +    currentDSL = migrateRadioGroupAlignmentProperty(currentDSL);
@dilippitchika Could you check this out,
The migration is simple as @somangshu said, So most likely nothing would break.

Just a design review, the Radio buttons don't look aligned

2022-04-01 09:42 UTC, wmdev0808 commented
/ok-to-test sha=25f280e

2022-04-01 09:46 UTC, dilippitchika commented on app/client/src/utils/DSLMigrations.ts
> +    currentDSL = migrateRadioGroupAlignmentProperty(currentDSL);
I think there is a change in the radio buttons happening, previously the distance between 2 radio buttons was more compared to what it is now vertically. Upon resize the distance doesn't change. @wmdev0808 what is happening here?

OLD
![Screenshot 2022-04-01 at 3 14 35 PM](https://user-images.githubusercontent.com/19730984/161239209-c17b8e64-fa85-4e3a-86ee-7492c49403ef.png)
NEW
![Screenshot 2022-04-01 at 3 14 27 PM](https://user-images.githubusercontent.com/19730984/161239231-ad564978-0607-41ed-b740-04d177a7bec1.png)

2022-04-01 09:55 UTC, wmdev0808 commented
/ok-to-test sha=2d0b3d9

2022-04-01 10:00 UTC, Tooluloope submitted a review, later dismissed
LGTM,

@appsmithorg/qa this would need design audit as well

2022-04-01 10:08 UTC, wmdev0808 commented on app/client/src/utils/DSLMigrations.ts
> +    currentDSL = migrateRadioGroupAlignmentProperty(currentDSL);
@dilippitchika ,
It is because `inline` prop is `true`.
So NEW is the result of being wrapped of inline version

2022-04-01 11:14 UTC, dilippitchika commented on app/client/src/utils/DSLMigrations.ts
> +    currentDSL = migrateRadioGroupAlignmentProperty(currentDSL);
<img width="404" alt="Screenshot 2022-04-01 at 4 42 36 PM" src="https://user-images.githubusercontent.com/19730984/161252780-5a0ef051-6cb6-4011-877b-eb2c33a5ce88.png">
@wmdev0808 the behavior is different for checkbox group and radio group then when inline is turned on. We should follow what checkbox group is doing for radio group as well. Please check the image above from the dp.

2022-04-02 00:05 UTC, wmdev0808 commented
/ok-to-test sha=44097f4

2022-04-03 19:20 UTC, wmdev0808 commented
/ok-to-test sha=470ce29

2022-04-04 02:43 UTC, ashit-rath commented on app/client/src/widgets/RadioGroupWidget/component/index.tsx
> +export const RadioGroupContainer = styled.div<RadioGroupContainerProps>`
If components have specific styles and every component needs to push around the label to get it to its perfect position then the components are just not written correctly and we need to refactor every one of them to get it right. Imagine a UI library like material UI or ant design, when using their component you can add labels/tooltip/error messages without any extra configuration; they just work out of the box so we don't have to think about it. That is how things should be, continuous layers of abstraction. That being said, I think this refactor would be a bigger task as we need to verify each component; so we'll take this up in widget reskinning.
cc: @jsartisan

2022-04-04 02:51 UTC, ashit-rath commented on app/client/src/widgets/SwitchGroupWidget/component/index.tsx
> +  useEffect(() => {
Using useEffect with setState would cause unnecessary re-renders. Use `useMemo` 

```jsx
const scrollable = useMemo(() => {
    return (
      containerElement &&
      containerElement.scrollHeight > containerElement.clientHeight
    )
  }
), [
    height,
    width,
    inline,
    JSON.stringify(options),
    labelText,
    labelPosition,
    labelWidth,
  ])
```

2022-04-04 02:51 UTC, ashit-rath commented on app/client/src/widgets/SwitchGroupWidget/component/index.tsx
> +        scrollable={scrollable}
What is the purpose of `scrollable`?

2022-04-04 12:42 UTC, wmdev0808 commented on app/client/src/components/ads/LabelWithTooltip.tsx
> +      className="label-container"
It's just my way of deal with such a case.
Do you have better solution?

2022-04-04 14:21 UTC, wmdev0808 commented on app/client/src/widgets/RichTextEditorWidget/component/index.tsx
> +      labelPosition={labelPosition}
Yes, I've extract the common styles as `labelLayoutStyles` css method

2022-04-04 14:22 UTC, wmdev0808 commented on app/client/src/widgets/RadioGroupWidget/component/index.tsx
> +        labelPosition={labelPosition}
The same answer as above

2022-04-04 14:38 UTC, wmdev0808 commented on app/client/src/widgets/SwitchGroupWidget/component/index.tsx
> +        scrollable={scrollable}
It is not required anymore

2022-04-04 15:35 UTC, wmdev0808 commented
/ok-to-test sha=ae4a5b8

2022-04-05 05:10 UTC, ashit-rath approved these changes

2022-04-05 05:10 UTC, ashit-rath commented on app/client/src/components/ads/LabelWithTooltip.tsx
> +      className="label-container"
I think the problem I had is that, when I look at the input widget and see the style as 
```css
& .label-container {
 ...
}
```
I would need to find where this class is and which element I am changing.

I think here we can take an approach from blueprintjs where they export classNames as constants
So we can export this className as a constant and use it in the input component.

```js
// LabelWithTooltip.tsx
export const LABEL_CONTAINER_CLASS = "label-container"

<LabelContainer
      alignment={alignment}
      className={LABEL_CONTAINER_CLASS}

// Input component
& ${LABEL_CONTAINER_CLASS} {
 ...
}
```

2022-04-05 05:24 UTC, ashit-rath commented on app/client/src/components/ads/LabelWithTooltip.tsx
> +            height={14}
Can we put this in a const like `TOOLTIP_ICON_SIZE` and keep it in this file as it only belongs to this.

2022-04-05 05:24 UTC, ashit-rath commented on app/client/src/components/constants.ts
> +export const LABEL_MAX_WIDTH_RATE = 70;
I don't this these constants `LABEL_MAX_WIDTH_RATE` `LABEL_DEFAULT_GAP`  `LABEL_TOOLTIP_OPEN_DELAY` belong here as they won't be used by any component other than the Label. So let's move these to the LabelWithTooltip component.

Whereas the `LabelPosition` belongs to this file as it would be pulled by almost all the components.

Great job on adding comments.

2022-04-05 05:24 UTC, ashit-rath commented on app/client/src/components/ads/LabelWithTooltip.tsx
> +            <HelpIcon className={helpTextClassName} />
Can we rename this as `cyHelpTextClassName`?

2022-04-05 05:30 UTC, dilippitchika commented
@wmdev0808 for the top alignment of labels did we change something, I can now see a scroll bar by default for anything I top align in the release.app.appsmith.com and open it in the DP, attached is the image for reference

Release
<img width="277" alt="Screenshot 2022-04-05 at 10 58 34 AM" src="https://user-images.githubusercontent.com/19730984/161685050-1422bbf3-157d-4938-b943-278d3f281bb8.png">

DP
<img width="266" alt="Screenshot 2022-04-05 at 10 58 44 AM" src="https://user-images.githubusercontent.com/19730984/161685072-2690ba9d-a6e5-462f-a5cb-a75431726d0a.png">

2022-04-05 07:34 UTC, wmdev0808 commented
> @wmdev0808 for the top alignment of labels did we change something, I can now see a scroll bar by default for anything I top align in the release.app.appsmith.com and open it in the DP, attached is the image for reference
> 
> Release <img alt="Screenshot 2022-04-05 at 10 58 34 AM" width="277" src="https://user-images.githubusercontent.com/19730984/161685050-1422bbf3-157d-4938-b943-278d3f281bb8.png">
> 
> DP <img alt="Screenshot 2022-04-05 at 10 58 44 AM" width="266" src="https://user-images.githubusercontent.com/19730984/161685072-2690ba9d-a6e5-462f-a5cb-a75431726d0a.png">

That is inevitable because we should keep consistency across affected widgets and the original ones are not normalized one

2022-04-05 07:57 UTC, wmdev0808 commented
/ok-to-test sha=f246f6a

2022-04-05 08:20 UTC, wmdev0808 commented
/ok-to-test sha=1886cf8

2022-04-05 18:03 UTC, wmdev0808 commented
/ok-to-test sha=5621113

2022-04-05 21:22 UTC, wmdev0808 commented
/ok-to-test sha=7fc2427

2022-04-06 05:45 UTC, ashit-rath commented
@wmdev0808 @dilippitchika If we are still under discussion for the scrolling issue, can we move this card to `Needs PRD/Design`?

2022-04-06 05:58 UTC, dilippitchika commented
@ashit-rath we will have to resolve this today. No point moving it there and back here again for this.

2022-04-06 19:52 UTC, wmdev0808 commented
/ok-to-test sha=afdbed5

2022-04-07 04:25 UTC, ashit-rath commented on app/client/src/components/ads/LabelWithTooltip.tsx
> +      ${!width && `width: 33%`};
Nice catch! Paul please take of this.

2022-04-07 04:25 UTC, ashit-rath commented on app/client/src/widgets/MultiSelectTreeWidget/component/index.styled.tsx
> +  ${({ labelPosition }) => labelPosition && "height: 32px"};
`32px` is repeated across all the widgets. Please put it in the constants

2022-04-07 04:25 UTC, ashit-rath commented on app/client/src/widgets/MultiSelectWidgetV2/component/index.styled.tsx
> +  ${({ labelPosition }) => labelPosition && "height: 32px"};
Here as well

2022-04-07 04:25 UTC, ashit-rath commented on app/client/src/widgets/SelectWidget/component/index.styled.tsx
> +          return "margin-bottom: 5px";
this margin bottom value can also be put in the constants

2022-04-07 06:47 UTC, Tooluloope commented on app/client/src/widgets/SelectWidget/component/index.styled.tsx
> +          return "margin-bottom: 5px";
https://github.com/appsmithorg/appsmith/blob/1d27c951de17a830320841fb8f59fcc50a01e68d/app/client/src/widgets/WidgetUtils.ts#L78

Do help correct the comment on the constant

2022-04-07 06:58 UTC, ashit-rath commented on app/client/src/widgets/SelectWidget/component/index.styled.tsx
> +          return "margin-bottom: 5px";
This should be used but I think we should move this to the `constants.ts` file rather than the WidgetUtils.

2022-04-07 12:00 UTC, wmdev0808 commented
/ok-to-test sha=c89700e

2022-04-07 12:34 UTC, ashit-rath approved these changes

2022-04-08 09:25 UTC, wmdev0808 commented
/ok-to-test sha=b5473b7

2022-04-08 13:10 UTC, wmdev0808 commented
/ok-to-test sha=3a0f765

2022-04-08 15:24 UTC, wmdev0808 commented
/ok-to-test sha=fb6769d

2022-04-08 18:29 UTC, wmdev0808 commented
/ok-to-test sha=ad77f9c

2022-04-12 05:44 UTC, ashit-rath submitted a review, later dismissed

2022-04-12 07:53 UTC, YogeshJayaseelan commented
@wmdev0808  Testing is in progress for the for and please find the status below 

**Status of Bugs that are linked to this PR:**

Issue 1 - #7064 - Testing in progress

Issue 2 - #9781 - **Issue still exists - Reopen** - https://loom.com/share/37068f042f5841858628d1d31718412e

Issue 3 - #7215 - **Fixed**

Issue #10119 - **Fixed**

Issue #9908 - **Fixed**

Issue #11844 - **Fixed**

Issue #12355 - **Verified in the issue #7064**

**New issues on Enhancement 7064**

1. When any of the widths of the widget is set to 0 it consumes the area of width which is equivalence to width 6 

https://loom.com/share/ed33ccf587614d888805f2367c86257e

2. By default the outer boundary breaks for the Switch group and Checkbox group widget 

https://www.loom.com/share/046b97c7615448be85ef08412cc826cb

3. When the label position is set to top the outer boundary shows UI discrepancies and in case if there are any widgets that are placed below overlaps 

https://www.loom.com/share/2a1dd7029a464454afe4b9dc4b8fdd9b

4. By default the label component is not separated for Switch group/ Checkbox Group and Radio group widget

https://www.loom.com/share/55f9eac969444f5e91b890853a5b50b0


**Note: We will update the status of bugs that are mentioned in the comments earlier on this PR...**

2022-04-12 13:02 UTC, YogeshJayaseelan commented
> * We need to fix item 2 by increasing the default width, we will not be fixing the rest
> * @YogeshJayaseelan did not understand new issue 4

@dilippitchika If you compare the label component will be shown separated for other widgets except 'Switch group,Radio group  and CheckboxGroup'

<img width="1680" alt="Screenshot 2022-04-12 at 6 26 05 PM" src="https://user-images.githubusercontent.com/35128442/162968422-aaf51c74-d687-406d-a415-3f3bd48bc26d.png">

2022-04-12 20:00 UTC, wmdev0808 commented
/ok-to-test sha=9257a4c

2022-04-13 09:09 UTC, YogeshJayaseelan commented
@wmdev0808 @dilippitchika Tested this PR and please find the status below,

Status of Bugs that are linked to this PR:

Issue 1 - https://github.com/appsmithorg/appsmith/issues/7064 - **Fixed**

Issue 2 - https://github.com/appsmithorg/appsmith/issues/9781 - **Will not be Fixed**

Issue 3 - https://github.com/appsmithorg/appsmith/issues/7215 - **Fixed**

Issue https://github.com/appsmithorg/appsmith/issues/10119 - **Fixed**

Issue https://github.com/appsmithorg/appsmith/issues/9908 - **Fixed**

Issue https://github.com/appsmithorg/appsmith/issues/11844 - **Fixed**

Issue https://github.com/appsmithorg/appsmith/issues/12355 - **Verified in the issue https://github.com/appsmithorg/appsmith/issues/7064**

**Status of New issues raised on 12/04/2022**

Issue 1 - When any of the widths of the widget is set to 0 it consumes the area of width which is equivalence to width 6 - **Will not be fixed**

Issue 2 - By default the outer boundary breaks for the Switch group and Checkbox group widget - **Fixed**

Issue 3 - When the label position is set to top the outer boundary shows UI discrepancies and in case if there are any widgets that are placed below overlaps - **Will not be Fixed**

Issue 4 - By default the label component is not separated for Switch group/ Checkbox Group and Radio group widget - **This is not an issue** 

**New issues Dated 13/04/2022:**

Issue 1 - The widget value fonts slightly differ from other fonts in the property pane - Slightly bigger and bold 

<img width="1680" alt="Screenshot 2022-04-13 at 2 27 41 PM" src="https://user-images.githubusercontent.com/35128442/163141035-34d74148-486b-4098-803d-20e8d7076507.png">

Question 1: what is the purpose of field Auto under position? will it show the complete label text(70%) and the widget to (30%)

2022-04-13 10:17 UTC, dilippitchika commented
Auto is for maintaining the release like experience, if you resize the widget the label will move to top/left @YogeshJayaseelan

2022-04-13 12:15 UTC, wmdev0808 commented
/ok-to-test sha=cd766eb

2022-04-14 05:57 UTC, YogeshJayaseelan commented
@wmdev0808 Tested this PR and it is working as expected. We can proceed further

2022-04-14 08:46 UTC, somangshu approved these changes
After the last approval, I found 2 small changes that look acceptable. In the essence of time, moving ahead here. @ashit-rath @Tooluloope if you see any concerns when you get back, Please let us know urgently, and we shall look into it

2022-04-14 08:47 UTC, merged

2022-04-15 05:55 UTC, dilippitchika commented
@YogeshJayaseelan @wmdev0808 this issue is still happening. How was this tested?
Issue 2 - By default the outer boundary breaks for the Switch group and Checkbox group widget - Fixed

Loom - https://www.loom.com/share/c030793964954a96ab72f2e8cbbfb721

2022-04-15 06:11 UTC, YogeshJayaseelan commented
> @YogeshJayaseelan @wmdev0808 this issue is still happening. How was this tested? Issue 2 - By default the outer boundary breaks for the Switch group and Checkbox group widget - Fixed
> 
> Loom - [![LOOM DEMO](https://camo.githubusercontent.com/7a8959c8ae51303659acf7c915b17ce79f52de4fc2adf9e02db37497c6bb9680/687474703a2f2f63646e2e6c6f6f6d2e636f6d2f73657373696f6e732f7468756d626e61696c732f63303330373933393634393534613936616237326632653863626266623732312d30303030312e676966)](https://www.loom.com/share/c030793964954a96ab72f2e8cbbfb721)

@dilippitchika @wmdev0808 I did not experience the above problem during the second iteration of testing. Below is the screenshot which highlights the default state of Switch and Checkbox Group 

<img width="1680" alt="Screenshot 2022-04-15 at 11 40 43 AM" src="https://user-images.githubusercontent.com/35128442/163528983-6ab62a8a-2dd3-4b8a-9310-dda9bfe9653b.png">

2022-04-15 06:16 UTC, wmdev0808 commented
@dilippitchika , I can also reproduce the issue

2022-04-15 06:33 UTC, YogeshJayaseelan commented
@dilippitchika @wmdev0808 I also verified in release and I'm not able to reproduce. Any specific steps to reproduce?

https://loom.com/share/d1e194ba8ea241aea1ad67eab1eeadc4

2022-04-15 06:35 UTC, dilippitchika commented
@YogeshJayaseelan i guess you are using a monitor, you need to check in a smaller screen. Either resize the canvas width to tablet or try using a smaller screen

2022-04-15 06:35 UTC, dilippitchika commented
@wmdev0808 the video i shared is from release. I am using a monitor with 1366x768 resolution.

2022-04-15 06:36 UTC, dilippitchika commented
Satyajit and Abhishek also saw this issue in release - Please check the conversation here https://theappsmith.slack.com/archives/C02TWLJ26PM/p1650003769229109?thread_ts=1649920090.459319&cid=C02TWLJ26PM

2022-05-03 12:22 UTC, Rishabh-Rathod commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/Inputv2_spec.js
> +    cy.addSuccessMessage("Submitted!!", ".t--property-control-onsubmit");
This leads to adding `"Submitted!!"` to the label instead of the message field of the action creator.
Though the test passed this was not expected as now the message field remains empty and onSubmit shows an error.

2022-05-03 12:28 UTC, Rishabh-Rathod commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/Inputv2_spec.js
> +    cy.addSuccessMessage("Submitted!!", ".t--property-control-onsubmit");
Also, I see this PR was huge and still wasn't reviewed by developers. ( looking at PR approvals )

Can I understand why we didn’t get this PR reviewed by multiple devs? 
( i don't mean that the PR code has issues, trying to understand the process here. )

cc: @somangshu