fix: Table Filter pane overflows when Table is at the top of the canvas
appsmithorg/appsmith pull request #10618
Opened 2022-01-25 10:28 UTC by yaldram

## Description
- When the Table is placed at the top of the Canvas the Filterplane overflows / gets out of the canvas. Please check the issue below.

Fixes # (issue)
- https://github.com/appsmithorg/appsmith/issues/7996

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Tested it Manually on the Canvas.
- Tested it Manually by deploying the app.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-01-26 05:08 UTC, marks0351 requested changes

2022-01-26 05:08 UTC, marks0351 commented on app/client/src/widgets/TableWidget/component/TableFilterPane.tsx
> +      const boundaryParent =
can u pls use the MAIN_CONTAINER_WIDGET_ID constant instead of using 0  to provide more context and readability.

2022-01-26 05:08 UTC, marks0351 commented on app/client/src/widgets/TableWidget/component/TableFilterPane.tsx
> +        document.querySelector('[type="CANVAS_WIDGET"]');
I am guessing that this will always return the main canvas coz the first element of type canvas_widget is the main container.

2022-01-26 05:08 UTC, marks0351 commented on app/client/src/widgets/TableWidget/component/TableFilterPane.tsx
> +          boundaryParent={boundaryParent || "viewport"}
Not a big comment: no need to send viewport coz i see that you have handled that path inside the popper.

2022-01-26 06:55 UTC, yaldram commented on app/client/src/widgets/TableWidget/component/TableFilterPane.tsx
> +        document.querySelector('[type="CANVAS_WIDGET"]');
Thanks, `canvas_widget` can be used as the container for both edit and deployed apps.

2022-01-26 06:57 UTC, yaldram commented on app/client/src/widgets/TableWidget/component/TableFilterPane.tsx
> +      const boundaryParent =
We don't need this anymore : - 
```javascript
const boundaryParent = document.querySelector('[type="CANVAS_WIDGET"]');
```
Do you want me to move `type="CANVAS_WIDGET"` to a constant ?

2022-01-26 07:00 UTC, yaldram commented on app/client/src/widgets/TableWidget/component/TableFilterPane.tsx
> +          boundaryParent={boundaryParent || "viewport"}
Actually `boundaries` element requires a type - `Element | PopperJS.Boundary`. Before our fix we were passing `viewport` as a value. Now `document.querySelector()` can also return undefined so we handled that case here `boundaryParent={boundaryParent || "viewport"`. If you are using Propper anywhere else you don't need to pass the `boundaryParent` prop we have given it a default value of "viewport" in the Popper.tsx file. Thanks

2022-01-26 07:28 UTC, marks0351 commented on app/client/src/widgets/TableWidget/component/TableFilterPane.tsx
> +      const boundaryParent =
this is fine

2022-01-26 08:18 UTC, marks0351 requested changes
Changes look good. can u pls add cypress test cases if possible.

2022-01-27 11:00 UTC, yaldram commented
I am new to cypress, I did follow this example for testing drag and drop scenarios - https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/testing-dom__drag-drop/cypress/integration. But I am clueless about how should I test the `Filterpane overflow`. I did add - 
```javascript
cy.get(publish.tableFilterPopup).then((element) => {
      Cypress.dom.isVisible(element);
 });
```
But with the above we are just making sure that the widget isVisible which is true even if it goes under the Pages Tab. I think you can add better test cases @marks0351. Thanks.

2022-01-28 06:04 UTC, marks0351 requested changes

2022-01-28 06:04 UTC, marks0351 commented on app/client/src/pages/Editor/utils.ts
> +    if (calculatedTop <= 70) {
this wont work when there is no page tab, try creating an app with just one page. we need to get this value in real time based on the popper's parent top offset wrt the window.

2022-01-28 07:39 UTC, yaldram commented on app/client/src/pages/Editor/utils.ts
> +    if (calculatedTop <= 70) {
Yes, It will push the popper a bit more. In align with your suggestion I got this working - 
```javascript
const top =document.querySelector('[type="CANVAS_WIDGET"]')?.getBoundingClientRect() .top || 70;

if (calculatedTop <= top) {
  calculatedTop = top;
}
```
Just like the Popper.tsx I will send the boundaryParent as a parameter to the `draggableElement` function in utils.tsx.

2022-01-28 09:34 UTC, marks0351 requested changes

2022-01-28 09:34 UTC, marks0351 commented on app/client/src/pages/Editor/utils.ts
> +    const canvasTopOffset =
can u get the parent as an input parameter.

2022-01-28 10:26 UTC, yaldram commented on app/client/src/pages/Editor/utils.ts
> +    const canvasTopOffset =
Yes, I have added another prop to the Popper component, I thought of using `boundaryParent`, but it is of type - `boundaryParent?: Element | PopperJS.Boundary;` and our parent is of type `Element | null`, therefore I had to add another prop name `parentElement`. Also I have made this prop as optional, so that if you popper is not draggable no need to pass this prop.

2022-02-04 05:16 UTC, marks0351 approved these changes

2022-02-04 10:46 UTC, marks0351 commented
/ok-to-test sha=608183f

2022-02-15 07:06 UTC, YogeshJayaseelan commented
@yaldram Tested this PR and it is working as expected

2022-02-16 08:04 UTC, yaldram commented
/ok-to-test sha=dbf4b73

2022-02-17 12:42 UTC, yaldram commented
/ok-to-test sha=1ba5131

2022-02-18 09:59 UTC, yaldram commented
/ok-to-test sha=7ae23cd

2022-02-18 12:26 UTC, merged