First version of the templates in mongo plugin commands (Aggregate, D…
appsmithorg/appsmith pull request #10626
Opened 2022-01-25 12:13 UTC by felixsuarez0727

## Description

First version of the templates in mongo plugin commands.

2022-01-31 02:36 UTC, sumitsum commented on app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/commands/Aggregate.java
> +        setValueSafelyInFormData(configMap, SMART_SUBSTITUTION, Boolean.FALSE);
Please set this value to `TRUE`.

2022-01-31 03:09 UTC, sumitsum requested changes

2022-01-31 03:09 UTC, sumitsum commented on app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/commands/Distinct.java
> +        templates.add(generateKeyTemplate(collectionName, key));
Can you please remove the two different templates and only provide one ? We can use both `key` and `query` in the same template i.e we don't need different templates for `key` and `query` fields.

2022-01-31 03:09 UTC, sumitsum commented on app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/commands/Distinct.java
> +        setValueSafelyInFormData(configMap, DISTINCT_QUERY, "{ \"_id\": ObjectId(\"id_of_document_to_distinct\") }");
Can you please add the `DISTINCT_KEY` key as well here ? We can assign it a value of `_id`.

2022-01-31 03:09 UTC, sumitsum commented on app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/commands/Distinct.java
> +    }
IMO, the `testStructure()` method defined in `MongoPluginTest.java` would also need to be updated. Also, please run all the JUnit test cases in `MongoPluginTest.java` and make sure that all the test cases pass.

2022-02-03 20:16 UTC, felixsuarez0727 commented on app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/commands/Distinct.java
> +    }
Hello, I got some doubts with the unit tests:
Some of the already developed tests for the mongo commands (aggregate, distinct and count) are incorrect, for example:
    @Test
    public void testAggregateCommand() {
        DatasourceConfiguration dsConfig = createDatasourceConfiguration();
        Mono<MongoClient> dsConnectionMono = pluginExecutor.datasourceCreate(dsConfig);

        ActionConfiguration actionConfiguration = new ActionConfiguration();

        Map<String, Object> configMap = new HashMap<>();
        setValueSafelyInFormData(configMap, SMART_SUBSTITUTION, Boolean.FALSE);
        setValueSafelyInFormData(configMap, COMMAND, "AGGREGATE");
        setValueSafelyInFormData(configMap, COLLECTION, "users");
        setValueSafelyInFormData(configMap, AGGREGATE_PIPELINE, "[ {$sort :{ _id  : 1 }}, { $project: { age : 1}}]");
        setValueSafelyInFormData(configMap, AGGREGATE_LIMIT, "2");

        actionConfiguration.setFormData(configMap);

        Mono<Object> executeMono = dsConnectionMono.flatMap(conn -> pluginExecutor.executeParameterized(conn, new ExecuteActionDTO(), dsConfig, actionConfiguration));
        StepVerifier.create(executeMono)
                .assertNext(obj -> {
                    ActionExecutionResult result = (ActionExecutionResult) obj;
                    assertNotNull(result);
                    assertTrue(result.getIsExecutionSuccess());
                    assertNotNull(result.getBody());
                    int numOfOutputResults = ((ArrayNode) result.getBody()).size();
                    assertEquals(numOfOutputResults, 2); // This would be 3 if `AGGREGATE_LIMIT` was not set to 2.
                })
                .verifyComplete();
    }
Where Aggregate command does not have a limit key. (According to mongo doc https://docs.mongodb.com/manual/reference/command/aggregate/#mongodb-dbcommand-dbcmd.aggregate)
This individual tests are necessary, knowing that there's a test that cover all the tests? (I'm talking about testStructure() that tests all these commands).

2022-02-09 08:49 UTC, sumitsum submitted a review, later dismissed

2022-02-09 08:49 UTC, sumitsum commented on app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/commands/Distinct.java
> +        setValueSafelyInFormData(configMap, DISTINCT_KEY, "\"_id\"");
IMO, we dont' need the escaped quotes with `_id` i.e the value should be `_id` instead of `\"_id\"`

2022-02-09 08:49 UTC, sumitsum commented on app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/commands/Distinct.java
> +        "  \"key\": \"_id\"," +
Same as above.

2022-02-09 15:50 UTC, sumitsum commented on app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/commands/Distinct.java
> +        "  \"key\": \"_id\"," +
Sorry, this is correct.

2022-02-09 15:54 UTC, sumitsum commented on app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/commands/Distinct.java
> +    }
Hi Felix, `formData` is just an internal representation for the data that the user provides via query editor form. When we construct the actual query that is sent to the db, we don't use the `limit` keyword in case of `aggregate` cmd but instead use the `batchSize` keyword.

2022-02-11 07:11 UTC, felixsuarez0727 commented
In this last commit (2bd7ddc) I had to pull changes from release branch to solve client build problems.

2022-02-15 11:38 UTC, nidhi-nair approved these changes

2022-02-15 16:32 UTC, felixsuarez0727 commented
This was completed and merged on <https://github.com/appsmithorg/appsmith/pull/11153>

2022-02-15 16:32 UTC, closed without merging