fix: Cyclic dependency error occurs when enabling JS in the checkbox group options field
appsmithorg/appsmith pull request #10696
Opened 2022-01-27 15:19 UTC by wmdev0808

## Description
It is observed that in the checkbox group widget by passing the below name and option value and clicking on JS throws cyclic dependency error

Name - Y Value - {{Y}} and
Name - N Value - {{N}}

- Convert options control type to plain INPUT_TEXT
- Make a selectedValues meta property to be a derived one
- Convert validation for defaultSelectedValues to be plain string array one
- Remove a validation function for defaultSelectedValues and its test spec file

Fixes #10332 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Test A
- Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/10332-cyclic-dependency-error 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 54.95 **(0.01)** | 36.4 **(0.01)** | 34.63 **(0.02)** | 55.36 **(0.01)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.71 **(-0.23)** | 40.83 **(-0.84)** | 36.21 **(0)** | 56.74 **(-0.25)**
 :green_circle: | app/client/src/widgets/CheckboxGroupWidget/widget/index.tsx | 61.67 **(10.32)** | 41.18 **(14.26)** | 53.33 **(15.23)** | 61.4 **(9.23)**</details>

2022-01-27 15:20 UTC, wmdev0808 commented
/ok-to-test sha=6e8032f

2022-01-28 06:18 UTC, somangshu commented
@rahulramesha can you review, I am not sure about the change here

2022-01-28 10:11 UTC, rahulramesha requested changes

2022-01-28 10:11 UTC, rahulramesha commented on app/client/src/widgets/CheckboxGroupWidget/widget/index.tsx
> +        selectedValues={compact(this.props.selectedValues)}
Is this `selectedValuesArray`?

2022-01-28 22:34 UTC, wmdev0808 commented on app/client/src/widgets/CheckboxGroupWidget/widget/index.tsx
> -                fn: defaultSelectedValuesValidation,
The reason for simplicity and consistency.
The current OPTION_INPUT control is somehow buggy for the group widgets, such as CheckboxGroup, SwitchGroup, etc.
And We should not use custom validation function as less as possible.
Switch group is the one which I reach agreement with @riodeuno. 
For further information, please refer to the conversation with @riodeuno at https://github.com/appsmithorg/appsmith/pull/7590

In addition, I commit a migration for defaultSelectedValues prop which will deal with your concern

2022-01-28 22:35 UTC, wmdev0808 commented on app/client/src/widgets/CheckboxGroupWidget/widget/index.tsx
> +                          unique: true,
I've revert the corresponding config for the above

2022-01-28 22:37 UTC, wmdev0808 commented on app/client/src/widgets/CheckboxGroupWidget/widget/index.tsx
> +        selectedValues={compact(this.props.selectedValues)}
No, it should be selectedValues derived property, which will finally determine values to be selected

2022-01-28 22:37 UTC, wmdev0808 commented
/ok-to-test sha=4f25087

2022-01-31 08:11 UTC, rahulramesha requested changes

2022-01-31 08:11 UTC, rahulramesha commented on app/client/src/widgets/CheckboxGroupWidget/widget/index.tsx
> -                fn: defaultSelectedValuesValidation,
@wmdev0808, I understand the change away from `OPTION_INPUT`. I also agree that if it accepts just an array, the `ValidationType` should just be an `ARRAY` for simplicity.
But Since, this already had a custom method that not only validated but also parsed the inputs, changing it now will break existing widgets. Migrating the DSL will not cover all scenarios, for example, a single string being returned from a Query or API, or a string from another widget like, `{{Button1.text}}`. 
I would suggest that we keep the `defaultSelectedValuesValidation` as is for this. Please let me know if there is any concern in doing so.

2022-02-03 10:12 UTC, riodeuno commented on app/client/src/widgets/CheckboxGroupWidget/widget/index.tsx
> -                fn: defaultSelectedValuesValidation,
@wmdev0808 We were able to safely do this for switch group widget, because, switch group widget was a new widget in development at the time.

Users have been using the CheckboxGroup widget so far.
They must have potentially added all types of values which the existing `defaultSelectedValuesValidation` validated correctly, might fail in case of the validation configuration based validation.

With that mentioned, if we're sure that the migrations are handled correctly, and cover all cases -- we can move ahead with this.

However, if we cannot be certain, and can imagine cases where user applications might break, or start providing incorrect `parsed` values, we should consider @rahulramesha 's suggestion.

2022-02-03 12:07 UTC, wmdev0808 commented on app/client/src/widgets/CheckboxGroupWidget/widget/index.tsx
> -                fn: defaultSelectedValuesValidation,
Okay, got it

2022-02-03 21:52 UTC, wmdev0808 commented
/ok-to-test sha=981e8cb

2022-02-07 07:26 UTC, rahulramesha approved these changes
LGTM

2022-02-08 06:30 UTC, YogeshJayaseelan commented
@wmdev0808 Tested this PR and the issue is not happening on DP. But there is a migration issue - on opening any of the older apps which has checkbox group widget and reframing the values within {{Green}} and changing the Key value to APPLE throws cyclic dependency error. Refer the video below,

https://www.loom.com/share/874971cc3ced4f69925b20606e43c6a3

2022-02-08 20:05 UTC, wmdev0808 commented
> @wmdev0808 Tested this PR and the issue is not happening on DP. But there is a migration issue - on opening any of the older apps which has checkbox group widget and reframing the values within {{Green}} and changing the Key value to APPLE throws cyclic dependency error. Refer the video below,
> 
> [![LOOM DEMO](https://camo.githubusercontent.com/d3ae7ea45a7a5aea79e73b2bc690925a4d588ce8dd3ab028d9192dd34f88f23b/687474703a2f2f63646e2e6c6f6f6d2e636f6d2f73657373696f6e732f7468756d626e61696c732f38373439373163633363656434663639393235623230363036653433633661332d30303030312e676966)](https://www.loom.com/share/874971cc3ced4f69925b20606e43c6a3)

Hi @YogeshJayaseelan , 
Through debugging the issue you mentioned, I don't think it is associated with this issue.
@rahulramesha , @riodeuno , @hetunandu , I need your guys' confirmation about this issue because I think this issue is associated with the implementation of data tree evaluation logic(DataTreeEvaluator.ts)

2022-02-14 08:40 UTC, riodeuno commented
@wmdev0808 @YogeshJayaseelan I'm triaging this, let me get back with an update on this thread.

2022-03-14 08:33 UTC, somangshu commented
@riodeuno any update here?

2022-03-16 11:25 UTC, riodeuno commented
@wmdev0808 On triaging it seems like there are two issues shown in @YogeshJayaseelan's loom screen share. 
1. SwitchGroupWidget crashes when [`selected`](https://github.com/appsmithorg/appsmith/blob/3486e7c0c8fd2ddc16c77b3d7a72ab8d63c32321/app/client/src/widgets/SwitchGroupWidget/component/index.tsx#L104) is `undefined`

2. The CheckboxGroupWidget should ideally show an `undefined` variable linting error and not a cyclic dependency error. I've shared this with the team members, let's see what the root cuase here is.

2022-03-16 11:31 UTC, riodeuno commented
Also, @wmdev0808 @somangshu, based on the above comment, it seems like the original issue is unrelated to the code changes here in this PR. Can we update the description in the PR and tag the correct issue, which relates to the changes in this PR?

2022-03-22 07:49 UTC, wmdev0808 commented
According to @riodeuno's suggestion, this PR will be closed and create a new issue at #12078

2022-03-22 07:49 UTC, closed without merging