feat: Add unconfigured datasource import export by file
appsmithorg/appsmith pull request #10699
Opened 2022-01-28 05:41 UTC by AnaghHegde

## Description

> Per new design of git-import we are showing the un configured datasources post import. It will be inconsistent if we not show the un configured datasources for file import and it is really helpful for the users as well. This change set adds un-configured datasources list to the existing import-export by file API. 

Fixes #

> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Locally 
- Unit tests

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-01-28 08:12 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
> -                    */
Can we please keep this comment as this might be needed in case of file migrations for files when we alter the fields? This basically acts as a reference

2022-01-28 08:15 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
> +                                })));
This is going to break our import flow can we please merge both client and server-side changes in a single PR?

2022-01-28 08:17 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
> +    private Mono<List<Datasource>> findNonConfiguredDatasourceByApplicationId(String applicationId,
If I'm not mistaken we have implemented a similar method for git-import why are we replicating the code here? Also can we move this method to `datasourceService` if possible

2022-01-28 08:22 UTC, abhvsn commented on app/server/appsmith-server/src/test/resources/test_assets/ImportExportServiceTest/valid-application-with-un-configured-datasource.json
> +  "decryptedFields": {
Can we please assign `decryptedFields:{}` as we need not want to share any details considering the TC that we are looking at

2022-01-28 08:24 UTC, abhvsn commented on app/server/appsmith-server/src/test/resources/test_assets/ImportExportServiceTest/valid-application-with-un-configured-datasource.json
> +  ],
I'm curious as both the datasources seems to have the `datasourceConfiguration` object but still end up in `unConfiguredDatasourceList` as per the testcase!

2022-01-28 08:27 UTC, abhvsn requested changes
Added minor changes, but I was thinking should we also remove the `decryptedFields` from the exported file altogether and have consistent behaviour with the git-sync where we don't save 'decryptedFields` and `datasourceConfiguration`.

2022-01-28 09:32 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
> +    private Mono<List<Datasource>> findNonConfiguredDatasourceByApplicationId(String applicationId,
No i can't move this `datasourceService` as it creates cyclic dependency. I will remove the code from gitService class

2022-01-28 10:09 UTC, AnaghHegde commented
@abhvsn Since this is a breaking change, as you said i will merge the changes to @haojin111 branch. Lets continue continue this from here - https://github.com/appsmithorg/appsmith/pull/10453

2022-01-28 11:22 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
> +    private Mono<List<Datasource>> findNonConfiguredDatasourceByApplicationId(String applicationId,
Cool that also works!

2022-01-28 11:39 UTC, abhvsn commented on app/server/appsmith-server/src/test/resources/test_assets/ImportExportServiceTest/valid-application-with-un-configured-datasource.json
> +  ],
`datasourceConfiguration` will be empty if we try to save the datasource imported without this object. But when you try to create one from UI this object will be sent from the client-side that's why you might be seeing some values there

2022-01-28 12:49 UTC, AnaghHegde commented on app/server/appsmith-server/src/test/resources/test_assets/ImportExportServiceTest/valid-application-with-un-configured-datasource.json
> +  ],
Yes, i never thought of that. I will switch it back to use `datasourceConfiguration` attribute.

2022-02-01 20:34 UTC, AnaghHegde commented
@abhvsn ready for review :)
PR is continued from here - https://github.com/appsmithorg/appsmith/pull/10453

2022-02-02 11:58 UTC, AnaghHegde commented
/ok-to-test sha=3623946

2022-02-17 16:42 UTC, closed without merging