fix(mysqlPlugin): MySQL allow empty password if user is not empty
appsmithorg/appsmith pull request #10711
Opened 2022-01-28 09:35 UTC by mojtab23

## Description

mysqlPlugin will ignore and validate the empty password if the user field is not empty.

Fixes #9221

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

-  With unit tests against the MySQL `root` user and also with another user.
-  Test file `MySqlWithEmptyPasswordTest` is added to `mysqlPlugin`
## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-01-31 03:28 UTC, sumitsum requested changes

2022-01-31 03:28 UTC, sumitsum commented on app/server/appsmith-plugins/mysqlPlugin/src/main/java/com/external/plugins/MySqlPlugin.java
> +import com.appsmith.external.models.*;
Hi Mojtaba, please replace the `*` import everywhere with specific imports since we don't want to import the libraries that we are not using.

2022-01-31 03:28 UTC, sumitsum commented on app/server/appsmith-plugins/mysqlPlugin/src/main/java/com/external/plugins/MySqlPlugin.java
> +                if (StringUtils.isEmpty(authentication.getPassword()) && StringUtils.isEmpty(authentication.getUsername())) {
Can we replace the `if else` by :
```
if (StringUtils.isEmpty(authentication.getPassword())) { 
    authentication.setPassword("");
}
```
Since we are already adding an error statement in case of missing `username` we only have to handle the case when the username is provided.

2022-01-31 03:28 UTC, sumitsum commented on app/server/appsmith-plugins/mysqlPlugin/src/test/java/com/external/plugins/MySqlWithEmptyPasswordTest.java
> +package com.external.plugins;
Can you please move the tests to `MySqlPluginTest.java` ?

2022-02-01 09:51 UTC, mojtab23 commented on app/server/appsmith-plugins/mysqlPlugin/src/test/java/com/external/plugins/MySqlWithEmptyPasswordTest.java
> +package com.external.plugins;
Sure, I did that.

2022-02-01 09:51 UTC, mojtab23 commented on app/server/appsmith-plugins/mysqlPlugin/src/main/java/com/external/plugins/MySqlPlugin.java
> +import com.appsmith.external.models.*;
I fixed the imports.

2022-02-02 07:12 UTC, sumitsum approved these changes

2022-02-02 07:12 UTC, sumitsum commented
/ok-to-test sha=d1ddebd

2022-02-02 11:51 UTC, sumitsum commented
/ok-to-test sha=d1ddebd

2022-02-02 15:09 UTC, merged