fix: added sentry exception for invalid DynamicBindingListPath
appsmithorg/appsmith pull request #10790
Opened 2022-02-01 11:13 UTC by keyurparalkar

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.

## Description

> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change.

Fixes #10712

> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-02-02 05:18 UTC, sbalaji1192 requested changes

2022-02-02 05:18 UTC, sbalaji1192 commented on app/client/src/utils/helpers.test.ts
> +  it("DSL should not alter", () => {
DSL should not be altered

2022-02-02 05:18 UTC, sbalaji1192 commented on app/client/src/utils/helpers.tsx
> +  const { bindingPaths } = getAllPathsFromPropertyConfig(
We don't need to check all the bindingPaths in a widget. We just to need to check the keys in the `dynamicBindingPathList`

2022-02-02 07:17 UTC, keyurparalkar commented on app/client/src/sagas/PageSagas.tsx
> +    isInvalidDynamicBindingPath(
Changed the name to `captureInvalidDynamicBindingPath`

2022-02-02 07:17 UTC, keyurparalkar commented on app/client/src/utils/helpers.test.ts
> +  it("DSL should not alter", () => {
Done

2022-02-02 07:18 UTC, keyurparalkar commented on app/client/src/utils/helpers.tsx
> +  const { bindingPaths } = getAllPathsFromPropertyConfig(
Changed the logic to traverse through `dynamicBindingPathList` instead of `bindingPaths`

2022-02-02 10:49 UTC, sbalaji1192 approved these changes

2022-02-02 11:23 UTC, riodeuno commented on app/client/src/sagas/PageSagas.tsx
> +    captureInvalidDynamicBindingPath(
Please check `migrateIncorrectDynamicBindingPathLists` on line 451. I believe it is doing the same thing there. Can we re-use it?

2022-02-02 11:44 UTC, keyurparalkar commented on app/client/src/sagas/PageSagas.tsx
> +    captureInvalidDynamicBindingPath(
@riodeuno We needed to execute a `captureInvalidDynamicBindingPath` before saving a page. And it seems the `migrateIncorrectDynamicBindingPathLists` might only get executed in the 2nd try. Capturing the error before from the client end might be beneficial.

@sbalaji1192 can you also provide your comments on this.

2022-02-02 11:46 UTC, riodeuno commented on app/client/src/sagas/PageSagas.tsx
> +    captureInvalidDynamicBindingPath(
I was only wondering if we can re-use the `migrateIncorrectDynamicBindingPathLists` function in our case. Is that possible?

2022-02-02 11:50 UTC, riodeuno commented on app/client/src/sagas/PageSagas.tsx
> +    captureInvalidDynamicBindingPath(
Whoops! Please ignore my comments, I completely missed the point of this PR. We're creating new sentry exceptions, not fixing the issues. My bad. 😓

2022-02-02 11:51 UTC, riodeuno approved these changes

2022-02-02 11:51 UTC, keyurparalkar commented on app/client/src/sagas/PageSagas.tsx
> +    captureInvalidDynamicBindingPath(
No problem @riodeuno

2022-02-02 11:52 UTC, keyurparalkar commented
/ok-to-test sha=a064d8c

2022-02-03 01:59 UTC, keyurparalkar commented
/ok-to-test sha=a064d8c

2022-02-03 05:52 UTC, merged