fix: Delete the pages post merge operation from application when they are removed from file system
appsmithorg/appsmith pull request #10810
Opened 2022-02-02 05:20 UTC by AnaghHegde

## Description

> When we try to delete the resource by using the git branching, we can see the resource if we create the new branch from the parent branch even after we merged the sub-branch where the resource was deleted.

Fixes #10773

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Locally
- JUnit Tests

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-02-02 05:28 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
> +                            .thenReturn(Mono.empty())
Why do we need this `thenReturn`?

2022-02-02 05:35 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
> +                                                   .flatMap(newPageService::archiveById)
We need to delete all the actions and JS object attached to this page. Can we use `deleteUnpublishedPage` instead of `archive` method

2022-02-02 05:36 UTC, abhvsn requested changes
Added minor comments for improvements

2022-02-02 05:39 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
> +                            .flatMap(unused -> {
Should we avoid executing this block for traditional import-export as this is valid only for git-sync as you commented below?
FYI `applicationId` will be null for traditional import-export.

2022-02-02 07:20 UTC, AnaghHegde commented
@abhvsn ready for review :)

2022-02-02 07:21 UTC, AnaghHegde commented
/ok-to-test sha=4f680b4

2022-02-02 09:50 UTC, AnaghHegde commented
/ok-to-test sha=ea20277

2022-02-02 10:45 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
> +                            .flatMap(unused -> {
When I meant `applicationId` will not be null for git-sync I was referring to the one passed in for the global method 
```
 public Mono<Application> importApplicationInOrganization(String organizationId,
                                                             ApplicationJson applicationJson,
                                                             String applicationId,
                                                             String branchName)
```

2022-02-02 10:54 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
> +                            .thenReturn(Mono.empty())
Same reason as it was used before adding this logic. We had `.then` & `.thenReturn` so that the next block executes post this Flux.

2022-02-02 11:06 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
> +                                if (!Optional.ofNullable(applicationId).isEmpty()) {
Hey also why are we not using the `StringUtils.isEmpty(applicationId)` for checking the availability of `applicationId` as it has a String type instead of more generic `Optional.ofNullable`

2022-02-02 11:56 UTC, AnaghHegde commented
/ok-to-test sha=9afc003

2022-02-03 08:15 UTC, abhvsn commented on app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ImportExportApplicationServiceTests.java
>                      assertThat(pageNames.contains("Page3"));
We are not checking any condition here this should be 
```
assertThat(pageNames).contains("Page3");
or
assertThat(pageNames.contains("Page3")).isTrue();
```

2022-02-03 10:48 UTC, AnaghHegde commented
/ok-to-test sha=ab4e2ab

2022-02-03 12:44 UTC, abhvsn approved these changes

2022-02-04 05:45 UTC, AnaghHegde commented
/ok-to-test sha=ab4e2ab

2022-02-04 06:37 UTC, merged