Dropdown option gets overlapped on the Modal #1000
appsmithorg/appsmith pull request #1083
Opened 2020-10-08 15:45 UTC by reachtokish

## Description
Dropdown option getting overlapped on the modal. As suggested in [this issue](https://github.com/appsmithorg/appsmith/issues/1000) I tries `z-index` but that was not working as the dropdown is portal by default and dropdown component getting rendered in very bottom of html. By making `portal: false` and bit css solves the issue.

Fixes #1000 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manual testing

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2020-10-08 16:19 UTC, jyash97 commented on app/client/src/components/designSystems/blueprint/DropdownComponent.tsx
> +    &.ifupwd {
Isn't this a JS generated class name?  
If yes this would likely change if there is a change in the styles as the hashing function most of the library uses relies on the styles.

2020-10-08 16:52 UTC, reachtokish commented on app/client/src/components/designSystems/blueprint/DropdownComponent.tsx
> +    &.ifupwd {
@jyash97 I don't think `ifupwd` is getting generated. Because all the time this `ifupwd` is same. It's not getting changed. And somewhere in css it's written like

```
.ifupwd div {
  height: 32px;
}
```

to overwrite the above css I have written my css. Let me know if you have any suggestions here.

2020-10-12 05:31 UTC, riodeuno requested changes

2020-10-12 05:31 UTC, riodeuno commented on app/client/src/components/designSystems/blueprint/DropdownComponent.tsx
> +    &.ifupwd {
@reachtokish The class `ifupwd` is being generated dynamically by `styled-components`, you may see the same class for a session, but this cannot be guaranteed.

I have two suggestions here:
1. Instead of using `.bp3-popover-wrapper` we can use `.${ClassNames.POPOVER_WRAPPER}` 
2. `styled-components` support nesting. So we can try to find the element which we need to style instead of using the class `ifupwd`. For example:
```
    .${Classes.POPOVER_WRAPPER} > div {
        height: auto;
    }
```
IF, there is only one `div` nested in the children.

2020-10-12 15:20 UTC, reachtokish commented on app/client/src/components/designSystems/blueprint/DropdownComponent.tsx
> +    &.ifupwd {
@riodeuno thanks for your suggestions. Let me try one of those.

2020-10-12 15:47 UTC, reachtokish commented on app/client/src/components/designSystems/blueprint/DropdownComponent.tsx
> +    &.ifupwd {
[This line](https://github.com/appsmithorg/appsmith/blob/release/app/client/src/components/designSystems/blueprint/DropdownComponent.tsx#L162) causing the issue. @riodeuno / @jyash97 could you guys pls tell me if I can replace that div with some specific selector? If I can replace then what should be the specific selector in that case?

2020-10-22 13:24 UTC, hetunandu commented
Hey @reachtokish ! Not seeing a lot of activity here since some time. Do you need any help to implement the changes requested? Do reach out if there is something we can do move this is faster

2020-10-22 13:35 UTC, reachtokish commented
Hi @hetunandu , yes I need help. I asked [here](https://github.com/appsmithorg/appsmith/pull/1083#discussion_r503383832) a query but I didn't receive any answer. Request you to kindly check the above thread. Thanks

2020-10-22 14:10 UTC, hetunandu commented on app/client/src/components/designSystems/blueprint/DropdownComponent.tsx
> +    &.ifupwd {
https://blueprintjs.com/docs/#select/multi-select
You can pass a className [here](https://github.com/appsmithorg/appsmith/blob/release/app/client/src/components/designSystems/blueprint/DropdownComponent.tsx#L280) to access that in the styledComponents

2020-10-23 13:42 UTC, reachtokish commented on app/client/src/components/designSystems/blueprint/DropdownComponent.tsx
> +    &.ifupwd {
Removed [this unnecessary styles](https://github.com/appsmithorg/appsmith/blob/release/app/client/src/components/designSystems/blueprint/DropdownComponent.tsx#L162) as it is creating lot of other issues.

2020-10-26 06:41 UTC, hetunandu commented on app/client/src/components/designSystems/blueprint/DropdownComponent.tsx
> +                usePortal: false,
We still need to use portal for dropdown widget or else it will not render the option over other widgets on the same level

2020-10-26 06:42 UTC, hetunandu commented
@riodeuno Please take a look at this

2020-11-03 07:06 UTC, mohanarpit commented
@reachtokish Can you please update your branch with the latest code from `release`? There were some breaking changes introduced in `release` which probably caused tests to fail on your branch.

2021-01-07 05:14 UTC, closed without merging

2021-01-07 05:15 UTC, hetunandu commented
Hey @reachtokish We did not see any activity here for a long time and the fix was not working out as well, hence closing this