fix: fix refresh token flow in REST API OAuth
appsmithorg/appsmith pull request #10875
Opened 2022-02-04 07:12 UTC by sumitsum

## Description
- This PR adds the following config to REST API datasource when OAuth2.0 authentication is selected:
  - config to add client credentials on either header or body during refresh token flow.
  - if scope needs to be sent on refresh token flow.
- The configurations above are required because various OAuth servers behave differently and prefer different configurations. 
- This PR also includes minor refactor to improve code debuggability (no change in code logic)

Fixes #10493 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manual

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-02-04 07:21 UTC, nidhi-nair commented
LGTM, would recommend that the client adds these into a separate "Advanced" section since these settings won't usually be helpful for providers that follow the spec.

2022-02-04 07:21 UTC, nidhi-nair approved these changes

2022-02-07 06:20 UTC, nidhi-nair commented on app/client/src/pages/Editor/DataSourceEditor/RestAPIDatasourceForm.tsx
> +        <Collapsible defaultIsOpen title="Advanced Settings">
Can we keep this settings closed by default? We should design for least friction for the 80% user base

2022-02-07 06:23 UTC, nidhi-nair commented on app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/connections/OAuth2ClientCredentials.java
> +                && (Boolean.TRUE.equals(oAuth2.getSendScopeWithRefreshToken()) || oAuth2.getSendScopeWithRefreshToken() == null)) {
I'm not sure if these settings make sense for client credentials, since we don't really use the refresh token grant type in this flow. In client credentials grant type, the original request is sent again to get new the new access token. @sumitsum

2022-02-07 07:47 UTC, sumitsum commented on app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/connections/OAuth2ClientCredentials.java
> +                && (Boolean.TRUE.equals(oAuth2.getSendScopeWithRefreshToken()) || oAuth2.getSendScopeWithRefreshToken() == null)) {
@nidhi-nair thanks for catching this :) . I totally didn't know about it.

2022-02-07 09:48 UTC, nidhi-nair commented on app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/connections/OAuth2ClientCredentials.java
> +                && (Boolean.TRUE.equals(oAuth2.getSendScopeWithRefreshToken()) || oAuth2.getSendScopeWithRefreshToken() == null)) {
We should also make the advanced settings appear only for Authorization code grant type on the UI. I believe it appears for all OAuth2 types right now.

2022-02-07 09:49 UTC, nidhi-nair requested changes
Needs a few UI changes

2022-02-08 14:00 UTC, sumitsum commented
/ok-to-test sha=b023cbe

2022-02-08 14:06 UTC, nidhi-nair approved these changes

2022-02-08 14:07 UTC, nidhi-nair approved these changes

2022-02-08 14:45 UTC, Irongade approved these changes

2022-02-08 14:47 UTC, sumitsum commented
/ok-to-test sha=b023cbe

2022-02-09 04:08 UTC, merged