feat: adding slug names in urls
appsmithorg/appsmith pull request #10957
Opened 2022-02-08 07:45 UTC by arunvjn

## Description
This PR aims to change the structure of the current URL with a more user friendly URL.
/applications/:appId/pages/:pageId -> /applicationSlugName/pageSlugName-pageId

Fixes # (issue)

## Type of change

> Please delete options that are not relevant.
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How Has This Been Tested?
- Manual

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-02-23 09:46 UTC, arunvjn commented
/ok-to-test sha=6af5f2c

2022-03-03 15:18 UTC, arunvjn commented
/ok-to-test sha=3981305

2022-03-03 16:57 UTC, arunvjn commented
/ok-to-test sha=51bcd14

2022-03-04 05:43 UTC, arunvjn commented
/ok-to-test sha=7faf1a5

2022-03-04 05:59 UTC, arunvjn commented
/ok-to-test sha=c0c28c3

2022-03-09 03:13 UTC, arunvjn commented
/ok-to-test sha=5bebd68

2022-03-09 03:23 UTC, arunvjn commented
/ok-to-test sha=d6244e4

2022-03-09 04:52 UTC, arunvjn commented
/ok-to-test sha=16703c8

2022-03-11 02:42 UTC, arunvjn commented
/ok-to-test sha=790c69b

2022-03-15 04:40 UTC, arunvjn commented
/ok-to-test sha=17d9cd6

2022-03-15 14:42 UTC, arunvjn commented
/ok-to-test sha=1e446b1

2022-03-16 02:31 UTC, arunvjn commented
/ok-to-test sha=dab6d4d

2022-03-16 03:38 UTC, arunvjn commented
/ok-to-test sha=b97a18e

2022-03-17 03:03 UTC, arunvjn commented
/ok-to-test sha=d05d52a

2022-03-17 17:55 UTC, arunvjn commented
/ok-to-test sha=cb21c51

2022-03-18 10:05 UTC, arunvjn commented
/ok-to-test sha=ecdb948

2022-03-18 12:40 UTC, arunvjn commented
/ok-to-test sha=5d93a1d

2022-03-18 12:48 UTC, arunvjn commented
/ok-to-test sha=75cf206

2022-03-18 14:32 UTC, akash-codemonk requested changes

2022-03-19 13:20 UTC, arunvjn commented
@mohanarpit Could you please review the backend changes on this PR ?

2022-03-19 13:21 UTC, arunvjn commented on app/client/src/pages/Editor/BottomBar/ManualUpgrades.tsx
> +      {applicationVersion < latestVersion && <RedDot />}
DP points to release, update works with the backend changes on this branch.

2022-03-21 03:39 UTC, arunvjn commented on app/client/src/pages/Editor/BottomBar/ManualUpgrades.tsx
> +      "All URLs in your applications will update to a new readable format that includes the application and page names.",
Done

2022-03-21 03:39 UTC, arunvjn commented on app/client/src/sagas/ApplicationSagas.tsx
> +            //Comeback
Done

2022-03-21 10:43 UTC, arunvjn commented
/ok-to-test sha=89068cf

2022-03-21 13:18 UTC, arunvjn commented
/ok-to-test sha=292d29b

2022-03-21 13:50 UTC, akash-codemonk submitted a review, later dismissed

2022-03-22 02:56 UTC, arunvjn commented
/ok-to-test sha=c0d5670

2022-03-22 03:36 UTC, arunvjn commented
/ok-to-test sha=1ba7001

2022-03-22 04:18 UTC, arunvjn commented
/ok-to-test sha=9c9e38d

2022-03-22 09:27 UTC, arunvjn commented
/ok-to-test sha=27f8a75

2022-03-22 12:57 UTC, arunvjn commented
/ok-to-test sha=570f314

2022-03-22 13:15 UTC, arunvjn commented
/ok-to-test sha=c429559

2022-03-23 03:13 UTC, arunvjn commented
/ok-to-test sha=4a956fc

2022-03-23 04:30 UTC, arunvjn commented
/ok-to-test sha=f071b6c

2022-03-23 07:20 UTC, arunvjn commented
/ok-to-test sha=aed03bc

2022-03-23 10:23 UTC, arunvjn commented
/ok-to-test sha=76bd1ce

2022-03-24 06:38 UTC, akash-codemonk submitted a review, later dismissed

2022-03-24 08:35 UTC, arunvjn commented
/ok-to-test sha=b2d3125

2022-03-24 14:21 UTC, arunvjn commented
/ok-to-test sha=18ddc18

2022-03-25 04:24 UTC, akash-codemonk submitted a review, later dismissed

2022-03-25 07:42 UTC, sharat87 approved these changes

2022-03-25 08:30 UTC, akash-codemonk approved these changes

2022-03-25 08:42 UTC, arunvjn commented
/ok-to-test sha=87a40fa

2022-03-25 10:43 UTC, merged