added new library and reduced function calls for global data
appsmithorg/appsmith pull request #11001
Opened 2022-02-08 13:03 UTC by ApekshaBhosale

## Description
Performance issue - App was taking a lot of time to create the first data Tree
solution - 
1. As part of Promises, we were creating global data to provide context for each evaluation which clones data each time. In this, we are limiting the number of times the data tree will be cloned by only adding platform functions for triggered paths. 
2. We were using cloneDeep from loadash which is not the faster one. Now we will be using rfdc https://www.npmjs.com/package/rfdc. 
  BenchMarking - 
  benchDeepCopy*100: 457.568ms
  benchLodashCloneDeep*100: 1230.773ms
  benchCloneDeep*100: 655.208ms
  benchFastCopy*100: 747.017ms
  benchRfdc*100: 281.018ms
  benchRfdcProto*100: 277.265ms
  benchRfdcCircles*100: 328.148ms
  benchRfdcCirclesProto*100: 323.004ms

Fixes #

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-02-09 14:01 UTC, hetunandu requested changes

2022-02-09 17:22 UTC, ApekshaBhosale commented on app/client/src/utils/deepCopy.js
> +function copyBuffer(cur) {
this is copied library hence no test cases. took from this package https://www.npmjs.com/package/rfdc
i didn't want to install package hence nothing @hetunandu

2022-02-10 05:21 UTC, hetunandu commented on app/client/src/utils/deepCopy.js
> +function copyBuffer(cur) {
It will still need some tests and comments. Why are we not installing the package instead?

2022-02-10 05:22 UTC, hetunandu requested changes

2022-02-10 05:22 UTC, hetunandu commented on app/client/src/workers/Actions.ts
> +  const clonedDT = rfdc()(dataTree);
We should have `rfdc()` called once only

2022-02-10 05:44 UTC, ApekshaBhosale commented on app/client/src/workers/Actions.ts
> +  const clonedDT = rfdc()(dataTree);
what do you mean? i didn't get it. if you are talking about syntax that's how it works @hetunandu

2022-02-10 06:03 UTC, SatishGandham commented on app/client/src/workers/Actions.ts
> +  const clonedDT = rfdc()(dataTree);
I think this is what he means.
```
const cloneDeep = rfdc()
const clonedDT = cloneDeep(dataTree)
```

2022-02-10 07:31 UTC, hetunandu approved these changes

2022-02-11 10:52 UTC, merged