fix: Select widget accept string and object
appsmithorg/appsmith pull request #11082
Opened 2022-02-10 13:28 UTC by Tooluloope

## Description

> Accept both string and object for defaultOption
Fixes #11074

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

- This change requires a documentation update

## How Has This Been Tested?

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-02-10 22:29 UTC, Tooluloope commented
/ok-to-test sha=107d6fb

2022-02-10 23:34 UTC, Tooluloope commented
/ok-to-test sha=167667f

2022-02-11 04:28 UTC, sbalaji1192 requested changes

2022-02-11 04:28 UTC, sbalaji1192 commented on app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx
> +  return {
This validation allows all object values.

2022-02-11 04:28 UTC, sbalaji1192 commented on app/client/src/widgets/SelectWidget/widget/index.tsx
> +  try {
need to check if its a string before JSON.parse

2022-02-12 11:03 UTC, Tooluloope commented
/ok-to-test sha=1de375f

2022-02-14 08:38 UTC, Tooluloope commented
/ok-to-test sha=8ef91b5

2022-02-14 10:31 UTC, riodeuno requested changes
A few notes and suggestions.

2022-02-14 10:31 UTC, riodeuno commented on app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx
> +import _ from "lodash";
Let us tree shake this import. We can potentially reduce the build size by making sure we tree shake where-ever possible. I realise that lodash is being used in the application where the root import is necessary. However, I think it will help us in the long run if we use this approach as a practice.

2022-02-14 10:31 UTC, riodeuno commented on app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx
> +  const hasUniqueValues = (arr: []) => {
Two things I would suggest here:
1. We move this function out of this validation function and put it in workers/utils. Not sure if this will work, but we can try and see.
2. We don't need to do an `Array.from`. We can probably check this using `set.size < arr.length`

2022-02-14 10:31 UTC, riodeuno commented on app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx
> +  if (_.isString(value) && value !== "") {
This will probably pass strings like `"   "` as `true`. Let's make sure to trim the value, and them check for length.

2022-02-14 10:31 UTC, riodeuno commented on app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx
> +  if (value === "") {
Do we want to trim here and check for this condition?

2022-02-14 10:31 UTC, riodeuno commented on app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx
> +  const hasUniqueValues = (arr: []) => {
Also, shall we type this as `arr: Array<string>`

2022-02-14 10:31 UTC, riodeuno commented on app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx
> +            ? { laebl: o, value: o }
There is a typo here. `label`. Let's fix this and see if there is any input we could have added to the test cases to have caught this.

2022-02-14 10:31 UTC, riodeuno commented on app/client/src/widgets/SelectWidget/component/index.styled.tsx
> +import _ from "lodash";
Same suggestion as above regarding tree-shaking.

2022-02-14 10:31 UTC, riodeuno commented on app/client/src/widgets/SelectWidget/widget/index.tsx
> +    if (
Let's look at a solution in a separate PR for this:
I am curious if this can be caught in the `derviedProperty`? Instead of using componentDidUpdate and componentDidMount.

2022-02-14 11:34 UTC, Tooluloope commented on app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx
> +  if (value === "") {
We currently allow empty values,
Since the values are Unique, You can only have one option with an Empty string and most users use this as a placeholder

2022-02-14 11:40 UTC, Tooluloope commented on app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx
> +            ? { laebl: o, value: o }
I think just adding types to Values would have caught this

2022-02-14 11:47 UTC, Tooluloope commented on app/client/src/widgets/SelectWidget/widget/index.tsx
> +    if (
I'll add that to the list of task here
https://github.com/appsmithorg/appsmith/issues/10575

2022-02-14 11:48 UTC, Tooluloope commented on app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx
> +  if (value === "") {
We currently allow empty values,
Since the values are Unique, You can only have one option with an Empty string and most users use this as a placeholder

2022-02-14 15:08 UTC, Tooluloope commented on app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx
> +  const hasUniqueValues = (arr: []) => {
Didn't work in utils.
is there any reason why you advise I put this in utils?

2022-02-14 15:10 UTC, Tooluloope commented
/ok-to-test sha=1396470

2022-02-15 05:16 UTC, riodeuno commented on app/client/src/widgets/MultiSelectWidgetV2/widget/index.test.tsx
> +    const input = `{"green"`;
I'm not sure if this is a typo or do we pass through any string values in default values? Or does this match one of the values in the options?

2022-02-15 05:19 UTC, riodeuno commented on app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx
> +  const hasUniqueValues = (arr: []) => {
Yes, I believe as we're defining a function within another function -- so each time the parent function runs JS has to deal with defining the child function, this should come with a performance expense. 

If we can't move it out, it's ok, let's move on with this.

2022-02-15 05:21 UTC, sbalaji1192 commented on app/client/src/widgets/MultiSelectWidgetV2/widget/index.test.tsx
> +    const input = `{"green"`;
@riodeuno We pass string values in defaultValues, if there is no binding. This test case tests that invalid json strings don't throw error.

2022-02-15 05:30 UTC, riodeuno approved these changes
Looks good to me.

2022-02-15 05:33 UTC, riodeuno commented
@sbalaji1192 @Tooluloope Although we have added jest tests to validate our updates to the validation function -- I can see that we've made a few updates to the components to handle certain values and use-cases. We should look into adding/updating cypress tests for these scenarios, if we don't already have them in place.

2022-02-15 05:45 UTC, sbalaji1192 commented
> @sbalaji1192 @Tooluloope Although we have added jest tests to validate our updates to the validation function -- I can see that we've made a few updates to the components to handle certain values and use-cases. We should look into adding/updating cypress tests for these scenarios, if we don't already have them in place.

+1

2022-02-15 10:53 UTC, ashit-rath commented on app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx
> +      const splitByComma = (value as string).split(",") || [];
@riodeuno @Tooluloope  Should this check be enough for checking if it is a `CSV`?
ex - If I pass the value `"['green', 'red]"`, (notice `red` does not have closing single quotes). It would go to the catch clause and the value would come out to be `["['green', "'red]"]`.
This would a mistake by the Appsmith developer (missing quotes) but we are not informing the developer and treating it as a CSV.

2022-02-15 11:22 UTC, Tooluloope commented on app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx
> +      const splitByComma = (value as string).split(",") || [];
@ashit-rath, So when the user sees that in the Popup, they would be able to correct the value they inputted.

It's like having `'Green` in the PropertyPane for any width that accepts sting, it would still render as a string `"'Green". The developer can then correct  and add the extra quote

2022-02-15 11:37 UTC, riodeuno commented on app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx
> +      const splitByComma = (value as string).split(",") || [];
@ashit-rath I see your point. Nice catch! @Tooluloope could you look into the logic here to catch this case?

2022-02-15 12:06 UTC, sbalaji1192 commented on app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx
> +      const splitByComma = (value as string).split(",") || [];
@riodeuno @ashit-rath There could be many such cases involving invalid JSON strings. For eg. the user forgetting to close the square bracket or curly bracket. Are we gonna cover that case as well? 
I guess as @Tooluloope  pointed out, the user can see the evaluated value popup and debug the issue. rather than us trying to catch all invalid cases and throw an error.

2022-02-15 12:26 UTC, ashit-rath commented on app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx
> +      const splitByComma = (value as string).split(",") || [];
@sbalaji1192 You are right Balaji, we should have a limit as to how far we should validate. IMO we should only check for valid CSV.

Found this well-explained answer in [stack overflow](https://stackoverflow.com/questions/8493195/how-can-i-parse-a-csv-string-with-javascript-which-contains-comma-in-data). It does not fully comply with [RFC 4180](https://datatracker.ietf.org/doc/html/rfc4180#page-2) but is a good enough case for us.

2022-02-15 12:28 UTC, ashit-rath commented on app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx
> +      const splitByComma = (value as string).split(",") || [];
BTW what was the original reason to have comma-separated strings? Are we trying to support values coming from google sheets?

2022-02-15 12:30 UTC, Tooluloope commented on app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx
> +      const splitByComma = (value as string).split(",") || [];
We were supporting such values earlier when Select and Multiselect were 1 widget, and continue it support till now

2022-02-15 12:32 UTC, Tooluloope commented on app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx
> +      const splitByComma = (value as string).split(",") || [];
Also, the value you dropped in the First comment wasn't a CSV

2022-02-16 08:50 UTC, ashit-rath commented on app/client/src/widgets/SelectWidget/widget/index.tsx
> +    message = `value does not evaluate to type: string | { "label": "label1", "value": "value1" }'`;
@Tooluloope There is an extra `'` at the end of this line.

2022-02-16 13:33 UTC, Tooluloope commented
/ok-to-test sha=71a5db1

2022-02-17 08:39 UTC, riodeuno approved these changes

2022-02-17 08:58 UTC, Tooluloope commented
/ok-to-test sha=6f9c5ef

2022-02-18 08:01 UTC, vivekverma2312 commented
@Tooluloope Object value is not working when I use sniping mode.
https://www.loom.com/share/6d5872d293fe43929beb1ee097dc5b67

2022-02-22 08:40 UTC, shwetha-ramesh commented
@Tooluloope Co tested this PR with @YogeshJayaseelan. DP working fine for issues  #11081 & #11074. 
Moving to Done.

2022-02-22 08:43 UTC, merged