fix: handled to hide widget in preview mode
appsmithorg/appsmith pull request #11138
Opened 2022-02-14 10:56 UTC by techbhavin

## Description

>  Add Wrapper component for render preview mode. this component is responsible for hiding and showing content 
>   components base on isVisible 

Fixes #10228 

## Type of change

- Bugfix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-02-14 10:57 UTC, techbhavin commented
/ok-to-test sha=15f9e29

2022-02-16 06:30 UTC, techbhavin commented
/ok-to-test sha=6a0f047

2022-02-16 06:55 UTC, sbalaji1192 reviewed
@riodeuno Could you please have a look at these changes?

2022-02-16 06:55 UTC, sbalaji1192 commented on app/client/src/components/editorComponents/PreviewModeComponent.tsx
> +    return null as any;
do we need `as any` ?

2022-02-16 08:26 UTC, riodeuno requested changes
This needs a proper cypress test for the following:
- A successful case, where an invisible widget in preview mode doesn't show up
- An unsuccessful case, where a visible widget in preview mode shows up (We probably have this one)

2022-02-16 08:26 UTC, riodeuno commented on app/client/src/components/editorComponents/PreviewModeComponent.tsx
> +    return null as any;
@techbhavin I agree with @sbalaji1192 we don't need to return anything here if the condition is false, I believe.

We can simply say `if(!(isPreviewMode && !isVisible)) return children;`. Please see if this approach works.

2022-02-16 08:31 UTC, sbalaji1192 commented on app/client/src/components/editorComponents/PreviewModeComponent.tsx
> +    return null as any;
we can use a much simpler condition `if (!isPreviewMode || isVisible) return children;`

2022-02-16 08:33 UTC, sbalaji1192 commented
> This needs a proper cypress test for the following:
> 
> * A successful case, where an invisible widget in preview mode doesn't show up
> * An unsuccessful case, where a visible widget in preview mode shows up (We probably have this one)

And a case to make sure that the invisible widgets show up in the edit mode.

2022-02-18 12:06 UTC, riodeuno commented on app/client/src/components/editorComponents/PreviewModeComponent.tsx
> +  return null as any;
@techbhavin I am curious as to why would we need `any` here? Can we try returning a `ReactNode` or something like that? Can we return a Fragment?

2022-02-18 13:21 UTC, riodeuno approved these changes
Looks good to me! @techbhavin let's move this to the QA pipeline.

2022-02-22 08:06 UTC, shwetha-ramesh commented
@techbhavin tested this PR. DP works fine. Widgets when ```Visible``` is off doesn't show up in Preview mode

![image](https://user-images.githubusercontent.com/92293815/155088968-0eb32e9e-4e6a-4d7c-ac36-b25e35a6477e.png)

Moving to Done.

2022-02-23 03:43 UTC, techbhavin commented
/ok-to-test sha=dde57f7

2022-02-23 04:52 UTC, merged