feat: Add api to check the git connection after the key is regenerated
appsmithorg/appsmith pull request #11144
Opened 2022-02-14 13:06 UTC by AnaghHegde

## Description

> A user should have an option to regenerate the ssh keys for the git connected applications in case the key is compromised. This change set adds an API to test the connection after the key is regenerated by the user. 

Fixes #10299

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-02-14 13:09 UTC, AnaghHegde commented
/ok-to-test sha=9b9fea2

2022-02-14 18:55 UTC, abhvsn commented on app/server/appsmith-git/src/main/java/com/appsmith/git/service/GitExecutorImpl.java
> +                    .call();
If I'm not wrong `git ls-remote` fetches the list of `commit ids` along with the `refs`, does this checks the write access as well?

2022-02-14 18:56 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java
> +                    ).onErrorResume(error -> {
Can we please log the error here

2022-02-14 18:57 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java
> +    }
Should we log the analytics event as well?

2022-02-14 18:57 UTC, abhvsn requested changes
Minor comments added for improvements

2022-02-15 05:01 UTC, AnaghHegde commented on app/server/appsmith-git/src/main/java/com/appsmith/git/service/GitExecutorImpl.java
> +                    .call();
No to check write access we need to do push operation.

2022-02-15 05:02 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java
> +    }
Thats a good point. I will add this for analytics.

2022-02-15 05:52 UTC, abhvsn commented on app/server/appsmith-git/src/main/java/com/appsmith/git/service/GitExecutorImpl.java
> +                    .call();
AFAIK we should be checking the write access by pushing the logfile, am I missing something here

2022-02-15 06:02 UTC, AnaghHegde commented on app/server/appsmith-git/src/main/java/com/appsmith/git/service/GitExecutorImpl.java
> +                    .call();
Yeah agreed. But that would involves committing and pushing to remote repo. What is the user has uncommitted changes during the operation. That is why i resorted to this way. I believe the user will update the keys and not giving the write access chance is less. But i am open to other alternatives.

2022-02-15 13:49 UTC, AnaghHegde commented on app/server/appsmith-git/src/main/java/com/appsmith/git/service/GitExecutorImpl.java
> +                    .call();
I can edit the readme file in that case and do commit+push

2022-02-15 13:52 UTC, abhvsn commented on app/server/appsmith-git/src/main/java/com/appsmith/git/service/GitExecutorImpl.java
> +                    .call();
Can you please bring this discussion on pod so that we can get the inputs from other folks, IMO committing another file won't be a big deal from implementation point of view. Also I'm not inclined in making changes to readme file as this change is not related to it and this may confuse users

2022-02-16 08:44 UTC, abhvsn commented on app/server/appsmith-git/src/main/java/com/appsmith/git/service/GitExecutorImpl.java
> +                    .call();
@AnaghHegde are we going ahead with the log file or just the read access will be enough at this point?

2022-02-16 10:27 UTC, AnaghHegde commented on app/server/appsmith-git/src/main/java/com/appsmith/git/service/GitExecutorImpl.java
> +                    .call();
@abhvsn We can do that, but i just don't think we need that at the movement. Because user would already gone through updating keys.

2022-02-16 16:15 UTC, abhvsn approved these changes

2022-02-16 16:55 UTC, merged