feat: Deprecate form button widget
appsmithorg/appsmith pull request #11152
Opened 2022-02-14 21:33 UTC by wmdev0808

## Description
Since we have resetWidget as a trigger function, we can deprecate the form button widget added with every form widget. This needs to be a backwards compatible change.

Fixes #3613 

## Type of change

- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?

- Test A
- Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-02-14 21:34 UTC, wmdev0808 commented
/ok-to-test sha=e133c89

2022-02-15 05:22 UTC, ashit-rath requested changes

2022-02-15 05:22 UTC, ashit-rath commented on app/server/appsmith-server/src/main/resources/system-themes.json
> +      "BUTTON_WIDGET": {
Shouldn't we remove this entry instead of renaming it? We should already have an entry for `BUTTON_WIDGET`

2022-02-15 05:22 UTC, ashit-rath commented on app/server/appsmith-server/src/main/resources/system-themes.json
> +      "BUTTON_WIDGET": {
Please check rest of this file for similar changes and remove if redundant entries are made for `BUTTON_WIDGET`

2022-02-15 10:04 UTC, ashit-rath commented
Note to QA: Please verify the Generate CRUD app.

2022-02-15 10:05 UTC, ashit-rath approved these changes

2022-02-18 13:23 UTC, wmdev0808 commented
/ok-to-test sha=210f8c5

2022-02-18 14:35 UTC, wmdev0808 commented
/ok-to-test sha=b6c1a03

2022-02-18 17:38 UTC, wmdev0808 commented
/ok-to-test sha=31206a8

2022-02-23 08:38 UTC, wmdev0808 commented
/ok-to-test sha=581b8a6

2022-02-24 10:16 UTC, riodeuno commented on app/client/src/widgets/ButtonWidget/widget/index.tsx
> +              "Works only inside Form widget. Disables the button if any required widget in form is invalid",
I think the copy here should be:
`Works within a Form Widget. Disables the button if the Form values are invalid`

2022-02-24 10:18 UTC, riodeuno approved these changes
Code looks fine to me!

2022-02-24 10:35 UTC, riodeuno commented
@appsmithorg/qa This needs extensive testing w.r.t making sure that existing form widgets work exactly as they have so far. Testing this is critical.

2022-02-24 15:10 UTC, wmdev0808 commented
/ok-to-test sha=4b768bc

2022-03-01 19:48 UTC, wmdev0808 commented
/ok-to-test sha=d860aca

2022-03-04 10:19 UTC, somangshu commented
@vivekverma2312 @wmdev0808  A user that has found an issue - formButton.isDisabled is not working. Can we please add it in our test plan for newer alternative? - https://community.appsmith.com/t/how-can-i-validate-if-a-form-is-valid-in-a-widget-outside-the-form/700/2 - I hope its working here. 

also @riodeuno should this be fixed in the form button since we are going to maintain it, Or we simply tell the user to migrate to the new form button?

2022-03-04 10:27 UTC, YogeshJayaseelan commented
@wmdev0808 @riodeuno @somangshu Testing in progress for this feature and please find the status below,

Issue 1: Disabled Invalid form does not work on passing the JS queries like {{Button3.text==="Submit"}}  or {{Input1.text.length>4}}

https://loom.com/share/57d4e3b1b3ae403fa13d99cc52ab4ca1

Questions:

Question 1 - Migration - Opening any older apps which has a form widget - The button name still reads as 'FormButton1' and 'FormButton2' are we okay with keeping the button name as 'FormButton1' or 'FormButton2' in older apps?

Question 2 -Properties of the button is not the same in the table button property

2022-03-07 07:49 UTC, riodeuno commented
@YogeshJayaseelan We're not changing the names of the widgets. So, FormButton1, etc, are correct names.
@somangshu I was wondering if we have decided to maintain the FormButton widget? The code updates here, deprecates and removes references to the FormButton widget.

If we're removing FormButton widget, @YogeshJayaseelan we need to absolutely make sure that all Form widgets work when migrating to this DP. So, we should work on creating complex forms, and using some of our complex application on release, then opening them in the deploy preview and making sure that they work fine.

If we're still going to maintain FormButton widget, @YogeshJayaseelan we need to make sure freshly added Form widgets in the deploy preview don't have any regression in features.

2022-03-07 10:16 UTC, somangshu commented
@riodeuno multiple people suggested that we do not write migration as that will have high chance of breaking an old app, So based on this my assumption would be that we will have to maintain the old formButton

2022-03-09 08:29 UTC, YogeshJayaseelan commented
@riodeuno @somangshu We have paused testing this for now. Will resume testing once the migration-related discussion is closed 

CC - @vivekverma2312

2022-03-09 09:04 UTC, somangshu commented
@wmdev0808 can you understand the change required here? Please let me know if a discussion is required. Do collect all possible questions before we start our discussion

2022-03-09 10:57 UTC, wmdev0808 commented
> @wmdev0808 can you understand the change required here? Please let me know if a discussion is required. Do collect all possible questions before we start our discussion
@somangshu , I want your reply with the followings:
>  Here are my understanding for the new requirements:
- We don't need any migration for backward compatibility
- The newly created forms will be using `ButtonWidget` instead of `FormButtonWidget`, ensuring its original functionalities
- `ButtonWidget` should include from related form fields

> Here are my questions:
- Am I missing any other requirements?
- Does the current implementation has issues with old forms or even newly created forms?
- If yes with the above, please add demonstrating videos for my reference.

2022-03-09 11:01 UTC, somangshu commented
@wmdev0808 please help me understand what is the migration doing in the PR. I am not sure right now

2022-03-09 11:22 UTC, wmdev0808 commented
> @wmdev0808 please help me understand what is [the migration](https://github.com/appsmithorg/appsmith/pull/11152/files#diff-d4528352502419c7042ff8f1037b71c3e3895dce1474ea5a73317700f6809953R1529) doing in the PR. I am not sure right now

It just replaces the widget type with button widget's

2022-03-09 12:00 UTC, somangshu commented
> It just replaces the widget type with button widget's, that is, `FORM_BUTTON_WIDGET` to `BUTTON_WIDGET`
@wmdev0808 what is the reason to do that, @YogeshJayaseelan @vivekverma2312 did we test around this, We need to be sure that this cannot break anything

2022-03-09 12:04 UTC, wmdev0808 commented
> > It just replaces the widget type with button widget's, that is, `FORM_BUTTON_WIDGET` to `BUTTON_WIDGET`
> > @wmdev0808 what is the reason to do that, @YogeshJayaseelan @vivekverma2312 did we test around this, We need to be sure that this cannot break anything

Because we will be using `ButtonWidget` instead of `FormButtonWidget`, resulting remove `FormButtonWidget` in our code base

2022-03-15 07:34 UTC, riodeuno commented
@somangshu Whether this will break any existing applications is a tough question to answer. Looking at the code and how these widgets work, it seems like they shouldn't. With that said, we need rigorous testing for the migration nevertheless. 

This concern is also the reason for contention over whether to 
1. keep maintaining the `FORM_BUTTON_WIDGET` and use `BUTTON_WIDGET` as a replacement in _*new*_ forms or to
2. replace all references of `FORM_BUTTON_WIDGET` to `BUTTON_WIDGET` while migrating existing DSLs as well (the current PR's changes).

Form Widget is one of our most used widgets and breaking changes can impact our users negatively. To avoid a breaking scenario, we are approaching this solution in approach 1.

@wmdev0808 we can consider migration as a separate effort. The idea is to phase this solution into two parts
1. Stop using Form Button Widget for any new forms added henceforth.
2. Deprecate the Form Button Widget and cleanup the codebase with migrations to the widget.

2022-03-31 09:38 UTC, closed without merging