Update contribution guide: add details about nvm
appsmithorg/appsmith pull request #1119
Opened 2020-10-09 16:52 UTC by jyash97

## Description
Update contribution guide to cover node mismatch version error on client app.

## Type of change

Contribution guide update

## Checklist:

- [x] My changes generate no new warnings

2020-10-12 01:50 UTC, avats-dev reviewed
@jyash97 check for these and update the pr. Thanks for contributing.

2020-10-12 01:50 UTC, avats-dev commented on contributions/ClientSetup.md
> +This error occurs because the node version is not compaitble with the app environment. In this case Node version manager can be used which allows multiple
Fix typos: compatible

and add references for other platforms too. 

Link guides to contributing guide at root of source as mentioned in the issue.

2020-10-14 05:48 UTC, Nikhil-Nandagopal commented on CONTRIBUTING.md
> +- [Running the Client](contributions/ClientSetup.md)
@jyash97 this information is in the Code Contribution Guide so it's not needed here

2020-10-14 05:49 UTC, Nikhil-Nandagopal commented on contributions/ClientSetup.md
> +5. If you ran `./start-https`, but containers failed to start (you have to check with `docker ps` since it fails silently). Some Linux distros (`Ubuntu` for example) have installed and running `apach
not clear what changed here

2020-10-14 05:50 UTC, Nikhil-Nandagopal requested changes
I have a few minor changes requested

2020-10-14 05:59 UTC, jyash97 commented on CONTRIBUTING.md
> +- [Running the Client](contributions/ClientSetup.md)
Right, even I was not confident about these change, but did it based on the previous review.

2020-10-14 12:34 UTC, jyash97 commented on contributions/ClientSetup.md
> +5. If you ran `./start-https`, but containers failed to start (you have to check with `docker ps` since it fails silently). Some Linux distros (`Ubuntu` for example) have installed and running `apach
Hey @Nikhil-Nandagopal  I copy-pasted the current text as well still these shows up. Not sure why the diff is showing these. Since nothing is changed.

2020-10-15 06:24 UTC, mohanarpit approved these changes

2020-10-15 06:25 UTC, merged