fix: 8878 - To handle Comma delimited float values
appsmithorg/appsmith pull request #11207
Opened 2022-02-16 11:04 UTC by leotom2000

## Google Sheet Data processing issue with comma

- Fix for Comma delimited Number with or without decimal places

Fixes #8878 

## Type of change
- Bug fix (non-breaking change which fixes an issue) 

## How Has This Been Tested?
- Manually tested
- Existing @Tests were checked to work fine
- Added new @Tests to test new implementation

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

2022-02-16 11:17 UTC, nidhi-nair commented on app/server/appsmith-interfaces/src/test/java/com/appsmith/external/helpers/DataTypeStringUtilsTest.java
> +    public void checkCommaDelimitedNumbers() {
Nitpick: Could you please rename the tests so that it is clear what we are testing here?

2022-02-16 11:18 UTC, nidhi-nair commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/DataTypeStringUtils.java
> +        String strNumericValue = input.trim().replaceAll(",","");
Does this change the value that is displayed in the end result?

2022-02-16 11:19 UTC, nidhi-nair requested changes
A few tiny comments, please also format the files you have edited. I was pretty confused when I read `.replaceAll(",","")`. I got lost in those quotes and commas for a second because there were no spaces. :)

2022-02-16 12:35 UTC, leotom2000 commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/DataTypeStringUtils.java
> +        String strNumericValue = input.trim().replaceAll(",","");
No, it enables to decide the DataType

2022-02-16 13:58 UTC, leotom2000 commented on app/server/appsmith-interfaces/src/test/java/com/appsmith/external/helpers/DataTypeStringUtilsTest.java
> +    public void checkCommaDelimitedNumbers() {
Updated

2022-02-16 14:58 UTC, leotom2000 commented
> A few tiny comments, please also format the files you have edited. I was pretty confused when I read `.replaceAll(",","")`. I got lost in those quotes and commas for a second because there were no spaces. :)



> A few tiny comments, please also format the files you have edited. I was pretty confused when I read `.replaceAll(",","")`. I got lost in those quotes and commas for a second because there were no spaces. :)

Renamed the Test methods

2022-02-16 20:44 UTC, nidhi-nair approved these changes

2022-02-17 05:30 UTC, nidhi-nair commented
/ok-to-test sha=d21efb6

2022-02-17 07:59 UTC, nidhi-nair commented
Merging in because failing tests are flaky and unrelated.

2022-02-17 08:00 UTC, merged