fix: Fixed test MongoDB datasource shows ok even if there is no database matching the name in the 'Default Database Name' input
appsmithorg/appsmith pull request #11238
Opened 2022-02-17 10:10 UTC by mojtab23

## Description

Test MongoDB datasource shows ok even if there is no database matching the name in the 'Default Database Name' input.

Fixes #11214

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Test case [`MongoPluginTest.testDatasourceFailWithInvalidDefaultDatabaseName()`](https://github.com/appsmithorg/appsmith/blob/979bd9b2d066f1ab028001fa8e91827569786698/app/server/appsmith-plugins/mongoPlugin/src/test/java/com/external/plugins/MongoPluginTest.java#L189)  is added
- Tested manually

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-02-17 10:36 UTC, nidhi-nair commented on app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java
> +                        log.debug("list databases:{}",document.toJson());
Can we remove the logging here? We should only log things that will be required for debugging.

2022-02-17 10:40 UTC, nidhi-nair commented on app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java
> +            final String defaultDatabaseName = datasourceConfiguration.getConnection().getDefaultDatabaseName();
Should we be using `datasourceConfiguration.authentication.databaseName` here instead of `datasourceConfigurations.connection.defaultDatabaseName`?

2022-02-17 10:45 UTC, nidhi-nair commented on app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java
> +                            return Mono.just(new DatasourceTestResult("Default Database Name is invalid, no database found with this name."));
Should we not be throwing an error at this point?

2022-02-17 10:54 UTC, nidhi-nair commented on app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java
> +                                    .doOnSuccess(MongoClient::close).then(Mono.just(new DatasourceTestResult()))
Will the doOnSuccess prevent the connection from closing if the default DB is empty?

2022-02-17 10:55 UTC, nidhi-nair commented on app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java
>                                              return Mono.zip(Mono.just(mongoClient), Mono.from(result));
Instead of zipping the two, you can chain them right here, so you're only left with the connection at the end of this flatMap

2022-02-17 10:57 UTC, nidhi-nair requested changes
Needs a few changes to the flow, also need confirmation on the field being manipulated.

2022-02-17 11:58 UTC, mojtab23 commented on app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java
> +                        log.debug("list databases:{}",document.toJson());
Sure, I removed the logs.

2022-02-17 12:07 UTC, mojtab23 commented on app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java
> +            final String defaultDatabaseName = datasourceConfiguration.getConnection().getDefaultDatabaseName();
The problem we try to solve here is to make sure that the _default database name_ field in datasource configuration is valid.  `datasourceConfiguration.authentication.databaseName` is used by mongoDB to verify the credentials, it might be usable if we want to entirely change the process for _testing datasource_. but with this flow I used the correct `databaseName`.

2022-02-17 12:09 UTC, mojtab23 commented on app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java
> +                            return Mono.just(new DatasourceTestResult("Default Database Name is invalid, no database found with this name."));
I've tested it manually and it's working as expected. what for replace do you have in mind?

2022-02-17 12:16 UTC, mojtab23 commented on app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java
> +                                    .doOnSuccess(MongoClient::close).then(Mono.just(new DatasourceTestResult()))
I'm not sure, its behavior will be the same as before. You are right, there is no guarantee to call the client.close() if there is an error.

2022-02-17 12:18 UTC, mojtab23 commented on app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java
>                                              return Mono.zip(Mono.just(mongoClient), Mono.from(result));
I'm not sure what to do here. can you help me?

2022-02-17 12:26 UTC, nidhi-nair commented on app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java
> +            final String defaultDatabaseName = datasourceConfiguration.getConnection().getDefaultDatabaseName();
Oh I see. In that case we should switch out the `admin` on L#885 with authentication database. I missed this in the previous change during review as well. This is my bad. :)

2022-02-17 12:28 UTC, nidhi-nair commented on app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java
> +                                    .doOnSuccess(MongoClient::close).then(Mono.just(new DatasourceTestResult()))
Can we use a `.then` in that case? This will make sure that the closing happens regardless of the result of the previous flatMap

2022-02-17 12:32 UTC, nidhi-nair commented on app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java
> +                                        if (datasourceConfiguration.getConnection() != null && defaultDatabaseName != null) {
If getConnection can return a null, we will already have failed at L#882 where you are initializing `defaultDatabaseName`

2022-02-17 12:36 UTC, nidhi-nair commented on app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java
>                                              return Mono.zip(Mono.just(mongoClient), Mono.from(result));
How are we checking if result is valid here? That is, how do we know is `result` returned with an error?

2022-02-18 06:08 UTC, nidhi-nair commented
/ok-to-test sha=161ec76

2022-02-18 07:11 UTC, merged