removed unnecessary uncaught promise errors stopped from logging to S…
appsmithorg/appsmith pull request #11319
Opened 2022-02-21 12:23 UTC by ApekshaBhosale

## Description
All user errors were logged into sentry.  There is the flooding of these user errors as UncaughtPromiseError. 

Fixes #10865\

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-02-22 05:34 UTC, hetunandu requested changes

2022-02-22 05:34 UTC, hetunandu commented on app/client/src/sagas/PostEvaluationSagas.ts
> +        if (!(error instanceof UncaughtPromiseError)) {
Add it as a case and just log it on the console. Dont ignore

2022-02-22 06:31 UTC, ApekshaBhosale commented on app/client/src/sagas/PostEvaluationSagas.ts
> +        if (!(error instanceof UncaughtPromiseError)) {
this is in default condition so other types needs to be sent to Sentry and this error does not have a type @hetunandu

2022-02-23 06:22 UTC, hetunandu requested changes

2022-02-23 06:22 UTC, hetunandu commented on app/client/src/sagas/PostEvaluationSagas.ts
> +        if (!(error instanceof UncaughtPromiseError)) {
Can we add a type to it? That handling will be better

2022-03-13 16:41 UTC, closed without merging