removing unnecessary paths to evaluate
appsmithorg/appsmith pull request #11341
Opened 2022-02-22 09:24 UTC by ApekshaBhosale

## Description
Removing internal paths from evaluations by making it 'NOOP' during translated diff creation. Paths that will be removed are 
all the paths which are inside dynamicBindingPathList, bindingPaths, validationPaths & triggerPaths

Fixes #10799 

## Type of change
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-02-22 09:35 UTC, hetunandu requested changes

2022-02-22 09:35 UTC, hetunandu commented on app/client/src/workers/evaluationUtils.ts
> +  if (
This is not a well thought out change. Please think of a better long term solution and refactor to make this function generic. 
- What are the performance improvements by adding this change?
- Why not move these paths under `__evaluation__` so that we can just ignore a single key?
- Why does JSON form editor face this problem with these keys? Why are they getting evaluated because of that?
- Why not `dynamicTriggerPathList` ?

2022-02-22 09:51 UTC, ApekshaBhosale commented on app/client/src/workers/evaluationUtils.ts
> +  if (
What is the consequence of this? 
1.  it reduces the number of paths to be evaluated hence the time taken is less
2.  why move them under __evaluation__? isn't that where we store evaluated data and errors but this is neither
3. JSON form widget has a schema. and each property in JSON is a widget so if there are 10 properties, it has 10 widgets and these 10 widgets have properties of their own. As a result of this, it's creating too many paths to be evaluated. JSON widget just increases the number of paths for evaluation. and if you check for each new diff we check references in other entities which again are too many. 
4. dynamicTriggerPathList is internal for us to create a dependency map etc. but what is the use of actually evaluating dynamicTriggerPathList? we don't evaluate or validate that path. eg - Table1 -> dynamicTriggerPathList - Table1.dynamicBindingPathList.primaryColumns.id.computedValue

Let me know if I am missing something

2022-02-22 09:59 UTC, hetunandu commented on app/client/src/workers/evaluationUtils.ts
> +  if (
- I would like to see some numbers of how much of an impact does these paths have on performance
- We can move all these paths that do not need to be evaluated under `__evaluation__` to keep them all in the same place. That way you don't have to check the `indexOf` of multiple paths. indexOf is an O!n computation
- We might not be evaluating `dynamicTriggerPathList` today but we may end up coming in the differences in the future, since we will never need to evaluate it, it should also get a NOOP.
- This solution only solves for `updateDataTree`. `createFirstTree` will still evaluate all these paths, that means the first load would still be slower

2022-02-22 10:05 UTC, ApekshaBhosale commented on app/client/src/workers/evaluationUtils.ts
> +  if (
- it used to take 7sec for updateDependencyMap for JSON widget it now takes 0.7 sec
- I made changes during translatedDiffs, not while eval
- createFirst does not eval all paths it evaluates dependency maps all paths and this does not contain in dependency map hence no problem during the first eval

2022-02-22 10:07 UTC, ApekshaBhosale commented on app/client/src/workers/evaluationUtils.ts
> +  if (
cc @trishaanand

2022-02-22 10:42 UTC, hetunandu commented on app/client/src/workers/evaluationUtils.ts
> +  if (
So, why can't we move these "path lists" inside a single key and remove them from the dataTree even before taking differences?

2022-02-22 10:45 UTC, ApekshaBhosale commented on app/client/src/workers/evaluationUtils.ts
> +  if (
I am planning to create 2 different trees for eval and as meta tree. and this is what it's going to do remove them from eval and validation. That is a bigger change and till then we can ship as basic funda is same.

2022-02-22 10:48 UTC, hetunandu commented on app/client/src/workers/evaluationUtils.ts
> +  if (
Is there an issue for this?

2022-02-22 12:28 UTC, ApekshaBhosale commented on app/client/src/workers/evaluationUtils.ts
> +  if (
I will be creating the issue

2022-02-22 12:38 UTC, ApekshaBhosale commented on app/client/src/workers/evaluationUtils.ts
> +  if (
https://github.com/appsmithorg/appsmith/issues/11351 i have created it. i will add more details to it @hetunandu

2022-02-24 12:25 UTC, ApekshaBhosale commented on app/client/src/workers/evaluationUtils.ts
> +  if (
@hetunandu I haven't moved the change you suggested because we need differences to apply to the eval tree which goes for evaluation.

2022-02-25 12:01 UTC, hetunandu approved these changes

2022-03-01 09:58 UTC, mohanarpit commented
/ok-to-test sha=7096fbda59bcee22ab5742b853ca5ba82574b704

2022-03-01 15:48 UTC, ApekshaBhosale commented
/ok-to-test sha=7096fbd

2022-03-03 07:42 UTC, merged