feature: Add Array type to MultipartFormDataType variants
appsmithorg/appsmith pull request #11386
Opened 2022-02-23 09:38 UTC by mojtab23

## Description
Users can add an array as a value for multipart requests, and it will handle every item in the list as a part of the multipart request.

TODO add screenshots...

Fixes #10876

## Type of change

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

## How Has This Been Tested?

- Unit test - ‍‍‍‍`DataUtilsTest.testParseMultipartArrayDataWorks()`

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-03-14 12:30 UTC, AmanAgarwal041 submitted a review, later dismissed

2022-03-14 15:42 UTC, nidhi-nair requested changes

2022-03-14 15:42 UTC, nidhi-nair commented on app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/helpers/DataUtils.java
> +                                        MediaType.TEXT_PLAIN);                                break;
Nit: Please format the file before commiting

2022-03-14 15:42 UTC, nidhi-nair commented on app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/helpers/DataUtils.java
> +                                System.out.println(property);
Can we remove this extraneous log?

2022-03-14 15:42 UTC, nidhi-nair commented on app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/helpers/DataUtilsTest.java
> +                    Assertions.assertThat(content).contains("Content-Disposition: form-data; name=\"arrayOne\"");
Can we test for each of the array values getting passed here?

2022-03-15 07:41 UTC, mojtab23 commented on app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/helpers/DataUtils.java
> +                                        MediaType.TEXT_PLAIN);                                break;
Fixed!

2022-03-15 07:41 UTC, mojtab23 commented on app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/helpers/DataUtils.java
> +                                System.out.println(property);
Fixed!

2022-03-15 07:41 UTC, mojtab23 commented on app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/helpers/DataUtilsTest.java
> +                    Assertions.assertThat(content).contains("Content-Disposition: form-data; name=\"arrayOne\"");
I changed the test.

2022-03-15 09:46 UTC, nidhi-nair approved these changes
Looks good to me. @mojtab23, please also raise a Github issue for adding documentation for this change and assign it to @Pranay105. You will also need to provide a draft that they can then edit to add in the docs.

2022-03-15 10:56 UTC, mojtab23 commented
/ok-to-test sha=af686a0

2022-03-17 13:17 UTC, nidhi-nair commented
/ok-to-test sha=af686a0

2022-03-24 11:45 UTC, danieldare commented
/ok-to-test sha=af686a0

2022-03-24 19:53 UTC, Aishwarya-U-R commented
/ok-to-test sha=2c8f0bf

2022-03-25 07:45 UTC, danieldare commented
/ok-to-test sha=f8355af

2022-03-25 16:10 UTC, Aishwarya-U-R commented
/ok-to-test sha=a9f8a03

2022-03-25 16:33 UTC, Aishwarya-U-R commented
/ok-to-test sha=a9f8a03

2022-03-25 16:54 UTC, Aishwarya-U-R commented
/ok-to-test sha=a9f8a03

2022-03-25 18:46 UTC, Aishwarya-U-R commented
/ok-to-test sha=a9f8a03

2022-03-26 05:49 UTC, Aishwarya-U-R commented
/ok-to-test sha=a9f8a03

2022-03-26 06:51 UTC, Aishwarya-U-R commented
/ok-to-test sha=a9f8a03

2022-03-26 06:53 UTC, Aishwarya-U-R commented
/ok-to-test sha=fca63f1

2022-03-26 19:08 UTC, Irongade approved these changes

2022-03-26 19:08 UTC, merged