feat: Internal property to detect changes in a form
appsmithorg/appsmith pull request #11383
Opened 2022-02-23 08:29 UTC by wmdev0808

## Description
As a user, I need an internal property in the form to detect any changes made to the form elements

> Motivation

"I would want to implement something to alert users before changing page with unsaved changes. But to do that I am missing a feature on the form widget: properties that would be like form_1.has_changes , that would be true if any of the fields have been manually changed after loading its default value."

Fixes #4182 

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Test A
- Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-02-24 05:59 UTC, somangshu commented
@riodeuno will need your help here

2022-02-28 10:50 UTC, riodeuno requested changes

2022-02-28 10:50 UTC, riodeuno commented on app/client/src/widgets/FilePickerWidgetV2/widget/index.tsx
> +      isDirty: `{{ this.selectedFiles.length > 0 }}`,
@wmdev0808 I believe we have existing issues with the filepicker's selected files, they don't get reset I think. Can we make sure that `resetWidget` works properly with filepicker and that this becomes isDirty=false, when we submit a form or reset the form.

2022-02-28 10:50 UTC, riodeuno commented on app/client/src/widgets/FormWidget/widget/index.tsx
> +    const childWidgets = containerWidget.children || [];
There can be deep nesting of children. Can we re-use the `updateFormData` method here?

2022-02-28 10:50 UTC, riodeuno commented on app/client/src/widgets/InputWidgetV2/widget/index.tsx
> +    // If defaultText property has changed, reset isDirty to false
I was wondering if we can use the `isDirty` property as a derived property?

2022-02-28 10:50 UTC, riodeuno commented on app/client/src/widgets/MultiSelectTreeWidget/widget/index.tsx
> +      isDirty: `{{ ((array1, array2) => {if (array1.length === array2.length) {return !array1.every(element => array2.includes(element));} return true;})(this.defaultOptionValue, this.selectedOptionV
@wmdev0808 I have the same suggestion here as with the other widget where I recommended using `_.without`

2022-02-28 10:50 UTC, riodeuno commented on app/client/src/widgets/PhoneInputWidget/widget/index.tsx
> +      this.props.updateWidgetMetaProperty("isDirty", false);
@wmdev0808 @sbalaji1192 I am wondering if we can use `isDirty` as a derived property.

2022-02-28 10:50 UTC, riodeuno commented on app/client/src/widgets/RichTextEditorWidget/widget/index.tsx
> +  componentDidUpdate(prevProps: RichTextEditorWidgetProps): void {
@wmdev0808 I believe we're fixing two different issues here. It is nice to fix another issue we've identified. Can you comment on which issues we are fixing and how are we fixing it? I am asking because I don't get the point of the `isDefaultTextChanged` property.

2022-02-28 10:50 UTC, riodeuno commented on app/client/src/widgets/SelectWidget/widget/index.tsx
> +      isDirty: `{{ this.value !== this.defaultValue }}`,
Perfect! Let's try and use derived property instead of meta property everywhere!

2022-02-28 10:50 UTC, riodeuno commented on app/client/src/widgets/SwitchGroupWidget/widget/index.tsx
> +      isDirty: `{{ ((array1, array2) => {if (array1.length === array2.length) {return !array1.every(element => array2.includes(element));} return true;})(this.defaultSelectedValues, this.selectedValu
@wmdev0808 Same suggestion as the other widgets where I recommended using `_.without`

2022-02-28 10:50 UTC, riodeuno commented on app/client/src/widgets/SwitchGroupWidget/widget/index.tsx
> +    if (this.props.defaultSelectedValues !== prevProps.defaultSelectedValues) {
@wmdev0808 I was wondering if we can populate this `selectedValuesArray` properly in the `handleSwitchStateChange` handler?

2022-02-28 10:57 UTC, sbalaji1192 commented on app/client/src/widgets/FilePickerWidgetV2/widget/index.tsx
> +      isDirty: `{{ this.selectedFiles.length > 0 }}`,
@riodeuno Filepicker's selected files issue has been resolve  with this PR - https://github.com/appsmithorg/appsmith/pull/10734

2022-02-28 11:05 UTC, sbalaji1192 commented
@wmdev0808 @riodeuno It appears that we have inconsistency between Input widget's isDirty vs select widget isDirty. 
Input widget's isDirty is true even after the user undoes the changes she made. But with select widget, if the user undoes the change, it will become false.

2022-02-28 11:12 UTC, riodeuno commented on app/client/src/widgets/PhoneInputWidget/widget/index.tsx
> +      this.props.updateWidgetMetaProperty("isDirty", false);
Got it. We might need a platform change where we can update multiple meta properties at once. Because, the way I see it, the update to value and update `isDirty` seem to be related and can be done with computations together.

2022-02-28 11:20 UTC, SatishGandham commented on app/client/src/widgets/CheckboxGroupWidget/widget/index.tsx
> +      isDirty: `{{ ((array1, array2) => {if (array1.length === array2.length) {return !array1.every(element => array2.includes(element));} return true;})(this.defaultSelectedValues, this.selectedValu
Considering the size of selected values, it won't have any notable impact.

2022-02-28 11:20 UTC, SatishGandham commented on app/client/src/widgets/CheckboxGroupWidget/widget/index.tsx
> +      isDirty: `{{ ((array1, array2) => {if (array1.length === array2.length) {return !array1.every(element => array2.includes(element));} return true;})(this.defaultSelectedValues, this.selectedValu
Considering the size of selected values, it won't have any notable impact.

2022-02-28 11:56 UTC, wmdev0808 commented on app/client/src/widgets/AudioRecorderWidget/widget/index.tsx
> +      isDirty: `{{ !!this.blobURL }}`,
Yes, it does

2022-02-28 11:58 UTC, wmdev0808 commented on app/client/src/widgets/CameraWidget/component/index.tsx
> +    resetMedia();
It is just for cleanup displayed timer, timer, image or video whenever we switch the mode

2022-02-28 13:07 UTC, riodeuno commented on app/client/src/widgets/CheckboxGroupWidget/widget/index.tsx
> +      isDirty: `{{ ((array1, array2) => {if (array1.length === array2.length) {return !array1.every(element => array2.includes(element));} return true;})(this.defaultSelectedValues, this.selectedValu
We might want to look at _.xor then. Basically Lodash utilities can make this more readable and as a result more maintainable

2022-02-28 13:22 UTC, wmdev0808 commented on app/client/src/widgets/CheckboxWidget/widget/index.tsx
> +      this.props.updateWidgetMetaProperty("isDirty", false);
Yes, it's required.
Without the above cleanup, we cannot guarantee the right `isDirty`.
For example, when you change defaultCheckedState property from false to true,  and then change the UI's state, the functionality, `isDirty` does not work

2022-02-28 14:31 UTC, wmdev0808 commented on app/client/src/widgets/CurrencyInputWidget/widget/index.tsx
> +    if (value === String(this.props.defaultText)) {
@riodeuno ,
We should be able to set `isDirty` to both of true and false here.
And two conditions are exclusive, so it never set `isDirty` twice

2022-02-28 22:01 UTC, wmdev0808 commented on app/client/src/widgets/RichTextEditorWidget/widget/index.tsx
> +  componentDidUpdate(prevProps: RichTextEditorWidgetProps): void {
@riodeuno ,
The point is that the meta property `text` is parsed by underlying RTE package, so we can't directly compare this value to `defaultText`.
From this standpoint, we are introducing two meta properties `defaultTextHtml` and `defaultTextMarkdown`, which will be used for comparing.
Whenever `defaultText` property is changed, we need to update the above newly introduced meta properties to parsed value, which can only be obtained from `onValueChange` method.
That's why we need `isDefaultTextChanged`

2022-02-28 22:24 UTC, wmdev0808 commented on app/client/src/widgets/SwitchGroupWidget/widget/index.tsx
> +    if (this.props.defaultSelectedValues !== prevProps.defaultSelectedValues) {
Yes, 
In addition, `handleSwitchStateChange` is triggered only by user interaction, that is, the handler does not triggered when we change `defaultSelectedValues`

2022-02-28 22:34 UTC, wmdev0808 commented
@riodeuno and @sbalaji1192 ,
I am somehow confused with regard to you two guys comments.
My question is if `isDirty` can be implemented as a derived prop with even Input widgets.
Please clarify this

2022-03-01 05:21 UTC, sbalaji1192 commented
@wmdev0808 There is a small caveat if we make the isDirty a derived property. As of now, isDirty is a meta property. So when we set it to true, it will hold that state until we call resetWidget. But if we make it derived property, it will hold the state unless the user undoes the changes she did.

2022-03-01 06:38 UTC, sbalaji1192 commented
@riodeuno @wmdev0808 Please refer to this video for the explanation of the issue with making it a derived property - https://www.loom.com/share/9c9b9b8e1543438c9648411be1e5f75d

@riodeuno Paul is blocked until we make a decision on derived property / meta property.

2022-03-01 07:55 UTC, riodeuno commented
@sbalaji1192 Here are the problems I see with this:
1. The platform doesn't/can't support resetting derived properties at this time. This makes `resetWidget` not work for any property other than the `meta` property.
2. `isDirty` is supposed to be true until the user edits the field somehow, even if the user clears out or reverts back to the pristine value, it should still be considered as dirty. This means that the only ways to go back to `isDirty = false` state, are the following:
- When the Form Widget or the widget is reset
- When the page is refreshed
- When the `defaultValue` changes (This means that the form has new set of values coming in, making it pristine)

Could you confirm the above points?

If the above are true, then 
1. We should make sure `isDirty` is always a meta property. Possibly try to allow widgets to update multiple meta properties at once to avoid a re-render.
2. The 3 ways in which one can make the field pristine again, must be implemented for all widgets in this PR.

2022-03-01 08:11 UTC, riodeuno commented
Got it. How about the first point about `resetWidget` not working for non-meta properties? 
If this is also true, then @wmdev0808 I'm sorry for my previous incorrect suggestion. 
I believe we need to convert all `isDirty` into a `meta` property, because it is the widget which decides when it is pristine.

cc @sbalaji1192 are my assumptions correct?

2022-03-01 08:18 UTC, sbalaji1192 commented
@riodeuno regarding resetWidget, Yeah your assumption is correct. resetWidget only works with meta properties. Since derived property doesn't hold any state and gets its value computed from other properties (meta and widget properties), there is nothing to be cleared of.

Agree with your point that Widget should decide when to update isDirty.

2022-03-01 09:51 UTC, Tooluloope requested changes

2022-03-01 09:51 UTC, Tooluloope commented on app/client/src/widgets/MultiSelectTreeWidget/widget/index.tsx
> +      isDirty: `{{ ((array1, array2) => {if (array1.length === array2.length) {return !array1.every(element => array2.includes(element));} return true;})(this.defaultOptionValue, this.selectedOptionV
@wmdev0808 From what I understand here, Selecting an option and deselecting the option to make `selectedOptionValues === defaultOptionValue `  would make `isDirty` false. And from what I think, as long as any operation has been done on the input field it's meant to be dirty

2022-03-01 09:51 UTC, Tooluloope commented on app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx
> +      isDirty: `{{ ((array1, array2) => {if (array1.length === array2.length) {return !array1.map((o) => o.value).every(element => array2.includes(element));} return true;})(this.defaultOptionValue,
Going by the previous comment

> @wmdev0808 From what I understand here, Selecting an option and deselecting the option to make
> selectedOptionValues === defaultOptionValue would make isDirty false. And from what I think, as long as any operation has been done on the input field it's meant to be dirty

using isDirty as a Meta property would be ideal, as we can just update it once when a change occurs and reset it when `defaultOptionValue` is changed or at any point where reset is necessary

2022-03-01 09:51 UTC, Tooluloope commented on app/client/src/widgets/SelectWidget/widget/index.tsx
> +      isDirty: `{{ this.value !== this.defaultValue }}`,
https://www.loom.com/share/75592d640fc345b1a819cc59e2317d31

Not sure if this is the right approach

2022-03-01 09:53 UTC, Tooluloope commented
@riodeuno @sbalaji1192 @wmdev0808 I noticed we used `isDirty` as derived properties in some places and as meta properties in others, Shouldn't we align both, and from the use-cases I mentioned, meta property seems like the best approach

2022-03-01 10:04 UTC, riodeuno commented
> I believe we need to convert all `isDirty` into a `meta` property, because it is the widget which decides when it is pristine.


@Tooluloope @sbalaji1192 I think we all agree that we have to do this. cc @wmdev0808

2022-03-01 19:17 UTC, wmdev0808 commented
/ok-to-test sha=e7355bd

2022-03-02 23:49 UTC, Tooluloope requested changes
@wmdev0808 could you take time to add cypress test for all the widgets involved.
Also a More detailed Description of the PR would be appreciated

2022-03-03 00:54 UTC, Tooluloope requested changes

2022-03-03 00:54 UTC, Tooluloope commented on app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx
> +      this.props.isDirty
I think there's an issue here, DefaultOptionValue for multiselectv2 has been updated to allow 
```string | string[]``` and ```Array<{value: string, label: string}>``` I guess I omitted the latter type when updating it. Could you help correct it?

So when using Array of Objects we might need to use ```xorWith(objects, others, _.isEqual)```

2022-03-03 00:54 UTC, Tooluloope commented on app/client/src/widgets/RichTextEditorWidget/widget/index.tsx
> +
Could you please explain why this is still needed, `onValueChange` should trigger `isDirty` by default

2022-03-03 00:54 UTC, Tooluloope commented on app/client/src/widgets/RichTextEditorWidget/widget/index.tsx
> +      isDirty: `{{ this.inputType === "html" ? this.text !== this.defaultTextHtml : this.text !== this.defaultTextMarkdown }}`,
Also, is there a reason why we still use it as a derived property?

2022-03-03 00:54 UTC, Tooluloope commented on app/client/src/widgets/SelectWidget/widget/index.tsx
> +      prevProps.defaultOptionValue.value ?? prevProps.defaultOptionValue;
Changing the label should as well reset the `isDirty` property

2022-03-03 06:47 UTC, wmdev0808 commented
@somangshu ,
I am going to increase the time estimation for this PR for the following reason:
- The estimation of 3 has already been spent by the first commit for this PR
- 1 day for switching from derived property to meta property because we could reach the agreement later.
- 2 days: I am now required to add Cypress tests all over the widgets involved  
To sum up, the final estimation for this issue will be 6

2022-03-03 13:34 UTC, wmdev0808 commented on app/client/src/widgets/RichTextEditorWidget/widget/index.tsx
> +
Because `onValueChange` is even triggered by defaultText change

2022-03-03 13:36 UTC, wmdev0808 commented on app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx
> +      this.props.isDirty
Sure, thank you for your tip

2022-03-03 13:36 UTC, wmdev0808 commented on app/client/src/widgets/RichTextEditorWidget/widget/index.tsx
> +      isDirty: `{{ this.inputType === "html" ? this.text !== this.defaultTextHtml : this.text !== this.defaultTextMarkdown }}`,
No, that is just code smell, I will remove it, thank you

2022-03-03 13:47 UTC, wmdev0808 commented on app/client/src/widgets/SelectWidget/widget/index.tsx
> +      prevProps.defaultOptionValue.value ?? prevProps.defaultOptionValue;
I don't think so because the current implementation only relies on `value` property

2022-03-07 15:52 UTC, wmdev0808 commented
/ok-to-test sha=fd2acfc

2022-03-07 18:10 UTC, wmdev0808 commented
/ok-to-test sha=37a2b4c

2022-03-10 09:11 UTC, somangshu commented
@Tooluloope why are we facing a delay in review here?

2022-03-14 11:51 UTC, Tooluloope commented
> @Tooluloope why are we facing a delay in review here?

Was preoccupied with a lot last week.
Currently reviewing

2022-03-14 13:03 UTC, Tooluloope requested changes

2022-03-14 18:30 UTC, sbalaji1192 commented
> > Got it. How about the first point about `resetWidget` not working for non-meta properties? If this is also true, then @wmdev0808 I'm sorry for my previous incorrect suggestion. I believe we need to convert all `isDirty` into a `meta` property, because it is the widget which decides when it is pristine.
> > cc @sbalaji1192 are my assumptions correct?
> 
> I believe we should be able to reset `isDirty` when DefaultValue changes or the data coming into the widget changes like `options` for Select widget. @sbalaji1192

@Tooluloope Yeah. Ideally, we should set isDirty false when the source of truth itself changes.

2022-03-15 07:58 UTC, Tooluloope commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/FilePickerV2_spec.js
> +    cy.get(".t--widget-textwidget").should("contain", "true");
@sbalaji1192 @somangshu is it possible to reset the FilePicker widget via Propertypane

2022-03-15 08:59 UTC, sbalaji1192 commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/FilePickerV2_spec.js
> +    cy.get(".t--widget-textwidget").should("contain", "true");
@Tooluloope As in reset Meta properties ? It's not possible.

2022-03-15 10:14 UTC, Tooluloope commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/FilePickerV2_spec.js
> +    cy.get(".t--widget-textwidget").should("contain", "true");
Got it ✌️

2022-03-16 12:28 UTC, wmdev0808 commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/FormWidget_Nested_HasChanges_spec.js
> +    cy.wait(2000);
It can be removed, thank you

2022-03-16 13:52 UTC, wmdev0808 commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/RichTextEditor_spec.js
> -
No, it happened by mistake, it should be restored, thank you

2022-03-16 14:53 UTC, wmdev0808 commented
/ok-to-test sha=7403449

2022-03-17 08:23 UTC, Tooluloope requested changes

2022-03-17 08:23 UTC, Tooluloope commented on app/client/src/widgets/RichTextEditorWidget/widget/index.tsx
> +  isDefaultTextChanged: boolean;
@wmdev0808 I don't think these properties are still needed

2022-03-17 11:28 UTC, wmdev0808 commented
/ok-to-test sha=3e37914

2022-03-18 09:36 UTC, Tooluloope submitted a review, later dismissed
LGTM

2022-03-21 21:15 UTC, wmdev0808 commented
/ok-to-test sha=0e6ade6

2022-03-22 09:08 UTC, Tooluloope commented
@wmdev0808 Could you fix the vercel deployment, so QA can test

2022-03-22 10:11 UTC, wmdev0808 commented
/ok-to-test sha=2b278ee

2022-03-23 06:36 UTC, Tooluloope approved these changes

2022-03-30 06:19 UTC, chandannkumar commented
@wmdev0808  Tested this PR and had few observations:
1. For Phone Input widget's isDirty sets to 'false' when Default text is empty
https://www.loom.com/share/9a7f1b9723f74ac2a9072787bfa1aa48

2. For RTE widget's isDirty remains 'false' for the very first input after removing the Default text from property pane
https://www.loom.com/share/98d787f3c6ff442896208a7d6fb28357

2022-03-30 15:21 UTC, wmdev0808 commented
/ok-to-test sha=965876b

2022-03-31 06:03 UTC, chandannkumar commented
This PR is working as expected

1.Tested **isDirty** must be added under meta property for above listed widgets 
2. Tested exposed **hasChanges** property in Form widget 
3. Tested widgets pristine state scenarios

2022-03-31 08:40 UTC, Tooluloope commented
@wmdev0808 Could you resolve the conflict and run the tests.
Let's try to merge this in this week.

2022-03-31 08:43 UTC, Tooluloope submitted a review, later dismissed

2022-03-31 09:29 UTC, riodeuno submitted a review, later dismissed

2022-03-31 09:54 UTC, wmdev0808 commented
/ok-to-test sha=c582ad2

2022-03-31 11:57 UTC, Tooluloope submitted a review, later dismissed

2022-04-01 05:57 UTC, Tooluloope submitted a review, later dismissed

2022-04-01 07:45 UTC, wmdev0808 commented
/ok-to-test sha=afb7b40

2022-04-01 10:15 UTC, Tooluloope commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/ExplorerTests/Entity_Explorer_Widgets_Copy_Paste_Delete_Undo_Keyboard_Event_spec.js
> +      expect($lis).to.have.length(3);
Why are you making this changes?

2022-04-01 10:17 UTC, wmdev0808 commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/ExplorerTests/Entity_Explorer_Widgets_Copy_Paste_Delete_Undo_Keyboard_Event_spec.js
> +      expect($lis).to.have.length(3);
Because we have added a new meta property, `hasChanges`

2022-04-01 10:41 UTC, wmdev0808 commented
/ok-to-test sha=69f5c65

2022-04-01 16:15 UTC, wmdev0808 commented
/ok-to-test sha=9590e0f

2022-04-02 00:15 UTC, wmdev0808 commented
/ok-to-test sha=cc9db78

2022-04-02 18:03 UTC, wmdev0808 commented
/ok-to-test sha=bbf7f12

2022-04-04 05:28 UTC, wmdev0808 commented
/ok-to-test sha=dfd3662

2022-04-05 05:34 UTC, Tooluloope approved these changes

2022-04-05 05:35 UTC, merged