fix: 9824 Google Sheet to filter empty condition ver.2
appsmithorg/appsmith pull request #11435
Opened 2022-02-24 19:37 UTC by leotom2000

## Description
To fetch data from Google Sheet with empty where condition, ie with no entry in Where Conditions, value field
User needs this implementation as he want to search a member with no emailId from the googlesheet database.

Fixes #9824

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manually tested with Single and Multiple conditions
- Unit Test Added

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

2022-02-28 03:01 UTC, nidhi-nair commented on app/server/appsmith-interfaces/src/test/java/com/appsmith/external/services/FilterDataServiceTest.java
> +                    .forEach(val -> val.setValue(" ")); // Setting null fails in null validation
Should this not be an empty string?

2022-02-28 09:27 UTC, leotom2000 commented on app/server/appsmith-interfaces/src/test/java/com/appsmith/external/services/FilterDataServiceTest.java
> +                    .forEach(val -> val.setValue(" ")); // Setting null fails in null validation
In appsmith-Interfaces module, Condition.java has a method isValid(Condition condition),
This evaluates for StringUtills.isEmpty and throws error.

So we are adding a Space to bypass that 
updated to StringUtills.Space  instead of " " now

2022-02-28 11:33 UTC, nidhi-nair commented on app/server/appsmith-interfaces/src/test/java/com/appsmith/external/services/FilterDataServiceTest.java
> +                    .forEach(val -> val.setValue(" ")); // Setting null fails in null validation
Then the fix needs to be made for the empty check right? The end user would always have an empty string that they pass.

2022-03-01 10:48 UTC, leotom2000 commented on app/server/appsmith-interfaces/src/test/java/com/appsmith/external/services/FilterDataServiceTest.java
> +                    .forEach(val -> val.setValue(" ")); // Setting null fails in null validation
Resolved this issue as discussed with you

2022-03-01 11:26 UTC, nidhi-nair commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/services/ce/FilterDataServiceCE.java
> +            if ((value != null || (value != null && !value.equals(StringUtils.EMPTY))) &&
There seems to be a redundant check here? Could you please confirm?

2022-03-01 11:26 UTC, nidhi-nair commented on app/server/appsmith-interfaces/src/test/java/com/appsmith/external/services/FilterDataServiceTest.java
> +            Condition condition2 = new Condition("productName", "EQ", null); //The UI sends null when that field is untouched
Good job on this test case

2022-03-01 11:27 UTC, nidhi-nair requested changes
@leotom2000 Please check the condition to add brackets for `IN` and `NOT IN`

2022-03-01 19:43 UTC, leotom2000 commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/services/ce/FilterDataServiceCE.java
> +            if ((value != null || (value != null && !value.equals(StringUtils.EMPTY))) &&
Simplified the line of code
Anyhow the objective is, value should not be EMPTY or null

2022-03-01 20:55 UTC, leotom2000 commented
> @leotom2000 Please check the condition to add brackets for `IN` and `NOT IN`

The functionality taking array as inputs for IN and NOT IN remains unmodified and works fine except that it is validated for Empty and null which is taken care by the current implementation. All non null values remains the same and handled as earlier.


![image](https://user-images.githubusercontent.com/8027694/156246967-6d660afc-d62f-4da7-ae26-a761e92804aa.png)

2022-03-02 09:18 UTC, leotom2000 commented
/ok-to-test sha=f72e09f

2022-03-02 17:04 UTC, merged