Add widget cta in query pane
appsmithorg/appsmith pull request #1157
Opened 2020-10-13 07:45 UTC by akash-codemonk

Fixes #929

2020-10-14 05:23 UTC, hetunandu commented on app/client/src/sagas/WidgetOperationSagas.tsx
> +function* addWidgetSaga(action: ReduxAction<AddWidgetPayload>) {
This needs to be `addTableWidgetFromQuerySaga` since it is only used for that

2020-10-14 05:23 UTC, hetunandu commented on app/client/src/sagas/WidgetOperationSagas.tsx
> +    }
Why is this piece of code needed?

2020-10-14 05:30 UTC, akash-codemonk commented on app/client/src/sagas/WidgetOperationSagas.tsx
> +    }
If you have a look at the deploy preview adding a table widget with let's say `{{Query2.data}}` to the `tableData` prop, it does not get evaluated i.e the table doesn't show the data. So here I am updating that property which seems to do the evaluation.

2020-10-14 12:32 UTC, hetunandu requested changes
You need to make this feature specific to adding a table from an action. From the action only the action name should be sent. Everything else should be calculated in the saga. After creating the empty Table widget, update the tableData property with the correct value and everything should fall into place

2020-10-14 12:32 UTC, hetunandu commented on app/client/src/actions/widgetActions.tsx
> +    type: ReduxActionTypes.ADD_WIDGET,
Make this a addTableFromQuery action

2020-10-14 12:32 UTC, hetunandu commented on app/client/src/actions/widgetActions.tsx
> +  evaluateProperty?: string;
Nothing except the query name should be passed in this payload

2020-10-14 12:32 UTC, hetunandu commented on app/client/src/pages/Editor/QueryEditor/Form.tsx
> +    addWidget(widgetConfig);
Use the useDispatch hook instead of passing this function down from the props

2020-10-14 12:32 UTC, hetunandu commented on app/client/src/pages/Editor/QueryEditor/Form.tsx
> +    addWidget(widgetConfig);
No need to use the useCallback as well.

2020-10-14 12:32 UTC, hetunandu commented on app/client/src/sagas/WidgetOperationSagas.tsx
> +    const {
Why are you passing this from the payload if this is getting calculated here again.

2020-10-14 12:43 UTC, akash-codemonk commented on app/client/src/sagas/WidgetOperationSagas.tsx
> +    const {
The values which are passed are default values. `calculateNewWidgetPosition` expects these values to be passed. 
It expects a widget of type `WidgetProps` which defines that these values are required.

2020-10-15 06:12 UTC, hetunandu commented on app/client/src/sagas/WidgetOperationSagas.tsx
> +  } catch (error) {}
Handle the error over here

2020-10-15 07:06 UTC, hetunandu approved these changes

2020-10-15 07:21 UTC, merged