fix: onSubmit gets triggered before evaluation
appsmithorg/appsmith pull request #11590
Opened 2022-03-03 07:43 UTC by wmdev0808

## Description
- A user reported that quickly hitting enter key in an input widget was submitting only part of the input
- Enforce to update text meta property before trigger the submit action

Fixes #7507 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Test A
- Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-03-03 07:44 UTC, wmdev0808 commented
/ok-to-test sha=f7e3940

2022-03-03 09:02 UTC, sbalaji1192 commented
@wmdev0808
1. Let's add a detailed comment on why we're updating the text property on submit?
2. We need to write a cypress test for this. You have to verify that when enter key is pressed immediately after the text in the input, the action handlers are executed with the updated meta properties.

2022-03-03 12:43 UTC, wmdev0808 commented
/ok-to-test sha=215a076

2022-03-03 21:10 UTC, wmdev0808 commented
/ok-to-test sha=f16ceda

2022-03-07 04:58 UTC, sbalaji1192 commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/Inputv2_spec.js
> +
@wmdev0808 did you run this test case without your fix and see if this is catching the issue?

2022-03-07 04:58 UTC, sbalaji1192 commented on app/client/src/widgets/BaseInputWidget/widget/index.tsx
> +      // In case users quickly type input text followed by hitting enter and using super.executeAction to trigger ON_SUBMIT action, they encounters an issue which they only get part of the input beca
1. Use block comment.
2. Let's use the following comment
```
Originally super.executeAction was used to trigger the ON_SUBMIT action and updateMetaProperty to update the text. Since executeAction is not queued and updateMetaProperty is, the user would observe that the data tree only gets partially updated with text before the ON_SUBMIT would get triggered, if they type {enter} really fast after typing some input text. So we're using updateMetaProperty to trigger the ON_SUBMIT to let the data tree update before we actually execute the action. Since updateMetaProperty expects a meta property to be updated, we are redundantly updating the text here. But the main part is the action execution payload.
```
3. Let's move this to QA. Please sit with QA and explain the whole scenario.

2022-03-07 17:09 UTC, wmdev0808 commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/Inputv2_spec.js
> +
Good point, I will fix, thank you

2022-03-07 17:35 UTC, sbalaji1192 approved these changes
@wmdev0808 Looks good. Please confirm that the cypress test case is catching the issue without your fix. Lets move this to QA.

2022-03-07 17:42 UTC, wmdev0808 commented
> @wmdev0808 Looks good. Please confirm that the cypress test case is catching the issue without your fix. Lets move this to QA.

Yes, I've already confirmed and moved to Needs QA pipeline

2022-03-11 05:26 UTC, YogeshJayaseelan commented
@wmdev0808 Tested this PR and now clicking on submitting immediately shows the complete input text in the toast message and it is working as expected. 

@somangshu @sbalaji1192 @dilippitchika Apart from the original fix observed the following scenario - Clicking on Submit with empty input shows an empty toast message. Is an empty toast message is expected when there is no input text for onSubmit action?

https://www.loom.com/share/0d59e603c4754982a414e90778f19021

2022-03-11 05:39 UTC, dilippitchika commented
Hey @YogeshJayaseelan yes, if the users want to prevent empty submissions they need to write some validation to prevent this. Can you check that as well, that if there's any validation and the criteria is not met then user should not be able to submit.

2022-03-11 09:26 UTC, YogeshJayaseelan commented
@dilippitchika @wmdev0808 I wrote an validation condition which does not meet the criteria and still i could see empty toast message OnSubmit

https://www.loom.com/share/2d32f743646d465bb122d5001bd33f40

2022-03-11 09:35 UTC, sbalaji1192 commented
@YogeshJayaseelan You need to enable the `required` flag.

2022-03-11 10:20 UTC, sbalaji1192 requested changes

2022-03-11 10:20 UTC, sbalaji1192 commented on app/client/src/widgets/BaseInputWidget/widget/index.tsx
> +      this.props.updateWidgetMetaProperty("text", this.props.text, {
@wmdev0808 We have changed this property to `inputText` in inputWidgetV2 recently in a [PR](https://github.com/appsmithorg/appsmith/pull/11579). could also change here?

2022-03-11 10:21 UTC, sbalaji1192 commented on app/client/src/widgets/BaseInputWidget/widget/index.tsx
> +      this.props.updateWidgetMetaProperty("text", this.props.text, {
Please reach out to me before proceeding

2022-03-11 11:15 UTC, dilippitchika commented
@YogeshJayaseelan there is a mistake in the condition, the spelling of length is wrong. I was able to check using this condition - {{Input1.text.length>12}} and we are not able to submit in that case, it's working as expected.

2022-03-11 11:46 UTC, YogeshJayaseelan commented
> @YogeshJayaseelan there is a mistake in the condition, the spelling of length is wrong. I was able to check using this condition - {{Input1.text.length>12}} and we are not able to submit in that case, it's working as expected.

My Bad!!! Yeah after correcting spelling mistakes it is working as expected. Thanks

2022-03-11 12:24 UTC, somangshu commented
@YogeshJayaseelan do we have your sign-off here? Is there anything else from the QA?

2022-03-14 10:40 UTC, sbalaji1192 commented on app/client/src/widgets/BaseInputWidget/widget/index.tsx
> +      this.props.updateWidgetMetaProperty("text", this.props.text, {
@wmdev0808 As discussed, Please use isDirty instead of text here. We want to use a common property across the three inherited widget

2022-03-15 05:28 UTC, YogeshJayaseelan commented
@wmdev0808 Tested this PR and it is working as expected

2022-03-16 14:45 UTC, merged