use changeStream API to check replica set
appsmithorg/appsmith pull request #11613
Opened 2022-03-04 07:43 UTC by khoahuynhdev

## Description

- Use changeStream API from mongoDB driver to check if replica set is enabled
- Create new appsmithctl command `appsmith check-replica-set` or `appsmithctl crs`

Fixes # (issue)
- issue: https://github.com/appsmithorg/appsmith/issues/11418

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How Has This Been Tested?
### How to test

#### admin user with replica set

1. Start Appsmith with docker/docker-compose

#### Non-admin user with replica set

1. Prepare non-admin user (read/write or read-only permission) with replica set enable (using cloud mongo, container image) and EXTERNAL\_URI
2. Run Appsmith with docker/docker-compose
3. Update mongoDB connection string to EXTERNAL\_URI
4. Restart container
    [![66,1,66,1](https://collab.geekup.vn/uploads/images/gallery/2022-03/scaled-1680-/9hyvVm2l2hIFI94O.png)](https://collab.geekup.vn/uploads/images/gallery/2022-03/9hyvVm2l2hIFI94O.png)

#### Non-admin user without replica set

1. Prepare non-admin user(read/write or read-only permission) without replica set enable (using cloud mongo, container image,etc) and EXTERNAL\_URI
2. Run Appsmith with docker/docker-compose
3. Update mongoDB connection string to EXTERNAL\_URI
4. Restart container
    [![76,1,76,1](https://collab.geekup.vn/uploads/images/gallery/2022-03/scaled-1680-/0xuLf65hACO0FUkV.png)](https://collab.geekup.vn/uploads/images/gallery/2022-03/0xuLf65hACO0FUkV.png)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-03-08 09:14 UTC, sharat87 requested changes

2022-03-08 09:14 UTC, sharat87 commented on deploy/docker/entrypoint.sh
> +    if $cmd; then
Is there a reason we are using a `cmd` variable here? Wherever possible, let's avoid variable interpolation without double-quotes. Can we just change this to `if appsmithctl check-replica-set; then` instead?

2022-03-08 09:14 UTC, sharat87 commented on deploy/docker/utils/bin/check_replica_set.js
> +  });
Should we do the `client.close()` call in a `.finally`instead of inside the `.then`? So that if there's an error in the `checkReplicaSet` function, the client is still closed, right?

2022-03-08 09:14 UTC, sharat87 commented on deploy/docker/utils/bin/check_replica_set.js
> +  return new Promise((resolve) => {
I think this will result in an unintentional nested-promise. We likely need an `await` here, like:

```suggestion
  return await new Promise((resolve) => {
```

2022-03-08 09:14 UTC, sharat87 commented on deploy/docker/utils/bin/utils.js
> +  console.log('\tcrs, check_replica_set\t\tcheck replica set mongoDB.\r');
Shouldn't this be `check-replica-set` instead of `check_replica_set`, like the command in the entrypoint.sh script?

2022-03-10 02:55 UTC, geekup-legodevops commented on deploy/docker/utils/bin/utils.js
> +  console.log('\tcrs, check_replica_set\t\tcheck replica set mongoDB.\r');
The commands in the 'appsmithctl' are following the under_score syntax, so i think the check replica set command should follow the same.

2022-03-10 02:57 UTC, geekup-legodevops commented on deploy/docker/utils/bin/utils.js
> +  console.log('\tcrs, check_replica_set\t\tcheck replica set mongoDB.\r');
It's a typo, i will update it

2022-03-10 03:43 UTC, khoahuynhdev commented on deploy/docker/utils/bin/check_replica_set.js
> +  return new Promise((resolve) => {
updated

2022-03-10 03:43 UTC, khoahuynhdev commented on deploy/docker/entrypoint.sh
> +    if $cmd; then
i have changed the condtion as suggested

2022-03-10 03:48 UTC, khoahuynhdev commented on deploy/docker/utils/bin/check_replica_set.js
> +  });
- I have added the `catch` phase to exit 1 when there is an error. 
- The `finally` phase will **always run** after `then` and `catch` phase but we exit the process in the `then` and `catch` so the client won't be closed in the `finally`.

2022-03-10 04:11 UTC, sharat87 requested changes

2022-03-10 04:11 UTC, sharat87 commented on deploy/docker/utils/bin/check_replica_set.js
> +  return new Promise((resolve) => {
I don't see the `await` keyword in the return statement still, do you need to push your local commits perhaps? 🤔

2022-03-10 04:11 UTC, sharat87 commented on deploy/docker/entrypoint.sh
> +    if $(appsmithctl check_replica_set); then
I'm not sure this would work. For this to work, the command `appsmitctl check_replica_set` should _print_ `true` or `false`. But from the implementation it doesn't seem to do that.

Instead the command exits with 0 or 1 status code. To make use of that, this should be written without interpolation, like this:

```suggestion
    if appsmithctl check_replica_set; then
```

2022-03-10 04:28 UTC, geekup-legodevops commented on deploy/docker/utils/bin/check_replica_set.js
> +  return new Promise((resolve) => {
Sorry, my bad. I have updated from the local

2022-03-10 04:30 UTC, geekup-legodevops commented on deploy/docker/entrypoint.sh
> +    if $(appsmithctl check_replica_set); then
thanks for the suggestion. We updated it.

2022-03-10 04:45 UTC, sharat87 approved these changes

2022-03-10 04:46 UTC, merged