fix: 10527 Google Sheet crud generation header issue v2
appsmithorg/appsmith pull request #11664
Opened 2022-03-07 07:07 UTC by leotom2000

## Description
The CRUD operation cannot be performed when there are no rows in the google sheet even though headers are present.
A fix was made so that even if there are no data rows but headers are present, then the button to initiate crud operation is enabled and crud operation can be done. If no rows are found including headers, then button is not enabled.

Fixes #10527

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?
**Manual Tests Done**
| Test Case | Actions | Result | Status |
| --- | -----------| --- | :---: |
| Created a new Sheet through application| Create CRUD interface |Button not enabled |  Pass |
| Above steps + Added headers in row 1| Create CRUD interface | Button enabled |  Pass |
| Above steps +  Moved headers to row 2| Create CRUD interface  | Button NOT enabled |  Pass |
| Above steps +  Changed 'table header Index' in app to 2| Create CRUD interface  | Button enabled |  Pass |
| Above steps +  Added rows to the sheet| Create CRUD interface  | Button enabled |  Pass |
| Manually created empty sheet and created datasource|  Create CRUD interface | Button not enabled |  Pass |
| Above step + Added another sheet Sheet2| Create CRUD interface | Button not enabled |  Pass |
| Above steps + Added header in Sheet1| Create CRUD interface  | Button enabled |  Pass |
| Above steps + Added row in Sheet1| Create CRUD interface  | Button enabled |  Pass |
| Above steps + Changed table header Index' in app to 2 | Create CRUD interface  | Button enabled ** |  Pass |
| Above steps + Selected the Sheet2  | Create CRUD interface  | Button not enabled |  Pass |
| Above steps + Added row in Sheet2 | Create CRUD interface  | Button enabled |  Pass |
| Above steps + Inserted 3 row above headers in Sheet2 | Create CRUD interface  | Button Not enabled |  Pass |
| Above steps + Changed 'table header Index' in app to 4  |Create CRUD interface | Button enabled |  Pass |
** - App created with data as headers

Unit Tests Added
|----|
|com.external.config.GetStructureMethodTest.testTransformResponse_missingJSON_throwsException()|
|com.external.config.GetStructureMethodTest.testTransformResponse_missingValues_returnsEmpty()|
|com.external.config.GetStructureMethodTest.testTransformResponse_singleRowJSON_returnsEmpty()|
|com.external.config.GetStructureMethodTest.testTransformResponse_emptyJSON_returnsEmpty()|
|com.external.config.GetStructureMethodTest.testTransformResponse_emptyStartingRows_toListOfObjects()|
|com.external.config.GetStructureMethodTest.testTransformResponse_emptyRows_returnsIndices()|
|com.external.config.GetStructureMethodTest.transformResponse() |

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>
No changes to code coverage between the base branch and the head branch</details>

2022-03-07 10:03 UTC, nidhi-nair requested changes
Needs some changes to remove redundancies.

2022-03-07 10:03 UTC, nidhi-nair commented on app/server/appsmith-plugins/googleSheetsPlugin/src/test/java/com/external/config/GetStructureMethodTest.java
> +    public void testTransformResponse_emptyJSON_returnsEmpty() throws JsonProcessingException {
This scenario should not return as empty for get structure. We expect to be able to show column headers only.

2022-03-07 10:03 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/DatasourceStructureSolutionCEImpl.java
> +    public Mono<DatasourceStructure> getStructure(String datasourceId, List<Property> pluginSpecifiedTemplates, boolean ignoreCache) {
How are we using the pluginSpecifiedTemplates here?

2022-03-07 10:03 UTC, nidhi-nair commented on app/server/appsmith-plugins/googleSheetsPlugin/src/test/java/com/external/config/GetStructureMethodTest.java
> +    public void transformResponse() throws JsonProcessingException {
Could you please show an example of how get structure is different from get? What format does this response look like?

2022-03-07 13:42 UTC, leotom2000 commented on app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/GetStructureMethod.java
> +        if ("ROWS".equalsIgnoreCase(methodConfig.getQueryFormat())) {
Updated to fetch max by 2 rows
and removed code to fetch range

2022-03-07 17:38 UTC, leotom2000 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/DatasourceStructureSolutionCEImpl.java
> +    public Mono<DatasourceStructure> getStructure(String datasourceId, List<Property> pluginSpecifiedTemplates, boolean ignoreCache) {
This method is not in use, so removed

2022-03-07 19:24 UTC, leotom2000 commented on app/server/appsmith-plugins/googleSheetsPlugin/src/test/java/com/external/config/GetStructureMethodTest.java
> +    public void transformResponse() throws JsonProcessingException {
Removed this test as it is repetitive

2022-03-07 19:40 UTC, leotom2000 commented on app/server/appsmith-plugins/googleSheetsPlugin/src/test/java/com/external/config/GetStructureMethodTest.java
> +    public void testTransformResponse_emptyJSON_returnsEmpty() throws JsonProcessingException {
Updated the method name, this method tests the transposeResponse() specific to getStructure in which functions like WHERE condition, Range consideration are ignored. Test for pulling data from sheets are not included.

2022-03-08 05:22 UTC, nidhi-nair commented on app/server/appsmith-plugins/googleSheetsPlugin/src/test/java/com/external/config/GetStructureMethodTest.java
> +            getStructureMethod.transformResponse(null, null);
Yes I understand the test case, but it should also include the failing scenario. What happens if a refactor of the method fails to throw an error in the current test? It would simply pass through all the code without reporting an error.

2022-03-08 05:23 UTC, nidhi-nair commented on app/server/appsmith-plugins/googleSheetsPlugin/src/test/java/com/external/config/GetStructureMethodTest.java
> +    public void transformResponse() throws JsonProcessingException {
@leotom2000 Could you please also include an example of the end result of this request?

2022-03-08 05:23 UTC, nidhi-nair requested changes
I think we need to change the format of the response for this request. Please provide an example so we can discus over it with more clarity.

2022-03-08 18:21 UTC, leotom2000 commented on app/server/appsmith-plugins/googleSheetsPlugin/src/test/java/com/external/config/GetStructureMethodTest.java
> +            getStructureMethod.transformResponse(null, null);
Yes got it, updated the test case

2022-03-08 18:40 UTC, leotom2000 commented on app/server/appsmith-plugins/googleSheetsPlugin/src/test/java/com/external/config/GetStructureMethodTest.java
> +    public void transformResponse() throws JsonProcessingException {
Added a new Unit Test to evaluate end result derived from the method (testTransformResponse_VerifyEndResult())

2022-03-08 18:51 UTC, leotom2000 commented on app/server/appsmith-plugins/googleSheetsPlugin/src/test/java/com/external/config/GetStructureMethodTest.java
> +    public void transformResponse() throws JsonProcessingException {
Input : 
`{"valueRanges":[{"range":"Sheet1!A1:D1","majorDimension":"ROWS","values":[["Name","Actor","Music","Director"]]},{"range":"Sheet1!A3:D7","majorDimension":"ROWS","values":[["Bean","Sean","Dean","Mean"],["Cow","Dow","Sow","Bow"],["Luke","Make","Duke","Cake"]]}]}`


Output :
`[{"Name":"Bean","Actor":"Sean","Music":"Dean","Director":"Mean","rowIndex":"1"},{"Name":"Cow","Actor":"Dow","Music":"Sow","Director":"Bow","rowIndex":"2"},{"Name":"Luke","Actor":"Make","Music":"Duke","Director":"Cake","rowIndex":"3"}]`

2022-03-08 18:59 UTC, leotom2000 commented
/ok-to-test sha=46b7860

2022-03-09 06:10 UTC, leotom2000 commented
/ok-to-test sha=46b7860

2022-03-15 16:43 UTC, leotom2000 commented on app/server/appsmith-plugins/googleSheetsPlugin/src/test/java/com/external/config/GetStructureMethodTest.java
> +    public void transformResponse() throws JsonProcessingException {
Updated end result to process as one row

2022-03-15 16:51 UTC, leotom2000 commented
/ok-to-test sha=4eb950a

2022-03-15 16:57 UTC, nidhi-nair approved these changes
We'll be working on getStructure again in another PR. This one allows us to fix the generate CRUD bug in a non-breaking way. We'll introduce a few other defaults to be able to use getStructure with this same set of calls in the future.

2022-03-16 04:27 UTC, leotom2000 commented
/ok-to-test sha=4eb950a

2022-03-16 14:50 UTC, merged