fix: 11468 select widget performance on a large data set.
appsmithorg/appsmith pull request #11673
Opened 2022-03-07 08:16 UTC by prsidhu

## Description

- Improvements in initial render time of Select Widget on large data set.
- The original complaint was that in case of large data set, the widget takes up to 5 seconds to render.

Updates -
1. Biggest improvement gained by manually controlling the visibility of the menu list through a state variable. Prevents rendering of each item (total = 1000) on every parent re-render (even when the menu is hidden).
2. Cutting down unnecessary re-renders through memoization of child components and additional checks before calling setState.
3. Initial render is now down to ~100ms once the options are available from the api call.

<img width="1680" alt="Screen Shot 2022-03-07 at 12 54 24 PM" src="https://user-images.githubusercontent.com/5424788/156992050-57b40e6f-c46e-44c8-bd5e-a5b6a95143c2.png">

Fixes # (issue)

https://github.com/appsmithorg/appsmith/issues/11468

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

1. Add a Select Widget to a page. 
5. Fetch options through an api call. Use the following api to get a 1000 item list - ```https://demo7762119.mockable.io/dropdown```.
6. Set default value to the first item [0].
7. Re-load the page and observe that the widget renders in under 100ms after the options are available from the api call. Use React profiler or performance dev tools to observe render times.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-03-07 15:24 UTC, prsidhu commented
/ok-to-test=32f6b46

2022-03-11 10:45 UTC, somangshu commented
@prsidhu please link the issue to the PR, gets easier to track

2022-03-14 06:44 UTC, somangshu commented
@SatishGandham @riodeuno can we accelerate the review here? are we waiting on something?

@prsidhu can you clear the conflicts

2022-03-15 10:38 UTC, riodeuno commented
@prsidhu Is it possible to virtualise the renders so that we can bring down the 700ms number?

2022-03-15 11:32 UTC, riodeuno reviewed
A few queries. The rest looks good. @prsidhu Thanks for working on this, we will see much-needed performance improvements in this component.

2022-03-15 11:32 UTC, riodeuno commented on app/client/src/widgets/SelectWidget/component/index.tsx
> +export default React.memo(SelectComponent);
I was wondering if we can leverage the second argument to `React.memo` to get performance gains?

2022-03-16 06:28 UTC, prsidhu commented
@riodeuno Virtualizing list render has yielded great improvement. Thanks for the suggestion. Will update the PR after ironing our a few kinks

2022-03-17 05:45 UTC, prsidhu commented
@riodeuno @SatishGandham Render performance on first click has improved to ~100ms through virtualisation. 

Due to large number of changes, I will merge in the release after these updates are approved.
<img width="1677" alt="Screen Shot 2022-03-17 at 10 21 47 AM" src="https://user-images.githubusercontent.com/5424788/158744728-2b67bd37-9415-4f42-b097-f8dd1d4592e1.png">

2022-03-17 05:49 UTC, riodeuno commented
@prsidhu This is awesome! Going from 5000ms to 100ms is an extremely huge boost. 
Could you also reply to my comments in the previous review?

2022-03-17 05:50 UTC, prsidhu commented on app/client/src/widgets/SelectWidget/component/index.tsx
> +  return useMemo(
updated. switched React.memo

2022-03-17 06:02 UTC, prsidhu commented on app/client/src/components/ads/Icon.tsx
> +export default React.memo(Icon);
@riodeuno Without passing the equality function, memo does a shallow comparison of all the props which seems to suffice the use case. It has already helped trim down some re-renders.

2022-03-17 06:07 UTC, riodeuno submitted a review, later dismissed
Looks good to me.

2022-03-17 06:09 UTC, riodeuno commented
@prsidhu Please merge with the latest release to resolve conflicts. We can then comment with ok-to-test to run CI workflows.

2022-03-17 06:27 UTC, prsidhu commented
/ok-to-test sha=53c8b18

2022-03-17 09:37 UTC, prsidhu commented
/ok-to-test sha=1a1efc3

2022-03-17 13:07 UTC, prsidhu commented
/ok-to-test sha=b3920ab

2022-03-18 07:34 UTC, prsidhu commented
/ok-to-test sha=13c3ab9

2022-03-21 07:11 UTC, SatishGandham commented on app/client/src/widgets/SelectWidget/component/SelectButton.tsx
> +export const isEmptyOrNill = (value: any) => {
Shouldn't this be in utils?

2022-03-21 07:24 UTC, SatishGandham requested changes
Scrollbar position is off compared to release.
Please check.

2022-03-21 07:57 UTC, prsidhu commented
/ok-to-test sha=1595a7a

2022-03-21 08:03 UTC, prsidhu commented
@SatishGandham addressed your suggestions.

2022-03-22 12:02 UTC, prsidhu commented
/ok-to-test sha=4867327

2022-03-22 16:58 UTC, prsidhu commented
/ok-to-test sha=6d33570

2022-03-23 04:39 UTC, prsidhu commented
/ok-to-test sha=9b5b835

2022-03-23 05:24 UTC, prsidhu commented on app/client/cypress/support/Objects/CommonLocators.ts
> +  _selectOptionValue = (ddOption: string) =>
@SatishGandham this is the only addition to this file. _selectOptionValue

2022-03-23 05:26 UTC, prsidhu commented on app/client/cypress/support/Pages/AggregateHelper.ts
> +    cy.get(locator._selectOptionValue(ddOption)).click({ force: true });
@SatishGandham That locator is used here (replacing _dropDownValue())

2022-03-23 05:33 UTC, SatishGandham submitted a review, later dismissed

2022-03-24 12:42 UTC, prsidhu commented
/ok-to-test sha=19c7786

2022-03-24 12:58 UTC, prsidhu commented
/ok-to-test sha=5b6d762

2022-03-24 19:45 UTC, Aishwarya-U-R commented
/ok-to-test sha=7d0b6b7

2022-03-25 10:43 UTC, prsidhu commented
/ok-to-test sha=63f99fc

2022-03-25 11:15 UTC, prsidhu commented
/ok-to-test sha=74def3b

2022-03-26 11:03 UTC, prsidhu commented
/ok-to-test sha=fb48aca

2022-03-28 05:17 UTC, SatishGandham requested changes

2022-03-28 05:17 UTC, SatishGandham commented on app/client/src/widgets/SelectWidget/component/index.tsx
> +        style={{ height: "auto", maxHeight: 300 }}
1. Check what happens if the select is put in a small container, we may need min-height.
2. This will render whenever parent renders because style is a new object every-time. Since this static, move it out of the component

2022-03-28 05:53 UTC, SatishGandham submitted a review, later dismissed

2022-03-28 06:10 UTC, riodeuno commented on app/client/src/widgets/SelectWidget/component/index.tsx
> +        style={{ height: "auto", maxHeight: 300 }}
We should also make this into an object -- as its properties have static values -- outside the component. as otherwise, there will be new references every time we render this component.

2022-03-28 06:33 UTC, prsidhu commented
/ok-to-test sha=d456df8

2022-03-28 06:44 UTC, riodeuno approved these changes

2022-03-28 09:55 UTC, prsidhu commented
/ok-to-test sha=8734ae0

2022-03-30 08:23 UTC, vivekverma2312 commented
@prsidhu Tested select widget and working fine.

2022-03-30 13:11 UTC, merged