Allow Download File Type dropdown to be deselected
appsmithorg/appsmith pull request #1169
Opened 2020-10-13 10:32 UTC by daniel-shuy

Description
Add a default selection to the Download File Type dropdown so that it can be deselected.

Fixes # (issue)
#674 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2020-10-13 12:18 UTC, Nikhil-Nandagopal commented on app/client/src/components/editorComponents/actioncreator/ActionCreator.tsx
> +  { label: 'Select file type (optional)', value: "", id: "" },
@daniel-shuy, should the value be undefined instead of an empty value?

2020-10-13 12:58 UTC, daniel-shuy commented on app/client/src/components/editorComponents/actioncreator/ActionCreator.tsx
> +  { label: 'Select file type (optional)', value: "", id: "" },
good point, I've changed it to `undefined`. Should I leave `id` as empty string?

2020-10-14 05:35 UTC, Nikhil-Nandagopal commented on app/client/src/components/editorComponents/actioncreator/ActionCreator.tsx
> +  { label: 'Select file type (optional)', value: "", id: "" },
@daniel-shuy yeah id needs to be a valid unique value

2020-10-14 05:40 UTC, Nikhil-Nandagopal commented on app/client/src/components/editorComponents/actioncreator/ActionCreator.tsx
> +  { label: 'Select file type (optional)', value: undefined, id: "" },
@daniel-shuy for some reason this option is always showing selected even when it's not. Might have to have a valid id here or it could be something else

2020-10-14 05:41 UTC, Nikhil-Nandagopal requested changes
Requested changes

2020-10-14 07:20 UTC, daniel-shuy commented on app/client/src/components/editorComponents/actioncreator/ActionCreator.tsx
> +  { label: 'Select file type (optional)', value: undefined, id: "" },
Turns out that was due to the `undefined` `value`, which was causing a compilation error. Changing the `value` back to empty string solves it

2020-10-14 07:35 UTC, daniel-shuy commented on app/client/src/components/editorComponents/actioncreator/ActionCreator.tsx
> +  { label: 'Select file type (optional)', value: undefined, id: "" },
I've dropped the previous commit

2020-10-14 10:05 UTC, Nikhil-Nandagopal commented on app/client/src/components/editorComponents/actioncreator/ActionCreator.tsx
> +  { label: 'Select file type (optional)', value: undefined, id: "" },
Ok this looks good then. Can you check why the tests are failing? Likely pull release into your branch should solve this

2020-10-14 10:11 UTC, daniel-shuy commented on app/client/src/components/editorComponents/actioncreator/ActionCreator.tsx
> +  { label: 'Select file type (optional)', value: undefined, id: "" },
Ironically it started failing after I rebased onto `release`. #1191 should fix it I think.

2020-10-14 10:24 UTC, Nikhil-Nandagopal commented on app/client/src/components/editorComponents/actioncreator/ActionCreator.tsx
> +  { label: 'Select file type (optional)', value: undefined, id: "" },
Yikes! Sorry about that 😅

2020-10-31 14:07 UTC, daniel-shuy commented
Rebased onto `release`, hopefully the tests are fixed

2020-11-03 07:08 UTC, mohanarpit commented
@daniel-shuy I'm really sorry about this but can you please update your branch again with the latest code from `release`? There were some breaking changes introduced in `release` which is probably causing tests to fail on your branch. We've fixed those tests and the CI code as well.

The tests should then pass on this branch.

2020-11-04 14:28 UTC, daniel-shuy commented
@mohanarpit it's passing now, thanks!

2020-11-05 10:17 UTC, Nikhil-Nandagopal approved these changes

2020-11-05 10:17 UTC, merged