fix: Update copy and flag for all toggle buttons on Admin settings page
appsmithorg/appsmith pull request #11703
Opened 2022-03-08 08:02 UTC by ankitakinger

## Description

> Updated the copy and flags for all toggle buttons on the Admin settings page so it is easy to understand on the UI.

Fixes #11702 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Go to the Admin Settings page
- Click on the Authentication tab.
- Click edit for Form Login authentication method.
- Check the default toggle value for Form login should be Enabled and the flag should be on.
- On clicking the toggle and saving the changes, the form login should turn off (provided some other authentication method is enabled).

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-03-08 08:24 UTC, IAmAnubhavSaini requested changes

2022-03-08 08:24 UTC, IAmAnubhavSaini commented on app/client/src/ce/pages/AdminSettings/config/authentication/index.tsx
>        },
This can be one lined: `toggleText: (value: boolean) => value ? "Enabled" : "Disabled",`

2022-03-08 08:24 UTC, IAmAnubhavSaini commented on app/client/src/pages/Settings/FormGroup/Toggle.tsx
> +      ComponentProps.input.onChange && ComponentProps.input.onChange(!value);
Why is param name starting with a capital letter?

2022-03-08 08:24 UTC, IAmAnubhavSaini commented on app/client/src/pages/Settings/config/general.ts
> +          return " Share Anonymous Telemetry";
A space? This should be handled in UI via CSS.

2022-03-09 08:01 UTC, ankitakinger commented
/ok-to-test sha=187a947

2022-03-09 15:04 UTC, ankitakinger commented
/ok-to-test sha=187a947

2022-03-10 09:08 UTC, IAmAnubhavSaini approved these changes

2022-03-10 09:50 UTC, albinAppsmith approved these changes

2022-03-10 10:15 UTC, ankitakinger commented
@RakshaKShetty could you please test the deploy preview for this and give confirmation?

2022-03-11 05:10 UTC, RakshaKShetty commented
Seems good can be merged

2022-03-11 06:21 UTC, ankitakinger commented
/ok-to-test sha=4949e2c

2022-03-11 11:21 UTC, merged