[fix]: where clause improvements
appsmithorg/appsmith pull request #11748
Opened 2022-03-10 04:58 UTC by rashmi-rai

New where clause improvements as per https://www.figma.com/file/Qs7p5frNx7uEfVYpADGk0d/Query-Pane-Improvements?node-id=54%3A4654

## Description

Fixes #9302 

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-03-14 06:21 UTC, rashmi-rai commented
/ok-to-test sha=2635860bebb980e70ea2510414df0fef1275dd59

2022-03-16 08:51 UTC, AmanAgarwal041 approved these changes
LGTM

2022-03-19 08:14 UTC, ayushpahwa commented
<img width="1164" alt="image" src="https://user-images.githubusercontent.com/8526215/159113401-b487c645-d785-459b-8f17-2428f80a541b.png">
Should we need an outer box here?

2022-03-19 08:15 UTC, ayushpahwa commented
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/8526215/159113408-41ca3d08-3bd3-4a3a-9810-dd0a8a712739.png">
This text seems to be wrong here

2022-03-19 08:16 UTC, ayushpahwa commented
<img width="1095" alt="image" src="https://user-images.githubusercontent.com/8526215/159113444-33c14867-bc16-4df0-a0c4-c73a40ba89cc.png">
Just a question here. Should we allow for the first element to be deleted as well?

2022-03-19 08:19 UTC, ayushpahwa requested changes

2022-03-19 08:19 UTC, ayushpahwa commented on app/client/src/components/formControls/WhereClauseControl.tsx
> +          content="For S3 only 4 nested where condition group is allowed"
This should be a dynamic text

2022-03-22 06:04 UTC, rashmi-rai commented on app/client/src/components/formControls/WhereClauseControl.tsx
> +          content="For S3 only 4 nested where condition group is allowed"
We are not supporting using tooltips, labels, etc in composite components right now. This issue should be picked separately.

2022-03-22 06:10 UTC, rashmi-rai commented
> <img alt="image" width="1164" src="https://user-images.githubusercontent.com/8526215/159113401-b487c645-d785-459b-8f17-2428f80a541b.png">
> Should we need an outer box here?

Here we are expecting that user will add a group of conditions, hence the box.

2022-03-22 06:11 UTC, rashmi-rai commented
> <img alt="image" width="1072" src="https://user-images.githubusercontent.com/8526215/159113408-41ca3d08-3bd3-4a3a-9810-dd0a8a712739.png">
> This text seems to be wrong here

What am I missing here?

2022-03-22 06:14 UTC, rashmi-rai commented
> <img alt="image" width="1095" src="https://user-images.githubusercontent.com/8526215/159113444-33c14867-bc16-4df0-a0c4-c73a40ba89cc.png">
> Just a question here. Should we allow for the first element to be deleted as well?

Look at the latest deploy preview and let me know if you still think so.

2022-03-22 06:18 UTC, rashmi-rai commented
/ok-to-test sha=863ea335524c9a80b6e15341d313a673cc75a888

2022-03-22 12:49 UTC, rashmi-rai commented
/ok-to-test sha=0f0d6d01782245fa080d0749a1284b761a71fd0e

2022-03-23 09:23 UTC, AmanAgarwal041 approved these changes

2022-03-23 09:27 UTC, AmanAgarwal041 commented
There are some hard coded css which is present on the specific control components. Those will be solved in the issue #12159 with respect to the ads theming.

2022-03-24 13:32 UTC, rashmi-rai commented
/ok-to-test sha=9f987dba807a7d4c95299eb838e058fec336302c

2022-03-24 19:43 UTC, Aishwarya-U-R commented
/ok-to-test sha=2b9b4cc

2022-03-25 05:17 UTC, rashmi-rai commented
/ok-to-test sha=ba6e41db87e48446119b74757500e89b44270697

2022-03-25 07:15 UTC, rashmi-rai commented
/ok-to-test sha=cf82470a954a6ac777fe0231ce2f0edbbf4e2823

2022-03-25 11:38 UTC, Aishwarya-U-R commented
/ok-to-test sha=55a74b8

2022-03-27 11:47 UTC, rashmi-rai commented
/ok-to-test sha=e06ecf19ad8c4dafbcf6c625663853ee8def9ec6

2022-03-27 13:38 UTC, AmanAgarwal041 approved these changes

2022-03-27 13:40 UTC, merged