fix: Update admin settings permission from users when they are added or re…
appsmithorg/appsmith pull request #11770
Opened 2022-03-10 12:30 UTC by nayan-rafiq

## Description

Update user permission when email address is added as admin email from settings page.

Fixes #11118 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manually

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-03-11 05:46 UTC, sharat87 requested changes
Few changes, but overall looks good.

Are we not handling the case of checking for email in admin list on signup? Will that be a separate PR?

2022-03-11 05:46 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/EnvManagerCEImpl.java
> +        }
Could this be replaced with the `removeAll` method of Java's Set class? Something like:

```
        Set<String> removedUsers = new HashSet<>(oldAdminEmails);
        removedUsers.removeAll(newAdminEmails);
        Set<String> addedUsers = new HashSet<>(newAdminEmails);
        addedUsers.removeAll(oldAdminEmails);
```

2022-03-11 05:46 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/EnvManagerCEImpl.java
> +        }
What happens if the value of `oldAdminEmailsCsv` is just a space, like `" "`? Then the resulting set of emails will contain one string, which is the empty string, `""`. Then we subsequently attempt to find user with this email... which isn't harmless I think, but is there something we can do to avoid? Check out also inputs like `"a@one.com, , , b@two.com"`, which might also screw this up. I think if we use the split regex as `"(\\s*,\\s*)+"` perhaps.

2022-03-11 05:46 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/EnvManagerCEImpl.java
> +         * should be persisted to DB before that
Calling `.subscribe` on them doesn't mean they'll be called immediately. In fact, it's a little closer to the opposite. By calling this, we are telling the Reactive framework, that these can be done a separate thread, so just queue them up. When a thread in bounded thread pool becomes free, then schedule these jobs on those free threads.

To ensure they are finished before the restart, have this method return a `Mono<Void>` or something, and change this to something like:

```java
return Mono.whenDelayError(
        removedUserFlux.then(),
        newUsersFlux.then()
);
```

This will run the two `Flux` chains in parallel, and the returned `Mono` will only emit when _both_ of them are finished.

Now, in the caller of this method, ensure this returned `Mono` is finished before restart. Something like:

```java
updateAdminsMono.then(Mono.delay(Duration.ofSeconds(1))).flatMap(ignored -> restart())
```

2022-03-14 05:36 UTC, nayan-rafiq commented
> separate

Good point. I really missed that. I'll handle the case and update this PR.

2022-03-15 10:36 UTC, nayan-rafiq commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/EnvManagerCEImpl.java
> +                    changes.put(APPSMITH_ADMIN_EMAILS.name(), String.join(",", adminEmails));
@sharat87 We're removing the empty strings, duplicate emails during the validation. We've to do that again when storing the values. For example `b@example.com,,` is a valid input here so we'll end up storing this. As there will not be a lot of emails in this field, I think loosing the order will be ok.

2022-03-15 10:46 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/ValidationUtils.java
> +            "^[\\W]*([\\w+\\-.%]+@[\\w\\-.]+\\.[A-Za-z]+[\\W]*,{1}[\\W]*)*([\\w+\\-.%]+@[\\w\\-.]+\\.[A-Za-z]+)[\\W]*$"
Ah okay. Let's add with a link to that SO answer as well then. If there's improvements on that answer, we have a linkback. 😄

2022-03-15 13:14 UTC, nayan-rafiq commented
@sharat87 Thanks a lot for your valuable review. I've updated the PR as per the points you mentioned. Would you please review it once again?

2022-03-16 10:23 UTC, sharat87 requested changes
Really sorry for going back-and-forth on this, just a couple of super-minor things and we should merge this in. Thanks for your patience man 🙏

2022-03-16 10:23 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/ValidationUtils.java
> +            "^[\\s]*(" + EMAIL_PATTERN + "[\\s]*,[\\s]*)*(" + EMAIL_PATTERN + ")[\\s]*$"
Isn't `[\\s]` the same as just `\\s` here? 🤔

2022-03-16 10:23 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/TextUtils.java
> +//        return stringSet;
Can we remove commented code please?

2022-03-16 10:41 UTC, nayan-rafiq commented on app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/ValidationUtils.java
> +            "^[\\s]*(" + EMAIL_PATTERN + "[\\s]*,[\\s]*)*(" + EMAIL_PATTERN + ")[\\s]*$"
Yeah, it's the same. Let me remove the extra square brackets. Thanks a lot man for pointing this out.

2022-03-16 10:43 UTC, nayan-rafiq commented
@sharat87 Thanks a lot for your time and patience. The PR has improved a lot for your great observations. Would you please have a look once again?

2022-03-21 11:57 UTC, sharat87 approved these changes

2022-03-24 12:13 UTC, nayan-rafiq commented
/ok-to-test sha=9b3c1c40537513997763c1c923f19491211c5c56

2022-03-31 14:17 UTC, merged