fix: Button group widget's pop-over/drop-down enlarged along the width
appsmithorg/appsmith pull request #11804
Opened 2022-03-11 10:37 UTC by wmdev0808

## Description

- When we turn the button inside a button group widget into a menu type, then the pop-over/dropdown of that menu button has an enlarged width.
- Make the popover width to be the same as the target width

Fixes #11564 

## Type of change

- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How Has This Been Tested?

- Test A
- Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-03-11 10:37 UTC, wmdev0808 commented
/ok-to-test sha=e3e7aba

2022-03-14 13:33 UTC, wmdev0808 commented
/ok-to-test sha=941ab6f

2022-03-15 23:50 UTC, wmdev0808 commented
/ok-to-test sha=b93fe01

2022-03-16 08:43 UTC, somangshu commented
@jsartisan please check this code out

2022-03-17 10:39 UTC, jsartisan commented
The solution can be improved. We need to have min-width for the dropdown

![image](https://user-images.githubusercontent.com/6636360/158791862-1825f17c-d73f-43f1-b9d6-a0a18483985b.png)

2022-03-17 10:42 UTC, jsartisan commented
Just checked the issue. this issue can be solved with just CSS. We can use a combination of min-width and max-width.

2022-03-17 17:13 UTC, wmdev0808 commented
/ok-to-test sha=cda649d

2022-03-18 04:34 UTC, dilippitchika submitted a review, later dismissed

2022-03-18 05:01 UTC, dilippitchika commented
![Screenshot 2022-03-18 at 10 30 08 AM](https://user-imag@wmdev0808 githubusercontent.com/19730984/158940503-fc4d043b-0869-41c3-98fe-cf5f87212a05.png)

@wmdev0808 there is a small misalignment between the pop-over and the button, happening when I see this in the view mode. Can you please check this?

2022-03-18 09:14 UTC, wmdev0808 commented
/ok-to-test sha=9110f40

2022-03-18 09:39 UTC, Tooluloope requested changes

2022-03-22 15:21 UTC, wmdev0808 commented
/ok-to-test sha=5a58f15

2022-03-23 07:30 UTC, Tooluloope requested changes
LGTM

2022-03-23 07:30 UTC, Tooluloope commented on app/client/src/widgets/ButtonGroupWidget/component/index.tsx
> +  const buttonData = Object.keys(groupButtons).reduce((acc: any[], id) => {
Could we avoid the use of `any`
```
const getButtonData = (
  groupButtons: Record<string, GroupButtonProps>,
): ButtonData[] => {
  return Object.keys(groupButtons).reduce((acc: ButtonData[], id) => {
    return [
      ...acc,
      {
        id,
        type: groupButtons[id].buttonType as string,
        label: groupButtons[id].label as string,
        iconName: groupButtons[id].iconName as string,
      },
    ];
  }, []);
};
```

2022-03-23 07:30 UTC, Tooluloope commented on app/client/src/widgets/ButtonGroupWidget/component/index.tsx
> +          }, {}),
Could you refactor this into a function, it's similar with the function in Line 483

2022-03-23 07:30 UTC, Tooluloope commented on app/client/src/widgets/ButtonGroupWidget/component/index.tsx
> +            }, {}),
Also, this is similar with the reduce function in line 434

2022-03-23 08:15 UTC, wmdev0808 commented
/ok-to-test sha=10e19f8

2022-03-23 08:16 UTC, Tooluloope approved these changes

2022-03-23 09:45 UTC, shwetha-ramesh commented
@wmdev0808 tested this dp. 
As per the comments the agreed design would be "Make the popover width to be the same as the target width"
But when a button group widget is dropped on a canvas the drop down is not same as the button 
![image](https://user-images.githubusercontent.com/92293815/159670442-bbdc310e-0ca3-4534-81f3-4dd5399bfded.png)
https://loom.com/share/db4e6825306f4e369e7395b1619bd034

2022-03-23 09:50 UTC, dilippitchika commented
@shwetha-ramesh we have added a minimum width on this so that the dropdown doesn't become too small. It follows the similar behavior as the menu button widget.

2022-03-24 06:57 UTC, shwetha-ramesh commented
@wmdev0808 as discussed please find the below video and steps to reproduce the issue when
1. Drag and drop button group widget  on fluid width canvas > Change the orientation to VERTICAL > Check the drop down
2. Now change the canvas size to Mobile device > D&D button group widget > Check drop down > Now verify first button group widget drop down.

https://loom.com/share/3f9ef89253be41f0bb1d7e3d5720046b

2022-03-24 08:16 UTC, wmdev0808 commented
/ok-to-test sha=224543c

2022-03-24 10:38 UTC, shwetha-ramesh commented
@wmdev0808 re-tested this DP after fix. Working as expected.

2022-03-24 22:08 UTC, wmdev0808 commented
/ok-to-test sha=0152298

2022-03-25 06:41 UTC, wmdev0808 commented
/ok-to-test sha=cec0315

2022-03-25 07:38 UTC, Aishwarya-U-R commented
/ok-to-test sha=cec0315

2022-03-25 09:35 UTC, wmdev0808 commented
/ok-to-test sha=c37aed0

2022-03-26 10:55 UTC, Tooluloope approved these changes

2022-03-28 07:14 UTC, merged