fix: 10771 show text widget warning on exceeding line breaks limit
appsmithorg/appsmith pull request #11812
Opened 2022-03-12 05:50 UTC by prsidhu

## Description

Case: Attempting to render a large json object in a TextWidget. Currently, it makes the app unresponsive due large number of line breaks.
Fix: If line breaks > 5000; then render the text without line breaks and show a warning to the user about the same.

Fixes # (issue)

https://github.com/appsmithorg/appsmith/issues/10771

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

1. Add a text widget to your app.
2. Fetch data for the text widget using this api: ```https://restcountries.com/v3.1/all```.
3. Observe that the text is rendered without line breaks and that user is shown an appropriate warning in the property pane. (See image attached)

<img width="1680" alt="Screen Shot 2022-03-11 at 8 07 11 PM" src="https://user-images.githubusercontent.com/5424788/158005791-aa015ebd-8a2d-47e7-acb5-e2c5673865e2.png">
<img width="1680" alt="Screen Shot 2022-03-12 at 11 17 44 AM" src="https://user-images.githubusercontent.com/5424788/158005796-bc9e5ef2-6e2b-4f2c-9dcb-e2d99c2f8e19.png">

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-03-12 06:05 UTC, prsidhu commented
/ok-to-test sha=d5a59d4

2022-03-14 05:19 UTC, somangshu commented
@dilippitchika can you check this as well? the DP I mean!

2022-03-21 07:38 UTC, prsidhu commented
cc: @rohitagarwal88

2022-03-21 08:54 UTC, SatishGandham commented on app/client/src/workers/validations.ts
> +              `Warning: Line breaks in text exceed ${MAX_ALLOWED_LINE_BREAKS}. Text will be visible without line breaks.`,
Can we say number of lines instead of line breaks? Line breaks feels too technical, and the user is not putting these line breaks.

@somangshu, @dilippitchika  thoughts?

2022-03-21 08:56 UTC, SatishGandham commented on app/client/src/workers/validations.ts
> +          return {
@riodeuno Is returning isValid false for valid value the right thing to do?
Any better way to do it? Is it going to break anything?

Also, should we start supporting warnings along with errors at the platform level?

2022-03-21 09:04 UTC, SatishGandham requested changes

2022-03-21 09:04 UTC, SatishGandham commented on app/client/src/workers/validations.ts
> +          parsed.match(/[^\n]*\n[^\n]*/gi)?.length || 0;
@prsidhu Since validations run several times on the editor, can you explore a faster alternate provided here
https://stackoverflow.com/questions/4009756/how-to-count-string-occurrence-in-string

@riodeuno , Do all the validations run in every eval cycle, or only for the changed paths and the ones dependent on it?

2022-03-21 09:33 UTC, riodeuno commented on app/client/src/workers/validations.ts
> +          parsed.match(/[^\n]*\n[^\n]*/gi)?.length || 0;
According to this [line of code](https://github.com/appsmithorg/appsmith/blob/aef4001fdeb676e1444dc71df290db7804fa1b30/app/client/src/workers/DataTreeEvaluator.ts#L663), it happens only if it belongs to the subtree which has been re-computed.

2022-03-21 09:41 UTC, riodeuno commented on app/client/src/workers/validations.ts
> +          return {
@SatishGandham As far as the property is concerned, a value can be valid or invalid. If we consider a string with more than MAX_ALLOWED_LINE_BREAKS,  a value that we cannot safely work with, then I would say it is an invalid value.

I was wondering about this scenario -- Is it possible for users to resolve the issue, or does the page freeze when we have more than the MAX_ALLOWED_LINE_BREAKS? If it freezes, then we can consider this an `invalid` value, and replace it with defaults during validation. If not, then we can "warn" the user -- 

We have been doing something akin to warnings so far, in some validations, we flag them as `isValid: false` however, we simply pass through the original value to the widget, without resorting to defaults. This is a case, where we do inform the user that there is something wrong with the value, but we don't modify or intercept the value itself.

2022-03-21 09:56 UTC, SatishGandham commented on app/client/src/workers/validations.ts
> +          return {
@riodeuno , The page doesn't freeze, we format the text to not include line breaks when the line breaks are beyond the threshold.
This will be a warning.

2022-03-21 10:09 UTC, prsidhu commented on app/client/src/workers/validations.ts
> +      let parsed: string = JSON.stringify(value, null, 2);
@SatishGandham I'll add this as a part of the validation at the end. However, I'm unsure about preserving 2k line breaks; it'll make for an odd user experience. @dilippitchika thoughts?

2022-03-22 05:09 UTC, dilippitchika commented on app/client/src/workers/validations.ts
> +              `Warning: Line breaks in text exceed ${MAX_ALLOWED_LINE_BREAKS}. Text will be visible without line breaks.`,
@SatishGandham can we use line breaks and number of lines interchangeably here? if so then yes we can update it.

2022-03-22 05:14 UTC, dilippitchika commented on app/client/src/workers/validations.ts
> +      let parsed: string = JSON.stringify(value, null, 2);
Agreed with Preet, it's a weird experience to have 2k line breaks in a way and the rest in another way.

2022-03-22 05:20 UTC, dilippitchika commented
Note to self on this, need to update the text widget documentation to help users render these with line-breaks in an iframe widget's srcDoc property with the following code. Adding this as a snippet will also help - 

```
{{
`<pre><code>
${JSON.stringify(GetCountries.data, undefined, 2)}
</code></pre>`
}}
```

2022-03-22 05:35 UTC, dilippitchika commented on app/client/src/workers/validations.ts
> +              `Warning: Line breaks in text exceed ${MAX_ALLOWED_LINE_BREAKS}. Text will be visible without line breaks.`,
@prsidhu @SatishGandham does this error message work better? - 
"New lines in the text exceed X. The text displayed will not contain any new lines."

2022-03-22 06:10 UTC, prsidhu commented
/ok-to-test sha=29fca66

2022-03-22 12:05 UTC, prsidhu commented
/ok-to-test sha=d8afae2

2022-03-22 13:07 UTC, prsidhu commented
/ok-to-test sha=64dfaf1

2022-03-22 13:34 UTC, SatishGandham approved these changes
LGTM

2022-03-23 09:52 UTC, prsidhu commented
/ok-to-test sha=bbb4a9f

2022-03-24 13:24 UTC, chandannkumar commented
Tested this PR and working as expected

2022-03-25 10:35 UTC, prsidhu commented
/ok-to-test sha=7b8a950

2022-03-28 04:53 UTC, prsidhu commented
/ok-to-test sha=88e326d

2022-03-28 09:54 UTC, prsidhu commented
/ok-to-test sha=7382159

2022-03-30 13:10 UTC, merged