Fix/onclick linting issue
appsmithorg/appsmith pull request #11875
Opened 2022-03-15 11:40 UTC by eco-monk

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.

## Description

> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change.

Fixes # (issue)

> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-03-30 11:14 UTC, eco-monk commented
/ok-to-test sha=cb8c2af

2022-03-30 12:24 UTC, sbalaji1192 reviewed
@riodeuno Could you have a look once?

2022-03-30 12:24 UTC, sbalaji1192 commented on app/client/src/widgets/BaseWidget.tsx
> +  static getLoadingProperties(): Array<RegExp> | undefined {
Could you add comment about the purpose of this `getLoadingProperties` ?

2022-03-30 12:24 UTC, sbalaji1192 commented on app/client/src/utils/WidgetLoadingStateUtils.test.ts
> +          loadingPropertiesMap.get(widgetType),
can we simply return `[/.tableData$/]` ?

2022-03-30 13:13 UTC, eco-monk commented on app/client/src/widgets/TableWidget/widget/index.tsx
> +    return [/.tableData$/];
Discussing in the above thread.

2022-03-30 13:17 UTC, eco-monk commented on app/client/src/utils/WidgetLoadingStateUtils.test.ts
> +          loadingPropertiesMap.get(widgetType),
This has to be returned only when called for a TABLE_WIDGET. 
Other test cases (e.g. SELECT_WIDGET cases) would fail, if we return tableData by default

2022-03-30 17:58 UTC, sbalaji1192 commented on app/client/src/utils/WidgetLoadingStateUtils.test.ts
> +          loadingPropertiesMap.get(widgetType),
oh yeah.  you're correct.

2022-03-31 07:02 UTC, eco-monk commented on app/client/src/widgets/BaseWidget.tsx
> +  static getLoadingProperties(): Array<RegExp> | undefined {
@sbalaji1192 
updated with comments, please check if it is appropriate.

2022-03-31 07:04 UTC, eco-monk commented
/ok-to-test sha=f02aaef

2022-03-31 07:32 UTC, ohansFavour requested changes

2022-03-31 07:32 UTC, ohansFavour commented on app/client/src/workers/DataTreeEvaluator.ts
> +        dynamicTriggerPathlist.forEach((dynamicPath) => {
This logic (lines 525 - 534) seems to be repeated in two other places (see 569 - 580 and 584-599). can we compose this into a helper function?  and add a test?

2022-03-31 10:15 UTC, sbalaji1192 approved these changes

2022-03-31 11:19 UTC, ohansFavour approved these changes

2022-03-31 11:36 UTC, eco-monk commented on app/client/src/workers/DataTreeEvaluator.ts
> +        dynamicTriggerPathlist.forEach((dynamicPath) => {
Discussed, the functions behave slightly differently.

2022-03-31 11:37 UTC, merged