fix: Embedded MongoDB not removed immediately when changing the MongoDB URI
appsmithorg/appsmith pull request #11894
Opened 2022-03-16 09:00 UTC by geekup-legodevops

## Description

- The script will check for APPSMITH_MONGODB_URI for **internal/external** and **enable/disable** supervisor config accordingly.
- Restart the related services including `backend, editor, rts`
![Flow](https://user-images.githubusercontent.com/72587752/158553135-3a6571b5-775b-4fdc-8ad6-8c69b4902632.png)

Fixes # (issue)
- [[Bug]: Embedded MongoDB not removed immediately when changing the MongoDB URI](https://github.com/appsmithorg/appsmith/issues/9967)

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Have appsmith-ce running
- Update `APPSMITH_MONGODB_URI` ( using external src)
- Call `supervisor-mongodb.sh` script
- Check supervisord status.
## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-03-16 09:28 UTC, sharat87 requested changes
Please rename the script to something that illustrates the purpose of the script. Something like `update-supervisor-and-restart.sh`.

2022-03-16 09:28 UTC, sharat87 commented on deploy/docker/scripts/supervisor-mongodb.sh
> +    ls | grep -i mongodb | sed -e "p;s/\.disable/\.conf/" | xargs -n2 mv
If local MongoDB was disabled originally, and then enabled, there would be no file called `mongodb.conf.disabled`. Please refer to the entrypoint script. If an external MongoDB is configured, we don't copy the `mongodb.conf` _at all_.

Can we instead remove the file when disabled, and copy it from the original source when it's enabled? Just like in the entrypoint script please?

2022-03-16 09:28 UTC, sharat87 commented on deploy/docker/scripts/supervisor-mongodb.sh
> +set -e
Let's enable xtrace so we get logs of what's happening when this script is run.

```suggestion
set -e
set -o xtrace
```

2022-03-16 09:28 UTC, sharat87 commented on deploy/docker/scripts/supervisor-mongodb.sh
> +supervisorctl restart backend editor rts
The update command will immediately terminate the MongoDB process, leaving the backend server and RTS starting to throw errors. Can we restart those first, so they can connect to the external MongoDB, and then do a `supervisorctl update`?

```suggestion
supervisorctl restart backend editor rts
supervisorctl update
```

2022-03-16 09:28 UTC, sharat87 commented on deploy/docker/scripts/supervisor-mongodb.sh
> +update_supervisord_mongodb_conf
Can we also fix the same problem for Redis as well please?

2022-03-17 07:36 UTC, khoahuynhdev commented on deploy/docker/scripts/supervisor-mongodb.sh
> +set -e
i have updated this.

2022-03-17 07:36 UTC, khoahuynhdev commented on deploy/docker/scripts/supervisor-mongodb.sh
> +update_supervisord_mongodb_conf
We do the check for local redis and update supervisor config as well

2022-03-17 07:37 UTC, khoahuynhdev commented on deploy/docker/scripts/supervisor-mongodb.sh
> +supervisorctl restart backend editor rts
i have updated this.

2022-03-17 07:57 UTC, geekup-legodevops commented on deploy/docker/scripts/supervisor-mongodb.sh
> +    ls | grep -i mongodb | sed -e "p;s/\.disable/\.conf/" | xargs -n2 mv
we have updated following the logic in `entrypoint` file

2022-03-17 07:58 UTC, geekup-legodevops commented on deploy/docker/scripts/supervisor-mongodb.sh
> +update_supervisord_mongodb_conf
we have updated logic to check and update for redis as well

2022-03-17 12:10 UTC, sharat87 approved these changes

2022-03-17 12:28 UTC, merged