fix: Design QA changes & form login removed from signup screen if disabled
appsmithorg/appsmith pull request #11958
Opened 2022-03-18 06:14 UTC by ankitakinger

## Description

> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change.

Fixes #11956 

## Type of change

- Bugfix (non-breaking change which fixes an issue)
- Update UI

## How Has This Been Tested?

- Tested UI on Admin settings page
- Tested if form login is hidden if the toggle for the same is off

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-03-18 06:20 UTC, albinAppsmith commented on app/client/src/ce/pages/AdminSettings/config/authentication/AuthPage.tsx
> +                        <Icon fillColor="#03B365" name="oval-check" />
use colors from colors constant

2022-03-18 06:46 UTC, ankitakinger commented on app/client/src/ce/pages/AdminSettings/config/authentication/AuthPage.tsx
> +                        <Icon fillColor="#03B365" name="oval-check" />
done

2022-03-18 06:49 UTC, albinAppsmith approved these changes

2022-03-18 06:50 UTC, ankitakinger commented
/ok-to-test sha=9e2a44e

2022-03-18 08:33 UTC, ankitakinger commented
@RakshaKShetty could you please test this change out once before I merge it?

2022-03-20 06:04 UTC, IAmAnubhavSaini requested changes

2022-03-20 06:04 UTC, IAmAnubhavSaini commented on app/client/src/pages/Settings/FormGroup/Common.tsx
> +export const StyledLabel = styled.label<{ isLabel?: string }>`
The name of the component is already `StyledLabel`, passing a param named `isLabel` doesn't make sense here.

`display: none` will remove the element from the DOM tree, are you sure you want to do that?

If you do want to remove the element from the DOM tree, you can use `isLabel && <StyledLabel...>`, so that when `setting.label` (below) is `false` then it won't render `StyledLabel`.

2022-03-21 05:29 UTC, ankitakinger commented on app/client/src/ce/constants/messages.ts
> +  "You can try refreshing the page for the settings to take place.";
- If the server is not restarted, then even refreshing the page won't work. Hence the word "try".
- Also, this is just a temporary change. We are working on a new plan for this to probably show a page instead of a modal. This is just updating the error message because contact your administrator is incorrect here.

2022-03-21 05:30 UTC, ankitakinger commented on app/client/src/ce/pages/AdminSettings/config/authentication/AuthPage.tsx
> +                        content={`${method.label} authentication method is enabled`}
Haven't added it as this will not be used in any other component

2022-03-21 05:49 UTC, ankitakinger commented on app/client/src/components/ads/formFields/UneditableField.tsx
> +    right: -24px;
Nope. This component was created by me a few days back and it is only being used in one place.

2022-03-21 06:04 UTC, IAmAnubhavSaini commented on app/client/src/ce/pages/AdminSettings/config/authentication/AuthPage.tsx
> +                        content={`${method.label} authentication method is enabled`}
Still. Keeping all strings in one place is a good thing.

2022-03-21 06:07 UTC, IAmAnubhavSaini commented on app/client/src/ce/constants/messages.ts
> +  "You can try refreshing the page for the settings to take place.";
It needs work. Could you talk to @hiteshjoshi and @vuiets about this string?

2022-03-21 07:56 UTC, ankitakinger commented on app/client/src/pages/Settings/FormGroup/Common.tsx
> +export const StyledLabel = styled.label<{ isLabel?: string }>`
done

2022-03-21 07:57 UTC, ankitakinger commented on app/client/src/ce/pages/UserAuth/SignUp.tsx
> +          }}
done

2022-03-21 07:57 UTC, ankitakinger commented on app/client/src/ce/pages/AdminSettings/config/authentication/AuthPage.tsx
> +                        content={`${method.label} authentication method is enabled`}
done

2022-03-21 07:57 UTC, ankitakinger commented on app/client/src/ce/pages/UserAuth/SignUp.tsx
> +              disabled={pristine || !isFormValid}
done

2022-03-21 09:00 UTC, ankitakinger commented on app/client/src/ce/constants/messages.ts
> +  "You can try refreshing the page for the settings to take place.";
Will make this change in a separate PR along with other changes as per Joy's design. Hence, reverted this change here completely.

2022-03-21 09:08 UTC, IAmAnubhavSaini commented on app/client/src/sagas/SuperUserSagas.tsx
> +const RESTART_POLL_TIMEOUT = 120000;
This can be done later, whenever writing time down, break it in factors like: `2 * 60 * 1000`. This conveys two minutes in milliseconds faster and cleanly.

2022-03-21 09:08 UTC, IAmAnubhavSaini commented on app/client/src/pages/Settings/DisconnectService.tsx
> +        text={warnDisconnectAuth ? "Are you sure?" : "Disconnect"}
These strings could be moved to messages.ts

2022-03-21 09:08 UTC, IAmAnubhavSaini approved these changes

2022-03-21 09:25 UTC, ankitakinger commented
/ok-to-test sha=b244111

2022-03-22 05:51 UTC, ankitakinger commented on app/client/src/pages/Settings/DisconnectService.tsx
> +        text={warnDisconnectAuth ? "Are you sure?" : "Disconnect"}
done

2022-03-22 05:51 UTC, ankitakinger commented on app/client/src/sagas/SuperUserSagas.tsx
> +const RESTART_POLL_TIMEOUT = 120000;
done

2022-03-22 06:29 UTC, albinAppsmith approved these changes

2022-03-22 12:30 UTC, ankitakinger commented
/ok-to-test sha=6f5cc77

2022-03-23 07:55 UTC, albinAppsmith commented
/ok-to-test sha=6f5cc77

2022-03-23 14:26 UTC, RakshaKShetty commented
1.Tested UI on Admin settings page->Done ->The space issues has been resolved here->The tooltip is added in the authentication tab when user hover on tick mark icon 
2.Tested if form login is hidden if the toggle for the same is off->the form login is hidden
3.Tested verification is done before disconnecting an Authentication method->Works it asks for double confirmation now and gets disconnected

2022-03-24 07:05 UTC, merged