fix: commit bottom bar's tooltip and impoart app modal of not git import feature
appsmithorg/appsmith pull request #11975
Opened 2022-03-18 10:05 UTC by haojin111

## Description

> Updated tooltip of "commit" in the bottom bar as "Commit" from "Commit Changes"
> Without gitimport feature, import from file picker is fulfilled over import application modal.

Fixes #11558 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Manual test

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-03-20 08:35 UTC, IAmAnubhavSaini requested changes

2022-03-20 08:35 UTC, IAmAnubhavSaini commented on app/client/src/pages/Applications/ImportApplicationModal.tsx
> +  width: ${(props) => (props.gitEnabled ? "320px" : "100%")};
This is not we agreed upon. Hide the GitImportCard when git is not enabled.

2022-03-22 08:35 UTC, haojin111 commented on app/client/src/pages/Applications/ImportApplicationModal.tsx
> +  width: ${(props) => (props.gitEnabled ? "320px" : "100%")};
yes, when we hide git import card, file import card should be full width.

2022-03-23 05:26 UTC, IAmAnubhavSaini approved these changes

2022-03-23 05:54 UTC, IAmAnubhavSaini requested changes

2022-03-23 05:54 UTC, IAmAnubhavSaini commented on app/client/src/ce/constants/messages.test.ts
> +    { key: "COMMIT_CHANGES", value: "Commit" },
Not required. Design has changed again to "Commit N changes" which I am working on. You have to revert this change.

2022-03-23 05:54 UTC, IAmAnubhavSaini commented on app/client/src/ce/constants/messages.ts
> +export const COMMIT_CHANGES = () => "Commit";
Not required. Design has changed again to "Commit N changes" which I am working on. You have to revert this change.

2022-03-23 05:58 UTC, IAmAnubhavSaini approved these changes

2022-03-23 08:29 UTC, AnaghHegde commented
/ok-to-test sha=a9f0ded

2022-03-23 08:32 UTC, AnaghHegde commented
/ok-to-test sha=4915a7d

2022-03-23 11:14 UTC, IAmAnubhavSaini commented
/ok-to-test sha=e4b22fc

2022-03-23 11:20 UTC, RakshaKShetty commented
Import modal looks as below. Its fine for now 
<img width="724" alt="image" src="https://user-images.githubusercontent.com/45958978/159688148-af40240e-0331-4995-88d5-6380b03989c4.png">

2022-03-23 11:20 UTC, IAmAnubhavSaini submitted a review, later dismissed

2022-03-23 12:36 UTC, IAmAnubhavSaini commented
@haojin111  failing cypress test

```

────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  Smoke_TestSuite/ClientSideTests/GitSync/Git_spec.js                           (9 of 269)
  Estimated: 4 minutes, 32 seconds


  Git sync:
    ✓ shows remote is ahead warning and conflict error during commit and push (100944ms)
    ✓ detect conflicts when merging head to base branch (43309ms)
    ✓ supports merging head to base branch (16994ms)
    ✓ enables pulling remote changes from bottom bar (49465ms)
    1) "after all" hook for "clicking '+' icon on bottom bar should open deploy popup"


  4 passing (4m)
  1 failing

  1) Git sync:
       "after all" hook for "clicking '+' icon on bottom bar should open deploy popup":
     CypressError: Timed out retrying after 20000ms: `cy.type()` failed because this element:

`<div class="bp3-editable-text bp3-disabled t--application-name editable-application-name max-w-48">...</div>`

is being covered by another element:

`<div class="bp3-overlay-backdrop bp3-overlay-appear-done bp3-overlay-enter-done" tabindex="0"></div>`

Fix this problem, or use {force: true} to disable error checking.

https://on.cypress.io/element-cannot-be-interacted-with

Because this error occurred during a `after all` hook we are skipping the remaining tests in the current suite: `Git sync:`

Although you have test retries enabled, we do not retry tests when `before all` or `after all` hooks fail
      at $Cy.ensureDescendents (https://dev.appsmith.com/__cypress/runner/cypress_runner.js:160723:87)
      at ensureDescendents (https://dev.appsmith.com/__cypress/runner/cypress_runner.js:147550:8)
      at ensureDescendentsAndScroll (https://dev.appsmith.com/__cypress/runner/cypress_runner.js:147557:14)
      at ensureElIsNotCovered (https://dev.appsmith.com/__cypress/runner/cypress_runner.js:147691:5)
      at runAllChecks (https://dev.appsmith.com/__cypress/runner/cypress_runner.js:147878:52)
      at retryActionability (https://dev.appsmith.com/__cypress/runner/cypress_runner.js:147901:16)
      at tryCatcher (https://dev.appsmith.com/__cypress/runner/cypress_runner.js:13212:23)
      at Function.Promise.attempt.Promise.try (https://dev.appsmith.com/__cypress/runner/cypress_runner.js:10486:29)
      at tryFn (https://dev.appsmith.com/__cypress/runner/cypress_runner.js:165383:61)
      at whenStable (https://dev.appsmith.com/__cypress/runner/cypress_runner.js:165422:14)
      at https://dev.appsmith.com/__cypress/runner/cypress_runner.js:164909:18
      at tryCatcher (https://dev.appsmith.com/__cypress/runner/cypress_runner.js:13212:23)
      at Promise._settlePromiseFromHandler (https://dev.appsmith.com/__cypress/runner/cypress_runner.js:11147:31)
      at Promise._settlePromise (https://dev.appsmith.com/__cypress/runner/cypress_runner.js:11204:18)
      at Promise._settlePromise0 (https://dev.appsmith.com/__cypress/runner/cypress_runner.js:11249:10)
      at Promise._settlePromises (https://dev.appsmith.com/__cypress/runner/cypress_runner.js:11329:18)
  From Your Spec Code:
      at Context.eval (https://dev.appsmith.com/__cypress/tests?p=cypress/integration/Smoke_TestSuite/ClientSideTests/GitSync/Git_spec.js:289:47)



[mochawesome] Report HTML saved to /home/runner/work/appsmith/appsmith/app/client/results/mochawesome_001.html


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        5                                                                                │
  │ Passing:      4                                                                                │
  │ Failing:      1                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  1                                                                                │
  │ Video:        true                                                                             │
  │ Duration:     3 minutes, 55 seconds                                                            │
  │ Estimated:    4 minutes, 32 seconds                                                            │
  │ Spec Ran:     Smoke_TestSuite/ClientSideTests/GitSync/Git_spec.js                              │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘

```

![Screenshot 2022-03-23 at 6 05 46 PM](https://user-images.githubusercontent.com/1573771/159700685-d54955f2-be36-4e12-a15a-5c76bb9b9fbd.png)

2022-03-25 08:11 UTC, IAmAnubhavSaini requested changes
![Screenshot 2022-03-25 at 1 39 07 PM](https://user-images.githubusercontent.com/1573771/160080794-7348e5b9-68cc-45f4-aec0-d1e91a68bece.png)

2022-03-25 08:28 UTC, IAmAnubhavSaini approved these changes
Fixed merge issues.

2022-03-25 08:36 UTC, IAmAnubhavSaini commented
/ok-to-test sha=cfcf292

2022-03-26 06:47 UTC, haojin111 commented
/ok-to-test sha=8f5f231

2022-03-26 15:33 UTC, merged