fix: Fixed Icon Button onClick in disabled state.
appsmithorg/appsmith pull request #11973
Opened 2022-03-18 09:36 UTC by yaldram

## Description

- Icon Button `onClick` was working when `isDisable: true`.
- Button Disabled textstyles were breaking in release, fixed it.

Fixes #11957

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Tested Manually on the Canvas.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-03-18 09:45 UTC, dilippitchika approved these changes

2022-03-18 09:45 UTC, dilippitchika commented
@yaldram can you also add some test-cases to prevent this from happening again?

2022-03-18 11:02 UTC, yaldram commented
Hey @ashit-rath for more context on the `ButtonContainer` please check this Pull Request - https://github.com/appsmithorg/appsmith/pull/11627

2022-03-18 11:02 UTC, yaldram commented
Hey @ashit-rath for more context on the `ButtonContainer` please check this Pull Request - https://github.com/appsmithorg/appsmith/pull/11627

2022-03-18 12:41 UTC, ashit-rath requested changes
Few callouts:

1. Can you add some cypress test for the icon button disabled state?

2. Please do make a list of places the QA should expect the color to get fixed (I think it's 5 places)

3. Can you please update the title of this PR to include the color change and also improve the description of this PR. Please do add more information as to why we are changing the color and mention the PR where this got changed.
The reason for doing the above exercise is to provide as much context as possible to anyone looking at this (like during release notes preparation or any dev for reference) and also leave breadcrumbs to how we came to conclusion to change this.

2022-03-18 12:47 UTC, ashit-rath commented on app/client/src/widgets/IconButtonWidget/component/index.tsx
> -      onClick={onClick}
Any idea why the `onClick` is on this div rather than on the `StyledButton`?

2022-03-18 12:52 UTC, ashit-rath commented on app/client/src/widgets/ButtonWidget/component/DragContainer.tsx
> +        onClick={(event) => {
I don't understand this, IMO the `DragContainer` as the name implies should not have the `onClick` action. Also, in the places where this container is used, a button is placed as its child and that also has the same `onClick` function as its prop. Why are we need to do this?

2022-03-18 12:53 UTC, yaldram commented on app/client/src/widgets/IconButtonWidget/component/index.tsx
> -      onClick={onClick}
Well the `StyledButton` is wrapped by the `div`, all the clicks will be registered on the `div` and not the `StyledButton`.

2022-03-18 12:54 UTC, yaldram commented on app/client/src/widgets/ButtonWidget/component/DragContainer.tsx
> +        onClick={(event) => {
Yes we had to do this, you can refer to this Pull Request - https://github.com/appsmithorg/appsmith/pull/11627

2022-03-18 13:17 UTC, yaldram commented
The color changes done in this Pull Request - 
1. Check `TimerContainer` for `AudioRecorderWidget`.
2. Check `Pagination` component for `TableWidget`.
3. Check `Buttons Disabled` for the `TableWidget`.

2022-03-21 05:03 UTC, yaldram commented
Some Tests for the Q/A for `Button`, `IconButton`, `MenuButton`, `ButtonGroup` widgets  : - 
- Please check for the button Styles in both canvas and deploy mode they should work.
- Enable and Disabled states should function as expected.
- Please check if the Button Captcha is working as expected both in Enable and Disable mode.

2022-03-21 14:10 UTC, somangshu commented
@yaldram from the internal conversation I found out that this change was made by @IAmAnubhavSaini / @albinAppsmith, Are the aware of the change we are doing here? Why was this change made in the first place?

Lets act quickly on this informing all the people and getting it merged to release

2022-03-21 14:36 UTC, vivekverma2312 commented
@yaldram Tested and it's working fine but I see the PR has conflicting files.

2022-03-21 14:44 UTC, IAmAnubhavSaini commented
@yaldram change to `GREY_8` is not required in app/client/src/pages/Editor/gitSync/DisconnectGitModal.tsx

You can take release changes for resolving conflict.

2022-03-22 05:26 UTC, YogeshJayaseelan commented
@yaldram Tested this PR and please find the status below,

* Original issue - Icon button OnClick on the disabled state is working fine

Observed an issue with button captcha 

Issue 1 - Clicking on the disabled Button widget generates the google Recaptcha token 

https://www.loom.com/share/73e1127b06fc45e6a1cebf33d4e7f632

2022-03-22 06:53 UTC, yaldram commented
@YogeshJayaseelan both the above issues have been fixed.

2022-03-23 05:55 UTC, ashit-rath submitted a review, later dismissed

2022-03-23 06:26 UTC, YogeshJayaseelan commented
@yaldram Tested the fixes and did a round of sanity on button styles on the button widget family. They are working as expected

2022-03-23 06:37 UTC, yaldram commented
/ok-to-test sha=4084b21

2022-03-23 08:00 UTC, ashit-rath reviewed
Good job!

2022-03-23 08:00 UTC, yaldram commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/IconButton_spec.js
> +  it.only("1. check default buttonVariant with isJSConvertible", function() {
Ah so sorry will push a fix.

2022-03-23 08:16 UTC, yaldram commented
/ok-to-test sha=7af65dc

2022-03-23 08:53 UTC, ashit-rath approved these changes
LGTM!

2022-03-23 09:51 UTC, merged