Feature: Rename orgnization in homepage
appsmithorg/appsmith pull request #1201
Opened 2020-10-14 14:53 UTC by devrk96

2020-10-14 15:00 UTC, satbir121 commented on app/client/src/sagas/OrgSagas.ts
> +        payload: {
`SAVE_ORG_SUCCESS` is also called on `website` and `email`. If the save request is for `website`, there will be no name. What will happen to the `org` then?

2020-11-19 07:54 UTC, hetunandu commented on app/client/src/pages/Applications/index.tsx
> +  const ApplicationNameChange = (newName: string, orgId: string) => {
Should be called OrgNameChange

2020-11-19 07:55 UTC, hetunandu approved these changes

2020-11-19 07:56 UTC, hetunandu requested changes
Small change

2020-11-25 12:01 UTC, hetunandu approved these changes

2020-11-25 12:24 UTC, merged