Fix/fix input size
appsmithorg/appsmith pull request #1207
Opened 2020-10-14 20:00 UTC by ThakurKarthik

## Description
fix extra padding issue of input field after losing focus.

Fixes #958
> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce. 
> Please also list any relevant details for your test configuration.

- Verified in different input fields in local

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2020-10-14 20:19 UTC, ThakurKarthik commented
@hetunandu @Nikhil-Nandagopal I tried to remove the padding-bottom from CodeMirror-Scroll class by setting to 0 then i noticed vertical scrollbars coming up in input fields after losing focus,so i searched for this an came across `scrollbarStyle: string` prop by setting this to "null" it seems to remove that padding without changing any CSS. Can you verify this and see if it is breaking any other areas?

Thanks

2020-10-15 05:48 UTC, hetunandu requested changes
Small change

2020-10-15 05:48 UTC, hetunandu commented on app/client/src/components/editorComponents/CodeEditor/index.tsx
> +        scrollbarStyle: "null",
Can we add this prop conditionally when EditorSize.COMPACT is true?
Similar to lineWrapping prop

2020-10-15 17:44 UTC, ThakurKarthik commented
@hetunandu can you review once, Thanks !

2020-10-16 06:25 UTC, hetunandu approved these changes

2020-10-16 06:26 UTC, merged