fix: Switch group widget is crashed when selectedValues is undefined
appsmithorg/appsmith pull request #12095
Opened 2022-03-22 09:00 UTC by wmdev0808

## Description
- When selectedValues is undefined, the app is crashed
- Make selected prop for the component to return empty array if its value is falsy

Fixes #12078 

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Test A
- Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-03-22 09:01 UTC, wmdev0808 commented
/ok-to-test sha=1f056f6

2022-03-22 09:44 UTC, riodeuno commented on app/client/src/widgets/SwitchGroupWidget/component/index.tsx
> +            checked={(selected || []).includes(option.value)}
@wmdev0808 This fix should do it. However, in the interest of never regressing. Let's add a cypress test for this scenario.

2022-03-22 09:44 UTC, riodeuno requested changes
The code looks good. Need to add a cypress test to avoid regressions.

2022-03-22 12:25 UTC, wmdev0808 commented
/ok-to-test sha=6c56a82

2022-03-22 12:26 UTC, riodeuno approved these changes
Looks good to me!

2022-03-23 07:22 UTC, YogeshJayaseelan commented
@wmdev0808 @riodeuno Tested this fix and now the switch widget is not crashing but is it okay to get a cyclic dependency error?


https://www.loom.com/share/d19df25d3dab4895af00300ad42133b4

2022-03-23 07:27 UTC, wmdev0808 commented
> @wmdev0808 @riodeuno Tested this fix and now the switch widget is not crashing but is it okay to get a cyclic dependency error?
> 
> [![LOOM DEMO](https://camo.githubusercontent.com/516d745a0715b7bee09dff8641b6eaf774c4d5ae0460343eecc2c2a44a851ee1/687474703a2f2f63646e2e6c6f6f6d2e636f6d2f73657373696f6e732f7468756d626e61696c732f64313964663235643364616234383935616630303330306164343231333362342d30303030312e676966)](https://www.loom.com/share/d19df25d3dab4895af00300ad42133b4)


> @wmdev0808 @riodeuno Tested this fix and now the switch widget is not crashing but is it okay to get a cyclic dependency error?
> 
> [![LOOM DEMO](https://camo.githubusercontent.com/516d745a0715b7bee09dff8641b6eaf774c4d5ae0460343eecc2c2a44a851ee1/687474703a2f2f63646e2e6c6f6f6d2e636f6d2f73657373696f6e732f7468756d626e61696c732f64313964663235643364616234383935616630303330306164343231333362342d30303030312e676966)](https://www.loom.com/share/d19df25d3dab4895af00300ad42133b4)

@YogeshJayaseelan ,
Yes, you don't have to worry about that

2022-03-23 08:51 UTC, riodeuno commented
@YogeshJayaseelan The cyclic dependency error is an issue that needs to be dealt with from the perspective of evaluations. We need to triage that separately. This fix helps prevent the crash of the Switch Group widget.

2022-03-23 09:00 UTC, somangshu commented
@YogeshJayaseelan based on the above comment, Can you create another issue around the cyclic dependency and tag the @appsmithorg/fe-coders-pod  for the same. We can also do this when we verify this on release

2022-03-23 09:08 UTC, riodeuno commented
@somangshu I think the original issue reported by @YogeshJayaseelan, already talks about the cyclic dependency. We can potentially move that forward for triaging.

2022-03-24 07:16 UTC, merged