fix: Update success message for reset password link sent
appsmithorg/appsmith pull request #12147
Opened 2022-03-22 15:28 UTC by ankitakinger

## Description

> If a user who has not signed up, directly tries to sign with his credentials, then the message "It looks like you may have entered incorrect/invalid credentials. Please try again or reset the password using the button below." appears on the login screen.

> If the user clicks on "Reset Password" and gives a non-registered email id, it shows a successful message "A password reset link has been sent to [abc@c.com](mailto:abc@c.com)".

> This PR fixes this issue by updating the successful message to "A password reset link has been sent to your email address  [abc@c.com](mailto:abc@c.com) registered with Appsmith." This had to be done instead of showing error message for nog registered account due to security concerns.

> Another issue fixed under this PR is that if the user tries to change the email address after submitting the reset password form, then the form should be reset instead of just updating the email id in the field as well as successful message.

Fixes #11672 [#185](https://github.com/appsmithorg/appsmith-ee/issues/185)

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Tested if the form gets reset every time we try to change the email id field after the reset password form has already been submitted.
- Tested if the new successful message gets displayed instead of the old one.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-03-22 17:04 UTC, Aishwarya-U-R commented
/ok-to-test sha=ae214a7

2022-03-23 08:26 UTC, sharat87 commented on app/client/src/pages/UserAuth/ForgotPassword.tsx
> +        props.reset();
Ignorant question: This `reset` call will reset the `emailValue` to empty string right? So, if we are emptying the `emailValue` right after a success response from the server, does that mean we won't be able to show the email in the success massage `FORGOT_PASSWORD_SUCCESS_TEXT`? Since that is also using the value of `emailValue` only no?

2022-03-23 08:26 UTC, sharat87 commented on app/client/src/ce/constants/messages.ts
> +  `A password reset link has been sent to your email address ${email} registered with Appsmith.`;
This sounds as if we are implying that that email is already registered. I'm not sure if that's okay. 🤔

How about a message like on https://github.com/appsmithorg/appsmith/issues/11672#issuecomment-1072271495 cc @hiteshjoshi

2022-03-23 12:39 UTC, ankitakinger commented on app/client/src/ce/constants/messages.ts
> +  `A password reset link has been sent to your email address ${email} registered with Appsmith.`;
I checked that message earlier. That can be read like "if the email id exists". What if the user's email id exists, but they are have not registered on Appsmith using the same.

I'd asked @Pranay105 to reframe it for me and he shared the below options:
`We have shared a password reset link to your email address (<aaa@aaa.com>) that exists on Appsmith
OR
We have shared a password reset link to the email address (<aaa@aaa.com>) registered with Appsmith
OR
A password reset link has been sent to your email address (aaa@aaa.com) registered with Appsmith`

2022-03-23 12:42 UTC, ankitakinger commented
@RakshaKShetty could you please test this out before I merge it?

2022-03-23 13:32 UTC, RakshaKShetty commented
Point 1. The text message has been changed as mentioned above i e "A password reset link has been sent to your email address [abc@c.com](mailto:abc@c.com) registered with Appsmith"
Point 2. When the user tries to re-edit the email id after submitting, the success message won't get edited instead the success message is removed and the user should reenter the email id
Point 3. In Local I couldn't verify the email this part i will be verifying in the release instance

Tested above points LGTM

2022-03-24 08:16 UTC, ankitakinger commented on app/client/src/pages/UserAuth/ForgotPassword.tsx
> +        props.reset();
Nope, it's not right after the success response. This will be reset only when a user tries to change the email value after submit success response is received from the server. `props.emailValue` dependency has been added in this useEffect.

2022-03-24 10:08 UTC, sharat87 commented on app/client/src/pages/UserAuth/ForgotPassword.tsx
> +        props.reset();
Ah I see. Then in that case, say I input `abc@test.com` and click on the Reset button, then I see the green success message, then I try changing the email to `abcd@test.com`, by just inserting a `d`, then the success message goes away, but the email is still `abc@test.com`. The `d` is not inserted. Could it be because of this? It's acting a little weird, I'm not sure what's happening.

https://user-images.githubusercontent.com/120119/159893103-70969af1-1f2e-4f8a-8b31-156d048d799e.mov

2022-03-24 10:12 UTC, ankitakinger commented on app/client/src/pages/UserAuth/ForgotPassword.tsx
> +        props.reset();
Ohh interesting. When I and Raksha both tested on our end, we both didn't face this. Let me have a look again. Thanks for this.

2022-03-24 11:28 UTC, ankitakinger commented on app/client/src/pages/UserAuth/ForgotPassword.tsx
> +        props.reset();
this should be fixed now. @RakshaKShetty could you confirm?

2022-03-24 11:47 UTC, ankitakinger commented
/ok-to-test sha=cdc857c

2022-03-24 12:53 UTC, ankitakinger commented
/ok-to-test sha=cdc857c

2022-03-24 19:51 UTC, Aishwarya-U-R commented
/ok-to-test sha=409179a

2022-03-25 11:46 UTC, sharat87 approved these changes

2022-03-25 11:50 UTC, albinAppsmith approved these changes

2022-03-25 11:58 UTC, IAmAnubhavSaini requested changes
The email label and input, and reset button should be hidden on the success screen.

User has submitted their email for password reset, we are not expecting them to send another reset email. There is no use case for email and reset button to be there.

2022-03-25 11:58 UTC, IAmAnubhavSaini commented on app/client/src/ce/constants/messages.ts
> +  `A password reset link has been sent to your email address ${email} registered with Appsmith.`;
This message should be `A password reset link has been sent to ${email}, if it is registered with Appsmith.` Or the if part can come first. 

You can get product input on it.

I really hope that we send email only when it is registered with Appsmith.

2022-03-25 12:44 UTC, IAmAnubhavSaini approved these changes
It can go as it is ATM.

2022-03-28 05:59 UTC, RakshaKShetty commented on app/client/src/pages/UserAuth/ForgotPassword.tsx
> +        props.reset();
yes LGTM

2022-03-28 06:03 UTC, merged