fix: Mongodb not accepting valid array update query
appsmithorg/appsmith pull request #12241
Opened 2022-03-25 03:19 UTC by devnamrits

## Description

Initially, when we were passing the correct MongoDB update query written in array form eg. `[{"$set":{name: "Ram singh"} },{"$set": {age: 30}}]`, it was raising an error. After this change, the valid update query is working fine. Since `Document.parse` doesn't parse array. Hence I added a default key with a JSON structure pointing towards that array. As `Document. parse` will parse this JSON hence it works fine further. 

Fixes #11419 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Testing is being done by passing the update command of the type array from the frontend.
Screenshot:

<img width="1158" alt="Screenshot 2022-03-25 at 8 47 21 AM" src="https://user-images.githubusercontent.com/54183698/160047470-88f86c15-ade7-40e3-8e83-2b9401852db0.png">

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-03-28 13:55 UTC, devnamrits commented
@mojtab23 Any update?

2022-03-31 14:27 UTC, sumitsum commented
@devnamrits thanks for raising the PR. I will be reviewing it.

2022-04-01 03:12 UTC, devnamrits commented
Thank you @sumitsum for reviewing it.

2022-04-07 10:57 UTC, sumitsum requested changes

2022-04-07 10:57 UTC, sumitsum commented on app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/commands/UpdateMany.java
> +            this.update = "{\"updateKey\":" + this.update + "}";
Hi @devnamrits , this approach has a drawback. If we do this, then we can never validate any input as valid or invalid. e.g. If `this.update` is `"abc"` then this will be parsed as a valid input which is not intended. Essentially this change converts any input into a valid input. However, what we want is to be able to detect if the user input is valid or not. Up until now we have only tried to check if the input is a valid `Document` or not, which in this case is not sufficient since MongoDB 4.2 onwards it also accepts an array of Documents (pipleine) as well. Hence, IMO, the correct approach here should be to parse for two things - (1) valid Document (2) valid array of Documents. To achieve this one good way would be create a new method `parseSafely(fieldName, input., boolean)` along the lines of `parseSafely` method that already exists and use the last parameter to check if we need to validate for array of Documents as well.

2022-04-07 10:57 UTC, sumitsum commented
Can you please add a JUnit test case for this change in `MongoPluginTest.java` ?

2022-04-07 13:44 UTC, devnamrits commented on app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/commands/UpdateMany.java
> +            this.update = "{\"updateKey\":" + this.update + "}";
Okay then I'll try to validate and parse as you mentioned. 

Also, I need to add those JUnit test cases after making these changes, Right??

2022-04-07 14:24 UTC, sumitsum commented on app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/commands/UpdateMany.java
> +            this.update = "{\"updateKey\":" + this.update + "}";
@devnamrits thanks for following up on this. Yes, once you have made the necessary changes and manually tested them, you should then add one JUnit test case to test it as well.

2022-04-26 05:29 UTC, sumitsum commented
@devnamrits , can you please confirm if you are still working on this ? If you need help regarding the implementation, we can meet and discuss as well.

2022-05-16 07:27 UTC, sumitsum commented
@devnamrits please comment here if you are still working on it, otherwise, this issue may get re-assigned.

2022-11-01 20:00 UTC, closed without merging