feat: Exclude configs from actions while committing to git repo
appsmithorg/appsmith pull request #12251
Opened 2022-03-25 09:07 UTC by AnaghHegde

## Description
Exclude the app slug from git repo as the imported app from git repo will have different name.
For actions created from datasources of type SAAS, API we need to exclude the config values from committing to git repo

Fixes #11997 

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Locally

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-03-28 12:15 UTC, abhvsn commented
I'll let @nidhi-nair to review this PR as I don't have the complete context here 🙂

2022-03-31 05:25 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog2.java
> +    @ChangeSet(order = "005", id = "add-isConfigStoredAtDataSource-for-plugins", author = "")
Let's maintain ordering here?

2022-03-31 05:27 UTC, nidhi-nair commented on app/server/appsmith-server/src/test/java/com/appsmith/server/services/GitServiceTest.java
> +        Mockito.when(gitFileUtils.saveApplicationToLocalRepo(Mockito.any(Path.class), Mockito.any(ApplicationJson.class), Mockito.anyString(), Mockito.anyList()))
Could we please add a test for `true`, `false` and `null` values here?

2022-03-31 05:27 UTC, nidhi-nair commented
@AnaghHegde, for the remote plugin migration, we'll also have Twilio and a bunch of Hubspot plugins on prod. Could you please limit that to Airtable. Also let's talk to @hiteshjoshi and get a clear set of guidelines about when we're supposed to mark this value as true or false from a product perspective? We can use Twilio and Hubspot as examples to figure this out. This will help our SaaS (remote) team set this up independently.

Also, looks like our default behaviour for this is that we do copy over the config. Is that intended? If one of the plugins skips on this config because of an oversight, what behaviour do we want to default to?

2022-03-31 07:00 UTC, AnaghHegde commented
@nidhi-nair For the default behaviour yes we do copy over the config as it does not have any sensitive data and does not affect the import flow.For Twilio and Hubspot we can have a call to discuss this in detail.

2022-03-31 07:01 UTC, AnaghHegde commented on app/server/appsmith-server/src/test/java/com/appsmith/server/services/GitServiceTest.java
> +        Mockito.when(gitFileUtils.saveApplicationToLocalRepo(Mockito.any(Path.class), Mockito.any(ApplicationJson.class), Mockito.anyString(), Mockito.anyList()))
It won't make sense to include this here, as we are mocking the implementation here. But i am writing test for this in `GitFileUtilsTest` class, i will push this.

2022-04-04 06:06 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/domains/Plugin.java
> +    Boolean isConfigStoredAtDataSource;
Nit: Can we use lowercase for datasource? This is to maintain consistency with how we refer to datasources across Appsmith.

2022-04-04 06:12 UTC, nidhi-nair requested changes
Just a tiny change in the name that'll help with maintenance

2022-04-04 06:22 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/domains/Plugin.java
> +    Boolean isConfigStoredAtDataSource;
@nidhi-nair If you look at the [L.72 ](https://github.com/appsmithorg/appsmith/blob/release/app/server/appsmith-server/src/main/java/com/appsmith/server/domains/Plugin.java#L72) we have used it in capital words.

2022-04-04 12:05 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/domains/Plugin.java
> +    Boolean isConfigStoredAtDataSource;
Thanks for catching this, we should fix this reference as well!

2022-04-06 11:46 UTC, mohanarpit commented
@AnaghHegde Since the linked issue has been closed because we don't wish to follow the proposed implemenetation plan, is this PR still relevant? Can we close this PR?

2022-04-08 02:49 UTC, AnaghHegde commented
Closing this PR as we have decided to not to implement this feature.

2022-04-08 02:49 UTC, closed without merging