Create a new input field which outputs a key value pair
appsmithorg/appsmith pull request #1226
Opened 2020-10-15 11:58 UTC by akash-codemonk

Fixes #1209

2020-10-15 15:01 UTC, sharat87 commented
LGTM, but I'd wait for Hetu's review.

2020-10-16 06:41 UTC, hetunandu requested changes
Minor changes regarding abstractions of repeated code

2020-10-16 06:41 UTC, hetunandu commented on app/client/src/components/formControls/FixedKeyInputControl.tsx
> +      <div style={{ width: "50vh" }}>
Can we add a styled component instead of inline styles

2020-10-16 06:41 UTC, hetunandu commented on app/client/src/components/formControls/FixedKeyInputControl.tsx
> +  }
This functionality seems to be repeated.. make it abstracted and come from the same place.

2020-10-16 06:41 UTC, hetunandu commented on app/client/src/pages/Editor/DataSourceEditor/Connected.tsx
> +                <div style={{ marginTop: 9 }}>
This margin top can be abstracted in a styled component

2020-10-16 07:12 UTC, hetunandu approved these changes

2020-10-16 07:34 UTC, merged