chore: Improve UX on admin settings page
appsmithorg/appsmith pull request #12279
Opened 2022-03-28 06:19 UTC by ankitakinger

## Description

> Improved UX on the admin settings page:
1. Scope field was not in line with other fields
2. Not enabling the save and restart button on Admin settings till all mandatory fields are filled up

Fixes #12172 

## Type of change

- UX improvement

## How Has This Been Tested?

- Tested if the scope field has the same length as the other fields
- Tested if the save and restart button only gets enabled when some field has changed from its initial state and all mandatory fields are filled up.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-03-28 13:33 UTC, IAmAnubhavSaini requested changes

2022-03-28 13:33 UTC, IAmAnubhavSaini commented on app/client/src/pages/Settings/SaveSettings.tsx
> +            props.settings[eachSetting.id]?.trim() === ""))
I'd really like `if` conditions to be short. Put condition in a variable. Because then it can be read as `if hasId then return it`.

2022-03-28 13:33 UTC, IAmAnubhavSaini commented on app/client/src/pages/Settings/SaveSettings.tsx
> +    return disabled;
```
let disabled = false;
...
code in review
```

can be rewritten as:

```
const disabled = requiredFields.length || Object.keys(settings).length == 0 || !props.valid;
return disabled;
```

or even:
```
return requiredFields.length || Object.keys(settings).length == 0 || !props.valid;
```

2022-03-28 13:33 UTC, IAmAnubhavSaini commented on app/client/src/pages/Settings/SaveSettings.tsx
> +        disabled={checkForEnabling()}
A better name could be `isDisabled`.

2022-03-28 13:57 UTC, ankitakinger commented on app/client/src/pages/Settings/FormGroup/group.tsx
> +            color: #000;
done

2022-03-28 13:57 UTC, ankitakinger commented on app/client/src/components/ads/TagInputComponent.tsx
> +          };
done

2022-03-28 14:39 UTC, ankitakinger commented on app/client/src/pages/Settings/SaveSettings.tsx
> +        disabled={checkForEnabling()}
done

2022-03-28 14:40 UTC, ankitakinger commented on app/client/src/pages/Settings/SaveSettings.tsx
> +            props.settings[eachSetting.id]?.trim() === ""))
I understand. The naming of the variable here would have to be long though hence didn't do so. Let me think on it.

2022-03-28 14:40 UTC, ankitakinger commented on app/client/src/pages/Settings/SaveSettings.tsx
> +  const checkForEnabling = () => {
done

2022-03-28 14:41 UTC, ankitakinger commented on app/client/src/pages/Settings/SaveSettings.tsx
> +    return disabled;
done

2022-03-30 07:25 UTC, ankitakinger commented on app/client/src/pages/Settings/SaveSettings.tsx
> +            props.settings[eachSetting.id]?.trim() === ""))
done

2022-03-30 12:25 UTC, ankitakinger commented
/ok-to-test sha=0c71f22

2022-03-31 12:24 UTC, ankitakinger commented
/ok-to-test sha=3832e37

2022-03-31 12:39 UTC, albinAppsmith approved these changes

2022-04-04 07:07 UTC, merged