fix: 12225 default value behaviour in select and multi select widgets
appsmithorg/appsmith pull request #12302
Opened 2022-03-28 12:42 UTC by prsidhu

## Description

Issue - the widgets render the provided default value even if it is unavailable in the options list.
Fix - Filter valid selections in the widget.

Fixes # (issue)

https://github.com/appsmithorg/appsmith/issues/12225

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

1. Create a new app. 
2. Drag in a select widget. The widget will render GREEN text as provided by the default value.
3. Change the options list to not include the option { value: "GREEN", label: "GREEN" }. Keep the default value as the same.
4. Refresh the widget. Observe that the widget renders with a default message : "Select option".
5. Repeat the same for multi select widget.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-03-28 12:46 UTC, Tooluloope commented
Hi @prsidhu 
This was a known fix.
Using these widgets in Serverside filtering, 
You'll realize that a selected value might not be in the list of options when the widget/options are filtered

2022-03-28 12:55 UTC, prsidhu commented
@Tooluloope What do you suggest then? The logic could be ported to the component rather than the widget.

2022-03-31 06:54 UTC, Tooluloope commented
@prsidhu a conclusion was made here https://github.com/appsmithorg/appsmith/issues/12225#issuecomment-1082910936

2022-03-31 07:51 UTC, prsidhu commented
@Tooluloope thanks for intimation. I've made the changes. Could you review it again?

2022-03-31 08:59 UTC, Tooluloope requested changes
Hi @prsidhu, You'll need to act on their derived properties `SelectedOptionValues` and `SelectedOptionlabels`.

![Screenshot 2022-03-31 at 09 58 48](https://user-images.githubusercontent.com/31691737/161018032-243182a8-b2e5-436f-9090-19eb8cd3cbca.png)

2022-04-03 07:02 UTC, prsidhu commented
/ok-to-test sha=01cf99a

2022-04-03 07:04 UTC, prsidhu commented
/ok-to-test sha=01cf99a

2022-04-05 07:29 UTC, Tooluloope requested changes
https://www.loom.com/share/b37e89b1579b401fae23addcd5a69048

Could you look into this crash?

2022-04-05 08:06 UTC, Tooluloope requested changes
Please add comprehensive tests for what you're doing.

Lastly, let's update the title and description to reflect the changes we are making

2022-04-05 08:06 UTC, Tooluloope commented on app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx
> +    this.validateSelections(values);
So this shouldn't be here.
To update the SelectedOptionValue, You'll do the filtering in the derived property, and also you filter the value getting into the component.

Your implementation would cause multiple rerenders, that's why it crashes

2022-04-05 08:06 UTC, Tooluloope commented on app/client/src/widgets/SelectWidget/widget/index.tsx
> +    }
this would also always run, I think you need to validate the value, if the value is empty you don't need to run this.

2022-04-19 16:44 UTC, closed without merging