feat: activity logging
appsmithorg/appsmith pull request #12383
Opened 2022-03-30 12:31 UTC by riodeuno

## Description
The client's activity pulse logging mechanism. Works in conjunction with #12340

## Type of change
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
This is a prototype, no tests are necessary, at this juncture.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-03-31 09:16 UTC, riodeuno commented
/ok-to-test sha=73005a7

2022-03-31 09:33 UTC, riodeuno commented
/ok-to-test sha=73005a7

2022-03-31 11:04 UTC, riodeuno commented
/ok-to-test sha=e6bafd2

2022-04-01 06:18 UTC, sharat87 requested changes

2022-04-01 06:18 UTC, sharat87 commented on app/client/public/logger.js
> +    credentials: "same-origin",
```suggestion
    method: "POST",
    credentials: "same-origin",
```

2022-04-01 06:18 UTC, sharat87 commented on app/client/public/logger.js
> +  return timestamp - (date.getUTCMinutes() * 60 + date.getUTCSeconds());
I gather from the comments above, that the point  here is to reset minutes and seconds to 0 from current time. Would this be more reliable then?

```suggestion
  date.setUTCMinutes(0);
  date.setUTCSeconds(0);
  return getCurrentUTCTimestamp(date);
```

2022-04-01 06:21 UTC, riodeuno commented on app/client/public/logger.js
> +    credentials: "same-origin",
Whoops! Good catch! I'll make the change.

2022-04-01 06:43 UTC, riodeuno commented on app/client/public/logger.js
> +  return timestamp - (date.getUTCMinutes() * 60 + date.getUTCSeconds());
Yes, we can, they both result in the same value.

<img width="445" alt="Screenshot 2022-04-01 at 12 11 45 PM" src="https://user-images.githubusercontent.com/103687/161209633-fb230af8-8146-47ee-9af0-47b62cd8b075.png">

2022-04-01 06:44 UTC, sharat87 commented on app/client/public/logger.js
> +  return timestamp - (date.getUTCMinutes() * 60 + date.getUTCSeconds());
Got it. No worries then. Less of an issue than the other comment. :)

2022-04-01 06:45 UTC, sharat87 approved these changes

2022-04-01 06:46 UTC, riodeuno commented
/ok-to-test sha=23751a1

2022-04-01 09:55 UTC, merged