chore: add perf test for select widget
appsmithorg/appsmith pull request #12409
Opened 2022-03-31 04:25 UTC by prsidhu

## Description

Add perf test for select widget.
Actions included:
1. rendering options list.
2. selecting an option

## Type of change

## Checklist:

- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-03-31 04:29 UTC, prsidhu commented
/ok-to-test sha=e2e78ed

2022-03-31 06:13 UTC, SatishGandham requested changes

2022-03-31 06:13 UTC, SatishGandham commented on app/client/perf/src/utils/utils.js
> +  await page.type(emailSelector, "hello@mail.com");
You should not change these values.

2022-03-31 06:13 UTC, SatishGandham commented on app/client/perf/tests/select-widget.perf.js
> +const actions = {
These should be unique across the suite.
Move them to the actions file we have.

2022-04-01 10:23 UTC, prsidhu commented
/ok-to-test sha=2f1f14b

2022-04-04 03:15 UTC, SatishGandham submitted a review, later dismissed

2022-04-07 03:54 UTC, SatishGandham commented
/ok-to-test sha=2f1f14b

2022-04-15 10:16 UTC, SatishGandham requested changes

2022-04-15 10:16 UTC, SatishGandham commented on app/client/perf/start-single-test.sh
> +cd tests
What is this file for?

2022-04-15 10:16 UTC, SatishGandham commented on app/client/perf/src/utils/utils.js
> +  await page.type(emailSelector, "hello@ymail.com");
This email should not be changed

2022-04-15 10:16 UTC, SatishGandham commented on app/client/perf/tests/actions.js
>  };
Please prefix your actions like this. If you have a better idea please share. Ideally earlier action should have been prefixed with golden.
SELECT_WIDGET_MENU_OPEN
SELECT_WIDGET_SELECT_OPTION

2022-04-15 10:16 UTC, SatishGandham commented on coverage-summary.json
> -,"/Users/balajisoundararajan/projects/appsmith/app/client/src/utils/hooks/usePositionedContainerZIndex.ts": {"lines":{"total":21,"covered":21,"skipped":0,"pct":100},"functions":{"total":4,"covered":4
Is this file supposed to be committed?

2022-04-20 17:33 UTC, prsidhu commented on app/client/perf/start-single-test.sh
> +cd tests
simple script to execute a single test. I was having to set env repeatedly.

2022-04-20 17:34 UTC, prsidhu commented
/ok-to-test sha=d23bc76

2022-04-27 06:01 UTC, SatishGandham requested changes

2022-04-27 06:01 UTC, SatishGandham commented on app/client/perf/start-single-test.sh
> +cd tests
This should not be part of GIT. Please remove it.
You can edit your bash profile to set the env variable.

2022-04-27 13:46 UTC, prsidhu commented
/ok-to-test sha=7a53ff2

2022-04-29 08:41 UTC, SatishGandham approved these changes

2022-04-29 08:42 UTC, merged