fix : onclick handler update
appsmithorg/appsmith pull request #12442
Opened 2022-03-31 11:08 UTC by techbhavin

## Description

> Button group widget onClick doesn't work for buttons 

Fixes #12410 

## Type of change

- Bugfix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-03-31 11:08 UTC, techbhavin commented
/ok-to-test sha=5048a45

2022-03-31 11:17 UTC, techbhavin commented
/ok-to-test sha=73a7d53

2022-03-31 11:18 UTC, yaldram approved these changes

2022-03-31 11:30 UTC, somangshu commented
Tested the deploy preview and the failing case now works. @appsmithorg/qa can confirm further

2022-03-31 11:48 UTC, vivekverma2312 commented
@techbhavin Tested On click and it is working as expected.

2022-03-31 11:53 UTC, Tooluloope requested changes

2022-03-31 11:53 UTC, Tooluloope commented on app/client/cypress/fixtures/buttonGroupDsl.json
> +                        "index": 2,
@techbhavin is it possible for a `SIMPLE` ButtonType to have MenuItems?

2022-03-31 11:53 UTC, Tooluloope commented on app/client/cypress/fixtures/buttonGroupDsl.json
> +                        "index": 2,
Also, could you add tests for the other buttons and also the menuItems

2022-03-31 12:08 UTC, techbhavin commented on app/client/cypress/fixtures/buttonGroupDsl.json
> +                        "index": 2,
@NandanAnantharamu  can you plz look here

2022-03-31 12:17 UTC, NandanAnantharamu commented on app/client/cypress/fixtures/buttonGroupDsl.json
> +                        "index": 2,
@Tooluloope dsl file is auto generated based on my actions, so it did generate based on that and simple is available as option PFA
![Uploading Screenshot 2022-03-31 at 5.46.28 PM.png…]()

2022-03-31 12:23 UTC, Tooluloope commented on app/client/cypress/fixtures/buttonGroupDsl.json
> +                        "index": 2,
@techbhavin Should this be possible?

2022-04-01 05:27 UTC, techbhavin commented
Here we cover the required test case. so @somangshu  @Tooluloope we can merge this PR.

2022-04-01 05:53 UTC, Tooluloope approved these changes

2022-04-01 05:58 UTC, merged