feat: Import an template inside an existing Application
appsmithorg/appsmith pull request #12507
Opened 2022-04-01 10:14 UTC by nayan-rafiq

## Description
This PR adds the feature to import a template inside an application. 

Fixes #12336

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- JUnit test
- Manually

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-04-09 18:03 UTC, nayan-rafiq commented
/ok-to-test sha=4f97635

2022-04-11 06:43 UTC, AnaghHegde requested changes
Can we not repeat the same logic again here? I would suggest to modify the appJson file to do the changes `updateNewPagesbeforeMerge`. The current importApplication handles importing resources to the existing app as well as the new app. 
It would be difficult to maintain this in the coming days when we fix a bug or change something in the import flow, we would have to maintain in both the places.

2022-04-11 06:43 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/ApplicationTemplateControllerCE.java
> +        return applicationTemplateService.mergeTemplateWithApplication(templateId, applicationId, branchName, pagesToImport)
I am not able to follow on why we are expecting the list of pages to in request param? Is it because we allow the users to import selected pages from templates as well?

2022-04-11 10:02 UTC, nayan-rafiq commented on app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/ApplicationTemplateControllerCE.java
> +        return applicationTemplateService.mergeTemplateWithApplication(templateId, applicationId, branchName, pagesToImport)
Yeah, that's right. Users will be able to either import the whole application or specific pages of the application.

2022-04-11 10:06 UTC, nayan-rafiq commented
@AnaghHegde Definitely it would be better if import application method is used for this purpose. I tried using that earlier but faced some issues - `gitSyncId` was just one of it. Another issue was - existing actions were being delete from pages. I'll try again.

2022-04-14 06:50 UTC, AnaghHegde commented
@nayan-rafiq Here is what i am thinking, let's not touch the ImportApplication method. It is already designed to handle merging two applications(for git sync) where it can create/delete/update resources. For templates what we can do is set the the git sync id as null after exporting the json file - this way one can use the same template in the same application multiple times. Second, for application name getting updated, we can update the appJson so that the application name is same as where it is being imported. Let me know your thoughts on this.

2022-04-14 06:50 UTC, AnaghHegde reviewed
@nayan-rafiq Here is what i am thinking, let's not touch the ImportApplication method. It is already designed to handle merging two applications(for git sync) where it can create/delete/update resources. For templates what we can do is set the the git sync id as null after exporting the json file - this way one can use the same template in the same application multiple times. Second, for application name getting updated, we can update the appJson so that the application name is same as where it is being imported. Let me know your thoughts on this.

2022-04-18 08:09 UTC, nayan-rafiq commented
/ok-to-test sha=6db0553

2022-04-19 11:20 UTC, AnaghHegde submitted a review, later dismissed

2022-04-20 18:11 UTC, nayan-rafiq commented
/ok-to-test sha=033013c

2022-04-21 06:14 UTC, nayan-rafiq commented
/ok-to-test sha=22a261

2022-04-21 08:20 UTC, abhvsn submitted a review, later dismissed

2022-04-21 10:08 UTC, AnaghHegde submitted a review, later dismissed

2022-04-22 07:46 UTC, AnaghHegde approved these changes

2022-04-22 10:27 UTC, nayan-rafiq commented
/ok-to-test sha=a9a6372

2022-04-24 10:12 UTC, nayan-rafiq commented
/ok-to-test sha=af366ba4a2992f9c5652a34dcd3f2671a7138772

2022-04-26 17:29 UTC, nayan-rafiq commented
/ok-to-test sha=af366ba

2022-04-29 06:11 UTC, AnaghHegde approved these changes

2022-04-29 06:41 UTC, nayan-rafiq commented
/ok-to-test sha=db10426

2022-05-10 05:43 UTC, nayan-rafiq commented
/ok-to-test sha=95a5531

2022-05-10 07:34 UTC, nayan-rafiq commented
/ok-to-test sha=9b57bd4

2022-05-11 10:18 UTC, AnaghHegde approved these changes

2022-05-11 10:27 UTC, nayan-rafiq commented
/ok-to-test sha=9b57bd4

2022-05-11 12:26 UTC, nayan-rafiq commented
/ok-to-test sha=e84be56

2022-05-13 09:59 UTC, nayan-rafiq commented
/ok-to-test sha=b59665b

2022-05-14 17:50 UTC, nayan-rafiq commented
/ok-to-test sha=10f0d3f

2022-05-15 11:46 UTC, nayan-rafiq commented
/ok-to-test sha=10f0d3f

2022-05-16 05:25 UTC, nayan-rafiq commented
/ok-to-test sha=cba82e8

2022-05-17 05:16 UTC, AnaghHegde approved these changes

2022-05-17 06:38 UTC, nayan-rafiq commented
/ok-to-test sha=16ec8337b2024d691aabc5a963da670893e86791

2022-05-18 05:08 UTC, nayan-rafiq commented
/ok-to-test sha=2a3108285ab6b148da23ad0d883ab09af9d61626

2022-05-18 10:05 UTC, nayan-rafiq commented
/ok-to-test sha=2a31082

2022-05-20 17:43 UTC, nayan-rafiq commented
/ok-to-test sha=da2629f

2022-05-24 06:22 UTC, nayan-rafiq commented
/ok-to-test sha=96a0a4d

2022-05-25 08:29 UTC, abhvsn submitted a review, later dismissed

2022-05-26 10:33 UTC, nayan-rafiq commented
/ok-to-test sha=2d8f3e7

2022-05-27 07:10 UTC, nayan-rafiq commented
/ok-to-test sha=e62d831

2022-05-28 18:04 UTC, nayan-rafiq commented
/ok-to-test sha=89cabb9

2022-05-29 19:28 UTC, nayan-rafiq commented
/ok-to-test sha=89cabb9

2022-06-01 12:05 UTC, AnaghHegde approved these changes

2022-06-02 05:45 UTC, nayan-rafiq commented
/ok-to-test sha=5436558

2022-06-04 17:35 UTC, nayan-rafiq commented
/ok-to-test sha=adffbcb

2022-06-05 18:56 UTC, nayan-rafiq commented
/ok-to-test sha=6275ccb

2022-06-05 18:57 UTC, nayan-rafiq commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
> +        }
I've updated the PR.

2022-06-06 04:59 UTC, nayan-rafiq commented
/ok-to-test sha=5a53280

2022-06-06 06:35 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
> +        return themeService.importThemesToApplication(application, importedApplicationJson);
Thanks, @nayan-rafiq for moving this to the service class. We will be doing this clean up for other methods as well.   
We should also move the export as well to service class.

2022-06-06 06:35 UTC, abhvsn approved these changes

2022-06-08 07:24 UTC, merged