Add a field for the post message api exposure
appsmithorg/appsmith pull request #12551
Opened 2022-04-04 09:40 UTC by rimildeyjsr

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.

## Description

> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change.

Fixes # (issue)

> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-04-18 13:16 UTC, Rishabh-Rathod commented on app/client/src/components/editorComponents/ActionCreator/Fields.tsx
> +  postMessageToTargetWindow: "postMessageToTargetWindow",
Why not keep name of the function as postMessage itself for users?  Internally, we name function as `postMessageToTargetWindow` in `Actions.ts` when creating action to avoid conflict with postMessage of worker.

2022-04-18 13:50 UTC, Rishabh-Rathod commented on app/client/src/components/editorComponents/ActionCreator/Fields.tsx
> +          defaultParams = `,'https://www.example.com'`;
<img width="1624" alt="Screenshot 2022-04-18 at 7 13 22 PM" src="https://user-images.githubusercontent.com/23132741/163816976-10c2b785-d613-4e49-b40e-fc506f615919.png">

I was expecting a linting error here as postMessage should have a message argument passed.

Also, when I typed
```
postMessageToTargetWindow(this.myVar1, '*');
``` 
I was expecting a warning. Mentioning '*' in the target window argument is not supported. How else do we communicate it to the user?

2022-04-18 14:29 UTC, Rishabh-Rathod requested changes
Can you please resolve the below comments and nitpicks?

2022-04-18 14:29 UTC, Rishabh-Rathod commented on app/client/src/components/editorComponents/ActionCreator/Fields.tsx
> +        fieldLabel = "Target origin";
Can we not maintain an object with key as fieldType and value as field label here to avoid the if-else chain here?

2022-04-18 14:29 UTC, Rishabh-Rathod commented on app/client/src/components/editorComponents/ActionCreator/index.tsx
> +
Instead of adding one more if condition here, Could we write a logic here to loop an object which has a key as action name and value as an array of fields to push?

2022-04-18 14:29 UTC, Rishabh-Rathod commented on app/client/src/entities/DataTree/actionTriggers.ts
> +    targetOrigin: string;
Any reason why we don't support `transfer` ( optional ) argument as mentioned here https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage. 
Is it out of scope for now?

2022-04-18 14:29 UTC, Rishabh-Rathod commented on app/client/src/utils/autocomplete/EntityDefinitions.ts
> +    "!type": "fn(message: any, targetOrigin: any, transfer: [any])",
```suggestion
    "!type": "fn(message: any, targetOrigin: string, transfer: [any])",
```
Shouldn't we have `targetOrigin` as a string?

2022-04-18 14:29 UTC, Rishabh-Rathod commented on app/client/src/workers/Actions.test.ts
> +  it("post message to target window works", () => {
Instead of only `string` value, can we test for multiple dataTypes here?

2022-04-18 14:29 UTC, Rishabh-Rathod commented on app/client/src/workers/Actions.ts
> +  postMessageToTargetWindow: function(message: any, targetOrigin: string) {
Instead of type as `any` for message argument. Can we use `unknown` here? Just as a good practise. https://dmitripavlutin.com/typescript-unknown-vs-any/ 
```suggestion
  postMessageToTargetWindow: function(message: unknown, targetOrigin: string) {
```

2022-04-19 09:45 UTC, rimildeyjsr commented on app/client/src/components/editorComponents/ActionCreator/Fields.tsx
> +        fieldLabel = "Target origin";
@Rishabh-Rathod - I had this refactor in mind, since its touches a lot of different parts of the codebase, I have raised an issue for that - https://app.zenhub.com/workspaces/fe-coders-pod-6167d1b64ee5f20014242ab7/issues/appsmithorg/appsmith/13077

2022-04-19 09:46 UTC, rimildeyjsr commented on app/client/src/utils/autocomplete/EntityDefinitions.ts
> +    "!type": "fn(message: any, targetOrigin: any, transfer: [any])",
done - miss on my part

2022-04-19 09:47 UTC, rimildeyjsr commented on app/client/src/workers/Actions.ts
> +  postMessageToTargetWindow: function(message: any, targetOrigin: string) {
great suggestion, done

2022-04-19 10:01 UTC, rimildeyjsr commented on app/client/src/components/editorComponents/ActionCreator/Fields.tsx
> +  postMessageToTargetWindow: "postMessageToTargetWindow",
@Rishabh-Rathod - should we make a separate issue for this or handle in this PR?

2022-04-19 10:08 UTC, rimildeyjsr commented on app/client/src/components/editorComponents/ActionCreator/index.tsx
> +
@Rishabh-Rathod - had this in mind, addressing it in this issue
https://app.zenhub.com/workspaces/fe-coders-pod-6167d1b64ee5f20014242ab7/issues/appsmithorg/appsmith/13080

2022-04-19 11:18 UTC, Rishabh-Rathod commented on app/client/src/components/editorComponents/ActionCreator/Fields.tsx
> +  postMessageToTargetWindow: "postMessageToTargetWindow",
I was suggesting that name of the action should be `postMessage` here.

I noticed that it was named earlier as `postMessage` and the function in Actions.ts `postMessage` was conflicting with the worker's global `postMessage` method. 

Can you help me understand if we could have just renamed the function and still kept the action name as `postMessage`, will that still be a problem?

How do we do that change?
I believe changing action name from  `postMessageToTargetWindow` -> `postMessage` should do the job.

2022-04-19 11:22 UTC, rimildeyjsr commented on app/client/src/components/editorComponents/ActionCreator/Fields.tsx
> +  postMessageToTargetWindow: "postMessageToTargetWindow",
renaming to postMessage crashes the onclick because it is conflicting with worker.postmessage . It is leading to this issue - https://theappsmith.slack.com/archives/C02K0SZQ7V3/p1649225249081599

I can rename it to something shorter or better, if you have any better suggestions

2022-04-20 09:22 UTC, rimildeyjsr commented on app/client/src/components/editorComponents/ActionCreator/Fields.tsx
> +  postMessageToTargetWindow: "postMessageToTargetWindow",
renamed this

2022-04-20 10:20 UTC, ohansFavour commented
We would need to update the docs for this feature.

cc: @rimildeyjsr @ajinkyakulkarni

2022-04-20 14:42 UTC, rimildeyjsr commented on app/client/src/workers/Actions.test.ts
> +  it("post message to target window works", () => {
done

2022-04-21 04:39 UTC, rimildeyjsr commented on app/client/src/components/editorComponents/ActionCreator/Fields.tsx
> +          defaultParams = `,'https://www.example.com'`;
Added a warning msg for "*"

How do I add the linting error?

2022-04-21 04:41 UTC, rimildeyjsr commented on app/client/src/components/editorComponents/ActionCreator/Fields.tsx
> +      return textSetter(value, currentValue, 1);
I have added an error in the postMessageSaga to raise an error if '*' is passed, do I need any more checks here?

2022-04-21 04:44 UTC, rimildeyjsr commented on app/client/src/entities/DataTree/actionTriggers.ts
> +    targetOrigin: string;
The transfer argument accepts a sequence of [transferable objects](https://developer.mozilla.org/en-US/docs/Glossary/Transferable_objects), and providing a check for these seemed a little complex. Given that this is an optional argument and most of the usage will come from the message and target origin, I made the decision to keep this out of scope for now.

Open to any suggestions or further discussions on this!

2022-04-21 04:54 UTC, rimildeyjsr commented on app/client/src/components/editorComponents/ActionCreator/Fields.tsx
> +          defaultParams = `,'https://www.example.com'`;
Discussed this offline, reaching out to favour to add linting errors here!

2022-04-21 20:27 UTC, Rishabh-Rathod commented
/ok-to-test sha=6c8d79e

2022-04-25 12:24 UTC, rimildeyjsr commented
/ok-to-test sha=50be67a

2022-04-25 12:43 UTC, rimildeyjsr commented on app/client/src/components/editorComponents/ActionCreator/Fields.tsx
> +          defaultParams = `,'https://www.example.com'`;
Added here - https://app.zenhub.com/workspaces/fe-coders-pod-6167d1b64ee5f20014242ab7/issues/appsmithorg/appsmith/13274

2022-04-25 12:47 UTC, rimildeyjsr commented on app/client/src/utils/autocomplete/EntityDefinitions.ts
> +    "!type": "fn(message: unknown, targetOrigin: string, transfer: [any])",
done

2022-04-25 14:16 UTC, rimildeyjsr commented
/ok-to-test sha=f4d5746

2022-04-25 18:50 UTC, Rishabh-Rathod approved these changes
Looks good to me. 

Let's start working on the docs of it. 

@ramsaptami We will need `QA` for this.

2022-06-09 14:49 UTC, ramsaptami commented
- [ ] Boolean, null and number values are read as an error

2022-06-15 07:12 UTC, ramsaptami commented
- [ ] Returning null value as {{null}} does not work
- [ ] Calling an API from a JS and returning those values does not work, i.e. `trigger field --> js --> api` and then return filtered data
- [ ] Calling JS from another JS does not work
- [ ] Using target window link as a variable in a JS object does not work

2022-06-22 10:16 UTC, Rishabh-Rathod approved these changes
LGTM.

2022-06-22 10:17 UTC, Rishabh-Rathod reviewed
Are above QA queries resolved that are mentioned here https://github.com/appsmithorg/appsmith/pull/12551#issuecomment-1156075714 ?

Please mark it as done, if resolved.

2022-06-23 06:20 UTC, rimildeyjsr commented
/ok-to-test sha=bcd16cc

2022-06-23 08:43 UTC, rimildeyjsr commented
/ok-to-test sha=b82b37e

2022-06-23 09:44 UTC, rimildeyjsr commented
/ok-to-test sha=0735bfc

2022-06-24 03:51 UTC, rimildeyjsr commented
/ok-to-test sha=9edc361

2022-06-24 05:42 UTC, Rishabh-Rathod approved these changes

2022-06-24 06:32 UTC, merged