fix: 12456, 12420, 12422 on reconnect modal issues
appsmithorg/appsmith pull request #12569
Opened 2022-04-04 21:30 UTC by haojin111

## Description

> Updating logic of datasource selecton on reconnect datasource modal
> Fixed issue of latest gsheet authentication issue

Fixes #12456 , #12420 , #12422 

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Please see linked issue - manually testing

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-04-05 10:17 UTC, haojin111 commented
https://www.loom.com/share/2d21817ff27b4e2ea666869f0dbee752

2022-04-05 10:17 UTC, haojin111 commented
/ok-to-test sha=5645242

2022-04-05 14:14 UTC, IAmAnubhavSaini requested changes
There is another task, "Reconnect Application" should be "Reconnect", when we go to datasources.

2022-04-05 14:14 UTC, IAmAnubhavSaini commented on app/client/src/pages/Editor/gitSync/ReconnectDatasourceModal.tsx
> +  const shouldShowSuccessMessages = datasource && datasource.isConfigured;
This can be `datasource?.isConfigured`.

2022-04-05 14:15 UTC, IAmAnubhavSaini commented
We need tests too.

2022-04-05 14:31 UTC, IAmAnubhavSaini commented
**Reconnect**

![Screenshot 2022-04-05 at 7 58 30 PM](https://user-images.githubusercontent.com/1573771/161777422-fc7517f6-5b08-4985-bbbc-b60f2a607efd.png)
![Screenshot 2022-04-05 at 8 00 40 PM](https://user-images.githubusercontent.com/1573771/161777433-a022aa24-37a7-47db-bd1c-0fcd411dfd1c.png)

2022-04-07 08:47 UTC, haojin111 commented on app/client/src/pages/Editor/gitSync/ReconnectDatasourceModal.tsx
> +  const shouldShowSuccessMessages = datasource && datasource.isConfigured;
resolved it! please check!

2022-04-07 08:51 UTC, IAmAnubhavSaini submitted a review, later dismissed
Since there is no starting point for state and selector testing, and state being 10k lines, we are not going ahead with redux selector testing.

2022-04-08 05:37 UTC, haojin111 commented
/ok-to-test sha=9992322

2022-04-09 16:43 UTC, haojin111 commented
/ok-to-test sha=60fb8a9

2022-04-11 06:04 UTC, haojin111 commented
/ok-to-test sha=ef48dd8

2022-04-11 14:56 UTC, haojin111 commented
/ok-to-test sha=aa778fc

2022-04-11 16:10 UTC, IAmAnubhavSaini approved these changes

2022-04-11 17:30 UTC, merged