fix:MongoDB Fetch with DBRef - fix  with codec
appsmithorg/appsmith pull request #12571
Opened 2022-04-05 04:07 UTC by leotom2000

## Description

Reactive MongoDB driver does not support fetching DBRef directly.
Applied Codec so that fetching happens.

Fixes #10114

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?

**Manual**
Input:
```
{
_id:61d2afdc27368d17882c8636
inventory:DBRef(stores, 1, testdb)
}
```
Output
 ```
 {
    "_id": "61d2afdc27368d17882c8636",
    "inventory": {
      "$db": "testdb",
      "$ref": "stores",
      "$id": 1
   }
```

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

2022-04-05 11:09 UTC, sumitsum commented
@leotom2000 jfyi, please keep the branch name as either `fix/my_branch_name` or `feature/my_branch_name` to keep up with the guidelines as mentioned here: https://github.com/appsmithorg/appsmith/blob/release/contributions/CodeContributionsGuidelines.md

2022-04-05 11:22 UTC, sumitsum requested changes

2022-04-05 11:22 UTC, sumitsum commented on app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java
> +                            DocumentCodec documentCodec = new DocumentCodec(
Please add a comment here explaining why this coded was required, along with the URL for the Github issue.

2022-04-06 12:46 UTC, leotom2000 commented on app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java
> +                            DocumentCodec documentCodec = new DocumentCodec(
Updated code comments

2022-04-06 13:25 UTC, leotom2000 commented
/ok-to-test sha=94e666b

2022-04-07 09:27 UTC, leotom2000 commented
/ok-to-test sha=94e666b

2022-04-08 07:32 UTC, sumitsum commented
Closing in favor of https://github.com/appsmithorg/appsmith/pull/12670

2022-04-08 07:32 UTC, closed without merging