fix: update custom chart data and type only
appsmithorg/appsmith pull request #12574
Opened 2022-04-05 05:13 UTC by techbhavin

## Description

> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change.

> custom fusion chart is refreshed on change of data to fixed this issue we remove chart config on `componentDidUpdate`

Fixes #11962 

## Type of change

- Bugfix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-04-05 05:13 UTC, techbhavin commented
/ok-to-test sha=bfe03de

2022-04-05 05:43 UTC, Tooluloope requested changes

2022-04-05 05:43 UTC, Tooluloope commented on app/client/src/widgets/ChartWidget/component/index.tsx
> +      ) {
Could you add a cypress test for this?

2022-04-06 11:53 UTC, techbhavin commented
/ok-to-test sha=2a3f996

2022-04-07 06:44 UTC, techbhavin commented
/ok-to-test sha=5080533

2022-04-08 03:45 UTC, techbhavin commented
ok-to-test sha=783d399

2022-04-08 05:06 UTC, techbhavin commented
/ok-to-test sha=602a5eb

2022-04-08 06:18 UTC, techbhavin commented
/ok-to-test sha=f58a2be

2022-04-12 05:47 UTC, YogeshJayaseelan commented
@techbhavin Tested this PR and it is working as expected now. The chart doesn't refresh on choosing different data values on the fusion chart

https://www.loom.com/share/7c5e80c78c0b404ba3e04b88182db780

2022-04-15 05:29 UTC, jsartisan commented on app/client/src/widgets/ChartWidget/component/index.tsx
> +    return config || {};
Don't we need the following config like we were doing previously? Ignore if that is unecessary
```
renderAt: this.chartContainerId,
          width: "100%",
          height: "100%",
          events: {
            dataPlotClick: (evt: any) => {
              const data = evt.data;
              const seriesTitle = this.getSeriesTitle(data);
              this.props.onDataPointClick({
                x: data.categoryLabel,
                y: data.dataValue,
                seriesTitle,
              });
            },
          },
          ```

2022-04-15 06:00 UTC, techbhavin commented on app/client/src/widgets/ChartWidget/component/index.tsx
> +    return config || {};
@jsartisan 
`this.chartInstance` has those settings already so we don't have to declare it again 
in the previous case, we are declaring and re-rendering custom charts every time
to fix that scenario in the current pr, we are updating data only.

2022-04-15 06:02 UTC, jsartisan approved these changes

2022-04-15 10:58 UTC, merged