Fix/readme v2
appsmithorg/appsmith pull request #1262
Opened 2020-10-18 16:51 UTC by pric-appsmith

## Description
Improves  README inline with [this document](https://docs.google.com/document/d/1dFOcF6n85O5feGbJjCJil7ELjiQXngKB9y6X-ms_ZYg/).

Fixes # (issue)
https://github.com/appsmithorg/appsmith/issues/1166

2020-10-19 09:32 UTC, Nikhil-Nandagopal requested changes
Added some comments

2020-10-19 09:32 UTC, Nikhil-Nandagopal commented on README.md
> +  [![GitHub release](https://img.shields.io/github/v/release/appsmithorg/appsmith.svg?logo=GitHub)](https://github.com/appsmithorg/appsmith/releases/latest)
Fix badges with a space between p tag

2020-10-19 09:32 UTC, Nikhil-Nandagopal commented on README.md
> +* **Intellisense**: Write JavaScript faster with Appsmith’s IDE-quality intellisense.
Bring focus to the feature which is to write code instead of IntelliSense which helps a developer write that code

2020-10-19 09:32 UTC, Nikhil-Nandagopal commented on README.md
> +* **One-click deployment**: Deploy your app with a click of a button.
Mention that apps hosting is managed entirely by the platform

2020-10-19 09:32 UTC, Nikhil-Nandagopal commented on README.md
> +* **Trigger APIs**: Connect to any internal or external REST and GraphQL APIs to build dashboards, forms, and workflows.
Push these 2 points higher, maybe right after frontend as a service or ever higher

2020-10-19 09:32 UTC, Nikhil-Nandagopal commented on README.md
> +* **Security**:
Database credentials are stored in an encrypted format and no retrieved/updated by the application is stored by the appsmith platform.

2020-10-19 09:32 UTC, Nikhil-Nandagopal commented on README.md
> +2. Create an Organization
Let's add more steps 
1. Create App
2. Create a query
- Select * from users limit 10
3. Drag a widget
- Connect the widget to the query using JS
- {{ query1.data }}
4. Deploy your app
Got started with your first? Connect your own data now!

2020-10-19 09:32 UTC, Nikhil-Nandagopal commented on README.md
> +2. Create an Organization
Need to link to docs somewhere in the quick start

2020-10-19 09:32 UTC, Nikhil-Nandagopal commented on README.md
> +You can build dashboards, forms, workflows by connecting to any API or Database, and deploy them with one click, ready to be shared with your users, with built-in support for Role-based Access contro
Need some work on explaining appsmith. Maybe more like Hasura i.e
Appsmith gives you drag and drop UI over your databases and API etc. etc.

2020-10-19 09:34 UTC, Nikhil-Nandagopal commented on README.md
> +But if you’d rather check out some real applications that can be built with Appsmith, check below:
Can you come up with 3 really good example apps and tutorials we should have?

2020-10-19 11:10 UTC, mohanarpit commented
@pric-appsmith Minor: Can we bring back the emojis? 😄

2020-10-19 17:00 UTC, pric-appsmith commented on README.md
> +You can build dashboards, forms, workflows by connecting to any API or Database, and deploy them with one click, ready to be shared with your users, with built-in support for Role-based Access contro
Is there in the description section https://github.com/appsmithorg/appsmith/pull/1262/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R21

2020-10-20 13:15 UTC, Nikhil-Nandagopal commented on README.md
> +* **Security**:
AES 256

2020-10-22 12:39 UTC, mohanarpit commented on README.md
> +<img src="https://github.com/appsmithOrg/appsmith/blob/fix/readme-v2/static/UI.gif">
Minor: Can we speed up this gif a little bit? By simply looking at it, I get the impression that the platform is slow and jerky. I understand that the current gif is too fast and hard to understand. Can we find a middle ground?

2020-10-23 09:45 UTC, Nikhil-Nandagopal requested changes
@pric-appsmith added the comments

2020-10-23 09:45 UTC, Nikhil-Nandagopal commented on README.md
> +* **Frontend as a service**: Drag-and-drop to build sophisticated **dashboards** and **workflows, without writing HTML/CSS**. Write Javascript anywhere to transform data. [Read more here.](https://do
or dynamically control widget properties

2020-10-23 09:45 UTC, Nikhil-Nandagopal commented on README.md
> +* **Authentication**: Allow users to authenticate via Google Auth or GitHub Auth.
or build a login page to use your own authentication!

2020-10-23 09:45 UTC, Nikhil-Nandagopal commented on README.md
> +API Support: REST & GraphQL APIs
These are not showing in separate lines

2020-10-23 09:45 UTC, Nikhil-Nandagopal commented on README.md
> -## 🏃‍♀️ Getting Started
Right now, we'll go with a simple demo and example apps. Focus more on getting people to quick start

2020-10-23 09:45 UTC, Nikhil-Nandagopal commented on README.md
> +Hosting: Cloud-hosted & On-premise
Lets have a CTA to jump to quickstart section

2020-10-23 09:45 UTC, Nikhil-Nandagopal commented on README.md
> -* Documentation: [Documentation](https://docs.appsmith.com)
documentation should be upfront in this section and code of conduct can be relegated to the contribution section

2020-10-23 09:45 UTC, Nikhil-Nandagopal commented on README.md
> +3. Explore our [open issues](https://github.com/appsmithorg/appsmith/issues/new/choose)
This link should point to our good first issues

2020-10-23 09:45 UTC, Nikhil-Nandagopal commented on README.md
> +## Contributors
Can we bring back the emoji

2020-10-23 09:45 UTC, Nikhil-Nandagopal commented on README.md
> +2. Learn how to set up your local environment, in our [developer-guide](https://github.com/appsmithorg/appsmith/blob/master/contributions/CodeContributionsGuidelines.md#-setup-for-local-development)
Development guide instead of developer guide?

2020-10-23 09:45 UTC, Nikhil-Nandagopal commented on README.md
> +3. Navigate to `Pages -> Queries -> Mock Database` and follow these steps to create a new query -
Click on the + icon next to the query section and add a new query for the mock db?

2020-10-23 09:45 UTC, Nikhil-Nandagopal commented on README.md
> +    2. Name the query as `usersQuery`.
change the order to name the query, write the query and add run the query.
Also go to settings and enable the onPageLoad option

2020-10-23 09:45 UTC, Nikhil-Nandagopal commented on README.md
> +4. Navigate to `Pages -> Widgets` and create a table `UsersTable` by dragging-and-droping the table-widget.
Users can now just hit the + Add widget on the query page to add the table widget with the query connected

2020-10-23 09:45 UTC, Nikhil-Nandagopal commented on README.md
> +5. Navigate to `Table Data` property of `UsersTable`, and fill in `{{usersQuery.data}}` to display thq query's results in this table.
Here you can explain that the table is connected to the query using JS

2020-10-23 09:45 UTC, Nikhil-Nandagopal commented on README.md
> +You just built your first app with mock data. Connect your own data to build real apps. [Read more here.](https://docs.appsmith.com/)
What do you think about side by side also having a high fidelity version of these steps in the docs with images and gifs and linking to it for users who want clearer instructions?

2020-10-23 10:29 UTC, pric-appsmith commented on README.md
> +4. Navigate to `Pages -> Widgets` and create a table `UsersTable` by dragging-and-droping the table-widget.
Still don't see an option to add a widget on the query page on my cloud setup

2020-10-23 10:30 UTC, pric-appsmith commented on README.md
> +5. Navigate to `Table Data` property of `UsersTable`, and fill in `{{usersQuery.data}}` to display thq query's results in this table.
I think that it's clear because setting the data property to a query effectively connecting the two.

2020-10-23 10:37 UTC, pric-appsmith commented on README.md
> +* **Authentication**: Allow users to authenticate via Google Auth or GitHub Auth.
Changing to `Supports OAuth` to drive that message, instead them being able to create forms

2020-10-23 10:42 UTC, pric-appsmith commented on README.md
> +2. Learn how to set up your local environment, in our [developer-guide](https://github.com/appsmithorg/appsmith/blob/master/contributions/CodeContributionsGuidelines.md#-setup-for-local-development)
used `developer` because it's a guide `for` developers

2020-10-23 10:45 UTC, pric-appsmith commented on README.md
> +4. Navigate to `Pages -> Widgets` and create a table `UsersTable` by dragging-and-droping the table-widget.
Ref https://theappsmith.slack.com/archives/C01CFTXD0N8/p1603449532003400 IMO we should stick with the current step because 
1. user sees the add widget option only after running the query, even though the query gets saved w/o running it
2. after clicking on `add widget`, I'm taken to the page which has multiple widgets with no pointers on how to go about choosing the widget that I want to connect

2020-10-23 10:48 UTC, pric-appsmith commented on README.md
> +You just built your first app with mock data. Connect your own data to build real apps. [Read more here.](https://docs.appsmith.com/)
Yes, we should definitely have the same quickstart section in the docs with high fidelity images.

2020-10-23 10:55 UTC, pric-appsmith commented on README.md
> +Hosting: Cloud-hosted & On-premise
Not able to link it right, most likely because of the emoji in the header of Quickstart. Can you please help with this? @Nikhil-Nandagopal

2020-10-23 11:07 UTC, Nikhil-Nandagopal commented on README.md
> +Hosting: Cloud-hosted & On-premise
Done

2020-10-27 06:54 UTC, areyabhishek commented
Leaving my global comments here:
1. We need to reduce the number of files that show up before the user can read a single line of the readme. Today the readme is an entire scroll away.
2. Please remove the logo(nobody cares about our logo except for us :)) and reduce the empty space below it which doesn't say much. 
3. Does the line of GitHub badges really need to be the first thing someone reads after our name? They say nothing of value and only increase scroll length
4. Why does Appsmith exist should be the very first line of the read me.
So the first thing a user should read is some variation of this: **Appsmith** was created to build custom internal tools really quickly. Our visual MVC Framework gives you UI widgets, DB integrations, API connectors, and user management features that reduce repetitive work. The current line says things that you don't have to do and then the next line explains what Appsmith is.

2020-10-27 12:00 UTC, pric-appsmith commented
@areyabhishek 

> We need to reduce the number of files that show up before the user can read a single line of the readme. Today the readme is an entire scroll away.

Agreed.

> Please remove the logo(nobody cares about our logo except for us :)) and reduce the empty space below it which doesn't say much.

It's true that readers don't care about the logo. However, IMO -
1. The logo sets the stage for the details. It's a good starter.
2. To compare the options - logo+Appsmith-text against Appsmith-text written on an image. The former, IMO, is better simply because picture+text looks better than just text - when both of them are images. Picture is easier to remember. Also both the options are currently taking roughly the same amount of screen-space, so we aren't saving users from an extra scroll.
3. The proposal of having no image at all - an only a Heading-text saying Appsmith, is IMO, going overboard because GitHub users are used to seeing a logo, a byline, and then the details; and hence used to scrolling away quickly from there on.
To summarize - I think we should have the logo, may be smaller in size.

> Does the line of GitHub badges really need to be the first thing someone reads after our name? They say nothing of value and only increase scroll length

I agree. I refrained from proposing a rethinking of them earlier because I am not entirely sure of how GitHub users judge repositories since I've not been an open-source contributor. I'll take the liberty to share my opinion on them now. 

- From my experience of being a user of open-source products, I can say that I'd want to first know whether the repository is useful for me, and second the legalities around forking it to build something on top of it. 
- Badges should exist only when they convey something of value, and when those badges are the best way to give that value. Going by this principle, maybe all current badges can be gotten rid of.
- I feel the same about emojis :)

> Why does Appsmith exist should be the very first line of the read me.
> So the first thing a user should read is some variation of this: Appsmith was created to build custom internal tools really quickly. Our visual MVC Framework gives you UI widgets, DB integrations, API connectors, and user management features that reduce repetitive work. The current line says things that you don't have to do and then the next line explains what Appsmith is.

Agreed. I'll come up with the changes.

> Also, we use MVC in the first line, but then don't expand on it. It feels like it was just used for the sake of it.

I absolutely agree. @Nikhil-Nandagopal and I had had a quick conversation on the same lines - that since the MVC bit about it is not clear, IMO, it is rather confusing as the introductory line. If you can may be help me understand briefly the discussions the Appsmith team has had regarding this phrase - how and why they came up with it, etc., it'll help me come up with the changes, and also give an opinion on whether we should use the phrase at all. As of today, I think we shouldn't.

2020-10-27 12:09 UTC, Nikhil-Nandagopal commented on README.md
> +* **Authentication**: Allow users to authenticate via Google Auth or GitHub Auth.
@pric-appsmith that seems like a different message. Giving someone OAuth is not the same as them being able to use their own OAuth. Plus we support user name password login and OAuth authentication mechanisms.

2020-10-27 18:07 UTC, areyabhishek commented
> @areyabhishek
> 
> > We need to reduce the number of files that show up before the user can read a single line of the readme. Today the readme is an entire scroll away.
> 
> Agreed.
> 
> > Please remove the logo(nobody cares about our logo except for us :)) and reduce the empty space below it which doesn't say much.
> 
> It's true that readers don't care about the logo. However, IMO -
> 
> 1. The logo sets the stage for the details. It's a good starter.
> 2. To compare the options - logo+Appsmith-text against Appsmith-text written on an image. The former, IMO, is better simply because picture+text looks better than just text - when both of them are images. Picture is easier to remember. Also both the options are currently taking roughly the same amount of screen-space, so we aren't saving users from an extra scroll.
> 3. The proposal of having no image at all - an only a Heading-text saying Appsmith, is IMO, going overboard because GitHub users are used to seeing a logo, a byline, and then the details; and hence used to scrolling away quickly from there on.
>    To summarize - I think we should have the logo, may be smaller in size.
Make sense.

> > Does the line of GitHub badges really need to be the first thing someone reads after our name? They say nothing of value and only increase scroll length
> 
> I agree. I refrained from proposing a rethinking of them earlier because I am not entirely sure of how GitHub users judge repositories since I've not been an open-source contributor. I'll take the liberty to share my opinion on them now.
> 
> * From my experience of being a user of open-source products, I can say that I'd want to first know whether the repository is useful for me, and second the legalities around forking it to build something on top of it.
> * Badges should exist only when they convey something of value, and when those badges are the best way to give that value. Going by this principle, maybe all current badges can be gotten rid of.
We'll need a way to point users towards Discord so that badge can probably be pushed down. But these badges aren't very readable. An actual button with Discord icon would have more impact.

There's no clear call to action on the page and our main objective is to get the user to try Appsmith cloud. So what about a single CTA button that says "Try Appsmith" and links to the sign up page? 

> * I feel the same about emojis :)
Today they serve as guides for the users that are scanning and scrolling. Websites use icons to organize and guide a reader who is scanning. Without these visual breaks, the page just looks monotonous. Our choice icons could be better for sure.

> > Why does Appsmith exist should be the very first line of the read me.
> > So the first thing a user should read is some variation of this: Appsmith was created to build custom internal tools really quickly. Our visual MVC Framework gives you UI widgets, DB integrations, API connectors, and user management features that reduce repetitive work. The current line says things that you don't have to do and then the next line explains what Appsmith is.
> 
> Agreed. I'll come up with the changes.
> 
> > Also, we use MVC in the first line, but then don't expand on it. It feels like it was just used for the sake of it.
> 
> I absolutely agree. @Nikhil-Nandagopal and I had had a quick conversation on the same lines - that since the MVC bit about it is not clear, IMO, it is rather confusing as the introductory line. If you can may be help me understand briefly the discussions the Appsmith team has had regarding this phrase - how and why they came up with it, etc., it'll help me come up with the changes, and also give an opinion on whether we should use the phrase at all. As of today, I think we shouldn't.

This is why we've been discussing MVC:
1. Users need to understand the architecture of how things are built in Appsmith so that they can understand how things interact with each other. Some devs described Appsmith to be similar in architecture like Angular or RoR. We thought describing Appsmith as MVC is a potential shortcut
2. In Appsmith world, model=data sources, view=widgets, controller=JS logic(we are building a dedicated section for JS logic)
3. So the idea was if a developer understands these concepts, they'll be able to build quicker and debug faster. They'll never have to think, 'So where do I go fix this problem?'. This architecture will also help us design features in a way that doesn't break their mental models

2020-10-31 07:32 UTC, pric-appsmith commented on README.md
> +Learn more about Appsmith below, or [quickly start building on your own](#%EF%B8%8F-quickstart).
@Nikhil-Nandagopal The sentence `Learn more about...` is abrupt here. Since the introduction has barely started - only 2 sentences have been spoken. IMO this should not be here. The user just started understanding the Appsmith-offering, and suddenly is asked to make the choice of going to Quickstart.

2020-10-31 07:33 UTC, pric-appsmith commented on README.md
> +<img src="https://github.com/appsmithOrg/appsmith/blob/fix/readme-v2/static/UI.gif">
@Nikhil-Nandagopal ^

2020-10-31 07:34 UTC, pric-appsmith commented on README.md
> +  </a>&nbsp;
IMO there should also be a License Badge. @areyabhishek @mohanarpit @Nikhil-Nandagopal  Thoughts?

2020-11-02 09:46 UTC, pric-appsmith commented
@Nikhil-Nandagopal Resolved comments. Please see if it can be approved.

2020-11-02 10:05 UTC, Nikhil-Nandagopal submitted a review, later dismissed

2020-11-02 10:55 UTC, merged