feat: git delete branch | FE
appsmithorg/appsmith pull request #12681
Opened 2022-04-07 12:06 UTC by IAmAnubhavSaini

## Description

This PR cleans up git branch popup, and introduces a new feature: delete branch.

Fixes #12612, #12677,  #12074

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

## How Has This Been Tested?

Tests will be provided.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-04-10 12:14 UTC, IAmAnubhavSaini commented
/ok-to-test sha=258ccf9

2022-04-11 00:59 UTC, IAmAnubhavSaini commented
**Issue while installing packages**

<img width="1169" alt="Screenshot 2022-04-11 at 6 26 35 AM" src="https://user-images.githubusercontent.com/1573771/162648523-de6d705b-33da-4301-878f-453831305e61.png">

2022-04-11 01:45 UTC, Aishwarya-U-R commented
/ok-to-test sha=258ccf9

2022-04-12 14:35 UTC, IAmAnubhavSaini commented
/ok-to-test sha=1e95214

2022-04-12 22:42 UTC, IAmAnubhavSaini commented
https://user-images.githubusercontent.com/1573771/163066371-a8e7fb9d-eaf3-4e37-be6e-22e600fdfe9f.mov

<img width="324" alt="Screenshot 2022-04-13 at 4 10 10 AM" src="https://user-images.githubusercontent.com/1573771/163066417-0710ee76-38d8-49a1-ab11-b1753c83e91d.png">
<img width="288" alt="Screenshot 2022-04-13 at 4 10 20 AM" src="https://user-images.githubusercontent.com/1573771/163066418-5a98e451-8203-4a68-b340-af7785a5287c.png">
<img width="302" alt="Screenshot 2022-04-13 at 4 10 26 AM" src="https://user-images.githubusercontent.com/1573771/163066421-cf617372-1888-421d-9c96-112c12e001d7.png">

2022-04-13 05:10 UTC, ankitakinger commented on app/client/src/pages/Editor/gitSync/components/BetaTag.test.tsx
> +    expect(actual).toHaveStyleRule("border", "1px solid #191919");
Can we use `Colors.COD_GRAY` here?

2022-04-13 05:14 UTC, ankitakinger commented on app/client/src/pages/Editor/gitSync/components/BranchList.tsx
>    & span {
since span is changed to div below, the identifier here should also change.

2022-04-13 05:18 UTC, ankitakinger requested changes
Will this file be re-written?
app/client/src/pages/Editor/gitSync/components/BranchList.test.tsx

2022-04-13 05:27 UTC, ankitakinger commented on app/client/src/pages/Editor/gitSync/hooks/useSSHKeyPair.ts
> +} from "../../../../actions/gitSyncActions";
can use `actions/gitSyncActions` and `selectors/gitSyncSelectors` instead?

2022-04-13 05:31 UTC, IAmAnubhavSaini commented on app/client/src/pages/Editor/gitSync/components/BetaTag.test.tsx
> +    expect(actual).toHaveStyleRule("border", "1px solid #191919");
I am testing for exact value.

2022-04-13 05:33 UTC, IAmAnubhavSaini commented on app/client/src/pages/Editor/gitSync/hooks/useSSHKeyPair.ts
> +} from "../../../../actions/gitSyncActions";
I have already updated similar code in other places too. Need to push that commit.

2022-04-13 05:36 UTC, IAmAnubhavSaini commented
> Will this file be re-written? app/client/src/pages/Editor/gitSync/components/BranchList.test.tsx

Check utils test file. The function moved and so did the tests.

2022-04-13 06:55 UTC, IAmAnubhavSaini commented
/ok-to-test sha=cb5a188

2022-04-13 10:03 UTC, ankitakinger approved these changes
LGTM

2022-04-13 10:03 UTC, merged