feat: Container Jump Improvements and Code for tracking Container Jumps
appsmithorg/appsmith pull request #12686
Opened 2022-04-07 14:20 UTC by rahulramesha

## Description
This PR is to optimise container Jumps and add code to track user behaviour on container jumps.
Changes:
* moving Container jump thresholds to absolute values
* adding additional check for container jump that the mouse pointer has to be on the container before jumping
* Additional code to track container jumps from main Canvas.

Fixes #12690
Fixes #11487

## Type of change
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Manual and jest

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>

    // Code coverage diff between base branch:release and head branch: containerJumpOptimization 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 56.34 **(0)** | 37.72 **(-0.02)** | 35.97 **(0.02)** | 56.56 **(0)**
 :red_circle: | app/client/src/components/designSystems/appsmith/PositionedContainer.tsx | 100 **(0)** | 82.54 **(-1.33)** | 100 **(0)** | 100 **(0)**
 :sparkles: :new: | **app/client/src/pages/common/CanvasArenas/hooks/ContainerJumpMetric.ts** | **88.89** | **100** | **75** | **88.89**
 :red_circle: | app/client/src/pages/common/CanvasArenas/hooks/useBlocksToBeDraggedOnCanvas.ts | 89.44 **(-5.49)** | 76.47 **(-10.74)** | 90.63 **(0.63)** | 89.26 **(-6.09)**
 :red_circle: | app/client/src/pages/common/CanvasArenas/hooks/useCanvasDragging.ts | 83.64 **(-1.25)** | 67.05 **(-0.63)** | 84.38 **(0)** | 84.19 **(-1.43)**
 :green_circle: | app/client/src/utils/WidgetPropsUtils.tsx | 88.66 **(0.62)** | 76 **(0)** | 85.71 **(1.09)** | 85.33 **(0.82)**
 :red_circle: | app/client/src/utils/hooks/useReflow.ts | 81.69 **(-9.49)** | 60.61 **(-16.06)** | 100 **(0)** | 86.36 **(-5.7)**
 :red_circle: | app/client/src/widgets/SelectWidget/component/index.tsx | 15.32 **(-0.55)** | 0 **(0)** | 4.55 **(0)** | 15.93 **(-0.59)**</details>

2022-04-07 16:19 UTC, rahulramesha commented
/ok-to-test sha=e0ceade

2022-04-08 10:43 UTC, riodeuno commented on app/client/src/utils/WidgetPropsUtils.test.tsx
> +    const mouseEvent = ({
Please add another test case for really small offset values (1 or 2)

2022-04-08 14:40 UTC, rahulramesha commented on app/client/src/utils/WidgetPropsUtils.test.tsx
> +    const mouseEvent = ({
Added a test, for testing low Offset numbers, that generates negative values of mouse Positions, which is expected.

Also, today I learnt, javascript has `-0`.

2022-04-11 07:10 UTC, riodeuno commented on app/client/src/pages/common/CanvasArenas/hooks/useBlocksToBeDraggedOnCanvas.ts
> +  //This method is called whenever a there is a canvas change
canvas (DropTarget)

2022-04-11 07:13 UTC, riodeuno commented on app/client/src/pages/common/CanvasArenas/hooks/useBlocksToBeDraggedOnCanvas.ts
> +    canvasId: string,
Let's rename this to make sense of what this value containers. `dropTargetWidgetId`

2022-04-11 07:13 UTC, riodeuno commented on app/client/src/pages/common/CanvasArenas/hooks/useBlocksToBeDraggedOnCanvas.ts
> +  //This method is called whenever a there is a canvas change
Also, what does this method do?

2022-04-11 07:27 UTC, riodeuno commented on app/client/src/utils/WidgetPropsUtils.tsx
> +  const mouseTop = Math.round(
Please verify if Math.floor would be appropriate here.

2022-04-11 07:28 UTC, riodeuno requested changes
A few changes requested. The rest looks good to me.

2022-04-11 12:38 UTC, rahulramesha commented
@riodeuno , addressed most of the review comments, `useReducer` did not work in this situation because, placing it inside the Instance causes it to re-render whenever the value changes. Decided to convert it into a class instead for better readability.

2022-04-11 12:59 UTC, riodeuno approved these changes

2022-04-13 06:42 UTC, rahulramesha commented
/ok-to-test sha=161c6c5

2022-04-13 08:39 UTC, marks0351 approved these changes

2022-04-13 10:47 UTC, vivekverma2312 commented
@rahulramesha Tested and working fine.

2022-04-13 14:57 UTC, merged