fix: handle editor value update
appsmithorg/appsmith pull request #12726
Opened 2022-04-08 13:26 UTC by techbhavin

## Description

RichTextEditor isn’t loading at the start to fix that issue `textChange` event prevents while initializations of RichTextEditor.

Fixes #11624 

## Type of change

- Bugfix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-04-08 13:26 UTC, techbhavin commented
/ok-to-test sha=aa00af7

2022-04-10 19:56 UTC, lublak commented
@techbhavin there is something like this:

```js
editor.on('init', function (e) {
  editor.setContent(content);
});
```

2022-04-11 06:12 UTC, techbhavin commented
/ok-to-test sha=aa00af7

2022-04-12 06:10 UTC, SatishGandham reviewed
Why is it not changing?
We pass the value prop, why is it not changing when the value prop changes?

2022-04-12 08:54 UTC, techbhavin commented
As per my observation, in the initial render when props are changing, `editorRef.current` is not there, but when `editorRef.current` changes, `props.value` is stable and that will not effect on `useEffect`

<img width="975" alt="image" src="https://user-images.githubusercontent.com/58818598/162921819-e6686ae5-3369-49f7-b8bf-7cd333d4ea0a.png">

2022-04-14 04:14 UTC, SatishGandham approved these changes

2022-04-20 04:33 UTC, shwetha-ramesh commented
@techbhavin tested this on Windows machine on Chrome browser. This issue is still partially reproducible. 
https://loom.com/share/cbacf59b9c204c00abab01cfbad0277f

2022-04-21 08:12 UTC, techbhavin commented
/ok-to-test sha=0c195ec

2022-04-22 06:57 UTC, techbhavin commented
/ok-to-test sha=76e09e3

2022-04-22 12:12 UTC, SatishGandham requested changes

2022-04-22 12:12 UTC, SatishGandham commented on app/client/src/widgets/RichTextEditorWidget/component/index.tsx
> +    const timeOutId = setTimeout(() => props.onValueChange(value.text), 1000);
Why are you waiting a second to trigger the update?

2022-04-22 12:21 UTC, SatishGandham commented on app/client/src/widgets/RichTextEditorWidget/component/index.tsx
> +    const timeOutId = setTimeout(() => props.onValueChange(value.text), 1000);
@Tooluloope 
Why did we add a one second debounce. Update meta property is already debounced.

2022-04-22 12:22 UTC, techbhavin commented on app/client/src/widgets/RichTextEditorWidget/component/index.tsx
> +    const timeOutId = setTimeout(() => props.onValueChange(value.text), 1000);
to prevent triggering onValueChange method when the user typing. it will call when the user takes a pause while typing

2022-04-22 12:22 UTC, SatishGandham approved these changes

2022-04-25 06:46 UTC, shwetha-ramesh commented
@techbhavin re-tested this on Windows machine on Chrome browser. Working as expected now.
https://loom.com/share/ee17b306517b436888d307aaada35273

Moving to Done.

2022-04-25 07:02 UTC, merged

2022-05-26 10:06 UTC, Rishabh-Rathod commented on app/client/src/widgets/RichTextEditorWidget/component/index.tsx
> +    const timeOutId = setTimeout(() => props.onValueChange(value.text), 1000);
Why do we want to prevent calling `onValueChange` when the user is typing? 
I believe that will cause the local state to update unexpectedly as per current logic.

@techbhavin I would like to understand why we need the local state for the RTE component and how is it different from the input widget?

2022-05-26 10:09 UTC, Tooluloope commented on app/client/src/widgets/RichTextEditorWidget/component/index.tsx
> +    const timeOutId = setTimeout(() => props.onValueChange(value.text), 1000);
- If we leave it solely to the meta property to provide the value, once a new value is provided, the cursor would shift to the beginning, which is bad UX.