feat: Disable js toggle button if field is not empty
appsmithorg/appsmith pull request #12754
Opened 2022-04-11 06:53 UTC by aswathkk

## Description

Disable the JS toggle button if the value is non-empty and non-default value.
This is done to avoid the loss of the user's code on accidentally clicking the JS toggle button.

Fixes #10833 

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Manual

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-06-06 17:37 UTC, rahulramesha requested changes

2022-06-06 17:37 UTC, rahulramesha commented on app/client/src/pages/Editor/PropertyPane/PropertyControl.tsx
> +    if (
Could you please add some comments here and the condition below

2022-06-06 17:37 UTC, rahulramesha commented on app/client/src/pages/Editor/PropertyPane/PropertyControl.tsx
> +                content="A dynamic or invalid value cannot be represented in the UI mode. Please update the value or clear the value to toggle back to UI mode."
Could you use `messages.ts` to store the text and access it here.

2022-06-07 07:01 UTC, aswathkk commented on app/client/src/pages/Editor/PropertyPane/PropertyControl.tsx
> +    if (
done. Can you check?

2022-06-07 07:15 UTC, rahulramesha submitted a review, later dismissed

2022-06-07 10:55 UTC, aswathkk commented
/ok-to-test sha=181b256

2022-06-09 07:07 UTC, Sripriya93 commented
Checkbox group Widget "Options" JS toggle is affected by this feature.

https://images.zenhubusercontent.com/275993885/ffd69a3b-843f-41d2-8a8b-96ade483f6b6/js_toggle___editor___appsmith___9_june_2022.mp4

2022-06-10 06:59 UTC, aswathkk commented
/ok-to-test sha=4b87d7c

2022-06-13 08:14 UTC, aswathkk commented
/ok-to-test sha=57c07e9

2022-06-16 05:39 UTC, aswathkk commented
/ok-to-test sha=1a2da42

2022-06-16 09:29 UTC, rahulramesha approved these changes

2022-06-16 09:47 UTC, merged