fix: Table derived properties removal on js toggle off.
appsmithorg/appsmith pull request #12840
Opened 2022-04-12 09:06 UTC by yaldram

## Description

- Remove Table `derivedColumn` properties when js toggle is turned off for a property.

Fixes #10037 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Tested manually on the canvas.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/bindPathList-error 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 56.43 **(0)** | 37.91 **(-0.01)** | 35.82 **(0)** | 56.66 **(-0.01)**
 :red_circle: | app/client/src/sagas/WidgetOperationUtils.ts | 67.39 **(-0.97)** | 44.55 **(-0.3)** | 65.28 **(-1.86)** | 66.93 **(-0.96)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.71 **(-0.23)** | 40.83 **(-0.84)** | 36.21 **(0)** | 56.74 **(-0.25)**</details>

2022-04-12 09:08 UTC, yaldram commented
@sbalaji1192 I have handled the case for js toggle on and off on the Table `derivedColumn` properties in align with your discussion yesterday.
I also started investigating the `computed` fields bindingList problem I understood the code flow but there are some edge cases there. I will get back to you on the same once I have some bandwidth. In the meantime we can review and merge the above changes / fix.  Thanks :)

2022-04-14 04:40 UTC, riodeuno commented on app/client/src/sagas/WidgetOperationSagas.tsx
> +    if (_.startsWith(propertyPath, "primaryColumns")) {
If I understand this correctly, what we're trying to achieve is to remove `derivedColumns` as well when removing the `primaryColumns` path. Am I right?
Maybe we can put this code in a function which returns what to reject from the `dynamicBindingPathList` so that we can simply call the function and use the `_.reject`. This way, we can make sure to add unit tests for the function as well.

2022-04-14 05:05 UTC, yaldram commented on app/client/src/sagas/WidgetOperationSagas.tsx
> +    if (_.startsWith(propertyPath, "primaryColumns")) {
Yes, @riodeuno. Thanks for your suggestion will move this to a function.

2022-04-27 05:59 UTC, riodeuno commented on app/client/src/widgets/TableWidget/widget/propertyUtils.ts
> +    propertyValue.buttonColor = Colors.GREEN;
@jsartisan @keyurparalkar Will this effect the application of themeing?

2022-04-27 18:19 UTC, sbalaji1192 commented on app/client/src/sagas/WidgetOperationSagas.tsx
> +export function removeDynamicBindingProperties(
Could you move this function to widgetOperationsUtils file?

2022-04-28 05:06 UTC, yaldram commented on app/client/src/sagas/WidgetOperationSagas.tsx
> +export function removeDynamicBindingProperties(
Done.

2022-04-28 10:22 UTC, sbalaji1192 submitted a review, later dismissed
LGTM. Please connect with pawan or keyur. As they might have changed this function in the theming branch

2022-05-05 05:13 UTC, riodeuno commented on app/client/src/widgets/TableWidget/component/TableUtilities.tsx
> +  // Object.keys(widgetProperties.defaultProperties).map((propertyKey) => {
@yaldram Let's remove this commented out code, if it is no longer necessary.

2022-05-05 05:14 UTC, yaldram commented on app/client/src/widgets/TableWidget/component/TableUtilities.tsx
> +  // Object.keys(widgetProperties.defaultProperties).map((propertyKey) => {
I am planning to close this PR and create a new Pull Request, I see some of my changes are not present after the theming got merged.

2022-05-05 05:16 UTC, riodeuno commented on app/client/src/sagas/WidgetOperationUtils.ts
> +export function removeDynamicBindingProperties(
@yaldram Do we have unit tests for this function? If not, please add one.

2022-05-05 05:16 UTC, riodeuno requested changes
@yaldram Please update the unit tests and remove the commented code.

2022-05-05 05:17 UTC, yaldram commented on app/client/src/sagas/WidgetOperationUtils.ts
> +export function removeDynamicBindingProperties(
Sure we had I will add in the new PR.

2022-05-05 05:29 UTC, closed without merging