fix : handle default value in Multiselect and select widget
appsmithorg/appsmith pull request #12876
Opened 2022-04-13 06:32 UTC by techbhavin

## Description

> fix issue of default value is displayed on  Select/multi-select/TreeSelect/Multi tree select widget even it is not available in widget options list

Fixes #12225

## Type of change

- Bugfix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-04-13 06:33 UTC, techbhavin commented
/ok-to-test sha=76b235c

2022-04-14 04:03 UTC, techbhavin commented
/ok-to-test sha=76b235c

2022-04-18 06:12 UTC, techbhavin commented
/ok-to-test sha=9d17b19

2022-04-19 05:26 UTC, ashit-rath requested changes
Please update the title of the PR to give more context and add cypress tests.

2022-04-19 05:26 UTC, ashit-rath commented on app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx
> +
This solution wouldn't resolve the issue completely.
The `selectedOptions` should always have the correct options from the start and don't need to be filtered explicitly by using `intersectionBy` .
The reason for this is, as the `selectedOptionValue` is derived from `selectedOptionValueArr` and these two are used to compute other values (`selectedOptionLabels`, `selectedOptionValues`). If we have to explicitly filter before using then we would have to repeat this logic everywhere.
So my recommendation is to fix it at the source i.e `selectedOptionValueArr` and everything would fall in order.

2022-04-19 05:26 UTC, ashit-rath commented on app/client/src/widgets/SelectWidget/widget/index.tsx
> +    const showValue = this.props.serverSideFiltering || selectedIndex !== -1;
You would have to alter the logic of your solution here as well
`selectedOptionLabel` and `selectedOptionValue` would still show that value

2022-04-20 06:34 UTC, techbhavin commented
@somangshu  @dilippitchika  @ashit-rath 

closing this PR. a related issue is covered is PR[#13079](https://github.com/appsmithorg/appsmith/pull/13079)

2022-04-20 06:34 UTC, closed without merging