fix: Reset app, page and widget details when switching between apps
appsmithorg/appsmith pull request #12890
Opened 2022-04-13 07:39 UTC by arunvjn

## Description
When switching between apps, we do not reset the widgets state in the reducer causing the widgets from other apps to show up in the omnibar. 
This was working fine earlier because used to do a full reload while launching an app in edit mode.

Fixes #12871 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manual

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-04-13 07:41 UTC, arunvjn commented
/ok-to-test sha=354f6ea

2022-04-13 07:58 UTC, arunvjn commented
/ok-to-test sha=cf17168

2022-04-13 10:09 UTC, arunvjn commented
/ok-to-test sha=80cad18

2022-04-14 02:56 UTC, arunvjn commented
/ok-to-test sha=2eca199

2022-04-14 05:57 UTC, arunvjn commented
/ok-to-test sha=c7c227b

2022-04-14 05:58 UTC, akash-codemonk requested changes

2022-04-14 05:58 UTC, akash-codemonk commented on app/client/src/reducers/uiReducers/applicationsReducer.tsx
> +  [ReduxActionTypes.RESET_APPLICATION]: () => initialState,
Do we want to reset the whole reducer to it's initial state? This also resets the application list stored here.

2022-04-14 08:20 UTC, arunvjn commented
/ok-to-test sha=bb97d4b

2022-04-14 08:25 UTC, arunvjn commented on app/client/src/reducers/uiReducers/applicationsReducer.tsx
> +  [ReduxActionTypes.RESET_APPLICATION]: () => initialState,
Not sure if we need the application list when were are in edit/view mode. 
We fetch application list every time we visit the dashboard as well. 
I have remove it for now since we do not need it to fix this particular issue. Will add that change in a different PR.

2022-04-14 10:14 UTC, akash-codemonk submitted a review, later dismissed

2022-04-14 11:25 UTC, arunvjn commented
/ok-to-test sha=f9950d1

2022-04-14 16:34 UTC, arunvjn commented
/ok-to-test sha=1a7b327

2022-04-15 03:47 UTC, arunvjn commented
/ok-to-test sha=65dcb4e

2022-04-15 04:31 UTC, arunvjn commented
/ok-to-test sha=65dcb4e

2022-04-15 05:40 UTC, akash-codemonk approved these changes

2022-04-15 05:40 UTC, merged