fix: Firestore where condition issue
appsmithorg/appsmith pull request #12929
Opened 2022-04-14 10:48 UTC by leotom2000

## Description
Firestore Unit test for testing Array

Fixes #6060

## Type of change

- Added Unit Test

## How Has This Been Tested?

Added Unit test

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

2022-04-18 10:50 UTC, sumitsum requested changes

2022-04-18 10:50 UTC, sumitsum commented on app/server/appsmith-plugins/firestorePlugin/src/test/java/com/external/plugins/FirestorePluginTest.java
> +import java.util.*;
Please replace it with specific classes that need to be imported. In general we don't want to use wild card import statements because of the following: https://stackoverflow.com/questions/147454/why-is-using-a-wild-card-with-a-java-import-statement-bad

2022-04-18 10:50 UTC, sumitsum commented on app/server/appsmith-plugins/firestorePlugin/src/test/java/com/external/plugins/FirestorePluginTest.java
> +        setValueSafelyInFormData(configMap, COMMAND, "GET_DOCUMENT");
where condition is only evaluated when command is `GET_COLLECTION`. IMO, this test case does ignores the where condition completely. Can you please update the command to `GET_COLLECTION` ?

2022-04-18 10:50 UTC, sumitsum commented on app/server/appsmith-plugins/firestorePlugin/src/test/java/com/external/plugins/FirestorePluginTest.java
> +        param.setValue("[333]");
The parameter here should be non-arrray i.e. it should be "333" instead of `[333]`. Ref: https://firebase.google.com/docs/firestore/query-data/queries#array_membership

2022-04-18 10:50 UTC, sumitsum commented on app/server/appsmith-plugins/firestorePlugin/src/test/java/com/external/plugins/FirestorePluginTest.java
> +    public void testArrayContainsWhereConditional() {
Same comments as above.

2022-04-18 10:50 UTC, sumitsum commented on app/server/appsmith-plugins/firestorePlugin/src/test/java/com/external/plugins/FirestorePluginTest.java
> +        setValueSafelyInFormData(configMap, COMMAND, "GET_DOCUMENT");
Same as above - command should be `GET_COLLECTION`.

2022-04-18 10:50 UTC, sumitsum commented on app/server/appsmith-plugins/postgresPlugin/src/main/java/com/external/plugins/PostgresPlugin.java
> +        //JDBC override parameter for resolving Cast Errors on PostgreSQL
This change should not be here.

2022-04-18 10:50 UTC, sumitsum commented on app/server/appsmith-plugins/postgresPlugin/src/test/java/com/external/plugins/PostgresPluginTest.java
> +    @Test
This change should not be here.

2022-04-18 10:59 UTC, sumitsum commented
@leotom2000 can you please edit `getCollection.json` file to add ARRAY_CONTAINS and ARRAY_CONTAINS_ANY operators ?

2022-04-19 10:11 UTC, leotom2000 commented on app/server/appsmith-plugins/firestorePlugin/src/test/java/com/external/plugins/FirestorePluginTest.java
> +import java.util.*;
Resolved, updated the IDE settings too

2022-04-19 19:08 UTC, leotom2000 commented on app/server/appsmith-plugins/firestorePlugin/src/test/java/com/external/plugins/FirestorePluginTest.java
> +        param.setValue("[333]");
resolved

2022-04-19 19:25 UTC, leotom2000 commented on app/server/appsmith-plugins/firestorePlugin/src/test/java/com/external/plugins/FirestorePluginTest.java
> +        setValueSafelyInFormData(configMap, COMMAND, "GET_DOCUMENT");
Updated to GET_COLLECTION

2022-04-19 19:26 UTC, leotom2000 commented on app/server/appsmith-plugins/firestorePlugin/src/test/java/com/external/plugins/FirestorePluginTest.java
> +        setValueSafelyInFormData(configMap, COMMAND, "GET_DOCUMENT");
Updated to GET_COLLECTION

2022-04-19 19:36 UTC, leotom2000 commented on app/server/appsmith-plugins/postgresPlugin/src/main/java/com/external/plugins/PostgresPlugin.java
> +        //JDBC override parameter for resolving Cast Errors on PostgreSQL
Seems that was from another PR,
will check it is not carried over in the next update

2022-04-19 19:36 UTC, leotom2000 commented on app/server/appsmith-plugins/postgresPlugin/src/test/java/com/external/plugins/PostgresPluginTest.java
> +    @Test
Seems that was from another PR,
will check it is not carried over in the next update

2022-04-20 06:24 UTC, leotom2000 commented on app/server/appsmith-plugins/postgresPlugin/src/main/java/com/external/plugins/PostgresPlugin.java
> +        //JDBC override parameter for resolving Cast Errors on PostgreSQL
> @leotom2000 can you please edit `getCollection.json` file to add ARRAY_CONTAINS and ARRAY_CONTAINS_ANY operators to the query config page ?

Added the changes

2022-04-22 07:04 UTC, leotom2000 commented on app/server/appsmith-plugins/firestorePlugin/src/main/resources/editor/getCollection.json
> -          "value": "NOT_IN"
NOT_IN not supported in backend, it is there in front end.
is it okay that we add it back when the backend is ready ?

2022-04-28 05:56 UTC, sumitsum requested changes

2022-04-28 05:56 UTC, sumitsum commented on app/server/appsmith-plugins/firestorePlugin/src/main/java/com/external/utils/WhereConditionUtils.java
> +                return query.whereArrayContainsAny(fieldPath, Arrays.asList(value.toString().split(",")) );
Please restore the earlier code version where `parseList` method is used, since we assume the user to provide input like `["abc", "def", 123]` because we have used similar format elsewhere in Firestore plugin query config.

2022-04-28 05:56 UTC, sumitsum commented on app/server/appsmith-plugins/firestorePlugin/src/main/resources/editor/getCollection.json
> +          "label": "Any",
Please rename to `Contains Any`

2022-04-28 05:56 UTC, sumitsum commented on app/server/appsmith-plugins/firestorePlugin/src/test/java/com/external/plugins/FirestorePluginTest.java
> +    public void testArrayContainsAnyWhereConditional() {
Please update the TC as per the suggested changes above.

2022-04-29 08:30 UTC, leotom2000 commented on app/server/appsmith-plugins/firestorePlugin/src/main/resources/editor/getCollection.json
> +          "label": "Any",
Updated, this is word Wrapping in the UI dropdown, 
so we need to update the Width in the front end

2022-04-29 09:16 UTC, leotom2000 commented on app/server/appsmith-plugins/firestorePlugin/src/test/java/com/external/plugins/FirestorePluginTest.java
> +    public void testArrayContainsAnyWhereConditional() {
Updated

2022-04-29 13:22 UTC, sumitsum requested changes

2022-04-29 13:22 UTC, sumitsum commented on app/client/src/components/formControls/WhereClauseControl.tsx
> -const DropdownWidth = 100; //pixel value
Can you please remove this change ?

2022-04-29 19:42 UTC, sumitsum approved these changes

2022-04-29 19:43 UTC, sumitsum commented
/ok-to-run sha=916ffaa

2022-05-02 05:40 UTC, leotom2000 commented
/ok-to-test sha=916ffaa

2022-05-03 07:02 UTC, leotom2000 commented
/ok-to-test sha=916ffaa

2022-05-03 18:13 UTC, leotom2000 commented
/ok-to-test sha=916ffaa

2022-05-04 08:32 UTC, leotom2000 commented
/ok-to-test sha=916ffaa

2022-05-04 10:22 UTC, leotom2000 commented
/ok-to-test sha=929d55b

2022-05-06 07:40 UTC, leotom2000 commented
/ok-to-test sha=2907089

2022-05-06 08:28 UTC, merged