Fix/table widget pagination changes
appsmithorg/appsmith pull request #1298
Opened 2020-10-20 02:33 UTC by vicky-primathon

## Description
> Triggering onPageChange event with client side pagination in table widget. 

Fixes # (issue)
#731 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

-Workflow is tested manually

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2020-10-29 13:34 UTC, riodeuno requested changes

2020-10-29 13:34 UTC, riodeuno commented on app/client/src/widgets/TableWidget.tsx
> +    let event = EventType.ON_NEXT_PAGE;
@vicky-primathon  This seems like it will trigger when the user manually enters the same page number. Please check this scenario.

2020-11-03 13:06 UTC, Nikhil-Nandagopal commented
@vicky-primathon @riodeuno is this PR ready to be merged?

2020-11-06 11:15 UTC, riodeuno approved these changes
LGTM

2020-11-06 11:15 UTC, merged