fix: Select widget's default selectedOptionLabel shows data from the value field and not the label field
appsmithorg/appsmith pull request #13079
Opened 2022-04-19 10:04 UTC by wmdev0808

## Description
> Issue details:
Select related widgets are not exposing correct `selectedOptionLabel(s)` and `selectedOptionValue(s)` properties when:
- mounting for the first time
- changing `defaultOptionValue`
- changing `options`

> What is done:
- Always gets `selectedOptionLabel(s)` and `selectedOptionValue(s)` in cases of the above scenarios
- Even calculate nested labels and values with MultiSelectTreeWidget

Fixes #12554 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Test A
- Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-04-19 12:05 UTC, wmdev0808 commented
/ok-to-test sha=d307c4b

2022-04-20 05:43 UTC, ashit-rath reviewed
I am submitting a partial review here as I thing we need to re-think and re-work on the last comment.

2022-04-20 05:43 UTC, ashit-rath commented on app/client/src/widgets/SelectWidget/widget/index.tsx
> +    if (xorWith(this.props.options, prevProps.options, isEqual).length > 0) {
When serverside filtering is enabled, the options would change. Now if the new options does not have the selectedOption then we are going to remove it and post that if the options do come back we won't be showing it.

cc: @dilippitchika

2022-04-20 06:28 UTC, wmdev0808 commented on app/client/src/widgets/SelectWidget/widget/index.tsx
> +      selectedOption: undefined,
Because we are keeping the state for them in one object meta property, "selectedOption"

2022-04-20 06:34 UTC, wmdev0808 commented
/ok-to-test sha=05f3acd

2022-04-20 10:31 UTC, Tooluloope requested changes
Hi @wmdev0808 could you use the nullish check rather than the falsy Check in your PR

2022-04-20 10:31 UTC, Tooluloope commented on app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx
> +          ).includes(option.value)
We need to check if serverSide filtering Is enabled.

Please look through this comment and let me know if it's clear
https://github.com/appsmithorg/appsmith/issues/12225#issuecomment-1082910936

2022-04-20 10:31 UTC, Tooluloope commented on app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx
> +    }
The same applies to these changes, in Serverside Filtering, previous Values would be misplaced.
Do check the comment if that solution is best, else you could propose a new solution

2022-04-20 10:31 UTC, Tooluloope commented on app/client/src/widgets/SelectWidget/widget/index.tsx
> +    }
is there a reason why the `isChanged` logic was removed?

At the moment, selecting the same option would always fire OptionChanged and isDirty

2022-04-20 10:31 UTC, Tooluloope commented on app/client/src/widgets/SelectWidget/widget/index.tsx
> +      value: this.props.selectedOption?.value || this.props.selectedOption,
if the value is `0` this would fail, Let's be careful with this.

2022-04-20 10:31 UTC, Tooluloope commented on app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx
> +            value: selectedOption.value || selectedOption,
if the value is `0` this would fail, Let's be careful with this.

2022-04-20 10:31 UTC, Tooluloope commented on app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx
> +            selectedOption => selectedOption.value || selectedOption
if the value is `0` this would fail, Let's be careful with this.

2022-04-20 10:31 UTC, Tooluloope commented on app/client/src/widgets/SingleSelectTreeWidget/widget/index.tsx
> +  }
`Flat()` and `FlatOptions()` are similar, Could we re-use 1 of the two functions across the Widget

Or better still, add the function to widgetUtils and use in both TreeSelect widgets

2022-04-20 10:37 UTC, Tooluloope requested changes
Could you write a test for serverSide filtering for Multiselect and Select, So we're sure nothing would break

2022-04-20 10:37 UTC, Tooluloope commented on app/client/src/widgets/MultiSelectTreeWidget/widget/index.tsx
> +  getOptionSubTree(options: DropdownOption[], value: string | number) {
Could you write a Unit Test for this method

2022-04-20 11:58 UTC, ashit-rath commented on app/client/src/widgets/SelectWidget/widget/index.tsx
> +    if (xorWith(this.props.options, prevProps.options, isEqual).length > 0) {
@Tooluloope Any thoughts on this?

2022-04-20 12:01 UTC, Tooluloope commented on app/client/src/widgets/SelectWidget/widget/index.tsx
> +    if (xorWith(this.props.options, prevProps.options, isEqual).length > 0) {
Yeah, You're right @ashit-rath 
I also raise a comment during my review.

@wmdev0808 do check this comment https://github.com/appsmithorg/appsmith/issues/12225#issuecomment-1082910936 for the proposed solution.

If you feel this can be implemented better do let us know before implementation.

@ashit-rath do you think this https://github.com/appsmithorg/appsmith/issues/12225#issuecomment-1082910936 is okay?

2022-04-21 06:39 UTC, wmdev0808 commented on app/client/src/widgets/MultiSelectTreeWidget/widget/index.tsx
> +      return result;
I can't understand why you consider `Mode` for selectedOptionsValue.
That should always includes subtrees regardless of `Mode`, I think

2022-04-21 06:42 UTC, wmdev0808 commented on app/client/src/widgets/MultiSelectTreeWidget/widget/index.tsx
> +    options.every((option) => {
Because we don't have to traverse whole option tree, should break early if found without further proceeding.
Foreach cannot be used for that purpose

2022-04-21 07:31 UTC, wmdev0808 commented
> Hi @wmdev0808 could you use the nullish check rather than the falsy Check in your PR

Could you please specify exactly which one you mean?

2022-04-21 08:18 UTC, wmdev0808 commented on app/client/src/widgets/MultiSelectTreeWidget/widget/index.tsx
> +      );
When user select from the UI, we don't have to calculate subtree for the selected options.
However, if user changes defaultOptionValue, it leads to changing `selectedOptionValueArr`, we need to calculate subtrees.
After all this is just to identify the above two cases

2022-04-21 08:22 UTC, wmdev0808 commented on app/client/src/widgets/SelectWidget/widget/index.tsx
> +      value: this.props.selectedOption?.value || this.props.selectedOption,
Please provide me with a demonstrating example

2022-04-21 12:57 UTC, wmdev0808 commented on app/client/src/widgets/MultiSelectTreeWidget/widget/index.tsx
> +    );
Here, _.uniq is used to eliminate duplications produced by calculation

2022-04-21 17:47 UTC, wmdev0808 commented
/ok-to-test sha=1637654

2022-04-22 04:27 UTC, ashit-rath commented on app/client/src/widgets/SelectWidget/widget/index.tsx
> +    if (xorWith(this.props.options, prevProps.options, isEqual).length > 0) {
Yeah, I was also thinking about caching but we have to have to make sure we cache it in the right way to avoid unnecessary re-rendering.

2022-04-22 12:29 UTC, Tooluloope requested changes

2022-04-22 12:29 UTC, Tooluloope commented on app/client/src/widgets/SelectWidget/widget/index.tsx
> +    }
Same here, Moving this to Derived Property Calculation

2022-04-22 12:29 UTC, Tooluloope commented on app/client/src/widgets/SelectWidget/widget/index.tsx
> +
This also does strict checking which should be

2022-04-22 13:36 UTC, wmdev0808 commented on app/client/src/widgets/MultiSelectTreeWidget/widget/getOptionSubTree.test.ts
> +});
When I use this input, all the test cases even pass

2022-04-24 17:43 UTC, Tooluloope commented on app/client/src/widgets/MultiSelectTreeWidget/widget/getOptionSubTree.test.ts
> +});
Try running this on the application and see the result

https://replit.com/@TOLULOPEADETULA/InsistentCookedIdentifier#index.ts

2022-04-25 05:24 UTC, ashit-rath commented on app/client/src/widgets/SelectWidget/widget/index.tsx
> +      selectedOption: undefined,
Wouldn't removing `value` cause friction in the Form widget as it depends on the `value` property?

2022-04-25 05:24 UTC, ashit-rath commented on app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx
> +    }
Yes, I agree. Is it also possible to move the logic in componentDidMount to derived properties?

2022-04-25 06:30 UTC, wmdev0808 commented on app/client/src/widgets/MultiSelectTreeWidget/widget/getOptionSubTree.test.ts
> +});
What is wrong with the above?

2022-04-25 10:34 UTC, wmdev0808 commented
/ok-to-test sha=c4d59f0

2022-04-26 06:21 UTC, Tooluloope reviewed
I think after these it should be Okay.

2022-04-26 06:21 UTC, Tooluloope commented on app/client/src/widgets/SelectWidget/widget/index.tsx
> -      value: "defaultOptionValue",
@wmdev0808 Please Add Value back, this was kept for form changes

2022-04-26 06:21 UTC, Tooluloope commented on app/client/src/widgets/SelectWidget/widget/index.tsx
> +        value: this.props.selectedOption.value,
this should be `value: this.props.selectedOption.value ?? this.props.selectedOption

2022-04-26 06:53 UTC, wmdev0808 commented
/ok-to-test sha=100a23c

2022-04-26 08:28 UTC, Tooluloope requested changes

2022-04-26 08:28 UTC, Tooluloope commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/SelectWidgets_selectedOptionLabels_spec.js
> +  });
Same thing here, Why shouldn't it contain Red?

2022-04-26 08:28 UTC, Tooluloope commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/SelectWidgets_selectedOptionLabels_spec.js
> +  });
Could you add tests for the Mode changes

2022-04-26 08:28 UTC, Tooluloope commented on app/client/src/widgets/SelectWidget/widget/index.tsx
> -      value: "defaultOptionValue",
@wmdev0808 Should value be here or in derivedProperties,
Here, value would always be equal to the initial default Value

2022-04-26 08:28 UTC, Tooluloope commented on app/client/src/widgets/SelectWidget/widget/index.tsx
> -      this.props.updateWidgetMetaProperty("value", selectedOption.value ?? "", {
Value was previously been updated, Since we are not updating it anymore, please move it to derived properties
``` value: `{{this.selectedOption.value}}` ```

2022-04-26 09:06 UTC, wmdev0808 commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/SelectWidgets_selectedOptionLabels_spec.js
> +      .should("not.contain.text", "BLUE");
> At the prior step, BLUE is removed from selectedOption by excluding it from options. So after restoring options, it should not be restored as far as severSideFiltering is off

After all, the assertion is to check the removed option in the earlier step should not restored after its options are restored

2022-04-26 10:11 UTC, wmdev0808 commented
/ok-to-test sha=4ff9d29

2022-04-26 11:37 UTC, Tooluloope commented
@wmdev0808 Here's the recording
https://user-images.githubusercontent.com/31691737/165291629-2675fe59-4988-4e0d-9de0-b0dbf700f88a.mov

2022-05-02 08:52 UTC, ashit-rath reviewed
@Tooluloope  I have skimmed through the MultiSelectTreeWidget here. Please do have a deeper look if required.

2022-05-02 08:52 UTC, ashit-rath commented on app/client/src/widgets/SelectWidget/widget/index.tsx
> +
Please break this whole thing down to 2 functions, similar to the multi-select widget and add test to the `getSelectedOption`.
Please do write test to cover https://github.com/appsmithorg/appsmith/issues/12225#issuecomment-1110526570

2022-05-02 08:52 UTC, ashit-rath commented on app/client/src/widgets/SingleSelectTreeWidget/widget/index.tsx
> +    if (!isEqual(this.props.selectedOption, prevProps.selectedOption)) {
Why are we checking this?

2022-05-02 08:52 UTC, ashit-rath commented on app/client/src/widgets/SingleSelectTreeWidget/widget/index.tsx
> +      !this.props.__evaluation__?.errors.options?.length
We shouldn't be looking into the `__evaluation__` object. Isn't there proper validation for `options`?

2022-05-02 08:52 UTC, ashit-rath commented on app/client/src/widgets/SingleSelectTreeWidget/widget/index.tsx
> -  selectedOption: string | number;
Why did we remove `selectedOption`?

2022-05-02 08:52 UTC, ashit-rath commented on app/client/src/widgets/SingleSelectTreeWidget/widget/index.tsx
> +  options: DropdownOption[];
Are we sure options would always be there?
If so then why do we have such checks [here](https://github.com/appsmithorg/appsmith/pull/13079/files#diff-477fa90c63460418797f2ccb1a946ff6789106e8272d63523808afc5dfa6d7a0R420)?

2022-05-02 08:52 UTC, ashit-rath commented on app/client/src/widgets/SingleSelectTreeWidget/widget/index.tsx
> +  setSelectedOptionLabel(
This isn't getting called from anywhere.

2022-05-02 08:52 UTC, ashit-rath commented on app/client/src/widgets/SingleSelectTreeWidget/widget/index.tsx
> -      selectedLabel: [],
Why are we removing from here? Is this not required?
cc: @Tooluloope

2022-05-02 08:52 UTC, ashit-rath commented on app/client/src/widgets/SingleSelectTreeWidget/widget/index.tsx
> +  setSelectedOption = () => {
This function is not about setting selected option. 
`selectedOption` gets updated with a value only when a user selects something in the dropdown with a real value.

Here we are looping through the options to find an option that matches with the `selectedOption` and then update that value as the selectedOption? If there is a match wouldn't that value and `selectedOption` (that we use to find) would always be the same?

This function's use case is to unset `selectedOption`. If the `selectedOption` is not present in the option then update with `{}` to unset the value.

2022-05-02 08:52 UTC, ashit-rath commented on app/client/src/widgets/SingleSelectTreeWidget/widget/index.tsx
> +      ).length > 0
This is a very expensive operation and what makes this expensive is
1. Flattening of options
2. Xor with deep-equal
3. It would happen twice (prev option and current option)
4. the number of times `componentDidUpdate` runs.

Alternative approach: When options are changed, in the property config of option, in the `updateHook` we can set a flag to true denoting options changed. And here we can check if that flag is set; update accordingly and reset the flat
There could be an even better solution than this.
cc: @Tooluloope

2022-05-02 08:52 UTC, ashit-rath commented on app/client/src/widgets/SingleSelectTreeWidget/widget/index.tsx
> +      }
Isn't `setSelectedOption` for doing this?

2022-05-02 08:52 UTC, ashit-rath commented on app/client/src/widgets/MultiSelectTreeWidget/widget/index.tsx
> +      this.props.isDirty === false
`!this.props.isDirty`

2022-05-02 08:52 UTC, ashit-rath commented on app/client/src/widgets/MultiSelectTreeWidget/widget/index.tsx
> +      if (this.props.isDirty) {
This can be clubbed with the previous condition

```js
if (xor(...) && this.props.isDirty) 
```

2022-05-02 21:13 UTC, wmdev0808 commented on app/client/src/icons/WidgetIcons.tsx
> +import React, { JSXElementConstructor } from "react";
It should be removed

2022-05-03 07:44 UTC, wmdev0808 commented on app/client/src/widgets/SingleSelectTreeWidget/widget/index.tsx
> +  setSelectedOption = () => {
No, this function is to always set/update a valid/normalized `selectedOption` object in the following use cases:
- When mounting
- When `defaultOptionValue` changes
- When `options` changes

NB: I will refactor this part for your better understanding

2022-05-03 08:02 UTC, wmdev0808 commented on app/client/src/widgets/SingleSelectTreeWidget/widget/index.tsx
> +      ).length > 0
@ashit-rath ,
First, thank you for your solution.
However, how can we check if `options` property has actually changed in `updateHook`?
Without the above computation, we cannot decide if the value has actually changed

2022-05-03 08:06 UTC, wmdev0808 commented
/ok-to-test sha=5e690b3

2022-05-03 08:49 UTC, ashit-rath commented on app/client/src/widgets/SingleSelectTreeWidget/widget/index.tsx
> +  setSelectedOption = () => {
@wmdev0808  Can you give an example where the `matchingOption` and the `this.props.selectedOption` be different and the `matchingOption` is not `{}`?

2022-05-03 08:50 UTC, ashit-rath commented on app/client/src/widgets/SingleSelectTreeWidget/widget/index.tsx
> +      ).length > 0
`updateHook` only runs when the property value changes.

2022-05-03 09:14 UTC, wmdev0808 commented on app/client/src/widgets/SelectWidget/widget/index.tsx
> +      this.props.updateWidgetMetaProperty("selectedOption", selectedOption, {
There is still a code snippet for isDirty update

2022-05-03 09:19 UTC, wmdev0808 commented on app/client/src/widgets/SingleSelectTreeWidget/widget/index.tsx
> +    if (!isEqual(this.props.selectedOption, prevProps.selectedOption)) {
The purpose is to catch `defaultOptionValue` changes because it leads to changing selectedOption.
In addition, I've refactored that part again

2022-05-03 09:20 UTC, wmdev0808 commented on app/client/src/widgets/SingleSelectTreeWidget/widget/index.tsx
> +      !this.props.__evaluation__?.errors.options?.length
This code is from @Tooluloope ,
you should confirm with him

2022-05-03 09:29 UTC, wmdev0808 commented on app/client/src/widgets/SingleSelectTreeWidget/widget/index.tsx
> +      ).length > 0
I mean for the following case, for example:
- User just add/or remove a space, resulting in the same evaluation

2022-05-03 09:29 UTC, wmdev0808 commented on app/client/src/widgets/SingleSelectTreeWidget/widget/index.tsx
> +      }
right

2022-05-03 09:34 UTC, wmdev0808 commented on app/client/src/widgets/SingleSelectTreeWidget/widget/index.tsx
> +  setSelectedOption = () => {
For example, 
- If defaultOptionValue can be simple string, "BLUE" for the first time, but matchingOption is always object

2022-05-03 09:35 UTC, wmdev0808 commented on app/client/src/widgets/SingleSelectTreeWidget/widget/index.tsx
> -      selectedLabel: [],
We are using selectedOption as a source of true for selectedOptionLabel and selectedOptionValue, so they are not required

2022-05-03 09:39 UTC, wmdev0808 commented on app/client/src/widgets/SingleSelectTreeWidget/widget/index.tsx
> +  options: DropdownOption[];
I think so.
How is that check  related with options?

2022-05-03 10:01 UTC, wmdev0808 commented on app/client/src/widgets/SingleSelectTreeWidget/widget/index.tsx
> -  selectedOption: string | number;
I will add it

2022-05-04 05:23 UTC, ashit-rath commented on app/client/src/widgets/SingleSelectTreeWidget/widget/index.tsx
> +      ).length > 0
Still, it's better than doing deep checking in `componentDidUpdate` which would still run if one add/remove a space. It would also run for every tiny update which is not related to the options change

2022-05-04 05:25 UTC, ashit-rath commented on app/client/src/widgets/SingleSelectTreeWidget/widget/index.tsx
> +  setSelectedOption = () => {
Isn't `defailtOptionValue`  always an object? Don't we have similar validation like in the Select widget where we compare with the options?

2022-05-04 05:26 UTC, ashit-rath commented on app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx
> +      }}`,
@wmdev0808 This comment isn't addressed

2022-05-04 05:26 UTC, ashit-rath commented on app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx
> +      const matchingOptions = this.props.selectedOptions.reduce(
This isn't addressed.

2022-05-04 05:27 UTC, ashit-rath commented on app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx
> +          }) as DropdownOption;
@wmdev0808 Can you let us know about this?

2022-05-04 05:27 UTC, ashit-rath commented on app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx
> +
@wmdev0808 Can you address this comment?

2022-05-04 05:28 UTC, ashit-rath commented on app/client/src/widgets/SingleSelectTreeWidget/widget/index.tsx
> -      selectedLabel: [],
We need to verify if `selectedLabel` is used by any user. If so then we cannot remove it as it may break their app.
@dilippitchika Can we verify this in the mixpanel?

2022-05-04 05:29 UTC, ashit-rath commented on app/client/src/widgets/SingleSelectTreeWidget/widget/index.tsx
> +      }
Please do make the necessary changes

2022-05-04 05:30 UTC, Tooluloope commented
Kinda hard to get where my attention is needed here.
@wmdev0808 Could you please tag me again.

@ashit-rath thanks for helping with the reviews

2022-05-04 05:30 UTC, ashit-rath commented on app/client/src/widgets/SingleSelectTreeWidget/widget/index.tsx
> +    if (!isEqual(this.props.selectedOption, prevProps.selectedOption)) {
If that's the case then this is not the way of checking. 
The `selectedOption` also changes when the user clicks an option. In that case this block would unnecessary run.

2022-05-04 05:32 UTC, Tooluloope commented on app/client/src/widgets/SingleSelectTreeWidget/widget/index.tsx
> -      selectedLabel: [],
@wmdev0808 You could make it a derived property just like selectedOptionLabel, but an array.

Although, I really think we should remove it, cos it shouldn't be accessible to the users

2022-05-04 05:37 UTC, Tooluloope commented on app/client/src/widgets/SingleSelectTreeWidget/widget/index.tsx
> +      !this.props.__evaluation__?.errors.options?.length
This was quite a long time, we could refactor this if there's something better

2022-05-04 05:38 UTC, ashit-rath reviewed
@wmdev0808  Why is this PR up for review again if most of the major comments are not addressed?
Please push all changes, do a self-review, and then request for a review otherwise we would unnecessary go back and forth.

2022-05-04 05:39 UTC, ashit-rath commented on app/client/src/widgets/SingleSelectTreeWidget/widget/index.tsx
> +      !this.props.__evaluation__?.errors.options?.length
We should fix the validation fn of the `options` here similar to SingleSelect. We are checking for errors here because we aren't parsing it properly.

2022-05-04 05:44 UTC, ashit-rath commented on app/client/src/widgets/SingleSelectTreeWidget/widget/index.tsx
> -      selectedLabel: [],
Agreed @Tooluloope, we should work towards removing it. But the problem is that all the properties of widgets are exposed by default. If we suddenly remove it, it may cause friction; which we should avoid and deprecate properties gracefully. 
Further, we only have statistics for cloud users not the self hosted.

2022-05-04 13:23 UTC, wmdev0808 commented on app/client/src/widgets/WidgetUtils.test.ts
> +    const input = [
The followings are out of this function features, it should be taken from validation logic. 
- null from 1
- 3, 4, 5

2022-05-04 13:36 UTC, wmdev0808 commented
/ok-to-test sha=5c330a3

2022-05-04 13:40 UTC, ashit-rath commented on app/client/src/widgets/SelectWidget/widget/index.tsx
> +      this.props.updateWidgetMetaProperty("selectedOption", selectedOption, {
Can you share where this is hapenning?

2022-05-17 11:18 UTC, souma-ghosh commented
/ok-to-test sha=9156e9a69

2022-05-20 12:10 UTC, closed without merging