fix: set max-height for Dropdown component
appsmithorg/appsmith pull request #13105
Opened 2022-04-19 18:18 UTC by aswathkk

## Description

Set a max height for dropdown

Fixes #12572

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Manual

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-04-21 16:43 UTC, aswathkk commented
/ok-to-test sha=e0cfd44

2022-04-22 04:55 UTC, aswathkk commented
/ok-to-test sha=b478f9c

2022-04-26 07:52 UTC, riodeuno requested changes

2022-04-26 07:52 UTC, riodeuno commented on app/client/src/components/ads/Dropdown.tsx
> +        border-color: ${Colors.GRAY_900}!important;
We can increase specificity by using multiple `&`. This should help us remove the need for `!important`
```suggestion
       &&&:focus { 
             border-color: ${Colors.GRAY_900}`,
```

2022-04-26 07:52 UTC, riodeuno commented on app/client/src/components/ads/Dropdown.tsx
> +type SubTextPosition = "BOTTOM" | "LEFT";
We can use an `enum` instead of string literals here.

2022-04-26 07:52 UTC, riodeuno commented on app/client/src/components/ads/Dropdown.tsx
> +const SelectedDropDownHolder = styled.div<{ enableScroll?: boolean }>`
`enableScroll` might cause a warning in the browser's console. This is a new attribute added to the `div` element. React might complain, please verify this.

2022-04-26 07:52 UTC, riodeuno commented on app/client/src/components/ads/Dropdown.tsx
> +  &::-webkit-scrollbar {
Are we removing scrollbars in the dropdown? 
I was wondering if this has been reviewed by someone from the design team? I am concerned because this effects all dropdowns in Appsmith's platform UI.

2022-04-26 07:52 UTC, riodeuno commented on app/client/src/components/ads/Dropdown.tsx
> +          !(selected as DropdownOption[])
Would `findIndex` make for a more performant mechanism?

2022-04-26 08:24 UTC, aswathkk commented on app/client/src/components/ads/Dropdown.tsx
> +        border-color: ${Colors.GRAY_900}!important;
It doesn't work. That's why I added `!important`

2022-04-26 08:27 UTC, aswathkk commented on app/client/src/components/ads/Dropdown.tsx
> +  &::-webkit-scrollbar {
This is not to remove scrollbar in dropdown. This is to remove scrollbar in multi select value display.

https://user-images.githubusercontent.com/10436935/165256665-afa66c01-90c4-421a-892b-88714d685aae.mov

2022-04-26 08:27 UTC, aswathkk commented on app/client/src/components/ads/Dropdown.tsx
> +  &::-webkit-scrollbar {
I will get this reviewed by @vasanth-appsmith

2022-04-26 08:46 UTC, aswathkk commented on app/client/src/components/ads/Dropdown.tsx
> +const SelectedDropDownHolder = styled.div<{ enableScroll?: boolean }>`
I checked this. React is not complaining about this.

2022-04-26 08:48 UTC, vivekverma2312 commented
@aswathkk 
1. The drop down option do not scroll using keyboard
https://www.loom.com/share/16817daa61a44e3d904a0e71b2d7a6f2

2. Are we not setting max height for these drop-downs?
![Screenshot 2022-04-26 at 2 02 07 PM](https://user-images.githubusercontent.com/83569920/165260702-c349b5d8-a951-4f98-a770-0992c5fd9a2d.png)

3. On table widget Primary key property also do not have max height
![Screenshot 2022-04-26 at 2 16 26 PM](https://user-images.githubusercontent.com/83569920/165260817-df4b7ba5-904f-4804-81fd-876d6e7ff403.png)

2022-04-26 08:58 UTC, aswathkk commented
@vivekverma2312 
1. Great finding. I will try to implement it.
2. That's not a dropdown. That's technically an Action Selector. Designs are not available for this. I will discuss with @vasanth-appsmith and pick up that in a separate PR
3. I will fix this too.

2022-04-29 13:45 UTC, aswathkk commented
/ok-to-test sha=58aa50e

2022-04-30 07:43 UTC, aswathkk commented
/ok-to-test sha=878fa3c

2022-05-03 04:52 UTC, aswathkk commented
Thanks, @rahulramesha. That was a regression that came as a part of merging the code. Fixed it.

@vivekverma2312, as Rahul pointed out, this Dropdown is being used in other parts of Appsmith as well. I've taken a look at those and found no issues. You can also take a look at those.
The other places where we use the same Dropdown component are Dropdown inside JSObjects, Query Editor, Data Source pages, Generate pages, Debugger Filter, Git connect, Currency and Phone input widget.

2022-05-03 06:32 UTC, vivekverma2312 commented
@aswathkk Can you check the keyboard scroll is not looking smooth.
https://www.loom.com/share/926756a3b726400199594fe9d8480a2b

2022-05-03 08:25 UTC, vivekverma2312 commented
@aswathkk On JS Object screen dropdown
![Screenshot 2022-05-03 at 1 53 18 PM](https://user-images.githubusercontent.com/83569920/166423684-14cd692e-aa5c-4eb6-95bc-8d8dad19ca7d.png)

2022-05-03 08:31 UTC, vivekverma2312 commented
@aswathkk Drop-down on git
![Screenshot 2022-05-03 at 2 00 33 PM](https://user-images.githubusercontent.com/83569920/166424465-b67c815f-f8e9-4104-91d7-0e6d17f4bcae.png)

2022-05-03 08:44 UTC, aswathkk commented
@vivekverma2312 For dropdown in Git and JSObject, if you are talking about the height, then that is not under the scope of this issue. You can create a separate issue for that and assign it to the respective team.

2022-05-03 10:01 UTC, aswathkk commented
> @aswathkk Can you check the keyboard scroll is not looking smooth.

This is fixed. @vivekverma2312 Can you check?

2022-05-04 06:13 UTC, vivekverma2312 commented
@aswathkk Tested and working fine.

2022-05-04 07:18 UTC, aswathkk commented
/ok-to-test sha=b592857

2022-05-04 10:16 UTC, riodeuno approved these changes

2022-05-05 16:56 UTC, aswathkk commented
/ok-to-test sha=74b450e

2022-05-06 05:04 UTC, rahulramesha approved these changes

2022-05-06 05:04 UTC, merged