fix: Popover in Multi select widget inside modals breaks away from the widget
appsmithorg/appsmith pull request #13129
Opened 2022-04-20 09:07 UTC by wmdev0808

## Description
When I add a multi-select inside a modal with options exceeding the height to see a scroll. After reaching the end of the scroll the multi-select popover breaks away from the modal.

Fixes #12161 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Test A
- Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-04-20 09:08 UTC, wmdev0808 commented
/ok-to-test sha=43ca423

2022-04-20 10:34 UTC, Tooluloope requested changes

2022-04-20 10:34 UTC, Tooluloope commented on app/client/src/widgets/MultiSelectTreeWidget/component/index.tsx
>    }, []);
Can we make getting the Closest canvas widget into a utility function rather than repeating this across

2022-04-20 12:42 UTC, wmdev0808 commented
/ok-to-test sha=0771f23

2022-04-21 11:54 UTC, Tooluloope submitted a review, later dismissed

2022-04-21 11:56 UTC, Tooluloope commented
@wmdev0808 
Moving to QA but please dont merge till Theming is merged.
There's a conflict
<img width="845" alt="Screenshot 2022-04-21 at 12 55 37" src="https://user-images.githubusercontent.com/31691737/164453076-c16033b8-afb2-4100-b920-82e8e9357c1b.png">

2022-04-22 07:35 UTC, chandannkumar commented
Tested this PR and working as expected
- scrolling the multi-select popover breaks away from the modal - fixed

2022-05-04 02:52 UTC, Tooluloope approved these changes

2022-05-04 13:48 UTC, wmdev0808 commented
/ok-to-test sha=58dfb48

2022-05-25 05:00 UTC, dilippitchika commented
@vivekverma2312 can you please #11485 here, the treeselect issue where it navigates to the top once opened?

2022-05-25 05:08 UTC, ashit-rath reviewed
I think there is a scroll function in cypress that we can use to verify the fix. Can you check if that's useful and add a cypress test if possible?

2022-05-25 12:11 UTC, Tooluloope commented on app/client/src/widgets/MultiSelectTreeWidget/component/index.tsx
> +    return node as HTMLElement;
@ashit-rath 
using `const _menu = useRef<HTMLElement>();` wont help as _menu could then be HTMLElement or Undefined

2022-05-25 14:24 UTC, Tooluloope commented on app/client/src/widgets/MultiSelectTreeWidget/component/index.tsx
> +    return node as HTMLElement;
Oh no, the reason I'm asserting is because the needed return type for the function is HTMLElement, so either way, I'll still need to assert

2022-05-26 05:32 UTC, Tooluloope commented on app/client/src/widgets/MultiSelectTreeWidget/component/index.tsx
> +    return node as HTMLElement;
It cant throw an error since `getPopupContainer` can only be called after the dropdown has been rendered.

2022-05-26 05:53 UTC, Tooluloope commented on app/client/src/widgets/MultiSelectTreeWidget/component/index.tsx
> +    return node as HTMLElement;
As for the scrolling, the scroll commands in cypress are just to help simulate scrolling and not to assert if it scrolled

2022-05-26 05:53 UTC, Tooluloope commented
/ok-to-test sha=d07d8f8

2022-05-26 06:16 UTC, ashit-rath submitted a review, later dismissed

2022-05-27 06:55 UTC, chandannkumar commented
@Tooluloope  
Observation:
- Since the size of the pop-over dropdown is now fixed which actually hides few list at the bottom, if the size of the modal is compact.
- It is also observed that pop-over list is now transparent as we can see background buttons when we move the cursor away from the pop-over. refer video
https://www.loom.com/share/79fd60ae6a014c92b94aac9af77ad0dd

2022-05-31 10:53 UTC, Tooluloope commented
/ok-to-test sha=af17e7b

2022-05-31 10:55 UTC, Tooluloope commented on app/client/src/widgets/MultiSelectTreeWidget/component/index.tsx
> -            autoFocus
@ashit-rath this was the major reason for the jumps/scrolling when the dropdown is rendered

2022-05-31 13:50 UTC, ashit-rath submitted a review, later dismissed
@Tooluloope Minor callout.

2022-05-31 14:23 UTC, Tooluloope commented
/ok-to-test sha=b22975f

2022-06-01 06:13 UTC, Tooluloope approved these changes

2022-06-01 06:21 UTC, chandannkumar commented
@Tooluloope @dilippitchika 
1st point on my last callout is still not fixed where few list items in bottom of dropdown is hidden since the modal size is compact
https://www.loom.com/share/552e452105a54a9fabbf997c2a12c19e

or else this is an expected behavior here?

2022-06-01 06:28 UTC, Tooluloope commented
Could you confirm this also happens in release or Production?
If it does I can handle that in another PR @chandannkumar

2022-06-01 06:32 UTC, chandannkumar commented
@Tooluloope Since on release/Production we didn't have fixed size of the dropdown and hence the dropdown list can be seen beyond the modal size
![image.png](https://images.zenhubusercontent.com/61e65341d503e6aafa5df216/be58f524-d04e-470b-ad8b-0b2cb23386d9)

2022-06-01 10:01 UTC, chandannkumar commented
Moving it to in Progress again.
@Tooluloope Please let me know if we are going to track this separately

2022-06-01 13:45 UTC, Tooluloope commented
@chandannkumar Please do test for the Multiselect, MultiTreeSelect and TreeSelect  positioning issues, scrolling issues,

2022-06-01 13:45 UTC, Tooluloope commented
/ok-to-test sha=6108d6f

2022-06-07 06:25 UTC, chandannkumar commented
@Tooluloope 
Observation: When we try to scroll the dropdown list after reaching to the bottom of the list, the list went to the top of the canvas and cuts the view of dropdown.
This behavior occurs to all the select family in this DP and only when widget added on Modal
https://www.loom.com/share/76608810c457433baa5d7acaca0695f8

2022-06-08 11:09 UTC, chandannkumar commented
Tested this PR and it is working as expected

2022-06-09 04:23 UTC, Tooluloope commented
/ok-to-test sha=6665aec5

2022-06-09 06:12 UTC, Tooluloope commented
/ok-to-test sha=4d5fc3b

2022-06-09 06:18 UTC, ashit-rath reviewed
@Tooluloope It seems that we have now implemented a different logic than before. Why didn't the old one work and what are we doing with this new logic?

2022-06-09 06:18 UTC, ashit-rath commented on app/client/src/widgets/MultiSelectWidgetV2/component/index.tsx
> -  useEffect(() => {
Are we relocating these somewhere else?

2022-06-09 06:18 UTC, ashit-rath commented on app/client/src/widgets/MultiSelectTreeWidget/component/index.tsx
> +import { BackDrop } from "widgets/MultiSelectWidgetV2/component";
It seems a bit odd to import such components from Multiselect.
Is there any other place we can keep this?

2022-06-09 06:18 UTC, ashit-rath commented on app/client/src/widgets/MultiSelectWidgetV2/component/index.tsx
> +      if (popupContainer.current && renderMode === RenderModes.CANVAS) {
I see a lot of code getting repeated across the select family. 
Let's create a hook and have the hook do the following
1. Create `popupContainer` and manage to add the canvas to it.
2. Create `selectRef` and return it to add it to the Select component
3. Return a function that toggles the overflow of the container which you can use here.
4. Returns `getPopupContainer` function
5. Returns `closeBackDrop` function
6. Return the Backdrop component as well

2022-06-09 06:18 UTC, ashit-rath commented on app/client/src/widgets/MultiSelectWidgetV2/component/index.tsx
> +  return <div className="select-backdrop" onClick={onClick} />;
Can this not be a Styled component? With this we are including the same style everywhere.

2022-06-09 06:25 UTC, Tooluloope commented
> It seems that we have now implemented a different logic than before. Why didn't the old one work and what are we doing with this new logic?
@ashit-rath , We decided to disable scrolling when the Dropdown is opened, That's why I'm using a backDrop.

2022-06-09 08:40 UTC, Tooluloope commented on app/client/src/widgets/MultiSelectWidgetV2/component/index.tsx
> -  useEffect(() => {
I think this was duplicated

2022-06-09 09:01 UTC, ashit-rath commented on app/client/src/widgets/useDropdown.tsx
> +      console.log(popupContainer.current);
Remove `console.log`

2022-06-09 09:05 UTC, ashit-rath commented on app/client/src/widgets/useDropdown.tsx
> +      if (popupContainer.current && renderMode === RenderModes.CANVAS) {
Don't we need to do this in the View mode as well?

2022-06-09 09:34 UTC, Tooluloope commented on app/client/src/widgets/useDropdown.tsx
> +      if (popupContainer.current && renderMode === RenderModes.CANVAS) {
Not needed for view mode

2022-06-09 09:54 UTC, Tooluloope commented
/ok-to-test sha=3d7d891

2022-06-09 12:59 UTC, ashit-rath approved these changes

2022-06-09 13:13 UTC, Tooluloope commented
/ok-to-test sha=3d7d891

2022-06-09 13:14 UTC, Tooluloope commented
/ok-to-test sha=ddaf283

2022-06-17 06:14 UTC, ashit-rath commented
/ok-to-test sha=90532f1

2022-06-17 06:22 UTC, somangshu approved these changes
LGTM

2022-06-17 09:20 UTC, somangshu commented
Seems like related tests are failing, Please check @Tooluloope

2022-06-20 22:08 UTC, Tooluloope commented
/ok-to-test sha=7ab05c4

2022-06-21 12:10 UTC, Tooluloope commented
/ok-to-test sha=5af2839

2022-06-22 00:16 UTC, Tooluloope commented
/ok-to-test sha=31f91f6

2022-06-22 01:41 UTC, Tooluloope commented
/ok-to-test sha=43ecd36

2022-06-22 08:59 UTC, merged