fix: Page order sequence for git import
appsmithorg/appsmith pull request #13126
Opened 2022-04-20 07:22 UTC by AnaghHegde

## Description

> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change.

Fixes #12944 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Locally 
- Junit Tests

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-04-20 08:55 UTC, AnaghHegde commented
/ok-to-test sha=4a704d4

2022-04-20 08:56 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/domains/ApplicationJson.java
> +    List<String> pageOrder;
We should have a seperate list for unpublished and published pages as the sequence might be different

2022-04-20 08:59 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/domains/ApplicationJson.java
> +    List<String> pageOrder;
@abhvsn IIUC, it is not possible right? Say you have Page1 at top in edit mode and in view mode it is at bottom. Now while you are creating a new App, the same page will have two different order and we have to ignore one of these two. And IMO, edit mode takes precedence over view mode.

2022-04-20 09:02 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
>                      return pageFlux
This again result in mismatched order can we instead take the reference from `pages` and `publishedPages` from the application object that will be easier to deal with. Also we are referencing the pages from application object only

2022-04-20 09:08 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
>                      return pageFlux
It does not matter now as we are storing the page order as a metadata, which is used in import flow. So no matter how the pages are stored in json-file/git-repo, the order is maintained as we keep update the order in metadata during the export flow here - https://github.com/appsmithorg/appsmith/blob/4a704d415f7abfe484114ddf2fb2c696f6d13345/app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java#L254.

2022-04-20 12:25 UTC, AnaghHegde commented
/ok-to-test sha=6353d24

2022-04-22 11:29 UTC, AnaghHegde commented
/ok-to-test sha=6c0de3d

2022-04-25 09:29 UTC, abhvsn reviewed
Please take a look at the case mentioned in the comment also can we add the testcase with the mentioned scenario

2022-04-25 10:07 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
> +                                Collections.sort(newPages, Comparator.comparing(newPage -> publishedPageOrderList.indexOf(newPage.getId())));
@abhvsn This is handled correctly during the import. But when we add the page order to json file during export, i have missed out on this case. Let me fix this.

2022-04-25 10:12 UTC, AnaghHegde commented
/ok-to-test sha=5867f17

2022-04-26 06:17 UTC, abhvsn commented on app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ImportExportApplicationServiceTests.java
> +                    List<String> publishedPageList = applicationJson.getPageOrder();
```suggestion
                    List<String> publishedPageList = applicationJson.publishedPageOrder();
```

2022-04-26 12:47 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
> +                                Collections.sort(newPages, Comparator.comparing(newPage -> publishedPageOrderList.indexOf(newPage.getId())));
Now getting the NPE during the export

2022-04-26 12:49 UTC, abhvsn requested changes
Now I'm getting the NPE for the for the scenario described https://github.com/appsmithorg/appsmith/pull/13126/files#r857259455 at 
`pageOrder.add(page.getPublishedPage().getName());`

2022-04-26 14:16 UTC, AnaghHegde commented
/ok-to-test sha=eb40146

2022-04-27 05:33 UTC, abhvsn approved these changes

2022-04-27 06:15 UTC, merged