Feature/track recently forked templates
appsmithorg/appsmith pull request #13159
Opened 2022-04-20 17:55 UTC by nayan-rafiq

## Description

This PR adds feature to track recently forked templates by the user. 

Fixes #12339

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- JUnit tests

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-04-22 10:18 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/ApplicationTemplateControllerCE.java
>                  .map(templates -> new ResponseDTO<>(HttpStatus.OK.value(), templates, null));
Why are we setting the value to null here ?

2022-04-22 10:21 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UserDataServiceCEImpl.java
> +                    addIdToRecentList(userData.getRecentlyUsedTemplateIds(), templateId, 5)
What does the number 5 represents here?

2022-04-22 10:23 UTC, AnaghHegde requested changes
One last thing, i noticed that we are adding the template ids to the userData object. Suppose if i use a same template multiples times, will the same id is added to the userData object multiple time? If yes, then can we keep the count or reorder the list of ids so that last used is always present at the top ?

2022-04-25 12:02 UTC, nayan-rafiq commented on app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/ApplicationTemplateControllerCE.java
>                  .map(templates -> new ResponseDTO<>(HttpStatus.OK.value(), templates, null));
`getActiveTemplates()` takes an optional list of id. If present, they'll be used to fetch only the provided templates. This method is called in two places - `get all templates` and `get recent templates`. We're providing a list of id for the later one. When getting all templates, this parameter is not required and hence sending null.

2022-04-25 12:03 UTC, nayan-rafiq commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UserDataServiceCEImpl.java
> +                    addIdToRecentList(userData.getRecentlyUsedTemplateIds(), templateId, 5)
We want to keep track of the last 5 recently used templates.

2022-04-25 12:06 UTC, nayan-rafiq commented
> One last thing, i noticed that we are adding the template ids to the userData object. Suppose if i use a same template multiples times, will the same id is added to the userData object multiple time? If yes, then can we keep the count or reorder the list of ids so that last used is always present at the top ?

Good point. It actually does this. The algorithm to add a new template id to the list is: 

- Prepend template id to the list
- Remove duplicates from the list
- Truncate the list to 5 if number of records are more than 5

The function that does this already exists and we use the same method to track recently used applications and organizations.

2022-04-25 12:17 UTC, nayan-rafiq commented
/ok-to-test sha=cab1e5f

2022-04-29 12:11 UTC, nayan-rafiq commented
/ok-to-test sha=cab1e5f

2022-05-09 05:15 UTC, nayan-rafiq commented
/ok-to-test sha=790276f

2022-05-10 06:12 UTC, nayan-rafiq commented
/ok-to-test sha=e0a2873

2022-05-10 07:28 UTC, merged