Add "back to home" CTA on 500 page (#1303)
appsmithorg/appsmith pull request #1319
Opened 2020-10-20 12:12 UTC by JeffResc

## Description
This PR adds a "Back to homepage" CTA on the [500 page](https://app.appsmith.com/500) to match the [400 page](https://app.appsmith.com/404).

Fixes #1303.

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Using the internal tests available on GitHub.

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

2020-10-20 12:12 UTC, JeffResc commented
The checklist mentions adding my own tests to test the functionality of this PR. Is something like that required for something minor like this?

2020-10-22 13:12 UTC, hetunandu requested changes

2020-10-22 13:12 UTC, hetunandu commented on app/client/src/pages/common/ServerUnavailable.tsx
> +        <Button
Button is not defined

2020-10-23 00:24 UTC, JeffResc commented on app/client/src/pages/common/ServerUnavailable.tsx
> +        <Button
Ah, got it, thanks 👍

2020-10-23 08:42 UTC, hetunandu commented
Hey @JeffResc almost there, there are a few [prettier](https://prettier.io/) errors that is failing your build. Can we fix that? Looks like it is mainly indent issues
<img width="752" alt="Screenshot 2020-10-23 at 2 11 52 PM" src="https://user-images.githubusercontent.com/12022471/96976653-ba6da880-1539-11eb-9504-ebd89a6036c8.png">

2020-10-23 19:57 UTC, JeffResc commented
@hetunandu Thanks for letting me know, I looked through the PR checks and it's hard to find where you're getting that error from, I looked for a while. Anyway, I installed [Preitter for VSCode](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode), then configured and ran it, but it only seemed to change some formatting on line 12 rather than adjust the indentations. Is there a more preferred way to run Prettier to get it to output correctly?

2020-10-24 02:49 UTC, hetunandu commented
Ideally this should be caught and fixed when you commit. Let me get back to you on this.

2020-10-24 02:49 UTC, hetunandu commented
Ideally this should be caught and fixed when you commit. Let me get back to you on this.

2020-10-27 05:14 UTC, hetunandu commented
@JeffResc Not being able to debug this as it seems to work properly on my side. Seems like we have some issue with our lint-staged plugin as this [file.](https://github.com/appsmithorg/appsmith/blob/release/app/client/.lintstagedrc) is not getting triggered. If you don't mind can you fix this manually as it is not working automatically? 

Sorry for this issue. We will try to resolve this soon.

2020-10-27 05:37 UTC, hetunandu commented
😕
<img width="491" alt="Screenshot 2020-10-27 at 11 07 07 AM" src="https://user-images.githubusercontent.com/12022471/97261326-987b6b00-1844-11eb-9cb6-dff8464297fc.png">

2020-10-27 05:39 UTC, JeffResc commented
@hetunandu Huh, I ran `npx eslint --fix`, then `npx prettier --write <file>` and commited my changes. Is that right?

2020-10-27 05:45 UTC, hetunandu commented
> @hetunandu Huh, I ran `npx eslint --fix`, then `npx prettier --write <file>` and commited my changes. Is that right?

Yes it should have worked. It always works on our side. Can you add any other details about your issue here #1411

2020-10-28 07:48 UTC, hetunandu requested changes

2020-10-28 07:48 UTC, hetunandu commented on app/client/src/pages/common/ServerUnavailable.tsx
> +    font-weight: ${(props) => props.theme.fontWeights[3]};
```suggestion
    font-weight: ${props => props.theme.fontWeights[3]};
```

2020-10-28 08:08 UTC, hetunandu approved these changes

2020-10-28 08:08 UTC, merged