fix: Prevent sync functions from running on pageload
appsmithorg/appsmith pull request #13200
Opened 2022-04-21 18:30 UTC by ohansFavour

## Description

Fixes # (issue)

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Jest

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-04-21 18:32 UTC, ohansFavour commented
/ok-to-test sha=739689d

2022-04-27 08:49 UTC, ApekshaBhosale requested changes

2022-04-27 08:49 UTC, ApekshaBhosale commented on app/client/src/utils/JSPaneUtils.tsx
> +            executeOnLoad: action.isAsync ? preExisted.executeOnLoad : false,
if it is not async it shouldn't be executed on page load. it is still coming in the layout call? because we take functions from there. if you set this, I think this will manually set the value and behavior becomes different. can you talk to @nidhi-nair and confirm this?

2022-05-03 15:20 UTC, ohansFavour commented on app/client/src/utils/JSPaneUtils.tsx
> +            executeOnLoad: action.isAsync ? preExisted.executeOnLoad : false,
@ApekshaBhosale, with this change, in layout calls;  sync functions don't come as part of pageActions (which run on page load). After the modification here, `updateJSCollection` causes update of the executeOnLoad property on the server side.

2022-05-10 09:14 UTC, closed without merging