[WIP] - Format JS code
appsmithorg/appsmith pull request #13222
Opened 2022-04-22 11:14 UTC by rimildeyjsr

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.

## Description

> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change.

Fixes # (issue)

> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-05-13 06:36 UTC, eco-monk commented on app/client/src/utils/AnalyticsUtil.tsx
>    | "PROPERTY_PANE_OPEN_CLICK"
`PROPERTY_PANE_CLOSE_CLICK`, `CREATE_DATA_SOURCE_AUTH_API_CLICK` and a few other events are removed from this list.
is this intentional?

2022-05-13 06:36 UTC, eco-monk commented on app/client/src/utils/helpers.tsx
> +    for (let index = 0; index < platformOSList.length; index++) {
This loop could be simplified?
`platformOSList.find(([os, regex]) => regex.test(browserPlatform))`

2022-05-13 06:36 UTC, eco-monk commented on app/client/public/tinymce/tinymce.min.js
> +import {isMacOrIOS} from "../../src/utils/helpers";
@Rishabh-Rathod / @ApekshaBhosale / @ohansFavour could use your comment on this.
Is it okay to add / import code here?
I'm not sure if there are any cons to this.

@rimildeyjsr, Since this is a library.
I would suggest adding comments in the file. About where and why this function is being used.
Also about any other changes that you might have made in this file.
So, we don't miss these details when working on this file.

2022-05-16 04:23 UTC, Rishabh-Rathod commented on app/client/public/tinymce/tinymce.min.js
> +import {isMacOrIOS} from "../../src/utils/helpers";
> Is it okay to add / import code here?

I would like to understand the need of importing the file inside the library code here. 
@rimildeyjsr 
We should try to not modify the minified library code.

2022-05-16 04:48 UTC, Rishabh-Rathod commented on app/client/src/components/ads/TreeDropdown.tsx
> +  min-width: 260px;
`TreeDropdown` component is a common component being used at multiple places, are we planning to change the min-widget for all of those use-cases?

2022-05-16 04:48 UTC, Rishabh-Rathod commented on app/client/src/pages/Editor/Explorer/JSActions/MoreJSActionsMenu.tsx
> +import AnalyticsUtil from "../../../../utils/AnalyticsUtil";
```suggestion
} from "components/editorComponents/CodeEditor/utils/autoIndentUtils";
import AnalyticsUtil from "utils/AnalyticsUtil";
```

2022-05-16 04:48 UTC, Rishabh-Rathod commented on app/client/src/pages/Editor/Explorer/JSActions/MoreJSActionsMenu.tsx
> +            autoIndentCode(editor);
Can we also mention why we need `@ts-ignore` here?
In the future, if we upgrade typescript and those challenges are resolved we could remove such `@ts-ignore`.

2022-05-16 04:48 UTC, Rishabh-Rathod commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/WidgetGrouping/WidgetGrouping_spec.js
> +    const isMacOrIOS = Cypress.platform === "darwin";
In line 2, we imported `isMacOrIOS`, and it was re-declared here. Is it intentional?

2022-05-16 04:48 UTC, Rishabh-Rathod commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/GlobalSearch/GlobalSearch_spec.js
> +    const isMacOrIOS = Cypress.platform === "darwin";
In line 5, we imported isMacOrIOS, and it was re-declared here. Is it intentional?

2022-05-16 04:48 UTC, Rishabh-Rathod commented on app/client/src/pages/Editor/Explorer/JSActions/MoreJSActionsMenu.tsx
> +  const prettifyCodeKeyboardShortCut = getAutoIndentShortcutKeyText();
We could declare `prettifyCodeKeyboardShortCut` outside the component avoiding to call `getAutoIndentShortcutKeyText()` on each rendering event of component.

2022-05-17 10:33 UTC, Rishabh-Rathod commented on app/client/src/components/ads/TreeDropdown.tsx
> +    min-width: 220px;
```suggestion
    min-width: 260px;
```
We can undo min-widget to 260px correct?

2022-05-18 08:01 UTC, rimildeyjsr commented on app/client/src/pages/Editor/Explorer/JSActions/MoreJSActionsMenu.tsx
> +            autoIndentCode(editor);
done

2022-05-18 08:01 UTC, rimildeyjsr commented on app/client/src/utils/AnalyticsUtil.tsx
>    | "PROPERTY_PANE_OPEN_CLICK"
these were duplicated, hence removed them

2022-05-18 08:10 UTC, rimildeyjsr commented on app/client/src/pages/Editor/Explorer/JSActions/MoreJSActionsMenu.tsx
> +  const prettifyCodeKeyboardShortCut = getAutoIndentShortcutKeyText();
done

2022-05-18 08:10 UTC, rimildeyjsr commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/GlobalSearch/GlobalSearch_spec.js
> +    const isMacOrIOS = Cypress.platform === "darwin";
done

2022-05-18 08:10 UTC, rimildeyjsr commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/WidgetGrouping/WidgetGrouping_spec.js
> +    const isMacOrIOS = Cypress.platform === "darwin";
done

2022-05-18 09:01 UTC, rimildeyjsr commented on app/client/public/tinymce/tinymce.min.js
> +import {isMacOrIOS} from "../../src/utils/helpers";
@eco-monk @Rishabh-Rathod - I was just grepping through the files to make the changes, will remove it if required

2022-05-18 09:01 UTC, rimildeyjsr commented on app/client/src/utils/helpers.tsx
> +    for (let index = 0; index < platformOSList.length; index++) {
done

2022-05-18 09:01 UTC, rimildeyjsr commented on app/client/src/components/editorComponents/CodeEditor/index.tsx
> +      if (this.props.showLineNumbers && !isReadOnly) {
removed

2022-06-06 11:53 UTC, ohansFavour commented on app/client/src/components/editorComponents/CodeEditor/utils/autoIndentUtils.ts
> +    if (!!lineNumber) {
We won't ever prettify the first line (lineNumber === 0). Is this deliberate?

Consider using lodash's `isNil()`

2022-06-06 11:59 UTC, ohansFavour commented on app/client/src/components/editorComponents/CodeEditor/index.tsx
> +      const isReadOnly = !this.props.input.onChange || this.props.disabled;
We already have a `isReadOnly` prop, can we use that instead?

2022-06-07 06:37 UTC, rimildeyjsr commented on app/client/src/components/editorComponents/CodeEditor/utils/autoIndentUtils.ts
> +    if (!!lineNumber) {
@ohansFavour - good catch! changing

2022-06-07 06:59 UTC, rimildeyjsr commented on app/client/src/components/editorComponents/CodeEditor/index.tsx
> +      const isReadOnly = !this.props.input.onChange || this.props.disabled;
done

2022-06-21 08:34 UTC, Rishabh-Rathod submitted a review, later dismissed
LGTM

2022-06-21 08:44 UTC, Rishabh-Rathod commented
Have we tested shortcuts for windows, linux and macOS all three platform?
@rimildeyjsr  @ramsaptami

2022-06-21 09:48 UTC, ramsaptami commented
@yaldram Could you please comment here?

2022-06-22 08:22 UTC, arslanhaiderbuttar commented
> Have we tested shortcuts for windows, linux and macOS all three platform? @rimildeyjsr @ramsaptami

cmd+option+F is not working in macOS
@ramsaptami @Rishabh-Rathod

2022-06-22 09:37 UTC, Aishwarya-U-R commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/LayoutValidation/JSEditorIndent_spec.js
> +      .wait(3000); //allowing time to prettify!
Why are 2 clicks on Preetify Code needed? I added it in first case I wrote because of existence of bug that time.. does that still exists?

And for the code editor click aft preetifying.. can you write cypress covering that also - to make sure that preetify does not revert?

2022-06-22 10:08 UTC, ohansFavour approved these changes
Code changes look good.

2022-06-28 07:16 UTC, rimildeyjsr commented
/ok-to-test sha=21a3b17

2022-06-28 08:31 UTC, Aishwarya-U-R commented
Issues:
1. JS Editor is unusable for few secods after applying Preetify code & upon clicking inside JSEditor once click is enabled is also reverting the applied Preetify
2. Changing function names from dropdown from JSEditor is reverting applied Preetify
3. Running a function from JSEditoris reverting applied Preetify

**Attached video showing the above issues:**

https://user-images.githubusercontent.com/91450662/176132105-55b9e34a-c56b-4f81-a6af-510008ef7f2b.mov

2022-06-30 09:39 UTC, ohansFavour submitted a review, later dismissed

2022-06-30 09:50 UTC, rimildeyjsr commented
/ok-to-test sha=e385b8d

2022-07-01 06:38 UTC, rimildeyjsr commented
/ok-to-test sha=e14b653

2022-07-04 09:57 UTC, rimildeyjsr commented
/ok-to-test sha=dd45a22

2022-07-05 06:13 UTC, rimildeyjsr commented
/ok-to-test sha=01f0446

2022-07-05 07:48 UTC, Aishwarya-U-R commented
@rimildeyjsr - can you correct the error seen at in this PR run : https://dashboard.cypress.io/projects/eyxvp8/runs/21023/overview

2022-07-05 07:49 UTC, Aishwarya-U-R requested changes
Correct errors seen at : https://dashboard.cypress.io/projects/eyxvp8/runs/21023/overview

2022-07-05 08:16 UTC, rimildeyjsr commented
> @rimildeyjsr - Can you correct errors seen at : https://dashboard.cypress.io/projects/eyxvp8/runs/21023/overview

@Aishwarya-U-R - these tests are unrelated to my PR, and the CI run was successful

2022-07-05 09:40 UTC, Aishwarya-U-R requested changes
Nope, please correct them.. I see them modified in ur PR:

GlobalSearch_spec.js & WidgetGrouping_spec.js

2022-07-07 04:45 UTC, rimildeyjsr commented
/ok-to-test sha=c213ddd

2022-07-07 06:08 UTC, rimildeyjsr commented
/ok-to-test sha=c330910

2022-07-07 11:05 UTC, rimildeyjsr commented
/ok-to-test sha=f208484

2022-07-08 07:12 UTC, rimildeyjsr commented
/ok-to-test sha=dc785db

2022-07-08 11:40 UTC, rimildeyjsr commented
/ok-to-test sha=f9f0cc5

2022-07-13 05:26 UTC, rimildeyjsr commented
/ok-to-test sha=1b391c6

2022-07-13 15:13 UTC, Aishwarya-U-R commented
/ok-to-test sha=cc87579

2022-07-13 16:23 UTC, Aishwarya-U-R commented
/ok-to-test sha=b33f982

2022-07-14 12:49 UTC, Aishwarya-U-R submitted a review, later dismissed
Approving cypress tests!

2022-07-14 12:50 UTC, ApekshaBhosale commented
ok-to-test sha=7fa4975

2022-07-14 13:39 UTC, Aishwarya-U-R commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/VisualTests/JSEditorIndent_spec.js
> +describe("JSEditor Indendation - Visual tests", () => {
@Rishabh-Rathod - where do you see the relation for #1865 here? <img width="43" alt="Screenshot 2022-07-14 at 7 09 14 PM" src="https://user-images.githubusercontent.com/91450662/178995812-b0aafa82-0c69-4053-83e3-f7470b0fa6ff.png">

2022-07-14 13:43 UTC, Aishwarya-U-R commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/VisualTests/JSEditorIndent_spec.js
> +describe("JSEditor Indendation - Visual tests", () => {
@Rishabh-Rathod - Sorry, corrected the link to the correct test smith now!

2022-07-15 08:50 UTC, Aishwarya-U-R commented
/ok-to-test sha=04077d7

2022-07-18 07:01 UTC, rimildeyjsr commented
/ok-to-test sha=84370ce

2022-07-18 12:46 UTC, Aishwarya-U-R commented
/ok-to-test sha=16fcb99

2022-07-19 06:01 UTC, ohansFavour approved these changes
Looks good

2022-07-20 07:13 UTC, merged