Apply serverSide Filtering Condition
appsmithorg/appsmith pull request #13245
Opened 2022-04-24 18:19 UTC by Tooluloope

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.

## Description

> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change.

Fixes # (issue)

> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-04-25 08:37 UTC, Tooluloope commented on app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx
> +    this.props.updateWidgetMetaProperty("selectedOptions", value);
@ashit-rath Could you help confirm if this would suffice for the serverside filtering Implementation

2022-04-26 05:03 UTC, ashit-rath commented
@Tooluloope Please update the description of this PR with appropriate title

2022-04-26 06:05 UTC, Tooluloope commented
> @Tooluloope Please update the description of this PR with appropriate title

Done.

Although this PR meant to be for #13079

2022-04-26 13:28 UTC, ashit-rath commented on app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx
> +    this.props.updateWidgetMetaProperty("selectedOptions", value);
So for the server side, we are not bothering about the selected option being present in the options list, we always show whatever is selected but we do bother when server side is disabled i.e if the select option is not present options we completely remove it.
This is what is a bit confusing to me as the options can be populated dynamically irrespective of server side enabled or not. It's just that when server side is enabled the onFilterUpdate event is enabled.
Is this the right way forward from a product point of view?

2022-04-28 01:11 UTC, Tooluloope commented on app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx
> +    this.props.updateWidgetMetaProperty("selectedOptions", value);
IMO, as long as the option changes and it's not serverside filtered, it should be strictly checked

2022-04-28 01:15 UTC, Tooluloope commented on app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx
> +      selectedOptionValues: `{{!this.serverSideFiltering ? this.selectedOptions?.filter(selectedOption => this.options?.some(option => option.value === (selectedOption.value ?? selectedOption))).map(
@ashit-rath @wmdev0808 Here was the solution I proposed earlier, Handling the Serverside check in the derived Properties. Here, nothing is changed in place but just consumed.

It feels hacky but then @wmdev0808 You could make it look better.

2022-04-28 03:12 UTC, wmdev0808 requested changes
@Tooluloope ,
First, thank you for your trouble.
BTW, isDirty does not work as expected
> Steps to reproduce: 
- Drop a text widget and bind to `isDirty`
- Select an option from the widget, resulting in `isDirty` to `true`
- Change `Default Value`, then the bound property `isDirty` does not change to `false`

2022-04-28 08:23 UTC, Tooluloope commented on app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx
> +    this.props.updateWidgetMetaProperty("selectedOptions", value);
@ashit-rath

2022-04-29 04:35 UTC, closed without merging