fix: Git connected Application forking should use default branch application
appsmithorg/appsmith pull request #13255
Opened 2022-04-25 05:53 UTC by AnaghHegde

## Description

> For git connected application user can update the default branch. When the user updated the default branch forking service should use the default branched application not the original(appsmith default) application. 

Fixes #13185 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- JUnit Tests
- Locally

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-04-25 05:57 UTC, AnaghHegde commented
/ok-to-test sha=54f835d

2022-04-25 09:15 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ApplicationForkingServiceCEImpl.java
> +                .flatMap(application -> {
Let's make changes to upstream method as it has branch reference already:
```
public Mono<Application> forkApplicationToOrganization(String srcApplicationId,
                                                           String targetOrganizationId,
                                                           String branchName)
```

2022-04-25 09:16 UTC, abhvsn reviewed
Can you please fix this for other APIs as well:
1. Duplicate
2. Export

2022-04-26 03:09 UTC, AnaghHegde commented
@abhvsn We do not fetch the application there. It would be good to add it here right?

2022-04-28 11:14 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ApplicationForkingServiceCEImpl.java
> +                .flatMap(application -> {
Can we please move this to requested location just like we had done for cloneApplication?

2022-04-28 11:17 UTC, abhvsn commented
> @abhvsn We do not fetch the application there. It would be good to add it here right?

But here we expect we have the actual `srcApplicationId`, which is a abstraction layer we have between the actual business logic and the controller

2022-04-28 11:20 UTC, abhvsn requested changes
Please follow the same implementation that we have for duplicate application API. Also can you please add the same for export application

2022-04-29 11:40 UTC, abhvsn requested changes

2022-04-29 11:40 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ApplicationForkingServiceCEImpl.java
> +                                    AclPermission.MANAGE_APPLICATIONS
Please update this with read_permission as forking is enabled for view access as well for sample apps

2022-04-29 12:05 UTC, AnaghHegde commented
/ok-to-test sha=bb5825e

2022-04-29 13:35 UTC, merged