feat: add build tools as part of Dockerfile
appsmithorg/appsmith pull request #13278
Opened 2022-04-25 13:15 UTC by pratapaprasanna

Issue: [11820](https://github.com/appsmithorg/appsmith/issues/11820)

Currently, any engineer has to run a script and then run ```docker build ``` to build the docker image.
Ideally, an engineer should just use docker build and get all the stuff generated followed by the image built.

## Description

Currently, any engineer has to run a script and then run
```docker build ``` to build the docker image.
Ideally, an engineer should just use docker build and get all
the stuff generated and the image to be built.

Fixes # (11820)

> [11820](https://github.com/appsmithorg/appsmith/issues/11820)

## Type of change

- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?

Build the docker image locally and jars are built as a part of another `docker build` itself.

**Build steps**
<img width="1417" alt="Screenshot 2022-03-15 at 11 25 31 AM" src="https://user-images.githubusercontent.com/15846947/158315993-d8463966-d113-4d1d-98f6-eba2b0c60188.png">

**contents of the container**

Above is the 

* appsmith-ce image
* built image with the PR

<img width="1785" alt="Screenshot 2022-03-24 at 7 26 55 PM" src="https://user-images.githubusercontent.com/15846947/159932470-a718bd6e-512b-4d2f-a323-4706907be4b5.png">

* Local deployment

<img width="1437" alt="Screenshot 2022-04-06 at 4 01 17 PM" src="https://user-images.githubusercontent.com/15846947/161955895-d7d182c5-9a2a-4d09-a870-4d070fdadbde.png">

2022-04-27 08:35 UTC, sharat87 commented on Dockerfile
> +FROM openjdk:11 as javabuild
Can we use the same JDK as the server slim image please?

https://github.com/appsmithorg/appsmith/blob/fc36a3af94350aa8b07f8cf82e881c532431bd80/app/server/Dockerfile#L3

Also, to be inline with the other two, should we name this `serverbuild` instead of `javabuild`.

2022-04-27 08:36 UTC, sharat87 commented on Dockerfile
> +FROM node:14 as rtsbuild
Also here, can we use the exact version specified in the package.json file please?

https://github.com/appsmithorg/appsmith/blob/fc36a3af94350aa8b07f8cf82e881c532431bd80/app/rts/package.json#L10

https://hub.docker.com/_/node?tab=tags&page=1&name=14.15.4

2022-04-27 08:40 UTC, sharat87 commented on Dockerfile
> +FROM node:14 as clientbuild
Also here, can we use the exact version specified in the package.json file please?

https://github.com/appsmithorg/appsmith/blob/fc36a3af94350aa8b07f8cf82e881c532431bd80/app/client/package.json#L6

https://hub.docker.com/_/node?tab=tags&page=1&name=14.15.4

2022-04-27 08:44 UTC, sharat87 commented on Dockerfile
> +COPY .git /app
I'm guessing we are doing this only for the GIT_SHA in the build script, right? Can we just grab that and use it instead of copying the whole `.git` folder?

Like, in https://github.com/appsmithorg/appsmith/blob/fc36a3af94350aa8b07f8cf82e881c532431bd80/app/client/build.sh#L5-L6, we'll wrap it with `if [[ -z "${GIT_SHA-}" ]]; then` and `fi`.

Then, we'll get the SHA here in the Dockerfile, and set it for the `yarn build` command. This feels cleaner. What say?

2022-04-27 08:45 UTC, sharat87 commented on Dockerfile
> +RUN yarn install; yarn build
Let's do a `--frozen-lockfile` here as well, just as you did with RTS.

2022-04-28 08:08 UTC, pratapaprasanna commented on Dockerfile
> +FROM openjdk:11 as javabuild
* Will change to `serverbuild`
* regarding using the same alpine image is that in the mac-books with M1 i see this error

```
(base) ➜  appsmith git:(release) ✗ docker build . -t serverbuild
Sending build context to Docker daemon  315.8MB
Step 1/5 : FROM adoptopenjdk/openjdk11:jdk-11.0.10_9-alpine  as serverbuild
jdk-11.0.10_9-alpine: Pulling from adoptopenjdk/openjdk11
no matching manifest for linux/arm64/v8 in the manifest list entries
```

In other devices i get this
```
(ansible) ➜  test_write docker build . -t temp_java
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM adaptopenjdk/openjdk:jdk-11.0.10_9-alpine as serverbuild
pull access denied for adaptopenjdk/openjdk, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

So i tried using the alternative java image . Incase we can do it in a different way please do let me know thanks

2022-04-28 08:08 UTC, pratapaprasanna commented on Dockerfile
> +FROM node:14 as rtsbuild
Noted

2022-04-28 08:08 UTC, pratapaprasanna commented on Dockerfile
> +FROM node:14 as clientbuild
noted

2022-04-28 08:11 UTC, pratapaprasanna commented on Dockerfile
> +COPY .git /app
the other alternative would be to use 
```docker build --build-arg GIT_SHA=$(git rev-parse HEAD) -t appsmith .```
and make changes to the script as per your suggestions 
eg:

```
if [[ -z "${GIT_SHA-}" ]]; then 
  GIT_SHA=$(eval git rev-parse HEAD)
  echo $GIT_SHA 
fi
```

2022-04-28 08:11 UTC, pratapaprasanna commented on Dockerfile
> +RUN yarn install; yarn build
Noted

2022-04-28 09:40 UTC, pratapaprasanna commented on Dockerfile
> +RUN curl https://packages.redis.io/gpg | apt-key add - \
when i tried with latest ubuntu:20.04 lts docker image there seems to be an issue with installing redis

Therefore changed it.

2022-04-28 11:28 UTC, sharat87 commented on Dockerfile
> +FROM openjdk:11 as javabuild
Oh sorry, I wasn't clear. I just meant that let's use the same _JDK version_, doesn't have to be alpine, some other base is also okay. As long as the Java version is consistent. :)

2022-05-09 12:19 UTC, mohanarpit commented on Dockerfile
> -  && apt-get clean \
Are these commands no longer required? If not, can you help me understand why?

2022-05-09 12:21 UTC, mohanarpit commented on Dockerfile
> +RUN mv ${JAR_FILE} backend/server.jar
Can you help me understand why we moved from COPY to RUN here? Is RUN command better?

2022-05-09 12:23 UTC, mohanarpit commented on Makefile
> +# Latest commit hash
Is this makefile already being used somewhere? If yes, can you point me in that direction? I didn't seem to find it in this PR, hence I'm asking.

2022-05-10 01:36 UTC, sharat87 commented on Dockerfile
> -  && apt-get clean \
This is odd. These lines were already removed on the release branch a while ago. I'm not sure why they are showing up here.

@pratapaprasanna, can you try pulling release into your branch once?

2022-05-10 03:49 UTC, pratapaprasanna commented on Dockerfile
> -  && apt-get clean \
Sure, @sharat87  its an issue with the rebase will rebase this again.

2022-05-10 03:55 UTC, pratapaprasanna commented on Dockerfile
> +RUN mv ${JAR_FILE} backend/server.jar
1- No COPY and RUN are two different things
2- In this new approach, i.e multi-stage docker build 
[line88](https://github.com/appsmithorg/appsmith/pull/13278/files/87f3ff98e68a6e9b9d64d4bbc63a045763954e5f#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R88) you can see we are copying the jar into `/opt` in Line103 we are just the moving the jars to `backend`

2022-05-10 04:02 UTC, pratapaprasanna commented on Makefile
> +# Latest commit hash
I think the context is not mentioned [here](https://github.com/appsmithorg/appsmith/pull/13278#discussion_r859540452),
 
The Makefile, is something we are using for the first time. and following are the reasons
1- It was recommended not to copy `.git` to the client build. But,  inorder to build the client dist we need latest git sha and a reasonable way to get the GIT_SHA into the container is via the build-arg parameter.
2- We use the makefile to build images as mentioned in the description.
3- Not a fan of Make but to avoid copying of `.git` into the container i took this approach. However, we can use make in various other steps going forward (if needed)

2022-05-10 04:11 UTC, sharat87 commented on Makefile
> +# Latest commit hash
Can you link to where we are running `make` though? Since, without running `make`, nothing in the `Makefile` would run right?

Also, can we not run the commands in the `Makefile`, directly from `Dockerfile` itself?

2022-05-10 05:16 UTC, pratapaprasanna commented on Makefile
> +# Latest commit hash
Instead of `docker build . -t appsmith` we run `make build` to build the docker image 
**for arm** 
we run `make build-arm`

2022-05-10 05:25 UTC, pratapaprasanna commented on Dockerfile
> -  && apt-get clean \
rebased

2022-05-10 06:00 UTC, mohanarpit commented on Makefile
> +# Latest commit hash
If we are moving to `make` commands, should we modify this in our CI as well to leverage this Makefile?

2022-05-10 07:24 UTC, pratapaprasanna commented on Makefile
> +# Latest commit hash
Yes, will try to modify them.

2022-05-13 10:11 UTC, mohanarpit commented on .github/workflows/test-build-docker-image-fat.yml
> +          make build
The actual fat container that is uploaded to Docker Hub is built in the file: `test-build-docker-image.yml` . This particular CI workflow was created only to test the fat container. 

Should we be modifying the docker build command in the other CI file as well? Or do you think we should take that up as a separate PR?

2022-05-13 10:14 UTC, mohanarpit commented on app/client/build.sh
> +if [ -z $GIT_SHA ]
In what scenarios will the GIT_SHA not be available to us when building the code? This sha is used to mark a new release in Sentry. Hence, should we let the build fail/crash if the GIT sha is not available? Else, there may be scenarios where even though the sha isn't avaiable, the build will succeed. That might cause more issues.

2022-05-16 05:29 UTC, sharat87 commented on Makefile
> +# Latest commit hash
A minor question on this, I see that `build` target is building amd64, and `build-arm` is building arm64. But this will only hold true on am64 systems right? On arm64 systems, I imagine both will build images for arm64 only, no?

2022-05-18 06:56 UTC, pratapaprasanna commented on .github/workflows/test-build-docker-image-fat.yml
> +          make build
I think we still need time to make changes to the test-build-docker-image.yml the reason being there are a lot of steps and I want to know the necessity for those steps

2022-05-20 10:39 UTC, pratapaprasanna commented on app/client/build.sh
> +if [ -z $GIT_SHA ]
This can happen in the scenario where some engineer runs 

`docker build . -t fat_container`

instead of  `docker build --build-arg GIT_SHA=${GITHUB_SHA} . -t fat_container`.

In the Dockerfile we are not copying the `.git` folder. Rather, we take the sha in build args and bake it as an environment variable in the container. So, in case if the sha is not sent as part of build args the docker build it will fail.

To also let the engineers build client locally, using 

`yarn install --frozen-lockfile; yarn build`

 Where the GIT_SHA wont be there by default but the script will get the git_sha and wont fail.

2022-05-20 10:42 UTC, pratapaprasanna commented on Makefile
> +# Latest commit hash
@sharat87 thanks for pointing out addressed it now.

2022-06-01 07:26 UTC, sharat87 requested changes
Few minor changes, otherwise ready to merge. Let's get this in after the current freeze is done. Thanks!

2022-06-01 07:26 UTC, sharat87 commented on .github/workflows/test-build-docker-image.yml
> +          docker build . --build-arg GIT_SHA=${GITHUB_SHA} -t fatcontainer
We are moving the `.` to be ahead of the arguments here, unlike in the other workflows. Is that okay?

2022-06-01 07:26 UTC, sharat87 commented on .github/workflows/test-build-docker-image.yml
> +            --build-arg GIT_SHA=${GITHUB_SHA} APPSMITH_SEGMENT_CE_KEY=${{ secrets.APPSMITH_SEGMENT_CE_KEY_RELEASE }} \
This needs another `--build-arg`, no?

```suggestion
            --build-arg GIT_SHA="${GITHUB_SHA}" \
            --build-arg APPSMITH_SEGMENT_CE_KEY="${{ secrets.APPSMITH_SEGMENT_CE_KEY_RELEASE }}" \
```

2022-06-01 07:26 UTC, sharat87 commented on .github/workflows/test-build-docker-image.yml
> +            --build-arg GIT_SHA=${GITHUB_SHA} APPSMITH_SEGMENT_CE_KEY=${{ secrets.APPSMITH_SEGMENT_CE_KEY }} \
Same here.

```suggestion
            --build-arg GIT_SHA="${GITHUB_SHA}" \
            --build-arg APPSMITH_SEGMENT_CE_KEY="${{ secrets.APPSMITH_SEGMENT_CE_KEY }}" \
```

2022-06-01 07:26 UTC, sharat87 commented on Dockerfile
> +FROM node:14.15.4 as clientbuild
Looks like we've upgraded here. 😅

https://github.com/appsmithorg/appsmith/blob/73e43fadbd7e5aaa6d87e3419cf0106976ab92d3/app/client/package.json#L6

```suggestion
FROM node:16.14.0 as clientbuild
```

2022-06-01 07:26 UTC, sharat87 commented on app/client/build.sh
> +if [ -z $GIT_SHA ]
Please use bash + double braces + unquoted variables, or sh + quoted variables + single braces. Only those two combinations work reliably.

```suggestion
if [ -z "$GIT_SHA" ]
```

2022-06-23 11:40 UTC, pratapaprasanna commented on .github/workflows/test-build-docker-image.yml
> +          docker build . --build-arg GIT_SHA=${GITHUB_SHA} -t fatcontainer
It will be the same behavior only, However shifting for the sake of consistency

2022-06-23 11:42 UTC, Athayde3586 commented
Stop

On Thu, Jun 23, 2022, 6:41 AM Goutham Pratapa ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In .github/workflows/test-build-docker-image.yml
> <https://github.com/appsmithorg/appsmith/pull/13278#discussion_r904916559>
> :
>
> > @@ -533,7 +533,7 @@ jobs:
>          if: steps.run_result.outputs.run_result != 'success'
>          working-directory: "."
>          run: |
> -          docker build -t fatcontainer .
> +          docker build . --build-arg GIT_SHA=${GITHUB_SHA} -t fatcontainer
>
> It will be the same behavior only, However shifting for the sake of
> consistency
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/appsmithorg/appsmith/pull/13278#discussion_r904916559>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AYYXGWWVVGPOFTX77F4EVULVQRENVANCNFSM5UIRGSGQ>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2023-05-04 04:38 UTC, mohanarpit commented
Closing this as we have now crossed the 1-year anniversary for this PR. 😄

2023-05-04 04:38 UTC, closed without merging