Entity Explorer Render
appsmithorg/appsmith pull request #1354
Opened 2020-10-22 17:57 UTC by riodeuno

## Description
We've noticed that the entity explorer, particularly the entity properties re-render multiple times when it is not necessary.
This attempts to manage the number of unnecessary renders for the entity explorer.

Fixes #750 

## Type of change
Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
Unit tests have been added to test the canvas structure generator (performance and functionality)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2020-10-28 11:35 UTC, hetunandu requested changes
Minor changes needed

2020-10-28 11:35 UTC, hetunandu commented on app/client/.eslintrc.js
> +    "@typescript-eslint/ban-ts-ignore": 0,
is this still needed? I think we solved this with the ban-comment rule itself right?

2020-10-28 11:35 UTC, hetunandu commented on app/client/cypress/integration/Smoke_TestSuite/Binding/InputWidgets_NavigateTo_validation_spec.js
> +    cy.get(`.t--entity-name:contains("${pageid}")`).should("be.visible");
We should add this in the `Createpage` command itself

2020-10-28 14:24 UTC, hetunandu requested changes

2020-10-28 14:24 UTC, hetunandu commented on app/client/.eslintrc.js
> +    "@typescript-eslint/ban-ts-ignore": 0,
This means that `@ts-ignore` can now be written without any warning or error. I would suggest instead of disabling this issue, we go with the workaround where we commit with `--no-verify` flag. That way any new `@ts-ignore` is still flagged in newer commits. You will have to revert all changes to eslint-disable comments as well

2020-11-02 05:26 UTC, riodeuno commented on app/client/.eslintrc.js
> +    "@typescript-eslint/ban-ts-ignore": 0,
This has been fixed holistically, by upgrading a few packages. Now, there are no discrepancies between the linting during commit, and building the project. ban-ts-ignore is deprecated and ban-ts-comment is the enforced rule.

2020-11-03 04:58 UTC, hetunandu approved these changes

2020-11-03 09:55 UTC, hetunandu approved these changes

2020-11-03 13:05 UTC, merged