fix: NPE when `connectionCookie` is `undefined`
appsmithorg/appsmith pull request #13541
Opened 2022-05-04 01:39 UTC by sharat87

Fix NPE in RTS when the `connectionCookie` is `undefined`.

2022-05-04 04:34 UTC, IAmAnubhavSaini requested changes

2022-05-04 04:34 UTC, IAmAnubhavSaini commented on app/rts/src/server.ts
> +    if (connectionCookie == null || connectionCookie === "") {
`===` for the first check.

2022-05-04 04:34 UTC, IAmAnubhavSaini commented on app/rts/src/server.ts
> +    const matchedCookie = connectionCookie.match(/\bSESSION=\S+/);
Following check is missing:

```
if (!matchedCookie) {
    return false;
}
```

Then the code block in `matchedCookie` can be unindented too.

2022-05-04 04:34 UTC, IAmAnubhavSaini commented on app/rts/src/server.ts
> +        const email = response.data.data.email;
`response?.data?.data?.email`

2022-05-04 04:34 UTC, IAmAnubhavSaini commented on app/rts/src/server.ts
>      const connectionCookie = socket.handshake.headers.cookie;
`socket?.handshake?.headers?.cookie`

2022-05-04 04:34 UTC, IAmAnubhavSaini commented on app/rts/src/server.ts
> +        const name = response.data.data.name ? response.data.data.name : email;
same as above

2022-05-04 10:33 UTC, sharat87 commented on app/rts/src/server.ts
> +    if (connectionCookie == null || connectionCookie === "") {
That was the problem actually. If we use `===` for `null`, then `undefined` will go through. I want to check for `null` and `undefined`. It is recommended to use `==` for null-checks in Javascript, and `===` everywhere else. Like the `smart` option in eslint: <https://eslint.org/docs/rules/eqeqeq>.

2022-05-04 10:42 UTC, sharat87 commented on app/rts/src/server.ts
> +        const email = response.data.data.email;
Done.

2022-05-04 10:42 UTC, sharat87 commented on app/rts/src/server.ts
>      const connectionCookie = socket.handshake.headers.cookie;
Done.

2022-05-04 10:42 UTC, sharat87 commented on app/rts/src/server.ts
> +        const name = response.data.data.name ? response.data.data.name : email;
Done.

2022-05-04 10:42 UTC, sharat87 commented on app/rts/src/server.ts
> +    const matchedCookie = connectionCookie.match(/\bSESSION=\S+/);
Good call, done. :)

2022-05-10 12:20 UTC, IAmAnubhavSaini commented on app/rts/src/server.ts
> +    if (connectionCookie == null || connectionCookie === "") {
@sharat87 This change is pending. For maintainability it is very important for code to be unsurprising and boring.

2022-05-16 05:52 UTC, sharat87 commented on app/rts/src/server.ts
> +    if (connectionCookie == null || connectionCookie === "") {
Done.

2022-05-16 06:10 UTC, IAmAnubhavSaini approved these changes

2022-05-27 11:34 UTC, merged