fix: Add support to generate ssh keys of type RSA
appsmithorg/appsmith pull request #13640
Opened 2022-05-06 07:51 UTC by AnaghHegde

## Description

> 

Fixes # (issue)

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Locally
- Unit Test

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-05-06 07:52 UTC, AnaghHegde commented
Tests are on the way

2022-05-06 08:34 UTC, abhvsn requested changes

2022-05-06 08:34 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/GitDeployKeyDTO.java
> +    String platFormSupported;
```suggestion
    String platformSupported;
```

2022-05-06 08:34 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationServiceCE.java
> +    Mono<GitAuth> createOrUpdateSshKeyPair(String applicationId, String keyType);
Should we share the supported keys array in the response itself so as to avoid another API call?

2022-05-06 08:34 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/GitDeployKeyGenerator.java
> +        }
Please invert the condition so that, we will generate RSA key only when requested for other scenarios we will always generate the key with ECDSA.

2022-05-06 12:04 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationServiceCE.java
> +    Mono<GitAuth> createOrUpdateSshKeyPair(String applicationId, String keyType);
Are you referring to get SSH Key response? I guess we can do that.

2022-05-06 12:06 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationServiceCE.java
> +    Mono<GitAuth> createOrUpdateSshKeyPair(String applicationId, String keyType);
Yes

2022-05-09 07:16 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/GitDeployKeyDTO.java
> +    String platFormSupported;
Should it be List<String> as many platforms can support particular protocol along with the size

2022-05-09 07:38 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/GitDeployKeyDTO.java
> +    String platFormSupported;
I was thinking of keeping it as a comma separated value.

2022-05-09 07:39 UTC, AnaghHegde commented
/ok-to-test sha=601975c

2022-05-09 08:34 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/GitDeployKeyDTO.java
> +    String platFormSupported;
I think keeping this as a List will give more flexibility on client-side.

2022-05-09 08:39 UTC, abhvsn approved these changes
LGTM
Just a minor comment

2022-05-10 08:19 UTC, AnaghHegde commented
Let's not merge this change as it is a breaking change. Once the client  changes are in we can merge this to release.

2022-05-10 08:31 UTC, IAmAnubhavSaini commented
@AnaghHegde What are the breaking changes? Are we not defaulting to earlier keyType?

2022-05-17 05:26 UTC, AnaghHegde commented
/ok-to-test sha=f4dff3c

2022-05-17 05:56 UTC, abhvsn submitted a review, later dismissed

2022-05-18 05:05 UTC, AnaghHegde commented
/ok-to-test sha=ac0d9a9

2022-05-25 09:57 UTC, AnaghHegde commented
/ok-to-test sha=1822d2f

2022-05-25 13:44 UTC, abhvsn approved these changes

2022-05-25 14:14 UTC, merged