chore: Add isSysteGenerated field to analytics for git operations
appsmithorg/appsmith pull request #13705
Opened 2022-05-10 06:07 UTC by AnaghHegde

## Description

> We want to distinguish the events generated from Appsmith vs the user-generated events to optimize the mixpanel funnels.

Fixes #13477 

## Type of change

> Please delete options that are not relevant.

- New feature (non-breaking change which adds functionality)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-05-12 06:44 UTC, abhvsn requested changes
As we are using the `isSystemGenerated` flag only in commit flow, does it make sense to keep 2 methods:
1. addAnalyticsForGitOperation(String eventName, Application application, Boolean isRepoPrivate, Boolean isSystemGenerated)
2. addAnalyticsForGitOperation(String eventName, Application application, Boolean isRepoPrivate)

This will prevent us from making larger change if this is only specific to certain flow

2022-05-12 06:44 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java
> +                                isSystemGenerated
Why are we adding the `isSystemGenerated` for error events?

2022-05-12 08:55 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java
> +                                isSystemGenerated
It is set false. But yeah i get what you are saying.

2022-05-12 10:55 UTC, AnaghHegde commented
@abhvsn Only commit is system generated action. All other cases are user generated. I would add a new method just for commit operation.

2022-05-18 03:53 UTC, abhvsn commented
@AnaghHegde can you please resolve the conflicts, I can start the review once this is done

2022-05-18 04:17 UTC, AnaghHegde commented
@abhvsn I have not made any changes. I want you to reply for the comments.

2022-05-18 09:03 UTC, abhvsn commented
> @abhvsn Only commit is system generated action. All other cases are user generated. I could add a new method just for commit operation. But if i do that then `isSystemGenerated` will be present for few cases and not at all present in other cases. What if i add one method where we set this only for commit operation. This way we would not have to deal with the problem of having to check if the value is present or not while building the charts in mixpanel.

Is this different from what I was expecting in above comment? Can you please elaborate how your approach will be different than what I was expecting here. The other part where you were asking for having `isSystemGenerated` boolean for all the events still can be achieved by specifically setting that variable in 
`addAnalyticsForGitOperation(String eventName, Application application, Boolean isRepoPrivate)`
https://github.com/appsmithorg/appsmith/pull/13705#pullrequestreview-970319295

2022-05-18 12:25 UTC, AnaghHegde commented
@abhvsn per your suggestion we would still be passing the default values to the method where we actually call the analytics service method. I am suggesting we would have a separate implementation just for the commit flow.

2022-05-19 04:23 UTC, abhvsn approved these changes

2022-05-19 15:12 UTC, merged