Added HA and PV
appsmithorg/appsmith pull request #13722
Opened 2022-05-10 11:02 UTC by sub1983

## Description
The main changes bought here are to implement a Horizontal POD Auto Scaler and the Persistent Volume.

-  Added hpa.yaml 
-   To enable autoscaling we have changed stateful set to deployment 
-  The Persistent volume has been added in the /appsmith-data path so now will be available on every pods
- the hpa uses metrics Server which needs to be setup
-  an efs-csi driver is used to setup the persistent  volume

### Setup metrics server run below 
`kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml '

###  To setup aws-efs-csi-driver

`helm repo add aws-efs-csi-driver https://kubernetes-sigs.github.io/aws-efs-csi-driver/
`

` helm upgrade --install aws-efs-csi-driver --namespace kube-system aws-efs-csi-driver/aws-efs-csi-driver -f efs/values.yaml `

Ref: [
](https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/charts/aws-efs-csi-driver/values.yaml)
 Add the IAM role under the annotations of values.yaml 

Detailed Steps for aws-efs-csi-driver can be found in the [link](https://docs.aws.amazon.com/eks/latest/userguide/efs-csi.html)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-05-10 11:02 UTC, sub1983 commented
@sharat87  Can you please review the PR and add your comments

2022-05-13 09:59 UTC, mohanarpit commented on deploy/helm/values.yaml
> +  APPSMITH_MONGODB_URI: "mongodb+srv://appsmith:appsmith@appsmith.yj62f.mongodb.net/newappsmith12"
Please don't commit credentials. This is now a security breach for us. :( 
I'd highly recommend that we destroy this MongoDB & Redis cluster **_immediately_**.

2022-05-13 10:05 UTC, mohanarpit commented on deploy/helm/templates/persistentVolume.yaml
> +    driver: efs.csi.aws.com
Based on the value of the driver here, will this Helm chart work on another cloud provider like Azure or on minikube?

2022-05-13 15:47 UTC, sub1983 commented on deploy/helm/values.yaml
> +  APPSMITH_MONGODB_URI: "mongodb+srv://appsmith:appsmith@appsmith.yj62f.mongodb.net/newappsmith12"
hey @mohanarpit  these are dummy values i created and is already destroyed after the testing and also these are not in our official account as well

2022-05-13 15:51 UTC, sub1983 commented on deploy/helm/templates/persistentVolume.yaml
> +    driver: efs.csi.aws.com
Nope, @mohanarpit  the Persistent Volume confs we have to create separately depending on the storage type  as this was tested in AWS and we use EFS as storage for AWS this conf will  only work with AWS. 
The generic solution will be difficult as store type of each cloud provider is different. We can create different conf for widely used cloud providers like azure, gcp ..etc..

2022-05-16 04:37 UTC, sharat87 commented on deploy/helm/values.yaml
> +  APPSMITH_MONGODB_URI: "mongodb+srv://appsmith:appsmith@appsmith.yj62f.mongodb.net/newappsmith12"
In such cases, please use dummy URIs, or non-URIs like `APPSMITH_MONGODB_URI: "valid-mongodb-uri-here"` or something of that sort.

2022-05-16 05:25 UTC, sharat87 requested changes
Lots of things here. Can you please take a look at the whole PR once and let me know for the next review please? Thanks

2022-05-16 05:25 UTC, sharat87 commented on deploy/helm/values.yaml
> -fullnameOverride: ""
We seem to be removing a lot of variables in the default `values.yaml` file. Can you confirm if there really are not used anywhere and are safe to remove? For example, I see we are removing `global.namespaceOverride`, but the `_helpers.tpl` is still using it.

Secondly, what happens on existing installations? Ones that have already defined these values in their `values.yaml` and are running with that? Will thier installations break? If yes, can we avoid that? If no, can we minimize the damage and document how they can resolve please?

2022-05-16 05:25 UTC, sharat87 commented on deploy/helm/values.yaml
> +useStatefulSet: false
If statefulset is disabled, then won't the git-storage data be lost on pod recreation, or when there's an update to Appsmith?

2022-05-16 05:25 UTC, sharat87 commented on deploy/helm/values.yaml
> +  tag: "release"
Please change this to `latest`, since this is the public Him charts. We want our self-hosted users to be on `latest`, unless they choose otherwise.

2022-05-16 05:25 UTC, sharat87 commented on deploy/helm/templates/ingress.yaml
> -  namespace: {{ include "appsmith.namespace" . }}
I see that we are _adding_ this in other resource files and _removing_ it here? Shouldn't we stay consistent? Or is this file an exception?

2022-05-16 05:25 UTC, sharat87 commented on deploy/helm/values.yaml
> +  create: true
I don't see anywhere that we are using this value. Should we remove it, if it's unused?

2022-05-16 05:25 UTC, sharat87 commented on deploy/helm/values.yaml
> +      - path: "/"
Can we remove this hard-coded hostname please?

2022-05-16 05:25 UTC, sharat87 commented on deploy/helm/values.yaml
> +  enabled: true
We seem to be changing the default here? Would this be a breaking change for our users? If yes, can we do something to avoid breaking changes please?

2022-05-16 05:25 UTC, sharat87 commented on deploy/helm/values.yaml
> -    # kubernetes.io/ingress.class: nginx
This config seems to be still used in the `ingress.yaml`, can we not remove it please?

2022-05-16 05:25 UTC, sharat87 commented on deploy/helm/values.yaml
> +  enabled: true
Please disable autoscaling by default.

2022-05-16 05:25 UTC, sharat87 commented on deploy/helm/values.yaml
> +  APPSMITH_REDIS_URL: "redis://subin-test-001.ihh5sj.0001.aps1.cache.amazonaws.com:6379"
Please use a dummy URL here as well.

2022-05-16 05:25 UTC, sharat87 commented on deploy/helm/templates/ingress.yaml
> -    {{- if not .Values.ingress.hosts }}
Can you elaborate why we are removing this by default for our new users?

2022-05-16 05:25 UTC, sharat87 commented on deploy/helm/templates/ingress.yaml
> -              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
I see these checks removed in a few places. Does this mean we won't be supporting some older versions of Kubernetes?

2022-08-02 12:25 UTC, closed without merging