fix: order async functions in settings tab alphabetically
appsmithorg/appsmith pull request #13731
Opened 2022-05-10 18:37 UTC by ohansFavour

## Description

This PR orders async functions alphabetically in the settings tab

Fixes #13732 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
**TestPlan**

- [ ] [[Test Case] : verify that multiple async functions can be added in JS object’s editor](https://github.com/appsmithorg/TestSmith/issues/1875) 
- [ ] [[Test Case] : Verify the order of async functions in Setting Tab of Js editor](https://github.com/appsmithorg/TestSmith/issues/1876)
- [ ] [[Test Case] : Verify that async functions can be execute](https://github.com/appsmithorg/TestSmith/issues/1877)

Cypress

- [x] Assert that number of async functions in settings tab corresponds to number of async function in js object
- [x] Assert that function settings remain in alphabetical order after running a function
- [x] Assert that function settings remain in alphabetical order after running multiple functions on pageload
- [x] https://github.com/appsmithorg/TestSmith/issues/1742
- [x] https://github.com/appsmithorg/TestSmith/issues/1743

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/order-async-settings-alphabetically 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 56.71 **(0)** | 38.65 **(-0.01)** | 36.22 **(0)** | 56.96 **(0)**
 :red_circle: | app/client/src/selectors/entitiesSelector.ts | 48.37 **(0)** | 11.3 **(-0.13)** | 23.95 **(0)** | 44.1 **(0)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.71 **(-0.23)** | 40.83 **(-0.84)** | 36.21 **(0)** | 56.74 **(-0.25)**</details>

2022-05-12 08:26 UTC, eco-monk submitted a review, later dismissed

2022-05-12 09:50 UTC, rimildeyjsr commented on app/client/src/selectors/entitiesSelector.ts
> +  return jsCollection?.config.actions
Do we need to provide a fallback here for when `jsCollection` is not defined? or returning undefined is enough?

2022-05-12 09:58 UTC, ohansFavour commented on app/client/src/selectors/entitiesSelector.ts
> +  return jsCollection?.config.actions
In line 797, we already have a fallback.   `jsCollection?.config.actions` is a conditional here.

2022-05-12 10:12 UTC, rimildeyjsr commented on app/client/src/selectors/entitiesSelector.ts
> +  return jsCollection?.config.actions
Cool, approving!

2022-05-12 10:13 UTC, rimildeyjsr approved these changes
LGTM

2022-05-17 20:13 UTC, Aishwarya-U-R requested changes
Can the locators please be moved to JSEditor.ts as they are JSEditor specific locators? And there is already '_settingsTab' locator in the file that can be reused here also.

2022-05-19 16:33 UTC, ohansFavour commented
/ok-to-test sha=20671c9

2022-05-19 17:36 UTC, Aishwarya-U-R requested changes
@ohansFavour - I see - in the test case - you are running only the last method once. But the issue can be seen only if more than one functions are invoked at a time. Hence please add scenarios for random methods with set OnPageLoad & Confirm before calling & then check if the order persists after running them on a page reload.

2022-05-23 20:49 UTC, ohansFavour commented
/ok-to-test sha=e65af73

2022-05-24 06:49 UTC, Aishwarya-U-R commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/JsFunctionExecution/JSFunctionExecution_spec.ts
> +    assertAsyncFunctionsOrder();
Can we repeat this section by enabling Confirmbefore run for different method combinations [eg, assert & zip], reload & confirm order once again?

2022-05-24 08:03 UTC, ohansFavour commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/JsFunctionExecution/JSFunctionExecution_spec.ts
> +    assertAsyncFunctionsOrder();
@Aishwarya-U-R Does confirming before running functions in any way affect the order of function settings?. This seems like a redundant assertion.

2022-05-25 04:56 UTC, ohansFavour commented
/ok-to-test sha=1ad65c3

2022-05-25 04:59 UTC, ohansFavour commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/JsFunctionExecution/JSFunctionExecution_spec.ts
> +    assertAsyncFunctionsOrder();
@Aishwarya-U-R , I misunderstood your initial comment. Yes, this makes sense. Now done :white_check_mark:

2022-05-26 19:54 UTC, ohansFavour commented
/ok-to-test sha=ffdeae4

2022-05-27 06:04 UTC, Rishabh-Rathod submitted a review, later dismissed
Approving according to the previous review done.

2022-05-27 06:17 UTC, Rishabh-Rathod commented
@ohansFavour  seems like we updated the cypress test. Does @Aishwarya-U-R  needs to re-review this?

2022-05-27 06:22 UTC, ohansFavour commented
> @ohansFavour seems like we updated the cypress test. Does @Aishwarya-U-R need to re-review this?

Without her endorsement, the `test plan approved` label won't be added.

2022-05-27 08:07 UTC, Aishwarya-U-R commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/JsFunctionExecution/JSFunctionExecution_spec.ts
> +    agHelper.GetNClick(jsEditor._settingsTab);
@ohansFavour - Hey sorry I missed to mention it clearly in my previous comment.. Can you please make a few methods - both true - OnpPageLoad + ConfirmBeforeRunning - then reload - handle the confirm popup's then navigate to settings tab & verify order..

I put a comment to handle the Confirm pop's after reload - but the  EnableDisableAsyncFuncSettings() method i gave wasn't complying to both setting to true.

So I expect ideally something like below:
jsEditor.EnableDisableAsyncFuncSettings("assert", **true**, true);
    jsEditor.EnableDisableAsyncFuncSettings("base", true, false);
    jsEditor.EnableDisableAsyncFuncSettings("zip", **true**, true);
    jsEditor.EnableDisableAsyncFuncSettings("getId", false, false);

2022-05-27 08:19 UTC, Aishwarya-U-R commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/JsFunctionExecution/JSFunctionExecution_spec.ts
> +    agHelper.GetNClick(jsEditor._settingsTab);
Also instead of cy.reload - please use agHelper.RefreshPage() which waits a bit before proceeding since we have seen failures with cy.load, coz of it having a flickering effect & this method gives it some time to settle.

2022-06-08 14:28 UTC, ohansFavour commented
/ok-to-test sha=c7ac284

2022-06-09 05:11 UTC, ohansFavour commented
/ok-to-test sha=0fa6175

2022-06-09 08:18 UTC, rimildeyjsr submitted a review, later dismissed

2022-06-12 20:23 UTC, ohansFavour commented
/ok-to-test sha=398986e

2022-06-13 08:10 UTC, Aishwarya-U-R commented
/ok-to-test sha=9905543

2022-06-13 09:11 UTC, Aishwarya-U-R commented
/ok-to-test sha=072925f

2022-06-13 10:20 UTC, Aishwarya-U-R submitted a review, later dismissed

2022-06-13 10:35 UTC, Aishwarya-U-R commented
/ok-to-test sha=e4ba1cc

2022-06-13 12:06 UTC, Aishwarya-U-R commented
/ok-to-test sha=9007090

2022-06-13 14:21 UTC, Aishwarya-U-R commented
/ok-to-test sha=aaaf413

2022-06-13 17:01 UTC, Aishwarya-U-R commented
/ok-to-test sha=aaaf413

2022-06-15 07:14 UTC, Aishwarya-U-R approved these changes

2022-06-15 07:16 UTC, merged