chore: prioritize parse errors in debugger callout
appsmithorg/appsmith pull request #13765
Opened 2022-05-11 20:55 UTC by ohansFavour

## Description 

Fixes #13764

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Cypress

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-05-11 20:56 UTC, ohansFavour commented
/ok-to-test sha=a441f1a

2022-05-16 05:07 UTC, Rishabh-Rathod commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/JsFunctionExecution/JSFunctionExecution_spec.ts
> +      .then((el: any) => {
nit: Will `el: HTMLElement` not work here? 
If we are not aware of the type in the worst case we could use `unknown` instead of `any`.

2022-05-16 06:20 UTC, ohansFavour commented
/ok-to-test sha=42d1147

2022-05-16 06:23 UTC, Rishabh-Rathod submitted a review, later dismissed
LGTM

2022-05-17 20:06 UTC, Aishwarya-U-R requested changes
@ohansFavour - Testcase 4, line 87 to 103 - can we please update the existing CreateJSObj method in JSEditor.ts to use the same method instead of hardcoded lines in the spec?

@Aishwarya-U-R this is done. I have also cleaned up the CreateJSObject util, it had too many function parameters(ideally, parameters should be 3 or less).

<img width="516" alt="Screenshot 2022-05-19 at 00 03 23" src="https://user-images.githubusercontent.com/46670083/169169405-2a4eea71-1a8b-4ad0-8f05-8bbb15129ca0.png">
<img width="761" alt="Screenshot 2022-05-19 at 00 02 55" src="https://user-images.githubusercontent.com/46670083/169169414-6d9acd5c-b1c7-4bca-82fd-b28e0a712680.png">

2022-05-18 22:28 UTC, ohansFavour commented
/ok-to-test sha=403fc1d

2022-05-19 08:08 UTC, Aishwarya-U-R submitted a review, later dismissed
CypressTests enhancements looks good!

2022-05-19 08:49 UTC, ohansFavour commented
/ok-to-test sha=92764ac

2022-05-19 08:58 UTC, ohansFavour commented
/ok-to-test sha=d880c96

2022-05-19 09:01 UTC, Aishwarya-U-R approved these changes
Approving cypress changes!

2022-05-19 10:57 UTC, merged