Fix: Outdated design for Queries/JS/API Editor
appsmithorg/appsmith pull request #13812
Opened 2022-05-13 04:53 UTC by ChandanBalajiBP

## Description

> Changed background color and fixed the padding along with margin in quick access tip
>Fixed selected and hover color in http method dropdown
>Proper alignment of slash icon in Input editor.

Fixes #13330

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-05-13 05:01 UTC, ChandanBalajiBP commented
/ok-to-test sha=3d753166

2022-05-13 08:59 UTC, Irongade submitted a review, later dismissed

2022-05-13 09:30 UTC, AmanAgarwal041 approved these changes

2022-05-30 09:40 UTC, yatinappsmith commented
Testplan link 
- [ ]  [1731 [TestCase] Design tests for REST api(Bugs) ](https://github.com/appsmithorg/TestSmith/issues/1731)

2022-05-30 10:01 UTC, ChandanBalajiBP commented
/ok-to-test sha=3d753166

2022-06-07 19:32 UTC, ChandanBalajiBP commented
/ok-to-test sha=a42d630

2022-06-09 17:32 UTC, ChandanBalajiBP commented
/ok-to-test sha=9373458

2022-06-24 05:29 UTC, ChandanBalajiBP commented
/ok-to-test sha=cbcc27e

2022-06-24 08:23 UTC, Irongade submitted a review, later dismissed

2022-06-30 07:41 UTC, btsgh commented
Tested for the changes mentioned in the issue - https://github.com/appsmithorg/appsmith/issues/13330
All the changes seem to have been incorporated.

2022-07-07 12:11 UTC, Aishwarya-U-R requested changes

2022-07-07 12:11 UTC, Aishwarya-U-R commented on app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/ApiTests/API_Styles_spec.js
> +  it("Quick access command background color", function() {
Give number to "it" functions - which will make the debugging easier incase of CI failures. ex: `it("1. Quick access command background color", function()`

2022-07-07 14:03 UTC, ChandanBalajiBP commented
/ok-to-test sha=77b698f

2022-07-08 10:53 UTC, Aishwarya-U-R approved these changes
Approving cypress tests!

2022-07-08 11:34 UTC, ChandanBalajiBP commented
/ok-to-test sha=2da1380

2022-07-08 14:31 UTC, merged