feat: 13412 - improve import app with progress bar
appsmithorg/appsmith pull request #13864
Opened 2022-05-16 10:17 UTC by haojin111

## Description

> Added status bar while importing application with json

Fixes #13412 

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

> Jest test
> cypress test

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-05-16 21:31 UTC, haojin111 commented
/ok-to-test sha=a3be249

2022-05-17 04:33 UTC, IAmAnubhavSaini requested changes
Remove coverage-summary.json from changeset.

2022-05-17 06:44 UTC, IAmAnubhavSaini commented
There are 0 files to review.

2022-05-17 06:58 UTC, haojin111 commented
/ok-to-test sha=27ebbfa

2022-05-18 00:39 UTC, IAmAnubhavSaini requested changes

2022-05-18 00:39 UTC, IAmAnubhavSaini commented on app/client/src/ce/constants/messages.test.ts
> +    { key: "UPLOADING_JSON", value: "Uploading JSON" },
Should be `Uploading JSON file`.

2022-05-18 00:39 UTC, IAmAnubhavSaini commented on app/client/src/ce/constants/messages.test.ts
> +      value: "Uploading Application",
Should be `Uploading application`.

2022-05-18 00:39 UTC, IAmAnubhavSaini commented on app/client/src/ce/constants/messages.test.ts
> +      value: "Import from Git Repository",
Should be `Import from git repository`.

2022-05-18 00:39 UTC, IAmAnubhavSaini commented on app/client/src/ce/constants/messages.test.ts
> +      key: "IMPORT_FROM_GIT_REPOSITORY_MESSAGE",
This key and value are not used anywhere. Remove it.

2022-05-18 00:39 UTC, IAmAnubhavSaini commented on app/client/src/ce/constants/messages.test.ts
> +        "While importing Appsmith will does not import the datasource credentials to prevent a breach. After a successfull import you can add the credentials manually so the application behaves norma
- Typo: use either will or does.
- Are credentials ever exported?

2022-05-18 00:39 UTC, IAmAnubhavSaini commented on app/client/src/pages/Applications/ImportApplicationModal.tsx
> +    background: ${Colors.GREY_4};
Use CSS color variables.

2022-05-18 00:39 UTC, IAmAnubhavSaini commented on app/client/src/pages/Applications/ImportApplicationModal.tsx
> +        // onClose && onClose();
This should be removed.

2022-05-18 00:39 UTC, IAmAnubhavSaini commented on app/client/src/pages/Applications/ImportApplicationModal.tsx
> +            <Icon fillColor={Colors.GREY_800} name="file-line" />
Use CSS color variables.

2022-05-18 00:39 UTC, IAmAnubhavSaini commented on app/client/src/pages/Applications/ImportApplicationModal.tsx
> +              {appFileToBeUploaded?.file.name || "filename.JSON"}
1. `appFileToBeUploaded?.file?.name`
2. `"filename.json"`

2022-05-18 04:08 UTC, haojin111 commented on app/client/src/ce/constants/messages.test.ts
> +    { key: "UPLOADING_JSON", value: "Uploading JSON" },
the text is fetched from figma design

2022-05-18 04:08 UTC, haojin111 commented on app/client/src/ce/constants/messages.test.ts
> +      value: "Uploading Application",
the text is fetched from figma design

2022-05-18 04:47 UTC, IAmAnubhavSaini commented on app/client/src/ce/constants/messages.test.ts
> +    { key: "UPLOADING_JSON", value: "Uploading JSON" },
@Debsourabh could you please update Figma design. I have left comments there too. https://www.figma.com/file/IOx0WPeZsChCaXwgVxU3LX/Import%2FExport-Design?node-id=1594%3A8197

2022-05-20 04:11 UTC, IAmAnubhavSaini approved these changes

2022-05-20 11:17 UTC, haojin111 commented
/ok-to-test sha=82dcfef

2022-05-23 09:57 UTC, haojin111 commented
/ok-to-test sha=7e5332c

2022-05-26 08:49 UTC, merged