fix: move git file operations to elastic schedulers
appsmithorg/appsmith pull request #13907
Opened 2022-05-17 15:00 UTC by AnaghHegde

## Description
>We would walk through the file tree and returns stream of file names. And we are also moving all file system related processing to bounded elastic threads.

Fixes #13824 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Locally

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-05-18 04:09 UTC, abhvsn requested changes

2022-05-18 04:09 UTC, abhvsn commented on app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/FileUtilsImpl.java
> +                        //return Mono.error(new IOException("Unable to delete directory for path {} with message {}"));
Do we want to continue even if the delete operation failed for some reason? Asking this because this may result in resource being deleted in DB but still present in file system. IMO we should throw the exception as earlier

2022-05-18 04:09 UTC, abhvsn commented on app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/FileUtilsImpl.java
> +                    processStop.stopAndLogTimeInMillis();
Please remove this as it will stop the stopwatch and will result in incorrect result, as the intention was to log complete time for the `saveApplicationToGitRepo`

2022-05-18 04:09 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java
> + * midwa`y producing corrupted states.
typo

2022-05-18 04:20 UTC, AnaghHegde commented on app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/FileUtilsImpl.java
> +                        Mono<List<Boolean>> pageList = Flux.fromStream(Files.walk(pageDirectory)
I don't see any reason on why we should create a local variable. It is not used in any other places, except the delete option.

2022-05-18 04:22 UTC, AnaghHegde commented on app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/FileUtilsImpl.java
> +                        //return Mono.error(new IOException("Unable to delete directory for path {} with message {}"));
There was no error thrown before. It was not at all present. I have added this to test few things.

2022-05-18 05:46 UTC, abhvsn commented on app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/FileUtilsImpl.java
> +                .subscribeOn(scheduler);
Hey, we have converted the blocking calls to reactive streams, is this still required?

2022-05-18 05:59 UTC, AnaghHegde commented on app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/FileUtilsImpl.java
> +                .subscribeOn(scheduler);
Not really. The save and read file operations are still blocking. Thats the reason why i wanted it to execute on a separate thread.

2022-05-18 08:35 UTC, abhvsn commented on app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/FileUtilsImpl.java
> +                        //return Mono.error(new IOException("Unable to delete directory for path {} with message {}"));
This may happen when we don't have permission to perform the file ops. If you think this will not happen then we can keep this in logs for now

2022-05-18 08:36 UTC, abhvsn commented on app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/FileUtilsImpl.java
> +                .subscribeOn(scheduler);
Should we convert these to async calls then

2022-05-19 04:33 UTC, AnaghHegde commented on app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/FileUtilsImpl.java
> +                .subscribeOn(scheduler);
I would prefer using the elastic schedule as it is used even for action execution and jgit apis.

2022-05-19 10:04 UTC, abhvsn submitted a review, later dismissed

2022-05-26 10:29 UTC, AnaghHegde commented
/ok-to-test sha=071ad92

2022-05-30 04:49 UTC, AnaghHegde commented
/ok-to-test sha=2cf5606

2022-06-02 07:30 UTC, AnaghHegde commented
/ok-to-test sha=fae76af

2022-06-02 10:24 UTC, AnaghHegde commented
/ok-to-test sha=fae76af

2022-06-02 13:59 UTC, AnaghHegde commented
/ok-to-test sha=951df4b

2022-06-03 05:33 UTC, AnaghHegde commented
/ok-to-test sha=7fffaf0

2022-06-03 10:24 UTC, vishnu-gp approved these changes

2022-06-03 10:24 UTC, merged

2022-06-09 08:09 UTC, AnaghHegde commented
@allcontributors add @AnaghHegde as a contributor for code, bug