fixes the flicker of widgets
appsmithorg/appsmith pull request #13917
Opened 2022-05-18 05:06 UTC by jsartisan

> Pull Request Template
When there are widgets on the canvas, on refresh the width of the widget flickers due to a bug in dynamic app layout logic. This PR fixes that

Fixes #12292

## Type of chang

- Bug fix

## How Has This Been Tested?

- Manually tested

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-05-18 10:15 UTC, yaldram requested changes

2022-05-18 10:15 UTC, yaldram commented on app/client/src/utils/hooks/useDynamicAppLayout.tsx
> +  return initialized;
we can return a clean up function `return () => { observer.disconnect() }`

2022-05-18 10:15 UTC, yaldram commented on app/client/src/utils/hooks/useDynamicAppLayout.tsx
> +
Also we can pass an empty dependency array to useEffect `[]`

2022-05-18 16:06 UTC, yaldram approved these changes

2022-05-19 05:05 UTC, jsartisan commented
/ok-to-test sha=8c75809

2022-05-19 10:06 UTC, jsartisan commented
/ok-to-test sha=c72b3bb

2022-05-20 06:54 UTC, keyurparalkar approved these changes
LGTM!

2022-05-25 04:51 UTC, jsartisan commented
@vivekverma2312 can someone from qa team pick this up to test?

2022-05-25 15:52 UTC, btsgh commented
Tested on vercel link and found to be fixed.

2022-05-26 04:52 UTC, merged