Feat/tenant
appsmithorg/appsmith pull request #13935
Opened 2022-05-18 10:30 UTC by trishaanand

2022-05-24 09:06 UTC, trishaanand commented
/ok-to-test sha=0893a69

2022-05-25 10:19 UTC, mohanarpit commented on app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog2.java
> +        defaultTenant.setDisplayName("Appsmith");
Can we rename this to "Default"? Makes it consistent with the slug name.

2022-05-25 10:19 UTC, mohanarpit commented on app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog2.java
> +        try(Stream<Workspace> stream = mongockTemplate.stream(workspaceQueryAll, Workspace.class)
Instead of iterating over each workspace, can we write a single MongoDB query to update all workspace entries (deleted or not) with the tenantId?

2022-05-25 10:19 UTC, mohanarpit commented on app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog2.java
> +        try(Stream<User> stream = mongockTemplate.stream(userQueryAll, User.class)
Instead of iterating over each user, can we write a single MongoDB query to update all user entries (deleted or not) with the tenantId?

2022-05-25 10:19 UTC, mohanarpit commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/TenantServiceCEImpl.java
> +                .onErrorResume(throwable -> {
This error statement can be removed because we seem to be calling the same function again. Unless we know what error is thrown and can handle those errors in particular fashion, we shouldn't call the same function twice hoping for different results.

2022-05-25 10:19 UTC, mohanarpit commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/TenantServiceCEImpl.java
> +            defaultTenantIdCacheMono = getDefaultTenantIdFromRepository();
This mono variable doesn't seem to be cached. Are we confident that each invocation to this function will not trigger a DB call?

2022-05-25 11:31 UTC, sidhantgoel commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/TenantServiceCEImpl.java
> +    private Mono<String> defaultTenantIdCacheMono = null;
Mono can't be cached, it is a single value publisher once published a Mono can not be reused, consider caching String instead or consider using CacheMono helper functions.

2022-05-25 12:08 UTC, sidhantgoel requested changes
Caching of default tenant id needs little work, everything else looks good to me.

2022-05-26 08:59 UTC, mohanarpit approved these changes

2022-05-26 09:02 UTC, trishaanand commented
/ok-to-test sha=4a4d28d

2022-05-27 10:42 UTC, trishaanand commented
/ok-to-test sha=32e3956

2022-05-27 12:59 UTC, merged