fix: added healthcheck for editor with https
appsmithorg/appsmith pull request #13947
Opened 2022-05-18 18:41 UTC by sum35h

## Description
Added a fix for the docker health check on editor with ssl enabled for `appsmith-ce` fat container and the slim client `appsmith-editor`

2022-05-19 07:26 UTC, pratapaprasanna submitted a review, later dismissed

2022-05-19 07:31 UTC, sharat87 commented on app/client/Dockerfile
> +HEALTHCHECK --interval=15s --timeout=15s --start-period=15s --retries=3 CMD curl -f http://localhost/ || curl -fk https://localhost/ || exit 1
Do we need to check for both http and https? The http URL will redirect to HTTPS when available right? So, just adding `-L` to the http curl command will address this I think?

2022-05-19 09:11 UTC, sum35h commented on app/client/Dockerfile
> +HEALTHCHECK --interval=15s --timeout=15s --start-period=15s --retries=3 CMD curl -f http://localhost/ || curl -fk https://localhost/ || exit 1
Yes, that looks good. Wasn't aware of that option.

2022-05-23 04:26 UTC, sharat87 requested changes

2022-05-23 04:26 UTC, sharat87 commented on deploy/docker/scripts/healthcheck.sh
> +        if [[ $(curl -s -w "%{http_code}\n" http://localhost/ -o /dev/null) -ne 200 ]]; then
Could we do the same thing here as well please? Using `-L`?

2022-05-23 10:42 UTC, sum35h commented on deploy/docker/scripts/healthcheck.sh
> +        if [[ $(curl -s -w "%{http_code}\n" http://localhost/ -o /dev/null) -ne 200 ]]; then
@sharat87 I checked it with -L here, but the status code still comes to be 301.

2022-05-23 11:11 UTC, sharat87 approved these changes

2022-05-23 11:53 UTC, pratapaprasanna approved these changes

2022-05-27 11:35 UTC, merged