Show template menu on click of datasource table
appsmithorg/appsmith pull request #1410
Opened 2020-10-27 05:00 UTC by akash-codemonk

Fixes #1364

2020-10-28 10:02 UTC, riodeuno requested changes

2020-10-28 10:02 UTC, riodeuno commented on app/client/src/pages/Editor/Explorer/Datasources/DatasourceStructure.tsx
> +      action={() => setActive(!active)}
This seems to negate the `onInteraction` above. For example, when we click on the table again, the popover closes but opens back again.
We can probably pass a `action={noop}` here.

2020-10-28 10:12 UTC, akash-codemonk commented on app/client/src/pages/Editor/Explorer/Datasources/DatasourceStructure.tsx
> +      action={() => setActive(!active)}
Hmm yeah that's correct. I can't use a `noop` because the popover must open(or close if it's already open) when I click on the table. I might have to probably check for some condition in the action callback.

2020-11-02 08:36 UTC, riodeuno approved these changes

2020-11-02 08:54 UTC, merged