fix: update error highlight border in RTE widget
appsmithorg/appsmith pull request #14112
Opened 2022-05-26 03:33 UTC by techbhavin

## Description

> In RTE Widget Remove Error Highlight from the label and apply only on RTE input.

Fixes #14019

## Type of change

- Bugfix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ]x I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-05-26 03:34 UTC, techbhavin commented
/ok-to-test sha=982c476

2022-05-26 06:19 UTC, Tooluloope requested changes

2022-05-26 06:19 UTC, Tooluloope commented on app/client/src/widgets/RichTextEditorWidget/component/index.tsx
> +  border: 1px solid ${(props) => (props.isValid ? "none" : Colors.DANGER_SOLID)};
Could you add a cypress test for this, so it doesn't reoccur

2022-05-28 13:54 UTC, techbhavin commented
/ok-to-test sha=464abcf

2022-05-30 03:56 UTC, techbhavin commented
/ok-to-test sha=464abcf

2022-05-30 08:03 UTC, techbhavin commented
/ok-to-test sha=e76b30c

2022-05-30 10:16 UTC, Tooluloope submitted a review, later dismissed

2022-05-31 04:26 UTC, shadabbuchh commented
This issue if fixed. The error (red) highlight now appears only on the input component of the RTE widget.
![Screenshot 2022-05-31 at 9.49.27 AM.png](https://images.zenhubusercontent.com/6278b12bad578328630ba2e7/f35d80a1-4459-4174-adda-284b31034436)![Screenshot 2022-05-31 at 9.50.14 AM.png](https://images.zenhubusercontent.com/6278b12bad578328630ba2e7/8d49f1d1-fa0d-4c5c-abb1-149250e6d8c8)

However @Tooluloope / @techbhavin I notice that the error highlight does not adjust with the changing `Border Radius`. Is that something that is expected?
![Screenshot 2022-05-31 at 9.56.07 AM.png](https://images.zenhubusercontent.com/6278b12bad578328630ba2e7/aa236ee6-b443-4e9f-9c03-0f3c948231ac)

2022-05-31 17:24 UTC, techbhavin commented
/ok-to-test sha=af374f6

2022-06-01 04:17 UTC, techbhavin commented
/ok-to-test sha=af374f6

2022-06-01 05:01 UTC, shadabbuchh commented
The issue is fixed. Moving it to `Done`.

2022-06-01 12:11 UTC, merged