fix: remove debounce from RTE component
appsmithorg/appsmith pull request #14126
Opened 2022-05-26 16:52 UTC by Rishabh-Rathod

## Description

Remove debounce from RTE component

Fixes #14045 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-05-30 06:45 UTC, Rishabh-Rathod commented on app/client/src/widgets/RichTextEditorWidget/component/index.tsx
> +      initialRender.current = false;
Added comment.

2022-05-30 06:49 UTC, Rishabh-Rathod commented
/ok-to-test sha=686d392

2022-05-30 07:45 UTC, keyurparalkar approved these changes
LGTM!

2022-05-30 21:20 UTC, Tooluloope requested changes
Some issues I noticed
https://user-images.githubusercontent.com/31691737/171059905-0f64b804-7ec5-4447-a8e2-f54c83c0e990.mov

2022-05-31 09:49 UTC, Rishabh-Rathod commented
> Some issues I noticed https://user-images.githubusercontent.com/31691737/171059905-0f64b804-7ec5-4447-a8e2-f54c83c0e990.mov

Thanks for reviewing it @Tooluloope. Seems like checking for `props.value` is not correct approach here.

2022-06-08 13:02 UTC, Rishabh-Rathod reviewed
Changes look good to me. Can we add a test for Rich Text Editor for the issues we faced? 

Suggestion: We could add RichTextEditor in `AllInputsWidgets_spec.js` to easily add a cypress test for it.

2022-06-20 19:37 UTC, Tooluloope requested changes

2022-06-20 19:37 UTC, Tooluloope commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/RichTextEditor_spec.js
> +    // cy.setTinyMceContent("rte-6h8j08u7ea", "abc");
Any reason why this was commented out.
If it's not needed we can remove it

2022-06-20 19:37 UTC, Tooluloope commented on app/client/src/widgets/RichTextEditorWidget/component/index.tsx
> +  isDirty: boolean;
Are you using this property in this component?

2022-06-21 05:00 UTC, techbhavin submitted a review, later dismissed

2022-06-21 06:09 UTC, keyurparalkar commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/RichTextEditor_spec.js
> +    // cy.setTinyMceContent("rte-6h8j08u7ea", "abc");
I have added a new way to update the text inside the RTE widget. Therefore, removing this comment.

2022-06-21 06:09 UTC, keyurparalkar commented on app/client/src/widgets/RichTextEditorWidget/component/index.tsx
> +  isDirty: boolean;
No, I have removed the `isDirty` and `defaultText` properties at the component level since they were not required

2022-06-21 06:10 UTC, keyurparalkar commented
/ok-to-test sha=83ff4b1

2022-06-21 06:54 UTC, Tooluloope approved these changes

2022-06-21 11:32 UTC, keyurparalkar commented
/ok-to-test sha=83ff4b1

2022-06-22 08:42 UTC, keyurparalkar commented
/ok-to-test sha=0246a10

2022-06-22 10:47 UTC, keyurparalkar commented
/ok-to-test sha=0246a10

2022-06-22 14:10 UTC, Tooluloope approved these changes

2022-06-23 05:27 UTC, keyurparalkar commented
/ok-to-test sha=0246a10

2022-06-23 06:19 UTC, Rishabh-Rathod reviewed
Changes won't be conflicting with https://github.com/appsmithorg/appsmith/pull/14468

2022-06-23 09:48 UTC, keyurparalkar commented
/ok-to-test sha=0246a10

2022-06-24 11:05 UTC, keyurparalkar commented
/ok-to-test sha=b8f2a49

2022-07-01 08:02 UTC, keyurparalkar commented
/ok-to-test sha=45323bf

2022-07-01 10:16 UTC, shadabbuchh commented
Validated https://github.com/appsmithorg/appsmith/issues/14922 and moved it to `Done`.

2022-07-01 10:42 UTC, keyurparalkar commented
/ok-to-test sha=53d49b0

2022-07-01 10:57 UTC, vivekverma2312 commented
@keyurparalkar Tested the RTE widget and looks good.

2022-07-02 05:10 UTC, keyurparalkar commented
/ok-to-test sha=b75731e

2022-07-03 01:44 UTC, keyurparalkar commented
/ok-to-test sha=b75731e

2022-07-03 14:30 UTC, keyurparalkar commented
/ok-to-test sha=39b0bb4

2022-07-04 03:01 UTC, merged