feat: make AmazonS3 plugin error messages more readable. #8554
appsmithorg/appsmith pull request #14121
Opened 2022-05-26 11:36 UTC by somnathdasadhikari

## Description

- Make AmazonS3 plugin's error more readable

Fixes #8554 

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Manual
- JUnit TC

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-05-27 10:03 UTC, sumitsum commented on app/server/appsmith-plugins/amazons3Plugin/src/main/java/com/external/utils/AmazonS3ErrorUtils.java
> +            synchronized (AmazonS3ErrorUtils.class) {
Great to see that you have used the synchronized block here. Awesome work !

2022-05-27 10:05 UTC, sumitsum commented on app/server/appsmith-plugins/amazons3Plugin/src/main/java/com/external/utils/AmazonS3ErrorUtils.java
> +                return error.getMessage();
Can you please surround it line inside curly braces - just for the sake of maintaining parity since we follow the same style elsewhere in the code as well ?

2022-05-27 10:05 UTC, sumitsum commented on app/server/appsmith-plugins/amazons3Plugin/src/main/java/com/external/utils/AmazonS3ErrorUtils.java
> +            externalError = error;
Same as above. Please check for this across the PR.

2022-06-02 05:02 UTC, somnathdasadhikari commented on app/server/appsmith-plugins/amazons3Plugin/src/main/java/com/external/utils/AmazonS3ErrorUtils.java
> +                return error.getMessage();
added curly braces

2022-06-02 05:02 UTC, somnathdasadhikari commented on app/server/appsmith-plugins/amazons3Plugin/src/main/java/com/external/utils/AmazonS3ErrorUtils.java
> +            externalError = error;
added curly braces

2022-06-03 07:10 UTC, sumitsum requested changes

2022-06-03 07:10 UTC, sumitsum commented on app/server/appsmith-plugins/amazons3Plugin/src/test/java/com/external/utils/AmazonS3ErrorUtilsTest.java
> +        assertNotNull(message);
Please also add a check for what the final readable error should match.

2022-06-03 07:10 UTC, sumitsum commented on app/server/appsmith-plugins/amazons3Plugin/src/test/java/com/external/utils/AmazonS3ErrorUtilsTest.java
> +        assertNotNull(message);
Please also add a check for what the final readable error should match.

2022-06-03 07:10 UTC, sumitsum commented on app/server/appsmith-plugins/amazons3Plugin/src/test/java/com/external/plugins/AmazonS3PluginTest.java
> +
Please add a test case for `AmazonS3Exception` as well.

2022-06-03 07:38 UTC, sumitsum requested changes

2022-06-03 07:38 UTC, sumitsum commented on app/server/appsmith-plugins/amazons3Plugin/src/main/java/com/external/plugins/AmazonS3Plugin.java
> +        static {
QQ: why do we need to use static block here ?

2022-06-03 07:38 UTC, sumitsum commented on app/server/appsmith-plugins/amazons3Plugin/src/main/java/com/external/plugins/AmazonS3Plugin.java
> +                        //result.setErrorInfo(e);
Minor: please remove the commented out line.

2022-06-03 07:38 UTC, sumitsum commented on app/server/appsmith-plugins/amazons3Plugin/src/main/java/com/external/plugins/AmazonS3Plugin.java
> +                    //.onErrorResume(error -> Mono.just(new DatasourceTestResult(error.getMessage())))
Minor: please remove the commented out line.

2022-06-03 07:38 UTC, sumitsum commented on app/server/appsmith-plugins/amazons3Plugin/src/main/java/com/external/plugins/AmazonS3Plugin.java
> +                        else if (e instanceof AmazonServiceException) {
Instead of using a `else if` block here can we update the `if` conditon above like : `if( e instance of xyz | abc)` ?

2022-06-06 13:53 UTC, somnathdasadhikari commented on app/server/appsmith-plugins/amazons3Plugin/src/main/java/com/external/utils/AmazonS3ErrorUtils.java
> +    public static AmazonS3ErrorUtils getInstance() throws InstantiationException {
The InstantiationException is a runtime exception in Java that occurs when an application attempts to create an instance of a class using the Class.newInstance() method, but the specified class object cannot be instantiated.

2022-06-06 14:04 UTC, somnathdasadhikari commented on app/server/appsmith-plugins/amazons3Plugin/src/main/java/com/external/plugins/AmazonS3Plugin.java
>                              return Mono.error(new AppsmithPluginException(AppsmithPluginError.PLUGIN_ERROR, e.getMessage()));
This was developed earlier and I don't have idea about scenario for `AmazonS3Exception`, Should I modify this?

2022-06-06 14:26 UTC, somnathdasadhikari commented on app/server/appsmith-plugins/amazons3Plugin/src/main/java/com/external/plugins/AmazonS3Plugin.java
> +                        else if (e instanceof AmazonServiceException) {
Handling `AmazonS3Exception` was implemented earlier. I have added `AmazonServiceException` section. Moreover the constructor of `AppsmithPluginException` I have used is different from the constructor `AmazonS3Exception`

2022-06-06 14:38 UTC, somnathdasadhikari commented on app/server/appsmith-plugins/amazons3Plugin/src/main/java/com/external/utils/AmazonS3ErrorUtils.java
> +            /**
modified accordingly

2022-06-06 14:39 UTC, somnathdasadhikari commented on app/server/appsmith-plugins/amazons3Plugin/src/main/java/com/external/utils/AmazonS3ErrorUtils.java
> +            return amazonServiceException.getErrorMessage().split("\\(")[0].trim();
modified accordingly

2022-06-06 14:39 UTC, somnathdasadhikari commented on app/server/appsmith-plugins/amazons3Plugin/src/main/java/com/external/utils/AmazonS3ErrorUtils.java
> +        return error.getMessage().split("\\.")[0].trim() + ".";
modified accordingly

2022-06-06 14:40 UTC, somnathdasadhikari commented on app/server/appsmith-plugins/amazons3Plugin/src/main/java/com/external/utils/AmazonS3ErrorUtils.java
> +
modified accordingly

2022-06-06 14:42 UTC, somnathdasadhikari commented on app/server/appsmith-plugins/amazons3Plugin/src/main/java/com/external/utils/AmazonS3ErrorUtils.java
> +        if (amazonS3ErrorUtils != null)
modified accordingly

2022-06-06 14:44 UTC, somnathdasadhikari commented on app/server/appsmith-plugins/amazons3Plugin/src/main/java/com/external/plugins/AmazonS3Plugin.java
> +                        //result.setErrorInfo(e);
modified accordingly

2022-06-08 08:15 UTC, sumitsum requested changes

2022-06-08 08:15 UTC, sumitsum commented on app/server/appsmith-plugins/amazons3Plugin/src/test/java/com/external/utils/AmazonS3ErrorUtilsTest.java
> +        String expectedMessage = "null";
@somnathdasadhikari we need to handle this error separately. Since here the readable part is not good i.e. `null` does not inform the user about anything useful - we need to handle it separtely and return the exact info.

2022-08-15 10:03 UTC, closed without merging