Feat: Perform file ops only when the resource is updated
appsmithorg/appsmith pull request #14184
Opened 2022-05-30 14:38 UTC by vishnu-gp

## Description

This PR optimises git related file operations. With this, the resources like Pages, JsonObjects and Queries are only updated in the file system only if there is a change in the same available on Database.

Fixes #13893 #13825

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Manually via the local app

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-05-31 05:29 UTC, abhvsn requested changes

2022-05-31 05:29 UTC, abhvsn commented on app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/FileUtilsImpl.java
> +                    .filter(path -> Files.isDirectory(path) && !path.equals(resourceDirectory) && !validResources.contains(path.getFileName().toString()))
Can we please get rid of contains as this may create issues when 1 of the resources is the substring of other?
e.g. page1 and page11

2022-05-31 05:29 UTC, abhvsn commented on app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/FileUtilsImpl.java
> +                    .forEach(this::deleteDirectory);
Not sure if I got this correctly but are we clearing the complete directory instead of single file. Consider we delete the `action1` from `page1`, so `resourceDirectory = {basePath}/page1/actions` what will happen if we have few more actions action2, action3 still attached to the page1?

2022-05-31 05:29 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/GitFileUtils.java
> +                    }
Not able to understand the implementation here, can you please elaborate?

2022-05-31 05:29 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
> +                    Instant applicationLastCommittedAt = application.getGitApplicationMetadata().getLastCommittedAt();
This may end up in NPE when application is not connected to git

2022-05-31 05:29 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
> +                                    }
Should we create another field `Set<String> updatedResource` to list all the updated resources since last commit and pass this to `saveFile` method to avoid the dependency on updatedAt field. Asking this because we are not committing the updatedAt field and devs can make the mistake of removing this field during the export flow

2022-05-31 07:39 UTC, vishnu-gp commented on app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/FileUtilsImpl.java
> +                    .forEach(this::deleteDirectory);
@abhvsn The idea of this method is to delete non-existing directory objects. Basically deletes directories inside the resourceDirectory which are not in the validResource list. The only use case we have now is deleting the page directory if the page is deleted. In that case, resourceDirectory would be {basePath}/pages

2022-05-31 07:42 UTC, vishnu-gp commented on app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/GitFileUtils.java
> +                    }
@abhvsn At this point, if the page resource has a non-null updatedAt field means it has updates after the last commit. The logic for this can be found in ImportExportApplicationService.

2022-05-31 07:58 UTC, vishnu-gp commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
> +                                    }
@abhvsn We can have a different boolean field to avoid dependency on updatedAt but then removing that field from being committed can be the same problem. A list also works, the current `Map<String, Map<String, Boolean>> updatedResources;` is a map of all the updated resources only which would take care of only invoking saveFile() for updated resources only.

2022-05-31 11:15 UTC, abhvsn commented on app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/FileUtilsImpl.java
> +                    .forEach(this::deleteDirectory);
Does this mean we are not deleting the files selectively? If yes then can we please modify the implementation accordingly?

2022-05-31 11:19 UTC, vishnu-gp commented on app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/FileUtilsImpl.java
> +                    .filter(path -> Files.isDirectory(path) && !path.equals(resourceDirectory) && !validResources.contains(path.getFileName().toString()))
@abhvsn This checks and matches the exact directory name in the Set and I don't think the substring issue will happen here.

2022-06-01 11:16 UTC, abhvsn commented on app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/FileUtilsImpl.java
> +                    .forEach(this::deleteDirectory);
This looks sorted as we are using this to remove the page directory when the page is removed from the application.

2022-06-02 15:41 UTC, vishnu-gp commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
> +                                    }
@abhvsn The latest commit would solve the dependency on updatedAt and addresses the other issues mentioned here.

2022-06-06 14:18 UTC, abhvsn commented on app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/FileUtilsImpl.java
> +                            Boolean isResourceUpdated = updatedResources.get(ACTION_LIST).contains(names[0])  ;
What happens when we have multiple actions with the same name on different pages?

2022-06-06 14:31 UTC, abhvsn commented on app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/FileUtilsImpl.java
> +                            Boolean isResourceUpdated = updatedResources.get(ACTION_COLLECTION_LIST).contains(actionCollectionName);
Same as above.

2022-06-06 14:33 UTC, abhvsn commented on app/server/appsmith-git/src/test/java/com/appsmith/git/helpers/FileUtilsImplTest.java
> +        Path pageDirectoryPath = Path.of(pageDirectory);
Can we please use the Path to create the directory path to be consistent?

2022-06-06 14:36 UTC, abhvsn commented on app/server/appsmith-git/src/test/java/com/appsmith/git/helpers/FileUtilsImplTest.java
> +    }
Let's include the testcase for `scanAndDeleteFileForDeletedResources` as well

2022-06-07 15:32 UTC, vishnu-gp commented on app/server/appsmith-git/src/test/java/com/appsmith/git/helpers/FileUtilsImplTest.java
> +    }
@abhvsn Done

2022-06-07 15:33 UTC, vishnu-gp commented on app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/FileUtilsImpl.java
> +                            Boolean isResourceUpdated = updatedResources.get(ACTION_COLLECTION_LIST).contains(actionCollectionName);
@abhvsn corrected

2022-06-08 05:05 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/constants/FieldName.java
> +    public static final String NAME_SEPARATOR = "##ENTITY_SEPARATOR##";
Please use the `com/appsmith/external/constants/GitConstants.java` so as to avoid keeping the same copy in multiple places.

2022-06-08 05:18 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
> +                                    String actionCollectionName = unpublishedActionCollectionDTO != null ? unpublishedActionCollectionDTO.getName() + NAME_SEPARATOR + unpublishedActionCollectionDTO.g
It will be great if we can make this more readable 🙂

2022-06-08 05:19 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
> +                                    String newActionName = unpublishedActionDTO != null ? unpublishedActionDTO.getValidName() + NAME_SEPARATOR + unpublishedActionDTO.getPageId() : publishedActionDTO
Same here

2022-06-08 05:19 UTC, abhvsn commented
LGTM some minor nits.
@vishnu-gp can you also resolve the merge conflicts.

2022-06-09 13:10 UTC, vishnu-gp commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
> +                                    String actionCollectionName = unpublishedActionCollectionDTO != null ? unpublishedActionCollectionDTO.getName() + NAME_SEPARATOR + unpublishedActionCollectionDTO.g
@abhvsn Done

2022-06-09 13:10 UTC, vishnu-gp commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
> +                                    String newActionName = unpublishedActionDTO != null ? unpublishedActionDTO.getValidName() + NAME_SEPARATOR + unpublishedActionDTO.getPageId() : publishedActionDTO
@abhvsn Done

2022-06-10 04:09 UTC, abhvsn approved these changes

2022-06-10 04:30 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/domains/ApplicationJson.java
> +    Map<String, Set<String>> updatedResources;
@vishnu-gp as this should not be included in the exported file let's JsonIgnore this field.

2022-06-14 04:59 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
> +                    boolean isServerSchemaMigrated = application.getServerSchemaVersion() != JsonSchemaVersions.serverVersion;
Just to be consistent with rest of the implementation can we change this to 
`!JsonSchemaVersions.serverVersion.equals(application.getServerSchemaVersion());`

2022-06-14 05:29 UTC, vishnu-gp commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
> +                    boolean isServerSchemaMigrated = application.getServerSchemaVersion() != JsonSchemaVersions.serverVersion;
@abhvsn Done

2022-06-14 05:29 UTC, vishnu-gp commented on app/server/appsmith-server/src/main/java/com/appsmith/server/domains/ApplicationJson.java
> +    Map<String, Set<String>> updatedResources;
@abhvsn Done

2022-06-14 05:30 UTC, vishnu-gp commented
/ok-to-test sha=83b7770

2022-06-14 05:44 UTC, abhvsn approved these changes

2022-06-17 09:18 UTC, vishnu-gp commented
/ok-to-test sha=214b4c1

2022-06-17 09:51 UTC, vishnu-gp commented
/ok-to-test sha=aaa3aa8

2022-06-20 05:21 UTC, vishnu-gp commented
/ok-to-test sha=1fbf31e

2022-06-22 05:23 UTC, merged