Fixed a few other flows
appsmithorg/appsmith pull request #14225
Opened 2022-06-01 09:27 UTC by nidhi-nair

- Fixed generate CRUD flow
- Fixed migration when spreadsheet url and sheet name have bindings
- Fixed projection selection getting used for updates and inserts
- Fixed defaulting to component data for all migrated form fields

2022-06-02 04:55 UTC, abhvsn approved these changes
LGTM

2022-06-03 06:03 UTC, sumitsum requested changes

2022-06-03 06:07 UTC, sumitsum commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/plugins/CrudTemplateService.java
> +    default void updateCrudTemplateFormData(Map<String, Object> formData,
Can you please mention in the comments why this was required ? Maybe add an example of how this method will get used ?

2022-06-03 06:21 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog2.java
>              formDataMap.put(key, map);
Yes, we're meant to call this function only to convert the leaf node into the js or form mode structure.

2022-06-03 06:30 UTC, sumitsum approved these changes

2022-06-03 06:33 UTC, merged