fix: fix postgres multiple idle connections
appsmithorg/appsmith pull request #14348
Opened 2022-06-07 11:03 UTC by sumitsum

## Description
- Currently when a datasource does not exist and multiple actions connected to the same datasource are run simultaneously then they all try to create a new connection object resulting in multiple connections being created to the datasource. 
- This PR attempts to solve the race condition problem defined above in the following way:  
  - enclose the datasource context creating logic within a critical section. 
  - the critical section above is synchronized based on datasource id. Hence, if two threads want to create a datasource on different datasource ids then they would not be blocked. 

Fixes #14117 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- JUnit TC
- Manual

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-06-07 13:08 UTC, sumitsum commented
/ok-to-test sha=81a8a09

2022-06-15 11:37 UTC, nidhi-nair approved these changes

2022-06-15 11:45 UTC, sumitsum commented
/ok-to-test sha=81a8a09

2022-06-20 10:08 UTC, sumitsum commented
As discussed with @prapullac, It is not possible to add cypress test for this.

2022-07-18 09:21 UTC, nidhi-nair approved these changes
LGTM

2022-07-18 09:38 UTC, sumitsum commented
/ok-to-test sha=19e4754

2022-07-18 09:58 UTC, Aishwarya-U-R requested changes

2022-07-18 09:58 UTC, Aishwarya-U-R commented on app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/OnLoadTests/CheckPostgresConnOnPageLoad_spec.ts
> +  });
Can we add case for clean up - Deleting both datasources & dropping user too!

2022-07-19 09:59 UTC, sumitsum commented on app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/OnLoadTests/CheckPostgresConnOnPageLoad_spec.ts
> +      dataSources.NavigateFromActiveDS(dsName, true);
As discussed, due to issue with cypress helper methods unfurling the datasource tab, we can't push the test case as it is right now. Hence, adding it to commented out section.

2022-07-19 09:59 UTC, sumitsum commented on app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/OnLoadTests/CheckPostgresConnOnPageLoad_spec.ts
> +      agHelper.RenameWithInPane("Postgres " + guid, false);
As discussed, due to issue with cypress helper methods unfurling the datasource tab, we can't push the test case as it is right now. Hence, adding it to commented out section.

2022-07-19 09:59 UTC, sumitsum commented on app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/OnLoadTests/CheckPostgresConnOnPageLoad_spec.ts
> +  });
As discussed, due to issue with cypress helper methods unfurling the datasource tab, we can't push the test case as it is right now. Hence, adding it to commented out section.

2022-07-19 10:02 UTC, sumitsum commented
/ok-to-test sha=a08a3dc

2022-07-19 10:04 UTC, Aishwarya-U-R approved these changes
Approving cypress - analysis stage!

2022-07-19 10:25 UTC, sumitsum commented on app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/OnLoadTests/CheckPostgresConnOnPageLoad_spec.ts
> +  it("6. Run query to check number of open connections to Postgres db", () => {
As discussed, due to issue with cypress helper methods unfurling the datasource tab, we can't push the test case as it is right now. Hence, adding it to commented out section.

2022-07-19 10:42 UTC, nidhi-nair approved these changes

2022-07-20 07:45 UTC, sumitsum commented
/ok-to-test sha=d82413f

2022-07-20 18:01 UTC, merged