chore: Update get ssh key api response
appsmithorg/appsmith pull request #14340
Opened 2022-06-07 08:05 UTC by AnaghHegde

## Description

> When the ssh key is not empty for an app instead of throwing the error state we should send other datapoints like supported key types, reference doc url as there are still need by FE

Fixes #14339 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Locally
- Junit tests

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-06-07 08:09 UTC, AnaghHegde commented
/ok-to-test sha=8cba19d

2022-06-07 08:23 UTC, abhvsn requested changes
Minor comments rest LGTM

2022-06-07 08:23 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java
> +                                }
1. How can we end up in this scenario?
2. Also this seems like a SSH key config error can we please replace this with INVALID_GIT_SSH_CONFIGURATION in that case?

2022-06-07 08:23 UTC, abhvsn commented on app/server/appsmith-server/src/test/java/com/appsmith/server/services/ApplicationServiceTest.java
> +                    assertThat(gitAuthDTO.getPublicKey()).isNull();
If I understood correctly, this should be empty and not null.

2022-06-07 08:23 UTC, abhvsn commented on app/server/appsmith-server/src/test/java/com/appsmith/server/services/GitServiceTest.java
> +        Application application = createApplicationConnectedToGit("deleteBranch_defaultBranchUpdated_Successw", "master");
Please revert this change.

2022-06-07 08:32 UTC, IAmAnubhavSaini commented on app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/ApplicationControllerCE.java
> +                .map(created -> new ResponseDTO<>(HttpStatus.OK.value(), created, null));
👍

2022-06-07 08:34 UTC, IAmAnubhavSaini reviewed
There's a typo as Abhijeet mentioned, rest looks ok to me.

2022-06-07 10:07 UTC, AnaghHegde commented on app/server/appsmith-server/src/test/java/com/appsmith/server/services/GitServiceTest.java
> +        Application application = createApplicationConnectedToGit("deleteBranch_defaultBranchUpdated_Successw", "master");
This is on purpose because of the duplicate key error in test class.

2022-06-07 10:31 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java
> +                                }
I have added this check because the same was present in getSShKey of `ApplicationServiceClass` and now we do not throw the error for the same case

2022-06-07 10:31 UTC, AnaghHegde commented
/ok-to-test sha=f8126fc

2022-06-08 04:57 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java
> +                                }
I am still of the opinion we will not end up in this error state because we are making changes in `CreateBranch` flow, but there is no harm I suppose. Can we use the standard SSH key error response as this is specifically related to SSH keys?

2022-06-08 09:28 UTC, AnaghHegde commented
/ok-to-test sha=5d6d3f4

2022-06-09 05:40 UTC, abhvsn approved these changes

2022-06-09 05:49 UTC, AnaghHegde commented
/ok-to-test sha=0106aad

2022-06-09 05:51 UTC, abhvsn submitted a review, later dismissed

2022-06-10 02:58 UTC, AnaghHegde commented
@IAmAnubhavSaini Can you try this in local env? Because the cypress tests are failing for the same reason i have mentioned above. Key gen step is failing in cypress tests.

2022-06-16 06:05 UTC, AnaghHegde commented
/ok-to-test sha=3fa6bb0

2022-06-16 06:23 UTC, abhvsn approved these changes

2022-06-16 17:06 UTC, AnaghHegde commented
/ok-to-test sha=e3f089b

2022-06-17 04:44 UTC, AnaghHegde commented
/ok-to-test sha=5f31499

2022-06-17 04:48 UTC, abhvsn approved these changes

2022-06-17 05:37 UTC, AnaghHegde commented
/ok-to-test sha=79bde8a

2022-06-21 04:53 UTC, abhvsn approved these changes

2022-06-21 13:27 UTC, IAmAnubhavSaini commented
This is causing a frontend issue after implementation. API is returning an empty string, front end is dependent upon error when ssh-keypair is not generated; so for the time being front-end is going to save the protocols and the learn more link above ssh-key input.

Closing for now.

2022-06-21 13:27 UTC, closed without merging