fix: Moved datatree diff from main thread to worker
appsmithorg/appsmith pull request #14344
Opened 2022-06-07 09:31 UTC by ayushpahwa

## Description

We are calculating the diff in the data tree on the main thread in `EvaluationSagas`. This PR changes this functionality and moves it to the worker thread. This saves us around 10-25 ms on the main thread, variable based on the data tree size.

Fixes #7461 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-06-07 16:46 UTC, ayushpahwa commented
/ok-to-test sha=d4a3305

2022-06-08 11:42 UTC, SatishGandham requested changes

2022-06-08 11:42 UTC, SatishGandham commented on app/client/src/workers/evaluation.worker.ts
>            errors,
If you check the code above, dataTree is never empty. This condition in treeReducer is always true.
```
if (Object.keys(dataTree).length) {
      return dataTree;
    }
```
This will make the edit and view mode very slow.

2022-06-08 11:43 UTC, ayushpahwa commented on app/client/src/workers/evaluation.worker.ts
>            errors,
Okay, looking into it.

2022-07-07 13:14 UTC, Rishabh-Rathod commented on app/client/src/workers/DataTreeEvaluator/DataTreeEvaluator.ts
> +    const oldEvalTree = _.cloneDeep(this.evalTree);
Can we please use `klona` to clone the dataTree.

2022-07-08 11:34 UTC, ayushpahwa commented on app/client/src/workers/DataTreeEvaluator/DataTreeEvaluator.ts
> +    const oldEvalTree = _.cloneDeep(this.evalTree);
Done, please check

2022-07-08 11:45 UTC, ayushpahwa commented on app/client/src/reducers/evaluationReducers/treeReducer.ts
> +    }
Done, please see

2022-07-08 11:55 UTC, Rishabh-Rathod reviewed
Could you check below comments

2022-07-08 11:55 UTC, Rishabh-Rathod commented on app/client/src/workers/DataTreeEvaluator/index.ts
> +    const evaluationChanges = diff(oldEvalTree, newEvalTree);
how do we make sure `updates` happened while `EVAL_TRIGGER` are persisted to be sent in next `EVAL_TREE`? 
As we also run `updateDataTree` in `EVAL_TRIGGER`.

If losing them is not a problem then instead of finding `updates` in `updateDataTree` can we do it in evaluation.worker for `EVAL_TREE`.

2022-07-08 11:55 UTC, Rishabh-Rathod commented on app/client/src/sagas/EvaluationsSaga.ts
> +  // const updates = diff(oldDataTree, dataTree) || [];
nit: We could remove commented code if not needed.

2022-07-08 12:01 UTC, Rishabh-Rathod commented on app/client/src/workers/DataTreeEvaluator/index.ts
> +    const evaluationChanges = diff(oldEvalTree, newEvalTree);
Maybe easy way to solve this could be to maintain a separate `oldDataTree` value in `evaluation.worker` file which stores dataTree used for last `updates` calculation and then keep updating it per evaluations.

We could also skip diff calculation for 1st evaluation.

2022-07-11 07:26 UTC, SatishGandham requested changes

2022-07-11 07:26 UTC, SatishGandham commented on app/client/src/reducers/evaluationReducers/treeReducer.ts
> +      if (Object.keys(dataTree).length) {
Isn't this if condition redundant?

2022-07-11 07:26 UTC, SatishGandham commented on app/client/src/workers/DataTreeEvaluator/index.ts
> +    const oldEvalTree = klona(this.evalTree);
I don't think we need a deep clone here.
It's not getting changed anywhere.
@Rishabh-Rathod , Please  verify.

2022-07-15 07:59 UTC, SatishGandham reviewed
LGTM. I will let @Rishabh-Rathod give the approval.

2022-07-15 10:46 UTC, ayushpahwa commented on app/client/src/reducers/evaluationReducers/treeReducer.ts
> +      if (Object.keys(dataTree).length) {
This is done

2022-07-15 10:47 UTC, ayushpahwa commented on app/client/src/sagas/EvaluationsSaga.ts
> +  // const updates = diff(oldDataTree, dataTree) || [];
This is done

2022-07-15 10:47 UTC, ayushpahwa commented on app/client/src/workers/DataTreeEvaluator/index.ts
> +    const evaluationChanges = diff(oldEvalTree, newEvalTree);
Working on this one.

2022-07-18 05:52 UTC, somangshu commented
@ayushpahwa please close this soon after getting any review you need!

2022-07-18 05:57 UTC, Rishabh-Rathod requested changes
As review was requested, just making a `request changes` review with expected change.

2022-07-18 05:57 UTC, Rishabh-Rathod commented on app/client/src/workers/DataTreeEvaluator/index.ts
> +    const evaluationChanges = diff(oldEvalTree, newEvalTree);
waiting for the changes discussed here to re-review.

2023-09-08 05:02 UTC, closed without merging