fix: [WIP] reset meta to default value
appsmithorg/appsmith pull request #14468
Opened 2022-06-10 23:18 UTC by Rishabh-Rathod

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.

## Description

> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change.

Fixes # (issue)

> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-06-10 23:30 UTC, Rishabh-Rathod reviewed
Next steps

2022-06-10 23:30 UTC, Rishabh-Rathod commented on app/client/src/reducers/entityReducers/metaReducer/index.ts
> +
- Fix typescript errors and make this code properly typed.
- Also, add a test to reset.

2022-06-10 23:30 UTC, Rishabh-Rathod commented on app/client/src/sagas/WidgetOperationUtils.ts
> +        );
Child reset is not yet supported. Figure out how to widget `childWidget` from evaluatedTree.

2022-06-11 08:12 UTC, Rishabh-Rathod commented on app/client/src/sagas/WidgetOperationUtils.ts
> +        );
Fixed

2022-06-11 08:13 UTC, Rishabh-Rathod commented on app/client/src/reducers/entityReducers/metaReducer/index.ts
> +
done

2022-06-11 08:20 UTC, Rishabh-Rathod commented on app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx
> +      // filterText: "",
https://github.com/appsmithorg/appsmith/pull/10359/files#r894994806

@Tooluloope  Can you check the above comment and review this line of code change.

2022-06-11 11:43 UTC, Rishabh-Rathod reviewed
NEXT STEPS: 
- [x] Add a new cypress test for resetWidget
   - multiselect 

2. Run CI test and verify all tests working fine.

2022-06-11 11:44 UTC, Rishabh-Rathod commented
/ok-to-test sha=776a473

2022-06-13 16:11 UTC, Rishabh-Rathod commented
/ok-to-test sha=0cdf871

2022-06-14 18:10 UTC, Rishabh-Rathod commented
/ok-to-test sha=3185560

2022-06-15 04:56 UTC, Rishabh-Rathod reviewed
Add comments

2022-06-15 04:56 UTC, Rishabh-Rathod commented on app/client/src/reducers/entityReducers/metaReducer/index.ts
> +    }
Please add comment to explain what is happening here.

2022-06-15 04:56 UTC, Rishabh-Rathod commented on app/client/src/sagas/WidgetOperationUtils.ts
> +  return childrenList;
Please add a comment here.

2022-06-15 04:56 UTC, Rishabh-Rathod commented on app/client/cypress/support/Pages/AggregateHelper.ts
> +      });
Please explain this maths magic with a comment.

2022-06-15 04:56 UTC, Rishabh-Rathod commented on app/client/src/sagas/WidgetOperationSagas.tsx
> +    yield put(resetWidgetMetaProperty(childId, childWidget));
What if we do yield all then logic to dispatch each action in parallel?

2022-06-15 07:29 UTC, Rishabh-Rathod commented on app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx
> +      // filterText: "",
Quoting @Tooluloope "I think, it's fine to remove from the map". 
Also, as i believe that is correct way, will go ahead and remove this.

2022-06-15 07:51 UTC, Rishabh-Rathod commented on app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx
> +      // filterText: "",
done ✅

2022-06-15 07:52 UTC, Rishabh-Rathod commented on app/client/src/sagas/WidgetOperationSagas.tsx
> +    yield put(resetWidgetMetaProperty(childId, childWidget));
could be tried in a separate PR

2022-06-15 07:55 UTC, Rishabh-Rathod commented
/ok-to-test sha=25057ef

2022-06-15 08:18 UTC, Aishwarya-U-R commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/MultiSelect_spec.js
> +  it("Verify MultiSelect resets to default value", function() {
Hey, from next time - please give test case a number - so it makes it little easier to identify a test-case in CI runs/debugging!

2022-06-15 08:22 UTC, Aishwarya-U-R commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/MultiSelect_spec.js
> +    );
Can we also add few more cases -
1. Default value is more than one option value
2. Default value is empty
3. Default value outside of options value, eg: in this case ["BLUE"]

2022-06-15 08:48 UTC, Rishabh-Rathod commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/MultiSelect_spec.js
> +  it("Verify MultiSelect resets to default value", function() {
I will add it to this PR itself. I unintentionally followed what was already there.

2022-06-15 09:15 UTC, Rishabh-Rathod commented
/ok-to-test sha=54f5410

2022-06-15 09:58 UTC, Rishabh-Rathod commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/MultiSelect_spec.js
> +        ],
Done

2022-06-15 09:58 UTC, Rishabh-Rathod commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/MultiSelect_spec.js
> +    );
done

2022-06-15 09:59 UTC, Rishabh-Rathod commented
/ok-to-test sha=1bb35cd

2022-06-15 12:38 UTC, Aishwarya-U-R commented
/ok-to-test sha=565576d

2022-06-15 14:36 UTC, Aishwarya-U-R approved these changes
Approving cypress tests

2022-06-15 15:11 UTC, Aishwarya-U-R requested changes
Needs dev approval!

2022-06-16 05:32 UTC, rimildeyjsr commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/MultiSelect_spec.js
> +const agHelper = ObjectsRegistry.AggregateHelper,
can we rename this to aggregateHelper? documents this variable in the latter half of the file

2022-06-16 05:32 UTC, rimildeyjsr commented on app/client/cypress/support/Pages/AggregateHelper.ts
> +  public SelectDropDown(ddOption: string, endp = "selectwidget") {
same comment here as well, if we could use better variable names here, the code would be self-documented. We can skip this if it leads to too many changes

2022-06-16 05:32 UTC, rimildeyjsr commented on app/client/cypress/support/Pages/AggregateHelper.ts
>      if (mode == "false") {
can we have strict equality here?

2022-06-16 05:32 UTC, rimildeyjsr commented on app/client/cypress/support/Pages/AggregateHelper.ts
>        mode == "true"
can we have strict equality here?

2022-06-16 05:32 UTC, rimildeyjsr commented on app/client/cypress/support/Pages/AggregateHelper.ts
> +        const dropdownCenterPosition = +$element.height / 2;
Question - what does + infront of $element mean?

2022-06-16 05:32 UTC, rimildeyjsr commented on app/client/src/reducers/entityReducers/metaReducer/index.ts
> +            if (defaultPropertyValue !== undefined) {
do we need to explicitly check for defaultPropertyValue to be undefined? else we can shorten this to just defaultPropertyValue in the if else part

2022-06-16 05:32 UTC, rimildeyjsr commented on app/client/src/sagas/WidgetOperationUtils.ts
> +  if (widget === undefined) {
do we need to explicitly check for undefined here?

2022-06-16 05:51 UTC, Aishwarya-U-R commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/MultiSelect_spec.js
> +const agHelper = ObjectsRegistry.AggregateHelper,
Rename what - the constant name? No, I prefer it be agHelper so as to not be very clumsy (as object name is also AggregateHelper) and be synchronous with all other const names.

2022-06-16 05:52 UTC, Aishwarya-U-R commented on app/client/cypress/support/Pages/AggregateHelper.ts
> +  public SelectDropDown(ddOption: string, endp = "selectwidget") {
Will change ddOption - to dropdown in next check-in

2022-06-16 05:52 UTC, Rishabh-Rathod commented on app/client/src/sagas/WidgetOperationUtils.ts
> +  if (widget === undefined) {
The new `getWidgetChildren` function has similar logic to the older one where we were doing the same check. I maintained the same logic here.

It is possible then the widget is deleted and it won't be present in `canvasWidgets` and hence the undefined check here.
``` 
const widget = _.get(canvasWidgets, widgetId);
  // When a form widget tries to resetChildrenMetaProperties
  // But one or more of its container like children
  // have just been deleted, widget can be undefined
  if (widget === undefined) {
  ```

2022-06-16 05:54 UTC, Aishwarya-U-R commented on app/client/cypress/support/Pages/AggregateHelper.ts
>      if (mode == "false") {
There is no need of strict equality here, since this variable is 'set' & 'get' only in this file. There is no user setting value to this variable directly, so do not see a need for strict equality check!

2022-06-16 05:54 UTC, Aishwarya-U-R commented on app/client/cypress/support/Pages/AggregateHelper.ts
>        mode == "true"
Same as above!

2022-06-16 05:57 UTC, rimildeyjsr commented on app/client/src/sagas/WidgetOperationUtils.ts
> +  if (widget === undefined) {
got it!

2022-06-16 06:09 UTC, Rishabh-Rathod commented on app/client/cypress/support/Pages/AggregateHelper.ts
> +  public SelectDropDown(ddOption: string, endp = "selectwidget") {
All the changes in AggregateHelper from `let to const` or removal of unnecessary type `:string` was autofixed by eslint in vscode.

I believe we could separately improve our test code. 
I see lot of places in test code where
- strict equality check is not used and 
- variables are not named in detail to make them self explanatory.

2022-06-16 06:24 UTC, Rishabh-Rathod commented on app/client/src/reducers/entityReducers/metaReducer/index.ts
> +            if (defaultPropertyValue !== undefined) {
If `defaultPropertyValue` is any falsy value like `0` , `""` then `if(defaultPropertyValue)` won't help here. 

we will need to explicitly check here for the case of `undefined` only then don't update.
That put me into thought if we should allow `undefined` or not. Let me check that.

2022-06-16 06:45 UTC, Rishabh-Rathod commented on app/client/cypress/support/Pages/AggregateHelper.ts
> +        const dropdownCenterPosition = +$element.height / 2;
This was added to convert the type to number and resolve type error. I saw a same practice in other part of code and hence adopted it here also.

<img width="582" alt="Screenshot 2022-06-16 at 12 12 55 PM" src="https://user-images.githubusercontent.com/23132741/174008256-053f8664-87e9-45ba-a501-20b7f7ce3c8d.png">
<img width="558" alt="Screenshot 2022-06-16 at 12 13 06 PM" src="https://user-images.githubusercontent.com/23132741/174008263-88d889f6-46c5-409e-b9df-68d301b74bfb.png">

2022-06-16 06:47 UTC, Rishabh-Rathod commented on app/client/src/sagas/WidgetOperationUtils.ts
> +  if (widget === undefined) {
https://github.com/appsmithorg/appsmith/pull/14468/files#r898716879

2022-06-16 07:08 UTC, Rishabh-Rathod commented on app/client/src/reducers/entityReducers/metaReducer/index.ts
> +            if (defaultPropertyValue !== undefined) {
> That put me into thought if we should allow undefined or not. Let me check that.

metaState will already be undefined if not set any value. Hence, we could keep it like this.

2022-06-16 07:11 UTC, Rishabh-Rathod commented on app/client/src/sagas/WidgetOperationUtils.ts
> +  if (widget === undefined) {
we could have used `if (widget)` but until we don't know all the scenarios here, we could keep it as earlier.

2022-06-16 07:36 UTC, Rishabh-Rathod commented
/ok-to-test sha=3a348f3

2022-06-16 09:18 UTC, rimildeyjsr submitted a review, later dismissed
LGTM

2022-06-16 09:18 UTC, rimildeyjsr commented on app/client/cypress/support/Pages/AggregateHelper.ts
> +  public SelectDropDown(ddOption: string, endp = "selectwidget") {
I agree - maybe a refactor PR for this change? Can we make a backlog task in zenhub?

2022-06-16 09:18 UTC, rimildeyjsr commented on app/client/cypress/support/Pages/AggregateHelper.ts
> +        const dropdownCenterPosition = +$element.height / 2;
got it

2022-06-16 09:18 UTC, rimildeyjsr commented on app/client/src/reducers/entityReducers/metaReducer/index.ts
> +            if (defaultPropertyValue !== undefined) {
got it

2022-06-16 10:26 UTC, Rishabh-Rathod commented on app/client/cypress/support/Pages/AggregateHelper.ts
> +  public SelectDropDown(ddOption: string, endp = "selectwidget") {
I think issue should be to add eslint check for test code too. That way it will make sure all the rules are followed and if we don't want any rule we could change that config. 
@Aishwarya-U-R  Do we have any plan to add eslint and prettier config in test code?

2022-06-16 12:54 UTC, Aishwarya-U-R commented on app/client/cypress/support/Pages/AggregateHelper.ts
> +  public SelectDropDown(ddOption: string, endp = "selectwidget") {
Hey, we will need to understand that existing cypress suite was not created over-night & definitely not by one person. Lot of hands on the deck & we are trying to make it as organized as possible with new typescript cases.
Older cases/methods are too huge to change/update all of it in short span of time.

And this exercise has been on our (Automation team's) mind for sometime now - but cant guarantee any timeline for the effort as we have our hands full for new work mostly & this definitely is not the priority.

2022-06-16 12:57 UTC, Aishwarya-U-R reviewed
Cypress tests OK!

2022-06-16 12:57 UTC, Aishwarya-U-R approved these changes

2022-06-16 16:10 UTC, ramsaptami approved these changes

2022-06-19 17:44 UTC, ramsaptami commented
- [ ] Audio widget reset does not stop playing when reset using `resetWidget` even though `playState` property changes to **NOT_STARTED**
- [ ] Triggering audio recorder reset using below code returns a success message but nothing happens to the audio recorder widget if it is already recording. But it does reset widget and it's properties when it's finished recording
`{{resetWidget("AudioRecorder1",true).then(() => showAlert('success'))}}`
- [ ] Camera widget only resets it's properties but not the UI when widget is reset. i.e., widget still shows `ok` and `discard` options after reset
- [ ] Currency widget does not reset to default values
- [ ] Tab widget does not reset default tab value correctly. Toggles between selected tab and default tab values when reset
- [ ] Similar to audio widget, video widget also only changes it's playState value but not actual UI

Widget that could not be tested:
Button, Button group, Container, Divider,  Document viewer, Filepicker, Icon, iFrame, Image (indirectly tested), List, Map chart, Menu button, Modal, Statebox, Table (partly), Text

2022-06-19 18:43 UTC, Rishabh-Rathod commented
NOTE: With above changes behaviour of widgets is not changed when we reset it, it will work same as on release. 
Mainly what is changed here is evaluated values like `AudioRecorder1.blobURL`

> * [ ]  Audio widget reset does not stop playing when reset using `resetWidget` even though `playState` property changes to **NOT_STARTED**
> * [ ]  Similar to audio widget, video widget also only changes it's playState value but not actual UI

- Issue about audio & video widget on reset doesn't stop playing is widget's issue as it is not handling such cases of reset properly to verify we could compare behaviour on release.

> * [ ]  Camera widget only resets it's properties but not the UI when widget is reset. i.e., widget still shows `ok` and `discard` options after reset

- Seems like an issue with camera widget not handling reset.

> * [ ]  Triggering audio recorder reset using below code returns a success message but nothing happens to the audio recorder widget if it is already recording. But it does reset widget and it's properties when it's finished recording
>   `{{resetWidget("AudioRecorder1",true).then(() => showAlert('success'))}}`

-  When we start recording there is no property change in audio recorder widget until recording is stopped.
-  Audio recorder also doesn’t handle reset and also doesn’t have a `isRecording` property which could have changed on reset. 

> * [ ]  Currency widget does not reset to default values

- Checking (will update the comment)

> * [ ]  Tab widget does not reset default tab value correctly. Toggles between selected tab and default tab values when reset

- Checking  (will update the comment)


> Widget that could not be tested: Button, Button group, Container, Divider, Document viewer, Filepicker, Icon, iFrame, Image (indirectly tested), List, Map chart, Menu button, Modal, Statebox, Table (partly), Text

2022-06-19 19:58 UTC, Rishabh-Rathod commented
/ok-to-test sha=[481fe67](https://github.com/appsmithorg/appsmith/pull/14468/commits/481fe6785a8aeacd34c49575d5c73891d2c210ac)

2022-06-20 12:42 UTC, Rishabh-Rathod commented on app/client/src/widgets/CurrencyInputWidget/widget/index.tsx
>          const formattedValue = formatCurrencyNumber(
Now when we reset a widget we reset `props.text` to `defaultText` and hence, we should be tracking changes in meta fields instead of value. 

@sbalaji1192

2022-06-20 14:36 UTC, Rishabh-Rathod commented on app/client/cypress/support/Pages/AggregateHelper.ts
> +  public SelectDropDown(ddOption: string, endp = "selectwidget") {
replaced `ddOption` with dropdownOption here. I was not sure what `endp` stands for so i have kept it like this for now.

2022-06-20 16:39 UTC, Rishabh-Rathod commented on app/client/src/widgets/CurrencyInputWidget/widget/index.tsx
>          const formattedValue = formatCurrencyNumber(
@sbalaji1192  could you please review this change.

2022-06-22 14:10 UTC, rohitagarwal88 commented
@yatinappsmith : Need SDET to fix test cases.
cc @somangshu @ajinkyakulkarni

2022-06-23 05:38 UTC, Rishabh-Rathod commented
> @yatinappsmith : Need SDET help to fix test cases.
> cc @somangshu @ajinkyakulkarni 

Just to clarify we need to add tests here.

Test cases are mentioned https://github.com/appsmithorg/TestSmith/issues/1898

Please refer `AllInputWidget_spec` for an approach for how to write this test case faster. ( I can elaborate more on this to the assignee ) 

Ideal candidate to write such test cases will be one who has knowledge of most of the  selectors used for widgets and for interacting with widgets as we need to interact with 24 widgets here.

2022-06-24 08:26 UTC, Rishabh-Rathod commented
/ok-to-test sha=b4990ac

2022-06-24 08:59 UTC, rimildeyjsr commented on app/client/src/sagas/EvaluationsSaga.ts
> +  log.debug({ evalMetaUpdatesLength: evalMetaUpdates.length });
why are we changing this?

2022-06-24 09:02 UTC, rimildeyjsr approved these changes
Two questions, but otherwise LGTM

2022-06-24 11:47 UTC, Rishabh-Rathod commented on app/client/src/sagas/EvaluationsSaga.ts
> +  log.debug({ evalMetaUpdatesLength: evalMetaUpdates.length });
`evalMetaUpdates` has values typed by user and in case there is any sensitive data, we don't want to log that. 
Hence, changed this to provide enough information needed for logs.

2022-06-24 12:03 UTC, Rishabh-Rathod commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/MultiSelect_spec copy.js
> +/// <reference types="Cypress" />
This is to load ` load type definitions that come with Cypress module`

https://docs.cypress.io/guides/tooling/typescript-support#Types-for-Custom-Commands

This is supposed to be done in `index.ts` not sure how this got added here and i don't see this locally. let me check what is wrong here.

2022-06-24 12:18 UTC, Aishwarya-U-R commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/MultiSelect_spec copy.js
> +/// <reference types="Cypress" />
This line is added so VSCode enables IntelliSense for Cypress methods in this file. Sometimes in js specs it doesnt work & we add it on case basis. Should not harm anything else.

2022-06-25 03:16 UTC, rimildeyjsr approved these changes

2022-06-25 05:30 UTC, merged