task: WIP widget re-rendering refactor
appsmithorg/appsmith pull request #14485
Opened 2022-06-13 08:58 UTC by ashit-rath

## Description

Fixes #12938

## Type of change

> Please delete options that are not relevant.

- Performance improvement

## How Has This Been Tested?

- All existing test spec should pass
 
## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-06-13 08:59 UTC, ashit-rath commented
/ok-to-test sha=4d9cec6

2022-06-13 09:42 UTC, ashit-rath commented
/ok-to-test sha=8027618

2022-06-17 09:44 UTC, ashit-rath commented
/ok-to-test sha=28fb4fc

2022-06-17 12:03 UTC, ashit-rath commented
/ok-to-test sha=1daa9fb

2022-06-20 12:45 UTC, ashit-rath commented
/ok-to-test sha=f08fc55

2022-06-20 13:48 UTC, ashit-rath commented
/ok-to-test sha=f196fb9

2022-06-21 03:37 UTC, ashit-rath commented
/ok-to-test sha=49dd097

2022-06-21 10:12 UTC, ashit-rath commented
/ok-to-test sha=749af42

2022-06-21 13:02 UTC, ashit-rath commented
/ok-to-test sha=52a3e8e

2022-06-22 08:57 UTC, ashit-rath commented
/ok-to-test sha=d39c970

2022-06-22 09:48 UTC, ashit-rath commented
/ok-to-test sha=cbcfbbc

2022-06-24 05:54 UTC, ashit-rath commented
/ok-to-test sha=5449dde

2022-06-24 06:58 UTC, ashit-rath commented on app/client/src/utils/WidgetFactory.tsx
>      renderMode: RenderMode,
Remove?

2022-06-24 07:19 UTC, ashit-rath commented on app/client/src/pages/Editor/WidgetsEditor/CanvasContainer.tsx
> +  const widgetsStructure = useSelector(getCanvasWidgetsStructure);
Add deep equal check.

2022-06-24 07:20 UTC, ashit-rath commented on app/client/src/reducers/entityReducers/canvasWidgetsStructureReducer.ts
> +    return denormalize("0", action.payload.widgets);
Check for re-rendering

2022-06-24 17:00 UTC, SatishGandham commented
/ok-to-test sha=5449dde

2022-07-05 14:30 UTC, rahulramesha commented
/ok-to-test sha=66cf39e

2022-07-05 17:41 UTC, SatishGandham commented
/ok-to-test sha=66cf39e

2022-07-05 18:07 UTC, Rishabh-Rathod commented on app/client/src/utils/hooks/useCommentMode.ts
> +import { matchBuilderPath, matchViewerPath } from "constants/routes";
Can we separate `useCommentMode()` changes and widget re-rendering changes, if they are not dependent? 
- This way we could measure performance separately for both the changes.
- Maybe `useCommentMode()` can be shipped sooner and we could continue refactor for widget re-rendering.

2022-07-06 06:23 UTC, SatishGandham commented
/ok-to-test sha=66cf39e

2022-07-07 08:14 UTC, rahulramesha commented
/ok-to-test sha=0473bb6

2022-07-07 08:17 UTC, rahulramesha commented on app/client/src/utils/hooks/useCommentMode.ts
> +import { matchBuilderPath, matchViewerPath } from "constants/routes";
@Rishabh-Rathod I agree that changing it to a different PR helps in reviews, but I am clubbing in as much performance changes where ever visible in this PR as we are planning to have a complete regression on this PR.

2022-07-07 08:44 UTC, Rishabh-Rathod commented on app/client/src/utils/hooks/useCommentMode.ts
> +import { matchBuilderPath, matchViewerPath } from "constants/routes";
> I am clubbing in as much performance changes where ever visible in this PR as we are planning to have a complete regression on this PR.


This PR might take more time IMO to be ready. 
One of my concerns is regarding https://github.com/appsmithorg/appsmith/pull/14485#discussion_r905786853
- We will need to determine if denormalization here is causing re-rendering of widgets. If yes then we will need to figure out solution to it.
( please let me know if this is no more a concern  )

 
Few of the optimisations could be shipped without a need of separate regression testing. 
( normal release regression testing might serve the purpose ) 
_we could merge those code to release and take pull to this PR._

- Performance improvements per optimisation will be hard to determine as we club multiple optimisations into single PR. 

If we keep shipping improvements separately we would have clarity on improvements per optimisation.

I could help if in case separating code is bit complicated here.

2022-07-07 14:35 UTC, rahulramesha commented
/ok-to-test sha=e2c5289

2022-07-08 06:27 UTC, SatishGandham commented
/ok-to-test sha=e2c5289

2022-07-11 10:44 UTC, SatishGandham commented
/ok-to-test sha=e2c5289

2022-07-11 13:00 UTC, rahulramesha commented
/ok-to-test sha=687d5b6

2022-07-12 15:56 UTC, rahulramesha commented
/ok-to-test sha=f335d1f

2022-07-13 05:25 UTC, rahulramesha commented
/ok-to-test sha=07e5830

2022-07-17 15:03 UTC, rahulramesha commented
/ok-to-test sha=869cdea

2022-07-17 16:44 UTC, rahulramesha commented
/ok-to-test sha=5745cdf

2022-07-18 10:08 UTC, rahulramesha commented
/ok-to-test sha=b58f824

2022-07-18 17:06 UTC, rahulramesha commented
/ok-to-test sha=3d82b0a

2022-07-19 08:08 UTC, riodeuno commented
@rahulramesha The title says, WIP. Is there anything in particular you'd like to review and discuss?

2022-07-19 12:20 UTC, riodeuno requested changes

2022-07-19 12:20 UTC, riodeuno commented on app/client/src/widgets/FormWidget/widget/index.tsx
> +    const { childWidgets = [] } = this.props;
Now I see the use of `childWidgets` 😄 
I was wondering if we can create a new Widget API called `getDerivedPropertiesFromChildren`, and have the evaluation phase determine these?
cc @SatishGandham

2022-07-19 12:20 UTC, riodeuno commented on app/client/src/widgets/FormWidget/widget/index.tsx
> +    // @ts-ignore
As @ashit-rath mentioned, let us try to avoid disabling eslint.

2022-07-19 12:20 UTC, riodeuno commented on app/client/src/widgets/ListWidget/widget/index.tsx
> +      childWidget.skipWidgetPropsHydration = true;
This can be done via enhancements. `widgets/ListWidget/index.ts`

2022-07-19 12:20 UTC, riodeuno commented on app/client/src/widgets/withWidgetProps.tsx
> +const WIDGETS_WITH_CHILD_WIDGETS = ["LIST_WIDGET", "FORM_WIDGET"];
I was wondering if we can move this to a widget config? In the `index.ts` file within the individual widget folders?

2022-07-19 12:20 UTC, riodeuno commented on app/client/src/widgets/withWidgetProps.tsx
> +const WIDGETS_WITH_CHILD_WIDGETS = ["LIST_WIDGET", "FORM_WIDGET"];
If we can have the `getDerviedPropertiesFromChildren` API, this won't be necessary.

2022-07-19 12:20 UTC, riodeuno commented on app/client/src/widgets/withWidgetProps.tsx
> +    if (!skipWidgetPropsHydration) {
Since we have an opportunity to hydrate like this, we could perform the property updates which we do in the ContainerWidget for the child CanvasWidget, here.

2022-07-19 12:20 UTC, riodeuno commented on app/client/src/reducers/entityReducers/canvasWidgetsStructureReducer.ts
> +  bottomRow: number;
`topRow` is not mentioned here. Is that intentional?

2022-07-19 12:20 UTC, riodeuno commented on app/client/src/reducers/entityReducers/canvasWidgetsStructureReducer.ts
> +  bottomRow: 10,
@rahulramesha I believe we've added a default min bottomRow here. Shall we use the same constant?

2022-07-19 12:20 UTC, riodeuno commented on app/client/src/constants/WidgetConstants.tsx
> +  bottomRow: true,
Also, how about making this an `enum` instead?

2022-07-19 12:20 UTC, riodeuno commented on app/client/src/reducers/entityReducers/canvasWidgetsStructureReducer.ts
> +    return denormalize("0", action.payload.widgets);
If we're using the `UPDATE_LAYOUT` action, it is possible that even for property updates, we're re-computing the canvas widget structure. Resulting in the Canvas re-render. 
However, I believe, we've measured that re-renders no longer happen unless  the structure actually changes. 
So, I was wondering why it is not the case as I imagine. Please help me understand.

2022-07-19 12:20 UTC, riodeuno commented on app/client/src/selectors/editorSelectors.tsx
> + * Method to build a child widget tree
This seems like a regular function. Could we move this out of the selectors and add unit tests for this? Also, elaboration on what is happening here would help.

2022-07-19 13:16 UTC, rahulramesha commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/Button/ButtonGroup_spec.js
> +  const mod = Cypress.platform === "darwin" ? "meta" : "ctrl";
Couldn't see anything, other files seem to be using similiar code as well. Will try to move this into a separate File, to be accessed for others.

2022-07-19 13:19 UTC, rahulramesha commented on app/client/src/actions/pageActions.tsx
> +  updatedWidgetIds?: string[],
For updating the canvasWidgets Redux State, in this PR we are currently diffing to get the value, but this variable tells us which widgets were updated only those get updated in the redux state. For now it is only implemented for only one saga, this can be used for other sagas in the future and get rid of the diffing.

2022-07-19 13:27 UTC, rahulramesha commented on app/client/src/pages/common/CanvasArenas/hooks/useBlocksToBeDraggedOnCanvas.ts
> +  const occupiedSpaces =
This was included in the PR as this caused re-render of widget components even when that particular widget did not update. As the main goal of the PR is to make sure only those widget that changed gets rendered, included this as well.

2022-07-19 13:31 UTC, rahulramesha commented on app/client/src/reducers/entityReducers/canvasWidgetsReducer.tsx
> +      const updateLayoutDiff = diff(state, action.payload.widgets);
`updatedWidgetIds` in the payload is already provided in the top as an alternative to this, only one saga uses it now. Later on, once all sagas use this payload, we can even remove the diffing.

For benchmarking, will try to do that and update you, but i'm confident that whatever the time it took to diff, it would have taken even more time in rendering if there was no diffing.

2022-07-19 13:39 UTC, rahulramesha commented on app/client/src/selectors/entitiesSelector.ts
> +export const getCanvasWidget = createSelector(
yeah, now that i see it, both are similar, with check this out.

2022-07-19 13:40 UTC, rahulramesha commented on app/client/src/widgets/CanvasWidget.tsx
> +    const childWidget = klona(childWidgetData);
@ashit-rath can explain better on this one.

2022-07-19 14:22 UTC, ashit-rath commented on app/client/src/widgets/CanvasWidget.tsx
> +    const childWidget = klona(childWidgetData);
@riodeuno In this method we were modify the `childWidgetData` object by doing 
```js
childWidgetData.parentColumnSpace = snapSpaces.snapColumnSpace;
childWidgetData.parentRowSpace = snapSpaces.snapRowSpace;
```
As the `childWidgetData` was directly coming from the `props` of the widget component, they were not extensible and we were getting `Cannot add property parentColumnSpace, object is not extensible` error.

Not sure why we were not getting this error before.

2022-07-19 14:29 UTC, ashit-rath commented on app/client/src/utils/WidgetFactory.tsx
> +      // eslint-disable-next-line @typescript-eslint/ban-ts-comment
We should remove the disable eslint and fix the ts error by modifying the `widgetMap` typing to use the `CanvasWidgetStructure`

```ts
static widgetMap: Map<
    WidgetType,
    WidgetBuilder<CanvasWidgetStructure, WidgetState>
  > = new Map();
  ```
cc: @rahulramesha

2022-07-20 07:18 UTC, SatishGandham commented on app/client/src/constants/WidgetConstants.tsx
> +  bottomRow: true,
@rahulramesha , How are widgets getting these props? Are they subscribing to them individually?

2022-07-20 07:25 UTC, SatishGandham commented on app/client/src/pages/AppViewer/AppViewerPageContainer.tsx
> +  const widgetsStructure = useSelector(getCanvasWidgetsStructure);
What does this do? Does it return the widgets as nested json?

2022-07-20 07:52 UTC, riodeuno commented on app/client/src/widgets/CanvasWidget.tsx
> +    const childWidget = klona(childWidgetData);
The error is because the props are now immer objects. So, we can't change the value without using `produce` or extracting it. If cloning is necessary, I would recommend using `produce` from `immerjs`. If we can avoid this, it would be for the best. In fact, we could use `produce` once, in the `withWidgetProps.tsx` and update all properties we need to update there. This way, we will have one single point of mutation.

2022-07-20 15:07 UTC, Rishabh-Rathod commented on app/client/src/widgets/withWidgetProps.tsx
> +        widgetProps.rightColumn = canvasWidgetProps.rightColumn;
As above we have widgetProps generated using canvasWidgetProps `widgetProps = { ...canvasWidgetProps };` 
we might not need this code, correct?

2022-07-20 15:08 UTC, Rishabh-Rathod commented on app/client/src/widgets/withWidgetProps.tsx
> +        widgetProps.parentRowSpace = canvasWidgetProps.parentRowSpace;
As above we have widgetProps generated using canvasWidgetProps `widgetProps = { ...canvasWidgetProps };` 
we might not need this code, correct?

2022-07-20 15:09 UTC, Rishabh-Rathod commented on app/client/src/widgets/withWidgetProps.tsx
> +        if ("isFormValid" in props) widgetProps.isFormValid = props.isFormValid;
Shouldn't we check if widget type is form widget then only run above logic?

2022-07-20 15:11 UTC, Rishabh-Rathod commented on app/client/src/widgets/withWidgetProps.tsx
> +      }
Instead of if-else ladder can we use switch case here according to widget type taking particular action?

2022-07-20 15:34 UTC, Rishabh-Rathod commented on app/client/src/widgets/withWidgetProps.tsx
> +    const childWidgets = useSelector((state: AppState) => {
Just thinking out loud, instead of using `useSelector` to subscribe the store what if inside `getChildWidgets` we get store value from store.getState(). 
- I am assuming that whenever a child widget value will change, it will also change a value in parent making parent to re-render. 
- That re-render would be enough to trigger `getChildWidgets` and do the needed calculation.
- Like FormWidget has `data` and ListWidget has `childrenMetaPropertiesMap`, `childrenDefaultPropertiesMap`, `childrenEntityDefinitions` , `privateWidgets`

2022-07-20 17:16 UTC, rahulramesha commented on app/client/src/widgets/withWidgetProps.tsx
> +    const childWidgets = useSelector((state: AppState) => {
hmm, It sounds possible but don't think we can be sure that form widgets gets updated values of its children.

2022-07-21 06:10 UTC, rahulramesha commented on app/client/src/widgets/withWidgetProps.tsx
> +        widgetProps.parentRowSpace = canvasWidgetProps.parentRowSpace;
Thanks for pointing it out, must have missed this

2022-07-21 06:10 UTC, rahulramesha commented on app/client/src/widgets/withWidgetProps.tsx
> +        if ("isFormValid" in props) widgetProps.isFormValid = props.isFormValid;
`isFormValid` will only exist in Form widget props, so don't think there is a need to check for form widget.

2022-07-21 06:10 UTC, rahulramesha commented on app/client/src/widgets/withWidgetProps.tsx
> +      }
Will be removing the first if condition, so it will just be a single if.. else statement

2022-07-21 06:10 UTC, rahulramesha commented on app/client/src/widgets/withWidgetProps.tsx
> +    const childWidgets = useSelector((state: AppState) => {
This sounds possible but don't think, We can be always sure the parent gets updated child widgets.

2022-07-21 06:27 UTC, ashit-rath commented on app/client/src/sagas/WidgetOperationSagas.tsx
> +      undefined,
Instead of having 4 parameters for the `updateAndSaveLayout`, can we have just 2 and it could look something like
```
updateAndSaveLayout(updatedStateWidgets, options)
```
the `options` would have the reset of the parameters as properties.
There are some benefits of doing this
1. We won't have to pass `undefined`
2. The options object make the values more verbose.
3. Order does not matter anymore and less chance of mistakes

2022-07-21 06:27 UTC, ashit-rath commented on app/client/src/utils/hooks/useCommentMode.ts
> +    window.location.pathname,
Can we also add `setCommentMode` to the deps just to be safe?

2022-07-21 06:51 UTC, Rishabh-Rathod commented on app/client/src/widgets/withWidgetProps.tsx
> +        if ("isFormValid" in props) widgetProps.isFormValid = props.isFormValid;
Yes, but as this else for is for all widgets except `MAIN_CONTAINER_WIDGET_ID` and `CANVAS_WIDGET` shouldn’t we first check if type is form widget then only do 
```
widgetProps.onReset = props.onReset;
 if ("isFormValid" in props) widgetProps.isFormValid = props.isFormValid;
```
I understand that `"isFormValid" in props` is only in FORM_WIDGET but won't it be better to have a separate case for FORM_WIDGET ? where we do
```
case "FORM_WIDGET": {
widgetProps.onReset = props.onReset;
widgetProps.isFormValid = props.isFormValid;
}
```

2022-07-21 06:53 UTC, Rishabh-Rathod commented on app/client/src/widgets/withWidgetProps.tsx
> +      }
https://github.com/appsmithorg/appsmith/pull/14485#discussion_r926314305
As above comments mention to add case for `FORM_WIDGET` if that seems valid maybe switch case could still be better for readability but just a suggestion.

2022-07-24 21:18 UTC, Rishabh-Rathod commented on app/client/src/widgets/withWidgetProps.tsx
> +    const childWidgets = useSelector((state: AppState) => {
> don't think, We can be always sure the parent gets updated child widgets.

Makes sense to implement current way as we are planning to solve FormWidget and ListWidget issue separately soon and there is no performance degradation for those widgets.

2022-07-25 05:21 UTC, SatishGandham commented on app/client/src/pages/Editor/WidgetsEditor/CanvasContainer.tsx
> +  const widgetsStructure = useSelector(getCanvasWidgetsStructure, isEqual);
Check how canvasWidgetsStructure is updated and see if we need isEqual here.

2022-07-25 05:22 UTC, SatishGandham commented on app/client/src/pages/AppViewer/AppViewerPageContainer.tsx
> +  const widgetsStructure = useSelector(getCanvasWidgetsStructure);
We may need deep equal, check how getCanvasWidgetsStructure is updated.
Make all uses of this selector consistent.

2022-07-25 05:27 UTC, SatishGandham commented on app/client/src/resizable/resizenreflow/index.tsx
> +import { getContainerOccupiedSpacesSelectorWhileResizing } from "selectors/editorSelectors";
Do we use selector in the name of the selectors?

2022-07-25 05:47 UTC, SatishGandham commented on app/client/src/reducers/entityReducers/canvasWidgetsReducer.tsx
> +      const updateLayoutDiff = diff(state, action.payload.widgets);
`updateLayoutDiff` name feels like an action or function name instead of a variable name. Can we change it to
updateLayoutDiffs

2022-07-25 05:48 UTC, SatishGandham commented on app/client/src/reducers/entityReducers/canvasWidgetsReducer.tsx
> +      const updateLayoutDiff = diff(state, action.payload.widgets);
Action item #1, create an issue to pass down updated widget list from all sagas.

2022-07-25 10:04 UTC, SatishGandham commented on app/client/src/selectors/propertyPaneSelectors.tsx
> +  getCurrentWidgetProperties,
What is current widget?
Since we are only using widget name, can't we use the selected widgets?

And, why are we using ID's to maintain selected widgets?

2022-07-25 10:08 UTC, SatishGandham commented on app/client/src/widgets/StatboxWidget/widget/index.tsx
> -  renderChildWidget(childWidgetData: WidgetProps): React.ReactNode {
Are we removing this because this is an override from the container widget?

2022-07-25 10:14 UTC, ashit-rath commented on app/client/src/widgets/StatboxWidget/widget/index.tsx
> -  renderChildWidget(childWidgetData: WidgetProps): React.ReactNode {
Yes this is an override.
The logic used here was not functional and from a product's perspective, the functionality seemed irrelevant. So we decided to remove it.
Removing this gives us a brownie point to not persist the modified properties in the `withWidgetProps`.

2022-07-25 10:14 UTC, rahulramesha commented on app/client/src/pages/Editor/WidgetsEditor/CanvasContainer.tsx
> +  const widgetsStructure = useSelector(getCanvasWidgetsStructure, isEqual);
This is required because the `widgetsStructure` changes reference during denormalization

2022-07-25 10:18 UTC, SatishGandham commented on app/client/src/pages/Editor/WidgetsEditor/CanvasContainer.tsx
> +  const widgetsStructure = useSelector(getCanvasWidgetsStructure, isEqual);
Ok, there are places where we are using this selector without isEqual. Please check if we need deep equal there.

2022-07-25 10:19 UTC, rahulramesha commented on app/client/src/resizable/resizenreflow/index.tsx
> +import { getContainerOccupiedSpacesSelectorWhileResizing } from "selectors/editorSelectors";
`getContainerOccupiedSpacesSelectorWhileResizing` is a method that returns a selector and not a selector itself. selector was added in the name to indicate that.

2022-07-25 10:23 UTC, SatishGandham commented on app/client/src/widgets/FormWidget/widget/index.tsx
> +    return { ...childWidgets[0] };
Why are we spreading it and creating a new top level object?

2022-07-25 10:37 UTC, SatishGandham commented on app/client/src/widgets/CanvasWidget.tsx
> +    const childWidget = klona(childWidgetData);
@rahulramesha , @ashit-rath 
Since our CanvasWidgetStructure is very basic without nesting except for children array, can we use simple spread?

2022-07-25 10:38 UTC, rahulramesha commented on app/client/src/selectors/propertyPaneSelectors.tsx
> +  getCurrentWidgetProperties,
Current widget is the widget that was selected. selected widgets are stored in IDs, so we need to access the widgetName by getting the properties.

I think we store selected Widget in IDs because we store normalized values by IDs as well.

2022-07-25 10:41 UTC, SatishGandham commented on app/client/src/selectors/propertyPaneSelectors.tsx
> +  getCurrentWidgetProperties,
Action item 3, use only one unique identifier for widgets.

2022-07-25 10:49 UTC, rahulramesha commented on app/client/src/widgets/FormWidget/widget/index.tsx
> +    return { ...childWidgets[0] };
This was to make sure it doesnt mutate the childWidget.

2022-07-25 14:52 UTC, rahulramesha commented on app/client/src/reducers/uiReducers/dragResizeReducer.ts
> +    if (widgetIds && !areArraysEqual(widgetIds, state.selectedWidgets)) {
should check arrays regardless of order hence deepEqual might not work here

2022-07-26 08:24 UTC, SatishGandham commented on app/client/src/reducers/entityReducers/canvasWidgetsStructureReducer.ts
> +  const staticProps = [...Object.keys(WIDGET_DSL_STRUCTURE_PROPS)];
Is this spread required?

2022-07-26 08:35 UTC, SatishGandham commented on app/client/src/selectors/editorSelectors.tsx
> +function getWidgetSpecificChildProps(type: string) {
It's not a good sign if we have to handle per widget here.
We should find a better way to do it. 
Action item 4

2022-07-26 08:38 UTC, ashit-rath commented on app/client/src/widgets/CanvasWidget.tsx
> +    const childWidget = klona(childWidgetData);
Yes a spread should work here

2022-07-26 08:40 UTC, SatishGandham commented on app/client/src/selectors/editorSelectors.tsx
> +import _ from "lodash";
Please import only the functions we are using.
I see that we are only using bind so `import {bind} from "lodash";`

2022-07-26 08:42 UTC, SatishGandham commented on app/client/src/selectors/editorSelectors.tsx
> +    _.bind(generateOccupiedSpacesForContainer, null, _, true, containerId),
What does this do?

2022-07-26 09:06 UTC, rahulramesha commented on app/client/src/reducers/entityReducers/canvasWidgetsStructureReducer.ts
> +  const staticProps = [...Object.keys(WIDGET_DSL_STRUCTURE_PROPS)];
Will remove this

2022-07-26 09:22 UTC, SatishGandham commented on app/client/src/selectors/editorSelectors.tsx
> +    _.bind(generateOccupiedSpacesForContainer, null, _, true, containerId),
Won't passing null or undefined work? Is bind required at all? We are  not passing `this` context anyway.
My concern is with that import statement, webpack will include the entire lodash library.

Can you please add some comments to the bind line. I haven't used bind a lot and I find it confusing!!

2022-07-27 18:32 UTC, rahulramesha commented on app/client/src/widgets/withWidgetProps.tsx
> +        if ("isFormValid" in props) widgetProps.isFormValid = props.isFormValid;
The problem is, even with the switch case, we still need to check the condition `"isFormValid" in props` because of how it is written here, https://github.com/appsmithorg/appsmith/blob/9dea16317216d7ffb9796cdb59329bcb84e34e93/app/client/src/widgets/FormButtonWidget/widget/index.tsx#L158.
The code will look like, 
```
case "FORM_WIDGET": {
  if ("isFormValid" in props) {
    widgetProps.onReset = props.onReset;
    widgetProps.isFormValid = props.isFormValid;
  }
}
```

2022-07-27 18:32 UTC, rahulramesha commented on app/client/src/widgets/withWidgetProps.tsx
> +const WIDGETS_WITH_CHILD_WIDGETS = ["LIST_WIDGET", "FORM_WIDGET"];
Yes, This change is temporary. there is an issue to move this out by using derivedProperties. https://github.com/appsmithorg/appsmith/issues/15097

2022-07-27 18:33 UTC, rahulramesha commented on app/client/src/widgets/ContainerWidget/widget/index.tsx
> +    childWidget.rightColumn = componentWidth;
@riodeuno, Sounds like a viable solution to have this logic elsewere. Maybe we can explore the solution in a separate PR

2022-07-27 18:34 UTC, rahulramesha commented
/ok-to-test sha=a7b2b5a

2022-07-29 08:46 UTC, SatishGandham commented on app/client/src/constants/AppConstants.ts
> +export const CANVAS_DEFAULT_MIN_HEIGHT_ROWS = Math.ceil(
Shouldn't this be `CANVAS_DEFAULT_MIN_ROWS`

2022-07-29 11:35 UTC, SatishGandham commented
/ok-to-test sha=5ea91c8

Because it's nice to see the dip in scripting numbers 😀

2022-08-01 05:21 UTC, SatishGandham commented on app/client/src/utils/widgetRenderUtils.tsx
> +export function areArraysEqual(arr1: string[], arr2: string[]) {
This should be moved to global utils.

2022-08-01 05:22 UTC, SatishGandham commented on app/client/src/reducers/entityReducers/canvasWidgetsStructureReducer.ts
> +  const staticProps = [...Object.keys(WIDGET_DSL_STRUCTURE_PROPS)];
cc: @rahulramesha

2022-08-01 09:36 UTC, SatishGandham approved these changes

2022-08-01 17:21 UTC, rahulramesha commented
/ok-to-test sha=453e40a

2022-08-03 12:48 UTC, rahulramesha commented
/ok-to-test sha=b85ec10

2022-08-04 16:33 UTC, rahulramesha commented
/ok-to-test sha=4a03a64

2022-08-04 19:25 UTC, rahulramesha commented
/ok-to-test sha=d72182f

2022-08-05 04:48 UTC, ashit-rath reviewed
Couple of tiny comments, otherwise LGTM!

2022-08-05 04:48 UTC, ashit-rath commented on app/client/src/widgets/ContainerWidget/widget/index.tsx
> +    // childWidget.isVisible = this.props.isVisible;
Can we remove this commented out code?

2022-08-05 04:48 UTC, ashit-rath commented on app/client/src/widgets/ModalWidget/widget/index.tsx
> +    childData.isVisible = this.props.isVisible;
Do we need to set this? as if the widget's `isVisible` is set to false
View Mode - the modal widget will not render so the child won't render
Edit Mode - the modal widget will get an overlay and I think doesn't matter if the child widget `isVisible` is true as the parent overlay should be suffice.

I think we removed it in the container widget and it's also not being used in the `withWidgetProps`

2022-08-07 17:37 UTC, rahulramesha commented
/ok-to-test sha=9361f31

2022-08-08 08:54 UTC, rahulramesha commented
@SatishGandham @ashit-rath @Rishabh-Rathod @riodeuno This is ready for QA. Please let me know if this requires anymore changes.

cc: @somangshu

2022-08-08 08:57 UTC, somangshu commented
cc @vivekverma2312 @laveena-en please plan how we are going to do a full round of testing all widgets here.

2022-08-08 09:04 UTC, riodeuno commented
@rahulramesha I don't have any other comments other than the ones I've already shared in the review. I have noticed that a few of them don't have responses. Would you and other contributors to this PR go through them and respond?

2022-08-08 09:24 UTC, rahulramesha commented on app/client/src/widgets/BaseWidget.tsx
> +  childWidgets?: DataTreeWidget[];
The `childWidgets` are specifically used by List widget and Form widget, these are different from `children`, because we childWidgets contain evaluatedValues as well, which are required to determine form or list widget's state. However this is a temporary arrangement and there is already an issue to move that logic to derived properties.

2022-08-08 09:24 UTC, rahulramesha commented on app/client/src/widgets/CanvasWidget.tsx
> +    const childWidget = klona(childWidgetData);
This is resolved, we are not cloning this anymore.

2022-08-08 09:25 UTC, rahulramesha commented on app/client/src/widgets/FormWidget/widget/index.tsx
> +    const { childWidgets = [] } = this.props;
yes, there is already an issue to do exactly this. Once that is done, we can get rid of `childWidgets`.

2022-08-08 09:25 UTC, rahulramesha commented on app/client/src/widgets/ListWidget/widget/index.tsx
> +      childWidget.skipWidgetPropsHydration = true;
cc: @ashit-rath

2022-08-08 09:25 UTC, rahulramesha commented on app/client/src/widgets/withWidgetProps.tsx
> +    if (!skipWidgetPropsHydration) {
As mentioned in above comment, we can explore moving that logic in a separate PR

2022-08-08 09:30 UTC, rahulramesha commented
@riodeuno apologies, must have lost track of few of them in all the review comments, replied to the queries, 
for, https://github.com/appsmithorg/appsmith/pull/14485#discussion_r924420866
As you guessed since the structure is recalculated, the reference changes and should re-render, but we select the state at only one place and we have a deepEqual there, which prevents them from re-renders. Since the structure sized down, the deepEqual will also not take much time to calculate.

2022-08-08 09:32 UTC, ashit-rath commented on app/client/src/widgets/ListWidget/widget/index.tsx
> +      childWidget.skipWidgetPropsHydration = true;
Yes we can do it in enhancements but the intention was to keep this property transient and not part of the DSL.

2022-08-08 13:12 UTC, riodeuno commented
@rahulramesha Sounds good for now. In general, using `deepEquals` should be the last resort, as it is more of a patch fix in my opinion. Ideally, to prevent re-renders, the component data itself should have referential integrity.  This applies to data used by react components in general.

Here, this means that instead of calling `UPDATE_LAYOUT` where we replace all values, we should ideally update individual paths which have changed. This would make the `deepEquals` moot.

2022-08-08 13:24 UTC, riodeuno commented on app/client/src/reducers/entityReducers/canvasWidgetsReducer.tsx
> +      const updateLayoutDiff = diff(state, action.payload.widgets);
Sounds good. I've created a new issue for this. We'll tackle it separately.

2022-08-08 13:25 UTC, rahulramesha commented
@riodeuno yes, but in this particular scenario, where we consume the state in only one component per page for the CanvasStructure that contains all the values, diffing logic to update specific paths would take up more time or be equal to the deepEqual.

But Ideally, in the future, when we decide to further replace children with just their IDs instead of whole tree structure of children, That would be a much better solution without deepEqual. But currently to do that will require more cleanup and there are more unknowns with respect to how few widgets work.

2022-08-08 13:26 UTC, riodeuno commented on app/client/src/widgets/ListWidget/widget/index.tsx
> +      childWidget.skipWidgetPropsHydration = true;
@ashit-rath Could you elaborate on the rationale behind this? A little background on what `skipWidgetPropsHydration` does would help.

2022-08-08 13:42 UTC, ashit-rath commented on app/client/src/widgets/ListWidget/widget/index.tsx
> +      childWidget.skipWidgetPropsHydration = true;
In the `withWidgetProps` HOC, a widget's properties are computed by looking into the evaluated value, canvasWidget value and certain positional properties of the parent.

For the list widget's children, this is not applicable as they are generated by the List widget and are not present in any reducer. Further any positional manipulation like the `parentColumnSpace` or `bottomRow` can throw off the calculations made by the list widget. So whatever the `withWidgetProps` receives, we would render it untouched.
https://github.com/appsmithorg/appsmith/pull/14485/files#diff-c28fdfd0ee823c81a1a1f4908d76304f7d647da672da05e8d98492426ae631b5R56


We are planning to remove this in the list v2.

2022-08-11 10:51 UTC, rahulramesha commented
/ok-to-test sha=60a9e24

2022-08-16 09:39 UTC, rahulramesha commented
/ok-to-test sha=e5d0eb7

2022-08-17 06:16 UTC, somangshu commented
@rahulramesha there is a pending change request, Can you request the author for an approval or make the change if required. 

@vivekverma2312 @laveena-en can you please give us an update on what is happening here with the QA regression.

2022-08-17 07:14 UTC, rahulramesha commented
/ok-to-test sha=ddd5477

2022-08-17 07:17 UTC, rahulramesha commented
@riodeuno, looks like there is change request still on the PR, since the review comments were all answered, could you please give a final review on the PR.

2022-08-17 07:52 UTC, riodeuno approved these changes

2022-08-18 06:05 UTC, vivekverma2312 commented
@somangshu Testing is in progress. 7 widgets are pending, will be done by today EOD.

2022-08-18 09:26 UTC, somangshu commented
Awesome. 

@rahulramesha we can merge this as soon as we have the signoff on the rest

2022-08-19 08:41 UTC, vivekverma2312 commented
@rahulramesha Completed regression on widgets and working fine.

2022-08-19 09:54 UTC, SatishGandham approved these changes
Looks good. 
Congratulations @rahulramesha 🥳🥳🥳

2022-08-19 10:10 UTC, merged