fix: Added dropdown to select whether to send credentials in header or body in client credentials flow
appsmithorg/appsmith pull request #14545
Opened 2022-06-14 18:36 UTC by nidhi-nair

## Description

We were missing the option to select between body and header while sending credentials in the client credentials flow. This fix introduces the dropdown and maintains the default of sending as body for existing APIs.

Fixes #14218 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manually tested by hitting a mock endpoint with both settings
- JUnit tests for both settings
- Cypress test to check for correct form rendering and default option to send as body selected

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-06-14 19:28 UTC, nidhi-nair commented
/ok-to-test sha=dfa5af3

2022-06-21 11:20 UTC, Parthvi12 requested changes

2022-06-21 11:26 UTC, nidhi-nair commented on app/client/cypress.json
> +	},
Oops :|

2022-06-21 11:28 UTC, nidhi-nair commented on app/client/cypress.json
> +	},
Done :D

2022-06-21 11:36 UTC, Parthvi12 submitted a review, later dismissed

2022-06-21 11:37 UTC, Parthvi12 commented
Cypress tests look good to me.

2022-06-21 14:02 UTC, somnathdasadhikari approved these changes

2022-07-13 06:16 UTC, nidhi-nair commented
/ok-to-test sha=b587e8b

2022-07-13 08:57 UTC, sumitsum approved these changes

2022-07-13 09:03 UTC, nidhi-nair commented
Merging in because tests have passed but ui-test-result won't update.

2022-07-13 09:03 UTC, merged