fix: show js function execution errors in debugger
appsmithorg/appsmith pull request #14555
Opened 2022-06-15 06:10 UTC by ohansFavour

## Description

Fixes #14503 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
WIP

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-06-15 07:12 UTC, ohansFavour commented
/ok-to-test sha=18ff66a

2022-06-25 13:53 UTC, ohansFavour commented
/ok-to-test sha=777df48

2022-06-25 17:44 UTC, ohansFavour commented
/ok-to-test sha=7e50444

2022-06-27 05:35 UTC, ApekshaBhosale requested changes

2022-06-27 05:35 UTC, ApekshaBhosale commented on app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/JsFunctionExecution/JSFunctionExecution_spec.ts
> +  jsObj: any;
can we add type here please?

2022-06-27 06:37 UTC, ohansFavour commented
/ok-to-test sha=b2bad77

2022-06-27 08:28 UTC, ApekshaBhosale submitted a review, later dismissed

2022-06-28 09:59 UTC, ohansFavour commented
> * [ ]  function name does not appear on debugger the first time error occurs
>   ![image](https://user-images.githubusercontent.com/79509062/176142816-bb7bc270-8bc2-41c2-8b73-ece7d0d2ab31.png)
> * [ ]  The second time the same error occurs, function name appears but execution does not terminate and continues to run even in error state when explictly defined as async
> * [ ]  When code is in error state and is not async then correct error is displayed the second time
>   https://www.loom.com/share/9a08454394bc4f459aa92cdec0250134

@ramsaptami all of these issues are in release.

2 & 3 are related to https://github.com/appsmithorg/appsmith/issues/14863

2022-06-28 10:09 UTC, ramsaptami commented
PR fixes only the issue related to showing errors on the debugger that were previously not present. This functionality has been tested on the DP

2022-06-28 12:47 UTC, Rishabh-Rathod submitted a review, later dismissed
Looks good

2022-06-29 14:28 UTC, Aishwarya-U-R commented on app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/JsFunctionExecution/JSFunctionExecution_spec.ts
> +    agHelper.GetNClick(jsEditor._runButton);
@ohansFavour - is this comment addressed?

2022-06-29 14:37 UTC, ohansFavour commented on app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/JsFunctionExecution/JSFunctionExecution_spec.ts
> +    agHelper.GetNClick(jsEditor._runButton);
Yes

2022-06-29 14:38 UTC, ohansFavour commented
/ok-to-test sha=8525edb

2022-06-29 18:40 UTC, ohansFavour commented
/ok-to-test sha=4e900c6

2022-06-30 06:27 UTC, Aishwarya-U-R approved these changes

2022-06-30 07:21 UTC, merged