feature: GraphQL pagination server side support
appsmithorg/appsmith pull request #14558
Opened 2022-06-15 07:58 UTC by sumitsum

## Description
- This PR provides server-side support for pagination feature of GraphQL plugin. Two types of pagination is supported: limit offset based and cursor based. 
- In case a user has configured a query variable in both the query variables editor box and the pagination tab then a warning / hint message is returned to the client. Hint message is computed and returned at the time of query edit and at the time of query execution.
- Minor refactor: Some singleton pattern helper classes have been modified to allow for inheritance and extension. This was also suggested as a feedback on one of the earlier PRs. 

Fixes #13830 

## Type of change
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
- Manual
- TBD: JUnit TC will be added as part of a different PR.

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-06-21 13:30 UTC, nidhi-nair requested changes

2022-06-21 13:30 UTC, nidhi-nair commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/ActionConfiguration.java
> +    Object selfReferencingData;
Instead of introducing another object to store data in, do you think we can store this information in `pluginSpecifiedTemplates` and have a list of paths in this location instead? That way we have a cleaner configuration for accessing data, and we'll have separated the use case of storing configuration related information and cyclical reference configuration.

This will come in useful especially wrt future migrations.

2022-07-06 01:38 UTC, sumitsum commented on app/server/appsmith-plugins/graphqlPlugin/src/main/java/com/external/utils/GraphQLPaginationUtils.java
> +        if (PaginationType.PAGE_NO.equals(actionConfiguration.getPaginationType())) {
As discussed, we can take this up later based on future requirements. I have created an issue to track it: https://github.com/appsmithorg/appsmith/issues/15034

2022-07-06 01:40 UTC, sumitsum commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/ActionConfiguration.java
> +    Object selfReferencingData;
Done. I have replaced this identifier with `selfReferencingDataPaths` which contains a set of paths instead of the data itself.

2022-07-06 04:15 UTC, nidhi-nair approved these changes
LGTM

2022-07-06 07:06 UTC, merged