fix: Property pane components re-render
appsmithorg/appsmith pull request #14581
Opened 2022-06-15 12:34 UTC by aswathkk

## Description

The following components were re-rendering when any property changes
- PropertyPaneSidebar
- PropertyPaneView
- ProeprtyPaneConnections

After inspection, I found that it was due to the selectors they were using. Modified the selector code to fix the re-rendering issue.

Fixes #14580 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manual

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-06-15 13:41 UTC, rahulramesha reviewed
@aswathkk As discussed please verify changes with respect to `() => true` for selectors.

2022-06-15 17:52 UTC, SatishGandham requested changes

2022-06-15 17:52 UTC, SatishGandham commented on app/client/src/components/editorComponents/Debugger/hooks/debuggerHooks.ts
> +  const dataTree = useSelector(getDataTree, (left, right) => {
This is not the right solve for this.
We should not use use selector at all. We don't need the dataTree until the user click the link and its not used to render any element, so use can access the store directly in the returned function.

2022-06-15 17:52 UTC, SatishGandham commented on app/client/src/pages/Editor/Explorer/Widgets/useNavigateToWidget.ts
> +  const allWidgets = useSelector(getCurrentPageWidgets, (left, right) => {
Same as previous comment.

2022-06-15 17:52 UTC, SatishGandham commented on app/client/src/pages/Editor/PropertyPane/PropertyPaneConnections.tsx
> +  const dataTree = useSelector(getDataTree, () => true);
Will this work when the dependencies change? 

For example, on text widget I change the value to {{Input1.text}}, will the dependency list be updated?

2022-06-15 17:52 UTC, SatishGandham commented on app/client/src/pages/Editor/PropertyPane/PropertyPaneView.tsx
> +    (left, right) => {
1. Use prev and next instead of left right. This is the convention followed in react and in Appsmith.
2. Can you explain what you are doing here.

2022-06-16 05:52 UTC, aswathkk commented on app/client/src/pages/Editor/PropertyPane/PropertyPaneConnections.tsx
> +  const dataTree = useSelector(getDataTree, () => true);
@SatishGandham @rahulramesha This doesn't work when the dependency changes.

I will explore the right solution and update this.

2022-06-16 05:56 UTC, aswathkk commented on app/client/src/pages/Editor/PropertyPane/PropertyPaneView.tsx
> +    (left, right) => {
1. okay. I will follow the convention.
2. getWidgetPropsForPropertyPane is returning some data that is not being used in this component. So, this one renders whenever some unwanted data changes. To resolve this, I pass a comparator function to `useSelector` which checks the equality between only the properties that are being used in the component.

2022-06-16 05:59 UTC, SatishGandham commented on app/client/src/pages/Editor/PropertyPane/PropertyPaneView.tsx
> +    (left, right) => {
In that case, please write a selector that give it only the information it needs.

2022-06-16 06:12 UTC, aswathkk commented on app/client/src/components/editorComponents/Debugger/hooks/debuggerHooks.ts
> +  const dataTree = useSelector(getDataTree, (left, right) => {
Correct.
This was also pointed out by @rahulramesha 
I will use a different approach.

2022-06-16 07:51 UTC, SatishGandham commented on app/client/src/components/editorComponents/Debugger/hooks/debuggerHooks.ts
> +    const dataTree = getDataTree(store.getState());
@aswathkk , To maintain existing logic, you need the dataTree at the time the link was clicked. 

For this to work,  subsequent updates to datatree shouldn't change the existing links.

2022-06-16 08:25 UTC, aswathkk commented on app/client/src/components/editorComponents/Debugger/hooks/debuggerHooks.ts
> +    const dataTree = getDataTree(store.getState());
@SatishGandham I didn't get you.
According to previous logic, an update to dataTree will also update navigateToEntity function. Check the dependency list of useCallback in the previous case.
Is that something else you were talking about?

2022-06-16 12:29 UTC, SatishGandham requested changes

2022-06-16 12:29 UTC, SatishGandham commented on app/client/src/pages/Editor/PropertyPane/PropertyPaneConnections.tsx
> +  );
We don't need deep equal at L204. It changes only when it actually changes.
Please verify.

2022-06-16 12:29 UTC, SatishGandham commented on app/client/src/pages/Editor/PropertyPane/PropertyPaneConnections.tsx
> +  const dataTree = useSelector(getDataTreeWithOnlyId, equal);
Shouldn't this be getDataTreeWithOnlyIds

2022-06-16 12:29 UTC, SatishGandham commented on app/client/src/pages/Editor/PropertyPane/PropertyPaneView.tsx
> +    pick(props, [
Check the time taken by pick in the chrome profiler.

2022-06-16 12:29 UTC, SatishGandham commented on app/client/src/pages/Editor/PropertyPane/PropertyPaneView.tsx
> +const getWidgetPropsForPropertyPaneView = createSelector(
See if moving the selector to selectors folder, or a separate file in the same folder makes sense.

2022-06-16 14:25 UTC, aswathkk commented on app/client/src/pages/Editor/PropertyPane/PropertyPaneConnections.tsx
> +  const dataTree = useSelector(getDataTreeWithOnlyId, equal);
Yeah. 💯  I will make the change.

2022-06-20 17:56 UTC, rahulramesha requested changes

2022-06-20 17:56 UTC, rahulramesha commented on app/client/src/components/editorComponents/PropertyPaneSidebar.tsx
> -  const selectedWidgets = useMemo(
Was thinking about this and remembered why `selectedWidgets` was accessed from `canvasWidgets`.
This was to make sure that the `selected widgetIds` still exists in `canvasWidgets`. This was a mechanism to verify if the selected widgets had not been cut or deleted or the user had selected widgets from previous pages.

To fix this you could create a `selector` that had access to `canvasWidgets`, from there you could filter out the `widgetIds` that did not exist in `canvasWidgets`. You could use such selector here with an `equal` check.

2022-06-21 14:08 UTC, SatishGandham requested changes
Looks good except for few minor clarification and may be changes.

2022-06-21 14:08 UTC, SatishGandham commented on app/client/src/selectors/propertyPaneSelectors.tsx
> +  (canvasWidgets, selectedWidgets) => {
How about iterating over selected widgets and pop the array if its not on the canavs?
We won't need compact.

2022-06-22 05:17 UTC, aswathkk commented on app/client/src/pages/Editor/PropertyPane/PropertyPaneConnections.tsx
> +  );
Yes. Reference changes.

2022-06-22 05:22 UTC, aswathkk commented on app/client/src/pages/Editor/PropertyPane/PropertyPaneView.tsx
> +    getWidgetPropsForPropertyPaneView,
It is hardcoded to 4 keys ["type", "widgetId", "widgetName", "displayName"]

2022-06-22 05:35 UTC, aswathkk commented on app/client/src/pages/Editor/PropertyPane/PropertyPaneConnections.tsx
> +  );
I tested it by replacing `equal` function with a custom function and found that reference changes (using `===` operator)

2022-06-22 08:43 UTC, SatishGandham submitted a review, later dismissed

2022-06-22 14:11 UTC, aswathkk commented
/ok-to-test sha=796f9ee

2022-06-24 02:58 UTC, aswathkk commented
/ok-to-test sha=0d8d86a

2022-06-24 06:01 UTC, merged