fix: clear search input on selection
appsmithorg/appsmith pull request #14609
Opened 2022-06-16 13:07 UTC by yaldram

## Description
- The search input inside the select and multi-select widgets should clear on item selection or when the widget is closed.

Fixes #14469 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Tested Manually on the canvas.
- Added cypress test cases for all four select widgets.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-06-20 06:24 UTC, Tooluloope commented
@dilippitchika should the search input be cleared when we close the dropdown or only when a selection has been made.

Also, if the above is on selection, Then it would be ideal to leave Multiselect and MultiTreeSelect out of it.

2022-06-20 11:37 UTC, dilippitchika commented
Hey @Tooluloope let's not persist the search upon closing the widget. Let it be cleared everytime we close the widget.

2022-06-20 19:44 UTC, Tooluloope requested changes
No change was made to Single Tree Select

2022-06-21 11:41 UTC, Tooluloope requested changes

2022-06-24 10:54 UTC, yaldram commented on app/client/src/widgets/SingleSelectTreeWidget/component/index.tsx
> +      setFilter("");
- @Tooluloope I have merged the latest release with your `useDropdown` changes, please check.
- For the widgets that have the `serverSideFiltering`, only two widgets namely `select & multselect` we will not clear the search input if `serverSideFiltering` is on. I have added the test cases for each scenario
- Also I have not use a `useCallback` hook for my `onDropdownVisibleChange` function because I think it is not doing any expensive calculations.

2022-06-30 23:03 UTC, Tooluloope requested changes
Could you just fix the UX
https://user-images.githubusercontent.com/31691737/176792446-bfcc89dc-28f4-402f-8df3-a29df8cbebcf.mov

2022-06-30 23:03 UTC, Tooluloope commented on app/client/src/widgets/MultiSelectTreeWidget/component/index.tsx
> +
Please make the UX same with that of Select Widget.
Clear filter on open

2022-07-01 07:33 UTC, yaldram commented on app/client/src/widgets/MultiSelectWidgetV2/component/index.tsx
> +    }
Thanks a lot @Tooluloope for pointing this out, I have made the necessary changes. Now we remove / clear the `filterText` on widget close.

2022-07-01 07:34 UTC, yaldram commented on app/client/src/widgets/MultiSelectTreeWidget/component/index.tsx
> +
We will clear the `filterText` on widget close. With my recent changes this behaviour is consistent across all the select family.

2022-07-08 13:09 UTC, Sripriya93 commented
Have checked in select widget, searched for an option and selected and checked again, not able to see the searched option, Working fine. Also have added a new option and checked the same. Working as expected. Moving to done.

2022-07-08 13:27 UTC, merged

2025-09-05 12:31 UTC, yusben commented on app/client/src/widgets/SingleSelectTreeWidget/component/index.tsx
> +      setFilter("");
@yaldram Hello, could you please shed some light on `serverSideFiltering` limitation? I have `Select` widget with `serverSideFiltering` and currently I need repeat the same action again and again: erase the old value manually from the search field every time I open it before entering a new value.
Thank you in advance.
P. S. Decided to ask here to be in the context, hope it is okay.