fix: invite user and password reset email not being sent via config page setup
appsmithorg/appsmith pull request #14663
Opened 2022-06-19 12:04 UTC by ankitakinger

## Description

> Invite user and password reset emails not being sent via config page setup

Fixes #13976 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Tested if the values being passed to the API while toggling is correct.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-06-19 12:38 UTC, ankitakinger commented
/ok-to-test sha=81338c9

2022-06-21 05:10 UTC, IAmAnubhavSaini commented
@ankitakinger how does this affect https://github.com/appsmithorg/appsmith/pull/11703 

I am trying to understand why it was introduced and now being removed. Could you provide some description on how this change helps with "Invite user and password reset emails not being sent via config page setup".

2022-06-24 03:29 UTC, ankitakinger commented
/ok-to-test sha=b22705c

2022-06-24 04:51 UTC, ankitakinger commented
> @ankitakinger how does this affect #11703
> 
> I am trying to understand why it was introduced and now being removed. Could you provide some description on how this change helps with "Invite user and password reset emails not being sent via config page setup".

This introduced a bug elsewhere. So this is a better fix right now to tackle both scenarios - the earlier one and the current one.

2022-06-24 05:25 UTC, IAmAnubhavSaini requested changes

2022-06-24 05:25 UTC, IAmAnubhavSaini commented on app/client/src/pages/Settings/FormGroup/Toggle.tsx
> +            setting.name?.toLowerCase().includes("enable") ? false : true,
`setting.name?.toLowerCase().includes("enable")` is a boolean value. Could use `!setting.name?.toLowerCase().includes("enable")`.

2022-06-24 05:25 UTC, IAmAnubhavSaini commented on app/client/src/pages/Settings/SettingsForm.tsx
> +            props.settingsConfig[settingName].toString() == "true";
`props.settingsConfig[settingName].toString()` can be put in a variable as it is being evaluated multiple times. Above too.

2022-06-24 05:25 UTC, IAmAnubhavSaini commented on app/client/src/pages/Settings/SettingsForm.tsx
> +            props.settingsConfig[settingName].toString() == "true";
Can we use `===` instead of `==`?

2022-06-24 05:25 UTC, IAmAnubhavSaini commented on app/client/src/pages/Settings/FormGroup/Toggle.tsx
>      function onToggle(value?: boolean) {
Is there any place where `value` is not boolean? In ads/Toggle, we have `value: boolean`.

2022-06-24 05:25 UTC, IAmAnubhavSaini commented on app/client/src/pages/Settings/FormGroup/Toggle.tsx
> +        componentProps.input.onBlur(isDisableProperty ? !value : value);
`isDisableProperty ? !value : value` can be assigned to a variable.

2022-06-24 05:25 UTC, IAmAnubhavSaini commented on app/client/src/pages/Settings/FormGroup/Toggle.tsx
> +  isDisableProperty?: boolean,
This should be renamed. `isPropertyDisabled` or `isDisabledProperty` or `shouldDisableProperty`.

2022-06-24 05:25 UTC, IAmAnubhavSaini commented on app/client/src/pages/Settings/FormGroup/Toggle.tsx
> +            : componentProps.input.value
`componentProps.input.value` can be put in to a variable. Above too.

2022-06-24 05:25 UTC, IAmAnubhavSaini commented on app/client/src/pages/Settings/config/email.ts
> +        return values && values["APPSMITH_MAIL_SMTP_TLS_ENABLED"];
Can `values` be falsy?

2022-06-24 05:25 UTC, IAmAnubhavSaini commented on app/client/src/pages/Settings/SettingsForm.tsx
> +  useEffect(onClear, [subCategory]);
Are we sure that we want to fire onClear every time `subCategory` is updated?

2022-06-24 05:37 UTC, ankitakinger commented on app/client/src/pages/Settings/SettingsForm.tsx
> +  useEffect(onClear, [subCategory]);
yes

2022-06-24 05:37 UTC, ankitakinger commented on app/client/src/pages/Settings/config/email.ts
> +        return values && values["APPSMITH_MAIL_SMTP_TLS_ENABLED"];
Have handled it in SettingsForm.tsx

2022-06-24 05:59 UTC, ankitakinger commented on app/client/src/pages/Settings/FormGroup/Toggle.tsx
> +  isDisableProperty?: boolean,
done

2022-06-24 05:59 UTC, ankitakinger commented on app/client/src/pages/Settings/FormGroup/Toggle.tsx
>      function onToggle(value?: boolean) {
I'm not sure on this. Will have to check separately.

2022-06-24 06:00 UTC, ankitakinger commented on app/client/src/pages/Settings/FormGroup/Toggle.tsx
> +        componentProps.input.onBlur(isDisableProperty ? !value : value);
done

2022-06-24 06:00 UTC, ankitakinger commented on app/client/src/pages/Settings/FormGroup/Toggle.tsx
> +            : componentProps.input.value
done

2022-06-24 06:00 UTC, ankitakinger commented on app/client/src/pages/Settings/FormGroup/Toggle.tsx
> +            setting.name?.toLowerCase().includes("enable") ? false : true,
done

2022-06-24 06:00 UTC, ankitakinger commented on app/client/src/pages/Settings/SettingsForm.tsx
> +            props.settingsConfig[settingName].toString() == "true";
done

2022-06-24 06:00 UTC, ankitakinger commented on app/client/src/pages/Settings/SettingsForm.tsx
> +            props.settingsConfig[settingName].toString() == "true";
done

2022-06-24 06:12 UTC, IAmAnubhavSaini approved these changes

2022-06-24 06:13 UTC, ankitakinger commented
/ok-to-test sha=ab806f7

2022-06-24 09:52 UTC, merged

2024-02-11 16:27 UTC, stevenleeg commented
Was there ever a resolution to this one? I'm also experiencing the same issue on a fresh install of appsmith.