fix: Added support for self signed certificate during OAuth2 flows
appsmithorg/appsmith pull request #14719
Opened 2022-06-21 17:27 UTC by nidhi-nair

This PR only includes the server side changes. I'm not sure how we're meant to use switches in datasources.

Fixes #14275 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Unable to write JUnit test case for self-signed certs, have tested the flow manually
- We will need to create Cypress tests when the client side changes come in

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-07-13 17:25 UTC, nidhi-nair commented
/ok-to-test sha=e838919

2022-07-13 17:48 UTC, nidhi-nair commented
/ok-to-test sha=02beb21

2022-07-13 22:21 UTC, nidhi-nair commented
/ok-to-test sha=f4e625f

2022-07-14 11:03 UTC, nidhi-nair commented
/ok-to-test sha=f4e625f

2022-07-16 11:31 UTC, sumitsum requested changes

2022-07-16 11:31 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/AuthenticationServiceCEImpl.java
> +                    final HttpClient httpClient = HttpClient.create();
These few lines to create http client and check for self signed cert seems to be duplicated in Authorisation code and client credentials code section as well. Can we instead create a utility method somewhere like `getHttpClient` and then use that to prevent code duplication ?

2022-07-18 06:38 UTC, nidhi-nair commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/SSLHelper.java
> +    public static Consumer<? super SslProvider.SslContextSpec> sslCheckForHttpClient(DatasourceConfiguration datasourceConfiguration) {
That's actually the expected type for the lambda where this is used. I'm guessing the spec ends up being the vessel to hold other mutable configs. I've just retained the same type. :)

2022-07-18 06:55 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/AuthenticationServiceCEImpl.java
> +                    final HttpClient httpClient = HttpClient.create();
I've collected some of the logic for this into `ApiConnection`, which is a super type for these and all other types that we'll want to use for REST. I've left out the WebClient optimization though, because that will be coming in with one of Shri's [PR](https://github.com/appsmithorg/appsmith/pull/14427) which is WIP.

2022-07-18 07:10 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/AuthenticationServiceCEImpl.java
> +                    final HttpClient httpClient = HttpClient.create();
Can we use the `getSecuredHttpClient` method here as well ?

2022-07-18 07:17 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/AuthenticationServiceCEImpl.java
> +                    final HttpClient httpClient = HttpClient.create();
We'll be picking up this refactor after the conflicting PRs are merged in. Tracking this change [here](https://github.com/appsmithorg/appsmith/issues/15257).

2022-07-18 07:18 UTC, sumitsum approved these changes

2022-07-18 07:18 UTC, nidhi-nair commented
/ok-to-test sha=ac10775

2022-07-18 07:27 UTC, Aishwarya-U-R submitted a review, later dismissed
Approving cypress changes!

2022-07-18 07:55 UTC, nidhi-nair commented
/ok-to-test sha=629f76d

2022-07-20 06:35 UTC, nidhi-nair commented
/ok-to-test sha=629f76d

2022-07-21 07:49 UTC, nidhi-nair commented
/ok-to-test sha=d9637fc

2022-07-21 08:04 UTC, nidhi-nair commented
/ok-to-test sha=70e92e9

2022-07-21 10:40 UTC, merged