fix: remove the duplicate and rename the actions to events in property panel
appsmithorg/appsmith pull request #14714
Opened 2022-06-21 12:29 UTC by techbhavin

## Description

> Fix the issue of the User getting "Actions" & "Events" (duplicate) sections in the tree-select and multi-tree-select widget in the property Panel.

Fixes #14620 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-06-22 01:18 UTC, Tooluloope requested changes

2022-06-22 01:18 UTC, Tooluloope commented on app/client/src/widgets/ButtonGroupWidget/widget/index.tsx
> +                            sectionName: "Events",
Button Group.
Camera
Currency Input
Input
JSONForm and All Field Types
MapChart
All Selects
Phone Input
Switch Group

These are all the Widgets that uses Actions instead of Events

2022-06-22 06:59 UTC, Tooluloope commented on app/client/src/widgets/ButtonGroupWidget/widget/index.tsx
> +                            sectionName: "Events",
This would be handled in another PR

2022-06-22 06:59 UTC, Tooluloope submitted a review, later dismissed

2022-06-22 07:12 UTC, techbhavin commented
/ok-to-test sha=73cf628

2022-06-22 08:14 UTC, chandannkumar commented
@techbhavin The DP link seems broken here

2022-06-22 10:14 UTC, vivekverma2312 commented
@techbhavin Duplicate properties are removed the issue is now all the drop-down widget is not consistent.

- `Select` widget has `Action` at bottom of property pane
- `Multiselect` has `Action` at bottom of property pane
- `Treeselect` has `Events` in center of property pane
- `Multitreeselect` has `Event` in center of property pane

2022-06-22 10:22 UTC, techbhavin commented
@dilippitchika  can we want to rename 'Actions' to 'Events' in the Select and MultiSelect widget in a current PR?

2022-06-22 10:29 UTC, dilippitchika commented
@techbhavin yes please rename

2022-06-23 11:27 UTC, techbhavin commented
/ok-to-test sha=e61cca6

2022-06-23 11:29 UTC, Athayde3586 commented
Ok to what test

On Thu, Jun 23, 2022, 6:27 AM Bhavin K ***@***.***> wrote:

> /ok-to-test sha=e61cca6
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/appsmithorg/appsmith/pull/14714#issuecomment-1164292339>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AYYXGWQITN2OR5E3BZDTWILVQRC3BANCNFSM5ZMFLXSQ>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2022-06-24 09:25 UTC, techbhavin commented
/ok-to-test sha=0c47fdd

2022-06-24 09:40 UTC, Tooluloope submitted a review, later dismissed

2022-06-27 08:39 UTC, techbhavin commented
/ok-to-test sha=1aa2a6a

2022-06-28 05:29 UTC, vivekverma2312 commented
@techbhavin Thanks for the fix it's working fine now.

2022-06-28 06:41 UTC, techbhavin commented
/ok-to-test sha=57db9de

2022-06-28 11:14 UTC, techbhavin commented
/ok-to-test sha=57db9de

2022-06-28 12:51 UTC, Tooluloope approved these changes

2022-06-29 11:54 UTC, merged