Fix 10379 file picker
appsmithorg/appsmith pull request #14782
Opened 2022-06-24 02:45 UTC by prsidhu

## Description

TextWidget:
if text.length > 2000 and number of line breaks in text == 0;
then render only a substring (2000) of the text and display appropriate warning.

Fixes # (issue)

https://github.com/appsmithorg/appsmith/issues/10379

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

 - Follow the steps in the linked issue description.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-06-24 02:58 UTC, prsidhu commented
<img width="1542" alt="Screen Shot 2022-06-23 at 10 58 03 PM" src="https://user-images.githubusercontent.com/5424788/175453330-13a05cda-b486-455e-8887-0c40b8268cbb.png">

2022-06-24 04:35 UTC, SatishGandham requested changes

2022-06-24 04:35 UTC, SatishGandham commented on app/client/src/workers/validations.ts
> +function validateExcessLength(text: string): boolean {
Take max length as a parameter to the function.

2022-06-24 04:35 UTC, SatishGandham commented on app/client/src/workers/validations.ts
> +  const lineBreakCount = countOccurrences(text, "\n", false, 0);
How did we arrive at 20k and 2k?
I can understand giving 10-20% for edge cases, but here we are showing 20k characters, and reducing it to 2k if the length is 20k+

2022-06-24 10:19 UTC, prsidhu commented on app/client/src/workers/validations.ts
> +  const lineBreakCount = countOccurrences(text, "\n", false, 0);
@SatishGandham no that's a typo error. I'll fix it. The number of characters is a hunch. The problem is that experiment listed in the issue tries to render a single sentence of 5.5 million characters, which works on my system but crashes on Aparna's. So I have tried to play safe with the sub string length (2000). What do you suggest?

2022-06-24 10:22 UTC, prsidhu commented
/ok-to-test sha=7cd6aea

2022-06-24 11:08 UTC, prsidhu commented
/ok-to-test sha=6674590

2022-06-28 06:13 UTC, SatishGandham submitted a review, later dismissed

2022-06-28 11:51 UTC, chandannkumar commented
@prsidhu Facing app crash(page unresponsive) when we try to bind Filepicker with Text widget after uploading a file on filepicker
https://www.loom.com/share/0f8021588d724b0e86481aaaf9ee6d3f

P.S: It works fine when we bind widgets before uploading a file on filepicker

2022-06-29 12:05 UTC, prsidhu commented
/ok-to-test sha=6674590

2022-06-30 20:26 UTC, prsidhu commented
/ok-to-test sha=c105f41

2022-07-05 06:26 UTC, SatishGandham approved these changes

2022-07-05 18:45 UTC, prsidhu commented
/ok-to-test sha=cde3646

2022-07-07 05:38 UTC, merged