feat: appsmithctl backup error loggin and mailer
appsmithorg/appsmith pull request #14797
Opened 2022-06-24 12:47 UTC by sum35h

## Description

## Type of change
- New feature (non-breaking change which adds functionality)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-06-28 06:22 UTC, sharat87 requested changes
@sum35h, can you check code formatting once please? Please ensure 2-space indentation, and terminating all statements with a semicolon. I see quite a few changes that aren't consistent in these, and that's making it very hard to follow the code flow and review.

Can you fix this and submit for review again please?

2022-06-28 06:22 UTC, sharat87 commented on deploy/docker/utils/bin/constants.js
> +    MIN_REQUIRED_DISK_SPACE_IN_BYTES
```suggestion
    MIN_REQUIRED_DISK_SPACE_IN_BYTES,
```

2022-06-28 06:22 UTC, sharat87 commented on deploy/docker/utils/bin/backup.js
> +      process.exit(errorCode);
```suggestion
    utils.start(['backend', 'rts']);
    process.exit(errorCode);
```

2022-06-28 06:22 UTC, sharat87 commented on deploy/docker/utils/bin/backup.js
> +const mailer = require('./mailer')
```suggestion
const mailer = require('./mailer');
```

2022-06-28 06:22 UTC, sharat87 commented on deploy/docker/utils/bin/backup.js
> +      }
```suggestion
    utils.stop(['backend', 'rts']);

    console.log('Available free space at /appsmith-stacks');
    const availSpaceInBytes =  Number(shell.exec('df --output=avail -B 1 /appsmith-stacks | tail -n 1'));
    console.log('\n');

    if (availSpaceInBytes < Constants.MIN_REQUIRED_DISK_SPACE_IN_BYTES){
      throw new Error('Not enough space avaliable at /appsmith-stacks. Please ensure availability of atleast 5GB to backup successfully.');
    }
```

2022-06-28 06:22 UTC, sharat87 commented on deploy/docker/utils/bin/logger.js
> +    backup_error
```suggestion
    backup_error,
```

2022-06-28 06:22 UTC, sharat87 commented on deploy/docker/utils/bin/logger.js
> +      await fsPromises.mkdir(Constants.BACKUP_ERROR_LOG_PATH)
```suggestion
      await fsPromises.mkdir(Constants.BACKUP_ERROR_LOG_PATH);
```

2022-06-29 09:58 UTC, sum35h commented on deploy/docker/utils/bin/mailer.js
> +                domainNameOrIP = shell.exec('curl -s ifconfig.me')
@sharat87  Would this be acceptable way to get the ip of the instance?

2022-07-01 06:25 UTC, mohanarpit commented on deploy/docker/utils/bin/mailer.js
> +            let text = 'Appsmith backup did not complete successfully.\n\n ' +
Not urgent. But instead of hard-coding the text, is it possible to use a template? This way, all Appsmith emails will look & feel the same. 

In the Appsmith server code base, some of the mail templates can be found at: `app/server/appsmith-server/src/main/resources/email/`. It'll just look slightly more professional than a plain text mail.

2022-07-01 08:02 UTC, mohanarpit commented on deploy/docker/utils/bin/mailer.js
> +            //   console.log('Mail body: ' + text)
Suggestion to please remove commented code.

2022-07-01 08:02 UTC, mohanarpit commented on deploy/docker/utils/bin/mailer.js
> +            //   console.log('Mail body: ' + text)
Suggestion to please remove commented code.

2022-07-01 08:02 UTC, mohanarpit commented on deploy/docker/utils/bin/mailer.js
> +            console.log(err);
If we are using logger.backup_error, do we need the console.log as well?

2022-07-01 08:12 UTC, sum35h commented on deploy/docker/utils/bin/mailer.js
> +            console.log(err);
logger.backup_error() only writes to the backup log file, so console.log is being used to display it on terminal.

2022-07-01 09:02 UTC, sum35h commented on deploy/docker/utils/bin/mailer.js
> +            let text = 'Appsmith backup did not complete successfully.\n\n ' +
Okay, I'll look into this and maybe pick it up after this pr.

2022-07-04 09:55 UTC, sharat87 requested changes
Looks good. Couple of minor things, let's merge after these two.

2022-07-04 09:55 UTC, sharat87 commented on deploy/docker/utils/bin/backup.js
> +    if (command_args.includes('--error_mail')) {
Can we use `--error-mail` instead of `--error_mail` here, to stay compliant with POSIX style arguments?

2022-07-04 09:55 UTC, sharat87 commented on deploy/docker/utils/bin/backup.js
> +    const availSpaceInBytes = Number(shell.exec('df --output=avail -B 1 /appsmith-stacks | tail -n 1'));
Minor, it's recommended to use `parseInt` to turn strings into Number in JS, unless if there's a specific reason not to.

```suggestion
    const availSpaceInBytes = parseInt(shell.exec('df --output=avail -B 1 /appsmith-stacks | tail -n 1'), 10);
```

2022-07-04 11:20 UTC, sum35h commented on deploy/docker/utils/bin/mailer.js
> +            let text = 'Appsmith backup did not complete successfully.\n\n ' +
Created issue for this at [zenhub](https://app.zenhub.com/workspaces/devops-pod-629d9a5ad45779001f66d8e0/issues/appsmithorg/appsmith/14984).

2022-07-05 06:05 UTC, sharat87 approved these changes

2022-07-07 05:49 UTC, merged