feat: Simplified Google Sheets queries
appsmithorg/appsmith pull request #14869
Opened 2022-06-28 13:43 UTC by nidhi-nair

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.

## Description

> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change.

Fixes # (issue)

> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-06-28 17:35 UTC, nidhi-nair commented
/ok-to-test sha=e2fed56

2022-06-29 17:04 UTC, albinAppsmith commented on app/client/src/components/ads/Dropdown.tsx
> +            <TooltipComponent
If we need tooltip as a wrapper can't we use custom render instead of changing ADS? Or if this change is necessary then please let QA know to validate all dropdown across the system.

2022-06-29 17:05 UTC, albinAppsmith commented on app/client/src/components/ads/Dropdown.tsx
> +  let dropdownHeight = props.isMultiSelect ? "auto" : "36px";
This change also require a QA regression across the platform.

2022-06-29 21:19 UTC, ayushpahwa commented
/ok-to-test sha=aade330

2022-06-30 05:44 UTC, nidhi-nair commented
/ok-to-test sha=aade330

2022-06-30 07:14 UTC, ayushpahwa commented
/ok-to-test sha=1dcbf7c

2022-06-30 08:45 UTC, Irongade commented
/ok-to-test sha=c4a5a4a

2022-06-30 11:57 UTC, Irongade commented
/ok-to-test sha=76baa70

2022-06-30 14:49 UTC, Irongade commented
/ok-to-test sha=37961b6

2022-06-30 17:41 UTC, ayushpahwa commented on app/client/cypress/integration/Smoke_TestSuite/Application/MongoDBShoppingCart_spec.js
> +    cy.get("body").click(0, 0);
Tried with this @Aishwarya-U-R . Didn't work out.

2022-07-01 05:58 UTC, albinAppsmith commented on app/client/src/components/ads/Dropdown.tsx
> +            <TooltipComponent
This is already breaking the ellipsis functionality in JSObject page dropdown

2022-07-01 09:37 UTC, Irongade commented on app/client/src/components/ads/Dropdown.tsx
> +            <TooltipComponent
I believe this has been resolved.

2022-07-01 09:52 UTC, Irongade commented on app/client/src/components/ads/Dropdown.tsx
> +  backgroundColor?: string;
I believe this was done to ensure backwards compatibility, The default styles for the squarebox didn't meet the requirements for the UQI design. What this means is that we have two separate design look for this component. And in order to accommodate both, we pass in this flexible option.

2022-07-01 12:19 UTC, ApekshaBhosale requested changes

2022-07-01 12:26 UTC, Irongade commented on app/client/src/sagas/FormEvaluationSaga.ts
> +          yield delay(300);
No we cannot, We intentionally add an extra delay to make sure evaluations has been properly completed and the datatree has been updated before we call fetchDynamicValuesSaga.

2022-07-01 13:18 UTC, Irongade commented on app/client/src/actions/datasourceActions.ts
> +    trigger: T;
S3 queries don't use of this anymore, They make use of the new datasourceStructure API.

2022-07-04 03:57 UTC, ApekshaBhosale commented on app/client/src/sagas/FormEvaluationSaga.ts
> +          yield delay(300);
I understand you are waiting for evaluations to get over but won't this create problems in the future? is there no other way?

2022-07-04 04:54 UTC, ayushpahwa commented on app/client/src/sagas/FormEvaluationSaga.ts
> +          yield delay(300);
Hey Apeksha, I agree that the delay should be removed in this case. we have tried to optimise this but haven't been able to reliably solve this. I've created an issue for perf improvement for the same and will be picking it up after this merge. #14965

2022-07-04 05:16 UTC, Aishwarya-U-R reviewed
Approving Cypress changes!

2022-07-04 05:28 UTC, ApekshaBhosale approved these changes

2022-07-04 05:43 UTC, merged

2022-12-27 07:53 UTC, Rishabh-Rathod commented on app/client/src/components/formControls/utils.ts
> +  const updatedSection = klona(section);
We could prefer using `klona/lite` if that satisfies the cloning requirement here as it is the faster version. 

Docs link https://github.com/lukeed/klona#modes to help understand the difference in `klona/lite` vs `klona/full` mode.

cc: @nidhi-nair

2022-12-28 04:45 UTC, nidhi-nair commented on app/client/src/components/formControls/utils.ts
> +  const updatedSection = klona(section);
I'm going to defer to @ayushpahwa for this, could you please take a look?