feat: Search properties in property pane
appsmithorg/appsmith pull request #14876
Opened 2022-06-28 19:07 UTC by aswathkk

## Description

This is a POC for showing search results in property pane

Fixes #14439

## TODO

- [ ] UI for Empty search results
- [ ] Performance optimizations

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-07-27 05:33 UTC, riodeuno commented
@rahulramesha @aswathkk How will this work if we filter out the property pane, and undo? Will we clear the search filter and highlight the property control which was last changed?

2022-07-27 05:49 UTC, riodeuno requested changes
@aswathkk Overall the code looks good to me. A few comments and requests for changes. 
Have we considered how undo and redo of property updates would work in tandem with search?

2022-07-27 05:49 UTC, riodeuno commented on app/client/src/pages/Editor/PropertyPane/Generator.tsx
> +        No Properties found based on your search
Let's use the messages.ts file to save this copy.

2022-07-27 05:49 UTC, riodeuno commented on app/client/src/pages/Editor/PropertyPane/Generator.tsx
> +function EmptySearchResult() {
Shall we move this to a separate file?

2022-07-27 05:49 UTC, riodeuno commented on app/client/src/pages/Editor/PropertyPane/Generator.tsx
> +    props.searchQuery.length > 0 &&
Do we need to trim this?

2022-07-27 05:49 UTC, riodeuno commented on app/client/src/pages/Editor/PropertyPane/PanelPropertiesEditor.tsx
>    PropertyPaneControlConfig,
@aswathkk This file is getting large. Let's split the contents into multiple files. Especially, the `updateConfigPaths` function.

2022-07-27 05:51 UTC, aswathkk commented on app/client/src/pages/Editor/PropertyPane/Generator.tsx
> +    props.searchQuery.length > 0 &&
No need to trim since `props.searchQuery` is already trimmed

2022-08-02 06:25 UTC, riodeuno approved these changes

2022-08-02 18:05 UTC, merged