fix: JS toggle issue with Numeric Input & multi select dropdown controls
appsmithorg/appsmith pull request #14892
Opened 2022-06-29 06:34 UTC by aswathkk

## Description

NumericInput control which is used for the Label width property was not having a JS toggle validation. Also, the validation logic written for Dropdown control was not handling multi-select. These two validations were added to fix the issues with these controls.

Fixes #14867 
Fixes #14810 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manual
- Jest tests are added

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-06-30 18:07 UTC, rahulramesha requested changes

2022-06-30 18:07 UTC, rahulramesha commented on app/client/src/components/propertyControls/DropDownControl.tsx
> +        for (const x of values.map((x: string | number) => x.toString())) {
Looks like you are just iterating over the list twice first with `.map` and then with `for` loop. Can you just use `x.toString()` below in the if loop?

Also don't feel like a good idea to use `.map` to get the array you are iterating over inside the `for` condition. You could just create the array before and then use that in the `for` condition.

2022-07-01 05:04 UTC, aswathkk commented on app/client/src/components/propertyControls/DropDownControl.tsx
> +        for (const x of values.map((x: string | number) => x.toString())) {
My bad 🤦 

@rahulramesha 
Totally agree with your first point. I will make the change and commit.

But, I didn't get the second point. Did you mention that in terms of readability?

2022-07-03 17:10 UTC, rahulramesha approved these changes

2022-07-03 17:11 UTC, rahulramesha commented on app/client/src/components/propertyControls/DropDownControl.tsx
> +        for (const x of values.map((x: string | number) => x.toString())) {
@aswathkk yes, it is better to not have logic inside conditional statements

2022-07-04 03:55 UTC, aswathkk commented
/ok-to-test sha=7a51ac3

2022-07-07 05:37 UTC, merged