feat: Add API to get sample apps related to a template
appsmithorg/appsmith pull request #14942
Opened 2022-07-01 05:52 UTC by nayan-rafiq

## Description
This PR adds query params to the get similar templates API.

Fixes #14786

## Type of change
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
- Manually

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-07-06 07:13 UTC, sharat87 requested changes
Just one change I'd like to see, otherwise good to go.

2022-07-06 07:13 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationTemplateServiceCEImpl.java
> +                .queryParams(params)
Looks like the params is passed on as received without looking inside? Can we validate this map? Or, even better, just take the params we want/expect from this map, and pass _only_ those that we know.

2022-07-11 10:21 UTC, nayan-rafiq commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationTemplateServiceCEImpl.java
> +                .queryParams(params)
@sharat87 This API is actually a proxy to the underlying cloud services API, so I didn't validate the map attributes here as it's validated in the cloud services API. If in future we need an additional parameter, we only need to change in the cloud services. Do you think validating the parameters here as well is necessary?

2022-07-15 18:09 UTC, nayan-rafiq commented
/ok-to-test sha=16d0305

2022-07-18 18:19 UTC, nayan-rafiq commented
/ok-to-test sha=db910ed

2022-07-19 05:43 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationTemplateServiceCEImpl.java
> +                .queryParams(params)
Yeah, figured, but it feels a little implicit. It's probably just me being paranoid again, 🤷

2022-07-19 05:43 UTC, sharat87 approved these changes

2022-07-19 16:56 UTC, nayan-rafiq commented
/ok-to-test sha=14219c4

2022-07-21 10:56 UTC, merged