fix: switch datasource option list contains similar ds
appsmithorg/appsmith pull request #14959
Opened 2022-07-01 14:11 UTC by AmanAgarwal041

## Description

Switching Datasource on the query pane or api pane editor was showing non-similar datasources in dropdown. The list is now filtered using the `pluginId` of the current datasource with the other active datasources.

Fixes #13326

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

1. Create an application
2. Add multiple datasources (some similar, some different)
3. Create a query or api for one of the above datasources
4. When the editor opens, go to switch datasource dropdown and click on it
5. You will now see a list of only similar datasources (earlier all the active datasources were listed)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-07-01 14:14 UTC, AmanAgarwal041 commented
/ok-to-test sha=3cee6f3

2022-07-01 15:47 UTC, Irongade submitted a review, later dismissed

2022-07-04 12:52 UTC, AmanAgarwal041 commented
/ok-to-test sha=3ede568

2022-07-06 08:39 UTC, Irongade submitted a review, later dismissed

2022-07-06 10:11 UTC, Aishwarya-U-R requested changes

2022-07-06 10:11 UTC, Aishwarya-U-R commented on app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/QueryPane/SwitchDatasource_spec.js
>      );
Where is the query run on Ds - postgresDatasourceNameSecond ?

2022-07-06 10:11 UTC, Aishwarya-U-R commented on app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/QueryPane/SwitchDatasource_spec.js
DS - 'postgresDatasourceNameSecond' is not deleted?
Also please correct the test case numbers.

2022-07-07 10:23 UTC, AmanAgarwal041 commented
/ok-to-test sha=2b1ba41

2022-07-07 10:24 UTC, AmanAgarwal041 commented on app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/QueryPane/SwitchDatasource_spec.js
>      );
done

2022-07-07 10:27 UTC, AmanAgarwal041 commented on app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/QueryPane/SwitchDatasource_spec.js
>      );
done

2022-07-07 10:28 UTC, AmanAgarwal041 commented
/ok-to-test sha=3fb4bdb

2022-07-08 05:46 UTC, merged