Fix/api url field
appsmithorg/appsmith pull request #1495
Opened 2020-10-31 17:29 UTC by sumanthyedoti

fixes #1248 

Also, fixes the big twitch when text in URL field wraps multiline(file attached), by making the multiline text as a single line (assuming the URL field no need to be multiline)

![ezgif com-gif-maker](https://user-images.githubusercontent.com/30371888/97785414-dbce3480-1bca-11eb-891f-b0628d7cea16.gif)

2020-11-02 14:21 UTC, hetunandu requested changes

2020-11-02 14:21 UTC, hetunandu commented on app/client/src/components/editorComponents/CodeEditor/index.tsx
> +    singleLine?: boolean;
This setting is exposed in a different way. Use `EditorSize.COMPACT` instead

2020-11-02 14:21 UTC, hetunandu commented on app/client/.eslintrc.js
> +    "@typescript-eslint/ban-ts-ignore": "off"
Please remove this setting change. This a separate issue being worked on. For now you can commit with "--no-verify" to bypass the error while committing

2020-11-02 14:21 UTC, hetunandu commented on app/client/src/components/editorComponents/CodeEditor/index.tsx
> +      ? removeMultiLineCharacters(this.editor.getValue(), " ")
Can you add a comment here to explain why this is needed?

2020-11-02 16:42 UTC, sumanthyedoti commented on app/client/src/components/editorComponents/CodeEditor/index.tsx
> +    singleLine?: boolean;
`EditorSize.COMPACT` is only affecting 'lineWraping' of a single line without line breaks.
I had Introduced the new prop `singleLine`, not to disturb other code wherever the CodeEditor fields are used, with COMPACT size but also allowing multi-lines.
With the `singleLine` prop I am removing multiline characters. When this behaviour is desired in someother place, the `singleLine` prop can be used. Do you still want me to implement this with `EditorSize.COMPACT`, itself?

2020-11-02 16:57 UTC, hetunandu commented on app/client/src/components/editorComponents/CodeEditor/index.tsx
> +    singleLine?: boolean;
`EditorSize.COMPACT` is used for "single line" fields so that is the correct use of the prop.

2020-11-02 16:58 UTC, hetunandu commented on app/client/src/components/editorComponents/CodeEditor/index.tsx
> +      ? removeMultiLineCharacters(this.editor.getValue(), " ")
I am considering if this is a good idea. Changing the user input in such a drastic way could lead to confusion

2020-11-02 17:21 UTC, sumanthyedoti commented on app/client/src/components/editorComponents/CodeEditor/index.tsx
> +    singleLine?: boolean;
@hetunandu Apologies, if I understood wrongly and extending the discussion. 
Since allowing multi-lines for the URL field is causing a big twitch, I tried to make it in a single line by removing multiline characters. The intention was not to allow multiline in that URL field.
Is it supposed to allow multiline in the API URL field? 
`EditorSize.COMPACT` is only intended to decide whether to wrap non-breaking lines or not, but it allows multi-lines. Like a code snippet, for example.
Not to affect other parts of the code where `EditorSize.COMPACT` is used and also multi-lines are allowed, I had introduced a new Prop.

2020-11-03 04:51 UTC, hetunandu commented on app/client/src/components/editorComponents/CodeEditor/index.tsx
> +    singleLine?: boolean;
Hey @sumanthyedoti, looks like there is definitely some lapse in understanding. Let me try to explain all the points here again. If there is still some confusion, we can jump on a discord chat to make it easier to have a back and forth.

- Essentially, "Compact" size is used to indicate that the Code Editor is a single line input. It can have a long string that when rendered and focused could be multi line (with or without new line chars) but when blurred it will always be rendered as a single line of input. Check this [recording](https://www.loom.com/share/4c9a476d85dd4386890e71ca84a4d46e)
- This behaviour is driven by `EditorSize.COMPACT` which other than setting lineWrapping makes sure that the input is always rendered in a single line. It does this by [setting the positions and height when focused vs blurred ](https://github.com/appsmithorg/appsmith/blob/release/app/client/src/components/editorComponents/CodeEditor/styledComponents.ts#L108-L212) 
- The issue is about an extra pixel of margin being rendered when the input moves from absolute positioning (when focused) to relative positioning ( when blurred ). This shows up visually as a twitch and we need to find a solution around it. Another non related issue is that line breaks are allowed which tends to break the single line of the input

- Your solution with adding the min-height solves the first issue which is to avoid the twitch as the row size is maintained when the input inside it becomes absolute.
- The solution with line breaks is a welcome extra credit but I don't really like updating a user input after they have seen it work. I would instead try to disallow the line breaks to begin with so as to avoid the confusion. Since this is unrelated to the issue tagged, you can either remove that change and create a new issue/pr around it, or just create a new issue and tag that here but a solve would be more involved than just the style fix needed for #1248

2020-11-03 06:10 UTC, hetunandu requested changes

2020-11-03 06:10 UTC, hetunandu commented on app/client/src/utils/helpers.tsx
> +export const removeMultiLineCharacters = (
Can we remove this utility as well. You can add it to the other PR.

2020-11-03 06:50 UTC, hetunandu approved these changes

2020-11-03 06:51 UTC, merged

2020-11-03 06:53 UTC, hetunandu commented
Thanks @sumanthyedoti for your contributions in making Appsmith the best tool out there 😄 

@all-contributors please add @sumanthyedoti as a contributor for code