feat: Triggerpath dependency
appsmithorg/appsmith pull request #15015
Opened 2022-07-05 09:20 UTC by ohansFavour

## Description

This PR introduces trigger path dependency and keeps linting in sync with dataTree

Fixes #11943

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
- Jest
- Cypress

- [x] https://github.com/appsmithorg/TestSmith/issues/1927
- [x] https://github.com/appsmithorg/TestSmith/issues/1928
- [x] https://github.com/appsmithorg/TestSmith/issues/1929
- [x] https://github.com/appsmithorg/TestSmith/issues/1930

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-07-05 23:08 UTC, ohansFavour commented
/ok-to-test sha=9cc1631

2022-07-06 21:37 UTC, ohansFavour commented
/ok-to-test sha=9da8e0c

2022-07-08 12:06 UTC, Rishabh-Rathod reviewed
initial review

2022-07-08 12:06 UTC, Rishabh-Rathod commented on app/client/src/workers/DataTreeEvaluator/index.ts
> +    this.allKeys = getAllPaths(unEvalTree);
we could consume `this.allKeys` directly as it was calculated in `createDependencyMap`

2022-07-08 12:06 UTC, Rishabh-Rathod commented on app/client/src/workers/linting/index.ts
> +import { DataTree, DataTreeEntity } from "entities/DataTree/dataTreeFactory";
Maybe a nit pick but as out folderName are `TitleCase` can you make linting folder as `Linting` just to be consistent.

2022-07-09 12:50 UTC, ohansFavour commented
/ok-to-test sha=81e2ce1

2022-07-09 13:45 UTC, ohansFavour commented
/ok-to-test sha=4f49dee

2022-07-09 13:54 UTC, ohansFavour commented
/ok-to-test sha=2482928

2022-07-09 16:31 UTC, ohansFavour commented
/ok-to-test sha=b3e0653

2022-07-10 16:31 UTC, ohansFavour commented
/ok-to-test sha=487ef9f

2022-07-11 10:09 UTC, Aishwarya-U-R requested changes

2022-07-11 10:09 UTC, Aishwarya-U-R commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Linting/linting_spec.ts
> +      agHelper.RenameWithInPane("Query1");
A new query is already Query1 - do we need to rename here?

2022-07-12 06:39 UTC, Rishabh-Rathod reviewed
Initial review

2022-07-12 06:39 UTC, Rishabh-Rathod commented on app/client/src/workers/DataTreeEvaluator/index.ts
> +              if (entityName in this.triggerFieldInverseDependencyMap) {
This logic can also be moved inside above `if (isWidget(entity)) {` condition, correct?
As only widget has triggerFields if entity wasn't a widget it will not be there in `triggerFieldInverseDependencyMap` ?

2022-07-12 06:39 UTC, Rishabh-Rathod commented on app/client/src/workers/DataTreeEvaluator/index.ts
> +                this.triggerFieldInverseDependencyMap[entityName].forEach(
Can we please add a comment here explaining we are removing deleted entity from the `triggerFieldInverseDependencyMap`

2022-07-12 07:48 UTC, Rishabh-Rathod reviewed
Review `Lint` folder

2022-07-12 07:48 UTC, Rishabh-Rathod commented on app/client/src/workers/evaluationUtils.ts
> +  fullPropertypath: string,
nit-pick: ~`fullPropertypath`~ -> `fullPropertyPath`

2022-07-12 07:48 UTC, Rishabh-Rathod commented on app/client/src/workers/Lint/index.ts
> +  );
1. Why are we creating global data using `unEvalTree` ? 
2. For `GLOBAL_DATA_WITHOUT_FUNCTIONS` instead of using `createGlobalData` we could directly use the `unEvalTree` here, correct?

2022-07-12 07:48 UTC, Rishabh-Rathod commented on app/client/src/workers/Lint/index.ts
> +        );
Could you please explain why we need to create both `GLOBAL_DATA_WITH_FUNCTIONS` and `GLOBAL_DATA_WITHOUT_FUNCTIONS` 

In `lintBindingPath` & `lintTriggerPath` we pass this globalData to `getLintingErrors` which has below code
```
const globalData: Record<string, boolean> = {};
  for (const dataKey in data) {
    globalData[dataKey] = true;
  }
  ```
According to my understanding, we only need all the entityNames here and single `unEvalTree` should suffice that. 
Can you please help me understand here.

2022-07-12 07:48 UTC, Rishabh-Rathod commented on app/client/src/workers/Lint/index.ts
> +  const unEvalTree = klona(unEvalDataTree);
As we are only reading values here can we please avoid deep cloning?

2022-07-13 05:19 UTC, ramsaptami commented
- [ ] Query name shows up as an error even though it exists when copy pasting snippet
- [ ] `run` keyword is identified as an error
- [ ] Non-existent JS object name does not rectify itself even after object with the same name has been created

https://www.loom.com/share/579ea6bb070447df819b0f65454ec008

2022-07-15 12:42 UTC, ohansFavour commented on app/client/src/workers/DataTreeEvaluator/index.ts
> +              if (entityName in this.triggerFieldInverseDependencyMap) {
No, any entity can be in the triggerFieldInverseDependencyMap, as long as it is referenced (or bound) in a trigger field.

2022-07-15 12:52 UTC, ohansFavour commented on app/client/src/workers/Lint/index.ts
> +        );
@Rishabh-Rathod , we can use the unEvalTree as global data for non-trigger fields, but for trigger fields, we need APPSMITH functions like `storeValue`, `showAlert` to be present in the global data hence the need for GLOBAL_DATA_WITH_FUNCTIONS.

2022-07-15 12:57 UTC, ohansFavour commented
"Query name shows up as an error even though it exists when copy pasting snippet"

This is a valid error because you've separated each call expression with a `comma`. The linter then assumes you're trying to initialize a new variable Query2.
Could we use this instead?
```
{{
Api1.run(); Query.run();
}}
```
It's the same reason `run` is errored out too.

cc: @ramsaptami

2022-07-15 13:17 UTC, ohansFavour commented
/ok-to-test sha=016e299

2022-07-19 06:54 UTC, Rishabh-Rathod submitted a review, later dismissed
LGTM, just a suggestion related to performance.

2022-07-19 06:54 UTC, Rishabh-Rathod commented on app/client/src/workers/Lint/index.ts
> +  const GLOBAL_DATA_WITH_FUNCTIONS = createGlobalData(unEvalTree, {}, true);
nitpick: Just a suggestion what if we add functions using `DATA_TREE_FUNCTIONS` something like `enhanceDataTreeWithFunctions` but only the else part avoiding looping through each dataTree entity for if part.

2022-07-19 08:06 UTC, Rishabh-Rathod requested changes

2022-07-19 08:06 UTC, Rishabh-Rathod commented on app/client/src/workers/Lint/utils.ts
> +    globalData[func] = true;
We will need to check for `funcOrFuncCreator` similar to how we do in `enhanceDataTreeWithFunctions` but here we want to avoid all action which has qualifier.
This will avoid to add `run`, `clear` , `getGeoLocation`,  `watchGeoLocation`, `stopWatchGeoLocation` which we need to avoid here. 
```suggestion
if (
      !(typeof funcOrFuncCreator === "object" &&
      "qualifier" in funcOrFuncCreator)
    ) {
    globalData[func] = true;
    }
```

2022-07-19 08:29 UTC, ohansFavour commented on app/client/src/workers/Lint/utils.ts
> +    globalData[func] = true;
@Rishabh-Rathod Nice suggestion, one caveat is that in enhanceDataTreeWithFunctions, we are doing a deep clone.  That is why I am using a new function for this.

2022-07-19 23:08 UTC, ohansFavour commented
> Please confirm on 7th case toasts as discussed!

@Aishwarya-U-R Yes, that is the behavior in production, when the texts are the same.

2022-07-19 23:09 UTC, ohansFavour commented
/ok-to-test sha=737b11a

2022-07-20 02:06 UTC, Aishwarya-U-R approved these changes
Approving Cypress tests!

2022-07-20 02:19 UTC, Aishwarya-U-R commented
@ramsaptami - Can you please help test this fix & add TestPlanApproved label accordingly? Cypress tests stands verified.

2022-07-20 06:55 UTC, ohansFavour commented
/ok-to-test sha=c7dea46

2022-07-20 07:48 UTC, ohansFavour commented
/ok-to-test sha=62637e6

2022-07-20 13:18 UTC, ohansFavour commented
/ok-to-test sha=23447a7

2022-07-20 17:19 UTC, Aishwarya-U-R commented
/ok-to-test sha=390f3dd

2022-07-21 11:04 UTC, Rishabh-Rathod approved these changes
Code LGTM. 

_2 small nit pick comments._

2022-07-21 11:04 UTC, Rishabh-Rathod commented on app/client/src/workers/Actions.ts
> +      !skipEntityFunctions &&
Can we not add the `!skipEntityFunctions` inside If condition itself?

2022-07-21 11:04 UTC, Rishabh-Rathod commented on app/client/src/workers/Lint/index.ts
> +  });
Do we need `GLOBAL_DATA_WITHOUT_FUNCTIONS` or `unEvalTree` can do the job here?

2022-07-21 14:25 UTC, ohansFavour commented on app/client/src/workers/Lint/index.ts
> +  });
Yes, we need to add fields like `THIS_CONTEXT` which is used in the script that gets linted.

2022-07-21 14:25 UTC, ohansFavour commented on app/client/src/workers/Lint/index.ts
> +  });
I will add a comment to this effect

2022-07-21 18:23 UTC, Rishabh-Rathod commented on app/client/src/workers/Actions.ts
> +      !skipEntityFunctions &&
correct, my bad. Thanks for clarification.

2022-07-21 18:58 UTC, Rishabh-Rathod approved these changes
LGTM.

2022-07-21 19:05 UTC, ohansFavour commented
/ok-to-test sha=d71a336

2022-07-22 06:05 UTC, Aishwarya-U-R commented
@ohansFavour - Failing test '4. Chart-Copy Verification' is flaky, this PR can be merged in.

2022-07-22 09:26 UTC, ohansFavour commented
/ok-to-test sha=c727881

2022-07-22 19:45 UTC, Rishabh-Rathod approved these changes
LGTM

2022-07-22 20:31 UTC, merged