fix: collapse animation changed transition duration.
appsmithorg/appsmith pull request #15017
Opened 2022-07-05 09:51 UTC by yaldram

## Description
- PropertyPane collapse animation was very slow. I have decreased the `transitionDuration` property to `20ms` I have not removed the animation totally because its causing layout shifts.

Fixes #13928

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Tested manually on the canvas the animation is fast now.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-07-08 03:15 UTC, aswathkk requested changes
@yaldram I couldn’t notice any difference after this change.
Layout shifts still happen!

Can you try disabling the transition via CSS along with setting `transitionDuration` to `0`?
```
  .bp3-collapse {
    transition: none;
  }
```

2022-07-08 08:39 UTC, aswathkk reviewed
@yaldram We still need to add `transitionDuration={0}` to the Collapse so that the component will avoid doing any extra activities required for the animation.

2022-07-08 10:24 UTC, aswathkk approved these changes

2022-07-08 12:27 UTC, Sripriya93 commented
@somangshu - The arrow in each sections might also need to be rotated faster along with the property pane collapse.

2022-07-08 13:41 UTC, yaldram commented
@Sripriya93 thanks for pointing this out. Yes the arrows should rotate faster. I have pushed a fix please verify.

2022-07-10 06:49 UTC, yaldram commented
/ok-to-test sha=dbab511

2022-07-11 05:06 UTC, aswathkk approved these changes

2022-07-11 05:41 UTC, merged