feature: Code-split for admin setting for toggling appsmith watermark
appsmithorg/appsmith pull request #15036
Opened 2022-07-06 05:43 UTC by jsartisan

Code-split for adding a checkbox for toggling the appsmith watermark in admin settings

2022-07-06 06:58 UTC, ankitakinger commented on app/client/src/pages/AppViewer/PageMenu.tsx
> +import { getAppsmithConfigs } from "ce/configs";
the import should be: `import { getAppsmithConfigs } from "**@appsmith**/configs";`

2022-07-06 06:59 UTC, ankitakinger commented on app/client/src/pages/AppViewer/BrandingBadge.tsx
> +    <span className="flex items-center p-1 px-2 space-x-2 bg-white border rounded-md w-max backdrop-blur-xl backdrop-filter">
any reason we are removing the anchor tag?

2022-07-06 07:01 UTC, ankitakinger commented on app/client/src/pages/Settings/FormGroup/group.tsx
> +                    data-testid="admin-settings-group-toggle"
data-testid needs to be updated

2022-07-06 07:15 UTC, ankitakinger commented on app/client/src/pages/Settings/FormGroup/Checkbox.tsx
> +const StyledAuthButton = styled(Button)`
This is the StyledUpgradeButton if I'm not wrong?

2022-07-06 07:19 UTC, ankitakinger requested changes
Could you please add a loom video showing these changes on Admin settings page?

2022-07-06 11:19 UTC, jsartisan commented
@ankitakinger This PR will add a UI to toggle watermark in super admin settings page. But for CE, it will be disabled
![image](https://user-images.githubusercontent.com/6636360/177538559-7b0d8b66-3809-4879-8d1f-756603a069b1.png)

2022-07-06 14:29 UTC, ankitakinger submitted a review, later dismissed

2022-07-07 05:47 UTC, jsartisan commented
/ok-to-test sha=dba14e9

2022-07-07 08:10 UTC, jsartisan commented
/ok-to-test sha=912178b

2022-07-21 14:16 UTC, jsartisan commented
/ok-to-test sha=f656918

2022-07-21 14:30 UTC, ankitakinger approved these changes

2022-07-22 07:17 UTC, ankitakinger commented
@jsartisan can we add unit and cypress tests for the new files/changes?

2022-07-25 06:23 UTC, jsartisan commented
@ankitakinger Added the cypress tests for the setting. Checking if the setting has a upgrade button. 
https://github.com/appsmithorg/appsmith/pull/15036/commits/3dd11cbe863e93bac3c95ec4ad313f9d8ea0a497

2022-07-25 06:23 UTC, jsartisan commented
/ok-to-test sha=3dd11cb

2022-07-25 06:28 UTC, ankitakinger approved these changes

2022-07-28 08:38 UTC, merged