chore: JSON Form Grouping & Reorganisation
appsmithorg/appsmith pull request #15033
Opened 2022-07-05 21:09 UTC by aswathkk

## Description

Property pane grouping and reorganisation of JSONForm widget.

This one is based on changes done in #14379

- Platform changes to support Content and Style tabs inside the panel
- Implemented the configuration changes for JSON Form Widget

Fixes #14439

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Manual

## Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-07-20 04:15 UTC, riodeuno requested changes
@aswathkk Overall this looks good to me. I have a couple of comments, and a few place where I couldn't find the relevant code. Please link to those.

2022-07-20 04:15 UTC, riodeuno commented on app/client/src/pages/Editor/PropertyPane/PropertySection.tsx
> +  /* Referring to a nested SectionWrapper */
Nice! TIL we can add comments in styles like these. This is super useful!

2022-07-20 04:15 UTC, riodeuno commented on app/client/src/pages/Editor/PropertyPane/PropertySection.tsx
> +        onClick={props.collapsible ? () => open(!isOpen) : noop}
Let's useCallback here is possible.

2022-07-20 04:15 UTC, riodeuno commented on app/client/src/widgets/JSONFormWidget/widget/propertyConfig/generatePanelPropertyConfig.ts
> +    contentChildren: [
@ashit-rath Could you review this file?

2022-07-20 04:15 UTC, riodeuno commented on app/client/src/widgets/JSONFormWidget/widget/propertyConfig/helper.ts
> +export const hiddenIfArrayOrObject = (
The function name doesn't match what this does. It seems to return a boolean. Could we rename this to `isFieldTypeArrayOrObject` or something on those lines?

2022-07-20 04:15 UTC, riodeuno commented on app/client/src/widgets/JSONFormWidget/widget/propertyConfig/properties/radioGroup.ts
> +  content: {
@aswathkk I've noticed a different way of defining content and style properties in this PR. In the previous PR, getPropertyPaneContentConfig and getPropertyPaneStyleConfig. I see that we have two different objects defined in the JSONFormWidget's `propertyConfig.ts` file. I could not find the piece of code which parses this format to the other. Can  you help me by linking to it?

2022-07-20 04:39 UTC, ashit-rath commented on app/client/src/widgets/JSONFormWidget/widget/propertyConfig/generatePanelPropertyConfig.ts
> +          ...CHECKBOX_PROPERTIES.content.general,
Shouldn't the checkbox export `content.data` instead of `content.general` and use it here?

2022-07-20 04:39 UTC, ashit-rath commented on app/client/src/widgets/JSONFormWidget/widget/propertyConfig/generatePanelPropertyConfig.ts
> +          ...ARRAY_PROPERTIES.content.data,
Shouldn't this be moved above the `Field Configuration` property?

2022-07-20 04:39 UTC, ashit-rath commented on app/client/src/widgets/JSONFormWidget/widget/propertyConfig/properties/input.ts
> +        propertyName: "defaultValue",
Can we make the `propertyName` as the first property of each property config object? It becomes easy to look for configs in a quick glance.

2022-07-21 07:25 UTC, aswathkk commented on app/client/src/widgets/JSONFormWidget/widget/propertyConfig/properties/radioGroup.ts
> +  content: {
@riodeuno Since there are a lot of properties belonging to JSON Form, they have organised it into different files.
If you look at JSONFormWidget's widget/index.ts file, you will still see getPropertyPaneContentConfig and getPropertyPaneStyleConfig.

2022-07-21 07:37 UTC, aswathkk commented on app/client/src/widgets/JSONFormWidget/widget/propertyConfig/generatePanelPropertyConfig.ts
> +          ...ARRAY_PROPERTIES.content.data,
No @ashit-rath.
We need to show the array's default property after the array's field configuration according to the Design.

2022-07-21 08:41 UTC, riodeuno approved these changes

2022-07-21 09:27 UTC, aswathkk commented on app/client/src/widgets/JSONFormWidget/widget/propertyConfig/generatePanelPropertyConfig.ts
> +          ...ARRAY_PROPERTIES.content.data,
@ashit-rath I had a discussion with @dilippitchika 
I will move this above Field configuration.

2022-07-21 09:58 UTC, ashit-rath approved these changes

2022-07-21 10:26 UTC, merged