feat: appsmithctl auto-backup and cleanup
appsmithorg/appsmith pull request #15203
Opened 2022-07-14 06:36 UTC by sum35h

## Description
Auto-cleanup of backup files using env variable `APPSMITH_BACKUP_ARCHIVE_LIMIT` (default value is 4) after every backup.
Updated docker file to include watchtower hook scripts.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-07-15 07:32 UTC, mohanarpit commented on deploy/docker/utils/bin/backup.js
>      console.log('Finished taking a baceup at', archivePath);
Nit: Typo fix.
```suggestion
    console.log('Finished taking a backup at', archivePath);
```

2022-07-15 07:42 UTC, mohanarpit commented on deploy/docker/utils/bin/backup.js
> +  console.log('Post-backup cleanup')
Suggestion: Please improve the log messages to be user friendly or remove them. 

Eg: "Starting the cleanup task after taking a backup"

This is because these log messages will be read by & inspected by users. Having user friendly log messages goes a long way in helping users understand what is happening in the script.

2022-07-15 11:14 UTC, sharat87 requested changes

2022-07-15 11:14 UTC, sharat87 commented on deploy/docker/utils/bin/utils.js
> +  }
This can actually be simplified with the `recursive` option. From the docs:

> Calling fsPromises.mkdir() when path is a directory that exists results in a rejection only when recursive is false.
> -- https://nodejs.org/api/fs.html#fspromisesmkdirpath-options

```suggestion
  await fsPromises.mkdir(Constants.BACKUP_PATH, { recursive: true });
```

2022-07-15 11:14 UTC, sharat87 commented on deploy/docker/utils/bin/utils.js
> +  return parseInt(ts, 10);
The call to `readFile` itself would do the access right? So can we just use that in the `try` block?

```suggestion
  try {
    const ts = await fsPromises.readFile(BACKUP_PATH + '/last-error-mail-ts');
    return parseInt(ts, 10);
  } catch (error) {
    return 0;
  }
```

2022-07-15 11:14 UTC, sharat87 commented on deploy/docker/watchtower-hooks/pre-check.sh
> +exit 0
We are making these files _executable_, with the `chmod +x` in the `Dockerfile`. For scripts that'll be executable, it's best to always have a shebang line. It _may_ be okay for us even without it, since these scripts only ever run on Ubuntu, but I'd still advise including the shebang line.


```suggestion
#!/usr/bin/env bash
exit 0
```

Same in the `pre-update.sh` script as well.

2022-07-18 07:25 UTC, sum35h commented on deploy/docker/watchtower-hooks/pre-check.sh
> +exit 0
chore: review change

2022-07-26 05:24 UTC, sharat87 requested changes

2022-07-26 05:24 UTC, sharat87 commented on deploy/docker/watchtower-hooks/pre-update.sh
> +appsmithctl backup --error_mail || exit 1
This is `--error-mail`, right?

```suggestion
appsmithctl backup --error-mail || exit 1
```

2022-07-26 05:24 UTC, sharat87 commented on deploy/docker/utils/bin/utils.js
> +    const ts = await fsPromises.readFile(BACKUP_PATH + '/last-error-mail-ts');
Can we move this file name or full path to a constant as well please?

2022-07-26 08:50 UTC, sharat87 approved these changes

2022-07-28 12:14 UTC, sharat87 approved these changes

2022-07-28 12:15 UTC, merged