fix: Reskinning Radio + Toggle + Checkbox
appsmithorg/appsmith pull request #15329
Opened 2022-07-20 10:29 UTC by jsartisan

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.

## Description

> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change.

Fixes # (issue)

> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-07-22 11:25 UTC, keyurparalkar requested changes

2022-07-22 11:25 UTC, keyurparalkar commented on app/client/src/components/ads/LabelWithTooltip.tsx
> -    if (compactMode || labelPosition === LabelPosition.Left) return "center";
Why are we removing this condition?

2022-07-22 11:25 UTC, keyurparalkar commented on app/client/src/components/wds/Checkbox/index.tsx
> +      background: ${darkenColor(accentColor)} !important;
Can we use css variable for accentColor?

2022-07-22 11:25 UTC, keyurparalkar commented on app/client/src/components/wds/Checkbox/index.tsx
> +      background-color: ${accentColor} !important;
Can we make use of css variable here?

2022-07-22 11:25 UTC, keyurparalkar commented on app/client/src/components/wds/Checkbox/index.tsx
> +      background-image: url(/widgets/disabledcheck-icon.svg);
Can we import this svg as an ES import rather than hard coding it here in css?

Can we do this for all the below imports?

2022-07-22 11:25 UTC, keyurparalkar commented on app/client/src/theme/wds.css
> +:root {
Is is possible to use the approach in this PR for storing css variables?  https://github.com/appsmithorg/appsmith/pull/15183/files#diff-2d7db458ec9c671d341dd63f05054a41201d03e5ff582d174e74d81ae922362d

2022-07-22 11:25 UTC, keyurparalkar commented on app/client/src/widgets/SwitchWidget/component/index.tsx
> +        `${darkenColor(accentColor)}`} !important;
Can we use css variable for accentColor?

2022-07-25 10:28 UTC, jsartisan commented on app/client/src/theme/wds.css
> +:root {
These are CSS variables that will be used by every widget. So these ones will be static. So using static CSS file is better here.

2022-07-25 10:29 UTC, jsartisan commented on app/client/src/components/wds/Checkbox/index.tsx
> +      background-image: url(/widgets/disabledcheck-icon.svg);
Actually, we can't because es import will convert it into react component and we don't want react component here.

2022-07-25 10:42 UTC, jsartisan commented on app/client/src/widgets/SwitchWidget/component/index.tsx
> +        `${darkenColor(accentColor)}`} !important;
We can use it but it won't benefit us much right now. I was using CSS variables at other places because the variables were the same. But here variables value needs to change according to props. I can send the variables with props like you did for filepicker but it won't help us much because we are anyway using styled-components that will take care of these dynamic styles.
Check out this file - I will be exactly what you suggested with wds - https://github.com/appsmithorg/appsmith/blob/wds/checkbox/app/client/src/components/wds/Checkbox/styles.module.css

2022-07-25 10:43 UTC, jsartisan commented on app/client/src/components/wds/Checkbox/index.tsx
> +      background-color: ${accentColor} !important;
Replied below.

2022-07-25 10:43 UTC, jsartisan commented on app/client/src/components/wds/Checkbox/index.tsx
> +      background: ${darkenColor(accentColor)} !important;
Replied below.

2022-07-26 05:06 UTC, jsartisan commented on app/client/src/components/ads/LabelWithTooltip.tsx
> -    if (compactMode || labelPosition === LabelPosition.Left) return "center";
Yes. This is something we changed with reskinning. We want label to be shown at flex-start when the label is on left.

2022-07-26 05:47 UTC, keyurparalkar approved these changes
LGTM!

2022-07-29 11:15 UTC, chandannkumar commented
Tested this PR for:
- Switch widget reskinning
- Switch Group widget reskinning
- Radio Group reskinning
- Checkbox widget reskinning
- Checkbox Group widget reskinning

All reskinning widgets here are working as expected

2022-08-01 07:35 UTC, jsartisan commented
/ok-to-test sha=18ed980

2022-08-02 12:43 UTC, jsartisan commented
/ok-to-test sha=a1989b6

2022-08-03 09:48 UTC, jsartisan commented
/ok-to-test sha=22c7dab

2022-08-03 11:42 UTC, jsartisan commented
/ok-to-test sha=9cc789a

2022-08-04 09:47 UTC, keyurparalkar approved these changes
LGTM!

2022-08-04 09:58 UTC, keyurparalkar commented on app/client/src/widgets/SwitchGroupWidget/index.ts
> +    rows: 4,
@jsartisan Wouldn't changing this value cause UI inconsistencies between the existing users?

2022-08-05 04:46 UTC, jsartisan commented on app/client/src/widgets/SwitchGroupWidget/index.ts
> +    rows: 4,
6 rows were not actually required for default drop. so changed it according to what we needed.

2022-08-05 04:46 UTC, merged