This commit changes two things:
appsmithorg/appsmith pull request #15332
Opened 2022-07-20 10:44 UTC by sondermanish

## Summary
	* Pom.xml --> ES- Restclient version to 7.17.5 from 7.9.2
	* ElasticSearchPlugin.java ---> changed the testDatasource method to expect a 200 instead of a 200 or 404 HTTP status code

This commit fixes a high-priority bug with github issue  https://github.com/appsmithorg/appsmith/issues/14909
	* it can now negotiate around a 403 forbidden error as it does try to send head only to user provided  URI

This commit has been tested:
	* manually for CRUD at local with ES version 7.9.2
	* manually for CR at user provide AWS instance running 7.9.3 on docker

## Description

> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change.

Fixes # (issue)

> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

The code has been manually tested for the create read delete and update use cases manually on locally hosted ES instance and server hosted ES instance

## Checklist:

- [✅] My code follows the style guidelines of this project
- [✅] I have performed a self-review of my own code
- [✅] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [✅] New and existing unit tests pass locally with my changes

2022-07-27 18:17 UTC, sondermanish commented
/ok-to-test sha=427243a

2022-07-28 11:26 UTC, sumitsum requested changes

2022-07-28 11:26 UTC, sumitsum commented on app/server/appsmith-plugins/elasticSearchPlugin/src/test/java/com/external/plugins/ElasticSearchPluginTest.java
> +                    for (String message: result.getInvalids())System.out.println("------- meow" +message);
Should this print statement be removed ?

2022-07-28 11:52 UTC, sondermanish commented on app/server/appsmith-plugins/elasticSearchPlugin/src/test/java/com/external/plugins/ElasticSearchPluginTest.java
> +                    for (String message: result.getInvalids())System.out.println("------- meow" +message);
removed the debug comments.

2022-07-28 11:52 UTC, sondermanish commented on app/server/appsmith-plugins/elasticSearchPlugin/src/main/java/com/external/plugins/ElasticSearchPlugin.java
> +        public static final String esDatasourceNotFoundMessage = "404 Error: The Page you are tyring to access does not exist";
modified as suggested.

2022-07-28 11:53 UTC, sumitsum approved these changes

2022-08-02 11:32 UTC, sondermanish commented
/ok-to-test sha=f41f3d2

2022-08-02 12:30 UTC, mohanarpit commented on app/server/appsmith-plugins/elasticSearchPlugin/src/test/java/com/external/plugins/ElasticSearchPluginTest.java
> +import com.appsmith.external.models.*;
Please remove wildcard imports

2022-08-03 07:31 UTC, Aishwarya-U-R commented
Adding 'Test Plan Approved' since cypress is NA for this DS.

2022-08-03 08:58 UTC, sondermanish commented
/ok-to-test sha=f237107

2022-08-03 08:59 UTC, sondermanish commented on app/server/appsmith-plugins/elasticSearchPlugin/src/test/java/com/external/plugins/ElasticSearchPluginTest.java
> +import com.appsmith.external.models.*;
Changed as suggested.

2022-08-03 09:22 UTC, sumitsum approved these changes

2022-08-03 11:01 UTC, merged