Add pod labels to allow for selector labels across different configs
appsmithorg/appsmith pull request #15352
Opened 2022-07-21 07:56 UTC by heroic

## Description

Some services such as istio need labels to identify pods. This will allow those services to be configurable.

Fixes #15351 

## Type of change

New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Using this in our production cluster

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

2022-07-25 15:21 UTC, heroic commented
@[pratapaprasanna](https://github.com/pratapaprasanna) any update on this?

2022-08-04 07:53 UTC, sharat87 requested changes
Small correction I think, but otherwise looks good.

Thank you for your contribution to make Appsmith better for everyone! 🎉 🍰

2022-08-04 07:53 UTC, sharat87 commented on deploy/helm/templates/statefulset.yaml
> +{{- end }}
I think you meant `podLabels` instead of `podsLabels`, right? Also, can we indent this to line up under `labels:` please? Makes it easier to read:

```suggestion
        {{- if .Values.podLabels }}
        {{- toYaml .Values.podLabels | nindent 8 }}
        {{- end }}
```

2022-08-04 09:51 UTC, merged

2022-08-04 09:51 UTC, sharat87 commented
Merged. Thank you @heroic! 🎊