fix: adds a new rule to show selectedRow in autocomplete's best match
appsmithorg/appsmith pull request #15406
Opened 2022-07-24 19:50 UTC by arunvjn

## Description
Refactored sorting logic for autocomplete.

Fixes #12790 

## Type of change
- Manual

## How Has This Been Tested?
- Manual

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-07-24 19:51 UTC, arunvjn commented
@Rishabh-Rathod Can you check out the DP ?

2022-07-25 14:23 UTC, arunvjn commented
/ok-to-test sha=bf039b4

2022-07-26 16:34 UTC, arunvjn commented
/ok-to-test sha=29c1753

2022-07-27 19:50 UTC, Rishabh-Rathod approved these changes
Code LGTM.

Few nit picks mentioned in below comments.

2022-07-27 19:50 UTC, Rishabh-Rathod commented on app/client/src/utils/autocomplete/AutocompleteSortRules.ts
> +  computeScore(completion: Completion): number {
Can you help me understand how the max score here is 10^4.
1. `RuleWeight.DataTreeFunction` value according to above seems to be 3.
2. `threshold` value for 1 << 4 will be 16 which is 2^4.
Do you meant to write  `2^4` here?

2022-07-27 19:50 UTC, Rishabh-Rathod commented on app/client/src/utils/autocomplete/AutocompleteSortRules.ts
> +  static threshold = 1 << 3;
`static threshold = 1 << 3;` can we maintain the threshold in `RuleWeight` instead of hardcoding here?

2022-07-27 19:50 UTC, Rishabh-Rathod commented on app/client/src/utils/autocomplete/TernServer.ts
> +      this.fieldEntityInformation.entityType !== "JSACTION";
Can we please use ENTITY_TYPE.JSACTION here instead of hardcoded string.

2022-07-28 04:23 UTC, arunvjn commented on app/client/src/utils/autocomplete/AutocompleteSortRules.ts
> +  computeScore(completion: Completion): number {
Yes, I was using 10 as base when I wrote the comments for these rules. Missed to update the comments when I changed the base.

2022-07-28 04:58 UTC, arunvjn commented on app/client/src/components/editorComponents/CodeEditor/index.tsx
> +        }
Changed

2022-07-28 04:58 UTC, arunvjn commented
/ok-to-test sha=4ef3be0

2022-07-28 06:43 UTC, arunvjn commented
/ok-to-test sha=fa6bb61

2022-07-28 09:28 UTC, arunvjn commented
/ok-to-test sha=04be347

2022-07-29 05:55 UTC, arunvjn commented
/ok-to-test sha=ebe6dda

2022-07-29 15:58 UTC, arunvjn commented
/ok-to-test sha=3b1c040

2022-08-01 18:01 UTC, arunvjn commented
/ok-to-test sha=b963d82

2022-08-01 19:39 UTC, arunvjn commented
/ok-to-test sha=71b76eb

2022-08-02 03:23 UTC, arunvjn commented
/ok-to-test sha=0c201a2

2022-08-02 04:06 UTC, ramsaptami commented
@Aishwarya-U-R DP has been tested and verified, only Cypress tests need a check from you :)

2022-08-02 07:40 UTC, Aishwarya-U-R commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/Autcomplete-bugs.spec.js
> +  const modifierKey = Cypress.platform === "darwin" ? "meta" : "ctrl";
1. Consider writing test scripts in ts spec file - which is lot better in maintenance
2. Index the test cases for easier debugging in CI - like `it("1. Bug #bugId test case title goes here",() =>{`
3. I see the complete spec in this case is against bug, so this can be named after bug id & added to BugTests folder under ClientSideTests.

2022-08-02 11:18 UTC, Aishwarya-U-R requested changes
Please update to ts cypress test spec!

2022-08-02 13:02 UTC, arunvjn commented
/ok-to-test sha=ca5e3f3

2022-08-02 14:35 UTC, Aishwarya-U-R approved these changes
Approving Cypress tests!

2022-08-02 15:49 UTC, arunvjn commented
/ok-to-test sha=b4c519a

2022-08-03 07:24 UTC, merged