fix: Table Widget shows scrollbar when not in focus
appsmithorg/appsmith pull request #15573
Opened 2022-08-01 10:58 UTC by souma-ghosh

## Description

1. Fixes issue where Table widget was showing scrollbar even when not in focus.
2. Verified on a windows system that this was a problem only for horizontal scroll bar for table body
3. `autoHide` property was missing for table body horizontal scroll bar; added in the fix

Fixes #3744 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manually tested

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-08-01 11:04 UTC, sbalaji1192 submitted a review, later dismissed

2022-08-02 05:26 UTC, dilippitchika commented
@sbalaji1192 @souma-ghosh can we also make the change in v1?

2022-08-02 05:28 UTC, sbalaji1192 commented
@dilippitchika Yes. The change required is really small. 
@souma-ghosh Could you fix it in V1 as well?

2022-08-02 05:39 UTC, souma-ghosh commented
/ok-to-test sha=60de46d

2022-08-02 05:39 UTC, souma-ghosh commented
Pushed the fix @sbalaji1192 @dilippitchika

2022-08-02 05:41 UTC, sbalaji1192 submitted a review, later dismissed

2022-08-02 08:28 UTC, laveena-en commented
Tested and verified (on Windows and Mac)

2022-08-02 10:42 UTC, dilippitchika commented
@sbalaji1192 @souma-ghosh this is hard to grok if the table is scrollable when my cursor is on the table. Is there some way where we show the scroll bars when user is hovering on the table?

2022-08-02 10:44 UTC, sbalaji1192 commented
@dilippitchika Yeah. we can selectively hide the scrollbar when the cursor is not on the table.
@souma-ghosh We need to ditch react custom scrolls config and achieve the functionality with CSS.

2022-08-02 10:46 UTC, souma-ghosh commented
@sbalaji1192 Got it. Will rework this

2022-08-02 10:46 UTC, sbalaji1192 commented
Thanks @souma-ghosh

2022-08-08 05:20 UTC, albinAppsmith approved these changes

2022-08-08 08:50 UTC, souma-ghosh commented
/ok-to-test sha=d8bdec3

2022-08-10 11:19 UTC, sbalaji1192 commented on app/client/src/components/ads/ScrollIndicator.tsx
> +  showScrollbarOnHover?: boolean;
`showScrollbarOnlyOnHover`

2022-08-10 11:19 UTC, sbalaji1192 commented on app/client/src/components/ads/ScrollIndicator.tsx
> +    if (showScrollbarOnHover) {
add `showScrollbarOnHover` to dependency

2022-08-10 11:19 UTC, sbalaji1192 commented on app/client/src/components/ads/ScrollIndicator.tsx
> +    if (showScrollbarOnHover) {
create a handler functions seperately using useCallback

2022-08-10 11:19 UTC, sbalaji1192 commented on app/client/src/components/ads/ScrollIndicator.tsx
> +  }, []);
containerRef, showScrollbarOnHover to dependency

2022-08-10 11:19 UTC, sbalaji1192 commented on app/client/src/widgets/TableWidget/component/Table.tsx
> +          autoHide
remove it

2022-08-10 11:19 UTC, sbalaji1192 commented on app/client/src/widgets/TableWidgetV2/component/TableStyledWrappers.tsx
> +      opacity: 0;
display none/block

2022-08-10 11:19 UTC, sbalaji1192 commented on app/client/src/widgets/TableWidgetV2/component/TableStyledWrappers.tsx
> +      &:active {
remove

2022-08-10 11:19 UTC, sbalaji1192 commented on app/client/src/widgets/TableWidgetV2/component/TableStyledWrappers.tsx
> +  .track-horizontal {
extract this into separate string.

2022-08-10 12:44 UTC, dilippitchika commented
Do we have a latest dp for this @souma-ghosh ?

2022-08-10 12:54 UTC, souma-ghosh commented
/ok-to-test sha=d8bdec3

2022-08-10 12:55 UTC, souma-ghosh commented
> Do we have a latest dp for this @souma-ghosh ?

Should be in this thread. Cannot find it. Retriggering the tests.

2022-08-10 16:17 UTC, Aishwarya-U-R commented
/ok-to-test sha=cbb9bf2

2022-08-11 09:51 UTC, souma-ghosh commented on app/client/src/widgets/TableWidgetV2/component/TableStyledWrappers.tsx
> +      &:active {
When we hover on the scroll bar its width changes from 4 to 6px. So for active state also the width needs to stay at 6px. Hence this is required

2022-08-11 09:59 UTC, souma-ghosh commented on app/client/src/widgets/TableWidgetV2/component/TableStyledWrappers.tsx
> +      opacity: 0;
Display none to hide scrollbar is causing a bug here. When page is rendered for the first time and we hover over the table the scroll bars don't appear. They only appear after the first time we try to scroll. Once they appear the subsequent "show scrollbar on hover" behaviour is fine. In ScrollIndicator component as well we are using opacity to hide the scrollbar. So sticking to opacity here.

2022-08-11 10:20 UTC, souma-ghosh commented
/ok-to-test sha=d58d7d5

2022-08-11 12:14 UTC, souma-ghosh commented
@dilippitchika Latest DP is up
https://appsmith-elv0e643f-get-appsmith.vercel.app/applications

2022-08-11 13:12 UTC, dilippitchika commented
Verified this, good to go from my end

2022-08-12 06:05 UTC, sbalaji1192 commented on app/client/src/widgets/TableWidgetV2/component/TableStyledWrappers.tsx
> +      opacity: 0;
Lets go with opacity since we're already using opacity in scrollIndicator as you mentioned

2022-08-12 06:11 UTC, sbalaji1192 commented on app/client/cypress/support/index.js
> +  // if (!navigator.userAgent.includes("Cypress")) {
Do we need this ?

2022-08-12 06:11 UTC, sbalaji1192 commented on app/client/src/components/ads/ScrollIndicator.tsx
>      if (isScrollVisible) {
change the condition to `isScrollVisible && !showScrollbarOnlyOnHover` and remove the first if

2022-08-12 06:11 UTC, sbalaji1192 commented on app/client/src/components/ads/ScrollIndicator.tsx
> +        containerRef.current?.removeEventListener("mouseenter", () =>
you need to pass the same handler reference you passed to `addEventListener` function

2022-08-12 06:11 UTC, sbalaji1192 commented on app/client/src/widgets/TableWidgetV2/component/Constants.ts
> +export const showScrollbarOnHover = `
use an appropriate name. something like scrollbarOnHoverCSS

2022-08-12 06:11 UTC, sbalaji1192 commented on app/client/src/widgets/TableWidgetV2/component/TableStyledWrappers.tsx
> +      &:active {
club this selector with `&:hover` to above

2022-08-12 06:11 UTC, sbalaji1192 commented on app/client/src/widgets/TableWidgetV2/component/TableStyledWrappers.tsx
> +    &:active {
here too

2022-08-12 06:22 UTC, Aishwarya-U-R commented on app/client/cypress/support/index.js
> +  // if (!navigator.userAgent.includes("Cypress")) {
Reverted!

2022-08-12 13:49 UTC, souma-ghosh commented
/ok-to-test sha=83f8d27

2022-08-13 09:42 UTC, tanvibhakta commented
Hey folks - just before you merge this in, can you also make sure the functional changes from here are reflected on the design system component [here](https://github.com/appsmithorg/design-system/tree/release/packages/design-system/src/ScrollIndicator)? Sorry about having to duplicate the effort.

2022-08-15 11:03 UTC, sbalaji1192 submitted a review, later dismissed

2022-08-17 10:00 UTC, tanvibhakta requested changes

2022-08-17 10:00 UTC, tanvibhakta commented on app/client/src/components/ads/ScrollIndicator.tsx
> +  showScrollbarOnlyOnHover?: boolean;
Hey folks, can you please raise a PR making these updates in the design system repo as well? 
Sorry about the duplication. 
https://github.com/appsmithorg/design-system/blob/release/packages/design-system/src/ScrollIndicator/index.tsx

2022-08-17 10:03 UTC, souma-ghosh commented on app/client/src/components/ads/ScrollIndicator.tsx
> +  showScrollbarOnlyOnHover?: boolean;
Sure will do @tanvibhakta .

2022-08-17 11:18 UTC, souma-ghosh commented
/ok-to-test sha=20a0ce4

2022-08-18 05:48 UTC, souma-ghosh commented
/ok-to-test sha=20a0ce4

2022-08-18 06:20 UTC, laveena-en commented
@souma-ghosh I noticed that the scrollbars don’t seem to be seen on hover consistently. Can you please have a look?

1. On hovering over the table for the first time, the bottom scrollbar is seen. But the one on the right is seen very faintly.
2. However on scrolling down, the scrollbar on the right is seen.
3. From the second time onwards, on hovering over the table, both the scrollbars are seen. https://www.loom.com/share/bd7eff3332024a5ca533e96b33754304

2022-08-18 09:16 UTC, tanvibhakta commented on app/client/src/components/ads/ScrollIndicator.tsx
> +        or the scroll thumb won't be visible until scroll the first scroll event happens
```suggestion
        or the scroll thumb won't be visible until the first scroll event happens
```

2022-08-18 09:17 UTC, tanvibhakta submitted a review, later dismissed

2022-08-18 09:52 UTC, souma-ghosh commented
/ok-to-test sha=3cb5c06

2022-08-18 10:35 UTC, laveena-en commented
Tested and verified.

2022-08-19 11:21 UTC, sbalaji1192 approved these changes

2022-08-19 11:30 UTC, souma-ghosh commented
/ok-to-test sha=2b07adc

2022-08-22 08:20 UTC, souma-ghosh commented
@sbalaji1192 The ScrollIndicator file has been remove from this repo and is being used directly from the design-systems repo. Sent the latest ScrollIndicator code to @albinAppsmith . He is working on pushing the changes to design-systems.

2022-08-22 08:23 UTC, souma-ghosh commented
/ok-to-test sha=01fda05

2022-08-23 06:30 UTC, sbalaji1192 approved these changes

2022-08-23 06:32 UTC, merged