Test/twilio establish connection
appsmithorg/appsmith pull request #15636
Opened 2022-08-02 17:59 UTC by felixsuarez0727

## Description

List of test to establish connection with Twilio.

Related issues: [#1866](https://github.com/appsmithorg/TestSmith/issues/1866), [#1867](https://github.com/appsmithorg/TestSmith/issues/1867), [#1868](https://github.com/appsmithorg/TestSmith/issues/1868), [#1869](https://github.com/appsmithorg/TestSmith/issues/1869)

## Relevant details for test configuration.

The following variables must be added to `app/client/cypress/fixtures/datasources.json`:

    "bearerToken":"keyXXXXXXX",
    "twilio-username":"ACXXXXXXXXX",
    "twilio-password":"XXXXXX

 If you have access to Notion you can check Twilio EngSpec for trial credentials. 

The files to be tested has the name `TwilioDataSource_spec.js`, `TwilioDataSourceBehavior_spec.js` , `TwilioDataSourceEntityExplorer_spec.js` , `TwilioDataSourceQueryPane_spec.js`  and are located in the path `app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/Datasources`

## Checklist:

- [X] Ensure is user is displayed with Twilio setup on Datasource page along with the symbol
- [X] Ensure the user is able to click on the Twilio for establishing a connection
- [X] Ensure user is displayed with Auth type and user is able to select Basic Auth
- [X]  On selection user must be displayed with Username and Password
- [X]  Ensure user is displayed with following button 1) Delete2) Test (Non -Functional)3) Save 4) Twilio Logo5) Edit name of Datasource6) Back option
- [X]  Ensure clicking on Save option the DS gets saved
- [X]  Ensure clicking on Delete the DS gets deleted
- [X]  Ensure on delete if the DS is associated with a query the DS must show an error and unable to delete
- [X]  Ensure the Password is encrypted
- [X] Ensure clicking on the back button user should be navigated to the active Datasources page
- [X] Ensure the saved Twilio is displayed under the Active tab section
- [X] Ensure the saved Twilio is displayed with the following 
                2) New Query
                3) Action Icon
                        a) Edit b) Delete
- [X] Clicking on New Query user must be navigated to Query Pane
- [X] Ensure clicking on Edit option of the action icon it is observed that the user is navigated into Datasource pane
- [X]  Ensure user is displayed with following command 1) Create Message2) Delete Message3) Fetch Message 4) List Messages5) Schedule Message 6) Update Message
- [X]  Ensure user is able to select Create message cmd and the following fields are displayed to the user 1) Twilio Account SID2) To 3) From 4) Body
- [X]  Ensure mandatory Fields are added
- [X]  Ensure the user is displayed appropriate error messages on the wrong field data
- [X]  Ensure Long body form is added
- [X]  Ensure use the method from the drop-down
- [X]  Ensure user is able to change the name from the pane
- [X]  Ensure user is able to add longer name
- [X]  Ensure user is able to add special characters to the name from Pane
- [X]  Ensure user is able to save the queries
- [X]  Ensure user is able to reopen the query pane
- [X]  Ensure user is able to edit the query pane and the changes get saved
- [X]  Ensure user is able to COPY query into the same page from Query Pane
- [X]  Ensure user is able to COPY query into the Different page from Query Pane
- [X]  Ensure user is able to MOVE query into the Different page from Query Pane
- [X]  Ensure user is able to Name conventions that are appropriate when moved/Copied
- [X]  Ensure the user is able to see the query in the entity explorer
- [X]  Ensure the user is able to change the name from the Entity explorer
- [X]  Ensure the user is able to COPY query into the same page from entity explorer
- [X]  Ensure the user is able to COPY query into the Different page from entity explorer
- [X]  Ensure the user is able to MOVE query into the Different page from entity explorer
- [X]  Ensure the user is able to Name conventions that are appropriate when moved/Copied
- [X]  Ensure the user is able to delete the query from the Entity explorer
- [X]  Ensure the user is able to add special characters as names and is reflected into the
- [X]  Ensure the user is able to copy the binding from the entity explorer and bind to a widget
- [X]  Ensure the user is able to click Show Bindings and added binding are displayed to the user
- [X]  Ensure the user is able to copy the binding from the entity explorer
- [X]  Ensure the user is able to close the binding option by clicking on the cross mark
- [X]  Ensure to add a longer query name and observe the behavior of the entity explorer
- [ ]  Ensure to add a longer query name and observe if it is truncated in the entity explorer

2022-08-03 12:45 UTC, sumitsum commented
/ok-to-test sha=86298f8

2022-08-04 18:35 UTC, felixsuarez0727 commented
/ok-to-test sha=a6c8575

2022-08-06 03:58 UTC, felixsuarez0727 commented
/ok-to-test sha=11bfdc7

2022-08-08 11:56 UTC, sumitsum commented
/ok-to-test sha=44059a3

2022-08-09 04:11 UTC, felixsuarez0727 commented
/ok-to-test sha=a04c0dc

2022-08-10 04:17 UTC, felixsuarez0727 commented
Only one test fails when running the tests in PR

![testfail.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/f4f34c6c-bac3-4a2d-b2ca-c56c7daf3c38)

But locally all issues are successful

![image.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/7690c6c6-0e7b-417f-b7a7-b801439751d5)

2022-08-10 05:19 UTC, Aishwarya-U-R requested changes

2022-08-10 05:19 UTC, Aishwarya-U-R commented on app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/Datasources/TwilioDataSourceQueryPane_spec.js
> +    cy.get(
You **cant use the styledform locators** - it will fail in CI but pass in local runs - since style components may attach or not during run time. Consider accepted locators like cy.contains('Twilio Account SID').contains("*")

2022-08-11 04:11 UTC, felixsuarez0727 commented
/ok-to-test sha=9c18525

2022-08-12 10:52 UTC, felixsuarez0727 commented
/ok-to-test sha=ac49fc6

2022-08-12 11:10 UTC, felixsuarez0727 commented on app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/Datasources/TwilioDataSourceQueryPane_spec.js
> +    cy.get(
Use of `.StyledFormComponents_*` selectors has been removed.

2022-08-12 11:14 UTC, felixsuarez0727 commented
/ok-to-test sha=ac49fc6

2022-08-13 03:26 UTC, felixsuarez0727 commented
/ok-to-test sha=1f196ac

2022-08-15 04:30 UTC, felixsuarez0727 commented
/ok-to-test sha=b9f5b49

2022-08-15 07:17 UTC, felixsuarez0727 commented
/ok-to-test sha=f688100

2022-08-16 05:41 UTC, Aishwarya-U-R reviewed
Why are Test files renamed/named with prefix spec_ .. Kindly remove, they have a naming convention to follow to be picked up for re-run & it should be '_spec' or '_Spec'

2022-08-17 06:03 UTC, felixsuarez0727 commented
/ok-to-test sha=e7247b6

2022-08-18 01:53 UTC, felixsuarez0727 commented
/ok-to-test sha=b9f5b49

2022-08-18 04:44 UTC, nidhi-nair commented
/ok-to-test sha=51b2570

2022-08-18 04:48 UTC, nidhi-nair reviewed
@felixsuarez0727 seems like we removed a bunch of tests from this PR? Could you please help me understand why this was done?

2022-08-18 10:28 UTC, Aishwarya-U-R commented
/ok-to-test sha=a52140b

2022-08-18 15:20 UTC, Aishwarya-U-R commented
@felixsuarez0727 - Also why is RTE spec removed? And publish case from AllDefault meta is commented?

2022-08-18 19:46 UTC, nidhi-nair commented
/ok-to-test sha=f9969b8

2022-08-18 22:45 UTC, felixsuarez0727 commented
/ok-to-test sha=37d12ed

2022-08-19 01:04 UTC, felixsuarez0727 commented
/ok-to-test sha=37d12ed

2022-09-27 00:52 UTC, mohanarpit commented on app/client/cypress/fixtures/datasources.json
> +  "twilio-password": "802e414f9556ec9394c135b99cc420de"
@felixsuarez0727 Are these actual Twilio credentials? If yes, please remove them from the code base & please change your credentials ASAP! 

In Cypress, when we wish to use such credentials, we always pass them as environment variables through Github secrets.

2022-09-27 21:30 UTC, felix-appsmith commented on app/client/cypress/fixtures/datasources.json
> +  "twilio-password": "802e414f9556ec9394c135b99cc420de"
Those are not "real" credentials. Twilio provides a set of "Test Credentials" that don't reduce your credit and can be used as throw away for testing.

Before making this pull, we discussed with @Aishwarya-U-R the possibility of making a Twilio account with another email (maybe support@appsmith.com) and add them as secrets. Currently, the scope of the Twilio SaaS Integration allows us to use "Test Credentials" just fine, but for more thorough testing we would need to switch to "Live Credentials".

I will remove the ones you pointed out, but we need another set for the tests to work.

2022-10-09 16:44 UTC, closed without merging