fix: graphql test cases moved to server side tests from client side tests folder
appsmithorg/appsmith pull request #15649
Opened 2022-08-03 08:03 UTC by AmanAgarwal041

## Description

Graphql Tests Added for creation, execution without pagination, execution with limit based pagination

Fixes #13367

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Running Test cases

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-08-03 13:02 UTC, Aishwarya-U-R requested changes

2022-08-03 13:02 UTC, Aishwarya-U-R commented on app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/Datasources/GraphQL_execution_spec.ts
> +    cy.get(dataSources._graphqlQueryEditor)
datacources.EnterQuery() - can be checked if it works here.. No direct cy statements in ts specs please.

2022-08-03 13:02 UTC, Aishwarya-U-R commented on app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/Datasources/GraphQL_execution_spec.ts
> +    cy.get(dataSources._graphqlPagination.limitVariable).click({
Use     this.agHelper.GetNClick()- here

2022-08-03 13:02 UTC, Aishwarya-U-R commented on app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/Datasources/GraphQL_execution_spec.ts
> +    cy.wait(1000);
Use this.agHelper.Sleep() here

2022-08-03 16:24 UTC, AmanAgarwal041 commented on app/client/cypress/support/Pages/DataSources.ts
> +  public CreateGraphqlDatasource(datasourceName: string) {
Added the function, changed the logic

2022-08-03 16:26 UTC, AmanAgarwal041 commented on app/client/cypress/support/Pages/DataSources.ts
> +    nextCursorValue:
Changed the variable names.

2022-08-03 16:26 UTC, AmanAgarwal041 commented on app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/Datasources/GraphQL_creation_spec.ts
> +import { ObjectsRegistry } from "../../../../support/Objects/Registry";
Done

2022-08-03 16:32 UTC, AmanAgarwal041 commented on app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/Datasources/GraphQL_execution_spec.ts
> +    cy.get(dataSources._graphqlPagination.limitVariable).click({
Moved the logic to `datasources` file. As all the locators were different so did not use `this.agHelper.GetNClick`

2022-08-03 16:32 UTC, AmanAgarwal041 commented on app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/Datasources/GraphQL_execution_spec.ts
> +    cy.wait(1000);
done

2022-08-03 16:38 UTC, Aishwarya-U-R reviewed
Approving cypress tests!

2022-08-04 07:08 UTC, AmanAgarwal041 commented
> Approving cypress tests!

Adding `Test Plan Approved` label

2022-08-04 10:28 UTC, merged