fix: navigation issue in the Iframe widget due to src change
appsmithorg/appsmith pull request #15656
Opened 2022-08-03 09:30 UTC by techbhavin

## Description

> Fixed the navigation issue in the Iframe widget due to the src change.

Fixes #15585 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-08-03 09:32 UTC, techbhavin commented
/ok-to-test sha=d9db302

2022-08-04 11:49 UTC, keyurparalkar requested changes
@techbhavin can we add cypress test cases here

2022-08-04 11:49 UTC, keyurparalkar commented on app/client/src/widgets/IframeWidget/component/index.tsx
> +    if (isFirstSrcDocRender.current) {
Is this the condition that prevents the onSrcDocChange to execute on first render? @techbhavin

2022-08-04 11:49 UTC, keyurparalkar commented on app/client/src/widgets/IframeWidget/component/index.tsx
> +    if (isFirstURLRender.current) {
@techbhavin are we renaming the variable here?

2022-08-04 12:53 UTC, techbhavin commented on app/client/src/widgets/IframeWidget/component/index.tsx
> +    if (isFirstSrcDocRender.current) {
Yes @keyurparalkar

2022-08-05 09:54 UTC, techbhavin commented
/ok-to-test sha=6eb1974

2022-08-05 13:47 UTC, laveena-en commented
Tested and verified.

2022-08-08 13:53 UTC, keyurparalkar approved these changes
LGTM!

2022-08-09 07:55 UTC, techbhavin commented
/ok-to-test sha=6eb1974

2022-08-09 08:51 UTC, techbhavin commented
/ok-to-test sha=6eb1974

2022-08-15 10:57 UTC, techbhavin commented
/ok-to-test sha=4d30499

2022-08-16 03:42 UTC, merged