feat: capture console from across the app
appsmithorg/appsmith pull request #15676
Opened 2022-08-03 11:03 UTC by ayushpahwa

## Description

Added an override function that captures console logs from the functions/ moustache bindings and stores them in the redux store.

Note: have added functionality to remove functions from the objects to prevent issues with passing the data to promise resolutions.

Fixes #14454 

## Type of change

- New feature (non-breaking change which adds functionality)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-08-03 11:06 UTC, ayushpahwa commented
/ok-to-test sha=3def7b4

2022-08-03 11:16 UTC, arunvjn commented on app/client/src/workers/evaluate.ts
> +  logs?: any[];
Can we add types here ?

2022-08-03 11:52 UTC, ayushpahwa commented on app/client/src/workers/evaluate.ts
> +  logs?: any[];
Added comments and types.

2022-08-03 11:55 UTC, arunvjn commented on app/client/src/sagas/EvaluationsSaga.ts
> +      if (requestData.result.logs.length) {
Is requestData.result.logs guaranteed to be defined ?

2022-08-03 12:07 UTC, ayushpahwa commented on app/client/src/sagas/EvaluationsSaga.ts
> +      if (requestData.result.logs.length) {
Oh, that skipped my checks. Great catch. Have added the fix for this. Thanks!

2022-08-10 19:48 UTC, ayushpahwa commented
Changed the base branch to a feature branch so that the rest of the dependent PRs can be shown in a DP.

2022-08-11 07:17 UTC, ApekshaBhosale requested changes

2022-08-11 07:17 UTC, ApekshaBhosale commented on app/client/src/workers/DataTreeEvaluator/index.ts
> +            if ("ENTITY_TYPE" in entity) {
we have functions to indetify types isAction/isJSAction. can we not have a switch statement,. this can we simple statement

2022-08-11 07:17 UTC, ApekshaBhosale commented on app/client/src/workers/UserLog.ts
> +  public flushLogs(): LogObject[] {
can give different name instead of flushLogs. i thought it was emptying the logs

2022-08-11 07:17 UTC, ApekshaBhosale commented on app/client/src/workers/UserLog.ts
> +    const id = uuid4();
why this id is here? can not crate id with info from error?

2022-08-11 07:17 UTC, ApekshaBhosale commented on app/client/src/workers/evaluate.ts
> +      userLogs.resetLogs();
can you add this part of createGlobal data which is called in both sync and async functions? so that you don't have to write each time?

2022-08-11 08:16 UTC, ayushpahwa commented on app/client/src/sagas/EvaluationsSaga.ts
> +  logs?.forEach((evalLog: any) => {
I removed the userlogs from the performance/tracking logs for clear understanding. The evalLog will always be of type any since it's goal is to be printed in the console.

2022-08-11 08:16 UTC, ayushpahwa commented on app/client/src/sagas/EvaluationsSaga.ts
> +    log.debug(evalLog);
This was already added here, it prints performance tracking/analaysis logs like time taken etc.

2022-08-11 08:24 UTC, ayushpahwa commented on app/client/src/workers/DataTreeEvaluator/index.ts
> +            if ("ENTITY_TYPE" in entity) {
Done

2022-08-11 08:24 UTC, ayushpahwa commented on app/client/src/workers/UserLog.ts
> +  public flushLogs(): LogObject[] {
Actually, the function returns all the current logs in the object and clears the internal logs object. I will update the function comment too, but I feel like flush is the right name.

2022-08-11 08:26 UTC, ayushpahwa commented on app/client/src/workers/UserLog.ts
> +    const id = uuid4();
this is the unique ID for each console log that is being stored. Not sure how error info can relate here. For each console log written, we create a unique ID.

2022-08-11 08:29 UTC, ayushpahwa commented on app/client/src/workers/evaluate.ts
> +      userLogs.resetLogs();
Done

2022-08-11 10:41 UTC, ApekshaBhosale commented on app/client/src/workers/UserLog.ts
> +    const id = uuid4();
example: entity+property path can be unique_id right?

2022-08-11 10:43 UTC, ApekshaBhosale approved these changes

2022-08-11 10:57 UTC, merged

2022-08-16 07:46 UTC, ramsaptami commented
- Logs once triggered don't register again on the debugger, i.e. new timeline and/or grouping does not happen
- After observing above scenario, add a new trigger to generate console log and observe that these newly added logs don't appear on the debugger

2022-08-23 07:40 UTC, AnandiKulkarni commented
Issue - Console Logs default filter is not getting updated when moving from JSob1 to JSobj2 


![image.png](https://images.zenhubusercontent.com/62e22001d9217b61b1f9c235/5e66fc76-1deb-48f7-9758-a9c4478a048f)