feat: Extraction of AST Logic
appsmithorg/appsmith pull request #15892
Opened 2022-08-10 10:20 UTC by Irongade

This PR extracts AST Logic into Shared/ast folder

Fixes #15642 

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

Jest

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-08-11 17:01 UTC, Irongade commented
/ok-to-test sha=5425ef7

2022-08-11 17:25 UTC, Irongade commented
/ok-to-test sha=a837095

2022-08-15 05:23 UTC, AmanAgarwal041 approved these changes

2022-08-16 08:08 UTC, AmanAgarwal041 approved these changes

2022-08-16 08:49 UTC, ApekshaBhosale requested changes

2022-08-16 08:49 UTC, ApekshaBhosale commented on app/shared/ast/src/jsObject/index.ts
> +  const ast = parse(jsCode, { ecmaVersion: ECMA_VERSION });
can we use getAST instead of parse directly?

2022-08-16 08:49 UTC, ApekshaBhosale commented on app/shared/ast/src/jsObject/index.ts
> +  isPropertyAFunctionNode,
rather than moving the entire logic to share. can we keep this locally because this is built on top of ast logic? so keep the ast logic in shared but not this.

2022-08-19 12:02 UTC, Irongade reviewed
Kindly review.

2022-08-19 15:59 UTC, Irongade commented
/ok-to-test sha=e16a731

2022-08-19 17:13 UTC, ApekshaBhosale approved these changes

2022-08-22 07:19 UTC, Irongade commented
/ok-to-test sha=c45327d

2022-08-22 08:40 UTC, Irongade commented
/ok-to-test sha=b420d8e

2022-08-23 05:40 UTC, ramsaptami commented
QA on AST DP has been completed

2022-08-23 11:09 UTC, merged