feat: refactor invite modal UI
appsmithorg/appsmith pull request #15957
Opened 2022-08-12 05:37 UTC by ankitakinger

## Description

> Refactored invite modal UI to support suggestions in the input field in case of RBAC.

Fixes #15335 

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

> Tested the functionality still remains the same for invite modal in spite of these changes.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-08-13 09:47 UTC, tanvibhakta commented
Hey Ankita, just before merging this can you please make sure the changes you've made on the components `Button`, `Callout`, 'Dropdown`, and `TabInputComponent` are made on the [design system repository's components](https://github.com/appsmithorg/design-system/tree/release/packages/design-system/src) as well? Sorry about having to duplicate the effort - this is just for the next week or so.

2022-08-16 07:42 UTC, IAmAnubhavSaini requested changes

2022-08-16 07:42 UTC, IAmAnubhavSaini commented on app/client/src/components/ads/TagInputComponent.tsx
> +        : [],
This can be a function, same logic is used in useState above.

2022-08-16 07:42 UTC, IAmAnubhavSaini commented on app/client/src/components/ads/TagInputComponent.tsx
> +        : [],
You should use `?.`.

2022-08-16 07:42 UTC, IAmAnubhavSaini commented on app/client/src/components/ads/TagInputComponent.tsx
> +          suggestions.filter((sugg) => sugg.name?.includes(e.target.value));
`s` would be much better than `sugg`. `s` here would be a typeof `Suggestion`. You should add type info there, if possible.

2022-08-16 07:42 UTC, IAmAnubhavSaini commented on app/client/src/components/ads/TagInputComponent.tsx
> +      (e.target.value.trim() && !showSuggestions && !suggestions.length) ||
`e` is typed `any`, it would make sense to use `?.` here.

2022-08-16 07:42 UTC, IAmAnubhavSaini commented on app/client/src/components/ads/TagInputComponent.tsx
> +    );
This can be simplified to:

```
props?.input?.onChange([props?.input?.value, value].filter(Boolean).join(','));
```

2022-08-16 07:42 UTC, IAmAnubhavSaini commented on app/client/src/components/ads/TagInputComponent.tsx
> +    background: var(--appsmith-color-black-0);
👍 

But there are other places where we are still using `Colors.tsx`. Could you change them?

2022-08-16 07:42 UTC, IAmAnubhavSaini commented on app/client/src/components/ads/TagInputComponent.tsx
> +      )}
I feel like the logic should be split in two.

1. `shouldShowSuggestions`
2. A map of suggestions that is then just rendered.

```
const shouldShowSuggestions = suggestions?.length > 0 && showSuggestions;
const mappedSuggestions = suggestions.map((each: any) => (
              <Suggestion
                key={each.id}
                onClick={() => handleSuggestionClick(each.name)}
              >
                <HighlightText highlight={currentValue} text={each.name} />
              </Suggestion>
            ));
```

Then it basically becomes:

```
{ shouldShowSuggestions && (
    <SuggestionsWrapper>
          <div>{mappedSuggestions}</div>
    </SuggestionsWrapper>
)}
```

This looks cleaner to me. Thoughts?

2022-08-16 07:42 UTC, IAmAnubhavSaini commented on app/client/src/components/ads/TagInputComponent.tsx
>        if (e.target.value.length === 0) {
Ideally, `?.` but a check is being made for `e.target.value` above. Your call.

2022-08-16 07:42 UTC, IAmAnubhavSaini commented on app/client/src/components/ads/TagInputComponent.tsx
> +      }
This is repeated in `if` and `else-if` blocks. Refactor it to move the common code outside.

2022-08-16 07:42 UTC, IAmAnubhavSaini commented on app/client/src/components/ads/Button.tsx
> +      {..._.omit(props, ["fill"])}
You should variabalise it `filteredProps` or something.

2022-08-16 07:43 UTC, ankitakinger commented on app/client/src/components/ads/TagInputComponent.tsx
> +    background: var(--appsmith-color-black-0);
I'll pick that up separately.

2022-08-16 07:45 UTC, RakshaKShetty commented
Following are the use case that we have tested as part of this pr 

1. tag input->Tested
2. callouts->Tested
3. calloutv2->i cant test this because i cant access admin setting
4. Dropdown functionality works fine as before

2022-08-16 10:04 UTC, ankitakinger commented on app/client/src/components/ads/TagInputComponent.tsx
> +      )}
I agree.

2022-08-16 10:26 UTC, IAmAnubhavSaini commented on app/client/src/components/ads/TagInputComponent.tsx
> +      )}
Remove `const shouldShowSuggestions = suggestions?.length > 0 && ` and depend upon only `showSuggestions`.

Then update the mappedSuggestions:

```
const mappedSuggestions = (showSuggestions ? suggestions : []).map...
```

And in render, `showSuggestions &&...`

2022-08-16 12:34 UTC, ankitakinger commented
/ok-to-test sha=41e0acb

2022-08-16 12:52 UTC, IAmAnubhavSaini approved these changes

2022-08-16 18:46 UTC, ankitakinger commented
/ok-to-test sha=41e0acb

2022-08-17 05:30 UTC, merged