fix: dataTree mutation
appsmithorg/appsmith pull request #15952
Opened 2022-08-11 17:46 UTC by Rishabh-Rathod

## Description

In this PR we fix the mutation of dataTree which got enabled by changes [here](https://github.com/appsmithorg/appsmith/pull/11001)

Fixes #14699

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Cypress Test case
- [x] Try mutating Api response data and verify mutation doesn’t work 
- [ ] https://github.com/appsmithorg/TestSmith/issues/2050

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-08-11 18:01 UTC, Rishabh-Rathod commented
/ok-to-test sha=023696e

2022-08-11 20:07 UTC, Rishabh-Rathod commented
/ok-to-test sha=d664954

2022-08-12 06:29 UTC, Rishabh-Rathod reviewed
Add a cypress test case to test mutation doesn’t happen again.

2022-08-12 10:31 UTC, Rishabh-Rathod commented
/ok-to-test sha=0338b07

2022-08-15 06:11 UTC, rohan-arthur commented
tested #15877 - looks good

2022-08-15 10:19 UTC, Rishabh-Rathod commented
/ok-to-test sha=f43226d

2022-08-17 11:40 UTC, Rishabh-Rathod commented
/ok-to-test sha=0d86e77

2022-08-17 12:50 UTC, Rishabh-Rathod commented
/ok-to-test sha=0d86e77

2022-08-18 06:47 UTC, Rishabh-Rathod commented
/ok-to-test sha=0d86e77

2022-08-18 13:21 UTC, ApekshaBhosale requested changes

2022-08-18 13:21 UTC, ApekshaBhosale commented on app/client/src/workers/evaluate.ts
> +  const clonedDataTree = klona(dataTree);
you can club this with createGlobal data btw? it's the same functionality @Rishabh-Rathod

2022-08-18 14:47 UTC, Rishabh-Rathod commented on app/client/src/workers/evaluate.ts
> +  const clonedDataTree = klona(dataTree);
We will be removing `isFunctionAsync` code with [this task ](https://github.com/appsmithorg/appsmith/pull/15092) which i will pick next. 

Does it seem fine to skip refactor for now as we are anyways gonna remove this code?
 
 Let me know what are your thoughts on it.  @ApekshaBhosale

2022-08-19 05:41 UTC, ApekshaBhosale commented on app/client/src/workers/evaluate.ts
> +  const clonedDataTree = klona(dataTree);
sure! let's not refactor for now if we are taking it up immediately @Rishabh-Rathod

2022-08-19 07:22 UTC, Rishabh-Rathod commented on app/client/src/workers/evaluate.ts
> +  const clonedDataTree = klona(dataTree);
@ApekshaBhosale Could you also review the PR as `request changes` blocks the PR until approved by same reviewer.

2022-08-19 11:04 UTC, ApekshaBhosale approved these changes

2022-08-24 16:36 UTC, merged