fix: prevent children rerender in listwidget
appsmithorg/appsmith pull request #16015
Opened 2022-08-15 12:19 UTC by Tooluloope

## Description

Avoid re-rendering the list widget children in the List widget when making Canvas operations

Fixes # (issue)

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-08-15 15:02 UTC, Tooluloope commented on app/client/src/widgets/ListWidget/widget/index.tsx
> +      perPage,
Klona is imported in line 46, we can just go with that

2022-08-15 15:03 UTC, SatishGandham commented on app/client/src/widgets/ListWidget/widget/index.tsx
> +      perPage,
No. Change that import.

2022-08-15 15:20 UTC, Tooluloope commented
/ok-to-test sha=c12e843

2022-08-16 05:59 UTC, SatishGandham requested changes

2022-08-16 05:59 UTC, SatishGandham commented on app/client/src/widgets/ListWidget/widget/index.tsx
> +  deepEqual = (prev: any[], next: any[]) => {
Sorry, I should have said this earlier. It is a comparison function, not a deepEqual.
Rename it to may be compareProps or something better.

2022-08-16 10:40 UTC, Tooluloope commented
/ok-to-test sha=040c3a9

2022-08-16 10:57 UTC, SatishGandham approved these changes
Looks good. Please create an issue for the PR.

2022-08-16 11:12 UTC, somangshu commented
@Tooluloope no issue linked to this, Can you please rectify this

2022-08-17 07:08 UTC, SatishGandham commented
/ok-to-test sha=040c3a9

2022-08-17 16:56 UTC, merged