Feat/setup pseudo canvas widget reducer for evaluation
appsmithorg/appsmith pull request #16021
Opened 2022-08-16 02:30 UTC by Tooluloope

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.

## Description

> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change.

Fixes #15779 

> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-08-25 12:22 UTC, SatishGandham requested changes

2022-08-25 12:22 UTC, SatishGandham commented on app/client/src/actions/metaWidgetActions.ts
> +export const addMetaWidget = (
I think we only need to have updateMetaWidget. Can we clean up the code after checking with @ashit-rath .
Shouldn't this be plural?`updateMetaWidgets`

2022-08-25 12:22 UTC, SatishGandham commented on app/client/src/entities/DataTree/dataTreeFactory.ts
> +  metaCanvasWidgets: MetaCanvasWidgetsReduxState;
How do we treat them differently compared to regular widgets?
Can we combine these with them

2022-08-25 12:22 UTC, SatishGandham commented on app/client/src/entities/DataTree/dataTreeFactory.ts
> +      metaCanvasWidgets: endMetaCanvasWidgets - startMetaCanvasWidgets,
Can you share the results of this?

2022-08-25 12:22 UTC, SatishGandham commented on app/client/src/sagas/selectors.tsx
> +  return state.entities.metaCanvasWidgets;
@ashit-rath Have we considered treating them as regular widgets? Is it possible?

2022-08-25 12:25 UTC, ashit-rath commented on app/client/src/sagas/selectors.tsx
> +  return state.entities.metaCanvasWidgets;
@SatishGandham Do you mean not to introduce the concept of `metaWidgets` and just add to the canvasWidgetsReducer like regular widgets?

2022-08-25 12:28 UTC, SatishGandham commented on app/client/src/sagas/selectors.tsx
> +  return state.entities.metaCanvasWidgets;
We may call them that, and might be needed to exclude from update layout,  but does the worker/evaluations need to know about it?

2022-08-25 12:41 UTC, ashit-rath commented on app/client/src/sagas/selectors.tsx
> +  return state.entities.metaCanvasWidgets;
The main reason to introduce this new reducer was to avoid the mixup in the canvas reducer. 
There are a lot of components that subscribe to this reducer and list widget can add 100s of widgets to the reducer so every subscription has to be carefully done in order to not include the metaWidgets.

Mixing also sort of gives an access to add/remove the canvasWidgets using the apis dynamically, though we can restrict this but all of these extra logic may create problems.

Also the first row item widgets are also meta widgets with the actual widget's widgetName and widgetId. The reason why we do it meta, is to make sure the properties where currentItem is used gets evaluated according to the index. We cannot alter the property values of the actual canvasWidget for the first row item the way we do it for the metaWidgets.

2022-08-26 03:32 UTC, ashit-rath commented
@Tooluloope Can you modify the base branch of this PR to the one that you merged? It would be easier to review if we can see only the changes you made.

2022-08-26 06:55 UTC, ashit-rath commented on app/client/src/widgets/withWidgetProps.tsx
> +        //if (isMetaCanvasWidget) return metaCanvasWidget;
Let's remove this line

2022-08-26 06:57 UTC, ashit-rath approved these changes
LGTM!

2022-08-26 07:00 UTC, ashit-rath commented
@Tooluloope Let's not merge this PR right now.
There are some performance profiling we are doing on the other POCs and until we do that we want to hold off on merging this.

2022-09-01 09:13 UTC, SatishGandham commented on app/client/src/pages/Editor/PropertyPane/PropertyControl.tsx
> +        widgetProperties,
We are changing the value type here. Is this intentional?

2022-09-01 09:52 UTC, ashit-rath commented on app/client/src/pages/Editor/PropertyPane/PropertyControl.tsx
> +        widgetProperties,
@SatishGandham Yes this is intentional, `childWidgetPropertyUpdateEnhancementFn` was always called with the `widgetName` only. This worked for List v1 but in v2 we needed the `widgetId` instead.

So instead of add another argument to the `childWidgetPropertyUpdateEnhancementFn` function, we decided to make the whole props available.

@Tooluloope Have we made sure this works in the List v1?

2022-09-01 10:03 UTC, SatishGandham approved these changes

2022-09-01 11:53 UTC, Tooluloope commented on app/client/src/pages/Editor/PropertyPane/PropertyControl.tsx
> +        widgetProperties,
Yes, this works in V1.
Using `widgetProperties. widgetName` in  List widget's `propertyUpdateHook`

2022-09-01 11:53 UTC, merged