fix: welcome tour ending on page refresh
appsmithorg/appsmith pull request #16079
Opened 2022-08-17 03:18 UTC by akash-codemonk

## Description

> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change.

Fixes #10923

> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-08-17 14:38 UTC, akash-codemonk commented
/ok-to-test sha=ca9f077

2022-08-18 04:52 UTC, akash-codemonk commented
/ok-to-test sha=c606b61

2022-08-22 05:14 UTC, hetunandu requested changes

2022-08-22 05:14 UTC, hetunandu commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Onboarding/GuidedTour_spec.js
> +    cy.reload();
After reload, assert that the guide banner is still showing

2022-08-22 05:14 UTC, hetunandu commented on app/client/src/pages/Editor/GuidedTour/utils.ts
> +export function closeSidebar(dispatch: Dispatch<ReduxAction<any>>) {
We should not pass dispatch as an argument here. Instead you can batch these actions, via redux batch. Returning an array of actions in this function, and dispatching it from outside should work

2022-08-22 05:14 UTC, hetunandu commented on app/client/src/utils/localStorage.tsx
> +type WebStorageType = "local" | "session";
Can we create a new WebStorage or Session storage class instead? Lets not combine these.

2022-08-24 12:16 UTC, akash-codemonk commented
/ok-to-test sha=fd6c6ca

2022-08-25 09:25 UTC, akash-codemonk commented
/ok-to-test sha=62d40d1

2022-08-25 11:00 UTC, akash-codemonk commented on app/client/src/utils/localStorage.tsx
> +type WebStorageType = "local" | "session";
Created two classes LocalStorage and SessionStorage which extends WebStorage as both local and session storage have the same api.

2022-09-01 09:09 UTC, hetunandu approved these changes

2022-09-02 08:08 UTC, akash-codemonk commented
/ok-to-test sha=8567a37

2022-09-02 13:15 UTC, merged