Added Vanuatu Vatu to currency list
appsmithorg/appsmith pull request #16121
Opened 2022-08-18 05:09 UTC by nzidol

## Description

> Added missing currency for Vanuatu

## Type of change

- New feature (non-breaking change which adds functionality)
- Addition to list of constants

2022-08-18 07:52 UTC, Tooluloope requested changes

2022-08-18 07:52 UTC, Tooluloope commented on app/client/src/constants/Currency.tsx
> +  },
```
{
    code: "VU",
    currency: "VUV",
    currency_name: "Vanuatu Vatu",
    label: "Vanuatu",
    phone: "678",
    symbol_native: "VT",
  }
  ```
  
  Hi @nzidol 
  Thanks for making this contribution, Here is the correct detail for Vanuatu

2022-08-19 00:30 UTC, nzidol commented on app/client/src/constants/Currency.tsx
> +  },
updated

2022-08-19 06:30 UTC, Tooluloope approved these changes

2022-08-19 08:09 UTC, Tooluloope commented
/ok-to-test sha=b48a35b

2022-08-22 07:28 UTC, Tooluloope commented
@mohanarpit can you help merge this PR

2022-08-25 11:47 UTC, merged

2022-08-25 11:48 UTC, mohanarpit commented
@nzidol Thank you so much for your contribution towards making Appsmith a better product. 🎉