Poc/listv2 pseudo api
appsmithorg/appsmith pull request #16149
Opened 2022-08-19 06:07 UTC by ashit-rath

## Description

Fixes #15777 

## Type of change
- PoC

## How Has This Been Tested?

- Manual testing

2022-08-19 06:08 UTC, ashit-rath commented on app/client/src/actions/pseudoWidgetActions.ts
> +import { ReduxActionTypes } from "@appsmith/constants/ReduxActionConstants";
We would only keep the `modifyPseudoWidgets` action here and remove the rest

2022-08-19 06:09 UTC, ashit-rath commented on app/client/src/reducers/entityReducers/canvasWidgetsStructureReducer.ts
> -/**
Moved this to a `canvasStructureHelpers.ts` file under utils

2022-08-19 06:11 UTC, ashit-rath commented on app/client/src/widgets/ListWidgetV2/index.ts
> +// TODO: Ashit - Add jest test for all the functions
As we won't be maintaining a `template` property anymore, all the related code would be removed

2022-08-19 06:12 UTC, ashit-rath commented on app/client/src/widgets/ListWidgetV2/index.ts
> +            dynamicPathMap[widgetName] = [
`dynamicPathMap` helps us identifying the properties of the child widget which uses the `currentItem` key as the value so that we can modify it's code in the List widget

2022-08-19 07:52 UTC, SatishGandham commented on app/client/src/widgets/BaseWidget.tsx
> +  modifyPseudoWidgets = (modifications: ModifyPseudoWidgetPayload) => {
What is the difference between update and modify? Is modify a bulk update?
If it is, can we call it that.

2022-08-30 08:50 UTC, ashit-rath commented on app/client/src/reducers/entityReducers/canvasWidgetsStructureReducer.ts
> -/**
Moved to `app/client/src/utils/canvasStructureHelpers.ts`

2022-08-30 09:30 UTC, SatishGandham requested changes

2022-08-30 11:08 UTC, ashit-rath commented on app/client/src/widgets/BaseWidget.tsx
> +  addMetaWidget = (metaWidgets: Record<string, FlattenedWidgetProps>) => {
I might have missed removing them

2022-08-30 11:08 UTC, ashit-rath commented on app/client/src/widgets/withWidgetProps.tsx
> +    const metaCanvasWidget = useSelector(getMetaCanvasWidget(widgetId));
Yes, it's undefined

2022-08-30 11:09 UTC, ashit-rath commented on app/client/src/reducers/entityReducers/metaCanvasWidgetsReducer.ts
> +  [ReduxActionTypes.MODIFY_META_WIDGET]: (
Yes it should be, Changing

2022-08-30 11:13 UTC, ashit-rath commented on app/client/src/reducers/entityReducers/metaCanvasWidgetsReducer.ts
> +    Object.entries(action.payload.addOrUpdate).forEach(
If there are 3 widgets then in total there would be 4 widget per row (4th is the container)
20 Widgets in total and they would be in flat structure like we have `canvasWidgets`
```js
{
  "<metaWidgetId1_row1>": {
     // ...metaWidgetprops
  },
  "<metaWidgetId2_row1>": { 
    // ...metaWidgetprops
  },
  ...
  "<metaWidgetId1_row5>": { 
    // ...metaWidgetprops
  },
  ...
}
```

2022-09-01 05:12 UTC, SatishGandham approved these changes

2022-09-01 05:36 UTC, merged