feat: New settings pane
appsmithorg/appsmith pull request #16361
Opened 2022-08-29 06:29 UTC by eco-monk

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.

## Description

> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change.

Fixes # (issue)

> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-09-02 08:07 UTC, akash-codemonk requested changes

2022-09-02 08:07 UTC, akash-codemonk commented on app/client/src/pages/Editor/AppSettingsPane/PaneHeader.tsx
> +export default connect(null, mapDispatchToProps)(PaneHeader);
nit: do we want to have functional components

2022-09-06 05:47 UTC, eco-monk commented on app/client/src/actions/applicationActions.ts
> +
I thought so too.
Turns out, update application only updates the application data in `userWorkspaces`.
And we have a separate object `currentApplication`, where the current application details are stored and read.

<img width="820" alt="image" src="https://user-images.githubusercontent.com/66776129/188556130-2770e91d-4583-4c75-aded-10d4626d5922.png">

2022-09-06 05:51 UTC, eco-monk commented on app/client/src/actions/applicationActions.ts
> +
There's also `CURRENT_APPLICATION_NAME_UPDATE` action which already exists. But that will trigger a URL_CHANGE.

It was best to create a separate action for this. Because, URL shouldn't be updated when icon changes.

2022-09-06 05:59 UTC, eco-monk commented on app/client/craco.dev.config.js
> +    // plugins: ["babel-plugin-styled-components"],
Yes. This will be reverted before pushing the changes.

2022-09-28 11:01 UTC, eco-monk commented on app/client/src/actions/appSettingsPaneActions.ts
> +};
Initially suspected open settings might need a few more parameters later on.
Right now, it has tab type and pageId as parameters.

So keeping them separate has some utility.

2022-10-08 08:40 UTC, eco-monk commented
/ok-to-test sha=d494ce4

2022-10-13 09:21 UTC, eco-monk commented on app/client/src/pages/Editor/AppSettingsPane/AppSettings/GeneralSettings.tsx
> +      <HeaderText className="leading-[3rem] font-medium">
Hand some trouble using padding. 
That's when I switched to using div's instead.
Created issue #17532.

2022-10-17 06:22 UTC, hetunandu commented on app/client/src/actions/appSettingsPaneActions.ts
> +export const setReopenExplorerOnSettingsCloseAction = (reopen: boolean) => {
This should just be a side effect and not a new action.

2022-10-21 06:48 UTC, ramsaptami commented
- [ ] Update modal should say, `".....new app URL will be.."` not `"current app URL"`
![image](https://user-images.githubusercontent.com/79509062/197130778-03be5c44-2ab0-456e-85b2-ba95cdece168.png)

- [ ] Need more space between error text and fixed content
![image](https://user-images.githubusercontent.com/79509062/197131035-51a38084-04a8-4400-be84-b7095f8278e2.png)

2022-10-26 07:07 UTC, eco-monk commented
@RoopKrrish9696 @kocharrahul7 Most of @ramsaptami's comments will require your input.

> * [ ]  Update modal should say, `".....new app URL will be.."` not `"current app URL"`
> ![image](https://user-images.githubusercontent.com/79509062/197130778-03be5c44-2ab0-456e-85b2-ba95cdece168.png)
We're not creating a new app are we?
We could make it `current app's URL will be become:` instead?

> * [ ]  Need more space between error text and fixed content
>   ![image](https://user-images.githubusercontent.com/79509062/197131035-51a38084-04a8-4400-be84-b7095f8278e2.png)
>   ![image](https://user-images.githubusercontent.com/79509062/197141907-d8aa9170-04bb-4387-abac-c3bb5798d2e1.png)
Agreed, this is being discussed with design system. #17393

> * [ ]  The input box here is disabled here because of the URL not being updated but does not convey this information since cursor turns into edit icon but CTA amounts to nothing. Provide a better feedback when such an action is taking place.
>   ![image](https://user-images.githubusercontent.com/79509062/197133044-5e16d248-25ab-4c4a-bb96-160335bd429e.png)
Agreed, should be fixed by design system #17431.

> * [ ]  Text `"to new readable format to change this*"` does not provide ample information since `this*` does not have a link or a sub text explanation following the astrix
>   ![image](https://user-images.githubusercontent.com/79509062/197133063-426f0e30-0398-42d8-8355-ecfc2b699d9a.png)
`this` means the Change page URL field here, as far as I can tell.
@RoopKrrish9696 can help review this better.

> * [ ]  Add a tooltip here since the purpose of this toggle is unclear
>   ![image](https://user-images.githubusercontent.com/79509062/197134021-f7fd7c42-04f6-4b53-b4ba-d1213efb44d3.png)
@RoopKrrish9696, FYI.

> * [ ]  Incorrect tooltip on a non-home page page. Also, the tooltip needs a rephrase
>   ![image](https://user-images.githubusercontent.com/79509062/197135032-62a3eac7-3fcd-46d0-ba00-ee389613ee82.png)
Tooltip will be hidden appropriately in latest DP.
@kocharrahul7 / @RoopKrrish9696, can you help with rephrasing this?

> * [ ]  Text shows lint error but nothing shows up on hover
>   ![image](https://user-images.githubusercontent.com/79509062/197137773-a3ff5c2b-6a88-42a0-a3f2-72474140373e.png)
We haven't enabled linting on this field. This must be browser's grammar correction.
https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_input_test
Should we consider disabling that? (To be done at design system)

2022-10-26 11:50 UTC, eco-monk commented
/ok-to-test sha=3913db2

2022-10-26 14:21 UTC, eco-monk commented on app/client/src/actions/appSettingsPaneActions.ts
> +export const setReopenExplorerOnSettingsCloseAction = (reopen: boolean) => {
This action has been removed.
Now we're listening to OPEN and CLOSE events in explorerReducer itself.

2022-10-26 14:41 UTC, eco-monk commented
/ok-to-test sha=4b28df6

2022-10-26 23:43 UTC, eco-monk commented
/ok-to-test sha=4b28df6

2022-10-27 06:22 UTC, ramsaptami commented
Function testing issues observed from the video attached
https://www.loom.com/share/964088785a054ee9a026bd857f0229a4
- [ ] Need to improve the copy experience of the URL on page settings
- [ ] Manually copying the URL from the field adds blank space which is incorrect
- [ ] URL signature is incorrect when custom URL is set since it removes the page name

2022-10-27 11:17 UTC, RoopKrrish9696 commented
Thanks for those points @ramsaptami can you suggest what do you think would be the right terminology for the last tooltip?

2022-10-27 12:18 UTC, ramsaptami commented
@roop something on the lines of "Set current page as your homepage by clicking here" or "Toggle this to set the current page as your homepage"

2022-10-28 06:17 UTC, eco-monk commented
/ok-to-test sha=4759d4a

2022-10-29 05:56 UTC, eco-monk commented
/ok-to-test sha=2b6b586

2022-10-31 06:25 UTC, eco-monk commented
/ok-to-test sha=ebbb8fd

2022-10-31 08:15 UTC, eco-monk commented
/ok-to-test sha=698bafb

2022-11-01 04:22 UTC, eco-monk commented
/ok-to-test sha=e0edda2

2022-11-01 12:53 UTC, eco-monk commented
/ok-to-test sha=98f219e

2022-11-02 10:14 UTC, ramsaptami commented
- [ ] Import app naming convention conflicts with page name format so an error shows up by default for an importa
![image](https://user-images.githubusercontent.com/79509062/199463531-770f6015-11af-4c8d-9fb5-5269a7b4c50f.png)

2022-11-03 02:11 UTC, eco-monk commented
/ok-to-test sha=424541c

2022-11-03 12:30 UTC, eco-monk commented
/ok-to-test sha=4ff2b84

2022-11-21 05:07 UTC, eco-monk commented
/ok-to-test sha=2509d90

2022-11-24 11:58 UTC, eco-monk commented
/ok-to-test sha=db904ff

2022-11-27 08:09 UTC, eco-monk commented
/ok-to-test sha=2d62851

2022-11-27 18:13 UTC, eco-monk commented
/ok-to-test sha=c670c31

2022-11-28 03:21 UTC, eco-monk commented
/ok-to-test sha=c670c31

2022-11-28 08:07 UTC, eco-monk commented
/ok-to-test sha=2aea7ca

2022-11-28 12:45 UTC, eco-monk commented
/ok-to-test sha=deee351

2022-11-28 12:54 UTC, eco-monk commented
/ok-to-test sha=13f627e

2022-11-30 03:20 UTC, eco-monk commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/BugTests/Bug9334_Spec.ts
> +    appSettings.openPaneFromCta();
Done

2022-11-30 03:20 UTC, eco-monk commented on app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/Postgres_DataTypes/Array_Spec.ts
> +    appSettings.goToThemeSettings();
Done

2022-11-30 03:21 UTC, eco-monk commented
/ok-to-test sha=8ea2acf

2022-11-30 05:37 UTC, akash-codemonk submitted a review, later dismissed

2022-11-30 05:50 UTC, eco-monk commented
/ok-to-test sha=59ba73b

2022-11-30 06:15 UTC, hetunandu approved these changes

2022-11-30 06:16 UTC, Parthvi12 submitted a review, later dismissed

2022-11-30 06:16 UTC, Parthvi12 commented
Cypress tests LGTM.

2022-11-30 06:24 UTC, eco-monk commented
/ok-to-test sha=821714b

2022-11-30 07:53 UTC, eco-monk commented
/ok-to-test sha=821714b

2022-11-30 14:34 UTC, eco-monk commented
/ok-to-test sha=821714b

2022-12-01 04:36 UTC, eco-monk commented
/ok-to-test sha=511f17b

2022-12-01 15:31 UTC, eco-monk commented
/ok-to-test sha=c9c2bf2

2022-12-01 16:16 UTC, eco-monk commented
/ok-to-test sha=b945b82

2022-12-02 01:49 UTC, eco-monk commented
/ok-to-test sha=19b37db

2022-12-02 05:43 UTC, ramsaptami commented
LGTM, we can go ahead and merge this @eco-monk

2022-12-02 05:48 UTC, akash-codemonk approved these changes

2022-12-02 05:49 UTC, merged