Adding JS Object Events
appsmithorg/appsmith pull request #16472
Opened 2022-09-02 07:07 UTC by satbir121

## Description

Adding mixpanel events for JS Object creation and run.

## Type of change

> Please delete options that are not relevant.

- Chore

## How Has This Been Tested?
Yes

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-09-02 07:10 UTC, ApekshaBhosale submitted a review, later dismissed

2022-09-05 10:40 UTC, ApekshaBhosale requested changes

2022-09-05 10:40 UTC, ApekshaBhosale commented on app/client/src/sagas/JSPaneSagas.ts
> +            AnalyticsUtil.logEvent("JS_OBJECT_FUNCTION_ADDED", {
this is an update of an object and can be added/updated of functions. can we refect that in even name as well please?

2022-09-05 10:45 UTC, ApekshaBhosale requested changes

2022-09-05 10:45 UTC, ApekshaBhosale commented on app/client/src/sagas/JSPaneSagas.ts
> +    num_params: action.actionConfiguration.jsArguments.length,
please add check action.actionConfiguration?.jsArguments?.length because some functions might not have arguments. this might give error

2022-09-05 10:45 UTC, ApekshaBhosale commented on app/client/src/utils/AnalyticsUtil.tsx
> +  | "GUTTER_BUTTON"
can we give event name to specific to JS object? this feels like global, is it?

2022-09-06 07:19 UTC, satbir121 commented on app/client/src/sagas/JSPaneSagas.ts
> +            AnalyticsUtil.logEvent("JS_OBJECT_FUNCTION_ADDED", {
There are different variables for newActions, updatedActions and deletedActions.

2022-09-06 07:52 UTC, ApekshaBhosale submitted a review, later dismissed

2022-09-06 08:02 UTC, ApekshaBhosale approved these changes

2022-09-13 12:51 UTC, sharat87 commented
/ok-to-test sha=86a49c5

2022-09-14 15:34 UTC, merged