feat: merge GraphQL plugin to release
appsmithorg/appsmith pull request #16554
Opened 2022-09-05 23:38 UTC by sumitsum

## Description
- This PR will merge the GraphQL feature branch into `release` branch.
- DP available [here](15.206.27.204) 

Fixes #2284

## Type of change
- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

## How Has This Been Tested?
- JUnit and Cypress test cases
- Maual

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-09-05 23:46 UTC, sumitsum commented
/ok-to-test sha=e945522

2022-09-06 00:09 UTC, sumitsum commented
Adding the `test plan approved` label since we would only run the CI tests on this and no manual testing is supposed to happen since the manual testing has already been done with individual feature PRs. This is as per one of the discussions that was done regarding the same earlier cc: @nidhi-nair @prapullac

2022-09-06 05:32 UTC, nidhi-nair commented on app/client/package.json
> +    "design-system": "npm:@appsmithorg/design-system@0.0.0-beta-20220905091344",
This seems old?

2022-09-06 05:35 UTC, AmanAgarwal041 commented on app/client/package.json
> +    "design-system": "npm:@appsmithorg/design-system@0.0.0-beta-20220905091344",
This was a new version updated by Albin yesterday. I will inform him to upgrade the version.

2022-09-06 05:36 UTC, nidhi-nair commented on app/server/appsmith-plugins/rapidApiPlugin/pom.xml
This might conflict with your other PR @sumitsum

2022-09-06 05:38 UTC, nidhi-nair reviewed
Couple of comments to validate recency of changes.

2022-09-06 06:59 UTC, sumitsum commented on app/server/appsmith-plugins/rapidApiPlugin/pom.xml
@nidhi-nair yes, I will keep the rapid api changes open till this is merged.

2022-09-06 07:00 UTC, sumitsum commented on app/client/package.json
> +    "design-system": "npm:@appsmithorg/design-system@0.0.0-beta-20220905091344",
@AmanAgarwal041 can you please check this ?

2022-09-06 07:23 UTC, sumitsum commented on app/client/package.json
> +    "design-system": "npm:@appsmithorg/design-system@0.0.0-beta-20220905091344",
@AmanAgarwal041 is there something that needs to be done on this PR from our side ?

2022-09-06 07:24 UTC, sumitsum commented
/ok-to-test sha=e945522

2022-09-06 14:06 UTC, sumitsum commented
/ok-to-test sha=fb25daa

2022-09-06 14:08 UTC, sumitsum commented
/ok-to-test sha=fb25daa

2022-09-06 18:31 UTC, AmanAgarwal041 commented on app/client/package.json
> +    "design-system": "npm:@appsmithorg/design-system@0.0.0-beta-20220905091344",
Updated the version.

2022-09-06 18:32 UTC, AmanAgarwal041 commented
/ok-to-test sha=5deccfe

2022-09-07 08:28 UTC, sumitsum commented
/ok-to-test sha=0483612

2022-09-07 08:28 UTC, sumitsum commented on app/client/package.json
> +    "design-system": "npm:@appsmithorg/design-system@0.0.0-beta-20220905091344",
Done.

2022-09-07 08:54 UTC, sumitsum commented
/ok-to-test sha=e3d1d3c

2022-09-07 09:37 UTC, sumitsum commented
/ok-to-test sha=e3d1d3c

2022-09-07 10:53 UTC, sumitsum commented
/ok-to-test sha=e3d1d3c

2022-09-07 18:39 UTC, Aishwarya-U-R commented
/ok-to-test sha=31555ed

2022-09-07 18:52 UTC, albinAppsmith requested changes

2022-09-07 18:52 UTC, albinAppsmith commented on app/client/src/components/ads/Radio.tsx
> +import { CommonComponentProps } from "./common";
Why is this component added again?

2022-09-07 18:58 UTC, sumitsum commented on app/client/src/components/ads/Radio.tsx
> +import { CommonComponentProps } from "./common";
@AmanAgarwal041 can you please check on this with Albin ?

2022-09-09 07:45 UTC, sumitsum commented
/ok-to-test sha=f712166

2022-09-09 08:46 UTC, sumitsum commented
/ok-to-test sha=74de7ed

2022-09-09 08:57 UTC, sumitsum commented on app/client/src/components/ads/Radio.tsx
> +import { CommonComponentProps } from "./common";
@albinAppsmith if this is not a highly impactful change, can we make this change post merge to release ?

2022-09-09 09:36 UTC, AmanAgarwal041 commented
/ok-to-test sha=e2dc666

2022-09-09 09:47 UTC, AmanAgarwal041 commented on app/client/src/components/ads/Radio.tsx
> +import { CommonComponentProps } from "./common";
Removed the above mentioned file

2022-09-09 12:24 UTC, nidhi-nair commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/TriggerUtils.java
> +public class TriggerUtils {
Trigger might be a name that conflicts with the UQI data trigger functionality. Please consider renaming this in the future.

2022-09-09 12:26 UTC, nidhi-nair approved these changes
LGTM, just a comment that can be deferred for later as well.

2022-09-09 12:39 UTC, sumitsum commented
/ok-to-test sha=2e16715

2022-09-09 12:42 UTC, sumitsum commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/TriggerUtils.java
> +public class TriggerUtils {
Created an Github issue to track it: https://github.com/appsmithorg/appsmith/issues/16670. This would be picked up as a separate change.

2022-09-09 14:37 UTC, Irongade approved these changes

2022-09-09 14:37 UTC, Irongade commented on app/client/src/sagas/QueryPaneSagas.ts
> +      actionType: pluginType === PluginType.DB ? "Query" : "API",
Why is this conditional being checked for here? I'm asking because the QueryPaneSagas is for Datasources type of actions and not APIs (which Graphql is more of)

2022-09-09 14:47 UTC, AmanAgarwal041 commented on app/client/package.json
> +    "design-system": "npm:@appsmithorg/design-system@0.0.0-beta-20220905091344",
The version is already updated to `npm:@appsmithorg/design-system@1.0.21` : ref https://github.com/appsmithorg/appsmith/pull/16554/files#diff-b8d2936a034f3ef827722f0cd18b81d5522b816bfe559ce499e8841f2142aeaf

2022-09-09 14:49 UTC, AmanAgarwal041 commented on app/client/src/sagas/QueryPaneSagas.ts
> +      actionType: pluginType === PluginType.DB ? "Query" : "API",
These actions have been merged at one place. Now there is a single function to create any api or query so that it becomes a single source of truth for creation of actions.

2022-09-09 15:59 UTC, merged