feat: added WIDGET_DRAG event.
appsmithorg/appsmith pull request #16591
Opened 2022-09-06 13:16 UTC by yaldram

## Description

- Added a `WIDGET_DRAG` event, when the user finishes moving the widget on the canvas and places it.

Fixes #15345

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Not tested, might need to test it either on release or production

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-09-06 13:26 UTC, yaldram commented
When we move a widget, we have the following scenarios - 
- We can move a single widget.
- We can move multiple widgets.
- We can move the widget / widgets on the canvas or inside a container.

Therefore, in the analytics event we have the following information: - 
1. widgets - array field with `widget.type` & `widget.widgetName`.
2. multiple - boolean field to indicate if we are moving a single widget or multiple widgets.
3. mainCanvas - boolean field to indicate if we are moving the widgets on the canvas or inside a container widget.

2022-09-07 05:08 UTC, vuiets commented
Hey great coverage for the event here guys 👏 Thanks for the detailed write up too.

Instead of `mainCanvas` can we add a property to look at the source and destination of the dragged widget? Look for different terms instead of `source` though since its a meta property that exists to tell which widget was dragged, let this remain as is as multiple widget-related events use this convention.

2022-09-07 06:57 UTC, rahulramesha commented
@vuiets by source and destinations do you mean the source canvas to destination canvas, eg, from mainCanvas to Container widget?

2022-09-07 06:59 UTC, yaldram commented
I was thinking instead of the `mainCanvas` as a boolean field can we have a filed called containerWidget which will have the name of the container widget. 
 Also, I don't think source and destination might help us, like during form alignment or widget alignment my co-ordinates don't change drastically.

2022-09-08 14:10 UTC, rahulramesha requested changes

2022-09-08 14:10 UTC, rahulramesha commented on app/client/src/sagas/CanvasSagas/DraggingCanvasSagas.ts
> +        const parentWidget = allWidgets[parentId].widgetName;
@yaldram Instead of widgetName, it would be better if we log widgetType, to better understand which types of widget are the parents.
Also to point out, parent Widget of all widgets will always be a CANVAS_WIDGET. The ParentWidget's parent will give you the actual Type of widget (Except for MainCanvas)

Changes required,
1. Check if Parent Widget is main Canvas, if not log the Parent's ParentWidget Type. for both source and destination.
2. If one of them is main Canvas, their type is also CANVAS_WIDGET, instead log it as MAIN_CONTAINER
3. instead of mainCanvas parameter as boolean, it would be better to log a boolean to indicate if source and destination parentId are same.

cc: @vuiets

2022-09-12 08:02 UTC, vuiets commented on app/client/src/sagas/CanvasSagas/DraggingCanvasSagas.ts
> +        const parentWidget = allWidgets[parentId].widgetName;
Are you looking for any input from me here?

2022-09-12 09:56 UTC, rahulramesha commented on app/client/src/sagas/CanvasSagas/DraggingCanvasSagas.ts
> +        const parentWidget = allWidgets[parentId].widgetName;
@vuiets just wanted to keep you in loop for the logs Arsalan will be adding

2022-09-13 06:46 UTC, vuiets commented on app/client/src/sagas/CanvasSagas/DraggingCanvasSagas.ts
> +        const parentWidget = allWidgets[parentId].widgetName;
Got it, thanks @rahulramesha!

2022-09-13 07:11 UTC, rahulramesha approved these changes

2022-09-17 05:13 UTC, yaldram commented
/ok-to-test sha=c53ab95

2022-09-17 06:51 UTC, merged