feat: Add a service layer to get AppsmithType from client-type (#16508)
appsmithorg/appsmith pull request #16619
Opened 2022-09-07 12:31 UTC by subrata71

This PR takes care of the following things
- It creates a service layer to get the target AppsmithType from the client-side data type and the evaluated value
- This service layer is currently not consumed by any plugins
- A full JUnit test suit for MySQL specific data types

## Description

Fixes #16508 

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- JUnit

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-09-07 12:32 UTC, subrata71 commented
/ok-to-test sha=708c987

2022-09-07 20:04 UTC, subrata71 commented
/ok-to-test sha=2d97675

2022-09-08 10:39 UTC, nidhi-nair commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/services/ce/DataTypeServiceCEImpl.java
> +           new FloatType(),
Weren't we going to skip floats?

2022-09-08 10:40 UTC, nidhi-nair commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/services/ce/DataTypeServiceCEImpl.java
> +    public DataTypeServiceCEImpl() {
How would plugins use their types in this service?

2022-09-08 10:44 UTC, subrata71 commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/services/ce/DataTypeServiceCEImpl.java
> +           new FloatType(),
Yes, yes. Sorry, I didn't get any definitive guideline for that. Thought you are not 100% convinced. :-| 
Anyway, will update the PR by removing the `FloatType`.

2022-09-08 10:48 UTC, subrata71 commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/services/ce/DataTypeServiceCEImpl.java
> +    public DataTypeServiceCEImpl() {
Plugins can pass their types by invoking the following function:

`AppsmithType appsmithType = DataTypeStringUtils.stringToKnownAppsmithTypeConverter(clientDataType, value, pluginSpecificTypes);`

Where plugin will define its supported data types in the respective plugin class this way

```
private static Map<ClientDataType, List<AppsmithType>> pluginSpecificTypes;

    static {
        pluginSpecificTypes = new HashMap<>();
        pluginSpecificTypes.put(ClientDataType.NULL, List.of(new NullType()));

        pluginSpecificTypes.put(ClientDataType.BOOLEAN, List.of(new MySQLBooleanType()));

        pluginSpecificTypes.put(ClientDataType.NUMBER, List.of(
                new IntegerType(),
                new LongType(),
                new DoubleType(),
                new BigDecimalType()
        ));

        pluginSpecificTypes.put(ClientDataType.OBJECT, List.of(
                new JsonObjectType(),
                new StringType()
        ));

        pluginSpecificTypes.put(ClientDataType.STRING, List.of(
                new TimeType(),
                new MySQLDateType(),
                new MySQLDateTimeType(),
                new StringType()
        ));
```

2022-09-10 18:12 UTC, subrata71 commented
/ok-to-test sha=140dcda

2022-09-11 07:40 UTC, subrata71 commented
/ok-to-test sha=7b1d726

2022-09-12 15:04 UTC, subrata71 commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/services/ce/DataTypeServiceCEImpl.java
> +           new FloatType(),
Removed FloatType and updated the PR.

2022-09-14 05:11 UTC, subrata71 commented
/ok-to-test sha=6a350a7

2022-09-14 12:21 UTC, nidhi-nair requested changes
@subrata71 sorry again for taking time on this PR review. :)

2022-09-14 12:21 UTC, nidhi-nair commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/DataTypeStringUtils.java
> +    public static AppsmithType stringToKnownAppsmithTypeConverter(ClientDataType clientDataType, String value, Object... args) {
Can we avoid creating an intermediate method like this one? Let's isolate this functionality to just the `DataTypeService` instead?

2022-09-14 12:21 UTC, nidhi-nair commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/DataTypeStringUtils.java
> +    public static AppsmithType stringToKnownAppsmithTypeConverter(ClientDataType clientDataType, String value, Object... args) {
Also, could you please share your reasoning as to the choice of variable argument `args` instead of a specific one?

2022-09-14 12:21 UTC, nidhi-nair commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/services/ce/DataTypeServiceCEImpl.java
> +        return null;
Shall we default to String here as the base type, just so we always have a backup expectation and avoid NPEs?

2022-09-14 12:21 UTC, nidhi-nair commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/services/DataTypeServiceImpl.java
> +    public static synchronized DataTypeServiceImpl getInstance() {
I'm a little iffy about having all our integration services be singletons. What do you think about extending the Spring context to our other modules?

2022-09-14 12:21 UTC, nidhi-nair commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/services/ce/DataTypeServiceCEImpl.java
> +     final Map<ClientDataType, List<AppsmithType>> defaultAppsmithTypes = new HashMap<>();
Could you please add a comment here explaining the structure of this map to a consumer of the datatype service?

2022-09-14 12:21 UTC, nidhi-nair commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/services/ce/DataTypeServiceCEImpl.java
> +     final Map<ClientDataType, List<AppsmithType>> defaultAppsmithTypes = new HashMap<>();
Could you please add a comment here explaining the structure of this map to a consumer of the datatype service?

2022-09-14 12:22 UTC, nidhi-nair commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/services/ce/DataTypeServiceCEImpl.java
> +        return null;
We could create another data type to server this purpose as well. One which would always test to true, and does no transformation.

2022-09-14 16:16 UTC, subrata71 commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/services/DataTypeServiceImpl.java
> +    public static synchronized DataTypeServiceImpl getInstance() {
We can avoid singleton behavior for a class like DataTypeService. This fits well as a util class. @nidhi-nair

2022-09-14 18:58 UTC, subrata71 commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/DataTypeStringUtils.java
> +    public static AppsmithType stringToKnownAppsmithTypeConverter(ClientDataType clientDataType, String value, Object... args) {
If the DataTypeService is written as a util class then we don't need to use DataTypeStringUtils class anymore. What do you think?

2022-09-14 18:59 UTC, subrata71 commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/services/ce/DataTypeServiceCEImpl.java
> +     final Map<ClientDataType, List<AppsmithType>> defaultAppsmithTypes = new HashMap<>();
I will add a comment on this method but let's decide first whether we should implement this as a util class or not.

2022-09-14 19:03 UTC, subrata71 commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/services/ce/DataTypeServiceCEImpl.java
> +        return null;
I kept StringType as the fallback data type for the Object type. Do you think it should also be the fallback data type for the rest of the data types? If so, then we can do like this

```
@Override
public AppsmithType getAppsmithType(ClientDataType clientDataType, String value, Map<ClientDataType, List<AppsmithType>> pluginSpecificTypes) {
        for (AppsmithType currentType : pluginSpecificTypes.get(clientDataType)) {
            if (currentType.test(value)) {
                return currentType;
            }
        }
        //Send StringType as the fallback data type
        return new StringType();
}
```

2022-09-15 02:33 UTC, nidhi-nair commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/DataTypeStringUtils.java
> +    public static AppsmithType stringToKnownAppsmithTypeConverter(ClientDataType clientDataType, String value, Object... args) {
Hmm ... it does look like we'll only ever have stateless utilities here. Plus there's a low chance of needing to depend on another service. I think we can do what you suggest here. :)

2022-09-15 02:43 UTC, nidhi-nair commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/services/ce/DataTypeServiceCEImpl.java
> +        return null;
Could you please give an example of when converting something identified as an object by JavaScript will be useful to convert into a string?

I suggested a separate type so that we're able to distinguish between data that has been genuinely identified as a string, and data that seems to be in error state but we want to treat as a string. That way if any plugin wants to handle the error scenario differently, they'll be able to.

2022-09-15 05:14 UTC, subrata71 commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/services/ce/DataTypeServiceCEImpl.java
> +        return null;
I don't have a very good example but let's consider this

The type of new Date() in javascript is of object type. And for object type the respective Appsmith type is JsonObjectType but it's not a valid JSON, right? 
In that case if the fallback datatype were StringType then it could take over.

Does it make any sense to you? @nidhi-nair 

That's a nice idea to keep a separate fallback data type for the case you mentioned. I am going to name it "FallbackDataType"

2022-09-15 05:18 UTC, nidhi-nair commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/services/DataTypeServiceImpl.java
> +    public static synchronized DataTypeServiceImpl getInstance() {
We seem to be talking about the same thing in two different [threads](https://github.com/appsmithorg/appsmith/pull/16619#discussion_r971465406). :P

Yes, let's go ahead with a utility class.

2022-09-15 10:31 UTC, subrata71 commented
/ok-to-test sha=607f214

2022-09-15 11:04 UTC, nidhi-nair commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/DataTypeService.java
> +public class DataTypeService {
Nit: Let's call this Utils for consistent guidelines?

2022-09-15 11:16 UTC, subrata71 commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/DataTypeService.java
> +public class DataTypeService {
Done. @nidhi-nair

2022-09-15 11:17 UTC, subrata71 commented
/ok-to-test sha=58d6f3c

2022-09-15 13:32 UTC, nidhi-nair approved these changes

2022-09-15 17:07 UTC, subrata71 commented
/ok-to-test sha=4fe79c8

2022-09-16 05:56 UTC, subrata71 commented
/ok-to-test sha=cadc4c4

2022-09-16 11:40 UTC, merged