Feature: Informative error messages on cyclic dependency for queries on page load
appsmithorg/appsmith pull request #16634
Opened 2022-09-08 06:31 UTC by sondermanish

## Description

> This commit addresses [16154](https://github.com/appsmithorg/appsmith/issues/16154) and changes the files mentioned below:

Layout.java  
ActionCollectionDTO.java
ActionDTO.java
LayoutDTO.java
LayoutActionServiceCEImpl.java
LayoutCollectionServiceCEImpl.java
LayoutActionServiceTest.java 

## Type of change

> New feature: The user will now see the toast and debug messages when the user will encounter/ generate cyclic dependency on below mentioned flows.

- Changing JS object: Receiving <ActionCollectionDTO> Endpoint: api/v1/collections/actions/{id}
- Refactoring JSObject:  Response <LayoutDTO> Endpoint: api/v1/collections/actions/refactor
- Changing DSL name: Response <LayoutDTO> Endpoint: api/v1/layouts/refactor
- Changing DSL attribute: Response <LayoutDTO> Endpoint: api/v1/{layoutId}/pages/{pageId}
- Reloading page: Response<NewPage> Endpoint: api/v1/pages/{pageId}
- Changing db query: Response <ActionDTO> Endpoint: api/v1/actions/{actionId} 

## How Has This Been Tested?

The backend changes has been tested:
- Junit test cases
- Manually

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-09-15 08:37 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/domains/Layout.java
> +    List<Map<String,Object>> layoutOnLoadActionErrors;
Can you please check if we an use `ErrorDTO` class (`ErrorDTO.java`) instead of a `Map` object ? If it is possible to do so (even with small modifications) then could we replace (everywhere) the `Map` object with the `ErrorDTO` object ? Reason being that a `Map` object is usually useful where a fixed format of data is not available or if the format of data keeps changing frequently. However, if the data format is fixed the we should try to formalize that contract via a well defined Object.

2022-09-15 08:37 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/domains/Layout.java
> +    List<Map<String,Object>> layoutOnLoadActionErrors;
Can you please annotate all the `error` related variables that are newly defined in this PR with `@JsonProperty(access = JsonProperty.Access.READ_ONLY)` - this should ensure that the variable cannot be set by the client but will only be set by the server.

2022-09-15 08:37 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/ActionCollectionDTO.java
> +    List<Map<String, Object>> errorReports;
Can you please check if any `errorReports` variable is defined in a Class that gets persisted on the DB ? If so, then please annotate that variable with `@Transient` - this will make sure that we don't persist the errors in the DB and only one the page layout object persists it.

2022-09-15 08:37 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/LayoutActionServiceCEImpl.java
> +        layoutDTO.setLayoutOnLoadActionErrors(layout.getLayoutOnLoadActionErrors());
Can you please move all these `set` calls into a separate method say `setLayoutDTO` ?

2022-09-15 08:37 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/LayoutActionServiceCEImpl.java
> +    private final String layoutOnLoadActionErrorToastMessage = "A Cyclic dependency has been encountered on current page, \nqueries on Page load will not run. \nCheck debugger for more information";
Can you please update the message to mention documentation as well - `... Check debugger and Appsmith documentation for more information` ?

2022-09-15 08:37 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/LayoutCollectionServiceCEImpl.java
> +                .zipWith(newPageMono,
Can you please replace `newPageMono` with `newPageService.findById(pageId, MANAGE_PAGES)` ?

2022-09-15 08:37 UTC, sumitsum commented on app/server/appsmith-server/src/test/java/com/appsmith/server/services/LayoutActionServiceTest.java
> +        ActionDTO createdAction = layoutActionService.createSingleAction(actionDTO).block();
Can you please move all the `actionDTO` related lines (1562 - 1569) to just above this ? This would ensure that usage is closer to definition of a variable - which should improve the code readability.

2022-09-15 15:46 UTC, sondermanish commented on app/server/appsmith-server/src/main/java/com/appsmith/server/domains/Layout.java
> +    List<Map<String,Object>> layoutOnLoadActionErrors;
Made changes as suggested.

2022-09-15 15:47 UTC, sondermanish commented on app/server/appsmith-server/src/main/java/com/appsmith/server/domains/Layout.java
> +    List<Map<String,Object>> layoutOnLoadActionErrors;
made changes as suggested

2022-09-15 15:47 UTC, sondermanish commented on app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/ActionCollectionDTO.java
> +    List<Map<String, Object>> errorReports;
Checked and added the `@Transient` property, wherever applicable.

2022-09-15 15:48 UTC, sondermanish commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/LayoutActionServiceCEImpl.java
> +    private final String layoutOnLoadActionErrorToastMessage = "A Cyclic dependency has been encountered on current page, \nqueries on Page load will not run. \nCheck debugger for more information";
Augmented the message as mentioned.

2022-09-15 15:50 UTC, sondermanish commented on app/server/appsmith-server/src/test/java/com/appsmith/server/services/LayoutActionServiceTest.java
> +        ActionDTO createdAction = layoutActionService.createSingleAction(actionDTO).block();
Shifted the Code block for better readability.

2022-09-15 15:50 UTC, sondermanish commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/LayoutCollectionServiceCEImpl.java
> +                .zipWith(newPageMono,
Changed as suggested.

2022-09-16 10:50 UTC, Aishwarya-U-R commented on app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/OnLoadTests/JSOnLoad_cyclic_dependency_errors_spec.js
> +    cy.wait(3000);
We are already in Explorer tab view & this seems repetition.

2022-09-16 10:50 UTC, Aishwarya-U-R commented on app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/OnLoadTests/JSOnLoad_cyclic_dependency_errors_spec.js
> +    ee.SelectEntityByName(entityName);
Remove ExpandCollapseEntity. Instead `ee.SelectEntityByName(entityName, "Widgets);` will automatically Expand & Select the widget!

2022-09-16 10:50 UTC, Aishwarya-U-R commented on app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/OnLoadTests/JSOnLoad_cyclic_dependency_errors_spec.js
> +    ee.SelectEntityByName(entityName);
In this case - line 145 to 147 can also be removed. Since '`SelectEntityByName`' will do it.

2022-09-16 17:40 UTC, sumitsum submitted a review, later dismissed

2022-09-19 06:14 UTC, sondermanish commented on app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/OnLoadTests/JSOnLoad_cyclic_dependency_errors_spec.js
> +    ee.SelectEntityByName(entityName);
@Aishwarya-U-R  this test case fails when we remove the `line number 148`. From `line 145 to 148` gets the view to the entity explorer page, without that the `selectEntityByName` fails.

2022-09-19 08:25 UTC, sondermanish commented on app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/OnLoadTests/JSOnLoad_cyclic_dependency_errors_spec.js
> +    cy.wait(3000);
Made changes as suggested

2022-09-19 08:25 UTC, sondermanish commented on app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/OnLoadTests/JSOnLoad_cyclic_dependency_errors_spec.js
> +    ee.SelectEntityByName(entityName);
Made changes as suggested.

2022-09-19 12:47 UTC, sneha122 commented
/ok-to-test sha=562dcff

2022-09-21 10:27 UTC, ayushpahwa requested changes

2022-09-21 10:27 UTC, ayushpahwa commented on app/client/src/sagas/ActionExecution/PluginActionSaga.ts
> +    const actionCount = _.flatten(pageActions).length;
For performance improvement, Instead of importing the whole lodash lib, it's better to just import the function you need here.

2022-09-21 10:27 UTC, ayushpahwa commented on app/client/src/sagas/ActionExecution/PluginActionSaga.ts
> +      PerformanceTracker.startAsyncTracking(
Please add a comment for this block.

2022-09-21 10:27 UTC, ayushpahwa commented on app/client/src/sagas/ActionSagas.ts
> +      if (
I think it's better to just extract the `errorReports` variable once from `response.data`

2022-09-21 10:27 UTC, ayushpahwa commented on app/client/src/sagas/ActionSagas.ts
> +      if (
Or since we are doing the if conditions repeatedly, we can just include `logCyclicDependecyErrors` function inside the `checkIfNoCyclicDependencyErrors`. Will be cleaner.

2022-09-21 10:27 UTC, ayushpahwa commented on app/client/src/sagas/helper.ts
> +    for (let index = 0; index < layoutErrors.length; index++) {
Instead of calling `addError` on loop, we can just call it once for all the logs.

2022-09-21 14:23 UTC, sneha122 commented on app/client/src/sagas/ActionExecution/PluginActionSaga.ts
> +    const actionCount = _.flatten(pageActions).length;
Made suggested changes

2022-09-21 14:50 UTC, sneha122 commented on app/client/src/sagas/helper.ts
> +    for (let index = 0; index < layoutErrors.length; index++) {
Made suggested changes

2022-09-21 15:20 UTC, sneha122 commented on app/client/src/sagas/ActionExecution/PluginActionSaga.ts
> +      PerformanceTracker.startAsyncTracking(
Made suggested changes

2022-09-22 05:25 UTC, sneha122 commented
/ok-to-test sha=843a303

2022-09-22 05:50 UTC, ayushpahwa approved these changes
LGTM

2022-09-22 07:59 UTC, sondermanish commented
/ok-to-test sha=15cb6bd

2022-09-22 15:32 UTC, sondermanish commented
/ok-to-test sha=02b5bc8

2022-09-23 14:24 UTC, sondermanish commented
/ok-to-test sha=9fd0505

2022-09-23 14:34 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/LayoutActionServiceCEImpl.java
> +    private final String layoutOnLoadActionErrorToastMessage = "A cyclic dependency error has been encountered on current page, \nqueries on page load will not run. \n Please check debugger and appsm
Minor: please capitalize `a` in `appsmith`.

2022-09-23 14:40 UTC, sondermanish commented
/ok-to-test sha=7d9733f

2022-09-23 14:43 UTC, sumitsum approved these changes

2022-09-24 10:01 UTC, merged