Show api datasource list on focus
appsmithorg/appsmith pull request #1668
Opened 2020-11-10 07:35 UTC by akash-codemonk

Fixes #1663

2020-11-17 05:19 UTC, hetunandu requested changes

2020-11-17 05:19 UTC, hetunandu commented on app/client/src/components/editorComponents/CodeEditor/styledComponents.ts
> +    max-width: 350px;
Instead of changing styles over here, we need to find a way to override it from the `EmbeddedDatasourcePathComponent`

2020-11-17 05:19 UTC, hetunandu commented on app/client/src/components/editorComponents/form/fields/EmbeddedDatasourcePathField.tsx
> +  };
Let us find a better way to handle this.

2020-11-17 10:49 UTC, akash-codemonk commented on app/client/src/components/editorComponents/form/fields/EmbeddedDatasourcePathField.tsx
> +  };
We could call `handleAutocompleteVisibility` in `handleEditorFocus` of the CodeEditor component. `!instance.state.completionActive` check would still be required otherwise picking a hint turns out to have no effect.

2020-11-19 05:11 UTC, akash-codemonk commented on app/client/src/components/editorComponents/form/fields/EmbeddedDatasourcePathField.tsx
> +  };
Instead of showHint added an extra method `trigger` which gets called in `onFocusTrigger` and `onChangeTrigger` in the codeeditor.

2020-11-19 05:15 UTC, akash-codemonk commented on app/client/src/components/editorComponents/CodeEditor/styledComponents.ts
> +    max-width: 350px;
Passing extraStyles to `HintStyles` will modify the hint ui for the bindings(for EmbeddedDatasourcePathComponent) as well. 
So instead of adding a width to CodeMirror-Hints I added it to each list item(CodeMirror-hint). This class can be extended by passing a `className` to `showHint`. This will help in modifying only for the datasource hints.

2020-11-19 11:40 UTC, hetunandu approved these changes

2020-11-19 11:41 UTC, merged