fix: Extra Space at the end of the Canvas in Viewmode
appsmithorg/appsmith pull request #16747
Opened 2022-09-14 08:01 UTC by rahulramesha

## Description

We had logic to fix MainCanvas height when a Widget is dragged, resized or deleted. Extending that logic to When a widget is added to mainCanvas as well.

Also added logic to trim mainCanvas width in View Mode.

Fixes #12672 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Manual UI and Jest test

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-09-19 07:07 UTC, riodeuno reviewed
Just one comment, the rest looks good.

2022-09-19 07:07 UTC, riodeuno commented on app/client/src/constants/WidgetConstants.tsx
> +  MAIN_CANVAS_EXTENSION_OFFSET: 8,
@rahulramesha What's the rationale? Can't we use the `CANVAS_EXTENSION_OFFSET` here?

2022-09-19 07:08 UTC, marks0351 requested changes

2022-09-19 07:08 UTC, marks0351 commented on app/client/src/components/editorComponents/DropTargetUtils.ts
> +  const canvasOffset =
@rahulramesha  why a different offset for main canvas, if it is to decrease annoyance then its fine but i see the offset being applied in view mode as well which creates a scroll when a page is created exactly for the view port height.

2022-09-19 07:18 UTC, rahulramesha commented on app/client/src/components/editorComponents/DropTargetUtils.ts
> +  const canvasOffset =
@riodeuno @marks0351 The main rationale for `MAIN_CANVAS_EXTENSION_OFFSET` was that, `CANVAS_EXTENSION_OFFSET` is too small for mainCanvas. On edit mode, if the same `CANVAS_EXTENSION_OFFSET` is used, it looks as if the canvas grids abruptly ends at the last widget position and doesn't looks good while dragging. On View mode, it acts as a padding below the last widget, so that the bottom most widgets are easily accessible to interact rather than at the border of the browser, It does have a bit of scroll only if canvas goes beyond a certain length but not by much.

2022-09-19 07:25 UTC, marks0351 commented on app/client/src/components/editorComponents/DropTargetUtils.ts
> +  const canvasOffset =
why do we need this padding in view mode? did we have any feedback regarding usability? It's better if we do this only out of necessity else just skip and have the height equal to the bottom most widgets bottom row.

2022-09-19 07:49 UTC, rahulramesha commented on app/client/src/components/editorComponents/DropTargetUtils.ts
> +  const canvasOffset =
@marks0351 This is the one i was mentioning, you could check the below image, with regular canvas offset (on release). It makes the button non interactive
<img width="1324" alt="image" src="https://user-images.githubusercontent.com/71900764/190971735-c0c20a04-05ea-4eb7-9a10-6902175c7ff1.png">
Same app on this DP,
<img width="1300" alt="image" src="https://user-images.githubusercontent.com/71900764/190972006-979b18b8-61d0-4bd7-a840-1a2b5a29cb76.png">

2022-09-19 09:06 UTC, marks0351 commented on app/client/src/components/editorComponents/DropTargetUtils.ts
> +  const canvasOffset =
yea it makes sense to implement this to accommodate this particular area of the canvas but in ee apps i think we have the provision to  hide the appsmith label and there it might be an unwanted feature and i dont recommend having a flag to deal with that. if we are going to fix this lets fix it as a feature by giving the ability to the user to set their bottom row. what do you guys think?

2022-09-20 07:13 UTC, rahulramesha commented on app/client/src/components/editorComponents/DropTargetUtils.ts
> +  const canvasOffset =
Providing the feature to set their bottom row which is intuitive to the user might require designs and UX. We can pursue that approach as well but since this works for more cases and solves the long canvas issue, I think the extra 8 rows wont make a difference since most websites have a padding at the bottom.  thoughts?

2022-09-20 19:25 UTC, rahulramesha commented
/ok-to-test sha=27c3c42

2022-09-20 19:30 UTC, riodeuno submitted a review, later dismissed

2022-09-21 14:47 UTC, rahulramesha commented
/ok-to-test sha=319e76c

2022-09-23 05:05 UTC, marks0351 submitted a review, later dismissed

2022-09-25 12:54 UTC, rahulramesha commented
/ok-to-test sha=a27e1b2

2022-09-27 02:21 UTC, riodeuno commented on app/client/src/sagas/WidgetOperationUtils.ts
> +export function resizeCanvasToLowestWidget(
@rahulramesha I am concerned that this is a mutating function. Do you think we could return a value from this? There are two concerns I have.
1. It makes testing easier, no need for cloning.
2. This function only changes one value. It should be fairly simple to add a line and update these in the `finalWidgets` where necessary.

2022-09-27 02:23 UTC, riodeuno commented on app/client/src/sagas/WidgetOperationUtils.ts
> +  finalWidgets[parentId].bottomRow = Math.max(
Should this be Math.min instead?

2022-09-27 02:24 UTC, riodeuno reviewed
A few comments. Overall looks good to me.

2022-09-27 02:25 UTC, riodeuno commented on app/client/src/constants/WidgetConstants.tsx
> +  MAIN_CANVAS_EXTENSION_OFFSET: 8,
@rahulramesha I thought we were changing this to 5. Have we reconsidered?

2022-09-27 07:48 UTC, rahulramesha commented on app/client/src/sagas/WidgetOperationUtils.ts
> +export function resizeCanvasToLowestWidget(
@riodeuno got it, I had just moved the method from another file. I agree with the points will change it to return the value instead of mutating it

2022-09-27 07:50 UTC, rahulramesha commented on app/client/src/sagas/WidgetOperationUtils.ts
> +  finalWidgets[parentId].bottomRow = Math.max(
It is supposed to be Math.max, because it is comparing the maximum value of the lowest bottom row of the widget or the bottom row that is required to fill the entire height of the browser window.

2022-09-27 17:36 UTC, rahulramesha commented
/ok-to-test sha=2cb25ba

2022-09-28 11:07 UTC, riodeuno approved these changes

2022-09-29 10:51 UTC, rahulramesha commented
/ok-to-test sha=f829617

2022-09-30 08:19 UTC, merged