Store tabs name data as array instead of string
appsmithorg/appsmith pull request #1676
Opened 2020-11-10 10:25 UTC by hetunandu

2020-11-11 11:30 UTC, riodeuno reviewed
`WidgetOperationSagas` and `TabsWidget` files also have the `JSON.stringify(tabs)`. Please verify if they need to be updated.

2020-11-17 11:30 UTC, riodeuno requested changes

2020-11-17 11:30 UTC, riodeuno commented on app/client/src/sagas/WidgetOperationSagas.tsx
> -              tabs.push({
Removing this piece of code will not allow users to undo the delete of a tab in a tabs widget.
I suggest we keep `tabs.push` logic intact, to keep the undo delete feature intact.

2020-11-17 11:30 UTC, riodeuno commented on app/client/src/sagas/WidgetOperationSagas.tsx
> -          if (Array.isArray(tabs)) {
Removing this piece of code will copy the widgetIds of the individual tabs as well. This will result in duplicates when pasting a widget in the new or original tabs, as there will be two widgets with the same widgetId as the child widget.

I would suggest we keep lines 957 - 962 sans the `JSON.stringify`

2020-11-17 11:30 UTC, riodeuno commented on app/client/src/components/propertyControls/TabControl.tsx
> +  migrateTabData(
Could you explain the motivation behind having a migration here instead of the WidgetPropsUtils's DSL migration flow?

2020-11-23 06:18 UTC, hetunandu commented on app/client/src/components/propertyControls/TabControl.tsx
> +  migrateTabData(
It follows the stuff we did for chart widget which had a similar change.

2020-11-30 08:50 UTC, riodeuno approved these changes

2020-12-02 12:53 UTC, merged