fix: hint overlap
appsmithorg/appsmith pull request #16769
Opened 2022-09-14 21:39 UTC by Rishabh-Rathod

## Description

Fixes # (issue)

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-09-14 21:42 UTC, Rishabh-Rathod commented
/ok-to-test sha=c9a4182

2022-09-15 08:51 UTC, Rishabh-Rathod reviewed
self-review is done. LGTM.

2022-09-15 08:52 UTC, Rishabh-Rathod commented
/ok-to-test sha=6666693

2022-09-15 12:47 UTC, Rishabh-Rathod commented
/ok-to-test sha=f07cabe

2022-09-15 13:01 UTC, Rishabh-Rathod reviewed
Fixed jest test correctly. Code LGTM

2022-09-15 13:01 UTC, Rishabh-Rathod commented on app/client/src/utils/autocomplete/TernServer.test.ts
> +        expectedOutput: { ch: 6, line: 0 },
completion.text.length = 4
cursor start = 2
from ( end ) = 4 + 2

2022-09-15 13:02 UTC, Rishabh-Rathod commented
/ok-to-test sha=cd345e4

2022-09-16 07:39 UTC, Rishabh-Rathod commented
/ok-to-test sha=b26bc57

2022-09-16 08:11 UTC, ohansFavour approved these changes

2022-09-16 08:20 UTC, ohansFavour requested changes
Get design sign-off first

2022-09-26 04:19 UTC, Rishabh-Rathod commented
Closing PR. 

Internal slack discussion:- https://theappsmith.slack.com/archives/C02K0SZQ7V3/p1664165909501019?thread_ts=1663320235.839129&cid=C02K0SZQ7V3

2022-09-26 04:19 UTC, closed without merging