feat: Image Widget Reskinning
appsmithorg/appsmith pull request #16787
Opened 2022-09-15 08:19 UTC by dhruvikn

## Description

This PR fixes UI inconsistencies in the Image widget.

- Update rotate and download control icons
- Add border radius and box shadow to control wrapper
- Multiple CSS fixes to follow the designs

Fixes #10979

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manually

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-09-15 11:14 UTC, keyurparalkar reviewed
Whenever the object is fit to cover and then rotated then should the border-radius be applied?
![Screenshot 2022-09-15 at 4 42 07 PM](https://user-images.githubusercontent.com/14138515/190389722-a482bc5e-f6d6-4fd5-bb4b-244d94f8d468.png)

Also, seems like the rotate icon is bit off from center?
![Screenshot 2022-09-15 at 4 41 27 PM](https://user-images.githubusercontent.com/14138515/190389891-d7256658-e10f-4d31-8d1c-cd9d9fabeaa2.png)

2022-09-15 11:14 UTC, keyurparalkar commented on app/client/src/widgets/ImageWidget/component/index.tsx
> +                    d="M2.23333 2.17702C3.19999 1.21035 4.52666 0.610352 5.99999 0.610352C8.94666 0.610352 11.3267 2.99702 11.3267 5.94368C11.3267 8.89035 8.94666 11.277 5.99999 11.277C3.51333 11.277
@dhruvikn can you please move this SVG to a folder?

2022-09-15 11:14 UTC, keyurparalkar commented on app/client/src/widgets/ImageWidget/component/index.tsx
> +                  fill="none"
Move svg to different folder

2022-09-15 11:14 UTC, keyurparalkar commented on app/client/src/widgets/ImageWidget/component/index.tsx
> +                className="is-download-icon"
Move svg to different folder

2022-09-15 16:48 UTC, Aishwarya-U-R commented
/ok-to-test sha=3385c7f

2022-09-16 07:27 UTC, dhruvikn commented
Hey @keyurparalkar, the rotate icon is centered. 😄 
I took some screenshots, and applied constraints of the same dimensions around the icon. Please check this [Figma](https://www.figma.com/file/DvUd9OJqhMfNgXXLE21PN7/Rotate-Icon-Center-Checks?node-id=0%3A1) or [PDF](https://github.com/appsmithorg/appsmith/files/9581534/Rotate.Icon.Center.Checks.pdf) out with maximum zoom in level.

<img width="1274" alt="image" src="https://user-images.githubusercontent.com/22471214/190580941-3d6b0513-a0b3-434e-bd80-4865c9374603.png">

Moreover, for this -

> Whenever the object is fit to cover and then rotated then should the border-radius be applied?

Had a discussion with @dilippitchika, there are a few thoughts - 
1. We have changed the deafult object fit to cover now.
2. The border radius issue when the image is rotated still exists. Border radius also fails when we change the dimensions of the image. This happens because we are rendering images as a `div` background and we are applying border radius to the container. This can be solved if we render images inside an `<img>` tag. This is a larger problem and we will be creating a new issue for the same.

2022-09-16 07:30 UTC, dhruvikn commented
/ok-to-test sha=e4d76e3

2022-09-19 05:18 UTC, keyurparalkar approved these changes
LGTM!

2022-09-19 07:30 UTC, jsartisan requested changes
LGTM. Just one comment.

2022-09-19 07:30 UTC, jsartisan commented on app/client/src/widgets/ImageWidget/component/index.tsx
> +  background-color: ${Colors.GREY_5};
Hey can we use the css variable here?

2022-09-19 07:36 UTC, dhruvikn commented on app/client/src/widgets/ImageWidget/component/index.tsx
> +  background-color: ${Colors.GREY_5};
Do you mean variables for colors from here? https://github.com/appsmithorg/appsmith/blob/769719ccfe667f059fe0b107a19ec9feb90f2e40/app/client/src/theme/wds.css

2022-09-20 07:16 UTC, laveena-en commented
Tested and verified.

2022-09-20 09:29 UTC, dhruvikn commented
/ok-to-test sha=6cf1fd8

2022-09-20 10:00 UTC, jsartisan approved these changes

2022-09-21 08:12 UTC, keyurparalkar approved these changes

2022-09-21 09:41 UTC, merged