task: POC - Listv2 - Introduces currentItemsView and currentRow + Refactoring
appsmithorg/appsmith pull request #16785
Opened 2022-09-15 08:00 UTC by ashit-rath

## Description
Introduces 2 properties and refactors the meta widget generation logic
`currentItemsView` - Belongs to list widget which returns the current view's widget's properties
`currentRow` - special keyword to refer any other widget in the same row, Eg - `{{currentRow.Input1.text}}``

Fixes #16422

2022-09-15 09:00 UTC, Tooluloope commented
@ashit-rath `currentItemsView` or `currentViewItems`

2022-09-15 09:04 UTC, ashit-rath commented
@Tooluloope  In code i did `currentViewItems` but in description I mentioned it as `currentItemsView`. Let me update

2022-09-19 12:41 UTC, Tooluloope requested changes

2022-09-19 12:41 UTC, Tooluloope commented on app/client/src/widgets/ListWidgetV2/MetaWidgetGenerator.ts
> +type generateMetaWidgetReturn = {
can this be `GeneratedMetaWidget`

2022-09-19 12:41 UTC, Tooluloope commented on app/client/src/widgets/ListWidgetV2/MetaWidgetGenerator.ts
> +        metaWidgetName: undefined,
any reason why we are returning `undefined` here and `string` on line 198?

2022-09-19 12:41 UTC, Tooluloope commented on app/client/src/widgets/ListWidgetV2/MetaWidgetGenerator.ts
> +    (templateWidget.children || []).map((childWidgetId: string) => {
can we use `forEach` here instead of `map`

2022-09-19 12:43 UTC, ashit-rath commented on app/client/src/widgets/ListWidgetV2/widget/index.tsx
>      this.generateChildrenEntityDefinitions(this.props);
There is an autocomplete derived property which uses this. So I'm not 100% sure if we need it or not, we'd have to verify it's usage and then take the call.

2022-09-19 13:00 UTC, Tooluloope approved these changes

2022-09-19 13:17 UTC, merged