optimized the reflows
appsmithorg/appsmith pull request #16812
Opened 2022-09-16 05:34 UTC by ankitakinger

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.

## Description

> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change.

Fixes # (issue)

> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-09-16 09:53 UTC, SatishGandham submitted a review, later dismissed

2022-09-16 10:01 UTC, ankitakinger commented
/ok-to-test sha=d2bce74

2022-09-16 14:32 UTC, ankitakinger commented
/ok-to-test sha=86c3723

2022-09-16 14:45 UTC, ankitakinger commented
/ok-to-test sha=24120c3

2022-09-17 05:29 UTC, SatishGandham requested changes

2022-09-17 05:29 UTC, SatishGandham commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/OtherUIFeatures/UpdateApplication_spec.js
> +    cy.get(".bp3-popover-target.bp3-popover-open").should("not.exist");
Where are we checking that the application name has updated?

2022-09-17 05:30 UTC, ankitakinger commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/OtherUIFeatures/UpdateApplication_spec.js
> +    cy.get(".bp3-popover-target.bp3-popover-open").should("not.exist");
I discussed this with @Parthvi12 and since we have removed the tooltip now, she asked me to add the check of it not existing.

2022-09-17 06:08 UTC, SatishGandham approved these changes

2022-09-17 06:08 UTC, merged