Add new property hidden to formControl fields
appsmithorg/appsmith pull request #1682
Opened 2020-11-11 05:00 UTC by akash-codemonk

Fixes #1659

2020-11-11 06:46 UTC, hetunandu requested changes
The hidden logic should be handled in the BaseControl and not in each and every control. This is leading to lots of code duplication

2020-11-11 06:52 UTC, riodeuno requested changes
@akash-codemonk when the value is READ_ONLY, we do not render the `Field` this leads me to believe, that the value may not available when the form is submitted. Could you confirm if the READ_ONLY fields have their original values sent to the servers?

2020-11-11 06:52 UTC, riodeuno commented on app/client/src/components/formControls/utils.ts
> +import _ from "lodash";
Let us start tree-shaking lodash. We can `import { get, isBoolean } from "lodash"`

2020-11-11 06:52 UTC, riodeuno commented on app/client/src/components/formControls/utils.ts
> +import _ from "lodash";
Let us add a unit test for this function.
It should to see if it handles scenarios of `undefined` or `null` values in the `hidden` config object properties gracefully.

2020-11-17 07:01 UTC, akash-codemonk commented
@hetunandu Will create a separate component which will create the control. Similar to https://github.com/appsmithorg/appsmith/blob/release/app/client/src/pages/Editor/PropertyPane/PropertyControl.tsx, this will handle the hidden logic and avoid duplication.

2020-11-17 07:07 UTC, akash-codemonk commented
@riodeuno The form values are initialised with the action or datasource values with for e.g `changeQuerySaga`. So yes the original value still remains in the form state when it is submitted even if the field is hidden.

2020-11-18 13:19 UTC, mohanarpit approved these changes

2020-11-18 13:34 UTC, riodeuno commented on app/client/src/components/formControls/BaseControl.tsx
> +  | "EQUALS"
Please elaborate on the reasoning behind moving to string literals from enum.

2020-11-18 13:36 UTC, riodeuno reviewed
Looks good to me.

2020-11-18 13:40 UTC, akash-codemonk commented on app/client/src/components/formControls/BaseControl.tsx
> +  | "EQUALS"
The json is going to be in a string format.

2020-11-19 03:32 UTC, merged