fix: update rts logic to use updated shared AST logic
appsmithorg/appsmith pull request #16849
Opened 2022-09-17 20:56 UTC by Irongade

This PR ensures the RTS code makes use of the updated AST logic. The changes made can be found in this [PR](https://github.com/appsmithorg/appsmith/pull/16171).

Fixes #16848 

- Bug fix (non-breaking change which fixes an issue)

Manual Tests

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-09-19 05:21 UTC, AmanAgarwal041 commented on app/rts/src/routes/ast_routes.ts
> +  "/multiple-script-infos",
We already have `multiple` attached in the route. Can we remove `s` from info?

2022-09-19 06:02 UTC, nidhi-nair commented on app/rts/src/controllers/Ast/AstController.ts
> -  async getDependentIdentifiers(req: Request, res: Response) {
Can we rename this method to something more descriptive? I am unable to understand what `info` indicates here.

2022-09-19 06:04 UTC, ohansFavour commented on app/rts/src/controllers/Ast/AstController.ts
> +            await AstService.extractInfoFromScript(script, evalVersion)
There should be a third argument here too

2022-09-19 06:04 UTC, ohansFavour commented on app/rts/src/controllers/BaseController.ts
> +type Extractions = ExtractInfoFromCode;
is there any reason for the re-assignment here?. If "Extractions" is a better name then we could change it in the @shared/ast file itself.

2022-09-19 06:04 UTC, ohansFavour commented on app/rts/src/services/AstService.ts
> +        const extractions = extractInfoFromCode(script, evalVersion);
Third argument needed here too

2022-09-19 07:16 UTC, nidhi-nair requested changes
Could we please add integration test cases here to make sure that CI fails if any PR tries to change the structure of how this library returns data in the future?

Also, does this change affect the API response in any way? If yes, could you please share the expected response structure in the PR description?

2022-09-19 07:44 UTC, Irongade commented on app/rts/src/controllers/Ast/AstController.ts
> -  async getDependentIdentifiers(req: Request, res: Response) {
We are returning a bunch of Information from the function, hence why we used Info, However on a second thought, we can make use of the word "Data". Data will be a good enough generic name.

2022-09-19 07:48 UTC, Irongade commented
> Also, does this change affect the API response in any way? If yes, could you please share the expected response structure in the PR description?

Expected change in the API response will follow the schema below.
 
```
 interface Extractions {
  references: string[];
  functionalParams: string[];
  variables: string[];
}
```

2022-09-19 08:05 UTC, AmanAgarwal041 commented
> Could we please add integration test cases here to make sure that CI fails if any PR tries to change the structure of how this library returns data in the future?
> 
> Also, does this change affect the API response in any way? If yes, could you please share the expected response structure in the PR description?

The API routes also change.

2022-09-19 21:18 UTC, Irongade commented
/ok-to-test sha=368dba9

2022-09-20 06:25 UTC, nidhi-nair commented on app/rts/src/services/AstService.ts
> -import { extractIdentifiersFromCode } from "@shared/ast";
Hey I'm sorry to nitpick, but this is still not informative. Info and data are quite generic and do not glean insight into what kind of data we expect to get here. Could we either revert to identifiers or use something more informative here?

I am guessing we will need to make this change to the ast library as well.

2022-09-26 21:41 UTC, Irongade commented
/ok-to-test sha=d44ef04

2022-09-27 05:04 UTC, nidhi-nair reviewed
QQ, @Irongade could you please explain to me why we need to version control the yarn lock file?

2022-09-27 11:07 UTC, Irongade commented
> QQ, @Irongade could you please explain to me why we need to version control the yarn lock file?

@nidhi-nair, I'm not sure why yarn.lock file was version controlled as well, but my guess would be that there might be certain dependencies that we don't want changing.

2022-09-27 15:38 UTC, AmanAgarwal041 commented on .github/workflows/rts-build.yml
> +      - name: Install dependencies
Build step already installs dependencies. Why do we need to install dependencies here? Can we not move this step after the build process ?

2022-09-27 16:31 UTC, Irongade commented on app/shared/ast/src/index.test.ts
> +        expectedResults: ["Table6"],
Good, then there will be no merge conflicts. It was automatically done by Prettier.

2022-09-27 16:36 UTC, Irongade commented on .github/workflows/rts-build.yml
> +      - name: Install dependencies
1. We need to install all dependencies in order to be able to run the Jest test cases, as Jest, Supertest and other dependencies are required for this step.
2. Ideally we should run jest test cases before commencing a build as this is the best practice. So I think we have to remove the extra yarn install in the build.sh file (as long as it does not break the docker deployment for RTS - I did not remove it for this reason).

2022-09-28 05:35 UTC, AmanAgarwal041 commented on .github/workflows/rts-build.yml
> +      - name: Install dependencies
Since both jest test cases and build are independent on each other here, we can move the running of jest test cases after build as both steps are important. We cannot remove the `yarn install` step in build.sh file as this is the file being called when the build is created.

2022-09-28 09:05 UTC, nidhi-nair commented
> I'm not sure why yarn.lock file was version controlled as well, but my guess would be that there might be certain dependencies that we don't want changing.

@Irongade I thought yarn allowed you to specify particular versions in the definition itself, no? Is that understanding incorrect? 🤔

2022-09-28 10:08 UTC, Irongade commented
> > I'm not sure why yarn.lock file was version controlled as well, but my guess would be that there might be certain dependencies that we don't want changing.
> 
> @Irongade I thought yarn allowed you to specify particular versions in the definition itself, no? Is that understanding incorrect? 🤔

Yes, but we would be hardcoding the versions in the package.json file for example `moment: 4.5.2`. It is often better to use the yarn.lock file instead to maintain versions. We make use of this pattern in the client folder as well.

2022-09-28 10:11 UTC, AmanAgarwal041 approved these changes

2022-09-28 10:49 UTC, nidhi-nair approved these changes

2022-09-28 17:28 UTC, merged