fix: JS option missing for some style items in table widget v2
appsmithorg/appsmith pull request #16958
Opened 2022-09-21 12:43 UTC by souma-ghosh

## Description

The JS toggle option was missing in Text formatting section of table widget v2 for:

1. Emphasis
2. Text Align
3. Vertical Alignment

Enabled the options in styleConfig

Fixes #2906

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manually tested

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-09-21 12:44 UTC, souma-ghosh commented
/ok-to-test sha=7f71c46

2022-09-22 07:09 UTC, souma-ghosh commented
/ok-to-test sha=3ecdbe1

2022-09-22 07:15 UTC, aswathkk requested changes
@souma-ghosh We don't need to make use of `ValidationTypes.TABLE_PROPERTY`. Otherwise PR looks good to me.

2022-09-22 07:15 UTC, aswathkk commented on app/client/src/widgets/TableWidgetV2/widget/propertyConfig/styleConfig.ts
> +          type: ValidationTypes.TABLE_PROPERTY,
You don't need to make use of `ValidationTypes.TABLE_PROPERTY` since this configuration is not for the column but for the Table itself.

Just the following is enough:
```js
validation: {
   type: ValidationTypes.TEXT,
   params: {
     allowedValues: ["LEFT", "CENTER", "RIGHT"],
   },
}
```

2022-09-22 07:15 UTC, aswathkk commented on app/client/src/widgets/TableWidgetV2/widget/propertyConfig/styleConfig.ts
> +        validation: {
Same as above

2022-09-22 07:34 UTC, souma-ghosh commented
/ok-to-test sha=617420f

2022-09-22 10:03 UTC, aswathkk approved these changes

2022-09-22 11:15 UTC, sbalaji1192 commented on app/client/src/widgets/TableWidgetV2/widget/propertyConfig/styleConfig.ts
> +        validation: { type: ValidationTypes.TEXT },
we need to provide the expected value as well.

2022-09-22 11:51 UTC, laveena-en commented
Tested and verified.

2022-09-22 11:59 UTC, souma-ghosh commented on app/client/src/widgets/TableWidgetV2/widget/propertyConfig/styleConfig.ts
> +        validation: { type: ValidationTypes.TEXT },
We can select multiple values for BUTTON_TABS control type.
It is accepting any string where it can find "bold" or "italic" somewhere in the string.
So valid values can be any of the following

- bolditalic
- bold,italic
- ["bold", "italic"]
- somethingboldsomething - bold gets activated
- randomitalicrandomboldrandom - both bold and italic gets activated

So what should we provide as expected value?
@sbalaji1192

2022-09-23 09:41 UTC, souma-ghosh commented on app/client/src/widgets/TableWidgetV2/widget/propertyConfig/styleConfig.ts
> +        validation: { type: ValidationTypes.TEXT },
Consulted @aswathkk  on this. Seems like the expected validation for BUTTON_TABS control type has been discussed before. Hence opening a new issue here https://github.com/appsmithorg/appsmith/issues/17018. Moving ahead with this one @sbalaji1192 @aswathkk

2022-09-23 09:41 UTC, merged