fix: Form and JSONForm reskinning
appsmithorg/appsmith pull request #16956
Opened 2022-09-21 11:41 UTC by jsartisan

## Description

> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change.

Fixes #15171
Fixes #10977

> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-09-23 06:46 UTC, chandannkumar commented
Tested this for:
- UI inconsistencies in RTE, Form and JSON Form reskinning
- Fixes one small color bug for checkbox in disabled state

2022-09-23 07:02 UTC, dhruvikn requested changes

2022-09-23 07:05 UTC, jsartisan commented on app/client/src/widgets/FormWidget/index.ts
> +    borderColor: Colors.GREY_5,
We can't use css variables here :/ 
This config will require actual values as these will be used in property pane.

2022-09-23 07:05 UTC, dhruvikn commented on app/client/src/widgets/FormWidget/index.ts
> +    borderColor: Colors.GREY_5,
Ah my bad, looks good then!

2022-09-23 07:06 UTC, dhruvikn submitted a review, later dismissed

2022-09-23 07:10 UTC, jsartisan commented
/ok-to-test sha=a0abade

2022-09-23 09:38 UTC, jsartisan commented
/ok-to-test sha=72156eb

2022-09-26 05:16 UTC, jsartisan commented
/ok-to-test sha=d02b5ea

2022-09-26 07:21 UTC, jsartisan commented
/ok-to-test sha=ab3bd31

2022-09-26 16:03 UTC, jsartisan commented
/ok-to-test sha=937431f

2022-09-28 10:41 UTC, dhruvikn approved these changes

2022-09-28 17:28 UTC, merged