fix: List + Modal reskinning
appsmithorg/appsmith pull request #16974
Opened 2022-09-22 07:43 UTC by jsartisan

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.

## Description

> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change.

Fixes # (issue)

> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-09-27 08:07 UTC, laveena-en commented
@jsartisan Could you please change the tab labels not to be bold? 
![image](https://user-images.githubusercontent.com/109572422/192469902-ce6e231e-661c-4265-aca0-c0a6af39cf4a.png)

2022-09-29 05:34 UTC, jsartisan commented
/ok-to-test sha=57c1122

2022-09-29 07:27 UTC, dhruvikn requested changes

2022-09-29 07:27 UTC, dhruvikn commented on app/client/src/widgets/TabsWidget/widget/index.tsx
> +            helpText: "Sets the checked state color of the checkbox",
Seems like we missed changing the helpText. Can we please add a relevant message like
`Sets the color for the selected tab`

2022-09-29 18:04 UTC, jsartisan commented
/ok-to-test sha=69e94e4

2022-09-30 04:59 UTC, jsartisan commented
/ok-to-test sha=7109c17

2022-09-30 06:29 UTC, jsartisan commented
/ok-to-test sha=8f640f9

2022-09-30 08:44 UTC, dhruvikn approved these changes

2022-09-30 09:18 UTC, merged