fix:Slow rendering of JSON and RAW response
appsmithorg/appsmith pull request #16971
Opened 2022-09-22 05:31 UTC by ChandanBalajiBP

## Description

> API response JSON/RAW rendering is too slow.

Fixes #16705 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-09-22 08:45 UTC, ChandanBalajiBP commented
/ok-to-test sha=58e465b

2022-09-22 13:23 UTC, mohanarpit commented on app/client/src/components/editorComponents/ApiResponseView.tsx
> +        containerHeight={tableBodyHeight}
QQ: Since `tableBodyHeight` is a nullable parameter, what happens if the value passed to this function is null?

I'm simply asking this question to further my understanding of how React works :)

2022-09-22 13:39 UTC, ChandanBalajiBP commented on app/client/src/components/editorComponents/ApiResponseView.tsx
> +        containerHeight={tableBodyHeight}
1. The size of the editor is set to 100% in the constructor. So would render without any issue. 
2. This parameter is only considered when the container size is altered. So the editor will refresh only if the parameter is not null and has increased from its previous value.

2022-09-26 05:15 UTC, ayushpahwa commented on app/client/src/components/editorComponents/CodeEditor/index.tsx
> +        prevProps.containerHeight < this.props.containerHeight
Should we be debouncing this action? Instead of allowing refresh on every change, maybe we can reduce the number of calls to only when the user is done editing or maybe debounce it by some ms. Also, what are the performance impacts of this PR?

2022-09-26 08:09 UTC, ChandanBalajiBP commented on app/client/src/components/editorComponents/CodeEditor/index.tsx
> +        prevProps.containerHeight < this.props.containerHeight
I completely agree with you on debouncing. I will update the same. There is no change in performance w.r.t to loading of the component. And no observable performance impact on resizing.

2022-09-26 09:40 UTC, ChandanBalajiBP commented
/ok-to-test sha=de4a111

2022-09-26 11:56 UTC, ayushpahwa requested changes

2022-09-26 11:56 UTC, ayushpahwa commented on app/client/src/components/editorComponents/CodeEditor/index.tsx
> +    console.log("ondhu 3");
Please remove any console statements

2022-09-26 11:56 UTC, ayushpahwa commented on app/client/src/components/editorComponents/CodeEditor/index.tsx
> +import _, { isString, debounce as _debounce } from "lodash";
Please remove the import of the whole `_` from lodash and only use the functions that are needed.

2022-09-26 12:35 UTC, ChandanBalajiBP commented on app/client/src/components/editorComponents/CodeEditor/index.tsx
> +import _, { isString, debounce as _debounce } from "lodash";
@ayushpahwa  Codemirror editor linter is using the whole lodash package in getAnnotations function. (line num~248). So can we use _ in this case?

2022-09-27 05:48 UTC, ChandanBalajiBP commented
/ok-to-test sha=fb35b71

2022-09-28 05:34 UTC, ayushpahwa approved these changes

2022-09-30 07:28 UTC, ChandanBalajiBP commented
/ok-to-test sha=57222ee

2022-09-30 15:21 UTC, merged