feat: Implement data type handling in MySQL (#16621)
appsmithorg/appsmith pull request #17017
Opened 2022-09-23 09:16 UTC by subrata71

## Description
With this implementation we can now achieve the following under prepared statement:
- Ability to distinguish between null object and "null" string
- Ability to distinguish values like {{"098765"}} and {{098765}}. The former is identified as a string and the latter is identified as an integer

Fixes #16621 

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Test A
- Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-09-26 05:11 UTC, nidhi-nair requested changes

2022-09-26 05:11 UTC, nidhi-nair commented on app/server/appsmith-plugins/mysqlPlugin/src/main/java/com/external/plugins/MySqlPlugin.java
> +import com.appsmith.external.datatypes.*;
Could we please use complete references here?

2022-09-26 05:11 UTC, nidhi-nair commented on app/server/appsmith-plugins/mysqlPlugin/src/main/java/com/external/plugins/MySqlPlugin.java
> +    static {
Could we please separate out everything to do with datatypes into a different class? The `plugins/PluginClass/java` files should always only be entry points to all plugin related methods. Any logic can be separated out, for readability, extensibility, and maintainability.

2022-09-26 05:11 UTC, nidhi-nair commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/plugins/SmartSubstitutionInterface.java
> +                            value, input, insertedParams, append(args, matchingParam.get().getClientDataType()));
Hey sorry, I might be missing something here, but why did we decide to proceed with the varargs way of using a method call here?

2022-09-26 06:58 UTC, subrata71 commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/plugins/SmartSubstitutionInterface.java
> +                            value, input, insertedParams, append(args, matchingParam.get().getClientDataType()));
The client data type is required in the substituteValueInInput method. One way we could pass this argument is by introducing a new variable just before the `varargs` but that would require changes along the way to all the plugins. I have found that in Postgres plugin `connectionPool` and `explicitCastDataTypes` objects are passed through varargs. @nidhi-nair

2022-09-26 07:07 UTC, subrata71 commented on app/server/appsmith-plugins/mysqlPlugin/src/main/java/com/external/plugins/MySqlPlugin.java
> +import com.appsmith.external.datatypes.*;
Yes, will do. Thanks

2022-09-26 07:08 UTC, subrata71 commented on app/server/appsmith-plugins/mysqlPlugin/src/main/java/com/external/plugins/MySqlPlugin.java
> +    static {
Do you suggest introducing a separate class where all the supported data types are accessible as a static member? @nidhi-nair

2022-09-26 07:12 UTC, nidhi-nair commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/plugins/SmartSubstitutionInterface.java
> +                            value, input, insertedParams, append(args, matchingParam.get().getClientDataType()));
Alright, I think we should keep these changes in mind for the future. Varargs are not great for visibility into the interface of a method because we end up not having any idea about what usage is like without dipping our fingers into code. The refactor here is a must have, put we can push it for late to a point when making the change becomes trivial.

2022-09-26 07:14 UTC, nidhi-nair commented on app/server/appsmith-plugins/mysqlPlugin/src/main/java/com/external/plugins/MySqlPlugin.java
> +    static {
For the data type definitions as well as anything to do with substitution. Essentially anything outside of the pure functionality the is defined in the `PluginExecutor` interface should be split up.

2022-09-26 07:18 UTC, subrata71 commented on app/server/appsmith-plugins/mysqlPlugin/src/main/java/com/external/plugins/MySqlPlugin.java
> +    static {
So, I am planning to introduce a new class like that and that will be accessed in the `PluginExecutor`

```
public class MySQLSpecificDataTypes {
    public static final Map<ClientDataType, List<AppsmithType>> pluginSpecificTypes;
    static {
      // populate the map
    }
}
```

**Usage**

`AppsmithType appsmithType = DataTypeServiceUtils.getAppsmithType(clientDataType, value, MySQLSpecificDataTypes.pluginSpecificTypes);`

Does it look okay? @nidhi-nair

2022-09-26 07:20 UTC, subrata71 commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/plugins/SmartSubstitutionInterface.java
> +                            value, input, insertedParams, append(args, matchingParam.get().getClientDataType()));
Agreed with that but looking into the codebase I couldn't come up with a better choice. :( 
@nidhi-nair

2022-09-26 07:53 UTC, subrata71 commented on app/server/appsmith-plugins/mysqlPlugin/src/main/java/com/external/plugins/MySqlPlugin.java
> +    static {
There are a few methods implemented inside the PluginExecutor class which fit best inside a util class. I can keep this on my to-do list for future refactoring.
@nidhi-nair

2022-09-26 08:00 UTC, nidhi-nair commented on app/server/appsmith-plugins/mysqlPlugin/src/main/java/com/external/plugins/datatypes/MySQLSpecificDataTypes.java
> +import com.appsmith.external.datatypes.*;
Looks like the import here ended up being generic as well. :) There's a setting in IntelliJ to disable this. Auto-formatting will not introduce this after you do that.

2022-09-26 08:08 UTC, subrata71 commented on app/server/appsmith-plugins/mysqlPlugin/src/main/java/com/external/plugins/datatypes/MySQLSpecificDataTypes.java
> +import com.appsmith.external.datatypes.*;
Yeah! 
Set 9999 to the following two fields (previously it was 5).

`Editor > Code Style > Java > Imports > "Class count to use import with '*" and "Names count to use static import with '*'"
`
@nidhi-nair

2022-09-26 08:10 UTC, nidhi-nair submitted a review, later dismissed

2022-09-26 08:11 UTC, subrata71 commented
/ok-to-test sha=a0218fb

2022-09-26 10:58 UTC, subrata71 commented
/ok-to-test sha=f6d21b8

2022-09-26 11:04 UTC, nidhi-nair commented on app/server/appsmith-plugins/mysqlPlugin/src/test/java/com/external/plugins/MySqlPluginTest.java
> +                            structure.getTables().
Nit: formatting seems off here.

2022-09-26 11:07 UTC, nidhi-nair commented on app/server/appsmith-plugins/mysqlPlugin/src/test/java/com/external/plugins/MySqlPluginTest.java
>                      assertEquals("possessions", possessionsTable.getName());
Seems like a redundant check

2022-09-26 11:56 UTC, subrata71 commented
/ok-to-test sha=f0f8f5a

2022-09-26 12:00 UTC, subrata71 commented on app/server/appsmith-plugins/mysqlPlugin/src/test/java/com/external/plugins/MySqlPluginTest.java
>                      assertEquals("possessions", possessionsTable.getName());
In my local MySQL server there were a few other tables so the ordering of the tables that this test case expected was not happening. This made a tight coupling with the ordering of the tables. As we are only matching the structure of the two tables e.g. possession and users we are still achieving that but with no tight coupling with the order.
@nidhi-nair

2022-09-26 12:02 UTC, subrata71 commented on app/server/appsmith-plugins/mysqlPlugin/src/test/java/com/external/plugins/MySqlPluginTest.java
> +                    assertTrue(structure.getTables().size() > 0);
In the latter part of this test case, we are matching the structure of two tables e.g. possesions and users. I thought we shouldn't expect exactly two tables. If there exist more tables (depending on the environment) should we still stick to 2 tables' checking?
@nidhi-nair

2022-09-26 12:08 UTC, subrata71 commented
/ok-to-test sha=f70faa6

2022-09-26 12:31 UTC, nidhi-nair commented on app/server/appsmith-plugins/mysqlPlugin/src/test/java/com/external/plugins/MySqlPluginTest.java
>                      assertEquals("possessions", possessionsTable.getName());
Yes I meant that now that you are filtering on the basis of table name, the check with the name seems redundant. :) Instead the check should be in the previous step, that the `get` was successful.

2022-09-26 13:02 UTC, subrata71 commented on app/server/appsmith-plugins/mysqlPlugin/src/test/java/com/external/plugins/MySqlPluginTest.java
>                      assertEquals("possessions", possessionsTable.getName());
Ohh yes, that check now becomes redundant. Nice catch! I am removing this check and will update the PR accordingly. @nidhi-nair

2022-09-26 13:02 UTC, subrata71 commented on app/server/appsmith-plugins/mysqlPlugin/src/test/java/com/external/plugins/MySqlPluginTest.java
> +                    assertTrue(structure.getTables().size() > 0);
Got it. I am retaining the check then.

2022-09-26 13:02 UTC, subrata71 commented on app/server/appsmith-plugins/mysqlPlugin/src/test/java/com/external/plugins/MySqlPluginTest.java
> +                            structure.getTables().
Will format that.

2022-09-26 13:14 UTC, subrata71 commented
/ok-to-test sha=961b6cf

2022-09-26 15:54 UTC, nidhi-nair approved these changes

2022-09-26 17:45 UTC, subrata71 commented
/ok-to-test sha=49916a2

2022-09-27 10:56 UTC, subrata71 commented
/ok-to-test sha=722209c

2022-09-28 08:05 UTC, ChandanBalajiBP commented
/ok-to-test sha=f376a60

2022-09-28 09:05 UTC, Aishwarya-U-R commented on app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/Datatypes/MySQL_false_Spec.ts
> +    dataSources.DeleteDatasouceFromWinthinDS(dsName, 409); //Since all queries exists
This check can be removed from here since you are doing in spec1.
Directly delete the query, deploy, delete the ds - so few secs are saved.

2022-09-28 10:52 UTC, ChandanBalajiBP commented
/ok-to-test sha=43b5e9b

2022-09-28 10:52 UTC, ChandanBalajiBP commented on app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/Datatypes/MySQL_false_Spec.ts
> +    dataSources.DeleteDatasouceFromWinthinDS(dsName, 409); //Since all queries exists
updated

2022-09-28 14:12 UTC, Aishwarya-U-R commented
/ok-to-test sha=8d26c9c

2022-09-29 08:43 UTC, ChandanBalajiBP commented
/ok-to-test sha=2bc9680

2022-09-29 10:16 UTC, ChandanBalajiBP commented
/ok-to-test sha=15fa7ce

2022-09-29 13:08 UTC, subrata71 commented
/ok-to-test sha=fa2612b

2022-09-29 15:54 UTC, Aishwarya-U-R commented
/ok-to-test sha=c0a51cb

2022-09-30 06:42 UTC, subrata71 commented
/ok-to-test sha=d370dbb

2022-09-30 09:56 UTC, ChandanBalajiBP commented
/ok-to-test sha=a455e8b

2022-09-30 13:55 UTC, nidhi-nair approved these changes

2022-09-30 14:03 UTC, Aishwarya-U-R reviewed
Cypress tests looks good!

2022-09-30 15:21 UTC, ChandanBalajiBP commented on app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/Datatypes/MySQL_Spec.ts
> +const isEqual = require("lodash/isEqual");
Removed

2022-10-04 05:05 UTC, ChandanBalajiBP commented
/ok-to-test sha=a05f496

2022-10-04 05:30 UTC, Aishwarya-U-R approved these changes
Cypress looks good!

2022-10-04 10:45 UTC, merged