Fix: Application name update checks
appsmithorg/appsmith pull request #1710
Opened 2020-11-12 09:39 UTC by devrk96

2020-11-12 17:23 UTC, mohanarpit commented
@devrk96 Is it possible to write Jest/Cypress tests to assert these bug fixes?

2020-11-18 17:11 UTC, hetunandu requested changes

2020-11-18 17:11 UTC, hetunandu commented on app/client/src/components/ads/EditableText.tsx
> +      }
Application name specific code here in the design system file. You need to extract this validation somewhere else

2020-11-25 19:05 UTC, hetunandu approved these changes

2020-12-04 06:47 UTC, hetunandu commented on app/client/src/components/ads/EditableTextWrapper.tsx
> +          } else if (value === "") {
Trim the name before checking for this

2020-12-04 06:48 UTC, hetunandu requested changes
Minor change needed

2020-12-07 06:51 UTC, mohanarpit approved these changes

2020-12-07 06:52 UTC, merged