reset end focus
appsmithorg/appsmith pull request #17339
Opened 2022-10-06 06:36 UTC by developer-honoru

## Description

There is no function to set the focus on the input window.
When reset, if it is an input, the focus is fixed

Fixes # (issue)
#16965 

## Type of change

> Please delete options that are not relevant.

- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How Has This Been Tested?
https://user-images.githubusercontent.com/33475816/194231270-fa6ab2de-b816-4a2d-ba16-796d595a3105.mov
Try executing the 'resetWidget' function as input.

## Checklist:

- [x ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-10-10 00:16 UTC, developer-honoru commented
@hetunandu What else do I need to check?

2022-10-10 02:52 UTC, hetunandu requested changes

2022-10-10 02:52 UTC, hetunandu commented on app/client/src/sagas/WidgetOperationSagas.tsx
> +
This is not the right approach to take. We should not piggyback on another action to focus on an element (input or otherwise). A better approach would be create a new action that can focus a widget of choice.

2022-10-10 02:54 UTC, hetunandu commented
@rimildeyjsr Can you help @developer-honoru on steps to create a new action.

2022-10-10 06:07 UTC, developer-honoru commented on app/client/src/sagas/WidgetOperationSagas.tsx
> +
I think so too. But adding an action requires changing a lot of files. Do you have a manual for it?

2022-10-10 06:09 UTC, hetunandu commented on app/client/src/sagas/WidgetOperationSagas.tsx
> +
@satbir121 can help you out for this. He should reach out to you soon

2022-10-10 06:10 UTC, developer-honoru commented on app/client/src/sagas/WidgetOperationSagas.tsx
> +
thank you

2022-10-10 10:08 UTC, developer-honoru commented on app/client/src/sagas/WidgetOperationSagas.tsx
> +
@satbir121  hello?

2022-10-10 11:18 UTC, satbir121 commented on app/client/src/sagas/WidgetOperationSagas.tsx
> +
@developer-honoru Thank you for your patience. I agree with Hetu on creating a new action. 

We are in middle of a refactor which would make it very easy to add an action. The refactor will be done in the coming weeks. We would reach out to you once the refactor is done. @rimildeyjsr is leading the refactor for it.

2022-10-11 10:09 UTC, developer-honoru commented on app/client/src/sagas/WidgetOperationSagas.tsx
> +
Unfortunately, I'm in a situation where I need that feature quickly.
Can you give me a manual on how to blow PR now? @satbir121 @rimildeyjsr

2022-10-11 10:10 UTC, developer-honoru commented on app/client/src/sagas/WidgetOperationSagas.tsx
> +
I am in a situation where I need functions such as 'focus' and 'top scroll up'.

2022-10-13 02:39 UTC, developer-honoru commented on app/client/src/sagas/WidgetOperationSagas.tsx
> +
@satbir121 @rimildeyjsr  hello?

2022-10-24 02:32 UTC, developer-honoru commented on app/client/src/sagas/WidgetOperationSagas.tsx
> +
@satbir121 @rimildeyjsr  hello?

2022-10-31 16:45 UTC, closed without merging