Fix/16994 refactor common datatype handling
appsmithorg/appsmith pull request #17429
Opened 2022-10-10 07:21 UTC by subrata71

## Description

WIP

Fixes #16994 

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Manual
- JUnit Tests

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-10-11 10:21 UTC, subrata71 commented
/ok-to-test sha=48dadd3

2022-10-11 10:53 UTC, nidhi-nair requested changes
Mostly shared code related comments.

2022-10-11 10:53 UTC, nidhi-nair commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/datatypes/ArrayType.java
> +            return  (!trimmedInputBetweenBraces.isEmpty());
Could you please help me understand this change? Should we be considering empty arrays here?

2022-10-11 10:53 UTC, nidhi-nair commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/datatypes/NullType.java
> +        if (trimmedValue.startsWith("[") && trimmedValue.endsWith("]")) {
Let's create specific null types for these?

2022-10-11 10:53 UTC, nidhi-nair commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/DataTypeServiceUtils.java
> +        defaultAppsmithTypes.put(ClientDataType.OBJECT, List.of(new JsonObjectType(), new BsonType()));
Should `BsonType` be a default? Would we want this to only apply for Mongo?

2022-10-11 10:53 UTC, nidhi-nair commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/DataTypeStringUtils.java
> +                                                                  Object...args) {
I'm sorry I keep asking this over and over. Why are we using varargs here? It's a code smell and I know we've talked about this before, I forget your reason.

2022-10-11 11:07 UTC, subrata71 commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/DataTypeStringUtils.java
> +                                                                  Object...args) {
I will remove this varargs. I forgot to refactor this. It's not required anymore at this.

2022-10-11 12:06 UTC, subrata71 commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/DataTypeServiceUtils.java
> +        defaultAppsmithTypes.put(ClientDataType.OBJECT, List.of(new JsonObjectType(), new BsonType()));
I will move it to mongoplugin module.

2022-10-12 05:28 UTC, nidhi-nair commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/DataTypeServiceUtils.java
> +        defaultAppsmithTypes.put(ClientDataType.ARRAY, List.of(new NullArrayType(), new ArrayType()));
NullArrayType only applies to SQL plugins right?

2022-10-12 05:28 UTC, nidhi-nair commented on app/server/appsmith-plugins/mongoPlugin/src/test/java/com/external/plugins/MongoPluginDataTypeTest.java
> +        pluginSpecificTypes.put(ClientDataType.OBJECT, List.of(new JsonObjectType(), new BsonType()));
QQ: Could you please explain the order of prioritization between JSON and BSON here? We should also add a comment so we don't ask this question again!

2022-10-12 05:45 UTC, subrata71 commented on app/server/appsmith-plugins/mongoPlugin/src/test/java/com/external/plugins/MongoPluginDataTypeTest.java
> +        pluginSpecificTypes.put(ClientDataType.OBJECT, List.of(new JsonObjectType(), new BsonType()));
I just followed the same order which was in `jsonSmartReplacementPlaceholderWithValue` method. Inspired by that type hierarchy.

2022-10-12 05:46 UTC, subrata71 commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/DataTypeServiceUtils.java
> +        defaultAppsmithTypes.put(ClientDataType.ARRAY, List.of(new NullArrayType(), new ArrayType()));
This one I am not 100% certain about. There could be use cases for non-sql plugins too. I put it in the default datatypes collection though.

2022-10-12 07:23 UTC, subrata71 commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/datatypes/ArrayType.java
> +            return  (!trimmedInputBetweenBraces.isEmpty());
If the array is not empty only then it will be identified as an array data type. You see a (!) before that condition.

2022-10-12 07:41 UTC, nidhi-nair commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/datatypes/ArrayType.java
> +            return  (!trimmedInputBetweenBraces.isEmpty());
Can empty array types not be identified as this as well?

2022-10-12 07:42 UTC, nidhi-nair commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/DataTypeServiceUtils.java
> +        defaultAppsmithTypes.put(ClientDataType.ARRAY, List.of(new NullArrayType(), new ArrayType()));
I think we should. treat this on a case by case basis? Since this is a known problem for SQL, let's use it for those plugins only? The reason for this is that we're going to add a null kind of handling for other plugins as well and that might be undesirable.

2022-10-12 07:43 UTC, subrata71 commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/datatypes/ArrayType.java
> +            return  (!trimmedInputBetweenBraces.isEmpty());
No, empty will be identified as `NullArray`.

2022-10-12 07:43 UTC, nidhi-nair commented on app/server/appsmith-plugins/mongoPlugin/src/test/java/com/external/plugins/MongoPluginDataTypeTest.java
> +        pluginSpecificTypes.put(ClientDataType.OBJECT, List.of(new JsonObjectType(), new BsonType()));
It would be great if you can add a comment here about the possible logic for this as per your understanding. :)

2022-10-12 07:44 UTC, nidhi-nair commented on app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java
> +    public void testNumericStringHavingLeadingZeroWithPreparedStatement() {
This seems to be an incorrect name for this plugin.

2022-10-17 07:58 UTC, subrata71 commented
/ok-to-test sha=ea6cbce

2022-10-17 11:14 UTC, nidhi-nair commented on app/server/appsmith-plugins/amazons3Plugin/src/test/java/com/external/plugins/AmazonS3PluginTest.java
>  import com.amazonaws.services.s3.model.*;
Not your change, but could you please fix this?

2022-10-17 11:14 UTC, nidhi-nair commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/datatypes/ArrayType.java
> +            return  (!trimmedInputBetweenBraces.isEmpty());
QQ: What does `[]` return with here?

2022-10-17 13:12 UTC, subrata71 commented
/ok-to-test sha=f41c8f3

2022-10-18 05:32 UTC, merged