feat: AST based entity refactor
appsmithorg/appsmith pull request #17434
Opened 2022-10-10 10:41 UTC by ChandanBalajiBP

## Description

Fixes #17333 

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-10-10 10:42 UTC, ChandanBalajiBP commented
/ok-to-test sha = 8435205

2022-10-10 10:44 UTC, ChandanBalajiBP commented
/ok-to-test sha=8435205

2022-10-11 09:51 UTC, ChandanBalajiBP commented
/ok-to-test sha=1273c68

2022-10-13 14:52 UTC, ohansFavour commented on app/shared/ast/src/index.ts
> +  var ast = parse(code, {
There is a getAST function which is already present, can we use that instead?. That function is memorized, this could help improve performance.

2022-10-13 14:59 UTC, ChandanBalajiBP commented on app/shared/ast/src/index.ts
> +  var ast = parse(code, {
Updated

2022-10-14 13:20 UTC, ChandanBalajiBP commented
/ok-to-test sha=b3da46c

2022-10-14 16:20 UTC, Irongade requested changes

2022-10-14 18:02 UTC, ChandanBalajiBP commented on app/rts/src/controllers/Ast/AstController.ts
> +      const { script, evalVersion = 2 }: ScriptToIdentifiersType = req.body;
Updated

2022-10-14 18:12 UTC, Irongade submitted a review, later dismissed
Nice work Chandan, LGTM!

2022-10-14 18:24 UTC, ohansFavour commented on app/shared/ast/src/index.ts
> +const ancestorParsing = (ast: Node): NodeList => {
What is happening in this function is "Tree walking" and not parsing. getAST is where parsing occurs. Can we consider a much more semantic name?

2022-10-14 18:32 UTC, ohansFavour commented on app/shared/ast/src/index.ts
> +    const sanitizedScript = sanitizeScript(script, 2);
Why aren't we passing evaluationVersion here? we could set its default to 2. The evaluation version determines how we sanitize code.

2022-10-15 19:12 UTC, ChandanBalajiBP commented on app/shared/ast/src/index.ts
> +const ancestorParsing = (ast: Node): NodeList => {
Updated

2022-10-15 19:12 UTC, ChandanBalajiBP commented on app/shared/ast/src/index.ts
> +    const sanitizedScript = sanitizeScript(script, 2);
Updated

2022-10-15 19:16 UTC, ChandanBalajiBP commented
/ok-to-test sha=b6313cd

2022-10-17 07:54 UTC, ChandanBalajiBP commented on app/shared/ast/src/index.ts
> +        functionalParams.has(topLevelIdentifier) ||
I tried doing this but can only achieve the helper function for the shouldUpdate logic. Because inside the array filter logic is a bit different for entity refactoring(string manipulation). 
But if we have a helper function only for shouldUpdate, then we have to pass all params(reference, functionalParams, variableDeclarations, invalidIdentifiers). Which would be more cumbersome.

2022-10-17 08:26 UTC, ChandanBalajiBP commented
/ok-to-test sha=bd6b406

2022-10-17 10:56 UTC, ChandanBalajiBP commented
/ok-to-test sha=edfdb7d

2022-10-17 11:24 UTC, ChandanBalajiBP commented on app/shared/ast/src/index.ts
> +      //check if nodde should be updated
Updated

2022-10-17 11:24 UTC, ChandanBalajiBP commented on app/shared/ast/src/index.ts
> +  //List of all nodes
Updated!!

2022-10-18 06:29 UTC, ohansFavour approved these changes

2022-10-18 06:36 UTC, ChandanBalajiBP commented
This doesn't need QA as this is a non-breaking change and API is yet to be consumed. This will be tested once backend integration is completed. Hence adding test plan approved label.

2022-10-18 06:37 UTC, merged