[Bug]: JS option missing for Label Font Style in Input widget
appsmithorg/appsmith pull request #17631
Opened 2022-10-17 18:21 UTC by sanjus-robotic-studio

## Description

> Made changes to baseinputwidget label style - Emphasis Property
Fixes # (issue)
#15542

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

This has been tested locally on my Computer

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-10-18 03:33 UTC, dilippitchika commented
@aswathkk can you review this change? It's from our external contributor

2022-10-18 06:10 UTC, aswathkk requested changes
Hi @sanjus-robotic-studio,

Thanks for contributing. We need to make the `isBindingProperty` `true` so that this field will accept binding.

2022-10-18 06:10 UTC, aswathkk commented on app/client/src/widgets/BaseInputWidget/widget/index.tsx
>              isBindProperty: false,
`isBindProperty` should be `true` so that bindings will be accepted by this field.

2022-10-18 12:22 UTC, sanjus-robotic-studio commented on app/client/src/widgets/BaseInputWidget/widget/index.tsx
>              isBindProperty: false,
Hey @aswathkk  I have made the changes

2022-10-18 12:22 UTC, sanjus-robotic-studio commented
@aswathkk I have made the changes

2022-10-19 05:35 UTC, aswathkk approved these changes
LGTM

2022-10-19 05:35 UTC, aswathkk commented
/ok-to-test sha=d76c635

2022-10-19 10:08 UTC, merged