[Bug]: ClassCastException: class java.lang.Integer cannot be cast to class java.lang.String
appsmithorg/appsmith pull request #17707
Opened 2022-10-19 08:06 UTC by amogh2019

## Description

Fixes #16251

as per the suggestion
> [Apparently](https://app.smartlook.com/org/9b6c5c859e85745d01196fa4/project/e373e3a21d27278fd281d8b0/recordings?filter=ff5c57b6ed2be106f1ea85e57140fec16b4d51f5fee6aabb1d66950bcbfb4742&player=1&session=7WzknO24Dx&visitor=vesDHD7SFx) this user had bound the url string to a value that evaluated to a number. Possibly the same kind of error for other users before this. We shouldn't fail here in either case, can switch this to safer conversion.

- added a util method in PluginUtils which was earlier returning Object class, but is now returning a casted String.
- this method is a wrapper on the existing method only
- added junit to verify the error in casting in the existing method
- added junit to verify the correct casting behaviour in the new method

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Added junit to test the bug as an exception case
- Added junit to test that bug to show correct behaviour

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-10-19 08:11 UTC, amogh2019 commented
@Nikhil-Nandagopal  @mohanarpit

2022-10-20 04:55 UTC, amogh2019 commented
@subrata71
Could you review and let me know of changes, if any?

2022-10-20 06:19 UTC, subrata71 commented
Hi @amogh2019 
Thanks for raising this PR. I will take a look soon.

2022-10-21 06:26 UTC, subrata71 requested changes

2022-10-21 10:38 UTC, subrata71 commented on app/server/appsmith-interfaces/src/test/java/com/appsmith/external/helpers/PluginUtilsTest.java
> +            log.info("Value of key : k as String casted from Integer is", result);
Other than the above the changes look good to me.

2022-10-24 12:09 UTC, amogh2019 commented on app/server/appsmith-interfaces/src/test/java/com/appsmith/external/helpers/PluginUtilsTest.java
> +            log.info("Value of key : k as String casted from Integer is", result);
compilation error was coming if I just casted data into string.
it only worked after adding the second line.

2022-10-24 12:19 UTC, amogh2019 commented on app/server/appsmith-interfaces/src/test/java/com/appsmith/external/helpers/PluginUtilsTest.java
> +            log.info("Value of key : k as String casted from Integer is", result);
If I just do the casting
assertThrows(ClassCastException.class, () -> { (String) data;}

```
java.lang.Error: Unresolved compilation problems: 
 The method assertThrows(Class[T], Executable) in the type Assertions is not applicable for the arguments (Class[ClassCastException], () -] {})
 String cannot be resolved to a variable
 Syntax error on token ")", AssignmentOperator expected after this token

 at com.appsmith.external.helpers.PluginUtilsTest.([PluginUtilsTest.java:1]
 ```

2022-10-24 17:40 UTC, subrata71 commented on app/server/appsmith-interfaces/src/test/java/com/appsmith/external/helpers/PluginUtilsTest.java
> +            log.info("Value of key : k as String casted from Integer is", result);
> If I introduce a variable, sonar / ide starts giving error

Is it an error or a warning? If it's a warning then it shouldn't be a blocker. @amogh2019

2022-10-25 08:47 UTC, amogh2019 commented on app/server/appsmith-interfaces/src/test/java/com/appsmith/external/helpers/PluginUtilsTest.java
> +            log.info("Value of key : k as String casted from Integer is", result);
not getting a good feeling about it. We okay to have a warning?
Anyways,
Done.

2022-10-25 10:23 UTC, subrata71 commented
/ok-to-test sha=718f766

2022-10-25 10:28 UTC, subrata71 approved these changes
LGTM

2022-10-25 12:56 UTC, merged