task: List v2 virtual list
appsmithorg/appsmith pull request #17716
Opened 2022-10-19 09:25 UTC by ashit-rath

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.

## Description

> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change.

Fixes #17378 

> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-10-19 10:37 UTC, Tooluloope commented on app/client/package.json
> +    "@tanstack/virtual-core": "^3.0.0-beta.18",
Can you please just highlight why we used this Library?

2022-10-19 10:39 UTC, ashit-rath commented on app/client/package.json
> +    "@tanstack/virtual-core": "^3.0.0-beta.18",
Do you want me to leave a comment somewhere in the code?

2022-10-19 22:58 UTC, Tooluloope requested changes
https://user-images.githubusercontent.com/31691737/196819837-eb8c5987-ea61-44a2-b286-6964657cf800.mov

2022-10-19 22:58 UTC, Tooluloope commented on app/client/src/widgets/ListWidgetV2/widget/index.tsx
> +    if (this.props.infiniteScroll && prevProps?.infiniteScroll) {
why the optional chaining  for prevProps

2022-10-19 22:59 UTC, Tooluloope requested changes
Second Observation
https://user-images.githubusercontent.com/31691737/196820038-c62bb742-0961-4fd2-b584-05eef1ba374d.mov

2022-10-19 23:00 UTC, Tooluloope commented on app/client/package.json
> +    "@tanstack/virtual-core": "^3.0.0-beta.18",
Yeah, Probably at the top of `ListWidgetv2/widget/index.tsx` file

2022-10-19 23:02 UTC, Tooluloope commented
Also, it looks like there are a lot of changes that would cause conflict in my task #17480, so I'll wait for this is to be merged

2022-10-20 04:08 UTC, ashit-rath commented on app/client/src/selectors/editorSelectors.tsx
> -      if (parentId === parentWidgetId) {
This makes it much more readable as `parentId === parentWidgetId` seemed very vague at a quick glance

`metaWidget.parentId === parentWidgetId` is much more descriptive.

2022-10-20 04:10 UTC, ashit-rath commented on app/client/src/widgets/ListWidgetV2/widget/propertyConfig.ts
> +      },
We have to do a few more things to ensure infinite scroll does not work with serverside pagination. We would also need to identify the copy for this property. 
So all of these things are to be done separately in a new issue.

2022-10-20 04:17 UTC, ashit-rath commented on app/client/src/widgets/ListWidgetV2/MetaWidgetGenerator.ts
> +        overscan: 2,
https://tanstack.com/virtual/v3/docs/api/virtualizer#overscan

We have a task to calculate this overscan #17558

2022-10-20 04:19 UTC, ashit-rath commented on app/client/src/widgets/ListWidgetV2/widget/index.tsx
> +    if (this.props.infiniteScroll && prevProps?.infiniteScroll) {
`setupMetaWidgets` get called in componentDidMount without passing `prevProps` so it would be undefined.

2022-10-20 04:20 UTC, ashit-rath commented on app/client/src/widgets/ListWidgetV2/widget/index.tsx
> +        this.virtualizer._willUpdate();
Didn't quite get this

2022-10-20 04:21 UTC, ashit-rath commented
> Screen.Recording.2022-10-19.at.23.55.17.mov

The horizontal scroll is a result of the scrollbar taking up a fixed space. This is still under discussion as to how to deal with it.
I'll look into the extra scrollbar that appears.

2022-10-20 07:04 UTC, Tooluloope commented on app/client/src/widgets/ListWidgetV2/widget/index.tsx
> +        this.virtualizer._willUpdate();
`this.virtualizer` is always undefined as it was never initialized in the constructor or anywhere.

Also, I seem not to be able to make `hasTemplateBottomRowChanged()` be true

2022-10-20 22:12 UTC, Tooluloope approved these changes

2022-10-21 03:48 UTC, merged