Feature/change label pos
appsmithorg/appsmith pull request #17726
Opened 2022-10-19 14:44 UTC by adarshlilha

## Description

Changes default label position to TOP for the below widgets:
- Inputs
    - Text Input
    - Phone Input
    - Currency Input
- Select
    - Select
    - TreeSelect
    - MultiSelect
    - MultiTree Select
- DatePicker
- Group Widgets
    - Radio group
    - Switch group
    - Checkbox group

Fixes #17143 
<img width="685" alt="Screenshot 2022-10-19 at 19 00 09" src="https://user-images.githubusercontent.com/13575704/196723901-866c06b7-d887-4c06-ad9d-322ff132d57c.png">

## Type of change
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Does not break the existing tests

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-10-25 16:27 UTC, mohanarpit commented on yarn.lock
> +# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
This diff doesn't look right. Can we please remove this file from the PR?

2022-10-25 21:39 UTC, Tooluloope commented
<img width="683" alt="Screenshot 2022-10-25 at 22 38 43" src="https://user-images.githubusercontent.com/31691737/197887159-db8fc568-75fa-4311-95bf-6c33dfe9e4f3.png">
The deploy preview seems not to work

2022-10-25 21:41 UTC, Tooluloope requested changes

2022-10-25 21:41 UTC, Tooluloope commented on yarn.lock
> +# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
Please fix this file and pull latest release

2022-10-26 08:51 UTC, Tooluloope approved these changes

2022-10-26 08:51 UTC, adarshlilha commented on yarn.lock
> +# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
file removed :)

2022-10-27 10:02 UTC, merged

2022-10-28 05:19 UTC, Tooluloope commented
/ok-to-test sha=22415c9