feat: wrap widgets into a component which listens to content height changes
appsmithorg/appsmith pull request #17729
Opened 2022-10-19 18:15 UTC by ankurrsinghal

- Problem
We know that some of our widgets are dynamic, take for example CheckboxGroup widget, we can add and remove options from the property pane or hook its data to an API. How can we know how much this widget wants to grow in height?

- Solution
What if we wrap each widget in a simple div whose height is auto, so now this div will always have height equal to the widget's height, whatever widget wants to grow or shrink the height of this div will be equal to that. What about the changes in height? We used `ResizeObserver` on this simple div which keep sending us updates whenever a widget wants to change it's height. And then we send these updates to our `updateDynamicHeight` store actions from the BaseWidget.

- Features
This component is very simple, accepts 3 props, maxDynamicHeight, isAutoWithLimits and onHeightUpdate.
- maxDynamic this is used only when isAutoWithLimits is enabled, and adds 2 containers to the div while the inner one sends the height updates and the outer one checks if the max is less than the expected height of the widget, in that case it scrolls.
- onHeightUpdate is a callback function sent from BaseWidget, which actually calls the `updateDynamicHeight` action.

2022-10-19 18:16 UTC, ankurrsinghal commented
/ok-to-test sha=dd12eb3

2022-10-19 18:20 UTC, ankurrsinghal commented
/ok-to-test sha=de40677

2022-10-19 18:33 UTC, riodeuno commented on app/client/src/components/dynamicHeight/DynamicHeightContainer.tsx
> +    console.log("expectedHeightInRows", expectedHeightInRows);
Please remove a missed out `console.log`

2022-10-19 18:35 UTC, ankurrsinghal commented on app/client/src/components/dynamicHeight/DynamicHeightContainer.tsx
> +    console.log("expectedHeightInRows", expectedHeightInRows);
Done

2022-10-19 18:35 UTC, riodeuno reviewed
Please checkout the updates I've made in this component in this PR here: https://github.com/appsmithorg/appsmith/pull/17686

The reason for this, is that when we get a new min or max dynamic height, we need to make sure we need to run the updateDynamicHeight to make sure that the changes are reflected in the UI.

2022-10-19 18:37 UTC, riodeuno commented
@ankurrsinghal I really like the PR's description. It explains what we've done here.
The checklist from the PR template is missing. Can we use the template and add all the current contents into the description section of the template?

2022-10-19 19:00 UTC, ankurrsinghal commented
> @ankurrsinghal I really like the PR's description. It explains what we've done here. The checklist from the PR template is missing. Can we use the template and add all the current contents into the description section of the template?

Done

2022-10-19 19:00 UTC, ankurrsinghal commented
> Please checkout the updates I've made in this component in this PR here: #17686
> 
> The reason for this, is that when we get a new min or max dynamic height, we need to make sure we need to run the updateDynamicHeight to make sure that the changes are reflected in the UI.

Did the corresponding updates!

2022-10-19 19:26 UTC, ankurrsinghal commented
/ok-to-tesh sha=31c9ed4

2022-10-19 19:26 UTC, ankurrsinghal commented
/ok-to-test sha=31c9ed4

2022-10-20 16:49 UTC, rahulramesha approved these changes

2022-10-21 09:44 UTC, Rhitottam commented
/perf-test ref=rhito/feat-create-run-meta-before-test-starts-compare-lt-st-for-prev-runs

2022-10-21 10:56 UTC, Rhitottam commented
/perf-test ref=rhito/feat-create-run-meta-before-test-starts-compare-lt-st-for-prev-runs

2022-10-21 11:17 UTC, Rhitottam commented
/perf-test ref=rhito/feat-create-run-meta-before-test-starts-compare-lt-st-for-prev-runs

2022-10-21 13:53 UTC, Rhitottam commented
/perf-test ref=rhito/feat-create-run-meta-before-test-starts-compare-lt-st-for-prev-runs

2022-10-21 14:58 UTC, Rhitottam commented
/perf-test ref=rhito/feat-create-run-meta-before-test-starts-compare-lt-st-for-prev-runs

2022-10-21 15:36 UTC, Rhitottam commented
/perf-test ref=rhito/feat-create-run-meta-before-test-starts-compare-lt-st-for-prev-runs

2022-10-26 07:54 UTC, ankurrsinghal commented
/ok-to-test sha=c048f52

2022-10-31 05:27 UTC, marks0351 requested changes

2022-10-31 05:27 UTC, marks0351 commented on app/client/src/components/dynamicHeight/DynamicHeightContainer.tsx
> +  }, [observer]);
u can remove observer it will have no effect on the code.

2022-10-31 07:35 UTC, riodeuno commented on app/client/src/components/dynamicHeight/DynamicHeightContainer.test.tsx
> +
@ankurrsinghal Let's rename the folder from `dynamicHeight` to `autoHeight`, and `DynamicHeightContainer` to `AutoHeightContainer`

2022-10-31 07:35 UTC, riodeuno requested changes
Please change the names of the files. A new push to this branch should help with the vercel run as well. @marks0351 also has a comment, please look into that.

2022-10-31 07:44 UTC, ankurrsinghal commented on app/client/src/components/dynamicHeight/DynamicHeightContainer.tsx
> +  }, [observer]);
Done

2022-10-31 07:44 UTC, ankurrsinghal commented on app/client/src/components/dynamicHeight/DynamicHeightContainer.test.tsx
> +
Done

2022-10-31 08:25 UTC, riodeuno approved these changes

2022-10-31 08:26 UTC, riodeuno commented
/ok-to-test sha=5374af1

2022-10-31 10:32 UTC, marks0351 approved these changes

2022-10-31 10:33 UTC, ankurrsinghal commented
/ok-to-test sha=7bf2a79

2022-11-01 08:18 UTC, merged