Added missing JS toggles
appsmithorg/appsmith pull request #17725
Opened 2022-10-19 13:56 UTC by trishitapingolia

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.

## Description

Added JS toggles for:
Phone input regular
-Allow country code change

Currency input regular

- Allow currency change
- Decimals allowed

Fixes # (issue)

#16743 

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-10-20 09:22 UTC, somangshu commented
@trishitapingolia can you please go through the checklist of your PR description while our reviewers look into this

2022-10-21 06:55 UTC, aswathkk requested changes
@trishitapingolia We need to add a validation whenever a property is made JS convertible.

Also, there are some more properties that need to be made JS convertible. Refer [this comment](https://github.com/appsmithorg/appsmith/issues/16743#issuecomment-1246264850) on the same issue.

2022-10-21 06:55 UTC, aswathkk commented on app/client/src/widgets/CurrencyInputWidget/widget/index.tsx
> +              isJSConvertible: true,
@trishitapingolia We need to add a validation here.

2022-10-25 08:46 UTC, trishitapingolia commented
> @trishitapingolia We need to add a validation whenever a property is made JS convertible.
> 
> Also, there are some more properties that need to be made JS convertible. Refer [this comment](https://github.com/appsmithorg/appsmith/issues/16743#issuecomment-1246264850) on the same issue.

I have made the modifications, please review. I am having difficulty in other properties that need to be made js convertible. Can you review and merge this for now?

2022-10-26 08:44 UTC, aswathkk requested changes
@trishitapingolia There's some issue with code formatting. Try using [prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) which will automatically format the code.

2022-10-26 08:44 UTC, aswathkk commented on app/client/src/widgets/CurrencyInputWidget/widget/index.tsx
> +              type: ValidationTypes.NUMBER,
@trishitapingolia The formatting is not proper here. Can you fix that?

2022-10-30 08:09 UTC, trishitapingolia commented
@aswathkk @somangshu can please someone review and merge this as it's the last day of Hacktoberfest.

2022-10-30 08:24 UTC, somangshu commented
Hey @trishitapingolia please do not worry as this is last day of oct. We will still consider the PR and merge it if everything looks good.

Cc @aswathkk

2022-10-30 09:40 UTC, trishitapingolia commented
> Hey @trishitapingolia please do not worry as this is last day of oct. We will still consider the PR and merge it if everything looks good.
> 
> Cc @aswathkk

Ok thanks

2022-10-31 09:13 UTC, aswathkk submitted a review, later dismissed
LGTM

2022-10-31 09:14 UTC, somangshu commented
/ok-to-test sha=28c9c40

2022-10-31 10:48 UTC, aswathkk commented
/ok-to-test sha=6e4937e

2022-10-31 10:52 UTC, somangshu approved these changes

2022-11-01 08:29 UTC, merged