fix: MongoPlugin Update Command : parsing valid document or array of valid documents
appsmithorg/appsmith pull request #17732
Opened 2022-10-19 19:27 UTC by amogh2019

## Description

Fixes #11419

Based on the suggestion : https://github.com/appsmithorg/appsmith/pull/12241#discussion_r844997566
> Hi @devnamrits , this approach has a drawback. If we do this, then we can never validate any input as valid or invalid. e.g. If `this.update` is `"abc"` then this will be parsed as a valid input which is not intended. Essentially this change converts any input into a valid input. However, what we want is to be able to detect if the user input is valid or not. Up until now we have only tried to check if the input is a valid `Document` or not, which in this case is not sufficient since MongoDB 4.2 onwards it also accepts an array of Documents (pipleine) as well. Hence, IMO, the correct approach here should be to parse for two things - (1) valid Document (2) valid array of Documents. To achieve this one good way would be create a new method `parseSafely(fieldName, input., boolean)` along the lines of `parseSafely` method that already exists and use the last parameter to check if we need to validate for array of Documents as well.

- Added a method parseSafelyRawInput : parsing valid document or array of valid documents
- Added junit to check the existing error on the existing parseSafely method
- Added junits to check success and failures for the new method.

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Added junit to check the existing error on the existing parseSafely method
- Added junits to check success and failures for the new method.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-10-19 19:30 UTC, amogh2019 commented
@sumitsum @mojtab23 
Could you review and let me know of changes, if any?

2022-10-19 19:32 UTC, amogh2019 commented
cc @Nikhil-Nandagopal @mohanarpit

2022-10-19 20:00 UTC, sumitsum commented
@amogh2019 thanks for raising this PR. I will be reviewing it. Can you please comment on the issue as well asking for the issue to be assigned to you, post which I can change the issue assignment to reflect your id.

2022-10-24 08:03 UTC, sumitsum requested changes

2022-10-24 08:03 UTC, sumitsum commented on app/server/appsmith-plugins/mongoPlugin/src/test/java/com/external/plugins/utils/MongoPluginUtilsTest.java
> +    void testParseSafelyRawInput_onArrayValues_FailureOnNonJsonValue() {
Great work on the extensive test cases 🥇 :)

2022-10-24 08:03 UTC, sumitsum commented on app/server/appsmith-plugins/mongoPlugin/src/test/java/com/external/plugins/utils/MongoPluginUtilsTest.java
> +
Can you please add a JUnit TC along the lines of `testUpdateManyFormCommand` in `MongoPluginTest.java` for the array based input as well ?

2022-10-24 09:00 UTC, amogh2019 commented on app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/utils/MongoPluginUtils.java
> +        } catch (Exception e) {
Did this change while writing my junits

This exisitng code is written wrong.
Existing code expected that a JsonParseException would be thrown,
if an incorrect json string is passed in document.parse
While writing my junit, void testParseSafely_FailureOnArrayValues() {, verified that this was not happening,
and so made the change accordingly to the generic exception.
this will handle future unhandled exceptions as well.
and will always return the AppsmithException as tested in the junit

2022-10-24 09:02 UTC, amogh2019 commented on app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/utils/MongoPluginUtils.java
> +    public static Object parseSafelyRawInput(String fieldName, String input){
missed adding, just changed the singature on that class but not the name,
will do

2022-10-24 09:03 UTC, amogh2019 commented on app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/utils/MongoPluginUtils.java
> +    public static Object parseSafelyRawInput(String fieldName, String input){
i dont think this was required
but will change, not much effort

2022-10-24 09:06 UTC, amogh2019 commented on app/server/appsmith-plugins/mongoPlugin/src/test/java/com/external/plugins/utils/MongoPluginUtilsTest.java
> +    void testParseSafelyRawInput_Success() {
will do

2022-10-24 09:06 UTC, amogh2019 commented on app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/utils/MongoPluginUtils.java
> +                JSONArray jsonArray = new JSONArray(input);
will do

2022-10-24 09:06 UTC, amogh2019 commented on app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/utils/MongoPluginUtils.java
> +                List<Document> jsonList = new ArrayList<>();
will do

2022-10-24 09:08 UTC, amogh2019 commented on app/server/appsmith-plugins/mongoPlugin/src/test/java/com/external/plugins/utils/MongoPluginUtilsTest.java
> +
There is a running PR for MongoPluginTest.java refector.
https://github.com/appsmithorg/appsmith/pull/17633
If i make a change now, it will require a refactor there as well.
Will make this change once all these changes are merged.

2022-10-24 09:26 UTC, amogh2019 commented on app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/utils/MongoPluginUtils.java
> +    public static Object parseSafelyRawInput(String fieldName, String input){
done

2022-10-24 09:26 UTC, amogh2019 commented on app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/utils/MongoPluginUtils.java
> +    public static Object parseSafelyRawInput(String fieldName, String input){
done

2022-10-24 09:26 UTC, amogh2019 commented on app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/utils/MongoPluginUtils.java
> +                JSONArray jsonArray = new JSONArray(input);
done

2022-10-24 09:26 UTC, amogh2019 commented on app/server/appsmith-plugins/mongoPlugin/src/test/java/com/external/plugins/utils/MongoPluginUtilsTest.java
> +    void testParseSafelyRawInput_Success() {
done

2022-10-25 11:58 UTC, amogh2019 commented
@sumitsum

2022-10-27 12:37 UTC, amogh2019 commented
@mohanarpit @Nikhil-Nandagopal  Could you add more reviewers?
Sorry for pushing for this, but hacktoberfest will be ending on 31oct and then this contribution of mine won't be counted

2022-10-27 13:55 UTC, sumitsum commented
@amogh2019 apologies for delay, I was OOO. Reviewing it now.

2022-10-27 14:15 UTC, sumitsum commented on app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/utils/MongoPluginUtils.java
> +            new JSONObject(input);
@amogh2019 within the `parseSafely` method we are already check the validity of input using `Document.parse()` - wouldn't it do the same thing - i.e checking if the input string is malformed ?

2022-10-27 14:20 UTC, sumitsum commented on app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/utils/MongoPluginUtils.java
> +        } catch (Exception e) {
@amogh2019 instead of handling for generic exception can you please mention both the specific exceptions like `(Type1Exception | Type2Exception e) {...}` - reason being that we don't want to handle all the exceptions that way it is handled here. The reason why we have shied away from using generic exceptions is that we want to handle specific exceptions differently wherever applicable.

2022-10-27 14:21 UTC, sumitsum commented on app/server/appsmith-plugins/mongoPlugin/src/test/java/com/external/plugins/utils/MongoPluginUtilsTest.java
> +
Can you please create GitHub issue to track this change i.e. to add a JUnit TC once this PR is merged ? Please share the issue URL here as well.

2022-10-27 14:41 UTC, amogh2019 commented on app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/utils/MongoPluginUtils.java
> +            new JSONObject(input);
done

2022-10-27 14:42 UTC, amogh2019 commented on app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/utils/MongoPluginUtils.java
> +        } catch (Exception e) {
done

2022-10-27 14:51 UTC, amogh2019 commented on app/server/appsmith-plugins/mongoPlugin/src/test/java/com/external/plugins/utils/MongoPluginUtilsTest.java
> +
https://github.com/appsmithorg/appsmith/issues/17919

2022-10-27 14:51 UTC, amogh2019 commented
addressed review comments

2022-10-27 15:04 UTC, sumitsum submitted a review, later dismissed

2022-10-27 15:04 UTC, sumitsum commented
@amogh2019 Approved it.

2022-10-27 15:05 UTC, sumitsum commented
/ok-to-test sha=50204ee

2022-10-27 16:30 UTC, sumitsum commented
@amogh2019 can you please rebase with release and update the PR ? - since this may improve changes of CI run passing.

2022-10-27 16:44 UTC, amogh2019 commented
Hi,
the branch is up-to-date with upstream release,
and is This branch is [4 commits ahead](https://github.com/amogh2019/appsmith/compare/appsmithorg:appsmith:release...fix/mongo_update_formdataparsing) of appsmithorg:release.

2022-10-28 06:12 UTC, amogh2019 commented
Can we merge? @sumitsum

2022-10-28 10:34 UTC, sumitsum commented
@amogh2019 can you please pull again from the remote release into your branch (rebase) and update the PR ? Some changes have been pushed in recently to fix CI failures. Also, would it be possible for you to provide my account with push / edit access to your PR branch so that I may do such kind updates if required (in case you are not accessible) ?

2022-10-28 11:12 UTC, sumitsum commented
@amogh2019 seems like I am able to update the PR directly. I have updated the PR with the latest release. I will re-run the CI now.

2022-10-28 11:32 UTC, sumitsum commented
/ok-to-test sha=db96cad

2022-10-28 11:53 UTC, sumitsum approved these changes

2022-10-28 13:58 UTC, sumitsum commented
/ok-to-test sha=db96cad

2022-10-28 15:36 UTC, amogh2019 commented
not sure why ui-test-result is failing

2022-10-30 11:37 UTC, merged