Fix: Add JS for icon property in buttons
appsmithorg/appsmith pull request #17779
Opened 2022-10-20 15:11 UTC by sanjus-robotic-studio

## Description

Add JS functionality for icon in buttons, button group, menu button

Fixes #11142

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Tested Manually

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-10-21 04:33 UTC, Rhitottam commented
/perf-test ref=rhito/feat-create-run-meta-before-test-starts-compare-lt-st-for-prev-runs

2022-10-22 02:48 UTC, Rhitottam commented
/perf-test ref=rhito/feat-create-run-meta-before-test-starts-compare-lt-st-for-prev-runs

2022-10-25 06:22 UTC, sanjus-robotic-studio commented
Hey when will this PR be accepted

2022-10-25 11:38 UTC, sanjus-robotic-studio commented
Hey @Tooluloope Can you approve the changes

2022-10-25 12:10 UTC, sanjus-robotic-studio commented
@somangshu Can you review this too?

2022-10-25 12:15 UTC, somangshu requested changes
LGTM apart from one small change

2022-10-25 12:15 UTC, somangshu commented on app/client/src/widgets/BaseInputWidget/widget/index.tsx
> +            isJSConvertible: true,
I dont see where its requested to change the label style to have JS convertible option @sanjus-robotic-studio 

cc @dilippitchika kindly confirm this soon

2022-10-25 12:17 UTC, somangshu commented
@sanjus-robotic-studio while I am looking into the above query, can you merge with latest release branch

2022-10-25 12:19 UTC, sanjus-robotic-studio commented on app/client/src/widgets/BaseInputWidget/widget/index.tsx
> +            isJSConvertible: true,
Hey @somangshu, that commit is from the previous issue #17631. But accidentally it got added to this PR is there any way I can remove that commit

2022-10-25 12:20 UTC, Tooluloope commented on app/client/src/widgets/BaseInputWidget/widget/index.tsx
> +            isJSConvertible: true,
From this comment https://github.com/appsmithorg/appsmith/issues/11142#issuecomment-1277496781 it should only be icons.

2022-10-25 12:24 UTC, Tooluloope commented on app/client/src/widgets/BaseInputWidget/widget/index.tsx
> +            isJSConvertible: true,
<img width="306" alt="Screenshot 2022-10-25 at 13 22 12" src="https://user-images.githubusercontent.com/31691737/197771722-357127e5-b3f9-4257-8cb7-9dc73abf0f72.png">
Although looking at it now, Select family and all other Widgets have JS convertible  for Label Style except Input family

2022-10-25 12:28 UTC, sanjus-robotic-studio commented on app/client/src/widgets/BaseInputWidget/widget/index.tsx
> +            isJSConvertible: true,
@Tooluloope but I have already created a PR and it got merged for that issue. the pr no is https://github.com/appsmithorg/appsmith/pull/17631

2022-10-25 12:30 UTC, Tooluloope commented on app/client/src/widgets/BaseInputWidget/widget/index.tsx
> +            isJSConvertible: true,
oh, got it.
Thanks for clarifying that.

2022-10-25 12:30 UTC, Tooluloope approved these changes

2022-10-25 12:33 UTC, Tooluloope commented
/ok-to-test sha=a4daf2a

2022-10-25 12:35 UTC, somangshu commented on app/client/src/widgets/BaseInputWidget/widget/index.tsx
> +            isJSConvertible: true,
@sanjus-robotic-studio please remove the change from here; remerge release branch; and push a new commit;

we cant remove the old commit as such. Post that we will be good to go

2022-10-25 12:37 UTC, sanjus-robotic-studio commented on app/client/src/widgets/BaseInputWidget/widget/index.tsx
> +            isJSConvertible: true,
Hey @somangshu, I have done that and now it is removed

2022-10-25 13:19 UTC, somangshu approved these changes
LGTM

2022-10-25 13:20 UTC, somangshu commented
@sanjus-robotic-studio thanks for the changes, the tests are running right now; Ill merge this by tomorrow. 🙏

2022-10-25 13:24 UTC, sanjus-robotic-studio commented
Sure, Thanks

2022-10-26 09:45 UTC, merged