Fix/entity name coincide issue 1396
appsmithorg/appsmith pull request #1781
Opened 2020-11-18 10:30 UTC by jsartisan

Fixes #1770

2020-11-18 14:55 UTC, jsartisan commented
@hetunandu The test of Pages_spec.js is fixed in the `fix/truncated-page-name-in-appviewer-issue-1597` branch. So you can ignore those test cases for now in this branch. I'll run the test cases in this branch again after that branch is merged in release.

2020-11-19 07:22 UTC, hetunandu commented on app/client/src/sagas/selectors.tsx
> +
No need for this selector as it is already defined in `/selectors/dataTreeSelectors`

2020-11-19 07:25 UTC, hetunandu commented on app/client/src/pages/Editor/DataSourceEditor/FormTitle.tsx
> +  const evalTreeKeyNames = Object.keys(evalTree);
This can be a new selector that always returns back with these names directly

2020-11-19 07:27 UTC, hetunandu commented on app/client/src/utils/helpers.tsx
> +  if (keywords.indexOf(name) > -1 || invalidNames.indexOf(name) > -1) {
searching through an array with indexOf is slow. Instead consider doing a map lookup

2020-11-19 07:27 UTC, hetunandu requested changes
Few refactors

2020-11-19 09:28 UTC, jsartisan commented
@hetunandu Made the requested changes.

2020-11-20 07:45 UTC, jsartisan commented
@hetunandu Converted array lookup to map lookup.

2020-11-20 07:49 UTC, hetunandu requested changes

2020-11-20 07:49 UTC, hetunandu commented on app/client/src/utils/helpers.tsx
> +  invalidNames: { [key: string]: any },
```suggestion
  invalidNames: Record<string, any>,
```

2020-11-20 07:49 UTC, hetunandu commented on app/client/src/utils/helpers.tsx
> +  const keywords = {
Move to a constants file

2020-11-20 07:49 UTC, hetunandu commented on app/client/src/utils/helpers.tsx
> +};
Not needed anymore right?

2020-11-20 12:17 UTC, hetunandu approved these changes

2020-11-23 09:27 UTC, merged