feat: Enabled fetch
appsmithorg/appsmith pull request #17832
Opened 2022-10-23 14:03 UTC by arunvjn

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.

## Description

> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change.

Fixes # (issue)

> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.
> Delete anything that is not important

- Manual
- Jest
- Cypress

### Test Plan
> Add Testsmith test cases links that relate to this PR

### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-10-27 10:06 UTC, Rishabh-Rathod commented on app/client/package.json
> +    "whatwg-fetch": "^3.6.2",
@arunvjn Could you please help in understanding where is `whatwg-fetch` library is being used?

2022-10-27 10:08 UTC, arunvjn commented on app/client/package.json
> +    "whatwg-fetch": "^3.6.2",
It is used inside `fetch-intercept`

2022-10-27 10:11 UTC, Rishabh-Rathod commented on app/client/src/workers/evaluate.ts
> +  interceptAndOverrideHttpRequest();
[Out of scope] Just thinking out load, If we create a polyfill for `setInterval` and `clearInterval` using setTimeout like https://codesandbox.io/s/vbfgz?file=/src/index.js:367-377 will that help in resolving callback unable to access outer variables ( closure values ) issue?

2022-10-28 06:48 UTC, sharat87 requested changes

2022-10-28 06:48 UTC, sharat87 commented on app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/JsFunctionExecution/fetch_xhr_spec.ts
> +describe("Tests fetch and xhr calls", () => {
The title mentions XHR, but I don't see tests on XHR. There's two tests, but both are calling `fetch` only. Can we please add a test or two for XHR too?

2022-10-28 06:48 UTC, sharat87 commented on app/client/package.json
> +    "whatwg-fetch": "^3.6.2",
Isn't that needed only in environmens where `fetch` isn't available? Like old NodeJS versions? The `attach` call checks if `fetch` is already available in `env`, and if not, only then requires this module. From https://github.com/mlegenhausen/fetch-intercept/blob/develop/src/attach.js#L43.

In our case, `env` will be `self`, from https://github.com/mlegenhausen/fetch-intercept/blob/develop/src/browser.js#L4.

So, we should be okay not needing this dependency, no?

2022-10-28 06:48 UTC, sharat87 commented on app/client/src/workers/HTTPRequestOverride.ts
> +      const request = new Request(args[0], { ...args[1], credentials: "omit" });
Curious, we are assuming `args` will be two arguments at least. What happens when there's a single request object passed here? How does it still work? 🤔

2022-10-28 06:48 UTC, sharat87 commented on app/client/src/workers/HTTPRequestOverride.ts
> +  self.XMLHttpRequest.prototype = XHRPrototype;
Can you elaborate a little on this please? I see two problems.

One, we are overriding the `withCredentials` to `false` in the constructor, but it can be changed before calling `open`, right? Like this:

```javascript
const xhr = new XMLHttpRequest();
xhr.open("GET", '/api/v1/applications/new', true);
xhr.withCredentials = true;
xhr.send();
```

This will still be possible, right?

Two, the original `XMLHttpRequest` class is still accessible here, with `XMLHttpRequest.prototype.constructor`. Check this out:
![Screenshot 2022-10-28 at 12 16 11 PM](https://user-images.githubusercontent.com/120119/198521385-51a2f25b-d967-4cca-b6b5-bf6e5834202e.png)

2022-10-30 10:10 UTC, arunvjn commented on app/client/src/workers/HTTPRequestOverride.ts
> +      const request = new Request(args[0], { ...args[1], credentials: "omit" });
fetch and Request constructor accepts similar arguments i.e both could take a url string or Request object as the first param and an options object as a second param. 
The override here always reconstructs a new Request object whose credentials attribute is set to 'omit'. 
The second param in both `Request` and `fetch` is always the options object. We override the 'credentials' attribute in this options object.

2022-10-30 10:11 UTC, arunvjn commented on app/client/src/workers/HTTPRequestOverride.ts
> +  self.XMLHttpRequest.prototype = XHRPrototype;
Yes, nice catch :). We need to make this property immutable.

2022-10-30 10:14 UTC, sharat87 commented on app/client/src/workers/HTTPRequestOverride.ts
> +      const request = new Request(args[0], { ...args[1], credentials: "omit" });
Yeah, that's where my question comes.

> both could take a url string or Request object as the first param and an options object as a second param

This means that `args` can be `[url: string, request: Record<string, unknown>]` or `[request: Record<string, unknown>]`, right?

But in line 16, we are using `args` as if we already know that it's the former, and not the latter. I'm wondering if that assumption is true here. 🙂

2022-10-30 10:17 UTC, sharat87 commented on app/client/src/workers/HTTPRequestOverride.ts
> +  self.XMLHttpRequest.prototype = XHRPrototype;
Instead, I'm wondering if we should just override the `open` method in `XMLHttpRequest`. Like this:

```javascript
// UNTESTED CODE
{
  const originalOpen = XMLHttpRequest.open;
  XMLHttpRequest.open = (...args) => {
    this.withCredentials = false;
    return originalOpen.apply(this, args);
  };
}
```

May be simpler? 🤔

2022-10-30 10:24 UTC, arunvjn commented on app/client/src/workers/HTTPRequestOverride.ts
> +      const request = new Request(args[0], { ...args[1], credentials: "omit" });
fetch's args could be `[ url: string, options: Record<string, unknown> ] `or `[ request: Request, options? : Record<string, unknown> ]` 

[Request](https://developer.mozilla.org/en-US/docs/Web/API/Request/Request) constructor args `[ url: string, options?: Record<string, unknown> ] ` or `[ request: Request, options? : Record<string, unknown> ]`. 

Second argument if provided will always be the options object that contains the 'credentials' attribute. 

What I am doing here is always creating a new Request using arg[0] (url or Request) and passing default options from arg[1] after overriding the credentials attribute.

2022-10-30 10:29 UTC, arunvjn commented on app/client/src/workers/HTTPRequestOverride.ts
> +  self.XMLHttpRequest.prototype = XHRPrototype;
^^ This should work.  It could solve the 2nd issue you mentioned as well.

2022-10-30 10:38 UTC, sharat87 commented on app/client/src/workers/HTTPRequestOverride.ts
> +  self.XMLHttpRequest.prototype = XHRPrototype;
I'm hoping `send` is the _only_ way to actually execute a request. See if there's other ways to execute it, we'll have to patch those up as well. 🙂

2022-10-30 10:49 UTC, arunvjn commented on app/client/src/workers/evaluate.ts
> +  interceptAndOverrideHttpRequest();
This might actually work. We could definitely try this out.

2022-10-30 20:00 UTC, arunvjn commented on app/client/src/workers/HTTPRequestOverride.ts
> +  self.XMLHttpRequest.prototype = XHRPrototype;
Just found out that we cannot disable same origin cookies in XHR even with `withCredentials: false` . Reverting the changes around XHR.

2022-10-30 20:05 UTC, arunvjn commented on app/client/package.json
> +    "whatwg-fetch": "^3.6.2",
Ah okay, I guess I looked at the source code of an older version of `fetch-intercept`.

2022-10-30 20:06 UTC, arunvjn commented on app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/JsFunctionExecution/fetch_xhr_spec.ts
> +describe("Tests fetch and xhr calls", () => {
Changed the file and the spec name

2022-10-31 02:45 UTC, sharat87 commented on app/client/src/workers/HTTPRequestOverride.ts
> +  self.XMLHttpRequest.prototype = XHRPrototype;
I see that we are disabling XHR completely. Does this mean that including any libraries that need XHR to run, won't be supported? 🤔 😞

Do you think we can create a custom XHR class, that's actually powered by `fetch` under the hood? Or is that too much? 🫤

2022-10-31 05:45 UTC, arunvjn commented on app/client/src/workers/HTTPRequestOverride.ts
> +  self.XMLHttpRequest.prototype = XHRPrototype;
Yes, libraries that needs XHR cannot be run. 
Custom implementation of XHR could be attempted but synchronous request feature via XHR might be slightly complicated to implement.

2022-10-31 09:10 UTC, sharat87 commented on app/client/src/workers/HTTPRequestOverride.ts
> +  self.XMLHttpRequest.prototype = XHRPrototype;
Oh yeah, sync can't be done. But I doubt a very many libraries use that. Sync API calls not being possible, can actually be a good thing for us. May be not for v1, but let's see if we can create such an XHR. I suspect a _lot_ of libraries will need this instead of `fetch`.

2022-10-31 10:41 UTC, arunvjn commented
/ok-to-test sha=516b447

2022-11-01 02:07 UTC, sharat87 reviewed
Minor changes.

2022-11-01 02:07 UTC, sharat87 commented on app/client/src/workers/HTTPRequestOverride.ts
> +
This isn't needed may be?

```suggestion
```

2022-11-01 02:07 UTC, sharat87 commented on app/client/src/workers/evaluate.ts
> +      result = (1, eval)(script);
This is a non-obvious piece of code. Can you add a comment with a link to MDN on what this does, and why this is important please?

2022-11-01 09:26 UTC, arunvjn commented on app/client/src/workers/HTTPRequestOverride.ts
> +
Done

2022-11-02 04:11 UTC, sharat87 commented on app/client/src/workers/HTTPRequestOverride.ts
> +      const request = new Request(args[0], { ...args[1], credentials: "omit" });
Really sorry, but I'm afraid my brain is back on this.

In the signatures you gave for `fetch` function, consider `[ request: Request, options? : Record<string, unknown> ]`. The `options?` means that the second argument is optional, right? That's what the `?` means right? If yes, then `args[1]` will de `undefined`, and this line will throw an error right?

(This is the problem I'm trying to hint at earlier also, but I confused myself. 😅)

2022-11-02 09:06 UTC, sharat87 commented on app/client/src/workers/HTTPRequestOverride.ts
> +      const request = new Request(args[0], { ...args[1], credentials: "omit" });
Ah, TIL. I recall seeing an NPE from that, but I can't reproduce it now, I was probably not drunk enough at the time.

Cool, thanks.

2022-11-02 09:08 UTC, sharat87 approved these changes
Thank you @arunvjn for sticking with me and tolerating my back-and-forth. I think this is now in a good shape. Please take it off 🛫.

2022-11-03 09:45 UTC, sharat87 commented on app/client/src/workers/HTTPRequestOverride.ts
> +      }
@arunvjn, can you give me a brief on the significance of this block here please? 🤔

2022-11-03 09:51 UTC, arunvjn commented on app/client/src/workers/HTTPRequestOverride.ts
> +      }
Currently, as we type away on JS Editor, we do a dry run(execute) of the function that is being edited to determine its nature. We mark a function async if it uses an Appsmith function or returns a promise. The function that is marked "async" is then disabled on data fields in property pane. `IS_ASYNC ` flag which gets set marks the function that contains fetch call as 'async'.

We will soon be removing this dry run. I believe there is a draft PR for it already.

2022-11-03 10:18 UTC, arunvjn commented
/ok-to-test sha=8898a89

2022-11-03 10:30 UTC, sharat87 commented on app/client/src/workers/HTTPRequestOverride.ts
> +      }
Thank you. Does this dry run also call `eval`, or is it a static AST traversal? Can you point me to the place in code where this happens please? 🙂

2022-11-03 10:35 UTC, arunvjn commented on app/client/src/workers/HTTPRequestOverride.ts
> +      }
Here's the function. https://github.com/appsmithorg/appsmith/blob/d7fc4784911cac1a1846d4624012070195c730b0/app/client/src/workers/Evaluation/evaluate.ts#L403

We simply call the JSObject's edited function. No eval or AST. Note that this method is fairly primitive and doesn't work that well.

2022-11-13 19:41 UTC, AnandiKulkarni commented
@arunvjn when you give wrong api name it remain in executing mode for really long time, there is no error displayed or no error catched, no linting errors for some places such as if we write wrong method .jason, also expecting autocomplete for .json or res.text or res.blob
trycatch: async () => {
try{
	return fetch('https://dmmy.restapiexample.com/api/v1/employees').then(res=>res.json()).then().then((res2)=>{
			return res2.data
		})
}catch(error){
console.error(error.message)
}}

2022-11-14 10:18 UTC, arunvjn commented
> @arunvjn Sometimes getting error while JSobject function is mapped to table. JSobject function has fetch method
> 
>  Screen.Recording.2022-11-14.at.2.02.03.PM.mov

Are you able to replicate it consistently ? 
Could you also try replicating it with appsmith's mock users API ?

2022-11-14 11:25 UTC, AnandiKulkarni commented
> > @arunvjn Sometimes getting error while JSobject function is mapped to table. JSobject function has fetch method
> > Screen.Recording.2022-11-14.at.2.02.03.PM.mov
> 
> Are you able to replicate it consistently ? Could you also try replicating it with appsmith's mock users API ?

@arunvjn  yes It worked with Github api, it seems it is api issue

2022-11-27 21:00 UTC, arunvjn commented
/ok-to-test sha=ca343d1

2022-11-28 08:18 UTC, arunvjn commented
/ok-to-test sha=19d4990

2022-11-28 08:26 UTC, arunvjn commented
/ok-to-test sha=3f1f2d4

2022-11-29 11:36 UTC, sharat87 approved these changes

2022-11-29 17:09 UTC, arunvjn commented
/ok-to-test sha=582bef3

2022-11-30 06:04 UTC, Aishwarya-U-R commented
/ok-to-test sha=2dd4439

2022-11-30 07:29 UTC, arunvjn commented
/ok-to-test sha=07401c8

2022-11-30 10:34 UTC, Aishwarya-U-R reviewed
Cypress looks good! 
**Note:** Not all cases from respective TestSmith is covered in Cypress since the coverage done via script is enough to proceed.

2022-11-30 18:24 UTC, Rishabh-Rathod approved these changes
LGTM

2022-11-30 19:58 UTC, arunvjn commented
/ok-to-test sha=a911372

2022-11-30 21:58 UTC, merged

2022-12-09 11:15 UTC, JhouXerox commented
<img width="1827" alt="image" src="https://user-images.githubusercontent.com/24403596/206690328-292d3068-d51c-446e-b431-d8d697966b91.png">
can't get http code in res