feat: Feature to have widget features
appsmithorg/appsmith pull request #17852
Opened 2022-10-24 20:35 UTC by riodeuno

## Description

- [ ] Adds structure for adding widget features
- [ ] Currently added details for the auto height feature

Fixes # TBD

## Type of change
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
- Jest PENDING

### Test Plan
NA

### Issues raised during DP testing
NA

## Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-10-24 20:39 UTC, riodeuno commented on app/client/src/utils/WidgetFeatures.ts
> +export enum RegisteredWidgetFeatures {
Split this file (unless this gives us a cyclic dependency errors) and add unit tests.

2022-10-26 05:16 UTC, marks0351 commented on app/client/src/constants/WidgetConstants.tsx
> +  MAX_HEIGHT_IN_ROWS: 9000,
can we add comments why 9000 and 4?

2022-10-26 06:55 UTC, marks0351 requested changes

2022-10-26 07:07 UTC, riodeuno commented on app/client/src/utils/WidgetFeatures.ts
> +  const _value: number = parseInt(value as string, 10);
No, this is the [parseInt's second parameter (base or radix)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt). We can also use hex or binary, etc, as well.

2022-10-26 07:07 UTC, riodeuno commented on app/client/src/utils/WidgetFeatures.ts
> +  if (isNaN(_value) || _value < 4) {
This one should be `WidgetHeightLimits.MIN_HEIGHT`. I'll fix this.

2022-10-30 19:35 UTC, riodeuno commented on app/client/src/utils/WidgetFeatures.ts
> +export enum RegisteredWidgetFeatures {
Adding unit tests, but we won't split this in this PR.

2022-10-30 19:37 UTC, riodeuno commented on app/client/src/utils/WidgetFeatures.ts
> +export enum RegisteredWidgetFeatures {
Task created: https://github.com/appsmithorg/appsmith/issues/17965

2022-11-06 07:52 UTC, riodeuno commented
/ok-to-test sha=b2e6e71

2022-11-08 09:37 UTC, ankurrsinghal commented
/ok-to-test sha=bb390fe

2022-11-10 00:10 UTC, marks0351 submitted a review, later dismissed

2022-11-14 08:58 UTC, riodeuno commented
/ok-to-test sha=ce39bff

2022-11-16 20:46 UTC, ankurrsinghal commented
/ok-to-test sha=bb7ff70

2022-11-17 08:12 UTC, marks0351 approved these changes

2022-11-17 20:34 UTC, merged