feat: Ability to disable vertical resize handles
appsmithorg/appsmith pull request #17851
Opened 2022-10-24 20:24 UTC by riodeuno

## Description
- [ ] This feature adds ability to disable vertical resizing of widgets by disabling the handles

Fixes # TBD

## Type of change
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
- Manual
- Jest
- Cypress

### Test Plan
TBD

### Issues raised during DP testing
NA

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [NA] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-10-25 13:23 UTC, Rhitottam commented
/perf-test ref=rhito/feat-upload-run-artificats-to-s3

2022-10-25 15:34 UTC, Rhitottam commented
/perf-test ref=rhito/feat-upload-run-artificats-to-s3

2022-10-25 19:07 UTC, rahulramesha commented on app/client/src/components/editorComponents/ResizableUtils.tsx
> +export function isHandleResizeAllowed(
NIT: I can see that we are using this is used to only indicate the dots. Could we possibly rename the method because it sounded a bit misleading as if the value is used to restrict someone from resizing.

2022-10-26 10:37 UTC, Rhitottam commented
/perf-test ref=rhito/feat-upload-run-artificats-to-s3

2022-10-27 06:48 UTC, marks0351 requested changes

2022-10-27 06:48 UTC, marks0351 commented on app/client/src/components/editorComponents/ResizableUtils.tsx
> +  if (direction === ReflowDirection.TOP || direction === ReflowDirection.BOTTOM)
do corner resize handles need special handling ?
just want to make sure that we have not missed them.

2022-10-27 06:48 UTC, marks0351 commented on app/client/src/resizable/resize/index.tsx
> +          $prevents={pointerEvents}
any reason for the dollar? looks like a new/odd convention

2022-10-27 06:48 UTC, marks0351 commented on app/client/src/resizable/resizenreflow/index.tsx
> +        onStart={() => {
should we have this function declared before the map it creates new function for each handle.

2022-10-27 06:52 UTC, riodeuno commented on app/client/src/components/editorComponents/ResizableUtils.tsx
> +  if (direction === ReflowDirection.TOP || direction === ReflowDirection.BOTTOM)
That's a point we've considered. Right now, we don't need to consider the corner resize handles and I don't forsee a scenario where we would as the resizable component today only handles vertical or horizontal resize. This means that if only horizontal resize is available, corner resize will only resize horizontally. If both are disabled, the resize handles will not show up at all.

2022-10-27 06:52 UTC, riodeuno commented on app/client/src/components/editorComponents/ResizableComponent.tsx
> +  const isVerticalResizeEnabled = useMemo(() => {
Yep, it was necessary when used with dynamic height. We can remove it for now.

2022-10-27 06:53 UTC, riodeuno commented on app/client/src/components/editorComponents/ResizableUtils.tsx
> +export function isHandleResizeAllowed(
This function is agnostic of its usage. So, we're using it for dots today, but it could be used for other scenarios as well. I'd like to keep this agnostic, what do you think?

2022-10-27 06:59 UTC, riodeuno commented on app/client/src/resizable/resizenreflow/index.tsx
> +        onStart={() => {
Yes absolutely, great point! This is however outside the scope of this PR. Would you mind creating a task for this?

2022-10-31 08:34 UTC, riodeuno commented
/ok-to-test sha=fde1023

2022-10-31 09:03 UTC, marks0351 approved these changes

2022-10-31 09:08 UTC, rahulramesha commented on app/client/src/components/editorComponents/ResizableComponent.tsx
> +  const isVerticalResizeEnabled = useMemo(() => {
@riodeuno this still seems to be memoized

2022-10-31 09:12 UTC, riodeuno commented on app/client/src/components/editorComponents/ResizableComponent.tsx
> +  const isVerticalResizeEnabled = useMemo(() => {
Right, fixing it now. ... and done.

2022-10-31 09:16 UTC, marks0351 approved these changes

2022-11-05 17:30 UTC, riodeuno commented
/ok-to-test sha=da73e18

2022-11-08 12:17 UTC, ankurrsinghal commented
/ok-to-test sha=999e223

2022-11-12 06:30 UTC, riodeuno commented
/ok-to-test sha=3aab4ea

2022-11-16 10:50 UTC, ankurrsinghal commented
/ok-to-test sha=3209505

2022-11-17 16:36 UTC, merged