fix: Execute api pagination fix
appsmithorg/appsmith pull request #17886
Opened 2022-10-26 10:21 UTC by vaibh1297

## Description

> Url encoding added for pagination cases.

Fixes #16202 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manual
- Unit Testing

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-10-31 12:07 UTC, mohanarpit commented on app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java
> +//                    datasourceConfiguration.setUrl(URLDecoder.decode(actionConfiguration.getNext(), StandardCharsets.UTF_8));
Please don't leave commented code in the code base. Makes it much harder for future developers to read & understand the code base.

2022-10-31 12:09 UTC, mohanarpit commented on app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java
> +                String[] a = queryParam.split("=");
Suggestion to use a better variable name. As a rule of thumb, please use minimum 4 characters to define a variable name. At any point, if you find yourself using a variable name less than 4 characters, please reconsider. 

At this point in the code, I don't know what `a` is or what it represents.

2022-10-31 12:13 UTC, mohanarpit commented on app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java
> +                new Property("Authorization","Basic TmlraGlsLU5hbmRhZ29wYWw6ODJjY2ZlMDljN2M4MDU5M2VkOTRjZTI1OTA0OTEyYmQ1OTA0NWJmNA=="),
What API key is this? I hope this is not your API key for Github. If yes, please remove it & immediately change the key because this is a security issue.

2022-10-31 12:14 UTC, mohanarpit commented on app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java
> +        String url = "https://api.github.com/orgs/appsmithorg/issues?filter=all&state=open&labels=UI Builders Pod&pulls=true&per_page=100&page=2";
Nit: Is it necessary for us to use a Github endpoint? Can we not hit our mock-api endpoint for testing purposes?

2022-10-31 12:17 UTC, mohanarpit commented on app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java
> +        String actionId = "634f0dcee577f13a234483a2";
Can you help me understand what `actionId` is this? Are we sure that this will NEVER change?

2022-11-18 08:20 UTC, sumitsum requested changes

2022-11-18 08:20 UTC, sumitsum commented on app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java
> +                    assertEquals(3,body.size());
Can you please add a check here to see that we have hit the correct URL with the correct query params ?

2022-11-18 08:20 UTC, sumitsum commented on app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java
> +        Param param = new Param();
Can we remove this since we don't seem to be using the `param` variable anywhere ? Please mention here in case it is being used anywhere.

2022-11-18 08:20 UTC, sumitsum commented on app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java
> +        String actionId = "6363b463274d262e00edc1c5";
APMU, we don't need to set or use the `actionId` for this test case. Can you please check if remvoing the `actionId` is ok for this test case ?

2022-11-18 08:20 UTC, sumitsum commented on app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java
> +    public void testExecuteApiWithPaginationForNextUrl() {
Please check once if the points mentioned above apply for this test case as well.

2022-11-21 00:55 UTC, vaibh1297 commented on app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java
> +//                    datasourceConfiguration.setUrl(URLDecoder.decode(actionConfiguration.getNext(), StandardCharsets.UTF_8));
done

2022-11-21 00:55 UTC, vaibh1297 commented on app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java
> +                String[] a = queryParam.split("=");
done

2022-11-21 00:55 UTC, vaibh1297 commented on app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java
> +
done

2022-11-21 00:55 UTC, vaibh1297 commented on app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java
> +import com.appsmith.external.models.*;
done

2022-11-21 00:55 UTC, vaibh1297 commented on app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java
> +                new Property("Authorization","Basic TmlraGlsLU5hbmRhZ29wYWw6ODJjY2ZlMDljN2M4MDU5M2VkOTRjZTI1OTA0OTEyYmQ1OTA0NWJmNA=="),
done

2022-11-21 00:55 UTC, vaibh1297 commented on app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java
> +        String url = "https://api.github.com/orgs/appsmithorg/issues?filter=all&state=open&labels=UI Builders Pod&pulls=true&per_page=100&page=2";
done

2022-11-21 12:48 UTC, vaibh1297 commented on app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java
> +        String actionId = "6363b463274d262e00edc1c5";
actionId is removed.

2022-11-21 12:49 UTC, vaibh1297 commented on app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java
> +        Param param = new Param();
removed.

2022-11-21 12:49 UTC, vaibh1297 commented on app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java
> +                    responseBuilder.append(keyValue[0]).append("=").append(URLEncoder.encode(keyValue[1], StandardCharsets.UTF_8));
done

2022-11-21 12:50 UTC, vaibh1297 commented on app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java
> +            String[] urlParts = inputUrl.split("\\?");
done

2022-11-21 12:50 UTC, vaibh1297 commented on app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java
> +        private String encodeUrl(String inputUrl) {
done

2022-11-21 12:51 UTC, vaibh1297 commented on app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java
> +        String nextUrl = "https://mock-api.appsmith.com/users?pageSize=1&page=4&mock_filter=abc 11";
done

2022-11-21 12:51 UTC, vaibh1297 commented on app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java
> +                    assertEquals(3,body.size());
done

2022-11-21 12:52 UTC, vaibh1297 commented on app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java
> +    public void testExecuteApiWithPaginationForNextUrl() {
done

2022-11-21 13:36 UTC, vaibh1297 commented on app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java
> +        String actionId = "634f0dcee577f13a234483a2";
This is not required.

2022-11-22 07:44 UTC, sumitsum requested changes

2022-11-22 07:44 UTC, sumitsum commented on app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java
> +            String[] urlParts = decodedUrl.split("\\?");
QQ: Have we added a check anywhere to make sure that we encode query params only when the `encode query params` toggle is switched on in the settings tab ?

2022-11-23 07:29 UTC, vaibh1297 commented on app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java
> +            String[] urlParts = decodedUrl.split("\\?");
done

2022-11-23 07:40 UTC, sumitsum commented on app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java
> +                List<Property> queryParamsList = new ArrayList<>();
Can you please rename this to `paginationQueryParams` ?

2022-11-23 07:58 UTC, sumitsum requested changes

2022-11-23 07:58 UTC, sumitsum commented on app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java
> +                    queryParamsList.addAll(decodeUrlAndEncodeQueryParams(datasourceConfiguration,actionConfiguration.getNext()));
Please change the function name `decodeUrlAndEncodeQueryParams` to something since we are not encoding the query params in this function now I think ? Something like `decodeUrlAndGetAllQueryParams` ?

2022-11-23 07:58 UTC, sumitsum commented on app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java
> +            for (String queryParam : queryParamArray) {
Can you please check if this case is handled here: https://stackoverflow.com/questions/4557387/is-a-url-query-parameter-valid-if-it-has-no-value

2022-11-23 07:58 UTC, sumitsum commented on app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java
> +                String key = keyValue.length > 0 ? keyValue[0] : "";
Can you please check what happens when key evaluates to empty ? i.e. whether the API server runs into any error during further processing ?

2022-11-23 07:58 UTC, sumitsum commented on app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java
> +    private List<Property> getQueryParamList(String queryParams) {
Can you please rename this to `getQueryParamListFromUrlSuffix` ?

2022-11-23 11:59 UTC, vaibh1297 commented on app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java
> +    private List<Property> getQueryParamList(String queryParams) {
done

2022-11-23 11:59 UTC, vaibh1297 commented on app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java
> +                    queryParamsList.addAll(decodeUrlAndEncodeQueryParams(datasourceConfiguration,actionConfiguration.getNext()));
done

2022-11-23 11:59 UTC, vaibh1297 commented on app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java
> +                List<Property> queryParamsList = new ArrayList<>();
done

2022-11-23 12:02 UTC, sumitsum approved these changes

2022-11-23 12:24 UTC, vaibh1297 commented
/ok-to-test sha=84f7421

2022-11-24 15:52 UTC, btsgh commented
Tested the fix with following Apis - 
1. https://mock-api.appsmith.com/users?pageSize=1&page=3&mock_filter=abc 11
2. https://637f8e5a2f8f56e28e8fd6ef.mockapi.io/api/v1/articles?page=3&mock filter=abc 11&pagesize=1

In both the cases, the api runs successfully
In the Pagination tab, on the next and previous url, test works fine - no errors. 
On disabling the Encode Query Params toggle, the run as well as test fails .. this is as expected. 

One concern - the Performance results have many values showing up in red in the SD (Variation%) column. @vaibh1297  - please can you connect with the performance team to check if this is acceptable.

2022-11-25 05:07 UTC, sumitsum commented
@SatishGandham can you please check out the performance metrics mentioned by Aparna.

2022-11-25 07:38 UTC, btsgh commented
Found an issue with logging into this branch using my appsmith id. It gave internal server error and the docker logs had the following errors - 
 ![DockerErrors.png](https://images.zenhubusercontent.com/6242f2f59960209e891f50ec/7248204f-d791-43a6-935c-8553b6af9d71)
Logging into localhost of other branches using the same appsmith id does not give any errors. 
Discussed the same with @vaibh1297  - he tried it on his local with my appsmith id and he did not face any issues.

Just bringing this up here as wanted to take a call if this is something that needs to be looked at?

2022-11-25 10:35 UTC, sumitsum commented
@btsgh can you please share steps to reproduce the error ?

2022-11-25 11:19 UTC, btsgh commented
> @btsgh can you please share steps to reproduce the error ?

Bring up the local environment for this branch
Try to login using my appsmith credentials - aparna@appsmith.com and corresponding password

2022-11-30 10:34 UTC, sumitsum commented
/ok-to-test sha=84f7421

2022-12-01 09:42 UTC, vaibh1297 commented
/ok-to-test sha=ee32aad

2022-12-01 13:41 UTC, Aishwarya-U-R commented
/ok-to-test sha=1b89d7d

2022-12-08 07:36 UTC, vaibh1297 commented
/ok-to-test sha=b483601

2022-12-08 09:13 UTC, vaibh1297 commented
/ok-to-test sha=62a36da

2022-12-09 12:05 UTC, vaibh1297 commented
/ok-to-test sha=38969e9

2022-12-12 08:27 UTC, vaibh1297 commented
/ok-to-test sha=b935254

2022-12-13 09:07 UTC, merged