feat: Add auto height computation functions
appsmithorg/appsmith pull request #17962
Opened 2022-10-30 17:48 UTC by riodeuno

## Description
- [ ] Add function to generate the auto height layout tree for computations
- [ ] Add function to update box positions based on delta

Fixes #17961 17961
## Type of change
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
- Jest PENDING

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
~~- [NA] I have made corresponding changes to the documentation~~
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-11-01 05:52 UTC, marks0351 requested changes

2022-11-01 13:00 UTC, riodeuno commented on app/client/src/utils/autoHeight/generateTree.ts
> +  for (let i = 0; i < spaces.length; i++) {
Yes, that's a great point. I'll check this out. Thanks for this, performance optimisation review comments are my favorite!

2022-11-01 13:02 UTC, riodeuno commented on app/client/src/utils/autoHeight/generateTree.ts
> +        const comparisionSpace = { ..._spaces[j] };
After sorting the spaces based on topRow, we're calling `.shift()`, this should eject the currentSpace from the _spaces list so that comparisonSpace will never have to compare against itself. 

At least, that's my understanding. I wrote this pretty late in the night. Let me review it again.

2022-11-05 16:56 UTC, riodeuno commented on app/client/src/utils/autoHeight/generateTree.ts
> +        const comparisionSpace = { ..._spaces[j] };
done.

2022-11-05 19:32 UTC, riodeuno commented
/ok-to-test sha=8316704

2022-11-06 07:11 UTC, riodeuno commented
/ok-to-test sha=612f820

2022-11-08 12:14 UTC, ankurrsinghal commented
/ok-to-test sha=6436742

2022-11-15 10:52 UTC, rahulramesha submitted a review, later dismissed

2022-11-16 04:37 UTC, marks0351 submitted a review, later dismissed

2022-11-16 20:45 UTC, ankurrsinghal commented
/ok-to-test sha=fa8125e

2022-11-17 07:03 UTC, marks0351 approved these changes

2022-11-20 06:12 UTC, merged