feat: base widget Auto height enhancements
appsmithorg/appsmith pull request #17994
Opened 2022-10-31 10:51 UTC by riodeuno

## Description
The BaseWidget now does the following:
- [ ] Enables calls to update auto height of widget
- [ ] Checks if this update should be applied
- [ ] Adds the auto height overlay in edit mode
- [ ] Wraps widgets in auto height container

Fixes #1799

## Type of change
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Manual (Smoke test, should not break existing apps)
- Jest (For new functions added)
- Cypress (Existing tests)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
~~- [NA] I have made corresponding changes to the documentation~~
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-10-31 11:20 UTC, riodeuno commented
@rahulramesha @marks0351 The two components in this PR are placeholders, @ankurrsinghal will be creating separate PRs which implement them correctly.

2022-11-01 06:06 UTC, marks0351 requested changes

2022-11-01 06:06 UTC, marks0351 commented on app/client/src/widgets/BaseWidget.tsx
> +    const content =
better process content after the if check to avoid it's execution when not needed.

2022-11-01 12:51 UTC, riodeuno commented on app/client/src/widgets/BaseWidget.tsx
> +    const { updateWidgetAutoHeight } = {
This is actually an issue due to lack of implementation. This function is supposed to come from the context. This context is available in another PR which when merged into release, will enable us to do something like `const {updateWidgetAutoHeight} = this.context`

2022-11-01 12:52 UTC, riodeuno commented on app/client/src/widgets/BaseWidget.tsx
> +    if (updateWidgetAutoHeight) {
Typescript makes this necessary -- as noted in the previous comment, when the context is available, the context is possibly undefined, leading us to have this check.

2022-11-01 12:53 UTC, riodeuno commented on app/client/src/widgets/BaseWidget.tsx
> +      }
Sounds good. I'll use this. Thanks for the suggestion.

2022-11-01 12:56 UTC, riodeuno commented on app/client/src/widgets/BaseWidget.tsx
> +    const content =
Thanks for pointing this out, the actual code should be `return this.addAutoHeightContainer(content);` instead of `return this.addAutoHeightContainer(this.getPageView());`

The processing is common for both scenarios. Regardless of the render mode, we need to make sure to wrap the autoheightoverlay and the error boundary. 

I'll make this change.

2022-11-01 17:59 UTC, rahulramesha commented on app/client/src/widgets/BaseWidget.tsx
> +        // postUpdateAction: ReduxActionTypes.CHECK_CONTAINERS_FOR_DYNAMIC_HEIGHT,
Will this be enabled in the other PRs?

2022-11-04 05:59 UTC, riodeuno commented on app/client/src/widgets/BaseWidget.tsx
> +        // postUpdateAction: ReduxActionTypes.CHECK_CONTAINERS_FOR_DYNAMIC_HEIGHT,
@rahulramesha Yes. This is related to the postUpdateActions PR created.

2022-11-04 06:00 UTC, riodeuno commented on app/client/src/widgets/BaseWidget.tsx
> +      }
Done.

2022-11-04 06:00 UTC, riodeuno commented on app/client/src/widgets/BaseWidget.tsx
> +    const content =
Done.

2022-11-04 06:14 UTC, marks0351 approved these changes

2022-11-04 06:58 UTC, merged