chore: List v2 primary key & hashing
appsmithorg/appsmith pull request #18017
Opened 2022-11-01 06:12 UTC by ashit-rath

## Description

1. Adds a new property "Primary key" to the property pane
2. This is used for internal caching of relevant meta data to provide data consistency over page change
3. When no primary key is selected from the dropdown, default hashing takes over
4. Provides a JS mode, which can be used for composite key. In order to access the `listData`, `currentItem` and `currentIndex` can be used. Eg `{{currentItem.name + currentItem.age}}`
5. This composite key internally generates an array which is equal to the number of items present in `listData`

#### Hashing
Package - object-hash
Algorithm - MD5
Other options considered - murmur3, crc64, SHA-128

Reason for choosing `object-hash`
As we are hashing the objects present in the listData and over API calls, the JS spec does not ensure the order of objects.
Eg an object - { a: 100, b: 200 } can arrive as { b: 200, a: 100 }

If any algorithm is used directly like murmur3, this has to be converted to a string and then hashed. 
To make sure we always get the same hash for different ordering of objects, the keys has to be first sorted, stringified and then hashed
`object-hash` does the same thing for us so that we don't break our heads to make this right.

Why MD5
object-hash provides limited option so MD5 is the quickest of the lot.

Fixes #16582 

## Type of change
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
- Jest
a. Test cases for Queue class
b. Test cases for the primary key validation function

- Cypress
1. Property - primary key test cases
a. if present in the property pane
b. on selection of key from dropdown, it should show same number of rows
c. shows list of keys present in list data
d. when given composite key, should produce a valid array

### Test Plan
> Add Testsmith test cases links that relate to this PR

### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)

## Checklist:
### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2022-11-01 06:12 UTC, ashit-rath commented
/ok-to-test sha=98796c0

2022-11-02 02:22 UTC, Tooluloope requested changes

2022-11-02 02:22 UTC, Tooluloope commented on app/client/src/widgets/ListWidgetV2/MetaWidgetGenerator.ts
> +      this.prevViewMetaWidgetIds = [];
why not reset or remap based on the type of pagination, rather than defaulting to resetting?

2022-11-02 02:22 UTC, Tooluloope commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/ListV2/Listv2_primaryKeyProperty_spec.js
> +const simpleListDSL = require("../../../../../fixtures/Listv2/simpleList.json");
Add a test for no unique primary key error

2022-11-02 04:14 UTC, ashit-rath commented on app/client/src/widgets/ListWidgetV2/widget/propertyConfig.ts
> +        options: (props: ListWidgetProps) => {
The options would be computed using the listData and would be dynamic based on the object keys in the listData. The implementation of the dropdown control accepted only a static array.

2022-11-02 04:16 UTC, ashit-rath commented on app/client/src/widgets/ListWidgetV2/widget/propertyConfig.ts
> +              type: "Array<string | number>",
yes, with this we are only validating when the values are coming from the custom js control as the dropdown would either be some value or undefined which is fine.

2022-11-02 04:16 UTC, ashit-rath commented on app/client/src/widgets/ListWidgetV2/widget/propertyConfig.test.ts
> +    ];
Yes correct, but we need to test other inputs as we are testing this in isolation.

2022-11-02 04:19 UTC, ashit-rath commented on app/client/src/widgets/ListWidgetV2/MetaWidgetGenerator.ts
> +      this.prevViewMetaWidgetIds = [];
I thought about this but the logic to do that would have a lot of edge cases and modification of primary key is not expected to be in the view mode.
Check this out - https://github.com/appsmithorg/appsmith/pull/18017/files#diff-b673b712c3c6608c19af587167a07d79733ee58b94977ee9c6b516328ee5d2e1R262-R288

Let me know if you think something else is a better option.

2022-11-02 04:20 UTC, ashit-rath commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/ListV2/Listv2_primaryKeyProperty_spec.js
> +const simpleListDSL = require("../../../../../fixtures/Listv2/simpleList.json");
I have a jest test for that. Do you think I should add a cypress test as well?

2022-11-02 04:30 UTC, ashit-rath commented on app/client/src/widgets/ListWidgetV2/widget/propertyConfig.ts
> +    const areKeysUnique = _.uniq(inputValue).length === props.listData?.length;
Is this DP or local as this seem to work fine locally but doesn't seem to throw any error when used `img` here. I'll improve the logic

2022-11-02 04:33 UTC, ashit-rath commented on app/client/src/widgets/ListWidgetV2/widget/propertyConfig.ts
> +  };
I think we need to add primitive values as well. I wasn't expecting anyone to enter keys as string directly in the JS mode as it's only for the composite key. But I think we should be prepared for that

2022-11-02 10:51 UTC, Tooluloope commented on app/client/src/widgets/ListWidgetV2/widget/propertyConfig.ts
> +    const areKeysUnique = _.uniq(inputValue).length === props.listData?.length;
This is DP, Also when the primary key isn't unique, should we render it as it is, or just default undefined but then show the errors?

As shown above, the first and second items weren't rendered correctly.

2022-11-02 10:52 UTC, Tooluloope commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/ListV2/Listv2_primaryKeyProperty_spec.js
> +const simpleListDSL = require("../../../../../fixtures/Listv2/simpleList.json");
Yeah, for some reasons I wasn't seeing the error in the evaluation Pop up.

2022-11-02 10:53 UTC, ashit-rath commented on app/client/src/widgets/ListWidgetV2/widget/propertyConfig.ts
> +    const areKeysUnique = _.uniq(inputValue).length === props.listData?.length;
I have updated the logic
Now we are always expecting an array out of the primary key for both JS mode enabled and disabled.

2022-11-02 10:53 UTC, ashit-rath commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/ListV2/Listv2_primaryKeyProperty_spec.js
> +const simpleListDSL = require("../../../../../fixtures/Listv2/simpleList.json");
Could you check the latest DP?

2022-11-02 11:06 UTC, Tooluloope commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/ListV2/Listv2_primaryKeyProperty_spec.js
> +const simpleListDSL = require("../../../../../fixtures/Listv2/simpleList.json");
Must `primaryKey` be set?

The evaluation Pop up error seems to work now 👍.
https://user-images.githubusercontent.com/31691737/199472343-729ca0a4-6df9-4d0e-b77e-49a78e6b7516.mov

2022-11-02 11:07 UTC, ashit-rath commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/ListV2/Listv2_primaryKeyProperty_spec.js
> +const simpleListDSL = require("../../../../../fixtures/Listv2/simpleList.json");
It is a must but we cannot completely enforce it so we have a fallback for `undefined` and empty primaryKey (`[]`)

2022-11-02 11:13 UTC, Tooluloope approved these changes

2022-11-02 12:46 UTC, kamakshibhat-appsmith commented
Hey @ashit-rath , is Manual QA required for this task ?
cc: @laveena-en

2022-11-02 12:49 UTC, ashit-rath commented
@kamakshibhat-appsmith Yeah, a quick sanity check would be great.

2022-11-03 09:24 UTC, kamakshibhat-appsmith commented
Issues observed:
1. For a valid primary key, the client side pagination is broken. https://www.loom.com/share/e3359e84135643239560c53c6b3b45f2
2. If primary key is not selected and you toggle to JS mode, there comes unwanted square parenthesis which makes it difficult to switch back to normal mode
 https://www.loom.com/share/8a48054cb5a0460badd0b1c08eaeaa36
3. Issue with server side pagination https://www.loom.com/share/e6761c52258f44c9917ba7827a5d0078
    You can find the same pagination issues with Infinite scroll as well

@ashit-rath

2022-11-03 12:55 UTC, ashit-rath commented
/ok-to-test sha=9365776

2022-11-04 03:36 UTC, ashit-rath commented
/ok-to-test sha=9365776

2022-11-04 06:38 UTC, kamakshibhat-appsmith commented
@ashit-rath the server side pagination seems to be broken. Can you have a look at it and see if it's related

2022-11-08 05:48 UTC, chandannkumar commented
Observation:
- When no Primary key is being selected, App break on changing pagination in List v2
- When a non unique Primary key is selected from the dropdown, the App breaks on changing pagination
Video: https://www.loom.com/share/dfc4f48dc17d46278c4b313da174c0d7

- List v2 on view mode seems like disabled
https://www.loom.com/share/764355366c2143a8b0d5d83bb764efd5

2022-11-15 17:03 UTC, kamakshibhat-appsmith commented
few more observations 
1. List item click is not working for List v2
2. Issues with List v2 page size evaluation on page reload in the DB query page(Not sure if it falls under our scope or is an JS evaluation issue )
    https://www.loom.com/share/bf95456e9b064835895eaede04daa4cf

2022-11-16 05:47 UTC, kamakshibhat-appsmith commented
@ashit-rath 
_This issue falls out of scope of the current issue and is being worked on separately_.-- NOTED
_Is this working fine on the base PR and not here? https://github.com/appsmithorg/appsmith/pull/15839_-- Checked in base PR. Doesn't seem to be working there as well

2022-11-16 05:50 UTC, ashit-rath commented
@kamakshibhat-appsmith We have an open issue for the page size https://github.com/appsmithorg/appsmith/issues/16586
Could you drop your findings there for easier tracking?

2022-11-16 09:11 UTC, ashit-rath commented
@chandannkumar 
> * List v2 on view mode seems like disabled

This is out of scope of this issue and will be dealt separately.

The other callout has been fixed

2022-11-17 08:32 UTC, chandannkumar commented
Tested this PR and LGTM
- verified all callouts

2022-11-17 08:38 UTC, merged

2022-12-16 10:01 UTC, kamakshibhat-appsmith commented
@ashit-rath DnD a list v2 widget and remove all the pre-listed items , you'll notice when no primary key is selected , and we toggle to JS mode, you will find the binding there for ID. by default.
https://www.loom.com/share/0553d12f776744049d6485b63343183a