Consume multiple-script-data endpoint of AST (#17619)
appsmithorg/appsmith pull request #18018
Opened 2022-11-01 06:20 UTC by subrata71

This PR is to deal with the following items
- Connections quickly get exhausted when AST single-script-data endpoint is invoked several times.
- Users face internal server errors when there's no connection available to call the AST API
- The multiple-script-data endpoint is supposed to take multiple bindings in one single request and to serve the need for multiple connections through one connection where applicable
- Now RTS server is accessed through 127.0.0.1 instead of localhost to avoid the domain name resolution before every API call ([Related SO post](https://stackoverflow.com/questions/7382602/what-is-the-difference-between-127-0-0-1-and-localhost))
- Max connections are increased to 1000 which we can reduce later when we have a permanent solution to this problem

## Description

[RCA and possible solution on Notion](https://www.notion.so/appsmith/RCA-Internal-Server-Error-while-Editing-Large-JS-object-88017c9245dd4a6a9f9237eddec6f82c)

Fixes #17619 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manual
- JUnit

### Test Plan
> Add Testsmith test cases links that relate to this PR

## Checklist:
### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2022-11-01 06:32 UTC, sondermanish commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/AstServiceCEImpl.java
> +                    .flatMapMany(Flux::fromIterable)
Why not start with Flux.fromIterable over here?

2022-11-01 07:18 UTC, subrata71 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/AstServiceCEImpl.java
> +                    .flatMapMany(Flux::fromIterable)
Done

2022-11-01 07:28 UTC, sondermanish approved these changes

2022-11-01 07:29 UTC, subrata71 commented
/ok-to-test sha=49b87ca

2022-11-01 10:39 UTC, sondermanish approved these changes

2022-11-01 16:05 UTC, subrata71 commented
There are several factors/issues which are hindering the potential benefit that we could gain over this PR

- For a moderately complex app it requires thousands of connections to be available for consuming AST APIs. The binding values are quite distinct and there are only a few cases where multiple binding values are multiplexed into one single request (/ast/multiple-script-data). Thus we couldn't exploit the multiple-script-data endpoint.
- The AST API is consumed more by the appsmith-defined binding values e.g. {appsmith.theme.colors.primaryColor, appsmith.theme.boxShadow.appBoxShadow etc}. Can we work on that particular area so that AST API is consumed to get possible entity references for the user-defined binding values or can we introduce caching in the webclient?
- The debounce time is currently configured as `100ms` in the front-end. For every small change the update JS collection API is triggered and that requires a lot of connections to be available for consuming the AST API. Can we increase the debounce time to something larger or can we introduce a button for saving the JS object explicitly by the user?

2022-11-04 06:52 UTC, nidhi-nair requested changes

2022-11-04 06:52 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/LayoutActionServiceCE.java
> +    Mono<String> updatePageLayoutsGivenAction(String pageId);
This seems to be a misnomer, and looks like it should belong in another service altogether

2022-11-04 06:52 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/LayoutActionServiceCEImpl.java
> +                        return this.updateSingleAction(id, action)
Can we have two versions of this method, one that performs the update layout as well, and one that only does the update action? This is so that we are able to knowingly use one of the two all the time. It would also require lesser refactor in this PR.

2022-11-04 06:52 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/LayoutCollectionServiceCEImpl.java
> +                            .flatMap(updatedAction -> layoutActionService.updatePageLayoutsGivenAction(updatedAction.getPageId()).thenReturn(updatedAction))
We seem to be calling update layout for each action here, why is that?

2022-11-04 07:54 UTC, sondermanish commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/LayoutCollectionServiceCEImpl.java
> +                .flatMap(savedActionCollection -> layoutActionService.updatePageLayoutsGivenAction(savedActionCollection.getPublishedCollection().getPageId()).thenReturn(savedActionCollection))
Since, the method updatePageLayoutsGivenAction require only pageId to work, could we refactor the method name?

2022-11-04 08:12 UTC, sondermanish submitted a review, later dismissed
The flow looks good to me, and since the updateSingleAction has been made to follow single responsibility principle, Here are some questions to ponder about:

-  Instead of linking this `updateSingleAction(id, action).flatMap(updatedAction -> updatePageLayoutsGivenAction(updatedAction.getPageId()).thenReturn(updatedAction))` snippet in all the places , Can create a method which aggregates these two together?

- Let's refactor the name of `updatePageLayoutGivenAction`  to `updatePageLayoutActionWithPageId` ?

2022-11-15 07:17 UTC, subrata71 commented
/ok-to-test sha=74e4ce0

2022-11-15 08:57 UTC, subrata71 commented
/ok-to-test sha=c115cb0

2022-11-15 10:21 UTC, riteshkew commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/AstServiceCEImpl.java
> +            .maxConnections(100)
how did we finalise upon these numbers?

2022-11-15 10:22 UTC, riteshkew commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/AstServiceCEImpl.java
> +        if (bindingValues.size() == 1 && bindingValues.get(0).startsWith("appsmith.theme.")) {
can we consider this for other appsmith related binding values which are usually static, is it always appsmith.theme

2022-11-15 10:24 UTC, riteshkew commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/AstServiceCEImpl.java
> +                .retryWhen(Retry.max(3))
what does this retry solve for

2022-11-15 12:00 UTC, subrata71 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/AstServiceCEImpl.java
> +            .maxConnections(100)
We have reached this number through trial and error. We have noticed that with this number the latency of the API is less and the time spent on closing these connections is also less compared to the time when the number of connections is higher.

2022-11-15 12:06 UTC, subrata71 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/AstServiceCEImpl.java
> +        if (bindingValues.size() == 1 && bindingValues.get(0).startsWith("appsmith.theme.")) {
We will keep enriching this list in order to reduce the number of API calls. But for now, I have found the following binding parameters appear most of the time

```
appsmith.theme.colors.primaryColor
appsmith.theme.borderRadius.appBorderRadius
appsmith.theme.boxShadow.appBoxShadow

```
And these are appsmith-defined. There are a few other bindings that are not appsmith-defined but start with appsmith e.g. `appsmith.store.*`.

2022-11-15 12:10 UTC, subrata71 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/AstServiceCEImpl.java
> +                .retryWhen(Retry.max(3))
Let's say one UPDATE JS collection API call requires 600 AST API calls. If one of the 600 API calls fails the user will see the internal server error. Adding retry (3) ensures that one failed AST API call will be retried 3 times by the `Webclient` itself. Thus the chance of encountering internal server error is reduced.

2022-11-15 13:29 UTC, riteshkew approved these changes
The current Changes look good and the next set of changes for this would be covered in another PR.

2022-11-15 14:19 UTC, subrata71 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/LayoutActionServiceCE.java
> +    Mono<String> updatePageLayoutsGivenAction(String pageId);
This function needs to be called explicitly from that JS collection update part once all the actions are updated. Hence, keeping this as a separate method inside that interface.

2022-11-15 14:20 UTC, subrata71 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/LayoutActionServiceCEImpl.java
> +                        return this.updateSingleAction(id, action)
I have already done the refactor from the places where it's called. Besides if we introduce two functions one having the update page layout logic and another only having the update action logic, we require one more function to update the page layouts separately. Hence, we will end up introducing three functions.

2022-11-15 14:22 UTC, btsgh commented
Tested this fix  by trying the following scenarios - 

1. Cut / copy paste a code within a JS Object to a different area- works fine
2. Git connected apps JS Object editing - works fine
3. Import and export flow of git connected apps - works fine
4. Editor - adding lines in the js editor - works fine
5. Create  New JS object - works fine. (code from highlighted jsobject is copied, but this is being handled as part of different bug)
6.  Delete JS object  - works fine
7. Copy Js object  to same or different page - works fine
8.  Move JS object  to a different page - works fine
The internal server error was no longer seen.
The JS Object editor works fine, without hanging or crashing in any of the above scenarios.

2022-11-16 00:10 UTC, merged