Query pane plugin form should be initializable
appsmithorg/appsmith pull request #1802
Opened 2020-11-19 13:24 UTC by akash-codemonk

2020-11-20 06:59 UTC, hetunandu requested changes

2020-11-20 06:59 UTC, hetunandu commented on app/client/src/sagas/QueryPaneSagas.ts
> +    }
Handle error case here

2020-11-20 06:59 UTC, hetunandu commented on app/client/src/components/formControls/utils.ts
> +// TODO (Akash): Add test
Can we add the test now?

2020-11-20 09:35 UTC, akash-codemonk commented on app/client/src/sagas/QueryPaneSagas.ts
> +    }
Here we are checking whether the plugin form api has completed(success or error). If it is successful we assign the config to `currentEditorConfig` which is initialised to null. If the api fails the `currentEditorConfig` remains to be null and is handled [here](https://github.com/appsmithorg/appsmith/pull/1802/files#diff-55f932705204ffa9c5fac701443eba4e09edb89b3407fee923132ca9f6e46311R83l)

2020-11-23 06:24 UTC, hetunandu approved these changes

2020-11-23 06:28 UTC, merged