fix: Login password length upper limit changed from 48 to 256 characters
appsmithorg/appsmith pull request #18176
Opened 2022-11-15 13:22 UTC by ankitsrivas14

## Description

Changed the login password length upper limit from 48 to 256 characters

Fixes # (issue)
[[Bug]-[672]:Passwords longer than 48 characters are "not strong enough](https://github.com/appsmithorg/appsmith/issues/12965)

### Before
![image](https://user-images.githubusercontent.com/67647761/201931201-efaf345a-e62a-4cf3-9212-946b3cf7df3a.png)

### After
![image](https://user-images.githubusercontent.com/67647761/201930946-7f9ef53c-2a4b-4e63-b3ff-5186033b9f1d.png)

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist:
### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2022-11-15 14:12 UTC, IAmAnubhavSaini requested changes

2022-11-15 14:12 UTC, IAmAnubhavSaini commented on app/client/src/utils/formhelpers.ts
> +  return passwordLength >= PASSWORD_MIN_LENGTH;
Might need to delete `const PASSWORD_MAX_LENGTH = 48;` from above in the file. Check if that value is used anywhere in all of our repos.

2022-11-15 14:12 UTC, IAmAnubhavSaini commented on app/client/src/utils/formhelpers.ts
> +  return passwordLength >= PASSWORD_MIN_LENGTH;
We can further simplify the function. `export const isStrongPassword = (value: string) => value.trim().length >= PASSWORD_MIN_LENGTH`.

2022-11-15 16:05 UTC, ankitsrivas14 commented on app/client/src/utils/formhelpers.ts
> +  return passwordLength >= PASSWORD_MIN_LENGTH;
@IAmAnubhavSaini  -- Done.

2022-11-16 03:15 UTC, IAmAnubhavSaini approved these changes

2022-11-16 03:16 UTC, IAmAnubhavSaini commented
/ok-to-test sha=7286dbd

2022-11-21 10:29 UTC, IAmAnubhavSaini requested changes
@Ankit Srivastava Please make max limit 256 characters long.

2022-11-21 11:30 UTC, ankitsrivas14 commented
> @ankit Srivastava Please make max limit 256 characters long.

Done

2022-11-21 11:31 UTC, IAmAnubhavSaini approved these changes

2022-11-25 04:23 UTC, IAmAnubhavSaini commented
/ok-to-test sha=e2d1f79

2022-12-08 05:32 UTC, IAmAnubhavSaini commented
/ok-to-test sha=5b414a2

2022-12-13 05:13 UTC, IAmAnubhavSaini commented
Update the branch with release changes and trigger testing.

2022-12-13 06:26 UTC, ankitsrivas14 commented
/ok-to-test sha=64545aa

2022-12-13 11:10 UTC, merged