feat: add crud functions
appsmithorg/appsmith pull request #18219
Opened 2022-11-17 06:23 UTC by sumitsum

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.

## Description

> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change
> Links to Notion, Figma or any other documents that might be relevant to the PR

> Add a TL;DR when description is extra long (helps content team)

Fixes # (issue)
> if no issue exists, please create an issue and ask the maintainers about this first

Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.
> Delete anything that is not important

- Manual
- Jest
- Cypress

### Test Plan
> Add Testsmith test cases links that relate to this PR

### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)

## Checklist:
### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2022-11-17 13:20 UTC, nidhi-nair requested changes
Few questions across

2022-11-17 13:20 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/domains/CustomJSLib.java
> +    Map<String, Object> defs;
@sumitsum for a better understanding, could you please specify what each of these props mean?

2022-11-17 13:20 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/BaseRepositoryImpl.java
> +    public Mono<T> findByIdAndFieldName(ID id, String fieldName) {
Should we be using a list here?

2022-11-17 13:20 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/CustomJSLibServiceCEImpl.java
> +                .flatMap(updatedJSLibs -> repository.updateByIdAndFieldName(applicationId, "installedCustomJSLibs",
Nit: Let's use a constant here?

2022-11-17 13:20 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/CustomJSLibControllerCE.java
> +        return customJSLibService.addJSLibToApplication(applicationId, customJSLib)
Looks like we're ignoring the branch name here?

2022-11-17 13:20 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/domains/Application.java
> +    List<CustomJSLib> installedCustomJSLibs = new ArrayList<>();
Do you think collecting this as a set might help retrieval?

2022-12-09 07:41 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
> +                    /*
We're giving up on uniqueness with this, would that be a possible issue? A TreeSet might help if that were a concern

2022-12-09 07:43 UTC, nidhi-nair commented on app/server/appsmith-git/src/main/java/com/appsmith/git/configurations/GitServiceConfig.java
> +    // TODO: revert it
What's this TODO about?

2022-12-09 07:45 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/domains/Application.java
> +        // TODO: check this
What's this TODO about?

2022-12-09 07:46 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/domains/CustomJSLib.java
> +    String url;
Does this url take care of the source of the library by itself or do you think we'd ever need to store the source repository separately?

2022-12-09 07:48 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/domains/CustomJSLib.java
> +    public void sanitiseToExportDBObject() {
I wonder if this needs to be in BaseDomain and overridden everywhere 🤔 Not relevant to this PR, but we should make this API available for use if it's getting used by import/export flow all the time.

2022-12-09 07:49 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/CustomJSLibApplicationDTO.java
> +         * TODO: add comment
Another TODO to clean up

2022-12-09 07:50 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/BaseRepository.java
> +    Mono<T> findByIdAndFieldName(ID id, String fieldName);
I think I'd asked this before, but wouldn't this method find a wider use case if it was a collection of field names instead of a single one?

2022-12-09 07:51 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/BaseRepository.java
> +    Mono<UpdateResult> updateByIdAndFieldName(ID id, String fieldName, Object value);
Same with this one

2022-12-09 07:56 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/CustomJSLibServiceCEImpl.java
> +    public static final String UNPUBLISHED_JS_LIBS_IDENTIFIER_IN_APPLICATION_CLASS = "unpublishedCustomJSLibs";
Can we move these to the FieldName class, or a similar aggregate?

2022-12-09 07:57 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/CustomJSLibApplicationDTO.java
> +public class CustomJSLibApplicationDTO {
Nit: Looks like this DTO is not in fact used in any of the APIs, but only for teh import/export flow? Could we please add a comment to add that clarity here?

2022-12-09 09:15 UTC, subrata71 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
> +                    /*
There's a unique index on the `uidString` field. So, it's guaranteed to be unique. And the reason for using a List here is to make sure there's an order maintained in the exported file. Previously it was a Set and a Set is a collection of unordered elements. So, there was always uncommitted changes even though I hadn't made any change.

2022-12-09 09:24 UTC, subrata71 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/domains/Application.java
> +        // TODO: check this
Same as above.

2022-12-09 09:25 UTC, subrata71 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/CustomJSLibApplicationDTO.java
> +         * TODO: add comment
Same as before.

2022-12-09 09:27 UTC, subrata71 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/BaseRepository.java
> +    Mono<T> findByIdAndFieldName(ID id, String fieldName);
Till now we don't have use cases for making this accept list of field names. It's called from `findById(ID id) `method which provides the field name as `null`.

2022-12-09 09:30 UTC, subrata71 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/CustomJSLibApplicationDTO.java
> +public class CustomJSLibApplicationDTO {
It's used in the APIs too e.g. Add Custom JS Library API.

2022-12-09 10:18 UTC, subrata71 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/CustomJSLibServiceCEImpl.java
> +    public static final String UNPUBLISHED_JS_LIBS_IDENTIFIER_IN_APPLICATION_CLASS = "unpublishedCustomJSLibs";
Done as suggested.

2022-12-09 10:26 UTC, subrata71 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/domains/CustomJSLib.java
> +    String url;
The URL takes care of the source of the library. I don't think we need to introduce a separate storage for that.

2022-12-09 10:32 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/BaseRepository.java
> +    Mono<T> findByIdAndFieldName(ID id, String fieldName);
I think if we're designing such an API we should make it extensible though, it is easy to imagine use cases for it :)

2022-12-12 06:01 UTC, sumitsum commented on app/server/appsmith-git/src/main/java/com/appsmith/git/configurations/GitServiceConfig.java
> +    // TODO: revert it
We simply have to revert this change, I had made this change to make the git sync feature work on my local system in development mode.

2022-12-12 06:32 UTC, subrata71 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/BaseRepository.java
> +    Mono<T> findByIdAndFieldName(ID id, String fieldName);
Hey @nidhi-nair 
Considering the urgency can we please defer this for now if it doesn't seem to be a blocker?
cc: @sumitsum

2022-12-12 10:35 UTC, subrata71 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/BaseRepositoryImpl.java
> +    public Mono<T> findByIdAndFieldName(ID id, String fieldName) {
Done

2022-12-12 10:36 UTC, subrata71 commented on app/server/appsmith-git/src/main/java/com/appsmith/git/configurations/GitServiceConfig.java
> +    // TODO: revert it
Done

2022-12-12 10:36 UTC, subrata71 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/domains/Application.java
> +        // TODO: check this
Done

2022-12-12 10:36 UTC, subrata71 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/CustomJSLibApplicationDTO.java
> +         * TODO: add comment
Done

2022-12-12 10:36 UTC, subrata71 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/BaseRepository.java
> +    Mono<T> findByIdAndFieldName(ID id, String fieldName);
Changed it to accept a list of field names now. @nidhi-nair

2022-12-12 10:36 UTC, subrata71 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/BaseRepository.java
> +    Mono<UpdateResult> updateByIdAndFieldName(ID id, String fieldName, Object value);
Done

2022-12-12 10:55 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/BaseAppsmithRepositoryCEImpl.java
> +                    if(!isEmpty(projectionFieldNames)) {
@nidhi-nair yes, at the moment we want to treat them as same since the expectation is that a programmed could explicitly pass `null` or `empty` list to indicate that they want to skip projection fields.

2022-12-19 04:08 UTC, sumitsum commented
Closing this since we have directly merged the change into release via PR: https://github.com/appsmithorg/appsmith/pull/18904

2022-12-19 04:08 UTC, closed without merging