fix: Form message component link issue
appsmithorg/appsmith pull request #18231
Opened 2022-11-17 11:15 UTC by albinAppsmith

## Description

While resetting the password, the link which shared over mail was showing 'oops something went wrong' screen (shown below).

![Screenshot 2022-11-18 at 9 49 23 AM](https://user-images.githubusercontent.com/87797149/202615905-f84c74e5-b21a-4691-882d-c8a76dfdab61.png)

This issue is fixed and now it will show appropriate message and link. This happened during design system migration.

Fixes #18086

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manually tested in local by taking the token link from prod password reset mail

### Test Plan

### Issues raised during DP testing

## Checklist:
### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2022-11-18 04:36 UTC, hetunandu requested changes

2022-11-18 04:36 UTC, hetunandu commented on app/client/src/pages/UserAuth/ForgotPassword.tsx
> +              linkAs={Link}
Instead of passing the component and it's props separately, lets just pass the whole component with the props assigned from here.

2022-11-18 04:48 UTC, albinAppsmith commented on app/client/src/pages/UserAuth/ForgotPassword.tsx
> +              linkAs={Link}
<img width="533" alt="Screenshot 2022-11-18 at 10 09 07 AM" src="https://user-images.githubusercontent.com/87797149/202618187-9938e52b-2607-4643-a943-47c983722703.png">
This is the code from design system component. Do you think this way it won't scale?

2022-11-18 05:00 UTC, hetunandu commented on app/client/src/pages/UserAuth/ForgotPassword.tsx
> +              linkAs={Link}
Yes. Seeing this, I feel there is too much logic on this component and will make it inflexible. Everything inside "StyledAction" should be just a prop passed down and rendered

2022-11-18 05:23 UTC, albinAppsmith commented on app/client/src/pages/UserAuth/ForgotPassword.tsx
> +              linkAs={Link}
Yeah, but now if I need to change this I need to touch all places the component being used... To summarise do you still want me to accept the link as a whole component with props?

2022-11-18 05:26 UTC, hetunandu commented on app/client/src/pages/UserAuth/ForgotPassword.tsx
> +              linkAs={Link}
Still yes. The change seems big now, but it will add a lot of flexibility for future design changes

2022-11-22 00:03 UTC, hetunandu submitted a review, later dismissed

2022-11-22 07:13 UTC, shadabbuchh commented
Tested this PR.
Now after clicking the `Reset Password` link the user is directed to the appropriate page without any errors and is able to reset the password.
https://www.loom.com/share/8f60d7aa29364c58a61d8618ff1f46ec

2022-11-29 10:02 UTC, albinAppsmith commented
/ok-to-test sha=4623936

2022-11-29 10:03 UTC, albinAppsmith commented
/ok-to-test sha=fc68e7d

2022-11-30 05:10 UTC, merged