chore: maintain focus of form control fields
appsmithorg/appsmith pull request #18240
Opened 2022-11-17 14:05 UTC by akash-codemonk

## Description

> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change
> Links to Notion, Figma or any other documents that might be relevant to the PR

> Add a TL;DR when description is extra long (helps content team)

Fixes #17435
> if no issue exists, please create an issue and ask the maintainers about this first

Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.
> Delete anything that is not important

- Manual
- Jest
- Cypress

### Test Plan
> Add Testsmith test cases links that relate to this PR

### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)

## Checklist:
### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2022-12-02 16:30 UTC, akash-codemonk commented
/ok-to-test sha=a4fac70

2022-12-03 06:38 UTC, akash-codemonk commented
/ok-to-test sha=bcfd7dd

2022-12-03 07:53 UTC, akash-codemonk commented
/ok-to-test sha=102407b

2022-12-05 07:01 UTC, akash-codemonk commented
/ok-to-test sha=5124fe5

2022-12-06 05:14 UTC, hetunandu requested changes

2022-12-06 05:14 UTC, hetunandu commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DynamicHeight/DynamicHeight_Auto_Height_spec.js
> +describe("Dynamic Height Width validation", function() {
Add numbers on the test cases

"1. Dynamic Height.... "

2022-12-06 05:14 UTC, hetunandu commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/IDE/MaintainContext&Focus_spec.js
> +    cy.get(".t--actionConfiguration\\.body .CodeEditorTarget").should(
Why did we remove the cursor position assertion here?

2022-12-06 05:14 UTC, hetunandu commented on app/client/src/navigation/FocusElements.ts
> -    {
We still need to do focus and restore cursor on code editor fields

2022-12-06 05:17 UTC, akash-codemonk commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DynamicHeight/DynamicHeight_Auto_Height_spec.js
> +describe("Dynamic Height Width validation", function() {
This test wasn't added in this PR. The file was auto formatted by the pre-commit hook.

2022-12-06 07:21 UTC, akash-codemonk commented on app/client/src/navigation/FocusElements.ts
> -    {
This has been removed to remove input focus invoked by the CodeEditor component as it conflicts with the focus of the rest of the inputs with the form control fields. We do the same for codeeditor fields in the canvas for the property pane. 
Regardless the cursor is still maintained when the input gets focused(when the field is focused and we press enter we can see the restored cursor position) as this is stored directly by the codeeditor component itself identified by the datatree path. 


https://user-images.githubusercontent.com/67054171/205846740-c656bafb-7af5-40af-a1fe-ed032e62445a.mov

2022-12-06 09:33 UTC, akash-codemonk commented
/ok-to-test sha=5c96bc4

2022-12-09 03:54 UTC, akash-codemonk commented
/ok-to-test sha=d345d0a

2022-12-09 13:00 UTC, akash-codemonk commented
/ok-to-test sha=025f90b

2022-12-10 05:01 UTC, akash-codemonk commented
/ok-to-test sha=14a153a

2022-12-12 04:38 UTC, akash-codemonk commented
/ok-to-test sha=3e170d1

2022-12-13 05:12 UTC, hetunandu requested changes

2022-12-13 05:12 UTC, hetunandu commented on app/client/src/navigation/FocusElements.ts
> +  ControlField = "ControlField",
Can we rename it to "InputField" which is more generic and applies to all

2022-12-13 08:53 UTC, akash-codemonk commented
/ok-to-test sha=c107be4

2022-12-13 15:24 UTC, akash-codemonk commented
/ok-to-test sha=a94b55a

2022-12-14 04:19 UTC, akash-codemonk commented
/ok-to-test sha=1493423

2022-12-14 10:30 UTC, hetunandu approved these changes

2022-12-14 12:09 UTC, akash-codemonk commented
/ok-to-test sha=1461e69

2022-12-15 03:02 UTC, akash-codemonk commented
/ok-to-test sha=0821258

2022-12-15 03:13 UTC, hetunandu approved these changes

2022-12-15 05:06 UTC, Rhitottam commented
/perf-test ref=rhito/remove-lintworker-scripting

2022-12-15 07:40 UTC, akash-codemonk commented
/ok-to-test sha=ae9fc5a

2022-12-15 14:15 UTC, merged