fix: slider widget issues
appsmithorg/appsmith pull request #18277
Opened 2022-11-18 13:54 UTC by yaldram

## Description

- Add tooltips to label and maintain consistency with other inputs.
- Change validation messages.
- Maintain consistency in widget sizes when dragged on the canvas.

Fixes #18272 
Fixes #18194 
Fixes #18070 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manual
- Cypress

### Test Plan

### Issues raised during DP testing

## Checklist:
### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2022-11-21 12:35 UTC, keyurparalkar requested changes

2022-11-21 12:35 UTC, keyurparalkar commented on app/client/src/widgets/RangeSliderWidget/widget/propertyConfig/contentConfig.ts
> +        label: "Show value always",
@yaldram aren't we changing `tooltipAlwaysOn` value for category slider as well?

2022-11-21 12:40 UTC, yaldram commented on app/client/src/widgets/RangeSliderWidget/widget/propertyConfig/contentConfig.ts
> +        label: "Show value always",
We don't have `tooltip always on` property for category sliders.

2022-11-21 13:44 UTC, keyurparalkar commented on app/client/src/widgets/RangeSliderWidget/widget/propertyConfig/contentConfig.ts
> +        label: "Show value always",
@yaldram Should this be added? Can you confirm?
CC: @dilippitchika

2022-11-21 13:46 UTC, yaldram commented on app/client/src/widgets/RangeSliderWidget/widget/propertyConfig/contentConfig.ts
> +        label: "Show value always",
Yes, I had discussed this with Dilip we removed it from the category slider.

2022-11-21 13:47 UTC, keyurparalkar approved these changes
LGTM!

2022-11-25 08:50 UTC, Sripriya93 commented
1. Tooltip property is present in General section
2. "Tooltip always on" is renamed to "Show value always"
3. Error message of the default start value in range and number slider is changed to "greater than or equal to" and default end value is "changed to less than or equal to"
4. In its default state category slider is now same as other sliders
5. Marks in category slider are now visible by default like other sliders

Moving to done

2022-11-26 09:15 UTC, yaldram commented
/ok-to-test sha=d08c702

2022-11-26 12:17 UTC, merged