passwordExists field added in DBAuth class
appsmithorg/appsmith pull request #18293
Opened 2022-11-21 05:20 UTC by vaibh1297

## Description

> Authenticated datasource passwordExists  field added for plugins

Fixes #14783

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manual

## Checklist:
### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2022-11-21 10:24 UTC, sumitsum commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/DBAuth.java
> +    public boolean isPasswordExists() {
Instead of a method, we need to have a field named `isPasswordExists` that should be set by the API server during the code flow when password is persisted in the DB. Also, we need to add this field in the following classes as well since they have password like fields as well:
```
OAuth2
BasicAuth
ApiKeyAuth
BearerTokenAuth
```

Just a thought - should we instead override the `setter` method of password field to update this new variable whenever the password field is set ?

2022-11-21 10:28 UTC, sumitsum commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/DBAuth.java
> +    public boolean isPasswordExists() {
Alternatively, we may choose not to persist the `isPasswordExists` field at all because we only need it once when sending back the data to the client and it is a derived value i.e. can be derived on the fly from the password field.

2022-11-21 10:29 UTC, sumitsum commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/DBAuth.java
> +    public boolean isPasswordExists() {
IMO, we should go with the second one if possible.

2022-11-23 06:03 UTC, mohanarpit commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/AuthenticationDTO.java
> +        return StringUtils.hasLength(secret);
Nit: Any reason we are saving the secret in a variable before checking its length? Strings are immutable and this just creates unnecessary garbage in the JVM. In this particular case, it would be simpler to just write `StringUtils.hasLength(getSecret())`

2022-11-23 09:11 UTC, vaibh1297 commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/AuthenticationDTO.java
> +        return StringUtils.hasLength(secret);
done

2022-11-25 11:44 UTC, sumitsum commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/AuthenticationDTO.java
> +    @JsonProperty
Can you please check once if this does not persist the value in DB ?

2022-11-27 08:46 UTC, vaibh1297 commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/AuthenticationDTO.java
> +    @JsonProperty
yes, value is not persisted in db.

2022-11-29 04:57 UTC, sumitsum submitted a review, later dismissed

2022-11-29 06:41 UTC, vaibh1297 commented
/ok-to-test sha=aeace31

2022-12-13 07:09 UTC, vaibh1297 commented
/ok-to-test sha=7e0678a

2022-12-13 07:14 UTC, sumitsum commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/SecretExists.java
> +//@JsonInclude(JsonInclude.Include.NON_NULL)
Please remove the commented out line.

2022-12-13 07:15 UTC, sumitsum commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/SecretExists.java
> +public class SecretExists {
Please add a comment explaining what this class does - ie. essentially what problem this class solves.

2022-12-13 07:42 UTC, vaibh1297 commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/SecretExists.java
> +//@JsonInclude(JsonInclude.Include.NON_NULL)
already removed, please check the updated version of pr.

2022-12-13 07:50 UTC, vaibh1297 commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/SecretExists.java
> +public class SecretExists {
done

2022-12-14 07:26 UTC, sumitsum submitted a review, later dismissed

2022-12-16 08:55 UTC, sumitsum commented on app/server/appsmith-plugins/amazons3Plugin/src/main/resources/form.json
> +          "valueExistPath": "datasourceConfiguration.authentication.secretExists.password"
Can you please rename this to `isSecretExistsPath` since it seems to better explain what the key stands for ? Please mention in case you have other opinions on this.

2022-12-20 06:21 UTC, sumitsum approved these changes

2022-12-20 06:53 UTC, vaibh1297 commented
/ok-to-test sha=57c1e75

2023-01-10 10:07 UTC, vaibh1297 commented
/ok-to-test sha=5b37aad

2023-01-11 08:58 UTC, vaibh1297 commented
/ok-to-test sha=457fb84

2023-01-11 12:50 UTC, Aishwarya-U-R commented
/ok-to-test sha=a83304b

2023-01-12 12:55 UTC, vaibh1297 commented
/ok-to-test sha=369255a

2023-01-13 06:27 UTC, vaibh1297 commented
/ok-to-test sha=6e2a2ab

2023-01-22 16:46 UTC, vaibh1297 commented
/ok-to-test sha=25557cd

2023-01-23 08:35 UTC, vaibh1297 commented
/ok-to-test sha=2a862ef

2023-01-24 05:52 UTC, sumitsum commented
/ok-to-test sha=2a862ef

2023-01-24 09:18 UTC, vaibh1297 commented
/ok-to-test sha=8a0d6f4

2023-01-26 07:49 UTC, sumitsum requested changes

2023-01-26 07:49 UTC, sumitsum commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/SecretExists.java
> +public class SecretExists {
Can you please rename this to `SecretExistsIndicator` ?

2023-01-26 07:49 UTC, sumitsum commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/ApiKeyAuth.java
> +    protected void buildSecretExists(SecretExists secretExists) {
Can you please rename this to `configureSecretExistsIndicator` ?

2023-02-06 01:31 UTC, sumitsum submitted a review, later dismissed

2023-02-06 05:49 UTC, mohanarpit commented
/ok-to-test sha=9199f3efff1de279d905b55fcd5010ebf6894480

2023-02-17 13:56 UTC, PiyushPushkar02 commented
/ok-to-test sha=637a1cd

2023-02-23 07:27 UTC, PiyushPushkar02 commented
/ok-to-test

2023-02-23 07:47 UTC, PiyushPushkar02 commented
/ok-to-test sha=637a1cd

2024-04-08 20:37 UTC, closed without merging