feat: Command click navigation via code
appsmithorg/appsmith pull request #18326
Opened 2022-11-21 12:43 UTC by hetunandu

## Description
Navigate to different entities in Appsmith with CMD + Click just like a text editor.

Implements #15652

## Type of change

- New Feature

## How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.
> Delete anything that is not important

- Manual
- Jest
- Cypress

### Test Plan
> Add Testsmith test cases links that relate to this PR

### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)

## Checklist:
### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2022-11-22 04:59 UTC, hetunandu commented
/ok-to-test

2022-11-22 10:24 UTC, ramsaptami commented
- [ ] Reword text since it's a bit ambigious now. Something like "Press down on Ctrl/Cmd keys to navigate on click"
![image](https://user-images.githubusercontent.com/79509062/203278318-dd8bb307-b0f3-4f0a-81b8-b6b6326111ec.png)
- [ ] Navigation shows up only for JS object name, not function name
- [ ] Navigation does not show up for Appsmith framework functions, like for example, inside a `showModal("modalName")`, `closeModal("modalName")`, resetWidget('WidgetName')
- [ ] Navigation does not show up when using `this.functionName` on a JS object
- [ ] Dynamic binding of a widget in an API URL param is not recognized for click navigation
![image](https://user-images.githubusercontent.com/79509062/203276963-f5bc9350-5dee-4fb9-b43d-619a6b38e685.png)
- [ ] If there's a reference with the same name, for example a store value as `helloWorld` and a widget called `helloWorld` then `appsmith.store.helloWorld` navigates to the widget

2022-11-22 16:28 UTC, hetunandu commented
/ok-to-test

2022-12-01 06:44 UTC, marks0351 requested changes
Added a few comments.

2022-12-01 06:44 UTC, marks0351 commented on app/client/src/sagas/WidgetSelectionSagas.ts
> +  if (action.payload.isMultiSelect) return;
even multi-select might need this right?

2022-12-01 06:44 UTC, marks0351 commented on app/client/src/sagas/WidgetSelectionSagas.ts
> +function* selectModalWidgetSaga(
can we change this function to handle parent widgets and make sure tabs is also handled here?
make sure the meta property for tabs widget is set when a widget inside a unselected tab is selected?

2022-12-01 06:44 UTC, marks0351 commented on app/client/src/selectors/navigationSelectors.ts
> +    actions.forEach((action) => {
(Not a review comment): Why does everyone hate reduce fn 🥲

2022-12-01 06:50 UTC, marks0351 commented
Also think we could avoid/remove/modify some code here handling the modal widget since widget selection can take care of it in the middle ware.
https://github.com/appsmithorg/appsmith/blob/release/app/client/src/pages/Editor/Explorer/Widgets/useNavigateToWidget.ts

2022-12-01 09:41 UTC, hetunandu commented on app/client/src/sagas/WidgetSelectionSagas.ts
> +  if (action.payload.isMultiSelect) return;
Multi select will not open/close modal. This saga is just for that

2022-12-01 10:39 UTC, hetunandu commented on app/client/src/sagas/WidgetSelectionSagas.ts
> +function* selectModalWidgetSaga(
Can you point to a place where this happens today? I dont see tabs switching on widget selection via entity explorer or omni bar

2022-12-01 10:40 UTC, hetunandu commented on app/client/src/selectors/navigationSelectors.ts
> +    actions.forEach((action) => {
Because, it is hard to read through and make sense of.

2022-12-01 10:40 UTC, marks0351 commented on app/client/src/sagas/WidgetSelectionSagas.ts
> +function* selectModalWidgetSaga(
yea it doesn't work today. i was hoping we can fix that here.

2022-12-01 10:42 UTC, marks0351 commented on app/client/src/sagas/WidgetSelectionSagas.ts
> +  if (action.payload.isMultiSelect) return;
correct me if i am wrong, if we select 3 widgets on a modal and refresh wont that be considered a multi-select?

2022-12-01 10:44 UTC, marks0351 commented on app/client/src/sagas/WidgetSelectionSagas.ts
> +  if (action.payload.isMultiSelect) return;
i think i got confused here, i was thinking about the maintaining context feature.

2022-12-01 11:37 UTC, hetunandu commented on app/client/src/sagas/WidgetSelectionSagas.ts
> +function* selectModalWidgetSaga(
Let's do that in a different PR

2022-12-01 13:28 UTC, hetunandu commented on app/client/src/sagas/WidgetSelectionSagas.ts
> +function* selectModalWidgetSaga(
https://github.com/appsmithorg/appsmith/issues/4748

It is a quite old issue

2022-12-01 15:01 UTC, hetunandu commented
/ok-to-test sha=8565f75

2022-12-02 05:57 UTC, marks0351 submitted a review, later dismissed

2022-12-02 05:58 UTC, marks0351 commented
are test cases being added?

2022-12-02 09:13 UTC, ramsaptami commented
- [ ] Blocker issue: object body is replaced when going back on the browser
https://www.loom.com/share/de4865bb8dea47ef9c144716610fcf31
Steps: 
1. Navigate from `JSObj1` to `JSObj2` and back
2. Use browser or mousepad shortcut to go back to `JSObj1` from `JSObj2`
3. Observe the object body of `JSObj1` is replaced with `JSObj2`
4. Refreshing the page reverts the temporary object body replacement - BUT, interacting with the object replaces the text and user looses their code

2022-12-02 12:21 UTC, ramsaptami commented
- [ ] Object reference is retained even after modification
https://www.loom.com/share/443cc3b0f84f41739ee2d2ba3865ce43

2022-12-05 13:45 UTC, hetunandu commented
/ok-to-test sha=3bd89a6

2022-12-05 15:21 UTC, hetunandu commented
/ok-to-test sha=4374258

2022-12-06 07:14 UTC, hetunandu commented
/ok-to-test sha=11f0d7b

2022-12-06 09:09 UTC, hetunandu commented
/ok-to-test sha=4db236e

2022-12-06 12:39 UTC, hetunandu commented
/ok-to-test sha=e9348b6

2022-12-07 05:36 UTC, Aishwarya-U-R commented
/ok-to-test sha=4d81d09

2022-12-07 06:45 UTC, hetunandu commented
/ok-to-test sha=0ebad49

2022-12-07 18:34 UTC, rahulramesha commented on app/client/src/sagas/WidgetSelectionSagas.ts
> +  if (action.payload.isMultiSelect) return;
I read @marks0351 comment, ,but we still might need multiselect, if the user selects multiple child of Modal from entity explorer while holding cmd, modal will not open up

2022-12-07 18:34 UTC, rahulramesha commented on app/client/src/components/editorComponents/CodeEditor/index.tsx
> +    if (event.target.hasAttribute(NAVIGATE_TO_ATTRIBUTE)) {
Instead of `@ts-ignore` can't these be type casted as HTMLDivElement and use optional chaining.

2022-12-08 07:18 UTC, Parthvi12 commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/IDE/Command_Click_Navigation_spec.js
> +  it.skip("7. Will work with string arguments in framework functions", () => {
@hetunandu Why are we skipping this test?

2022-12-08 07:20 UTC, hetunandu commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/IDE/Command_Click_Navigation_spec.js
> +  it.skip("7. Will work with string arguments in framework functions", () => {
This feature set was eventually removed and will be taken up later on. Skipping it right now so that it can be enabled later on

2022-12-08 09:05 UTC, hetunandu commented
/ok-to-test sha=076bf22

2022-12-08 09:38 UTC, hetunandu commented on app/client/src/sagas/WidgetSelectionSagas.ts
> +  if (action.payload.isMultiSelect) return;
https://user-images.githubusercontent.com/12022471/206411196-537eea7e-f586-46c9-848f-41c40bd3aaa0.mov

This does not work anyways. Basically, we cannot have modal open and have a multi selection. While the modal is open, you can select multiple child via cmd selection. That should still work. But if modal is closed, and we start multi select, it should not open the modal.

2022-12-08 11:31 UTC, rahulramesha approved these changes

2022-12-08 12:16 UTC, merged