feat: Automatic height updates for widgets based on contents (Auto Height)
appsmithorg/appsmith pull request #18341
Opened 2022-11-22 05:33 UTC by riodeuno

## Description

> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change
> Links to Notion, Figma or any other documents that might be relevant to the PR

> Add a TL;DR when description is extra long (helps content team)

Fixes # (issue)
> if no issue exists, please create an issue and ask the maintainers about this first

Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.
> Delete anything that is not important

- Manual
- Jest
- Cypress

### Test Plan
> Add Testsmith test cases links that relate to this PR

### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)

## Checklist:
### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2022-11-22 11:54 UTC, ankurrsinghal commented
/ok-to-test sha=4be03c3

2022-11-22 12:52 UTC, marks0351 requested changes

2022-11-22 12:52 UTC, marks0351 commented on app/client/src/sagas/autoHeightSagas/widgets.ts
> +      if (Array.isArray(widget.children) && widget.children.length === 1) {
if this is for modal widget better mention the type to provide better readability.

2022-11-22 12:52 UTC, marks0351 commented on app/client/src/utils/DSLMigrations.ts
> +// import { ALL_WIDGETS_AND_CONFIG } from "./WidgetRegistry";
remove if not needed.

2022-11-22 12:52 UTC, marks0351 commented on app/client/src/utils/DSLMigrations.ts
> +  // if (currentDSL.version === 64) {
remove if not needed.

2022-11-22 12:52 UTC, marks0351 commented on app/client/src/utils/DSLMigrations.ts
> +// export const migratePropertiesForDynamicHeight = (currentDSL: DSLWidget) => {
remove if not needed.

2022-11-22 12:52 UTC, marks0351 commented on app/client/src/utils/DSLMigrations.ts
> +// export const migratePropertiesForDynamicHeight = (currentDSL: DSLWidget) => {
I assume this migration is needed.

2022-11-22 12:52 UTC, marks0351 commented on app/client/src/utils/hooks/useDynamicAppLayout.tsx
> +  // useEffect(() => {
remove code if not needed.

2022-11-22 12:52 UTC, marks0351 commented on app/client/src/widgets/CanvasWidget.tsx
> +      // minHeight: this.props.bottomRow,
remove commented code

2022-11-22 12:52 UTC, marks0351 commented on app/client/src/widgets/CheckboxGroupWidget/widget/index.tsx
> +      let _selectedValues = this.props.selectedValues;
is this still necessary?
cc: @rahulramesha

2022-11-22 12:52 UTC, marks0351 commented on app/client/src/widgets/ContainerWidget/component/index.tsx
> +  // useCanvasMinHeightUpdateHook(props.widgetId, props.minHeight);
remove if not needed.

2022-11-22 12:52 UTC, marks0351 commented on app/client/src/widgets/TableWidget/component/Table.tsx
> +  // I don't see the need to useMemo here.
🥇

2022-11-22 12:52 UTC, marks0351 commented on app/client/src/widgets/TabsWidget/widget/index.tsx
> +    // childWidgetData.shouldScrollContents = this.props.shouldScrollContents;
remove if not needed.

2022-11-22 19:48 UTC, ankurrsinghal commented
/ok-to-test sha=a338d56

2022-11-22 19:59 UTC, riodeuno commented on app/client/src/pages/Editor/MainContainer.tsx
> +  // background-color: ${(props) => props.theme.appBackground};
We need this actually. Commented this out accidentally, thanks for noticing. I'll revert this.

2022-11-22 20:02 UTC, riodeuno commented on app/client/src/sagas/EvaluationsSaga.ts
> +    yield call(dynamicallyUpdateContainersSaga);
This is for invisible widgets in view mode. If the condition for invisibility is a binding, we will need to make sure that after eval we're fixing containers. However, now that we're using a different mechanism for dealing with invisible widgets this may not be needed. I'll verify and remove this.

2022-11-22 20:02 UTC, riodeuno commented on app/client/src/sagas/WidgetOperationSagas.tsx
> +  yield put(generateAutoHeightLayoutTreeAction(true, true));
💯

2022-11-22 20:04 UTC, riodeuno commented on app/client/src/sagas/autoHeightSagas/widgets.ts
> +      if (Array.isArray(widget.children) && widget.children.length === 1) {
Yeah, that makes sense. I'll do this.

2022-11-22 20:04 UTC, riodeuno commented on app/client/src/utils/DSLMigrations.ts
> +// import { ALL_WIDGETS_AND_CONFIG } from "./WidgetRegistry";
This is necessary, I'll uncomment this. This is for migrations

2022-11-22 20:04 UTC, riodeuno commented on app/client/src/utils/DSLMigrations.ts
> +  // if (currentDSL.version === 64) {
This is necessary, I'll uncomment this. This is for migrations

2022-11-22 20:05 UTC, riodeuno commented on app/client/src/widgets/CheckboxGroupWidget/widget/index.tsx
> +      let _selectedValues = this.props.selectedValues;
No this is no longer necessary. We fixed the issue that was causing it. I'll revert.

2022-11-22 20:06 UTC, riodeuno commented on app/client/src/widgets/TabsWidget/widget/index.tsx
> +    // childWidgetData.shouldScrollContents = this.props.shouldScrollContents;
I'll verify and remove. This may be needed to fix some scroll issues.

2022-11-22 20:18 UTC, ankurrsinghal commented
/ok-to-test sha=7ffd469

2022-11-22 21:58 UTC, riodeuno commented on app/client/src/components/editorComponents/ErrorTooltip.tsx
> +  height: auto;
@ankurrsinghal Please check this out ☝🏼

2022-11-22 21:58 UTC, riodeuno commented on app/client/src/components/autoHeightOverlay/index.tsx
> +    const [maxdY, setMaxdY] = useState(0);
@ankurrsinghal Please check this out ☝🏼

2022-11-22 21:59 UTC, riodeuno commented on app/client/src/components/autoHeightOverlay/hooks.ts
> +  const [isActive, setIsActive] = useState(false);
@ankurrsinghal Please check this out ☝🏼

2022-11-22 22:30 UTC, riodeuno commented on app/client/src/widgets/CheckboxGroupWidget/widget/index.tsx
> +      let _selectedValues = this.props.selectedValues;
On second thought, I'll leave this alone. Don't want to break functionality at this juncture. I'll note this down and revert at a later point.

2022-11-22 22:37 UTC, riodeuno commented on app/client/src/reducers/entityReducers/autoHeightReducers/autoHeightLayoutTreeReducer.ts
> +    const diff = xor(Object.keys(state), [...Object.keys(tree)]);
@rahulramesha Need some context around this one. I can't recall the issue we were having which this fixed.

2022-11-22 22:37 UTC, riodeuno commented on app/client/src/sagas/autoHeightSagas/widgets.ts
> +      if (Array.isArray(widget.children) && widget.children.length === 1) {
Added a comment explaining this. Referring to `MODAL_WIDGET`, is an abstraction leak, although this is only marginally better.

2022-11-23 01:42 UTC, riodeuno commented
/ok-to-test sha=30b34d1

2022-11-23 03:14 UTC, riodeuno commented
/ok-to-test sha=79b67f1

2022-11-23 04:26 UTC, rahulramesha commented on app/client/src/reducers/entityReducers/autoHeightReducers/autoHeightLayoutTreeReducer.ts
> +    const diff = xor(Object.keys(state), [...Object.keys(tree)]);
This particular code was to get the diff and delete the diff values inside the tree of widgets that no longer exists. The second argument that was being passed to xor was being spread and was no longer an array. And hence the tree was retaining deleted widgets as well. So I just made it into an array again. 
As @marks0351 pointed out during our review we can just use Object.keys since that itself is an array.

2022-11-23 04:36 UTC, riodeuno commented on app/client/src/reducers/entityReducers/autoHeightReducers/autoHeightLayoutTreeReducer.ts
> +    const diff = xor(Object.keys(state), [...Object.keys(tree)]);
Got it, so I'll leave this alone.

2022-11-23 05:21 UTC, marks0351 commented on app/client/craco.build.config.js
> -    maximumFileSizeToCacheInBytes: 10 * 1024 * 1024,
how much is the change from the present build?

2022-11-23 05:22 UTC, riodeuno commented on app/client/craco.build.config.js
> -    maximumFileSizeToCacheInBytes: 10 * 1024 * 1024,
It was complaining about 15.1MB, not sure why.

2022-11-23 05:26 UTC, riodeuno commented
/ok-to-test sha=36af950

2022-11-23 05:27 UTC, ankurrsinghal commented
/ok-to-test sha=36af950

2022-11-23 05:40 UTC, marks0351 requested changes

2022-11-23 05:40 UTC, marks0351 commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/ExplorerTests/Entity_Explorer_DragAndDropWidget_spec.js
> +    //cy.togglebar(commonlocators.scrollView);
why are we keeping it commented?

2022-11-23 05:40 UTC, marks0351 commented on app/client/src/components/autoHeight/AutoHeightContainer.tsx
> +  padding-right: 4px;
why is this needed?

2022-11-23 05:40 UTC, marks0351 commented on app/client/src/components/autoHeightOverlay/index.tsx
> +  z-index: 3;
Add z-index to Layers constant.

2022-11-23 05:40 UTC, marks0351 commented on app/client/src/components/autoHeightOverlay/ui/AutoHeightLimitHandleDot.tsx
> +  transform: translateX(-50%)
1.67 use them as constants with proper description and also make sure they work with all layouts and screen sizes.

2022-11-23 05:40 UTC, marks0351 commented on app/client/src/components/editorComponents/DropTargetComponent.tsx
> +    // console.log(
pls remove commented code.

2022-11-23 05:54 UTC, riodeuno commented
/ok-to-test sha=0e9c804

2022-11-23 05:59 UTC, NandanAnantharamu commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/ExplorerTests/Entity_Explorer_DragAndDropWidget_spec.js
> +    //cy.togglebar(commonlocators.scrollView);
i will remove the commented code

2022-11-23 06:20 UTC, riodeuno commented
/ok-to-test sha=73742e6

2022-11-23 07:51 UTC, NandanAnantharamu commented
/ok-to-test sha=139514f

2022-11-23 09:48 UTC, merged

2022-12-13 08:15 UTC, riodeuno commented on app/client/craco.build.config.js
> -    maximumFileSizeToCacheInBytes: 10 * 1024 * 1024,
We've reverted this back to 11MB.