Fix/auto height perf rca test
appsmithorg/appsmith pull request #18457
Opened 2022-11-25 12:53 UTC by riodeuno

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.

## Description
- Reverts the RenderModes.PREVIEW logic.

> Add a TL;DR when description is extra long (helps content team)

Fixes # (issue)
> if no issue exists, please create an issue and ask the maintainers about this first

Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.
> Delete anything that is not important

- Manual
- Jest
- Cypress

### Test Plan
> Add Testsmith test cases links that relate to this PR

### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)

## Checklist:
### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2022-11-25 15:08 UTC, rahulramesha requested changes
Have few comments, but other than that what exactly was the issue with select|multiselect type widgets?

2022-11-25 15:08 UTC, rahulramesha commented on app/client/src/widgets/withWidgetProps.tsx
> +    const isPreviewMode = useSelector(previewModeSelector);
This will still re-render all the widgets, let me see if i can write a selector for this.

2022-11-25 15:08 UTC, rahulramesha commented on app/client/src/widgets/BaseWidget.tsx
> -      case RenderModes.PREVIEW:
I remember there being a Preview container, is that not required anymore?

2022-11-25 15:09 UTC, riodeuno commented on app/client/src/reducers/entityReducers/canvasWidgetsReducer.ts
> +    console.log("Setting redux state: Time taken:", performance.now() - start);
Yep, build failed due to this. Removing it.

2022-11-25 15:12 UTC, riodeuno commented
In conjunction with RenderModes.PREVIEW (when all widgets used to re-render), we used to get `(Committing Changes) Warning: Lifecycle hook scheduled a cascading update`

Basically, for reasons I couldn't figure out, widgets like MultiSelect widget which has a lot of internal renders, used to block the thread for seconds. The cause of this was that we were somehow sending updates rapidly, even before React had a chance to commit it to the DOM. This resulted in a UI freeze.

2022-11-25 17:42 UTC, ankurrsinghal commented
/ok-to-test sha=33cf3ac

2022-11-27 11:22 UTC, ankurrsinghal commented
/ok-to-test sha=ca1dde6

2022-11-27 13:40 UTC, riodeuno commented
/ok-to-test sha=50b2195

2022-11-27 14:11 UTC, riodeuno commented
/ok-to-test sha=734222b

2022-11-27 14:51 UTC, rahulramesha approved these changes

2022-11-27 17:12 UTC, merged