Mobile/v1/main
appsmithorg/appsmith pull request #18461
Opened 2022-11-25 17:38 UTC by prsidhu

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.

## Description

> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change
> Links to Notion, Figma or any other documents that might be relevant to the PR

> Add a TL;DR when description is extra long (helps content team)

Fixes # (issue)
> if no issue exists, please create an issue and ask the maintainers about this first

Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.
> Delete anything that is not important

- Manual
- Jest
- Cypress

### Test Plan
> Add Testsmith test cases links that relate to this PR

### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)

## Checklist:
### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2023-02-07 23:37 UTC, prsidhu commented
/ok-to-test sha=006e486

2023-02-13 16:01 UTC, prsidhu commented
/ok-to-test sha=d00e2af

2023-02-14 09:39 UTC, marks0351 commented
/ok-to-test sha=7c4dd7a

2023-02-14 19:48 UTC, Aishwarya-U-R commented
/ok-to-test sha=42e00a5

2023-02-14 22:18 UTC, prsidhu commented
/ok-to-test sha=2ee5f77

2023-02-15 05:10 UTC, marks0351 commented
/ok-to-test sha=d817986

2023-02-15 13:17 UTC, riodeuno commented on app/client/cypress/support/Pages/AggregateHelper.ts
> +    shouldSleep && this.Sleep();
Instead of sleep, how about using the waituntileleappear?

2023-02-16 05:05 UTC, prsidhu commented
/ok-to-test sha=e881ba5

2023-02-16 13:22 UTC, prsidhu commented
/ok-to-test sha=c27e754

2023-02-16 16:42 UTC, prsidhu commented
/ok-to-test sha=d633e7e

2023-02-16 20:35 UTC, prsidhu commented
/ok-to-test sha=142d6fe

2023-02-22 09:44 UTC, prsidhu commented
/ok-to-test sha=bc71f0a

2023-02-22 13:36 UTC, riodeuno requested changes
Phase I of review is done. I've reviewed ~ 130 files. I'll look into the remaining in phase II

2023-02-22 13:36 UTC, riodeuno commented on app/client/src/constants/Colors.tsx
> +  JAFFA_DARK: "#F86A2B",
Have we confirmed that this doesn't have any cascading effects?

2023-02-22 13:36 UTC, riodeuno commented on app/client/src/constants/PropertyControlConstants.tsx
> +  additionalAction?: (
We already have the postUpdateAction. Did this not suffice our usecase? If so, can we change the `postUpdateAction` instead?

2023-02-22 13:36 UTC, riodeuno commented on app/client/src/constants/WidgetConstants.tsx
> +export const widgetTypeClassname = (widgetType: string): string =>
This is nice! I will recommend we move it to widgetUtils instead.

2023-02-22 13:36 UTC, riodeuno commented on app/client/src/constants/minWidthConstants.ts
> +export const ICON_BUTTON_MIN_WIDTH = 50;
Should we pick this up from the configuration file `index.ts` from the widgets? These values would be stored in WidgetFactory, and can be accessed via the `widgetConfigMap`

2023-02-22 13:36 UTC, riodeuno commented on app/client/src/navigation/FocusElements.ts
> +} from "actions/datasourceActions";
Still confused about how this is happening. Please share if we have a different prettier config or something.

2023-02-22 13:36 UTC, riodeuno commented on app/client/src/pages/Editor/MainContainer.test.tsx
> +  // ToDO(Ashok): Check with Rahul if this test case is still relevant post reflow.
Please confirm and remove or uncomment accordingly.

2023-02-22 13:36 UTC, riodeuno commented on app/client/src/pages/Editor/CanvasPropertyPane/index.tsx
> +import { AppPositionTypeControl } from "../AppPositionTypeControl";
Since we're removing the `MainContainerLayoutControl`'s reference, do we need the file?

2023-02-22 13:36 UTC, riodeuno commented on app/client/src/pages/Editor/MainContainerLayoutControl.tsx
> +import { ReactComponent as DesktopIcon } from "assets/icons/ads/app-icons/monitor-alt.svg";
Is this file being used anymore?

2023-02-22 13:36 UTC, riodeuno commented on app/client/src/pages/Editor/Popper.tsx
> +        style={props.style || {}}
Can we make sure that the `props.style ` object is always available instead of handling here?

2023-02-22 13:36 UTC, riodeuno commented on app/client/src/pages/Editor/PropertyPane/PropertyControl.tsx
> +  const getAdditionalActionsToDispatch = (
We can handle this in the `batchPropertyUpdatesSaga` (I think this was the name, I might be wrong) -- instead of handling this here. Depends on how we're using this, but I am assuming that we need to call a particular action after updating the properties.

2023-02-22 13:36 UTC, riodeuno commented on app/client/src/pages/Editor/PropertyPane/PropertyControl.tsx
> +        // Replace it with Abhinav's implementation of the same functionality on dynamic height, when available.
It is now available, however, it might not fit the use-case, let's discuss this if needed.

2023-02-22 13:36 UTC, riodeuno commented on app/client/src/pages/common/CanvasArenas/CanvasSelectionArena.tsx
> +  const appLayout = useSelector(getCurrentApplicationLayout) || "FLUID";
Could we return the value from the selector. Also, can we use an enum or a constant instead of the string "FLUID"?

2023-02-22 13:36 UTC, riodeuno commented on app/client/src/pages/common/CanvasArenas/hooks/canvasDraggingUtils.ts
> +  modifyBlock: boolean,
Please include the function of modifyBlock in the function comment above. Also, please elaborate on the rest of the entries.

2023-02-22 13:36 UTC, riodeuno commented on app/client/src/reducers/entityReducers/pageListReducer.tsx
> +  type: AppPositioningTypes;
Do we need this? I believe AppPositioningTypes can be used as a type. Could you point me to the code where it is being used, so that I can understand this?

2023-02-22 13:36 UTC, riodeuno commented on app/client/src/reducers/uiReducers/dragResizeReducer.ts
> +      draggedOn?: string;
There is always going to be a value which we can use instead of using `undefined` here. Can we have a default that's always the case. Due to the fact that this can be undefined, we now have to check for its availability, which I think is something we need to handle via data.

2023-02-22 14:17 UTC, prsidhu commented on app/client/src/ce/sagas/index.tsx
> +import SuperUserSagas from "@appsmith/sagas/SuperUserSagas";
cc: @marks0351 These were introduced in your initial commits.

2023-02-23 01:26 UTC, prsidhu commented on app/client/src/constants/minWidthConstants.ts
> +export const ICON_BUTTON_MIN_WIDTH = 50;
@riodeuno This change is being incorporated in the widget responsiveness PR.

2023-02-23 01:30 UTC, prsidhu commented on app/client/src/reducers/entityReducers/pageListReducer.tsx
> +  type: AppPositioningTypes;
@riodeuno Once statbox, list and form widgets have been fixed and converted to AutoLayout canvases, this check will be used as a global source of truth to determine fixed vs autoLayout canvas.

2023-02-23 01:50 UTC, prsidhu commented
/ok-to-test sha=33cae06

2023-02-23 07:00 UTC, marks0351 commented on app/client/src/ce/sagas/index.tsx
> +import SuperUserSagas from "@appsmith/sagas/SuperUserSagas";
https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode

Prettier does this under the hood. we could make this a standard coz it neatly sorts and orders the imports and also removes any unused imports.

I know i have been creating a lot of noise cause of changes like this. sry for that.

2023-02-23 09:09 UTC, riodeuno commented on app/client/src/ce/sagas/index.tsx
> +import SuperUserSagas from "@appsmith/sagas/SuperUserSagas";
We have a prettier config in our codebase. Does the config not have this flag? If it's not, can we add it, if we think this config is going to make things easier. If we don't think this is better, can we update this PR so that there aren't a lot of changes. It should as simple as adding the prettier config reference in vscode and then committing. Prettier should fix it, I think.

2023-02-23 13:02 UTC, riodeuno requested changes

2023-02-23 13:24 UTC, prsidhu commented on app/client/src/widgets/constants.ts
> +export const DRAG_MARGIN = 4;
This is a vestigial constant from when we were introducing margins during drag. Not being used now. Will remove it.

2023-02-23 13:30 UTC, prsidhu commented on app/client/src/utils/hooks/useTrace.tsx
> +export function useTraceUpdate(props: any, name?: string) {
This is not needed. Will remove it.

2023-02-24 02:53 UTC, prsidhu commented on app/client/src/widgets/TabsWidget/constants.ts
> +      positioning: Positioning;
@riodeuno This prop is only required for container like widgets that parent a canvas.

2023-02-24 05:29 UTC, marks0351 commented
/perf-test

2023-02-24 05:29 UTC, marks0351 commented
/build-deploy-preview

2023-02-27 06:00 UTC, riodeuno requested changes

2023-02-28 03:12 UTC, prsidhu commented
/ok-to-test sha=4c2ed8a

2023-02-28 03:14 UTC, prsidhu commented on app/client/src/sagas/CanvasSagas/AutoLayoutDraggingSagas.ts
> +  updatedWidgets[parentId] = {
@riodeuno Flex depends on the order in which children are presented to it. This (^) was crucial for horizontal stacks. What sort of issues could it lead to?

It might break cypress tests that depend on .get().eq() for selection.

2023-02-28 03:49 UTC, prsidhu commented
/ok-to-test sha=caaec16

2023-02-28 13:14 UTC, aswathkk commented on app/client/src/utils/layoutPropertiesUtils.ts
> +export const NonResizableWidgets = [
@preet,
We are working on moving information from `NonResizableWidgets` to Widget's configuration in #21041

2023-02-28 18:11 UTC, riodeuno reviewed
One more review update. Things are looking good overall. A few comments on code structure.

2023-02-28 18:11 UTC, riodeuno commented on app/client/src/selectors/editorSelectors.tsx
> +  type: "FLUID",
This should ideally be an enum based constant

2023-02-28 18:11 UTC, riodeuno commented on app/client/src/selectors/editorSelectors.tsx
> +export const getMainCanvasPositioning = createSelector(
Is this necessary anymore?

2023-02-28 18:11 UTC, riodeuno commented on app/client/src/widgets/ContainerWidget/component/index.tsx
> +  .auto-temp-no-display {
I'm not sure what this is for. Please elaborate

2023-02-28 18:11 UTC, riodeuno commented on app/client/src/widgets/ContainerWidget/widget/index.tsx
> +    super.componentDidMount();
This seems to serve no purpose. Please elaborate on what this is for

2023-02-28 18:11 UTC, riodeuno commented on app/client/src/widgets/ContainerWidget/widget/index.tsx
> +    const useAutoLayout = this.props.positioning
It seems like the this.props.positioning === positioning.vertical would have sufficed.

2023-02-28 19:57 UTC, riodeuno reviewed
This concludes the review of all files ✌️

2023-02-28 19:57 UTC, riodeuno commented on app/client/src/sagas/WidgetEnhancementHelpers.ts
> +export function appPositioningBasedPropertyFilter(
Note: Where is this being used?

2023-02-28 19:57 UTC, riodeuno commented on app/client/src/utils/autoLayout/AutoLayoutUtils.ts
> +    const canvasId = container.children ? container.children[0] : "";
This may give incorrect results for tabs widget

2023-02-28 19:57 UTC, riodeuno commented on app/client/src/utils/autoLayout/AutoLayoutUtils.ts
> +    if (!child) continue;
I was wondering why we needed to do this. Was it for the list widget's generated widgets?

2023-02-28 19:57 UTC, riodeuno commented on app/client/src/utils/autoLayout/AutoLayoutUtils.ts
> +  flexLayers = [
Another reason why map seems like a good idea when compared to array

2023-02-28 19:57 UTC, riodeuno commented on app/client/src/utils/autoLayout/AutoLayoutUtils.ts
> +      widget.mobileRightColumn = 64;
64 is a constant available in GridDefauls

2023-02-28 19:57 UTC, riodeuno commented on app/client/src/utils/autoLayout/AutoLayoutUtils.ts
> +      (canvasWidth * (widget.mobileRightColumn || 1)) / 64,
Should this be columnspace instead of canvaswidth?

2023-02-28 19:57 UTC, riodeuno commented on app/client/src/utils/autoLayout/AutoLayoutUtils.ts
> +export function getLayerIndexOfWidget(
Could we verify if we have missed any opportunities to use this function. I'm asking because I remember seeing code which does the exact same thing in other more complex functions

2023-02-28 19:57 UTC, riodeuno commented on app/client/src/utils/autoLayout/autoLayoutDraggingUtils.ts
> +            children: onlyUpdateFlexLayers
Should this be !onlyUpdateFlexLayers ?

2023-02-28 19:57 UTC, riodeuno commented on app/client/src/utils/autoLayout/autoLayoutDraggingUtils.ts
> +        if (prevParent && prevParent.children && isArray(prevParent.children)) {
Tip: Array.isArray takes care of undefined values so we don't need the previous check

2023-02-28 19:57 UTC, riodeuno commented on app/client/src/utils/autoLayout/autoLayoutTypes.ts
> +export interface HighlightInfo {
Nice!

2023-02-28 19:57 UTC, riodeuno commented on app/client/src/utils/autoLayout/highlightSelectionUtils.ts
> +  return Math.abs(Math.sqrt(distX * distX + distY * distY));
Hypotenuse!

2023-03-01 03:11 UTC, prsidhu commented on app/client/src/utils/autoLayout/AutoLayoutUtils.ts
> +    if (!child) continue;
It was a very basic attempt at conversion algorithm, when positioning of containers could be changed. Not needed. removed.

2023-03-01 03:11 UTC, prsidhu commented on app/client/src/utils/autoLayout/autoLayoutDraggingUtils.ts
> +            children: onlyUpdateFlexLayers
This is correct. if onlyUpdateFlexLayers is true, then we don't alter children.

2023-03-01 03:12 UTC, prsidhu commented on app/client/src/utils/autoLayout/AutoLayoutUtils.ts
> +    const canvasId = container.children ? container.children[0] : "";
unused. removed.

2023-03-01 03:14 UTC, prsidhu commented on app/client/src/widgets/ContainerWidget/widget/index.tsx
> +    super.componentDidMount();
removed.

2023-03-01 03:14 UTC, prsidhu commented on app/client/src/widgets/ContainerWidget/component/index.tsx
> +  .auto-temp-no-display {
removed.

2023-03-01 03:18 UTC, prsidhu commented on app/client/src/selectors/autoLayoutSelectors.tsx
> +    (layers: FlexLayer[]): number => {
@riodeuno There can be multiple layers. Each layer consists of three alignments. However, it can hold multiple widgets within those alignments. Had we used an object to define a layer. It would've been like:

layer: { [key: Alignmnet]: string[] }

We would've had to perform array operations regardless.

2023-03-01 03:19 UTC, prsidhu commented on app/client/src/selectors/autoLayoutSelectors.tsx
> +    return selectedLayer.children?.length;
yes. not used now. removed.

2023-03-01 06:25 UTC, prsidhu commented on app/client/src/pages/common/CanvasArenas/hooks/useAutoLayoutHighlights.ts
> +  let highlights: HighlightInfo[] = [];
@riodeuno yes, highlights don't survive re-renders. However, the highlight selection functionality is called on every mouse event. Hence, we have to persist this data to avoid redundant recalculation.

2023-03-01 06:26 UTC, prsidhu commented on app/client/src/pages/Editor/WidgetsEditor/CanvasContainer.tsx
> +CanvasContainer.whyDidYouRender = {
removed.

2023-03-01 06:26 UTC, riodeuno commented on app/client/src/pages/common/CanvasArenas/hooks/useAutoLayoutHighlights.ts
> +  let highlights: HighlightInfo[] = [];
Would it make a difference if we use `useRef` instead?

2023-03-01 06:31 UTC, riodeuno commented on app/client/src/selectors/autoLayoutSelectors.tsx
> +    (layers: FlexLayer[]): number => {
If I get this correctly, the array operations would be only on the widget list instead of the layer alignments themselves. My concern with `layers:FlexLayer[]` is that we are using nested loops which could be avoided by using maps which could be accessed by using `layers[Alignment.START]` or something similar.

This is more about the fact that nested loops cause reduced maintainability, than the logic itself.

Let me know if I'm getting this right.

2023-03-01 06:32 UTC, riodeuno commented on app/client/src/utils/autoLayout/autoLayoutDraggingUtils.ts
> +            children: onlyUpdateFlexLayers
Ah, I think I get it now.

2023-03-01 06:36 UTC, riodeuno commented on app/client/src/sagas/CanvasSagas/AutoLayoutDraggingSagas.ts
> +  updatedWidgets[parentId] = {
This is also more of a maintainability concern, let's say an year from now, I make changes to layout logic, and it slips my mind that the order of the children is important in the array. I will very likely create a bug. Also, the fact that we have to slice the array when ever we need to make any changes to the array, that leads to verbose code and not very readable. If we can maintain an index of the children separately, or change this data structure to a map, it would make things easier. 

The separate index is going to be another source of truth issue though.

I understand that changing how the DSL stores the children can be quite cumbersome at this point. This is the reason why I was wondering if there is a better way to do this.

2023-03-01 07:01 UTC, prsidhu commented on app/client/src/components/designSystems/appsmith/autoLayout/FlexBoxComponent.tsx
> +        wrapCenter={centerColumns > 64}
@riodeuno multiple alignments can get wrapped. 
e.g. flexLayer = {
START: ButtonWidget, InputWidget (Fill),
CENTER: ___,
END: ButtonWidget, InputWidget (Fill)
}

on mobile view port each input will want 64 columns.

2023-03-01 11:30 UTC, prsidhu commented
/ok-to-test sha=6435c5d

2023-03-02 02:59 UTC, prsidhu commented
/perf-test

2023-03-02 03:12 UTC, prsidhu commented
/perf-test

2023-03-02 04:03 UTC, prsidhu commented
/perf-test

2023-03-02 06:45 UTC, marks0351 commented
/perf-test

2023-03-02 07:33 UTC, marks0351 commented
/perf-test

2023-03-02 10:09 UTC, prsidhu commented
/perf-test

2023-03-02 10:20 UTC, prsidhu commented
/deploy-build-preview

2023-03-02 10:29 UTC, prsidhu commented
/build-deploy-preview

2023-03-02 10:33 UTC, prsidhu commented
/perf-test

2023-03-02 13:11 UTC, prsidhu commented
/build-deploy-preview

2023-03-02 13:12 UTC, prsidhu commented
/perf-test

2023-03-02 17:16 UTC, prsidhu commented
/build-deploy-preview

2023-03-02 17:25 UTC, prsidhu commented
/build-deploy-preview

2023-03-02 17:25 UTC, prsidhu commented
/ok-to-test sha=58c0db0

2023-03-03 04:12 UTC, prsidhu commented
/ok-to-test sha=7c31f61

2023-03-03 08:06 UTC, prsidhu commented
/build-deploy-preview

2023-03-03 08:51 UTC, yatinappsmith commented
/ci-merge-check

2023-03-03 09:54 UTC, prsidhu commented
/ok-to-test sha=233f6dc

2023-03-05 04:43 UTC, prsidhu commented on app/client/src/actions/autoLayoutActions.ts
> +export const removeWrappersAction = (parentId: string) => ({
added.

2023-03-05 04:45 UTC, prsidhu commented on app/client/src/components/editorComponents/DraggableComponent.tsx
> +  const widgetBoundaries = props.isFlexChild ? null : (
merged and updated.

2023-03-05 04:46 UTC, prsidhu commented on app/client/src/components/editorComponents/ResizableComponent.tsx
> +      ((props.isFlexChild &&
done.

2023-03-05 04:47 UTC, prsidhu commented on app/client/src/constants/PropertyControlConstants.tsx
> +  additionalAction?: (
Unused now. removed.

2023-03-05 04:47 UTC, prsidhu commented on app/client/src/constants/WidgetConstants.tsx
> +export const widgetTypeClassname = (widgetType: string): string =>
done.

2023-03-05 04:53 UTC, prsidhu commented on app/client/src/utils/autoLayout/positionUtils.ts
> +export type Widget = WidgetProps & {
updated.

2023-03-05 04:57 UTC, prsidhu commented on app/client/src/utils/WidgetPropsUtils.tsx
> +        rightColumn: fullWidth
@riodeuno Fill widgets will take up all available space. Ideally this information should come from the widget card / config itself. Doing so leads to rendering of a 64 column wide blue block while dragging a fill widget, which is an eye sore. The plan is to make this change once the drag blocks have been replaced by drag images (post v1). Does that work?

2023-03-05 05:01 UTC, prsidhu commented on app/client/src/components/designSystems/appsmith/autoLayout/AutoLayoutLayer.tsx
> + * 3. Only render start wrapper if a fill widget is present.
done.

2023-03-05 05:01 UTC, prsidhu commented on app/client/src/components/designSystems/appsmith/autoLayout/AutoLayoutLayer.tsx
> +export default React.memo(AutoLayoutLayer);
done.

2023-03-05 05:01 UTC, prsidhu commented on app/client/src/components/designSystems/appsmith/autoLayout/AutoLayoutLayer.tsx
> +  const flexDirection = getFlexDirection(getInverseDirection(props.direction));
removed.

2023-03-05 05:01 UTC, prsidhu commented on app/client/src/components/designSystems/appsmith/autoLayout/FlexBoxComponent.tsx
> +  const appMode = useSelector(getAppMode);
done.

2023-03-05 05:11 UTC, prsidhu commented on app/client/src/components/designSystems/appsmith/autoLayout/FlexBoxComponent.tsx
> +    const startColumns = columnInfo ? columnInfo[FlexLayerAlignment.Start] : 0,
done.

2023-03-05 05:11 UTC, prsidhu commented on app/client/src/components/designSystems/appsmith/autoLayout/FlexBoxComponent.tsx
> +      } else if (child.align === "center") {
done.

2023-03-05 05:11 UTC, prsidhu commented on app/client/src/components/designSystems/appsmith/autoLayout/FlexComponent.tsx
> +import { checkIsDropTarget } from "../PositionedContainer";
done.

2023-03-05 05:16 UTC, prsidhu commented on app/client/src/sagas/AutoLayoutUpdateSagas.tsx
> +      "updating layout for mobile viewport took",
done.

2023-03-05 05:16 UTC, prsidhu commented on app/client/src/sagas/AutoLayoutUpdateSagas.tsx
> +} from "../utils/autoLayout/AutoLayoutUtils";
done.

2023-03-05 05:16 UTC, prsidhu commented on app/client/src/sagas/CanvasSagas/AutoLayoutDraggingSagas.ts
> +    // console.error(e);
done.

2023-03-05 05:18 UTC, prsidhu commented on app/client/src/sagas/CanvasSagas/AutoLayoutDraggingSagas.ts
> +  const parentWidget = allWidgets[allWidgets[parentId].parentId || "0"];
done.

2023-03-05 05:23 UTC, prsidhu commented on app/client/src/pages/common/CanvasArenas/hooks/useAutoLayoutHighlights.ts
> +  const getDropInfo = (
updated.

2023-03-05 05:26 UTC, prsidhu commented on app/client/src/widgets/ContainerWidget/widget/index.tsx
> +    const useAutoLayout = this.props.positioning
removed.

2023-03-05 05:27 UTC, prsidhu commented on app/client/src/utils/autoLayout/autoLayoutDraggingUtils.ts
> +        if (prevParent && prevParent.children && isArray(prevParent.children)) {
done.

2023-03-05 05:28 UTC, prsidhu commented on app/client/src/utils/autoLayout/highlightSelectionUtils.ts
> +  return Math.abs(Math.sqrt(distX * distX + distY * distY));
done.

2023-03-05 14:27 UTC, prsidhu commented
/ok-to-test sha=3a1d327

2023-03-05 17:34 UTC, prsidhu commented
/ok-to-test sha=f9df3c7

2023-03-06 05:48 UTC, riodeuno commented on app/client/src/utils/WidgetPropsUtils.tsx
> +        rightColumn: fullWidth
Sounds good. Let's add a task for this in our project tracker as well.

2023-03-06 05:49 UTC, riodeuno commented on app/client/src/widgets/TabsWidget/constants.ts
> +      positioning: Positioning;
In this case, could we utilise the `isCanvas` property? Because, this property is for exactly the scenario you've described.

2023-03-08 03:02 UTC, prsidhu commented on app/client/src/widgets/WidgetUtils.ts
> +  if (props.isFlexChild) return false;
@riodeuno How do you suggest we handle this? We don't want to use autoHeight as is and this method is being called in multiple places.

2023-03-08 03:17 UTC, prsidhu commented on app/client/src/widgets/VideoWidget/widget/index.tsx
> +      ...getResponsiveLayoutConfig(this.getWidgetType()),
@riodeuno These props are automatically determined now and can't be changed by the user. Removing this for now as it is not needed.

2023-03-08 03:18 UTC, prsidhu commented on app/client/src/utils/hooks/useDynamicAppLayout.tsx
> +      appMode === "EDIT" &&
updated.

2023-03-08 03:19 UTC, prsidhu commented on app/client/src/utils/hooks/useDynamicAppLayout.tsx
> +    function relayoutAtBreakpoint() {
updated.

2023-03-08 03:20 UTC, prsidhu commented on app/client/src/utils/WidgetPropsUtils.tsx
> +          ? 64
updated.

2023-03-08 03:23 UTC, prsidhu commented on app/client/src/utils/WidgetPropsUtils.tsx
> +        rightColumn: fullWidth
added. https://github.com/orgs/appsmithorg/projects/12/views/8?pane=issue&itemId=22334764

2023-03-08 03:38 UTC, prsidhu commented on app/client/src/components/designSystems/appsmith/autoLayout/FlexBoxComponent.tsx
> +  isMobile?: boolean;
@riodeuno Updated these components to ensure that the props always hold a value. Doing the same to BaseWidget requires making a change to a LOT of files, most of which aren't event associated with this project at the moment. Is it okay to tackle this in a separate ticket once all the canvas have been converted to AutoLayout?

2023-03-08 03:39 UTC, prsidhu commented on app/client/src/components/designSystems/appsmith/autoLayout/FlexBoxComponent.tsx
> +        ? `${FLEXBOX_PADDING}px ${FLEXBOX_PADDING}px 22px ${FLEXBOX_PADDING}px`
@marks0351 Can you help with this?

2023-03-08 03:39 UTC, prsidhu commented on app/client/src/components/designSystems/appsmith/autoLayout/FlexComponent.tsx
> +export function FlexComponent(props: AutoLayoutProps) {
done.

2023-03-08 03:40 UTC, prsidhu commented on app/client/src/constants/WidgetConstants.tsx
> +export const FLEXBOX_PADDING = 4;
Done. Removed the unused constants. This is the one that is now being referred to in all places.

2023-03-08 06:39 UTC, marks0351 commented on app/client/src/components/designSystems/appsmith/autoLayout/FlexBoxComponent.tsx
> +        ? `${FLEXBOX_PADDING}px ${FLEXBOX_PADDING}px 22px ${FLEXBOX_PADDING}px`
have defined the widget name component height as a const.

2023-03-08 06:41 UTC, marks0351 commented on app/client/src/pages/Editor/AppPositionTypeControl.tsx
> +                      <div style={{ width: "16px", height: "16px" }}>
u mean just the icon to be defined as a separate view component?

2023-03-08 06:42 UTC, marks0351 commented on app/client/src/pages/Editor/AppPositionTypeControl.tsx
> +                    <button
This control will go away once we have app conversion feature. so thought we don't need the effort.

2023-03-08 06:44 UTC, marks0351 commented on app/client/src/pages/Editor/AppPositionTypeControl.tsx
> +          <Title className="text-sm">App Positioning Type</Title>
This is just a placeholder control for internal users until app conversion feature is done, do we still need to these changes?

2023-03-08 06:46 UTC, marks0351 commented on app/client/src/pages/Editor/AppPositionTypeControl.tsx
> +  const handleKeyDown = (event: React.KeyboardEvent, index: number) => {
^^ all this is just a rip off of existing MainContainerLayoutControl's implementation but i agree with you, we can create an issue on design system pod to create the necessary components.

2023-03-08 06:55 UTC, marks0351 commented on app/client/src/pages/common/CanvasArenas/hooks/useBlocksToBeDraggedOnCanvas.ts
> +    if (isNewWidget) addNewWidgetToAutoLayout(dropPayload, drawingBlocks);
yea makes sense, if we move them to the saga some overhead would be needed to fetch references, entities that the hook already provides but these functions would get defined only once rather than reinitiating each time the hook updates. but I think it should be part of efforts to clean up dragging arch, the current implementation is just trying to adhere to what is already there.

2023-03-08 06:57 UTC, marks0351 commented on app/client/src/selectors/editorSelectors.tsx
> +export const getMainCanvasPositioning = createSelector(
it's being removed in one of the trailing pr's. will merge it once we have the perf tests passing.

2023-03-08 07:10 UTC, prsidhu commented
/build-deploy-preview

2023-03-08 09:15 UTC, marks0351 commented
/perf-test

2023-03-08 11:16 UTC, prsidhu commented
/build-deploy-preview

2023-03-09 04:24 UTC, prsidhu commented on app/client/src/pages/common/CanvasArenas/hooks/useAutoLayoutHighlights.ts
> +  let highlights: HighlightInfo[] = [];
good idea. updated to employ useRef.

2023-03-09 04:27 UTC, prsidhu commented on app/client/src/sagas/WidgetOperationSagas.tsx
> +                parentChildren = [
@riodeuno We maintain the order separately in flexLayers. This was required for horizontal stacks which have been decommissioned since then.

2023-03-09 04:35 UTC, prsidhu commented on app/client/src/selectors/autoLayoutSelectors.tsx
> +    (layers: FlexLayer[]): number => {
@riodeuno Converting flexLayers to map will reduce some of the logic currently in place. However, this will be a big change in terms of volume of changes required. I'll create a ticket for this and take it up separately.

2023-03-09 04:41 UTC, marks0351 commented
/perf-test

2023-03-09 04:44 UTC, prsidhu commented on app/client/src/selectors/autoLayoutSelectors.tsx
> +    (layers: FlexLayer[]): number => {
https://github.com/orgs/appsmithorg/projects/12/views/8?pane=issue&itemId=22440250

2023-03-09 04:45 UTC, prsidhu commented on app/client/src/utils/autoLayout/AutoLayoutUtils.ts
> +      (canvasWidth * (widget.mobileRightColumn || 1)) / 64,
This is being handled in the widget responsiveness PR.

2023-03-09 05:24 UTC, prsidhu commented
/build-deploy-preview

2023-03-09 05:55 UTC, marks0351 commented
/build-deploy-preview

2023-03-09 07:00 UTC, riodeuno commented on app/client/src/selectors/autoLayoutSelectors.tsx
> +    (layers: FlexLayer[]): number => {
Yes, sounds good. Thanks!

2023-03-09 09:51 UTC, marks0351 commented
/perf-test

2023-03-14 07:55 UTC, prsidhu commented
/ok-to-test

2023-03-14 17:56 UTC, marks0351 commented
/ok-to-test

2023-03-14 17:57 UTC, marks0351 commented
/build-deploy-preview env=release

2023-03-15 06:59 UTC, marks0351 commented
/ok-to-test

2023-03-15 06:59 UTC, marks0351 commented
/build-deploy-preview env=release

2023-03-16 06:12 UTC, marks0351 commented
/perf-test

2023-08-31 09:01 UTC, closed without merging