fix: RestApiPlugin get request raw body fix
appsmithorg/appsmith pull request #18474
Opened 2022-11-27 08:54 UTC by vaibh1297

## Description

> RestApiPlugin fix for accepting raw body in get request.

Fixes #12343

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manual
- Unit Tests

## Checklist:
### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2022-12-13 07:15 UTC, vaibh1297 commented
/ok-to-test sha=2078d11

2022-12-13 07:56 UTC, sumitsum requested changes

2022-12-13 07:56 UTC, sumitsum commented on app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java
> +        actionConfiguration.setPaginationType(PaginationType.URL);
Should we should keep it as PaginationType.NONE, since we don't intend to use pagination ?

2022-12-13 07:56 UTC, sumitsum commented on app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java
> +        actionConfiguration.setFormData(Collections.singletonMap("apiContentType", MediaType.TEXT_PLAIN_VALUE));
Can you please check once if we do required this, since we are already setting the content type on line 240 as well ?

2022-12-13 07:56 UTC, sumitsum commented on app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java
> +            int currentIndex = i;
Instead of renaming the variable here, could we instead rename `i` to `requestBodyIndex` on line 264 itself ?

2022-12-13 07:56 UTC, sumitsum commented on app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java
> +                        final ActionExecutionRequest request = result.getRequest();
Instead of using `result.getRequest()` can you please check if `result.getBody()` can be used ? - reason being that APMU, the `request` object in `result` may actually be set by us as opposed to the remote service setting it.

2022-12-13 10:35 UTC, vaibh1297 commented on app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java
> +                        final ActionExecutionRequest request = result.getRequest();
But request and response body will be different, how can we validate if response is correct ?

2022-12-13 10:57 UTC, vaibh1297 commented on app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java
> +        actionConfiguration.setPaginationType(PaginationType.URL);
done

2022-12-13 10:57 UTC, vaibh1297 commented on app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java
> +        actionConfiguration.setFormData(Collections.singletonMap("apiContentType", MediaType.TEXT_PLAIN_VALUE));
Yes, this is required.

2022-12-13 10:58 UTC, vaibh1297 commented on app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java
> +            int currentIndex = i;
done

2022-12-13 11:06 UTC, vaibh1297 commented on app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java
> +                        final ActionExecutionRequest request = result.getRequest();
Also executed this test on release branch as well but it was not passed.

2022-12-20 06:19 UTC, sumitsum approved these changes

2022-12-20 11:40 UTC, sumitsum requested changes
Some un-intended client side changes have crept in the PR. Can you please check once ?

2022-12-20 13:59 UTC, sumitsum approved these changes

2022-12-20 17:31 UTC, vaibh1297 commented
/ok-to-test sha=7ae2e86

2022-12-30 09:28 UTC, vaibh1297 commented
/ok-to-test sha=2035b42

2022-12-30 12:04 UTC, merged