feat: Adding Embedding Apps Functionality
appsmithorg/appsmith pull request #18566
Opened 2022-11-29 19:57 UTC by NilanshBansal

## Description

This PR implements the functionality for Embedding Appsmith apps into any other platform. 

It reuses the following existing APIs:
- /api/v1/applications/{applicationId} (PUT)
- /api/v1/pages?pageId=<pageId> (GET)

An additional field `embedSetting` has been added to the `application` collection.

Fixes #18292 

## Job stories

> When I build an appsmith app, I want it to embed the app on another platform , so I can add new functionality to existing tools.

> When I embed an appsmith app, I want to easily configure the properties for embedding , so I can know all options available to me, and set it up as I please

> When I embed an appsmith app, I want it to have a visual interface to configure the embedded app, so I can do it without having to rely on documentation or outside resources

> When I embed an app, I want it to communicate with the platform it is embedded in , so I can leverage existing workflows/functionality of other tools, and enhance them using appsmith

## Type of change
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
- Manual

## Testing Results

> Postman testing results attached below

**Update EmbedSetting API**

- API Route: /api/v1/applications/{applicationId}
- API Method: PUT
- API JSON Response: [http://jsonblob.com/1047232397061668864](http://jsonblob.com/1047232397061668864)

<img width="1437" alt="image" src="https://user-images.githubusercontent.com/25542733/204628502-f0e8dd49-4980-4fba-bb33-2eb989838dc4.png">

- Database Record
<img width="848" alt="image" src="https://user-images.githubusercontent.com/25542733/204630143-68902501-7645-48bf-93e4-8b9f8da94180.png">

**GET EmbedSetting API**

- API Route: /api/v1/pages?pageId=<pageId>
- API Method: GET
- API JSON Response: [https://jsonblob.com/1047234433199128576](https://jsonblob.com/1047234433199128576)

<img width="964" alt="image" src="https://user-images.githubusercontent.com/25542733/204630880-29d4d12f-c299-458f-8c9f-21cb88db7041.png">

## Checklist:
### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reviewing all Cypress test

2022-11-30 10:57 UTC, sharat87 requested changes

2022-11-30 10:57 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/domains/Application.java
> +        private boolean showNavigationBar;
For classes that are used to deserialize data from the database, consider using boxed versions of primary data types. Like `Boolean` instead of `boolean`.

Why? Because if this field's value is `null` in the MongoDB document, then the deserializer will attempt to set this field to `null`, and that will throw a `NullPointerException`, since variables with primary types can _never_ be set to `null`.

So, any class, if it will be used for any deserialization, it's best to just use boxed versions, and be cautious of `null` values.

```suggestion
        private Boolean showNavigationBar;
```

2022-11-30 11:08 UTC, NilanshBansal commented on app/server/appsmith-server/src/main/java/com/appsmith/server/domains/Application.java
> +        private boolean showNavigationBar;
Updated

2022-11-30 11:12 UTC, sharat87 approved these changes

2022-12-01 10:55 UTC, NilanshBansal commented
/ok-to-test sha=7934ec3dfe0be9a8ea4d2c4ef3828c0b0fa6e0ae

2022-12-02 07:51 UTC, NilanshBansal commented
/ok-to-test sha=6580480614573558a6e41e61c9b8225c0aa476b8

2022-12-02 10:28 UTC, NilanshBansal commented
/ok-to-test sha=6580480614573558a6e41e61c9b8225c0aa476b8

2022-12-04 17:37 UTC, NilanshBansal commented
/ok-to-test sha=26abea8e0bf267c5fbb6e6f74d7395b99ce6adc2

2022-12-05 10:19 UTC, merged