chore: Update NavigateTo tests to verify params
appsmithorg/appsmith pull request #18581
Opened 2022-11-30 12:52 UTC by hetunandu

## Description

Recently, navigation broke where params were not retained when using the navigateTo function. Adding an assertion here to make sure it does not break again

2022-11-30 12:54 UTC, hetunandu commented
/ok-to-test

2022-11-30 12:57 UTC, rahulramesha requested changes

2022-11-30 12:57 UTC, rahulramesha commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/ActionExecution/NavigateTo_spec.ts
>      deployMode.DeployApp();
@hetunandu the issue was only in edit mode and this test in view mode, which did not break. Also, i remember @Aishwarya-U-R was also working on a similar spec.

2022-12-01 08:38 UTC, hetunandu commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/ActionExecution/NavigateTo_spec.ts
>      deployMode.DeployApp();
Updated to add edit mode assertion

2022-12-01 11:27 UTC, rahulramesha approved these changes

2022-12-02 04:07 UTC, hetunandu commented
/ok-to-test sha=9439647

2022-12-02 06:03 UTC, akash-codemonk approved these changes

2022-12-02 06:27 UTC, merged