chore: Update github actions to remove deprecation warnings
appsmithorg/appsmith pull request #18619
Opened 2022-12-02 05:03 UTC by hetunandu

## Description
Updating our github actions to remove deprecation warnings from ci

2022-12-02 05:03 UTC, hetunandu commented
/ok-to-test

2022-12-07 13:41 UTC, mohanarpit commented
@hetunandu Can we also improve the `set-output` invocations? This is also generates a big list of warnings in our Github actions.

2022-12-08 09:10 UTC, sharat87 commented on .github/workflows/integration-tests-command.yml
>            java-version: "11.0.10"
```suggestion
        with:
          java-version: "11.0.10"
          distribution: adopt
```

2022-12-08 09:20 UTC, sharat87 commented on .github/workflows/integration-tests-command.yml
> +        uses: actions/github-script@v6
This also seems to have a breaking change, https://github.com/actions/github-script#breaking-changes.

So I think we need to change `github.pulls` to `github.rest.pulls`, and `github.checks` to `github.rest.checks`.

(Github is not letting me add suggestion for those lines here).

2022-12-08 09:20 UTC, sharat87 commented on .github/workflows/server-build.yml
>            java-version: "11.0.10"
```suggestion
        with:
          java-version: "11.0.10"
          distribution: adopt
```

2022-12-08 09:21 UTC, sharat87 commented on .github/workflows/test-build-docker-image.yml
>            java-version: "11.0.10"
```suggestion
        with:
          java-version: "11.0.10"
          distribution: adopt
```

2022-12-08 09:22 UTC, sharat87 commented on .github/workflows/test-build-docker-image.yml
>            java-version: "11.0.10"
```suggestion
        with:
          java-version: "11.0.10"
          distribution: adopt
```

2022-12-08 09:22 UTC, sharat87 commented on .github/workflows/test-build-docker-image.yml
>            java-version: "11.0.10"
```suggestion
        with:
          java-version: "11.0.10"
          distribution: adopt
```

2022-12-10 05:17 UTC, sharat87 requested changes

2022-12-10 05:17 UTC, sharat87 commented on .github/workflows/appsmithctl.yml
> +          echo "appsmithctl_run_result=failed" >> $GITHUB_OUTPUT > ~/appsmithctl_run_result
I don't think multiple redirection works in `bash`. It works in `zsh`, I think, but not in `bash`. We'll have to use `tee`. I see a few other occurrences of this pattern, let's change them as well, to use `tee`.

```suggestion
          echo "appsmithctl_run_result=failed" | tee ~/appsmithctl_run_result >> $GITHUB_OUTPUT
```

<img width="940" alt="Screenshot 2022-12-10 at 10 41 46 AM" src="https://user-images.githubusercontent.com/120119/206830425-da190217-ec30-4c85-babd-182be18d1ee3.png">

2022-12-12 06:18 UTC, hetunandu commented on .github/workflows/appsmithctl.yml
> +          echo "appsmithctl_run_result=failed" >> $GITHUB_OUTPUT > ~/appsmithctl_run_result
@sharat87  I tested these changes on a forked repo and it worked as expected

2022-12-16 11:00 UTC, sharat87 commented on .github/workflows/appsmithctl.yml
> +          echo "appsmithctl_run_result=failed" >> $GITHUB_OUTPUT > ~/appsmithctl_run_result
Oh, that's interesting then! Cool, go ahead then.

2022-12-16 11:01 UTC, sharat87 approved these changes

2022-12-19 07:34 UTC, merged