Feature/min max date
appsmithorg/appsmith pull request #1865
Opened 2020-11-23 11:01 UTC by jsartisan

Fixes #1580

2020-11-24 05:14 UTC, hetunandu requested changes

2020-11-24 05:14 UTC, hetunandu commented on app/client/src/workers/evaluation.worker.ts
> +  [VALIDATION_TYPES.DATE_RANGE]: (
Rename to Default date

2020-11-24 05:14 UTC, hetunandu commented on app/client/src/components/propertyControls/DatePickerControl.tsx
> +          return;
Can we keep the date picker open yet still show the error. Right now it is closing it and resetting the input

2020-11-24 05:14 UTC, hetunandu commented on app/client/src/components/propertyControls/DatePickerControl.tsx
> +        !props.isValid ? `1px solid ${props.theme.colors.error}` : null};
Dont remove border when error it is valid. This will cause a stutter. Instead keep an neutral border of the same 1px width

2020-11-24 05:14 UTC, hetunandu commented on app/client/cypress/integration/Smoke_TestSuite/FormWidgets/DatePicker_spec.js
> +
Can add a test case for the default date validation as well here

2020-11-24 06:22 UTC, jsartisan commented on app/client/src/components/propertyControls/DatePickerControl.tsx
> +          return;
I just checked the docs. The `onChange` event is called after the user selects a date and we are using closeOnSelection as true. I can make closeOnSelection as false but that will not close the calendar even on selecting the right date.

2020-11-24 06:23 UTC, hetunandu commented on app/client/src/components/propertyControls/DatePickerControl.tsx
> +          return;
You can manually call the close after validation right?

2020-11-25 11:29 UTC, mohanarpit commented
@jsartisan Please improve the title of the PR.

2020-11-26 12:12 UTC, jsartisan commented on app/client/cypress/integration/Smoke_TestSuite/FormWidgets/DatePicker_spec.js
> +
@hetunandu added the test for the default date validation.

2020-11-26 12:16 UTC, jsartisan commented
@hetunandu Let me know if there is anything else needed in this PR.

2020-11-27 05:02 UTC, hetunandu approved these changes

2020-11-27 08:48 UTC, merged