Feat/code commenting #9369
appsmithorg/appsmith pull request #18667
Opened 2022-12-05 06:56 UTC by ravikp7

## Description
Adds code commenting in JS objects code editor and JS fields.

Fixes #9369

## Type of change

> Please delete options that are not relevant.

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
- Manual
- Jest

### Test Plan
> Add Testsmith test cases links that relate to this PR

### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)

## Checklist:
### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2022-12-05 08:47 UTC, rimildeyjsr requested changes

2022-12-05 08:47 UTC, rimildeyjsr commented on app/client/src/components/editorComponents/CodeEditor/utils/codeComment.ts
> +const nonWS = /[^\s\u00a0]/;
can we have a more descriptive name for this variable?

2022-12-05 08:47 UTC, rimildeyjsr commented on app/client/src/components/editorComponents/CodeEditor/utils/codeComment.ts
> +function firstNonWS(str: string) {
can we have a more descriptive name for this function?

2022-12-05 08:47 UTC, rimildeyjsr commented on app/client/src/components/editorComponents/CodeEditor/utils/codeComment.ts
> +  return found == -1 ? 0 : found;
can we have strict equality here?

2022-12-05 08:47 UTC, rimildeyjsr commented on app/client/src/components/editorComponents/CodeEditor/utils/codeComment.ts
> +  line: any,
can we add a type for this?

2022-12-05 08:47 UTC, rimildeyjsr commented on app/client/src/components/editorComponents/CodeEditor/utils/codeComment.ts
> +function probablyInsideString(
can we give a better name for the function?

2022-12-05 08:47 UTC, rimildeyjsr commented on app/client/src/components/editorComponents/CodeEditor/utils/codeComment.ts
> +function getMode(cm: CodeMirror.Editor, pos: CodeMirror.Position) {
this is a more generic function specific to the editor, can we move this to `codeEditorutils` file?

2022-12-05 08:47 UTC, rimildeyjsr commented on app/client/src/components/editorComponents/CodeEditor/utils/codeComment.ts
> +  return mode.useInnerComments === false || !mode.innerMode
nitpick - we can say `!mode.useInnerComments` here

2022-12-05 08:47 UTC, rimildeyjsr commented on app/client/src/components/editorComponents/CodeEditor/utils/codeComment.ts
> +    if (firstLine == null || probablyInsideString(self, from, firstLine))
nitpick - we can say `!firstLine` here

2022-12-05 08:47 UTC, rimildeyjsr commented on app/client/src/components/editorComponents/CodeEditor/utils/codeComment.ts
> +    );
can we move this part to its own function, getEndLinePosition?
also can we rename the variable to something more descriptive, this is a little hard to understand

2022-12-05 08:47 UTC, rimildeyjsr commented on app/client/src/components/editorComponents/CodeEditor/utils/codeComment.ts
> +    const pad = options.padding == null ? " " : options.padding;
nitpick - this can be `options.padding || " "`

also can we rename this constant to padding ?

2022-12-05 08:47 UTC, rimildeyjsr commented on app/client/src/components/editorComponents/CodeEditor/utils/codeComment.ts
> +    const blankLines = options.commentBlankLines || from.line == to.line;
lets use strict equality here

2022-12-05 08:47 UTC, rimildeyjsr commented on app/client/src/components/editorComponents/CodeEditor/utils/codeComment.ts
> +        /* Changes end */
do we need these changes? else lets get rid of them

2022-12-05 08:47 UTC, rimildeyjsr commented on app/client/src/components/editorComponents/CodeEditor/utils/codeComment.ts
> +          /* Changes end */
i think one comment line is enough, we don't need the changes end comment

2022-12-05 08:47 UTC, rimildeyjsr commented on app/client/src/components/editorComponents/CodeEditor/utils/codeComment.ts
> +          const cut = (baseString || "").length;
lets have a more descriptive constant here

2022-12-05 08:47 UTC, rimildeyjsr commented on app/client/src/components/editorComponents/CodeEditor/utils/codeComment.ts
> +          /* Changes end */
here also, we can get rid of the changes end comment

2022-12-05 08:47 UTC, rimildeyjsr commented on app/client/src/components/editorComponents/CodeEditor/utils/codeComment.ts
> +          /* Added below code to handle baseString individually for each line */
lets make this a line comment

2022-12-05 08:47 UTC, rimildeyjsr commented on app/client/src/components/editorComponents/CodeEditor/utils/codeComment.ts
> +          /* Changes end */
also if we don't need this, lets get rid of this

2022-12-05 08:47 UTC, rimildeyjsr commented on app/client/src/components/editorComponents/CodeEditor/utils/codeComment.ts
> +          /* Handle JS field lines starting with {{ */
lets change this to a line comment

2022-12-05 08:47 UTC, rimildeyjsr commented on app/client/src/components/editorComponents/CodeEditor/utils/codeComment.ts
> +          /* End changes for JS field handling */
here also, we can get rid of the changes end comment

2022-12-05 08:47 UTC, rimildeyjsr commented on app/client/src/components/editorComponents/CodeEditor/utils/codeComment.ts
> +            /* Handle JS field lines starting with {{ */
lets make this a line comment

2022-12-05 08:47 UTC, rimildeyjsr commented on app/client/src/components/editorComponents/CodeEditor/utils/codeComment.ts
> +            /* End changes for JS field handling */
here also, we can get rid of the changes end comment

2022-12-05 08:47 UTC, rimildeyjsr commented on app/client/src/components/editorComponents/CodeEditor/utils/codeComment.ts
> +    );
lets move this to a function

2022-12-05 08:47 UTC, rimildeyjsr commented on app/client/src/components/editorComponents/CodeEditor/utils/codeComment.ts
> +    let didSomething;
lets use a more descriptive variable name

2022-12-05 08:47 UTC, rimildeyjsr commented on app/client/src/components/editorComponents/CodeEditor/utils/codeComment.ts
> +    const pad = options.padding == null ? " " : options.padding;
can we rename this to `options.padding || " "`

2022-12-05 08:47 UTC, rimildeyjsr commented on app/client/src/components/editorComponents/CodeEditor/utils/codeComment.ts
> +        /* Change ends */
lets get rid of this if we don't need it

2022-12-05 08:47 UTC, rimildeyjsr commented on app/client/src/components/editorComponents/CodeEditor/utils/codeComment.ts
> +    if (open == -1) return false;
lets use strict equality here

2022-12-05 08:47 UTC, rimildeyjsr commented on app/client/src/components/editorComponents/CodeEditor/utils/codeComment.ts
> +  return isMacOrIOS() ? "Cmd-/" : "Ctrl-/";
you can have a object lookup that returns the shortcut needed

2022-12-05 08:47 UTC, rimildeyjsr commented on app/client/src/components/editorComponents/CodeEditor/utils/codeComment.ts
> +  cm.uncomment = function(from, to, options) {
can we move this part to its own function

2022-12-05 08:47 UTC, rimildeyjsr commented on app/client/src/components/editorComponents/CodeEditor/utils/codeComments.test.ts
> +import { handleCodeComment } from "./codeComment";
lets add cypress test cases for this as well, and get them reviewed by the QA team

2022-12-05 08:51 UTC, rimildeyjsr commented
@ravikp7 - you will have to add the title of the PR as  `feat:<title>` for the semantic PR check to pass.

Also, can we add a detailed PR description, with the shortcut keys described? This helps @theparthacus while preparing our release notes and serves as a future reference for anyone who needs to come back to this PR

2022-12-05 09:19 UTC, ravikp7 commented
@rimildeyjsr Most of the comments on the PR are on the code that I’ve copied from the codemirror comment library, and I know that code is pretty badly written. I just didn’t want to do any modifications to their code as it may introduce some unnecessary bugs. I want to keep it as close to the original code as possible, so I’ve put explicit comments where I’ve added my code or commented out their code. What do you think?

2022-12-05 09:20 UTC, ravikp7 commented on app/client/src/components/editorComponents/CodeEditor/utils/codeComment.ts
> +function getMode(cm: CodeMirror.Editor, pos: CodeMirror.Position) {
It's copied from the library, so kept it here only.

2022-12-05 09:21 UTC, ravikp7 commented on app/client/src/components/editorComponents/CodeEditor/utils/codeComment.ts
> +          /* Changes end */
I meant my changes end here. Like, this block has been inserted in the copied code.

2022-12-05 09:24 UTC, ravikp7 commented on app/client/src/components/editorComponents/CodeEditor/utils/codeComment.ts
> +  cm.lineComment = function(from, to, options = noOptions) {
We're overriding the existing `lineComment` function here. Not sure, what you're suggesting.

2022-12-05 09:32 UTC, ravikp7 commented on app/client/src/components/editorComponents/CodeEditor/utils/codeComment.ts
> +  return isMacOrIOS() ? "Cmd-/" : "Ctrl-/";
I think it's same for linux and windows, so went with `isMac` condition. We shouldn't need to handle linux and windows separately, right?

2022-12-07 04:40 UTC, ravikp7 commented on app/client/src/components/editorComponents/CodeEditor/utils/codeComment.ts
> +function probablyInsideString(
Can't come up with a better name, also not completely sure what it does, copied from the library. Let's leave this?

2022-12-07 04:48 UTC, ravikp7 commented on app/client/src/components/editorComponents/CodeEditor/utils/codeComment.ts
> +    );
Moved to a function

2022-12-07 05:00 UTC, ravikp7 commented on app/client/src/components/editorComponents/CodeEditor/utils/codeComment.ts
> +          const cut = (baseString || "").length;
Renamed with `offset`

2022-12-07 05:11 UTC, ravikp7 commented on app/client/src/components/editorComponents/CodeEditor/utils/codeComment.ts
> +    let didSomething;
Renamed with `didCommentCode`

2022-12-07 05:16 UTC, ravikp7 commented on app/client/src/components/editorComponents/CodeEditor/utils/codeComment.ts
> +    const lead = options.blockCommentLead || mode.blockCommentLead;
Renamed with `blockCommentLead`

2022-12-07 05:21 UTC, ravikp7 commented on app/client/src/components/editorComponents/CodeEditor/utils/codeComment.ts
> +      firstEnd == -1 || almostLastStart == -1 ? -1 : to.ch + almostLastStart;
It's very difficult to understand and we're not using block commenting, so I'm not in favor of modifying this code.

2022-12-07 05:23 UTC, ravikp7 commented on app/client/src/components/editorComponents/CodeEditor/utils/codeComment.ts
> +    return true;
I'm not sure of that, returning `false` also, doesn't affect anything, so just leaving it as it was.

2022-12-07 05:25 UTC, ravikp7 commented on app/client/src/components/editorComponents/CodeEditor/utils/codeComment.ts
> +  cm.uncomment = function(from, to, options) {
same comment as above.

2022-12-08 04:14 UTC, rimildeyjsr commented on app/client/src/components/editorComponents/CodeEditor/utils/codeComment.ts
> +  return isMacOrIOS() ? "Cmd-/" : "Ctrl-/";
Its better we handle for all cases

2022-12-08 04:14 UTC, rimildeyjsr commented on app/client/src/components/editorComponents/CodeEditor/utils/codeComment.ts
> +function probablyInsideString(
Can we assess the inputs and outputs to understand what it does? Else we can skip this

2022-12-08 04:14 UTC, rimildeyjsr commented on app/client/src/components/editorComponents/CodeEditor/utils/codeComment.ts
> +  cm.lineComment = function(from, to, options = noOptions) {
so we can have something like - 
const performLineCommenting = () => {}

and then set this function to cm.lineComment. We can do the same for uncomment as well

In my opinion, it makes the code little but readable, but let me know if you feel otherwise!

2022-12-08 04:14 UTC, rimildeyjsr commented on app/client/src/components/editorComponents/CodeEditor/utils/codeComment.ts
> +  cm.uncomment = function(from, to, options) {
replied above

2022-12-08 04:14 UTC, rimildeyjsr commented on app/client/src/components/editorComponents/CodeEditor/utils/codeComments.test.ts
> +import { handleCodeComment } from "./codeComment";
end to end testing will help us test the shortcut key scenarios, I think it would be helpful to have the E2E tests

2022-12-09 10:16 UTC, ravikp7 commented
@AnandiKulkarni Can you please help with E2E testing for this?

2022-12-12 04:10 UTC, ravikp7 commented on app/client/src/components/editorComponents/CodeEditor/utils/codeComments.test.ts
> +import { handleCodeComment } from "./codeComment";
Pushed E2E test

2022-12-12 04:11 UTC, ravikp7 commented
/ok-to-test sha=2e80158e28d87f23d43cfbe6e76a0c82859557c2

2022-12-12 05:12 UTC, Aishwarya-U-R reviewed
Cypress looks good!

2022-12-12 05:15 UTC, ravikp7 commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/VisualTests/JSEditorComment_spec.js
> +  it("comments code on the editor", () => {
added

2022-12-12 05:18 UTC, rimildeyjsr submitted a review, later dismissed

2022-12-13 11:50 UTC, ramsaptami commented
- [ ] Autocomplete does not work on a Windows machine. Selecting anything from the dropdown, closes the pop-up but does not insert anything

2022-12-13 15:32 UTC, ravikp7 commented
/ok-to-test sha=07cbc33f99063bde71deefe54c3fa5ffbe6dca56

2022-12-13 15:40 UTC, rimildeyjsr submitted a review, later dismissed

2022-12-20 08:47 UTC, ravikp7 commented
/ok-to-test sha=0090c53228675f1d82c1bfe0f84044346e78db65

2022-12-20 14:35 UTC, Aishwarya-U-R commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Autocomplete/PropertyPaneSuggestion_spec.js
> +  it("1. Should show Property Pane Suggestions on / command", () => {
Please consider writing tests in typescript. There is a /BugTests/Autocomplete_spec.ts which can be used to refer to the ts helpers available for validating this.

2022-12-22 05:39 UTC, Aishwarya-U-R commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Autocomplete/PropertyPaneSuggestion_spec.ts
> +      .click();
Can we use below instead:
`    agHelper.GetNAssertElementText(locator._hints, "New Binding");
`
`    agHelper.GetNClickByContains(locator._hints, "New Binding);
`

2022-12-22 05:39 UTC, Aishwarya-U-R commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Autocomplete/PropertyPaneSuggestion_spec.ts
> +      .click();
Same as above!

2022-12-22 05:39 UTC, Aishwarya-U-R commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Autocomplete/PropertyPaneSuggestion_spec.ts
> +});
Can you please also move the other related Autocomplete specs (js/ts) from BugTests into this Autocomplete folder please?

2022-12-22 05:39 UTC, Aishwarya-U-R commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/CodeComment/PropertyPaneCodeComment_spec.ts
> +    PropertyPane.TypeTextIntoField("Label", "{{appsmith}}");
TypeTextIntoField usually doesnt require - closing '}}', Hope these cases are passing!

2022-12-22 05:42 UTC, ravikp7 commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/CodeComment/PropertyPaneCodeComment_spec.ts
> +    PropertyPane.TypeTextIntoField("Label", "{{appsmith}}");
I've added `{{ }}` on purpose to test code commenting with JS snippets.

2022-12-22 07:10 UTC, ravikp7 commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Autocomplete/PropertyPaneSuggestion_spec.ts
> +});
Done

2022-12-22 07:10 UTC, ravikp7 commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Autocomplete/PropertyPaneSuggestion_spec.ts
> +      .click();
Done

2022-12-22 07:10 UTC, ravikp7 commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Autocomplete/PropertyPaneSuggestion_spec.ts
> +      .click();
Done, thanks!

2022-12-22 08:59 UTC, Aishwarya-U-R commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Autocomplete/PropertyPaneSuggestion_spec.ts
> +  it("1. Should show Property Pane Suggestions on / command", () => {
Is this feature automated against bug or test feature? If bug - can you please add the bug id to `it` or if feature - the related test smith id to `it` please?
So tomorrow if we need to automate some bug/test case when it comes to Automation team - we know its already covered & do not duplicate the work

2022-12-22 13:34 UTC, Rishabh-Rathod reviewed
Unit tests LGTM

2022-12-22 17:48 UTC, AnandiKulkarni commented
@ravikp7 below commenting in query is wrong 
Currently it is working as - select * from us
ers where name = {{ --input2.text,
input.text}}
ex: -- select * from users where name = {{ //input2.text,
input.text}}
<img width="1440" alt="Screenshot 2022-12-22 at 10 57 50 PM" src="https://user-images.githubusercontent.com/80756091/209195253-7f5db4c3-6abe-44a2-aba5-b714f00bc254.png">

2022-12-22 17:58 UTC, AnandiKulkarni commented
@ravikp7 Please find below recording on list widget cmd+l works outside {{}}, which does not evaluate anything but it works only before label and value and not before children, behaviour is very abrupt 

https://user-images.githubusercontent.com/80756091/209196871-f295647d-6a15-4e4d-b23c-d90dd09b1d83.mov

2022-12-22 19:10 UTC, ravikp7 commented
> @ravikp7 below commenting in query is wrong Currently it is working as - select * from us ers where name = {{ --input2.text, input.text}} ex: -- select * from users where name = {{ //input2.text, input.text}} <img alt="Screenshot 2022-12-22 at 10 57 50 PM" width="1440" src="https://user-images.githubusercontent.com/80756091/209195253-7f5db4c3-6abe-44a2-aba5-b714f00bc254.png">

@AnandiKulkarni This happened only when the cursor was placed inside the JS binding. Thanks for catching it. I've pushed a fix for it and added another unit test for this case.

2022-12-22 19:41 UTC, ravikp7 commented
> @ravikp7 Please find below recording on list widget cmd+l works outside {{}}, which does not evaluate anything but it works only before label and value and not before children, behaviour is very abrupt
> 
>  Screen.Recording.2022-12-22.at.11.20.18.PM.mov

@AnandiKulkarni I've fixed this issue as well and added unit tests, only the lines with text binding will get commented out with comments inside `{{ }}`. And, for the rest of the lines commenting will not work where `{{ }}` is not used because those lines are not JS, but just plain text.

2023-01-02 07:15 UTC, rimildeyjsr approved these changes

2023-01-02 07:17 UTC, ravikp7 commented
/ok-to-test sha=e0110bb8f6f1f29f05c50b12ec4d3fd1f7decb16

2023-01-02 08:30 UTC, ravikp7 commented
/ok-to-test sha=564de767b24e48424fe5296b642dbeca0e03cb8d

2023-01-02 09:52 UTC, ravikp7 commented
/perf-test sha=564de767b24e48424fe5296b642dbeca0e03cb8d

2023-01-02 10:29 UTC, ravikp7 commented
/ok-to-test sha=aeba6b22199408be4bc3473de29b484179517d94

2023-01-02 11:40 UTC, ravikp7 commented
/ok-to-test sha=4153fe29ea934db0d49bb0d4b8736170876d0331

2023-01-02 14:31 UTC, ravikp7 commented
/ok-to-test sha=004087ad10f4e66dee628a97b33bc5d7a1d3dfd7

2023-01-03 04:47 UTC, ravikp7 commented
/ok-to-test sha=004087ad10f4e66dee628a97b33bc5d7a1d3dfd7

2023-01-05 04:39 UTC, ravikp7 commented
/ok-to-test sha=994350755eb7281653062fed5dc6eed00aabc923

2023-01-05 15:50 UTC, ravikp7 commented
/ok-to-test sha=943ebfd60b255f8be0ec1102656ab7258c516af6

2023-01-05 17:47 UTC, rimildeyjsr submitted a review, later dismissed

2023-01-06 08:32 UTC, ravikp7 commented
/ok-to-test sha=6b6b26eed7d2342beecb724080e2eb2c3d716bef

2023-01-06 09:53 UTC, Aishwarya-U-R approved these changes

2023-01-06 11:57 UTC, merged