Test: updaed test for list widget
appsmithorg/appsmith pull request #18824
Opened 2022-12-09 09:44 UTC by NandanAnantharamu

Added test for list widget

2022-12-16 08:00 UTC, riodeuno requested changes

2022-12-16 08:00 UTC, riodeuno commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DynamicHeight/DynamicHeight_List_TextWidget_Spec.js
> +    it("Validate change with auto height width for list widgets", function () {
@NandanAnantharamu Let's add comments here where we describe what we're checking. The code is difficult to read for me.

2022-12-16 11:19 UTC, NandanAnantharamu commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DynamicHeight/DynamicHeight_List_TextWidget_Spec.js
> +    it("Validate change with auto height width for list widgets", function () {
I have added comments ,one thing drag and drop usecase were not possible so we have added tests using copy paste feature

2022-12-19 02:51 UTC, NandanAnantharamu commented
/ok-to-test sha=6ba9928

2022-12-19 05:22 UTC, NandanAnantharamu commented
/ok-to-test sha=fbf7eaf

2022-12-19 15:56 UTC, NandanAnantharamu commented
/ok-to-test sha=85fdb8d

2022-12-20 06:38 UTC, rahulramesha approved these changes

2022-12-20 14:08 UTC, NandanAnantharamu commented
/ok-to-test sha=8a103ea

2022-12-21 06:13 UTC, riodeuno approved these changes

2022-12-21 06:53 UTC, NandanAnantharamu commented
/ok-to-test sha=fee163d

2022-12-21 09:19 UTC, merged