feat: override helm chart images for init containers #18833
appsmithorg/appsmith pull request #18834
Opened 2022-12-09 22:39 UTC by ps-xaf

## Description

Small enhancement to permit usage of different image registries

Fixes #18833 1883

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Manual

## Checklist:
### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2022-12-12 19:25 UTC, ps-xaf commented
Manual test via helm template

Keeping the default values, we have the beahviour as before
```
$ helm dependency update                                                                                                                      
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "stable-appsmith" chart repository
<snip>...</snip>
Update Complete. ⎈Happy Helming!⎈
Saving 2 charts
Downloading redis from repo https://charts.bitnami.com/bitnami
Downloading mongodb from repo https://charts.bitnami.com/bitnami
Deleting outdated charts

$ helm template -n test appsmith-init-images . -s templates/statefulset.yaml | yq '.spec.template.spec.initContainers[].image'              
                                                                                                                              
"alpine"
"docker.io/bitnami/mongodb:4.4.11-debian-10-r12"
```


Overriding the default values, sets the values as required to use a different registry, image or tag.
```
$ helm dependency update                                                                                                      
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "stable-appsmith" chart repository
<snip>...</snip>
Update Complete. ⎈Happy Helming!⎈
Saving 2 charts
Downloading redis from repo https://charts.bitnami.com/bitnami
Downloading mongodb from repo https://charts.bitnami.com/bitnami
Deleting outdated charts

$ helm template -n test appsmith-init-images . -s templates/statefulset.yaml --set redis.images=123456789012.dkr.ecr.eu-west-1.amazonaws.com:external/alpine --set mongodb.images=123456789012.dkr.ecr.eu-west-1.amazonaws.com:external/ubuntu | yq '.spec.template.spec.initContainers[].image'
"123456789012.dkr.ecr.eu-west-1.amazonaws.com:external/alpine"
"123456789012.dkr.ecr.eu-west-1.amazonaws.com:external/ubuntu"

```

2022-12-16 10:54 UTC, sharat87 requested changes

2022-12-16 10:54 UTC, sharat87 commented on deploy/helm/templates/statefulset.yaml
> +        image: {{ .Values.redis.initImages | default "alpine" }}
Can we use the singular `image`, to make the meaning obvious please?

```suggestion
        image: {{ .Values.redis.image | default "alpine" }}
```

2022-12-16 10:54 UTC, sharat87 commented on deploy/helm/templates/statefulset.yaml
> +        image: {{ .Values.mongodb.initImages | default "docker.io/bitnami/mongodb:4.4.11-debian-10-r12" }}
```suggestion
        image: {{ .Values.mongodb.image | default "docker.io/bitnami/mongodb:4.4.11-debian-10-r12" }}
```

2022-12-16 10:54 UTC, sharat87 commented on deploy/helm/values.yaml
> +  initImages: alpine
```suggestion
  image: alpine
```

2022-12-16 10:54 UTC, sharat87 commented on deploy/helm/values.yaml
> +  initImages: docker.io/bitnami/mongodb:4.4.11-debian-10-r12
```suggestion
  image: docker.io/bitnami/mongodb:4.4.11-debian-10-r12
```

2022-12-18 19:35 UTC, ps-xaf commented on deploy/helm/templates/statefulset.yaml
> +        image: {{ .Values.redis.initImages | default "alpine" }}
I see your point, unfortunately the key **image** is passed [down to the subcharts of mongo](https://github.com/bitnami/charts/tree/b95989761f3feccc073f6739d4df62bf59ae34b7/bitnami/mongodb#mongodb-parameters) and [redis](https://github.com/bitnami/charts/tree/b95989761f3feccc073f6739d4df62bf59ae34b7/bitnami/redis#redis-image-parameters). 

Using it this way results in a parsing error:
```
$ git --no-pager diff
diff --git a/deploy/helm/templates/statefulset.yaml b/deploy/helm/templates/statefulset.yaml
index e42fd091d..b76251d71 100644
--- a/deploy/helm/templates/statefulset.yaml
+++ b/deploy/helm/templates/statefulset.yaml
@@ -51,7 +51,7 @@ spec:
       {{- end }}
       {{- if .Values.mongodb.enabled }}
       - name: mongo-init-container
-        image: {{ .Values.mongodb.initImages | default "docker.io/bitnami/mongodb:4.4.11-debian-10-r12" }}
+        image: {{ .Values.mongodb.image | default "docker.io/bitnami/mongodb:4.4.11-debian-10-r12" }}
         command: ['sh', '-c', "until mongo --host appsmith-mongodb.{{.Release.Namespace}}.svc.cluster.local --eval 'db.runCommand({ping:1})' ; do echo waiting for mongo; sleep 2; done"]
       {{- end }}
       containers:
diff --git a/deploy/helm/values.yaml b/deploy/helm/values.yaml
index f912aaeb0..6b8453374 100644
--- a/deploy/helm/values.yaml
+++ b/deploy/helm/values.yaml
@@ -9,7 +9,7 @@ redis:
 
 mongodb:
   enabled: true
-  initImages: docker.io/bitnami/mongodb:4.4.11-debian-10-r12
+  image: REGISTRY.LOCAL/bitnami/mongodb:4.4.11-debian-10-r12
   service:
     nameOverride: appsmith-mongodb
   auth:
```

```
$ helm template -n test appsmith-init-images .                    
Error: template: appsmith/charts/mongodb/templates/replicaset/statefulset.yaml:56:10: executing "appsmith/charts/mongodb/templates/replicaset/statefulset.yaml" at <include "mongodb.imagePullSecrets" .>: error calling include: template: appsmith/charts/mongodb/templates/_helpers.tpl:87:3: executing "mongodb.imagePullSecrets" at <include "common.images.pullSecrets" (dict "images" (list .Values.image .Values.metrics.image .Values.volumePermissions.image) "global" .Values.global)>: error calling include: template: appsmith/charts/mongodb/charts/common/templates/_images.tpl:36:14: executing "common.images.pullSecrets" at <.pullSecrets>: can't evaluate field pullSecrets in type interface {}

Use --debug flag to render out invalid YAML`
```

On a second thought it might even be better to keep the initContainer values out of the redis & mongo block, to avoid the misinterpretation that they could be passed through to the subcharts, at the end they are used in the appsmith chart only. 

I'll update the PR,  let me know what you think of the alternative approach

2022-12-20 20:30 UTC, ps-xaf commented
@sharat87 I've added a block for the init containers to the root of the chart as it seperates it from the subcharts.

2022-12-23 04:18 UTC, sharat87 requested changes
Hey @ps-xaf, sorry for the delay in getting to this. It was not showing up in my review queue, since it wasn't requested. Can you hit the request button so I can pick it up sooner please? Thanks man! 😃

![Screenshot 2022-12-23 at 9 46 44 AM](https://user-images.githubusercontent.com/120119/209269977-a7e32262-b81d-4674-af2f-38a7da625572.png)

2022-12-23 04:18 UTC, sharat87 commented on deploy/helm/templates/statefulset.yaml
> +      {{- end }}
I see that in the `values.yaml`, we set the default for this as `initContainer: {}`, which is an empty map.

But here, we check that if the `redis` key is not there in that map, we don't set an `image:` at all. Am I reading this right? Can we change the templating so that we _always_ ensure that an `image:` field is set? Something like:

```suggestion
      {{- if and .Values.initContainer.redis .Values.initContainer.redis.image }}
        image: {{ .Values.initContainer.redis.image }}
      {{- else }}
        image: "alpine"
      {{- end }}
```

Similarly for the MongoDB container as well. What do you think?

2022-12-23 11:05 UTC, ps-xaf commented
@sharat87 thanks and my bad. Will do next time. 🙂 

I'm traveling right now but will have a look at your requested changes when I am back home end of December.

2022-12-28 16:13 UTC, ps-xaf commented on deploy/helm/templates/statefulset.yaml
> +      {{- end }}
In the above case the outer condition has the else block (line 53/57/59) and we set the default image in line 58, if the redis key doesn't exists. 

Unfortunately the suggested change with function "and" doesn't work here, see also [Helm optional nested variables](https://stackoverflow.com/questions/59795596/helm-optional-nested-variables)

Therefore I've added the possible implementation from SO above, see also latest commit.

Out of the box chart, no initContainers set:
```
$ helm template -n test appsmith-init-images . -s templates/statefulset.yaml | yq '.spec.template.spec.initContainers[].image'              
"alpine"                                                                     
"docker.io/bitnami/mongodb:4.4.11-debian-10-r12"
```

Setting initContainers in values.yaml:
```
$ helm template -n test appsmith-init-images . -s templates/statefulset.yaml --set redis.images=123456789012.dkr.ecr.eu-west-1.amazonaws.com:external/alpine --set mongodb.images=123456789012.dkr.ecr.eu-west-1.amazonaws.com:external/ubuntu | yq '.spec.template.spec.initContainers[].image'          
"123456789012.dkr.ecr.eu-west-1.amazonaws.com:external/alpine"
"123456789012.dkr.ecr.eu-west-1.amazonaws.com:external/ubuntu
```

2022-12-29 05:22 UTC, sharat87 commented on deploy/helm/templates/statefulset.yaml
> +      {{- end }}
Awesome, thanks for pointing me to that detail. I didn't know parentheses had that feature in Go's template module. TIL.

Also, I just noticed that I misrepresented the problem I was noticing in this (now outdated) version of your code. What I wanted to point out what that, if `redis` is set, but `redis.image` is not set, then we'll be missing the `image:` key. But along the way I got confused and talked about it wrongly. The parent `if` does indeed have an `else`, like you point out, it's the child `if` that's missing one. 🙂

But not a problem, I see you've resolved this now. I'll approve in a moment, but we'll merge this next week, is that okay? Just want to avoid merging in the holiday season if I can. 🙂

2022-12-29 05:22 UTC, sharat87 approved these changes
Thank you so much @ps-xaf for your contribution here!

2022-12-29 14:47 UTC, ps-xaf commented on deploy/helm/templates/statefulset.yaml
> +      {{- end }}
Thank you and sorry for the back and forth. :slightly_smiling_face: Therefore no worries with the merge, whenever you are comfortable.   :slightly_smiling_face:

Also, just noticed the above helm template test is not correct, just for completeness here the corrected values settings as parameter. 
```
$ helm template -n test appsmith-init-images . -s templates/statefulset.yaml --set initContainer.redis.image=123456789012.dkr.ecr.eu-west-1.amazonaws.com:external/alpine --set initContainer.mongodb.image=123456789012.dkr.ecr.eu-west-1.amazonaws.com:external/ubuntu | yq '.spec.template.spec.initContainers[].image'                                                                                                              
                                                                                                      
"123456789012.dkr.ecr.eu-west-1.amazonaws.com:external/alpine"
"123456789012.dkr.ecr.eu-west-1.amazonaws.com:external/ubuntu"
```

I'll close the other comments above, as they are outdated.

2023-01-02 09:26 UTC, merged