test: List v2 meta widget generator jest test
appsmithorg/appsmith pull request #18949
Opened 2022-12-14 09:58 UTC by ashit-rath

## Description

Jest test for meta widget generator and minor refactor.

Fixes #16788

Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video

## Type of change
- Jest tests

## How Has This Been Tested?

- Manual
- Jest
- Cypress

### Test Plan
> Add Testsmith test cases links that relate to this PR

### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)

## Checklist:
### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2022-12-14 23:56 UTC, Tooluloope requested changes
The Properties belong to List widget not template widget

2022-12-14 23:56 UTC, Tooluloope commented on app/client/src/widgets/ListWidgetV2/MetaWidgetGenerator.test.ts
> +  it("it does not re-generates meta widgets options don't change", () => {
```suggestion
  it("it does not re-generates meta widgets when options don't change", () => {
```

2022-12-14 23:56 UTC, Tooluloope commented on app/client/src/widgets/ListWidgetV2/MetaWidgetGenerator.test.ts
> +  it("it re-generates meta widgets when template widgets page no changes", () => {
```suggestion
  it("it re-generates meta widgets when List widget page no changes", () => {
```

2022-12-14 23:56 UTC, Tooluloope commented on app/client/src/widgets/ListWidgetV2/MetaWidgetGenerator.test.ts
> +  it("it generates only extra meta widgets when template widgets page size increases", () => {
```suggestion
  it("it generates only extra meta widgets when List widget's page size increases", () => {
```

2022-12-14 23:56 UTC, Tooluloope commented on app/client/src/widgets/ListWidgetV2/MetaWidgetGenerator.test.ts
> +  it("it removes meta widgets when template widgets page size decreases", () => {
```suggestion
  it("it removes meta widgets when List widget's page size decreases", () => {
```

2022-12-15 09:14 UTC, ashit-rath commented on app/client/src/widgets/ListWidgetV2/MetaWidgetGenerator.test.ts
> +  it("it re-generates meta widgets when template widgets page no changes", () => {
@Tooluloope I think we should just mention
`it re-generates meta widgets when page no changes`

2022-12-15 09:15 UTC, Tooluloope commented on app/client/src/widgets/ListWidgetV2/MetaWidgetGenerator.test.ts
> +  it("it re-generates meta widgets when template widgets page no changes", () => {
Yes that's better @ashit-rath

2022-12-16 05:16 UTC, Tooluloope approved these changes

2022-12-16 06:36 UTC, merged