WIP: adding new api for release items, removing release items data from /a…
appsmithorg/appsmith pull request #18966
Opened 2022-12-15 07:45 UTC by vivonk

…pplication homepage api

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.

## Description

> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change
> Links to Notion, Figma or any other documents that might be relevant to the PR

> Add a TL;DR when description is extra long (helps content team)

Fixes # (issue)
> if no issue exists, please create an issue and ask the maintainers about this first

Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.
> Delete anything that is not important

- Manual
- Jest
- Cypress

### Test Plan
> Add Testsmith test cases links that relate to this PR

### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)

## Checklist:
### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2022-12-15 08:45 UTC, vivonk commented
/ok-to-test sha=c326f697b30719fbec500e33274986e1b7739cc2

2022-12-19 04:57 UTC, Rhitottam commented
/ok-to-test sha=1d8bf2c

2022-12-19 05:34 UTC, hetunandu requested changes

2022-12-19 05:34 UTC, hetunandu commented on app/client/src/sagas/ApplicationSagas.tsx
> +      // });
If this code is not needed, can we remove it instead of commenting it out

2022-12-19 05:44 UTC, trishaanand submitted a review, later dismissed
Server changes LGTM.

2022-12-19 05:44 UTC, trishaanand commented on app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/ApplicationControllerCE.java
> +        log.debug("Going to get version release items");
Could we remove this log?

2022-12-19 07:42 UTC, vivonk commented
/ok-to-test sha=fede93a970612471454f9d794008e2c1582afc4a

2022-12-20 05:09 UTC, Rhitottam commented
/ok-to-test sha=fede93a970612471454f9d794008e2c1582afc4a

2022-12-20 10:59 UTC, Rhitottam commented
/ok-to-test sha=fede93a970612471454f9d794008e2c1582afc4a

2022-12-20 18:09 UTC, Aishwarya-U-R commented
/ok-to-test sha=19824f0

2022-12-26 06:04 UTC, vivonk commented
/ok-to-test sha=278d1dc731c59a87bf236a00eeffa56197d5a0bc

2022-12-26 06:55 UTC, vivonk commented
@Rhitottam did you get a chance to look at the failing cypress tests?

2023-01-05 05:04 UTC, vivonk commented
/ok-to-test sha=7b42958a0fafa92af559027394b73c4721023654

2023-01-06 06:51 UTC, vivonk commented
/ok-to-test sha=356611d6f5cd074e2da2f16c0643fe17c419a8d1

2023-01-06 10:39 UTC, RakshaKShetty commented
@Rhitottam This is Fixed we can see the new API for the release notes

2023-01-06 13:07 UTC, Rhitottam commented
/ok-to-test sha=356611d6f5cd074e2da2f16c0643fe17c419a8d1

2023-01-09 04:39 UTC, Rhitottam commented
/ok-to-test sha=356611d6f5cd074e2da2f16c0643fe17c419a8d1

2023-01-09 06:22 UTC, Rhitottam commented
/ok-to-test sha=fa027a3c2efc552ffd36418b215d1feff9aa9555

2023-01-09 09:18 UTC, Rhitottam commented
/ok-to-test sha=ec0822855e65a85276e029f371dd000a4e762748

2023-01-09 13:27 UTC, Rhitottam commented
/ok-to-test sha=1740b47214fcc9adaab6fc06e19b62b6470ce04e

2023-01-09 16:42 UTC, Rhitottam commented
/ok-to-test sha=a4efc090f8f769dfc52222cbcfccd3816b82d234

2023-01-10 02:36 UTC, Rhitottam commented
/ok-to-test sha=a4efc090f8f769dfc52222cbcfccd3816b82d234

2023-01-10 09:40 UTC, Rhitottam commented
/ok-to-test sha=a6451035dd9786310db24e3eb8f4daa808ab1600

2023-01-10 09:49 UTC, hetunandu approved these changes

2023-01-10 09:49 UTC, hetunandu commented on app/client/src/ce/pages/Applications/index.tsx
> +    this.props.getAllApplication();
We should optimise this, as a separate issue.

I would suggest we call the api after anything is application changes. Does not make sense to keep calling that api since it is quite heavy

Or, if we already are sure what change it will do on the backend, just update the redux state directly

2023-01-10 10:01 UTC, Rhitottam commented on app/client/src/ce/pages/Applications/index.tsx
> +    this.props.getAllApplication();
Can track the issue in here: https://github.com/appsmithorg/appsmith/issues/19669

2023-01-11 05:38 UTC, merged