fix: auto height limits one row difference
appsmithorg/appsmith pull request #19001
Opened 2022-12-16 10:02 UTC by ankurrsinghal

## Description

....to be updated

Fixes # (issue)
> if no issue exists, please create an issue and ask the maintainers about this first

Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.
> Delete anything that is not important

- Manual
- Jest
- Cypress

### Test Plan
> Add Testsmith test cases links that relate to this PR

### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)

## Checklist:
### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2022-12-16 13:07 UTC, ankurrsinghal commented
/ok-to-test sha=ef07b23

2022-12-20 08:57 UTC, ankurrsinghal commented
/ok-to-test sha=9a27469

2022-12-20 14:44 UTC, Aishwarya-U-R commented
/ok-to-test sha=3e3f193

2022-12-20 20:02 UTC, riodeuno requested changes
@ankurrsinghal A couple of requests to change. I haven't seen the logic in `autoHeightOverlay/index.tsx`. 

The `BaseWidget.tsx` changes look fine to me.

2022-12-20 20:02 UTC, riodeuno commented on app/client/src/components/autoHeightOverlay/index.tsx
>      function onMaxStop() {
@ankurrsinghal Let us avoid defining functions within a component or another function. This is an anti-pattern and can cause performance issues.

2022-12-21 14:39 UTC, ankurrsinghal commented
/ok-to-test sha=7a3c6c8

2022-12-21 14:40 UTC, ankurrsinghal commented on app/client/src/components/autoHeightOverlay/index.tsx
>      function onMaxStop() {
Wanted to do this for a long time, to slice up this file into smaller components and use useCallback for the child props. Made those changes.

2022-12-21 14:40 UTC, ankurrsinghal commented on app/client/src/components/autoHeightOverlay/index.tsx
> +  batchUpdate: (options: { minHeight?: number; maxHeight?: number }) => void;
Added!

2022-12-21 18:47 UTC, riodeuno approved these changes

2022-12-22 07:45 UTC, ankurrsinghal commented
/ok-to-test sha=a9844df

2022-12-22 09:06 UTC, kamakshibhat-appsmith commented
Looks Good  @ankurrsinghal

2022-12-22 12:48 UTC, merged