feat: parent message listener
appsmithorg/appsmith pull request #19024
Opened 2022-12-19 04:30 UTC by eco-monk

## Description
When appsmith is embedded as an iframe, listen to messages from parent window.

Fixes #15538

## Global methods added
- `subscribeParentMessages`
```
subscribeParentMessages(
	"https://eco-monk.github.io", 
	(message) => { showAlert(message) }
)
```

- `unsubscribeParentMessages`
```
unsubscribeParentMessages("https://eco-monk.github.io")
```

## Todo
- [ ] `messageHandler` - check `event.currentTarget` vs `event.target` for event bubbling.
- [ ] Add methods in action creator

## Type of change
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Manual:
- Test by calling multiple subscribes and unsubscribes for same website (error message shown)
- Test with different origins (messages received only for subscribed origins)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-12-19 09:04 UTC, eco-monk commented
/ok-to-test sha=5060c49

2022-12-20 13:28 UTC, akash-codemonk requested changes

2022-12-20 13:28 UTC, akash-codemonk commented on app/client/src/AppRouter.tsx
> +            <RouteChangeListener />
I am guessing this is required in edit and view mode of an application. Should this be moved to AppViewer/index.tsx to not have to go through this code flow outside an application?

2022-12-21 02:06 UTC, eco-monk commented on app/client/src/AppRouter.tsx
> +            <RouteChangeListener />
Yes, I started out with something like that. But ended up here for two reasons.
- The redux event `ROUTE_CHANGED` becomes generic this way (which is implied in it's name) and `NavigationSaga` takes care of filtering out events according to it's needs.
- We want this event to be triggered when AppViewer and Editor is offloaded as well. 
e.g. when user exits an app (AppViewer/Editor is offloaded), we want to clear all subscriptions.

2023-01-20 04:22 UTC, closed without merging