feat: drag n drop and Container jump enhancements
appsmithorg/appsmith pull request #19047
Opened 2022-12-19 20:19 UTC by rahulramesha

## Description

> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change
> Links to Notion, Figma or any other documents that might be relevant to the PR

> Add a TL;DR when description is extra long (helps content team)

Fixes # (issue)
> if no issue exists, please create an issue and ask the maintainers about this first

Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.
> Delete anything that is not important

- Manual
- Jest
- Cypress

### Test Plan
> Add Testsmith test cases links that relate to this PR

### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)

## Checklist:
### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2022-12-22 17:05 UTC, rahulramesha commented
/ok-to-test sha=fbaf56d

2022-12-27 10:55 UTC, marks0351 requested changes

2022-12-27 10:55 UTC, marks0351 commented on app/client/src/reflow/reflowUtils.ts
> +  HORIZONTAL_RESIZE_LIMIT,
pls add min to the constants name.

2022-12-27 10:55 UTC, marks0351 commented on app/client/src/reflow/reflowUtils.ts
> +    ({
pls add comments to this.

2022-12-27 10:55 UTC, marks0351 commented on app/client/src/reflow/reflowUtils.ts
> +    return currentDirection;
pls add {}

2022-12-27 10:55 UTC, marks0351 commented on app/client/src/reflow/reflowUtils.ts
> +    return newSpacePosition;
{} braces please

2022-12-27 10:55 UTC, marks0351 commented on app/client/src/utils/hooks/useReflow.ts
> +          !collidingSpaces.some(
check if it is needed.

2022-12-27 19:10 UTC, rahulramesha commented on app/client/src/utils/hooks/useReflow.ts
> +          !collidingSpaces.some(
This check seems required as it stops from resetting params even when colliding with containers

2022-12-27 19:11 UTC, rahulramesha commented on app/client/src/pages/common/CanvasArenas/hooks/canvasDraggingUtils.ts
> +    fixedHeight === undefined
yes, if it has dynamic height it will not resize vertically

2022-12-27 19:11 UTC, rahulramesha commented
/ok-to-test sha=c4d9df9

2022-12-29 09:48 UTC, marks0351 submitted a review, later dismissed

2023-01-04 05:24 UTC, kamakshibhat-appsmith commented
https://www.loom.com/share/9808faae68004df79a9a6d3af5f73f42
The drop target is showing in red even though it is a legit one

2023-01-04 12:57 UTC, rahulramesha commented
/ok-to-test sha=6a44756

2023-01-05 06:06 UTC, rahulramesha commented
/ok-to-test sha=7b5058d

2023-01-05 15:15 UTC, kamakshibhat-appsmith commented
Looks good @rahulramesha

2023-01-05 15:15 UTC, kamakshibhat-appsmith commented
Looks good @rahulramesha

2023-01-05 19:59 UTC, rahulramesha commented
/ok-to-test sha=87204fc

2023-01-06 07:16 UTC, kamakshibhat-appsmith commented
few Questions:
1. The size of the input box is slightly increased and there is a scroll introduced inside the input box as soon as data type is changed to multi-line with fixed mode. This also makes the the input text inside the input box look misaligned because the text doesn't seem start from the top (there seems to be extra padding from the top than usual ) [LOOM](https://www.loom.com/share/0f5271f03c1941d98094fb5336c086db)
2. with data-type muti-line text and autoheight enabled, the default rows gets increased for the input type . is this expected? [LOOM](https://www.loom.com/share/6de48668c9124e128c298674c399dd99) 
@ankurrsinghal

2023-01-06 12:45 UTC, rahulramesha commented
/ok-to-test sha=fe019f3

2023-01-06 14:29 UTC, rahulramesha commented
/ok-to-test sha=0eff8c7

2023-01-06 16:57 UTC, merged

2023-01-20 20:38 UTC, Wall995501 commented
[GE](Wallpaper)