(WIP): Auto height instant update
appsmithorg/appsmith pull request #19082
Opened 2022-12-20 19:51 UTC by riodeuno

## Description
- [ ] Display the auto height updates during drag and resize, instead of after drop.

Fixes # (issue)
> if no issue exists, please create an issue and ask the maintainers about this first

Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.
> Delete anything that is not important

- Manual
- Jest
- Cypress

### Test Plan
> Add Testsmith test cases links that relate to this PR

### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)

## Checklist:
### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2022-12-23 08:36 UTC, SatishGandham commented
/perf-test
Testing performance infra, ignore.

2023-01-22 15:14 UTC, riodeuno commented on app/client/src/actions/autoHeightActions.ts
> +      resettingTabs: !!resettingTabs,
This will be removed if we don't find any issues with the Tabs Widget.

2023-01-22 15:15 UTC, riodeuno commented on app/client/src/components/editorComponents/DraggableComponent.tsx
> -  const dragBoundariesStyle: React.CSSProperties = useMemo(() => {
@rahulramesha @marks0351 I'll need some information on what this was doing. I've removed it, because, it seemed like it wasn't helpful.

2023-01-22 15:54 UTC, riodeuno commented on app/client/src/sagas/autoHeightSagas/containers.ts
> +  // Added this aciton payload to handle a scenario where the tabs widget's default is not Tab 1.
A comment to remember to do this.

2023-01-22 15:58 UTC, riodeuno commented on app/client/src/utils/autoHeight/mutateDOM.ts
> +function getNodesAndStylesToUpdate(
Add unit tests if possible.

2023-01-22 16:01 UTC, riodeuno commented on app/client/src/utils/WidgetPropsUtils.tsx
> +export function getCanvasWidgetHeightsToUpdate(
Add function doc and unit tests.

2023-01-22 16:02 UTC, riodeuno commented on app/client/src/utils/WidgetPropsUtils.tsx
> +export function getCanvasBottomRow(
Add function doc and tests

2023-01-22 16:39 UTC, riodeuno commented on app/client/src/components/editorComponents/DraggableComponent.tsx
> -  const dragBoundariesStyle: React.CSSProperties = useMemo(() => {
Nevermind, I got what this is about. I'll try to put this back.

2023-01-22 17:42 UTC, riodeuno commented
@rahulramesha @marks0351 @kamakshibhat-appsmith @Sripriya93 
This is now ready for QA and review.

2023-01-22 17:47 UTC, riodeuno commented
/ok-to-test sha=093649e

2023-01-22 18:38 UTC, riodeuno commented on app/client/src/pages/Editor/MainContainer.test.tsx
> +    // the above update to the main container now happens via a separate pathway (mutateDOM), and is not updated in the component
@marks0351 Please check this out.
In the meantime, I'll check with @appsmithorg/qa to see if we can automate this in cypress tests.

2023-01-22 18:43 UTC, riodeuno commented
/ok-to-test sha=bbaa131

2023-01-24 13:25 UTC, Sripriya93 commented
Observations @riodeuno 

1. Container as parent and tabs widget inside it, and when we drag a checkbox to go to the bottom tabs and container are both not resizing

https://user-images.githubusercontent.com/104895602/214274093-4c713200-eb89-4684-80b8-1978c26d7e4c.mp4

2. Tabs widget when we resize any widget inside it, we are seeing the dotted border of the tabs to be slightly above the actual size of the tabs

https://user-images.githubusercontent.com/104895602/214275855-38be1515-74a1-4224-bc0e-135e6b81a854.mp4

3. Canvas has a gap at the bottom when we drag and drop any widget in it.

![image](https://user-images.githubusercontent.com/104895602/214279800-b3697d35-f3e6-4f77-aae0-6aeebb95dba9.png)
 
4. Container as parent and tabs widget inside it, and when we drag a smaller widget to the bottom, we are able to see the scroll goes up a bit and reduces in height and when we drop the height enlarges to fit the widget.

https://user-images.githubusercontent.com/104895602/214284257-3607d8ab-6993-45e5-b662-4988d7a537a3.mp4

2023-01-24 13:27 UTC, riodeuno commented
@Sripriya93 Thank you for spotting these issues, I'll push fixes for this by tomorrow.

2023-01-24 18:05 UTC, Sripriya93 commented
5. Map widget have issue with displaying the map itself

![image](https://user-images.githubusercontent.com/104895602/214362993-e9bba502-4831-472d-91e5-60db454e3f24.png)

6. Able to see a huge space below Modal widget when we drag and drop it

https://user-images.githubusercontent.com/104895602/214363663-8e48648b-0fcf-4090-8887-62236d24e4ea.mp4

7. Modal widget collapses when we DnD a Tab widget inside it. (Also happens with JSON form, Switch group & stat box (When we move it a bit after placing it inside the Modal), )

https://user-images.githubusercontent.com/104895602/214364624-f9fbc640-e36c-4268-84b0-c4b70528088f.mp4

8. For Modal widget, we are seeing a scroll overriding the border of the widget.

<img width="290" alt="image" src="https://user-images.githubusercontent.com/104895602/214366164-0bd2ad30-feae-48b7-a8e1-50c77a6f627f.png">

9. Stat box inside Modal widget when we try to move it inside the Modal we are not able to see the position or the highlight of where the widget is placed at that moment 

https://user-images.githubusercontent.com/104895602/214368362-329ca407-d2bf-430d-9221-aac1271f9eea.mp4

10. Tabs widget, unnecessarily gets expand when we try to drop any widget inside the child widget, and then returning to the original height after the drop

https://user-images.githubusercontent.com/104895602/214370642-4e75f0ff-3360-408f-8c61-5287c3bdc6f7.mp4

11. Issue with Camera widget, size of the screen inside the camera is small

<img width="328" alt="image" src="https://user-images.githubusercontent.com/104895602/214371477-c3165bbe-f238-40c7-9510-c4aff657947d.png">

12. Progress widget is blank

<img width="272" alt="image" src="https://user-images.githubusercontent.com/104895602/214372205-ef8507d8-e5a4-4c1c-ac0b-728e5f6d8916.png">

2023-01-25 10:19 UTC, marks0351 requested changes

2023-01-25 10:19 UTC, marks0351 commented on app/client/src/widgets/ContainerWidget/component/index.tsx
> +  ${(props) => (props.noScroll ? `` : scrollCSS)}
pls check if box-shadow is necessary.

2023-01-26 11:03 UTC, riodeuno commented on app/client/src/components/editorComponents/ResizableComponent.tsx
> +    isAutoHeightEnabledForWidget(props, true) ||
Created an issue #20110

2023-01-26 11:06 UTC, riodeuno commented on app/client/src/components/designSystems/appsmith/WidgetStyleContainer.tsx
>    & > div {
Doesn't seem necessary.

2023-01-26 11:09 UTC, riodeuno commented on app/client/src/components/editorComponents/ResizableComponent.tsx
> +        className={`visibility-container-${props.widgetId}`}
Removed

2023-01-26 11:10 UTC, riodeuno commented on app/client/src/components/editorComponents/DropTargetComponent.tsx
> +      if (isParentAutoHeightEnabled || widgetId === MAIN_CONTAINER_WIDGET_ID) {
Done.

2023-01-26 11:10 UTC, riodeuno commented on app/client/src/actions/autoHeightActions.ts
> +export function immediatelyUpdateAutoHeightAction(
Used DOM keyword in the name.

2023-01-26 11:42 UTC, riodeuno commented on app/client/src/utils/WidgetPropsUtils.tsx
> +            if (bottomRow > 0)
Done.

2023-01-26 11:42 UTC, riodeuno commented on app/client/src/sagas/autoHeightSagas/helpers.ts
> +  if (widgetId === MAIN_CONTAINER_WIDGET_ID)
Done

2023-01-26 11:42 UTC, riodeuno commented on app/client/src/pages/common/CanvasArenas/StickyCanvasArena.tsx
> +      if (slidingArenaRef && slidingArenaRef.current)
Done.

2023-01-26 11:42 UTC, riodeuno commented on app/client/src/components/editorComponents/ErrorBoundry.tsx
> +      <ErrorBoundaryContainer className="error-boundary">
Done. Seems to be working fine.

2023-01-26 11:43 UTC, riodeuno commented on app/client/src/reducers/entityReducers/canvasWidgetsReducer.ts
> +    const canvasWidgetHeightsToUpdate: Record<
As discussed. We will make a conscious choice to make this change. I'll create a performance product note and share it on the team performance channel.

2023-01-26 11:52 UTC, riodeuno commented on app/client/src/widgets/ContainerWidget/component/index.tsx
> +  ${(props) => (props.noScroll ? `` : scrollCSS)}
Doesn't seem necessary, as it uses props.selected. which doesn't make sense.

2023-01-26 12:26 UTC, riodeuno commented on app/client/src/components/designSystems/appsmith/WidgetStyleContainer.tsx
> -      <div>{props.children}</div>
@Sripriya93 @kamakshibhat-appsmith Please help me test this.

2023-01-26 12:27 UTC, riodeuno commented
@marks0351 @rahulramesha This is once again ready for review.

2023-01-26 12:28 UTC, riodeuno commented
@kamakshibhat-appsmith @Sripriya93 This is ready for QA with the fixes for the known issues.

2023-01-26 13:23 UTC, riodeuno commented
/ok-to-test sha=2243f98

2023-01-27 13:48 UTC, Sripriya93 commented
@riodeuno here are the issues found today
1. Large space below the Modal widget is still seen (Already discussed please ignore)

2. White space seen below canvas, Is it expected?
![image](https://user-images.githubusercontent.com/104895602/215020833-3887a833-3cdd-403a-8ef0-03d1273c59bd.png)

3. Tabs widget, unnecessarily gets expand when we try to drop any widget inside the child widget, and then returning to the expected height after the drop, because of this when we put tabs widget inside container, we are not able to drop any widget at the bottom of the container, even if we scroll

4. When we have Tabs widget inside container and drop a widget inside Tab and scroll down in the container to place a widget at the bottom of the container, and move the mouse the tabs and container scroll back 

https://user-images.githubusercontent.com/104895602/215035259-d7a80d30-7e16-4220-8878-9a43ad31f077.mp4

5. Slider are all Top aligned, in release they are center aligned

6. No signifiers seen in Modal widget

https://user-images.githubusercontent.com/104895602/215056189-1066cd61-fd8b-4068-be45-4f545f14cf1c.mp4

7. Scroll contents toggle not working for Forms widget, in Fixed height

<img width="743" alt="image" src="https://user-images.githubusercontent.com/104895602/215077418-e907b5fb-6287-4eaf-9768-bcd4d2fd673d.png">

8. When we have widgets inside Tabs in Fixed height and when toggle off Scroll contents, we are seeing the widgets inside them disappears

https://user-images.githubusercontent.com/104895602/215076893-c58972ea-85d3-4d26-80b9-5da860d95131.mp4

9. Scroll doesnt get smaller when we remove from the bottom of the canvas

10. Widgets at the corner of the Container and Form widget with Border radius as 1.5 rem, widgets at the corner are not respecting the border radius

<img width="497" alt="image" src="https://user-images.githubusercontent.com/104895602/215094637-3ae96186-5bac-4743-9780-91053c89d4da.png">
<img width="334" alt="image" src="https://user-images.githubusercontent.com/104895602/215094742-f9888ebb-1617-415c-a9d4-381474f390d8.png">

11. In all container like widgets, in fixed height when resized to larger size after we drop two or three widgets, we arent able to drop another widget at the bottom of the widget

https://user-images.githubusercontent.com/104895602/215097699-9f8b2c4b-363e-4261-8fed-cf2ab9cb5c01.mp4

12. In fixed height in Modal widget scroll isnt working, so we are not able to place widgets

https://user-images.githubusercontent.com/104895602/215098588-60beff7e-9128-4c1f-a25f-37440b16d137.mp4

2023-01-29 20:24 UTC, riodeuno commented
@Sripriya93 First of all, thanks for finding these issues. These are issues I would not have noticed, and thanks to you finding them, I have more confidence in this feature.

> White space seen below canvas, Is it expected?
I need help replicating this issue. Please show me the steps to do this.

> Tabs widget, unnecessarily gets expand when we try to drop any widget inside the child widget, and then returning to the expected height after the drop, because of this when we put tabs widget inside container, we are not able to drop any widget at the bottom of the container, even if we scroll

This is a direct consequence of auto height instant update. I will not be fixing this in this release. We need to go back to the drawing board to figure out a good approach here.

> When we have Tabs widget inside container and drop a widget inside Tab and scroll down in the container to place a widget at the bottom of the container, and move the mouse the tabs and container scroll back

This happens because on focus, the widget name component shows up. This adds a small scroll.

> Slider are all Top aligned, in release they are center aligned

Fixed

> No signifiers seen in Modal widget

Fixed

> Scroll contents toggle not working for Forms widget, in Fixed height

Fixed

> When we have widgets inside Tabs in Fixed height and when toggle off Scroll contents, we are seeing the widgets inside them disappears

Fixed

> Widgets at the corner of the Container and Form widget with Border radius as 1.5 rem, widgets at the corner are not respecting the border radius

Fixed

> In all container like widgets, in fixed height when resized to larger size after we drop two or three widgets, we arent able to drop another widget at the bottom of the widget

I can't seem to replicate this. I believe the fixes for the above issues, must have fixed this, please let me know if this is consistently happening

> In fixed height in Modal widget scroll isnt working, so we are not able to place widgets

Fixed

2023-01-29 22:19 UTC, riodeuno commented
/ok-to-test sha=4e7c4c6

2023-01-30 07:35 UTC, Sripriya93 commented
@riodeuno Have retested the fixed issues and saw some issues mentioned below, will take a look at the PR again later today or tomorrow, 
1. Container like widgets are not reflowing (At the beginning of the loom we would be able to see the white space after we DnD a container widget)

https://user-images.githubusercontent.com/104895602/215408669-cd4f68c7-6c6c-4cb5-8b26-16b853410db1.mp4

2. Widget jumps when we drag and drop while reflow 

https://user-images.githubusercontent.com/104895602/215409520-a8574e59-2bd8-4e85-8dd0-754db54b808f.mp4

2023-01-30 19:29 UTC, riodeuno commented
/ok-to-test sha=2e6dd04

2023-01-31 07:09 UTC, marks0351 requested changes

2023-01-31 07:09 UTC, marks0351 commented on app/client/src/components/designSystems/appsmith/WidgetStyleContainer.tsx
>    & > div {
looks like its still exists.

2023-01-31 07:10 UTC, marks0351 commented
PR looks good. let me know once all bugs are fixed, il approve it one last time.

2023-01-31 23:39 UTC, riodeuno commented
@Sripriya93 
> Container like widgets are not reflowing

I noticed the same experience on release, so I will not be fixing this in this PR.

> Widget jumps when we drag and drop while reflow

This is a consequence of the widget needing more height when the auto height is computed. This is also something which we won't be fixing in this PR. This needs a product discussion.

2023-01-31 23:46 UTC, riodeuno commented on app/client/src/components/designSystems/appsmith/WidgetStyleContainer.tsx
>    & > div {
Yes, I forgot to mention it here. This turns out to be necessary. I found this when I was fixing QA issues.

2023-01-31 23:46 UTC, riodeuno commented on app/client/src/components/designSystems/appsmith/WidgetStyleContainer.tsx
>    & > div {
I added it back in this commit: https://github.com/appsmithorg/appsmith/pull/19082/commits/0d9417271083feb46f811dc3e85b2b381458cb8a

2023-01-31 23:53 UTC, riodeuno commented
/ok-to-test sha=3890aa8

2023-02-01 12:18 UTC, riodeuno commented
/ok-to-test sha=769ea75

2023-02-01 12:59 UTC, marks0351 submitted a review, later dismissed

2023-02-01 13:39 UTC, Sripriya93 commented
@riodeuno This PR is good to go.

2023-02-02 12:01 UTC, riodeuno commented
/ok-to-test sha=433b06f

2023-02-02 12:51 UTC, riodeuno commented
/ok-to-test sha=433b06f

2023-02-02 13:20 UTC, riodeuno commented
/ok-to-test sha=f7e5f91

2023-02-02 14:22 UTC, riodeuno commented
/perf-test

2023-02-03 05:46 UTC, marks0351 approved these changes

2023-02-03 05:47 UTC, merged

2023-02-12 19:07 UTC, kamakshibhat-appsmith commented
With this PR , do we expect fix for the issue where scrollbars were coming in deploy mode when border width was increased for container type(auto height) widgets ? @riodeuno

2023-02-13 03:00 UTC, riodeuno commented
@kamakshibhat-appsmith Yes, this PR should have fixed that. I can replicate this on release right now. Let me look into this.