chore: test anonymous id
appsmithorg/appsmith pull request #19122
Opened 2022-12-22 04:39 UTC by eco-monk

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.

## Description

> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change
> Links to Notion, Figma or any other documents that might be relevant to the PR

> Add a TL;DR when description is extra long (helps content team)

Fixes # (issue)
> if no issue exists, please create an issue and ask the maintainers about this first

Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.
> Delete anything that is not important

- Manual
- Jest
- Cypress

### Test Plan
> Add Testsmith test cases links that relate to this PR

### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)

## Checklist:
### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2022-12-23 04:58 UTC, SatishGandham commented
/perf-test
Just testing perf infra

2022-12-30 06:31 UTC, eco-monk commented
/ok-to-test sha=657cdb8

2023-01-02 07:33 UTC, Nikhil-Nandagopal reviewed
@eco-monk left my comments

2023-01-02 07:33 UTC, Nikhil-Nandagopal commented on app/client/src/api/ApiUtils.ts
> +  if (config.headers) {
@eco-monk if config.headers is not there then we should add it instead of not sending the values right?

2023-01-02 07:33 UTC, Nikhil-Nandagopal commented on app/client/src/utils/AnalyticsUtil.tsx
> +      windowDoc.analytics?.user?.().anonymousId() ||
This is kind of unreadable. Can you split this and make it simple for anyone else to understand?

2023-01-03 05:59 UTC, eco-monk commented on app/client/src/api/ApiUtils.ts
> +  if (config.headers) {
Yep, that's right.

2023-01-03 06:05 UTC, eco-monk commented on app/client/src/utils/AnalyticsUtil.tsx
> +      windowDoc.analytics?.user?.().anonymousId() ||
Done.

2023-01-03 06:06 UTC, eco-monk commented on app/client/src/api/ApiUtils.ts
> +  if (config.headers) {
Done

2023-01-04 15:02 UTC, eco-monk commented
/ok-to-test sha=2f98936

2023-01-04 16:04 UTC, eco-monk commented
/ok-to-test sha=42d5fa8

2023-01-05 05:03 UTC, hetunandu requested changes
Looks good. Just remove the comments

2023-01-05 10:05 UTC, eco-monk commented
Thanks @hetunandu.!
Will keep the logs for now, to test this.
Will remove once done.

2023-01-05 10:37 UTC, eco-monk commented
/ok-to-test sha=9a6ec56

2023-01-05 12:27 UTC, eco-monk commented
/ok-to-test sha=865d371

2023-01-06 08:21 UTC, eco-monk commented
/ok-to-test sha=ac22c86

2023-01-06 09:35 UTC, eco-monk commented
/ok-to-test sha=96925cd

2023-01-06 14:09 UTC, merged