feat: multi-line input and auto-resize textarea
appsmithorg/appsmith pull request #19141
Opened 2022-12-22 17:19 UTC by ankurrsinghal

## Description

....to be filled

Fixes # (issue)
> if no issue exists, please create an issue and ask the maintainers about this first

Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.
> Delete anything that is not important

- Manual
- Jest
- Cypress

### Test Plan
> Add Testsmith test cases links that relate to this PR

### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)

## Checklist:
### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2022-12-23 04:57 UTC, SatishGandham commented
/perf-test
Just testing perf infra

2022-12-23 07:47 UTC, SatishGandham commented
/perf-test
Testing performance infra, ignore.

2022-12-23 08:35 UTC, SatishGandham commented
/perf-test
Testing performance infra, ignore.

2022-12-23 10:02 UTC, riodeuno commented
@ankurrsinghal As there are pending tasks in the PR description. I'm going to convert this to draft.

2022-12-27 13:49 UTC, ankurrsinghal commented
/ok-to-test sha=a2c8c6c

2022-12-28 14:10 UTC, ankurrsinghal commented
test....

2022-12-28 14:39 UTC, riodeuno commented on app/client/src/utils/migrations/autoHeightMigrations.ts
> +            GRID_DENSITY_MIGRATION_V1 + 4
GRID_DENSITY_MIGRATION is not longer relevant, it has been more than year since we added this check. Almost a 100% of our users should have upgraded their version of Appsmith by now.

2022-12-29 09:12 UTC, ankurrsinghal commented on app/client/src/utils/migrations/autoHeightMigrations.ts
> +            GRID_DENSITY_MIGRATION_V1 + 4
But Abhinav, in release today this used to identify whether there should be input or textarea in the input widget, so I used the same thing to migrate the config.

2022-12-29 09:14 UTC, ankurrsinghal commented
/ok-to-test sha=5190a9c

2022-12-29 09:15 UTC, ankurrsinghal commented
@Sripriya93 @kamakshibhat-appsmith there are now changes releated to the alignment of the input field and the label also, which makes them similar to Datepicker widget and other select widgets.

2022-12-29 11:49 UTC, ankurrsinghal commented
/ok-to-test sha=37e6af5

2022-12-30 10:44 UTC, Sripriya93 commented
Moving to reopen as we are facing the below issue

https://images.zenhubusercontent.com/275993885/e1c163b3-5aef-48ae-98c2-49465ba503e4/untitled_application_1___editor___appsmith___30_december_2022__1_.mp4

2023-01-05 09:07 UTC, ankurrsinghal commented
/ok-to-test sha=64c30b9

2023-01-05 09:11 UTC, kamakshibhat-appsmith commented
Migration is failing, pls check @ankurrsinghal

2023-01-05 13:22 UTC, ankurrsinghal commented
/ok-to-test sha=d43410a

2023-01-05 15:30 UTC, kamakshibhat-appsmith commented
Migration is working @ankurrsinghal

2023-01-06 07:19 UTC, kamakshibhat-appsmith commented
few Questions:
1. The size of the input box is slightly increased and there is a scroll introduced inside the input box as soon as data type is changed to multi-line with fixed mode. This also makes the the input text inside the input box look misaligned because the text doesn't seem start from the top (there seems to be extra padding from the top than usual ) [LOOM](https://www.loom.com/share/0f5271f03c1941d98094fb5336c086db)
2. with data-type muti-line text and autoheight enabled, the default rows gets increased for the input type . is this expected? [LOOM](https://www.loom.com/share/6de48668c9124e128c298674c399dd99) 
@ankurrsinghal

2023-01-06 08:56 UTC, ankurrsinghal commented
test...

2023-01-06 09:03 UTC, ankurrsinghal commented
test

2023-01-06 09:08 UTC, ankurrsinghal commented
/ok-to-test sha=d2de1e3

2023-01-06 11:31 UTC, ankurrsinghal commented
/ok-to-test sha=780d5dd

2023-01-06 11:39 UTC, ankurrsinghal commented
@Sripriya93 @kamakshibhat-appsmith I think feature wise everything is done, after I made the requested changes, can we have a final round of ruthless testing?

2023-01-06 13:07 UTC, kamakshibhat-appsmith commented
@ankurrsinghal Regex validation doesn't seem to be working fro Multi-line input

2023-01-06 13:15 UTC, kamakshibhat-appsmith commented
Regex validation doesn't seem to work for multi-line input 
@ankurrsinghal

2023-01-09 12:03 UTC, Sripriya93 commented
Regex validation is working now, Moving to review, to know if the Icon property has to be removed for Multi line text data type.

2023-01-10 07:39 UTC, riodeuno commented
> The font icon and position is not working for multi line input(If icon is not needed , then can we remove it from properties)

@ankurrsinghal These properties do not make sense in a multi-line input, let's hide these properties when multi-line is selected. 

Good catch @kamakshibhat-appsmith 

cc: @dilippitchika @rohitagarwal88

2023-01-10 07:55 UTC, riodeuno requested changes
A few request for changes.

2023-01-10 07:55 UTC, riodeuno commented on app/client/src/components/editorComponents/AutoResizeTextArea.tsx
> +const PADDING = 10;
Please add a comment explaining this value. Why do we need it and where will it be used?

2023-01-10 07:55 UTC, riodeuno commented on app/client/src/components/editorComponents/AutoResizeTextArea.tsx
> +  box-sizing: border-box;
Is `border-box` not the default?

2023-01-10 07:55 UTC, riodeuno commented on app/client/src/components/editorComponents/AutoResizeTextArea.tsx
> +  function updateHeight() {
Let's try not to define a function within a component. Let's move it outside the component and pass anything we need within it as props.

2023-01-10 07:55 UTC, riodeuno commented on app/client/src/components/editorComponents/AutoResizeTextArea.tsx
> +  function assignRef(element: HTMLTextAreaElement) {
Let's move this function definition outside this component.

2023-01-10 07:55 UTC, riodeuno commented on app/client/src/widgets/InputWidgetV2/widget/index.tsx
> -    const minInputSingleLineHeight =
@ankurrsinghal Ok,, now the migrations make sense. It also helps have confidence in the migrations 😅

2023-01-10 08:30 UTC, ankurrsinghal commented on app/client/src/components/editorComponents/AutoResizeTextArea.tsx
> +const PADDING = 10;
Removed the const, it was not needed.

2023-01-10 08:30 UTC, ankurrsinghal commented on app/client/src/components/editorComponents/AutoResizeTextArea.tsx
> +  box-sizing: border-box;
It's really important for this feature to work, so added just in case, else we are picking up the border-box from tailwind I guess.

2023-01-10 08:31 UTC, ankurrsinghal commented on app/client/src/components/editorComponents/AutoResizeTextArea.tsx
> +  function assignRef(element: HTMLTextAreaElement) {
Refactored this whole dual ref thing in a utility hook.

2023-01-10 08:31 UTC, ankurrsinghal commented on app/client/src/widgets/InputWidgetV2/widget/index.tsx
> -    const minInputSingleLineHeight =
👍🏻

2023-01-10 08:33 UTC, ankurrsinghal commented
/ok-to-test sha=545906e

2023-01-10 10:28 UTC, riodeuno commented on app/client/src/utils/UseComposeRef.ts
> +const useComposedRef = <T extends HTMLElement>(
@ankurrsinghal Please add a comment here explaining what this does. Better yet, if you could add comments to all the relevant lines.

2023-01-11 09:42 UTC, ankurrsinghal commented
/ok-to-test sha=a3df171

2023-01-11 09:43 UTC, ankurrsinghal commented on app/client/src/utils/UseComposeRef.ts
> +const useComposedRef = <T extends HTMLElement>(
Done, added more comments wherever useful.

2023-01-11 09:54 UTC, riodeuno approved these changes

2023-01-12 05:03 UTC, dilippitchika approved these changes

2023-01-12 06:50 UTC, riodeuno commented
@ankurrsinghal Based on some of discussions. Let's do the following:
1. Let's not enable auto height by default for any of the input widgets
2. Let's enable auto height when users select multi-line in the input widget, by using the updateHook.

2023-01-12 08:11 UTC, riodeuno requested changes
@ankurrsinghal Based on some of discussions. Let's do the following:

- Let's not enable auto height by default for any of the input widgets
- Let's enable auto height when users select multi-line in the input widget, by using the updateHook.

2023-01-12 09:46 UTC, ankurrsinghal commented
> @ankurrsinghal Based on some of discussions. Let's do the following:
> 
> 1. Let's not enable auto height by default for any of the input widgets
> 2. Let's enable auto height when users select multi-line in the input widget, by using the updateHook.

Made these changes, 
CC: @Sripriya93 @kamakshibhat-appsmith

2023-01-12 09:49 UTC, riodeuno approved these changes

2023-01-12 10:40 UTC, ankurrsinghal commented
/ok-to-test sha=66ad30c

2023-01-13 09:19 UTC, ankurrsinghal commented
/ok-to-test sha=d79cb2a

2023-01-13 09:21 UTC, kamakshibhat-appsmith commented
@riodeuno @ankurrsinghal

2023-01-13 09:24 UTC, kamakshibhat-appsmith commented
One case: _`We drop an Input widget, Change it to multi-line text(Height changes to auto height). Now I changed the datatype back to Single-line`_
Should the height change to fixed again here in this case , or we will preserve the value from Multi-line text?
@riodeuno @ankurrsinghal

2023-01-13 12:14 UTC, kamakshibhat-appsmith commented
Case : 
1. DnD an Input widget

2023-01-13 12:16 UTC, kamakshibhat-appsmith commented
1. DnD an Input widget
2. Change the Height to Auto height
3. Now change the Datatype to Multi-line text

Should we change the default height to Auto-height , or should we preserve the previous change ?
@ankurrsinghal @riodeuno

2023-01-13 16:53 UTC, ankurrsinghal commented
/ok-to-test sha=1b29848

2023-01-16 08:18 UTC, kamakshibhat-appsmith commented
@riodeuno Gotcha !!. That was the concern 
@ankurrsinghal Pls make the necessary changes

2023-01-16 09:36 UTC, kamakshibhat-appsmith commented
@ankurrsinghal @riodeuno Pls check these observations  with Auto height with limits:
1. When we change the height to Autoheight with limits for Multi-line , should we change the min-height from 4 rows to the actual min height (4 rows doesn't make sense here)
2. When we change the min height to say 10 rows, should the text area also increase ?(Currently I don't see the use of min-height)
[LOOM](https://www.loom.com/share/347251d654ea40c9a5041b5f830a4ea3)

2023-01-16 11:16 UTC, ankurrsinghal commented
/ok-to-test sha=b717add

2023-01-17 07:08 UTC, riodeuno approved these changes

2023-01-17 11:24 UTC, Parthvi12 commented
/ok-to-test sha=d2dec65

2023-01-17 13:15 UTC, riodeuno approved these changes

2023-01-17 13:16 UTC, merged