Multi Pane IDE
appsmithorg/appsmith pull request #19261
Opened 2022-12-28 04:03 UTC by hetunandu

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.

## Description

> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change
> Links to Notion, Figma or any other documents that might be relevant to the PR

> Add a TL;DR when description is extra long (helps content team)

Fixes # (issue)
> if no issue exists, please create an issue and ask the maintainers about this first

Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.
> Delete anything that is not important

- Manual
- Jest
- Cypress

### Test Plan
> Add Testsmith test cases links that relate to this PR

### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)

## Checklist:
### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2022-12-30 07:27 UTC, hetunandu commented
/ok-to-test sha=50900e5

2023-01-04 18:42 UTC, rahulramesha requested changes
It seems to not clear previous draw while dragging, Please check it out.

https://user-images.githubusercontent.com/71900764/210626572-604719e3-caa2-4f2e-9c09-3cff51b302ca.mp4

2023-01-04 18:42 UTC, rahulramesha commented on app/client/src/constants/CanvasEditorConstants.tsx
> +  // MEDIUM = "MEDIUM", // 13 - 15 inch
can we just remove it, if it isn't used anymore

2023-01-04 18:42 UTC, rahulramesha commented on app/client/src/pages/common/CanvasArenas/StickyCanvasArena.tsx
> +        entry.intersectionRect.width / canvasScale + "px";
@marks0351 is this accurate, since we are multiplying by `canvasScale` in the `rescaleSliderCanvas` method

2023-01-06 12:11 UTC, hetunandu commented
/ok-to-test

2023-01-06 14:21 UTC, rahulramesha approved these changes

2023-01-07 05:06 UTC, hetunandu commented
/ok-to-test

2023-01-09 05:24 UTC, merged

2023-01-09 08:58 UTC, shwetha-ramesh commented
Tested this DP. All the other features are working as expected. 
1. Checked for other users if changes are reflected.
2. Checking widget d&d on all canvas size. > Widgets in 'Dekstop' size appears zoomed out (Fonts, widgets appear smaller) when compared to the rest of the canvas size 
4. Widget shadow tail is seen when widgets are moved on canvas
5. UI on datasource and query pages have misalignments 
![image](https://user-images.githubusercontent.com/92293815/211255779-6f570966-29d1-4c7d-ab38-5ac199cc2d66.png)
![image](https://user-images.githubusercontent.com/92293815/211255922-fd924b13-7f39-4688-b112-e03f719a8f6e.png)
![image](https://user-images.githubusercontent.com/92293815/211256142-48a2e090-bc72-44d3-9436-ac894048b84d.png)
![image](https://user-images.githubusercontent.com/92293815/211270567-130129af-4b1e-455f-ac1b-20f8c0ce60aa.png)
![image](https://user-images.githubusercontent.com/92293815/211270706-b294aa99-dcae-4226-825e-7d3eea3df3e2.png)
6. Since these icons are not clickable, its confusing for users
![image](https://user-images.githubusercontent.com/92293815/211260414-ffa7d425-019d-493c-9486-6d41a3dacc8b.png)
7. When the first pane size is increased, the canvas is lost completely. 
https://loom.com/share/4033fe60e3054a189bb8f5282c6aee88