fix git sync related bugs
appsmithorg/appsmith pull request #19352
Opened 2022-12-30 10:10 UTC by sumitsum

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.

## Description

> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change
> Links to Notion, Figma or any other documents that might be relevant to the PR

> Add a TL;DR when description is extra long (helps content team)

Fixes # (issue)
> if no issue exists, please create an issue and ask the maintainers about this first

Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.
> Delete anything that is not important

- Manual
- Jest
- Cypress

### Test Plan
> Add Testsmith test cases links that relate to this PR

### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)

## Checklist:
### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2023-01-03 05:23 UTC, AnaghHegde requested changes
All the changes done to ImportExportServiceV2 needs to copied to ImportExportService. The export and import by file is still using the same service. I am afraid we don't have any other way till we finish this up. Apologies for the inconvenience.

2023-01-03 05:23 UTC, AnaghHegde commented on app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/FileUtilsImpl.java
> +        applicationGitReference.setJsLibraries(jsLibrariesMap);
Can we use the existing readFile method to get this information?

2023-01-03 05:23 UTC, AnaghHegde commented on app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/FileUtilsImpl.java
> +            // pages, actions and actionCollections from the JSON files
Could you please help me understand this comment? Why do we need to loop through all the resources?

2023-01-03 06:46 UTC, sumitsum commented on app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/FileUtilsImpl.java
> +            // pages, actions and actionCollections from the JSON files
@AnaghHegde sorry, this comment got copied over from another place. This comment would not apply here. Removed it now.

2023-01-03 07:54 UTC, sumitsum commented on app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/FileUtilsImpl.java
> +        applicationGitReference.setJsLibraries(jsLibrariesMap);
Done.

2023-01-03 10:31 UTC, AnaghHegde submitted a review, later dismissed

2023-01-04 07:41 UTC, sumitsum commented
/ok-to-test sha=18ea7b2

2023-01-06 13:29 UTC, ramsaptami commented
- [ ] Commit message does not show up for a branch
https://www.loom.com/share/23b2dead86f24fc895543dec6080c38a

- [ ]

2023-01-09 10:10 UTC, AnaghHegde commented
@ramsaptami I don't see the git discard scenario covered in the test plan. Can we ensure that git discard is also handled correctly?

2023-01-09 10:41 UTC, sumitsum commented
/ok-to-test sha=eae0aa0

2023-01-09 11:02 UTC, sumitsum commented
/ok-to-test sha=58482db

2023-01-09 11:21 UTC, ramsaptami commented
@AnaghHegde Yep, will add those in. Thanks for reviewing!

2023-01-10 04:58 UTC, sumitsum commented
/ok-to-test sha=4dddfdd

2023-01-10 11:29 UTC, sidhantgoel requested changes
Looks good, 1 question, 1 change request

2023-01-10 11:29 UTC, sidhantgoel commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/dtos/GitStatusDTO.java
> +        int modifiedJSObjects;
QQ: Why we are modifying the data type?

2023-01-10 11:29 UTC, sidhantgoel commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImplV2.java
>  import com.appsmith.server.domains.ActionCollection;
You need to apply this change to ImportExportApplicationCEImpl.java as well, this file is used for git and the other one for normal import/export. Soon both will use  V2.

2023-01-10 11:43 UTC, sumitsum commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/dtos/GitStatusDTO.java
> +        int modifiedJSObjects;
@sidhantgoel the initial data type was `Long`, however IMO, we don't expect the number of changes to be so many that we actually need the `Long` data type. Please let me know if you think otherwise.

2023-01-10 11:44 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImplV2.java
>  import com.appsmith.server.domains.ActionCollection;
@sidhantgoel this change has already been done in `ImportExportApplicationCEImpl.java` - the current PR is changes specific to `Git`.

2023-01-10 11:46 UTC, sidhantgoel approved these changes

2023-01-10 11:46 UTC, abhvsn approved these changes

2023-01-10 13:51 UTC, Rhitottam commented
/perf-test

2023-01-10 13:56 UTC, merged