new key class and subsequent changes
appsmithorg/appsmith pull request #19485
Opened 2023-01-04 11:51 UTC by sondermanish

## Description

In order to account for multiple environments changes, the DatasourceContextServiceImpl.java methods needs refactoring to achieve minimal code duplicity.

- [ ] Create class to hold the key for dscontext maps.
- [ ] Refactor methods in order to have minimum duplicity.

Fixes #19451 

## Type of change
- chore

## This has been tested
- Manual
- Jest
- Cypress

## Checklist:
### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

2023-01-04 15:56 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/domains/DsContextMapKey.java
> +    Datasource datasource;
Could you please explain why we are storing the full datasource object and a basedomain type here?

2023-01-09 07:05 UTC, sondermanish commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceServiceCEImpl.java
> +    public Mono<Tuple3<Datasource, DsContextMapKey, Map<String, BaseDomain>>>
This will have EE override, where we will verify user's access on the environment, and then proceed to create dsContextMap key and environmentMap, In case of Oauth Authentication we will evaluate the dsConfiguration as well for checking refresh tokens. in next step.

2023-01-11 06:56 UTC, sondermanish commented on app/server/appsmith-server/src/main/java/com/appsmith/server/domains/DsContextMapKey.java
> +    @Override
could have used lombok.EqualsAndHashCode as well, however that makes all null equal.

2023-01-11 07:00 UTC, sondermanish commented on app/server/appsmith-server/src/main/java/com/appsmith/server/domains/ce/DsContextMapKeyCE.java
> +public class DsContextMapKeyCE {
The Classes are split in CE and EE because the Empty methods needs to be overridden in EE.

2023-01-11 09:37 UTC, sumitsum requested changes

2023-01-11 09:46 UTC, sondermanish commented on app/server/appsmith-server/src/main/java/com/appsmith/server/domains/DsContextMapKey.java
> +    public DsContextMapKey() {
resolving

2023-01-11 09:46 UTC, sondermanish commented on app/server/appsmith-server/src/main/java/com/appsmith/server/domains/DsContextMapKey.java
> +    public DsContextMapKey(String datasourceId, String environmentId) {
resolving

2023-01-11 10:03 UTC, sondermanish commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceContextServiceCEImpl.java
> +                    return getCachedDatasourceContextMono(datasource, pluginExecutor, monitor, dsContextMapKey);
Yes, thanks for pointing out.

2023-01-11 10:16 UTC, sondermanish commented on app/server/appsmith-server/src/main/java/com/appsmith/server/domains/DsContextMapKey.java
> +public class DsContextMapKey {
Agreed, Let's move forward with `DatasourceContextIdentifier` ?

2023-01-11 10:28 UTC, sondermanish commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceContextServiceCEImpl.java
>              Mono<Object> connectionMono = pluginExecutor.datasourceCreate(datasource.getDatasourceConfiguration()).cache();
In code flow, when we reach this point, `datasource` will already be evaluated, meaning that `datasourceConfiguration` will have required values as per environment.

2023-01-11 12:21 UTC, sondermanish commented on app/server/appsmith-server/src/main/java/com/appsmith/server/domains/DsContextMapKey.java
> +    public DsContextMapKey(String datasourceId, String environmentId) {
Since we are calling super over there, therefore keeping the parameterised constructor to call `super`.

2023-01-12 05:48 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/domains/DsContextMapKey.java
> +        boolean areBothEnvironmentIdSameOrNull = StringUtils.hasLength(environmentId) ?
@sondermanish I think there is a mis-understanding here. What I meant is could we import this method like`import static org.springframework.util.StringUtils.hasLength;` and just write `hasLength(xyz)`.

2023-01-12 06:56 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceContextServiceCEImpl.java
> +    Mono<Datasource> retrieveDatasourceFromDB( Datasource datasource, DatasourceContextIdentifier datasourceContextIdentifier) {
Would this method be overridden in EE to substitute values from environment into the datasource ?

2023-01-12 06:57 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceContextServiceCEImpl.java
> +        if (!datasourceContextIdentifier.isKeyNotValid()) {
Can we please change the boolean method here to `isKeyValild()`  i.e `if(....isKeyValid()) {then do something}`

2023-01-12 07:00 UTC, sondermanish commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceContextServiceCEImpl.java
> +    Mono<Datasource> retrieveDatasourceFromDB( Datasource datasource, DatasourceContextIdentifier datasourceContextIdentifier) {
@sumitsum yes, this is the point where we would fetch and evaluate the db for given environment, with the help of datasourceContextIdentifier

2023-01-12 07:00 UTC, sondermanish commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceContextServiceCEImpl.java
> +        if (!datasourceContextIdentifier.isKeyNotValid()) {
resolving as mentioned

2023-01-12 07:42 UTC, sumitsum approved these changes

2023-01-12 07:46 UTC, sondermanish commented
/ok-to-tesh sha=42d6ef8

2023-01-16 13:19 UTC, sondermanish commented
/ok-to-test sha=42d6ef8

2023-01-16 13:19 UTC, AnandShahs123 commented
@sondermanish Tested following DS
Rest API
SAAS INtegration (Airtable)
Gsheet
Postgres
Mongo
S3
Mysql

Got issue on gsheet (which is an issue related to local) {"responseMeta":{"status":500,"success":false,"error":{"code":5000,"message":"Internal server error while processing request"}}}

Rest worked fine.

2023-01-16 14:22 UTC, merged