Resize canvas on delete widget
appsmithorg/appsmith pull request #1958
Opened 2020-11-30 06:57 UTC by ofpiyush

## Description
- Recalculate canvas rows on delete

Fixes # 1919

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

TBD

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2020-12-10 06:34 UTC, ofpiyush commented
@riodeuno this is ready for review now. Arpit is working on getting codefactor sorted

2020-12-11 12:37 UTC, riodeuno requested changes

2020-12-11 12:37 UTC, riodeuno commented on app/client/src/sagas/WidgetOperationSagas.tsx
> +      resizeCanvasToLowestWidget(finalWidgets, parentId);
If this mutates, let's keep the contents here. I'm worried that another contributor might use this without knowing that this doesn't return anything.

2020-12-11 12:38 UTC, riodeuno approved these changes

2020-12-11 13:07 UTC, riodeuno submitted a review, later dismissed

2020-12-11 13:47 UTC, riodeuno approved these changes

2020-12-11 13:48 UTC, merged