Onboarding flow
appsmithorg/appsmith pull request #1960
Opened 2020-11-30 09:15 UTC by akash-codemonk

2020-12-10 08:55 UTC, hetunandu requested changes
Great work! Minor changes and refactors needed

2020-12-10 08:55 UTC, hetunandu commented on app/client/src/components/editorComponents/Onboarding/Tooltip.tsx
> +const ToolTipContent = (props: any) => {
Lets define these prop type.

2020-12-10 08:55 UTC, hetunandu commented on app/client/src/components/editorComponents/form/fields/EmbeddedDatasourcePathField.tsx
> +      const datasourceUrl = datasource.datasourceConfiguration?.url ?? "";
Changes not related to onboarding

2020-12-10 08:55 UTC, hetunandu commented on app/client/src/components/editorComponents/Onboarding/Boxed.tsx
> +import React, { ReactNode } from "react";
Nice one!

2020-12-10 08:55 UTC, hetunandu commented on app/client/src/pages/UserAuth/ThirdPartyAuth.tsx
> +        setOnboardingState(true);
Should only happen if it is a signup.

2020-12-10 08:55 UTC, hetunandu commented on app/client/src/reducers/entityReducers/actionsReducer.tsx
> +  [ReduxActionTypes.CREATE_ONBOARDING_ACTION_SUCCESS]: (
Lets use one of the old events to manipulate the state.

2020-12-10 08:55 UTC, hetunandu commented on app/client/src/reducers/uiReducers/datasourcePaneReducer.ts
> +  [ReduxActionTypes.CREATE_ONBOARDING_DBQUERY_SUCCESS]: (
Lets use one of the old events to manipulate the state.

2020-12-10 08:55 UTC, hetunandu commented on app/client/src/reducers/uiReducers/onBoardingReducer.ts
> +  currentStep: -1,
Instead of tracking and using numbers everywhere, create a onboarding steps name enum which can have number values. This way we can understand the step being referred to easily without finding the whole steps list

2020-12-10 08:55 UTC, hetunandu commented on app/client/src/reducers/uiReducers/onBoardingReducer.ts
> +  showingTooltip: -1,
Use that same enum for tooltips as well

2020-12-10 12:56 UTC, akash-codemonk commented on app/client/src/reducers/entityReducers/actionsReducer.tsx
> +  [ReduxActionTypes.CREATE_ONBOARDING_ACTION_SUCCESS]: (
Using this action type because the usual `CREATE_ACTION_SUCCESS` type is being listened to by [api](https://github.com/appsmithorg/appsmith/blob/feat/onboarding-flow/app/client/src/sagas/ApiPaneSagas.ts#L434) and [query pane sagas](https://github.com/appsmithorg/appsmith/blob/feat/onboarding-flow/app/client/src/sagas/QueryPaneSagas.ts#L207) which navigate to that action page when successful but for onboarding we have to navigate to the datasource page.

2020-12-18 13:18 UTC, hetunandu approved these changes

2020-12-18 13:18 UTC, merged