feat: APIs to Upload/Delete App navigation logo (#19164)
appsmithorg/appsmith pull request #19771
Opened 2023-01-12 19:17 UTC by NilanshBansal

## Description

Implements backend APIs for Uploading and Deleting Navigation Logo

Fixes #19164

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Manual
- Postman

## Checklist:
### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2023-01-12 19:32 UTC, NilanshBansal commented
/ok-to-test sha=ad51dee533fde85c2447b8682615bdcebb8ed665

2023-01-16 06:08 UTC, nidhi-nair reviewed
Hey we seem to be missing test cases, can we add a few here?

2023-01-16 06:08 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/ApplicationControllerCE.java
> +    @PostMapping(value = "/{defaultApplicationId}/logo", consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
From my understanding, is this property not dependent on git branches?

2023-01-16 06:17 UTC, NilanshBansal commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationServiceCEImpl.java
> +import com.appsmith.server.domains.*;
Sure @nidhi-nair

2023-01-16 06:17 UTC, NilanshBansal commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationServiceCEImpl.java
> +import com.appsmith.server.services.*;
Sure @nidhi-nair

2023-01-18 07:32 UTC, NilanshBansal commented on app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/ApplicationControllerCE.java
> +    @PostMapping(value = "/{defaultApplicationId}/logo", consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
@nidhi-nair Thanks for pointing out, i will make the necessary changes for git integration

2023-01-19 04:58 UTC, sidhantgoel commented on app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/ApplicationControllerCE.java
> +        return service.deleteAppNavigationLogo(defaultApplicationId)
For which branch this delete happens? do we delete from all branches?

2023-01-19 04:58 UTC, sidhantgoel commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationServiceCEImpl.java
> +        return repository.findById(applicationId)
should we consider branch when deleting logo?

2023-01-19 05:01 UTC, NilanshBansal commented on app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/ApplicationControllerCE.java
> +        return service.deleteAppNavigationLogo(defaultApplicationId)
I have not added git integration yet in delete branch. Right now the saveNavigationLogo function is failing for git integration, once that passes will add the same code here

2023-01-19 05:02 UTC, NilanshBansal commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationServiceCEImpl.java
> +        return repository.findById(applicationId)
Yes, will add it once logo updation works fine

2023-01-19 05:47 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationServiceCEImpl.java
> +        return this.findByBranchNameAndDefaultApplicationId(branchName, applicationId, applicationPermission.getEditPermission())
Why do we want to have a branch specific logo? I don't understand this. IMO, it should be independent of git branch. Once the logo is uploaded then it should be same for all the case.

If we are considering the logo at branch level, do we plan to save this information in git repository when the user makes commit and push?

2023-01-19 08:50 UTC, NilanshBansal commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationServiceCEImpl.java
> +        return this.findByBranchNameAndDefaultApplicationId(branchName, applicationId, applicationPermission.getEditPermission())
Yes @AnaghHegde we need to have the ability to have a branch-specific logo here since the logo config is editable and it comes packaged as a part of editing navigation settings. Since we allow git branch-specific updates for other nav features, we should not miss this part. 
Anyways, this is again an optional feature, but we should have the capability.
My [last commit](https://github.com/appsmithorg/appsmith/pull/19771/commits/7c458fa030ec350d67c3ca52a36fe7159fd6d5aa) fixes the git branch feature for both update/delete nav logo as well.

CC: @dilippitchika

2023-01-19 09:05 UTC, mohanarpit commented on app/server/appsmith-server/src/test/java/com/appsmith/server/helpers/GitUtilsTest.java
> -        assertThat(GitUtils.convertSshUrlToBrowserSupportedUrl("git@127.0.0.1:test/newRepo.git"))
@NilanshBansal Can you please pull the latest release into your branch? We seem to be removing a test case which is required for Git.

2023-01-19 09:06 UTC, mohanarpit commented on app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/GitUtils.java
> -                .replaceFirst("(\\.[a-zA-Z0-9]*):", "$1/")
This is a recent fix by @AnaghHegde. Please pull the latest code on your branch to ensure that we don't regress on such bug fixes.

2023-01-19 09:21 UTC, NilanshBansal commented on app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/GitUtils.java
> -                .replaceFirst("(\\.[a-zA-Z0-9]*):", "$1/")
Sure @mohanarpit

2023-01-19 09:21 UTC, NilanshBansal commented on app/server/appsmith-server/src/test/java/com/appsmith/server/helpers/GitUtilsTest.java
> -        assertThat(GitUtils.convertSshUrlToBrowserSupportedUrl("git@127.0.0.1:test/newRepo.git"))
Sure @mohanarpit

2023-01-19 09:28 UTC, AnaghHegde reviewed
Minor comments rest looks good to me.

2023-01-19 09:28 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationServiceCEImpl.java
> +        return this.findByBranchNameAndDefaultApplicationId(branchName, applicationId, applicationPermission.getEditPermission())
I hope we have verified all the git scenarios and please add a test case for the same behaviour. You can refer the ImportExportService tests.

2023-01-19 09:28 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationServiceCEImpl.java
> +        return this.findByBranchNameAndDefaultApplicationId(branchName, applicationId, applicationPermission.getEditPermission())
If we are doing the update can you use the `findBranchedApplicationId` of the same class and build the update application object and then call the `update` of mongo?

2023-01-19 11:12 UTC, NilanshBansal commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationServiceCEImpl.java
> +        return this.findByBranchNameAndDefaultApplicationId(branchName, applicationId, applicationPermission.getEditPermission())
Sure @AnaghHegde, the test-cases for all the scenarios are in-progress, will push them as completed.

2023-01-19 11:48 UTC, NilanshBansal commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationServiceCEImpl.java
> +        return this.findByBranchNameAndDefaultApplicationId(branchName, applicationId, applicationPermission.getEditPermission())
Why is that required here @AnaghHegde ? The update function needs a `defaultApplicationId` which is being passed. Can you pls clarify.

2023-01-20 04:13 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationServiceCEImpl.java
> +        return this.findByBranchNameAndDefaultApplicationId(branchName, applicationId, applicationPermission.getEditPermission())
Since we need only the application id, instead of fetching the entire Application object from the db, we can fetch only the id. `findBranchedApplicationId ` method returns only the id. The reason for using this is that it reduces the network transfer rate. Does that make sense?

2023-01-20 12:21 UTC, NilanshBansal commented
/ok-to-test sha=511e5f333a5490daab64c620d5a3f1e3bfc2a46f

2023-01-20 12:28 UTC, NilanshBansal commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationServiceCEImpl.java
> +        return this.findByBranchNameAndDefaultApplicationId(branchName, applicationId, applicationPermission.getEditPermission())
The `unpublishedNavigationSetting` also has other fields, which I need to keep as it is and only update the `logoAssetId` field.
i.e. `application.unpublishedNavigationSetting.logoAssetId`  = \<some value>

Updating using the `findBranchedApplicationId` and calling mongo update overwrites the other fields as well with the default values. 
But I get your point @AnaghHegde, will take note of this going forward.

2023-01-20 13:34 UTC, AnaghHegde requested changes
Minor request. I don't see the test cases for the git connect apps. Can we add the test cases for git connected apps as well? You can refer the `GitServiceTest` class for the same.

2023-01-20 13:34 UTC, AnaghHegde commented on app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ImportExportApplicationServiceTests.java
> +                })
Can we assert for other properties as well? Or is this sufficient?

2023-01-20 13:58 UTC, NilanshBansal commented on app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ImportExportApplicationServiceTests.java
> +                })
This is sufficient @AnaghHegde. If it works for one, it works for all.

2023-01-23 05:05 UTC, NilanshBansal commented
> Minor request. I don't see the test cases for the git connect apps. Can we add the test cases for git connected apps as well? You can refer the `GitServiceTest` class for the same.

Added test cases for git connected apps. @AnaghHegde can you pls re-review

2023-01-23 05:06 UTC, NilanshBansal commented
/ok-to-test sha=738512428a46a014807cb4066e700ea34b9585a0

2023-01-23 05:37 UTC, AnaghHegde requested changes
Minor nit. Rest looks good to me.

2023-01-23 05:37 UTC, AnaghHegde commented on app/server/appsmith-server/src/test/java/com/appsmith/server/services/GitServiceTest.java
> +        GitBranchDTO createGitBranchDTO = new GitBranchDTO();
Minor nit - The name of the test case seems odd. Please refer this - https://dzone.com/articles/7-popular-unit-test-naming and update the method name.

2023-01-23 06:38 UTC, NilanshBansal commented
/ok-to-test sha=8da859184e1ca1a66110b6abc4a7aedf29450109

2023-01-23 07:14 UTC, AnaghHegde approved these changes

2023-01-23 07:39 UTC, merged