Fix: FilePicker widget not setting loading state to true on calling action
appsmithorg/appsmith pull request #1985
Opened 2020-12-01 11:02 UTC by jsartisan

## Description
Filepicker widget was not setting isLoading to true on calling action whenever files were selected. 
Fixes #949 

## Type of change
- Bugfix

## How Has This Been Tested?
- Manually tested
- Added cypress tests

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2020-12-01 17:48 UTC, hetunandu requested changes

2020-12-01 17:48 UTC, hetunandu commented on app/client/src/widgets/FilepickerWidget.tsx
> +      this.props.updateWidgetMetaProperty("isLoading", true);
We should use the state here instead of WidgetMetaProperty

2020-12-01 17:48 UTC, hetunandu commented on app/client/src/widgets/FilepickerWidget.tsx
> +      this.props.updateWidgetMetaProperty("isLoading", true);
You can check Button Widget for implementation details

2020-12-02 06:15 UTC, jsartisan commented
@hetunandu added the isLoading in state.

2020-12-02 17:22 UTC, hetunandu approved these changes

2020-12-03 05:32 UTC, merged