fix: renamed rts port env
appsmithorg/appsmith pull request #20121
Opened 2023-01-27 03:36 UTC by sum35h

Renamed env PORT to APPSMITH_RTS_PORT for the rts server.

2023-01-27 10:25 UTC, sum35h commented
/build-deploy-preview

2023-01-30 14:17 UTC, sum35h commented
/build-deploy-preview

2023-01-31 05:17 UTC, sharat87 reviewed
Code formatting fix, otherwise looks good.

2023-01-31 05:17 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/CommonConfig.java
> +}
Indentation.

```suggestion
    public String getRtsBaseDomain() {
        return "http://127.0.0.1:" + rtsPort;
    }
```

2023-02-06 05:24 UTC, sharat87 requested changes

2023-02-06 05:24 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/CommonConfig.java
> +    public String getRtsBaseDomain() {
Sorry, one more tiny change. Can we change this to `rtsBaseUrl` please? It doesn't contain any domain, it's a base URL, and this will cause confusion later. 🙂

2023-02-08 03:25 UTC, sum35h commented
/ok-to-test sha=a822e07

2023-02-14 05:35 UTC, sharat87 requested changes

2023-02-14 05:35 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/CommonConfig.java
> +    private String rtsBaseDomain;
Is this variable used anywhere? Can we remove it if it's unused?

2023-02-15 01:36 UTC, merged

2023-02-16 14:48 UTC, mohamedgomran commented
Hello @sharat87 👋  When this can be released in docker image appsmith-ce?

2023-02-20 10:14 UTC, sum35h commented
@mohamedgomran  Unfortunately this fix will only be out on Release v1.9.9