fix: Return system theme when application theme not found
appsmithorg/appsmith pull request #20170
Opened 2023-01-27 12:51 UTC by nayan-rafiq

## Description
This PR returns the default theme if application theme is not available due to data corruption in DB.

Fixes #20169 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manual
- Jest

### Test Plan
> Add Testsmith test cases links that relate to this PR

### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)

## Checklist:
### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2023-01-27 12:55 UTC, nidhi-nair requested changes
Tiny comment

2023-01-27 12:55 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ThemeServiceCEImpl.java
> +                        return repository.findById(themeId, Optional.empty())
Should we use the deprecated lethod instead? Sidhant intends to revert the deprecation to favour code readability.

2023-01-27 13:01 UTC, nayan-rafiq commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ThemeServiceCEImpl.java
> +                        return repository.findById(themeId, Optional.empty())
@nidhi-nair I've updated. Would you please have a look?

2023-01-30 04:00 UTC, nidhi-nair approved these changes
Lgtm

2023-01-30 06:21 UTC, nayan-rafiq commented
/ok-to-test sha=d168dde9cfe3ca1d78ccd5e5576f3c0dd3bd214f

2023-01-30 09:55 UTC, nayan-rafiq commented
/ok-to-test sha=04a6eb7398375f673754cc36f23f96eaa54154e6

2023-01-30 13:56 UTC, merged