Add xml2json and json2xml functions
appsmithorg/appsmith pull request #2022
Opened 2020-12-03 17:43 UTC by hetunandu

## Description
Adds two new functions
xml2json and json2xml that will help in conversions between xml and json data strings
Uses this library: https://github.com/nashwaan/xml-js

Implements #2015 

## Type of change
- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

## How Has This Been Tested?
TODO

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2020-12-03 17:47 UTC, Nikhil-Nandagopal commented on app/client/src/constants/defs/xml2json.json
> +    "!doc": "converts xml string to json string",
please add this to docs :)

2020-12-03 17:47 UTC, Nikhil-Nandagopal commented on app/client/src/constants/defs/xml2json.json
> +    "!doc": "converts xml string to json string",
especially the function signature

2020-12-07 16:18 UTC, hetunandu commented
Docs PR opened here appsmithorg/appsmith-docs#69

2020-12-09 07:18 UTC, Nikhil-Nandagopal commented on app/client/src/constants/defs/xml2json.json
> +    "!doc": "converts xml string to json string",
@hetunandu this should convert it to a js object not a string

2020-12-09 07:20 UTC, Nikhil-Nandagopal commented on app/client/src/constants/defs/xml2json.json
> +    "!type": "fn(xml: string, options: object) -> string"
options should be an optional arg and it should function without it right?

2020-12-09 07:20 UTC, Nikhil-Nandagopal commented on app/client/src/constants/defs/xml2json.json
> +    "!type": "fn(json: string, options: object) -> string"
same here options should be optional

2020-12-10 07:48 UTC, Nikhil-Nandagopal commented on app/client/src/constants/defs/xml2json.json
> +    "!type": "fn(xml: string, options?: object) -> object"
@hetunandu I tried this out and I dislike the output of this library. It feels very complicated and not usable.
Can we use this instead
https://github.com/NaturalIntelligence/fast-xml-parser
This is a cleaner output

2020-12-10 07:48 UTC, Nikhil-Nandagopal requested changes
Left a comment on the lib we're using

2020-12-15 08:44 UTC, Nikhil-Nandagopal approved these changes

2020-12-15 08:46 UTC, merged