Fix: run fat container docker inside perf tests and update setup-perf-test workflow to use localhost for accessing dev environment
appsmithorg/appsmith pull request #20280
Opened 2023-02-01 07:43 UTC by Rhitottam

2023-02-01 08:03 UTC, Aishwarya-U-R commented on .github/workflows/perf-test.yml
> +          cd cicontainerlocal
cicontainerlocal - also should be created.
`mkdir -p cicontainerlocal/stacks/configuration/` - reference from integrations yml file

2023-02-01 09:58 UTC, kaustavy2k approved these changes

2023-02-01 11:32 UTC, Aishwarya-U-R commented on .github/workflows/perf-test.yml
> +          flags: --recursive
Downloading S3 image is not required for perf tests

2023-02-04 15:53 UTC, SatishGandham commented on .github/workflows/perf-test.yml
> +          ./cypress/setup-test-ci.sh
Lets maintain our own setup script.

2023-02-04 15:54 UTC, SatishGandham requested changes

2023-02-04 15:54 UTC, SatishGandham commented on app/client/perf/setup-perf-test.sh
> +sleep 30
Can we remove this sleep?

2023-02-04 15:54 UTC, SatishGandham commented on .github/workflows/perf-test.yml
> +      # - name: Exit if Server hasnt started
Is this no longer required?

2023-02-07 08:36 UTC, Rhitottam commented
/ok-to-test

2023-02-07 10:26 UTC, SatishGandham approved these changes

2023-02-07 10:26 UTC, merged