check boolean env values against 'true' string
appsmithorg/appsmith pull request #2055
Opened 2020-12-07 10:45 UTC by rishabhsaxena

## Description
Check boolean env variables against 'true' string

Fixes # (issue)
#2036

## Type of change
Convention with respect to boolean env variables

## How Has This Been Tested?

### setting value as falsy
- set `APPSMITH_MAIL_ENABLED` as any other string apart from 'true' or omit the variable from the env file
- restart nginx
  - `cd app/client`
  - `./start-https.sh`
- Forgot password page should show email not configured warning

### setting value as truthy
- set `APPSMITH_MAIL_ENABLED` as  'true'
- restart nginx
  - `cd app/client`
  - `./start-https.sh`
- Forgot password page should `not` show email not configured warning

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

2020-12-07 13:56 UTC, hetunandu requested changes
Refactor

2020-12-07 13:56 UTC, hetunandu commented on app/client/public/index.html
> +      mailEnabled: MAIL_ENABLED && MAIL_ENABLED === "true",
You should implement this logic in `parseConfig` itself and make sure other variables having the same check is also handled this way

2020-12-07 14:44 UTC, rishabhsaxena commented on app/client/public/index.html
> +      mailEnabled: MAIL_ENABLED && MAIL_ENABLED === "true",
Sure, we can have a check for supporting `false` strings as falsy within `parseConfig`

2020-12-07 15:03 UTC, rishabhsaxena commented on app/client/public/index.html
> +      mailEnabled: MAIL_ENABLED && MAIL_ENABLED === "true",
Another way I thought was returning `bool`  directly from `parseConfig` but since in general env vars are strings thought this might be more consistent. Let me know if that seems preferrable

@hetunandu

2020-12-07 15:10 UTC, rishabhsaxena commented on app/client/public/index.html
> +      mailEnabled: MAIL_ENABLED && MAIL_ENABLED === "true",
One possible issue might be with the config:
`disableTelemetry: DISABLE_TELEMETRY === "" || DISABLE_TELEMETRY === "true"`

In case we set the value as 'false', the flag would be set as true

2020-12-07 16:22 UTC, hetunandu commented on app/client/public/index.html
> +      mailEnabled: MAIL_ENABLED && MAIL_ENABLED === "true",
- If string true or false is passed in, we should parse it to `true` or `false`
- If nothing is passed in, we should parse it to `false`

2020-12-07 16:30 UTC, rishabhsaxena commented on app/client/public/index.html
> +      mailEnabled: MAIL_ENABLED && MAIL_ENABLED === "true",
```
    const parseConfig = (config) => {
      if (config.indexOf("__") === 0 || config.indexOf("$") === 0)
        return "";

      const result = config.trim();
      if (result.toLowerCase() === "false" || result === "") {
        return false;
      } else if (result.toLowerCase() === "true") {
        return true;
      }

      return result;
    }
```
something like this?

2020-12-07 16:40 UTC, rishabhsaxena commented on app/client/public/index.html
> +      mailEnabled: MAIL_ENABLED && MAIL_ENABLED === "true",
pushed these changes

2020-12-08 09:07 UTC, hetunandu commented on app/client/public/index.html
> +      disableTelemetry: DISABLE_TELEMETRY === "" || DISABLE_TELEMETRY,
This will return true if `DISABLE_TELEMETRY` is a `"false"` string right? Can you test this out

2020-12-08 09:15 UTC, rishabhsaxena commented on app/client/public/index.html
> +      disableTelemetry: DISABLE_TELEMETRY === "" || DISABLE_TELEMETRY,
actually here,
`const DISABLE_TELEMETRY = parseConfig("__APPSMITH_DISABLE_TELEMETRY__");`

so for `"false"`:
`DISABLE_TELEMETRY` would be `false`
`disableTelemetry` would also be `false`

for cases when the env val does not exist:
`DISABLE_TELEMETRY` would be `false`
`disableTelemetry` would also be `true`

2020-12-08 09:24 UTC, hetunandu commented on app/client/public/index.html
> +      disableTelemetry: DISABLE_TELEMETRY === "" || DISABLE_TELEMETRY,
I missed that you were creating this as a different variable on the top. Seems to be fine then.

2020-12-08 09:24 UTC, hetunandu approved these changes

2020-12-09 05:52 UTC, merged