Fixed menu items exceeded canvas issue.
appsmithorg/appsmith pull request #20579
Opened 2023-02-12 19:08 UTC by MuhammadAakash

## Description
Fixed the issue of when we added many menu items. So, they exceed the canvas. So, i fixed them by adding scroll bar on it and added the height for it so, it will not exceed the canvas.

Fixes #11684 

## Media
https://www.loom.com/share/5a1f9b4b2f294ad8a22b9de4b89f112e

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
Create a menu widget and add at least 20 to 30 items to it. So, previously it exceed the canvas length but now it's working perfectly fine.  

## Checklist:
### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2023-02-13 09:12 UTC, somangshu commented
/build-deploy-preview

2023-02-14 06:24 UTC, somangshu requested changes

2023-02-14 06:24 UTC, somangshu commented on app/client/src/widgets/MenuButtonWidget/component/index.tsx
> +    height: 384px;
I think it should rather be max-height. Checkout the behaviour on the popup, it has empty space for lesser number of items. cc @jsartisan what do you say?

![Screenshot 2023-02-14 at 11 53 18 AM](https://user-images.githubusercontent.com/11089579/218656188-29af8965-13e1-4acc-b7d4-59ce1e93ca90.png)

2023-02-14 07:52 UTC, MuhammadAakash commented on app/client/src/widgets/MenuButtonWidget/component/index.tsx
> +    height: 384px;
exactly, you are right.
I will add the commit with the necessary changes.

2023-02-15 05:01 UTC, somangshu commented
/build-deploy-preview

2023-02-15 07:11 UTC, somangshu approved these changes
LGMT, the change has fixed the issue

@jsartisan kindly review and verify

2023-02-15 12:17 UTC, jsartisan commented
/ok-to-test sha=2fafd78

2023-02-16 04:13 UTC, jsartisan approved these changes

2023-02-16 10:27 UTC, jsartisan commented
@MuhammadAakash can you take pull of latest release on your branch?

2023-02-16 10:50 UTC, MuhammadAakash commented
@jsartisan 
Sure, I will do this tonight.

2023-02-16 16:45 UTC, MuhammadAakash commented
@jsartisan 
After pulling the release branch into my current branch, I got that no files were changed.

2023-02-17 07:13 UTC, jsartisan commented
@MuhammadAakash You are taking a pull of release from your forked repo. You have to take a pull from appsmith's release branch. Basically your repo's release don't have the latest release code. A sync is required.

2023-02-18 17:26 UTC, MuhammadAakash commented
@jsartisan 
Sorry for being late. I have merged the release branch with my current branch. Please check

2023-02-20 05:34 UTC, somangshu commented
/ok-to-test sha=c019d52

2023-02-26 10:50 UTC, MuhammadAakash commented
@somangshu 
Are there any other changes which need to be completed?

2023-02-27 07:25 UTC, jsartisan commented
/ok-to-test sha=c019d52

2023-02-27 11:51 UTC, merged