Fix: The search in the multi select is not showing
appsmithorg/appsmith pull request #2057
Opened 2020-12-07 11:41 UTC by jsartisan

## Description
For the multi-select widget, the ghost input width was just 1px and was not visible at all. Increased the width for it to make it visible.

Fixes #2051 

## Type of change
- Bugfix

## How Has This Been Tested?
- Manually tested

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2020-12-10 05:23 UTC, hetunandu requested changes
Minor changes

2020-12-10 05:23 UTC, hetunandu commented on app/client/src/components/designSystems/blueprint/DropdownComponent.tsx
> +        width: 60px;
This values should be derived from the width of the widget

2020-12-10 06:36 UTC, jsartisan commented on app/client/src/components/designSystems/blueprint/DropdownComponent.tsx
> +        width: 60px;
This is not the widget of the widget. This is actually the widget of the ghost text input inside the select box.

2020-12-10 06:45 UTC, hetunandu commented on app/client/src/components/designSystems/blueprint/DropdownComponent.tsx
> +        width: 60px;
Limiting this width is causing it to only show a bit of the input text and the rest is going out of the screen. For this reason it should take account of the available width and then set this width.

https://www.loom.com/share/3e648dfe88fd496c8ceb196d9014d160

2020-12-11 04:51 UTC, jsartisan commented
@hetunandu Updated styling according to feedback.

2020-12-14 13:33 UTC, hetunandu approved these changes

2020-12-15 05:04 UTC, merged