fix: User gets an error even when table widget is added from the API …
appsmithorg/appsmith pull request #20593
Opened 2023-02-13 11:25 UTC by Druthi

…page successfully

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.

## Description

> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change
> Links to Notion, Figma or any other documents that might be relevant to the PR

> Add a TL;DR when description is extra long (helps content team)

Fixes # (issue)
> if no issue exists, please create an issue and ask the maintainers about this first

Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update

## How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.
> Delete anything that is not important

- Manual
- Jest
- Cypress

### Test Plan
> Add Testsmith test cases links that relate to this PR

### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)

## Checklist:
### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2023-02-13 11:47 UTC, Druthi commented
/ok-to-test sha=14d9f96

2023-02-14 06:46 UTC, ApekshaBhosale requested changes

2023-02-14 06:46 UTC, ApekshaBhosale commented on app/client/src/sagas/WidgetAdditionSagas.ts
> +  if (params.dynamicBindingPathList) {
what is the value of dynamicBindingPathList in params? can you give example, please?

2023-02-14 06:46 UTC, ApekshaBhosale commented on app/client/src/sagas/WidgetAdditionSagas.ts
> +    const copy = [...dynamicBindingPathList, ...params.dynamicBindingPathList];
please use a different variable name than `copy`

2023-02-14 10:07 UTC, ApekshaBhosale approved these changes

2023-02-16 05:13 UTC, Druthi commented
/ok-to-test sha=f41fa03

2023-02-16 05:18 UTC, Druthi commented
/ok-to-test sha=47c72af

2023-02-16 07:21 UTC, ramsaptami commented
LGTM @Druthi

2023-02-20 06:09 UTC, Druthi commented
/ok-to-test sha=a21f27b

2023-02-20 09:03 UTC, ApekshaBhosale approved these changes

2023-02-20 12:03 UTC, merged