ci: add workflows to cleanup merged deploy-previews
appsmithorg/appsmith pull request #20627
Opened 2023-02-15 05:19 UTC by pratapaprasanna

2023-02-16 02:26 UTC, sharat87 requested changes
Few refactorings and suggestions.

2023-02-16 02:26 UTC, sharat87 commented on scripts/cleanup_dp.sh
> +source_profile = default" > ~/.aws/config
Same as above, can we not overwrite global config files please?

For `role_arn`, we can provide `--role-arn "$AWS_ROLE_ARN"`. From https://awscli.amazonaws.com/v2/documentation/api/latest/reference/eks/update-kubeconfig.html.

So this can just be:

```suggestion
export AWS_REGION=ap-south-1
export AWS_DEFAULT_OUTPUT=json
```

2023-02-16 02:26 UTC, sharat87 commented on scripts/cleanup_dp.sh
> +aws eks update-kubeconfig --region $region --name $cluster_name --profile eksci
Now this should work without depending on anything in the `~/.aws` folder.

```suggestion
aws eks update-kubeconfig --name "$cluster_name" --role-arn "$AWS_ROLE_ARN"
```

2023-02-16 02:26 UTC, sharat87 commented on scripts/cleanup_dp.sh
> +sts_output=$(aws sts assume-role --role-arn env.AWS_ROLE_ARN --role-session-name ekscisession)
Did you mean `$AWS_ROLE_ARN` here?

```suggestion
sts_output=$(aws sts assume-role --role-arn "$AWS_ROLE_ARN" --role-session-name dp-cleanup-script)
```

2023-02-16 02:26 UTC, sharat87 commented on scripts/cleanup_dp.sh
> +export AWS_SESSION_TOKEN=$(echo $sts_output | jq -r '.Credentials''.SessionToken');
Minor refactoring.

```suggestion
export AWS_ACCESS_KEY_ID="$(echo "$sts_output" | jq -r '.Credentials.AccessKeyId')"
export AWS_SECRET_ACCESS_KEY="$(echo "$sts_output" | jq -r '.Credentials.SecretAccessKey')"
export AWS_SESSION_TOKEN="$(echo "$sts_output" | jq -r '.Credentials.SessionToken')"
```

2023-02-16 02:26 UTC, sharat87 commented on scripts/cleanup_dp.sh
> +deployed_charts=$(helm ls -A | grep ce | awk '{print $2}')
Simpler, if you're okay :)

```suggestion
deployed_charts="$(helm ls -A | awk '/ce/ {print $2}')"
```

2023-02-16 02:26 UTC, sharat87 commented on scripts/cleanup_dp.sh
> +      echo "helm uninstall $i -n $i"
Are we not _actually_ uninstalling? 🤔

```suggestion
      helm uninstall "$i" -n "$i"
```

2023-02-16 02:26 UTC, sharat87 commented on scripts/cleanup_dp.sh
> +    if [ $pr_state == "MERGED" ]
In bash, always prefer double-brackets for conditions:

```suggestion
    if [[ $pr_state == "MERGED" ]]
```

2023-02-16 02:26 UTC, sharat87 commented on .github/workflows/cleanup-dp.yml
> +          chmod 700 get_helm.sh; ./get_helm.sh
It's a little hard to read when some lines have multiple commands, and some don't. If it's hard to read, it'll be hard to debug next year. 🙂

```suggestion
          sudo apt update -q
          sudo apt install -y curl unzip less jq 
          curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.23.6/bin/linux/amd64/kubectl
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh
```

2023-02-16 02:26 UTC, sharat87 commented on .github/workflows/cleanup-dp.yml
> +        run: /bin/bash ./runbooks/tasks/upgrade_helm_chart.sh
Is this the right script? Shouldn't we be running the `cleanup_dp.sh` may be? 🤔

2023-02-23 07:46 UTC, pratapaprasanna commented on scripts/cleanup_dp.sh
> +      echo "helm uninstall $i -n $i"
Just testing the script before finalizing it

2023-02-25 01:05 UTC, sharat87 requested changes
Sorry, coming up with more stuff. Shell scripts tend to be very fragile so they make me a little anxious. Thank you for your patience with this. 🙏

2023-02-25 01:05 UTC, sharat87 commented on scripts/cleanup_dp.sh
> +deployed_charts="$(helm ls -A | awk '/ce/ {print $2}')"
I just ran this `helm ls` command and there's a lot of columns and it felt fragile. Should we just go with JSON here as well?

```suggestion
deployed_charts="$(helm ls -A --filter 'ce[0-9]+' --no-headers --output json | jq -r '.[].namespace')"
```

This feels more stable, and also states explicitly that we're after the _namespaces_ for each installation.

2023-02-25 01:05 UTC, sharat87 commented on scripts/cleanup_dp.sh
> +mkdir ~/.aws; touch ~/.aws/config
This is not needed anymore I think.

```suggestion
```

2023-02-25 01:05 UTC, sharat87 commented on scripts/cleanup_dp.sh
> +# Configure the AWS & kubectl environment
Can we set the `errexit` and `nounset` settings please?

```suggestion
#!/bin/bash
# Configure the AWS & kubectl environment

set -o errexit
set -o nounset
```

2023-03-14 10:30 UTC, sharat87 reviewed
I see you've requested for review, but looks like there's still some unresolved comments from my previous review. Can you resolve/comment on them please?

2023-04-14 11:30 UTC, sharat87 approved these changes

2023-04-17 06:09 UTC, merged