fix: Table breaks on adding binding to column name
appsmithorg/appsmith pull request #20686
Opened 2023-02-16 14:14 UTC by souma-ghosh

## Description

When user adds any sort of binding to the column name of a table from property pane Columns section, the table breaks.
This was happening because of the column label getting stored as undefined or as an object that the binding evaluates to.
Only string values are expected in column label. Hence the table was breaking for non string values of column label.

This PR fixes this issue by replacing the column name with a default text "customColumn" whenever the column label is not of type string

Fixes #20663 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Cypress

### Test Plan
> Add Testsmith test cases links that relate to this PR

### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)

## Checklist:
### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2023-02-20 11:01 UTC, keyurparalkar requested changes

2023-02-20 13:52 UTC, keyurparalkar commented on app/client/src/widgets/TableWidgetV2/widget/index.tsx
> +          Header:
As discussed with Dilip, @souma-ghosh please use "Default custom column" for placeholder text

2023-02-21 04:48 UTC, souma-ghosh commented on app/client/src/widgets/TableWidgetV2/widget/index.tsx
> +          Header:
@dilippitchika Here this error will happen for any column, not just custom columns. So we need a default label to be assigned to the column whenever required. Could you suggest an appropriate column label that will show up in the column header?

2023-02-21 04:50 UTC, dilippitchika commented on app/client/src/widgets/TableWidgetV2/widget/index.tsx
> +          Header:
Understood just use "Table column" for now and proceed. Let's aim to close this today.

2023-02-21 05:09 UTC, souma-ghosh commented on app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Widgets/TableV2/TableV2_misc.js
> +    cy.openPropertyPane("tablewidgetv2");
The second test case where we are typing {{ap}} into the column label will result in undefined.
The first one where {{appsmith}} is typed in will result in a defined object. Hence we are using 2 separate test cases here.

2023-02-21 06:36 UTC, keyurparalkar reviewed
Please move it to QA

2023-02-21 06:36 UTC, keyurparalkar commented on app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Widgets/TableV2/TableV2_misc.js
> +    ).type("{{}{{}appsmith.mode{}}{}}");
Add this as comment: https://docs.cypress.io/api/commands/type#Arguments

2023-02-21 06:42 UTC, souma-ghosh commented
/build-deploy-preview

2023-02-21 12:50 UTC, chandannkumar commented
Tested this PR and LGTM

2023-02-21 14:21 UTC, keyurparalkar commented on app/client/src/widgets/TableWidgetV2/widget/index.tsx
> +          Header:
> @souma-ghosh this error is happening because the label property on the column object does not exist.
> Also, add a check if the label property exists or not.

Can you please add this check?

2023-02-21 15:01 UTC, souma-ghosh commented
/build-deploy-preview

2023-02-22 04:31 UTC, keyurparalkar approved these changes

2023-02-22 05:41 UTC, chandannkumar commented
Re-tested this PR and LGTM

2023-02-22 05:57 UTC, souma-ghosh commented
/ok-to-test sha=923c04e

2023-02-22 14:13 UTC, Rhitottam commented
/perf-test

2023-02-22 15:32 UTC, merged