fix: Remove excess margin from the top of the canvas
appsmithorg/appsmith pull request #20751
Opened 2023-02-17 13:15 UTC by riodeuno

## Description
This is UI polish fix. 
We're reducing the margin at the top of the canvas to gain vertical real-estate

Fixes #20750 

Media
Before:
![Screenshot 2023-02-17 at 6 42 10 PM](https://user-images.githubusercontent.com/103687/219662397-490ad62e-b2fa-425e-a929-7d5fa4971974.png)

After
![Screenshot 2023-02-17 at 6 44 25 PM](https://user-images.githubusercontent.com/103687/219662432-78a9cb9f-0dba-4edf-af29-069ef074eac6.png)

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manual

### Test Plan

### Issues raised during DP testing

## Checklist:
### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2023-02-20 15:18 UTC, akash-codemonk submitted a review, later dismissed

2023-02-20 18:19 UTC, rahulramesha commented
@riodeuno Vercel build seems to have failed

2023-02-21 06:45 UTC, rahulramesha commented
/build-deploy-preview

2023-02-21 07:43 UTC, akash-codemonk commented on app/client/src/pages/Editor/WidgetsEditor/CanvasContainer.tsx
> -        "mt-0": !shouldHaveTopMargin,
Single page in preview mode has a top margin with this change.
PR
<img width="1440" alt="pr" src="https://user-images.githubusercontent.com/67054171/220279869-26c7e0e4-ad55-44b8-9763-09a973eb6388.png">
Release
<img width="1422" alt="release" src="https://user-images.githubusercontent.com/67054171/220279921-5759cc5a-6df9-4b34-8ce4-8c8c59b8d372.png">

2023-02-21 07:44 UTC, riodeuno commented on app/client/src/pages/Editor/WidgetsEditor/CanvasContainer.tsx
> -        "mt-0": !shouldHaveTopMargin,
Thanks @akash-codemonk I'll check it out.

2023-02-24 14:12 UTC, riodeuno commented
/build-deploy-preview

2023-02-24 14:13 UTC, riodeuno commented on app/client/src/pages/Editor/WidgetsEditor/CanvasContainer.tsx
> -        "mt-0": !shouldHaveTopMargin,
@akash-codemonk I've updated the code. Please review again.

2023-02-27 04:14 UTC, riodeuno commented
/ok-to-test sha=7dd71bd

2023-02-27 04:14 UTC, riodeuno commented
/build-deploy-preview

2023-02-27 04:27 UTC, akash-codemonk submitted a review, later dismissed

2023-02-27 18:58 UTC, rahulramesha submitted a review, later dismissed

2023-03-08 12:49 UTC, riodeuno commented
/ok-to-test sha=d334de6

2023-03-15 12:51 UTC, riodeuno commented
/ok-to-test sha=d334de6

2023-03-15 16:35 UTC, riodeuno commented
/ci-merge-check

2023-03-27 06:19 UTC, riodeuno commented
@dhruvikn I would need some context on how the margins are changing.

Context on this PR:
- We're trying to reduce the gap at the top in the "editor" (not the view mode or preview mode)
- The way I've done this is to utilise the `classNames` in `CanvasContainer`, and add smaller margins by checking if we're in `isPreviewMode`. So, if `isPreviewMode = false`, we use smaller margins (tailwind CSS classes)

Please review this. If you have any comments on this, let's discuss it on this thread.

2023-03-27 06:19 UTC, riodeuno commented
/build-deploy-preview skip-tests=true

2023-03-28 10:43 UTC, dhruvikn commented
Hi @riodeuno,

There are some flags that decide how much the top margin the canvas should have. Here's a breakdown - 

1. isPreviewMode - True when the preview mode (triggered from the top right preview button)
2. isAppSettingsPaneWithNavigationTabOpen - True when the app settings pane is open and the navigation sub-section is active. The canvas here should look exactly as in the preview mode (except for the width).
3. shouldHaveTopMargin - this flag is calculated by
```js
shouldHaveTopMargin = !isPreviewMode || !isAppSettingsPaneWithNavigationTabOpen || pages.length > 1;
```
4. showCanvasTopSection - True when "Start from a template" and "Generate page from a data table" cards are shown on top of the canvas when a user creates a new application.

Using a combination of these flags, we add different tailwind classes to the #canvas-viewport.

I checked out your branch but couldn't find any difference in the top margin.

Your branch - 
![CleanShot 2023-03-28 at 15 58 46](https://user-images.githubusercontent.com/22471214/228208302-1a23f89f-9eb6-4311-9584-9da440e1015d.png)

Release - 
![CleanShot 2023-03-28 at 15 59 04](https://user-images.githubusercontent.com/22471214/228208375-194e2277-0a47-4c0f-98fd-98fee5b265b8.png)

We will need to change line 278, which has the class "mt-8" as this is the margin in the edit mode.

Also, we can improve on this code chunk. Instead of 
```js
      className={classNames({
        [`${getCanvasClassName()} scrollbar-thin`]: true,
        "mt-0": !shouldHaveTopMargin && isPreviewMode,
        "mt-4": showCanvasTopSection && !isPreviewMode,
        "mt-8":
          shouldHaveTopMargin &&
          !showCanvasTopSection &&
          !isPreviewMode &&
          !isAppSettingsPaneWithNavigationTabOpen,
      })}
```
we can do 
```js 
      className={classNames({
        [`${getCanvasClassName()} scrollbar-thin`]: true,
        "mt-0": !shouldHaveTopMargin,
        "mt-4":
          showCanvasTopSection &&
          !isPreviewMode &&
          !isAppSettingsPaneWithNavigationTabOpen,
        "mt-8": shouldHaveTopMargin && !showCanvasTopSection,
      })}
```

I should have made this small improvement but I missed this in my last improved app navigation PR. Therefore, since you're making changes, can you please do the needful?

2023-03-28 10:46 UTC, dhruvikn requested changes
Requesting changes as mentioned here - https://github.com/appsmithorg/appsmith/pull/20751#issuecomment-1486626646

2023-04-07 06:35 UTC, riodeuno commented
@dhruvikn Thanks for the feedback. I'm going to be closing this PR in favour of the changes coming in with Auto Layout.

2023-04-07 06:35 UTC, closed without merging

2023-04-07 06:36 UTC, riodeuno commented
@prsidhu Here is a cleaner implementation that we were considering. Please see the sample provided by @dhruvikn and consider them in the implementation that we have for auto layout.

2023-04-10 12:29 UTC, prsidhu commented
@riodeuno @dhruvikn We'll include the changes derived from this conversation in our next release.