`Confirm before executing` setting does not work when a JS function is trigged
appsmithorg/appsmith pull request #20890
Opened 2023-02-23 05:23 UTC by Druthi

## Description
 Bug-17500: `Confirm before executing` setting does not work when a JS function is trigged on a button click
Bug-13636: Function execution does not wait for user confirmation when a nested function and when run on load.

Fixes #17500 
#13646 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manual
- Cypress

### Test Plan
> Add Testsmith test cases links that relate to this PR

### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)

## Checklist:
### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2023-02-23 05:25 UTC, Druthi commented
/ok-to-test sha=87b3fa0

2023-02-23 07:21 UTC, Druthi commented on app/client/src/workers/Evaluation/fns/utils/jsObjectFnFactory.ts
> +      const jsObject = globalThis[calledJsObject];
Not sure if there is a better way of accessing this

2023-02-28 05:58 UTC, ohansFavour commented
@Druthi Can you ensure that all tests (jest and cypress) pass? Jest tests are currently failing.

2023-02-28 06:19 UTC, ohansFavour requested changes

2023-02-28 06:19 UTC, ohansFavour commented on app/client/src/sagas/ActionExecution/PluginActionSaga.ts
> +      //Hacky way to wait for 1 second to ensure that evaluations are run before the page load action
Why are we waiting here?. In the previous implementation, there was no need to wait, so why now?.

2023-02-28 06:19 UTC, ohansFavour commented on app/client/src/sagas/JSPaneSagas.ts
> +
Why was the `if statement` removed here?. There is a different logic to set data for async executions. 

This will cause duplication of SET_JS_FUNCTION_EXECUTION_DATA

2023-02-28 06:19 UTC, ohansFavour commented on app/client/src/workers/Evaluation/fns/utils/jsObjectFnFactory.ts
> +      const calledJsObject = name.split(".")[0];
use getEntityNameAndPropertyPath here

2023-02-28 06:19 UTC, ohansFavour commented on app/client/src/workers/Evaluation/fns/utils/jsObjectFnFactory.ts
> +      const jsObject = globalThis[calledJsObject];
Use "self". Or consider passing the JSObject's config as a prop to jsObjectFunctionFactory

2023-02-28 06:31 UTC, Aishwarya-U-R commented on app/client/cypress/integration/Regression_TestSuite/ClientSideTests/BugTests/ConfirmBeforeExecutingBugs_Spec.ts
> +const dsl = require("../../../../fixtures/buttondsl.json");
Can we please add dsl with below instead of having const in specs?

```
 cy.fixture("buttondsl").then((val: any) => {
      agHelper.AddDsl(val);
    });
```

In this case - I dont see this dsl variable being used in the test. Is this dsl required in that case at all?

2023-03-01 06:00 UTC, Druthi commented on app/client/cypress/integration/Regression_TestSuite/ClientSideTests/BugTests/ConfirmBeforeExecutingBugs_Spec.ts
> +const dsl = require("../../../../fixtures/buttondsl.json");
Not being used. removed it.

2023-03-02 06:23 UTC, Druthi commented
/ok-to-test sha=a25493f

2023-03-02 07:35 UTC, Druthi commented
/ok-to-test sha=feacc71

2023-03-02 09:13 UTC, Druthi commented
/build-deploy-preview

2023-03-02 09:18 UTC, Druthi commented on app/client/src/reducers/entityReducers/jsActionsReducer.tsx
> +    state.map((a) => {
This was already there and a lot of places in the file seems to reference it this way. Leaving this for now.

2023-03-03 14:04 UTC, shwetha-ramesh commented
@Druthi  Tested [17500](https://github.com/appsmithorg/appsmith/issues/17500)
[13646](https://github.com/appsmithorg/appsmith/issues/13646), working as expected. Moving to Done.

2023-03-08 11:28 UTC, Druthi commented
/ok-to-test sha=6206aa8

2023-03-08 12:05 UTC, Druthi commented
/ok-to-test sha=921aabd

2023-03-09 04:32 UTC, Druthi commented
/ok-to-test sha=e4d3aef

2023-03-09 09:23 UTC, Druthi commented
/ok-to-test sha=4ecb41f

2023-03-13 05:20 UTC, Druthi commented
/ok-to-test sha=01da4f4

2023-03-14 17:42 UTC, Druthi commented
/ok-to-test sha=16c5811

2023-03-15 06:01 UTC, Druthi commented
/ok-to-test sha=6794c38

2023-03-16 07:15 UTC, Druthi commented
/build-deploy-preview env=release

2023-03-16 10:30 UTC, Rishabh-Rathod commented on app/client/src/workers/Evaluation/evaluate.ts
> +        ? jsObjectFunctionFactory(fn, jsObjectName + "." + fnName, dataTree)
Did we consider passing `jsObject` instead of dataTree here?

2023-03-16 10:30 UTC, Rishabh-Rathod commented on app/client/src/workers/Evaluation/fns/utils/jsObjectFnFactory.ts
> +  const confirmBeforeExecute = entityMeta[propertyPath].confirmBeforeExecute;
```suggestion
  const { isAsync, confirmBeforeExecute }  = entityMeta[propertyPath];
```

2023-03-20 08:07 UTC, Druthi commented
/build-deploy-preview env=release

2023-03-20 11:46 UTC, Druthi commented
/build-deploy-preview env=release

2023-03-21 03:10 UTC, Druthi commented
/ok-to-test sha=696f979

2023-03-21 03:10 UTC, Druthi commented
/build-deploy-preview env=release

2023-03-21 03:42 UTC, Druthi commented
/ok-to-test sha=7c141b7

2023-03-21 03:42 UTC, Druthi commented
/build-deploy-preview env=release

2023-03-21 04:20 UTC, Druthi commented
/ok-to-test sha=4a4c473

2023-03-21 04:31 UTC, Druthi commented
/build-deploy-preview env=release

2023-03-21 07:20 UTC, Rishabh-Rathod commented on app/client/src/workers/Evaluation/functionDeterminer.ts
> -    }
This change would also fix issue mentioned here https://github.com/appsmithorg/appsmith/issues/21303

2023-03-22 06:08 UTC, Druthi commented
/ok-to-test sha=2b2af25

2023-03-22 06:08 UTC, Druthi commented
/build-deploy-preview env=release

2023-03-22 10:40 UTC, Druthi commented
/ok-to-test sha=7b50074

2023-03-22 13:21 UTC, Druthi commented
/ok-to-test sha=3770d83

2023-03-23 03:42 UTC, Druthi commented
/ok-to-test sha=6ba9f1a

2023-03-23 04:18 UTC, Druthi commented
/ok-to-test sha=8c7f03e

2023-03-23 04:46 UTC, Druthi commented
/ok-to-test sha=24849a4

2023-03-23 06:16 UTC, Druthi commented
/build-deploy-preview env=release

2023-03-23 10:14 UTC, Druthi commented
/ok-to-test sha=5e76ecb

2023-03-27 04:01 UTC, Druthi commented
/ok-to-test sha=d899a2a

2023-03-27 04:50 UTC, Druthi commented
/ok-to-test sha=098fc8a

2023-03-27 10:07 UTC, Rishabh-Rathod reviewed
Let's try to avoid 
- configTree being passed as params in createEvaluationContext.
- using `isAsync` flag.

2023-03-27 10:07 UTC, Rishabh-Rathod commented on app/client/src/workers/Evaluation/fns/utils/jsObjectFnFactory.ts
> +  if (isAsync) {
Just realized that the `isAsync` flag being true doesn't mean that the code written by the user is actual javascript's async functions. In that case, we might need to return `async function` only in the case where the function actually uses `async` keyword. This could be done by using `fn.constructor.name === 'AsyncFunction'`.

2023-03-27 10:32 UTC, Druthi commented on app/client/src/workers/Evaluation/handlers/executeSyncJS.ts
> +  const configTree = dataTreeEvaluator.oldConfigTree;
Because it is not the most updated value at that point when we pass configTree down the chain.

2023-03-27 10:37 UTC, Druthi commented on app/client/src/workers/Evaluation/fns/utils/jsObjectFnFactory.ts
> +  if (isAsync) {
What does `isAsync` signify then?

2023-03-27 10:43 UTC, Druthi commented on app/client/src/workers/Evaluation/handlers/executeSyncJS.ts
> +  const configTree = dataTreeEvaluator.oldConfigTree;
Spoke to @ApekshaBhosale as well. She also suggested sending the configTree down

2023-03-27 10:52 UTC, Druthi commented on app/client/src/workers/Evaluation/handlers/executeSyncJS.ts
> +  const configTree = dataTreeEvaluator.oldConfigTree;
<img width="431" alt="image" src="https://user-images.githubusercontent.com/20187542/227920928-69a78e90-3be0-4253-a01f-9a339e232b3c.png">
This is the value of `dataTreeEvaluator.oldConfigTree`

While this is the value of the current `configTree` 
<img width="373" alt="image" src="https://user-images.githubusercontent.com/20187542/227921106-f61276eb-aa04-4009-b91d-cf67aedcdf22.png">

2023-03-29 06:19 UTC, closed without merging