Feat/create application snapshot
appsmithorg/appsmith pull request #20933
Opened 2023-02-24 06:08 UTC by nayan-rafiq

## Description
This PR adds a way to take a snapshot of an application on the database. That snapshot can be restored to the application. 

Under the hood it uses the Export-Import feature.

Fixes #19720

Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video

## Type of change

> Please delete options that are not relevant.
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
- Manual
- JUnit tests

### Test Plan
> Add Testsmith test cases links that relate to this PR

### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)

## Checklist:
### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2023-02-24 06:16 UTC, nayan-rafiq commented
/ok-to-test sha=3a6eb9e506012b3d28b342c1f87711f1951451d8

2023-02-24 09:29 UTC, nayan-rafiq commented
/ok-to-test sha=1aa1bccf47e7ce3b959aa4380dac3d6a97b5bc7a

2023-02-25 09:58 UTC, AnaghHegde requested changes
Can we Unit tests for ImportExport flow as well?

2023-02-25 09:58 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
> +                                                    importedApplication.setPolicies(null);
Why are we setting this to null? We don't export the policies right.

2023-02-25 09:58 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/ApplicationControllerCE.java
> +                                                           @RequestHeader(name = FieldName.BRANCH_NAME, required = false) String branchName) {
Nit - Indentation seems to be off.

2023-02-25 09:58 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/ApplicationControllerCE.java
> +                                                                  @RequestHeader(name = FieldName.BRANCH_NAME, required = false) String branchName) {
Same as above. Indentation seems off.

2023-02-25 09:58 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/ApplicationControllerCE.java
> +                .map(snapshotId -> new ResponseDTO<>(HttpStatus.OK.value(), snapshotId, null));
Since its a POST. shouldn't we be using the HttpStatus.CREATED.value() here?

2023-02-25 09:58 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/ApplicationControllerCE.java
> +                .map(application -> new ResponseDTO<>(HttpStatus.OK.value(), application, null));
Same. Shouldn't we be using the HttpStatus.CREATED.value() here?

2023-02-25 09:58 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/domains/ApplicationSnapshot.java
> +@NoArgsConstructor
With the `@Document` we don't need the Getter and Setter right?

2023-02-25 09:58 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog2.java
> +
With the Spring boot 3.x upgrade, i don't think this migration will work. We should be creating a separate class for each migration. Please refer this - https://github.com/appsmithorg/appsmith/blob/release/app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration003PermissionGroupDefaultWorkspaceIdMigration.java

Notion doc- https://www.notion.so/appsmith/Mongock-upgrade-3b4e5f32dcda47c08ef9d96cfedf15a9

2023-02-25 09:58 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/CustomApplicationSnapshotRepositoryImpl.java
> +@Component
Can you please help me in understanding on why we are using the @component annotation here?

2023-02-25 09:58 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationSnapshotServiceCEImpl.java
> +                    applicationSnapshot.setApplicationId(applicationId);
The maximum size of BSON document is 16MB with nested level of 100. If we have a huge application then this could lead to data corruption or data loss issues right? Can we add a check to ensure we don't run into this issue.

2023-02-25 09:58 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImplV2.java
> +                                                                existingApplication.getGitApplicationMetadata().getDefaultApplicationId()
Can you help me understand the logic here? How are we handling the non git connected Apps?

2023-02-26 05:59 UTC, nayan-rafiq commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImplV2.java
> +                                                                existingApplication.getGitApplicationMetadata().getDefaultApplicationId()
@AnaghHegde for non git connected apps, we don't need to fetch the parent aka default application. Hence in the else part of this `if`, I'm returning the current application using `Mono.just()`

2023-02-26 06:18 UTC, nayan-rafiq commented on app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/CustomApplicationSnapshotRepositoryImpl.java
> +@Component
@AnaghHegde Actually this is how we add custom implementation for repository classes in spring data. In spring boot, we don't need to implement the interface, the framework itself creates an implementation when application is started. But it it sees that the repository interface extends some other interfaces, it needs their implementations as well. Using `Component` annotation, we're marking the implementation class as a bean. The spring boot will automatically pick up this as the base class when it'll implement the repository interface.

Thanks for this question because I actually followed the existing pattern without knowing much. You'll find that all the `Impl` classes under the repository package has this annotation. I explored about this just to answer this question :)

2023-02-26 09:59 UTC, nayan-rafiq commented on app/server/appsmith-server/src/main/java/com/appsmith/server/domains/ApplicationSnapshot.java
> +@NoArgsConstructor
No, we need both actually. The one you're talking about is `@Data`. `Getter, Setter, NoArgsConstructor, Data` they are lombok annonations. We use them to generate Getters, Setters, Constructors on the fly. `@Document` annotation is from mongodb and it marks a class as persistable to DB.

The [`@Data`](https://projectlombok.org/features/Data) annotation is actually a wrapper that generates getters, setters and a constructor along with few other methods.  We don't use `@Data` for the domain classes because we don't need all args constructor for domain classes. That's why we use `Getter, Setter, NoArgsConstructor` annotations separately.

2023-02-26 10:12 UTC, nayan-rafiq commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
> +                                                    importedApplication.setPolicies(null);
@AnaghHegde I was facing trouble because the `importedApplication` had empty policies instead of null. As a result, the `copyNestedNonNullProperties` method was not copying the policies from existing app to imported app. That's why I think better set it to null to ensure the `copyNestedNonNullProperties` works as expected.

2023-02-26 10:17 UTC, nayan-rafiq commented
> Can we Unit tests for ImportExport flow as well?

@AnaghHegde I've added unit tests for the new services. As this calls the import-export service, I didn't add another test for the import-export services. I'll try adding unit tests for that as well.

2023-02-26 10:28 UTC, nayan-rafiq commented on app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/ApplicationControllerCE.java
> +                .map(application -> new ResponseDTO<>(HttpStatus.OK.value(), application, null));
@AnaghHegde, no. We're not creating any new resource through this endpoint. We're updating an existing application. That's why `HttpStatus.CREATED` should not be returned from this endpoint response.

2023-02-26 15:15 UTC, AnaghHegde commented
@nayan-rafiq Since this PR adds a support for merging the application json for non git connected apps, we can add a test case specifically for this flow.

2023-02-27 11:38 UTC, nayan-rafiq commented
/ok-to-test sha=cc2b05da76df4030e1c3c0e70d0b44b0ee35b6d9

2023-02-27 11:44 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
> +                                                    importedApplication.setPolicies(null);
@nayan-rafiq How are we getting this data? Can we ensure that this is handled in the same flow?

2023-02-27 11:45 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/domains/ApplicationSnapshot.java
> +@NoArgsConstructor
Yes you are right. I got confused with those two. My bad.

2023-02-27 11:46 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/CustomApplicationSnapshotRepositoryImpl.java
> +@Component
Thanks a lot for explaining this ❤️

2023-02-27 11:49 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationSnapshotServiceCEImpl.java
> +                        return Mono.error(new AppsmithException(AppsmithError.GENERIC_BAD_REQUEST, "Application too large for snapshot"));
Do we need to think of any other solutions here? Reason i am asking is because the user cannot try this feature on a large application. Is that correct?

2023-02-27 11:50 UTC, AnaghHegde commented on app/server/appsmith-server/src/test/java/com/appsmith/server/services/ApplicationSnapshotServiceTest.java
> +public class ApplicationSnapshotServiceTest {
Can we assert for a failure case as well?

2023-02-28 17:38 UTC, nayan-rafiq commented
/ok-to-test sha=47c4e5d0ae518166239d1a5f3dc1929b8eabe1b8

2023-02-28 17:40 UTC, nayan-rafiq commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationSnapshotServiceCEImpl.java
> +                        return Mono.error(new AppsmithException(AppsmithError.GENERIC_BAD_REQUEST, "Application too large for snapshot"));
@AnaghHegde I've updated the code. Instead of storing the applicationJson in a single collection, now I'm splitting it into multiple objects when the size limit exceeds.

2023-03-01 05:50 UTC, nayan-rafiq commented
/ok-to-test sha=6faca7a5780be7eaa06fc4446bc010a23a14fcdd

2023-03-01 08:52 UTC, AnaghHegde approved these changes
Minor comments. Rest Looks good to me

2023-03-01 08:52 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationSnapshotServiceCEImpl.java
> +    private Mono<String> getApplicationJsonString(String applicationId) {
Nit - can we rename this to `getApplicationJsonStringFromSnapShot`

2023-03-01 08:52 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationSnapshotServiceCEImpl.java
> +                            .thenMany(createSnapshots(branchedAppId, applicationJson));
Can you help me in understanding why do we need to use `thenMany` here?

2023-03-01 09:52 UTC, nayan-rafiq commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationSnapshotServiceCEImpl.java
> +                            .thenMany(createSnapshots(branchedAppId, applicationJson));
The `createSnapshots` method returns a Flux. We use `flatMap` on a `Mono` when we return another `Mono` from the `flatMap` method. But if we need to return a `Flux` from the `flatMap` method, we need to use `flatMapMany`. The `createSnapshots` method returns a `Flux` so we need to use `flatMapMany`.

2023-03-01 09:56 UTC, nayan-rafiq commented
/ok-to-test sha=1dac05d353866da7fb10ac5aa83c446697437ad6

2023-03-01 11:06 UTC, merged