Perf: Yarn 3 + deduping dependencies
appsmithorg/appsmith pull request #20964
Opened 2023-02-26 04:16 UTC by iamakulov

## Description

This PR:
- upgrades Appsmith to Yarn v3
  - see what’s new: https://yarnpkg.com/getting-started/qa#why-should-you-upgrade-to-yarn-modern
  - this upgrade also makes it possible to enable Yarn Plug'n'Play, which will make Yarn commands even faster. I haven’t attempted this (it needs a bit of work) but I’d recommend trying it out: https://yarnpkg.com/features/pnp
- migrates the `shared/ast` to Yarn Workspaces
  - this makes managing shared packages much simpler (you don’t need the whole `build-shared-dep.js`, `install-dependencies.js`, etc logic)
  - and makes Yarn runs cheaper (`shared/ast` is now rebuilt only when needed instead of on every `yarn add`)
- replaces `patch-package` with Yarn’s native package patching
- dedupes all packages
  - (did you know we had 4 versions of `@blueprintjs/core` installed?)
- makes `yarn dedupe` run on every install

Apart from DX improvements, this also makes the bundle almost 10% smaller (9.01 → 8.14 MB minified).

## Type of change

- Chore (housekeeping or task changes that don't impact user perception)

## How Has This Been Tested?

- Manual: smoke testing (clicking around the dashboard and the editor)

### Test Plan
> Add Testsmith test cases links that relate to this PR

### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)

## Checklist:
### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2023-02-28 05:10 UTC, yaldram commented on app/client/package.json
> -  "resolutions": {
These resolutions are necessary, because we want to use the following package versions, that have no security vulnerabilities, I fear removing these resolutions might install packages that have vulnerabilities.

2023-02-28 08:57 UTC, SatishGandham commented
/ok-to-test

2023-03-02 04:35 UTC, SatishGandham requested changes

2023-03-02 04:35 UTC, SatishGandham commented on app/client/package.json
> -  "resolutions": {
Why did we move these to app/package.json?

2023-03-02 04:35 UTC, SatishGandham commented on app/client/patches/@blueprintjs+core+3.36.0.patch
> -+        // updateInputDimensions is an expensive method. Call it only when the props
We are removing this patch, is it fixed in the version of blue-print we are using?

2023-03-02 06:07 UTC, yaldram approved these changes

2023-03-02 06:07 UTC, yaldram commented on app/client/package.json
> +    "@blueprintjs/core": "^3.43.0",
Blueprint is updated here, might need to check if everything is working as expected.

2023-03-03 17:15 UTC, iamakulov commented on app/client/package.json
> -  "resolutions": {
Oh, that’s a great q – I wasn’t quite sure myself when I was submitting the PR, but I have since figured out why. 

Basically:

1. CRA [sets a webpack flag](https://github.com/facebook/create-react-app/blob/d960b9e38c062584ff6cfb1a70e1512509a966e7/packages/react-scripts/config/webpack.config.js#L306-L312) called `resolve.modules`:
  
   ```js
   module.exports = {
     resolve: {
       modules: ['node_modules', 'src']
     }
   }
   ```
  
   This tells webpack where to look up package imports like `import 'foo/bar.js'`. With this config, webpack will try to look for `foo/bar.js` in `node_modules/foo/bar.js` and then in `src/foo/bar.js`. 
      
2. We have multiple versions of the `entities` package installed as a transitive dependency of `htmlparser2`, `domutils`, and more.

   Before this PR, the version of the package hoisted into `app/client/node_modules/entities` was `2.0.0`. After moving to Yarn workspaces and deduping dependencies, the version of the package hoisted into `app/node_modules/entities` became `4.4.0`.

   The key difference between `2.0.0` and `4.4.0` is that `4.4.0` has [an `exports` field](https://github.com/webpack/webpack/issues/9509) in its `package.json`:
   
    ```json
    {
        "exports": {
            ".": {
                "require": "./lib/index.js",
                "import": "./lib/esm/index.js"
            },
            "./lib/decode.js": {
                "require": "./lib/decode.js",
                "import": "./lib/esm/decode.js"
            },
            "./lib/escape.js": {
                "require": "./lib/escape.js",
                "import": "./lib/esm/escape.js"
            }
        }
    }
    ```
    
3. When the `exports` field is present, webpack (and Node.js) start verifying package imports more strictly. Without the `exports` field, when we had this import:

   ```js
   import { APP_MODE } from "entities/App";
   ```
   
   webpack would try to resolve it `node_modules/entities/App`, see that that file doesn’t exist, and try `src/entities/App` next.
   
   Now, with the `exports` field, webpack additionally verifies whether `entities/App` is an allowed export. And since the `exports` object above ↑ doesn’t include `App`, webpack throws an error:
   
    ```
    ERROR in ./src/RouteBuilder.ts 5:0-40
    Module not found: Error: Package path ./App is not exported from package /Users/iamakulov/Repos/appsmith/app/node_modules/entities (see exports field in /Users/iamakulov/Repos/appsmith/app/node_modules/entities/package.json)
    ```
    
4. That’s why the change is needed. It puts `src` as the first item in `require.modules` – and makes webpack try importing `src/entities/App` first. This resolves the error.

   The alternative is to rename `entities` to something else, but I’d rather solve the root issue. What if we install eg the `reflow` package next?

2023-03-03 17:17 UTC, iamakulov commented on app/client/package.json
> -  "resolutions": {
Linked to this from the comment to provide more background 👍

2023-03-03 17:21 UTC, iamakulov commented on app/client/patches/@blueprintjs+core+3.36.0.patch
> -+        // updateInputDimensions is an expensive method. Call it only when the props
Correct! https://github.com/palantir/blueprint/pull/4723 was released in v3.44.3. Due to `yarn dedupe`, we’re now using Blueprint v3.47.0 (instead of 3.36.0 + 3.33.0 + 3.43.0 + 3.47.0, [like before](https://share.cleanshot.com/CMml4mCf)).

2023-03-03 17:21 UTC, iamakulov commented on app/client/craco.common.config.js
> +      plugin: {
Oh, that’s a great q – I wasn’t quite sure myself when I was submitting the PR, but I have since figured out why. 

Basically:

1. CRA [sets a webpack flag](https://github.com/facebook/create-react-app/blob/d960b9e38c062584ff6cfb1a70e1512509a966e7/packages/react-scripts/config/webpack.config.js#L306-L312) called `resolve.modules`:
  
   ```js
   module.exports = {
     resolve: {
       modules: ['node_modules', 'src']
     }
   }
   ```
  
   This tells webpack where to look up package imports like `import 'foo/bar.js'`. With this config, webpack will try to look for `foo/bar.js` in `node_modules/foo/bar.js` and then in `src/foo/bar.js`. 
      
2. We have multiple versions of the `entities` package installed as a transitive dependency of `htmlparser2`, `domutils`, and more.

   Before this PR, the version of the package hoisted into `app/client/node_modules/entities` was `2.0.0`. After moving to Yarn workspaces and deduping dependencies, the version of the package hoisted into `app/node_modules/entities` became `4.4.0`.

   The key difference between `2.0.0` and `4.4.0` is that `4.4.0` has [an `exports` field](https://github.com/webpack/webpack/issues/9509) in its `package.json`:
   
    ```json
    {
        "exports": {
            ".": {
                "require": "./lib/index.js",
                "import": "./lib/esm/index.js"
            },
            "./lib/decode.js": {
                "require": "./lib/decode.js",
                "import": "./lib/esm/decode.js"
            },
            "./lib/escape.js": {
                "require": "./lib/escape.js",
                "import": "./lib/esm/escape.js"
            }
        }
    }
    ```
    
3. When the `exports` field is present, webpack (and Node.js) start verifying package imports more strictly. Without the `exports` field, when we had this import:

   ```js
   import { APP_MODE } from "entities/App";
   ```
   
   webpack would try to resolve it `node_modules/entities/App`, see that that file doesn’t exist, and try `src/entities/App` next.
   
   Now, with the `exports` field, webpack additionally verifies whether `entities/App` is an allowed export. And since the `exports` object above ↑ doesn’t include `App`, webpack throws an error:
   
    ```
    ERROR in ./src/RouteBuilder.ts 5:0-40
    Module not found: Error: Package path ./App is not exported from package /Users/iamakulov/Repos/appsmith/app/node_modules/entities (see exports field in /Users/iamakulov/Repos/appsmith/app/node_modules/entities/package.json)
    ```
    
4. That’s why the change is needed. It puts `src` as the first item in `require.modules` – and makes webpack try importing `src/entities/App` first. This resolves the error.

   The alternative is to rename `entities` to something else, but I’d rather solve the root issue. What if we install eg the `reflow` package next?

2023-03-03 17:21 UTC, iamakulov commented on app/client/craco.common.config.js
> +      plugin: {
Linked to this from the comment to provide more background 👍

2023-03-03 17:24 UTC, iamakulov commented on app/client/package.json
> -  "resolutions": {
Yarn requires resolutions to be present in the root `package.json` – because they’re used to resolve all dependencies across all workspaces.

This is what you’ll see if you try to move `resolutions` back to `app/client/package.json`:

```sh
$ yarn
➤ YN0000: ┌ Project validation
➤ YN0057: │ appsmith: Resolutions field will be ignored
➤ YN0000: └ Completed
...
```

2023-03-07 09:03 UTC, SatishGandham commented on app/.yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
> +/* eslint-disable */
Should this file be committed?

2023-03-07 17:26 UTC, iamakulov commented on app/.yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
> +/* eslint-disable */
Yes! That’s by design; it prevents accidental version mismatches between environments: https://yarnpkg.com/getting-started/qa#which-files-should-be-gitignored

2023-03-07 17:43 UTC, merged