poc: disable widget resize handlers
appsmithorg/appsmith pull request #21041
Opened 2023-02-28 10:42 UTC by yaldram

## Description
- Add `disableWidgetResize` config to the autoLayout widget config.
- Disable the resize handlers in vertical and horizontal directions.

> Add a TL;DR when description is extra long (helps content team)

Fixes # (issue)
> if no issue exists, please create an issue and ask the maintainers about this first

Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update

## How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.
> Delete anything that is not important

- Manual
- Jest
- Cypress

### Test Plan
> Add Testsmith test cases links that relate to this PR

### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)

## Checklist:
### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2023-03-01 06:06 UTC, yaldram commented on app/client/src/components/editorComponents/ResizableComponent.tsx
>      !(NonResizableWidgets.includes(props.type) || isMultiSelected) ||
This line of code is used to disable all resize selectors when, we select multiple widgets, so this a total different use case. We should let `NonResizableWidgets` array as it is.

2023-03-01 06:08 UTC, yaldram commented on app/client/src/widgets/ImageWidget/index.ts
> +      horizontal: true,
`NonResizbleWidgets` is a separate array used for disabling all resize handlers when multiple widgets are selected, it is not used to disable resize handlers for widgets laying on the canvas.

2023-03-03 12:27 UTC, aswathkk reviewed
Added minor comments.
I will add @marks0351 to review changes related to core resizing code.

2023-03-03 12:27 UTC, aswathkk commented on app/client/src/components/editorComponents/ResizableUtils.ts
>      return isFlexChild && responsiveBehavior === ResponsiveBehavior.Fill
I feel like this condition could be moved into `isResizingDisabled`.
That way `isHandleResizeAllowed` will only deals with fixed mode resize

2023-03-03 12:27 UTC, aswathkk commented on app/client/src/components/editorComponents/ResizableUtils.ts
>      return isFlexChild && responsiveBehavior === ResponsiveBehavior.Fill
Needs @marks0351's input here

2023-03-07 07:23 UTC, marks0351 requested changes

2023-03-07 07:23 UTC, marks0351 commented on app/client/src/components/editorComponents/ResizableUtils.ts
>      return isFlexChild && responsiveBehavior === ResponsiveBehavior.Fill
@yaldram Sry for bringing this up late, cud u cut the mobile/v1/qa branch, coz i have actually restructured resizing and have separated auto layout resizing. so u cud pick these changes and apply to the auto layout's resize only.

2023-03-09 09:45 UTC, aswathkk commented on app/client/src/resizable/autolayoutresize/index.tsx
> +    const disableResizing = isResizingDisabled(
@yaldram Do you think it is better to move the logic of disabling of horizontal resize for fill widgets here?
If we do so, `isHandleResizeAllowed` will used only for fixed mode resize.

2023-03-09 09:45 UTC, aswathkk commented on app/client/src/widgets/InputWidgetV2/index.ts
> -      rows: 6.6,
great job in catching this and fixing it

2023-03-10 05:33 UTC, aswathkk requested changes
@yaldram 
A comment needs to be cleaned up.
Also, can you resolve the merge conflict?

2023-03-10 05:33 UTC, aswathkk commented on app/client/src/components/editorComponents/ResizableUtils.ts
> +    // remove all the horizontal resize handlers for fill widgets
This comment is irrelevant

2023-03-10 06:51 UTC, aswathkk approved these changes

2023-03-10 06:51 UTC, merged