chore: modifying error messages for error handling
appsmithorg/appsmith pull request #21052
Opened 2023-02-28 15:17 UTC by sondermanish

## Description

> Add a TL;DR when description is extra long (helps content team)

Fixes # (issue)
> if no issue exists, please create an issue and ask the maintainers about this first

Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update

## How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.
> Delete anything that is not important

- Manual
- Jest
- Cypress

### Test Plan
> Add Testsmith test cases links that relate to this PR

### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)

## Checklist:
### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2023-02-28 17:04 UTC, sondermanish commented
/ok-to-test sha=f36a6cb779b708d2b84d326545717de3ed1140eb

2023-02-28 18:08 UTC, subrata71 requested changes

2023-02-28 18:08 UTC, subrata71 commented on app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/constants/ErrorMessages.java
> +    public static final String EMPTY_ROW_ARRAY_OBJECT_MESSAGE = "Row object(s) cannot be empty.";
These two are essentially the same.

2023-02-28 18:08 UTC, subrata71 commented on app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/constants/ErrorMessages.java
> +    public static final String EMPTY_UPDATE_ROW_OBJECTS_MESSAGE = "Update Row object(s) cannot be empty.";
These two are essentially the same.

2023-03-01 10:31 UTC, sondermanish commented on app/server/appsmith-plugins/postgresPlugin/src/main/java/com/external/plugins/exceptions/PostgresErrorMessages.java
> +    public static final String POSTGRES_JDBC_DRIVER_LOADING_ERROR_MSG = "Your PostgreSQL query failed to execute.";
Although this doesn't make any diff on the end result and messages, the variable name itself improves code readability.

2023-03-02 07:45 UTC, sondermanish commented on app/server/appsmith-plugins/postgresPlugin/src/main/java/com/external/plugins/exceptions/PostgresErrorMessages.java
> +    public static final String POSTGRES_JDBC_DRIVER_LOADING_ERROR_MSG = "Your PostgreSQL query failed to execute.";
Resolving conversation as discussed.

2023-03-02 08:10 UTC, sondermanish commented
/ok-to-test sha=c4c6ef7

2023-03-02 08:42 UTC, subrata71 commented
/build-deploy-preview

2023-03-02 10:06 UTC, subrata71 commented
/ok-to-test sha=901fe23

2023-03-02 19:06 UTC, sondermanish commented
/ok-to-test sha=8ba94165af7c715245afe5e159b1afff28130102

2023-03-03 04:23 UTC, ChandanBalajiBP commented
/ok-to-test sha=a46aaa2

2023-03-03 09:06 UTC, sondermanish commented
/ok-to-test sha=82116ad8ffcfcfe98258645a68c7786759c4dbdb

2023-03-03 11:02 UTC, subrata71 approved these changes

2023-03-03 11:27 UTC, subrata71 commented
/build-deploy-preview

2023-03-03 12:46 UTC, Aishwarya-U-R reviewed
Cypress changes looks ok!

2023-03-03 14:18 UTC, merged