fix: signup issues
appsmithorg/appsmith pull request #21183
Opened 2023-03-06 09:17 UTC by eco-monk

## Description
- #16941 - On signout
Re-open login page in a new tab to clear history. This makes sure user's cannot click back button to retrieve sensitive information
- #13093
When disabled, `Get started` button in welcome page will not redirect on click

Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manual
- Jest
- Cypress

### Test Plan
> Add Testsmith test cases links that relate to this PR

### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)

## Checklist:
### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2023-03-06 09:17 UTC, eco-monk commented
/ok-to-test

2023-03-06 10:37 UTC, eco-monk commented
/build-deploy-preview

2023-03-07 05:01 UTC, hetunandu requested changes

2023-03-07 05:01 UTC, hetunandu commented on app/client/src/ce/sagas/userSagas.tsx
> +      yield put(flushErrorsAndRedirect(redirectURL || AUTH_LOGIN_URL, true));
I always figured we will clear the history and not create a new tab

```suggestion
history.go(-history.length) // This will take it to the first page of the session
history.replace(redirectURL || AUTH_LOGIN_URL) // This will show the correct page
```

2023-03-07 05:01 UTC, hetunandu commented on app/client/src/sagas/ErrorSagas.tsx
> +  if (action.payload.inNewTab) {
This is a bad idea and setting created just for this particular scenario. I would avoid it

2023-03-07 06:05 UTC, eco-monk commented on app/client/src/ce/sagas/userSagas.tsx
> +      yield put(flushErrorsAndRedirect(redirectURL || AUTH_LOGIN_URL, true));
I actually started with that. But it doesn't seem to help.
Even though it successfully goes back to the login url, the history still exists.

Also tried `history.go(-(history.length - 1))` to move out of appsmith, but the result is same. Since the tab is still open the history persists.

https://www.loom.com/share/06243c58335f4ccf90588b37f604ff45

2023-03-07 06:06 UTC, eco-monk commented on app/client/src/ce/sagas/userSagas.tsx
> +      yield put(flushErrorsAndRedirect(redirectURL || AUTH_LOGIN_URL, true));
Hence I thought we'll close the tab instead.

2023-03-07 06:18 UTC, eco-monk commented on app/client/src/ce/sagas/userSagas.tsx
> +      yield put(flushErrorsAndRedirect(redirectURL || AUTH_LOGIN_URL, true));
As an alternative,
Perhaps we can restrict going back from signin page?
Instead of looking to clear history.

2023-03-07 12:37 UTC, eco-monk commented on app/client/src/ce/sagas/userSagas.tsx
> +      yield put(flushErrorsAndRedirect(redirectURL || AUTH_LOGIN_URL, true));
Using alternate approach to prevent back button instead of opening a new tab

2023-03-07 12:38 UTC, eco-monk commented
/ok-to-test

2023-03-07 13:14 UTC, akash-codemonk commented on app/client/src/ce/sagas/userSagas.tsx
> +      yield put(flushErrorsAndRedirect(redirectURL || AUTH_LOGIN_URL, true));
Is it possible to clear history from the browser programmatically? Also I didn't get what Id's are sensitive in the url that we have to clear. Is it page id, app id etc? Also other apps don't clear anything in history I think for e.g notion post signout it momentarily show the page name and id, either ways this can seen from the browser history.

2023-03-07 13:22 UTC, eco-monk commented
Note: need to account for redirections specific to EE repo (if any)

2023-03-08 05:32 UTC, hetunandu approved these changes

2023-03-08 05:45 UTC, eco-monk commented
/ok-to-test

2023-03-09 11:45 UTC, eco-monk commented
/ok-to-test

2023-03-10 03:03 UTC, eco-monk commented
/build-deploy-preview

2023-03-10 05:48 UTC, hetunandu approved these changes

2023-03-14 04:59 UTC, Richarex commented
Verified this on DP url, working as expected. There are few issues with the button widget added in this bug id [#406](https://github.com/appsmithorg/design-system/issues/406)

2023-03-14 05:06 UTC, eco-monk commented
Discussion on why DP flow is different:
https://theappsmith.slack.com/archives/CGBPVEJ5C/p1678694313317649

2023-03-14 05:28 UTC, Aishwarya-U-R commented
/ci-merge-check

2023-03-14 05:33 UTC, merged