Bugfix/binding success event
appsmithorg/appsmith pull request #21227
Opened 2023-03-07 10:36 UTC by Druthi

## Description
Adding another event called WIDGET_BINDING_SUCCESS which is fired whenever there is a successful binding created by the user. The BINDING_SUCCESS event was firing more events than actual binding and therefore we created a new event to capture the right data. 

Fixes #20468 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manual

### Test Plan
> Add Testsmith test cases links that relate to this PR

### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)

## Checklist:
### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2023-03-07 10:38 UTC, Druthi commented
/ok-to-test sha=69ecbe1

2023-03-07 10:39 UTC, Druthi commented
/build-deploy-preview

2023-03-07 11:43 UTC, Druthi commented
/build-deploy-preview

2023-03-07 12:15 UTC, ApekshaBhosale requested changes

2023-03-07 12:15 UTC, ApekshaBhosale commented on app/client/src/selectors/dataTreeSelectors.ts
> +export const getEvaluationSuccessfulBindindsMap = (state: AppState) =>
do we need to save this in reducers? @Druthi

2023-03-07 12:15 UTC, ApekshaBhosale commented on app/client/src/reducers/evaluationReducers/successfulBindingsReducer.ts
> +}
why do we need this?

2023-03-07 13:30 UTC, Druthi commented on app/client/src/selectors/dataTreeSelectors.ts
> +export const getEvaluationSuccessfulBindindsMap = (state: AppState) =>
How do we save it then to consume for the next evaluation cycle?

2023-03-08 06:42 UTC, Druthi commented
/ok-to-test sha=5b56ec9

2023-03-09 05:20 UTC, Druthi commented
/build-deploy-preview

2023-03-09 09:54 UTC, Druthi commented
/build-deploy-preview env=release

2023-03-13 09:36 UTC, Rishabh-Rathod commented on app/client/src/sagas/PostEvaluationSagas.ts
> +  }
Will there be a use case where we need to generate multiple instances of the class? 
If not in that case, why not create a class with static methods and directly consume `SuccessfulBindingMap.set()` and `SuccessfulBindingMap.get()`?

2023-03-13 09:38 UTC, Rishabh-Rathod commented on app/client/src/sagas/PostEvaluationSagas.ts
> +  const successfulBindingPaths: any = !successfulBindingsMap
```suggestion
  const successfulBindingPaths: unknown = !successfulBindingsMap
```

2023-03-13 10:07 UTC, Druthi commented
/ok-to-test sha=31efbc9

2023-03-13 10:09 UTC, Druthi commented
/build-deploy-preview

2023-03-13 11:38 UTC, Druthi commented
/ok-to-test sha=f05aa8e

2023-03-13 11:38 UTC, Druthi commented
/build-deploy-preview

2023-03-14 05:28 UTC, Druthi commented
/build-deploy-preview env=release

2023-03-14 09:37 UTC, Druthi commented
Updated DP: https://appsmith-q26b6hggx-get-appsmith.vercel.app/applications

2023-03-21 03:43 UTC, Druthi commented
/ok-to-test sha=6dc15c2

2023-03-21 03:43 UTC, Druthi commented
/build-deploy-preview env=release

2023-03-21 06:34 UTC, ApekshaBhosale requested changes

2023-03-21 06:34 UTC, ApekshaBhosale commented on app/client/src/sagas/PostEvaluationSagas.ts
> +  const successfulBindingPaths: any = !successfulBindingsMap
did you add type here?

2023-03-21 07:28 UTC, Druthi commented
/build-deploy-preview env=release

2023-03-21 07:33 UTC, Druthi commented
/ok-to-test sha=b4acace

2023-03-21 07:45 UTC, ApekshaBhosale approved these changes

2023-03-21 07:45 UTC, Druthi commented
/ok-to-test sha=b825ef6

2023-03-21 08:22 UTC, Druthi commented
/ok-to-test sha=ffeff70

2023-03-23 09:58 UTC, Druthi commented
/ok-to-test sha=9b3efc5

2023-03-24 06:05 UTC, shwetha-ramesh commented
Working as expected. Moving to Done.

2023-03-24 07:28 UTC, ApekshaBhosale approved these changes

2023-03-24 07:39 UTC, Aishwarya-U-R commented
/ci-merge-check

2023-03-24 07:41 UTC, KelvinOm commented
Please update the branch from the release, it is necessary for the added checks in the release to start working.

2023-03-24 07:45 UTC, Druthi commented
/ok-to-test sha=e4412de

2023-03-24 10:15 UTC, merged