fix: listwidget in formwidget
appsmithorg/appsmith pull request #21234
Opened 2023-03-07 11:40 UTC by Tooluloope

## Description

The list widget should be visible in the Form widget.
Also, updatePageNo shouldn't be called recursively when the List widget Height is adjusted.

Fixes #21113 

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manual

### Test Plan
> Add Testsmith test cases links that relate to this PR

### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)

## Checklist:
### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2023-03-07 11:44 UTC, Tooluloope commented
/ok-to-test sha=e7dd641

2023-03-07 11:45 UTC, Tooluloope commented
/build-deploy-preview sha=e7dd641

2023-03-08 04:50 UTC, ashit-rath commented on app/client/src/utils/widgetRenderUtils.tsx
> +    ...["hasMetaWidgets", "requiresFlatWidgetChildren"],
Can we add these to `additionalStaticProps`? let's not have keys like this, it doesn't give any context

2023-03-08 04:50 UTC, ashit-rath commented on app/client/src/widgets/ListWidgetV2/widget/index.tsx
> +  updatePageSize = throttle(
Is this the final solution we are proposing? Were you able to find out which PR caused this?

2023-03-08 12:49 UTC, Tooluloope commented on app/client/src/utils/widgetRenderUtils.tsx
> +    ...["hasMetaWidgets", "requiresFlatWidgetChildren"],
We could use DSL_STRUCTURE_PROPS.

2023-03-08 12:51 UTC, Tooluloope commented on app/client/src/widgets/ListWidgetV2/widget/index.tsx
> +  updatePageSize = throttle(
Yeah, I messaged @prsidhu concerning the issue, as I could pinpoint the problem only on this branch https://github.com/appsmithorg/appsmith/pull/21151. He's looking into it, but we can go with this for now.

2023-03-08 13:17 UTC, ashit-rath commented on app/client/src/widgets/ListWidgetV2/widget/index.tsx
> +  updatePageSize = throttle(
So this is a temporary fix?
Is 2000 too much for this and should we have leading true than trailing true?

2023-03-08 14:19 UTC, Tooluloope commented on app/client/src/widgets/ListWidgetV2/widget/index.tsx
> +  updatePageSize = throttle(
I tried using 200. It was called four times, so I settled with 500ms. Also, read and tested out
1. Trailing and leading => true 
2. Trailing -> true, Leading -> false
3. leading -true, trailing -> false

They were all called twice. Since it would be called at the beginning of throttling, all subsequent calls would be merged into one after the 500ms.

2023-03-09 08:05 UTC, kamakshibhat-appsmith commented
the page becomes unresponsive when we increase the size of list item container inside form with SSP on. [LOOM](https://www.loom.com/share/548530aaa0eb45bf9072f93b32890a67)

2023-03-09 13:02 UTC, kamakshibhat-appsmith commented
https://github.com/appsmithorg/appsmith/pull/21234#issuecomment-1461520291
EDIT :the page becomes unresponsive when we increase the size of list item container inside form/Modal/Tab/List with SSP on. [LOOM](https://www.loom.com/share/548530aaa0eb45bf9072f93b32890a67)
@Tooluloope

2023-03-09 20:17 UTC, Tooluloope commented
/ok-to-test sha=d5e390b

2023-03-09 20:40 UTC, Tooluloope commented
/ok-to-test sha=81dc790

2023-03-10 06:11 UTC, Tooluloope commented
/ok-to-test sha=4ab3953

2023-03-10 06:11 UTC, Tooluloope commented
/build-deploy-preview sha=4ab3953

2023-03-10 07:54 UTC, kamakshibhat-appsmith commented
LGTM !!

2023-03-10 09:27 UTC, marks0351 requested changes

2023-03-10 09:27 UTC, marks0351 commented on app/client/src/utils/widgetRenderUtils.tsx
> +    ...Object.keys({ ...WIDGET_STATIC_PROPS, ...WIDGET_DSL_STRUCTURE_PROPS }),
Why do we need this change?

2023-03-10 09:39 UTC, Tooluloope commented on app/client/src/utils/widgetRenderUtils.tsx
> +    ...Object.keys({ ...WIDGET_STATIC_PROPS, ...WIDGET_DSL_STRUCTURE_PROPS }),
Yeah, it's for the Form Widget.
I think I need to add some code comments there.

2023-03-10 11:13 UTC, merged