feature: Introduce Oracle Integration behind feature flag
appsmithorg/appsmith pull request #21273
Opened 2023-03-08 22:48 UTC by sumitsum

## Description
- This PR introduces Oracle integration behind a feature flag. Currently, the feature is only enabled for Appsmith and Moolya users. 
  - The entire feature will be shipped in chunks behind this feature flag.
- This PR introduces the following items:
  - Migration for Oracle plugin
  - Datasource and query execution forms
  - Datasource connection and validation
  - Core query execution flow
  - Usage of UQI data storage path
- The following pending items will be taken up immediately after this PR before the feature flag is removed:
  - Smart substitution
  - Use the new error framework
  - Better support for the following data types: json, array, local timestamp, blob, clob, interval
  - Get DB structure + query templates
  - JUnit TC
- As per discussion with Manish , no special changes should be required to support multiple envs feature. 
- Thanks to @ahmediqbal3012 for contributing the initial draft of the PR. 

Fixes #21274 #21275 

## Type of change
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
- Manual

### Test Plan
> Add Testsmith test cases links that relate to this PR

### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)

## Checklist:
### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2023-03-09 11:03 UTC, sneha122 commented
Client Side changes LGTM

2023-03-10 04:31 UTC, subrata71 requested changes

2023-03-13 05:43 UTC, sumitsum commented on app/server/appsmith-plugins/oraclePlugin/src/main/java/com/external/plugins/utils/OracleDatasourceUtils.java
> +            );
Hi Subrata, as mentioned in the description section, this change will be picked as part of a separate PR.

2023-03-13 05:45 UTC, sumitsum commented on app/server/appsmith-plugins/oraclePlugin/src/main/java/com/external/plugins/OraclePlugin.java
> +                        }
Hi Subrata, as mentioned in the description section, this change will be picked as part of a separate PR, before the feature flag is removed.

2023-03-13 05:45 UTC, sumitsum commented on app/server/appsmith-plugins/oraclePlugin/src/main/java/com/external/plugins/OraclePlugin.java
> +                                        mustacheValuesInOrder,
Hi Subrata, as mentioned in the description section, this change will be picked as part of a separate PR, before the feature flag is removed.

2023-03-13 05:50 UTC, subrata71 commented on app/server/appsmith-plugins/oraclePlugin/src/main/java/com/external/plugins/utils/OracleDatasourceUtils.java
> +            );
Sounds good then

2023-03-13 11:13 UTC, sumitsum commented on app/server/appsmith-plugins/oraclePlugin/src/main/java/com/external/plugins/OraclePlugin.java
> +                                query +
Done.

2023-03-13 11:14 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/featureflags/FeatureFlagEnum.java
> +    ORACLE_PLUGIN,
Hi Subrata, thanks for pointing this out. I have added a feature flag check in the datasource creating flow now, so the Oracle datasource creation will only be allowed if the feature flag is enabled.

2023-03-13 11:32 UTC, subrata71 commented on app/server/appsmith-plugins/oraclePlugin/src/main/java/com/external/plugins/OraclePlugin.java
> +                                query +
It would have been great if you make it get rid of the way to concatenate strings in the logs using `+`. It's more manageable if you use the `{}` placeholders like below:

```
log.debug("{}: Before executing oracle query [{}] Hikari Pool stats : active - {}, idle - {}, awaiting - {}, total - {}",
   Thread.currentThread().getName(),
   activeConnections,
   idleConnections,
   threadsAwaitingConnection,
   totalConnections
);
```

2023-03-13 11:39 UTC, sumitsum commented on app/server/appsmith-plugins/oraclePlugin/src/main/java/com/external/plugins/OraclePlugin.java
> +                                query +
Done

2023-03-13 11:41 UTC, sumitsum commented
/ok-to-test sha=018aba7

2023-03-13 11:43 UTC, subrata71 commented on app/server/appsmith-plugins/oraclePlugin/src/main/java/com/external/plugins/OraclePlugin.java
> +                                    threadsAwaitingConnection, totalConnections);
More arguments provided (5) than placeholders specified (4). Can you please also convert the other logs in this format?

2023-03-13 11:43 UTC, subrata71 commented on app/server/appsmith-plugins/oraclePlugin/src/main/java/com/external/plugins/OraclePlugin.java
> +                                threadsAwaitingConnection, totalConnections);
More arguments provided (5) than placeholders specified (4). Can you please also convert the other logs in this format?

2023-03-13 11:47 UTC, sumitsum commented on app/server/appsmith-plugins/oraclePlugin/src/main/java/com/external/plugins/OraclePlugin.java
> +                                    threadsAwaitingConnection, totalConnections);
Hi Subrata, thanks for catching this. I have updated it now with an extra placeholder.

2023-03-13 11:47 UTC, sumitsum commented on app/server/appsmith-plugins/oraclePlugin/src/main/java/com/external/plugins/OraclePlugin.java
> +                                threadsAwaitingConnection, totalConnections);
Hi Subrata, thanks for catching this. I have updated it now with an extra placeholder.

2023-03-13 11:51 UTC, subrata71 approved these changes

2023-03-13 11:53 UTC, sumitsum commented
/ok-to-test sha=d104e0b

2023-03-14 10:11 UTC, sumitsum commented
/ok-to-test sha=62e316f

2023-03-15 10:38 UTC, sumitsum commented
/ok-to-test sha=a850a3a

2023-03-15 11:39 UTC, sumitsum commented
/ok-to-test sha=e62d0a1

2023-03-15 11:59 UTC, subrata71 commented on app/server/appsmith-server/src/test/java/com/appsmith/server/services/DatasourceServiceTest.java
> +                            Workspace org = tuple2.getT1();
Nitpick: AFAIK, workspace replaces organization. The variable name here just drew my attention. 
I would prefer `Workspace workspace` to Workspace org`.

2023-03-15 14:37 UTC, sumitsum commented on app/server/appsmith-server/src/test/java/com/appsmith/server/services/DatasourceServiceTest.java
> +                            Workspace org = tuple2.getT1();
Done.

2023-03-15 14:43 UTC, sumitsum commented
/ok-to-test sha=b65fa66

2023-03-16 02:25 UTC, sumitsum commented
/ok-to-test sha=e490a7c

2023-03-16 11:24 UTC, merged