fix: Selected Widget Visibility
appsmithorg/appsmith pull request #21317
Opened 2023-03-10 07:10 UTC by hetunandu

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.

## Description

> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change
> Links to Notion, Figma or any other documents that might be relevant to the PR

> Add a TL;DR when description is extra long (helps content team)

Fixes # (issue)
> if no issue exists, please create an issue and ask the maintainers about this first

Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update

## How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.
> Delete anything that is not important

- Manual
- Jest
- Cypress

### Test Plan
> Add Testsmith test cases links that relate to this PR

### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)

## Checklist:
### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2023-03-10 07:13 UTC, hetunandu commented
/ok-to-test sha=2c66c85

2023-03-13 05:59 UTC, hetunandu commented
/build-deploy-preview env=release

2023-03-13 10:49 UTC, hetunandu commented
/ok-to-test sha=0bbfaa0

2023-03-13 11:02 UTC, hetunandu commented
/ok-to-test sha=2a17fe9

2023-03-13 11:21 UTC, hetunandu commented
/ok-to-test sha=219c678

2023-03-14 05:56 UTC, hetunandu commented
/ok-to-test sha=f5d6ea7

2023-03-14 05:57 UTC, hetunandu commented
/build-deploy-preview env=release

2023-03-14 08:29 UTC, hetunandu commented
/ok-to-test sha=c0c396e

2023-03-15 05:23 UTC, ashit-rath commented on app/client/src/widgets/TabsWidget/widget/index.tsx
> +        )?.widgetId ?? this.props.selectedTabWidgetId;
Not 100% sure but this may cause some problems in certain widget operation and auto height.

Here we are trying to derive the selectedTabWidgetId from either the meta prop `selectedTabWidgetId` or the `ancestry`. While this is fine in the context of Tabs widget rendering, there are other places where certain operations depend on the meta value `selectedTabWidgetId`.

We should set the `selectedTabWidgetId` meta value probably onMount.

2023-03-15 05:23 UTC, ashit-rath commented on app/client/src/sagas/ModalSagas.ts
Now when the `isVisible` property is not a factor for the modal's open/close state. Are we suppose to update the logic of `closeModalSaga` as well?

2023-03-15 05:23 UTC, ashit-rath commented on app/client/src/sagas/ModalSagas.ts
We should also look at 
`generateWidgetProps` in `WidgetPropsUtils.tsx`
default value of isVisible in `src/widgets/ModalWidget/index.ts`
assignment of widgetProps.isVisible in `withWIdgetProps`. We so not need to check for MODAL WIDGET.

2023-03-15 11:24 UTC, hetunandu commented
/ok-to-test sha=682e63b

2023-03-15 12:56 UTC, hetunandu commented on app/client/src/widgets/TabsWidget/widget/index.tsx
> +        )?.widgetId ?? this.props.selectedTabWidgetId;
Can you point out how I can check this?

The main goal of this change it to do it without updating the meta value of the tabs widget since it can be controlled by the developer user / end user

2023-03-15 13:06 UTC, hetunandu commented on app/client/src/widgets/TabsWidget/widget/index.tsx
> +const mapDispatchToProps = (state: AppState) => ({
Good point! I totally missed the withWidgetProps ability to pass in props. Updated the code

2023-03-15 13:27 UTC, ashit-rath commented on app/client/src/widgets/withWidgetProps.tsx
> +    const selectedWidgetAncestry = useSelector(getSelectedWidgetAncestry);
I think this may cause perf regression. Since all widgets have now subscribed to this selector, any time we click a widget; all the other widgets will receive this update even if it may not be relevant to that widget.

I think if we abstract the logic of the use of `selectedWidgetAncestry` in the `withWidgetProps` by doing something like 
```
// get only the bool value
const isWidgetPresentInSelectedAncestry = useAncestryHook()
```
We can save un-necessary re-renders.

That being said, we also need to pass `selectedWidgetAncestry` as prop to widget but not all widgets require this. So we can do a similar treatment `childWidgets` or `flattenedChildCanvasWidgets`

2023-03-15 13:27 UTC, riodeuno commented on app/client/src/widgets/TabsWidget/widget/index.tsx
> +        )?.widgetId ?? this.props.selectedTabWidgetId;
@ashit-rath Yes, we're relying on the `selectedTabWidgetId` for computations in auto height. The reason behind is that we need to make sure that we're computing the height of the tabs widget based on the currently selected tab. Here is a function which does this: https://github.com/appsmithorg/appsmith/blob/bc431d01629995b9f5f667da91f514b036f4e525/app/client/src/sagas/autoHeightSagas/helpers.ts#L36

If meta property is not the way to get this, we can always update this function to use the logic you've described. 
We could potentially add this logic into the widget configuration. We don't have the option of getting any "derived props" which have nothing to do with evaluations for widgets. The idea would be that we add a widget configuration that is a function to compute this. The function can probably be run in the `withWidgetProps` and the same configuration function can be used in the `helper.ts` I've linked to in this comment.

An example of this configurations could be something like this: https://github.com/appsmithorg/appsmith/blob/bc431d01629995b9f5f667da91f514b036f4e525/app/client/src/widgets/TabsWidget/index.ts#L22

2023-03-15 13:35 UTC, riodeuno commented on app/client/src/widgets/TabsWidget/widget/index.tsx
> +        )?.widgetId ?? this.props.selectedTabWidgetId;
Also, we have this being used in the paste workflow as well. However, this is a strange case. Any "selectable" widget's parent cannot be anything other than a canvas widget. So, this code flow doesn't seem to be doing what I think it is doing. https://github.com/appsmithorg/appsmith/blob/bc431d01629995b9f5f667da91f514b036f4e525/app/client/src/sagas/WidgetOperationUtils.ts#L459
If I am right, then it is possible that we can safely remove this reference. We just need to make sure of this.

2023-03-16 06:43 UTC, hetunandu commented
/build-deploy-preview env=release

2023-03-16 07:12 UTC, hetunandu commented
/ok-to-test sha=a78c111

2023-03-16 07:22 UTC, hetunandu commented on app/client/src/widgets/withWidgetProps.tsx
> +    const selectedWidgetAncestry = useSelector(getSelectedWidgetAncestry);
Updated code to make this only work for widgets with child widgets

2023-03-16 08:13 UTC, ashit-rath approved these changes

2023-03-16 10:57 UTC, hetunandu commented
/ok-to-test sha=3eb1887

2023-03-17 11:20 UTC, hetunandu commented
/build-deploy-preview env=release

2023-03-17 11:53 UTC, hetunandu commented
/ok-to-test sha=b375978

2023-03-22 06:16 UTC, marks0351 requested changes

2023-03-22 06:16 UTC, marks0351 commented on app/client/src/widgets/BaseWidget.tsx
> -        if (this.props.isVisible) {
@riodeuno isn't this change needed for hiding invisible widgets?

2023-03-22 06:16 UTC, marks0351 commented on app/client/src/widgets/withWidgetProps.tsx
> +      if (!WIDGETS_REQUIRING_SELECTED_ANCESTRY.includes(type)) return [];
please add {} for readability

2023-03-22 06:17 UTC, hetunandu commented on app/client/src/widgets/BaseWidget.tsx
> -        if (this.props.isVisible) {
This is already handled in withWidgetProps and hence not needed here

2023-03-22 06:34 UTC, marks0351 approved these changes

2023-03-22 06:36 UTC, hetunandu commented
/ok-to-test

2023-03-22 08:31 UTC, hetunandu commented
/ok-to-test

2023-03-23 04:14 UTC, hetunandu commented
/ok-to-test

2023-03-23 05:43 UTC, merged