ci: add comments for vercel-deploy-preview
appsmithorg/appsmith pull request #21349
Opened 2023-03-13 04:18 UTC by pratapaprasanna

2023-03-14 10:28 UTC, sharat87 commented on .github/workflows/on-demand-build-docker-image-deploy-preview.yml
> +    if: success()
Do we want to push the image for this case now? Deployment happens on Vercel if `env == release`, no?

2023-03-14 10:28 UTC, sharat87 commented on .github/workflows/on-demand-build-docker-image-deploy-preview.yml
> +      github.event.client_payload.slash_command.args.named.env != 'prod'
Are we supporting `env=prod` here?

2023-03-15 06:35 UTC, sharat87 commented on scripts/deploy_preview.sh
> +export DB_URL=$DB_URL
I don't think this is needed. None of the commands need these env variables, right? We just need them for interpolation in arguments. That'll work without this too.

```suggestion
```

2023-03-15 06:35 UTC, sharat87 commented on scripts/deploy_preview.sh
> +  --set applicationConfig.APPSMITH_MONGODB_URI="mongodb+srv://$DB_USERNAME:$DB_PASSWORD@$DB_URL/$DBNAME?retryWrites=true&minPoolSize=1&maxPoolSize=10&maxIdleTimeMS=900000&authSource=admin" \
This is using `DBNAME` env variable, but in the workflow, we aren't setting it. Instead, we are setting `DB_URL`. Is that okay?

2023-03-15 10:06 UTC, pratapaprasanna commented on scripts/deploy_preview.sh
> +export DB_URL=$DB_URL
main intention is keep track of variables and nothing more

2023-03-15 10:06 UTC, pratapaprasanna commented on scripts/deploy_preview.sh
> +  --set applicationConfig.APPSMITH_MONGODB_URI="mongodb+srv://$DB_USERNAME:$DB_PASSWORD@$DB_URL/$DBNAME?retryWrites=true&minPoolSize=1&maxPoolSize=10&maxIdleTimeMS=900000&authSource=admin" \
My bad

2023-03-15 15:42 UTC, sharat87 requested changes

2023-03-15 15:42 UTC, sharat87 commented on scripts/deploy_preview.sh
> +export DBNAME =ce"$PULL_REQUEST_NUMBER"
Syntax error. 🙂

```suggestion
export DBNAME=ce"$PULL_REQUEST_NUMBER"
```

2023-03-16 10:34 UTC, sharat87 approved these changes

2023-03-16 12:02 UTC, merged