chore: sentry issue - add null checks for datatree
appsmithorg/appsmith pull request #21358
Opened 2023-03-13 09:16 UTC by eco-monk

## Description

add null checks for datatree

Fixes #21308

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Cypress

### Test Plan
> Add Testsmith test cases links that relate to this PR

### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)

## Checklist:
### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2023-03-13 09:21 UTC, eco-monk commented
/ok-to-test

2023-03-13 12:47 UTC, eco-monk commented
/ok-to-test

2023-03-14 05:03 UTC, hetunandu requested changes
Improve check

2023-03-14 05:03 UTC, hetunandu commented on app/client/src/selectors/navigationSelectors.ts
> +      const result = dataTree && getActionChildrenNavData(action, dataTree);
Why are we not checking for dataTree once in the beginning itself?

2023-03-14 05:14 UTC, eco-monk commented on app/client/src/selectors/navigationSelectors.ts
> +      const result = dataTree && getActionChildrenNavData(action, dataTree);
I did think about it. But the dataTree is used only when creating navData for children of entities.

Top level entities get their navigation config regardless. Because, we rely on state from `getActions`, `getWidgets` etc...

2023-03-14 05:16 UTC, eco-monk commented on app/client/src/selectors/navigationSelectors.ts
> +      const result = dataTree && getActionChildrenNavData(action, dataTree);
This makes sure top level entities to get their navigation data regardless of whether dataTree / child nav data is available.

2023-03-14 05:19 UTC, eco-monk commented
/ok-to-test

2023-03-14 06:19 UTC, hetunandu commented on app/client/src/selectors/navigationSelectors.ts
> +      const result = dataTree && getActionChildrenNavData(action, dataTree);
The only time dataTree is not available is during initialisation. At this time, code editor is not usable anyways. By moving the check, the code becomes cleaner.

Another problem with this check is if dataTree is not available the result will be `undefined` which can cause other problems down the call stack. A top level check and return of empty object will ensure a standard output from the function

2023-03-14 06:26 UTC, hetunandu approved these changes

2023-03-14 06:28 UTC, eco-monk commented
/ok-to-test

2023-03-14 07:22 UTC, eco-monk commented
On Hold. Tests haven't run since, Server build is failing.
https://theappsmith.slack.com/archives/CGBPVEJ5C/p1678778487478079?thread_ts=1678772770.087069&cid=CGBPVEJ5C

2023-03-14 08:33 UTC, eco-monk commented
/ok-to-test

2023-03-16 00:50 UTC, merged