fix: fetch gsheet project id from cs added
appsmithorg/appsmith pull request #21361
Opened 2023-03-13 10:17 UTC by sneha122

## Description

File picker implementation for Limiting Gsheet Access requires google sheet project id. The changes in this PR gets the gsheet project id from cloud-services and returns it back to client. Client then uses this project id to open file picker and select required files.

Fixes https://github.com/appsmithorg/appsmith/issues/21298

Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manual

### Test Plan
> Add Testsmith test cases links that relate to this PR

### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)

## Checklist:
### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2023-03-13 10:19 UTC, sneha122 commented
/ok-to-test

2023-03-13 10:22 UTC, sneha122 commented
/build-deploy-preview

2023-03-13 12:44 UTC, sneha122 commented
/ok-to-test

2023-03-13 14:05 UTC, sumitsum requested changes

2023-03-13 14:05 UTC, sumitsum commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/AuthenticationResponse.java
> +    String projectID;
Is `projectID` something that we want to store as encrypted on the DB ? If so, we should use @Encrypted annotation for it.

2023-03-13 14:46 UTC, sneha122 commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/AuthenticationResponse.java
> +    String projectID;
there is no need to store projectID on DB as we are fetching it on demand and its the same for all datasources, so should I add Transient annotation instead so we do not save it in DB at all? Also in that case @encrypted is required?

2023-03-13 14:50 UTC, sumitsum requested changes

2023-03-13 14:50 UTC, sumitsum commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/AuthenticationResponse.java
> +    String projectID;
Agree, let us mark it as @Transient

2023-03-13 14:50 UTC, sumitsum commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/AuthenticationResponse.java
> +    String projectID;
Also, can you please mention a comment here saying that this field is not something that is returned as a response from the authorization server but it is something that the cloud service is providing.

2023-03-13 14:54 UTC, sneha122 commented
`Also, should we rename it to projectIDPrefix as I am assuming it is not the full project id but only the prefix part of it ?` - Project ID is the prefix part of client Id, essentially it already is a prefix @sumitsum

2023-03-13 14:56 UTC, sneha122 commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/AuthenticationResponse.java
> +    String projectID;
ProjectID is prefix part of clientId so it already is a prefix.

2023-03-14 06:12 UTC, sneha122 commented
/ok-to-test

2023-03-14 06:16 UTC, sumitsum commented
Server side changes LGTM.

2023-03-14 09:24 UTC, sneha122 commented
/ok-to-test

2023-03-16 06:46 UTC, Irongade approved these changes
Generally, I'd like to encourage you to add more comments in your code. Especially for new features, this will help you and anyone else looking into this in the future.

2023-03-16 07:05 UTC, sneha122 commented
> Generally, I'd like to encourage you to add more comments in your code. Especially for new features, this will help you and anyone else looking into this in the future.

Thanks @Irongade for the feedback!! Usually I add comments in the hard to understand areas, but is there any guidelines that you follow for comments?

2023-03-16 12:13 UTC, sumitsum submitted a review, later dismissed

2023-03-17 06:04 UTC, sneha122 commented
The code review is done for this but keeping it in code review pipeline because in order to move this to needs QA, cs PR needs to be merged, and code review for that is pending as of now

2023-03-17 10:43 UTC, sneha122 commented
/build-deploy-preview

2023-03-20 07:08 UTC, sneha122 commented
/build-deploy-preview

2023-03-20 07:53 UTC, sneha122 commented
/ok-to-test

2023-03-20 08:03 UTC, Irongade submitted a review, later dismissed

2023-03-20 08:33 UTC, sneha122 commented
/build-deploy-preview

2023-03-20 10:10 UTC, sneha122 commented
/build-deploy-preview

2023-03-20 13:16 UTC, sneha122 commented
/ok-to-test

2023-03-21 05:45 UTC, sumitsum approved these changes

2023-03-21 05:46 UTC, sneha122 commented
/build-deploy-preview

2023-03-21 07:18 UTC, sneha122 commented
This PR cannot be tested on DP, as DP generated with `build-deploy-preview` does not have cloud-services configured correctly. Hence as per this [thread](https://theappsmith.slack.com/archives/C04Q58L86RW/p1679318148732489), we have decided to merge the PR and test the changes on release. CC: @prapullac @rohan-arthur

2023-03-21 07:21 UTC, prapullac commented
As per above comment adding the label.

2023-03-21 07:23 UTC, merged