feat: deduplicate button and icon
appsmithorg/appsmith pull request #21375
Opened 2023-03-13 16:48 UTC by tanvibhakta

## Description

We have buttons that look nice and rounded and pass contrast tests. We also only have 4 types of them, and they don't arbitrarily fill the screen according to a designer's whim's and fancies. Buttons stay strictly around their content now. Their content is also improved - no more yelling, we just capitalize the first letter of the word. 

Fixed so far:
1. All usages of ds-old buttons
2. All usages of ds-old icons
3. Several usages of ds-old icon with an onClick have become a ds Button
4. Several  radix icons and html buttons have become ds Icons and ds Buttons
5. A few blueprint Icons have become ds Icons
6. All form icons have become regular icons 
7. All menu icons have become regular icons 
8. All help icons have become regular icons 

## Type of change
- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

## How Has This Been Tested?

This PR will not be tested individually. They will be tested as part of screen testing and regressions. 

### Test Plan

### Issues raised during DP testing

## Checklist:
### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2023-03-17 01:20 UTC, tanvibhakta commented
/build-deploy-preview

2023-03-17 01:23 UTC, tanvibhakta commented
/build-deploy-preview

2023-03-17 02:32 UTC, tanvibhakta commented
/build-deploy-preview

2023-03-20 09:31 UTC, tanvibhakta commented
/build-deploy-preview

2023-03-20 13:27 UTC, tanvibhakta commented
/build-deploy-preview

2023-03-21 03:26 UTC, tanvibhakta commented
/build-deploy-preview

2023-03-21 05:10 UTC, tanvibhakta commented
/build-deploy-preview

2023-03-21 07:18 UTC, tanvibhakta commented
/ok-to-test sha=f4985a6

2023-03-23 15:26 UTC, tanvibhakta commented
/build-deploy-preview

2023-03-24 01:33 UTC, tanvibhakta commented
/ok-to-test sha=2b0e40a7bdceb7b31a283173245efea4857e9d8a

2023-03-24 01:33 UTC, tanvibhakta commented
/build-deploy-preview

2023-03-24 04:48 UTC, tanvibhakta commented
/build-deploy-preview

2023-03-24 04:49 UTC, tanvibhakta commented
/ok-to-test sha=94c5b904d9f6edca15d3ed7b677c66b0485f21a5

2023-03-27 11:57 UTC, tanvibhakta commented
/ok-to-test sha=e8d7394

2023-03-27 19:19 UTC, albinAppsmith commented on app/client/src/components/editorComponents/Debugger/ContextualMenu.tsx
> +import { Classes, Text, FontWeight, TextType } from "design-system-old";
Why this import?

2023-03-27 19:20 UTC, albinAppsmith commented on app/client/src/components/editorComponents/Debugger/DebugCTA.tsx
> +        <Button kind="secondary" size="sm" startIcon="down-arrow">
Isn't it supposed to be end button?

2023-03-27 19:24 UTC, albinAppsmith commented on app/client/src/components/propertyControls/KeyValueComponent.tsx
> +              // onClick={() => deletePair(index, e.hasOwnProperty("detail"))}
Commented onClick?

2023-03-27 19:24 UTC, albinAppsmith commented on app/client/src/components/propertyControls/KeyValueComponent.tsx
> +        onClick={() => addPair}
Why anonymous function required here?

2023-03-28 03:59 UTC, tanvibhakta commented on app/client/src/components/propertyControls/KeyValueComponent.tsx
> +        onClick={() => addPair}
Because the type signature is incorrect otherwise.

2023-03-28 06:27 UTC, tanvibhakta commented on app/client/src/components/editorComponents/Debugger/ContextualMenu.tsx
> +import { Classes, Text, FontWeight, TextType } from "design-system-old";
They were two different imports and I combined it into one line.

2023-03-28 06:33 UTC, tanvibhakta commented on app/client/src/components/propertyControls/KeyValueComponent.tsx
> +        onClick={() => addPair}
The type signature error was when this was an onPress, I've fixed this now.

2023-03-28 06:33 UTC, tanvibhakta commented on app/client/src/components/propertyControls/KeyValueComponent.tsx
> +              // onClick={() => deletePair(index, e.hasOwnProperty("detail"))}
fixed.

2023-03-28 09:16 UTC, albinAppsmith commented
/build-deploy-preview

2023-03-29 05:11 UTC, albinAppsmith commented
/build-deploy-preview

2023-03-29 06:04 UTC, albinAppsmith requested changes
Revert widget changes

2023-03-29 07:35 UTC, albinAppsmith commented
/build-deploy-preview

2023-03-29 08:12 UTC, albinAppsmith commented
/build-deploy-preview

2023-03-29 08:48 UTC, albinAppsmith commented
/build-deploy-preview

2023-03-29 22:28 UTC, albinAppsmith commented
/build-deploy-preview

2023-03-29 22:58 UTC, albinAppsmith commented
/build-deploy-preview

2023-03-30 12:04 UTC, albinAppsmith commented
/build-deploy-preview

2023-03-30 12:32 UTC, albinAppsmith commented
/build-deploy-preview

2023-04-04 06:46 UTC, tanvibhakta commented
This branch has been merged into: https://github.com/appsmithorg/appsmith/pull/22030

2023-04-06 06:54 UTC, rohitagarwal88 commented
@albinAppsmith / @tanvibhakta : Is this PR still relevant?

2023-04-07 05:11 UTC, closed without merging