chore: Added tests for leave workspace flow
appsmithorg/appsmith pull request #21416
Opened 2023-03-15 05:13 UTC by nayan-rafiq

## Description

Added and updated tests for the leave workspace flow. 

Fixes # (issue)
> if no issue exists, please create an issue and ask the maintainers about this first

Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update

## How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.
> Delete anything that is not important

- Manual
- Jest
- Cypress

### Test Plan
> Add Testsmith test cases links that relate to this PR

### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)

## Checklist:
### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2023-03-15 05:14 UTC, nayan-rafiq commented
/ok-to-test sha=ddfa6e5

2023-03-15 05:58 UTC, nsarupr requested changes

2023-03-15 05:58 UTC, nsarupr commented on app/server/appsmith-server/src/test/java/com/appsmith/server/services/UserWorkspaceServiceTest.java
> +                })
Can you please add an assertion on `recentlyUserApplicationIds`?

2023-03-15 05:58 UTC, nsarupr commented on app/server/appsmith-server/src/test/java/com/appsmith/server/services/UserWorkspaceServiceTest.java
> +        myWorkspace.setName("Test org" + UUID.randomUUID());
Can you please use the same naming convention that you have used for the Application?

2023-03-15 09:41 UTC, nayan-rafiq commented on app/server/appsmith-server/src/test/java/com/appsmith/server/services/UserWorkspaceServiceTest.java
> +        myWorkspace.setName("Test org" + UUID.randomUUID());
Done

2023-03-15 09:41 UTC, nayan-rafiq commented on app/server/appsmith-server/src/test/java/com/appsmith/server/services/UserWorkspaceServiceTest.java
> +                })
Added

2023-03-15 09:41 UTC, nayan-rafiq commented
/ok-to-test sha=ce9fb6264301afec6ded408495ab3ddb5ca5df74

2023-03-15 10:25 UTC, nsarupr commented on app/server/appsmith-server/src/test/java/com/appsmith/server/services/UserWorkspaceServiceTest.java
> +                    assertThat(userData.getRecentlyUsedAppIds()).doesNotContain(application.getId());
```suggestion
                    assertThat(userData.getRecentlyUsedAppIds()).doesNotContain(savedApplication.getId());
```

2023-03-15 10:31 UTC, nayan-rafiq commented
/ok-to-test sha=06ec3b1

2023-03-15 11:13 UTC, nsarupr commented
/ok-to-test sha=ebcb0a0

2023-03-15 17:46 UTC, nayan-rafiq commented
/ok-to-test sha=6e271dd

2023-03-15 19:55 UTC, nayan-rafiq commented
/ci-merge-check

2023-03-16 05:00 UTC, nsarupr approved these changes
Looks good to me

2023-03-16 07:18 UTC, merged