feat: map of china added with mapchart
appsmithorg/appsmith pull request #21428
Opened 2023-03-15 09:48 UTC by qinjie1314520

This PR adds a new map of China to mapchart

## Description
Add China map to mapchart and provide more detailed description of map data fields, as shown in the figure below
![图片](https://user-images.githubusercontent.com/48704312/225271501-85eedc43-2d8d-4ec9-9483-d439eaf1d890.png)

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
- Manual

## Checklist:
### Dev activity
- [X] I My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2023-03-15 13:19 UTC, somangshu commented
/ok-to-test sha=3b6353a

2023-03-15 13:22 UTC, somangshu requested changes

2023-03-15 13:22 UTC, somangshu commented on app/client/src/widgets/MapChartWidget/constants.ts
> +export const dataSetForChina = [
We should shorten this data set and minify it as well maybe! This is increasing the build size for no reason!

2023-03-15 13:30 UTC, somangshu commented
/build-deploy-preview env=release

2023-03-16 06:24 UTC, somangshu approved these changes
LGTM

2023-03-16 06:25 UTC, somangshu commented
/build-deploy-preview env=release

2023-03-16 06:25 UTC, somangshu commented
/ok-to-test sha=ddd0b8c

2023-03-16 07:59 UTC, qinjie1314520 commented
I don't think I have anything to change. Maybe there are other things to change? Because there is "Some checks were not successful", this is my first time to contribute code, and I feel a little confused

2023-03-16 08:02 UTC, somangshu commented
@qinjie1314520 this is not related probably, I am trying to run the CI workflow, Ill let you know if there is anything related to your change!

2023-03-16 08:05 UTC, qinjie1314520 commented
I see. Thank you very much for your help. Thank you

2023-03-31 16:36 UTC, closed without merging