fix: performance improvements for js editor
appsmithorg/appsmith pull request #21492
Opened 2023-03-16 15:55 UTC by eco-monk

## Description

TL;DR performance improvements for js editor

- fix entityNavigationData generation (to prevent unnecessary component updates)
  - in codeEditor/index.ts (`addThisReference` was creating a new object everytime)
  - in navigationSelector.ts (use `getJSCollections` instead of `getJSCollectionsForCurrentPage`, which created a new object everytime, even if actions were not updated)
- combine markers for navigation and peek overlay to reduce the total number of markers
- clear and add marks for only the edited lines instead of the whole file

Note: once a js object is saved, it's still going to trigger a whole file clear and marking.
Because, it's an entity update which needs a whole refresh of the markers.

Fixes #21467

## Media
Case: Adding a blank space in js editor.

### Reduced un-necessary clears and marks:
#### Before: 
![image](https://user-images.githubusercontent.com/66776129/225681826-980e7ea6-5a9f-45ac-9de8-b6b5d73078d7.png)

####After:
![image](https://user-images.githubusercontent.com/66776129/225681997-064db06b-b208-4cdf-8ead-f67de8ea2d34.png)

---

### Reduced entity marker called count:
https://www.loom.com/share/23719f8dfde8457ea0a86f44500ec34a

---

### Reduced markers count:
#### Before:
![image](https://user-images.githubusercontent.com/66776129/225792984-1eb4082e-fbfe-4fa2-bad8-6797d7095673.png)

#### After:
![image](https://user-images.githubusercontent.com/66776129/225793028-04480724-8822-4934-8264-375ba7bd95cd.png)

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manual

### Test Plan
> Add Testsmith test cases links that relate to this PR

### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)

## Checklist:
### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2023-03-16 16:15 UTC, eco-monk commented
/ok-to-test

2023-03-20 06:12 UTC, eco-monk reviewed
Summary

2023-03-20 06:12 UTC, eco-monk commented on app/client/src/components/editorComponents/CodeEditor/MarkHelpers/bindingMarker.ts
Existing file split up,
No changes here.

2023-03-20 06:12 UTC, eco-monk commented on app/client/src/components/editorComponents/CodeEditor/MarkHelpers/entityMarker.ts
existing file split + changes.
Change commit [here](https://github.com/appsmithorg/appsmith/pull/21492/commits/71bbb17adb6b56d1b50f3a58b3e8b438de5047e2#diff-ff3b30c0a2202f90f94ff7a6ebccdd090cf40097b65d7b67098e4377cf1df619).

2023-03-20 06:12 UTC, eco-monk commented
/ok-to-test

2023-03-20 06:12 UTC, eco-monk commented
/build-deploy-preview

2023-03-20 06:24 UTC, hetunandu requested changes
Minor change request

2023-03-20 06:24 UTC, hetunandu commented on app/client/src/selectors/navigationSelectors.ts
> +    jsObjectName: string | undefined,
Except entity name here. You can choose to only check this in the JS Object loop

2023-03-20 06:24 UTC, hetunandu commented on app/client/src/selectors/navigationSelectors.ts
> +  getJSCollections, // don't use getJSCollectionsForCurrentPage (returns a new object everytime)
Comment should be part of the `getJSCollectionsForCurrentPage` selector

2023-03-20 06:24 UTC, hetunandu commented on app/client/src/components/editorComponents/CodeEditor/index.tsx
> +    props.isJSObject ? props.dataTreePath?.split(".")[0] : undefined,
pass the entity name every time

2023-03-20 07:01 UTC, eco-monk commented
/build-deploy-preview env=release

2023-03-20 07:01 UTC, eco-monk commented
/ok-to-test

2023-03-20 09:04 UTC, eco-monk commented
Pending QA verification.

2023-03-21 05:07 UTC, Richarex commented
Tested this on the DP url, working as expected.

2023-03-21 05:09 UTC, merged