fix: handle 413 errors on the client
appsmithorg/appsmith pull request #21565
Opened 2023-03-19 18:29 UTC by Irongade

This PR introduces client side error handling. Certain errors cannot be handled by the server for example, 413 errors (Content Too Large), this is because they get rejected by NGINX before it reaches the server code. Hence why they have to be fixed on the client side.

Fixes #20641

## Type of change

- Bug fix (non-breaking change which fixes an issue)

- Manual

## Checklist:
### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2023-03-19 18:31 UTC, Irongade commented
/ok-to-test sha=49957c1

2023-03-20 22:16 UTC, Irongade commented
/ok-to-test sha=c9933ea

2023-03-21 12:32 UTC, sneha122 commented on app/client/src/api/ApiUtils.ts
> +        errorType: "INTERNAL_ERROR",
Should we create enum for errorType?

2023-03-21 12:46 UTC, Irongade commented
/ok-to-test sha=1baf687

2023-03-21 12:55 UTC, sneha122 approved these changes

2023-03-22 05:27 UTC, ChandanBalajiBP requested changes
Sorry for the late review

2023-03-22 05:27 UTC, ChandanBalajiBP commented on app/client/src/api/ApiUtils.ts
> +        downstreamErrorCode: createMessage(APPSMITH_HTTP_ERROR_413),
Can we remove downstreamErrorCode and downstreamErrorMessage parameter as it is optional and this might mislead users as we are not connected downstream.

2023-03-22 13:45 UTC, btsgh commented
@Irongade - Would it be possible for you to  create a deploy preview for this issue so we could test it?

2023-03-22 18:39 UTC, Irongade commented
/build-deploy-preview env=release

2023-03-22 18:40 UTC, Irongade commented
/ok-to-test sha=6332c89

2023-03-22 18:40 UTC, Irongade commented on app/client/src/api/ApiUtils.ts
> +        downstreamErrorCode: createMessage(APPSMITH_HTTP_ERROR_413),
Resolved.

2023-03-22 18:55 UTC, Irongade commented
/ok-to-test sha=f8ea048

2023-03-22 18:58 UTC, Irongade commented
> Deploy-Preview-URL: https://appsmith-kb286luoc-get-appsmith.vercel.app

@btsgh @prapullac Kindly find the DP above.

2023-03-23 03:57 UTC, ChandanBalajiBP submitted a review, later dismissed
LGTM

2023-03-24 07:29 UTC, ChandanBalajiBP commented
/ok-to-test sha=f8ea048

2023-03-24 07:37 UTC, ChandanBalajiBP commented
/ok-to-test sha=b94b1a0

2023-03-27 04:02 UTC, Aishwarya-U-R commented
/ok-to-test sha=386a08c

2023-03-30 18:49 UTC, sum35h commented
/build-deploy-preview skip-tests=true

2023-03-31 09:19 UTC, Irongade commented
/ok-to-test sha=f341bd5

2023-03-31 09:22 UTC, ChandanBalajiBP approved these changes
LGTM!

2023-04-03 04:26 UTC, merged