fix: MongoDB Invalid DB Name Error Msg
appsmithorg/appsmith pull request #21599
Opened 2023-03-20 12:15 UTC by PiyushPushkar02

## Description

- This PR adds a check to throw a proper error if the default database name is empty and an invalid database name is provided in the authentication section for mongo db.
- Added JUnit test cases for the same. one for an invalid db name and one for a valid db name (Both with empty default db name)
- There is one more issue observed here which is not taken part in this ticket. When you try to save the mongo data source with the default database name and empty database name under auth section. Once you try to save the data source it will throw an internal server error. Created a ticket for the same: https://app.zenhub.com/workspaces/data-integration-pod-6322a759b3296d249ce5c4ed/issues/gh/appsmithorg/appsmith/21598

Fixes #12260 

## Type of change
- Bug Fix(non-breaking change which adds functionality)

## How Has This Been Tested?
- Manual
- JUnit TC added 

### **Checklist**:

- [x]  My code follows the style guidelines of this project
- [x]  I have performed a self-review of my own code
- [ ]  I have commented my code, particularly in hard-to-understand areas
- [ ]  I have made corresponding changes to the documentation
- [ ]  My changes generate no new warnings
- [x]  I have added tests that prove my fix is effective or that my feature works
- [x]  New and existing unit tests pass locally with my changes
- [ ]  PR is being merged under a feature flag

### **QA activity:**

- [ ]  Test plan has been approved by relevant developers
- [ ]  Test plan has been peer reviewed by QA
- [ ]  Cypress test cases have been added and approved by either SDET or manual QA
- [ ]  Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ]  Added Test Plan Approved label after reveiwing all Cypress test

2023-03-21 07:26 UTC, sumitsum requested changes

2023-03-21 07:26 UTC, sumitsum commented on app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java
> +                        invalids.add(MongoPluginErrorMessages.DS_INVALID_USER_DATABASE_NAME);
Can you please update the error name to `DS_INVALID_AUTH_DATABASE_NAME` ? as the concerned input field should ideally be named `Authentication Database`.

2023-03-21 07:26 UTC, sumitsum commented on app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java
> -                        if (defaultDatabaseName == null || defaultDatabaseName.isBlank()) {
I think we want to keep this flow as this field is optional which means that even if the user chooses to keep it as empty it should be fine.

2023-03-21 07:26 UTC, sumitsum commented on app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java
> +            final String databaseName;
Should we rename it to `authDatabaseName` ? as ideally the input field is capturing authentication database name.

2023-03-21 07:26 UTC, sumitsum commented on app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java
> +            if (datasourceConfiguration.getConnection() != null && datasourceConfiguration.getAuthentication() != null) {
QQ: Why are we checking for `datasourceConfiguration.getConnection() != null` ?

2023-03-21 07:26 UTC, sumitsum commented on app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java
> +            } else databaseName = null;
Shouldn't we add a check for authentication db being empty / null and throw an error ?

2023-03-21 07:26 UTC, sumitsum commented on app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java
> +            final String databaseName;
Can we pull this and the `defaultDatabaseName` variable definition right next to their usage lines ?

2023-03-21 07:26 UTC, sumitsum commented on app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java
> +                        if(defaultDatabaseName == null || defaultDatabaseName.isBlank()){
QQ: Why are we checking for both `userDB` and `defaultDatabaseName` ?

2023-03-21 07:26 UTC, sumitsum commented on app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/exceptions/MongoPluginErrorMessages.java
> +    public static final String DS_INVALID_USER_DATABASE_NAME = "Database Name is invalid, no database found with this name.";
As mentioned earlier, can we update the name to `DS_INVALID_AUTH_D...` and the message to `Authentication Database Name is...` ?

2023-03-21 07:26 UTC, sumitsum commented on app/server/appsmith-plugins/mongoPlugin/src/test/java/com/external/plugins/MongoPluginDatasourceTest.java
> +                    assertFalse(datasourceTestResult.isSuccess());
Also, please check add check for exact error message received if any.

2023-03-21 07:26 UTC, sumitsum commented on app/server/appsmith-plugins/mongoPlugin/src/test/java/com/external/plugins/MongoPluginDatasourceTest.java
> +    public void testDatasourceFailWithEmptyDefaultDatabaseNameAndValidUserDBName() {
As mentioned earlier, the default database name is optional and hence if the field is left empty it should be fine. In which case, we should update this test to check for test datasource pass.

2023-03-21 07:26 UTC, sumitsum commented on app/server/appsmith-plugins/mongoPlugin/src/test/java/com/external/plugins/MongoPluginDatasourceTest.java
> +                    assertTrue(datasourceTestResult.isSuccess());
QQ: The test case name says `testDatasourceFail...` but we seem to be checking for `isSuccess=True`. Is this ok ?

2023-03-21 07:34 UTC, PiyushPushkar02 commented on app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java
> +            if (datasourceConfiguration.getConnection() != null && datasourceConfiguration.getAuthentication() != null) {
to handle the case when the db is configured with with no authentication. In that case the DBAuth object returned here will be null.

2023-03-21 08:44 UTC, PiyushPushkar02 commented
/ok-to-test sha=524cc17

2023-03-22 06:22 UTC, sumitsum requested changes

2023-03-22 06:22 UTC, sumitsum commented on app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java
> +                        } else defaultDatabaseName = null;
Minor: can we please write the else block using curly braces ? 
if () {
// code
}
else {
// code
}

2023-03-22 06:22 UTC, sumitsum commented on app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java
> +                        if (datasourceConfiguration.getAuthentication() != null) {
In the `if` condition should we also check for `!isBlank(datasourceconfiguration.getAuthentication().getDatabaseName())` ?

2023-03-22 06:51 UTC, sumitsum commented on app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java
> +                                !((DBAuth)datasourceConfiguration.getAuthentication()).getDatabaseName().isBlank()) {
Should we replace the `.isBlank()` call with the function call `isBlank(....getDatabaseName())` reason being that in case the database name is `null` then `null.isBlank` will lead to NPE ?

2023-03-22 06:52 UTC, sumitsum commented on app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java
> +                                !((DBAuth)datasourceConfiguration.getAuthentication()).getDatabaseName().isBlank()) {
JFYI, I am referring to `StringUtils.isBlank` function here.

2023-03-22 07:21 UTC, sumitsum commented on app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java
> +                                isEmpty(((DBAuth)datasourceConfiguration.getAuthentication()).getDatabaseName())) {
QQ: Why did we choose to use `isEmpty` instead of `isBlank` ?

2023-03-22 07:21 UTC, sumitsum commented on app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java
> +                                isEmpty(((DBAuth)datasourceConfiguration.getAuthentication()).getDatabaseName())) {
Also, shouldn't it be `!isEmpty` ?

2023-03-22 07:33 UTC, PiyushPushkar02 commented on app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java
> +                                isEmpty(((DBAuth)datasourceConfiguration.getAuthentication()).getDatabaseName())) {
I have corrected the incorrect boolean check. Also, I have changed it to isBlank but it wouldn't have made a difference as they both do the same thing except isBlank also checks for whitespace. But that wouldn't have been a problem for us as the value is already trimmed. They belong to different classes isBlank comes from logging utils of apache and isEmpty comes from String utils.

2023-03-22 07:41 UTC, sumitsum commented on app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java
> +                                isEmpty(((DBAuth)datasourceConfiguration.getAuthentication()).getDatabaseName())) {
Hi Piyush, sorry I couldn't find if we are trimming the value anywhere. Can you please share where I can find it ?

2023-03-22 07:46 UTC, sumitsum approved these changes

2023-03-22 07:51 UTC, PiyushPushkar02 commented
/ok-to-test sha=245b95d

2023-03-22 10:36 UTC, PiyushPushkar02 commented
/build-deploy-preview skip-tests=true

2023-03-23 05:53 UTC, merged