bug: table ISO 8061 format bug for v1 and v2 version
appsmithorg/appsmith pull request #21600
Opened 2023-03-20 12:43 UTC by vsvamsi1

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.

## Description

> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change
> Links to Notion, Figma or any other documents that might be relevant to the PR

> Add a TL;DR when description is extra long (helps content team)

Fixes # (issue)
> if no issue exists, please create an issue and ask the maintainers about this first

Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update

## How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.
> Delete anything that is not important

- Manual
- Jest
- Cypress

### Test Plan
> Add Testsmith test cases links that relate to this PR

### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)

## Checklist:
### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2023-03-20 12:44 UTC, vsvamsi1 commented
/ok-to-test sha=f6679185a7417cda13b059838afaa71f12e54d10

2023-03-20 16:12 UTC, vsvamsi1 commented
/ok-to-test sha=509dbbf395a840f653d465bc6eb3d81dd6732899

2023-03-21 05:57 UTC, aswathkk requested changes
@vsvamsi1 The changes looks good to me.

I have a minor suggestion.
Also, I could see that this validation is wrong for `outputFormat` property too. Can you fix that too?

2023-03-21 05:57 UTC, aswathkk commented on app/client/src/widgets/TableWidget/widget/propertyConfig.ts
> +                          "YYYY-MM-DDTHH:mm:ss.SSSZ",
I think we need to replace the value `YYYY-MM-DDTHH:mm:ss.sssZ` (line number 380) to `YYYY-MM-DDTHH:mm:ss.SSSZ` instead of adding `YYYY-MM-DDTHH:mm:ss.SSSZ` to this array.

2023-03-21 06:14 UTC, vsvamsi1 commented on app/client/src/widgets/TableWidget/widget/propertyConfig.ts
> +                          "YYYY-MM-DDTHH:mm:ss.SSSZ",
I was thinking of the same, but will it break existing validations if someone has add in the JS expression `YYYY-MM-DDTHH:mm:ss.sssZ`?

2023-03-21 06:21 UTC, vsvamsi1 commented
> @vsvamsi1 The changes looks good to me.
> 
> I have a minor suggestion. Also, I could see that this validation is wrong for `outputFormat` property too. Can you fix that too?

@aswathkk with regards to this comment I have fixed it over here ....are these changes okay?
`https://github.com/appsmithorg/appsmith/blob/0c39a72b2402c798bb725ce4c85f49d40878946a/app/client/src/widgets/TableWidgetV2/widget/propertyConfig/PanelConfig/Data.ts#L275
https://github.com/appsmithorg/appsmith/blob/0c39a72b2402c798bb725ce4c85f49d40878946a/app/client/src/widgets/TableWidget/widget/propertyConfig.ts#L513
`

2023-03-21 06:25 UTC, aswathkk commented
@vsvamsi1 Yeah. But, there also I can see that you added the valid format (`YYYY-MM-DDTHH:mm:ss.SSSZ`) into the beginning of the array rather than fixing the invalid one (`YYYY-MM-DDTHH:mm:ss.sssZ`) inside the array

2023-03-21 06:42 UTC, aswathkk approved these changes

2023-03-21 13:44 UTC, chandannkumar commented
Tested this PR and LGTM
- Tested date format issue on Table v2
- Tested for validation error - fixed

P.S- Testing of table v1 fix will be verified after merge. Since above DP doesn't have older apps

2023-03-22 05:59 UTC, merged