var was set incorrectly
appsmithorg/appsmith pull request #21677
Opened 2023-03-22 07:45 UTC by ApekshaBhosale

## Description

variables prop of JSobject is part of configTree. it was getting set to the wrong location ie unEvalTree

Fixes #21676

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.
> Delete anything that is not important

- Manual
- Jest
- Cypress

### Test Plan
> Add Testsmith test cases links that relate to this PR

### Issues raised during DP testing
> Link issues raised during DP testing for better visibility and tracking (copy link from comments dropped on this PR)

## Checklist:
### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2023-03-22 07:50 UTC, Rishabh-Rathod approved these changes
LGTM

2023-03-22 07:58 UTC, ApekshaBhosale commented
/ok-to-test sha=fbfa883

2023-03-23 06:57 UTC, ApekshaBhosale commented
/ok-to-test sha=5a56ed9

2023-03-23 15:47 UTC, Rishabh-Rathod requested changes
Line no 212 :- `removeFunctionsAndVariableJSCollection` function also has code `set(modifiedDataTree, `${entityName}.variables`, []);` that needs to be modified to `set(oldConfig, `${entityName}.variables`, []);`

2023-03-24 07:05 UTC, ApekshaBhosale commented
/ok-to-test sha=ca7b93a

2023-03-25 06:49 UTC, Rishabh-Rathod approved these changes
Changes LGTM.

2023-03-29 10:47 UTC, ApekshaBhosale commented
/ok-to-test sha=460cf9a

2023-04-03 04:44 UTC, ApekshaBhosale commented
/ok-to-test sha=1b538ed

2023-04-04 05:58 UTC, ApekshaBhosale commented
/ok-to-test sha=def3239

2023-04-04 08:31 UTC, ApekshaBhosale commented
/ok-to-test sha=5927df1

2023-04-05 12:15 UTC, ApekshaBhosale commented
/ok-to-test sha=f531c14

2023-04-06 10:50 UTC, Rishabh-Rathod requested changes

2023-04-06 10:50 UTC, Rishabh-Rathod commented on app/client/src/workers/Evaluation/JSObject/utils.ts
> +        set(jsEntityConfig, `${entityName}.variables`, varList);
Shouldn't we modify the `configTree` here instead of jsEntityConfig? 
```suggestion
        set(configtree, `${entityName}.variables`, varList);
```

2023-04-06 10:54 UTC, ApekshaBhosale commented
/ok-to-test sha=9d79b28

2023-04-06 10:56 UTC, Rishabh-Rathod approved these changes
Looks good

2023-04-07 07:45 UTC, ApekshaBhosale commented
closing this on account of https://github.com/appsmithorg/appsmith/pull/19926

2023-04-07 07:45 UTC, closed without merging