feat: Added file id mapping in datasource config
appsmithorg/appsmith pull request #21699
Opened 2023-03-22 13:08 UTC by sneha122

## Description

This PR adds:
- File Id mapping of the google sheets selected by user, in datasource configuration, so that when creating queries on top of such gsheet datasource, only the selected spreadsheets can be seen in the spreadsheet dropdown.

> Add a TL;DR when description is extra long (helps content team)

Fixes #21074

Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video

## Type of change

> Please delete options that are not relevant.

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Manual
- JUnit

### Test Plan
> Add Testsmith test cases links that relate to this PR

### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)

## Checklist:
### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2023-03-22 13:17 UTC, sneha122 commented
/build-deploy-preview

2023-03-22 13:17 UTC, sneha122 commented
/ok-to-test

2023-03-23 07:01 UTC, sneha122 commented
/ok-to-test

2023-03-24 09:57 UTC, ChandanBalajiBP requested changes
Really appreciate the changes you have added in this PR. You have used enum and constants at required places👏

2023-03-24 09:57 UTC, ChandanBalajiBP commented on app/client/src/sagas/DatasourcesSagas.ts
> +    set(datasource, "datasourceConfiguration.properties[0].value", fileIds);
Can we merge these two set call to one?

2023-03-24 09:57 UTC, ChandanBalajiBP commented on app/client/src/entities/Datasource/index.ts
> +  CANCEL = "cancel",
can you please update these to Uppercases. You can refer above enum.

2023-03-24 10:32 UTC, sneha122 commented on app/client/src/entities/Datasource/index.ts
> +  CANCEL = "cancel",
@ChandanBalajiBP These values `cancel` and `picked` are coming from google's file picker api, hence cannot change it.

2023-03-24 11:53 UTC, sneha122 commented on app/client/src/sagas/DatasourcesSagas.ts
> +    set(datasource, "datasourceConfiguration.properties[0].value", fileIds);
@ChandanBalajiBP Can we set two different properties in the same set call? If yes could you please point me to the reference code for the same?

2023-03-24 14:09 UTC, ChandanBalajiBP commented on app/client/src/sagas/DatasourcesSagas.ts
> +    set(datasource, "datasourceConfiguration.properties[0].value", fileIds);
> ```
> set(datasource, "datasourceConfiguration.properties[0]", { 
> key: createMessage(GSHEET_AUTHORISED_FILE_IDS_KEY,
> value: fileIds
> })
> ```

We are reducing a call to setter method this way.

2023-03-24 14:15 UTC, sneha122 commented on app/client/src/sagas/DatasourcesSagas.ts
> +    set(datasource, "datasourceConfiguration.properties[0].value", fileIds);
Thanks a lot!! This was really helpful, have made the corresponding changes. Please check @ChandanBalajiBP

2023-03-24 14:36 UTC, ChandanBalajiBP approved these changes
LGTM!

2023-03-27 11:44 UTC, sumitsum requested changes

2023-03-27 11:44 UTC, sumitsum commented on app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/FileListMethod.java
> +                    if (allowedFileIds != null && !allowedFileIds.isEmpty()) {
Is this code section a duplicate of the code in `transformExecuteResponse` ? If so, should we extract the common code in a static function in say `SheetsUtil.java` and call that function instead ?

2023-03-27 11:44 UTC, sumitsum commented on app/server/appsmith-plugins/googleSheetsPlugin/src/test/java/com/external/config/FileListMethodTest.java
> +        assertEquals(result.size(), 2);
Can you please add an assert here to match the exact expected content of `result` ?

2023-03-27 11:44 UTC, sumitsum commented on app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ExamplesWorkspaceClonerTests.java
> +                                    new Property("custom token param 3", Set.of("file1", "file2", "file3"))
Sorry, I couldn't understand why this change is required here. Can you please provide details for this change ?

2023-03-27 11:44 UTC, sumitsum commented on app/server/appsmith-plugins/googleSheetsPlugin/src/test/java/com/external/config/FileListMethodTest.java
> +    public void testTransformTriggerResponse_withAllSheetsAccess_returnsAllSheets() throws JsonProcessingException {
Can you please add similar methods for `transformExecuteResponse` method as well ?

2023-03-27 13:19 UTC, sneha122 commented on app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/FileListMethod.java
> +                    } else {
In this case, the secondary if checks if the file is present in authorised list, if not it will come out of the if block, and return null by default [line 75], and in the end while aggregating all data as list, I am not taking these null objects [line 77]

2023-03-27 14:14 UTC, sneha122 commented on app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/GetStructureMethod.java
> +    public JsonNode transformExecutionResponse(JsonNode response, MethodConfig methodConfig, Set<String> allowedFileIds) {
By defining, do you mean in the interface, we would define it like this, and overriding classes can then decide whether to have 2/3 params?

2023-03-27 14:14 UTC, sneha122 commented on app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/utils/SheetsUtil.java
> +        if (datasourceConfiguration.getProperties() != null
@sumitsum isEmpty only checks if array is empty or not, if properties is null, it will throw NullPointerException right? Also I checked the code, properties is by default set to empty array so using isEmpty should work, as this will never be null in that case. Reference: https://stackoverflow.com/questions/11512034/does-java-util-list-isempty-check-if-the-list-itself-is-null. Let me know what you think.

2023-03-27 14:27 UTC, sneha122 commented on app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ExamplesWorkspaceClonerTests.java
> +                                    new Property("custom token param 3", Set.of("file1", "file2", "file3"))
This is not needed, I think this test was failing on server while coding, so I had added that, but checked now, removing it does not fail the test, hence removing this code. Thanks @sumitsum

2023-03-28 05:00 UTC, sumitsum commented on app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/plugins/GoogleSheetsPlugin.java
> +            final Set<String> allowedFileIds = SheetsUtil.getAuthorizedSheetIds(datasourceConfiguration);
Hi @sneha122 I am not able to see this change. Can you please check once ?

2023-03-28 05:08 UTC, sumitsum commented on app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/plugins/GoogleSheetsPlugin.java
> +            final Set<String> userAuthorizedSheetIds = SheetsUtil.getAuthorizedSheetIds(datasourceConfiguration);
Can you please update this usage to `getAuthorizedSheetIds` and the import to `import ...SheetsUtil.getAuthorizedSheetIds` ? Also, please update the same way in rest of the files wherever applicable.

2023-03-28 05:08 UTC, sumitsum commented on app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/utils/SheetsUtil.java
> +        if (datasourceConfiguration.getProperties() != null
Hi @sneha122 can you please check for `CollectionUtils.isEmpty(properties)` in the code base and mention if you were thinking about the same thing ?

2023-03-28 05:10 UTC, sumitsum commented on app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/GetStructureMethod.java
> +    public JsonNode transformExecutionResponse(JsonNode response, MethodConfig methodConfig, Set<String> allowedFileIds) {
Hi @sneha122 yes, we would define the default implementation in the interface. This way any class which does not override the 3 param method will still have a default implementation calling the 2 param method. The idea here is to save use form having to add any extra `null` param or any extra implementation at all at the individual class level.

2023-03-28 05:11 UTC, sumitsum commented on app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/FileListMethod.java
> +                    if (allowedFileIds != null && !allowedFileIds.isEmpty()) {
@sneha122 can you please check for this and mention if you were thinking about the same thing: `StringUtils.isEmpty(datasourceConfiguration.getUrl())` ?

2023-03-28 05:32 UTC, sumitsum requested changes

2023-03-28 05:32 UTC, sumitsum commented on app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/FileListMethod.java
> +                    if (userAuthorizedSheetIds != null && !userAuthorizedSheetIds.isEmpty()) {
Hi @sneha122 in case the entire block from the line 61 to 70 is still identical, can we refactor this into another function as well ?

2023-03-28 05:32 UTC, sumitsum commented on app/server/appsmith-plugins/googleSheetsPlugin/src/test/java/com/external/config/FileListMethodTest.java
> +        assertEquals(expectedObjectNode1, result.get(0));
QQ: Are we sure about the order of values here i.e. if we are using a `set` datastructure anywhere to hold values anywhere the order would get distured resulting in flaky tests. Can you please confirm this once ? Same for the test for `transformExecuteResponse`.

2023-03-28 14:20 UTC, sneha122 commented
/ok-to-test

2023-03-28 14:20 UTC, sneha122 commented
/build-deploy-preview

2023-03-29 04:05 UTC, sumitsum commented on app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/utils/SheetsUtil.java
> +        if (userAuthorizedSheetIds.contains(fileId)) {
Minor: could we combine the two if conditions into one like: 
```
if (userAuthorizedSheetIds == null || userAuthorizedSheetIds.contains(fileId))
```
I feel like you had mentioned something like this during our conversation yesterday but for some reason we couldn't get back to it.

2023-03-29 04:05 UTC, sumitsum commented on app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/GetStructureMethod.java
> +    public JsonNode transformExecutionResponse(JsonNode response, MethodConfig methodConfig, Set<String> allowedFileIds) {
As discussed yesterday, we are dropping this idea because it is making readability worse.

2023-03-29 05:13 UTC, sneha122 commented on app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/utils/SheetsUtil.java
> +        if (userAuthorizedSheetIds.contains(fileId)) {
@sumitsum We could but lets not do it, this way its clear that null condition is for all sheets modality and contains condition is for specific sheets. Also we did discuss about combining the if blocks, but instead we refactored the code to avoid nested if and wrote like this. LMK what you think

2023-03-29 05:23 UTC, sumitsum commented on app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/utils/SheetsUtil.java
> +        if (userAuthorizedSheetIds.contains(fileId)) {
Hi @sneha122 agree with the reasoning here. In that case, to make the reason more clear can you please add a comment on top of both the if conditions explaining which Gsheet dropdown condition they correspond to ?

2023-03-29 05:24 UTC, sneha122 commented on app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/utils/SheetsUtil.java
> +        if (userAuthorizedSheetIds.contains(fileId)) {
Yup will do that

2023-03-29 05:48 UTC, sneha122 commented
/ok-to-test

2023-03-29 05:48 UTC, sumitsum approved these changes

2023-03-29 06:56 UTC, sneha122 commented
/build-deploy-preview

2023-03-29 07:33 UTC, sneha122 commented
/ok-to-test

2023-03-30 02:53 UTC, sumitsum approved these changes

2023-03-30 08:04 UTC, sneha122 commented
> Deploy-Preview-URL: https://ce-21699.dp.appsmith.com

@prapullac

2023-04-04 08:13 UTC, merged