fix: API Url Whitespace Bug Fix
appsmithorg/appsmith pull request #21711
Opened 2023-03-23 06:52 UTC by PiyushPushkar02

## Description

- Added trim method to remove the whitespace from the URL while creating the request URL.

Fixes #21629 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manual

## Checklist:
### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2023-03-23 07:04 UTC, sumitsum commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/InitUtils.java
> +        return datasourceConfiguration.getUrl().trim() + path;
As requested by Arpit as well, please add a JUnit TC for this. Otherwise LGTM.

2023-03-23 07:10 UTC, PiyushPushkar02 commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/InitUtils.java
> +        return datasourceConfiguration.getUrl().trim() + path;
Added the JUnit test case for this

2023-03-23 07:23 UTC, sumitsum requested changes

2023-03-23 07:23 UTC, sumitsum commented on app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java
> +    @Test
@PiyushPushkar02 can you please add a test for GraphQL plugin as well ?

2023-03-23 07:23 UTC, sumitsum commented on app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java
> +                    assertEquals(HttpMethod.POST, request.getHttpMethod());
Should we remove all the following asserts since they are not related to the feature we are testing ? This should improve the readability of the test case.

2023-03-23 07:24 UTC, sumitsum commented on app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java
> +        dsConfig.setUrl("    https://postman-echo.com/post");
Can you please add spaces in the end as well, so that it covers both the situations - spaces at the start and the tail.

2023-03-23 08:42 UTC, sumitsum approved these changes

2023-03-23 10:02 UTC, PiyushPushkar02 commented
/ok-to-test sha=8592d1d

2023-03-24 10:27 UTC, PiyushPushkar02 commented
/ok-to-test

2023-03-24 11:38 UTC, PiyushPushkar02 commented
/build-deploy-preview skip-tests=true

2023-03-27 01:08 UTC, PiyushPushkar02 commented
/ok-to-test

2023-03-27 04:28 UTC, merged