Fix:404 showing server unavailable
appsmithorg/appsmith pull request #2195
Opened 2020-12-14 10:55 UTC by jsartisan

The 404 page was showing "Server not unavailable"

## Description

Fixes #2192 

## Type of change

- Bug fix

## How Has This Been Tested?
- Manually tested

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2020-12-14 11:03 UTC, mohanarpit commented on app/client/src/AppRouter.tsx
> +            <Switch>
As part of this change, is it possible to keep the URL the same instead of redirecting to a `/404` URL? I'm asking this so that the user can simply try to refresh the page and access the content again instead of clicking on the button?

2020-12-14 11:22 UTC, jsartisan commented on app/client/src/AppRouter.tsx
> +            <Switch>
Yes, It should be fairly easy to do that but I wonder why we changed the URL in the first place.

2020-12-14 11:27 UTC, jsartisan commented on app/client/src/AppRouter.tsx
> +            <Switch>
Let me confirm this with Hetu. I think we did that because react-router expects a specific router to render a component.

2020-12-14 12:07 UTC, hetunandu requested changes

2020-12-14 12:07 UTC, hetunandu commented on app/client/src/AppRouter.tsx
> +            </Switch>
You cannot switch based on routes here

2020-12-14 13:27 UTC, jsartisan commented
@hetunandu now rendering the page based on error code.

2020-12-14 13:31 UTC, hetunandu commented
Please also remove the two routes for 404 and 500 and make sure nothing else in the app tries to navigate to those routes

2020-12-14 13:36 UTC, jsartisan commented
> Please also remove the two routes for 404 and 500 and make sure nothing else in the app tries to navigate to those routes

Done.

2020-12-14 13:51 UTC, jsartisan commented on app/client/cypress/integration/Smoke_TestSuite/Pages/Pages_spec.js
> +    cy.visit("/route-that-does-exit");
This will be "route-that-does-not-exist" :P will update it in next commit.

2020-12-15 06:16 UTC, hetunandu requested changes

2020-12-15 06:16 UTC, hetunandu commented on app/client/src/utils/AppsmithUtils.tsx
> -            history.replace(SERVER_ERROR_URL);
set the crash code from here.

2020-12-15 06:16 UTC, hetunandu commented on app/client/src/AppRouter.tsx
> +  switch (safeCrashCode) {
Let us make a proper enum for this safeCrashCode and use that to keep this maintainable

2020-12-15 07:18 UTC, hetunandu requested changes
Please refactor properly

2020-12-15 07:18 UTC, hetunandu commented on app/client/src/constants/ApiConstants.tsx
> +  REQUEST_TIMEOUT = "ECONNABORTED",
Keeps it separate from API level codes
```suggestion
export enum ERROR_CODES {
  PAGE_NOT_FOUND = "PAGE_NOT_FOUND",
  SERVER_ERROR = "SERVER_ERROR",
  REQUEST_TIMEOUT = "REQUEST_TIMEOUT",
```

2020-12-15 07:18 UTC, hetunandu commented on app/client/src/sagas/InitSagas.ts
> +          API_STATUS_CODES.SERVER_ERROR,
Use the error code enum in this file

2020-12-15 07:18 UTC, hetunandu commented on app/client/src/constants/ReduxActionConstants.tsx
> +  code?: number | string;
Use the error code here

2020-12-15 07:18 UTC, hetunandu commented on app/client/src/api/Api.tsx
> +        code: ERROR_CODES.REQUEST_TIMEOUT,
Use the error code in all promise rejections here

2020-12-16 08:34 UTC, hetunandu requested changes

2020-12-16 18:03 UTC, jsartisan commented
@hetunandu Since we were not rendering the routes in `AppRouter` on `safeCrash`, `history.push` was not working at all in the header on the error page since there were no routes to render. So in the header of the error page, on clicking the logo, I am flushing errors.

2020-12-17 07:02 UTC, hetunandu approved these changes

2020-12-17 07:04 UTC, merged