fix: Firestore Invalid DS Test Success
appsmithorg/appsmith pull request #21954
Opened 2023-03-31 07:17 UTC by PiyushPushkar02

## Description

- The following PR fixes the issue where the firestore test data source was returning success even after providing an invalid project id.
- The PR address the invalid project id only not the db URL as it is fetched from the auth json If the URL is invalid in user provided entry. Also, the value is mutable at runtime from the firestore side.
-  For more detailed description of the following can be found in the notion doc here: https://www.notion.so/Firestore-c3f5c816a68a45b18395da74be97d666

Fixes #21373 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manual
- JUnit

## Checklist:
### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2023-03-31 07:33 UTC, mohanarpit commented on app/server/appsmith-plugins/firestorePlugin/src/main/java/com/external/plugins/FirestorePlugin.java
> +                            return FirebaseApp.initializeApp(options,projectId);
Nit: Can you please format the code in this PR according to standards? This changelog is not formatted correctly.

2023-03-31 07:34 UTC, mohanarpit commented on app/server/appsmith-plugins/firestorePlugin/src/main/java/com/external/plugins/exceptions/FirestoreErrorMessages.java
> +    public static final String DS_VALIDATION_FAILED_FOR_PROJECT_ID = "Invalid project id, no database found for given project id";
Please keep the sentence casing and grammar as per other error messages. Consistency is key to a polished product.

2023-04-04 06:36 UTC, sumitsum requested changes

2023-04-04 06:36 UTC, sumitsum commented on app/server/appsmith-plugins/firestorePlugin/src/main/java/com/external/plugins/FirestorePlugin.java
> +                                String metaDataAccessMissingMessage = "Unable to validate ProjectID, provided service " +
@PiyushPushkar02 just a general suggestion. Whenever we write an error message we should try to structure it so that (1) It is friendly / humane (2) It tells the user exaclty what th issue is (3) It tells the user what to do next. Since we don't have a platform wide convention on this, IMO, for now we should change the message to something along the following lines. Please mention if you think otherwise or if we could add / modify to improve upon it: 
```
Hi, it seems that the credentials provided here don't have the permission to gather metadata information. Please reach out to your database admin to understand more. 
```

2023-04-04 06:36 UTC, sumitsum commented on app/server/appsmith-plugins/firestorePlugin/src/main/java/com/external/plugins/FirestorePlugin.java
> +                                String metaDataAccessMissingMessage = "Unable to validate ProjectID, provided service " +
Can you please convert this message string in a `public static final String` macro and use the same in the test case as well ?

2023-04-04 06:36 UTC, sumitsum commented on app/server/appsmith-plugins/firestorePlugin/src/test/java/com/external/plugins/FirestorePluginTest.java
> +        FirebaseOptions firebaseOptions = FirebaseOptions.builder()
Instead of building the `Firestore` object explicitly here, could we instead create a new datasource config object with the required parameters and then `datasourceCreate` should build the Firestore object as part of its flow ? Reason being that if we build it explicitly here and then some code change happens as part of the datasource create flow then we wouldn't be able to verify the impact of that change on this PR since this PR creates the object on its own.

2023-04-04 08:03 UTC, sumitsum commented on app/server/appsmith-plugins/firestorePlugin/src/test/java/com/external/plugins/FirestorePluginTest.java
> +        //We cannot use the datasource create flow here as the client authentication json in unknown. Hence, using the
Minor: should it be `is unknown` instead of `in unknown` ?

2023-04-04 09:09 UTC, sumitsum approved these changes

2023-04-04 09:11 UTC, PiyushPushkar02 commented
/ok-to-test sha=7de5869

2023-04-05 05:56 UTC, PiyushPushkar02 commented
/ok-to-test

2023-04-10 06:41 UTC, PiyushPushkar02 commented
/ok-to-test

2023-04-11 05:18 UTC, PiyushPushkar02 commented
/ok-to-test sha=7de5869

2023-04-13 10:16 UTC, PiyushPushkar02 commented on app/server/appsmith-plugins/firestorePlugin/src/main/java/com/external/plugins/exceptions/FirestoreErrorMessages.java
> +    public static final String DS_VALIDATION_FAILED_FOR_PROJECT_ID = "Invalid project id, no database found for given project id";
done

2023-04-13 10:16 UTC, PiyushPushkar02 commented on app/server/appsmith-plugins/firestorePlugin/src/main/java/com/external/plugins/FirestorePlugin.java
> +                            return FirebaseApp.initializeApp(options,projectId);
done

2023-04-13 10:17 UTC, merged