chore: Render tailored html files in some cases
appsmithorg/appsmith pull request #21986
Opened 2023-04-01 02:46 UTC by sharat87

When opening Appsmith in edit mode, we _try_ to render the specialized `edit.html`, and for opening in view mode, we _try_ to render the specialized `view.html` files, instead of the `index.html`. If those files aren't available, we fallback to `index.html`, so there's no disruption in service.

These specialized files are, today, identical to `index.html`, but contain a few extra preloads that are tuned to work better for those pages.

Learn more at https://github.com/appsmithorg/appsmith/pull/21933.

2023-04-04 03:39 UTC, SatishGandham requested changes

2023-04-04 03:39 UTC, SatishGandham commented on deploy/docker/templates/nginx/nginx-app-http.conf.template.sh
> +  location ~ ^/app/[^/]+/[^/]+/edit\b {
I don't know the exact regex but, if there is something after the edit, then it is preceded by a `/`
This regex matches `/app/hello/123/editfoo`, it is not a problem now, but there may be a case in future.

2023-04-04 17:21 UTC, iamakulov approved these changes
This will work for Cypress tests as well, right? (We have a Cypress test that verifies that the preloads in `view.html`/`index.html` weren’t broken.)

2023-04-13 12:28 UTC, sharat87 commented
@iamakulov, yes. Cypress tests should be able to verify if things continue to work as is with the changes here.

2023-04-14 05:54 UTC, SatishGandham approved these changes

2023-04-25 02:10 UTC, sharat87 commented
Just checking in, we still want/need this, right? Anything I can do to help move this faster?

2023-05-16 04:13 UTC, sharat87 commented
Changes are already in `release`.

2023-05-16 04:13 UTC, closed without merging