Set document title as app name
appsmithorg/appsmith pull request #2203
Opened 2020-12-15 05:33 UTC by ashwanisindhu1

## Description
> We should add the app name to the document title attribute in view mode.

Fixes #1842 

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Manually tested

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes

2020-12-15 06:10 UTC, hetunandu requested changes
Use an existing library instead of setting this directly

2020-12-15 06:10 UTC, hetunandu commented on app/client/src/pages/AppViewer/viewer/AppViewerHeader.tsx
> +  useDocumentTitle(currentApplicationDetails?.name);
Use [Helmet](https://github.com/appsmithorg/appsmith/blob/release/app/client/src/pages/Editor/index.tsx#L221-L224) library here instead. 
Also If no name is found, it should have a default of `Appsmith`

2020-12-15 08:30 UTC, ashwanisindhu1 commented on app/client/src/pages/AppViewer/viewer/AppViewerHeader.tsx
> +  useDocumentTitle(currentApplicationDetails?.name);
Updated to use Helmet. 
By default, [global title](https://github.com/appsmithorg/appsmith/blob/release/app/client/public/index.html#L9) is `Appsmith`. So, we do not need to set default here.

2020-12-15 09:18 UTC, hetunandu approved these changes

2020-12-15 11:24 UTC, merged

2020-12-16 06:43 UTC, mohanarpit commented
@ashwanisindhu1 This PR has been merged. It will be available on Appsmith's next release. Thank you so much for your contribution to the project. 🎉