fix: Adding a permission check for creating new datasource on generate page
appsmithorg/appsmith pull request #22085
Opened 2023-04-04 11:01 UTC by ankitakinger

## Description

Adding a permission check for creating new datasource on generate page. When a custom role is assigned in GAC, where the user doesn't have access to create a new datasource, in spite of that the create new datasource option is showed in the dropdown on generate page with data. This is fixed with this PR.

Fixes [#22027](https://github.com/appsmithorg/appsmith/issues/22027)

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
> Tested it manually and it works fine.

- Manual

## Checklist:
### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2023-04-04 11:03 UTC, ankitakinger commented
/ok-to-test sha=fdebdc8

2023-04-05 03:38 UTC, berzerkeer requested changes

2023-04-05 03:38 UTC, berzerkeer commented on app/client/src/pages/Editor/GeneratePage/components/GeneratePageForm/GeneratePageForm.tsx
> +import { hasCreateDatasourcePermission } from "ce/utils/permissionHelpers";
Shouldn't this be from `@appsmith`

2023-04-05 04:11 UTC, ankitakinger commented on app/client/src/pages/Editor/GeneratePage/components/GeneratePageForm/GeneratePageForm.tsx
> +import { hasCreateDatasourcePermission } from "ce/utils/permissionHelpers";
oh yes. Thanks for pointing it out.

2023-04-05 04:28 UTC, berzerkeer approved these changes

2023-04-05 04:55 UTC, ankitakinger commented
/ok-to-test sha=4b8ca7a

2023-04-05 11:52 UTC, merged

2023-04-05 11:52 UTC, dipyamanbiswas07 approved these changes