feat: self host google fonts
appsmithorg/appsmith pull request #22129
Opened 2023-04-05 09:22 UTC by berzerkeer

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.

## Description

> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change
> Links to Notion, Figma or any other documents that might be relevant to the PR

> Add a TL;DR when description is extra long (helps content team)

Fixes # (issue)
> if no issue exists, please create an issue and ask the maintainers about this first

Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update

## How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.
> Delete anything that is not important

- Manual
- Jest
- Cypress

### Test Plan
> Add Testsmith test cases links that relate to this PR

### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)

## Checklist:
### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2023-04-06 05:06 UTC, jsartisan commented
/ok-to-test sha=efe7c48

2023-04-10 07:36 UTC, berzerkeer commented
/ok-to-test sha=a03ca99

2023-04-11 07:26 UTC, ichik requested changes
1. License files for fonts are missing, SIL OFL permits us to bundle fonts, but license files need to be included
2. Including anything besides `woff2` is a legacy compatibility overkill, format is [well supported](https://caniuse.com/woff2) for many years now

2023-04-11 11:13 UTC, ichik commented
> Hi @ichik can you help me with license files, a reference to it is fine. And so should I remove every other font face and just keep woff2?

1. [Inter](https://github.com/rsms/inter/blob/master/LICENSE.txt)
2. [Nunito](https://github.com/googlefonts/NunitoSans/blob/main/OFL.txt)
3. [Poppins](https://github.com/itfoundry/Poppins/blob/master/OFL.txt)
4. [Montserrat](https://github.com/JulietaUla/Montserrat/blob/master/OFL.txt)
5. [Noto](https://github.com/notofonts/NotoSans/blob/main/LICENSE)
6. [Open](https://github.com/googlefonts/opensans/blob/main/OFL.txt)
7. [Rubik](https://github.com/googlefonts/rubik/blob/main/OFL.txt)
8. [Roboto](https://github.com/googlefonts/roboto/blob/main/LICENSE)
9. [Ubuntu](https://ubuntu.com/legal/font-licence)

Notably, Roboto and Ubuntu are not OFL-licensed (Apache and some Ubuntu license respectively).

On binary formats: that'd be my recommendation (to keep `woff2` only).

2023-04-11 13:56 UTC, ichik submitted a review, later dismissed

2023-04-11 16:34 UTC, ichik submitted a review, later dismissed
Further optimizations: split font files by unicode range, introduce preload directives.

2023-04-11 16:40 UTC, berzerkeer commented
> Further optimizations: split font files by unicode range, introduce preload directives.

https://github.com/appsmithorg/appsmith/issues/22292#issue-1662868923

2023-04-12 06:53 UTC, berzerkeer commented
/ok-to-test sha=cb6f688

2023-04-12 07:02 UTC, berzerkeer commented
/ok-to-test sha=336606c

2023-04-12 07:18 UTC, berzerkeer commented
/ok-to-test sha=15e51fe

2023-04-12 07:29 UTC, jsartisan approved these changes
LGTM!

2023-04-12 08:45 UTC, ichik commented on app/client/src/assets/fonts/google/index.css
> +@import url("https://fonts.googleapis.com/css2?family=Nunito+Sans:ital,wght@0,300;0,400;0,700;1,300;1,400;1,700&display=swap");
Potential performance optimization for the future. Loading CSS with <link> is more performant than doing @import ([ref](https://dev.to/jasmin/how-does-import-works-in-css-what-is-the-pros-and-cons-136c)).
Additionally, since the font is defined in the application theme we don't need to load everything in the deployed app.

2023-04-12 08:45 UTC, ichik submitted a review, later dismissed

2023-04-12 12:26 UTC, berzerkeer commented
/ok-to-test sha=b216eea

2023-04-12 13:55 UTC, berzerkeer commented
/ok-to-test sha=6c346f2

2023-04-12 14:09 UTC, jsartisan approved these changes

2023-04-12 16:13 UTC, berzerkeer commented
/ci-merge-check

2023-04-12 17:28 UTC, ichik approved these changes

2023-04-13 13:18 UTC, merged