Hotfix circular
appsmithorg/appsmith pull request #2214
Opened 2020-12-15 16:37 UTC by ofpiyush

## Description

Catch circularJSON error and send back a broken but editable evaltree

Fixes #1735.

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Not yet

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2020-12-16 02:58 UTC, ofpiyush commented
@hetunandu in the proper fix, we'll somehow need to show the user what they need to do to resolve the issue they're facing.

2020-12-16 09:28 UTC, hetunandu requested changes

2020-12-16 09:28 UTC, hetunandu commented on app/client/src/workers/evaluation.worker.ts
> +        const cleanDataTree = JSON.stringify(getValidatedTree(dataTree));
Only send the validated uneval tree if there is no old eval tree(first eval), else send old eval tree as is.
We can also add some generic error here so the user knows something is wrong in the page.

2020-12-22 09:01 UTC, ofpiyush commented on app/client/src/workers/evaluation.worker.ts
> +        const cleanDataTree = JSON.stringify(getValidatedTree(dataTree));
Even if I do that, it seems to break the app, leaving it as is right now.

We can take a look again after you're back.

2020-12-23 03:39 UTC, ofpiyush commented on app/client/src/components/ads/Toast.tsx
> +    const toastId = JSON.stringify(config);
@riodeuno any ideas?

2020-12-23 06:02 UTC, trishaanand commented
Hey @ofpiyush! Once reviewed, can this also be pushed into subtree evaluation branch? I ask this because this adds new relationships to dependency map which may impact the the nodes being identified for evaluation for each diff. Would like to take that up and fix it once you push it out. Thanks!

2020-12-23 06:03 UTC, ofpiyush commented
@trishaanand it's already there, you can begin changing code around it.

2020-12-23 06:04 UTC, trishaanand commented
@ofpiyush : The addition of relationship between parents/children looks good to me. @riodeuno can do the deep review.

2020-12-23 12:02 UTC, riodeuno commented on app/client/src/components/ads/Toast.tsx
> +    const toastId = JSON.stringify(config);
This is what MD5, SHA1, etc do right? MD5 should be fine in this scenario, as it is just a config -> key map, and no security implications.
http://www.myersdaily.org/joseph/javascript/md5-speed-test.html

2020-12-23 12:05 UTC, ofpiyush commented on app/client/src/components/ads/Toast.tsx
> +    const toastId = JSON.stringify(config);
I didn't want to add a dependency just for this since it is already a unique string. 

The relevant question is, will the long key cause any issues? If not, we can leave it like this (or use `config.text`)

2020-12-23 13:30 UTC, riodeuno commented on app/client/src/workers/evaluation.worker.ts
> +  const rgx = /^(.*)\..*$/;
Let's add a comment of what the regex is matching.

2020-12-23 13:43 UTC, riodeuno approved these changes

2020-12-23 14:18 UTC, merged