Fix: App name UI in edit and deploy mode
appsmithorg/appsmith pull request #2216
Opened 2020-12-15 17:33 UTC by devrk96

2020-12-16 08:30 UTC, hetunandu requested changes

2020-12-16 08:30 UTC, hetunandu commented on app/client/src/pages/AppViewer/viewer/AppViewerHeader.tsx
> +  }
Why is this needed? Use flex to centre the name

2020-12-21 14:05 UTC, devrk96 commented on app/client/src/pages/AppViewer/viewer/AppViewerHeader.tsx
> +  }
@rishabhsaxena Please review the PR. I have fixed the center issue in both edit and deploy mode and removed the hard-coded margin values.

2020-12-22 07:28 UTC, rishabhsaxena commented on app/client/src/components/ads/EditableTextWrapper.tsx
> +    height: 31px;
we shouldn't need this, since parent uses `align-items: center;` ?

2020-12-22 07:31 UTC, rishabhsaxena commented on app/client/src/components/ads/EditableTextWrapper.tsx
> +    height: 31px;
I guess we are using figma for these styles, in that case it should be fine, since line-height might change the position slightly?

2020-12-22 07:34 UTC, devrk96 commented on app/client/src/components/ads/EditableTextWrapper.tsx
> +    height: 31px;
Yes, we are using Figma.

2020-12-22 07:40 UTC, devrk96 commented on app/client/src/components/ads/EditableTextWrapper.tsx
> +    height: 31px;
The parent `align-items: center`  is for the whole component and this one centered the text in the editable component because this is also a space needed for the loading icon to show.

2020-12-22 07:45 UTC, rishabhsaxena submitted a review, later dismissed

2020-12-24 12:06 UTC, rishabhsaxena approved these changes

2021-01-05 06:38 UTC, hetunandu commented on app/client/src/components/ads/EditableTextWrapper.tsx
> +    height: 31px;
Looks like this comment it yet to be resolved @devrk96

2021-01-07 05:05 UTC, hetunandu requested changes

2021-01-07 05:05 UTC, hetunandu commented on app/client/src/components/ads/EditableTextWrapper.tsx
> +    height: 31px;
Use the theme navbar height to calculate this number

2021-01-25 07:21 UTC, hetunandu approved these changes

2021-01-25 07:21 UTC, merged