21631 task show loading message in browser when server is still starting
appsmithorg/appsmith pull request #22215
Opened 2023-04-10 09:01 UTC by sum35h

## Description
Added Appsmith Initializing and Starting pages to inform the users that Appsmith is starting up and they will need to wait for a few minutes before their Appsmith deployment is up and running, instead of displaying the 503 error like it earlier.

## Type of change
- New feature (non-breaking change which adds functionality)

# Media
Initialization page
![image](https://user-images.githubusercontent.com/20785806/230869925-a342e327-c714-4cfa-8283-cf6f5bd225b5.png)

Starting page
![image](https://user-images.githubusercontent.com/20785806/230869770-67654c0a-e4de-4d18-83dd-9f68230648e9.png)

## How Has This Been Tested?
- Manual

2023-04-11 04:03 UTC, sharat87 requested changes

2023-04-11 04:03 UTC, sharat87 commented on deploy/docker/scripts/supervisor_event_listener.py
> +    sys.stdout.flush()
Make your life easier. 🙂

*Note* that with this change, you don't need the `\n` characters when calling `write_stdout`. The `print` function will do it for you.

```suggestion
def write_stdout(*args):
    # only eventlistener protocol messages may be sent to stdout
    print(*args, flush=True)
```

2023-04-11 04:03 UTC, sharat87 commented on deploy/docker/scripts/supervisor_event_listener.py
> +    sys.stderr.flush()
Here too. 🙂

```suggestion
def write_stderr(*args):
    print(*args, flush=True, file=sys.stderr)
```

2023-04-11 10:56 UTC, sum35h commented on deploy/docker/scripts/supervisor_event_listener.py
> +    sys.stdout.flush()
I tried running the script with the changes but the event stream did not work.
I think in some cases the output streams don't need the newline to communicate to the supervisor that it is ready.

2023-04-11 10:57 UTC, sum35h commented on deploy/docker/scripts/supervisor_event_listener.py
> +    sys.stderr.flush()
I tried running the script with the changes but the event stream did not work.
I think in some cases the output streams don't need the newline to communicate to the supervisor that it is ready.

2023-04-12 06:23 UTC, sharat87 commented
@sum35h, a few more pointers on this please.

1. Increase timeout to 5mins.
2. Add a message in this loading page, that "this may take ~5mins".
3. Add change in docs, instead of asking users to wait for "Appsmith is Running", let's ask them to open the browser, so they can see this message and wait.

2023-04-12 06:30 UTC, sharat87 requested changes
Few more suggestions.

2023-04-12 06:30 UTC, sharat87 commented on deploy/docker/scripts/supervisor_event_listener.py
> +        if line.__contains__('PROCESS_STATE_STARTING'):
```suggestion
        if 'PROCESS_STATE_STARTING' in line:
```

2023-04-12 06:30 UTC, sharat87 commented on deploy/docker/scripts/supervisor_event_listener.py
> +        elif line.__contains__('PROCESS_STATE_RUNNING'):
```suggestion
        elif 'PROCESS_STATE_RUNNING' in line:
```

2023-04-12 06:30 UTC, sharat87 commented on deploy/docker/scripts/supervisor_event_listener.py
> +        elif line.__contains__('PROCESS_STATE_FATAL'):
```suggestion
        elif 'PROCESS_STATE_FATAL' in line:
```

2023-04-12 06:30 UTC, sharat87 commented on deploy/docker/scripts/supervisor_event_listener.py
> +        headers = dict([ x.split(':') for x in line.split() ])
Ensure that the split is done exactly _once_. If the message contains `:` characters, we don't want it to split further, as the `dict` constructor expects 2-tuplis in the iterator.

We also don't need the `[]`, since `dict` can take a generator expression.

There's a few other places we can make this change too.

```suggestion
        headers = dict(x.split(':', 1) for x in line.split())
```

2023-04-12 06:30 UTC, sharat87 commented on deploy/docker/scripts/supervisor_event_listener.py
> +    while 1:
```suggestion
    while True:
```

2023-04-13 09:21 UTC, sum35h commented
/build-deploy-preview

2023-04-17 10:45 UTC, sum35h commented on deploy/docker/scripts/supervisor_event_listener.py
> +    timeout_sec = 45
```suggestion
    timeout_sec = 120
```

2023-04-17 10:46 UTC, sum35h commented on deploy/docker/templates/appsmith_starting.html
> +      <p>Please wait until Appsmith is ready. This should take less than a minute.</p>
```suggestion
      <p>Please wait until Appsmith is ready. This should about a minute.</p>
```

2023-04-18 03:42 UTC, mohanarpit commented on deploy/docker/templates/appsmith_starting.html
> +      href="https://res.cloudinary.com/dwpfockn8/image/upload/v1597920848/favicons/favicon-orange_pxfmdc.ico"
Instead of using Cloudinary URLs, can we use assets.appsmith.com endpoint for all assets? This makes it easy for us to change CDN providers without the fear of breaking anything.

2023-04-18 03:42 UTC, mohanarpit commented on deploy/docker/templates/appsmith_starting.html
> +        Appsmith is Starting.
Nit: Please use sentence casing in all user visible text. 
```suggestion
        Appsmith is starting.
```

2023-04-18 03:43 UTC, mohanarpit commented on deploy/docker/templates/appsmith_starting.html
> +      <p>Please wait until Appsmith is ready. This should about a minute.</p>
```suggestion
      <p>Please wait until Appsmith is ready. This process usually takes a minute. </p>
```

2023-04-18 03:44 UTC, mohanarpit commented on deploy/docker/templates/appsmith_initializing.html
> +        Please Wait
```suggestion
        Please wait 
```

2023-04-18 05:50 UTC, sum35h commented on deploy/docker/templates/appsmith_starting.html
> +      href="https://res.cloudinary.com/dwpfockn8/image/upload/v1597920848/favicons/favicon-orange_pxfmdc.ico"
cc @akash-codemonk

2023-04-18 06:54 UTC, sum35h commented on deploy/docker/templates/appsmith_starting.html
> +      href="https://res.cloudinary.com/dwpfockn8/image/upload/v1597920848/favicons/favicon-orange_pxfmdc.ico"
```suggestion
      href="https://assets.appsmith.com/appsmith-favicon-orange.ico"
```

2023-04-18 06:54 UTC, sum35h commented on deploy/docker/templates/appsmith_initializing.html
> +      href="https://res.cloudinary.com/dwpfockn8/image/upload/v1597920848/favicons/favicon-orange_pxfmdc.ico"
```suggestion
      href="https://assets.appsmith.com/appsmith-favicon-orange.ico"
```

2023-04-19 10:49 UTC, sharat87 approved these changes

2023-04-19 12:51 UTC, merged