feat: deduplicate datasources
appsmithorg/appsmith pull request #22250
Opened 2023-04-11 02:21 UTC by tanvibhakta

## Description

Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.
> Delete anything that is not important

- Manual
- Jest
- Cypress

### Test Plan
> Add Testsmith test cases links that relate to this PR

### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)

## Checklist:
### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2023-04-11 15:04 UTC, tanvibhakta commented
/build-deploy-preview env=release

2023-04-11 19:05 UTC, albinAppsmith commented on app/client/src/pages/Editor/DataSourceEditor/BackButton.tsx
> -    history.push(redirectURL, { invokedBy: NavigationMethod.ActionBackButton });
You should not remove invokedBy here.

2023-04-11 19:10 UTC, albinAppsmith commented
<img width="133" alt="Screenshot 2023-04-12 at 12 37 51 AM" src="https://user-images.githubusercontent.com/87797149/231264453-b0ff7b2c-c6ba-4139-b65d-d5c020e9fba4.png">
<img width="168" alt="Screenshot 2023-04-12 at 12 37 46 AM" src="https://user-images.githubusercontent.com/87797149/231264567-18d336ca-8736-484e-b9bf-ca4023a8c538.png">

Please make this consistent. As per design it should be the second one <-

2023-04-11 19:10 UTC, albinAppsmith requested changes
Make necessary changes as per comments.

2023-04-12 02:15 UTC, tanvibhakta commented on app/client/src/pages/Editor/DataSourceEditor/BackButton.tsx
> -    history.push(redirectURL, { invokedBy: NavigationMethod.ActionBackButton });
we're not using history at all here, because this function is returning a url that the href in our link is handling. If I leave this line in  _and_ return a url, there is an additional push that sits on top of the history stack that overrides other links in the page that we went back to. Is there a way to add `invokedBy` to an a tag directly?

2023-04-12 02:36 UTC, tanvibhakta commented
/build-deploy-preview env=release

2023-04-12 02:45 UTC, albinAppsmith commented on app/client/src/pages/Editor/DataSourceEditor/BackButton.tsx
> -    history.push(redirectURL, { invokedBy: NavigationMethod.ActionBackButton });
As far as I know, this will add a query param to the url `?invokedBy=<value>`. You can append this in URL. But please ensure this is the behaviour.

2023-04-12 06:43 UTC, tanvibhakta commented
/build-deploy-preview env=release

2023-04-12 06:59 UTC, tanvibhakta commented on app/client/src/pages/Editor/DataSourceEditor/BackButton.tsx
> -    history.push(redirectURL, { invokedBy: NavigationMethod.ActionBackButton });
This is helpful, thanks!

2023-04-13 01:08 UTC, tanvibhakta commented
/build-deploy-preview env=release

2023-04-15 06:24 UTC, laveena-en commented
1. Chevron arrows to be used in the `Show more/less` as given in [design](https://zpl.io/09xr6mx)
2.`Back` to be changed to `Go back` [design](zpl.io/09xr6mx)
3. Icon next to edit is missing
![image](https://user-images.githubusercontent.com/109572422/232190056-36e044b3-171c-4ea0-8982-52994d4a619d.png)
4. Also, there seems to be some unnecessary space towards the right and bottom of the component given there's no scroll.
5. The arrow next to `Back` doesn’t seem to be center aligned to the text. Can we bring it a couple of px below?
![image](https://user-images.githubusercontent.com/109572422/232190185-d1190c4e-6040-46b2-bb95-fda05e3dd19e.png)
6. An extra header line is present below the tabs
![image](https://user-images.githubusercontent.com/109572422/232190232-4de55e5f-9463-456a-940a-1c12318f279b.png)
7. The title `Datasources` font size is 20px but 24px in [design](https://zpl.io/09xr6mx)
Also just an FYI, not related to this PR, on clicking on `Delete` query, we're being directed to the edit screen

2023-04-18 02:55 UTC, tanvibhakta commented
> there seems to be some unnecessary space
I'm unable to reproduce this on firefox or chrome, could you please check if it's gone by me updating packages? 
<img width="153" alt="Screenshot 2023-04-18 at 8 17 52 AM" src="https://user-images.githubusercontent.com/13763558/232657827-9ec92a4a-f507-48ce-ad6f-07f34960f4cb.png">

> The arrow next to Back doesn’t seem to be center aligned to the text.
This component is coming fully from [the storybook](https://design-system.appsmith.com/?path=/story/design-system-link--internal-link&args=kind:secondary;children:Go+back;endIcon:;startIcon:arrow-left-line). I checked the spacing regardless and it's fully centered by flex. It might seem a tiiiny bit off because of odd number heights and also the eye's baseline perception. I don't think there's anything else to do here.
<img width="864" alt="Screenshot 2023-04-18 at 8 20 21 AM" src="https://user-images.githubusercontent.com/13763558/232658411-63ad72c9-1dbc-45ff-b048-d22801a1d6eb.png">

> An extra header line is present below the tabs
This should be fixed by me updating the packages

> The title Datasources font size is 20px but 24px in design
Font size changes are not in the scope of this project. For that matter, neither are icon changes or copy changes.

I've fixed everything else, please have another look.

2023-04-18 03:39 UTC, tanvibhakta commented
/build-deploy-preview env=release

2023-04-18 05:00 UTC, albinAppsmith commented on app/client/src/components/utils/CollapseComponent.tsx
> +    //justify-content: space-between;
Remove this

2023-04-18 05:02 UTC, albinAppsmith commented
<img width="147" alt="Screenshot 2023-04-18 at 10 31 40 AM" src="https://user-images.githubusercontent.com/87797149/232675810-739327f6-85b6-4107-8b3e-af2dc9871720.png">

Is this text change a decision made by design team? Else, can you revert this to back? Since all other pages are using back.

2023-04-18 05:19 UTC, albinAppsmith commented on app/client/src/pages/Editor/DataSourceEditor/BackButton.tsx
> +      Go back
Why is this text change?

2023-04-18 05:54 UTC, tanvibhakta commented on app/client/src/pages/Editor/DataSourceEditor/BackButton.tsx
> +      Go back
Because @laveena-en asked me to do it because the design screens are like this.

2023-04-18 06:01 UTC, albinAppsmith commented on app/client/src/pages/Editor/gitSync/components/GitChangesList.tsx
> +export function Change(props: GitStatusProps) {
why you removed partial

2023-04-18 06:05 UTC, albinAppsmith commented on app/client/src/pages/Editor/gitSync/components/GitChangesList.tsx
> +export function Change(props: GitStatusProps) {
This will make all parameters mandatory

2023-04-18 06:06 UTC, albinAppsmith commented on app/client/src/pages/Templates/ForkTemplate.tsx
>          // headerIcon={{ name: "fork-2", bgColor: Colors.GEYSER_LIGHT }}
remove this

2023-04-18 06:07 UTC, albinAppsmith requested changes
Please address the comments

2023-04-18 10:46 UTC, tanvibhakta commented on app/client/src/pages/Editor/DataSourceEditor/BackButton.tsx
> +      Go back
Have reverted as per design

2023-04-18 10:47 UTC, tanvibhakta commented on app/client/src/pages/Editor/gitSync/components/GitChangesList.tsx
> +export function Change(props: GitStatusProps) {
yes - in all the usages all parameters are passed, and we need the icon name to render the icon.

2023-04-18 10:48 UTC, tanvibhakta commented on app/client/src/pages/Templates/ForkTemplate.tsx
>          // headerIcon={{ name: "fork-2", bgColor: Colors.GEYSER_LIGHT }}
The comments are not changes in my PR, these are fixes we have all had to make as a result of the API changes in modal in the design-system. When the templates page gets merged this will be fine.

2023-04-18 10:52 UTC, tanvibhakta commented
/build-deploy-preview env=release

2023-04-19 05:09 UTC, albinAppsmith commented on app/client/src/pages/Editor/gitSync/components/GitChangesList.tsx
> +export function Change(props: GitStatusProps) {
Are you sure this won't break anything?

2023-04-19 05:12 UTC, albinAppsmith commented on app/client/src/pages/Editor/DataSourceEditor/BackButton.tsx
>  `;
Why are we altering padding of design system component?

2023-04-19 05:29 UTC, albinAppsmith commented on app/client/src/pages/Templates/ForkTemplate.tsx
>          // headerIcon={{ name: "fork-2", bgColor: Colors.GEYSER_LIGHT }}
Got it

2023-04-20 17:10 UTC, tanvibhakta commented on app/client/src/pages/Editor/DataSourceEditor/BackButton.tsx
>  `;
used margin instead.

2023-04-20 17:11 UTC, tanvibhakta commented
/build-deploy-preview env=release

2023-04-21 05:06 UTC, albinAppsmith commented on app/client/src/pages/Editor/GuidedTour/Guide.tsx
> +              name={info.icon || ""}
This condition is not necessary since you are already checking for icon exist

2023-04-21 05:07 UTC, albinAppsmith requested changes
Address the comments

2023-04-21 05:10 UTC, albinAppsmith commented
Is designers okay with this icon alignment?
<img width="640" alt="Screenshot 2023-04-21 at 10 39 49 AM" src="https://user-images.githubusercontent.com/87797149/233545860-80bc2484-86e4-40c5-9030-8d2971c849e3.png">

2023-04-21 05:13 UTC, albinAppsmith commented
Clicking on delete is not working, it is taking to edit data source page.
<img width="435" alt="Screenshot 2023-04-21 at 10 42 51 AM" src="https://user-images.githubusercontent.com/87797149/233546168-3063aa65-5860-42a8-b75f-2a18988eec1f.png">

2023-04-21 05:14 UTC, albinAppsmith commented
Clicking on generate new page is also not working, same as delete. This also taking to edit datasource page.
<img width="1330" alt="Screenshot 2023-04-21 at 10 44 00 AM" src="https://user-images.githubusercontent.com/87797149/233546287-cd17ee6d-4275-4615-baca-2c97b2690529.png">

2023-04-23 10:00 UTC, merged

2023-04-28 05:24 UTC, laveena-en commented
1. Sentence casing is required for: Create New -> Create new
New Query -> New query
![image](https://user-images.githubusercontent.com/109572422/235060956-c6fd29de-99f8-4b79-afec-f5ff83d21099.png)
![image](https://user-images.githubusercontent.com/109572422/235060988-14872360-050e-4421-a874-c092159391c0.png)
![image](https://user-images.githubusercontent.com/109572422/235061073-2fff244c-897f-4a63-9ce8-beafd6da88eb.png)

2. Text to be seen in red for Delete, Are you sure and Deleting 
![image](https://user-images.githubusercontent.com/109572422/235061195-0364117e-4819-4a02-93c9-0060b146e490.png)

3. Two tooltips are seen when deletion fails https://www.loom.com/share/354d2f2abf204801a9f66f1defcc7ffa
4. On clicking back, we're being navigated to the home page instead of the canvas https://www.loom.com/share/a290b3778edf4a3290f13c95b0ddac48