fix: Refactored homepage with new Design System components
appsmithorg/appsmith pull request #22308
Opened 2023-04-12 05:26 UTC by albinAppsmith

## Description

This PR has updated old design system components with new components. Also, updated colors of gray and texts.

Fixes # (issue)
https://github.com/appsmithorg/appsmith/issues/19386

Media

https://user-images.githubusercontent.com/87797149/231407141-55215a47-24da-49ac-aadb-c40e5b5815ff.mov

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.
> Delete anything that is not important

- Manual
- Jest
- Cypress

### Test Plan
> Add Testsmith test cases links that relate to this PR

### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)

## Checklist:
### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2023-04-12 06:46 UTC, tanvibhakta commented
/build-deploy-preview env=release

2023-04-12 06:58 UTC, tanvibhakta requested changes

2023-04-12 06:58 UTC, tanvibhakta commented on app/client/src/ce/pages/Applications/index.tsx
> +                                data-testid="t--workspace-setting"
update relevant cypress tests

2023-04-12 06:58 UTC, tanvibhakta commented on app/client/src/ce/pages/Home/LeftPaneBottomSection.tsx
> +      <MenuItem
Why are we using old menu here?

2023-04-12 06:58 UTC, tanvibhakta commented on app/client/src/pages/Applications/ApplicationCard.tsx
> +// const MoreOptionsContainer = styled.div`
remove if unused?

2023-04-12 06:58 UTC, tanvibhakta commented on app/client/yarn.lock
> +"babel-plugin-styled-components@>= 1.12.0", babel-plugin-styled-components@^2.0.7:
remove and regenerate

2023-04-12 07:49 UTC, albinAppsmith commented on app/client/src/ce/pages/Applications/index.tsx
> +    <ListItem
There is no list item component in new ADS... this is not a menu.

2023-04-12 07:50 UTC, albinAppsmith commented on app/client/src/ce/pages/Applications/index.tsx
> +                        <MenuTrigger>
Good catch

2023-04-12 07:51 UTC, albinAppsmith commented on app/client/src/ce/pages/Applications/index.tsx
> +                        data-testid="t--workspace-name"
That is in a separate PR

2023-04-12 07:52 UTC, albinAppsmith commented on app/client/src/pages/Applications/ApplicationCard.tsx
> +// const MoreOptionsContainer = styled.div`
Done

2023-04-12 07:52 UTC, albinAppsmith commented on app/client/craco.dev.config.js
> +  },
Done

2023-04-12 07:52 UTC, albinAppsmith commented on app/client/package.json
> +    "babel-plugin-styled-components": "^2.0.7",
Done

2023-04-12 07:54 UTC, albinAppsmith commented
/build-deploy-preview env=release

2023-04-12 08:24 UTC, tanvibhakta commented on app/client/src/ce/pages/Applications/index.tsx
> +    <ListItem
Ah my bad

2023-04-12 08:38 UTC, tanvibhakta approved these changes

2023-04-12 08:57 UTC, albinAppsmith commented
/build-deploy-preview env=release

2023-04-12 12:36 UTC, vasanth-appsmith commented
https://user-images.githubusercontent.com/92305123/231458625-c8df0989-d612-4235-b1d3-1beb869ad4db.mov

1. Menu opens and closed with a 2-3 sec delay.

2023-04-22 06:31 UTC, albinAppsmith commented
/build-deploy-preview env=release

2023-04-22 07:03 UTC, merged