feat: adding email property in google sheets
appsmithorg/appsmith pull request #22321
Opened 2023-04-12 08:32 UTC by sondermanish

## Description
As a part of google sheet scope limitation, the email address is being added in datasource configuration.  The email address 
is being stored in a property, an element in properties (`List<Property>`) with key: 'emailAddress' and value: (<emailId>) .

In order to retrieve this property a GET call to endpoint `https://www.googleapis.com/drive/v3/about?fields=user` is being made.

This property is being saved while google sheet datasource gets authorised, after access toke retrieval from cloud services.
in the endpoint `/saas/{datasourceId}/token`.

Since the flow is specific to google sheets, the main code is implemented in googlesheetPluginExecutor. The flow has three steps

- Getting access token from datasourceConfiguration
- making the call to googleApis and obtaining the email address
- saving it back into datasource configuration

The authorisation flow itself saves the datasource later on.  

> TL;DR Adding emailAddress in properties of datasource configuration when google sheets is authorised.

Fixes #21902 
- New feature (non-breaking change which adds functionality)

## This has been tested
- Manual

## Checklist:
### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

2023-04-18 08:24 UTC, sumitsum requested changes

2023-04-18 08:24 UTC, sumitsum commented on app/server/appsmith-plugins/googleSheetsPlugin/src/test/java/com/external/config/GetDatasourceMetadataMethodTest.java
> +    public void DsConfigPropertiesWithNoEmailTest() {
Can you please rename both test names to something that indicates in a more understandable way what the test is doing - e.g. something along the lines of `testGetUserEmailWhenPropertiesListIsEmpty()` ?

2023-04-18 08:24 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/AuthenticationServiceCEImpl.java
> +                                return featureFlagService.check(FeatureFlagEnum.LIMITING_GOOGLE_SHEET_ACCESS)
Minor: Should we instead wrap the feature flag specific code inside the `if` clause and leave the default implementation out ? This should be useful when say another feature flag specific change needs to be added here, in which case we can use another `if` clause so overall it will look like: 
```
if (featureFlag_1) {...}
if (featureFlag_2) {...}
if (featureFlag_3) {...}
default implementation
```

2023-04-20 10:28 UTC, sumitsum commented on app/server/appsmith-plugins/googleSheetsPlugin/src/test/java/com/external/config/GetDatasourceMetadataMethodTest.java
> +    public void verifyEmailUsageSamePropertyObjectForStorage() {
Hi Manish, this is something very minor, hence it is not a binding requirement, I would still approve the code, however, I just want to mention that the name this method name is still not understandable at all. e.g. could this be a more suggestive name : `verifyIfOldEmailGetsReplacedWhenUpdatedWithNewEmail`

2023-04-20 10:28 UTC, sumitsum approved these changes

2023-04-20 12:34 UTC, sondermanish commented
/ok-to-test sha=1014d1a

2023-04-20 13:46 UTC, sumitsum approved these changes

2023-04-21 05:24 UTC, sondermanish commented
/ci-merge-check

2023-04-21 05:44 UTC, sondermanish commented
/ok-to-test sha=1014d1a

2023-04-21 08:47 UTC, nidhi-nair approved these changes

2023-04-21 08:47 UTC, merged