task: [Design System V2] Update buttons in the bottom bar
appsmithorg/appsmith pull request #22356
Opened 2023-04-13 07:30 UTC by hetunandu

## Description

Fixes the buttons in the bottom bar right corner with the new DS buttons

2023-04-17 06:51 UTC, rohitagarwal88 commented
@hetunandu : Changes look good, only change is to dedup dropdown with Menu component
<img width="278" alt="Screenshot 2023-04-17 at 12 20 52 PM" src="https://user-images.githubusercontent.com/890915/232406497-474d0dec-657e-465e-b5a5-e63cab9ede3e.png">

2023-04-17 06:59 UTC, rohitagarwal88 requested changes

2023-04-17 06:59 UTC, rohitagarwal88 commented on app/client/src/components/editorComponents/Debugger/index.tsx
> -        <div className="debugger-count t--debugger-count">
@hetunandu : Please do not remove `t--debugger` class. It is used in the cypress test.

2023-04-17 06:59 UTC, rohitagarwal88 commented on app/client/src/pages/Editor/HelpButton.tsx
>        <Popover
@hetunandu : Can popover with our ADS 2.0 menu component? 

https://design-system.appsmith.com/?path=/story/design-system-menu--menu-story

2023-04-17 11:15 UTC, hetunandu commented
/build-deploy-preview env=release

2023-04-17 11:16 UTC, hetunandu commented on app/client/src/pages/Editor/HelpButton.tsx
>        <Popover
Updated

2023-04-17 11:16 UTC, hetunandu commented on app/client/src/components/editorComponents/Debugger/index.tsx
> -        <div className="debugger-count t--debugger-count">
Not removed. Just moved it to another place

2023-04-17 12:27 UTC, rohitagarwal88 commented on app/client/src/components/editorComponents/Debugger/index.tsx
> -        className="t--debugger"
Sry @hetunandu, tagged the wrong code,  Is this in another file? 
https://github.com/appsmithorg/appsmith/pull/22356/files/a68e462d63bbc345b24c19d4917bd13ab982d36c#r1168257182

2023-04-19 10:39 UTC, hetunandu commented
/build-deploy-preview env=release

2023-04-20 08:58 UTC, hetunandu commented
/build-deploy-preview env=release

2023-04-21 06:58 UTC, albinAppsmith commented
I see in release the bottom count button is red and in DP it is gray... Is it okay?
<img width="272" alt="Screenshot 2023-04-21 at 12 27 28 PM" src="https://user-images.githubusercontent.com/87797149/233563404-2386cc35-bc06-40dd-b968-ad47c6ef1332.png">

2023-04-21 06:58 UTC, albinAppsmith commented on app/client/src/components/editorComponents/Debugger/index.tsx
> +        color={"red"}
Button do not have a color prop

2023-04-21 07:00 UTC, albinAppsmith commented on app/client/src/pages/Editor/HelpButton.tsx
> +  border-top: 1px solid ${Colors.ALTO};
Please update the border color with `var(--ads-v2-color-border)`

2023-04-21 07:01 UTC, albinAppsmith commented on app/client/src/pages/Editor/HelpButton.tsx
> +  color: ${Colors.DOVE_GRAY2};
Please update color with `var(--ads-v2-color-fg)`

2023-04-21 11:21 UTC, hetunandu commented
/build-deploy-preview env=release

2023-04-23 19:48 UTC, albinAppsmith approved these changes

2023-04-23 20:03 UTC, merged

2023-04-26 04:27 UTC, laveena-en commented
1. Tooltip is missing for Help 
![image](https://user-images.githubusercontent.com/109572422/234469436-a20fdb95-2174-44f4-b442-f89949601cb2.png)
2. Go-to icon to be seen on hover and not as a static icon 
![image](https://user-images.githubusercontent.com/109572422/234469547-8e62df1e-c26b-4a23-a6ac-295bd4afd430.png)
3. Tooltip isn’t getting dismissed https://www.loom.com/share/698bd5a33ec349a982ccd592044ef6f8
4. Pointer cursor required on hovering over the update icon.
![image](https://user-images.githubusercontent.com/109572422/234469720-752aa16e-b5b5-414d-8288-30134a88463a.png)
5. Ellipses and a tooltip is required when the branch name is very long https://www.loom.com/share/1758b634e9a14d7da277a717e17845c5
6. Heading colours are not as per ADS2.0. Added more details here: https://www.notion.so/appsmith/Heading-colours-are-not-as-per-ADS2-0-2d695457152f40af93a7ad40c2a762e5?pvs=4
7. Size and padding of the update icon looks off, can we add in some padding and make the size consistent 
![image](https://user-images.githubusercontent.com/109572422/234469985-8d333370-4bec-414d-a474-8dc5cefa2cb3.png)