fix: Meta Hydration Test
appsmithorg/appsmith pull request #22382
Opened 2023-04-13 12:26 UTC by Tooluloope

## Description
Fix Meta Hydration Tests in ListV2

Fixes #22252

Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video

## Type of change
- Chore (housekeeping or task changes that don't impact user perception)

## How Has This Been Tested?

- Cypress

### Test Plan
> Add Testsmith test cases links that relate to this PR

### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)

## Checklist:
### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2023-04-13 12:27 UTC, Tooluloope commented
/ok-to-test sha=33299e5

2023-04-13 13:38 UTC, yatinappsmith requested changes
Avoid using thirdparty api. Instead use TED

2023-04-17 12:03 UTC, Tooluloope commented
/ok-to-test sha=02a2c21

2023-04-17 15:02 UTC, Tooluloope commented
/ok-to-test sha=17eb610

2023-04-18 17:09 UTC, Tooluloope commented
/ok-to-test sha=60be657

2023-04-18 18:46 UTC, Tooluloope commented
> Workflow run: https://github.com/appsmithorg/appsmith/actions/runs/4735099721. Commit: `60be657`. The following are new failures, please fix them before merging the PR:
> 
> 1. cypress/integration/Regression_TestSuite/ServerSideTests/OnLoadTests/JSOnLoad1_Spec.ts
> 
> 
> To know the list of identified flaky tests - [Refer here](https://app.appsmith.com/applications/613868bedd7786286ddd4a6a/pages/63ec710e8e503f763651791a)

@yatinappsmith DefaultSelectedItem is passing.

Running the tests again

2023-04-18 18:46 UTC, Tooluloope commented
/ok-to-test sha=60be657

2023-04-19 00:17 UTC, yatinappsmith requested changes
To skip the test please add it cypress.json

2023-04-19 00:27 UTC, Tooluloope commented
/ok-to-test sha=9f22b7f

2023-04-20 03:31 UTC, yatinappsmith submitted a review, later dismissed

2023-04-20 07:51 UTC, Tooluloope commented
/ok-to-test sha=84a7f03

2023-04-20 12:41 UTC, Tooluloope commented
/ok-to-test sha=40a5b0e

2023-04-20 16:14 UTC, Tooluloope commented
/ok-to-test sha=56faeb7

2023-04-21 05:37 UTC, yatinappsmith approved these changes

2023-04-21 05:46 UTC, Aishwarya-U-R commented on app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Widgets/ListV2/Listv2_Meta_Hydration_ServerSide_spec.js
> +describe.skip("List widget v2 - meta hydration tests", () => {
Please also consider adding the reason for skipping it. To not loose track of the reason.

2023-04-21 06:59 UTC, Tooluloope commented
/ok-to-test sha=a56156a

2023-04-24 06:55 UTC, Tooluloope commented
/ok-to-test sha=31bac42

2023-04-24 07:26 UTC, Tooluloope commented
/ok-to-test sha=31bac42

2023-04-24 09:04 UTC, merged