feat: enable datasource reconnection while forking application
appsmithorg/appsmith pull request #22390
Opened 2023-04-13 15:47 UTC by NilanshBansal

## Description
> This PR sets a field `isPartialImport` in the `/{defaultApplicationId}/fork/{workspaceId}` POST API response, based on which the client will show the reconnection modal.
> If the `isPartialImport` field is True, the client has to show the reconnection modal. 
> Earlier, this field was only added as part of the Import flow and not the forking flow, hence the reconnect datasource modal was only shown while importing an app from JSON when datasource credentials are not present.

This PR will solve the following issues: 

1. Create a new field `forkWithConfiguration` that will represent whether datasource credentials will be shared while forking or not. Issue #21691 (Initial PR #22157, but had to be closed due to the reconnection modal functionality, not being present in the forking code)
2. Enable Reconnection Datasource Modal while forking an app if datasource credentials are not shared. Issue #22305 
3. Reset flags `forkWithConfiguration` and `exportWithConfiguration` to False when forking/cloning/exporting an app. Issues #22165 #22166 

Fixes #22305 

## Type of change

> Please delete options that are not relevant.

- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.
> Delete anything that is not important

- Manual
- Jest
- Cypress

### Test Plan
> Add Testsmith test cases links that relate to this PR

### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)

## Checklist:
### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2023-04-24 09:38 UTC, akash-codemonk commented
/build-deploy-preview

2023-04-24 09:47 UTC, akash-codemonk commented
/build-deploy-preview

2023-04-24 10:16 UTC, akash-codemonk commented
/build-deploy-preview skip-tests=true

2023-04-24 18:56 UTC, NilanshBansal commented
/ok-to-test sha=8cdea413f6805c929ce6e652aa9e8ec86c70030e

2023-04-25 11:25 UTC, NilanshBansal commented
/ok-to-test sha=4f7d70c1ccda161beb0050a2718b4ba8e2347fb8

2023-04-25 16:21 UTC, NilanshBansal commented
/build-deploy-preview skip-tests=true

2023-04-26 05:50 UTC, akash-codemonk commented
/build-deploy-preview

2023-04-26 06:34 UTC, nayan-rafiq requested changes

2023-04-26 06:34 UTC, nayan-rafiq commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ApplicationForkingServiceImpl.java
> +                                         ImportExportApplicationServiceCEImplV2 importExportApplicationServiceCEImplV2) {
Instead of using the `ImportExportApplicationServiceCEImplV2` we need to use the interface instead.

2023-04-26 09:49 UTC, nayan-rafiq submitted a review, later dismissed
LGTM

2023-04-28 04:48 UTC, akash-codemonk commented
/ok-to-test

2023-05-03 09:19 UTC, hetunandu submitted a review, later dismissed
FE changes looks good

2023-05-08 18:17 UTC, nayan-rafiq commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/AuthenticationResponse.java
> +@EqualsAndHashCode
Why we're adding equals and hash code methods?

2023-05-09 04:42 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ExamplesWorkspaceClonerCEImpl.java
> +                                if (!Boolean.TRUE.equals(forkWithConfiguration)){
Is it possible to move this logic to datasources itself? It will reduce the clutter in this flow, and make sure that each datasource configuration type is handling its own forking logic.

2023-05-09 04:49 UTC, NilanshBansal commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/AuthenticationResponse.java
> +@EqualsAndHashCode
To compare the existing Gsheet datasource in the target workspace with the new Gsheet datasource from the source application. 
If the AuthenticationResponse is also same, then the Gsheet datasource is already present in the target workspace, hence we don't need to copy the source datasource in this case. 
This is used in the `softEquals` function in Datasource.java which is invoked from `cloneDatasource` function in ExamplesWorkspaceClonerCEImpl.java

2023-05-09 05:24 UTC, NilanshBansal commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ExamplesWorkspaceClonerCEImpl.java
> +                                if (!Boolean.TRUE.equals(forkWithConfiguration)){
Sure @nidhi-nair, can you pls help on how this can be done?

2023-05-09 05:26 UTC, NilanshBansal commented
/build-deploy-preview skip-tests=true

2023-05-10 05:06 UTC, eco-monk submitted a review, later dismissed
FE changes look good to me.

2023-05-10 08:55 UTC, nidhi-nair commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/Datasource.java
> +        }
Nit: Formatting issue

2023-05-10 08:56 UTC, nidhi-nair commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/Datasource.java
> +    /**
Nit: Please add this doc comment to the interface itself for future consumption. Maybe break it down into datasource specific and generic description. Also please make use of `@Override`

2023-05-10 11:38 UTC, NilanshBansal commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/Datasource.java
> +            newDs.setIsConfigured(isConfigured);
for all the other datasources except for Gsheets, the authenticationResponse is always null, as authenticationResponse contains the tokens which are not present for other datasources as they work on username and password.

2023-05-10 11:56 UTC, nidhi-nair commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/Datasource.java
> +            newDs.setIsConfigured(isConfigured);
Authentication response will also exist for any other datasource that implements OAuth2 auth flow. Also, what happens in the case of a GSheets datasource that just got created, isn't authenticated and hence does not have a response? What is the isConfigured flag doing here?

2023-05-10 12:20 UTC, nidhi-nair commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/Datasource.java
> +            newDs.setIsConfigured(isConfigured);
Understood, in that case would it make sense for us to have `AuthenticationDTO` types also implement this function, so that we can determine when to set this to false accurately? For instance, in the same example as above, since Gsheets was not authenticated, the response ends up being null. But `isConfigured` remains true from the initial condition, and we would not see the reconnect option. Please let me know if I am misunderstanding something here.

2023-05-11 10:00 UTC, nidhi-nair approved these changes

2023-05-11 10:04 UTC, NilanshBansal commented
/build-deploy-preview skip-tests=true

2023-05-11 16:53 UTC, nidhi-nair approved these changes

2023-05-12 04:25 UTC, merged