fix: Checking for stale connection when Oauth token expires (#21769)
appsmithorg/appsmith pull request #22406
Opened 2023-04-14 04:25 UTC by sanveer-osahan

## Description
For checking if the connection is stale or not for authenticated api, only the datasource `updatedAt` field was checked.
If `updatedAt` time is greater than connection `creationTime`, the connection is considered stale.
Added an additional check for Oauth token expiry. If token is expired, the connection will be considered stale and a new connection will be created using the `refresh_token` 

Fixes #21769

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manual

## Checklist:
### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2023-04-14 04:29 UTC, sanveer-osahan commented
/ok-to-test sha=d3fa1b5

2023-04-17 08:33 UTC, sanveer-osahan commented
/ok-to-test sha=c4346d1

2023-04-18 05:48 UTC, sumitsum requested changes

2023-04-18 05:48 UTC, sumitsum commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/AuthenticationDTO.java
> +    public boolean isExpired() {
Can you please add a comment here explaining that this method has primarily been added to check if OAuth token has expired ?

2023-04-18 05:48 UTC, sumitsum commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/OAuth2.java
> +        return this.authenticationResponse == null
Is there any reason for adding the first 2 conditions checking for null ? IMO, the first condition implies a failure of authentication and the second null check implies that the authentication didn't have refresh scope.

2023-04-18 05:48 UTC, sumitsum commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/OAuth2.java
> +                || this.authenticationResponse.expiresAt == null
Can you please refactor the `OAuth2ClientCredentials.java` and `OAuth2AuthorizationCode.java` files and replace with this function anywhere a check for expiry is being done ?

2023-04-18 05:48 UTC, sumitsum commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/plugins/BaseRestApiPluginExecutor.java
> +    public boolean isConnectionStale(DatasourceConfiguration datasourceConfiguration) {
Can you please change the method name to `isAuthenticationExpired` ? One reason being that `isConnectionStale` implies that we are checking the connection object, but here we are only passing the datasource config as parameter, not the actual connection object or datasourceContext object. Another reason being that in some datasources like MySQL we do a stale connection check during the action execution code flow and this function name might confuse someone with that flow. Please mention if you think otherwise.

2023-04-18 05:48 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceContextServiceCEImpl.java
> +        return getIsStale(datasource, datasourceContextIdentifier)
QQ: Could we only have one implementation / definition of the method ?

2023-04-18 05:48 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceContextServiceCEImpl.java
> +                    && pluginExecutor.isConnectionStale(datasource.getDatasourceConfiguration()));
Also, as discussed, please add a JUnit TC for this. IMO, adding a TC for the `getStale` method should be ok here. One way to do this would be to create and configure a new datasource config object within the test case and pass the same to the getStale method. We should be able to get rest api plugin executor object via :
```
plugin = pluginRepository.findByPackageName("restapi-plugin").block()
// now use  pluginExecutorHelper.getPluginExecutor(...) to get pluginExecutor object using plugin id.
```

2023-04-18 06:57 UTC, sanveer-osahan commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/plugins/BaseRestApiPluginExecutor.java
> +    public boolean isConnectionStale(DatasourceConfiguration datasourceConfiguration) {
Initially I was using the connection object as parameter, but we connected and checked that the datasource config contains the info when the token will be expired.
I can change the method name to `isAuthenticationExpired` but will it be still relevant to other plugins? As all plugins has connections but not all plugins has authentication.
Alternatively can I also pass the connection object along with datasource config in this method?
It might not be used for Rest API but may be used in case of other plugins

2023-04-18 07:47 UTC, sanveer-osahan commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/OAuth2.java
> +        return this.authenticationResponse == null
I have changed it to the following as per the requirement mentioned in below comments for `OAuth2ClientCredentials.java` and `OAuth2AuthorizationCode.java`

```
return this.authenticationResponse != null
                && this.authenticationResponse.expiresAt != null
                && this.authenticationResponse.expiresAt.isBefore(Instant.now().plusSeconds(60));

2023-04-18 07:48 UTC, sanveer-osahan commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/OAuth2.java
> +                || this.authenticationResponse.expiresAt == null
Done

2023-04-18 07:53 UTC, sanveer-osahan commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceContextServiceCEImpl.java
> +        return getIsStale(datasource, datasourceContextIdentifier)
This can be done. But now it has a high impact where any areas of code calling this are affected. I have made those changes.

2023-04-18 07:53 UTC, sanveer-osahan commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/AuthenticationDTO.java
> +    public boolean isExpired() {
Done

2023-04-18 08:05 UTC, sanveer-osahan commented
/ok-to-test sha=c3c6869

2023-04-18 09:37 UTC, nidhi-nair commented
QQ: Wa the `UpdatableConnection` logic not taking care of this?

2023-04-18 14:04 UTC, sanveer-osahan commented
> QQ: Was the `UpdatableConnection` logic not taking care of this?

Hi @nidhi-nair I tried searching in the codebase if refreshing of expired token is already handled in `UpdateableConnection`. There is only one place were I found the code for refresh - [`AuthenticationServiceCEImpl`](https://github.com/appsmithorg/appsmith/blob/release/app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/AuthenticationServiceCEImpl.java) 

But here the refresh is only for SAAS and Remote PluginTypes

And `UpdateableConnection` only comes into picture when connection is identified as stale in [`DatasourceContextServiceCEImpl`](https://github.com/appsmithorg/appsmith/blob/release/app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceContextServiceCEImpl.java). Here there is a check if connection is instance of `UpdateableConnection` and then updated.
But the stale logic doesn't handle expiry of token i

2023-04-20 04:58 UTC, sanveer-osahan commented
Hi @nidhi-nair, thanks for your input. 
It's clear now that in some apis, there are additional params required to fetch the refresh_token in response. 
If they are provided in datasource config, the refresh logic is working as expected without any change in the code.

2023-04-20 04:58 UTC, closed without merging