feat: Refactored template, workspace settings, and profile pages
appsmithorg/appsmith pull request #22493
Opened 2023-04-17 21:16 UTC by albinAppsmith

## Description

This PR includes template, workspace settings, and profile pages

Fixes # (issue)
https://github.com/appsmithorg/appsmith/issues/19387
https://github.com/appsmithorg/appsmith/issues/19388
https://github.com/appsmithorg/appsmith/issues/19389

Media

https://user-images.githubusercontent.com/87797149/232612403-f9a0e962-7182-438a-8514-733cc59573ba.mov

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)

## How Has This Been Tested?

- Manual
- Jest
- Cypress

### Test Plan
> Add Testsmith test cases links that relate to this PR

### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)

## Checklist:
### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2023-04-17 21:16 UTC, albinAppsmith commented
/build-deploy-preview env=release

2023-04-18 17:46 UTC, tanvibhakta commented on - move the cursor to the right by defaul.md
> +- move the cursor to the right by default
This probably doesn't belong here :) @rohitagarwal88

2023-04-18 17:48 UTC, rohitagarwal88 commented on - move the cursor to the right by defaul.md
> +- move the cursor to the right by default
Good catch. thanks for pointing it out

2023-04-19 04:31 UTC, tanvibhakta requested changes

2023-04-19 04:31 UTC, tanvibhakta commented on app/client/src/pages/Applications/ProductUpdatesModal/UpdatesButton.tsx
> +    <StyledUpdatesButton data-cy="t--product-updates-btn" onClick={onClick}>
This needs to be deduplicated?

2023-04-19 04:31 UTC, tanvibhakta commented on app/client/src/pages/Applications/ProductUpdatesModal/index.tsx
> +        <Container>
use `ModalBody` here?

2023-04-19 04:31 UTC, tanvibhakta commented on app/client/src/pages/Templates/DatasourceChip.tsx
> +    <StyledDatasourceChip isClosable={false} size="md">
Our tags by definition don't have an onClick  to them - they're not supposed to be interactive (as also evidenced by the lack of any other states like hover or focus to denote interactivity). Can you please bring this usage up to design in the the working-group channel?

2023-04-19 04:31 UTC, tanvibhakta commented on app/client/src/pages/Templates/DatasourceChip.tsx
>      //   <img className="image" src={getAssetUrl(plugin.iconLocation)} />
remove comments

2023-04-19 04:31 UTC, tanvibhakta commented on app/client/src/pages/UserProfile/index.tsx
> +                    {/* <Icon name={tab.icon} /> */}
remove?

2023-04-19 04:31 UTC, tanvibhakta commented on app/client/src/pages/common/ProfileImage.tsx
> +// import { Text, TextType } from "design-system-old";
remove?

2023-04-19 04:31 UTC, tanvibhakta commented on app/client/src/pages/common/ProfileImage.tsx
> +    // <Profile
this page has a lot of comments

2023-04-19 04:31 UTC, tanvibhakta commented on app/client/src/pages/workspace/General.tsx
> +  /* width: ${(props) => (props.isPortrait ? "336px" : "383px")};
remove things inside comment?

2023-04-19 04:31 UTC, tanvibhakta commented on app/client/src/pages/workspace/General.tsx
> +  .upload-form-container {
Why does this need to happen? icon accepts a color prop no?

2023-04-19 04:31 UTC, tanvibhakta commented on app/client/src/pages/workspace/SettingsPageHeader.tsx
> +// const StyledButton = styled(Button)`
remove comment!

2023-04-19 04:55 UTC, tanvibhakta commented
Also left [6] comments about the dp itself in your DM
https://theappsmith.slack.com/archives/D03K37HRU00/p1681768452166859

2023-04-22 06:40 UTC, albinAppsmith commented on app/client/src/components/editorComponents/form/FormDialogComponent.tsx
> +import { TabComponent, Text, TextType } from "design-system-old";
Arsalan is working on this in a separate PR

2023-04-22 06:41 UTC, albinAppsmith commented on app/client/src/ce/pages/workspace/Members.tsx
>      color: ${Colors.GREY_10};
Removed

2023-04-22 06:42 UTC, albinAppsmith commented on app/client/src/components/utils/helperComponents.tsx
> +// export const StyledSearchInput = styled(SearchInput)`
Removed

2023-04-22 06:42 UTC, albinAppsmith commented on app/client/src/components/utils/helperComponents.tsx
>      <StyledBackButton
It is a link

2023-04-22 06:45 UTC, albinAppsmith commented on app/client/src/pages/AppViewer/PrimaryCTA.tsx
> +          <Button
We have not de duplicated this button since it follows the theme of widgets. The change you see here is just the change in position of the button.

2023-04-22 06:47 UTC, albinAppsmith commented on app/client/src/pages/Applications/ForkApplicationModal.tsx
> -      trigger={props.trigger}
Trigger is not being used

2023-04-22 06:54 UTC, albinAppsmith commented on app/client/src/pages/Applications/ImportApplicationModal.tsx
>          margin-top: 35px;
Didn't get this

2023-04-22 07:07 UTC, albinAppsmith commented on app/client/src/pages/Applications/ImportApplicationModal.tsx
> +      <Text kind="body-m" style={{ marginBottom: theme.spaces[4] }}>
This is fine for now.

2023-04-22 07:08 UTC, albinAppsmith commented on app/client/src/pages/Applications/ProductUpdatesModal/UpdatesButton.tsx
> +    <StyledUpdatesButton data-cy="t--product-updates-btn" onClick={onClick}>
This is part of left sidebar. This cannot be de duplicated with button

2023-04-22 07:11 UTC, albinAppsmith commented on app/client/src/pages/Applications/ProductUpdatesModal/index.tsx
> +        <Container>
We cannot replace container since it have styles for scrollbar and related overflows. I have wrapped it inside modal body

2023-04-22 07:11 UTC, albinAppsmith commented on app/client/src/pages/Templates/DatasourceChip.tsx
>      //   <img className="image" src={getAssetUrl(plugin.iconLocation)} />
Removed

2023-04-22 07:14 UTC, albinAppsmith commented on app/client/src/pages/Templates/DatasourceChip.tsx
> +    <StyledDatasourceChip isClosable={false} size="md">
This tag is not clickable.

2023-04-22 07:14 UTC, albinAppsmith commented on app/client/src/pages/UserProfile/index.tsx
> +                    {/* <Icon name={tab.icon} /> */}
Removed

2023-04-22 07:15 UTC, albinAppsmith commented on app/client/src/pages/common/ProfileImage.tsx
> +// import { Text, TextType } from "design-system-old";
Removed

2023-04-22 07:15 UTC, albinAppsmith commented on app/client/src/pages/common/ProfileImage.tsx
> +    // <Profile
Removed

2023-04-22 07:17 UTC, albinAppsmith commented on app/client/src/pages/workspace/General.tsx
> +  /* width: ${(props) => (props.isPortrait ? "336px" : "383px")};
Removed

2023-04-22 07:18 UTC, albinAppsmith commented on app/client/src/pages/workspace/General.tsx
> +  .upload-form-container {
Removed

2023-04-22 07:19 UTC, albinAppsmith commented on app/client/src/pages/workspace/SettingsPageHeader.tsx
> +// const StyledButton = styled(Button)`
Removed

2023-04-22 07:51 UTC, rohitagarwal88 approved these changes

2023-04-22 07:51 UTC, merged