feat: Feat/add google sheets metdata
appsmithorg/appsmith pull request #22577
Opened 2023-04-20 04:37 UTC by Irongade

This PR does three things:

1. Cleans up the Datasource Form page and makes the code more readable and discoverable
2. Adds the Account information for google sheets
3. Adds a way to render form configs specifically in view or edit modes.

> Add a TL;DR when description is extra long (helps content team)

Fixes #21759 

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.
> Delete anything that is not important

- Manual
- Jest
- Cypress

### Test Plan
> Add Testsmith test cases links that relate to this PR

### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)

## Checklist:
### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2023-04-21 06:05 UTC, Irongade commented
/ok-to-test

2023-04-23 20:56 UTC, Irongade commented
/ok-to-test

2023-04-24 08:44 UTC, Irongade commented
/ok-to-test

2023-04-24 12:50 UTC, sneha122 commented
/ok-to-test

2023-04-25 09:52 UTC, sneha122 commented on app/client/src/pages/Editor/DataSourceEditor/DBForm.tsx
> +                <div style={{ marginTop: "30px" }}>
Is this marginTop needed?

2023-04-25 09:53 UTC, sneha122 commented on app/client/src/pages/Editor/DataSourceEditor/DatasourceSection.tsx
> +                section.hidden.comparison === "VIEW_MODE"
Can we use enum here instead for "VIEW_MODE"?

2023-04-25 10:14 UTC, Irongade commented on app/client/src/pages/Editor/DataSourceEditor/DBForm.tsx
> +                <div style={{ marginTop: "30px" }}>
Yes it does,

2023-04-25 10:17 UTC, Irongade commented
/ok-to-test

2023-04-25 11:40 UTC, sumitsum requested changes

2023-04-25 11:52 UTC, sneha122 commented on app/server/appsmith-plugins/googleSheetsPlugin/src/main/resources/form.json
> +          "initialValue": "Authorize datasource to fetch account name"
<img width="573" alt="Screenshot 2023-04-25 at 5 21 30 PM" src="https://user-images.githubusercontent.com/30018882/234267994-e70663dd-8d60-4303-a65b-8594c03a7c3f.png">


@sumitsum It is as per designs. CC: @Irongade

2023-04-25 13:50 UTC, Irongade commented on app/server/appsmith-plugins/googleSheetsPlugin/src/main/resources/form.json
> +          "configProperty": "datasourceConfiguration.properties[0].key",
Done

2023-04-25 13:51 UTC, Irongade commented
/ok-to-test

2023-04-25 15:35 UTC, sumitsum commented on app/server/appsmith-plugins/googleSheetsPlugin/src/main/resources/form.json
> +          "initialValue": "Authorize datasource to fetch account name"
@sneha122 its ok, I am pretty sure we are making it better by prefix with `Please` :)

2023-04-25 15:42 UTC, sumitsum approved these changes

2023-04-25 15:42 UTC, sumitsum commented
server side changes LGTM.

2023-04-26 05:22 UTC, sneha122 approved these changes

2023-04-26 06:52 UTC, sneha122 commented
/build-deploy-preview

2023-04-26 10:58 UTC, Irongade commented
/ok-to-test

2023-04-27 06:22 UTC, sneha122 approved these changes

2023-04-27 10:39 UTC, Irongade commented
/ok-to-test

2023-04-27 10:45 UTC, sumitsum approved these changes

2023-04-27 10:52 UTC, sneha122 approved these changes

2023-04-27 11:07 UTC, Irongade commented
/ok-to-test

2023-04-27 11:09 UTC, sneha122 approved these changes

2023-04-27 11:09 UTC, sumitsum approved these changes

2023-04-27 13:52 UTC, merged