Firestore plugin -> "Timestamp Path" fix
appsmithorg/appsmith pull request #22646
Opened 2023-04-23 20:21 UTC by harshmange44

## Description

> Firestore plugin -> "Timestamp Path" field must not be required field (isRequired: false)

Closes #21180 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist:
### Dev activity
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2023-04-24 05:48 UTC, harshmange44 commented
/ok-to-test sha=233e3ea10e9a4d6519179692b5d97c9ef1e2bd12

2023-04-24 06:12 UTC, rohan-arthur requested changes
@harshmange44 thank you for submitting this! I think for the sake of standard, the rest of the fields which are not mandatory simply don't have the parameter `isRequired` at all. Would you please just remove the line?

2023-04-24 07:07 UTC, harshmange44 commented
@rohan-arthur Sure removed "isRequired" field for "Timestamp Path"

2023-04-24 10:52 UTC, sumitsum approved these changes

2023-04-24 10:54 UTC, sumitsum commented
/ok-to-test

2023-04-24 13:57 UTC, harshmange44 commented
Hi, @sumitsum Could you pls inform me in case if any changes are required?

2023-04-25 05:22 UTC, rohan-arthur approved these changes

2023-04-25 15:36 UTC, rohan-arthur commented
/ci-merge-check

2023-04-26 09:43 UTC, rohan-arthur commented
/ci-merge-check

2023-04-27 05:27 UTC, rohan-arthur commented
/ci-merge-check

2023-04-27 05:33 UTC, merged