chore: cleaned up formatting for the template
appsmithorg/appsmith pull request #22670
Opened 2023-04-24 10:39 UTC by ramsaptami

## Description

Cleaned up template heading and section styles on PR template

- Chore (housekeeping or task changes that don't impact user perception)

2023-04-24 10:42 UTC, hetunandu requested changes

2023-04-24 10:42 UTC, hetunandu commented on .github/pull_request_template.md
> +#### Fixes # (issue)
This will not work in connecting the issue. The "fixes" keyword cannot be a heading tag. Consider another title for the section and add the "fixes" keyword under it

2023-04-24 11:04 UTC, hetunandu commented on .github/pull_request_template.md
> +#### PR fixes following issue(s)
```suggestion
#### PR fixes following issue(s)

Fixes # (issue number)
```

2023-04-24 11:10 UTC, hetunandu approved these changes

2023-05-04 19:10 UTC, Aishwarya-U-R commented on .github/pull_request_template.md
> +- [ ] Cypress test cases have been added and approved by SDET/manual QA
Can we split this to 2 pointers:
[ ] Cypress test cases have been added by dev and approved by SDET
[ ] DP has been functionally tests by manual QA

2023-05-05 07:12 UTC, ramsaptami commented on .github/pull_request_template.md
> +- [ ] Cypress test cases have been added and approved by SDET/manual QA
done, could you please review and merge changes if everything looks good? @Aishwarya-U-R

2023-05-05 07:14 UTC, Aishwarya-U-R commented on .github/pull_request_template.md
> +- [ ] I have added `Test Plan Approved` label after JUnit tests were reviewed by a developer
`I` here denotes the PR owner right? But `Test Plan Approved `usually gets added by respective QA know?

2023-05-05 07:14 UTC, Aishwarya-U-R commented on .github/pull_request_template.md
> +- [ ] I have manually tested functionality on generated DP
Here too.. Does `I` suite?

2023-05-05 07:22 UTC, ramsaptami commented on .github/pull_request_template.md
> +- [ ] I have added `Test Plan Approved` label after JUnit tests were reviewed by a developer
Both dev and QA owner can add as long as said task is completed

2023-05-05 07:23 UTC, ramsaptami commented on .github/pull_request_template.md
> +- [ ] I have manually tested functionality on generated DP
Made changes to explicitly indicate ownership similar to the dev checklist. Do you feel that's excess?

2023-05-05 07:30 UTC, ramsaptami commented on .github/pull_request_template.md
> +- [ ] I have manually tested functionality on generated DP
Removed the `I`, please review and lmk if things look good @Aishwarya-U-R

2023-05-05 08:55 UTC, Aishwarya-U-R commented on .github/pull_request_template.md
> +- [ ] I have added `Test Plan Approved` label after JUnit tests were reviewed by a developer
Correct so lets say something general then - `Test Plan Approved label added after Cypress tests were reviewed`
Because now its with QA but dev also adds it at times.
Here explicit `I` puts confusion again on the owner of PR.

2023-05-05 09:27 UTC, Aishwarya-U-R approved these changes

2023-05-05 15:08 UTC, merged