fix: this.params shows error in IIFE
appsmithorg/appsmith pull request #22683
Opened 2023-04-24 19:30 UTC by ravikp7

## Description
This fixes the issue where using `this.params` in an IIFE function in API query params showed error.

**How does this PR fix the issue?**
The PR adds an empty object as `params` in the global `this` context. So that `this.params` doesn't evaluate to `undefined`.

Fixes #6732

Media
<img width="1182" alt="Screenshot 2023-04-25 at 12 59 36 AM" src="https://user-images.githubusercontent.com/13567359/234096780-661be709-d5fc-40ed-800f-d5014c2da062.png">

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Cypress

### Test Plan
> Add Testsmith test cases links that relate to this PR

### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)

## Checklist:
### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [x] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [x] Added Test Plan Approved label after reveiwing all Cypress test

2023-04-24 19:31 UTC, ravikp7 commented
/ok-to-test sha=cd1b4e3

2023-04-24 19:43 UTC, Aishwarya-U-R commented on app/client/cypress/integration/Regression_TestSuite/ClientSideTests/BugTests/Bug6732_Spec.ts
> +    _.agHelper.GetNClick(_.locators._paramsTab);
_.apiPage.SelectPaneTab("Params"); - to be used. Also remove the associated new locator created.

2023-04-24 19:43 UTC, Aishwarya-U-R commented on app/client/cypress/integration/Regression_TestSuite/ClientSideTests/BugTests/Bug6732_Spec.ts
> +    });
Check if _.apiPage.EnterParams() can be used here.

2023-04-24 19:43 UTC, Aishwarya-U-R commented on app/client/cypress/integration/Regression_TestSuite/ClientSideTests/BugTests/Bug6732_Spec.ts
> +    });
If can be used, remove newly created locators.

2023-04-25 04:23 UTC, ravikp7 commented
/ok-to-test sha=13a3dc3

2023-04-25 04:28 UTC, arunvjn requested changes

2023-04-25 04:28 UTC, arunvjn commented on app/client/src/workers/common/DataTreeEvaluator/index.ts
> +                )}}}`,
This is not the solution. You could put the same binding in API headers and replicate the issue

2023-04-25 05:32 UTC, Aishwarya-U-R reviewed
The attached bug also talks about arrow function. Can we please include script for that also?

2023-04-25 10:17 UTC, ravikp7 commented
@Aishwarya-U-R The issue couldn't be replicated for arrow functions.

2023-04-25 10:56 UTC, Aishwarya-U-R commented on app/client/cypress/integration/Regression_TestSuite/ClientSideTests/BugTests/Bug6732_Spec.ts
> +    agHelper.VerifyEvaluatedValue("undefined", false);
Showing undefined is the bug too. I dint quite get the fix here.

2023-04-25 15:36 UTC, ravikp7 commented on app/client/cypress/integration/Regression_TestSuite/ClientSideTests/BugTests/Bug6732_Spec.ts
> +    agHelper.VerifyEvaluatedValue("undefined", false);
The issue was `this.params` was being evaluated as `undefined` and hence accessing `this.params.something` raised an error `Cannot read properties of undefined`. The fix makes sure that `this.params` is a an empty object to suppress this error. We can't be sure of the exact value of `this.params` here on API editor page as `this.params` is contextual to the invocation, where the API is being called passing the params object.

In the test, we're making sure that the value of `this.params.key` gets evaluated without any errors, and the value will be undefined because `this.params` is an empty object here on this page.

2023-04-25 18:01 UTC, Aishwarya-U-R commented on app/client/cypress/integration/Regression_TestSuite/ClientSideTests/BugTests/Bug6732_Spec.ts
> +    agHelper.VerifyEvaluatedValue("undefined", false);
Ok, why cant we send some value to this API param & see if its evaluated - instead of undefined?

2023-04-25 18:01 UTC, Aishwarya-U-R commented on app/client/cypress/integration/Regression_TestSuite/ClientSideTests/BugTests/Bug6732_Spec.ts
> +    agHelper.VerifyEvaluatedValue("undefined", false);
Before fix also it was undefined & after fix also its undefined - makes it confusing.

2023-04-25 19:33 UTC, ravikp7 commented on app/client/cypress/integration/Regression_TestSuite/ClientSideTests/BugTests/Bug6732_Spec.ts
> +  it("1. this.params should be available in IIFE function in API editor", () => {
@Aishwarya-U-R The spec file name itself mentions the bug id. Is it not enough?

2023-04-25 19:36 UTC, ravikp7 commented
/build-deploy-preview env=release

2023-04-26 05:30 UTC, Aishwarya-U-R commented on app/client/cypress/integration/Regression_TestSuite/ClientSideTests/BugTests/Bug6732_Spec.ts
> +  it("1. this.params should be available in IIFE function in API editor", () => {
File name doesn't show up in search results - in vscode. So a skim of all bug specs file names is needed, which can be visually daunting. Hence.

2023-04-26 05:37 UTC, ravikp7 commented on app/client/cypress/integration/Regression_TestSuite/ClientSideTests/BugTests/Bug6732_Spec.ts
> +  it("1. this.params should be available in IIFE function in API editor", () => {
added

2023-04-26 06:32 UTC, Rishabh-Rathod commented on app/client/src/workers/common/DataTreeEvaluator/index.ts
> +              );
As params is a valid entity name, the user code with JSObject named `params` might get impacted by the above logic, if in the API body, the user tries to call `params.myFun()` that would not work when API is executed. 

Also, I would suggest replacing it with a key that is already an invalid entity name like `$params` anything starting with `$` is an invalid entity name and hence safe to add to the global context.

2023-04-26 07:06 UTC, ravikp7 commented on app/client/src/workers/common/DataTreeEvaluator/index.ts
> +              );
Excellent point. Updated.

2023-04-26 09:41 UTC, Rishabh-Rathod commented on app/client/src/workers/common/DataTreeEvaluator/index.ts
> +              );
Could we please write this logic in a separate helper method and write a jest test to validate for cases mentioned in the PR description here https://github.com/appsmithorg/appsmith/pull/10826

2023-04-26 09:41 UTC, Rishabh-Rathod commented on app/client/src/workers/common/DataTreeEvaluator/index.ts
>                };
As this was the only line in the code base where `thisContext` was used and now we remove it. 

I would suggest for following changes to be done 
1. Let's remove `thisContext` implementation from the codebase which means from `evaluate.ts` and `evaluate.test.ts` 
2. Let's modify the evaluation script to remove `THIS_CONTEXT` 

```js

export const EvaluationScripts: Record<EvaluationScriptType, string> = {
  [EvaluationScriptType.EXPRESSION]: `
  function $$closedFn () {
    const $$result = ${ScriptTemplate}
    return $$result
  }
  $$closedFn()
  `,
  [EvaluationScriptType.ANONYMOUS_FUNCTION]: `
  function $$closedFn (script) {
    const $$userFunction = script;
    const $$result = $$userFunction?.apply(THIS_CONTEXT, ARGUMENTS);
    return $$result
  }
  $$closedFn(${ScriptTemplate})
  `,
  [EvaluationScriptType.ASYNC_ANONYMOUS_FUNCTION]: `
  async function $$closedFn (script) {
    const $$userFunction = script;
    const $$result = $$userFunction?.apply(THIS_CONTEXT, ARGUMENTS);
    return await $$result;
  }
  $$closedFn(${ScriptTemplate})
  `,
  [EvaluationScriptType.TRIGGERS]: `
  async function $$closedFn () {
    const $$result = ${ScriptTemplate};
    return await $$result
  }
  $$closedFn()
  `,
  [EvaluationScriptType.OBJECT_PROPERTY]: `
  function $$closedFn () {
    const $$result = {${ScriptTemplate}}
    return $$result
  }
  $$closedFn()
  `,
};
```
3. Fix the jest test cases in `evaluate.test.ts`

2023-04-27 10:30 UTC, ravikp7 commented on app/client/src/workers/common/DataTreeEvaluator/index.ts
>                };
@Rishabh-Rathod I'm now wondering what was this being used for earlier.

2023-04-28 10:12 UTC, ravikp7 commented on app/client/src/workers/common/DataTreeEvaluator/index.ts
> +              );
@Rishabh-Rathod Added

2023-04-28 10:13 UTC, ravikp7 commented on app/client/src/workers/common/DataTreeEvaluator/index.ts
>                };
We'll take care of this in the `this` refactor being done by Arun

2023-04-28 10:18 UTC, Rishabh-Rathod reviewed
Code LGTM.

2023-04-28 10:18 UTC, Rishabh-Rathod approved these changes

2023-04-28 10:23 UTC, ravikp7 commented
/ok-to-test sha=6ce6113

2023-04-29 07:03 UTC, ravikp7 commented
test comment

2023-04-29 07:21 UTC, ravikp7 commented
test sha=6ce6113

2023-04-29 07:27 UTC, ravikp7 commented
/build-deploy-preview env=release

2023-04-29 08:25 UTC, ravikp7 commented
/ok-to-test sha=6ce6113

2023-05-02 05:08 UTC, ravikp7 commented
/ok-to-test sha=6ce6113

2023-05-02 06:22 UTC, ohansFavour reviewed
Looks good

2023-05-02 06:45 UTC, ravikp7 commented
/ok-to-test sha=6ce6113

2023-05-03 07:08 UTC, arunvjn approved these changes

2023-05-03 07:08 UTC, merged