fix: Invalidated error state connection mono from cache (#20538)
appsmithorg/appsmith pull request #22718
Opened 2023-04-25 10:51 UTC by sanveer-osahan

## Description
When the token fetched from client credentials grant type in oauth2 is expired, a request to the token endpoint is made to fetch a new token.
But sometimes the token endpoint fail. It can be intermittent failure, a retry will fetch the desired token. 
When the failure occurs, the datasource context mono goes into an error state. As this mono is cached, all the subsequent authenticated api calls from the user fetches the cached error mono resulting in failures and thus the token endpoint is never retried.
For the fix, while checking if datasource context is valid, added the check if its in a failed state. If yes, then the context will be considered invalid.

Fixes #20538 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested

- Manual

## Checklist:
### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2023-04-26 03:51 UTC, sanveer-osahan commented
/ok-to-test sha=419d680

2023-04-26 09:45 UTC, sumitsum requested changes

2023-04-26 09:45 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceContextServiceCEImpl.java
> +                    && !datasourceContextMonoMap.get(datasourceContextIdentifier).toFuture().isCompletedExceptionally()) {
Hi Sanveer, I was just thinking, would it be better to move it to line no 82 ? i.e. the check where we remove the values in the map - reason being that once we have discovered that a value is in error state it doesn't seem meaningful to not remove it.

2023-04-26 10:23 UTC, sanveer-osahan commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceContextServiceCEImpl.java
> +                    && !datasourceContextMonoMap.get(datasourceContextIdentifier).toFuture().isCompletedExceptionally()) {
makes sense

2023-04-26 10:31 UTC, sanveer-osahan commented
/ok-to-test sha=95374dc

2023-04-26 11:47 UTC, sanveer-osahan commented
/ok-to-test sha=b47ab66

2023-04-27 06:39 UTC, sumitsum commented
/ok-to-test

2023-04-27 09:04 UTC, sanveer-osahan commented
/ok-to-test sha=84726a2

2023-04-28 02:00 UTC, sanveer-osahan commented
/ok-to-test sha=84726a2

2023-04-28 08:27 UTC, sumitsum approved these changes

2023-05-02 10:01 UTC, sanveer-osahan commented
/build-deploy-preview

2023-05-05 07:28 UTC, merged