fixed race condition in import application flow
appsmithorg/appsmith pull request #22764
Opened 2023-04-26 17:21 UTC by nayan-rafiq

## Description

This PR fixes the import application failure issue due to the race condition.

Fixes #18503

Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manual

### Test Plan
> Add Testsmith test cases links that relate to this PR

### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)

## Checklist:
### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2023-04-26 18:36 UTC, nayan-rafiq commented
/ok-to-test sha=8a584bf

2023-04-27 06:38 UTC, AnaghHegde requested changes
Minor nit. Rest LGTM

2023-04-27 06:38 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImplV2.java
> +
Why do we need to cache this? I don't see this being used anywhere else in the flow.

2023-04-27 10:16 UTC, Parthvi12 commented
/build-deploy-preview skip-tests=true

2023-04-27 11:43 UTC, Parthvi12 approved these changes

2023-04-29 17:31 UTC, nayan-rafiq commented
/ok-to-test sha=090d7ec

2023-04-30 17:32 UTC, nayan-rafiq commented
/ok-to-test sha=e75196d

2023-05-01 17:18 UTC, nayan-rafiq commented
/ok-to-test sha=1d9d51b

2023-05-01 18:08 UTC, AnaghHegde reviewed
This is needed for the ImportExport v1 as well right?

2023-05-02 05:40 UTC, nayan-rafiq commented
> This is needed for the ImportExport v1 as well right?

@AnaghHegde no, the v1 is a bit different. It has custom js lib import later in the flow, not in the first.

2023-05-02 06:31 UTC, AnaghHegde approved these changes

2023-05-02 09:34 UTC, merged