fix: Clear cache when switching pages
appsmithorg/appsmith pull request #22776
Opened 2023-04-27 09:14 UTC by rimildeyjsr

## Description

We noticed stale data from the previous page when having widgets with the same name on different pages. This PR fixes this by changing the data tree in the state when clearing the cache.

Fixes #17097 

## Media

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manual
- Cypress

### Test Plan

### Issues raised during DP testing

## Checklist:
### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer-reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reviewing all Cypress test

2023-05-03 10:49 UTC, rimildeyjsr commented
/ok-to-test

2023-05-03 10:51 UTC, rimildeyjsr commented
/ok-to-test

2023-05-03 10:52 UTC, rimildeyjsr commented
/build-deploy-preview env=release

2023-05-03 12:23 UTC, ohansFavour commented on app/client/src/reducers/evaluationReducers/treeReducer.ts
> +    state.dataTree = undefined;
Is there a reason why we are setting this to *undefined*, instead of an empty object (the initial state)

2023-05-05 03:52 UTC, rimildeyjsr commented
/ok-to-test sha=658322d

2023-05-05 03:52 UTC, rimildeyjsr commented on app/client/src/reducers/evaluationReducers/treeReducer.ts
> +    state.dataTree = undefined;
youre right, no good reason, made the change!

2023-05-05 03:52 UTC, rimildeyjsr commented
/build-deploy-preview env=release

2023-05-05 05:58 UTC, ohansFavour approved these changes

2023-05-05 06:38 UTC, ohansFavour requested changes
Set state as initial state in RESET_DATATREE handler

2023-05-05 07:37 UTC, rimildeyjsr commented
/ok-to-test sha=9852664

2023-05-05 07:44 UTC, rimildeyjsr commented
/ok-to-test sha=a43b576

2023-05-05 07:44 UTC, rimildeyjsr commented
/build-deploy-preview env=release

2023-05-05 07:54 UTC, ohansFavour approved these changes

2023-05-05 13:05 UTC, ramsaptami commented
lgtm
cc: @rimildeyjsr

2023-05-06 04:32 UTC, rimildeyjsr commented
/ok-to-test sha=dcac5df

2023-05-06 14:00 UTC, merged