Fixed Reformat JUnit TC to make query strings easier to work with
appsmithorg/appsmith pull request #22885
Opened 2023-05-01 18:43 UTC by abhishekS14

## Description

> Fixed [Task]: Oracle: Reformat JUnit TC to make query strings easier to work with

Fixes # (issue)
> #22880

## Type of change

> Please delete options that are not relevant.

- Chore (housekeeping or task changes that don't impact user perception)

## How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.
> Delete anything that is not important

- Manual
- Jest
- Cypress

### Test Plan
> Add Testsmith test cases links that relate to this PR

### Issues raised during DP testing
> Link issues raised during DP testing for better visibility and tracking (copy link from comments dropped on this PR)

## Checklist:
### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2023-05-02 02:32 UTC, sumitsum approved these changes

2023-05-02 05:15 UTC, sumitsum commented
/ok-to-test

2023-05-02 05:52 UTC, sumitsum requested changes

2023-05-02 05:52 UTC, sumitsum commented on app/server/appsmith-plugins/oraclePlugin/src/test/java/com/external/plugins/OracleExecutionTest.java
> +                "]";
Hi @abhishekS14 the server side tests are failing with the following error, can you please check: 
```
2023-05-02T05:18:29.7060327Z [INFO] Results:
2023-05-02T05:18:29.7060639Z [INFO] 
2023-05-02T05:18:29.7060947Z [ERROR] Failures: 
2023-05-02T05:18:29.7061511Z [ERROR]   OracleExecutionTest.lambda$verifyColumnValue$0:352 expected: <[
2023-05-02T05:18:29.7061945Z   {
2023-05-02T05:18:29.7062295Z     "C_VARCHAR2": "varchar2",
2023-05-02T05:18:29.7062743Z     "C_NVARCHAR2": "nvarchar2",
2023-05-02T05:18:29.7063149Z     "C_NUMBER": "5",
2023-05-02T05:18:29.7063533Z     "C_FLOAT": "11.22",
2023-05-02T05:18:29.7064111Z     "C_DATE": "2002-10-03",
2023-05-02T05:18:29.7064489Z     "C_BINARY_FLOAT": "11.22",
2023-05-02T05:18:29.7064883Z     "C_BINARY_DOUBLE": "11.22",
2023-05-02T05:18:29.7065434Z     "C_TIMESTAMP": "1997-01-01T09:26:50.124Z",
2023-05-02T05:18:29.7065952Z     "C_INTERVAL_YEAR": "1-0",
2023-05-02T05:18:29.7066364Z     "C_INTERVAL_DAY": "0 1:0:0.0",
2023-05-02T05:18:29.7066802Z     "C_ROWID": "AAAAAAAAGAAAAH4AAB",
2023-05-02T05:18:29.7067288Z     "C_UROWID": "000001F8.0001.0006",
2023-05-02T05:18:29.7067690Z     "C_CHAR": "char                ",
2023-05-02T05:18:29.7068243Z     "C_NCHAR": "nchar               ",
2023-05-02T05:18:29.7068580Z     "C_CLOB": "clob",
2023-05-02T05:18:29.7068826Z     "C_NCLOB": "nclob"
2023-05-02T05:18:29.7069037Z   }
2023-05-02T05:18:29.7069971Z ]> but was: <[{"C_VARCHAR2":"varchar2","C_NVARCHAR2":"nvarchar2","C_NUMBER":"5","C_FLOAT":"11.22","C_DATE":"2002-10-03","C_BINARY_FLOAT":"11.22","C_BINARY_DOUBLE":"11.22","C_TIMESTAMP":"1997-01-01T09:26:50.124Z","C_INTERVAL_YEAR":"1-0","C_INTERVAL_DAY":"0 1:0:0.0","C_ROWID":"AAAAAAAAGAAAAH4AAB","C_UROWID":"000001F8.0001.0006","C_CHAR":"char                ","C_NCHAR":"nchar               ","C_CLOB":"clob","C_NCLOB":"nclob"}]>
2023-05-02T05:18:29.7070579Z [ERROR]   OracleExecutionTest.lambda$verifyColumnValue$0:352 expected: <[
2023-05-02T05:18:29.7070848Z   {
2023-05-02T05:18:29.7071038Z     "C_VARCHAR2": "varchar2",
2023-05-02T05:18:29.7071547Z     "C_NVARCHAR2": "nvarchar2",
2023-05-02T05:18:29.7071745Z     "C_NUMBER": "4",
2023-05-02T05:18:29.7071943Z     "C_FLOAT": "11.22",
2023-05-02T05:18:29.7072190Z     "C_DATE": "2002-10-03",
2023-05-02T05:18:29.7072510Z     "C_BINARY_FLOAT": "11.22",
2023-05-02T05:18:29.7072874Z     "C_BINARY_DOUBLE": "11.22",
2023-05-02T05:18:29.7073423Z     "C_TIMESTAMP": "1997-01-01T09:26:50.124Z",
2023-05-02T05:18:29.7074009Z     "C_TIMESTAMP_TZ": "1997-01-01T09:26:56.66+02:00",
2023-05-02T05:18:29.7074582Z     "C_TIMESTAMP_LTZ": "1999-04-05T15:00:00Z",
2023-05-02T05:18:29.7075068Z     "C_INTERVAL_YEAR": "1-0",
2023-05-02T05:18:29.7075312Z     "C_INTERVAL_DAY": "0 1:0:0.0",
2023-05-02T05:18:29.7075550Z     "C_ROWID": "AAAAAAAAGAAAAH4AAB",
2023-05-02T05:18:29.7075777Z     "C_UROWID": "000001F8.0001.0006",
2023-05-02T05:18:29.7075994Z     "C_CHAR": "char                ",
2023-05-02T05:18:29.7076207Z     "C_NCHAR": "nchar               ",
2023-05-02T05:18:29.7076412Z     "C_CLOB": "clob",
2023-05-02T05:18:29.7076610Z     "C_NCLOB": "nclob"
2023-05-02T05:18:29.7076784Z   }
2023-05-02T05:18:29.7078289Z ]> but was: <[{"C_VARCHAR2":"varchar2","C_NVARCHAR2":"nvarchar2","C_NUMBER":"4","C_FLOAT":"11.22","C_DATE":"2002-10-03","C_BINARY_FLOAT":"11.22","C_BINARY_DOUBLE":"11.22","C_TIMESTAMP":"1997-01-01T09:26:50.124Z","C_TIMESTAMP_TZ":"1997-01-01T09:26:56.66+02:00","C_TIMESTAMP_LTZ":"1999-04-05T15:00:00Z","C_INTERVAL_YEAR":"1-0","C_INTERVAL_DAY":"0 1:0:0.0","C_ROWID":"AAAAAAAAGAAAAH4AAB","C_UROWID":"000001F8.0001.0006","C_CHAR":"char                ","C_NCHAR":"nchar               ","C_CLOB":"clob","C_NCLOB":"nclob"}]>
2023-05-02T05:18:29.7079076Z [INFO] 
```

2023-05-02 05:56 UTC, abhishekS14 commented on app/server/appsmith-plugins/oraclePlugin/src/test/java/com/external/plugins/OracleExecutionTest.java
> +                "]";
Hi, yes 
I'll check this

2023-05-02 06:42 UTC, abhishekS14 commented on app/server/appsmith-plugins/oraclePlugin/src/test/java/com/external/plugins/OracleExecutionTest.java
> +                "]";
Is there a way to test these locally? When I run the Junit , it fails because of no Docker environment available error

2023-05-02 21:28 UTC, sumitsum commented on app/server/appsmith-plugins/oraclePlugin/src/test/java/com/external/plugins/OracleExecutionTest.java
> +                "]";
Hi @abhishekS14 installing and running docker application should resolve the docker related error.

2023-05-10 10:57 UTC, sumitsum commented
Hi @abhishekS14 are you still working on this ?

2023-05-10 18:33 UTC, abhishekS14 commented
Hi, yes
I will resolve this asap

2023-05-11 05:51 UTC, abhishekS14 commented
HI @sumitsum, I have made the changes. Should I create a new PR or would this one get updated?

2023-05-17 06:13 UTC, sumitsum commented
/ok-to-test

2023-05-17 06:14 UTC, sumitsum approved these changes

2023-05-17 06:15 UTC, sumitsum commented
Thanks @abhishekS14 I have approved the PR and run the CI tests again, will let you know in case anything requires further change. I will merge the change in case CI run looks ok.

2023-05-17 07:17 UTC, abhishekS14 commented
Okay, thanks @sumitsum

2023-05-22 08:55 UTC, merged