POC: Fix Style recalcs for stickyCanvasArena
appsmithorg/appsmith pull request #22904
Opened 2023-05-02 09:13 UTC by rahulramesha

## Description
Test PR to fix style re-clacs only when necessary rather than all the time

Fixes # (issue)
> if no issue exists, please create an issue and ask the maintainers about this first

Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update

## How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.
> Delete anything that is not important

- Manual
- Jest
- Cypress

### Test Plan
> Add Testsmith test cases links that relate to this PR

### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)

## Checklist:
### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2023-05-03 18:55 UTC, rahulramesha commented
/build-deploy-preview env=release

2023-05-04 07:42 UTC, SatishGandham commented
/perf-test ref=use-appsmith-email

2023-05-26 13:01 UTC, rahulramesha commented
/build-deploy-preview env=release

2023-05-26 13:02 UTC, rahulramesha commented
/ok-to-test

2023-05-29 04:44 UTC, marks0351 approved these changes

2023-05-29 04:44 UTC, marks0351 submitted a review, later dismissed

2023-05-29 05:39 UTC, SatishGandham requested changes

2023-05-29 05:39 UTC, SatishGandham commented on app/client/src/pages/common/CanvasArenas/StickyCanvasArena.tsx
> +    const observeSliderIfNecessary = () => {
Why a wrapper function?
Lets just add the condition to the oberveSlider itself. It is also conditional anyway.
Don't forget to add a comment on why we are doing it.

2023-05-29 08:30 UTC, rahulramesha commented
/build-deploy-preview env=release

2023-05-29 08:30 UTC, rahulramesha commented
/ok-to-test

2023-05-29 10:41 UTC, SatishGandham approved these changes

2023-05-31 04:30 UTC, marks0351 submitted a review, later dismissed

2023-05-31 17:10 UTC, rahulramesha commented
/build-deploy-preview env=release

2023-06-01 14:56 UTC, rahulramesha commented
/ok-to-test

2023-06-02 06:13 UTC, SatishGandham approved these changes

2023-06-02 06:13 UTC, SatishGandham approved these changes

2023-06-02 10:11 UTC, rahulramesha commented
/ok-to-test

2023-06-02 12:06 UTC, merged