chore: poc to merge DS editor data flows
appsmithorg/appsmith pull request #22920
Opened 2023-05-02 13:27 UTC by ayushpahwa

## Description

POC to merge the DS editors for 3 different types of datasources
- Databases and SAAS
- G sheets
- Authenticated API and Graphql

Fixes #22850 
(Fixes #1367 from EE)

Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video

## Type of change

- Chore (housekeeping or task changes that don't impact user perception)

## How Has This Been Tested?

- Manual
- Jest
- Cypress

### Test Plan
> Add Testsmith test cases links that relate to this PR

### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)

## Checklist:
### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2023-05-02 13:29 UTC, ayushpahwa commented
/ok-to-test

2023-05-04 04:41 UTC, ayushpahwa commented
/ok-to-test

2023-05-04 08:41 UTC, ayushpahwa commented
/ok-to-test

2023-05-10 10:11 UTC, ayushpahwa commented
/build-deploy-preview

2023-05-10 10:48 UTC, ayushpahwa commented
/build-deploy-preview skip-tests=true

2023-05-11 02:15 UTC, AnandShahs123 commented
@ayushpahwa Add datasource forms are not scrollable. This is a blocker [UI] issue. 

<img width="1440" alt="mongo" src="https://github.com/appsmithorg/appsmith/assets/119847783/2c569482-d89a-475b-9ce8-b3a5cf5a058b">

2023-05-11 06:57 UTC, sneha122 commented on app/client/src/components/formControls/utils.ts
> +          keyValueErrors[objectKeys[0]] = "This field is required";
Can we please add this error message value in messages.ts?

2023-05-11 06:58 UTC, sneha122 commented on app/client/src/components/formControls/utils.ts
> +          keyValueErrors[objectKeys[1]] = "This field is required";
Can we please add this error message value in messages.ts?

2023-05-11 07:10 UTC, sneha122 commented on app/client/src/pages/Editor/DataSourceEditor/index.tsx
> +  const formData = getFormValues(DATASOURCE_DB_FORM)(state) as
should we replace DATASOURCE_DB_FORM with formName? for db plugins we use DATASOURCE_DB_FORM where as for rest api ds we use DATASOURCE_REST_API_FORM form

2023-05-11 07:13 UTC, btsgh commented
1. Rest API - after running an api and then doing save as datasource - the screen that comes up is incorrect
<img width="1179" alt="SaveAsDS_RestAPI" src="https://github.com/appsmithorg/appsmith/assets/101863839/54a6447a-381a-4992-acd1-c44ddc487863">

2023-05-11 08:10 UTC, btsgh commented
3. Test button seems to be missing on PostGreSQL and Mongo
<img width="1172" alt="PostGre_Mongo_Testbuttonmissing" src="https://github.com/appsmithorg/appsmith/assets/101863839/27e59318-988d-42a8-bb67-2d71e8519b96">

2023-05-11 11:28 UTC, ayushpahwa commented on app/client/src/pages/Editor/DataSourceEditor/index.tsx
> +  const formData = getFormValues(DATASOURCE_DB_FORM)(state) as
This is done, there was a big merge conflict in which lots of code was lost. Please check again.

2023-05-11 11:31 UTC, ayushpahwa commented on app/client/src/components/formControls/utils.ts
> +          keyValueErrors[objectKeys[1]] = "This field is required";
Great catch, done now! Please check!

2023-05-11 11:31 UTC, ayushpahwa commented
/build-deploy-preview skip-tests=true

2023-05-11 11:31 UTC, ayushpahwa commented
/ok-to-test

2023-05-11 17:00 UTC, ayushpahwa commented
/ok-to-test

2023-05-11 18:14 UTC, ChandanBalajiBP commented on app/client/src/pages/Editor/DataSourceEditor/index.tsx
> +  validateForm(): boolean {
Have you verified if validate doesn't cause whole config component to rerender?

2023-05-11 18:14 UTC, ChandanBalajiBP commented on app/client/src/pages/common/datasourceAuth/index.tsx
>    DELETE = "DELETE",
Are we using DELETE anywhere? if not can we remove?

2023-05-11 18:14 UTC, ChandanBalajiBP commented on app/client/src/pages/Editor/DataSourceEditor/index.tsx
> +  // updates the configDetails and requiredFields objects in the state
We have to function in DatasourceForm also, can we move to a common place?

2023-05-12 05:41 UTC, ayushpahwa commented on app/client/src/pages/Editor/DataSourceEditor/index.tsx
> +  // updates the configDetails and requiredFields objects in the state
Datasource form is going to be removed. It is only added for the meantime to move things to the parent datasource editor component.

2023-05-12 05:42 UTC, ayushpahwa commented on app/client/src/pages/common/datasourceAuth/index.tsx
>    DELETE = "DELETE",
Sure, will remove.

2023-05-12 05:42 UTC, ayushpahwa commented on app/client/src/components/formControls/utils.ts
> +export const validate = (
Yup, that's the goal. We can use this once we move to the epic

2023-05-12 05:43 UTC, ayushpahwa commented on app/client/src/components/formControls/utils.ts
> +export const getTrimmedData = (formData: any) => {
Sure. This is code that is moved from inside the nested child to a common utils. Will pick from their respective PRs.

2023-05-12 09:56 UTC, ayushpahwa commented
/build-deploy-preview skip-tests=true recreate=true

2023-05-12 11:47 UTC, ayushpahwa commented
/build-deploy-preview skip-tests=true recreate=true

2023-05-12 11:47 UTC, ayushpahwa commented
/:gtest

2023-05-12 11:47 UTC, ayushpahwa commented
/ok-to-test

2023-05-13 16:23 UTC, ayushpahwa commented
/ok-to-test

2023-05-13 16:24 UTC, ayushpahwa commented
/build-deploy-preview skip-tests=true recreate=true

2023-05-15 06:06 UTC, ayushpahwa commented
/build-deploy-preview skip-tests=true recreate=true

2023-05-15 08:38 UTC, ayushpahwa commented
/ok-to-test

2023-05-15 13:57 UTC, AnandShahs123 commented
@ayushpahwa - Getting this error "{"responseMeta":{"status":500,"success":false,"error":{"code":5000,"message":"Internal server error while processing request"}}}" on doing save and authorize datasource in google sheet

2023-05-16 02:04 UTC, ayushpahwa commented
@AnandShahs123 as mentioned by Rohan, you cannot test sheets on DP. You need to test it locally. @prapullac can help with the same.

2023-05-16 06:32 UTC, AnandShahs123 commented
@ayushpahwa - Delete button is not aligned as per the design. 

<img width="1440" alt="delete" src="https://github.com/appsmithorg/appsmith/assets/119847783/dd7f492f-5efb-4453-86e0-fe516a9938ed">

2023-05-16 07:49 UTC, AnandShahs123 commented
@ayushpahwa It should be "test configuration" in the bottom instead of "test".

<img width="1440" alt="test" src="https://github.com/appsmithorg/appsmith/assets/119847783/05869aa7-aa47-4c1e-af65-9ee4e5b13a6e">

2023-05-16 08:12 UTC, ayushpahwa commented
/ok-to-test

2023-05-16 08:12 UTC, ayushpahwa commented
/build-deploy-preview skip-tests=true recreate=true

2023-05-16 08:58 UTC, Aishwarya-U-R commented on app/client/cypress/integration/Regression_TestSuite/ServerSideTests/QueryPane/Mongo_Spec.js
> -    });
Here, value can either be 200, 409, In the current change its always expected to be 200 which may fail. For this I have made change in ADS PR. 
Can you please make them same as here & handle this. Please address all places where we had validation for both 200 & 409.

```
_.dataSources.DeleteDatasouceFromActiveTab(datasourceName, 409, false);
    cy.wait("@deleteDatasource").should((response) => {
      expect(response.status).to.be.oneOf([200, 409]);
    });
```

2023-05-16 08:59 UTC, ayushpahwa commented on app/client/cypress/integration/Regression_TestSuite/ServerSideTests/QueryPane/Mongo_Spec.js
> -    });
Actually, I added the ignore response flag which doesn't check for the response in these cases. Will that work?

2023-05-16 09:14 UTC, AnandShahs123 commented
@ayushpahwa - Whitelisting message is missing on the datasource page

2023-05-16 10:46 UTC, Aishwarya-U-R commented on app/client/cypress/integration/Regression_TestSuite/ServerSideTests/QueryPane/Mongo_Spec.js
> -    });
Please pick up method from ADS PR as shared in slack.

2023-05-16 11:13 UTC, Aishwarya-U-R commented on app/client/cypress/integration/Regression_TestSuite/ServerSideTests/QueryPane/Mongo_Spec.js
> -    });
Ok, just saw. No this makes the value to be sent for that parameter & we dont want to ignore checking here. Its should be either 200 or 409 only.. Please pick up updates from ADS PR as before.

2023-05-17 01:29 UTC, ayushpahwa commented
/ok-to-test

2023-05-17 06:35 UTC, ayushpahwa commented
/ok-to-test

2023-05-17 07:14 UTC, ChandanBalajiBP commented on app/client/src/pages/Editor/SaaSEditor/DatasourceForm.tsx
> +                  <div style={{ marginTop: "30px" }}>
can we remove inline styling

2023-05-17 07:22 UTC, riodeuno commented on app/client/src/components/utils/formComponents.tsx
> +import { Colors } from "constants/Colors";
I would suggest someone from the design system pod reviews this.

2023-05-17 10:44 UTC, ayushpahwa commented
/ok-to-test

2023-05-17 14:27 UTC, Aishwarya-U-R commented on app/client/cypress/support/Pages/AggregateHelper.ts
> +  public ValidateNetworkStatusFromArray(
Can we remove this? Is this used?

2023-05-17 15:44 UTC, ayushpahwa commented on app/client/cypress/support/Pages/AggregateHelper.ts
> +  public ValidateNetworkStatusFromArray(
Yup, missed this. Done now.

2023-05-17 16:19 UTC, Aishwarya-U-R reviewed
Cypress changes looks OK.

2023-05-18 03:25 UTC, ayushpahwa commented
/ok-to-test

2023-05-18 05:16 UTC, ChandanBalajiBP approved these changes
LGTM

2023-05-18 09:52 UTC, riodeuno requested changes
I see that we've cleaned up the codebase a lot. A lot of lines of code have been removed, and I appreciated the effort we've put into this. Thanks!

Let's get all the new and existing components reviewed by a team member from the design system pod, as we're moving towards one source of components in Appsmith.

2023-05-18 09:52 UTC, riodeuno commented on app/client/src/pages/Editor/DataSourceEditor/JSONtoForm.tsx
> +    margin-right: ${(props) => (props.floatLeft ? "auto" : "9px")};
Could we use `flexbox` or alternatively, use the `classNames` to assign tailwind classes based on the `floatLeft` property?
If this property changes rapidly, we may see performance issues where styled components rapidly updated classes.

2023-05-18 09:52 UTC, riodeuno commented on app/client/src/pages/Editor/gitSync/ReconnectDatasourceModal.tsx
> +  .t--cancel-edit-datasource {
The `t--` prefix are only for the cypress tests, and are subject to addition or removal or changes. I don't think we should tie these classes to CSS.

2023-05-22 07:58 UTC, ayushpahwa commented on app/client/src/pages/Editor/DataSourceEditor/DSFormHeader.tsx
> +    <Header style={{ paddingTop: "20px", flex: "1 1 10%" }}>
Thanks for pointing this out, have refactored and removed these.

2023-05-22 08:04 UTC, ayushpahwa commented on app/client/src/pages/Editor/DataSourceEditor/DSFormHeader.tsx
> +  datasource: Datasource | ApiDatasourceForm | undefined;
Since we haven't yet removed the saas editor form, this still has a chance for undefined. As soon as we remove that, it should be fixed.

2023-05-22 08:05 UTC, ayushpahwa commented on app/client/src/pages/Editor/DataSourceEditor/DSFormHeader.tsx
> +            text="EDIT"
Yup, this could've been a problem. I have updated all the buttons with the createMessage function.

2023-05-22 08:05 UTC, ayushpahwa commented on app/client/src/pages/Editor/DataSourceEditor/DSFormHeader.tsx
> +    viewMode,
viewMode signifies wether the datasource is in view or edit mode. We control the visibility of the header buttons accordingly

2023-05-22 08:08 UTC, ayushpahwa commented on app/client/src/pages/Editor/DataSourceEditor/JSONtoForm.tsx
> +    margin-right: ${(props) => (props.floatLeft ? "auto" : "9px")};
This is a static property only used in one place. I have updated this to be only used for the test config button

2023-05-22 08:10 UTC, ayushpahwa commented on app/client/src/pages/Editor/gitSync/ReconnectDatasourceModal.tsx
> +  .t--cancel-edit-datasource {
This is currently used in a lot of places. I have added this my to fix list, will pick this up when I am working on the datasource forms. Since this PR is now a blocker for a lot of further dev, will let this PR go in, Have also added a todo note here.

2023-05-22 08:14 UTC, ayushpahwa commented
/build-deploy-preview skip-tests=true recreate=true

2023-05-22 08:14 UTC, ayushpahwa commented
/ok-to-test

2023-05-22 09:32 UTC, ChandanBalajiBP submitted a review, later dismissed

2023-05-22 10:03 UTC, ayushpahwa commented
/ok-to-test

2023-05-22 11:17 UTC, ChandanBalajiBP approved these changes

2023-05-22 11:37 UTC, ayushpahwa commented
/ci-merge-check

2023-05-22 12:05 UTC, merged