fix: Add message prompt on min field
appsmithorg/appsmith pull request #22977
Opened 2023-05-04 01:12 UTC by rajatagrawal

Fixes #20235

This pull requests adds a prompt message to min/max/regex/errorMessage/required input validation fields. Also fixed css styling on the prompt message for these fields as well as additionally on Valid/ComputedValue fields.

The design shared by @vasanthappsmith is attached below : 

![image (1)](https://user-images.githubusercontent.com/1189106/236084717-fd899a32-1239-446c-9ee1-fd7f7c13e693.png)

## Checklist:
### Dev activity
- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings
- [ x] I have added tests that prove my fix is effective or that my feature works
- [ x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2023-05-04 01:14 UTC, rajatagrawal commented
/ok-to-test sha=a1a7aa0

2023-05-04 02:41 UTC, mohanarpit commented on app/client/src/components/propertyControls/TableInlineEditValidationControl.tsx
> +            Access the current cell using <CurlyBraces>{"{{"}</CurlyBraces>
Nit: Please move all strings to `messages.ts` file. This ensures that we can internationalize it and/or modify it from a single location.

2023-05-04 04:48 UTC, sbalaji1192 commented on app/client/cypress/support/index.js
> +let rapidMode = {
I think this should be part of a env file. @Aishwarya-U-R

2023-05-04 05:47 UTC, Aishwarya-U-R commented on app/client/cypress/support/index.js
> +let rapidMode = {
@rajatagrawal - is this not already merged to release?

2023-05-04 10:54 UTC, rajatagrawal commented on app/client/cypress/support/index.js
> +let rapidMode = {
yes sorry, it got accidentally pushed in this PR

2023-05-04 11:21 UTC, Aishwarya-U-R commented on app/client/cypress/support/index.js
> +let rapidMode = {
And @sbalaji1192 - Rishabh has also given a suggestion to keep this variable in cypress.json to avoid accident pushes & Rajat confirmed he will be working on it. @rajatagrawal - can give more updates.

2023-05-05 03:41 UTC, rajatagrawal commented on app/client/cypress/support/index.js
> +let rapidMode = {
yes, I will be working on it in a separate PR.

2023-05-05 03:42 UTC, rajatagrawal commented on app/client/src/components/propertyControls/TableInlineEditValidationControl.tsx
> +            Access the current cell using <CurlyBraces>{"{{"}</CurlyBraces>
This is fixed now.

2023-05-05 07:10 UTC, aswathkk requested changes
@rajatagrawal The changes are not applied in all the fields.
I think we need to make this style consistent across the product.

The components like `PromptMessage`, `StyledCode` and `CurlyBraces` are locally defined in multiple files causes the inconsistency.

We need to define all these in a central location, make the style changes in that central location and import it

2023-05-05 07:10 UTC, aswathkk commented on app/client/src/components/propertyControls/TableInlineEditValidationControl.tsx
> +export const PromptMessage = styled.span`
I can see that `PromptMessage` got defined in multiple files.
example: TableComputeValue.tsx, ListComputeControl.tsx, JSONFormComputeControl.tsx etc.
Just search for it in the codebase.
Can we de-duplicate them?

2023-05-05 07:10 UTC, aswathkk commented on app/client/src/components/propertyControls/TableInlineEditValidationControl.tsx
> +  color: ${Colors.PRIMARY_ORANGE};
This style is only applied to this component.
I think we need to make it consistent across the product.

![Screenshot 2023-05-05 at 12 32 26 PM](https://user-images.githubusercontent.com/10436935/236396235-282cf3db-3981-40d3-84fd-1aaeaa246de4.png)
![Screenshot 2023-05-05 at 12 32 34 PM](https://user-images.githubusercontent.com/10436935/236396245-83246c0a-e67e-4ac1-987a-426322234841.png)

2023-05-05 07:23 UTC, aswathkk submitted a review, later dismissed
Changes looks good to me.
The deduplication/inconsistency issues will be picked up in ADS2.0 it seems.

@rohitagarwal88 Can you attach the relevant task in this PR?

2023-05-06 02:02 UTC, rajatagrawal commented
/ok-to-test sha=3e47853

2023-05-08 10:19 UTC, merged