chore: Modify default seriliser to custom JsonSerialiser
appsmithorg/appsmith pull request #23029
Opened 2023-05-05 10:51 UTC by abhvsn

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.

## Description

> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change
> Links to Notion, Figma or any other documents that might be relevant to the PR

> Add a TL;DR when description is extra long (helps content team)

Fixes # (issue)
> if no issue exists, please create an issue and ask the maintainers about this first

Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update

## How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.
> Delete anything that is not important

- Manual
- Jest
- Cypress

### Test Plan
> Add Testsmith test cases links that relate to this PR

### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)

## Checklist:
### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2023-05-05 10:51 UTC, abhvsn commented
/ok-to-test

2023-05-05 10:59 UTC, abhvsn commented
/ok-to-test

2023-05-05 12:30 UTC, sharat87 requested changes

2023-05-05 12:30 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/RedisConfig.java
> +        RedisSerializer<Object> defaultSerializer = new JSONSessionRedisSerializer();
Can we use the bean instead of instantiating it again please?

```
    @Bean
    ReactiveRedisTemplate<String, Object> reactiveRedisTemplate(
            ReactiveRedisConnectionFactory factory,
            JSONSessionRedisSerializer serializer
    ) {
        RedisSerializer<String> keySerializer = new StringRedisSerializer();
        RedisSerializationContext<String, Object> serializationContext = RedisSerializationContext
                .<String, Object>newSerializationContext(serializer).key(keySerializer).hashKey(keySerializer)
                .build();
        return new ReactiveRedisTemplate<>(factory, serializationContext);
    }
```

The bean is doing the same thing, just above: 
https://github.com/appsmithorg/appsmith/pull/23029/files#diff-df658b66eae0aad492bb748a530e9e08bdb0ca9b348a5a7a670e0d7f26fbebf8R51

2023-05-05 13:19 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/RedisConfig.java
> +        RedisSerializer<Object> defaultSerializer = new JSONSessionRedisSerializer();
Pushed the changes with:
```
    ReactiveRedisTemplate<String, Object> reactiveRedisTemplate(ReactiveRedisConnectionFactory factory,
                                                                RedisSerializer<Object> serializer)
```
`serializer` will refer to the existing bean created in `springSessionDefaultRedisSerializer()`

2023-05-06 10:43 UTC, sharat87 approved these changes

2023-05-06 11:47 UTC, abhvsn commented
/ok-to-test

2023-05-07 12:34 UTC, abhvsn commented
/ok-to-test

2023-05-08 03:52 UTC, sharat87 approved these changes

2023-05-08 07:25 UTC, merged