fix: Redis Error Message Fix
appsmithorg/appsmith pull request #23067
Opened 2023-05-08 07:35 UTC by PiyushPushkar02

## Description

- Changed the error message returned in case of an invalid hostname for Redis.

Fixes #21405  

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manual
- JUnit

## Checklist:
### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2023-05-09 07:04 UTC, sumitsum requested changes

2023-05-09 07:04 UTC, sumitsum commented on app/server/appsmith-plugins/redisPlugin/src/main/java/com/external/plugins/RedisPlugin.java
> +
Can you please update the variable name to `connectionPool` ?

2023-05-09 07:09 UTC, PiyushPushkar02 commented on app/server/appsmith-plugins/redisPlugin/src/main/java/com/external/plugins/RedisPlugin.java
> +        private Mono<DatasourceTestResult> verifyPing(JedisPool connection) {
Yes as in case of error Mono.error() is thrown. In case of success, Mono.empty() is thrown as in the final testDatasource method a thenReturn method has been added with datasourceTest result object.

2023-05-09 07:24 UTC, sumitsum requested changes

2023-05-09 07:24 UTC, sumitsum commented on app/server/appsmith-plugins/redisPlugin/src/main/java/com/external/plugins/RedisPlugin.java
> +            return Mono.just(connection)
Hi Piyush, can you please update the variable name here as well in the `testDatasource` function ?

2023-05-09 07:57 UTC, PiyushPushkar02 commented on app/server/appsmith-plugins/redisPlugin/src/main/java/com/external/plugins/RedisPlugin.java
> +        private Mono<DatasourceTestResult> verifyPing(JedisPool connection) {
I have checked it @sumitsum everything works with The Mono<Void> return type. Have reverted the type to the same as changing the type there has no effect or usage.

2023-05-09 08:09 UTC, sumitsum approved these changes

2023-05-09 08:10 UTC, PiyushPushkar02 commented
/ok-to-test sha=c82f603

2023-05-10 07:23 UTC, PiyushPushkar02 commented
/build-deploy-preview

2023-05-10 12:38 UTC, merged