Feat: Update unevalTree when setter methods are executed and run evaluations for dependent properties and resolve promise
appsmithorg/appsmith pull request #23063
Opened 2023-05-08 07:12 UTC by Druthi

## Description
1. Update unevalTree when setter methods are executed
2. Run evaluation for the dependent property when a worker is idle and resolve the promise of the setter method.

Fixes #22705 and #22707 

#### Type of change
- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

## Testing
>
#### How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Also list any relevant details for your test configuration.
> Delete anything that is not relevant
- [ ] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-05-08 07:20 UTC, Druthi commented on app/client/src/sagas/EvaluationsSaga.ts
> +    jsUpdates = {},
Temporary change

2023-05-08 07:21 UTC, Druthi commented on app/client/src/workers/Evaluation/evaluate.ts
> +  Object.assign(self, klona(evalContext));
Temp changes

2023-05-17 16:51 UTC, Rishabh-Rathod requested changes

2023-05-17 16:51 UTC, Rishabh-Rathod commented on app/client/src/workers/Evaluation/evalTreeWithChanges.ts
> +  callback?: any,
Let's avoid using `any` for type wherever possible.

2023-05-18 03:29 UTC, Druthi commented on app/client/src/ce/workers/Evaluation/Actions.ts
>    if (entityConfig.__setters) {
But typescript throws errors if we dont

2023-05-18 05:53 UTC, Druthi commented on app/client/src/workers/common/DataTreeEvaluator/index.ts
> +    });
But we need  `overriddenProperties` for `updatedProperties` to be passed to `evalTreeWithChanges`

2023-05-18 10:18 UTC, Rishabh-Rathod commented on app/client/src/workers/Evaluation/evalTreeWithChanges.ts
> +      });
This should happen every time after the sync evaluation, It was a miss in JSObject variable mutation feature. I will create a PR to fix this.

2023-05-18 10:35 UTC, Rishabh-Rathod commented on app/client/src/workers/common/DataTreeEvaluator/index.ts
> +          evalMetaUpdates.push({
let's move this method to separate file and use setEvalTree to update evalTree

2023-05-18 10:35 UTC, Rishabh-Rathod commented on app/client/src/workers/Evaluation/evalTreeWithChanges.ts
> +      });
This was supposed to be there for all the cases, it was missed in JSObject variable mutation feature. I will create a separate PR to add this.

2023-05-19 02:36 UTC, Druthi commented on app/client/src/workers/Evaluation/evalTreeWithChanges.ts
> +      });
Cool makes sense. Shall I remove it from here then?

2023-05-21 12:11 UTC, Rishabh-Rathod commented on app/client/src/workers/Evaluation/setters.ts
> +  // dataTreeEvaluator?.setEvalTree(evalTree);
nit: remove the comment

2023-05-21 12:17 UTC, Druthi commented on app/client/src/workers/Evaluation/setters.ts
> +  // dataTreeEvaluator?.setEvalTree(evalTree);
Done

2023-05-22 05:17 UTC, Rishabh-Rathod approved these changes

2023-05-22 05:19 UTC, merged