feat: Added email bodyType to smtp action (#22749)
appsmithorg/appsmith pull request #23078
Opened 2023-05-08 11:10 UTC by sanveer-osahan

## Description
Added a new field bodyType to SMTP action.
The bodyType field specifies the content-type for email body. Users can choose between 2 options
- Plain Text (`text/plain`)
- HTML (`text/html`)

#### PR fixes following issue(s)
Fixes #22749 

#### Type of change
- New feature (non-breaking change which adds functionality)

## Testing
#### How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Also list any relevant details for your test configuration.
> Delete anything that is not relevant
- [ ] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-05-08 11:16 UTC, sanveer-osahan commented
/ok-to-test

2023-05-08 15:58 UTC, sanveer-osahan commented
/ok-to-test

2023-05-09 07:43 UTC, sumitsum requested changes

2023-05-09 07:43 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog2.java
> +    @ChangeSet(order = "044", id = "add-smtp-email-body-type-to-unpublished-actions", author = "")
Hi Sanveer, recently this way of writing the migrations has been deprecated and hence now each migration method will have to be written inside a class of its own. Please check out `Migration007UpdateOracleLogoToSVG.java` for details. Hence, would request you to move the migration to the newer model.

2023-05-09 07:43 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog2.java
> +                .addCriteria(where("unpublishedAction.actionConfiguration.formData.send.bodyType").exists(false));
Can we skip this criteria, as no configuration object is expected to have the `bodyType` key ?

2023-05-09 08:45 UTC, sanveer-osahan commented on app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog2.java
> +                .addCriteria(where("unpublishedAction.actionConfiguration.formData.send.bodyType").exists(false));
Is this migration executed only once? If yes, then this criteria won't be required. If no, then this is required for filtering the data generated after this PR is merged and ready in release as well as prod

2023-05-09 08:58 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog2.java
> +                .addCriteria(where("unpublishedAction.actionConfiguration.formData.send.bodyType").exists(false));
Hi Sanveer, the migration is run only once in case of success. However, the behaviour is not clear to me in case a failure occurs e.g. would the application still come up and become accessible to the users ? Hence it may be safe to let this change be. Also, as per the documentation, it seems mongock may attempt to re-run the migration on previous failure: 
`meaning this that in case of failure, it will force the migration to be aborted, tracked in the database as failed and Mongock will run it again in the next execution.`
Ref: https://docs.mongock.io/v5/migration/

2023-05-09 10:56 UTC, sumitsum requested changes

2023-05-09 10:56 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration010AddEmailBodyType.java
> +public class Migration010AddEmailBodyType {
Hi Sanveer, can you please change the method and file name to `Migration010AddEmailBodyTypeToSMTPPlugin` - because we also have a separate email service and people could get confused due to the name and assume that this migration is related to that email service.

2023-05-09 10:59 UTC, sumitsum requested changes

2023-05-09 10:59 UTC, sumitsum commented on app/server/appsmith-plugins/smtpPlugin/src/main/java/com/external/plugins/SmtpPlugin.java
> +                mimeBodyPart.setContent(msg, msgType);
Hi Sanveer, can you please check if it would be possible to add a JUnit TC along the lines of `testExecuteWithUTFEncoding()` ?

2023-05-10 05:31 UTC, sanveer-osahan commented
/ok-to-test

2023-05-10 05:32 UTC, sanveer-osahan commented on app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration010AddEmailBodyType.java
> +public class Migration010AddEmailBodyType {
Changed the file name as required

2023-05-10 05:32 UTC, sanveer-osahan commented on app/server/appsmith-plugins/smtpPlugin/src/main/java/com/external/plugins/SmtpPlugin.java
> +                mimeBodyPart.setContent(msg, msgType);
Added the required unit test

2023-05-10 10:07 UTC, sumitsum approved these changes

2023-05-10 11:14 UTC, sanveer-osahan commented
/deploy-preview

2023-05-10 11:15 UTC, sanveer-osahan commented
/build-deploy-preview

2023-05-11 04:33 UTC, prapullc commented
HI @sanveer-osahan 
Enhancement :  When the user selects the type of Body we can show the watermark in the Body field respectively this will enhance  our user experience.

2023-05-11 11:04 UTC, merged