CURL empty command error msg fix
appsmithorg/appsmith pull request #23119
Opened 2023-05-09 09:31 UTC by PiyushPushkar02

## Description

- Changed the error message returned in case of empty input from the user for CURL import

Fixes #12008 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manual

## Checklist:
### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2023-05-10 09:36 UTC, PiyushPushkar02 commented
> Hi @PiyushPushkar02 , can you please add a JUnit TC for this in `CurImporterServiceTests.java` if possible ?

Done @sumitsum

2023-05-10 09:50 UTC, PiyushPushkar02 commented
/ok-to-test

2023-05-10 10:36 UTC, sumitsum requested changes

2023-05-10 10:36 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/CurlImporterServiceCEImpl.java
>              if (input == null) {
Hi Piyush, can you please update this if condition to `StringUtils.isBlank(input)` - this will check for two input being null and input being empty string as well. Also, when using the function please use it like `isBlank(...)` instead of `StringUtils.isBlank(...)` (by using appropriate import statement).

2023-05-10 10:36 UTC, sumitsum commented on app/server/appsmith-server/src/test/java/com/appsmith/server/services/CurlImporterServiceTest.java
> +    public void testImportAction_NullLex() {
Can you please update the test case name to be more verbose and direct e.g. something along the lines of  `testImportActionErrorOnNullInput`. Also, can you please add another test case to test empty string input. ?

2023-05-10 10:44 UTC, PiyushPushkar02 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/CurlImporterServiceCEImpl.java
>              if (input == null) {
Here the input is not a string Object. Its an object of the Java Parent Object class.

2023-05-10 10:52 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/CurlImporterServiceCEImpl.java
>              if (input == null) {
Hi @PiyushPushkar02 , APMU, in the very next line the input object is being cast as a string : `action = curlToAction((String) input, name);` - i.e. the object is actually intended to be a string object. Could we do this type cast early and check for empty string as well ?

2023-05-10 11:40 UTC, sumitsum requested changes

2023-05-10 11:40 UTC, sumitsum commented on app/server/appsmith-server/src/test/java/com/appsmith/server/services/CurlImporterServiceTest.java
> +                        throwable.getMessage().equals(AppsmithError.EMPTY_CURL_INPUT_STATEMENT.getMessage()))
Hi Piyush, it seems like this test is named as `emptyLex` but the input string passed is not actually empty - it contains a single quote - so I am not sure if it is indeed testing for empty string case - can you please check this ? If required, please add a new test case for empty input string case.

2023-05-10 11:40 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/CurlImporterServiceCEImpl.java
> +            if (StringUtils.isBlank((String) input)) {
Hi Piyush, as mentioned earlier, if possible, can you please write it as `isBlank(...)` and add import statement like `import ...StringUtils.isBlank`

2023-05-10 12:21 UTC, PiyushPushkar02 commented on app/server/appsmith-server/src/test/java/com/appsmith/server/services/CurlImporterServiceTest.java
> +                        throwable.getMessage().equals(AppsmithError.EMPTY_CURL_INPUT_STATEMENT.getMessage()))
As suggested @sumitsum I have checked the mentioned method. It seems to be checking for invalid input rather than empty input. I have added a test case for empty input and also changed the name for above mentioned to to InvalidInput.

2023-05-10 12:32 UTC, sumitsum approved these changes

2023-05-11 06:13 UTC, PiyushPushkar02 commented
/build-deploy-preview

2023-05-11 07:20 UTC, PiyushPushkar02 commented
/build-deploy-preview

2023-05-11 11:39 UTC, merged