Feature: Run Button integration
appsmithorg/appsmith pull request #2319
Opened 2020-12-22 22:27 UTC by devrk96

2020-12-29 18:22 UTC, hetunandu requested changes

2020-12-29 18:22 UTC, hetunandu commented on app/client/src/pages/Editor/APIEditor/Form.tsx
> +  .t--apiFormRunBtn {
Dont use test classes for styling. Dont add arbitrary spacing for styles

2020-12-29 22:27 UTC, devrk96 commented on app/client/src/pages/Editor/APIEditor/Form.tsx
> +  .t--apiFormRunBtn {
@hetunandu Resolved it. Please review again.

2020-12-31 05:00 UTC, hetunandu approved these changes

2021-01-05 02:31 UTC, merged