fix: ArangoDB Integration: fix error message on bad host address
appsmithorg/appsmith pull request #23267
Opened 2023-05-12 07:54 UTC by sumitsum

## Description
- Add infra to re-format error messages. 
- Re-format error message for test datasource failure due to (1) bad endpoint (2) timeout

#### PR fixes following issue(s)
Fixes # 21782

#### Type of change
- Bug fix (non-breaking change which fixes an issue)

## Testing
#### How Has This Been Tested?
- JUnit TCs
- Manual

#### Test Plan

> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-05-12 09:56 UTC, sumitsum commented
/ok-to-test

2023-05-12 11:58 UTC, sanveer-osahan requested changes

2023-05-12 11:58 UTC, sanveer-osahan commented on app/server/appsmith-plugins/arangoDBPlugin/src/main/java/com/external/plugins/ArangoDBPlugin.java
> -                        log.error("Error when testing ArangoDB datasource.", error);
Why this `log.error()` was removed in the change?

2023-05-12 11:58 UTC, sanveer-osahan commented on app/server/appsmith-plugins/arangoDBPlugin/src/main/java/com/external/utils/ArangoDBErrorUtils.java
> +            arangodbErrorUtils = new ArangoDBErrorUtils();
It's always a good practice to have a private constructor for util classes and/or singleton classes.

2023-05-12 12:17 UTC, sumitsum commented on app/server/appsmith-plugins/arangoDBPlugin/src/main/java/com/external/plugins/ArangoDBPlugin.java
> -                        log.error("Error when testing ArangoDB datasource.", error);
Thanks for pointing this out, I have re-added the log.

2023-05-12 12:18 UTC, sumitsum commented on app/server/appsmith-plugins/arangoDBPlugin/src/main/java/com/external/utils/ArangoDBErrorUtils.java
> +            arangodbErrorUtils = new ArangoDBErrorUtils();
Hi Sanveer, thanks for pointing this out, I have made the default constructor private via lombok annotation `@NoArgsConstructor(access = AccessLevel.PRIVATE)`

2023-05-13 05:44 UTC, sanveer-osahan commented on app/server/appsmith-plugins/arangoDBPlugin/src/main/java/com/external/utils/ArangoDBErrorUtils.java
> +            arangodbErrorUtils = new ArangoDBErrorUtils();
Hi Sumit, I had missed that. Thanks

2023-05-13 05:45 UTC, sanveer-osahan approved these changes

2023-05-15 05:05 UTC, sumitsum commented
/ok-to-test

2023-05-15 23:28 UTC, sumitsum commented
/build-deploy-preview skip-tests=true

2023-05-16 11:03 UTC, sumitsum commented
/ok-to-test

2023-05-17 01:51 UTC, sumitsum commented
/ok-to-test

2023-05-22 05:35 UTC, sumitsum commented
/ok-to-test

2023-05-22 08:53 UTC, merged