feat: added notification support for workspace invite
appsmithorg/appsmith pull request #23272
Opened 2023-05-12 08:44 UTC by abhiappsmith

## Description

### Issue
We will send notification emails when a user is invited through workspace-level invites. Issue: #19462 

### Solution
Updated email template for a workspace to invite new and existing users. 

#### PR fixes following issue(s)
Fixes #19462 

#### Type of change
- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

## Testing
This is not tested yet.
#### How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Also list any relevant details for your test configuration.
> Delete anything that is not relevant
- [x] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-05-18 09:14 UTC, nsarupr requested changes

2023-05-18 09:14 UTC, nsarupr commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/EmailServiceCE.java
> +    EmailDto getSubjectAndForgotPasswordEmailTemplate(String instanceName);
Can we do the same here?
Rather than exposing a utility function to get the subject and template, can we create a method `sendResetPasswordEmail`?

2023-05-18 09:14 UTC, nsarupr commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UserServiceCEImpl.java
> +                    String instanceName = org.apache.commons.lang3.StringUtils.defaultIfEmpty(commonConfig.getInstanceName(), "Appsmith");
Let's check if the apache.common.lang3.StringUtils can be used for other usages as well, so that we can avoid such a long name.

2023-05-18 09:14 UTC, nsarupr commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UserServiceCEImpl.java
> +                    String instanceName = org.apache.commons.lang3.StringUtils.defaultIfEmpty(commonConfig.getInstanceName(), "Appsmith");
Can we move the hardcoded strings to a separate contants file, and name it EmailConstants?

2023-05-18 09:14 UTC, nsarupr commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UserServiceCEImpl.java
>                  })
Since we already have `emailService`, we should use it to abstract the send the reset password email.

2023-05-18 09:14 UTC, nsarupr commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/EmailServiceCEImpl.java
> +    public Mono<Map<String, String>> sendInviteWorkspaceEmail(String originHeader, Workspace workspace, User inviter,
```suggestion
    public Mono<Map<String, String>> sendInviteUserToWorkspaceEmail(String originHeader, Workspace workspace, User inviter,
```

2023-05-18 09:14 UTC, nsarupr commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UserServiceCEImpl.java
> +import kotlin.Pair;
Remove unnecessary imports.

2023-05-18 09:14 UTC, nsarupr commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/UserAndAccessManagementServiceCEImpl.java
> +import com.appsmith.server.services.*;
Same comment. 
Use specific imports.

2023-05-18 09:15 UTC, nsarupr requested changes
Requesting changes.

2023-05-22 06:42 UTC, nsarupr commented
Hi @abhiappsmith, just wanted to know what was the reason behind introducing `EmailService`. This looks more like an abstraction on top of `EmailSender` which exists, and doesn't serve any other purpose. 
And if there is a need to add this, please add it as `EmailSolution`

2023-05-22 06:56 UTC, nsarupr commented on app/server/appsmith-server/src/main/resources/email/forgotPasswordTemplate.html
For the test cases it's different as we some CE and EE folders, and that needs to be corrected as well.

2023-05-22 09:48 UTC, abhiappsmith commented on app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/EmailDto.java
> +import com.fasterxml.jackson.annotation.JsonView;
Changed to Data

2023-05-22 09:59 UTC, abhiappsmith commented on app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/EmailDto.java
> +@AllArgsConstructor
Done

2023-05-22 09:59 UTC, abhiappsmith commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/EmailService.java
> +import reactor.core.publisher.Mono;
Done

2023-05-22 09:59 UTC, abhiappsmith commented on app/server/appsmith-server/src/main/resources/email/forgotPasswordTemplate.html
I think for resources there should not be any ce folder and for ee there should be ee folder. 
Reason for no ce folder: From POV of CE repo, the structure looks like resources-> email->ce. If we place all templates inside ce folder, then ce folder will not look useful. From CE POV ee folder does not exist.
Reason for ee folder: From the POV of EE repo, the structure will look like resources->email->ee->"ee specific templates". Inside email folder there are ce files and ee folder with ee files.

2023-08-04 07:57 UTC, closed without merging