Docs/update client server setup readme
appsmithorg/appsmith pull request #23300
Opened 2023-05-12 21:12 UTC by micarner

This is my first PR for this project. Please let me know if anything is out of order.

## Description
I had some unique difficulties getting this going on Windows using WSL2. I added some additional verbiage to direct users to the WSL2 sections as well as some additional troubleshooting tips. Only changes are to the Client and Server readme's

#### PR fixes following issue(s)
Related to open issue #1227 for updating documentation

#### Type of change
- Chore (housekeeping or task changes that don't impact user perception)

## Testing

#### How Has This Been Tested?
No need, it's just the github readme pages
 

## Checklist:
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] PR is being merged under a feature flag

2023-05-15 14:15 UTC, somangshu commented
@danciaclara tagging you for the copy

2023-05-17 06:42 UTC, sumitsum requested changes

2023-05-17 06:42 UTC, sumitsum commented on contributions/ServerSetup.md
> +## What's in the box
Hi, can we please revert back to the older heading i.e. `What's in the docker container` as it is not clear what `box` means ?

2023-05-17 06:42 UTC, sumitsum commented on contributions/ServerSetup.md
> +This document explains how you can setup a development environment for Appsmith server. As the server codebase is written in Java and is powered by Spring + WebFlux we need Java and Maven installed t
Hi, could we move this para back to where it was as it mainly talks about installing pre-requisites (also the last line says `Let's get those prerequisites installed on your machine.`) . At the moment it looks wierd here because the last line says we are going to install pre-requisites but then the following section is about something else.

2023-05-17 06:42 UTC, sumitsum commented on contributions/ServerSetup.md
> -## MacOS/Unix Systems
Why is the `MacOS/Unix` header removed ? IMO, this would be useful to anyone wanting to install on Windows as they would be warned that these instructions are only for Mac / Unix.

2023-05-17 06:42 UTC, sumitsum commented on contributions/ServerSetup.md
> +### Convert a standalone MongoDB node to a replica set for non docker based set up
Hi, sorry, could we revert back to the earlier format for this section i.e. installing Mongo, as the formatting and nesting seems better in the earlier format. Also, it does not seem meaningful to create a new header for dealing with non-docker based setup as there is no header specefically for docker based setup.

2023-05-17 06:42 UTC, sumitsum commented on contributions/ServerSetup.md
> +#### 4. Setup Environment file
This looks inconsistent: step 4 shown as a header but steps 1-3 are non-headers.

2023-05-17 07:04 UTC, sumitsum commented on contributions/ServerSetup.md
> +### Troubleshooting
Is this section specific to WSL ?

2023-05-18 15:05 UTC, micarner commented on contributions/ServerSetup.md
> -## MacOS/Unix Systems
Not sure why this was removed in my commit. I just cleaned up some things including adding this back in.

2023-05-18 15:06 UTC, micarner commented on contributions/ServerSetup.md
> +This document explains how you can setup a development environment for Appsmith server. As the server codebase is written in Java and is powered by Spring + WebFlux we need Java and Maven installed t
This was done in error. I have fixed this in the most recent commit.

2023-05-18 15:07 UTC, micarner commented on contributions/ServerSetup.md
> +## What's in the box
I've made this change in the most recent commit

2023-05-30 15:20 UTC, micarner commented
@sumitsum 
I cleaned things up here, can you take another look? Please let me know if I should be making any other changes.

2023-07-08 16:36 UTC, closed without merging