chore: disable mongo/redis charts and update init-container images
appsmithorg/appsmith pull request #23401
Opened 2023-05-16 11:35 UTC by pratapaprasanna

Fixes: [21271](https://github.com/appsmithorg/appsmith/issues/21272)
and 
disable mongo and redis sub charts from installing appsmith by default and update the init-container images

2023-05-18 08:11 UTC, sharat87 commented on deploy/helm/templates/configMap.yaml
> +{{- $encryptionPassword := randAlphaNum 14 -}}
Since we are generating them when rendering this template, does that mean they'll be lost when they update the Helm charts? They won't be stored anywhere, right? Not in `values.yml`, and not in `docker.env`, so it'll be super hard to recover, right?

2023-05-18 08:50 UTC, pratapaprasanna commented on deploy/helm/templates/configMap.yaml
> +{{- $encryptionPassword := randAlphaNum 14 -}}
1- While updating from appsmith-ce-helm-chart-2.0.2 to  appsmith-ce-helm-chart-2.0.3 
for the first time we recommend users to give the existing encryptionSalt and encryptionPassword in values.yaml
  1.1- If the user is updating the helm charts. he usually does it with `helm upgrade` and as a practice it is recommended to keep configmap and secrets backedup.
  1.2- We can even suggest user to do `helm get values appsmith > values_existing.yaml`and preserve them before updating
2- If the values are present in configmap pod restarts also wont cause any disturbance
3- Incase, if some one uninstalls the helm charts without taking backup of salt and password and does a helm install only then the user may face issues.

2023-06-02 10:35 UTC, sharat87 requested changes

2023-06-02 10:35 UTC, sharat87 commented on deploy/helm/values.yaml
> +    periodSeconds: 60
Can you put a note on why we want to make these configurable please?

2023-06-05 04:05 UTC, pratapaprasanna commented on deploy/helm/values.yaml
> +    periodSeconds: 60
In our cloud-helm charts these values are configurable. To make them consistent across all places we have brought in these changes. 
You want me to add a note in values.yaml as well ?

2023-06-05 08:17 UTC, sharat87 commented on deploy/helm/values.yaml
> +    periodSeconds: 60
Okay, then next question is why do we have them configurable in cloud? Can we not hard-code them there as well? 🤔

2023-06-05 10:15 UTC, pratapaprasanna commented on deploy/helm/values.yaml
> +    periodSeconds: 60
The reason why we made it configurable is because, during times of things being unstable, we wanted a way to operate them via values.yaml and not touch the actual deployment.yaml. 

In this PR. we have hardcoded them [here](https://github.com/appsmithorg/appsmith/pull/23401/files#diff-58ba2866b40688c464b75a1e2b79b702ef338a9eacc84170aa9dcde3a4c331e6R84) . Do you think it makes sense to remove them from values.yaml ?

2023-06-05 12:44 UTC, sharat87 commented on deploy/helm/values.yaml
> +    periodSeconds: 60
Oh okay. Yeah, that the next thing I was coming at. Even if we have them configurable, I'd rather not advertise it. Let's not have it in `values.yaml`, and in fact, I would say name it as `_probes`, instead of just `probes`, to signify that this is an internal configuration section, and users aren't expected to fiddle with it.

What say?

2023-06-06 08:25 UTC, sharat87 requested changes
As discussed, let's remove the `probes` in the published `values.yml` file and then merge this in.

2023-06-07 08:56 UTC, sharat87 requested changes
@pratapaprasanna, there's some miscommunication happening here. I see that we've requested for review again on this PR, but the `probes` is still there in the diff. Am I missing something? 🤔

2023-06-08 10:14 UTC, sharat87 commented on deploy/helm/templates/statefulset.yaml
> +              {{- end }}
We are writing an `else` block only against the first `if` statement. This means, if I understand correct, that if we have `probes: {}` in `values.yaml`, then there will be no `path:` key in the resulting configuration, right? In terms of improving resiliency here, let's ensure that our template implementation works in these three scenarios at least:

1. No `probes` key.
2. Empty `probes` key, like `probes: {}`.
3. Full probes configuration with all nested configuration defined.

Can you confirm if this template works in the second case as well please?

2023-06-08 13:32 UTC, pratapaprasanna commented on deploy/helm/templates/statefulset.yaml
> +              {{- end }}
Updated the comment [here](https://github.com/appsmithorg/appsmith/pull/23401#issue-1711838081)

2023-06-08 14:23 UTC, pratapaprasanna commented on deploy/helm/templates/statefulset.yaml
> +              {{- end }}
However, this will fail for this scenario
```
probes:
   livenessProbe:
     api: "/api/v1/health"
     periodSeconds: 40
```
then 
failureThreshold doesnt appear by default. therefore

2023-06-14 06:06 UTC, sharat87 commented on deploy/helm/templates/statefulset.yaml
> +            {{- end }}
Can we simplify this with the [`default`](https://helm.sh/docs/chart_template_guide/function_list/#default) or [`dig`](https://helm.sh/docs/chart_template_guide/function_list/#dig) functions? It'll be easier to read and reason with I think. What say?
Similarly in other such cases as well.

```suggestion
              path: {{ dig "probes" "startupProbe" "api" "/api/v1/health" .Values | quote }}
```

2023-06-20 13:03 UTC, sharat87 requested changes
@pratapaprasanna, reg including the `probes: {}`, I know we talked about this, but a follow-up question. For existing users of our helm charts, if they update their Helm chart version, it'll fail, unless they go add the `probes: {}` to their `values.yaml`, right?

If we can't use `.Values` with `dig` directly, how about a variable instead? Like in here: https://stackoverflow.com/a/59800232/151048. Like:

```
{{- $probes := .Values.probes | default dict -}}
```

Somewhere at the top of the template, and then we use `$probes` with `dig` instead of `.Values.probes`. Would that work?

Sorry to send this back yet again, but I'm just looking to reduce the friction for folks updating their Helm charts. What say?

2023-06-21 11:01 UTC, pratapaprasanna commented
> @pratapaprasanna, reg including the `probes: {}`, I know we talked about this, but a follow-up question. For existing users of our helm charts, if they update their Helm chart version, it'll fail, unless they go add the `probes: {}` to their `values.yaml`, right?
> 
> If we can't use `.Values` with `dig` directly, how about a variable instead? Like in here: https://stackoverflow.com/a/59800232/151048. Like:
> 
> ```
> {{- $probes := .Values.probes | default dict -}}
> ```
> 
> Somewhere at the top of the template, and then we use `$probes` with `dig` instead of `.Values.probes`. Would that work?
> 
> Sorry to send this back yet again, but I'm just looking to reduce the friction for folks updating their Helm charts. What say?

I couldnt get it to work. I think we have to update docs to `helm show values` and then update

2023-06-27 02:26 UTC, sharat87 reviewed
@pratapaprasanna, can you verify if the changes in https://github.com/appsmithorg/appsmith/pull/23401/commits/bfcd2a1acc361ae25391b258edc6fe581306666a can work if `probes` is not included in `values.yaml` please?

2023-07-06 09:12 UTC, pratapaprasanna commented
> @pratapaprasanna, can you verify if the changes in [bfcd2a1](https://github.com/appsmithorg/appsmith/commit/bfcd2a1acc361ae25391b258edc6fe581306666a) can work if `probes` is not included in `values.yaml` please?

It doesnt work if the probes are commented out

2023-07-07 04:23 UTC, pratapaprasanna commented
> Seems to be working, no? Am I doing something wrong? 🤔
> 
> ![shot-2023-07-06-11-58-52](https://user-images.githubusercontent.com/120119/251442922-42b0677b-adbd-41c3-9e2b-43088acb7083.png)

I have no clue what is happening now. 

I tried the same thing and I was getting the following error. 

```
(base) ➜  helm git:(update/cosmetic/changes/ce) ✗ helm install testappsmith . -n test --create-namespace --dry-run > temp.yaml
Error: INSTALLATION FAILED: template: appsmith/templates/statefulset.yaml:85:23: executing "appsmith/templates/statefulset.yaml" at <dig "startupProbe" "api" "/api/v1/health" .Values.probes>: error calling dig: interface conversion: interface {} is nil, not map[string]interface {}
```

Now, its working .

2023-07-07 04:30 UTC, sharat87 approved these changes

2023-07-07 04:31 UTC, merged