chore: Move permission check to wrapper function in import-export
appsmithorg/appsmith pull request #23429
Opened 2023-05-17 05:21 UTC by nayan-rafiq

## Description
The permission checks for import-export are not centralized today. There are a lot of if-else inside the function that is responsible for the import-export. This PR removes the permission checks from the core process and move them to the wrapper functions which invokes this process.

#### PR fixes following issue(s)
Fixes #22821 

#### Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video
>
>
#### Type of change
> Please delete options that are not relevant.
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
## Testing
>
#### How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Also list any relevant details for your test configuration.
> Delete anything that is not relevant
- [ ] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-05-24 17:33 UTC, nayan-rafiq commented
/ok-to-test sha=c9509c7

2023-05-25 05:35 UTC, Parthvi12 commented
/build-deploy-preview

2023-05-25 09:47 UTC, abhvsn reviewed
Added minor comments but overall LGTM!
I would like @trishaanand to take a look before merging this in.

2023-05-25 09:47 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
> +                                            .userPermissionGroups(permissionGroups)
Should we include the `manage:theme` permission as well?

2023-05-25 09:47 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
> +                            .workspacePermission(workspacePermission.getApplicationCreatePermission())
Do we want to add `create:datasource` permission at workspace level, this might be needed for git pull? Compared to regular git ops this is far less required permission though and I would not restrict users using the git feature because this permission is missing.

2023-05-26 06:43 UTC, nayan-rafiq commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
> +                            .workspacePermission(workspacePermission.getApplicationCreatePermission())
Got it. As we check for create datasource permission runtime so I think we can check read permission here. What do you think?

2023-05-26 08:12 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
> +                            .workspacePermission(workspacePermission.getApplicationCreatePermission())
Yes, that should work.

2023-05-26 10:22 UTC, nayan-rafiq commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
> +                                            .userPermissionGroups(permissionGroups)
@abhvsn There is no explicit way to create or edit a theme so I've not added that permission here. When we edit a theme, we're actually editing the app because theme properties are stored in the application.

2023-05-26 10:30 UTC, nayan-rafiq commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
> +                            .workspacePermission(workspacePermission.getApplicationCreatePermission())
@abhvsn I've removed workspace permission check because the Git service already checks application create permission before passing it to import-export service.

2023-05-29 05:09 UTC, abhvsn approved these changes

2023-05-29 05:10 UTC, Parthvi12 commented
/build-deploy-preview

2023-05-29 08:54 UTC, Parthvi12 submitted a review, later dismissed

2023-05-30 05:10 UTC, nayan-rafiq commented
/ok-to-test sha=de612f8

2023-05-30 20:08 UTC, abhvsn approved these changes

2023-05-31 10:01 UTC, nayan-rafiq commented
/ok-to-test sha=4787c93

2023-06-05 05:05 UTC, nayan-rafiq commented
/ok-to-test sha=febf7cc

2023-06-05 08:45 UTC, trishaanand reviewed
LGTM. Added minor review comments.

2023-06-05 08:45 UTC, trishaanand commented on app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomPermissionGroupRepositoryCEImpl.java
> +    @Override
Why are we overriding this if all we do is call the super function?

2023-06-05 08:45 UTC, trishaanand commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCE.java
> +    Mono<Application> restoreSnapshot(String workspaceId, ApplicationJson importedDoc, String applicationId, String branchName);
Nit: Should we also add javadoc for this?

2023-06-05 08:45 UTC, trishaanand commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
> +                                    ImportApplicationPermissionProvider permissionProvider = ImportApplicationPermissionProvider.builder()
Nit: Could we move this to a helper function to increase code readability? Thanks!

2023-06-05 08:45 UTC, trishaanand commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
> +                            .applicationPermission(applicationPermission.getEditPermission())
What about datasource permissions? Would the datasources get created even if the current user does not have create datasource permissions?

2023-06-05 08:45 UTC, trishaanand commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
> +                                return newPageService.findByGitSyncIdAndDefaultApplicationId(defaultApplicationId, newPage.getGitSyncId(), Optional.empty())
Nit: Could we extract this section out in a helper function?

2023-06-05 08:45 UTC, trishaanand commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
> +                            return newActionRepository.findByGitSyncIdAndDefaultApplicationId(defaultApplicationId, newAction.getGitSyncId(), Optional.empty())
Nit: Could we extract this section out in a helper function?

2023-06-05 08:45 UTC, trishaanand commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
> +                            return actionCollectionRepository.findByGitSyncIdAndDefaultApplicationId(defaultApplicationId, actionCollection.getGitSyncId(), Optional.empty())
Nit: Could we extract this section out in a helper function?

2023-06-05 08:45 UTC, trishaanand reviewed
LGTM. Added minor review comments.

2023-06-05 12:47 UTC, nsarupr requested changes

2023-06-05 19:00 UTC, nayan-rafiq commented on app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomPermissionGroupRepositoryCEImpl.java
> +    @Override
Because the method in the parent class is defined as `protected` so it's not accessible from services.

2023-06-05 19:20 UTC, nayan-rafiq commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
> +                                    ImportApplicationPermissionProvider permissionProvider = ImportApplicationPermissionProvider.builder()
Done. Moved the builder code to a private method.

2023-06-05 21:57 UTC, nayan-rafiq commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
> +                            return actionCollectionRepository.findByGitSyncIdAndDefaultApplicationId(defaultApplicationId, actionCollection.getGitSyncId(), Optional.empty())
Done

2023-06-05 21:57 UTC, nayan-rafiq commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
> +                            return newActionRepository.findByGitSyncIdAndDefaultApplicationId(defaultApplicationId, newAction.getGitSyncId(), Optional.empty())
Done

2023-06-05 21:58 UTC, nayan-rafiq commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
> +                                return newPageService.findByGitSyncIdAndDefaultApplicationId(defaultApplicationId, newPage.getGitSyncId(), Optional.empty())
Done

2023-06-05 21:59 UTC, nayan-rafiq commented on app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomPermissionGroupRepositoryCEImpl.java
> +
The super method is protected, so it's not accessible outside the package. Hence I've added a public wrapper.

2023-06-06 04:55 UTC, nayan-rafiq commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
> +    public Mono<Application> restoreSnapshot(String workspaceId, ApplicationJson importedDoc, String applicationId, String branchName) {
Yeah, it may require that permission. Consider a case - application has a datasource, snapshot created and then the datasource is deleted. Now, restoring the snapshot will recreate the datasource.

2023-06-06 04:55 UTC, nayan-rafiq commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
> +        return permissionGroupRepository.getCurrentUserPermissionGroups().flatMap(userPermissionGroups -> {
Done

2023-06-06 08:44 UTC, nayan-rafiq commented on app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/PolicyUtils.java
> +
@nsarupr Once this is merged, we can create another PR in EE to use this method from CE. What do you think on this?

2023-06-06 09:38 UTC, nayan-rafiq commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/NewPageServiceCE.java
> +    Mono<Boolean> isPermissionPresentForCurrentUser(NewPage obj, String permission);
Done. Actually this method is no more required so I've removed it.

2023-06-06 09:46 UTC, nayan-rafiq commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationServiceCEImpl.java
> +
This method is no more required actually so I just removed it.

2023-06-06 10:57 UTC, nayan-rafiq commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
> +                }))
No specific reason actually, it was there. I added the log only. Moving this to the workspace mono.

2023-06-06 11:01 UTC, nayan-rafiq commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
> +        Mono<Workspace> workspaceMono = workspaceService.findById(workspaceId, permissionProvider.getWorkspacePermission());
@nsarupr This was the plan actually - separate permission from the main flow so that there is no if-else for permission checks. The permission provider will be supplied by the caller method. It's true that if the permission provider is not created properly, the permission will be bypassed. Can you suggest any other way that we can follow?

2023-06-09 10:12 UTC, nayan-rafiq commented
/ok-to-test sha=2ce830d

2023-06-09 11:17 UTC, trishaanand approved these changes

2023-06-09 11:34 UTC, merged