feat: Implemented Schema Fetch for MSSQL Plugin (#16014)
appsmithorg/appsmith pull request #23498
Opened 2023-05-18 12:55 UTC by sanveer-osahan

## Description

Implemented Get Structure for MSSQL Plugin.
Refactored the existing code for MSSQL Plugin. Added the following
- `MssqlDatasourceUtils` - contains the utilities for getting connection, logging Hikari CP Status and getting DB schema structure and templates
- `MssqlExecuteUtils` - contains utilities for populating rows  and columns, and closing connection  after query execution
- `MssqlTestDBContainerManager` - Test helper to create container, datasource configuration and run queries for MSSQL unit tests

#### PR fixes following issue(s)
Fixes #16014

#### Media
<img width="1438" alt="Screenshot 2023-05-19 at 9 36 07 AM" src="https://github.com/appsmithorg/appsmith/assets/28753975/aec5fe31-e3e1-43b4-a946-dfc946dcfd05">

#### Type of change
- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

## Testing
>
#### How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Also list any relevant details for your test configuration.
- [x] Manual
- [x] JUnit
>
>
#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-05-18 12:56 UTC, sanveer-osahan commented
/ok-to-test

2023-05-19 03:18 UTC, sanveer-osahan commented
/build-deploy-preview

2023-05-19 04:49 UTC, sumitsum requested changes

2023-05-19 04:49 UTC, sumitsum commented on app/server/appsmith-plugins/mssqlPlugin/src/main/java/com/external/plugins/MssqlPlugin.java
> +import com.appsmith.external.models.*;
Hi Sanveer, can you please replace wildcard import everywhere in the PR with specific import statements - this is a convention that we follow - although arguments can be made in favour or against of either of the two ways.

2023-05-19 04:49 UTC, sumitsum commented on app/server/appsmith-plugins/mssqlPlugin/src/main/java/com/external/plugins/utils/MssqlDatasourceUtils.java
> +            case "NUMBER", "INT" -> "1";
Nice. This newer Java syntax looks comparatively cleaner, should also server as an encouragement for any reader to migrate to newer syntax.

2023-05-19 04:53 UTC, sanveer-osahan commented on app/server/appsmith-plugins/mssqlPlugin/src/main/java/com/external/plugins/MssqlPlugin.java
> +import com.appsmith.external.models.*;
Hey Sumit, even I like to follow specific import statements instead of wildcard. Sometimes the IDE adds them on its own 😞 
Making the required change.
Thanks for noticing

2023-05-19 04:54 UTC, sanveer-osahan commented on app/server/appsmith-plugins/mssqlPlugin/src/main/java/com/external/plugins/utils/MssqlDatasourceUtils.java
> +            case "NUMBER", "INT" -> "1";
Thanks Sumit for the comment. I was aware that there some changes to how we write switch statements in new Java versions. But didn't know it was this concise.

2023-05-19 05:34 UTC, sumitsum requested changes

2023-05-19 05:34 UTC, sumitsum commented on app/server/appsmith-plugins/mssqlPlugin/src/main/java/com/external/plugins/MssqlPlugin.java
> +import java.sql.*;
Hi @sanveer-osahan looks like there are other wildcard imports as well, can you please replace them as well ?

2023-05-19 05:58 UTC, sumitsum submitted a review, later dismissed

2023-05-19 06:23 UTC, sanveer-osahan commented
@prapullac @btsgh We'll only be focusing on the schemas for MSSQL here. For Generate CRUD Page, there's a separate [issue](https://github.com/appsmithorg/appsmith/issues/8590) and will be fixed in that.

2023-05-22 12:19 UTC, prapullc commented
Hey @sanveer-osahan 
Trying to create a query from the entity explorer does not show an example query.
https://www.loom.com/share/7c5d40b343f84c39af515dc095d823e5

2023-05-23 00:55 UTC, sanveer-osahan commented
/build-deploy-preview

2023-05-23 03:10 UTC, sanveer-osahan commented
/ok-to-test

2023-05-24 04:37 UTC, sumitsum approved these changes

2023-05-24 06:08 UTC, merged