fix: casing changes
appsmithorg/appsmith pull request #23515
Opened 2023-05-19 05:55 UTC by tanvibhakta

#### Type of change

- Chore (housekeeping or task changes that don't impact user perception)

## Testing
>
#### How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Also list any relevant details for your test configuration.
> Delete anything that is not relevant
- [ ] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-05-19 06:41 UTC, tanvibhakta commented
/ok-to-test sha=8c8ec77

2023-05-19 12:44 UTC, tanvibhakta commented
/ok-to-test

2023-05-22 07:41 UTC, tanvibhakta commented
/ok-to-test

2023-05-22 07:46 UTC, albinAppsmith commented on app/client/src/ce/constants/messages.test.ts
> +      `The XYZ feature is exclusive to workspaces on the Business Edition`,
This was a decision taken by stakeholders?

2023-05-22 07:47 UTC, albinAppsmith submitted a review, later dismissed

2023-05-22 11:56 UTC, rohitagarwal88 requested changes

2023-05-22 11:56 UTC, rohitagarwal88 commented on app/client/src/ce/constants/messages.ts
> +export const CONNECT_TO_GIT_OPTION = () => "Connect to git repository";
@tanvibhakta / @albinAppsmith : This will be `Git` not `git`

2023-05-22 11:56 UTC, rohitagarwal88 commented on app/client/src/ce/constants/messages.ts
> +  `I would like to enable custom branding for my workspace and am interested in Appsmith Business.`;
@tanvibhakta / @albinAppsmith this will be `Custom Branding` coz its an offering

2023-05-22 11:56 UTC, rohitagarwal88 commented on app/client/src/ce/constants/messages.ts
>  export const DISCARD_SNAPSHOT_HEADER = () => "Discarding a Snapshot";
@tanvibhakta / @albinAppsmith : `Discarding a Snapshot` -> `Discarding a snapshot`

2023-05-22 11:56 UTC, rohitagarwal88 commented on app/client/src/ce/constants/messages.ts
> +export const CONVERT_TO_FIXED_TITLE = () => "Convert to fixed layout";
@tanvibhakta : @vinay-appsmith, Intentionally asked to keep `Fixed`, `Auto`.
Please correct me @vinay-appsmith , if I'm wrong

2023-05-22 11:57 UTC, rohitagarwal88 requested changes
Added comment please check

2023-05-26 10:47 UTC, tanvibhakta commented on app/client/src/ce/constants/messages.test.ts
> +      `The XYZ feature is exclusive to workspaces on the Business Edition`,
Yes - Pranay has confirmed this.

2023-05-27 13:03 UTC, theparthacus commented on app/client/src/ce/constants/messages.ts
> +export const CONVERT_TO_FIXED_TITLE = () => "Convert to fixed layout";
actually, `auto-layout` and `fixed layout`. neither are Appsmith-specific features and thus not, proper nouns.

2023-05-27 13:06 UTC, theparthacus commented on app/client/src/ce/constants/messages.ts
> +export const CONNECT_TO_GIT_OPTION = () => "Connect to git repository";
@tanvibhakta, the name of the project is Git. as such all repos that use the project are called Git repos. `git` is only used when referring to the command.

2023-05-27 13:07 UTC, theparthacus commented on app/client/src/ce/constants/messages.ts
> +export const ADD_QUERY_JS_TOOLTIP = () => "Add a new query/JS Object";
Nope. JS Object. Appsmith-specific feature, not an `object` as used in JavaScript. same as `Custom Branding`.

2023-06-05 03:16 UTC, tanvibhakta commented
/ok-to-test

2023-06-05 03:33 UTC, tanvibhakta commented
/ok-to-test

2023-06-05 04:52 UTC, tanvibhakta commented
/ok-to-test

2023-06-05 05:01 UTC, rohitagarwal88 requested changes

2023-06-05 06:48 UTC, tanvibhakta commented
/ok-to-test

2023-06-05 06:48 UTC, tanvibhakta commented
/build-deploy-preview skip-tests=true env=release

2023-06-06 02:07 UTC, tanvibhakta commented
/ok-to-test

2023-06-06 02:29 UTC, tanvibhakta commented
/ok-to-test

2023-06-07 04:48 UTC, rohitagarwal88 requested changes

2023-06-07 04:48 UTC, rohitagarwal88 commented on app/client/src/widgets/TableWidgetV2/component/ConnectDataOverlay.tsx
> +          To display data, connect your own datasource
@tanvibhakta : why are we updating text inside widget?
We have changed the text completely? Is it vetted by App Viewer Pod

2023-06-07 04:48 UTC, rohitagarwal88 commented on app/client/src/widgets/TableWidgetV2/component/ConnectDataOverlay.tsx
> +        <Footer>, or use mock data</Footer>
@tanvibhakta : same comment as above

2023-06-08 04:06 UTC, tanvibhakta commented
/ok-to-test

2023-06-08 07:29 UTC, tanvibhakta commented
/ok-to-test

2023-06-09 08:52 UTC, merged