Fix/issue 23274/refactor sql datasource plugins
appsmithorg/appsmith pull request #23521
Opened 2023-05-19 07:27 UTC by tkAppsmith

## Description
> Refactoring the create datasource method which initiates a connection in /test endpoint of datasources to a template pattern. Then this will be moved to a separate module.

#### PR fixes following issue(s)
Fixes #23274

#### Type of change
- Chore (housekeeping or task changes that don't impact user perception)

## Testing
>
#### How Has This Been Tested?
- [x] Manual
- [ ] Jest
- [ ] Cypress

#### Test Plan
> Need to get a sanity test done for all changed data sources operation such as test and execute.

#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-05-30 09:00 UTC, sumitsum requested changes

2023-05-30 09:00 UTC, sumitsum commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/datasource/connectionproperties/ArangoDBConnectionProperties.java
> +package com.appsmith.external.datasource.connectionproperties;
Hi @tkAppsmith , APMU, `appsmith-interfaces` module should not ideally have plugin specific files. Any plugin specific file needs to be in the `appsmith-plugin` module. Can you please mention why this file needs to be in the `appsmith-interfaces` module ? Alternatively, would it be possible to move it to the `appsmith-plugin` module ?

2023-05-30 09:51 UTC, tkAppsmith commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/datasource/connectionproperties/ArangoDBConnectionProperties.java
> +package com.appsmith.external.datasource.connectionproperties;
We plan to move all these connection properties and other aspects of connection such as connection creation and its lifecycle to a new module as per the data sources revamp that is being planned. hence clubbing all such things in interface package for now.

2023-05-30 09:54 UTC, sumitsum commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/datasource/connectionproperties/ArangoDBConnectionProperties.java
> +package com.appsmith.external.datasource.connectionproperties;
Hi @tkAppsmith 
(1) Can you please explain what this new module look like ? 
(2) Is there anything stopping us from keeping these files in the `appsmith-plugin` module in the respective plugin paths ? When the new module is available we can move these files to the new module from here.

2023-05-30 11:26 UTC, sumitsum commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/datasource/connectionproperties/ArangoDBConnectionProperties.java
> +package com.appsmith.external.datasource.connectionproperties;
Hi @tkAppsmith, sorry, I still have some questions. Let us discuss this over call, I will ping you regarding this.

2023-06-05 06:35 UTC, nidhi-nair commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/datasource/connectionproperties/ArangoDBConnectionProperties.java
> +package com.appsmith.external.datasource.connectionproperties;
I agree with Sumit here Tushar, the interfaces module is a parent to server as well. It is meant to be the parent module that abstracts high level interfaces for all our other modules. Can we structure this differently so that there is a layer between interfaces and individual plugins where we can define just the plugin specific interfaces?

2023-06-30 09:42 UTC, nidhi-nair requested changes
Waiting for changes, commenting to remove request

2023-12-04 06:01 UTC, closed without merging