Fix/error generic message
appsmithorg/appsmith pull request #2355
Opened 2020-12-24 10:30 UTC by jsartisan

Whenever an action was failing, we were not showing which action was failing. Now, we are showing toast with message as `The action with name ${name} has failed.` so that the user knows which actions are failing.

Fixes #1357 #2339 

- Bug fix

## How Has This Been Tested?
- Manually tested

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2020-12-24 10:56 UTC, mohanarpit commented
@jsartisan Is it possible for us to assert the error toast message? This is to ensure that we don't regress on this feature? It's an important debugging & UX tool in our kitty. Would like to ensure that this always works.

2020-12-24 11:13 UTC, jsartisan commented
> @jsartisan Is it possible for us to assert the error toast message in an automated test? This is to ensure that we don't regress on this feature? It's an important debugging & UX tool in our kitty. Would like to ensure that this always works.

Done :D 
Sorry, I should have created the PR after adding test cases.

2020-12-28 05:20 UTC, mohanarpit commented on app/client/src/sagas/ActionExecutionSagas.ts
> +            message: `The action with name "${pageAction.name}" has failed.`,
```suggestion
            message: `The action "${pageAction.name}" has failed.`,
```

Also, by any chance do you get the error message from the server? If yes, is it possible to add that to the display here? Will make it easier for users to debug this.

2020-12-28 06:42 UTC, jsartisan commented on app/client/src/sagas/ActionExecutionSagas.ts
> +            message: `The action with name "${pageAction.name}" has failed.`,
@mohanarpit We get this type of response from the server whenever the action is failing:

<img width="877" alt="Screenshot 2020-12-28 at 12 12 03 PM" src="https://user-images.githubusercontent.com/6636360/103194533-fd674600-4905-11eb-8667-60886f784667.png">

2020-12-28 06:51 UTC, jsartisan commented on app/client/src/sagas/ActionExecutionSagas.ts
> +            message: `The action with name "${pageAction.name}" has failed.`,
Showing message like this now:

<img width="306" alt="Screenshot 2020-12-28 at 12 20 52 PM" src="https://user-images.githubusercontent.com/6636360/103194940-2e944600-4907-11eb-9ed8-e89cdf768e89.png">

2020-12-30 08:28 UTC, hetunandu requested changes

2020-12-30 08:28 UTC, hetunandu commented on app/client/src/actions/widgetActions.tsx
> +  console.log({ executeErrorPayload });
Missed console.log

2020-12-30 08:29 UTC, riodeuno requested changes

2020-12-30 08:29 UTC, riodeuno commented on app/client/src/actions/widgetActions.tsx
> +  console.log({ executeErrorPayload });
We left a console.log in the code. Can we use `log.debug` if we need to log this?

2021-01-04 06:07 UTC, jsartisan commented on app/client/src/actions/widgetActions.tsx
> +  console.log({ executeErrorPayload });
Removed the log.

2021-01-04 06:07 UTC, jsartisan commented on app/client/src/actions/widgetActions.tsx
> +  console.log({ executeErrorPayload });
Sorry. That console was just for debugging purpose. Removed it.

2021-01-05 19:26 UTC, hetunandu submitted a review, later dismissed

2021-01-06 05:25 UTC, merged