feat: onboarding flow revamp for first time admin users: ce
appsmithorg/appsmith pull request #23581
Opened 2023-05-22 06:37 UTC by dipyamanbiswas07

Onboarding flow revamp for first time admin users.
Uses the new ADS2.0 Components.
Shows telemetry popup.

zeplin: https://app.zeplin.io/project/642f9f61af65ec6928659130/screen/64476316d729f744cb695232

#### PR fixes following issue(s)
Fixes #https://github.com/appsmithorg/cloud-services/issues/673

#### Type of change
> Please delete options that are not relevant.
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update
>
>
>
## Testing
>
#### How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Also list any relevant details for your test configuration.
> Delete anything that is not relevant
- [x] Manual
- [ ] Jest
- [x] Cypress
>
>
#### Test Plan
> 
> https://github.com/appsmithorg/TestSmith/issues/2401
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-05-22 06:38 UTC, dipyamanbiswas07 commented
/ok-to-test sha=99f48f4

2023-05-22 06:39 UTC, dipyamanbiswas07 commented
/build-deploy-preview

2023-05-22 08:59 UTC, dipyamanbiswas07 commented
/ok-to-test sha=1b1900b

2023-05-22 10:35 UTC, dipyamanbiswas07 commented
/ok-to-test sha=ae95576

2023-05-23 06:02 UTC, berzerkeer requested changes

2023-05-23 06:02 UTC, berzerkeer commented on app/client/src/pages/setup/SetupForm.tsx
> +    anonymousDataInput.checked = true;
so if its airgapped, this should be false I guess.

2023-05-23 06:30 UTC, ankitakinger commented on app/client/src/pages/setup/DetailsForm.tsx
> +import { isAirgapped } from "ce/utils/airgapHelpers";
should be `@appsmith` import

2023-05-23 06:31 UTC, ankitakinger commented on app/client/src/pages/setup/DetailsForm.tsx
> +          style={isFirstPage() ? { backgroundColor: `${Colors.GRAY_300}` } : {}}
Can we instead use ADS colors here? +1 on Sangeeth's point here.

2023-05-23 06:32 UTC, berzerkeer commented on app/client/src/pages/setup/DetailsForm.tsx
> +          style={isFirstPage() ? { backgroundColor: `${Colors.GRAY_300}` } : {}}
Ohh also ADS colors , I completely missed it 😅

2023-05-23 06:33 UTC, ankitakinger commented on app/client/src/pages/setup/DetailsForm.tsx
> +                  placeholder=""
blank placeholder, intentional?

2023-05-23 06:33 UTC, ankitakinger commented on app/client/src/pages/setup/DetailsForm.tsx
> +                  placeholder=""
same here, blank placeholder, intentional?

2023-05-23 06:36 UTC, ankitakinger commented on app/client/src/pages/setup/GetStarted.tsx
> +          disabled={props.invalid}
I don't think `Button` works with prop `disabled`. It should be `isDisabled`.

2023-05-23 08:20 UTC, dipyamanbiswas07 commented on app/client/src/pages/setup/DetailsForm.tsx
> +                  placeholder=""
Yes intentional. Since this is a text field which shows up on selection of Others, its self explanatory

2023-05-23 08:20 UTC, dipyamanbiswas07 commented on app/client/src/pages/setup/DetailsForm.tsx
> +                  placeholder=""
Yes intentional. Since this is a text field which shows up on selection of Others, its self explanatory

2023-05-23 08:26 UTC, dipyamanbiswas07 commented on app/client/cypress/support/commands.js
> -    cy.get(welcomePage.dataCollection).should("not.exist");
The allowCollectionAnonymous and signupForNewsletter fields do not exist anymore. So have removed it.

2023-05-23 10:37 UTC, dipyamanbiswas07 commented on app/client/src/pages/Editor/FirstTimeUserOnboarding/AnonymousDataPopup.tsx
> +} from "ce/constants/messages";
Done

2023-05-23 10:38 UTC, dipyamanbiswas07 commented on app/client/src/pages/Editor/FirstTimeUserOnboarding/AnonymousDataPopup.tsx
> +            children: "Admin Settings",
Done

2023-05-23 10:39 UTC, berzerkeer commented on app/client/cypress/support/commands.js
> -    cy.get(welcomePage.dataCollection).should("not.exist");
Then it should be removed from here aswell https://github.com/appsmithorg/appsmith/pull/23581#discussion_r1201571006

2023-05-23 10:41 UTC, dipyamanbiswas07 commented on app/client/src/pages/setup/DetailsForm.tsx
> +            {isFirstPage() ? "Continue" : "Get Started"}
Done

2023-05-23 10:41 UTC, dipyamanbiswas07 commented on app/client/src/pages/setup/DetailsForm.tsx
> +            <StyledFormGroup className="!w-52 t--welcome-form-first-name">
Its a css class from tailwind

2023-05-23 10:41 UTC, dipyamanbiswas07 commented on app/client/src/pages/Editor/FirstTimeUserOnboarding/AnonymousDataPopup.tsx
> +            to: "https://docs.appsmith.com/product/telemetry",
Done

2023-05-23 10:43 UTC, berzerkeer commented on app/client/src/pages/setup/DetailsForm.tsx
> +            <StyledFormGroup className="!w-52 t--welcome-form-first-name">
Yeah I get that its a utility class from tailwind for width but what does the `!` before it signifies. Having a hard time finding the doc for it or what it does here https://tailwindcss.com/docs/width . Can you help me with understanding that ? thanks !

2023-05-23 10:47 UTC, dipyamanbiswas07 commented on app/client/src/pages/setup/GetStarted.tsx
> +          disabled={props.invalid}
done

2023-05-23 10:48 UTC, dipyamanbiswas07 commented on app/client/src/pages/setup/SetupForm.tsx
> +    anonymousDataInput.checked = true;
Done

2023-05-23 10:48 UTC, dipyamanbiswas07 commented on app/client/src/pages/setup/DetailsForm.tsx
> +            <StyledFormGroup className="!w-52 t--welcome-form-first-name">
Yes ! means its important. Same as !important in CSS.

2023-05-23 10:50 UTC, dipyamanbiswas07 commented on app/client/src/pages/setup/DetailsForm.tsx
> +            <StyledFormGroup className="!w-52 t--welcome-form-first-name">
https://tailwindcss.com/docs/configuration#important-modifier

2023-05-23 10:51 UTC, berzerkeer commented
Also do you have the EE PR for this aswell ? I would suggest merging this after you pull these changes to your EE PR and run the `/ok-to-test` in that PR. Because we have onboarding changes here which could break airgap and EE onboarding cypress because of a behaviour change, i.e

We now show the disable telemetry test and since this toast won't be available on airgap, the tests could fail on beforeAll hook or wherever you are asserting it so make sure you assert for the absence of this toast in airgap aswell by following this doc https://www.notion.so/appsmith/Cypress-Airgap-a60eac72281b4c4d992a845b4b3a4fac?pvs=4

Add a `airgap` tagged test or just do `Cypress.env(AIRGAPPED)` to test for this behaviour so that its handled doesn't break cypress.  Please keep this in mind before merging this.

@dipyamanbiswas07

2023-05-23 10:51 UTC, dipyamanbiswas07 commented on app/client/cypress/support/commands.js
> -    cy.get(welcomePage.dataCollection).should("not.exist");
So the telemetry is by default turned on for non airgapped users now, so we should not remove that. The newsletter is now a check box and ill add a condition around it in the tests.

2023-05-23 10:57 UTC, berzerkeer commented on app/client/cypress/support/commands.js
> -    cy.get(welcomePage.dataCollection).should("not.exist");
Oh okay so the server still needs these values, its just not visible in the UI anymore ?

2023-05-23 10:58 UTC, dipyamanbiswas07 commented on app/client/cypress/support/commands.js
> -    cy.get(welcomePage.dataCollection).should("not.exist");
yes correct.

2023-05-23 11:34 UTC, dipyamanbiswas07 commented on app/client/src/pages/setup/DetailsForm.tsx
> +          style={isFirstPage() ? { backgroundColor: `${Colors.GRAY_300}` } : {}}
Done

2023-05-23 11:34 UTC, dipyamanbiswas07 commented on app/client/src/pages/setup/DetailsForm.tsx
> +        {!isFirstPage() && (
used useMemo

2023-05-24 04:52 UTC, dipyamanbiswas07 commented on app/client/src/pages/setup/DetailsForm.tsx
> +              <Checkbox defaultSelected name="signupForNewsletter" value="true">
Done

2023-05-24 04:52 UTC, dipyamanbiswas07 commented on app/client/src/pages/Editor/FirstTimeUserOnboarding/Tasks.tsx
> +      !isAirgapped() &&
already done

2023-05-24 05:24 UTC, dipyamanbiswas07 commented
/ok-to-test sha=1c21057

2023-05-24 06:17 UTC, ankitakinger submitted a review, later dismissed
LGTM

2023-05-24 12:40 UTC, dipyamanbiswas07 commented
/ok-to-test sha=423a7fd

2023-05-25 11:42 UTC, Harshask93 commented
Tested the feature on CE instance and also verified the observations reported and feedbacks incorporated.
The feature is working as expected.

Observations are mentioned in the comments section of PR - #23275 
Feedbacks incorporated: https://www.notion.so/Billing-and-Usage-8c5330a0ef4948cc92936931856a27bd

2023-05-25 12:54 UTC, ankitakinger commented on app/client/src/pages/setup/DetailsForm.tsx
> +      ? `var(--ads-color-black-300);`
should we use `--ads-v2-color-bg-muted` and `--ads-v2-color-bg-brand` instead?

2023-05-25 13:30 UTC, dipyamanbiswas07 commented on app/client/src/pages/setup/DetailsForm.tsx
> +      ? `var(--ads-color-black-300);`
Done

2023-05-25 16:58 UTC, dipyamanbiswas07 commented
/ok-to-test sha=3264713

2023-05-25 18:21 UTC, merged