fix: curl import curly bracket fix
appsmithorg/appsmith pull request #23680
Opened 2023-05-24 06:54 UTC by PiyushPushkar02

## Description

- Changed the method used to fetch the query params from the URL String.
- Previously the URI object was created to extract the query params which doesn't allows curly brackets in the URL.
- Added a method to split the URL string to fetch the query params

#### PR fixes following issue(s)
Fixes #19846 

#### Type of change
> Please delete options that are not relevant.
- Bug fix (non-breaking change which fixes an issue)

#### How Has This Been Tested?
- [x] Manual
- [x] JUnit
- [ ] Cypress

## Checklist:
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-05-24 07:26 UTC, sumitsum commented
Hi @PiyushPushkar02 , is the description correct ? You have mentioned that the issue is to fix the reading of query params but the query params are the ones that appear after the `?` character, and the string with the curly braces appears before, which means it is part of the URL path and not a query param e.g. here `https://api.baserow.io/api/database/rows/table/130952/{row_id}/?user_field_names=true]` the row_id part is not query param, it is part of the URL path.

2023-05-24 07:35 UTC, PiyushPushkar02 commented
Hi @sumitsum apologies for the confusion. Have updated the description for better understanding.

2023-05-24 07:45 UTC, sanveer-osahan requested changes
It's a recommended practice to add references to the original issue in the commit messages. It will make it easy to filter out (+ cherry pick) the commits that went in your changes if suppose an issue occurs in syncing the branches.

2023-05-24 07:45 UTC, sanveer-osahan commented on app/server/appsmith-server/src/test/java/com/appsmith/server/services/CurlImporterServiceTest.java
> +                    assertThat(actionDTO.getActionConfiguration().getQueryParameters()).isNotEmpty();
Can you add asserts that also checks for the url and params are equal to the expected ones?

2023-05-24 07:45 UTC, sanveer-osahan commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/CurlImporterServiceCEImpl.java
> +    private void trySaveURL(ActionDTO action, String token) throws MalformedURLException, URISyntaxException,IndexOutOfBoundsException {
Add a space here after `,` for better code formatting.

2023-05-24 08:15 UTC, sanveer-osahan approved these changes

2023-05-24 08:49 UTC, PiyushPushkar02 commented
/ok-to-test sha=49f4446

2023-05-26 05:03 UTC, prapullc commented
/build-deploy-preview skip-tests=true

2023-07-18 07:19 UTC, sumitsum commented
/build-deploy-preview

2023-07-25 13:42 UTC, closed without merging