fix: Fixed event gets triggered even when option is not changed
appsmithorg/appsmith pull request #23747
Opened 2023-05-26 05:25 UTC by harshitpandey0426

## Description
> Compared the previous and changed value, if its same we dont need to trigger onOptionChange event.

#### PR fixes following issue(s)
Fixes # 23109

#### Media
> https://www.loom.com/share/008d87273b50441f9f56d8f5eef1ed73

#### Type of change
Bug fix (non-breaking change which fixes an issue)

## Testing
>
#### How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Also list any relevant details for your test configuration.
> Delete anything that is not relevant
- [ ] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-05-26 05:27 UTC, harshitpandey0426 commented on app/client/src/widgets/SingleSelectTreeWidget/widget/index.tsx
> +    if (this.props.selectedOptionValue !== value) {
This is the only change, other changes are done due to prettier formatting for code to compile

2023-05-26 07:26 UTC, vsvamsi1 commented on app/client/src/widgets/SingleSelectTreeWidget/widget/index.tsx
> +    if (this.props.selectedOptionValue !== value) {
Hey @Ashit should the dirty assignment be moved into the value change block in line 585....just like how the select Widget behaves [Select Widget code block](https://github.com/appsmithorg/appsmith/blob/release/app/client/src/widgets/SelectWidget/widget/index.tsx#L673) 
@harshitpandey0426 Can you kindly remove this duplicate code block over here ....I just noticed it when reviewing the code of the SelectWidget https://github.com/appsmithorg/appsmith/blob/release/app/client/src/widgets/SelectWidget/widget/index.tsx#LL686C4-L688C8

2023-05-26 07:40 UTC, harshitpandey0426 commented on app/client/src/widgets/SingleSelectTreeWidget/widget/index.tsx
> +    if (this.props.selectedOptionValue !== value) {
@vsvamsi1 removed duplicate code block

2023-05-26 11:11 UTC, somangshu commented
/ok-to-test

2023-05-26 11:11 UTC, somangshu commented
/build-deploy-preview env=release skip-tests=true

2023-05-26 11:14 UTC, somangshu commented
This can be easily covered with a cypress test case. @harshitpandey0426 would you be willing to write it?

2023-05-26 11:26 UTC, harshitpandey0426 commented
> This can be easily covered with a cypress test case. @harshitpandey0426 would you be willing to write it?
* You mean to cover this case of onOptionChange event for SingleSelectTreeWidget with cypress?
* If yes, I can try it. Is it required in this pr?

2023-05-26 11:28 UTC, somangshu commented
@harshitpandey0426 yes, the same pr works

2023-05-28 04:35 UTC, vsvamsi1 requested changes

2023-05-28 04:35 UTC, vsvamsi1 commented on app/client/src/widgets/SingleSelectTreeWidget/widget/index.tsx
> +    if (this.props.selectedOptionValue !== value) {
@harshitpandey0426 most of it looks good....can you also move the dirty state code into line 585 `if` block as mentioned in the earlier comment.

2023-05-28 05:36 UTC, harshitpandey0426 commented on app/client/src/widgets/SingleSelectTreeWidget/widget/index.tsx
> +    if (this.props.selectedOptionValue !== value) {
@vsvamsi1 moved dirty block inside if block

2023-05-28 12:34 UTC, vsvamsi1 approved these changes

2023-05-29 05:03 UTC, vsvamsi1 commented
/build-deploy-preview env=release

2023-05-29 05:30 UTC, harshitpandey0426 commented
@vsvamsi1 I see couple of checks failing, is there anything pending from my end?

2023-05-29 13:57 UTC, somangshu commented
@vsvamsi1 can you please give a sign off on this. I need to know if the failing tests are un-related and if this needs a manual QA round. Please take the required actionable on this.

2023-05-30 05:14 UTC, merged