fix: updated Box shadow UI
appsmithorg/appsmith pull request #23795
Opened 2023-05-28 06:07 UTC by harshitpandey0426

## Description
> Updated box shadow UI from property pane. Removed tooltip and other css class. And added the text Small, Medium, Large as proposed UI change

#### PR fixes following issue(s)
Fixes #23760

#### Media (Screenshots to justify change)
> 
![image](https://github.com/appsmithorg/appsmith/assets/54776298/feda5958-1445-4921-a169-4a49036c0948)

>
![image](https://github.com/appsmithorg/appsmith/assets/54776298/a5e8c85e-b714-447c-adfe-f3a9233dfb3d)

>
#### Type of change
> Please delete options that are not relevant.
- Bug fix (non-breaking change which fixes an issue)
>
>
>
## Testing
>
#### How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Also list any relevant details for your test configuration.
> Delete anything that is not relevant
- [ ] Manual
- [ ] Jest
- [ ] Cypress

## Checklist:
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-05-28 06:15 UTC, sheoranabhishek commented on app/client/src/components/propertyControls/BoxShadowOptionsControl.tsx
> +          {optionKey === "S" && "Small"}
I suggest that we keep a mapping of these size literals to their full form. We might need to reuse it along various components. We can define this mapping within ThemeConstants. What do you say ?
`{
S : "Small",
M: "Medium",
L : "Large",
}`

2023-05-30 10:02 UTC, aswathkk requested changes
@harshitpandey0426 Thank you for the contribution.

Please take a look at the review comments.
Also, I could see that you made this change only for the widget's property pane.

We also need to change the UI in App theme settings pane too.
The file we need to make the change would be ThemeShadowControl.tsx

2023-05-30 10:09 UTC, harshitpandey0426 commented on app/client/src/components/propertyControls/BoxShadowOptionsControl.tsx
> +    <React.Fragment key={index}>
@aswathkk Since we removed Tooltip here fragment was needed to group multiple elements together. Can be changed to <> .. </>. Will this work? or I should think of something else like creating an array here?

2023-05-30 10:09 UTC, harshitpandey0426 commented on app/client/src/components/propertyControls/BoxShadowOptionsControl.tsx
> +    <React.Fragment key={index}>
I will create the mapping as suggested.

2023-05-30 10:13 UTC, harshitpandey0426 commented
@aswathkk 
> We also need to change the UI in App theme settings pane too. The file we need to make the change would be ThemeShadowControl.tsx

Thanks for the input, I will make these changes

2023-05-30 11:57 UTC, aswathkk commented on app/client/src/components/propertyControls/BoxShadowOptionsControl.tsx
> +    <React.Fragment key={index}>
@harshitpandey0426 There is only one div element available there. Right?
Fragments need to be used only when there are multiple elements are there.

2023-05-30 13:26 UTC, harshitpandey0426 commented on app/client/src/components/propertyControls/BoxShadowOptionsControl.tsx
> +    <React.Fragment key={index}>
@aswathkk There are 2 div elements with ternary operator on optionKey.

2023-05-30 20:04 UTC, harshitpandey0426 commented
/ok-to-test

2023-05-31 05:18 UTC, aswathkk requested changes
@harshitpandey0426 Seems like we can remove some unwanted DOM elements here.
Can you take a look at it?

2023-05-31 05:18 UTC, aswathkk commented on app/client/src/components/propertyControls/BoxShadowOptionsControl.tsx
> +    <div key={index}>
These divs are unnecessary and the label and value could just be as follows:
```javascript
label: optionKey === "none" ? (<Icon name="close-line" size="md" />) : (sizeMappings[optionKey]),
value: boxShadowOptions[optionKey],
```

2023-05-31 05:18 UTC, aswathkk commented on app/client/src/pages/Editor/ThemePropertyPane/controls/ThemeShadowControl.tsx
> +      <div key={index}>
Same as mentioned above

2023-05-31 11:56 UTC, harshitpandey0426 commented
@aswathkk Made the suggested changes. Please have a look.

2023-05-31 12:12 UTC, aswathkk submitted a review, later dismissed
LGTM

2023-05-31 19:16 UTC, harshitpandey0426 commented
@aswathkk 
Updated Theme_Default_spec.js, Theme_Default_spec.js, Theme_MultiSelectWidget_spec.js tests
I could not get what exactly is wrong with Basic_spec.js. I get that .ads-v2-segmented-control-value class is no longer present for box shadow. Should I remove that part of the test? Any input will be helpful.

2023-06-01 13:20 UTC, harshitpandey0426 commented
@aswathkk I could not get what exactly is wrong in basic_spec.js. I have updated the css class but still it is failing for the code I commented. Any input would be appreciable.

2023-06-01 13:24 UTC, harshitpandey0426 commented on app/client/cypress/e2e/Regression/ClientSide/ThemingTests/Basic_spec.js
> -          boxshadow, //rgba(0, 0, 0, 0.1) 0px 10px 15px -3px, rgba(0, 0, 0, 0.05) 0px 4px 6px -2px
Cypress is expecting "none" here

2023-06-01 19:25 UTC, harshitpandey0426 commented on app/client/cypress/e2e/Regression/ClientSide/ThemingTests/Basic_spec.js
> -      .then((boxshadow) => {
This is because box-shadow was passed in a div element from boxShadowOptionsElement.tsx and that is removed now

2023-06-01 19:26 UTC, harshitpandey0426 commented
@aswathkk Updated the tests, please have a look.

2023-06-01 20:07 UTC, harshitpandey0426 commented on app/client/cypress/e2e/Regression/ClientSide/ThemingTests/Theme_Default_spec.js
> -    cy.shadowMouseover("S");
Because tooltip is removed

2023-06-02 06:14 UTC, aswathkk requested changes
Minor nit-pick on the Cypress tests

2023-06-02 06:14 UTC, aswathkk commented on app/client/cypress/e2e/Regression/ClientSide/ThemingTests/Basic_spec.js
> -      .then((boxshadow) => {
ok. Got it.
In that case, we don't need to do ` cy.contains(".ads-v2-segmented-control-value-0", "Large").invoke("css", "box-shadow")` and then verify the box-shadow of iconButton and button widgets.
Rather, we could just verify them immediately.

2023-06-02 06:14 UTC, aswathkk commented on app/client/cypress/e2e/Regression/ClientSide/ThemingTests/Basic_spec.js
>          cy.get(widgetsPage.iconWidgetBtn).should(
Same as above.
We can put this out of then block and remove the invoke of box-shadow on the segmented control value

2023-06-02 06:52 UTC, harshitpandey0426 commented
@aswathkk made the changes please review.

2023-06-02 07:47 UTC, aswathkk approved these changes
LGTM

2023-06-02 07:48 UTC, aswathkk commented
/ok-to-test

2023-06-02 10:19 UTC, harshitpandey0426 commented
I checked these failing cypress tests are not related to this change and they are failing in release too.
@aswathkk @rohitagarwal88 Please lmk if anything else is pending from my end.

2023-06-06 02:01 UTC, aswathkk commented
Hi @harshitpandey0426, Can you merge the latest release branch with this branch?

2023-06-06 03:50 UTC, harshitpandey0426 commented
@aswathkk done

2023-06-06 05:54 UTC, aswathkk commented
/ok-to-test

2023-06-06 09:22 UTC, aswathkk commented
/build-deploy-preview env=release

2023-06-07 05:45 UTC, harshitpandey0426 commented
@aswathkk any update on this?

2023-06-08 01:23 UTC, merged