chore: Update entrypoint to deploy appsmith on cloudrun
appsmithorg/appsmith pull request #23829
Opened 2023-05-29 09:19 UTC by pratapaprasanna

2023-05-29 18:01 UTC, pratapaprasanna commented
/build-deploy-preview skip-tests=true

2023-05-29 18:48 UTC, pratapaprasanna commented
/build-deploy-preview skip-tests=true

2023-05-31 09:55 UTC, sharat87 commented
Unmarking myself for review, as discussed, since this is still WIP.

2023-06-02 07:51 UTC, sharat87 requested changes

2023-06-02 07:51 UTC, sharat87 commented on deploy/docker/entrypoint.sh
1. Let's please keep `set -e` and the Segment call as the very first things that run in the entrypoint. Can we move this to below that please?
2. Let's also change the indentation to 2-spaces to keep it consistent with the rest of this script please.

2023-06-02 07:51 UTC, sharat87 commented on deploy/docker/entrypoint.sh
> +then
The `if` check is incorrect. I think we need `[[ -n "$FILESTORE_IP_ADDRESS" ]]` to check if it's non-empty.

```suggestion
if [[ -n "$FILESTORE_IP_ADDRESS" ]]; then
```

2023-06-02 07:51 UTC, sharat87 commented on deploy/docker/entrypoint.sh
> +        FILE_SHARE_NAME=$(echo "$FILE_SHARE_NAME" | xargs)
Quotes please. 🙂

```suggestion
        ## Trim APPSMITH_FILESTORE_IP and FILE_SHARE_NAME
        FILESTORE_IP_ADDRESS="$(echo "$FILESTORE_IP_ADDRESS" | xargs)"
        FILE_SHARE_NAME="$(echo "$FILE_SHARE_NAME" | xargs)"
```

2023-06-02 07:51 UTC, sharat87 commented on deploy/docker/entrypoint.sh
> +        echo "Installing appsmith for cloudRun"
Not really _installing_, right? We're just running, no? 🤔

```suggestion
        echo "Running Appsmith for CloudRun"
```

2023-06-02 09:48 UTC, pratapaprasanna commented on deploy/docker/entrypoint.sh
> +        echo "Installing appsmith for cloudRun"
May be deploying appsmith for cloudrun ?

2023-06-05 12:40 UTC, sharat87 requested changes
@pratapaprasanna, I see that the thread is marked as resolved, but I don't see the requested changes made. The CloudRun check is still above the Segment call, and the indentation is still not 2 spaces. Can we fix them and then mark them resolved please?

Also, noticed another thing, should we `export` the changed values to `FILESTORE_IP_ADDRESS` and `FILE_SHARE_NAME`, or is that okay?

![shot-2023-06-05-12-38-20](https://github.com/appsmithorg/appsmith/assets/120119/04d87d8a-4acb-406a-aa48-a124b6a89127)

2023-06-05 14:28 UTC, pratapaprasanna commented
> @pratapaprasanna, I see that the thread is marked as resolved, but I don't see the requested changes made. The CloudRun check is still above the Segment call, and the indentation is still not 2 spaces. Can we fix them and then mark them resolved please?
> 
> Also, noticed another thing, should we `export` the changed values to `FILESTORE_IP_ADDRESS` and `FILE_SHARE_NAME`, or is that okay?
> 
> ![shot-2023-06-05-12-38-20](https://user-images.githubusercontent.com/120119/243354959-04d87d8a-4acb-406a-aa48-a124b6a89127.png)
Sorry I missed it. Doing them

2023-06-06 08:24 UTC, sharat87 requested changes

2023-06-06 08:24 UTC, sharat87 commented on deploy/docker/entrypoint.sh
> +if [[ -n "$FILESTORE_IP_ADDRESS" ]]; then
Can we try running this container once? I think this will fail to start the container. Since we now have a `set -e` above this, if this variable isn't defined, the entrypoint script will immediately break.

```suggestion
if [[ -n "${FILESTORE_IP_ADDRESS-}" ]]; then
```

Let's also run this once, on non-CloudRun systems to ensure we aren't missing anything else here please.

2023-06-07 04:07 UTC, sharat87 approved these changes

2023-06-08 13:39 UTC, pratapaprasanna commented
/ok-to-test

2023-06-09 04:54 UTC, merged