[Feature] Grid Widget
appsmithorg/appsmith pull request #2389
Opened 2020-12-29 10:53 UTC by jsartisan

## Description
Introducing new widget for lists/grid

Fixes #1427 

## Type of change
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

## Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-04-19 07:51 UTC, riodeuno approved these changes
Approving for CI tests to run.

2021-04-20 12:45 UTC, riodeuno requested changes

2021-04-20 12:45 UTC, riodeuno commented on app/client/src/pages/Editor/PropertyPane/PropertyControl.tsx
> +  const childWidgetPropertyUpdateEnhancementFn = useChildWidgetEnhancementFn(
Let's refactor this so that the tree traversals are not redundant.

2021-04-20 12:45 UTC, riodeuno commented on app/client/src/pages/Editor/PropertyPane/PropertyControl.tsx
> +        // TODO: Concat if exists, else replace
Let's remove this TODO

2021-04-20 12:45 UTC, riodeuno commented on app/client/src/pages/Editor/PropertyPane/PropertyControl.tsx
> +    const getCustomJSControl = () => {
Let's remove this if it isn't being used.

2021-04-20 12:45 UTC, riodeuno commented on app/client/src/pages/Editor/PropertyPane/PropertyPaneGenerator.tsx
> +export const generatePropertyControl = (
There have been modifications to the original file, please verify that all the changes are also reflected here.

2021-04-20 12:45 UTC, riodeuno commented on app/client/src/pages/Editor/PropertyPane/index.tsx
> +      return <></>;
Let's make this `null` instead of fragment.

2021-04-20 12:45 UTC, riodeuno commented on app/client/src/sagas/WidgetOperationUtils.ts
> +  console.log({ widget, widgets, widgetNameMap, newWidgetList });
Let's remove the console log

2021-04-20 12:45 UTC, riodeuno commented on app/client/src/selectors/propertyPaneSelectors.tsx
> +export const getCanvasWidgets = (state: AppState): CanvasWidgetsReduxState =>
Let's verify the usage of this selector.

2021-04-20 12:45 UTC, riodeuno commented on app/client/src/widgets/BaseWidget.tsx
> +        (this.props.noContainerOffset ? 0 : CONTAINER_GRID_PADDING),
Let's verify if noContainerOffset is needed.

2021-04-20 12:45 UTC, riodeuno commented on app/client/src/widgets/BaseWidget.tsx
> +    const { paddingEnabled } = this.props;
Let's verify if this is needed.

2021-04-20 12:45 UTC, riodeuno commented on app/client/src/widgets/BaseWidget.tsx
> +    virtualizedEnabled: false,
Let's verify if all of these are need, also if they need to be renamed.

2021-04-20 12:45 UTC, riodeuno commented on app/client/src/widgets/CanvasWidget.tsx
> +    if (this.props.virtualizedEnabled) {
Let's remove this condition.

2021-04-20 12:45 UTC, riodeuno commented on app/client/src/widgets/ContainerWidget.tsx
> +  stickyIndices: number[];
Let's see if this is needed.

2021-04-20 12:45 UTC, riodeuno commented on app/client/src/widgets/ContainerWidget.tsx
> +    const isVirtualized = this.props.virtualizedEnabled;
Let's remove the `virtualizedEnabled` code.

2021-04-20 12:45 UTC, riodeuno commented on app/client/src/widgets/ListWidget/ListComponent.tsx
> +          props.shouldScrollContents ? `${getCanvasClassName()}` : ""
Let's memoize this.
Also there is no need for ...remainingProps.

2021-04-20 12:45 UTC, riodeuno commented on app/client/src/widgets/ListWidget/ListWidget.tsx
> +    return {
this may not be required. Please verify.

2021-04-20 12:45 UTC, riodeuno commented on app/client/src/widgets/ListWidget/ListWidget.tsx
> +          this.onItemClick(index, this.props.onListItemClick, () => {
Please check if the last callback argument is needed.

2021-04-20 12:45 UTC, riodeuno commented on app/client/src/widgets/ListWidget/ListWidget.tsx
> +      return <>Nothing to display</>;
Let's style this.

2021-04-21 12:44 UTC, riodeuno approved these changes

2021-04-22 06:30 UTC, riodeuno submitted a review, later dismissed

2021-04-22 07:05 UTC, riodeuno submitted a review, later dismissed

2021-04-22 07:17 UTC, riodeuno approved these changes

2021-04-23 05:43 UTC, merged

2022-03-01 06:42 UTC, Rishabh-Rathod commented on app/client/src/widgets/ListWidget/ListWidget.tsx
> +                  )}'))}}`
JSON.stringify logic was added here.