feat: code splitting for git
appsmithorg/appsmith pull request #23894
Opened 2023-05-31 05:22 UTC by brayn003

## Description
Splitting DSL into different files when saving into git

#### PR fixes following issue(s)
Fixes #

#### Media

#### Type of change
- New feature (non-breaking change which adds functionality)

## Testing
Manual Testing

#### How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Also list any relevant details for your test configuration.
> Delete anything that is not relevant
- [ ] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-06-01 02:48 UTC, tanvibhakta commented
No ads review necessary

2023-06-14 08:05 UTC, KelvinOm commented on app/client/packages/dsl/.eslintrc.json
> +{
(nitpick) It may be worth adding tests as well.

2023-06-14 08:08 UTC, KelvinOm commented on app/client/packages/dsl/package.json
> +        "build": "rollup -c"
You need to add this script so that the lint checks for this package is run in CI

`"lint": "yarn g:lint"`

2023-06-14 09:10 UTC, brayn003 commented
/ok-to-test

2023-06-14 17:30 UTC, brayn003 commented
/ok-to-test

2023-06-15 05:19 UTC, brayn003 commented
/ok-to-test

2023-06-19 09:27 UTC, brayn003 commented
/ok-to-test

2023-06-20 09:48 UTC, brayn003 commented
/ok-to-test sha=c1ee28b

2023-06-20 16:21 UTC, brayn003 commented
/ok-to-test sha=a9715d9

2023-06-20 18:54 UTC, Aishwarya-U-R commented
@brayn003 - Since all tests are [pass in attempt1](https://cloud.cypress.io/projects/eyxvp8/runs/36487/overview), cancelling the re-run.

2023-06-21 06:25 UTC, Parthvi12 commented
/build-deploy-preview

2023-06-21 07:45 UTC, Parthvi12 commented
@brayn003 Latest deploy preview option is missing on DP in git sync modal, attaching screenshot, can you please check:
<img width="1440" alt="Screenshot 2023-06-21 at 1 12 08 PM" src="https://github.com/appsmithorg/appsmith/assets/80334441/4c605aed-8b5a-456e-bc2b-49a5ffe73351">

2023-06-21 08:47 UTC, Aishwarya-U-R commented
> @brayn003 Latest deploy preview option is missing on DP in git sync modal, attaching screenshot, can you please check: <img alt="Screenshot 2023-06-21 at 1 12 08 PM" width="1440" src="https://user-images.githubusercontent.com/80334441/247471459-4c605aed-8b5a-456e-bc2b-49a5ffe73351.png">

@Parthvi12 - We dont have Cypress to catch these issues?

2023-06-21 08:50 UTC, Parthvi12 commented
> > @brayn003 Latest deploy preview option is missing on DP in git sync modal, attaching screenshot, can you please check: <img alt="Screenshot 2023-06-21 at 1 12 08 PM" width="1440" src="https://user-images.githubusercontent.com/80334441/247471459-4c605aed-8b5a-456e-bc2b-49a5ffe73351.png">
> 
> @Parthvi12 - We dont have Cypress to catch these issues?

We do, It's there in lots of test cases, I am trying to understand how did cypress miss it.

2023-06-21 09:04 UTC, Aishwarya-U-R commented
> @Aishwarya-U-R We do, It's there in lots of test cases, I am trying to understand how did cypress miss it.

Yes please!

2023-06-21 09:23 UTC, hetunandu requested changes

2023-06-21 09:23 UTC, hetunandu commented on app/client/packages/dsl/src/index.test.ts
> +  };
Adding some builder functions like this is not a good idea. What is testing this code? It can be edited to make tests pass.

2023-06-21 09:23 UTC, hetunandu commented on app/client/packages/dsl/src/index.test.ts
> +const SAMPLE_DSL = {
You do not need actual DSLs. User simpler versions with just the keys you need like `name` and `children` and maybe one or two more to ensure any other keys are also converted and placed correctly.

2023-06-21 09:23 UTC, hetunandu commented on app/client/packages/dsl/src/index.test.ts
> +describe("Test #4 - normalize operations on REAL DSL structures", () => {
Not needed.

2023-06-21 09:23 UTC, hetunandu commented on app/client/packages/dsl/src/index.test.ts
> +    widgetId: "0",
Add some more dummy keys to this simple DSL and test if they are correctly handled

2023-06-21 09:23 UTC, hetunandu commented on app/client/packages/dsl/src/index.test.ts
> +  it("Check `unnestDSL` for 10 level deep nesting", () => {
I do not feel such kinds of tests are needed.

2023-06-21 09:23 UTC, hetunandu commented on app/client/src/sagas/PageSagas.tsx
> +// import type { DSLWidget } from "widgets/constants";
Remove comment

2023-06-21 09:23 UTC, hetunandu commented on app/client/packages/dsl/src/DSL.ts
> +export function unnestDSL<W>(nestedDSL: NestedDSL<W>): UnnestedDSL<W> {
rename to `flattenDSL` instead. unnest is hard to understand without context

2023-06-22 11:00 UTC, Parthvi12 commented
> @brayn003 Latest deploy preview option is missing on DP in git sync modal, attaching screenshot, can you please check: <img alt="Screenshot 2023-06-21 at 1 12 08 PM" width="1440" src="https://user-images.githubusercontent.com/80334441/247471459-4c605aed-8b5a-456e-bc2b-49a5ffe73351.png">

Since we were not able to reproduce this issue on any other app on DP, giving a go ahead.

2023-06-23 11:19 UTC, hetunandu approved these changes

2023-06-26 06:55 UTC, merged