fix: added gitsyncid assignment to DataSource constructor with dataSourceS…
appsmithorg/appsmith pull request #23912
Opened 2023-05-31 08:51 UTC by tkAppsmith

## Description
> Added gitsyncid assignment to DataSource constructor with dataSourceStorage as argument

#### PR fixes following issue(s)
Fixes #23816 (partially)

#### Type of change
- Bug fix (non-breaking change which fixes an issue)

## Testing
>
#### How Has This Been Tested?
- [x] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Test Plan
> To test this, please import an application to a workspace from git and commit the changes that come up in git sync tool. > Check that the datasources dont have their gitsyncid updated as it was happening in the issue https://github.com/appsmithorg/appsmith/issues/23816

## Checklist:
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-05-31 09:54 UTC, tkAppsmith commented
/ok-to-test

2023-05-31 11:21 UTC, tkAppsmith commented
/build-deploy-preview

2023-06-01 05:23 UTC, Parthvi12 commented
The issue is fixed, and verified on DP

2023-06-01 11:15 UTC, tkAppsmith commented
/ok-to-test

2023-06-01 11:15 UTC, tkAppsmith commented
/build-deploy-preview

2023-06-01 14:39 UTC, sondermanish requested changes

2023-06-01 14:39 UTC, sondermanish commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/Datasource.java
> +    public void sanitiseToExportDBObject() {
Please remove this snippet of code

2023-06-01 14:39 UTC, sondermanish commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/ActionDTO.java
> +            this.getDatasource().setDatasourceStorages(null);
could you confirm that this removal of datasourceStorages doesn't cause a ci failure for ImportExport?

2023-06-02 07:07 UTC, Parthvi12 commented
https://github.com/appsmithorg/appsmith/issues/23822 is also verified on DP and is working fine.

2023-06-02 08:23 UTC, sondermanish commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/Datasource.java
> +        this.gitSyncId = datasourceStorage.getGitSyncId();
let's leave a big comment in another small Pr in essence of time, for why we did take this approach. 
earlier this deep copy was made by`copyNestedNonNullNestedProperties`

2023-06-02 08:23 UTC, sondermanish approved these changes
LGTM

2023-06-02 10:24 UTC, sondermanish commented
/ok-to-test

2023-06-02 12:18 UTC, merged