feat: updating datasource endpoints contract
appsmithorg/appsmith pull request #23920
Opened 2023-05-31 11:27 UTC by sondermanish

## Description

With introduction of new collection called datasourceStorage the api contracts need to change.
This Pr addresses the same.

2023-06-01 10:29 UTC, ChandanBalajiBP commented
/ok-to-test

2023-06-02 08:34 UTC, ChandanBalajiBP commented
/ok-to-test

2023-06-05 13:45 UTC, sondermanish commented
/ok-to-test

2023-06-07 06:26 UTC, ChandanBalajiBP commented
/ok-to-test

2023-06-07 10:35 UTC, sondermanish commented
/ok-to-test

2023-06-07 11:08 UTC, sondermanish commented
/ok-to-test

2023-06-08 04:46 UTC, sondermanish commented
/build-deploy-preview skip-tests=true

2023-06-08 06:34 UTC, ChandanBalajiBP commented
/build-deploy-preview skip-tests=true

2023-06-08 07:27 UTC, nidhi-nair commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/OAuth2ResponseDTO.java
> +    Datasource datasource;
Why is this not storage instead?

2023-06-08 07:28 UTC, nidhi-nair commented on app/server/appsmith-plugins/amazons3Plugin/src/main/resources/form.json
> +          "configProperty": "datasourceStorages.active_env.datasourceConfiguration.properties[1].key",
Can you please explain this change?

2023-06-08 07:29 UTC, sondermanish commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/OAuth2ResponseDTO.java
> +    Datasource datasource;
This requires permission from datasources, which the client side uses to enable certain GAC flows.

2023-06-08 07:30 UTC, sondermanish commented on app/server/appsmith-plugins/amazons3Plugin/src/main/resources/form.json
> +          "configProperty": "datasourceStorages.active_env.datasourceConfiguration.properties[1].key",
@ayushpahwa has more context on this

2023-06-08 07:33 UTC, sondermanish commented
/ok-to-test

2023-06-08 07:34 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceServiceCEImpl.java
> +        if (!hasText(datasource.getGitSyncId())) {
QQ what's the difference between hasLength and hasText?

2023-06-08 07:35 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceServiceCEImpl.java
> +        datasource.nullifyStorageReplicaFields();
Do we expect to be getting values here or is this just an additional check?

2023-06-08 07:36 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceServiceCEImpl.java
> -                        datasource1.setHasDatasourceStorage(true);
QQ, why are we getting rid of this flag?

2023-06-08 07:38 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceServiceCEImpl.java
> +                                                    Boolean IsUserRefreshedUpdate) {
Nit: variable name does not conform to standards

2023-06-08 07:41 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceServiceCEImpl.java
> +                            return datasourceStorageService.updateByDatasourceAndEnvironmentId(datasource, environmentId, Boolean.TRUE)
We were using this method because of the need for transfer service. Now that the transfer is done, let's default to updating by datasourceStorage itself?

2023-06-08 07:45 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceServiceCEImpl.java
> +                .publishOn(Schedulers.boundedElastic())
Why are we publishing on a different scheduler here?

2023-06-08 07:54 UTC, sondermanish commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceServiceCEImpl.java
> -                        datasource1.setHasDatasourceStorage(true);
Since hasDatasourceStorage was only used for migration, should we not remove this?

2023-06-08 07:55 UTC, sondermanish commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceServiceCEImpl.java
> +        datasource.nullifyStorageReplicaFields();
We don't expect, but server side check is placed separately

2023-06-08 07:56 UTC, sondermanish commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceServiceCEImpl.java
> +        if (!hasText(datasource.getGitSyncId())) {
`hasLength` will give you positive for whitespace characters e.g `"     "`, `hasText` would not

2023-06-08 08:12 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceServiceCEImpl.java
> -                        datasource1.setHasDatasourceStorage(true);
I think we should maintain this at least till we stabilize ME so that we have a way to easily identify datasources that may or may not be in corrupted state. For example, the failures we are seeing right now in last migration.

2023-06-08 08:13 UTC, sondermanish commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceServiceCEImpl.java
> -                        datasource1.setHasDatasourceStorage(true);
reverting this

2023-06-08 08:14 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceServiceCEImpl.java
> +                    //not required by client side in order to avoid updating it to a null storage,
Sorry, I do not understand this change?

2023-06-08 08:15 UTC, sondermanish commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceServiceCEImpl.java
> +                .publishOn(Schedulers.boundedElastic())
Since we are able to use different threads to run subsequent db calls , this gives performance boost.

2023-06-08 08:17 UTC, nidhi-nair commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/OAuth2ResponseDTO.java
> +    Datasource datasource;
Sorry, could you please provide a few more specifics here? I am trying to understand why sending information as a map of datasourcestorages is warranted here.

2023-06-08 09:38 UTC, sondermanish commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceServiceCEImpl.java
> +                    //not required by client side in order to avoid updating it to a null storage,
Since we are only changing metadata of datasource i.e. name, we will be sending the datasource object without the datasourceStorages object, the client side does something similar to server side's `copyNestedNonNullProperties` . Hence we are setting it to null here.

2023-06-08 09:42 UTC, sondermanish commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/OAuth2ResponseDTO.java
> +    Datasource datasource;
The fix [issue](https://github.com/appsmithorg/appsmith/issues/23840) will give more context on the same

2023-06-08 09:53 UTC, ChandanBalajiBP commented on app/server/appsmith-plugins/amazons3Plugin/src/main/resources/form.json
> +          "configProperty": "datasourceStorages.active_env.datasourceConfiguration.properties[1].key",
Assuming a case where a user is editing the production environment and switches to the staging environment, how can we have forms for both environments?

For example, let's say the production environment's ID is "prod_env" and the staging environment's ID is also "prod_env". So we need two forms with the config property `datasourceStorages.prod_env.datasourceConfiguration.properties[1].key` and `datasourceStorages.prod_env.datasourceConfiguration.properties[1].key`.

This can be achieved in multiple ways:

1. Server maintains forms for each environment - worst possible solution
2. Server sends forms for all environments and the client selects the form based on the user selection - Here we are storing the same form twice just because of a change in the config property.
3. We consider `active_env` as the current editing environment and move the required `datasourceStorage` to `active_env` based on selection.

Advantages of the `active_env` method:

- This will also enable us to revert functionality in the future if required.
- The server maintains a single form for any number of environments.
- Much easier implementation.

2023-06-08 10:43 UTC, ChandanBalajiBP commented
/ok-to-test

2023-06-08 12:58 UTC, ChandanBalajiBP commented
/ok-to-test

2023-06-08 13:43 UTC, sondermanish commented
/ok-to-test

2023-06-08 21:41 UTC, ChandanBalajiBP commented
/ok-to-test

2023-06-08 21:52 UTC, ChandanBalajiBP commented
/ok-to-test

2023-06-08 22:04 UTC, ChandanBalajiBP commented
/ok-to-test

2023-06-09 07:26 UTC, ChandanBalajiBP commented
/ok-to-test

2023-06-09 08:11 UTC, nidhi-nair commented on app/server/appsmith-plugins/amazons3Plugin/src/main/resources/form.json
> +          "configProperty": "datasourceStorages.active_env.datasourceConfiguration.properties[1].key",
Doesn't this also mean that a form.json configuration is actually operating at a datasourceStorage level now? Is it possible to consider using that as the reference object for these property paths instead?

2023-06-09 08:47 UTC, ChandanBalajiBP commented
/build-deploy-preview skip-tests=true

2023-06-09 12:57 UTC, sondermanish commented
/ok-to-test

2023-06-11 08:50 UTC, sondermanish commented
/build-deploy-preview skip-tests=true

2023-06-11 21:38 UTC, ChandanBalajiBP commented
/ok-to-test

2023-06-12 03:06 UTC, nidhi-nair commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/OAuth2ResponseDTO.java
> +    Datasource datasource;
Okay, but it looks like we're conflating two concepts here. Returning a Datasource object at this point means that we're also operating at multiple environment level, which is not true. Should we not be dealing with a single `DatasourceStorage` here? This goes back to the same question of how client is dealing with datasource storage level permissions.

2023-06-12 04:19 UTC, ayushpahwa requested changes

2023-06-12 04:19 UTC, ayushpahwa commented on app/client/src/sagas/DatasourcesSagas.ts
> +    //Chandan
Fix comment please

2023-06-12 04:19 UTC, ayushpahwa commented on app/client/src/sagas/DatasourcesSagas.ts
> -  set(datasource, "datasourceConfiguration.headers", filteredDatasourceHeaders);
Why are we removing this?

2023-06-12 05:01 UTC, sondermanish commented on app/client/src/api/DatasourcesApi.ts
> +  static testDatasource(
The environmentId is being sent inside the object itself, we can send the envId here as well, but As far as I remember, this envirionment Id header is for the active environment (what we select from dropdown). Also, we can test staging config while being on production environment, hence we are sending configuration along with required envId as field.
does this answer your question?

2023-06-12 17:47 UTC, ChandanBalajiBP commented
/ok-to-test

2023-06-12 22:04 UTC, ChandanBalajiBP commented
/build-deploy-preview skip-tests=true

2023-06-12 22:15 UTC, ChandanBalajiBP commented
/ok-to-test

2023-06-12 22:21 UTC, ChandanBalajiBP commented
/ok-to-test

2023-06-12 22:26 UTC, ChandanBalajiBP commented
/ok-to-test

2023-06-12 22:39 UTC, ChandanBalajiBP commented on app/client/src/components/editorComponents/Debugger/index.tsx
> -  const totalMessageCount = messageCounters.errors + messageCounters.warnings;
It was leading to unnecessary rendering, hence updated

2023-06-12 22:40 UTC, ChandanBalajiBP commented on app/client/src/components/editorComponents/Debugger/index.tsx
> -  dispatch(setErrorCount(totalMessageCount));
Yes, came across and felt this is a small fix hence covered it here.

2023-06-12 22:41 UTC, ChandanBalajiBP commented on app/client/src/components/editorComponents/GlobalSearch/GlobalSearchHooks.test.ts
> +        unused_env: {
This is a CE test case, do we need to update still?

2023-06-12 22:42 UTC, ChandanBalajiBP commented on app/client/src/components/editorComponents/form/fields/EmbeddedDatasourcePathField.tsx
> +  datasource: DatasourceStorage | EmbeddedRestDatasource;
@sondermanish can you pitch in here

2023-06-12 23:15 UTC, ChandanBalajiBP commented on app/client/src/sagas/DatasourcesSagas.ts
> -  set(datasource, "datasourceConfiguration.headers", filteredDatasourceHeaders);
Have moved the logic down to line 1052

2023-06-12 23:40 UTC, ChandanBalajiBP commented
/ok-to-test

2023-06-12 23:40 UTC, ChandanBalajiBP commented
/build-deploy-preview skip-tests=true

2023-06-13 03:48 UTC, ChandanBalajiBP commented
/ok-to-test

2023-06-13 03:49 UTC, ChandanBalajiBP commented
/build-deploy-preview skip-tests=true

2023-06-13 06:59 UTC, sondermanish commented
//build-deploy-preview skip-tests=true

2023-06-13 06:59 UTC, sondermanish commented
/build-deploy-preview skip-tests=true

2023-06-13 07:16 UTC, sondermanish commented
/ok-to-test

2023-06-13 09:39 UTC, sondermanish commented on app/client/src/components/editorComponents/form/fields/EmbeddedDatasourcePathField.tsx
> +  datasource: DatasourceStorage | EmbeddedRestDatasource;
@ayushpahwa we have kept it to the older format because of two major reasonsl

- if we were to change that, we would have to write migrations for this. on prod this is around 1.3M documents
- It would also change the git files, which would be seen as a diff by end users, need to align with git team first, hence we have delayed on these for later on

2023-06-13 12:33 UTC, ChandanBalajiBP commented
/build-deploy-preview skip-tests=true

2023-06-14 03:22 UTC, ayushpahwa submitted a review, later dismissed

2023-06-14 03:22 UTC, ayushpahwa commented on app/client/src/api/DatasourcesApi.ts
> +  static testDatasource(
Nope, didn't get you. The header is the active env for the whole app while the test can be done for the env being currently edited in the datasource. Which object has the currently edited environment's id? @ChandanBalajiBP @sondermanish

2023-06-14 03:22 UTC, ayushpahwa commented on app/client/src/ce/utils/Environments/index.tsx
> +  return "unused_env";
Can you please use a variable here? The one defined in APIUtils

2023-06-14 03:22 UTC, ayushpahwa commented on app/client/src/components/editorComponents/Debugger/index.tsx
> +  });
The dependency should be on `messageCounters.errors` right?

2023-06-14 06:30 UTC, sondermanish commented
/ok-to-test

2023-06-14 08:41 UTC, sondermanish commented
/build-deploy-preview skip-tests=true

2023-06-15 12:36 UTC, nidhi-nair commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/DatasourceStorageDTO.java
>      public DatasourceStorageDTO(DatasourceStorage datasourceStorage) {
Hey we should be getting rid of all constructor kind of initialization, let's create a separate task for this and take it up in a different PR

2023-06-21 06:08 UTC, sondermanish commented
/ok-to-test

2023-06-21 07:12 UTC, ayushpahwa reviewed
removing since I made changes

2023-06-21 07:14 UTC, ayushpahwa commented
/build-deploy-preview skip-tests=true recreate=true

2023-06-21 07:29 UTC, ayushpahwa commented
/build-deploy-preview skip-tests=true recreate=true

2023-06-21 11:16 UTC, ayushpahwa commented on app/client/src/pages/Editor/DataSourceEditor/index.tsx
> +        id: DEFAULT_ENV_ID,
These filter params are for filtering the datasource based on the basis of the current env being edited. Hence by default, we are adding default env id. The main usage comes in EE

2023-06-21 11:17 UTC, ayushpahwa commented on app/client/src/pages/Editor/SaaSEditor/DatasourceForm.tsx
> +                  {!isNil(sections)
What's the difference here? We haven't introduced this, just removed the underscore import.

2023-06-21 11:17 UTC, ayushpahwa commented on app/client/src/pages/Editor/SaaSEditor/DatasourceForm.tsx
> +                  {!isNil(sections)
Also, the section can be undefined/null here also. Empty is not a case we know of.

2023-06-21 11:18 UTC, ayushpahwa commented on app/client/src/pages/Editor/gitSync/ReconnectDatasourceModal.tsx
> +        ds.datasourceStorages ? !isEnvironmentConfigured(ds) : true,
dsSotrages can't be empty in any case.

2023-06-21 11:18 UTC, ayushpahwa commented on app/client/src/reducers/entityReducers/datasourceReducer.ts
> +      recentDatasources: [
I am guessing this is used in replay flow. I don't think we introduced this.

2023-06-21 13:02 UTC, ayushpahwa commented
/build-deploy-preview skip-tests=true recreate=true

2023-06-21 13:02 UTC, ayushpahwa commented
/ok-to-test

2023-06-21 15:28 UTC, ayushpahwa commented
/build-deploy-preview skip-tests=true recreate=true

2023-06-21 16:55 UTC, ayushpahwa commented
/ok-to-test

2023-06-22 09:56 UTC, Irongade commented on app/client/src/pages/Editor/SaaSEditor/DatasourceForm.tsx
> +                  {!isNil(sections)
IsEmpty checks for null values or undefined as well. It is possible for the section to be an empty array or object. I've ran into this bug before as a Sentry issue.

2023-06-22 09:57 UTC, Irongade commented on app/client/src/pages/Editor/DataSourceEditor/index.tsx
> +        id: DEFAULT_ENV_ID,
Can we rename the id to envId then to make it clearer.

2023-06-22 11:11 UTC, ayushpahwa commented
/build-deploy-preview skip-tests=true recreate=true

2023-06-22 11:13 UTC, ayushpahwa commented
/build-deploy-preview skip-tests=true recreate=true

2023-06-22 12:54 UTC, btsgh commented
As part of this second round, based on Ayush's suggestions in this thread, these are the test cases covered by QA:

- Creation and updation of ds one of all types - Done [Also covered Firestore, Snowflake, Redis, Mongo, SMTP, Oracle, Redshift]
- DB- Postgres/mongo - Done [Also covered Firestore, Snowflake, Redis, Mongo, SMTP, Oracle, Redshift]
- Gsheets - Done- identified issues - resolved.
- OAuth2.0 - Done - identified issues - resolved.
- Saas- airtable - Done [Also covered - hubspot, Twillio]
- Rest/graphql - Done [Also covered - cURL API, Auth rest API, Auth GraphQL] - identified issues - resolved.
- Creation, updation and execution of a query made from these datasources - Done
- Creation, updation and execution of an API without a datasource ( please try to navigating away and coming back to the query. Also check with  refresh after updating the query) - Done
- Git operations / git import - export - Done
- Import - Done - identified issues. - resolved.
- Fork from inside app [Make application forkable] - is working. Done

Also to reiterate - Fork issues still exist on release, fix has not been merged. So we have not tested fork on this DP. This PR looks good to go.

2023-06-27 05:33 UTC, ayushpahwa commented
/build-deploy-preview skip-tests=true

2023-06-27 05:33 UTC, ayushpahwa commented
/ok-to-test

2023-06-28 14:01 UTC, sondermanish commented
/ok-to-test

2023-06-29 07:49 UTC, sondermanish commented
/ok-to-test

2023-06-30 05:21 UTC, ayushpahwa commented
/build-deploy-preview skip-tests=true

2023-06-30 05:21 UTC, ayushpahwa commented
/ok-to-test

2023-07-03 10:50 UTC, ayushpahwa commented
/ok-to-test

2023-07-03 12:06 UTC, ayushpahwa approved these changes
Re approving for CI merging

2023-07-03 13:06 UTC, merged