Copy Text trigger function
appsmithorg/appsmith pull request #2394
Opened 2020-12-29 17:39 UTC by hetunandu

## Description
Adds a new trigger function that can copy any *text*

```
{ { copy(Table1.selectedRow.id) }}
```

uses the [copy-to-clipboard](https://github.com/sudodoki/copy-to-clipboard#readme) library

resolves #2379 

## Type of change

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

## How Has This Been Tested?

> TODO

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2020-12-30 05:43 UTC, Nikhil-Nandagopal commented on app/client/src/workers/evaluation.worker.ts
> -      .millisecond(0);
@hetunandu please update the docs

2020-12-30 05:44 UTC, Nikhil-Nandagopal requested changes
Mostly looks good. Please update docs

2020-12-30 07:08 UTC, mohanarpit commented on app/client/src/components/editorComponents/actioncreator/ActionCreator.tsx
> +  copy: "copy",
```suggestion
  copyToClipboard: "copyToClipboard",
```

2020-12-30 07:08 UTC, mohanarpit commented on app/client/src/components/editorComponents/actioncreator/ActionCreator.tsx
> +    label: "Copy",
```suggestion
    label: "Copy to clipboard",
```

2020-12-30 07:10 UTC, mohanarpit commented on app/client/src/components/editorComponents/actioncreator/ActionCreator.tsx
> +        fieldLabel = "Text to copy";
```suggestion
        fieldLabel = "Text that will be copied to clipboard";
```

2020-12-30 07:12 UTC, hetunandu commented on app/client/src/components/editorComponents/actioncreator/ActionCreator.tsx
> +  copy: "copy",
Do you want to rename the function to this?

2020-12-30 07:17 UTC, mohanarpit commented on app/client/src/components/editorComponents/actioncreator/ActionCreator.tsx
> +  copy: "copy",
Yes. We should be explicit that this function will copy the text to the clipboard. Else, from a cursory glance, it's confusing as to where is the text being copied.

2020-12-31 01:46 UTC, Sayanta66 approved these changes

2020-12-31 05:16 UTC, hetunandu commented on app/client/src/components/editorComponents/actioncreator/ActionCreator.tsx
> +  copy: "copy",
I think the confusion would still remain with copyToClipboard (all copy is to clipboard). How about we name it `copyText` so we dont confuse it with copy widget

2020-12-31 07:08 UTC, mohanarpit commented on app/client/src/components/editorComponents/actioncreator/ActionCreator.tsx
> +  copy: "copy",
It's unlikely that folks will confuse this with `copyWidget`. This is because it's a JS function and not a product level trigger. For example, the underlying library that you used is also called `copy-to-clipboard`. Hence we should be clear about this. 

We can add clarifications to the function docs and also to the label in the action menu. If you still feel that the function name should have more details, what about : `copyTextToClipboard` ? I know it's a little long but it gets the job done.

2021-01-06 12:43 UTC, hetunandu commented
Not able to write a test because cypress cannot paste or give access to to clipboard

2021-01-06 12:52 UTC, hetunandu commented
Docs PR: appsmithorg/appsmith-docs#75

2021-01-06 13:14 UTC, mohanarpit approved these changes

2021-01-07 04:44 UTC, merged