design callouts one click binding
appsmithorg/appsmith pull request #23997
Opened 2023-06-02 11:38 UTC by vsvamsi1

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.
>
## Description
> Add a TL;DR when description is extra long (helps content team)
>
> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change
>
> Links to Notion, Figma or any other documents that might be relevant to the PR
>
>
#### PR fixes following issue(s)
Fixes # (issue number)
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
#### Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video
>
>
#### Type of change
> Please delete options that are not relevant.
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
## Testing
>
#### How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Also list any relevant details for your test configuration.
> Delete anything that is not relevant
- [ ] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-06-02 11:38 UTC, vsvamsi1 commented
/build-deploy-preview env=release

2023-06-03 07:04 UTC, Aishwarya-U-R commented on app/client/cypress/support/Objects/Registry.ts
> +import { OneClickBinding } from "../../e2e/Regression/ClientSide/OneClickBinding/spec_utility";
Since OneClickBinding is very specific to that folder, Registry entry is not required for it. Please remove from here + its object from ObjectsCore.
Directly import & use the OneClickBinding in the OneClickBinding folder specs.

2023-06-03 07:07 UTC, vsvamsi1 commented
/ok-to-test sha=447386131a49810b3a8c825b6c90ec4e5cf2ef3c

2023-06-03 07:22 UTC, vsvamsi1 commented
/ok-to-test sha=d9a0ab468ce0884c842c22a53b1a2dac0b6a2f1a

2023-06-03 14:00 UTC, vsvamsi1 commented
/ok-to-test sha=84af95ca891b320f55b673a16756d3dae8188923

2023-06-04 03:45 UTC, vsvamsi1 commented
/ok-to-test sha=d7a11713f3c7eb325aa8b3efa033def95dfde84a

2023-06-04 06:56 UTC, vsvamsi1 commented
/ok-to-test sha=8fc36c90425c9f1e096fc9ed4d63a9aed459ba6b

2023-06-04 09:02 UTC, vsvamsi1 commented
/ok-to-test sha=49fd5419e0828ce7595127067fd3bc16ea00cf5f

2023-06-04 13:02 UTC, vsvamsi1 commented
/ok-to-test sha=0f93ad2f44e98133b2bf07d0ca28fe46102be711

2023-06-04 19:48 UTC, vsvamsi1 commented
/ok-to-test sha=88bbf76bdf40d0e9d550f12af261b9c1550f3727

2023-06-05 04:23 UTC, tanvibhakta requested changes

2023-06-05 04:23 UTC, tanvibhakta commented on app/client/src/components/editorComponents/WidgetQueryGeneratorForm/CommonControls/DatasourceDropdown/index.tsx
> +  color: #4c5664;
please use `var(--ads-v2-color-gray-600)`

2023-06-05 05:24 UTC, vsvamsi1 commented
/ok-to-test sha=0e9b5af96ece9553deec32d599b7e4e730899044

2023-06-05 07:05 UTC, tanvibhakta submitted a review, later dismissed

2023-06-05 07:12 UTC, vsvamsi1 commented
/ok-to-test sha=cccfd73685e2ea6bdced82136e023e7d0fead099

2023-06-05 09:09 UTC, vsvamsi1 commented
/ok-to-test sha=801e1d81766b082fc1ced3b64efcdc8c393e71a3

2023-06-05 12:20 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ClientSide/OneClickBinding/spec_utility.ts
> +import { ObjectsRegistry } from "../../../../support/Objects/Registry";
When ObjectsCore import is there, ObjectsRegistry is not needed.

2023-06-05 12:20 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ClientSide/OneClickBinding/spec_utility.ts
> +  public onboardingLocator = OnboardingLocator;
User objects from ObjectsCore, these many private variables not needed.

2023-06-05 12:20 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ClientSide/OneClickBinding/spec_utility.ts
> +    this.agHelper.GetNClick(this.locator.datasourceDropdownSelector);
Should be `_.agHelper.GetNClick(this.locator.datasourceDropdownSelector)`

2023-06-05 12:20 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ClientSide/OneClickBinding/TableWidget/postgres_spec.ts
>        (cy as any).openPropertyPane(WIDGET.TABLE);
Use `_.draggableWidgets.TABLE` instead of WIDGET.TABLE & remove this WIDGET import.

2023-06-05 17:04 UTC, vsvamsi1 commented on app/client/cypress/e2e/Regression/ClientSide/OneClickBinding/spec_utility.ts
> +  public onboardingLocator = OnboardingLocator;
Hi @Aishwarya-U-R I did not follow this comment.
Do you want me to remove all these public variables and import the locators in their respective test files?

2023-06-05 17:38 UTC, vsvamsi1 commented on app/client/cypress/e2e/Regression/ClientSide/OneClickBinding/spec_utility.ts
> +  public onboardingLocator = OnboardingLocator;
Hi @Aishwarya-U-R I have resolved in the above manner please have a look.

2023-06-05 17:38 UTC, vsvamsi1 commented
/ok-to-test sha=eea0d26fdd663a3fabaa6825fee47021a9f92edd

2023-06-06 02:15 UTC, Aishwarya-U-R commented
> 2\. cypress/e2e/Regression/ClientSide/OneClickBinding/TableWidget/mongoDB_spec.ts

@vsvamsi1 - Please check.. mongoDB_spec.ts has failed.

2023-06-06 03:32 UTC, vsvamsi1 commented
/ok-to-test sha=4f92e5142ca40c2ed462e240b209e0af42ce7185

2023-06-06 03:32 UTC, vsvamsi1 commented
> > 2. cypress/e2e/Regression/ClientSide/OneClickBinding/TableWidget/mongoDB_spec.ts
> 
> @vsvamsi1 - Please check.. mongoDB_spec.ts has failed.

@Aishwarya-U-R ...that was a refactoring error i made from my end ....i fixed it right now

2023-06-06 05:12 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ClientSide/OneClickBinding/spec_utility.ts
> +      `.t--one-click-binding-table-selector--table:contains(${table})`,
Direct locator here.

2023-06-06 05:12 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ClientSide/OneClickBinding/spec_utility.ts
> +      `${oneClickBindingLocator.searchableColumn} .rc-select-selection-item:contains(${column})`,
Here too.

2023-06-06 05:12 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ClientSide/OneClickBinding/spec_utility.ts
> +      `.t--one-click-binding-column-searchableColumn--column:contains(${column})`,
Here.

2023-06-06 05:12 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ClientSide/OneClickBinding/PropertyControl_spec.ts
>      _.entityExplorer.DragDropWidgetNVerify("tablewidgetv2");
Use `_.draggableWidgets.TABLE`

2023-06-06 05:12 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ClientSide/OneClickBinding/TableWidget/postgres_spec.ts
> +      (cy as any).openPropertyPane(_.draggableWidgets.TABLE);
Use `_.entityExplorer.SelectEntityByName`. Point is use TS helpers as much as possible

2023-06-06 05:12 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ClientSide/OneClickBinding/TableWidget/postgres_spec.ts
>      cy.wait("@postExecute");
Use `_.agHelper.ValidateN/wStatus()` here

2023-06-06 06:44 UTC, vsvamsi1 commented
/ok-to-test sha=110c1b925d0700db0ccc2c2efa3ed3fe2a1d1e59

2023-06-06 08:18 UTC, vsvamsi1 commented
/ok-to-test sha=536fd43e9aacbf0db35761a5230debca3d6dcc12

2023-06-06 09:21 UTC, tanvibhakta approved these changes

2023-06-06 11:04 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ClientSide/OneClickBinding/TableWidget/postgres_spec.ts
>  import { WIDGET } from "../../../../../locators/WidgetLocators";
Is WIDGET still needed?

2023-06-06 11:04 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ClientSide/OneClickBinding/TableWidget/postgres_spec.ts
>        (cy as any).openPropertyPane(WIDGET.TABLE);
I dont see this yet?

2023-06-06 11:05 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ClientSide/OneClickBinding/TableWidget/mongoDB_spec.ts
>  import { WIDGET } from "../../../../../locators/WidgetLocators";
Is WIDGET still needed?

2023-06-06 11:05 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ClientSide/OneClickBinding/TableWidget/mongoDB_spec.ts
>        (cy as any).openPropertyPane(WIDGET.TABLE);
Replace here.

2023-06-06 11:48 UTC, vsvamsi1 commented on app/client/cypress/e2e/Regression/ClientSide/OneClickBinding/TableWidget/postgres_spec.ts
>  import { WIDGET } from "../../../../../locators/WidgetLocators";
This has been resolved already, you may be viewing an older commit of this PR.

2023-06-06 11:50 UTC, vsvamsi1 commented
/ok-to-test sha=cc69ee3157eab1d3c64269550250841b568460ca

2023-06-06 17:33 UTC, Aishwarya-U-R reviewed
Cypress changes looks OK!

2023-06-06 17:35 UTC, merged