Linter check for dangling it.only tests
appsmithorg/appsmith pull request #23991
Opened 2023-06-02 09:44 UTC by me-heer

## Description
Dangling it.only tests skips other tests in the file and reduces our test coverage.

Added rule in .eslintrc to detect it.only calls in test files.
Cypress tests are named as *_spec.js, *_Spec.js, *_spec.ts and *_Spec.ts, whereas other tests follow the *.test.js|ts|jsx convention. So, I added this rule differently for Cypress and Default ESLint configuration.

#### PR fixes following issue(s)
Fixes #23708

#### Media

#### Type of change
- Chore (housekeeping or task changes that don't impact user perception)

## Testing
>
#### How Has This Been Tested?
- [X] Manual

Test Cases:
- Cypress: Button_Text_WithRecaptcha_spec.js contains it.only test, which starts getting detected by ESLint after this change.
- Default: Randomly picked files (which has *.test.js, *.test.ts, or *.test.tsx extensions) and  changed some it tests to it.only tests. All these cases where detected by ESLint after this change.

#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-06-05 04:36 UTC, rajatagrawal commented
Hello @me-heer , Thank you for submitted this pull request. The change looks good. Would you also be able to add this for `describe.only` as well please ? Thanks!

2023-06-06 03:27 UTC, rajatagrawal requested changes
Can we please add the lint check for `describe.only` as well ?

2023-06-06 12:03 UTC, rajatagrawal commented
I have test the changes locally and they are working fine.

2023-06-06 12:10 UTC, merged

2023-06-06 12:10 UTC, somangshu commented
cc @Aishwarya-U-R

2023-06-06 13:10 UTC, Aishwarya-U-R commented
@rajatagrawal - When will this exactly come into play? When we try to merge a PR with .only or when oktotest is run?

2023-06-06 13:19 UTC, Aishwarya-U-R commented
@rajatagrawal @somangshu - In such cases - even though Cypress was not needed, we could atleast let the server/client build go thru before merging the PR. Now client-build is failing in all latests CI runs. Please note.

2023-06-06 13:29 UTC, somangshu commented
@Aishwarya-U-R we can revert if you want!

2023-06-06 13:36 UTC, Aishwarya-U-R commented
No, I dont want to :P Is it not an easy fix now?