Fix direct `remixicon` imports in `packages/design-system/*`
appsmithorg/appsmith pull request #24010
Opened 2023-06-03 22:33 UTC by iamakulov

## Description

This PR:
- moves the icon-related ESLint rules from to `eslintrc.base.json` – to make them apply to all packages
- fixes direct `remixicon` imports surfaced by the change

#### Type of change

- Bug fix (non-breaking change which fixes an issue)

## Testing

#### How Has This Been Tested?

- [ ] Manual – smoke-tested that the dashboard and the editor open correctly
- [ ] Jest
- [ ] Cypress

#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-06-03 22:35 UTC, iamakulov commented on app/client/packages/design-system/headless/package.json
> +    "@design-system/widgets-old": "workspace:^",
Note that to use `importRemixIcon`, I had to add a dependency onto `@design-system/widgets-old` (in `headless` and `widgets`). This doesn’t feel super clean, so let me know if you’d prefer this to be different! (Eg should `importRemixIcon` live somewhere else?)

2023-06-05 05:15 UTC, SatishGandham commented
/ok-to-test

2023-06-05 09:06 UTC, KelvinOm commented on app/client/packages/design-system/headless/package.json
> +    "@design-system/widgets-old": "workspace:^",
Hey @iamakulov, thank you!

We absolutely do not want to have a dependency on the `design-system/widgets-old`. We discussed this issue in the team and decided to use the SVG code of icons directly in components without importing. We also found that the RemixIcon code is not optimized and before using it in our components, it needs to be run through [SVGOMG](https://jakearchibald.github.io/svgomg/).

Could you help with this?

cc @jsartisan

2023-06-05 09:39 UTC, somangshu commented on app/client/packages/design-system/headless/package.json
> +    "@design-system/widgets-old": "workspace:^",
cc @SatishGandham

2023-06-05 09:42 UTC, iamakulov commented on app/client/packages/design-system/headless/package.json
> +    "@design-system/widgets-old": "workspace:^",
> We discussed this issue in the team and decided to use the SVG code of icons directly in components without importing. 

Hmm could you share more about this? Curious about the context of the decision

2023-06-05 10:12 UTC, KelvinOm commented on app/client/packages/design-system/headless/package.json
> +    "@design-system/widgets-old": "workspace:^",
We don't plan to use a large number of icons in WDS(shouldn't be more than there is now), so we don't need to implement something more complex. We will use icons in our components, but they will be supplied by a third-party library and will be passed them as prop.

2023-06-05 23:01 UTC, iamakulov commented on app/client/packages/design-system/headless/package.json
> +    "@design-system/widgets-old": "workspace:^",
Deal! In that case, I’ll keep the ESLint rule on for the `headless` package and will just inline the (optimized) svg 👍

2023-06-05 23:33 UTC, iamakulov commented on app/client/packages/design-system/headless/package.json
> +    "@design-system/widgets-old": "workspace:^",
https://github.com/appsmithorg/appsmith/pull/24010/commits/7c37dab2c0ef849a9d8ab89b5eedb6f237a32855 (tested in Storybook)

2023-06-06 08:04 UTC, KelvinOm commented on app/client/packages/design-system/widgets/src/custom.d.ts
> +declare module "*.svg" {
Do we really need this?

2023-06-06 08:04 UTC, KelvinOm commented on app/client/packages/design-system/widgets/src/components/Button/Button.test.tsx
> +import { importRemixIcon } from "@design-system/widgets-old";
I'm sure that there should be the same approach as in headless components. Also with this approach, we will be able to avoid changes in `package.json` and `jest.config.js`

2023-06-06 08:04 UTC, KelvinOm commented on app/client/packages/design-system/headless/src/components/Checkbox/Checkbox.tsx
> +const CheckIcon = ({ size }: { size: number }) => {
cc @jsartisan

2023-06-06 11:27 UTC, iamakulov commented on app/client/packages/design-system/headless/src/components/Checkbox/Checkbox.tsx
> +const CheckIcon = ({ size }: { size: number }) => {
Yup, lmk if you’d prefer a different API/structure of these components! I went with a simpler one.

My only worry is that the easier we make it to inline new icons to `design-system/headless` and `design-system/widgets`, the higher’s the chance someone will do that, which will lead to bundling more and more icons. This was why I didn’t create a reusable wrapper like this one:

```js
const IconWrapper = ({ size = 24, color = "currentColor", children ...props }) =>
  <svg viewbox="0 0 24 24" width={size} height={size} fill={color}>{children}</svg>
```

– having a wrapper like that would “normalize” inlining icons, make it a regular pattern instead of an exceptional one.

2023-06-06 11:50 UTC, KelvinOm commented on app/client/packages/design-system/headless/src/components/Checkbox/Checkbox.tsx
> +const CheckIcon = ({ size }: { size: number }) => {
I share your concerns but I suppose we can go without a wrapper and once we realize we need a more complex approach we'll rewrite all this. We also have an icon component and I think `IconWrapper` will lead to some confusion.

2023-06-06 13:24 UTC, iamakulov commented on app/client/packages/design-system/widgets/src/components/Button/Button.test.tsx
> +import { importRemixIcon } from "@design-system/widgets-old";
https://github.com/appsmithorg/appsmith/pull/24010/commits/eba0d8af6dc503f08bbe043200a51b5691f113c2

2023-06-06 13:25 UTC, iamakulov commented on app/client/packages/design-system/widgets/src/custom.d.ts
> +declare module "*.svg" {
++, I added it just for that! Removed it now.

2023-06-06 13:31 UTC, iamakulov commented
Failed build output:

```
[appsmith]: Process started
[appsmith]: 
[appsmith]: /home/runner/work/appsmith/appsmith/app/client/src/workers/Evaluation/__tests__/evaluate.test.ts
[appsmith]:   275:1  error  Reason: Dangling *.only tests skip other tests in the file and reduce test coverage  no-restricted-syntax
[appsmith]: 
[appsmith]: ✖ 1 problem (1 error, 0 warnings)
[appsmith]: 
[appsmith]: Process exited (exit code 1), completed in 1m 25s
```

Uhhh should I do anything with this? Code in question:

https://github.com/appsmithorg/appsmith/blob/4a90bb54eb0a5ef73b999284119d0ca657246443/app/client/src/workers/Evaluation/__tests__/evaluate.test.ts#L275-L312

2023-06-06 17:06 UTC, KelvinOm requested changes

2023-06-06 17:06 UTC, KelvinOm commented on app/client/packages/design-system/widgets/src/components/Spinner/index.styled.tsx
> +  const className = "remixicon-icon " + (props.className || "");
Why is it all here? Why not like in other files? This is also a regular icon that we animate through keyframes.

2023-06-06 18:30 UTC, iamakulov commented on app/client/packages/design-system/widgets/src/components/Spinner/index.styled.tsx
> +  const className = "remixicon-icon " + (props.className || "");
Oh okay, that’s a good question. I went with that implementation because, unlike all other icons, this one accepts arbitrary props:

https://github.com/appsmithorg/appsmith/blob/4a90bb54eb0a5ef73b999284119d0ca657246443/app/client/packages/design-system/widgets/src/components/Spinner/index.tsx#L5-L11

– so I wanted to ensure the maximum compatibility with existing code that might expect a Remix icon there. (There _is_ the `IconProps` type that only allows `className`, but I’ve seen a pretty common usage of `any` across the codebase, so I wasn’t sure if I can rely on that.)

But I just searched, and it looks like Spinner isn’t actually used anywhere except the `<Button />` component, lol. Let me fix that!

2023-06-06 18:33 UTC, iamakulov commented on app/client/packages/design-system/widgets/src/components/Spinner/index.styled.tsx
> +  const className = "remixicon-icon " + (props.className || "");
https://github.com/appsmithorg/appsmith/pull/24010/commits/cd82a701d74b7fec132eb9d5a53c5026f9835595

2023-06-06 18:55 UTC, KelvinOm commented on app/client/packages/design-system/widgets/src/components/Spinner/index.styled.tsx
> +  const className = "remixicon-icon " + (props.className || "");
Got it. We are in the process of developing new components for widgets, so it is only used here. We will start implementing them in the near future. 

[Any](https://github.com/appsmithorg/appsmith/blob/release/app/client/.eslintrc.base.json#L30) is my sadness.  I think we'll do something about it in the future.

2023-06-06 18:58 UTC, KelvinOm approved these changes
LGTM

2023-06-06 18:58 UTC, KelvinOm commented on app/client/package.json
> +    "json5": "^2.2.3",
Why do we need this package?

2023-06-06 18:59 UTC, KelvinOm commented
@iamakulov Thank you for your effort.

2023-06-06 19:06 UTC, iamakulov commented on app/client/package.json
> +    "json5": "^2.2.3",
See this:

https://github.com/appsmithorg/appsmith/blob/cd82a701d74b7fec132eb9d5a53c5026f9835595/app/client/.eslintrc.js#L7-L9

In `.eslintrc.base.json`, we have a `@typescript-eslint/no-restricted-imports` rule banning some imports. In `.eslintrc.js`, we want to add _more_ imports into that rule. ESLint offers no way to do that (https://github.com/eslint/eslint/issues/9192) – you can only override a rule completely. So instead, we require the base config, take the banned imports, extend them with new ones, and _then_ override the rule.

We need to use `json5` because the base config uses comments. Perhaps we can just switch the base config to `.js` as well, dunno :)

2023-06-06 19:16 UTC, iamakulov commented on app/client/packages/design-system/widgets/src/components/Spinner/index.styled.tsx
> +  const className = "remixicon-icon " + (props.className || "");
FWIW one client of mine implemented a very nice process to gradually enforce some TypeScript or ESLint flag (like this `any` one):

1. Keep the ESLint rule disabled in the codebase
2. Set up a separate CI job that runs ESLint with the rule _enabled_. (ESLint will obviously fail, but that’s okay)
3. After ESLint runs, count the number of errors in the codebase (eg by parsing the output), compare it with `release`, and fail a CI check if it gets larger
   1. You don’t need a separate storage to compare the numbers – you can just run the same job on `release`, save the number of errors into CI caches, and then pull these caches in every other branch
4. With time, as developers rewrite existing code, they won’t add any new `any`s – but will remove existing ones, so the number of errors will decrease

I saw that working pretty well over a course of a year!

Although, in that client’s case, a big part why this was successful was also the incentives. The number of `any`s was lightly gamified – you’d see it [+ the difference with `release`] shown in status checks in every PR:

> ✅ **\`any\` usage** — No change (137 ± 0)

or 

> ✅ **\`any\` usage** — Great job! (130, ↓ 7 vs release)

or

> ❌ **\`any\` usage** — Failed: found new usages of \`any\` (138, ↑ 1 vs release)

and there were a few developers who really got into getting that number lower.

2023-06-06 19:43 UTC, KelvinOm commented on app/client/packages/design-system/widgets/src/components/Spinner/index.styled.tsx
> +  const className = "remixicon-icon " + (props.className || "");
Interesting approach, thanks for sharing this 👍.

I believe that question is actually not only in `any` but also in other rules and checks as well. Previously, I have used the approach when we enabled a rule and then suppressed errors using this [package](https://github.com/amanda-mitchell/suppress-eslint-errors). It worked well, but it added a lot of annoying comments to the code, which worsened readability.

I'm also thinking about moving the reused parts of the code into packages and in package we can use as strict rules as possible.

2023-06-09 09:44 UTC, merged