fix: Text and icon align in dropdown propety control having both name and symbol
appsmithorg/appsmith pull request #24173
Opened 2023-06-07 06:20 UTC by iSatVeerSingh

## Description
This PR fixes the alignment of properties containing both name and symbol in the dropdown in property control.
#### PR fixes following issue(s)
Fixes #23859

#### Media

https://github.com/appsmithorg/appsmith/assets/85070570/899133c9-1a01-486d-b264-32010750de43

#### Type of change
- Bug fix (non-breaking change which fixes an issue)

## Testing
>
#### How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Also list any relevant details for your test configuration.
> Delete anything that is not relevant
- [x] Manual
- [ ] Jest
- [ ] Cypress
>
>

## Checklist:
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-06-08 06:47 UTC, tanvibhakta requested changes

2023-06-08 06:47 UTC, tanvibhakta commented on app/client/src/index.css
> +
You're right, this is not behaviour that should be applied to all selects in our platform. I'd recommend taking a look at where the Selects in the issue have been implemented, and if the children that are being rendered in the options are wrapped in a fragment. They should be instead wrapped in a div/span/other element so that rc-select can style them correctly.

2023-06-08 08:17 UTC, iSatVeerSingh commented on app/client/src/index.css
> +
Will you please explain? what you said.

2023-06-09 06:07 UTC, iSatVeerSingh commented on app/client/src/index.css
> +
It is already wrapped inside a div. The div has class 'rc-select-selection-item'

2023-06-09 07:07 UTC, albinAppsmith commented on app/client/src/index.css
> +
Yes, that's correct but that div is inside the component and hence we should not alter the styles of it until there is no other solution. In this case we can wrap the content of the options inside an div and make it flex.

2023-06-09 08:56 UTC, iSatVeerSingh commented on app/client/src/index.css
> +
It has nothing to do with options. Options are already rendering fine and have display flex. I think its singleSelector in Select Component.

2023-06-14 06:39 UTC, closed without merging