fix: Reset templates filter for templates modal
appsmithorg/appsmith pull request #24192
Opened 2023-06-07 09:31 UTC by rahulbarwal

## Description
Currently we do not reset the template filters when we close template modal and open it again in `add page from template flow`
This becomes confusing for some users.

#### PR fixes following issue(s)
Fixes #17276

#### Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video
>
>
#### Type of change
- Bug fix (non-breaking change which fixes an issue)
## Testing
>
#### How Has This Been Tested?
- [x] Cypress
#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-06-07 09:51 UTC, Aishwarya-U-R requested changes

2023-06-07 09:51 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesModal_filtering_spec.ts
> +    cy.get(_.templates.locators.templateDialogBox).should("be.visible");
USe `agHelper.AssrtElementVisible`

2023-06-07 09:51 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesModal_filtering_spec.ts
> +    cy.get(_.templates.locators._resultsHeader).then(($header) => {
USe `agHelper.GetElemnt`. No direct cy.get or cy.xpath in specs.

2023-06-07 09:51 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesModal_filtering_spec.ts
> +      cy.get(_.templates.locators._resultsHeader).should(
Use `agHelper.GetNAssertElementText`

2023-06-07 09:51 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesModal_filtering_spec.ts
> +        $header.text(),
Sam as above.

2023-06-07 09:51 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesModal_filtering_spec.ts
> +      _.templates.closeTemplateDialogBox();
TS helper method names are CamelCase - `CloseTemplateDialogBox`

2023-06-07 09:51 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesPage_filtering_spec.ts
> +import * as _ from "../../../../../support/Objects/ObjectsCore";
Correct the above comments in this spec also.

2023-06-07 11:00 UTC, rahulbarwal commented on app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesModal_filtering_spec.ts
> +    cy.get(_.templates.locators._resultsHeader).then(($header) => {
Done.

2023-06-07 15:38 UTC, akash-codemonk approved these changes

2023-06-08 03:59 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesModal_filtering_spec.ts
> +const NAME_FILTER = "order";
Can this variable go inside describe? Global scope necessarily not needed.

2023-06-08 03:59 UTC, Aishwarya-U-R commented on app/client/cypress/support/Pages/Templates.ts
> +    );
How many times do you think we will be using these methods? Are they really needed? instead can we use the helpers directly?
This is one more level - which is not needed.

2023-06-08 03:59 UTC, Aishwarya-U-R commented on app/client/cypress/support/Pages/Templates.ts
> +    return cy.get(this.locators._templateViewGoBack).click();
No direct cy.get or cy.xpath in specs/helpers. Use `agHelper.GetElement` only,

2023-06-08 03:59 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesPage_filtering_spec.ts
> +  afterEach(() => cy.reload());
Use `agHelper.Refresh()`

2023-06-08 03:59 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesModal_filtering_spec.ts
> +          _.templates.AssertResultsHeaderText(headerText, "not.have.text");
Can you explain this condition a bit. 
We are searching with 'order'. Then expecting header to not have text? Which element is this _resultsHeader in UI please?

2023-06-08 06:38 UTC, rahulbarwal commented on app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesModal_filtering_spec.ts
> +const NAME_FILTER = "order";
Done.

2023-06-08 06:39 UTC, rahulbarwal commented on app/client/cypress/support/Pages/Templates.ts
> +    );
Kept only those methods which have more than one usage.
I was thinking of future problems, but yeah why solve a problem which we have not faced yet.

2023-06-08 06:39 UTC, rahulbarwal commented on app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesPage_filtering_spec.ts
> +  afterEach(() => cy.reload());
Done.

2023-06-08 06:39 UTC, rahulbarwal commented on app/client/cypress/support/Pages/Templates.ts
> +    return cy.get(this.locators._templateViewGoBack).click();
Done.

2023-06-08 06:41 UTC, rahulbarwal commented on app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesModal_filtering_spec.ts
> +          _.templates.AssertResultsHeaderText(headerText, "not.have.text");
Before we type header will have something like: "Showing 20 templates"
After we type into the search input, if filtering is successful the number of templates should be less and header would have changed to something like "Showing 5 templates"

This check basically means that filtering via search input indeed is functional.

2023-06-08 07:19 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesModal_filtering_spec.ts
> +          _.templates.AssertResultsHeaderText(headerText, "not.have.text");
Oh I see that now!

2023-06-08 07:19 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesModal_filtering_spec.ts
> +import * as _ from "../../../../../support/Objects/ObjectsCore";
Also please import only needed objects from ObjectsCore:
```
import {
  agHelper,
  entityExplorer
} from "../../../../support/Objects/ObjectsCore";
```

I'm seeing only entityExplorer & agHelper are needed in specs. So why to import 100% of objects.

2023-06-08 07:19 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesPage_filtering_spec.ts
> +          });
Can we use` agHelper.CheckUncheck` here?

2023-06-08 07:19 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesPage_filtering_spec.ts
> +          .should("equal", NAME_FILTER);
Use `agHelper.AssertText` here

2023-06-08 07:21 UTC, Aishwarya-U-R commented on app/client/cypress/support/Pages/Templates.ts
> +    );
Yeah if method is needed more than once, we can definitely have them created. Else lets prefer to use the helpers to solve the case.

2023-06-08 07:23 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesModal_filtering_spec.ts
> +});
And hey, do you think we will add more cases to this spec? Can we please combine the below spec also into this - `TemplatesFiltering_Spec.ts`? Totally 5 `it` blocks in a spec is still fine.

2023-06-08 07:36 UTC, rahulbarwal commented on app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesModal_filtering_spec.ts
> +import * as _ from "../../../../../support/Objects/ObjectsCore";
Done in both files.

2023-06-08 07:38 UTC, rahulbarwal commented on app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesPage_filtering_spec.ts
> +          .should("equal", NAME_FILTER);
Done.

2023-06-08 07:39 UTC, rahulbarwal commented on app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesModal_filtering_spec.ts
> +});
There are 2 reasons for keeping these separate:
1. Process to reach these is different, for one we go to templates tab, for this one we go inside any app and then go to `add a page from template`
2. yes, we expect that test cases in this might increase in nearby future.

2023-06-08 07:44 UTC, Aishwarya-U-R reviewed
Cypress looks good!

2023-06-08 07:44 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesModal_filtering_spec.ts
> +describe("Templates modal filtering", () => {
Also better to add Bug id to describe - so anyone searching in future will know a test case exists for this & dont duplicate.
`describe("Bug 17276 - Templates modal filtering", () => {`

2023-06-08 08:28 UTC, rahulbarwal commented on app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesModal_filtering_spec.ts
> +describe("Templates modal filtering", () => {
Makes sense added. 

Thanks @Aishwarya-U-R  for a thorough review 🙂. I'll make lesser mistakes because of you.

2023-06-13 09:34 UTC, shwetha-ramesh commented
@rahulbarwal Tested this [DP](https://appsmith-m818t6doy-get-appsmith.vercel.app/) and found this [issue](https://www.loom.com/share/7d77ae5a742e4b4092021fbe417b4dda)

2023-06-13 12:59 UTC, rahulbarwal commented
Thanks @shwetha-ramesh for bringing this to attention. 
Upon debugging this we found a bug in design system, and raised a ticket for this: https://github.com/appsmithorg/design-system/issues/501

We will continue on this once that is resolved.

2023-06-23 06:24 UTC, rahulbarwal commented
/build-deploy-preview env=release

2023-06-23 06:25 UTC, rahulbarwal commented
/ok-to-test

2023-06-23 10:21 UTC, rahulbarwal commented
/ok-to-test

2023-06-23 10:26 UTC, rahulbarwal commented
Hey @shwetha-ramesh , 
>Tested this [DP](https://appsmith-m818t6doy-get-appsmith.vercel.app/) and found this [issue](https://www.loom.com/share/7d77ae5a742e4b4092021fbe417b4dda)

This issue has been fixed. Please test this on [DP URL](https://appsmith-bx0fm6izf-get-appsmith.vercel.app)

2023-06-27 12:15 UTC, rahulbarwal commented
/ok-to-test

2023-06-28 09:11 UTC, shwetha-ramesh commented
@rahulbarwal Re-tested this ticket along with the issue reported. Working as expected. 
QA Done

2023-06-28 09:31 UTC, rahulbarwal commented
/ok-to-test

2023-06-28 09:33 UTC, rahulbarwal commented on app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesPage_filtering_spec.ts
> +describe("excludeForAirgap", "Templates page filtering", () => {
Nope, with this PR I am increasing the test coverage to templates pages.

2023-06-28 09:34 UTC, rahulbarwal commented on app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesPage_filtering_spec.ts
> +        });
`FUNCTIONS_FILTER` is an array here, I am selecting multiple check boxes at once. Dont think `CheckUncheck` can be used.

2023-06-28 09:39 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesPage_filtering_spec.ts
> +        });
Ok, `CheckUncheck` can still be called individually which will also check the checked state after checked.
Leaving it to your call now. But if this is flaky - we may need to fix it.

2023-06-28 09:43 UTC, rahulbarwal commented on app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesPage_filtering_spec.ts
> +        }
I am testing filtering with this spec here. Consider this scenario:
1. We have 20 templates and header text says "Showing 20 templates"
2. I filter it using name or by checking the "Functions" 
3. resultant header text would be "Showing n templates" where n<20(if filter is successfull)
4. we can not assume what this n would turn out to be. And as the templates team keeps on adding new templates, these numbers would fluctuate more.

Only workaround this would be to use a fixture so that we can dictate the headers and filters. 
What do you think would be better to have this via fixtures OR via templates(& cloud services network call) communication?

2023-06-28 09:54 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesPage_filtering_spec.ts
> +        }
Ok, ah I see... According to me - the valid test for filtering would be to check if each of the filtered template has the filtered category against it. Headers - I'm all skeptical about test validation :)

2023-06-28 10:03 UTC, rahulbarwal commented on app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesPage_filtering_spec.ts
> +        });
We don't want that 😛. 
The checkboxes are dynamic in this page and did not have name attribute. Added that and used `CheckUncheck`

2023-06-28 11:38 UTC, rahulbarwal commented
@Aishwarya-U-R 
Updated the spec to address concerns raised above. Used fixtures where possible. Please take a look.

2023-06-28 13:15 UTC, Aishwarya-U-R commented on app/client/cypress/fixtures/Templates/AllowPageImportTemplates.json
> +      "functions": ["Customer Support"],
I dint get why this is added!

2023-06-29 05:03 UTC, rahulbarwal commented
/ok-to-test

2023-06-29 05:15 UTC, Aishwarya-U-R reviewed
Approving Cypress changes.

2023-06-29 05:15 UTC, Aishwarya-U-R commented on app/client/cypress/support/Pages/Templates.ts
> +  refreshTemplatesPage(
`RefreshTemplatesPage` - method name.

2023-06-29 05:26 UTC, rahulbarwal commented on app/client/cypress/support/Pages/Templates.ts
> +  refreshTemplatesPage(
Done. 👍

2023-06-29 06:19 UTC, abm17 approved these changes

2023-06-29 06:21 UTC, Aishwarya-U-R approved these changes

2023-06-29 06:22 UTC, merged