[Fix] - Authentication after 404 not redirecting back to the original page
appsmithorg/appsmith pull request #2423
Opened 2021-01-04 06:48 UTC by jsartisan

If you land on a private app without authentication, it is shown as 404. But after you sign in, you are redirected back to the homepage instead of the app

Fixes #2415 

## Type of change
- Bugfix

## How Has This Been Tested?
- Manually tested

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-01-04 08:24 UTC, hetunandu requested changes

2021-01-04 08:24 UTC, hetunandu commented on app/client/src/pages/common/PageNotFound.tsx
> +    get(user, "email") !== "anonymousUser"
This behaviour of appending the url should happen depending on the error and not on the auth user currently. Please confirm with backend the error code for an existing app but permission denied and decide the redirect url for that

2021-01-05 07:39 UTC, jsartisan commented on app/client/src/pages/common/PageNotFound.tsx
> +    get(user, "email") !== "anonymousUser"
@hetunandu I just changed the logic. Nikhil asked to redirect "not logged in" directly to the login page with `redirectTo` param. For other users, on clicking the button, the user will be redirected to the applications page. 

> Please confirm with backend the error code for an existing app but permission denied and decide the redirect URL for that
We get a 404 status code for `existing app but permission denied`.  Currently, we are not differentiating between existing apps ( but permission denied ) and non-existing apps.

2021-01-05 19:18 UTC, hetunandu requested changes
This does not check for if the app exists or not. That means it will redirect even if the app or page does not really exist

2021-01-06 05:22 UTC, jsartisan commented
> This does not check for if the app exists or not. That means it will redirect even if the app or page does not really exist

@hetunandu Seems like that is intentional for security reasons.

2021-01-06 05:55 UTC, hetunandu commented on app/client/src/pages/common/PageNotFound.tsx
> +    window.location.href = `${AUTH_LOGIN_URL}?redirectTo=${window.location.href}`;
This check can happen at the error level directly now since it is a redirect, dont render the PageNotFound page at all

2021-01-06 09:35 UTC, jsartisan commented
@hetunandu replaced every occurrence of `redirectTo` to `redirectUrl`.

2021-01-06 09:53 UTC, hetunandu requested changes

2021-01-06 09:53 UTC, hetunandu commented on app/client/src/pages/common/PageNotFound.tsx
> +export default connect(mapStateToProps, {
Not needed anymore right?

2021-01-06 09:53 UTC, hetunandu commented on app/client/src/sagas/ErrorSagas.tsx
> +function* preSafeCrashSaga(action: ReduxAction<{ code?: string }>) {
```suggestion
function* safeCrashSagaRequest(action: ReduxAction<{ code?: string }>) {
```

2021-01-06 09:53 UTC, hetunandu commented on app/client/src/sagas/ErrorSagas.tsx
> +    preSafeCrashSaga,
```suggestion
    safeCrashSagaRequest,
```

2021-01-06 10:11 UTC, jsartisan commented on app/client/src/sagas/ErrorSagas.tsx
> +function* preSafeCrashSaga(action: ReduxAction<{ code?: string }>) {
Oh sorry. I forgot this name change. Updated now.

2021-01-06 10:11 UTC, jsartisan commented on app/client/src/pages/common/PageNotFound.tsx
> +export default connect(mapStateToProps, {
Removed.

2021-01-06 10:21 UTC, hetunandu approved these changes

2021-01-06 11:24 UTC, merged