feat: query creation dumb templates replaced with smart templates
appsmithorg/appsmith pull request #24234
Opened 2023-06-08 07:29 UTC by sneha122

## Description
> Add a TL;DR when description is extra long (helps content team)
>
> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change
>
> Links to Notion, Figma or any other documents that might be relevant to the PR
>
>
#### PR fixes following issue(s)
Fixes # (issue number)
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
#### Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video
>
>
#### Type of change
> Please delete options that are not relevant.
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
## Testing
>
#### How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Also list any relevant details for your test configuration.
> Delete anything that is not relevant
- [ ] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-06-08 07:30 UTC, sneha122 commented
/ok-to-test

2023-06-09 06:19 UTC, sneha122 commented
A critical [issue](https://github.com/appsmithorg/appsmith/issues/24236) was prioritised while this was in progress

2023-06-09 09:19 UTC, sneha122 commented
/ok-to-test

2023-06-10 08:14 UTC, sneha122 commented
/ok-to-test

2023-06-12 10:37 UTC, sneha122 commented
/build-deploy-preview

2023-06-13 06:32 UTC, sneha122 commented
/ok-to-test

2023-06-13 10:40 UTC, sneha122 commented
/ok-to-test

2023-06-14 06:59 UTC, sneha122 commented
/build-deploy-preview

2023-06-14 14:18 UTC, Irongade requested changes

2023-06-14 14:18 UTC, Irongade commented on app/client/src/pages/Editor/FormControl.tsx
> +    if (showTemplate && !convertFormToRaw && !isMongoPlugin()) {
There is a better way to do this. Make use of the SQL Datasources List in QueryEditorConstants.

2023-06-14 14:18 UTC, Irongade commented on app/client/src/sagas/QueryPaneSagas.ts
>    const pluginTemplates: Record<string, unknown> = yield select(
So does this mean initialize will be called from the QueryEditor?

2023-06-15 05:15 UTC, sneha122 commented on app/client/src/pages/Editor/FormControl.tsx
> +    if (showTemplate && !convertFormToRaw && !isMongoPlugin()) {
Yes that seems like a good solution. I was not actually aware of this. Thanks @Irongade Will make the corresponding change

2023-06-15 05:16 UTC, sneha122 commented on app/client/src/sagas/QueryPaneSagas.ts
>    const pluginTemplates: Record<string, unknown> = yield select(
yes in changeQuerySaga, we have form initialise happening. Remember we had discussed this issue, initialisation was happening in two places. so removed from here. Let me know if you think otherwise

2023-06-15 05:56 UTC, Aishwarya-U-R requested changes
Hey @sneha122 , please make the change suggested in all specs below too & re-send for review.

2023-06-15 05:56 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ClientSide/BugTests/Moment_Spec.ts
>      _.dataSources.EnterQuery(query);
This will automatically replace the old. So line # 21 not needed here & all such places where `dataSources.EnterQuery` is used next

2023-06-15 05:56 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ClientSide/ExplorerTests/CopyQuery_RenameDatasource_spec.js
>      cy.get(".CodeMirror textarea").first().focus().type("select * from users");
Instead can you please replace this line to use `EnterQuery`?
Like `_.dataSources.EnterQuery("select * from users");` & remove line # 38, 39

2023-06-15 05:56 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ClientSide/Binding/JSObject_Postgress_Table_spec.js
>        cy.get(".CodeMirror textarea")
Replace this to use EnterQuery like `_.dataSources.EnterQuery("SELECT * FROM configs LIMIT 10;");` instead.

2023-06-15 05:56 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ClientSide/ExplorerTests/Datasource_Structure_spec.js
> +    dataSources.EnterQuery("");
Instead use EnterQuery like this  - `dataSources.EnterQuery("CREATE TABLE public.${tableName} ( ID int );");` in line # 90

2023-06-15 06:11 UTC, sneha122 commented on app/client/cypress/e2e/Regression/ClientSide/BugTests/Moment_Spec.ts
>      _.dataSources.EnterQuery(query);
@Aishwarya-U-R EnterQuery("") is needed because otherwise editor would already have a prepopulated query and EnterQuery(query) would add query in front of it. For example if editor is populated with `select * from users` and the test wants to add a new query of `select * from employees`, then if we dont use EnterQuery(""), it will populate like `select * from usersselect * from employees`

2023-06-15 08:30 UTC, Irongade commented on app/client/src/pages/Editor/FormControl.tsx
> +      !NO_SQL_DATASOURCES.includes(pluginName)
Here I think you should use SQL_Datasources directly, rather than use No_SQL_DATASOURCES, This is because for now, it is strictly an SQL feature.

`SQL_DATASOURCES.includes(pluginName)`

2023-06-15 09:08 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ClientSide/BugTests/Moment_Spec.ts
>      _.dataSources.EnterQuery(query);
Hey, I hope we stand clarified here 👍🏻

2023-06-15 09:25 UTC, sneha122 commented on app/client/src/pages/Editor/FormControl.tsx
> +      !NO_SQL_DATASOURCES.includes(pluginName)
okay yeah that makes sense

2023-06-16 09:07 UTC, sneha122 commented
/ok-to-test

2023-06-16 09:07 UTC, sneha122 commented
/build-deploy-review

2023-06-16 10:21 UTC, sneha122 commented
/build-deploy-preview

2023-06-16 13:23 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ServerSide/Params/ExecutionParams_spec.js
> +import { ObjectsRegistry } from "../../../../support/Objects/Registry";
Import from ObjectsCore & use the same objects. Line 7 is not needed.

2023-06-16 13:23 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ServerSide/QueryPane/AddWidget_spec.js
> +let dataSources = ObjectsRegistry.DataSources;
Import needed objects from ObjectsCore.

2023-06-16 13:23 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ServerSide/QueryPane/SwitchDatasource_spec.js
> +import * as _ from "../../../../support/Objects/ObjectsCore";
Import only needed objects. `import *` not required.

2023-06-16 13:23 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ServerSide/QueryPane/SwitchDatasource_spec.js
> +import * as _ from "../../../../support/Objects/ObjectsCore";
If no object is used, please remove this import.

2023-06-17 14:14 UTC, sneha122 commented
/ok-to-test

2023-06-17 14:50 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ServerSide/QueryPane/SwitchDatasource_spec.js
> -    cy.get(queryLocators.templateMenu).click({ force: true });
No `EnterQuery` needed here?

2023-06-17 14:55 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ServerSide/QueryPane/MySQL_Spec.ts
> +    dataSources.EnterQuery("SELECT * FROM users LIMIT 10");
Is this needed here? `runQueryNValidate` will already enter query & validate too!

2023-06-17 14:55 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ServerSide/QueryPane/MySQL_Spec.ts
> +    dataSources.EnterQuery("SELECT * FROM users LIMIT 10");
`EnterQuery` not needed here too.

2023-06-17 16:27 UTC, Aishwarya-U-R commented
/ok-to-test sha=0591e78

2023-06-17 16:29 UTC, Aishwarya-U-R approved these changes
Cypress changes looks good, Approving!

2023-06-17 16:29 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ServerSide/QueryPane/SwitchDatasource_spec.js
> -    cy.get(queryLocators.templateMenu).click({ force: true });
Ok, Understood why EnterQuery is not needed here.

2023-06-17 16:36 UTC, Aishwarya-U-R commented
/ok-to-test sha=e1bf61a

2023-06-17 18:06 UTC, Aishwarya-U-R commented
/ok-to-test sha=749905b

2023-06-18 14:09 UTC, prapullc commented
/build-deploy-preview skip-tests=true

2023-06-19 09:53 UTC, merged