feat/Replace fusion charts with Echarts
appsmithorg/appsmith pull request #24249
Opened 2023-06-08 10:41 UTC by rajatagrawal

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.
>
## Description
> Add a TL;DR when description is extra long (helps content team)
>
> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change
>
> Links to Notion, Figma or any other documents that might be relevant to the PR
>
>
#### PR fixes following issue(s)
Fixes # (issue number)
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
#### Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video
>
>
#### Type of change
> Please delete options that are not relevant.
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
## Testing
>
#### How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Also list any relevant details for your test configuration.
> Delete anything that is not relevant
- [ ] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-06-08 10:41 UTC, rajatagrawal commented
/build-deploy-preview env=release

2023-06-08 10:57 UTC, rajatagrawal commented
/build-deploy-preview env=release

2023-06-18 12:02 UTC, rajatagrawal commented
/build-deploy-preview env=release

2023-06-29 10:00 UTC, rajatagrawal commented
/build-deploy-preview env=release

2023-06-29 10:53 UTC, rajatagrawal commented
/ok-to-test sha=f157c96

2023-06-29 10:53 UTC, rajatagrawal commented
/build-deploy-preview env=release

2023-06-29 11:27 UTC, rajatagrawal commented
/build-deploy-preview env=release

2023-06-29 13:53 UTC, rajatagrawal commented
/ok-to-test sha=a214bec

2023-06-30 04:47 UTC, ashit-rath commented on app/client/src/components/editorComponents/ErrorBoundry.tsx
> +            Oops, Something went wrong 123.
Is this an accidental change?

2023-06-30 04:47 UTC, ashit-rath commented on app/client/src/widgets/ChartWidget/component/ChartWidgetErrorComponent.tsx
> +      style={{
Any reason for using inline styles over styled components?

2023-06-30 04:47 UTC, ashit-rath commented on app/client/src/widgets/ChartWidget/constants.ts
> +// export const CUSTOM_CHART_DEFAULT_PARSED = {
Can this comment be removed?

2023-06-30 04:50 UTC, ashit-rath reviewed
@rajatagrawal Is the PR ready for review? I see a lot of commented code, console logs.
Also please do fix the PR description

2023-06-30 05:39 UTC, rajatagrawal commented
> @rajatagrawal Is the PR ready for review? I see a lot of commented code, console logs. Also please do fix the PR description

@ashit-rath 

This PR isn't ready for review yet. It is still a work in progress. I think it got auto assigned to you because of code owners script. Apologies.

2023-06-30 05:39 UTC, rajatagrawal commented
/ok-to-test sha=ed55c72

2023-06-30 06:26 UTC, rajatagrawal commented
/ok-to-test sha=e0ce9ba

2023-06-30 06:38 UTC, ashit-rath commented
> > @rajatagrawal Is the PR ready for review? I see a lot of commented code, console logs. Also please do fix the PR description
> 
> @ashit-rath
> 
> This PR isn't ready for review yet. It is still a work in progress. I think it got auto assigned to you because of code owners script. Apologies.

Ahh okay, no worries

2023-06-30 07:16 UTC, rajatagrawal commented
/build-deploy-preview env=release

2023-06-30 11:08 UTC, rajatagrawal commented
/build-deploy-preview env=release

2023-06-30 11:26 UTC, rajatagrawal commented
/build-deploy-preview env=release

2023-07-05 10:52 UTC, rajatagrawal commented
@Aishwarya-U-R can you please review the changes in the cypress folder ?

2023-07-05 11:08 UTC, rajatagrawal commented
/build-deploy-preview env=release

2023-07-05 11:08 UTC, rajatagrawal commented
/ok-to-test sha=fc9a9d9

2023-07-06 02:09 UTC, rajatagrawal commented
@Aishwarya-U-R 
I think I have to make some more significant changes to cypress tests. The cypress tests are not ready for review yet. Removing you from review for now. Thanks!

2023-07-06 11:50 UTC, vsvamsi1 commented on app/client/src/widgets/ChartWidget/component/index.tsx
>      }
Can you scope the try block to the area generating error..I think in this it is the statement
```
  this.echartsInstance = echarts.init(chartContainerElement, undefined, {
          renderer: "svg",
        });
```

2023-07-06 11:54 UTC, vsvamsi1 commented on app/client/src/widgets/ChartWidget/component/EChartsConfiguration.ts
> +      !equal(prevProps.topRow, props.topRow)
This is a pretty heavy computation, If the referencing aren't changing for these properties can they be regular "===" checks?

2023-07-06 11:56 UTC, vsvamsi1 commented on app/client/src/widgets/ChartWidget/component/index.tsx
> +      },
This is also a pretty heavy computation "datasetFromData" is of O(n2) complexity, Is it possible you can cache this computation?

2023-07-10 02:07 UTC, rajatagrawal commented
/build-deploy-preview env=release

2023-07-10 02:51 UTC, rajatagrawal commented
/build-deploy-preview env=release

2023-07-18 16:27 UTC, KelvinOm commented on app/client/src/workers/Evaluation/validations.ts
> +      // console.log("***", "evaluatiing result ", result)
@rajatagrawal Is this PR ready to review?

2023-07-19 04:18 UTC, rajatagrawal commented on app/client/src/workers/Evaluation/validations.ts
> +      // console.log("***", "evaluatiing result ", result)
not yet

2023-07-19 06:32 UTC, rajatagrawal commented on app/client/src/widgets/ChartWidget/component/index.test.tsx
> +import ChartComponent from ".";
Sample UI Unit Test

2023-07-19 07:01 UTC, KelvinOm commented on app/client/src/workers/Evaluation/validations.ts
> +      // console.log("***", "evaluatiing result ", result)
Could you please mark PR as draft until it's ready?

2023-07-20 10:17 UTC, tanvibhakta commented
/build-deploy-preview env=release

2023-07-20 18:41 UTC, KelvinOm requested changes

2023-07-20 18:41 UTC, KelvinOm commented on app/client/src/widgets/ChartWidget/component/EChartsConfigurationBuilder.ts
> +    // console.log("***", "name gap is ", gap)
Don't forget clean up all of this before merge.

2023-07-20 18:41 UTC, KelvinOm commented on app/client/src/widgets/ChartWidget/component/EChartsConfigurationBuilder.ts
> +      if (props.chartType == "BAR_CHART" || props.chartType == "COLUMN_CHART") {
Better use `switch` because it faster and reads better than `if else` constructions.

2023-07-20 18:41 UTC, KelvinOm commented on app/client/src/widgets/ChartWidget/widget/index.tsx
> +      const chartError = new Error("rajat message")
Be careful with such messages, we would not like it to get into the release. Can we add a target message here?

2023-07-20 18:45 UTC, KelvinOm commented on app/client/src/widgets/ChartWidget/component/EChartsConfigurationBuilder.ts
> +  #nameGapForXAxisLabel = (props : ChartComponentProps) => {
Why not `privet ` TS access modifier?

2023-07-21 05:19 UTC, rajatagrawal commented
/ok-to-test sha=b02c93a

2023-07-21 05:30 UTC, rajatagrawal commented on app/client/src/pages/Editor/PropertyPane/PropertyPaneView.tsx
> +        {!isDeprecated && (
Fixed now

2023-07-21 05:36 UTC, rajatagrawal commented on app/client/src/widgets/ChartWidget/component/EChartsConfigurationBuilder.ts
> +export default class EChartsConfigurationBuilder {
Fixed now.

2023-07-21 05:42 UTC, rajatagrawal commented on app/client/src/widgets/ChartWidget/component/EChartsConfigurationBuilder.ts
> +      if (props.chartType == "BAR_CHART" || props.chartType == "COLUMN_CHART") {
Fixed now.

2023-07-21 06:45 UTC, rajatagrawal commented
/build-deploy-preview env=release

2023-07-24 04:29 UTC, rajatagrawal commented
/ok-to-test sha=9ee9368

2023-07-24 04:29 UTC, rajatagrawal commented
/build-deploy-preview env=release

2023-07-24 10:12 UTC, rajatagrawal commented
/ok-to-test sha=409aa13

2023-07-24 10:12 UTC, rajatagrawal commented
/build-deploy-preview env=release

2023-07-24 11:00 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ClientSide/Widgets/Chart/ChartWidgetErrors.ts
> +      ".t--widget-chartwidget",
Use -` locators._widgetInDeployed(draggableWidgets.CHART)`

2023-07-24 11:09 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ClientSide/Widgets/Chart/Chart_1_spec.js
> -const viewWidgetsPage = require("../../../../../locators/ViewWidgets.json");
Why are these files deleted?

2023-07-24 11:51 UTC, rajatagrawal commented
/ok-to-test sha=09d31f7

2023-07-24 11:51 UTC, rajatagrawal commented
/build-deploy-preview env=release

2023-07-24 11:52 UTC, rajatagrawal commented on app/client/src/widgets/ChartWidget/component/EChartsConfigurationBuilder.test.ts
> +import { Colors } from "constants/Colors";
Unit test for Charts Configuration

2023-07-24 11:53 UTC, rajatagrawal commented on app/client/cypress/e2e/Regression/ClientSide/Widgets/Chart/Chart_1_spec.js
> -const viewWidgetsPage = require("../../../../../locators/ViewWidgets.json");
The test cases in these files have been to unit tests in this file : https://github.com/appsmithorg/appsmith/pull/24249/files#r1272159699

2023-07-25 04:02 UTC, laveena-en commented
@rajatagrawal 
Can we add in data to be seen on hover of the datapoints?
Empty states i.e, when no data is present are inconsistent. 
Loom for the above two points: https://www.loom.com/share/b82963de494445a5afaffcfec9db1a3b?sid=e7e9e26f-8a86-4bff-bacb-bc4ffe26c758
Also, as discussed, 
The line for pie charts needs to be removed.
Positioning of the legends to be made horizontal so there's no overlap over the graph.
Can we also change the `More Details` button's styling to be similar to the `Connect Data` button that we see on the table widget.

2023-07-25 05:57 UTC, vsvamsi1 submitted a review, later dismissed

2023-07-25 06:57 UTC, rajatagrawal commented
/ok-to-test sha=c7d9442

2023-07-25 06:57 UTC, rajatagrawal commented
/build-deploy-preview env=release

2023-07-25 06:57 UTC, rajatagrawal commented
@jsartisan can you please help review changes in ChartErrorComponent file ?

2023-07-25 08:50 UTC, rajatagrawal commented
/build-deploy-preview env=release

2023-07-25 08:50 UTC, rajatagrawal commented
/ok-to-test sha=3a32acb

2023-07-25 12:02 UTC, chandannkumar commented
Observations:
- Data points are hard to read in multiple series data chart. As the datapoints are displayed above the bar. This is happening for only Bar_chart
![image.png](https://images.zenhubusercontent.com/61e65341d503e6aafa5df216/aedf5a7a-1b1e-46c6-92ee-8da1dc5a4c72)

- Pie chart behaviour is not same as we have in prod today. Check the video for the difference in feature
https://www.loom.com/share/4c1d5195fe76459e8c57cedd8f904978

2023-07-25 13:30 UTC, chandannkumar commented
@rajatagrawal added some more callouts above

2023-07-26 11:32 UTC, jsartisan commented
@rajatagrawal The error component code looks good. Just one question: Should the widget use the platform's component ( ADS Components ), or should it use wds components?
If the answer is "It should use wds components only", we will need to change the component later on once wds components are available to use.

2023-07-27 07:03 UTC, rajatagrawal commented
/build-deploy-preview env=release

2023-07-27 12:39 UTC, chandannkumar commented
Tested and verified all the callouts and LGTM
- Tested migration scenarios
- Tested on modals and containers
- Tested custom fusion charts as well
- Tested error state functionalities

2023-07-27 14:41 UTC, rajatagrawal commented
/ok-to-test sha=862bc41

2023-07-28 05:47 UTC, rajatagrawal commented
/build-deploy-preview env=release

2023-07-28 05:47 UTC, rajatagrawal commented
/ok-to-test sha=3763410

2023-07-28 05:49 UTC, vsvamsi1 approved these changes

2023-07-28 12:57 UTC, chandannkumar commented
Tested this PR in new DP and it LGTM

2023-07-28 13:29 UTC, merged