fix: table search is not working properly for url colums
appsmithorg/appsmith pull request #24244
Opened 2023-06-08 09:51 UTC by berzerkeer

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.
>
## Description
> Add a TL;DR when description is extra long (helps content team)
>
> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change
>
> Links to Notion, Figma or any other documents that might be relevant to the PR
>
>
#### PR fixes following issue(s)
Fixes # (issue number)
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
#### Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video
>
>
#### Type of change
> Please delete options that are not relevant.
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
## Testing
>
#### How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Also list any relevant details for your test configuration.
> Delete anything that is not relevant
- [ ] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-06-08 09:51 UTC, berzerkeer commented
/build-deploy-preview env=release

2023-06-08 10:37 UTC, berzerkeer commented
/build-deploy-preview env=release

2023-06-08 10:40 UTC, berzerkeer commented
/build-deploy-preview env=release

2023-06-12 12:36 UTC, berzerkeer commented
/ok-to-test

2023-06-12 15:45 UTC, berzerkeer commented
/ok-to-test

2023-06-13 12:02 UTC, sbalaji1192 commented on app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/TableV2_FilteredTableData_spec.js
> +    _.entityExplorer.SelectEntityByName("Table1");
1. We need to validate search, filter and sorting with display text.

2023-06-14 10:46 UTC, berzerkeer commented
/ok-to-test

2023-06-14 10:48 UTC, berzerkeer commented
/ok-to-test

2023-06-14 10:51 UTC, berzerkeer commented
/ok-to-test

2023-06-14 11:09 UTC, berzerkeer commented
/ok-to-test

2023-06-15 07:18 UTC, berzerkeer commented
/ok-to-test sha=acf88d0

2023-06-15 14:18 UTC, berzerkeer commented
/ok-to-test sha=5b98348

2023-06-16 06:00 UTC, berzerkeer commented
/ok-to-test sha=e37d353

2023-06-16 06:26 UTC, berzerkeer commented
/ok-to-test sha=c716bd1

2023-06-16 06:32 UTC, berzerkeer commented
/build-deploy-preview env=release

2023-06-16 09:35 UTC, sbalaji1192 commented on app/client/src/widgets/TableWidgetV2/widget/derived.test.js
> +          displayText: ["D.COM", "C.COM", "B.COM", "A.COM"],
switch this

2023-06-16 09:35 UTC, sbalaji1192 commented on app/client/src/widgets/TableWidgetV2/widget/derived.test.js
> +          displayText: ["D.COM", "C.COM", "B.COM", "A.COM"],
add cases for search and filter

2023-06-16 10:42 UTC, berzerkeer commented
/ok-to-test sha=d36dc80

2023-06-16 11:43 UTC, NandanAnantharamu requested changes
As discussed please update the test in .ts and then send for review.

2023-06-19 04:41 UTC, NandanAnantharamu commented on app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/TableV2_DisplayText_spec.ts
> +    _.entityExplorer.DragDropWidgetNVerify("tablewidgetv2", 650, 250);
import the relevant things from Objects Core like u have done for table, import entityExplorer/propPane and others on the same manner.
Eg: import {
  entityExplorer,
  agHelper,
  deployMode,
} from "../../../../support/Objects/ObjectsCore";

2023-06-19 04:42 UTC, NandanAnantharamu commented on app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/TableV2_DisplayText_spec.ts
> +    cy.wait(1000);
is this wait needed ? agHelper.Sleep() can be used if its really needed. since u r waiting for @updateLayout it should be fine and i suppose this hard wait is not needed

2023-06-19 04:43 UTC, NandanAnantharamu commented on app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/TableV2_DisplayText_spec.ts
> +    cy.get(table._searchInput).type("X");
please refer to relevant common helpers from agHelper.

2023-06-19 04:43 UTC, NandanAnantharamu commented on app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/TableV2_DisplayText_spec.ts
> +    cy.get(table._searchInput).clear();
please refer to relevant common helpers from agHelper.

2023-06-19 04:44 UTC, NandanAnantharamu commented on app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/TableV2_DisplayText_spec.ts
> +    cy.get(".t--property-control-columntype span.rc-select-selection-item span")
Dont use direct locators move to appropriate Helper Class, in this case it looks like propPane related one and hence move this to that support file and also look for relevant helper method to use invoke()

2023-06-19 04:45 UTC, NandanAnantharamu commented on app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/TableV2_DisplayText_spec.ts
> +    cy.get(".t--property-control-columntype span.rc-select-selection-item span")
same as above

2023-06-19 04:46 UTC, NandanAnantharamu commented on app/client/cypress/support/Pages/Table.ts
> +      ` ${this._columnHeaderDiv(columnName)} .header-menu .bp3-popover2-target`,
use agHelper method for cy.get().click() , there are many common helper methods that u can use

2023-06-19 04:49 UTC, NandanAnantharamu requested changes
added some review comments please address those.

2023-06-19 04:49 UTC, NandanAnantharamu commented on app/client/cypress/support/Pages/Table.ts
> +    cy.get(".bp3-menu")
direct locator cannot be used, create a locator and then use. There is a wait for 500ms is it needed ? use agHlper.sleep() if its really neeeded

2023-06-19 05:27 UTC, sbalaji1192 submitted a review, later dismissed
Please go ahead after addressing nandan's callouts.

2023-06-19 12:23 UTC, berzerkeer commented
/ok-to-test

2023-06-19 13:17 UTC, NandanAnantharamu commented
@Aishwarya-U-R i had reviewed the tests and @berzerkeer did resolve. Please cross check if you want.

2023-06-19 13:20 UTC, NandanAnantharamu submitted a review, later dismissed
LGTM

2023-06-19 13:39 UTC, Aishwarya-U-R reviewed
@berzerkeer - Good work with Cypress tests 👍 , over-all nits to be corrected but no merging till they are corrected :)

2023-06-19 13:39 UTC, Aishwarya-U-R commented on app/client/cypress/support/Pages/PropertyPane.ts
> +    `.t--property-control-${option} span.rc-select-selection-item span`;
Can we add new locators at end?

2023-06-19 13:39 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/TableV2_DisplayText_spec.ts
> +    entityExplorer.SelectEntityByName("Table1", "Widgets");
`DragDropWidgetNVerify` - will already open Widget's prop pane as done manually. Dont need this `SelectEntityByName` again.

2023-06-19 13:46 UTC, berzerkeer commented on app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/TableV2_DisplayText_spec.ts
> +    propPane.TogglePropertyState("clientsidesearch", "On");
Sorry, I don't get this one 😕

2023-06-19 13:47 UTC, berzerkeer commented
> @berzerkeer - Good work with Cypress tests 👍 , over-all nits to be corrected but no merging till they are corrected :)

Haha alright, will fix those and update :D

2023-06-20 05:52 UTC, berzerkeer commented on app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/TableV2_DisplayText_spec.ts
> +    agHelper.GetNClick(colSettings);
I am using the same selector in one other place within the same method.

2023-06-20 06:10 UTC, berzerkeer commented
/ok-to-test

2023-06-20 09:13 UTC, Aishwarya-U-R reviewed
Approving Cypress code changes 👍🏻

2023-06-20 09:26 UTC, berzerkeer commented
/build-deploy-preview env=release

2023-06-21 06:39 UTC, sbalaji1192 approved these changes

2023-06-21 06:39 UTC, Aishwarya-U-R approved these changes

2023-06-21 11:28 UTC, chandannkumar commented
Tested this PR and LGTM

2023-06-21 11:33 UTC, berzerkeer commented
/perf-test

2023-06-21 12:01 UTC, merged