fix: gsheet continuous re authorisation required issue fixed
appsmithorg/appsmith pull request #24273
Opened 2023-06-08 14:46 UTC by sneha122

## Description

After upgrade to v1.9.21, google sheets datasource would lose authentication after every couple of hours, causing all queries to fail. This PR fixes that issue. 

The issue started occurring after v1.9.21 because of the changes made as a part of multiple environments. Once the access token expires, we make an API call to google to refresh the access token. This API call does not return refresh token and hence we were setting refresh token as null. On subsequent refresh calls, this refresh token would be passed as null, hence causing failure in refresh. 

#### PR fixes following issue(s)
Fixes #24236 
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
#### Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video
>
>
#### Type of change
- Bug fix (non-breaking change which fixes an issue)
>
>
>
## Testing
>
#### How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Also list any relevant details for your test configuration.
> Delete anything that is not relevant
- [x] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-06-08 14:48 UTC, sumitsum requested changes

2023-06-08 14:48 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/AuthenticationServiceCEImpl.java
>                                  return datasourceStorageService
Can you please add a comment here explaining why we need to fetch the datasourceStorage value from DB again ?

2023-06-08 14:48 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/AuthenticationServiceCEImpl.java
> +                                authenticationResponse.setRefreshToken(integrationDTO.getAuthenticationResponse().getRefreshToken());
Can you please add a comment here why we need to explicitly set the refresh token ?

2023-06-08 14:49 UTC, sneha122 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/AuthenticationServiceCEImpl.java
>                                  return datasourceStorageService
yes will do that, thanks @sumitsum

2023-06-08 14:53 UTC, sneha122 commented
/build-deploy-preview

2023-06-08 14:58 UTC, sumitsum commented
/ok-to-test

2023-06-08 15:01 UTC, sneha122 commented
/ok-to-test

2023-06-08 15:20 UTC, sumitsum approved these changes

2023-06-09 03:38 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/AuthenticationServiceCEImpl.java
> +                                authenticationResponse.setRefreshToken(integrationDTO.getAuthenticationResponse().getRefreshToken());
Curious, did this line exist before and get removed along the way?

2023-06-09 03:39 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/AuthenticationServiceCEImpl.java
> +                                        .flatMap(ignore -> datasourceService.findByIdWithStorages(datasourceStorage.getDatasourceId())
Do we need to use the `withStorages` call here and then find storage again in the next line?

2023-06-09 04:20 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/AuthenticationServiceCEImpl.java
> +                                authenticationResponse.setRefreshToken(integrationDTO.getAuthenticationResponse().getRefreshToken());
Hi @nidhi-nair earlier we used to make `update` call instead of `save` call - APMU, the update call only updated the non null values, which made sure that even if the refresh token was set to null by the cloud services, it didn't get set as null in the API server DB.

2023-06-09 04:52 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/AuthenticationServiceCEImpl.java
> +                                        .flatMap(ignore -> datasourceService.findByIdWithStorages(datasourceStorage.getDatasourceId())
As discussed, will address this. I have created [this](https://github.com/appsmithorg/appsmith/issues/24282) issue to track it.

2023-06-09 05:54 UTC, sondermanish commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/AuthenticationServiceCEImpl.java
> +                                        .flatMap(ignore -> datasourceService.findByIdWithStorages(datasourceStorage.getDatasourceId())
Since this is small change, I'll take this up in My cleanup PR, given it's merged by then

2023-06-09 06:48 UTC, merged