test: uncommented the skipped tests
appsmithorg/appsmith pull request #24447
Opened 2023-06-14 06:46 UTC by NandanAnantharamu

Fixing one click binding flaky tests

2023-06-14 06:46 UTC, NandanAnantharamu commented
/ok-to-test

2023-06-14 07:01 UTC, NandanAnantharamu commented
/ok-to-test

2023-06-15 06:11 UTC, NandanAnantharamu commented
/ok-to-test

2023-06-15 09:19 UTC, NandanAnantharamu commented
/ok-to-test

2023-06-15 09:21 UTC, NandanAnantharamu commented
/ok-to-test

2023-06-15 09:54 UTC, NandanAnantharamu commented
/ok-to-test

2023-06-16 07:51 UTC, sbalaji1192 approved these changes

2023-06-16 07:53 UTC, sbalaji1192 approved these changes

2023-06-16 09:11 UTC, Aishwarya-U-R requested changes
I'm seeing mongo spec failed in [recent run](https://cloud.cypress.io/projects/eyxvp8/runs/36308/test-results?actions=%5B%5D&browsers=%5B%5D&groups=%5B%5D&isFlaky=%5B%5D&modificationDateRange=%7B%22startDate%22%3A%221970-01-01%22%2C%22endDate%22%3A%222038-01-19%22%7D&orderBy=EXECUTION_ORDER&oses=%5B%5D&specs=%5B%5D&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D&testingTypesEnum=%5B%5D)  again. 
Lets give a sturdy fix & then merge.

2023-06-16 09:11 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ClientSide/OneClickBinding/TableWidget/mongoDB_spec.ts
> +    _.entityExplorer.DragDropWidgetNVerify(_.draggableWidgets.TABLE, 800, 600);
Import only needed objects from ObjectsCore.

2023-06-16 09:11 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ClientSide/OneClickBinding/TableWidget/mongoDB_spec.ts
> +    _.agHelper.Sleep();
Can it be `agHelper.Sleep(2000);`?

2023-06-16 09:11 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ClientSide/OneClickBinding/TableWidget/postgres_spec.ts
> +    _.entityExplorer.DragDropWidgetNVerify(_.draggableWidgets.TABLE, 800, 600);
Do we really need to drag table in these co-ordinates? Look at smaller values. We are planning to work on some resolution changes for CI, & this may fail.

2023-07-04 16:39 UTC, closed without merging