feat: Flagsmith Integration
appsmithorg/appsmith pull request #24472
Opened 2023-06-14 20:12 UTC by NilanshBansal

## Description
> This PR integrates Flagsmith feature flagging into the Appsmith codebase
> It also sets some default traits such as instance_id, tenant_id and email/hashed email to the new and existing users

#### PR fixes following issue(s)
Fixes #24037 

#### Type of change
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Testing
>
#### How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Also list any relevant details for your test configuration.
> Delete anything that is not relevant
- [ ] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-06-15 07:35 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/authentication/handlers/ce/AuthenticationSuccessHandlerCE.java
> +                    featureFlagTraits.add(addTraitKeyValueToTraitObject(identifier, "email", user.getEmail()));
What happens if a single user email exists in multiple tenants or instances?

2023-06-15 07:36 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/featureflags/FeatureFlagScheduledTaskImpl.java
> +            initialDelay = 2 * 60 * 60 * 1000 /* two hours */,
We should likely reduce the initialDelay value here. Or features won't work for the first two hours an instance is up

2023-06-15 07:37 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/authentication/handlers/ce/AuthenticationSuccessHandlerCE.java
> +    private Mono<Void> addDefaultUserTraits(User user){
Looks like we're missing tests for this change

2023-06-15 07:50 UTC, NilanshBansal commented on app/server/appsmith-server/src/main/java/com/appsmith/server/featureflags/FeatureFlagScheduledTaskImpl.java
> +            initialDelay = 2 * 60 * 60 * 1000 /* two hours */,
What should be an ideal number here according to you?

2023-06-15 07:52 UTC, NilanshBansal commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/FeatureFlagServiceImpl.java
> +                // TODO: Better error handling
Not required, I'll remove this

2023-06-15 07:56 UTC, NilanshBansal commented on app/server/appsmith-server/src/main/java/com/appsmith/server/authentication/handlers/ce/AuthenticationSuccessHandlerCE.java
> +                    featureFlagTraits.add(addTraitKeyValueToTraitObject(identifier, "email", user.getEmail()));
Until we fix the mixpanel identifier and move it as a combination of instanceId-tenantId-userId, the data for the same email will be grouped together and the flags remain generic for that user. 

Ref: https://github.com/appsmithorg/cloud-services/pull/973/files#r1230584618

cc: @hetunandu @ginilpg @kocharrahul7

2023-06-15 09:53 UTC, NilanshBansal commented
/build-deploy-preview

2023-06-15 18:36 UTC, NilanshBansal commented
/ok-to-test

2023-06-15 18:36 UTC, NilanshBansal commented
/build-deploy-preview

2023-06-19 05:40 UTC, jsartisan requested changes

2023-06-19 05:40 UTC, jsartisan commented on app/client/src/ce/api/UserApi.tsx
> +  static fetchFeatureFlags(): AxiosPromise<ApiResponse<FeatureFlags>> {
The types here can be improved. We should ideally avoid adding types for things that should be automatically inferred by typescript.

**Suggested Solution**:
1. Removed the type for return value and pass a value for the geneic ( that will be used in Api.tsx )
```ts
// app/client/src/api/UserApi.tsx
 static fetchFeatureFlags()  {
  	return Api.get<FeatureFlags>(UserApi.featureFlagsURL);
 }
```

2. now, add a generic TData that will be consumed the axios library  in the `get` function of `Api.tsx`
```ts
 static get<TData = {}>(url: string, queryParams?: any, config: AxiosRequestConfig = {}) {
    return axiosInstance.get<ApiResponse<TData>>(url + convertObjectToQueryParams(queryParams), {
      ...apiRequestConfig,
      ...config,
    });
  }
  ```
  
  With this change, the type for the return value of fetchFeatureFlags will be
  ```Promise<AxiosResponse<ApiResponse<FeatureFlags>, any>>```
  No need to pass the type explicitly.
  
  **Note: Don't make this change as it will be break types at all other places of use of `get` API function. This was just for FYI.**

2023-06-19 05:40 UTC, jsartisan commented on app/client/src/ce/entities/FeatureFlag.ts
> +export enum FeatureFlag {
Enums are generally avoided as they can bring weird/dangerous behavior. Use POJOs instead ( Plain old javascript object )
Here is the link of the thread that discusses it: https://theappsmith.slack.com/archives/CGBPVEJ5C/p1686806755300739?thread_ts=1686750585.115319&cid=CGBPVEJ5C

**Suggested Solution**
```ts
const FEATURE_FLAG = {
  TEST_FLAG: "TEST_FLAG",
  DATASOURCE_ENVIRONMENTS: "DATASOURCE_ENVIRONMENTS",
  AUTO_LAYOUT: "AUTO_LAYOUT",
  ask_ai: "ask_ai",
  APP_NAVIGATION_LOGO_UPLOAD: "APP_NAVIGATION_LOGO_UPLOAD",
  ask_ai_sql: "ask_ai_sql",
  ask_ai_js: "ask_ai_js",
} as const;

export type FeatureFlags = Record<keyof typeof FEATURE_FLAG, boolean>;
```

2023-06-19 05:40 UTC, jsartisan commented on app/client/src/ce/entities/FeatureFlag.ts
> +export const DefaultFeatureFlagValue: FeatureFlags = {
shouldn't the name be: `defaultFeatureFlagValue` or `DEFAULT_FEATURE_FLAG_VALUE`?

2023-06-22 10:32 UTC, dhruvikn approved these changes

2023-06-23 05:45 UTC, jsartisan approved these changes

2023-06-23 07:24 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/authentication/handlers/ce/AuthenticationSuccessHandlerCE.java
> +    private String hash(String value) {
Nit: Can we move this utility to a separate class?

2023-06-23 07:26 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/authentication/handlers/ce/AuthenticationSuccessHandlerCE.java
> +    private String getUserIdentifier(User user){
Possibly this method as well?

2023-06-23 07:27 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/FeatureFlagServiceCEImpl.java
> +    private String getUserIdentifier(User user){
Please write tests for both these cases

2023-06-24 18:46 UTC, NilanshBansal commented
/ok-to-test

2023-06-25 06:22 UTC, nidhi-nair approved these changes

2023-06-25 06:33 UTC, NilanshBansal commented
@nidhi-nair 3 tests for flagsmith are failing in this PR (ok-to-test) because the cloud services code is updated and the tests point to the cloud services release. 
Can you pls first review the cloud services PR [here](https://github.com/appsmithorg/cloud-services/pull/973) 
Once that is merged to release, will re-run the tests for this PR.

2023-06-27 08:15 UTC, NilanshBansal commented
/ok-to-test

2023-06-27 10:45 UTC, merged