chore: [one click binding] convert select component to menu component on property control
appsmithorg/appsmith pull request #24517
Opened 2023-06-16 06:26 UTC by sbalaji1192

#### PR fixes following issue(s)
Fixes [# (issue number)](https://github.com/appsmithorg/appsmith/issues/24404)

#### Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video
>
>
#### Type of change
> Please delete options that are not relevant.
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
## Testing
>
#### How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Also list any relevant details for your test configuration.
> Delete anything that is not relevant
- [ ] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-06-16 06:38 UTC, sbalaji1192 commented
/ok-to-test

2023-06-16 06:39 UTC, sbalaji1192 commented
/build-deploy-preview skipTests=true

2023-06-16 09:22 UTC, sbalaji1192 commented
/ok-to-test

2023-06-16 09:22 UTC, sbalaji1192 commented
/build-deploy-preview skipTests=true

2023-06-16 12:59 UTC, chandannkumar commented
Observations @sbalaji1192 
- Search bar shows two "x" symbols (clear) instead of only one
![image.png](https://images.zenhubusercontent.com/61e65341d503e6aafa5df216/7385ff40-ce61-46ef-a00b-9a6a26529606)

- Search bar does not anything such as "No Results" when searched input is wrong
![image.png](https://images.zenhubusercontent.com/61e65341d503e6aafa5df216/ae374033-3775-41a6-8b98-ba09e255d968)

2023-06-19 06:28 UTC, sbalaji1192 commented
/ok-to-test

2023-06-19 06:28 UTC, sbalaji1192 commented
/build-deploy-preview skipTests=true

2023-06-19 06:32 UTC, sbalaji1192 commented
@chandannkumar the extra cross has been removed. Regarding the no results found, we are always showing the connect new data source link now. So you will see that link when you type an invalid search text. And we have also removed the insert binding as per @dilippitchika suggestion.

2023-06-19 11:12 UTC, chandannkumar commented
Halting this PR for now because of some backend issue https://theappsmith.slack.com/archives/CGBPVEJ5C/p1687167727785369

2023-06-19 12:35 UTC, chandannkumar commented
Tested this PR and LGTM
- Verified all callouts

2023-06-20 05:52 UTC, sbalaji1192 commented
/ok-to-test

2023-06-20 09:54 UTC, sbalaji1192 commented
/ok-to-test

2023-06-21 05:01 UTC, sbalaji1192 commented
/ok-to-test

2023-06-21 07:54 UTC, sbalaji1192 commented
/ok-to-test

2023-06-21 08:44 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ClientSide/OneClickBinding/spec_utility.ts
> +import { __asyncGenerator } from "tslib";
Is this import needed?

2023-06-21 08:44 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ClientSide/OneClickBinding/PropertyControl_spec.ts
> +  it("should check that load more options and search", () => {
Index `it` blocks.

2023-06-21 08:44 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ClientSide/OneClickBinding/PropertyControl_spec.ts
> +
This section of code is also duplicated in spec_utility.ts. Can we have one function & use it at both places?

2023-06-21 08:44 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ClientSide/OneClickBinding/PropertyControl_spec.ts
> +    cy.get(oneClickBindingLocator.datasourceQuerySelector()).then(($ele) => {
Use agHelper.GetElement() instead of direct cy.get or cy.xpaths in specs. So in future if the locators are changed - the spec will still work without having to change.

2023-06-21 08:47 UTC, vsvamsi1 requested changes

2023-06-21 08:47 UTC, vsvamsi1 commented on app/client/src/components/editorComponents/WidgetQueryGeneratorForm/CommonControls/DatasourceDropdown/index.tsx
> +          <div
Can you provide a class instead of inline styling it.

2023-06-21 08:47 UTC, vsvamsi1 commented on app/client/src/components/editorComponents/WidgetQueryGeneratorForm/CommonControls/DatasourceDropdown/index.tsx
> +            })}
I see scope extract the options and load more generation code into a separate function. The code is quiet similar for queryOptions, datasourceOptions and otherOptions. We can extract jsx code for the section title, options geneation and load more.

2023-06-21 08:47 UTC, vsvamsi1 commented on app/client/src/components/editorComponents/WidgetQueryGeneratorForm/CommonControls/DatasourceDropdown/useDatasource.tsx
> +  );
Can you use .includes instead 
```
 option.label.toLowerCase().includes(searchText.toLowerCase()) 
```

2023-06-21 09:48 UTC, sbalaji1192 commented on app/client/src/components/editorComponents/WidgetQueryGeneratorForm/CommonControls/DatasourceDropdown/index.tsx
> +            })}
I have extracted the load more into a separate component. The rest of the components were already there, we just migrated to diff component. Lets do this on a diff PR.

2023-06-21 10:03 UTC, sbalaji1192 commented
/ok-to-test

2023-06-21 10:06 UTC, sbalaji1192 commented
/build-deploy-preview skipTests=true

2023-06-21 10:50 UTC, vsvamsi1 requested changes

2023-06-21 10:50 UTC, vsvamsi1 commented on app/client/src/components/editorComponents/WidgetQueryGeneratorForm/CommonControls/DatasourceDropdown/index.tsx
> +      </Menu>
Can you refer to this code. If you can can extract further code that would be great.
```
import React, { memo, useCallback, useEffect, useState } from "react";
import { Bold, ErrorMessage, SelectWrapper } from "../../styles";
import { useDatasource } from "./useDatasource";
import {
  Icon,
  Menu,
  MenuTrigger,
  MenuContent,
  MenuGroupName,
  Text,
  MenuItem,
  MenuSeparator,
  SearchInput,
} from "design-system";
import { DropdownOption } from "./DropdownOption";
import styled from "styled-components";
import type { DropdownOptionType } from "../../types";
import { DATASOURCE_DROPDOWN_SECTIONS } from "../../constants";

function DropdownSection({
  getDropdownOptionProps,
  onSourceClose,
  options,
  sectionTitle,
  setOpen,
  setShowMoreOptions,
  showMoreOptions,
  testAttributes,
}) {
  return (
    <>
      {!!options.length && (
        <StyledMenuGroupName data-testId={testAttributes.title}>
          <Text kind="heading-xs">{sectionTitle}</Text>
        </StyledMenuGroupName>
      )}

      {options
        .slice(
          0,
          showMoreOptions ? options.length : DEFAULT_ITEM_COUNTS_TO_SHOW,
        )
        .map((option) => {
          return (
            <MenuItem
              data-testId={testAttributes.option}
              key={option.id}
              onSelect={() => {
                option.onSelect(option.value, option);
                onSourceClose();
                setOpen(false);
              }}
            >
              <DropdownOption {...getDropdownOptionProps(option)} />
            </MenuItem>
          );
        })}

      {options.length > DEFAULT_ITEM_COUNTS_TO_SHOW && !showMoreOptions && (
        <MenuItem>
          <div
            data-testId={testAttributes.loadMore}
            onMouseDown={(e) => {
              e?.stopPropagation();
            }}
            onMouseUp={(e) => {
              e?.stopPropagation();
              setShowMoreOptions(true);
            }}
          >
            <StyledLoadMore
              label={`Load ${
                options.length - DEFAULT_ITEM_COUNTS_TO_SHOW
              } more`}
              leftIcon={<Icon name="context-menu" size="md" />}
            />
          </div>
        </MenuItem>
      )}
    </>
  );
}
const StyledButton = styled.div<{ isDisabled: boolean; isValid: boolean }>`
  width: 100%;
  border: 1px solid
    var(
      ${(props) =>
        props.isValid ? "--ads-v2-color-border" : "--ads-v2-color-fg-error"}
    );
  border-radius: var(--ads-v2-border-radius);
  box-sizing: border-box;
  padding: 7px 8px;
  display: flex;
  justify-content: space-between;
  align-items: center;
  cursor: ${(props) => (props.isDisabled ? "default" : "pointer")};
  ${(props) => (props.isDisabled ? "pointer-events: none;" : "")}

  &:hover {
    border-color: var(--ads-v2-color-gray-400);
  }

  &:active,
  &:focus {
    border-color: var(--ads-v2-color-gray-600);
  }

  & .selected-item {
    width: calc(100% - 16px);
  }
`;

const StyledMenuSeparator = styled(MenuSeparator)`
  margin: 10px 0px;
`;

const StyledInput = styled(SearchInput)`
  padding: 10px 8px;
`;

const StyledMenuGroupName = styled(MenuGroupName)`
  margin-bottom: 5px;
`;

const StyledLoadMore = styled(DropdownOption)`
  color: var(--ads-color-black-500);
`;

const DEFAULT_ITEM_COUNTS_TO_SHOW = 4;

function DatasourceDropdown() {
  const [searchText, setSearchText] = useState("");

  const {
    datasourceOptions,
    disabled,
    error,
    isSourceOpen,
    onSourceClose,
    otherOptions,
    queryOptions,
    selected,
  } = useDatasource(searchText);

  const [open, setOpen] = useState(false);

  useEffect(() => {
    setOpen(isSourceOpen);
  }, [isSourceOpen]);

  const [showMoreQueries, setShowMoreQueries] = useState(false);

  const [showMoreDataSources, setShowMoreDataSources] = useState(false);

  const onChange = useCallback((value: string) => setSearchText(value), []);

  return (
    <SelectWrapper data-testId="t--one-click-binding-datasource-selector">
      <Menu
        onOpenChange={(open: boolean) => {
          setOpen(open);
          onSourceClose();
        }}
        open={open}
      >
        <MenuTrigger>
          <StyledButton
            data-testId="t--one-click-binding-datasource-trigger"
            isDisabled={disabled}
            isValid={!error}
          >
            <div className="selected-item">{selected}</div>
            <div>
              <Icon name="arrow-down-s-line" size="md" />
            </div>
          </StyledButton>
        </MenuTrigger>
        <MenuContent align="end" style={{ width: "350px", maxWidth: "350px" }}>
          <div
            onKeyDown={(e) => {
              // This is to prevent the Menu component to take focus away from the input
              // https://github.com/radix-ui/primitives/issues/1175
              e.stopPropagation();
            }}
          >
            <StyledInput
              autoFocus
              data-testId="t--one-click-binding-datasource--search"
              onChange={onChange}
              size="md"
              type="text"
              value={searchText}
            />

            <DropdownSection
              getDropdownOptionProps={({ icon, label }) => ({
                label,
                leftIcon: icon,
              })}
              onSourceClose={onSourceClose}
              options={queryOptions}
              sectionTitle={DATASOURCE_DROPDOWN_SECTIONS.CONNECT_TO_QUERY}
              setOpen={setOpen}
              setShowMoreOptions={setShowMoreQueries}
              showMoreOptions={showMoreQueries}
              testAttributes={{
                title:
                  "t--one-click-binding-datasource-selector--bind-to-query",
                option: "t--one-click-binding-datasource-selector--query",
                loadMore: "t--one-click-binding-datasource--load-more",
              }}
            />

            {!!queryOptions.length &&
              (!!datasourceOptions.length || !!otherOptions.length) && (
                <StyledMenuSeparator />
              )}

            <DropdownSection
              getDropdownOptionProps={(option) => ({
                label: (
                  <span>
                    New from {option.data.isSample ? "sample " : ""}
                    <Bold>{option.label?.replace("sample ", "")}</Bold>
                  </span>
                ),
                leftIcon: option.icon,
                rightIcon: <Icon name="add-box-line" size="md" />,
              })}
              onSourceClose={onSourceClose}
              options={datasourceOptions}
              sectionTitle={
                DATASOURCE_DROPDOWN_SECTIONS.CHOOSE_DATASOURCE_TO_CONNECT
              }
              setOpen={setOpen}
              setShowMoreOptions={setShowMoreDataSources}
              showMoreOptions={showMoreDataSources}
              testAttributes={{
                title:
                  "t--one-click-binding-datasource-selector--generate-a-query",
                option: "t--one-click-binding-datasource-selector--datasource",
                loadMore: "t--one-click-binding-datasource--load-more",
              }}
            />

            {!!datasourceOptions.length && !!otherOptions.length && (
              <StyledMenuSeparator />
            )}

            {!!otherOptions.length && (
              <StyledMenuGroupName data-testid="t--one-click-binding-datasource-selector--other-actions">
                <Text kind="heading-xs">
                  {DATASOURCE_DROPDOWN_SECTIONS.OTHER_ACTIONS}
                </Text>
              </StyledMenuGroupName>
            )}

            {otherOptions.map((option: DropdownOptionType) => {
              return (
                <MenuItem
                  data-testId="t--one-click-binding-datasource-selector--other-action"
                  key={option.id}
                  onSelect={() => {
                    option.onSelect?.(option.value || "", option);
                    onSour [...]

2023-06-21 13:51 UTC, sbalaji1192 commented on app/client/src/components/editorComponents/WidgetQueryGeneratorForm/CommonControls/DatasourceDropdown/index.tsx
> +      </Menu>
The code you refer to was already there. I have changed it from using select component to menu component. Lets merge this PR and will make these changes in a different pr.

2023-06-21 14:15 UTC, vsvamsi1 commented on app/client/src/components/editorComponents/WidgetQueryGeneratorForm/CommonControls/DatasourceDropdown/index.tsx
> +      </Menu>
Sure

2023-06-21 14:15 UTC, vsvamsi1 approved these changes

2023-06-21 14:35 UTC, Aishwarya-U-R reviewed
Approving Cypress changes!

2023-06-21 14:35 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ClientSide/OneClickBinding/PropertyControl_spec.ts
> +      });
nit: `agHelper.GetElementLength` can also be used.

2023-06-22 05:02 UTC, albinAppsmith commented on app/client/src/components/editorComponents/WidgetQueryGeneratorForm/CommonControls/DatasourceDropdown/DropdownOption.tsx
> +  color: var(--ads-color-black-500);
We should not use black shades. Is this requirement came from design?

2023-06-22 05:04 UTC, sbalaji1192 commented on app/client/src/components/editorComponents/WidgetQueryGeneratorForm/CommonControls/DatasourceDropdown/DropdownOption.tsx
> +  color: var(--ads-color-black-500);
<img width="355" alt="Screenshot 2023-06-22 at 10 33 29 AM" src="https://github.com/appsmithorg/appsmith/assets/5328605/f0976890-476c-4b29-bcc8-ac0ade2b6c97">
Yeah. we are using a grey shade for the load more option

2023-06-22 05:05 UTC, albinAppsmith commented on app/client/src/components/editorComponents/WidgetQueryGeneratorForm/CommonControls/DatasourceDropdown/DropdownOption.tsx
> +  color: var(--ads-color-black-500);
This is an old gray. Designer should port this to the new gray.

2023-06-22 05:07 UTC, albinAppsmith commented on app/client/src/components/editorComponents/WidgetQueryGeneratorForm/CommonControls/DatasourceDropdown/index.tsx
> +const StyledButton = styled.div<{ isDisabled: boolean; isValid: boolean }>`
Why are we writing custom button component here?

2023-06-22 05:10 UTC, albinAppsmith commented on app/client/src/components/editorComponents/WidgetQueryGeneratorForm/CommonControls/DatasourceDropdown/index.tsx
> +  padding: 10px 8px;
We should not alter the padding of components.

2023-06-22 05:12 UTC, albinAppsmith commented on app/client/src/components/editorComponents/WidgetQueryGeneratorForm/CommonControls/DatasourceDropdown/index.tsx
> +  margin-bottom: 5px;
Is this because the design is having a margin?

2023-06-22 05:16 UTC, albinAppsmith commented on app/client/src/components/editorComponents/WidgetQueryGeneratorForm/styles.tsx
> +  color: var(--ads-color-black-500);
This is a wrong color. Please use `--ads-v2-color-fg-subtle`. DS pod will soon publish a doc related to this color usage.

2023-06-22 08:05 UTC, sbalaji1192 commented on app/client/src/components/editorComponents/WidgetQueryGeneratorForm/CommonControls/DatasourceDropdown/index.tsx
> +const StyledButton = styled.div<{ isDisabled: boolean; isValid: boolean }>`
Renamed this to StyledDropdownTrigger.

2023-06-22 08:13 UTC, albinAppsmith approved these changes

2023-06-22 08:14 UTC, sbalaji1192 commented
/ok-to-test

2023-06-22 08:14 UTC, sbalaji1192 commented
/build-deploy-preview skipTests=true

2023-06-22 10:41 UTC, merged