feat: MySQL & MSSQL query generator
appsmithorg/appsmith pull request #24516
Opened 2023-06-16 06:21 UTC by berzerkeer

…ne-click-mssql-mysql> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.
>
## Description
> Add a TL;DR when description is extra long (helps content team)
>
> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change
>
> Links to Notion, Figma or any other documents that might be relevant to the PR
>
>
#### PR fixes following issue(s)
Fixes # (issue number)
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
#### Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video
>
>
#### Type of change
> Please delete options that are not relevant.
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
## Testing
>
#### How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Also list any relevant details for your test configuration.
> Delete anything that is not relevant
- [ ] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-06-20 07:35 UTC, berzerkeer commented
Note : As of now the `mssql_spec.ts` for one click binding fails in cypress because of duplicate key issues on local, even when I delete stacks and restart servers. So running it in CI here.

Also as of now I believe a lot of these cypress JS commands are not converted to TS yet, if its already done. Please let me know , I will update the tests to use TS methods in a different follow up PR. Since that should be done for other one click binding specs aswell. 

cc: @Aishwarya-U-R  @NandanAnantharamu

2023-06-20 07:36 UTC, berzerkeer commented
/ok-to-test

2023-06-20 08:49 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ClientSide/OneClickBinding/TableWidget/mssql_spec.ts
> +import * as _ from "../../../../../support/Objects/ObjectsCore";
Import only required objects from ObjectsCore.

2023-06-20 08:49 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ClientSide/OneClickBinding/TableWidget/mssql_spec.ts
> +    _.dataSources.CreateDataSource("MsSql", true, true, "fakeapi");
Refer to already existing way of using MsSQL ds & update this.

2023-06-20 08:49 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ClientSide/OneClickBinding/TableWidget/mssql_spec.ts
> +  it("should check that queries are created and bound to table widget properly", () => {
Index the `it` blocks.

2023-06-20 08:49 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ClientSide/OneClickBinding/TableWidget/mssql_spec.ts
> +    (cy as any).enterTableCellValue(3, 0, " 10");
Use Ts helper method `EditTableCell` similar to other OneClickBinding folder specs that is fixed now.

2023-06-20 08:49 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ClientSide/OneClickBinding/TableWidget/mssql_spec.ts
> +    (cy as any).wait(1000);
Use` agHelper.Sleep();`

2023-06-20 08:49 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ClientSide/OneClickBinding/TableWidget/mssql_spec.ts
> +    (cy as any).enterTableCellValue(3, 0, " 10");
Same comments for below spec too.

2023-06-20 15:56 UTC, berzerkeer commented
/ok-to-test

2023-06-21 08:00 UTC, berzerkeer commented
/ok-to-test

2023-06-21 09:30 UTC, berzerkeer commented
/ok-to-test

2023-06-21 09:30 UTC, berzerkeer commented
/build-deploy-preview env=release

2023-06-21 09:32 UTC, berzerkeer commented
@chandannkumar can you pick this one up next ? Thanks !

2023-06-22 09:42 UTC, berzerkeer commented
/ok-to-test

2023-06-22 12:13 UTC, Aishwarya-U-R requested changes

2023-06-22 12:13 UTC, Aishwarya-U-R commented on app/client/cypress/support/Pages/DataSources.ts
> +    databaseName?: string,
Is this needed?

2023-06-22 12:13 UTC, Aishwarya-U-R commented on app/client/cypress/support/Pages/AggregateHelper.ts
> +      .clear({ force: true })
Can you please get force as a parameter & use here? Not all will need force: true

2023-06-22 12:13 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Sanity/Datasources/MsSQL_Basic_Spec.ts
> +    entityExplorer.NavigateToSwitcher("Widgets");
Drag dropping table will automatically open Table's properties. Why we need these 2 lines?

2023-06-22 12:13 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Sanity/Datasources/MsSQL_Basic_Spec.ts
> +    entityExplorer.SelectEntityByName("Table1", "Widgets");
Also not needed.

2023-06-22 12:13 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Sanity/Datasources/MsSQL_Basic_Spec.ts
> +    // (cy as any).editTableCell(1, 0);
Can this comment be removed? As this method is not used anyways.

2023-06-22 12:39 UTC, sbalaji1192 commented on app/client/src/WidgetQueryGenerators/types.ts
> +  pluginSpecifiedTemplates: Array<object>;
can we reuse ActionConfigurationPostgreSQL?

2023-06-22 12:55 UTC, berzerkeer commented
/ok-to-test

2023-06-22 13:35 UTC, berzerkeer commented
/ok-to-test

2023-06-22 13:45 UTC, berzerkeer commented
/ok-to-test

2023-06-22 13:48 UTC, Aishwarya-U-R commented on app/client/cypress/support/Pages/AggregateHelper.ts
> +      .clear({ force })
Wrong syntax , it should be { force: force }. If you are sending false again here - why is this even needed?

2023-06-22 13:48 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ClientSide/OneClickBinding/TableWidget/mysql_spec.ts
> +    dataSources.CreateDataSource("MySql");
Is this tested after removing this  `entityExplorer.NavigateToSwitcher("Explorer");`? I think this is needed. Cross-check again.

2023-06-22 13:49 UTC, berzerkeer commented on app/client/cypress/support/Pages/AggregateHelper.ts
> +      .clear({ force })
Oh its not wrong syntax, in ES6 , if the key and value variable name is same ,  i.e `{ force : force }` doing `{force} is enough.

2023-06-22 13:53 UTC, Aishwarya-U-R reviewed
Approving Cypress changes!

2023-06-22 13:53 UTC, berzerkeer commented on app/client/cypress/e2e/Regression/ClientSide/OneClickBinding/TableWidget/mysql_spec.ts
> +    dataSources.CreateDataSource("MySql");
Yup tested it passed.

2023-06-22 13:54 UTC, berzerkeer commented
> Approving Cypress changes!

Thank you 💯

2023-06-22 14:47 UTC, berzerkeer commented
/ok-to-test

2023-06-23 05:36 UTC, sbalaji1192 commented on app/client/src/WidgetQueryGenerators/types.ts
> +export type ActionConfigurationMySQL = ActionConfigurationPostgreSQL;
we can rename ActionConfigurationPostgreSQL to ActionConfigurationSQL and use it.

2023-06-23 05:52 UTC, berzerkeer commented on app/client/src/WidgetQueryGenerators/types.ts
> +export type ActionConfigurationMySQL = ActionConfigurationPostgreSQL;
done

2023-06-23 06:10 UTC, sbalaji1192 submitted a review, later dismissed

2023-06-27 07:29 UTC, sondermanish commented
/build-deploy-preview skip-tests=true

2023-06-28 08:07 UTC, chandannkumar commented
Observation @berzerkeer 
- Able to Insert, update in MySQL even with Read-only access in DB
https://www.loom.com/share/5547aaff75b6453885e66764549b7d87?sid=2ded1bf7-1d10-4197-bd3e-735b706a07d5

2023-06-28 08:09 UTC, berzerkeer commented
> Observation @berzerkeer
> 
> * Able to Insert, update in MySQL even with Read-only access in DB
>   [loom.com/share/5547aaff75b6453885e66764549b7d87?sid=2ded1bf7-1d10-4197-bd3e-735b706a07d5](https://www.loom.com/share/5547aaff75b6453885e66764549b7d87?sid=2ded1bf7-1d10-4197-bd3e-735b706a07d5)

Does this happen with other Datasources too ? like postgres and Mongo ?

2023-06-28 08:12 UTC, Aishwarya-U-R approved these changes

2023-06-28 08:15 UTC, chandannkumar commented
> Does this happen with other Datasources too ? like postgres and Mongo ?

For eg in Postgres when only Read access is configured, we can observe there is no editable field checked and no insert, update query created automatically after one click binding

2023-06-28 08:25 UTC, berzerkeer commented
> > Does this happen with other Datasources too ? like postgres and Mongo ?
> 
> For eg in Postgres when only Read access is configured, we can observe there is no editable field checked and no insert, update query created automatically after one click binding

No, it does get created with postgres. 

Also I created a `READ_ONLY` Mysql datasource, and did `Generate page from CRUD` with that datasource. But I can still Update and Insert rows to that `READ_ONLY` datasource. 

Attached a video for reference. 
https://vdqm24wed6.vmaker.com/record/OLsIPiKIyAIl02jq

2023-06-28 08:58 UTC, chandannkumar commented
Agree @berzerkeer, Above callout is an existing behavior.

QQ - Should we not restrict or inform users at the first place saying Datasource has only Read access and hence insert, update cannot be done
cc: @dilippitchika @sbalaji1192

2023-06-29 06:40 UTC, laveena-en commented
Verified MSSQL for one-click binding. 
Apart from the existing issues stated [here](https://theappsmith.slack.com/archives/C02JV8G1MP0/p1687957379515339?thread_ts=1687526688.260129&cid=C02JV8G1MP0), this PR LGTM. (Props bound to `Total record count query would fail)

cc: @sbalaji1192 @chandannkumar

2023-06-29 10:28 UTC, sbalaji1192 commented
/ok-to-test

2023-07-03 03:14 UTC, berzerkeer commented
/ok-to-test

2023-07-03 03:33 UTC, berzerkeer commented
/ok-to-test

2023-07-03 04:43 UTC, berzerkeer commented
/ok-to-test

2023-07-03 07:16 UTC, berzerkeer commented
/ok-to-test

2023-07-03 12:50 UTC, berzerkeer commented
/ok-to-test

2023-07-03 16:48 UTC, berzerkeer commented
/ok-to-test

2023-07-03 18:01 UTC, berzerkeer commented
/ok-to-test

2023-07-04 07:57 UTC, berzerkeer commented
/ok-to-test sha=9de3e59

2023-07-04 09:41 UTC, berzerkeer commented
/build-deploy-preview env=release

2023-07-04 15:43 UTC, Aishwarya-U-R commented
/build-deploy-preview env=release

2023-07-05 08:49 UTC, berzerkeer commented
/build-deploy-preview

2023-07-05 10:44 UTC, berzerkeer commented
/ok-to-test

2023-07-05 13:39 UTC, Aishwarya-U-R approved these changes

2023-07-06 07:18 UTC, berzerkeer commented
/ok-to-test

2023-07-06 07:41 UTC, chandannkumar commented
Testing is done for Snowflake DB support with One click binding and it's LGTM

2023-07-06 08:20 UTC, merged

2023-07-06 09:56 UTC, berzerkeer commented
Created a [issue](https://github.com/appsmithorg/appsmith/issues/25149) to handle cypress failures.