fix: puts navbar functionality behind feature flag
appsmithorg/appsmith pull request #24561
Opened 2023-06-16 08:42 UTC by rahulbarwal

## Description
This PR puts shownavbar functionality behind a feature flag.

* adds analytics events to track apps that use this flag.
* updates relevant specs.

#### PR fixes following issue(s)
Fixes #24515

#### Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video
>
>
#### Type of change

- Bug fix (non-breaking change which fixes an issue)
## Testing
>
#### How Has This Been Tested?
- [x] Cypress
>
>
#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-06-16 08:45 UTC, rahulbarwal commented
/build-deploy-preview

2023-06-16 09:29 UTC, rahulbarwal commented
Hey @shwetha-ramesh, 
This needs to be tested from 2 user accounts:
1. Appsmith mail id
2. Any other mail ID

DP URL : https://ce-24561.dp.appsmith.com/
Steps: 
1. open any app
2. Go to app settings
3. Open share and embed settings
4. Make application public(if not already)
5. toggle `show navigation bar`
      a. Appsmith mail id : it should add and remove 'navbar=true` from snippet URL
                1. when show nav bar is set : https://ce-24561.dp.appsmith.com/app/my-first-application/page1-648c29c5ac2df1623cf16dbc?embed=true&navbar=true
                2. when show nav bar is unset : https://ce-24561.dp.appsmith.com/app/my-first-application/page1-648c29c5ac2df1623cf16dbc?embed=true
      b. Any other mail id : it should add and remove 'embed=true` from snippet URL
                1. when show nav bar is set : https://ce-24561.dp.appsmith.com/app/my-first-application/page1-648c29c5ac2df1623cf16dbc
                2. when show nav bar is unset : https://ce-24561.dp.appsmith.com/app/my-first-application/page1-648c29c5ac2df1623cf16dbc?embed=true

2023-06-16 09:33 UTC, akash-codemonk commented on app/client/src/pages/AppViewer/Navigation/index.tsx
> +  }
Inside a useEffect maybe? This will get called on every render.

2023-06-16 09:36 UTC, rahulbarwal commented on app/client/src/pages/AppViewer/Navigation/index.tsx
> +  }
Makes sense. added.

2023-06-16 14:15 UTC, rahulbarwal commented
/ok-to-test

2023-06-16 17:37 UTC, Aishwarya-U-R requested changes
Hey @rahulbarwal - [both the new cases are flaky](https://cloud.cypress.io/projects/eyxvp8/runs/36343/test-results?actions=%5B%5D&browsers=%5B%5D&groups=%5B%5D&isFlaky=%5B%7B%22value%22%3Atrue%2C%22label%22%3A%22Flaky%22%7D%5D&modificationDateRange=%7B%22startDate%22%3A%221970-01-01%22%2C%22endDate%22%3A%222038-01-19%22%7D&orderBy=EXECUTION_ORDER&oses=%5B%5D&specs=%5B%5D&statuses=%5B%5D&testingTypesEnum=%5B%5D). Please fix the flakyness & then merge the PR. NO merging till then.

2023-06-19 04:41 UTC, shwetha-ramesh commented
@rahulbarwal QA Done.

2023-06-19 07:02 UTC, rahulbarwal commented
/ok-to-test

2023-06-19 07:03 UTC, rahulbarwal commented on app/client/cypress/support/Pages/AppSettings/EmbedSettings.ts
> +        cy.wait("@changeAccess").should(
Done.

2023-06-19 07:03 UTC, rahulbarwal commented on app/client/cypress/e2e/Regression/ClientSide/SettingsPane/EmbedSettings_spec.ts
>      _.agHelper.RefreshPage();
Done.

2023-06-19 07:09 UTC, dhruvikn commented on app/client/src/utils/AnalyticsUtil.tsx
> +  | "APP_VIEW_WITH_NAVBAR_FLAG"
Just a minor nitpick, can we please rename this event to "APP_VIEWED_WITH_NAVBAR"?

2023-06-19 07:10 UTC, dhruvikn commented
The rest of the PR looks good to me @rahulbarwal.

2023-06-19 07:11 UTC, rahulbarwal commented on app/client/src/utils/AnalyticsUtil.tsx
> +  | "APP_VIEW_WITH_NAVBAR_FLAG"
Done.

2023-06-19 07:17 UTC, dhruvikn approved these changes

2023-06-19 07:37 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ClientSide/SettingsPane/EmbedSettings_spec.ts
> +    agHelper.Sleep();
If making an app public toggle - will always need some wait - can we consider adding this into TogglePublicAccess() itself? So any future use of the method is also taken care.

2023-06-19 09:38 UTC, rahulbarwal commented on app/client/cypress/e2e/Regression/ClientSide/SettingsPane/EmbedSettings_spec.ts
> +    agHelper.Sleep();
@Aishwarya-U-R I was testing a theory with this timeout; I was wrong. This Sleep would not be needed. CI run still marked these tests flaky. 
On local everything passes through in 1st run. Debugging this.

2023-06-19 10:51 UTC, rahulbarwal commented
/ok-to-test

2023-06-19 10:51 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ClientSide/SettingsPane/EmbedSettings_spec.ts
> +    agHelper.Sleep();
Got it, please do!

2023-06-19 12:10 UTC, rahulbarwal commented
/ok-to-test

2023-06-19 13:48 UTC, Aishwarya-U-R reviewed
Cypress looks good, what action did we exactly take here for the flakiness on new tests please?

2023-06-19 14:34 UTC, rahulbarwal commented
> Cypress looks good, what action did we exactly take here for the flakiness on new tests please?
@Aishwarya-U-R I had copied code to invoke the `checked` attribute from some location, but it was not evaluating correct value due to which `if` condition was failing.

Updated my function to invoke `prop` instead of `attr` and the `if` condition evaluated correctly.https://github.com/appsmithorg/appsmith/pull/24561/files#diff-0f3bbf2d7e8fd1cfcde4bef9e37b60194290ea0dc01b09135590c40f18542da9R73

------
This probably holds true for other locations as well where we are invoking `attr` to check "any" checkbox. They were outside the purview of this PR hence did not check them. 

This will serve as a learning to us as well. How I verified this?
Simply call the toggle function twice with same parameter. Since it must have checked the input the first time it should not go inside the `if` condition second time.

2023-06-19 14:54 UTC, Aishwarya-U-R commented
> Updated my function to invoke `prop` instead of `attr` and the `if` condition evaluated correctly.https://github.com/appsmithorg/appsmith/pull/24561/files#diff-0f3bbf2d7e8fd1cfcde4bef9e37b60194290ea0dc01b09135590c40f18542da9R73

Nice & Noted! 🙌🏻

2023-06-21 06:36 UTC, Aishwarya-U-R reviewed
Approving Cypress changes!

2023-06-21 07:15 UTC, akash-codemonk submitted a review, later dismissed

2023-06-21 07:15 UTC, dhruvikn submitted a review, later dismissed

2023-06-21 09:28 UTC, rahulbarwal commented
/ok-to-test

2023-06-21 12:55 UTC, Aishwarya-U-R commented
@rahulbarwal - [Fork_Template_Existing_app_spec.js has failed](https://cloud.cypress.io/projects/eyxvp8/runs/36529/test-results?actions=%5B%5D&browsers=%5B%5D&groups=%5B%5D&isFlaky=%5B%5D&modificationDateRange=%7B%22startDate%22%3A%221970-01-01%22%2C%22endDate%22%3A%222038-01-19%22%7D&orderBy=EXECUTION_ORDER&oses=%5B%5D&specs=%5B%5D&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D&testingTypesEnum=%5B%5D) & re-run is not working properly due to some issue we are debugging. Can you please confirm if this test is a pass in this branch local run?

2023-06-22 05:00 UTC, merged