chore: Skip tests in server build if no changes in server files for ok-to-test command
appsmithorg/appsmith pull request #24616
Opened 2023-06-19 09:28 UTC by rajatagrawal

Fixes #24700

These changes will allow the CI to skip tests if there are no changes in server folder when using ok-to-test command. This will save CI minutes

2023-06-19 10:50 UTC, Aishwarya-U-R commented
@rajatagrawal - can we do oktotest & test this out?

2023-06-19 12:56 UTC, sarojsarab commented
> > @rajatagrawal - can we do oktotest & test this out?
> 
> I am not sure how to do it, because it can only run if it is merged to `release` branch. I can test it if we add support for running ok-to-test command on a pull request if that is okay.

I think you can update the `test-build-docker-image.yml` and run the workflow manually to check . Once done you can simply revert the changes before merge.

2023-06-21 07:39 UTC, rajatagrawal commented
@sarojsarab 

I have tested the changes on `test-build-docker-image.yml` workflow.

These are the outputs of those test runs:

1. when server changes present, skip tests false : [https://github.com/appsmithorg/appsmith/actions/runs/5330910644](https://github.com/appsmithorg/appsmith/actions/runs/5330703671)
2. when server changes not present, skip tests true : https://github.com/appsmithorg/appsmith/actions/runs/5330879566

2023-06-21 07:54 UTC, sarojsarab approved these changes
LGTM

2023-06-21 08:22 UTC, rajatagrawal commented
@Aishwarya-U-R Can you please check Attempt #1 in both those links ? I think those links have two attempts. The ones that I have tested on are Attempt #1.

2023-06-21 08:25 UTC, rajatagrawal commented
Attempt #2 is showing as missing workflow files because I moved the changes from test docker image yml file to ok-to-test yml file for the final commit.

2023-06-21 08:28 UTC, Aishwarya-U-R approved these changes

2023-06-21 08:32 UTC, rajatagrawal commented
@Aishwarya-U-R can you please merge it also ? This PR doesn't need a CI test run.

2023-06-21 08:36 UTC, Aishwarya-U-R requested changes
@rajatagrawal - Have server-build parallel to client build as now.

2023-06-21 08:45 UTC, rajatagrawal commented
@Aishwarya-U-R 

This diagram is from test docker build.yml which was only used for testing the workflow. The changes are actually moved 
ok-to-test workflow after the changes work fine in it.

It is nonetheless parallel in test docker build yml as well, because in the workflow runs in this concerned screenshot, the server workflow ran after `changeset` passed. It didn't wait for client build.

I think that the diagram is showing that server has a dependency on client because all jobs i.e `client/server/rds` are required for the final `build docker image job`.

2023-06-21 09:20 UTC, Aishwarya-U-R commented
Ah ok, Thanks much @sarojsarab for explaining me the same.
@rajatagrawal - merging this now - please have an eye on new runs to make sure our changes are actually doing ok!

2023-06-21 09:20 UTC, merged