Fix: API pane style changes
appsmithorg/appsmith pull request #2467
Opened 2021-01-06 15:11 UTC by devrk96

- Placeholder added in the search component
- Height of section API header section fixed

2021-01-07 04:48 UTC, hetunandu commented on app/client/src/components/editorComponents/ActionNameEditor.tsx
> +    <ApiNameWrapper page={props.page}>
Please add a comment why this was needed and how it will be changed in the future

2021-01-07 05:08 UTC, hetunandu requested changes
Add comments

2021-01-07 14:12 UTC, devrk96 commented on app/client/src/components/editorComponents/ActionNameEditor.tsx
> +    <ApiNameWrapper page={props.page}>
@hetunandu Added the prop information.

2021-01-08 08:46 UTC, hetunandu approved these changes

2021-01-08 14:01 UTC, merged