Fix - 502 in save layout is abruptly taking me to an error screen
appsmithorg/appsmith pull request #2475
Opened 2021-01-07 12:05 UTC by jsartisan

## Description
Server error on any API on editor page was taking user to error page which is not ideal. So removed the crashing on API failures. Now will be crashing the page manually on certain errors.

Fixes # (issue)
> #2452 

## Type of change
- Bug fix

## How Has This Been Tested?

- Manually tested

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-01-08 08:47 UTC, hetunandu commented
We also want to show the error page when the /me call fails since this is always the first call.

2021-01-09 03:33 UTC, hetunandu requested changes

2021-01-09 03:33 UTC, hetunandu commented on app/client/src/api/Api.tsx
> +        });
Can we add a crash for 502 in `/me` call

2021-01-09 03:39 UTC, hetunandu commented
@all-contributors add @jsartisan  for code

2021-01-11 04:43 UTC, jsartisan commented on app/client/src/sagas/ErrorSagas.tsx
> +      ReduxActionErrorTypes.FETCH_USER_DETAILS_ERROR,
@hetunandu This will set the safeCrash now for user init call.

2021-01-11 04:59 UTC, hetunandu requested changes

2021-01-11 04:59 UTC, hetunandu commented on app/client/src/sagas/ErrorSagas.tsx
> +      ReduxActionErrorTypes.FETCH_USER_DETAILS_ERROR,
Not a clean solve. Why cant you dispatch safe crash from the user saga itself?

2021-01-11 05:10 UTC, jsartisan commented on app/client/src/sagas/userSagas.tsx
> +    yield put({
@hetunandu Dispatched the safeCrash action from here.

2021-01-11 05:14 UTC, hetunandu approved these changes

2021-01-11 05:28 UTC, merged