feat: Added a method to verify CS signature
appsmithorg/appsmith pull request #24766
Opened 2023-06-22 18:04 UTC by abhvsn

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.
>
## Description
> Add a TL;DR when description is extra long (helps content team)
>
> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change
>
> Links to Notion, Figma or any other documents that might be relevant to the PR
>
>
#### PR fixes following issue(s)
Fixes # (issue number)
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
#### Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video
>
>
#### Type of change
> Please delete options that are not relevant.
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
## Testing
>
#### How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Also list any relevant details for your test configuration.
> Delete anything that is not relevant
- [ ] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-06-23 10:06 UTC, rajatagrawal commented
/ok-to-test sha=638eeb7

2023-06-23 10:09 UTC, rajatagrawal commented
/ok-to-test sha=638eeb7

2023-06-23 10:14 UTC, rajatagrawal commented
/ok-to-test sha=638eeb7

2023-06-23 17:45 UTC, abhvsn commented
/ok-to-test

2023-06-26 07:10 UTC, abhvsn commented
/ok-to-test

2023-06-26 17:54 UTC, abhvsn commented
/ok-to-test

2023-06-27 06:39 UTC, sharat87 requested changes

2023-06-27 06:39 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/SignatureVerifier.java
> +    private static final String publicVerificationKey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICNwJ+zx2opXjjOga/YyzRxb2czvNgQ/twA+miCKDIX3 appsmith";
Can we rename this constant to `PUBLIC_VERIFICATION_KEY` please?

2023-06-27 06:39 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/SignatureVerifier.java
> +        String signature = Objects.requireNonNull(headers.get(APPSMITH_SIGNATURE)).get(0);
The `isEmpty` above will do null-check too, so we can remove the `requireNonNull` call here.

```suggestion
        String signature = headers.get(APPSMITH_SIGNATURE).get(0);
```

2023-06-27 06:39 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/SignatureVerifier.java
> +        String date = Objects.requireNonNull(headers.get(DATE)).get(0);
I think we want an explicit null-check here, instead of `requireNonNull`.

If I understand right, if the `Date` header is missing, we want to return `false`, instead of throwing an exception, right? Because that's what `requireNonNull` will do. If the parameter is `null`, it'll throw an NPE, which would've been thrown even if that `requireNonNull` call isn't there on this line. 🤷

2023-06-27 06:39 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/constants/ApiConstants.java
> +    public static final String APPSMITH_SIGNATURE = "Appsmith-Signature";
This is a HTTP header, right? If yes, let's use `X-Appsmith-Signature`. Custom headers are recommended to start with `X-`.

That said, this particular header, `X-Appsmith-Signature` is something we're already using for a very different purpose. You can search the code base for this. It's used to add a signature to API requests made from Appsmith as part of API actions, so that the target endpoint can verify that the request really came from Appsmith.

If this is about to cause confusion, consider using a different name for the header here. 🙂

2023-06-27 06:39 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/SignatureVerifier.java
> +        String encodedSignature = signature.split("\\.", 2)[1];
Minor refactoring.

```suggestion
        String[] signatureParts = signature.split("\\.", 2);
        if (signatureParts.length != 2) {
            return false;
        }
        String signingData = signatureParts[0];
        String encodedSignature = signatureParts[1];
```

2023-06-27 06:39 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/SignatureVerifier.java
> +    private static final String publicVerificationKey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICNwJ+zx2opXjjOga/YyzRxb2czvNgQ/twA+miCKDIX3 appsmith";
Also, looks like we only need the key part of this string. So, how about:

```suggestion
    // Public key for verifying signatures with ED25519 scheme.
    private static final String PUBLIC_VERIFICATION_KEY = "AAAAC3NzaC1lZDI1NTE5AAAAICNwJ+zx2opXjjOga/YyzRxb2czvNgQ/twA+miCKDIX3";
```

Then we don't have to do the `.split` to get the key every time.

2023-06-27 06:39 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/SignatureVerifier.java
> +        AsymmetricKeyParameter publicKeyParameters = OpenSSHPublicKeyUtil.parsePublicKey(Base64.getDecoder().decode(publicKeyBody));
Can we do this parsing once, when the class is loaded, instead of on every verification method call?

2023-06-27 08:39 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/SignatureVerifier.java
> +        String signature = Objects.requireNonNull(headers.get(APPSMITH_SIGNATURE)).get(0);
Will remove this I was of the same opinion but IntelliJ started throwing warning hence kept it.

2023-06-27 09:13 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/constants/ApiConstants.java
> +    public static final String APPSMITH_SIGNATURE = "Appsmith-Signature";
Oh thanks this is new we are using `X-APPSMITH-SIGNATURE` but this can get easily confusing, replacing this with `X-Appsmith-CS-Signature`.

2023-06-27 09:43 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/SignatureVerifier.java
> +        AsymmetricKeyParameter publicKeyParameters = OpenSSHPublicKeyUtil.parsePublicKey(Base64.getDecoder().decode(publicKeyBody));
Done

2023-06-27 09:45 UTC, abhvsn commented
/ok-to-test

2023-06-28 15:54 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/constants/ApiConstants.java
> +    public static final String APPSMITH_SIGNATURE = "Appsmith-Signature";
Headers are case-insensitive. So `X-Appsmith-Signature` and `X-APPSMITH-SIGNATURE`, are the same thing for HTTP.

2023-06-28 17:08 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/constants/ApiConstants.java
> +    public static final String APPSMITH_SIGNATURE = "Appsmith-Signature";
Hi @sharat87 we have already replaced the name with `X-Appsmith-CS-Signature` can you take a look at it if anything needs to be changed.

2023-06-29 19:51 UTC, abhvsn commented
/ok-to-test

2023-06-30 03:07 UTC, abhvsn commented
/ok-to-test

2023-07-05 08:33 UTC, abhvsn commented
/ok-to-test

2023-07-05 15:59 UTC, abhvsn commented
/ok-to-test

2023-07-17 03:58 UTC, abhvsn commented
/ok-to-test

2023-07-24 05:47 UTC, sharat87 commented
Unmarking myself for review, since this PR is in draft status. Please mark me again once it's ready for review. Thanks. 🙏

2023-08-01 18:15 UTC, abhvsn commented
/ok-to-test

2023-08-02 06:21 UTC, vishnu-gp approved these changes
Minor suggestion. LGTM

2023-08-02 06:21 UTC, vishnu-gp commented on app/server/appsmith-server/src/test/java/com/appsmith/server/helpers/SignatureVerifierTest.java
> +    }
@abhvsn Should we have a valid signature too with a hardcoded date and signature?

2023-08-02 12:17 UTC, abhvsn commented on app/server/appsmith-server/src/test/java/com/appsmith/server/helpers/SignatureVerifierTest.java
> +    }
Issue here is on Appsmith instance we don't have a way to generate the valid signature. Also if you check we have a protection against the replay attack where we say the signature is valid for only 24hrs.

2023-08-02 12:38 UTC, merged