Scroll to created org
appsmithorg/appsmith pull request #2477
Opened 2021-01-07 12:13 UTC by rishabhsaxena

## Description
Scroll to created org

Fixes #2457

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- manually

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-01-09 04:51 UTC, hetunandu approved these changes

2021-01-09 04:53 UTC, hetunandu requested changes
Did not work for me. History was updated though. Why dont we implement the smooth scrolling already present

2021-01-11 11:03 UTC, rishabhsaxena commented
@hetunandu found an issue, have updates the `ids` to use `slug` instead of `orgName`

2021-01-13 05:02 UTC, hetunandu requested changes

2021-01-13 05:02 UTC, hetunandu commented on app/client/src/sagas/OrgSagas.ts
> +    history.push(`${window.location.pathname}#${slug}`);
history.push is leading to a refresh.

2021-01-13 09:47 UTC, rishabhsaxena commented on app/client/src/sagas/OrgSagas.ts
> +    history.push(`${window.location.pathname}#${slug}`);
actually we're doing a `reload` within `switchUserOrgSaga`, not sure why it's needed there, may be we can fix it as a separate issue?

2021-01-19 05:10 UTC, hetunandu commented on app/client/src/sagas/OrgSagas.ts
> +    history.push(`${window.location.pathname}#${slug}`);
Lets do it with this PR itself

2021-01-21 05:53 UTC, rishabhsaxena commented
@hetunandu have pushed the updates

2021-01-21 05:56 UTC, hetunandu approved these changes

2021-01-21 06:19 UTC, merged