Fix tab width
appsmithorg/appsmith pull request #24797
Opened 2023-06-23 12:06 UTC by palashkaria

## Description
Fixes: https://github.com/appsmithorg/appsmith/issues/22455
Fixed by increase the max-width from 138px to 180px.

#### PR fixes following issue(s): 
Fixes # (issue number): https://github.com/appsmithorg/appsmith/issues/22455  
#### Type of change
> Please delete options that are not relevant.
- Bug fix (non-breaking change which fixes an issue)

## Testing
>
#### How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Also list any relevant details for your test configuration.
Tested by adding a long text and verifying that it's visible

> Delete anything that is not relevant
- [x] Manual

>
>

## Checklist:
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-06-23 12:08 UTC, palashkaria commented
@somangshu @dilippitchika @kamakshibhat-appsmith please take a look

2023-06-23 13:03 UTC, somangshu commented
@laveena-en can you please take this up for a round of QA. Dropping the previous context for you here  https://github.com/appsmithorg/appsmith/pull/23039#issuecomment-1564761134. Please vheck

2023-06-27 05:43 UTC, vsvamsi1 requested changes

2023-06-27 05:43 UTC, vsvamsi1 commented on app/client/src/widgets/TabsWidget/component/PageTabs.tsx
> +    max-width: 12.5rem;
Since it is identical to the parent's width can we inherit it. 
    max-width: inherit;

2023-06-27 12:13 UTC, laveena-en commented
Verified, changes LGTM!

cc: @somangshu

2023-06-27 12:53 UTC, somangshu approved these changes

2023-06-27 12:53 UTC, somangshu commented
/ok-to-test

2023-06-27 15:35 UTC, vsvamsi1 approved these changes

2023-06-28 07:34 UTC, vsvamsi1 commented
/ok-to-test sha=cab524ddc579f1fb807ac06c5c11cc8029c79b1c

2023-06-28 10:05 UTC, merged