Added provision for specific basic auth creds for actuator endpoints
appsmithorg/appsmith pull request #24846
Opened 2023-06-26 15:13 UTC by nidhi-nair

## Description
Adds provision to use custom basic authentication creds for actuator endpoints. If none are provided, we would still need to use basic auth header with empty creds.

Fixes https://github.com/appsmithorg/appsmith-ee/issues/1441

>
#### Type of change
- New feature (non-breaking change which adds functionality)
>
>
## Testing
>
#### How Has This Been Tested?
- [x] Manual
>
>
#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-06-27 06:51 UTC, sharat87 requested changes

2023-06-27 06:51 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/SecurityConfig.java
> +            }
Can we change this to keep backwards-compatibility? If username and password aren't set, can we allow this API to be accessible as in the past? Or are we expecting sensitive data to now go out of this endpoint?

2023-06-27 06:51 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/SecurityConfig.java
> +    private String INTERNAL_USER_NAME;
Minor, but this'll be uniform with the env variable.

```suggestion
    private String INTERNAL_USERNAME;
```

2023-06-27 09:12 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/SecurityConfig.java
> +            }
@sharat87 Shall I set another environment variable for this that determines whether auth needs to be used? Probably more foolproof than checking for blank fields.

2023-06-27 10:38 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/SecurityConfig.java
> +            }
Oh nah that's too much for this I think. In fact, I was going to suggest removing username, and just have password. Basic auth can work with just password. One configuration is more that enough for this.

Checking for blank is fine enough, I think. If blank, allow them, if not, require authentication.

2023-06-27 14:14 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/SecurityConfig.java
> +            }
Okay so Spring does not have an `isBlank` check on conditional properties. I've set up a separate prop for the config right now. Do you think we should make a custom annotation for the check instead? I'm a little divided between maintainability and configurability.

2023-06-28 07:54 UTC, sharat87 requested changes

2023-06-28 07:54 UTC, sharat87 commented on app/server/appsmith-server/src/main/resources/application.properties
> +#random.prop=false
Not random enough I think. :P

2023-06-28 07:54 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/SecurityConfig.java
> +        }
Feel free to not agree with this suggestion. 🙂

```suggestion
        // Either configured password is empty, or it's equal to what we received.
        return StringUtils.isEmpty(INTERNAL_PASSWORD) || INTERNAL_PASSWORD.equals(password);
```

2023-06-28 07:54 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/SecurityConfig.java
> +    @ConditionalOnProperty(name = "appsmith.internal.auth.enabled")
Can we use just the password for this? I see we have the implementation where, if password is empty, then auth is always accepted anyway, right? I think we can use `ConditionalOnExpression` to make this conditional on whether `password` is non-empty. One less configuration to care about. What say?

2023-07-04 06:49 UTC, sharat87 approved these changes

2023-07-04 06:59 UTC, merged