validate map center and markers
appsmithorg/appsmith pull request #2488
Opened 2021-01-08 07:20 UTC by rishabhsaxena

## Description
Validates the center and markers passed to the maps component, to prevent the map widget from crashing.

Although this would silently catch such errors. It could happen by manually setting this value or dynamically (on a button click for example).

Fixes #2347

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- manually set invalid initial location or marker for the map widget

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-01-09 04:31 UTC, hetunandu requested changes

2021-01-09 04:31 UTC, hetunandu commented on app/client/src/components/designSystems/appsmith/MapComponent.tsx
> +};
This validation needs to be on the widget level.

2021-01-11 17:35 UTC, hetunandu requested changes

2021-01-11 17:35 UTC, hetunandu commented on app/client/src/widgets/MapWidget.tsx
> +const validateLatLongObj = ({
I am sorry, I should have been more specific. What you really want to do is create a new validation and filter out bad markers there itself so that any other widget reading this info also gets the correct set of markers. You can see the existing validations in the function `getPropertyValidationMap`

2021-01-12 08:55 UTC, rishabhsaxena commented on app/client/src/widgets/MapWidget.tsx
> +const validateLatLongObj = ({
@hetunandu 

have updated the code here, need to look into why the `Default markers` property does not have an error boundary even though we're returning `isValid` as false

![chrome-capture (3)](https://user-images.githubusercontent.com/1944800/104291562-af476a80-54e1-11eb-88f8-9f137604a6a0.jpg)

2021-01-12 10:56 UTC, rishabhsaxena commented on app/client/src/widgets/MapWidget.tsx
> +const validateLatLongObj = ({
ok got it, we actually reset the evaluated value

2021-01-13 05:09 UTC, hetunandu approved these changes

2021-01-19 07:29 UTC, merged