fix: Feature Flag User Based Caching
appsmithorg/appsmith pull request #24931
Opened 2023-06-29 14:31 UTC by NilanshBansal

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.
>
## Description
> Add a TL;DR when description is extra long (helps content team)
>
> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change
>
> Links to Notion, Figma or any other documents that might be relevant to the PR
>
>
#### PR fixes following issue(s)
Fixes # (issue number)
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
#### Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video
>
>
#### Type of change
> Please delete options that are not relevant.
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
## Testing
>
#### How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Also list any relevant details for your test configuration.
> Delete anything that is not relevant
- [ ] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-06-30 10:05 UTC, AnaghHegde submitted a review, later dismissed
Redis cache chages LGTM

2023-06-30 10:10 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/resources/application.properties
> +appsmith.feature-flag.cache.in.minutes=${APPSMITH_FF_CACHE_TIME_MIN:120}
Should this be configurable at all? Would we not risk excessive requests if this has been set to a different value?

2023-06-30 10:10 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/FeatureFlagServiceCEImpl.java
> +                    return Mono.just(newValue.get(userIdentifier))
We need not return with a tuple here, please consider using a thenReturn

2023-06-30 10:11 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/FeatureFlagServiceCEImpl.java
> +        this.reactiveRedisTemplate = reactiveRedisTemplate;
Please consider using a utility service like the one being used in reactive-caching as a wrapper here. We should use a common prefix to all feature flag related entries so we have an easy to manage those values. The repository layer ops would also get isolated in another class that way.

2023-06-30 10:12 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/FeatureFlagServiceCEImpl.java
> +    @Value("${appsmith.feature-flag.cache.in.minutes}")
What do you think about configuring this in a config bean and using the value from there? That's the norm we have been following so far to avoid littering the code base with property references.

2023-06-30 10:13 UTC, nidhi-nair requested changes
Please write tests

2023-06-30 10:26 UTC, NilanshBansal commented on app/server/appsmith-server/src/main/resources/application.properties
> +appsmith.feature-flag.cache.in.minutes=${APPSMITH_FF_CACHE_TIME_MIN:120}
Valid point, for self-hosted, this can be configured to a shorter time by the user, which can lead to excessive requests. 
@hetunandu @ginilpg @kocharrahul7 shall we consider keeping the cache time per user to a fixed value?

2023-06-30 10:28 UTC, hetunandu commented on app/server/appsmith-server/src/main/resources/application.properties
> +appsmith.feature-flag.cache.in.minutes=${APPSMITH_FF_CACHE_TIME_MIN:120}
We can set it as a fixed value for now. Lets see if it needs shorter time in dev/release in the future

2023-07-01 14:22 UTC, NilanshBansal commented
/ok-to-test

2023-07-02 03:03 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/CacheableFeatureFlagHelperCEImpl.java
> +    public CacheableFeatureFlagHelperCEImpl(TenantService tenantService, ConfigService configService,
Nit, please use a formatter in your files before committing. Let's do this in whatever PR you work on next since this PR is a blocker for release.

2023-07-02 03:06 UTC, nidhi-nair commented on app/server/appsmith-server/src/test/java/com/appsmith/server/services/FeatureFlagServiceTest.java
> +        StepVerifier.create(cachedFlagsMono.then(Mono.defer(()-> hasKeyMono)))
Does this not work as expected without the deferring? Also in the main code? Could you please check?

2023-07-02 04:41 UTC, NilanshBansal commented on app/server/appsmith-server/src/test/java/com/appsmith/server/services/FeatureFlagServiceTest.java
> +        StepVerifier.create(cachedFlagsMono.then(Mono.defer(()-> hasKeyMono)))
Yes, @nidhi-nair without Mono.defer() as well tests and main code both work as expected

2023-07-02 05:33 UTC, NilanshBansal commented
/ok-to-test

2023-07-02 06:15 UTC, nidhi-nair approved these changes

2023-07-02 06:42 UTC, merged