19353 feature create password protected backup archives from appsmithctl with salt and password included
appsmithorg/appsmith pull request #24966
Opened 2023-06-30 11:14 UTC by sum35h

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.
>
## Description
> Add a TL;DR when description is extra long (helps content team)
>
> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change
>
> Links to Notion, Figma or any other documents that might be relevant to the PR
>
>
#### PR fixes following issue(s)
Fixes # (issue number)
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
#### Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video
>
>
#### Type of change
> Please delete options that are not relevant.
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
## Testing
>
#### How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Also list any relevant details for your test configuration.
> Delete anything that is not relevant
- [ ] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-06-30 11:16 UTC, sum35h commented
/build-deploy-preview skipTests=true

2023-07-05 11:36 UTC, sum35h commented
/build-deploy-preview skipTests=true

2023-07-06 11:34 UTC, sum35h commented
/build-deploy-preview skipTests=true

2023-07-06 13:53 UTC, sum35h commented
/build-deploy-preview skipTests=true

2023-07-14 04:37 UTC, sum35h commented
/build-deploy-preview env=release

2023-07-18 07:37 UTC, sharat87 commented on deploy/docker/utils/bin/restore.js
>      if (backupFileName == null) {
We're doing the null-check _after_ we're using the value of `backupFileName`. Can you review this segment of code please?

2023-07-18 07:41 UTC, sharat87 commented on deploy/docker/utils/bin/restore.js
> +    '\nAPPSMITH_MONGODB_USER=' + process.env.APPSMITH_MONGODB_USER + '\nAPPSMITH_MONGODB_PASSWORD=' + process.env.APPSMITH_MONGODB_PASSWORD ) ;
The control would go into this `else` block, when the encryption salt and password are _not_ there in the backup archive, right? If yes, shouldn't we be asking the user to enter them here?

2023-07-18 07:42 UTC, sharat87 commented on deploy/docker/utils/bin/restore.js
> +async function unencryptArchive(encryptedFilePath, backupFilePath){
Can we reword `unencrypt` to `decrypt` everywhere please?

2023-07-18 07:43 UTC, sharat87 commented on deploy/docker/utils/bin/backup.js
> +  encryptBackupArchive
```suggestion
  encryptBackupArchive,
```

2023-07-18 07:50 UTC, sharat87 commented on deploy/docker/utils/bin/backup.js
> +}
Suggestion, this implementation can be simplified like this:

```js
function getEncryptionPasswordFromUser(){
  for (const _ of [1, 2, 3]) {
    const encryptionPwd1 = readlineSync.question('Enter a password to encrypt the backup archive: ', {
      hideEchoBack: true
    });
    const encryptionPwd2 = readlineSync.question('Enter the above password again: ', {
      hideEchoBack: true
    });
    if (encryptionPwd1 === encryptionPwd2) {
      return encryptionPwd1;
    }
  }

  console.error("The passwords do not match, please try again.")
  return -1
}
```

2023-07-18 07:51 UTC, sharat87 commented on deploy/docker/utils/bin/backup.js
> +    if (encryptArchive) {
```suggestion
    if (encryptArchive) {
```

2023-07-18 07:52 UTC, sharat87 commented on deploy/docker/utils/bin/backup.js
> +    let keys_to_remove = 'all'
Can we use consistent variable naming please? Like `keysToRemove` instead of `keys_to_remove`?

2023-07-18 07:53 UTC, sharat87 commented on deploy/docker/utils/bin/backup.js
> +  let backupRootPath, ArchivePath, encryptionPassword;
Can we use consistent variable names please? Like `archivePath` instead of `ArchivePath` (which reads like a class name)?

2023-07-19 07:13 UTC, sum35h commented on deploy/docker/utils/bin/restore.js
> +    '\nAPPSMITH_MONGODB_USER=' + process.env.APPSMITH_MONGODB_USER + '\nAPPSMITH_MONGODB_PASSWORD=' + process.env.APPSMITH_MONGODB_PASSWORD ) ;
No, the else case handles decrypted archive which includes the salt and password.

2023-07-20 04:08 UTC, sum35h commented
/ok-to-test

2023-07-20 04:47 UTC, sum35h commented
/build-deploy-preview skipTests=ture

2023-07-28 09:57 UTC, sharat87 requested changes
Can we fix these two issues please:

1. When taking a backup, empty password works. Can we instead fail the backup command with an error, if the password entered is empty?

2. During restore, if the password is incorrect, the message isn't clear that that's the problem, and it doesn't offer to retry.
![shot-2023-07-28-09-50-38](https://github.com/appsmithorg/appsmith/assets/120119/c9c74f9f-dcc6-44aa-8e03-822b94306842)

2023-07-28 11:50 UTC, sharat87 submitted a review, later dismissed

2023-07-31 06:00 UTC, sum35h commented
/ok-to-test

2023-07-31 07:03 UTC, sum35h commented
/build-deploy-preview skipTests=true

2023-08-08 11:29 UTC, sum35h commented on deploy/docker/utils/bin/backup.js
> +    if (!command_args.includes('--non-interactive') && (tty.isatty(process.stdout.fd))){
checking for tty to run in interactive mode else runs in non-interactive mode for backward compatability.

2023-08-15 06:03 UTC, sharat87 commented
Let's come back to this and ensure the effective salt and password are in the archive, which is not necessarily the ones from `docker.env`. I'm unmarking myself for review on this. Please mark me once this change is ready. Thanks!

2023-09-19 05:37 UTC, sum35h commented
/ok-to-test

2023-09-20 06:19 UTC, sum35h commented
/build-deploy-preview skipTests=True

2023-09-20 06:21 UTC, sum35h commented
/ok-to-test

2024-03-27 12:40 UTC, closed without merging