chore: show additional toast with action type on cypress
appsmithorg/appsmith pull request #25037
Opened 2023-07-03 13:18 UTC by akash-codemonk

Adds an additional toast to show on cypress when error message is an empty string or null to help with debugging. Showing the action name causing the error in the toast. Temporary will be removed after. 

Related to  https://github.com/appsmithorg/appsmith/issues/23713

2023-07-04 12:09 UTC, hetunandu requested changes

2023-07-04 12:09 UTC, hetunandu commented on app/client/src/sagas/ErrorSagas.tsx
> +            yield call(showToast, message + type, { kind: "error" });
If the message is empty string, how will it help to show it on a toast message?

Can we do a console log instead? We can probably use this
https://github.com/appsmithorg/appsmith/blob/release/app/client/cypress/plugins/index.js#L66

Another option is to use Cypress.log
https://docs.cypress.io/api/cypress-api/cypress-log

2023-07-04 12:51 UTC, akash-codemonk commented on app/client/src/sagas/ErrorSagas.tsx
> +            yield call(showToast, message + type, { kind: "error" });
Yup `message` is not useful. The `type` will mention the action being dispatched. console.log or cypress.log is not useful since we only see a part of these logs in the cypress video recordings.  Have tried this before, these are completely missed. 

The toast with the action type will be easy to spot as we can already spot the empty toast now.

2023-07-06 06:58 UTC, hetunandu commented on app/client/src/sagas/ErrorSagas.tsx
> +            yield call(showToast, message + type, { kind: "error" });
I still think just having the type would not be enough. That could be blank as well for all we know. 
We need a more solid way to identify where the error is originating from. We can consider crashing the page and printing the error in bold text on the screen.

2023-07-06 11:54 UTC, akash-codemonk commented on app/client/src/sagas/ErrorSagas.tsx
> +            yield call(showToast, message + type, { kind: "error" });
Crash landing on cypress env with a stack trace. E.g screenshot
<img width="1439" alt="stack trace" src="https://github.com/appsmithorg/appsmith/assets/67054171/ab42b06a-a848-4e2b-9006-a2c02b32be28">

2023-07-06 11:54 UTC, akash-codemonk commented
/ok-to-test

2023-07-10 05:35 UTC, hetunandu approved these changes

2023-07-10 05:53 UTC, merged