feat: WDS `bgPositive` states and `Subtle` variant
appsmithorg/appsmith pull request #25062
Opened 2023-07-04 10:09 UTC by ichik

## Description

tl;dr States and other derivatives of `bgPositive`.

Fixes #24510 

## Type of change
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Manual

### Test Plan
Initial POC refinement, no testing necessary

## Checklist:
### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2023-07-04 10:20 UTC, jsartisan approved these changes

2023-07-05 07:25 UTC, KelvinOm requested changes

2023-07-05 07:25 UTC, KelvinOm commented on app/client/packages/design-system/theming/src/color/DarkModeTheme.ts
> +    const color = this.bgPositive.clone();
We have to add `to("sRGB")` for every token with created through new Color("oklch") function, also every token witch clone this tokens also should have `to("sRGB")`.

Please check it out.
<img width="400" alt="Снимок экрана 2023-07-05 в 10 17 19" src="https://github.com/appsmithorg/appsmith/assets/11555074/053a0fd9-dc43-45be-8c00-b07f08118aa4">

2023-07-05 07:25 UTC, KelvinOm commented on app/client/packages/design-system/theming/src/color/DarkModeTheme.ts
> +    // Lightness of bgPositive is known, no additional checks like in bgAccentHover
Please leave same comment in other hover | active functions as well.

2023-07-05 08:45 UTC, KelvinOm approved these changes

2023-07-05 08:58 UTC, merged