chore: Add button v2 under feature flag
appsmithorg/appsmith pull request #25106
Opened 2023-07-05 08:09 UTC by jsartisan

## Description

>
> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change
>
> Links to Notion, Figma or any other documents that might be relevant to the PR
>
>
#### PR fixes following issue(s)
Fixes # (issue number)
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
#### Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video
>
>
#### Type of change
> Please delete options that are not relevant.
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
## Testing
>
#### How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Also list any relevant details for your test configuration.
> Delete anything that is not relevant
- [ ] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-07-05 08:10 UTC, jsartisan commented
/build-deploy-preview env=release

2023-07-06 06:51 UTC, hetunandu commented on app/client/src/ce/entities/FeatureFlag.ts
> +  wds_v2: "wds_v2",
Can we rename this flag to follow the naming conventions? 
https://www.notion.so/appsmith/Using-Feature-Flags-in-Appsmith-d362fe7acc7d4ef0aa12e1f5f9b83b5f?pvs=4#f6d4242e56284e84af25cadef71b7aeb

2023-07-06 06:52 UTC, hetunandu commented on app/client/src/pages/AppViewer/index.tsx
> +  const featureFlags = useSelector(selectFeatureFlags);
Use the correct hook
https://www.notion.so/appsmith/Using-Feature-Flags-in-Appsmith-d362fe7acc7d4ef0aa12e1f5f9b83b5f?pvs=4#5a5fd3b4445a45679a0eb4237411ba9d

2023-07-06 09:58 UTC, riodeuno commented on app/client/packages/design-system/widgets/src/components/Tooltip/index.styled.tsx
> +  z-index: 9999;
We've had conflicts with z-index values before, where the same values were used, causing some elements to be overlapped when they shouldn't. Please look into tokenizing these values, or using a semantic mechanism to provide these.

![Screenshot 2023-07-06 at 3 28 07 PM](https://github.com/appsmithorg/appsmith/assets/103687/588d1edf-0ff0-49a6-af52-dd76de5263cd)

2023-07-06 09:59 UTC, riodeuno commented on app/client/src/components/wds/constants.ts
> +export const WDS_V2_WIDGET_MAP = {
Could we elaborate on why we need this map, and where it would be used?

2023-07-06 10:00 UTC, riodeuno commented on app/client/src/pages/AppViewer/index.tsx
> +      <ThemeProvider theme={lightTheme}>
Do we need two providers? I believe we'll remove the old provider once we've migrated all widgets. Is that correct?

2023-07-06 10:01 UTC, riodeuno commented on app/client/src/pages/AppViewer/index.tsx
> +          <WidgetGlobaStyles
@jsartisan Could you elaborate on what this is for?

2023-07-06 11:22 UTC, KelvinOm requested changes

2023-07-06 11:22 UTC, KelvinOm commented on app/client/src/widgets/ButtonWidgetV2/component/RecaptchaV2.tsx
> +    if (isDisabled) return onClickProp;
Why are we return onClickProp here?

2023-07-06 11:22 UTC, KelvinOm commented on app/client/src/widgets/ButtonWidgetV2/component/index.tsx
> +  color?: ButtonProps["color"];
Why do we need color prop? The color of the button should be determined through the variant.

2023-07-06 11:22 UTC, KelvinOm commented on app/client/src/widgets/ButtonWidgetV2/index.tsx
> +    columns: 16,
Noob question. why do we need `rows` and `columns` props?

2023-07-06 11:22 UTC, KelvinOm commented on app/client/src/widgets/ButtonWidgetV2/index.tsx
> +    isDefaultClickDisabled: true,
Why is this necessary?

2023-07-06 11:22 UTC, KelvinOm commented on app/client/src/widgets/ButtonWidgetV2/index.tsx
> +    responsiveBehavior: ResponsiveBehavior.Hug,
How do we handle this behavior? Does our component work well with `fill` as well?

2023-07-06 11:22 UTC, KelvinOm commented on app/client/src/widgets/ButtonWidgetV2/index.tsx
> +    minWidth: BUTTON_MIN_WIDTH,
As I wrote earlier, this should be in the button component.

2023-07-06 11:22 UTC, KelvinOm commented on app/client/src/widgets/ButtonWidgetV2/index.tsx
> +  autoLayout: {
If we only work with auto layout, why do we need this config?

2023-07-06 11:22 UTC, KelvinOm commented on app/client/src/widgets/ButtonWidgetV2/component/Container.tsx
> +  // TODO(pawan): Ask Albin if we can remove the important in ADS Code
I think it's for the old button from the widgets-old package and we don't need it anymore.

2023-07-06 11:22 UTC, KelvinOm commented on app/client/packages/design-system/widgets/src/components/Tooltip/WithTooltip.tsx
> +export function WithTooltip(props: TooltipProps) {
Let's just call this `tooltip`, and what used to be a tooltip before let's call `tooltip-container`. It will be easier for consumers use component this way.

2023-07-06 11:22 UTC, KelvinOm commented on app/client/packages/design-system/widgets/src/components/Tooltip/WithTooltip.tsx
> +  tooltip?: string;
As far as I understand, we can use not only a string as content for a tooltip. There should definitely be a string here?

I would also suggest renaming skip to `content`.

2023-07-06 11:47 UTC, jsartisan commented on app/client/src/pages/AppViewer/index.tsx
> +          <WidgetGlobaStyles
This is the theme provider of wds that generates all the tokens that the new wds components are consuming.

2023-07-06 11:48 UTC, jsartisan commented on app/client/src/components/wds/constants.ts
> +export const WDS_V2_WIDGET_MAP = {
I am using this map to show/hide cards in entity explorer. When WDS is enabled in flagsmith, i just want to only new wds widgets.

2023-07-06 11:48 UTC, jsartisan commented on app/client/jest.config.js
> +    "@design-system/widgets": "<rootDir>/node_modules/@design-system/widgets",
Done.

2023-07-06 11:50 UTC, jsartisan commented on app/client/src/reducers/uiReducers/appThemingReducer.ts
> +        primaryColor: "#000",
Jest tests were failing because they were getting empty values and when there was an empty seed color, the token accessor was throwing an error.

2023-07-06 11:51 UTC, jsartisan commented on app/client/src/widgets/ButtonWidgetV2/component/Container.tsx
> +const StyledContainer = styled.div<ContainerProps>`
So according to ashok, this is what they are expecting right now.

2023-07-06 11:52 UTC, jsartisan commented on app/client/src/widgets/ButtonWidgetV2/component/index.tsx
> +  color?: ButtonProps["color"];
The color is the semantic color ( accent, negative, warniing etc )

2023-07-06 11:52 UTC, jsartisan commented on app/client/src/widgets/ButtonWidgetV2/index.tsx
> +    columns: 16,
This won't be needed in the future i guess. This is meant for a fixed layout.

2023-07-06 11:57 UTC, jsartisan commented on app/client/packages/design-system/widgets/src/components/Tooltip/WithTooltip.tsx
> +  tooltip?: string;
Yea, that makes sense. Let me make it as React.ReactNode

2023-07-06 12:00 UTC, jsartisan commented on app/client/src/widgets/ButtonWidgetV2/component/Container.tsx
> +  // TODO(pawan): Ask Albin if we can remove the important in ADS Code
No no. ADS team has put a global style and that affects the color of our button icon. So I have asked Albin to remove that global style. Will remove it once he removes it.

2023-07-06 12:01 UTC, jsartisan commented on app/client/src/widgets/ButtonWidgetV2/index.tsx
> +    minWidth: BUTTON_MIN_WIDTH,
I am not really sure why we need it because i can see there is another in autolayout config.
I'll contact with ashok again and ask what all fields we need in our new widgets for the new autolayout

2023-07-06 12:03 UTC, jsartisan commented on app/client/src/widgets/ButtonWidgetV2/index.tsx
> +    isDefaultClickDisabled: true,
This seems obsolete. All these properties are from v1. Let me get clarity about this from ashok/abhinav about this.

2023-07-06 12:04 UTC, jsartisan commented on app/client/src/widgets/ButtonWidgetV2/component/RecaptchaV2.tsx
> +    if (isDisabled) return onClickProp;
the recapchav2/recaptcha3 hook returns an onClick function that the button component uses.

2023-07-06 12:04 UTC, jsartisan commented on app/client/src/components/wds/ThemeProvider.tsx
> +export function ThemeProvider(props: ThemeProviderProps) {
Right. Let me refactor it.

2023-07-06 12:05 UTC, jsartisan commented on app/client/packages/design-system/theming/src/theme/useTheme.tsx
> +export function useTheme(props: UseThemeProps) {
Yea sure.

2023-07-06 12:06 UTC, jsartisan commented on app/client/packages/design-system/widgets/src/components/Tooltip/index.styled.tsx
> +  z-index: 9999;
Noted.

2023-07-06 12:10 UTC, jsartisan commented on app/client/src/pages/AppViewer/index.tsx
> +      <ThemeProvider theme={lightTheme}>
Yea. The second provider is the legacy provider that is there since 3 years. no one removed it thinking that it might mess up something. I'll check if they can safely remove it.

2023-07-06 12:26 UTC, jsartisan commented on app/client/packages/design-system/widgets/src/components/Tooltip/WithTooltip.tsx
> +export function WithTooltip(props: TooltipProps) {
Hey, this component is more like a HOC that just wraps a component in a tooltip only if there is a tooltip provided..

So instead of doing this in the widget:

```jsx
const Widget = () => {
  if (props.tooltip) {
    <Component>
    	...
    </Component>
  }
  
  return <Tooltip>
      <TooltipTrigger><Component /></TooltipTrigger>
      <TooltipContent>{props.tooltip}</TooltipContent>
    </Tooltip>
}
```

We can do:

```jsx
const Widget = () => {
	return <WithToottip tooltip={props.tooltip}>
		<Component />
	</WithTooltip>
}
```	

The reason for this component is we will need the conditional wrapping in other widgets also like Icon button.

2023-07-06 13:44 UTC, KelvinOm commented on app/client/src/widgets/ButtonWidgetV2/component/Container.tsx
> +  // TODO(pawan): Ask Albin if we can remove the important in ADS Code
What will happen to our button if it's just deleted? Does it affect us somehow? I'm sure it shouldn't.

2023-07-07 07:32 UTC, jsartisan commented on app/client/src/widgets/ButtonWidgetV2/component/Container.tsx
> +  // TODO(pawan): Ask Albin if we can remove the important in ADS Code
Yes, it affects us. Since they are changing the color of blueprint icon globally, our icon in button widget is getting affected. 
![CleanShot 2023-07-07 at 13 01 48](https://github.com/appsmithorg/appsmith/assets/6636360/ced68998-c91e-4bd3-8224-a1f54b43a4f9)

2023-07-07 07:54 UTC, KelvinOm commented on app/client/src/widgets/ButtonWidgetV2/component/Container.tsx
> +  // TODO(pawan): Ask Albin if we can remove the important in ADS Code
Got it, here we redefine the styles for the blueprint icon and it has nothing to do with ADS. 

Let's put this style in our component, so we won't have to do this in every place where the button is used. Also, leave a comment that it is necessary while we use blueprint icons.

Does it make sense?

2023-07-07 09:31 UTC, riodeuno commented on app/client/src/pages/AppViewer/index.tsx
> +          <WidgetGlobaStyles
Ok, then I have a follow up question about the difference between `WidgetGlobalStyles` and `WDSThemeProvider`. I'll try to find the answer in the PR code.

2023-07-19 05:06 UTC, jsartisan commented
/build-deploy-preview env=release

2023-07-19 13:17 UTC, chandannkumar commented
@jsartisan Observations:
1. Label and icon seems very close when Position of button is set to right
![image](https://github.com/appsmithorg/appsmith/assets/95341241/1e5eb79e-71e1-4142-b5d8-58e6b1d86e98)

2. On switching to Style Tab, the selected icon for button widget turns to black color.
https://www.loom.com/share/b27b14346fe149cd8a868fd8a197bfa0?sid=dcdd50d9-fefb-41a1-a969-198c94e8e9ec

3. On adding long Label of button widget gets overflowed from actual size of button widget
https://www.loom.com/share/6fbcd415600b438ca30b00ee08b819e8?sid=3aa7bacd-69b8-4c31-8bcc-2bdfa7461a4d

4. On changing the background theme color, the changes are not reflected on canvas
https://www.loom.com/share/cc8ff9e4d6194319a4194ae0bdac8525?sid=b2f54432-130b-456a-9550-6a9923110f84

2023-07-19 16:26 UTC, KelvinOm requested changes

2023-07-19 16:26 UTC, KelvinOm commented on app/client/packages/design-system/widgets/src/components/Tooltip/Tooltip.tsx
> +import React from "react";
This component should be added to the documentation.

2023-07-19 16:26 UTC, KelvinOm commented on app/client/packages/storybook/.storybook/decorators/theming.tsx
> +  const { theme } = useTheme({
Nice 👍

2023-07-19 16:26 UTC, KelvinOm commented on app/client/src/pages/AppViewer/index.tsx
> +      <ThemeProvider theme={lightTheme}>
@jsartisan  What about deleting the legacy provider?

2023-07-19 16:26 UTC, KelvinOm commented on app/client/src/pages/AppViewer/index.tsx
> +          <WidgetGlobaStyles
@jsartisan  Why do we need these global styles? If we need something from this, let's put it in WDS provider.

```
export const WidgetGlobaStyles = createGlobalStyle<{
  primaryColor?: string;
  fontFamily?: string;
}>`
    :root{
      --wds-accent-color: ${({ primaryColor }) => primaryColor};
      --wds-font-family: ${({ fontFamily }) =>
        fontFamily === "System Default" ? "inherit" : fontFamily};
    }
  `;

```

2023-07-19 16:26 UTC, KelvinOm commented on app/client/src/pages/Editor/Canvas.tsx
> +  ThemeProvider as WDSThemeProvider,
Do we really need as syntax here?

2023-07-19 16:26 UTC, KelvinOm commented on app/client/src/widgets/ButtonWidgetV2/component/Container.tsx
> +const StyledContainer = styled.div<ContainerProps>`
I need to know more about this. I will read the code. For now, let's leave it as it is

2023-07-19 16:26 UTC, KelvinOm commented on app/client/src/widgets/ButtonWidgetV2/component/RecaptchaV2.tsx
> +    if (isDisabled) return onClickProp;
@jsartisan I understand that we have to return onСlick, I don't understand why we have to return it if `isDisabled === true`.

2023-07-19 16:26 UTC, KelvinOm commented on app/client/src/widgets/ButtonWidgetV2/index.tsx
> +    columns: 16,
@jsartisan Can we delete everything related to the fixed format now? Can we also enable auto layout by default and hide the toggle button to fixed one? This can be a separate task.

2023-07-19 16:26 UTC, KelvinOm commented on app/client/src/widgets/ButtonWidgetV2/index.tsx
> +    isDefaultClickDisabled: true,
@jsartisan What about these parameters? Are they outdated?

2023-07-19 16:26 UTC, KelvinOm commented on app/client/src/widgets/ButtonWidgetV2/index.tsx
> +    responsiveBehavior: ResponsiveBehavior.Hug,
@jsartisan What about this one?

2023-07-19 16:26 UTC, KelvinOm commented on app/client/src/widgets/ButtonWidgetV2/widget/index.tsx
> +export default ButtonWidget;
Can we avoid export default?  https://google.github.io/styleguide/tsguide.html#exports

@riodeuno I would like to start a discussion.

2023-07-20 06:59 UTC, jsartisan commented on app/client/packages/design-system/widgets/src/components/Text/index.styled.tsx
> +  width: auto;
adding 100% was a mistake in the first place.
when we used 100%, the text component was trying to take all available space and was pushing the icon to the edge.
We only want to take the space it needs.

with 100%
![CleanShot 2023-07-20 at 12 27 18](https://github.com/appsmithorg/appsmith/assets/6636360/20fc52e8-2d85-4086-a1b6-8ba1816736e8)

with auto
![CleanShot 2023-07-20 at 12 28 39](https://github.com/appsmithorg/appsmith/assets/6636360/2b5dab77-a539-49bb-9f54-95845e9ae9a0)

2023-07-20 07:55 UTC, jsartisan commented on app/client/src/widgets/ButtonWidgetV2/component/RecaptchaV2.tsx
> +    if (isDisabled) return onClickProp;
the recaptcha hook returns a modified onClick handler
but if the button has isDisabled or isLoading state, we don't want to return the modified onClick handler. we just return the original handler.

2023-07-20 08:11 UTC, jsartisan commented
/ok-to-test

2023-07-20 09:31 UTC, KelvinOm commented on app/client/packages/design-system/widgets/src/components/Text/index.styled.tsx
> +  width: auto;
@jsartisan Please check this https://github.com/appsmithorg/appsmith/pull/25106#issuecomment-1642065719

I believe that one of the points is just because of this. Try to use `max-width`.

2023-07-20 10:56 UTC, jsartisan commented
/build-deploy-preview env=release

2023-07-20 12:47 UTC, chandannkumar commented
Observation on new DP:

- onClick events are triggered twice on clicking on button widget
 https://www.loom.com/share/f9bc71249a494300971ab0dea7dfe8cd?sid=3915306b-a534-493d-a2f5-4904b68f0b7a

2023-07-21 07:49 UTC, jsartisan commented
/build-deploy-preview env=release

2023-07-21 10:50 UTC, chandannkumar commented
@jsartisan LGTM

2023-07-24 05:37 UTC, jsartisan commented
/ok-to-test

2023-07-25 06:54 UTC, jsartisan commented
/build-deploy-preview env=release

2023-07-25 07:03 UTC, jsartisan commented
/ok-to-test

2023-07-25 10:19 UTC, KelvinOm approved these changes

2023-07-25 11:01 UTC, jsartisan commented
/ok-to-test

2023-07-25 12:07 UTC, jsartisan commented
/ok-to-test

2023-07-26 10:58 UTC, jsartisan commented
/ok-to-test

2023-07-26 11:09 UTC, jsartisan commented
/ok-to-test

2023-07-26 12:37 UTC, KelvinOm approved these changes

2023-07-26 12:40 UTC, merged