chore: Refactors hide embed share setting flag.
appsmithorg/appsmith pull request #25284
Opened 2023-07-11 06:46 UTC by rahulbarwal

## Description
As we are deprecating FF4J system in favour of flagsmith. 
This PR renames APP_EMBED_VIEW_HIDE_SHARE_SETTINGS_VISIBILITY to release_embed_hide_share_settings_enabled
#### PR fixes following issue(s)
Fixes #25232 
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
#### Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video
>
>
#### Type of change
- Chore (housekeeping or task changes that don't impact user perception)

## Testing
>
#### How Has This Been Tested?
- [x] Cypress
>
>
#### Test Plan
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-07-11 06:49 UTC, rahulbarwal commented
/ok-to-test

2023-07-11 10:12 UTC, hetunandu requested changes

2023-07-11 10:12 UTC, hetunandu commented on app/server/appsmith-server/src/main/resources/features/init-flags.xml
> +        <feature uid="release_embed_hide_share_settings_enabled" enable="true"
You should remove this entry from this file

2023-07-11 10:22 UTC, rahulbarwal commented on app/server/appsmith-server/src/main/resources/features/init-flags.xml
> +        <feature uid="release_embed_hide_share_settings_enabled" enable="true"
done.

2023-07-11 10:29 UTC, hetunandu submitted a review, later dismissed

2023-07-11 11:11 UTC, rahulbarwal commented
/build-deploy-preview env=release

2023-07-11 11:54 UTC, rahulbarwal commented
Hey @shwetha-ramesh , 

This just moves flag to flagsmith. It is to be tested similar to this: https://github.com/appsmithorg/appsmith/pull/24561#issuecomment-1594395091

2023-07-12 09:22 UTC, shwetha-ramesh commented
@rahulbarwal QA Done

2023-07-12 10:59 UTC, hetunandu commented on app/client/src/ce/entities/FeatureFlag.ts
> +export const AB_TESTING_EVENT_KEYS = {
What is this used for?

2023-07-12 11:02 UTC, rahulbarwal commented on app/client/src/ce/entities/FeatureFlag.ts
> +export const AB_TESTING_EVENT_KEYS = {
This came in with release merge, PR #25126

2023-07-12 11:28 UTC, hetunandu approved these changes

2023-07-12 13:49 UTC, merged