feat: Build push and deploy from Github branch #Hackathon
appsmithorg/appsmith pull request #25357
Opened 2023-07-13 12:23 UTC by sum35h

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.
>
## Description
> Add a TL;DR when description is extra long (helps content team)
>
> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change
>
> Links to Notion, Figma or any other documents that might be relevant to the PR
>
>
#### PR fixes following issue(s)
Fixes # (issue number)
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
#### Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video
>
>
#### Type of change
> Please delete options that are not relevant.
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
## Testing
>
#### How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Also list any relevant details for your test configuration.
> Delete anything that is not relevant
- [ ] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-07-21 02:42 UTC, sharat87 commented
@sum35h, do we intend to use this? My understanding was that triggering the workflow via API wasn't working very well, so we're not doing that and instead running it via the ops API? 🤔

2023-07-28 05:47 UTC, sum35h commented
/ok-to-test

2023-07-28 05:54 UTC, sum35h commented
> @sum35h, do we intend to use this? My understanding was that triggering the workflow via API wasn't working very well, so we're not doing that and instead running it via the ops API? 🤔

The ops API was only a workaround for the Hackathon demo, since building the image takes a lot of time (min 45 mins).
I'm planning to use this workflow  going forward, and will also use the Ops API to trigger this.

2023-07-28 07:27 UTC, sharat87 requested changes

2023-07-28 07:27 UTC, sharat87 commented on .github/workflows/ad-hoc-deploy-preview.yml
> +                                                                )'
Did we get a chance to test this code? Doesn't look like it'll do what's intended.

2023-07-28 07:27 UTC, sharat87 commented on .github/workflows/ad-hoc-deploy-preview.yml
Can we reuse the `server-build.yml` and others instead of writing the workflow code for those steps here as well?

2023-07-28 07:27 UTC, sharat87 commented on scripts/build_dp_from_branch.sh
> +aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" > ~/.aws/credentials
Can we avoid writing to default configuration files when possible please? We should be able to get the same affect even if we don't have this here.

```suggestion
```

2023-07-28 07:56 UTC, sum35h commented on .github/workflows/ad-hoc-deploy-preview.yml
Due to the checkout step which uses` github.event.inputs.branch` unlike the `pr no` in workflows like `server-build.yml`, those will need to be edited to build from branch variable, if it is to be used in this workflow. Hence , went with writing these jobs again despite redundancy.

2023-07-28 07:59 UTC, sum35h commented on .github/workflows/ad-hoc-deploy-preview.yml
> +                                                                )'
```suggestion
         # mongosh '' --eval 'db.appsmiht-ce-github-dp-runs.update(
                                                                 # { _id:  ${{ github.event.inputs.uid }} },
                                                                 # {
                                                                  #  $set: {
                                                                 #     status: "DEPLOYMENT IN PROGRESS"
                                                                #    }
                                                                #  }
                                                            #    )'
```

2023-07-28 07:59 UTC, sum35h commented on .github/workflows/ad-hoc-deploy-preview.yml
> +                                                                )'
This was supposed to be commented and tried later. I've commented it now.

2023-07-28 09:00 UTC, sum35h commented on .github/workflows/ad-hoc-deploy-preview.yml
I'm Modifying dependent jobs to checkout branch.

2023-07-28 09:25 UTC, sum35h commented on .github/workflows/ad-hoc-deploy-preview.yml
Done.

2023-07-28 10:07 UTC, sharat87 approved these changes

2023-07-28 10:15 UTC, sum35h commented
/ok-to-test

2023-07-28 12:21 UTC, sum35h commented
/build-deploy-preview skipTests=true

2023-07-31 07:57 UTC, merged