fix: auto toggle js to normal on click of connect data in table widget
appsmithorg/appsmith pull request #25391
Opened 2023-07-17 09:27 UTC by berzerkeer

## Description
- When we click on connect data on table widget, if the prop pane data field is in JS mode and no binding value has been set , it should switch to normal mode automatically.

#### PR fixes following issue(s)
Fixes # (issue number)
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
#### Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video
>
>
#### Type of change
> Please delete options that are not relevant.
- Bug fix (non-breaking change which fixes an issue)

>
>
>
## Testing
>
#### How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Also list any relevant details for your test configuration.
> Delete anything that is not relevant
- [s] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-07-17 09:30 UTC, berzerkeer commented
/ok-to-test

2023-07-17 09:30 UTC, berzerkeer commented
/build-deploy-preview

2023-07-17 17:50 UTC, rahulramesha requested changes

2023-07-18 06:48 UTC, berzerkeer commented on app/client/src/pages/Editor/PropertyPane/PropertyControl.tsx
> +      propertyName === "tableData" &&
I don't get it, will DM you in slack. 😅

2023-07-19 05:17 UTC, rahulramesha requested changes

2023-07-19 05:17 UTC, rahulramesha commented on app/client/src/widgets/TableWidgetV2/widget/propertyConfig/contentConfig.ts
> +          propertyName === "tableData" &&
no need for propertyName check here

2023-07-19 05:17 UTC, rahulramesha commented on app/client/src/widgets/TableWidgetV2/widget/propertyConfig/contentConfig.ts
> +        switchToNormalMode: (
could you change the name to something like, `shouldSwitchToNormalMode`

2023-07-19 05:17 UTC, rahulramesha commented on app/client/src/constants/PropertyControlConstants.tsx
> +    triggerFlag: boolean,
Could you move the trigger flag as the last argument and make it optional? So that in the future it can be used without the last argument..

2023-07-19 05:49 UTC, berzerkeer commented
/build-deploy-preview

2023-07-19 05:50 UTC, berzerkeer commented
/ok-to-test

2023-07-19 05:54 UTC, rahulramesha submitted a review, later dismissed

2023-07-19 06:22 UTC, rahulramesha approved these changes

2023-07-19 06:24 UTC, berzerkeer commented
/ok-to-test

2023-07-19 06:25 UTC, berzerkeer commented
/build-deploy-preview

2023-07-19 06:37 UTC, Aishwarya-U-R commented
/ok-to-test

2023-07-19 06:43 UTC, Aishwarya-U-R commented
/ok-to-test

2023-07-20 06:55 UTC, laveena-en commented
Verified, PR looks good to me!

2023-07-20 10:05 UTC, berzerkeer commented
/ok-to-test

2023-07-20 14:03 UTC, merged