chore: Add Interaction tests for hover + focus state
appsmithorg/appsmith pull request #25427
Opened 2023-07-18 05:51 UTC by jsartisan

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.
>
## Description
> Add a TL;DR when description is extra long (helps content team)
>
> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change
>
> Links to Notion, Figma or any other documents that might be relevant to the PR
>
>
#### PR fixes following issue(s)
Fixes # (issue number)
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
#### Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video
>
>
#### Type of change
> Please delete options that are not relevant.
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
## Testing
>
#### How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Also list any relevant details for your test configuration.
> Delete anything that is not relevant
- [ ] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-07-18 16:23 UTC, KelvinOm requested changes

2023-07-18 16:23 UTC, KelvinOm commented on app/client/packages/design-system/widgets/src/components/Button/index.styled.tsx
> +        &:active:not([aria-disabled]) {
1. I believe that we should not modify components just for testing purposes.  I think we can sacrifice the active state and test only [hover and focus states](https://www.chromatic.com/docs/hoverfocus).
2. Also, I would not want the stories for testing to leak into the docs one, they either have to be invisible to the docs consumer or we have to separate them somehow.

2023-07-19 05:33 UTC, jsartisan commented on app/client/packages/design-system/widgets/src/components/Button/index.styled.tsx
> +        &:active:not([aria-disabled]) {
I would disagree here. If a small change in our code helps us to avoid any regression in UI, I would do it.
Anyway, I have incorporated the changes you suggested.
Removed the code I added for the active state
Used interaction tests with the 'play' function for hover and active
Hide the story in docs table for hover and active ( as they are for testing purposes )

2023-07-19 13:17 UTC, KelvinOm requested changes
We discussed the approach to the tests in direct messages, it is necessary to make changes.

2023-08-01 06:48 UTC, closed without merging