Added page not found page in API editor and Datasource editor
appsmithorg/appsmith pull request #2547
Opened 2021-01-13 06:27 UTC by vicky-primathon

## Description
Added not found page to be displayed when resource does not exist.

Fixes # (issue)

## Type of change
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
- Manually tested

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-01-13 09:05 UTC, riodeuno requested changes

2021-01-13 09:05 UTC, riodeuno commented on app/client/src/actions/datasourceActions.ts
> +  console.log({ type: ReduxActionTypes.FETCH_DATASOURCE_STRUCTURE_INIT, id });
missed console.log

2021-01-13 09:05 UTC, riodeuno commented on app/client/src/pages/Editor/PageNotFound.tsx
> +import React from "react";
Let's rename this to `EntityNotFoundPane`

2021-01-19 05:37 UTC, riodeuno submitted a review, later dismissed

2021-01-22 09:34 UTC, riodeuno commented
Please use the new designs for the Entity not found page. https://www.figma.com/file/a9VOA3LPsaBvDHYxcNs19Z/Generic-Error-State?node-id=0%3A1

2021-01-25 09:54 UTC, riodeuno requested changes

2021-01-25 09:54 UTC, riodeuno commented on app/client/src/pages/Editor/EntityNotFoundPane.tsx
> +          The page you’re looking for either does not exist, or cannot be found
Please use the `messages.ts` file for the copy.

2021-01-25 09:54 UTC, riodeuno commented on app/client/src/pages/Editor/EntityNotFoundPane.tsx
>            onClick={() => history.goBack()}
Does a simple `onClick={history.goBack}` work in this scenario?

2021-01-25 11:33 UTC, vicky-primathon commented on app/client/src/pages/Editor/EntityNotFoundPane.tsx
>            onClick={() => history.goBack()}
Yes onClick={history.goBack} is working, updated the code

2021-01-27 05:35 UTC, riodeuno approved these changes

2021-01-27 06:56 UTC, merged