fix: File lock issue git
appsmithorg/appsmith pull request #25504
Opened 2023-07-19 19:52 UTC by AnaghHegde

## Description

#### PR fixes following issue(s)
Fixes https://github.com/appsmithorg/appsmith/issues/24854

#### Type of change
- Bug fix (non-breaking change which fixes an issue)

## Testing
>
#### How Has This Been Tested?
- [ ] Manual

#### Test Plan

#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-07-19 21:09 UTC, AnaghHegde commented
/ok-to-test

2023-07-19 21:40 UTC, AnaghHegde commented
/build-deploy-preview

2023-07-21 06:13 UTC, nayan-rafiq approved these changes

2023-07-21 10:48 UTC, AnaghHegde commented
/build-deploy-preview

2023-07-24 04:48 UTC, nayan-rafiq approved these changes

2023-07-25 05:00 UTC, AnaghHegde commented
/build-deploy-preview

2023-07-25 06:13 UTC, AnaghHegde commented
/build-deploy-preview

2023-07-26 11:31 UTC, AnaghHegde commented
/build-deploy-preview

2023-07-26 13:36 UTC, AnaghHegde commented
/build-deploy-preview

2023-07-27 05:10 UTC, AnaghHegde commented
/ok-to-test

2023-07-27 05:57 UTC, nayan-rafiq requested changes
I recommend to add some unit tests for this.

2023-07-27 05:57 UTC, nayan-rafiq commented on app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/FileUtilsImpl.java
> +    public Mono<Long> deleteIndexLockFile(Path path, int validTime) {
```suggestion
    public Mono<Long> deleteIndexLockFile(Path path, int validTimeInSeconds) {
```

2023-07-27 05:57 UTC, nayan-rafiq commented on app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/FileUtilsImpl.java
> +            Instant validCreateTime = now.minusSeconds(validTime);
```suggestion
            Instant validCreateTime = now.minusSeconds(validTimeInSeconds);
```

2023-07-27 05:57 UTC, nayan-rafiq commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/git/FileInterface.java
> +    Mono<Long> deleteIndexLockFile(Path path, int validTime);
```suggestion
    Mono<Long> deleteIndexLockFile(Path path, int validTimeInSeconds);
```

2023-07-27 05:57 UTC, nayan-rafiq commented on app/server/appsmith-server/src/main/java/com/appsmith/server/exceptions/GlobalExceptionHandler.java
> +        // lockFailedException
```suggestion
```

2023-07-27 05:57 UTC, nayan-rafiq commented on app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/GitFileUtils.java
> +    public static final int INDEX_LOCK_FILE_STALE_TIME = 900;
```suggestion
    public static final int INDEX_LOCK_FILE_STALE_TIME = 900; // number of seconds after lock file is stale
```

2023-07-27 07:20 UTC, AnaghHegde commented
/ok-to-test

2023-07-27 08:31 UTC, Parthvi12 approved these changes

2023-07-27 10:23 UTC, AnaghHegde commented
@Aishwarya-U-R Its not possible to add a server side test case for this scenario.

2023-07-27 10:24 UTC, merged