added mongo version check on startup and shown alert conditionally wi…
appsmithorg/appsmith pull request #25611
Opened 2023-07-22 18:29 UTC by tkAppsmith

## Description
> Added version check of connected mongo db instance at app startup and set to common config to be used to show message conditionally.
#### PR fixes following issue(s)
Fixes #25610 
#### Type of change
- New feature (non-breaking change which adds functionality)
## Testing
>
#### How Has This Been Tested?
- [x] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Test Plan
> Connect a db version below 5 and you should see the alert message
> Connect a db version above 5 and you should not see the alert message
> You should not see the alert message on cloud instance
## Checklist:
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-07-23 04:56 UTC, sharat87 requested changes
Few minor changes and we should be ready.

2023-07-23 04:56 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/CommonConfig.java
> +    public Boolean isMongoUptoDate() {
This never returns `null`, so let's use the unboxed `boolean`.

```suggestion
    public boolean isMongoUptoDate() {
```

2023-07-23 04:56 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/CommonConfig.java
> +    public Boolean isConnectedMongoVersionAvailable() {
This never returns `null`, so let's use the unboxed `boolean`.

```suggestion
    public boolean isConnectedMongoVersionAvailable() {
```

2023-07-23 04:56 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/CommonConfig.java
> +    private String minSupportedMongoVersion;
I don't think we need this to be configurable. Let's make it a constant instead please.

```suggestion
    private static final String MIN_SUPPORTED_MONGODB_VERSION = 5;
```

We'll need to rename the variable where it's used as well.

2023-07-23 04:56 UTC, sharat87 commented on app/server/appsmith-server/src/main/resources/productAlerts/productAlertMessages.yml
Can we change this a cleaner YAML file please? Like, without all the braces, square brackets, quotes, backslashes... it's so hard to read/follow/edit what's in this file. 🙏

```yaml
productalertmessages:

  - messageId: "1"
    title: "You seem to be using an unsupported MongoDB version."
    message: >
      Appsmith now supports only MongoDB versions 5.x or higher. For self-managed MongoDB, upgrade to v5.x or higher.
      If you don't have self-managed MongoDB, just upgrade your Appsmith version to the latest.
      This is a mandatory checkpoint before you can use your Appsmith instance again.
    learnMoreLink: "https://www.mongodb.com/docs/manual/release-notes/5.0-upgrade-replica-set"
    canDismiss: true
    remindLaterDays: 5
    context: "COMMON_CONFIG"
    applicabilityExpression: "!isCloudHosting && !isMongoUptoDate"
    precedenceIndex: 1

  - messageId: "2"
    title: "Appsmith was not able to detect your current mongo version. You may be using an unsupported MongoDB version."
    message: >
      Appsmith now supports only MongoDB versions 5.x or higher. For self-managed MongoDB, upgrade to v5.x or higher.
      If you don't have self-managed MongoDB, just upgrade your Appsmith version to the latest.
      This is a mandatory checkpoint before you can use your Appsmith instance again.
    learnMoreLink: "https://www.mongodb.com/docs/manual/release-notes/5.0-upgrade-replica-set"
    canDismiss: true
    remindLaterDays: 5
    context: "COMMON_CONFIG"
    applicabilityExpression: "!isCloudHosting && !isConnectedMongoVersionAvailable"
    precedenceIndex: 2

```

2023-07-23 04:56 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/ce/InstanceConfigHelperCEImpl.java
> +    }
Can we do this check without establishing a new MongoDB connection, since we're already connected to it? Let's inject the `ReactiveMongoTemplate` bean into this class and [do something like this](https://github.com/appsmithorg/appsmith/pull/19521/files#diff-cf760556281bf144cec839574cc9d748ae79377df2f6e2c35610ea064ab7a345R30) to get the version number to compare with.

2023-07-24 04:43 UTC, tkAppsmith commented on app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/InstanceConfig.java
> +
@sharat87 I need help here. Without this it seems like the call to version check method is hanged up indefinitely and callbacks are not getting executed. Can you help me around this as how to write this fire and forget code that acually gets executed. .subscribeOn(scheduler) where scheduler = Schedulers.immediate() also didnt help.

2023-07-24 04:57 UTC, sharat87 requested changes

2023-07-24 04:57 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/InstanceConfig.java
> +
Hook it into the `startupProcess` below. Change it to something like this:

```java

        Mono<?> startupProcess = instanceConfigHelper
                .checkMongoDBVersion()
                .flatMap(ignored -> instanceConfigHelper.checkInstanceSchemaVersion())
                .flatMap(signal -> registrationAndRtsCheckMono)
                // Prefill the server cache with anonymous user permission group ids.
                .then(cacheableRepositoryHelper.preFillAnonymousUserPermissionGroupIdsCache())
                // Add cold publisher as we have dependency on the instance registration
                .then(Mono.defer(instanceConfigHelper::isLicenseValid));
```

I think this is what you need.

2023-07-24 04:57 UTC, sharat87 commented on app/server/appsmith-server/src/main/resources/application.properties
> +appsmith.productalert.minsupportedmongoversion=${APPSMITH_MIN_MONGO_VERSION:5}
We don't need this anymore I think.

2023-07-28 06:01 UTC, tkAppsmith commented
/ok-to-test

2023-07-28 07:36 UTC, tkAppsmith commented
/build-deploy-preview

2023-07-28 09:52 UTC, tkAppsmith commented
/ok-to-test

2023-07-28 09:52 UTC, tkAppsmith commented
/build-deploy-preview

2023-07-28 10:31 UTC, sharat87 approved these changes

2023-07-28 10:32 UTC, merged