feat: default camera config for camera widget
appsmithorg/appsmith pull request #25676
Opened 2023-07-25 08:00 UTC by berzerkeer

## Description
- Camera widget now defaults to back camera. Also a new control is added to property pane to select whether the camera should default to back camera or front.

Fixes #21554 
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
#### Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video
>
>
#### Type of change
- New feature (non-breaking change which adds functionality)

## Testing
>
#### How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Also list any relevant details for your test configuration.
> Delete anything that is not relevant
- [x] Manual
- [x] Jest
- [x] Cypress
>
>
#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-07-25 08:00 UTC, berzerkeer commented
/build-deploy-preview env=release

2023-07-25 08:53 UTC, berzerkeer commented
/ok-to-test

2023-07-26 07:09 UTC, berzerkeer commented
/ok-to-test

2023-07-26 07:09 UTC, berzerkeer commented
/build-deploy-preview

2023-07-26 09:58 UTC, rajatagrawal requested changes

2023-07-26 09:58 UTC, rajatagrawal commented on app/client/src/widgets/CameraWidget/widget/index.tsx
> +              "Default choice for mobile users. Not applicable for other devices",
Can we put this in messages.ts file please ?

2023-07-26 09:58 UTC, rajatagrawal commented on app/client/src/widgets/CameraWidget/widget/index.tsx
> +                label: "Front (Selfie)",
This can be moved to messages.ts file as well.

2023-07-26 09:59 UTC, berzerkeer commented on app/client/src/widgets/CameraWidget/widget/index.tsx
> +              "Default choice for mobile users. Not applicable for other devices",
my bad ! Sure !

2023-07-26 10:34 UTC, berzerkeer commented
/ok-to-test

2023-07-26 10:34 UTC, berzerkeer commented
/build-deploy-preview

2023-07-26 10:59 UTC, dhruvikn commented
Hey guys, a suggestion, can we also do this for the code scanner widget? 

cc: @dilippitchika

2023-07-26 11:22 UTC, rajatagrawal commented on app/client/src/widgets/CameraWidget/component/index.tsx
> +    setVideoConstraints({
There are no cypress tests for CameraWidget. Would like to suggest to write a cypress test and unit tests for it.

A suggested architecture to write requested tests:

1. A cypress to test that "Default Camera" dropdown shows up in UI and a relevant dom element shows up for that particular default camera drop down value.

2. Move videoConstraint configuration into a helper function and unit test the helper function.
2.1. Assert that appropriate configuration is returned when isMobile changes.
2.2 Assert that appropriate configuration is returned when defaultCamera prop changes.

All combinations don't need to be tested in cypress. A combination of cypress and unit test would be an ideal flow.

2023-07-26 11:23 UTC, rajatagrawal requested changes
Request to add cypress/unit tests for Camera Widget

2023-07-26 11:30 UTC, berzerkeer commented on app/client/src/widgets/CameraWidget/component/index.tsx
> +    setVideoConstraints({
Sure, the scope of this task was to just add an option to let the user select a default camera for mobile devices. 

So I think I can either increase the story points for this task to add the tests ( since I estimated it only for the new functionality ) or we can create a new task for tests separately. 

So how to go about this ?

2023-07-27 05:57 UTC, berzerkeer commented
/ok-to-test

2023-07-27 05:57 UTC, berzerkeer commented
/build-deploy-preview

2023-07-27 06:00 UTC, berzerkeer commented
/ok-to-test

2023-07-27 06:43 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ClientSide/Widgets/Camera/CameraWidgetSpec.ts
> +    entityExplorer.SelectEntityByName("Camera1", "Widgets");
When dragDropped - widget property is already in open state. This is not needed.

2023-07-27 06:43 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ClientSide/Widgets/Camera/CameraWidgetSpec.ts
> +    );
Also can validate the dropdown values using - `propPane.AssertPropertiesDropDownValues`
This method is in one of my open PR, will be merged soon.

2023-07-27 07:07 UTC, rajatagrawal approved these changes

2023-07-27 08:49 UTC, berzerkeer commented
/ok-to-test

2023-07-27 09:04 UTC, Aishwarya-U-R reviewed
Approving Cypress changes.

2023-07-27 09:05 UTC, rajatagrawal approved these changes

2023-07-28 07:49 UTC, chandannkumar commented
@berzerkeer Observation:
**On Android device -**
- The rear camera is not working when back camera is set as default, even though the permission is granted for camera and mic
![Screenshot_2023-07-28-13-15-27-384_com.android.chrome.jpg](https://images.zenhubusercontent.com/61e65341d503e6aafa5df216/4b3287a0-586e-43d3-9533-eb2d3b5d7143)

**On iPhone -**
- Bottom Buttons icons are not visible like  fullscreen, camera switch, microphone etc
![IMG_2921.png](https://images.zenhubusercontent.com/61e65341d503e6aafa5df216/efbf50d0-25b8-4f59-b85e-660f3148e9d8)

2023-07-28 12:33 UTC, berzerkeer commented
/build-deploy-preview

2023-07-28 12:33 UTC, berzerkeer commented
/ok-to-test

2023-07-31 04:55 UTC, rajatagrawal approved these changes

2023-07-31 08:51 UTC, chandannkumar commented
Tested this PR and LGTM
- Tested camera widget default feature
- Tested on older apps

2023-08-01 04:53 UTC, merged