feat: enabled server side filtering for table widget
appsmithorg/appsmith pull request #25732
Opened 2023-07-26 11:30 UTC by keyurparalkar

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.
>
## Description
> Add a TL;DR when description is extra long (helps content team)
>
> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change
>
> Links to Notion, Figma or any other documents that might be relevant to the PR
>
>
#### PR fixes following issue(s)
Fixes # (issue number)
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
#### Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video
>
>
#### Type of change
> Please delete options that are not relevant.
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
## Testing
>
#### How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Also list any relevant details for your test configuration.
> Delete anything that is not relevant
- [ ] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-07-26 11:45 UTC, keyurparalkar commented
/ok-to-test

2023-07-26 11:45 UTC, keyurparalkar commented
/build-deploy-preview skip-tests=true

2023-07-27 07:40 UTC, sbalaji1192 commented on app/client/src/widgets/TableWidgetV2/component/header/actions/filter/CascadeFields.tsx
> +      payload: Number(value) || value,
Use trenary operator here

2023-07-27 07:40 UTC, sbalaji1192 commented on app/client/src/widgets/TableWidgetV2/widget/derived.js
> +      /* prevent client-side filtering when server side filtering is enabled */
merge this to if statement below

2023-07-27 07:40 UTC, sbalaji1192 commented on app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/server_side_filtering_spec_1.ts
> +describe("Table widget v2: test server side filtering", function () {
We can just test the following
1. should not filter when serverside filtering is turned on.
2. should filter when serverside filtering is turned off.
3. onTableFilterUpdate should appear when on and gets executed only when its turned on.

2023-07-27 07:40 UTC, sbalaji1192 commented on app/client/src/widgets/TableWidgetV2/widget/index.tsx
> +    pushBatchMetaUpdates("filters", filters, {
should not fire when the flag is turned off.

2023-07-27 11:03 UTC, keyurparalkar commented
/ok-to-test

2023-07-27 11:03 UTC, keyurparalkar commented
/build-deploy-preview skip-tests=true

2023-07-28 08:03 UTC, sbalaji1192 approved these changes

2023-07-28 10:25 UTC, keyurparalkar commented
/ok-to-test

2023-07-28 10:25 UTC, keyurparalkar commented
/build-deploy-preview skip-tests=true

2023-07-28 18:08 UTC, sbalaji1192 submitted a review, later dismissed

2023-07-31 05:19 UTC, keyurparalkar commented
/build-deploy-preview skip-tests=true

2023-07-31 06:37 UTC, keyurparalkar commented
/build-deploy-preview env=release

2023-07-31 06:39 UTC, keyurparalkar commented
/build-deploy-preview skip-tests=true recreate=true

2023-07-31 06:42 UTC, keyurparalkar commented
/build-deploy-preview env=release

2023-07-31 07:00 UTC, keyurparalkar commented
/build-deploy-preview env=release

2023-07-31 07:27 UTC, keyurparalkar commented
/build-deploy-preview skip-tests=true

2023-07-31 13:06 UTC, laveena-en commented
@keyurparalkar Internal server error is being thrown on the latest DP. Can you please check? 
<img width="1440" alt="image" src="https://github.com/appsmithorg/appsmith/assets/109572422/fc21b67e-6c6a-43a1-84d6-829da05cfda4">

2023-07-31 13:15 UTC, chandannkumar commented
@keyurparalkar 
- Apply button is not working when Server side filtering is enabled
 https://www.loom.com/share/9e43b2f43bec4fb1ad847c8c2d931e01?sid=2a61c54b-467a-4e96-8be4-0ba7e285fcdd

2023-08-02 07:28 UTC, keyurparalkar commented
/ok-to-test

2023-08-02 10:53 UTC, sbalaji1192 approved these changes

2023-08-02 11:44 UTC, keyurparalkar commented
/build-deploy-preview skip-tests=true

2023-08-03 10:01 UTC, keyurparalkar commented
/perf-test

2023-08-03 10:52 UTC, keyurparalkar commented
/build-deploy-preview skip-tests=true

2023-08-03 13:06 UTC, chandannkumar commented
Tested the following and LGTM

- Tested the filter apply button text color should be clear and visible
- Tested the value property of table.filters is number when number is provided inside the filter.
- Tested client side filtering is disabled when server side filtering is enabled
- Tested filters property appears as an autocomplete.
- All the cases mentioned in this [test plan](https://docs.google.com/spreadsheets/d/1TgKPH5XPzIuaHAPooYr5o5jrhpjxFhBTq_Q6wv5rnVk/edit#gid=1701564241)

2023-08-21 05:56 UTC, keyurparalkar commented
/ok-to-test

2023-08-21 06:01 UTC, marks0351 requested changes

2023-08-21 06:01 UTC, marks0351 commented on app/client/src/widgets/BaseWidget.tsx
> +  static getFeatureFlag(featureFlag: FeatureFlag) {
can we pls avoid adding this in basewidget, instead add this to EditorContextProvider.

2023-08-21 09:36 UTC, keyurparalkar commented on app/client/src/widgets/BaseWidget.tsx
> +  static getFeatureFlag(featureFlag: FeatureFlag) {
@marks0351 this is a temporary change. Since we need this function to be static therefore we cannot use it in editorContextProvider. 

We will be raising a different PR to fix this later.

CC: @sbalaji1192

2023-08-21 10:12 UTC, marks0351 commented on app/client/src/widgets/BaseWidget.tsx
> +  static getFeatureFlag(featureFlag: FeatureFlag) {
can you pls let me know why we want to fix it in a different pr and not this one?

2023-08-21 10:43 UTC, keyurparalkar commented on app/client/src/widgets/BaseWidget.tsx
> +  static getFeatureFlag(featureFlag: FeatureFlag) {
@marks0351 we have to figure out a proper way to inject platform configurations like env and feature flags into the widgets. So we will work on that in a separate PR.

CC: @sbalaji1192

2023-08-21 10:49 UTC, marks0351 commented on app/client/src/widgets/BaseWidget.tsx
> +  static getFeatureFlag(featureFlag: FeatureFlag) {
can you pls create an issue for this.
If this is not a critical fix or feature, I would highly recommend we fix the implementation and then merge the pr.

2023-08-21 10:50 UTC, marks0351 submitted a review, later dismissed

2023-08-21 11:08 UTC, keyurparalkar commented on app/client/src/widgets/BaseWidget.tsx
> +  static getFeatureFlag(featureFlag: FeatureFlag) {
I have created a new request [here](https://github.com/appsmithorg/appsmith/issues/26523).

2023-08-21 11:54 UTC, Aishwarya-U-R commented
@keyurparalkar - Please [fix this issue](https://cloud.cypress.io/projects/eyxvp8/runs/39126/test-results?actions=%5B%5D&browsers=%5B%5D&groups=%5B%5D&isFlaky=%5B%5D&modificationDateRange=%7B%22startDate%22%3A%221970-01-01%22%2C%22endDate%22%3A%222038-01-19%22%7D&orderBy=EXECUTION_ORDER&oses=%5B%5D&specs=%5B%5D&statuses=%5B%5D&testingTypesEnum=%5B%5D) & then trigger new run in this PR:
<img width="1052" alt="Screenshot 2023-08-21 at 5 22 47 PM" src="https://github.com/appsmithorg/appsmith/assets/91450662/210cf749-8bcf-403a-94f9-7087977e0171">

2023-08-22 07:05 UTC, keyurparalkar commented
/ok-to-test

2023-08-22 07:14 UTC, keyurparalkar commented
/ok-to-test

2023-08-22 11:23 UTC, NandanAnantharamu approved these changes
lgtm

2023-08-22 11:27 UTC, merged

2024-06-19 10:58 UTC, akshayvijayjain commented
/coderabbit review