feat: Integrated features API to Appsmith
appsmithorg/appsmith pull request #25761
Opened 2023-07-26 20:13 UTC by vishnu-gp

## Description
Added features API to the instance for enabling and disabling features

#### PR fixes following issue(s)
Fixes https://github.com/appsmithorg/appsmith-ee/issues/1887
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
#### Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video
>
>
#### Type of change
> Please delete options that are not relevant.
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
## Testing
>
#### How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Also list any relevant details for your test configuration.
> Delete anything that is not relevant
- [ ] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-07-27 05:15 UTC, NilanshBansal commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/CacheableFeatureFlagHelperCEImpl.java
> +                        return clientResponse.createError();
Can we send an empty response from here, if CS is not reachable. I need to handle this in the user feature flagging system as well. Can you implement this.
Ref thread: https://theappsmith.slack.com/archives/C04H5PFRN1H/p1690380012513319?thread_ts=1690376124.426829&cid=C04H5PFRN1H

2023-07-27 05:26 UTC, NilanshBansal commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/CacheableFeatureFlagHelperCEImpl.java
> +                        return clientResponse.createError();
not required @vishnu-gp pls ignore

2023-07-27 07:56 UTC, abhvsn requested changes
Added some comments

2023-07-27 07:56 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/FeatureFlagServiceCEImpl.java
> +                            .evictTenantCachedFeatures(defaultTenantId)
Instead of evicting the cache can we update the same key entry with updated value? Asking this to keep the implementation failsafe in case call to CS or Flagsmith doesn't go through.

2023-07-27 07:56 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/PingScheduledTaskCEImpl.java
> +                .doOnError(error -> log.error("Error sending anonymous counts {0}", error))
Didn't get the context for this error, should it be "Error while fetching the feature flags for tenant {tenantId} {error_details}"

2023-07-27 07:56 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/PingScheduledTaskCEImpl.java
>  }
This bean is invoked if the instance is self-hosted, we need the flags for cloud instance as well right?

2023-07-27 20:39 UTC, vishnu-gp commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/FeatureFlagServiceCEImpl.java
> +                            .evictTenantCachedFeatures(defaultTenantId)
We might need to store the current features in DB for safe migrations. Let's take up this in a separate PR and unblock FE on the features API

2023-07-27 20:39 UTC, vishnu-gp commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/PingScheduledTaskCEImpl.java
> +                .doOnError(error -> log.error("Error sending anonymous counts {0}", error))
Corrected

2023-07-27 20:39 UTC, vishnu-gp commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/PingScheduledTaskCEImpl.java
>  }
Added a separate Scheduler class

2023-07-27 21:10 UTC, vishnu-gp commented
/ok-to-test

2023-07-27 21:44 UTC, vishnu-gp commented
/ok-to-test

2023-07-28 04:49 UTC, vishnu-gp commented
/ok-to-test

2023-07-28 05:19 UTC, vishnu-gp commented
/ok-to-test

2023-07-28 07:45 UTC, abhvsn reviewed
Few comments to improve but overall LGTM

2023-07-28 07:45 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/TenantControllerCE.java
> +        this.featureFlagService = featureFlagService;
Can we remove this if not needed?

2023-07-28 07:45 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/featureflags/CachedFeatures.java
> +    Instant refreshedAt;
I guess we are going to have a different entries in Redis for tenant level features as discussed. Also if we are going to add this as a separate entry in Redis let's not add the field in this PR otherwise you will have to invalidate the earlier entry.

2023-07-28 07:45 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/CacheableFeatureFlagHelperCEImpl.java
> +                                new ParameterizedTypeReference<ResponseDTO<Map<String, Map<String, Boolean>>>>() {});
Can we please have a seperate DTO object which can be scaled once we start putting in more fields in CS features response API.

2023-07-28 07:45 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/PingScheduledTaskCEImpl.java
> +    private final FeatureFlagService featureFlagService;
Let's remove this is not using in this class.

2023-07-30 12:44 UTC, NilanshBansal requested changes

2023-07-30 12:44 UTC, NilanshBansal commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ScheduledTaskCEImpl.java
> +    @Scheduled(initialDelay = 10 * 1000 /* ten seconds */, fixedRate = 2 * 60 * 60 * 1000 /* two hours */)
@vishnu-gp @abhvsn why are we using a scheduler to make the requests? Can this not be on-demand similar to the user-based features?

Invoking the features through scheduler will result in an increase in the number of flagsmith requests.

2023-07-30 16:42 UTC, vishnu-gp commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/CacheableFeatureFlagHelperCEImpl.java
> +    @Cache(cacheName = "features", key = "{#tenantId}")
Yes. We have decided to use two different caches. I will rename it to `tenantCurrentFeatures` and `tenantNewFeatures`

2023-07-30 16:46 UTC, vishnu-gp commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ScheduledTaskCEImpl.java
> +    @Scheduled(initialDelay = 10 * 1000 /* ten seconds */, fixedRate = 2 * 60 * 60 * 1000 /* two hours */)
Since the product requires to have the newly added features to reach all running instances at most in two hours and run the migrations we decided to go ahead with the scheduled task. Also, we never evict the cache but always update the cache with the latest features

2023-07-30 17:29 UTC, vishnu-gp commented on app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/TenantControllerCE.java
> +        this.featureFlagService = featureFlagService;
Done

2023-07-30 17:29 UTC, vishnu-gp commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/PingScheduledTaskCEImpl.java
> +    private final FeatureFlagService featureFlagService;
done

2023-07-30 19:55 UTC, vishnu-gp commented on app/server/appsmith-server/src/main/java/com/appsmith/server/featureflags/CachedFeatures.java
> +    Instant refreshedAt;
Done

2023-07-30 19:55 UTC, vishnu-gp commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/CacheableFeatureFlagHelperCEImpl.java
> +                                new ParameterizedTypeReference<ResponseDTO<Map<String, Map<String, Boolean>>>>() {});
Done

2023-07-31 05:40 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ScheduledTaskCEImpl.java
> +    @Scheduled(initialDelay = 10 * 1000 /* ten seconds */, fixedRate = 2 * 60 * 60 * 1000 /* two hours */)
@NilanshBansal let's address the issue for increased calls to Flagsmith with a separate architecture altogeter. We should ideally never call Flagsmith unless it's required but we are still calling to get the features if cache entry is evicted for user level feature, hence webhooks will be a good solution for this. For tenant level feature we want to keep this detached from the user activity. If needed we will add a workflow to detect the tenant level activity which may or may not coincide with user activity going forward.

2023-07-31 05:53 UTC, abhvsn submitted a review, later dismissed

2023-07-31 06:07 UTC, NilanshBansal requested changes

2023-07-31 06:07 UTC, NilanshBansal commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ScheduledTaskCEImpl.java
> +    @Scheduled(initialDelay = 10 * 1000 /* ten seconds */, fixedRate = 2 * 60 * 60 * 1000 /* two hours */)
@vishnu-gp since multiple pods are running for a server and each pod will run this scheduled task, there will be overlapping calls to flagsmith within the 2 hour window. Can you pls add a check for `refreshedAt`in the `getAllRemoteFeaturesForTenant` function before evicting.

2023-07-31 06:07 UTC, NilanshBansal commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/FeatureFlagServiceCEImpl.java
> +                            .evictCachedTenantNewFeatures(defaultTenantId)
Pls add a check to validate if lastRefreshedAt is within the 2 hour window.

2023-07-31 08:22 UTC, vishnu-gp commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/FeatureFlagServiceCEImpl.java
> +                            .evictCachedTenantNewFeatures(defaultTenantId)
Done

2023-07-31 08:23 UTC, vishnu-gp commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ScheduledTaskCEImpl.java
> +    @Scheduled(initialDelay = 10 * 1000 /* ten seconds */, fixedRate = 2 * 60 * 60 * 1000 /* two hours */)
done

2023-07-31 08:24 UTC, vishnu-gp commented
/ok-to-test

2023-07-31 08:28 UTC, NilanshBansal approved these changes
LGTM

2023-07-31 09:34 UTC, merged