Fix - Changing column width changes adjacent column sorting order
appsmithorg/appsmith pull request #2580
Opened 2021-01-14 09:24 UTC by vicky-primathon

## Description
Changing column width changes adjacent column sorting order

Fixes #624 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manually tested

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-01-15 04:55 UTC, riodeuno requested changes

2021-01-15 04:55 UTC, riodeuno commented on app/client/src/components/designSystems/appsmith/TableUtilities.tsx
> +    if (props.isResizingColumn) return;
We need a way to disable this so that sorting is available.

2021-01-18 05:46 UTC, riodeuno commented on app/client/src/components/designSystems/appsmith/Table.tsx
> +import React, { useCallback } from "react";
Please remove this import of `useCallback` as it is unused.

2021-01-20 06:19 UTC, riodeuno submitted a review, later dismissed

2021-01-20 09:24 UTC, Nikhil-Nandagopal commented
Hey @riodeuno @vicky-primathon  I saw the PR for the column width interaction, it still doesn't work very well. When I drag a column to the right to increase it's width, the left also expands and crushes the columns to the left

2021-01-28 13:29 UTC, Nikhil-Nandagopal commented
![standup_query](https://user-images.githubusercontent.com/3897254/106144893-de750180-619a-11eb-9da1-52d0952a1d9d.gif)
There's a problem with the PR where the columns mismatch with the cells

2021-02-09 13:20 UTC, riodeuno commented on app/client/src/components/designSystems/appsmith/ReactTableComponent.tsx
> +  //       }
Please remove this commented set of lines

2021-02-10 09:48 UTC, riodeuno approved these changes

2021-02-10 10:10 UTC, Nikhil-Nandagopal requested changes
@vicky-primathon @riodeuno seeing a big issue on this deploy preview where new apps have a broken canvas

2021-02-11 05:57 UTC, Nikhil-Nandagopal approved these changes

2021-02-11 06:00 UTC, merged