APPSMTH-33 - [Task]:  Update the widget_resize_end event to contain the details of the table's scrollbar and pagesize
appsmithorg/appsmith pull request #25840
Opened 2023-07-31 08:58 UTC by gitstart-appsmith

## What does this PR do?
 * It updates the `WIDGET_RESIZE_END` event to contain the details of the table's scrollbar and pagesize
 
 ## Issue References
 * https://github.com/appsmithorg/appsmith/issues/25307

___
 
 This code was written and reviewed by GitStart Community. Growing future engineers, one PR at a time.

2023-08-07 07:17 UTC, keyurparalkar reviewed
@gitstart-appsmith to avoid firing WIDGET_RESIZE_END event twice, can you please execute the `logEvent` function mentioned in the `useEffect` below with a new event name: `TABLE_VERTICAL_SCROLL`.

2023-08-07 07:17 UTC, keyurparalkar commented on app/client/src/widgets/TableWidgetV2/component/Table.tsx
> +  const isTableResizing = useSelector(
@gitstart-appsmith usage of redux state directly inside the widget is an abstraction leak. All the props for a widget are provided by the platform via BaseWidget.

Can you please remove this line?

2023-08-07 07:17 UTC, keyurparalkar commented on app/client/src/widgets/TableWidgetV2/component/Table.tsx
> +  if (!isTableResizing) {
Instead of `if` block, execute the `logEvent` function of `AnalyticsUtils` inside a `useEffect` here with dependency array containing `bottomRow`, `topRow`, `leftColumn` and `rightColumn` props.

The props mentioned above are available as a prop to the widget. 

This approach will make sure that the event gets fired whenever the widget is resized

2023-08-07 07:17 UTC, keyurparalkar commented on app/client/src/widgets/TableWidgetV2/widget/index.tsx
> +  handleVerticalScrollVisibility = (isVisible: boolean) => {
This is not required since we are calling the analytics function inside the Table component

2023-08-07 07:17 UTC, keyurparalkar commented on app/client/src/widgets/TableWidgetV2/component/index.tsx
> +      next.handleVerticalScrollVisibility &&
This is not required since we are calling the analytics function inside the Table component

2023-08-07 11:40 UTC, gitstart-appsmith commented on app/client/src/widgets/TableWidgetV2/component/Table.tsx
> +  if (!isTableResizing) {
@keyurparalkar, the `TableProps` doesn't extend the `WidgetProps` which makes `bottomRow, topRow, leftColumn and rightColumn` not available. Should we make it to extend it?

2023-08-07 16:32 UTC, keyurparalkar commented on app/client/src/widgets/TableWidgetV2/component/Table.tsx
> +  if (!isTableResizing) {
@gitstart-appsmith yes, let us consume these props via widget.

2023-08-08 10:01 UTC, keyurparalkar commented on app/client/src/widgets/TableWidgetV2/component/Table.tsx
> +    AnalyticsUtil.logEvent("TABLE_VERTICAL_SCROLL", {
@gitstart-appsmith Can you please move this logic into another useEffect along with its dependencies?
This effect should be below the existing useeffect.

2023-08-08 13:09 UTC, LuisChiej commented on app/client/src/widgets/TableWidgetV2/component/Table.tsx
> +    AnalyticsUtil.logEvent("TABLE_VERTICAL_SCROLL", {
Done

2023-08-08 16:49 UTC, gitstart-appsmith commented on app/client/src/widgets/TableWidgetV2/component/Table.tsx
> +    AnalyticsUtil.logEvent("TABLE_VERTICAL_SCROLL", {
Done

2023-08-09 02:52 UTC, keyurparalkar submitted a review, later dismissed
Can you please run the `ok-to-test` command in the comment of this PR to start the CI checks and tests?

2023-08-09 06:14 UTC, gitstart-appsmith commented
ok-to-test

2023-08-09 08:16 UTC, keyurparalkar commented
/ok-to-test

2023-08-09 08:16 UTC, keyurparalkar commented
/build-deploy-preview

2023-08-09 08:19 UTC, keyurparalkar commented
@chandannkumar can you please test the conditions mentioned in this PR for `TABLE_VERTICAL_SCROLL` event rather than `WIDGET_RESIZE_END`?

2023-08-09 08:20 UTC, keyurparalkar commented
@gitstart-appsmith can you please update the description of the PR to include TABLE_VERTICAL_SCROLL instead of the mentioned event?

2023-08-10 08:26 UTC, Aishwarya-U-R commented
@keyurparalkar - Merge latest release & trigger new oktotest. Cancelling the re-run since its past 12 hours from initial attempt.

2023-08-10 09:05 UTC, chandannkumar commented
@gitstart-appsmith Observations:
1. The logic of showing `pageSize` & `yScrollVisibility` is not correct as we can observe wrong results most of the time.
video: https://www.loom.com/share/e9aeaac1c9504a24845c96803367504d?sid=22ea1ef5-4fda-421f-993f-510530754dc4

2. When table is re-sized to 0 (only table header are visible), the `pageSize` on the event is still 1
![image](https://github.com/appsmithorg/appsmith/assets/95341241/aacf4bce-d9d3-49a1-a993-8ab83c8468dc)

3. Also observed that, fixing the size of Table without a scroll is not smooth. As we cannot fix the table page size with exact pixel manually.
Refer comment - https://github.com/appsmithorg/appsmith/issues/17857#issuecomment-1630762915

2023-08-21 11:33 UTC, keyurparalkar commented on app/client/src/widgets/TableWidgetV2/component/Table.tsx
> +  const isVerticalScrollVisible = () => {
Please memoize this callback

2023-08-23 11:57 UTC, keyurparalkar requested changes

2023-08-23 11:57 UTC, keyurparalkar commented on app/client/src/widgets/TableWidgetV2/component/Table.tsx
> +  const isVerticalScrollVisible = useMemo(() => {
@gitstart-appsmith let us move this block inside the useEffect of AnalyticsUtil. In this way, we won't need the `isVerticalScrollVisible` value to be dependency for the below useEffect's.

2023-08-25 05:08 UTC, keyurparalkar requested changes

2023-08-25 05:08 UTC, keyurparalkar commented on app/client/src/widgets/TableWidgetV2/component/Table.tsx
> +    const isVerticalScrollVisible = () => {
@gitstart-appsmith instead of wrapping this logic inside a function can we just store result of this logic in a variable like below:
```js
let yScrollVisibility = false;
if(condition...)
``` 
and then use it in the below event

2023-08-29 19:24 UTC, gitstart-appsmith commented
> @gitstart-appsmith avoid merging main directly to the branch. Instead merge the release branch

@keyurparalkar, it's just a comment. We didn't merge main into the branch

2023-09-06 04:43 UTC, keyurparalkar approved these changes

2023-09-06 04:44 UTC, keyurparalkar commented
/ok-to-test

2023-09-06 04:44 UTC, keyurparalkar commented
/build-deploy-preview

2023-09-06 04:44 UTC, keyurparalkar commented
@chandannkumar can you please re-test this PR and verify the previous callouts.

2023-09-07 14:02 UTC, gitstart-appsmith commented
Hello @chandannkumar 

> Event is not getting fired when if widget is resized in the fixed pageSize. This effects the scrollVisibility value as it results incorrect.

In our current setup, we trigger the event based on changes in the data and props.pageSize properties. But, after trying a few different approaches, we found a fix by adding props.bottomRow and props.topRow as new dependencies.
However, this tweak led to multiple event triggers, in cases where data is refreshed and the pageSize changes

> When table is re-sized to 0 (only table header are visible), the pageSize on the event is still 1

We noticed this inconsistency, during our testing however we also noticed that this behavior is by design. Based on the snippet below, if the table header is visible, the pageSize cannot be less than 1.
Would you like us to generally override this behavior?.
Would recommend that it’s done in a separate PR so that the potential side effects can be carefully analyzed.

https://github.com/appsmithorg/appsmith/blob/release/app/client/src/widgets/TableWidgetV2/widget/index.tsx#L1231-L1233
```
index.tsx
    pageSize={
        isVisibleHeaderOptions ? Math.max(1, pageSize) : pageSize + 1
    }
```

2023-09-11 06:18 UTC, keyurparalkar commented
> In our current setup, we trigger the event based on changes in the data and props.pageSize properties. But, after trying a few different approaches, we found a fix by adding props.bottomRow and props.topRow as new dependencies.
> However, this tweak led to multiple event triggers, in cases where data is refreshed and the pageSize changes

@gitstart-appsmith you can go with the fix of adding bottomRow and topRow dependencies. CC: @chandannkumar 

> We noticed this inconsistency, during our testing however we also noticed that this behavior is by design. Based on the snippet below, if the table header is visible, the pageSize cannot be less than 1.
> Would you like us to generally override this behavior?.
> Would recommend that it’s done in a separate PR so that the potential side effects can be carefully analyzed.
> 

@chandannkumar @gitstart-appsmith we can ignore this since this is an edge case.

2023-09-12 10:25 UTC, keyurparalkar commented on app/client/src/widgets/TableWidgetV2/component/Table.tsx
> +        clientHeight: scrollBarRef.current.getScrollElement().clientHeight || 0,
@gitstart-appsmith why are we passing object in `pageHeight` instead of number? Since `clientHeight` is not being used anywhere, is there a reason we added it?

2023-09-12 11:10 UTC, gitstart-appsmith commented on app/client/src/widgets/TableWidgetV2/component/Table.tsx
> +        clientHeight: scrollBarRef.current.getScrollElement().clientHeight || 0,
Hi @keyurparalkar,

In our test, we were able to reproduce edge cases where the scrollHeight remains thesame on a slight resize.
Including the scrollHeight and clientHeight makes it more stable and consistent.

[Here's a quick demo to reproduce the described case.](https://www.loom.com/share/34cb5ed1c0f046b8852135d57432ccb8?sid=2dfe38b6-e41d-40c2-a816-20e001342219)

2023-09-14 05:16 UTC, keyurparalkar approved these changes

2023-09-14 05:17 UTC, keyurparalkar commented
/ok-to-test

2023-09-14 05:17 UTC, keyurparalkar commented
/build-deploy-preview

2023-09-14 05:18 UTC, keyurparalkar commented
@chandannkumar @gitstart-appsmith has fixed the changes. Can you please re-test?

2023-09-14 15:29 UTC, gitstart-appsmith commented
Hello, @chandannkumar @keyurparalkar Thank you for highlighting this issue.
In the previous logic, we excluded certain logs to decrease the frequency of event logs since we have four dependent properties.
However, as you pointed out in your last comment, this approach can lead to unintended side effects.
With the current update, we’ve made adjustments to guarantee that the event log will be triggered whenever any of the dependencies undergo changes.
This means that in specific cases, you may notice multiple logs generated due to changes in various dependent properties, with the last log reflecting the latest state as shown in the demo below.

https://www.loom.com/share/6c8732fdfa3048a9a9f0bf57fe291d65?sid=169cc1f4-c0d6-4b4b-b21f-0f0ff19e20e4

2023-09-20 06:42 UTC, keyurparalkar commented
/ok-to-test

2023-09-20 06:42 UTC, keyurparalkar commented
/build-deploy-preview

2023-09-20 06:49 UTC, keyurparalkar commented
@chandannkumar can you please test the callouts once the DP is generated?

2023-09-25 05:58 UTC, chandannkumar commented
@gitstart-appsmith 
- We can observe that multiple events got fired for 1 time resizing of the Table widget(Page size). Although the last fired event's result are correct but multiple events could create inaccuracy in upcoming tasks
Video: https://www.loom.com/share/704280cbe8764ead812caf6ebd73a738?sid=fdac4924-5245-4487-aaf2-0213d2732df1

cc: @sbalaji1192

2023-09-29 11:15 UTC, gitstart-appsmith commented
Hi @chandannkumar, @keyurparalkar,

We've taken a close look at the issue you highlighted in your video, and we were able to replicate the multiple event logs.

It's essential for us to maintain all the current dependencies set up in the `useEffect` to ensure that we continue to meet the requirements you've raised in your previous reviews.

One possible solution we're considering is introducing a delay in the event logs. This approach would ensure that only the latest event log within a specified timeframe, say 1 second, gets logged. We believe this could help address the issue.

Before proceeding with this solution, we'd love to hear your thoughts and any suggestions you might have.

2024-01-23 13:16 UTC, closed without merging