CI: Deploy preview from branch
appsmithorg/appsmith pull request #25846
Opened 2023-07-31 10:14 UTC by sum35h

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.
>
## Description
> Add a TL;DR when description is extra long (helps content team)
>
> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change
>
> Links to Notion, Figma or any other documents that might be relevant to the PR
>
>
#### PR fixes following issue(s)
Fixes # (issue number)
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
#### Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video
>
>
#### Type of change
> Please delete options that are not relevant.
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
## Testing
>
#### How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Also list any relevant details for your test configuration.
> Delete anything that is not relevant
- [ ] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-08-02 07:28 UTC, sum35h commented on scripts/build_dp_from_branch.sh
> +echo "[default]
Could not figure out setting creds for eks, so I've used this, since it's also being used by the pr dp script https://github.com/appsmithorg/appsmith/blob/release/scripts/deploy_preview.sh#L8

2023-08-02 07:29 UTC, sum35h commented on .github/workflows/server-build.yml
> +  pull_request:
Not sure why this got removed, this is required by other workflows that use server build.

2023-08-02 07:51 UTC, sharat87 requested changes

2023-08-02 07:51 UTC, sharat87 commented on .github/workflows/ad-hoc-deploy-preview.yml
> +          --header 'Authorization: Bearer ${{secrets.INTENRAL_OPS_API_TOKEN}}' \
We can use `--oauth2-bearer` for this:

```suggestion
          --oauth2-bearer '${{secrets.INTENRAL_OPS_API_TOKEN}}' \
```

2023-08-02 07:51 UTC, sharat87 commented on .github/workflows/ad-hoc-deploy-preview.yml
> +                  "githubWorkflowHtmlUrl": ${{github.workflow.githubWorkflowHtmlUrl}},
Won't this be unquoted, and so result in invalid JSON?

```suggestion
                  "githubWorkflowHtmlUrl": "${{github.workflow.githubWorkflowHtmlUrl}}",
```

2023-08-02 07:51 UTC, sharat87 commented on .github/workflows/ad-hoc-deploy-preview.yml
> +          curl --location --request PATCH 'https://ops.appsmith.com/appsmith_deploy_workflow/${{github.event.inputs.uid}}' \
Do we need `--location`? Are we expecting redirects here? 🤔

2023-08-02 07:51 UTC, sharat87 commented on .github/workflows/ad-hoc-deploy-preview.yml
> +        uses: depot/setup-action@v1
Are we using Depot anywhere? 🤔

2023-08-02 07:51 UTC, sharat87 commented on .github/workflows/ad-hoc-deploy-preview.yml
> +        uses: depot/setup-action@v1
Are we using Depot anywhere? 🤔

2023-08-02 07:51 UTC, sharat87 commented on .github/workflows/server-build.yml
> +  pull_request:
I think this was intentional. It's being triggered as part of a different workflow now.

2023-08-02 10:53 UTC, sum35h commented on .github/workflows/ad-hoc-deploy-preview.yml
> +          curl --location --request PATCH 'https://ops.appsmith.com/appsmith_deploy_workflow/${{github.event.inputs.uid}}' \
There are no redirects, removing -L

2023-08-02 10:54 UTC, sum35h commented on .github/workflows/ad-hoc-deploy-preview.yml
> +                  "githubWorkflowHtmlUrl": ${{github.workflow.githubWorkflowHtmlUrl}},
Noted.

2023-08-02 11:00 UTC, sum35h commented on .github/workflows/ad-hoc-deploy-preview.yml
> +        uses: depot/setup-action@v1
Actually, we're not using it. I went ahead with copying it from the other dp workflow yaml file and since it was working I did not touch it. I'm removing it here. Will remove it from the other dp workflow as well later.

2023-08-02 11:02 UTC, sum35h commented on .github/workflows/server-build.yml
> +
```suggestion
```

2023-08-02 11:03 UTC, sum35h commented on .github/workflows/server-build.yml
> +      - "app/server/**"
```suggestion
```

2023-08-02 11:04 UTC, sum35h commented
/ok-to-test

2023-08-03 05:44 UTC, sharat87 approved these changes

2023-08-07 05:29 UTC, merged