feat: Create lightweight status api
appsmithorg/appsmith pull request #25857
Opened 2023-07-31 13:59 UTC by nayan-rafiq

## Description
This PR brings those changes:
1. Creates a new API to know whether there are any uncommitted changes or not
2. Creates a new API to compare the local branch with remote
3. Adds an optional parameter to the status API so that we can skip the git fetch

#### PR fixes following issue(s)
Fixes #24340

#### Media

#### Type of change
- New feature (non-breaking change which adds functionality)

## Testing
>
#### How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Also list any relevant details for your test configuration.
> Delete anything that is not relevant
- [x] Manual
- [x] Jest
- [ ] Cypress

#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-08-01 06:21 UTC, Parthvi12 commented
/build-deploy-preview

2023-08-01 07:49 UTC, Parthvi12 approved these changes

2023-08-01 18:45 UTC, AnaghHegde requested changes
Minor changes, rest looks good to me

2023-08-01 18:45 UTC, AnaghHegde commented on app/server/appsmith-server/src/test/java/com/appsmith/server/services/ce/GitServiceCEImplTest.java
> +    public void getUncommittedChanges_WhenRepoIsNotConnectedToGit_ReturnsFalse() {
Hey this a wrong Test class. This class has tests that are specific to the CE flow - example repo limit check. Since this is a common flow across we should use `GitServiceTest` class

2023-08-01 18:45 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java
> +                    Instant lastUpdateAt = application.getLastEditedAt();
QQ - Does this get updated when we add action or modify a datasource?

2023-08-01 18:45 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java
> +                                .addFileLock(gitApplicationMetadata.getDefaultApplicationId())
```suggestion
                                addFileLock(gitApplicationMetadata.getDefaultApplicationId())
```

2023-08-01 18:45 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java
> +                                .addFileLock(gitApplicationMetadata.getDefaultApplicationId())
There is a method which handles the jitter and retry. We can reuse the same

2023-08-01 18:45 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java
> +    public Mono<BranchTrackingStatus> compareWithRemote(
```suggestion
    public Mono<BranchTrackingStatus> fetchRemoteChanges(
```

2023-08-01 18:45 UTC, AnaghHegde commented on app/server/appsmith-git/src/main/java/com/appsmith/git/service/GitExecutorImpl.java
> +        return Mono.fromCallable(() -> {
Can you help me in understanding how we are utilising this in the new flow?

2023-08-02 07:19 UTC, nayan-rafiq commented on app/server/appsmith-git/src/main/java/com/appsmith/git/service/GitExecutorImpl.java
> +        return Mono.fromCallable(() -> {
@AnaghHegde This tells the tracking information i.e. how many commits ahead and behind the local branch is. We're using this in the new `fetch remote API` as the last step.

2023-08-02 07:35 UTC, nayan-rafiq commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java
> +                    Instant lastUpdateAt = application.getLastEditedAt();
When datasource information updated, it's not set. But when any domain related to application e.g. page, action etc are edited, this field is set.

2023-08-02 07:38 UTC, nayan-rafiq commented
/ok-to-test sha=5b002f5

2023-08-02 09:14 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java
> +                    Instant lastUpdateAt = application.getLastEditedAt();
We should be counting the datasource modifications as well right?

2023-08-02 17:20 UTC, nayan-rafiq commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java
> +                    Instant lastUpdateAt = application.getLastEditedAt();
@AnaghHegde Got it. Then this way of detecting the diff will not work. Because, when we edit a datasource, we don't update this property for the connected applications.
I'm going to remove the API as it'll not work as per our expectation. Anyway we'll have to figure out a better way to detect changes from DB.

2023-08-03 01:38 UTC, nayan-rafiq commented
/ok-to-test sha=2c4a8f4

2023-08-03 13:14 UTC, AnaghHegde approved these changes

2023-08-03 13:14 UTC, merged