feat: Email Verification
appsmithorg/appsmith pull request #25854
Opened 2023-07-31 12:50 UTC by hetunandu

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.
>
## Description
> Add a TL;DR when description is extra long (helps content team)
>
> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change
>
> Links to Notion, Figma or any other documents that might be relevant to the PR
>
>
#### PR fixes following issue(s)
Fixes # (issue number)
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
#### Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video
>
>
#### Type of change
> Please delete options that are not relevant.
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
## Testing
>
#### How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Also list any relevant details for your test configuration.
> Delete anything that is not relevant
- [ ] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-08-01 07:14 UTC, hetunandu commented
/build-deploy-preview

2023-08-11 07:28 UTC, hetunandu commented
/build-deploy-preview

2023-08-16 12:57 UTC, NilanshBansal commented
/build-deploy-preview

2023-08-16 19:53 UTC, NilanshBansal commented
/build-deploy-preview

2023-08-17 07:12 UTC, hetunandu commented
/build-deploy-preview

2023-08-18 11:06 UTC, NilanshBansal commented
/build-deploy-preview

2023-08-21 06:11 UTC, NilanshBansal commented
/build-deploy-preview

2023-08-21 08:17 UTC, NilanshBansal commented
/build-deploy-preview

2023-08-22 04:54 UTC, NilanshBansal commented
/build-deploy-preview

2023-08-22 06:36 UTC, hetunandu commented
/ok-to-test

2023-08-22 15:54 UTC, NilanshBansal commented
/build-deploy-preview

2023-08-23 14:02 UTC, NilanshBansal commented
/build-deploy-preview

2023-08-24 06:15 UTC, hetunandu commented
/ok-to-test

2023-08-24 07:22 UTC, hetunandu commented
/ok-to-test

2023-08-24 09:26 UTC, hetunandu commented
/ok-to-test

2023-08-24 12:26 UTC, NilanshBansal commented
/build-deploy-preview

2023-08-24 13:00 UTC, NilanshBansal commented
/build-deploy-preview skip-tests=true

2023-08-24 13:01 UTC, ankitakinger commented on app/client/src/ce/pages/AdminSettings/config/authentication/index.tsx
> +        return !(!settings.emailVerificationEnabled && !mailEnabled);
why is this condition so complicated? Wouldn't `settings.emailVerificationEnabled || mailEnabled` work?

2023-08-24 13:06 UTC, ankitakinger commented on app/client/src/pages/Settings/config/email.ts
> +      isDisabled: (settings?) => {
Can we add a type here?

2023-08-24 13:12 UTC, ankitakinger commented on app/client/src/pages/UserAuth/VerifyUser.tsx
> +      Sentry.captureMessage("User Email Verification link is damaged");
can we use sentence casing here?

2023-08-24 13:13 UTC, ankitakinger commented on app/client/src/ce/constants/messages.ts
> +  "Please ensure that the SMTP server is correctly configured. This will be used to send emails about forgot password and email verification";
Should we add a full stop towards the end?
<img width="692" alt="image" src="https://github.com/appsmithorg/appsmith/assets/28362912/5ec9b556-0ae4-453c-8196-951118857be2">

2023-08-24 13:16 UTC, ankitakinger commented on app/client/src/pages/Settings/FormGroup/group.tsx
> -                      setting.isHidden ? "hide" : "callout-link"
why have we removed `callout-link` class? There are styles being applied using this class in EE.

2023-08-24 13:18 UTC, ankitakinger requested changes
Added a few comments

2023-08-24 13:21 UTC, ankitakinger commented on app/client/src/ce/pages/AdminSettings/config/authentication/index.tsx
> +        // Visible when mail is disabled but settings is true
Couldn't reach this state on the DP. Could you share a recording of how can I land in this state?

2023-08-24 14:03 UTC, shubham7saxena7 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/domains/EmailVerificationToken.java
> +    Instant tokenGeneratedAt; // verification link is valid for 48 hours
do we need this comment ?

2023-08-24 14:11 UTC, shubham7saxena7 requested changes

2023-08-24 14:50 UTC, NilanshBansal commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UserServiceCE.java
> +    Mono<User> sendWelcomeEmail(User user, String originHeader);
I guess then we can take that up as a separate task, whenever we are sure of removing it. Right now, the intent of this PR is to mimic the behaviour as in prod today with email verification.

2023-08-24 14:52 UTC, NilanshBansal commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UserServiceCE.java
> +    Mono<User> sendWelcomeEmail(User user, String originHeader);
I agree with you on this but this has been not introduced as part of this PR. The intent was not to change the existing behavior of the codebase.

2023-08-24 15:12 UTC, NilanshBansal commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/TenantServiceCEImpl.java
> +                        envMono = envManager.getAllNonEmpty().flatMap(properties -> {
Have made this more readable now. It felt bulky because of the extraction of the variable being repeated.

2023-08-25 06:48 UTC, hetunandu commented on app/client/src/ce/pages/AdminSettings/config/authentication/index.tsx
> +        // Visible when mail is disabled but settings is true
Steps to repro:
- Add email settings
- Enable verification
- Remove email settings
- Check email verification settings.

This is needed to ensure users can disable email verification if email settings were removed for some reason. An edge case but needed to avoid users getting stuck with email verification. With this, user can disable email verification (otherwise the input is disabled since email is not configured)

2023-08-25 07:02 UTC, hetunandu commented
/build-deploy-preview

2023-08-25 07:02 UTC, hetunandu commented
/ok-to-test

2023-08-25 07:17 UTC, ankitakinger approved these changes
LGTM

2023-08-25 07:46 UTC, ankitakinger commented on app/client/src/ce/pages/AdminSettings/config/authentication/index.tsx
> +        // Visible when mail is disabled but settings is true
I see the `APPSMITH_FORM_DISABLED_BANNER` when I follow these steps listed by you. Could you cross-check once?

2023-08-25 08:58 UTC, NilanshBansal commented
/build-deploy-preview skip-tests=true

2023-08-25 09:54 UTC, abhvsn reviewed
Added very minor comments but LGTM

2023-08-25 09:54 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/authentication/handlers/ce/AuthenticationSuccessHandlerCE.java
> +        return redirectionMono;
It feels like lot of branching within the same method can we please abstract out the branching to improve the readability?

2023-08-25 09:54 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/exceptions/AppsmithError.java
> +    TENANT_EMAIL_VERIFICATION_NOT_ENABLED(
In what case we want to throw this exception? If not required let's remove this

2023-08-25 09:54 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/TenantServiceCEImpl.java
> +        this.envManager = envManager;
Can you help me understand why are we using @Lazy in 1 place and not in other?

2023-08-25 10:17 UTC, hetunandu commented
/ok-to-test

2023-08-25 10:19 UTC, NilanshBansal commented on app/server/appsmith-server/src/main/java/com/appsmith/server/exceptions/AppsmithError.java
> +    TENANT_EMAIL_VERIFICATION_NOT_ENABLED(
It's being used in the sending verification email method, which returns an error in case the email verification is not enabled but still trying to invoke this method.
[Reference](https://github.com/appsmithorg/appsmith/blob/3732273cccafd7ba7bdd6885c3eaea1dd8471158/app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UserServiceCEImpl.java#L924)

2023-08-25 10:58 UTC, shubham7saxena7 approved these changes

2023-08-25 13:41 UTC, NilanshBansal commented
/ok-to-test

2023-08-25 13:41 UTC, NilanshBansal commented
/build-deploy-preview skip-tests=true

2023-08-25 16:19 UTC, NilanshBansal commented
/ok-to-test

2023-08-25 18:18 UTC, abhvsn approved these changes

2023-08-26 04:22 UTC, merged