feat: code scanner widget default camera
appsmithorg/appsmith pull request #26083
Opened 2023-08-07 10:42 UTC by berzerkeer

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.
>
## Description
> Add a TL;DR when description is extra long (helps content team)
>
> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change
>
> Links to Notion, Figma or any other documents that might be relevant to the PR
>
>
#### PR fixes following issue(s)
Fixes # (issue number)
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
#### Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video
>
>
#### Type of change
> Please delete options that are not relevant.
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
## Testing
>
#### How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Also list any relevant details for your test configuration.
> Delete anything that is not relevant
- [ ] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-08-07 10:56 UTC, berzerkeer commented
/build-deploy-preview

2023-08-08 18:25 UTC, berzerkeer commented
/ok-to-test

2023-08-09 01:20 UTC, rajatagrawal requested changes

2023-08-09 01:20 UTC, rajatagrawal commented on app/client/src/widgets/CodeScannerWidget/widget/propertyConfig/contentConfig.ts
> +        propertyName: "defaultCamera",
Can we please consider adding a unit tests for changes in the property pane ? Sample property pane tests can referenced from [here](https://github.com/appsmithorg/appsmith/blob/ea435ae9e54648d2b622ff18c0e23c6cfed2576e/app/client/src/widgets/ChartWidget/widget/propertyConfig.test.ts#L174).

2023-08-09 01:20 UTC, rajatagrawal commented on app/client/cypress/e2e/Regression/ClientSide/Widgets/CodeScanner/CodeScanner_spec.js
> +describe("5 => Default mobile camera", () => {
we can skip this cypress test because the functionality tested in this test can be covered in property pane test suggested below. Thanks!

2023-08-09 11:17 UTC, berzerkeer commented
/ok-to-test

2023-08-09 12:52 UTC, chandannkumar commented
Tested this and LGTM
- Tested on Android and iphone

2023-08-09 18:27 UTC, dhruvikn approved these changes

2023-08-10 06:48 UTC, merged

2023-08-10 06:54 UTC, Aishwarya-U-R commented
@Vijetha-Kaja - Please check if we can add cypress for this change in our open PR for code scanner:
<img width="279" alt="Screenshot 2023-08-10 at 12 23 30 PM" src="https://github.com/appsmithorg/appsmith/assets/91450662/b03283ce-62ea-41b4-ac21-cb6b5abea62a">

2023-08-10 06:56 UTC, Aishwarya-U-R commented
Ok, seems unit test is enough for this case. @Vijetha-Kaja Cypress not needed.