POC: CSS Modules on Button component
appsmithorg/appsmith pull request #26162
Opened 2023-08-08 12:02 UTC by jsartisan

Fixes: #26019

2023-08-08 13:29 UTC, KelvinOm requested changes

2023-08-08 13:29 UTC, KelvinOm commented on app/client/packages/design-system/widgets/src/components/Button/styles.module.css
> +  @each $color in accent, neutral, negative, warning, positive {
Could we create global variable for this and import it here? Something like this:

```
:root {
    --colors: accent, neutral, negative, warning, positive;
}

@each $color in var(--colors) {
    @import "$val.css";
}
```

2023-08-10 07:38 UTC, jsartisan commented on app/client/packages/design-system/widgets/src/components/Button/Button.tsx
> +import styles from "./styles.module.css";
I tried this. Didn't work :|

2023-08-10 07:41 UTC, jsartisan commented on app/client/packages/design-system/widgets/src/components/Button/styles.module.css
> +  @each $color in accent, neutral, negative, warning, positive {
Where should we store it and how to load it?
Let's say I store it like` global.css` in `styles` folder. Will i load it like

`@import "../styles/global.css"`
If yes, what will happen if another component also needs it? As far as I know, only a few components will need semantics like buttons and icon buttons. I feel extracting these values to an variable won't help much as it will be mostly used in button.

2023-08-10 07:42 UTC, jsartisan commented on app/client/packages/storybook/.storybook/main.ts
> +              require("postcss-at-rules-variables"),
I just saw you used it like this only. Should I check without require too?

2023-08-10 07:59 UTC, jsartisan commented on app/client/packages/storybook/package.json
> +    "@storybook/addon-styling": "^1.3.5",
Removed.

2023-09-04 11:41 UTC, KelvinOm commented on app/client/packages/design-system/widgets/src/components/Button/Button.tsx
> +import styles from "./styles.module.css";
This is because of our current build configuration. Let's skip this for now.

2023-09-11 10:03 UTC, riodeuno commented on app/client/packages/design-system/theming/src/theme/src/ProviderStyleSheet.ts
> +export class ProviderStyleSheet {
What are sheets and what purpose do they serve?
Also, could we add jsdoc comments to the methods in this file?

2023-09-12 11:22 UTC, KelvinOm commented on app/client/packages/design-system/theming/src/theme/src/ProviderStyleSheet.ts
> +export class ProviderStyleSheet {
@riodeuno Added comments. Let me know if I should do more or something is unclear.

2023-09-14 07:48 UTC, riodeuno commented on app/client/packages/design-system/theming/src/theme/src/ProviderStyleSheet.ts
> +export class ProviderStyleSheet {
Thanks for adding the comment. It is a lot clearer now. Let's set this thread to resolved.

2023-09-15 07:17 UTC, merged