chore: Add id & ref to Flex component
appsmithorg/appsmith pull request #26190
Opened 2023-08-09 04:28 UTC by aswathkk

## Description
Added `id` and `ref` properties to Flex component

2023-08-09 08:04 UTC, KelvinOm commented on app/client/packages/design-system/widgets/src/components/Flex/Flex.tsx
> +Flex.displayName = "Flex";
(nitpick) We use bit different pattern for this.

```
const _Flex = () => {}
export const Flex = forwardRef(_Flex);
```

2023-08-10 07:19 UTC, jsartisan requested changes

2023-08-10 07:19 UTC, jsartisan commented on app/client/packages/design-system/widgets/src/components/Flex/types.ts
>  export type StyledFlexProps = OmitRename<FlexProps, "style" | "className">;
You missed adding
```
StyledFlexProps = OmitRename<FlexProps, keyof ComponentProps<"div">>
```

Here we want to rename with prop with a $ except that the default ones supported by div.

2023-08-10 07:28 UTC, jsartisan approved these changes

2023-08-16 06:07 UTC, jsartisan submitted a review, later dismissed

2023-08-16 13:09 UTC, KelvinOm approved these changes

2023-08-16 13:09 UTC, merged