chore: Refactor feature flag service to remove the dependency from tenant service
appsmithorg/appsmith pull request #26219
Opened 2023-08-09 18:38 UTC by abhvsn

## Description
We are facing the cyclical dependecy issue with tenant service and feature flag service on EE codebase, as are running the force feature flag update call whenever the tenant license is updated. This PR updates the implementation to use tenantId reference in feature flag service to fix the above mentioned issue.  

#### Type of change
- Chore (housekeeping or task changes that don't impact user perception)

#### How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Also list any relevant details for your test configuration.
- [x] Manual
- [ ] JUnit

#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-08-17 09:13 UTC, abhvsn commented
/ok-to-test

2023-08-17 18:41 UTC, abhvsn commented
/ok-to-test

2023-08-18 05:01 UTC, NilanshBansal requested changes

2023-08-18 05:33 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/CacheableFeatureFlagHelperCEImpl.java
> +        return this.fetchCachedTenantNewFeatures(tenantId);
`CacheEvict` annotation does go through the code as per the aspect implementation, you can check that [here](https://github.com/appsmithorg/appsmith/blob/a0db49d1f486498353c7996a2a00ab88b3ed9ed1/app/server/reactive-caching/src/main/java/com/appsmith/caching/aspects/CacheAspect.java#L220). As the method suggests this will need to force updated the cache where we have to implement following steps:
1. Evict the corresponding cache
2. Add new entry to the existing cache

Also on the other part we do have a separate method which is annotated with CacheEvict [here](https://github.com/appsmithorg/appsmith/blob/a0db49d1f486498353c7996a2a00ab88b3ed9ed1/app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/CacheableFeatureFlagHelperCEImpl.java#L198), but this was not working as expected so went ahead with above implementation.

2023-08-18 08:32 UTC, abhvsn commented
/ok-to-test

2023-08-18 09:17 UTC, NilanshBansal approved these changes
LGTM

2023-08-18 10:24 UTC, merged