fix: correct x,y values for sankey onDataPointClick
appsmithorg/appsmith pull request #26267
Opened 2023-08-10 20:54 UTC by dhruvikn

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.
>
## Description
> Add a TL;DR when description is extra long (helps content team)
>
> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change
>
> Links to Notion, Figma or any other documents that might be relevant to the PR
>
>
#### PR fixes following issue(s)
Fixes #26026
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
#### Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video
>
>
#### Type of change
> Please delete options that are not relevant.
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
## Testing
>
#### How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Also list any relevant details for your test configuration.
> Delete anything that is not relevant
- [ ] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-08-17 11:27 UTC, dhruvikn commented
/build-deploy-preview env=release

2023-08-17 11:46 UTC, dhruvikn commented
/ok-to-test

2023-08-17 14:25 UTC, rajatagrawal requested changes

2023-08-17 14:25 UTC, rajatagrawal commented on app/client/src/widgets/ChartWidget/constants.ts
> +  rawEventData: unknown[];
Would you like to consider the type to be just unknown instead of unknown[], since it may not always be an array if a new library in future doesn't return an array ?

2023-08-17 14:25 UTC, rajatagrawal commented on app/client/src/widgets/ChartWidget/component/index.tsx
> +            rawEventData: data,
I think that we want to pass rawEventData only for custom fusion chart. For basic chart, we don't want to pass this value to the users. [Relevant Slack thread](https://theappsmith.slack.com/archives/C0341RERY4R/p1691396411061089?thread_ts=1691135335.087569&cid=C0341RERY4R)

2023-08-17 14:25 UTC, rajatagrawal commented on app/client/src/widgets/ChartWidget/component/index.test.tsx
> +    expect(mockCallback.mock.results?.[0].value).toHaveProperty("rawEventData");
Can we have an assertion like 

```
expect(mockCallback.mock.results?.[0].value.rawEventData).toEq({//raw event value goes here})
```

2023-08-17 14:25 UTC, rajatagrawal commented on app/client/src/widgets/ChartWidget/component/index.tsx
> +      x: x ?? -1,
We can consider moving the logic for parsing event data into chartSelectedPoint params into a separate function. With that we would be also able to test that x and y are -1 if relevant values are not present in event data.

A wrapper unit test that tests that mockCallbackfunction gets called with a set of correct chartSelectedPoint params would validate that the helper function created above is getting called.

2023-08-17 14:25 UTC, rajatagrawal commented on app/client/src/widgets/ChartWidget/component/index.test.tsx
> +    expect(mockCallback.mock.results?.[0].value).toHaveProperty("rawEventData");
This way we can also test a set of possible values inside rawEventData.

2023-08-17 14:37 UTC, rajatagrawal commented
I think that we would also need a documentation update for this ticket. cc : @dilippitchika

2023-08-18 14:01 UTC, dhruvikn commented on app/client/src/widgets/ChartWidget/component/index.test.tsx
> +    expect(mockCallback.mock.results?.[0].value).toHaveProperty("rawEventData");
As discussed in our call, we are not writing a unit test for this, rather a cypress to test onDataPointClick functionality.

2023-08-18 14:01 UTC, dhruvikn commented on app/client/src/widgets/ChartWidget/component/index.tsx
> +      x: x ?? -1,
Have moved this logic to a separate `parseOnDataPointClickParams` function.

2023-08-18 15:11 UTC, dhruvikn commented
/build-deploy-preview env=release

2023-08-19 03:59 UTC, rajatagrawal approved these changes

2023-08-21 06:13 UTC, dhruvikn commented
/ok-to-test

2023-08-21 09:30 UTC, merged