feat: Added new api to fetch preview data
appsmithorg/appsmith pull request #26298
Opened 2023-08-11 13:13 UTC by sneha122

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.
>
## Description
> Add a TL;DR when description is extra long (helps content team)
>
> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change
>
> Links to Notion, Figma or any other documents that might be relevant to the PR
>
>
#### PR fixes following issue(s)
Fixes # (issue number)
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
#### Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video
>
>
#### Type of change
> Please delete options that are not relevant.
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
## Testing
>
#### How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Also list any relevant details for your test configuration.
> Delete anything that is not relevant
- [ ] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-08-16 10:46 UTC, sumitsum requested changes

2023-08-21 06:36 UTC, sneha122 commented on app/server/appsmith-plugins/postgresPlugin/src/main/java/com/external/plugins/PostgresPlugin.java
> +                        if (request.getRequestedAt() == null) {
Yes this is required here, because although we set this in ActionExecutionSolutionCEImpl.java, that gets set only during action execution, over here when executeCommon is called to fetch preview data, requestAt does not get set, hence doing it here in case of null value

2023-08-21 07:17 UTC, sneha122 commented on app/server/appsmith-plugins/postgresPlugin/src/main/java/com/external/plugins/PostgresPlugin.java
> +            return actionConfig;
No they are the same, I had something else in mind here hence created new variable but its not required here, will remove it, Thanks!

2023-08-21 07:44 UTC, sneha122 commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/exceptions/pluginExceptions/AppsmithPluginError.java
> +            ErrorType.INTERNAL_ERROR,
The API could also fail because of stale connection, in that case would it be valid to call it datasource config error?

2023-08-22 05:09 UTC, sumitsum requested changes

2023-08-22 05:11 UTC, sumitsum commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/exceptions/pluginExceptions/AppsmithPluginErrorCode.java
> +    PLUGIN_GET_PREVIEW_DATA_ERROR("PE-DSE-5006", "Failed to get preview data"),
Please check the error code in the same file in EE repository to confirm uniqueness otherwise there would be conflict in EE repository post merge.

2023-08-22 05:57 UTC, sneha122 commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/exceptions/pluginExceptions/AppsmithPluginErrorCode.java
> +    PLUGIN_GET_PREVIEW_DATA_ERROR("PE-DSE-5006", "Failed to get preview data"),
Done!! We dont have conflicting codes with EE

2023-08-22 05:57 UTC, sneha122 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/DatasourceStructureSolutionCEImpl.java
> +                        tuple2.getT1(), tuple2.getT2()))
Got it will do that

2023-08-22 06:28 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/DatasourceStructureSolutionCEImpl.java
> +                .onErrorMap(
Can you please check if the `.onErrorMap` is outside or inside the `retryOnce` function ? In case it is inside, could we place it outside the function. Please check out the usage in `DatasourceStructureSolutionCEImpl.java` once.

2023-08-22 08:10 UTC, sneha122 commented
/ok-to-test

2023-08-22 08:14 UTC, sneha122 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/DatasourceStructureSolutionCEImpl.java
> +                .onErrorMap(
@sumitsum Its outside `retryOnce` only. Let me know if any more changes are required here

2023-08-22 10:52 UTC, sumitsum approved these changes

2023-08-22 11:58 UTC, sneha122 commented
Since this PR adds a new API on server side, we cannot test it without the frontend, and these changes should not introduce any bugs in existing functionality as its a new API. In this case we can skip the testing and add `test-plan-approved` label.

CC: @prapullac @rohan-arthur @sumitsum

2023-08-22 12:02 UTC, merged