Added client credentials grant type for OAuth2
appsmithorg/appsmith pull request #2649
Opened 2021-01-20 13:56 UTC by nidhi-nair

Added OAuth2 with client credentials to the REST API plugin. This change allows users to configure their endpoints with access tokens that can be added to the header or query parameters, as per configuration.
The datasource view pane has a few non-user-friendly options visible on the screen with this change. Fixing this will require front end code changes in the way the datasource pane is built.

Fixes #2648 

## Type of change
- New feature (non-breaking change which adds functionality)
- This change will require documentation update

## How Has This Been Tested?
![image](https://user-images.githubusercontent.com/5298848/105184415-5452ea80-5b55-11eb-984c-920c24c2acf6.png)
![image](https://user-images.githubusercontent.com/5298848/105184423-561cae00-5b55-11eb-9bf8-1876c0a9d31d.png)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-02-02 04:52 UTC, mohanarpit commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/DatasourceServiceImpl.java
> +            if (datasource.getDatasourceConfiguration().getAuthentication().isEncrypted()) {
If we decrypt the credentials each time we fetch the datasourceById, will that cause any security leaks? For eg, if a user wishes to edit the datasource and opens the datasource management page, what will the response to `GET /datasources/{id}` return?

2021-02-02 05:09 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/DatasourceServiceImpl.java
> +            if (datasource.getDatasourceConfiguration().getAuthentication().isEncrypted()) {
All sensitive fields for authentication are marked with `@JSONIgnore` so they will never really go back to the client. We're also sure that the @JSONIgnore field is always present because otherwise users that enter their passwords will have both versions of the secrets and that in itself is a security leak.

2021-02-02 07:47 UTC, mohanarpit approved these changes

2021-02-05 13:57 UTC, ofpiyush commented
@nidhi-nair not sending the `datasourceConfiguration.authentication` key or sending a `null` does not reset the authentication data.

2021-02-10 08:04 UTC, mohanarpit commented on app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/DatasourceController.java
> +//    @GetMapping("/{datasourceId}/code")
Any particular reason that this code is commented out?

2021-02-10 08:06 UTC, mohanarpit commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/AuthenticationService.java
> +                            .queryParam(REDIRECT_URI, "https://app.appsmith.com/applications")
How would this redirect work in a self-hosted environment with a custom domain?

2021-02-10 08:06 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/DatasourceController.java
> +//    @GetMapping("/{datasourceId}/code")
It's part of the authorization code workflow and I just wanted make sure we don't expose this endpoint even on release.

2021-02-10 08:06 UTC, mohanarpit commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/AuthenticationService.java
> +                    map.add(REDIRECT_URI, "https://app.appsmith.com/applications");
Same here. How will this work in a self-hosted environment?

2021-02-10 08:08 UTC, mohanarpit commented on app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/AuthenticationServiceTest.java
> +        // 2. Without Client Id
Minor: Is it possible to split this test into multiple tests? I see different things being asserted in each StepVerifier. If they are all within the same test function, this makes test failures harder to understand. As a thumb rule, we should follow, 1 test-1 scenario.

2021-02-10 08:10 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/AuthenticationService.java
> +                            .queryParam(REDIRECT_URI, "https://app.appsmith.com/applications")
Sorry these changes are all part of the authorization code workflow and I have the working code stashed on my local for now! This seems to be causing unnecessary confusion, I'll update the PR to remove code from that flow

2021-02-10 08:12 UTC, mohanarpit commented on app/client/src/pages/Editor/DataSourceEditor/index.tsx
> +    if (pluginDatasourceForm === "RestAPIDatasourceForm") {
@ofpiyush For my understanding, is there a more generic way of doing this? For example, if we have a custom `FooDatasourceForm` tomorrow, we'll have to add another if condition here, right? In React, is it possible to render the correct component based on the name of the component itself?

2021-02-10 08:28 UTC, ofpiyush commented on app/client/src/pages/Editor/DataSourceEditor/index.tsx
> +    if (pluginDatasourceForm === "RestAPIDatasourceForm") {
Dynamic imports aren't possible.

You'll need to make a registry pattern to achieve something similar.

But in this case the props the two need are somewhat different each other.

My current opinion is that we should probably only pass in routing params and let each implementation deal with pulling in other dependencies as it needs them.


I feel like by the time I'll do the sheets implementation I will have a better idea + confidence on how to abstract this out cleaner.

2021-02-10 08:33 UTC, hetunandu requested changes

2021-02-10 08:33 UTC, hetunandu commented on app/client/src/pages/Editor/DataSourceEditor/RestAPIDatasourceForm.tsx
> +) => {
missing return type

2021-02-10 08:33 UTC, hetunandu commented on app/client/src/pages/Editor/DataSourceEditor/RestAPIDatasourceForm.tsx
> +  }
Can be a static value and not a function

2021-02-10 08:33 UTC, hetunandu commented on app/client/src/pages/Editor/DataSourceEditor/RestAPIDatasourceForm.tsx
> +        text: "Unable to create API. Try adding a url to the datasource",
Move error to messages.ts

2021-02-10 09:28 UTC, ofpiyush commented on app/client/src/pages/Editor/DataSourceEditor/RestAPIDatasourceForm.tsx
> +        text: "Unable to create API. Try adding a url to the datasource",
I'd rather merge this into release and then do it on the PR #2798 

It's the same message as this one. https://github.com/appsmithorg/appsmith/pull/2798/files#diff-f3b32e5ef8708622d1b9d4d89bc887d61758e18ab16933c47aa633cc8b585bcfR135

2021-02-10 09:53 UTC, nidhi-nair commented on app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/AuthenticationServiceTest.java
> +        // 2. Without Client Id
Noted, I'll do this on the second PR since this is related to the authorization code flow, deleted this code for now.

2021-02-11 05:17 UTC, hetunandu commented
LGTM ✅

2021-02-11 05:44 UTC, trishaanand commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/DatasourceServiceImpl.java
> +                            dbDatasource.getDatasourceConfiguration().setAuthentication(null);
QQ : This seems to be setting authentication to be null before saving it to db. I couldn't figure out why.

2021-02-11 05:44 UTC, trishaanand commented on app/server/appsmith-server/src/test/java/com/appsmith/server/services/DatasourceServiceTest.java
> -                    DBAuth authentication = (DBAuth) updatedDatasource.getDatasourceConfiguration().getAuthentication();
Same here. This test seems to have been nullified.

2021-02-11 05:46 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/DatasourceServiceImpl.java
> +                            dbDatasource.getDatasourceConfiguration().setAuthentication(null);
This is to enable allowing users to switch from one type of authentication to "None" again. The none option would be the only case when the client comes back with a null for authentication. @trishaanand

2021-02-11 08:14 UTC, nidhi-nair commented on app/server/appsmith-server/src/test/java/com/appsmith/server/services/DatasourceServiceTest.java
> -                    DBAuth authentication = (DBAuth) updatedDatasource.getDatasourceConfiguration().getAuthentication();
So I've split the test into two to over come this. Also, I've converted the encryption state to an object so that it can work in three states. Null when encryption is not applicable, and boolean otherwise @trishaanand

2021-02-11 09:40 UTC, trishaanand commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/DatasourceServiceImpl.java
>                  datasource.getDatasourceConfiguration().setAuthentication(decryptSensitiveFields(datasource.getDatasourceConfiguration().getAuthentication()));
Quick question. Why are we returning decrypted fields when the datasource is fetched by id? This would expose the secret keys over the network path every time the datasource is fetched by id. If this functionality is required, could we provide this in any other function other than this? I say this because getById is called by default by the controller when we do a GET on /datasources/{id}.

2021-02-11 09:46 UTC, trishaanand commented on app/server/appsmith-server/src/main/java/com/appsmith/server/exceptions/AppsmithError.java
> +    INVALID_DATASOURCE_CONFIGURATION(400, 4015, "Datasource configuration is invalid", AppsmithErrorAction.DEFAULT),
Could we not use INVALID_DATASOURCE error where the configuration is invalid ?

2021-02-11 09:46 UTC, trishaanand commented on app/server/appsmith-server/src/main/java/com/appsmith/server/domains/Plugin.java
> +    String actionComponent;
How is this different from uiComponent?

2021-02-11 09:46 UTC, trishaanand commented on app/server/appsmith-server/src/main/java/com/appsmith/server/domains/Plugin.java
> +    String actionComponent;
Could we add comments for what these fields are used for?

2021-02-11 09:46 UTC, trishaanand commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/DatasourceServiceImpl.java
> +                    if (datasource.getDatasourceConfiguration() == null || datasource.getDatasourceConfiguration().getAuthentication() == null) {
Once again, we seem to be doing this post the copying of the null fields from the saved datasource to the datasource object received from the client for update. Post this step, we go ahead and save the object to the repository. Would this not simply set the authentication to null in the database object? Shouldn't we be doing this before the `copyNestedNonNullProperties` call?

2021-02-11 10:07 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/DatasourceServiceImpl.java
> +                    if (datasource.getDatasourceConfiguration() == null || datasource.getDatasourceConfiguration().getAuthentication() == null) {
Not that's the intent right? If the client comes in and tells me that there is no authentication at all, then I proceed with removing the existing authentication object. There is no other way to do this currently.

In case of an authentication object with no change, the client will be sending back an object with at least one valid value that is not encrypted. @trishaanand

2021-02-11 10:09 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/domains/Plugin.java
> +    String actionComponent;
Done

2021-02-11 10:14 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/DatasourceServiceImpl.java
>                  datasource.getDatasourceConfiguration().setAuthentication(decryptSensitiveFields(datasource.getDatasourceConfiguration().getAuthentication()));
The keys are all tagged `JsonIgnore` so they'll never be returned. The decryption is at this point because at all points in-memory the value to be used needs to be available. I haven't spent much time making this any stricter because we'll be replacing the entire encryption logic with annotation based conversions which will standardize usage across the server.

2021-02-11 10:18 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/exceptions/AppsmithError.java
> +    INVALID_DATASOURCE_CONFIGURATION(400, 4015, "Datasource configuration is invalid", AppsmithErrorAction.DEFAULT),
We'd have to use non-standard values for the parameters is why. We can't know what kind of non-2xx issue the the Authorization server returned with (this is generally very server specific, the specs only give a minimum requirement). Works either way for me tbh. FYI this is used in the authorization code flow so we can bypass it for now :D

Sorry for littered code from both flows. Merging two branches into one already took a lot of conflict resolving and I wasn't willing to unmerge and re-merge again. :(

2021-02-11 10:25 UTC, trishaanand commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/DatasourceServiceImpl.java
>                  datasource.getDatasourceConfiguration().setAuthentication(decryptSensitiveFields(datasource.getDatasourceConfiguration().getAuthentication()));
Aah ok. Then resolving this for now.

2021-02-11 10:25 UTC, trishaanand approved these changes

2021-02-11 10:41 UTC, ofpiyush approved these changes
[Since github allows me to do this.](https://www.youtube.com/watch?v=UzrX1wFYsxw)

2021-02-11 11:53 UTC, hetunandu approved these changes

2021-02-11 12:02 UTC, hetunandu approved these changes

2021-02-11 12:28 UTC, merged