chore: Add switch environment configuration telemetry
appsmithorg/appsmith pull request #26504
Opened 2023-08-21 08:00 UTC by ChandanBalajiBP

## Description
> Adds switch environment telemetry during datasource configuration 
>
>
#### PR fixes following issue(s)
Fixes #26540 

#### Type of change
- Chore (housekeeping or task changes that don't impact user perception)
>
>
>
## Testing
>
#### How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Also list any relevant details for your test configuration.
> Delete anything that is not relevant
- [x] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-08-21 08:26 UTC, ayushpahwa requested changes

2023-08-21 08:26 UTC, ayushpahwa commented on app/client/src/pages/Editor/DataSourceEditor/index.tsx
> +      AnalyticsUtil.logEvent("SWITCH_ENVIRONMENT", {
Please move it to the function called updateFilterSuccess

2023-08-21 10:26 UTC, ChandanBalajiBP commented
/ok-to-test

2023-08-21 10:27 UTC, ChandanBalajiBP commented on app/client/src/pages/Editor/DataSourceEditor/index.tsx
> +      AnalyticsUtil.logEvent("SWITCH_ENVIRONMENT", {
Updated
FYI: Have added other events for EE

2023-08-22 00:59 UTC, ayushpahwa approved these changes

2023-08-22 00:59 UTC, merged