fix: ME design audit CE
appsmithorg/appsmith pull request #26535
Opened 2023-08-21 14:24 UTC by ChandanBalajiBP

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.
>
## Description
> Add a TL;DR when description is extra long (helps content team)
>
> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change
>
> Links to Notion, Figma or any other documents that might be relevant to the PR
>
>
#### PR fixes following issue(s)
Fixes # (issue number)
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
#### Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video
>
>
#### Type of change
> Please delete options that are not relevant.
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
## Testing
>
#### How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Also list any relevant details for your test configuration.
> Delete anything that is not relevant
- [ ] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-08-24 23:02 UTC, ChandanBalajiBP commented
/build-deploy-preview skip-tests=true

2023-08-24 23:03 UTC, ChandanBalajiBP commented
/ok-to-test

2023-08-24 23:22 UTC, ChandanBalajiBP commented
/build-deploy-preview skip-tests=true

2023-08-25 13:19 UTC, ankitakinger commented on app/client/src/ee/components/EnvDeployInfoModal/index.tsx
> +  return null;
this code should exist at the below path:
`app/client/src/ce/components/EnvDeployInfoModal/index.tsx`

The code for this file should be just:
`export * from "ce/components/EnvDeployInfoModal"`

2023-08-29 12:28 UTC, ChandanBalajiBP commented
/build-deploy-preview skip-tests=true

2023-08-29 12:30 UTC, ankitakinger approved these changes
LGTM

2023-08-31 09:28 UTC, ChandanBalajiBP commented
/ok-to-test

2023-09-01 06:24 UTC, ChandanBalajiBP commented
/build-deploy-preview skip-tests=true

2023-09-01 06:26 UTC, ChandanBalajiBP commented
/ok-to-test

2023-09-04 13:22 UTC, ChandanBalajiBP commented
/ok-to-test

2023-09-06 12:44 UTC, ChandanBalajiBP commented
/ok-to-test

2023-09-06 14:33 UTC, ChandanBalajiBP commented
/ok-to-test

2023-09-07 20:48 UTC, ChandanBalajiBP commented
/ok-to-test

2023-09-07 20:50 UTC, ChandanBalajiBP commented
/ok-to-test

2023-09-08 05:23 UTC, ayushpahwa requested changes

2023-09-08 05:23 UTC, ayushpahwa commented on app/client/src/ce/constants/messages.ts
> +export const SAVE_AND_AUTHORISE_BUTTON_TEXT = () => "Save and Authorize";
I think these messages are already present, I can see the same on line 1774

2023-09-08 05:23 UTC, ayushpahwa commented on app/client/src/pages/common/datasourceAuth/index.tsx
> +  SAVE_AND_AUTHORISE_BUTTON_TEXT,
This import is done twice here

2023-09-11 09:19 UTC, ChandanBalajiBP commented
/ok-to-test

2023-09-11 11:17 UTC, ChandanBalajiBP commented
./ok-to-test

2023-09-11 11:28 UTC, ChandanBalajiBP commented
/ok-to-test

2023-09-11 18:29 UTC, ayushpahwa approved these changes

2023-09-11 20:35 UTC, ChandanBalajiBP commented
This PR was tested in [EE PR](https://github.com/appsmithorg/appsmith-ee/pull/1970) and here is the [comment](https://github.com/appsmithorg/appsmith-ee/pull/1970#issuecomment-1702734755) for approval. Hence adding test plan label myself.

2023-09-12 06:18 UTC, merged