chore: BaseWidget Restructuring
appsmithorg/appsmith pull request #26562
Opened 2023-08-22 10:28 UTC by marks0351

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.
>
## Description
> Add a TL;DR when description is extra long (helps content team)
>
> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change
>
> Links to Notion, Figma or any other documents that might be relevant to the PR
>
>
#### PR fixes following issue(s)
Fixes # (issue number)
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
#### Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video
>
>
#### Type of change
> Please delete options that are not relevant.
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
## Testing
>
#### How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Also list any relevant details for your test configuration.
> Delete anything that is not relevant
- [ ] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-08-22 10:28 UTC, marks0351 commented
/build-deploy-preview env=release

2023-08-22 10:29 UTC, marks0351 commented
/ok-to-test

2023-08-22 15:47 UTC, marks0351 commented
/build-deploy-preview env=release

2023-08-22 16:16 UTC, marks0351 commented
/build-deploy-preview env=release

2023-08-23 10:48 UTC, marks0351 commented
/ok-to-test

2023-08-23 10:53 UTC, marks0351 commented
/build-deploy-preview env=release

2023-08-23 12:43 UTC, marks0351 commented
/build-deploy-preview env=release

2023-08-23 13:27 UTC, marks0351 commented
/ok-to-test

2023-08-24 05:50 UTC, marks0351 commented
/ok-to-test

2023-08-24 13:12 UTC, marks0351 commented
/ok-to-test

2023-08-24 17:19 UTC, marks0351 commented
/ok-to-test

2023-08-25 05:40 UTC, marks0351 commented
/ok-to-test

2023-08-25 09:13 UTC, marks0351 commented
/ok-to-test

2023-08-25 11:40 UTC, marks0351 commented
/ok-to-test

2023-08-26 08:50 UTC, marks0351 commented
/ok-to-test

2023-08-26 10:57 UTC, marks0351 commented
/ok-to-test

2023-08-28 05:43 UTC, marks0351 commented
/build-deploy-preview env=release

2023-08-28 14:38 UTC, KelvinOm commented on app/client/src/widgets/BaseWidgetHOC/render/common/DraggableComponent.test.tsx
> +import { canDrag } from "./DraggableComponent";
Will there be tests for other components?

2023-08-28 14:38 UTC, KelvinOm commented on app/client/src/widgets/BaseWidgetHOC/render/common/DraggableComponent.tsx
> +type DraggableComponentProps = WidgetProps;
Why do we need this? Why not use the type directly?

2023-08-28 14:38 UTC, KelvinOm commented on app/client/src/widgets/BaseWidgetHOC/render/common/DraggableComponent.tsx
> + * @param isResizingOrDragging
Why we need this JSDoc? It just repeats the same thing that is written a few lines below.

2023-08-28 14:38 UTC, KelvinOm commented on app/client/src/widgets/BaseWidgetHOC/render/common/DraggableComponent.tsx
> +export default DraggableComponent;
Let's avoid `export default`?
https://google.github.io/styleguide/tsguide.html#exports

cc @riodeuno

2023-08-28 14:38 UTC, KelvinOm commented on app/client/src/widgets/BaseWidgetHOC/render/common/DraggableComponent.tsx
> +  const onDragStart = (e: any) => {
Let's type this correctly?

2023-08-28 14:38 UTC, KelvinOm commented on app/client/src/widgets/BaseWidgetHOC/render/common/DraggableComponent.tsx
> +      data-testid={isSelected ? "t--selected" : ""}
Don't use className for testing purposes. It is worth separating styling and testing. Besides, we already have `data-testid`.

2023-08-29 05:14 UTC, marks0351 commented on app/client/src/widgets/BaseWidgetHOC/render/common/canvasOnionUtils.ts
> +  children: any,
Thanks for pointing, this was dead code that made it to the PR. will be removing them.

2023-08-29 05:17 UTC, marks0351 commented on app/client/src/widgets/BaseWidgetHOC/render/common/DraggableComponent.test.tsx
> +import { canDrag } from "./DraggableComponent";
all these components are very old implementation which already have cypress test cases. we will be adding test cases to the newly imlemented hocs.

2023-08-29 06:18 UTC, marks0351 commented
/build-deploy-preview env=release

2023-08-29 06:48 UTC, marks0351 commented on app/client/src/widgets/BaseWidgetHOC/render/common/DraggableComponent.tsx
> +type DraggableComponentProps = WidgetProps;
This is also very old implementations that are just moved. Let me add the types here to help clean up this mess.

2023-08-29 07:39 UTC, marks0351 commented on app/client/src/widgets/BaseWidgetHOC/render/common/DraggableComponent.tsx
> +      data-testid={isSelected ? "t--selected" : ""}
makes sense. I will be creating a github issue to clean up such code.

2023-08-30 06:34 UTC, marks0351 commented
/build-deploy-preview skip-tests=true

2023-08-30 06:52 UTC, Sripriya93 commented
Issue with Tabs widget: @marks0351 
When we try to drop wigets in Tab2, we are able to see it switches to Tab1 


https://github.com/appsmithorg/appsmith/assets/104895602/4c5325b6-9f8a-4126-9d62-bae084ca6d03

2023-08-30 09:41 UTC, sbalaji1192 submitted a review, later dismissed
Base widget and widget changes look good!

2023-08-30 10:42 UTC, marks0351 commented
> Issue with Tabs widget: @marks0351 When we try to drop wigets in Tab2, we are able to see it switches to Tab1
> 
>  Untitled.application.1._.Editor._.Appsmith.-.30.August.2023.mp4

@Sripriya93  Can we pls test Tabs, List and Table first.

2023-08-30 13:30 UTC, marks0351 commented
/ok-to-test

2023-08-30 15:06 UTC, marks0351 commented
/ok-to-test

2023-08-31 06:45 UTC, marks0351 commented
/build-deploy-preview skip-tests=true

2023-08-31 06:45 UTC, marks0351 commented
/ok-to-test

2023-08-31 08:57 UTC, marks0351 commented
/build-deploy-preview skip-tests=true

2023-08-31 08:57 UTC, marks0351 commented
/ok-to-test

2023-08-31 16:45 UTC, prsidhu commented on app/client/src/layoutSystems/common/widgetName/WidgetNameLayer.tsx
> +const getErrorCount = memoize(
should this be a util?

2023-08-31 16:47 UTC, prsidhu commented on app/client/src/layoutSystems/common/widgetName/WidgetNameLayer.tsx
> +        showControls={props.type === "MODAL_WIDGET"}
Can this be passed as a boolean prop? ModalWidgetOnionLayer sends ```showControls={true}```, rather than checking it for every widget.

2023-09-01 05:32 UTC, marks0351 commented
/ok-to-test

2023-09-01 05:32 UTC, marks0351 commented
/build-deploy-preview env=release

2023-09-01 05:33 UTC, marks0351 commented
/build-deploy-preview skip-tests=true

2023-09-01 08:58 UTC, rahulramesha commented
/build-deploy-preview skip-tests=true

2023-09-01 08:58 UTC, rahulramesha commented
/ok-to-test

2023-09-01 12:38 UTC, KelvinOm commented on app/client/src/layoutSystems/autolayout/editor/AutoLayoutCanvasArenas/hooks/useBlocksToBeDraggedOnCanvas.ts
> +  const parentDiff = isDragging
(nitpick) This hard to read. The checks can be made separately, the object can be created separately. Also, the repetition will disappear.

2023-09-01 12:38 UTC, KelvinOm commented on app/client/src/layoutSystems/autolayout/editor/AutoLayoutCanvasArenas/hooks/useBlocksToBeDraggedOnCanvas.ts
> +  const parentDiff = isDragging
Same for `relativeStartPoints`

2023-09-01 12:38 UTC, KelvinOm commented on app/client/src/layoutSystems/autolayout/editor/AutoLayoutCanvasArenas/hooks/useCanvasDragging.ts
> +    calculateHighlights(snapColumnSpace);
`useLayoutEffect` doesn't help here?

2023-09-01 12:38 UTC, KelvinOm commented on app/client/src/layoutSystems/autolayout/editor/AutoLayoutCanvasArenas/hooks/useRenderBlocksOnCanvas.ts
> +    highlight: HighlightInfo | undefined,
(nitpick) Still better `highlight?: HighlightInfo`

2023-09-01 12:38 UTC, KelvinOm commented on app/client/src/layoutSystems/common/modalOverlay/ModalOverlayLayer.tsx
> +    return <>{children}</>;
```suggestion
    return {children};
```

2023-09-01 12:38 UTC, KelvinOm commented on app/client/src/layoutSystems/common/utils/canvasDraggingUtils.ts
> + * @param newWidget
(nitpick) Useless JSdoc.

2023-09-04 08:10 UTC, marks0351 commented
/build-deploy-preview skip-tests=true

2023-09-04 08:11 UTC, marks0351 commented
/ok-to-test

2023-09-04 11:41 UTC, rahulramesha commented on app/client/src/layoutSystems/autolayout/editor/AutoLayoutCanvasArenas/hooks/useCanvasDragging.ts
> +    calculateHighlights(snapColumnSpace);
Not sure i understand. could you please elaborate?

2023-09-04 11:42 UTC, rahulramesha commented on app/client/src/layoutSystems/common/modalOverlay/ModalOverlayLayer.tsx
> +    return <>{children}</>;
This would make it not usable as a JSX node as used in the same file below
cc: @marks0351

2023-09-04 11:43 UTC, rahulramesha commented
/build-deploy-preview skip-tests=true

2023-09-04 11:43 UTC, rahulramesha commented
/ok-to-test

2023-09-04 13:42 UTC, KelvinOm commented on app/client/src/layoutSystems/autolayout/editor/AutoLayoutCanvasArenas/hooks/useCanvasDragging.ts
> +    calculateHighlights(snapColumnSpace);
As far as I understand, `setTimeout` is used here to perform an action at the end of the stack. Wouldn't it be enough to execute `calculateHighlights` after loading the DOM?

2023-09-05 10:07 UTC, rahulramesha commented on app/client/src/layoutSystems/autolayout/editor/AutoLayoutCanvasArenas/hooks/useCanvasDragging.ts
> +  calculateHighlights(snapColumnSpace);
@prsidhu I have removed the setTimeout that was wrapping this method. This seems to be working fine in the tested scenarios. Please let me know if i'm missing any scenarios that would be caused by this to fail

2023-09-05 12:08 UTC, marks0351 commented on app/client/src/layoutSystems/common/modalOverlay/ModalOverlayLayer.tsx
> +    return <>{children}</>;
you could remove children's type and make it any.

2023-09-05 12:31 UTC, riodeuno requested changes
Most of the existing functions in the Fixed Layout, can remain as they are, but when it comes to common code and utilities, there must be clarity with comments.

2023-09-05 12:31 UTC, riodeuno commented on app/client/src/layoutSystems/autolayout/editor/AutoLayoutEditorWraper.tsx
> +export const AutoLayoutEditorWraper = (props: WidgetProps) => {
Please add a jsdoc explaining what this component is supposed to do, and what the responsibilities are

2023-09-05 12:31 UTC, riodeuno commented on app/client/src/layoutSystems/autolayout/viewer/AutoLayoutViewerModalOnion.tsx
> +    <AutoLayoutWidgetComponent {...props}>
Do all of the wrappers need all the `props`?

2023-09-05 12:31 UTC, riodeuno commented on app/client/src/layoutSystems/common/draggable/DraggableComponent.tsx
> +type DraggableComponentProps = {
👍🏼

2023-09-05 12:31 UTC, riodeuno commented on app/client/src/layoutSystems/common/modalOverlay/ModalOverlayLayer.tsx
> +    // TODO(abhinav): Create a static property with is a map of widget properties
This comment is clearing not referring to anything here. Let's remove it.

2023-09-05 12:31 UTC, riodeuno commented on app/client/src/layoutSystems/common/utils/canvasDraggingUtils.ts
> + * This method helps in updating rows for dropTarget/canvas by using updateDropTargetRows
How does it "help"? Does it call a function? Does it dispatch an action? What does it do before calling or dispatching?

2023-09-06 07:20 UTC, marks0351 commented on app/client/src/layoutSystems/autolayout/editor/AutoLayoutEditorWraper.tsx
> +  const canvasWidget = props.type === "CANVAS_WIDGET";
This can be removed only if CanvasWidget is not a widget.
even if we wanted to use detachFromLayout prop we cannot coz Modal widget also has the same prop. This can only be done if we find a way to create canvas widgets without the createWidget api(may be someting like createCanvas).

we clearly have one Anstraction(Basewidget) doing the job(creating a base set of apis) for three types of widgets and all three need different Wrappers/Onions. 
- Persentational Onion(Layout Components) for Canvas widgets
- Overlay Onion for Modal widgets
- Widget Onion for rest of the widgets

potential fixes:

we either need special props for widgets like canvas widget to skip adding wrappers 
ex: CANVAS_WIDGET config will have a prop called presentationalComponent to avoid conditional wrapping using widget types.

Right way:

Explore a way to remove canvas widget as a Base widget extension, 
Canvas Widget IMO has no right to be in the widget system coz its deeply connected with Layout Engines, 
Canvas widget becomes a view component that lays down widgets
which is only used by the MainCanvas(this component would also become a view component instead of being the first parent in the dsl) and any droppable components.

Pros: all that we are talking about, better code structure, properly laid out responsibilities.
Cons: Backward compatibility with older dsls that use canvas widgets as a widget might need a lot of effort.

2023-09-06 07:41 UTC, marks0351 commented on app/client/src/layoutSystems/autolayout/common/resizer/AutoLayoutResizable.tsx
>    // auto-layouts resizable is dependent on the app state of the widget so on delete it crashes the app
This was added to fix a certain issue with List widget during Auto Layout V1 dev.

2023-09-06 07:43 UTC, marks0351 commented on app/client/src/layoutSystems/autolayout/common/resizer/AutoResizableLayer.tsx
> +  if (props.resizeDisabled || props.type === "SKELETON_WIDGET") {
yes it will. Skeleton widget is the first layer before the actual widget provided by widget component. which is then wrapped with all other layers of the layout system.

2023-09-06 07:45 UTC, marks0351 commented on app/client/src/layoutSystems/autolayout/common/resizer/AutoResizableLayer.tsx
> +      {...props}
yes present implementation require all props to be passed down. But this will fixed for Auto Layout in Anvil

2023-09-06 07:46 UTC, marks0351 commented on app/client/src/layoutSystems/autolayout/editor/AutoLayoutCanvasArenas/AutoCanvasDraggingArena.tsx
> +      snapColSpace={snapColumnSpace}
yes this is the current implementation so it is still relevant.

2023-09-06 07:49 UTC, marks0351 commented on app/client/src/layoutSystems/autolayout/editor/AutoLayoutCanvasArenas/hooks/useBlocksToBeDraggedOnCanvas.ts
> +  const defaultHandlePositions = {
they are the default handle positions when a user is dragging a widget. When dragged all widgets have a different handle position based on where the user is clicking and dragging, but for new widget dragged out of the entity explorer the position of handling will be top left corner, we cannot use the edge coz if so placing a widget would become difficult so we use a 20 pixel buffer on top and left corners.

2023-09-06 07:54 UTC, marks0351 commented on app/client/src/layoutSystems/autolayout/editor/AutoLayoutEditorModalOnion.tsx
> +    <AutoLayoutWidgetComponent {...props}>
it does need all props coz of current implementation of autoDimensionConfig which is called inside AutoDimensionObserverLayer which is rendered by this component.

2023-09-06 07:54 UTC, marks0351 commented on app/client/src/layoutSystems/autolayout/editor/AutoLayoutEditorWidgetOnion.tsx
> +            <AutoResizableLayer {...props}>
yes, coz of present day implementation of resizablecomponent.

2023-09-06 07:56 UTC, marks0351 commented on app/client/src/layoutSystems/autolayout/viewer/AutoLayoutViewerModalOnion.tsx
> +    <AutoLayoutWidgetComponent {...props}>
not all wrapper need all props, the need is only because of internal implemention of wrappers like ResizableComponent, Auto Height Layers, Auto Dimension Layers, etc

2023-09-06 14:04 UTC, rahulramesha commented on app/client/src/layoutSystems/autolayout/editor/AutoLayoutCanvasArenas/hooks/useBlocksToBeDraggedOnCanvas.ts
> +    setTimeout(() => {
Looks like It is there to select widget after the new widget is added to the DSL, This need to be changed added to the saga after it is added so that we can get rid of the `setTimeout`

2023-09-06 14:10 UTC, rahulramesha commented on app/client/src/layoutSystems/autolayout/editor/AutoLayoutCanvasArenas/hooks/useCanvasDragging.ts
> +      const resetCanvasState = () => {
This contains logic that is used in the same file and utilizes the objects from inside the hook... This also is being used in the eventListener as is, moving to a utility would still mean we would need to pass the variables used in the method and hence cannot be directly used in the event listener

2023-09-06 14:13 UTC, rahulramesha commented on app/client/src/layoutSystems/autolayout/editor/AutoLayoutCanvasArenas/hooks/useCanvasDragging.ts
> +        const resetDragging = () => {
This utilizes the variables and methods form the hook, i feel this fits in this file... please let me know if you feel that it definitely needs to be moved.

2023-09-06 14:14 UTC, rahulramesha commented on app/client/src/layoutSystems/common/utils/canvasDraggingUtils.ts
> + * This method returns blocks and dragging spaces of the widgets being dragged on canvas..
I have explained it below in the returns section of the jsdoc..

2023-09-06 14:19 UTC, rahulramesha commented on app/client/src/layoutSystems/common/utils/canvasDraggingUtils.ts
> + * @param isNewWidget indicates if the widget is a new widget
This method returns objects based on positions, for new widgets it would not have original positions and hence needs a different logic for default values, where as the existing widgets can update them from dsl. 
The caller in this scenario only cares about the result rather than having that logic to check what result it wants..

2023-09-06 14:20 UTC, rahulramesha commented on app/client/src/layoutSystems/common/utils/canvasDraggingUtils.ts
> + * @param selectedWidgets array of selected widget ids
It requires selected widgets because those are the widgets that are currently being dragged on canvas. and this method is used to get the drag widget objects by deriving from that array.

2023-09-06 14:23 UTC, rahulramesha commented on app/client/src/layoutSystems/common/utils/canvasDraggingUtils.ts
> + * Calculates parent positions diff in pixels
updated to jsdoc. This is required to offset widget positions to get the actual positions of widget relative to canvas.

2023-09-06 14:23 UTC, rahulramesha commented on app/client/src/layoutSystems/common/utils/canvasDraggingUtils.ts
> + * @param isChildOfCanvas indicates if the dragging widgets are the original child of the canvas
yes

2023-09-06 14:24 UTC, rahulramesha commented on app/client/src/layoutSystems/fixedlayout/editor/FixedLayoutCanvasArenas/hooks/useBlocksToBeDraggedOnCanvas.ts
> +    return updateBottomRowMethod(
changed the name to `updateBottomRowHelper`

2023-09-06 14:29 UTC, rahulramesha commented on app/client/src/layoutSystems/common/utils/canvasDraggingUtils.ts
> + * This method returns the bound updateRelativeRows method with the arguments bounded
This method returns the updateRelativeRows method which is bound to the arguments supplied to this method.
Honestly not sure why its called that but i feel, The name relativeRows might indicate the comparison of bottomMostWidget's rows and canvas's existing rows..

Couldn't think of a proper name for it, please feel free to suggest an appropriate name

2023-09-07 06:46 UTC, marks0351 commented
/ok-to-test

2023-09-07 06:47 UTC, marks0351 commented
/build-deploy-preview skip-tests=true

2023-09-07 07:02 UTC, kamakshibhat-appsmith commented
Unable to see vertical resize indicators on the MODAL

2023-09-07 07:12 UTC, kamakshibhat-appsmith commented
BUG : we are able to see the Modal widget's outline in preview mode

<img width="669" alt="Screenshot 2023-09-07 at 12 40 21 PM" src="https://github.com/appsmithorg/appsmith/assets/113327629/648c078f-21b7-404d-88d3-74b80ac509d5">

2023-09-07 07:34 UTC, kamakshibhat-appsmith commented
BUG: Modal is not shrinking to min dimesions in mobile breakpoint in the editor

<img width="1007" alt="Screenshot 2023-09-07 at 12 31 44 PM" src="https://github.com/appsmithorg/appsmith/assets/113327629/432cde72-2150-4c8e-bca5-5a2349ac5b9c">

2023-09-07 07:37 UTC, kamakshibhat-appsmith commented
BUG: We are able to resize the modal beyond the editor dimensions

<img width="1262" alt="Screenshot 2023-09-07 at 1 07 26 PM" src="https://github.com/appsmithorg/appsmith/assets/113327629/0ef1aa98-cabe-4139-a6ac-475229d0dcbe">

2023-09-07 08:31 UTC, marks0351 commented
/build-deploy-preview skip-tests=true

2023-09-07 08:31 UTC, marks0351 commented
/ok-to-test

2023-09-08 05:52 UTC, marks0351 commented
/ok-to-test

2023-09-08 05:52 UTC, marks0351 commented
/build-deploy-preview skip-tests=true

2023-09-08 11:01 UTC, riodeuno reviewed
Thanks for accepting my review suggestions. I do believe that we need to be more explicit with the details when writing code comments.

2023-09-08 14:09 UTC, marks0351 commented on app/client/src/layoutSystems/autolayout/common/autoDimensionObserver/AutoDimensionObserverLayer.tsx
> + * Component provides specific implementation for onDimensionUpdate and
@riodeuno the ideal way is to correct the implementation of this particular feature to actually make sense of what is being implemented which is not the scope of this pr. and all this code is going away once anvil comes.

2023-09-08 14:11 UTC, marks0351 commented on app/client/src/layoutSystems/autolayout/common/autoDimensionObserver/AutoDimensionObserverLayer.tsx
> +export const AutoDimensionObserverLayer = (props: BaseWidgetProps) => {
yes we are.

2023-09-08 16:41 UTC, rahulramesha commented on app/client/src/layoutSystems/autolayout/editor/AutoLayoutCanvasArenas/hooks/useBlocksToBeDraggedOnCanvas.ts
> +    setTimeout(() => {
https://github.com/appsmithorg/appsmith/issues/27118

2023-09-08 16:46 UTC, rahulramesha commented on app/client/src/layoutSystems/autolayout/editor/AutoLayoutCanvasArenas/hooks/useCanvasDragging.ts
> +          setDraggingCanvas(MAIN_CONTAINER_WIDGET_ID);
The canvas is reset when mouse leaves the canvas... 
When reset the the current canvas dragging is set to false, all the blocks drawn on html canvas are cleared. 
And if the page is still in dragging state the the dragging canvas is set to main canvas.

2023-09-08 16:51 UTC, rahulramesha commented on app/client/src/layoutSystems/autolayout/editor/AutoLayoutCanvasArenas/hooks/useCanvasDragging.ts
> +        const resetDragging = () => {
This does not contain unit tests because it is inside a hook and also because the method is simplistic with a simple goal that dispatches action based on two flags.

2023-09-11 07:25 UTC, marks0351 commented
@riodeuno @rahulramesha and myself will be creating discussion points out of the review comments that are not part of the scope of this particulars pr's tasks.
@riodeuno ur request changes status is blocking us from merging this pr. pls do check and approve if there are no changes needed in this particular pr.

2023-09-11 07:28 UTC, riodeuno approved these changes
@marks0351 Got it. Based on your above comment, I'm approving this PR. Please create the appropriate tasks as discussed.

2023-09-11 07:47 UTC, rahulramesha commented
/ok-to-test

2023-09-11 11:15 UTC, rahulramesha commented
/ok-to-test

2023-09-11 15:55 UTC, merged