feat: Add isSuggested value to templates for all plugins
appsmithorg/appsmith pull request #26623
Opened 2023-08-24 09:02 UTC by Irongade

This PR adds an isSuggested value to templates for all plugins

Fixes # (issue number)

- New feature (non-breaking change which adds functionality)

>
>
>
## Testing
>
#### How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Also list any relevant details for your test configuration.
> Delete anything that is not relevant
- [ ] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-08-24 09:14 UTC, Irongade commented
/ok-to-test

2023-08-24 09:16 UTC, nidhi-nair commented
@Irongade could we please attach the issue that we are fixing with this change? It helps for anyone outside of the immediate team working on this to gain context of what's up even when they look back at this PR in the future.

2023-08-24 09:18 UTC, Irongade commented
> @Irongade could we please attach the issue that we are fixing with this change? It helps for anyone outside of the immediate team working on this to gain context of what's up even when they look back at this PR in the future.

Sure, I just created one and I've attached it.

2023-08-25 04:39 UTC, sumitsum requested changes

2023-08-25 04:39 UTC, sumitsum commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/DatasourceStructure.java
> +            if (isSuggested) {
Hi Ade, QQ: could we remove the `if` condition here ?

2023-08-25 04:39 UTC, sumitsum commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/DatasourceStructure.java
> +            if (isSuggested) {
Could we remove the `if` condition here ? 
Same for all the other constructors.

2023-08-25 04:47 UTC, sumitsum commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/DatasourceStructure.java
> +        boolean isSuggested;
I think we also save query templates in Mongo DB. For all those templates this field does not exist, so when they get loaded in the API server memory and sent to the client this field should show up as null - is the client side designed to handle null value ? 
Have you been able to test this feature with a datasource which had structure fetched beforehand and then the instance got udated with this feature ?

2023-08-25 08:53 UTC, Irongade commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/DatasourceStructure.java
> +            if (isSuggested) {
The reason why I added an if condition here is because, this field should only be set for suggested templates only. For other templates, it should not exist.

2023-08-28 08:32 UTC, Irongade commented
/ok-to-test

2023-08-28 08:39 UTC, sumitsum approved these changes

2023-08-30 07:25 UTC, Irongade commented
/ok-to-test

2023-08-30 10:49 UTC, merged