feat: email notification
appsmithorg/appsmith pull request #26692
Opened 2023-08-28 08:48 UTC by shubham7saxena7

2023-08-28 11:22 UTC, shubham7saxena7 commented
/ok-to-test

2023-08-28 19:09 UTC, nsarupr requested changes
Reviewed.

Major concern is around adding a new service: `EmailService`. We already have a component `EmailSender` which is going the part of sending emails.

2023-08-29 09:25 UTC, shubham7saxena7 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/UserAndAccessManagementServiceCEImpl.java
> +                                                    true)
we are not sending two mails here, the createNewUserAndSendInviteEmail does not send mail anymore, will refactor the method name later. 

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UserServiceCEImpl.java check this file for ref

2023-08-30 11:23 UTC, nsarupr reviewed
Added comments. Please check.

2023-08-30 11:23 UTC, nsarupr commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UserServiceCEImpl.java
>       * @param user User object representing the user to be created/enabled.
Can we cleanup this code comment if not required?

2023-08-30 11:23 UTC, nsarupr commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UserServiceCEImpl.java
> +        return userCreate(newUser, isAdminUser);
Can we rename the method or remove it? We are no longer sending mails here.

2023-08-31 05:50 UTC, RakshaKShetty commented
/build-deploy-preview skip-tests=true

2023-08-31 06:39 UTC, RakshaKShetty commented
@shubham7saxena7 , @pratapaprasanna  I am seeing a ngnix error on this DP can anyone of you have a look on this.

2023-09-01 12:13 UTC, shubham7saxena7 commented
/build-deploy-preview skip-tests=true

2023-09-03 03:28 UTC, shubham7saxena7 commented
/ok-to-test

2023-09-03 10:01 UTC, shubham7saxena7 commented
/ok-to-test

2023-09-03 14:52 UTC, shubham7saxena7 commented
/build-deploy-preview skip-tests=true

2023-09-03 14:55 UTC, shubham7saxena7 commented
/ok-to-test

2023-09-06 07:38 UTC, ankitakinger commented
/build-deploy-preview skip-tests=true

2023-09-06 12:40 UTC, ankitakinger commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/UserAndAccessManagementServiceCEImpl.java
> +                                                        .sendInstanceAdminInviteEmail(newCreatedUser, originHeader)
QQ: Should this email be sent inside this function? I think it should come inside `updateSuperUsers` function and not `inviteUsers`. Correct me if I'm wrong. Asking because everything else seems to be fixed on CE notification emails as per what I checked. Only instance admin emails is still not working.
CC: @trishaanand @nsarupr

2023-09-10 11:02 UTC, shubham7saxena7 commented
/build-deploy-preview skip-tests=true

2023-09-12 05:55 UTC, nsarupr requested changes
Minor comments. Please resolve them and then we are good to go with this PR.

2023-09-12 05:55 UTC, nsarupr commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/UserAndAccessManagementServiceCEImpl.java
> +                .cache();
Nit: Don't need a cache here, since it is being used only once.

2023-09-12 05:55 UTC, nsarupr commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/UserSignupCE.java
> +            UserSignupRequestDTO userFromRequest, String originHeadr, ServerWebExchange exchange);
```suggestion
            UserSignupRequestDTO userFromRequest, String originHeader, ServerWebExchange exchange);
```

2023-09-12 05:55 UTC, nsarupr commented on app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/UserControllerCE.java
> +            @RequestHeader("OriginHeader") String originHeader, ServerWebExchange exchange) {
Please check if this needs to be `OriginHeader` or `Origin`

2023-09-12 05:55 UTC, nsarupr commented on app/server/.dev.env.swp
Remove this from git diff.

2023-09-12 05:55 UTC, nsarupr commented on app/server/appsmith-server/src/test/java/com/appsmith/server/services/ce/EmailServiceCEImplTest.java
Great job with the Email arguments assertions.

2023-09-12 06:30 UTC, shubham7saxena7 commented
/ok-to-test

2023-09-12 06:30 UTC, ankitakinger commented
@shubham7saxena7 Are we sure the instance admin emails are working now?

2023-09-12 06:30 UTC, shubham7saxena7 commented
/build-deploy-preview skip-tests=true

2023-09-12 13:27 UTC, shubham7saxena7 commented
/ok-to-test

2023-09-12 13:27 UTC, shubham7saxena7 commented
/build-deploy-preview skip-tests=true

2023-09-12 15:19 UTC, shubham7saxena7 commented
/build-deploy-preview skip-tests=true recreate=true

2023-09-12 17:18 UTC, shubham7saxena7 commented
/build-deploy-preview skip-tests=true

2023-09-13 09:38 UTC, RakshaKShetty commented
The testing scenario that is covered are as below :
1. I received email for forgot password and reset password both and the UI also looks gud
2. When the user is invited for the first time to a works space as a Admin/ developer/viewer the Emails are sent and UI also looks gud


Issues faced on This :
1.If the existing user is invited to any new user workspace the button should be displayed as "Go to your appsmith workspace instead of  "Join your appsmith workspace"
2.The Instance admin invite format looks different from the One we have on notion Docs

2023-09-13 10:56 UTC, shubham7saxena7 commented
/ok-to-test

2023-09-13 10:56 UTC, shubham7saxena7 commented
/build-deploy-preview skip-tests=true

2023-09-13 11:30 UTC, shubham7saxena7 commented
/build-deploy-preview skip-tests=true

2023-09-13 16:28 UTC, shubham7saxena7 commented
/build-deploy-preview skip-tests=true

2023-09-14 04:35 UTC, RakshaKShetty commented
/build-deploy-preview skip-tests=true

2023-09-14 06:25 UTC, RakshaKShetty commented
1. The CTA Should change according to the user status i.e if the user is new user or a old user
2.Instance admin email subject should be corrected

2023-09-14 14:01 UTC, ankitakinger commented
/build-deploy-preview skip-tests=true

2023-09-14 14:57 UTC, ankitakinger commented
/build-deploy-preview skip-tests=true

2023-09-15 05:38 UTC, trishaanand commented
/ok-to-test

2023-09-15 09:26 UTC, ankitakinger commented
/build-deploy-preview skip-tests=true

2023-09-15 09:58 UTC, nsarupr requested changes
We should not have multiple parallel calls happening on the makeSuperUsers().

2023-09-15 09:58 UTC, nsarupr commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/EnvManagerCEImpl.java
> +                        })))
Hey, this is a going to cause flakiness in the Administrator Role. Here, you are invoking multiple parallel calls to the makeSuperUser method with different usernames.

2023-09-15 11:55 UTC, shubham7saxena7 commented
/ok-to-test

2023-09-15 13:49 UTC, shubham7saxena7 commented
/build-deploy-preview skip-tests=true

2023-09-15 13:52 UTC, nsarupr approved these changes
Changes look good to me

2023-09-17 07:52 UTC, shubham7saxena7 commented
/ok-to-test

2023-09-17 11:30 UTC, merged