Property pane enhancements
appsmithorg/appsmith pull request #2670
Opened 2021-01-21 20:11 UTC by riodeuno

## Description

- Property pane sections are collapsible
- Property pane controls can be hidden conditionally
- Property pane configurations now come from the widget instead of a global config file
- Property pane property updates can be hooked with other related updates
- Property pane control and section ids are generated dynamically now.

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Manually

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-01-25 05:18 UTC, hetunandu commented on app/client/src/utils/PropertyControlFactory.tsx
> +      if (customEditor) controlBuilder = this.controlMap.get(customEditor);
Instead of passing a custom editor here, can we instead pass any custom config you want to set inside the code editor instead?

2021-01-25 08:28 UTC, riodeuno commented on app/client/src/utils/PropertyControlFactory.tsx
> +      if (customEditor) controlBuilder = this.controlMap.get(customEditor);
That's a great idea! It will allow for more customization. I'll make the change.

2021-03-07 20:04 UTC, riodeuno commented on app/client/src/utils/PropertyControlFactory.tsx
> +      if (customEditor) controlBuilder = this.controlMap.get(customEditor);
These changes are coming in #2389

2021-03-07 22:19 UTC, riodeuno commented
@hetunandu @Nikhil-Nandagopal This PR seems ready to merge. Please review.

2021-03-08 02:13 UTC, hetunandu requested changes
Minor changes needed

2021-03-08 02:13 UTC, hetunandu commented on app/client/src/components/designSystems/appsmith/ChartComponent.tsx
> +);
We should try to dynamically import these plugins if possible.

2021-03-08 02:13 UTC, hetunandu commented on app/client/src/components/designSystems/appsmith/ChartComponent.tsx
> +    let config = this.props.customFusionChartConfig as any;
The customFusionChartConfig type should be defined and used here instead of the Chart Widget level

2021-03-08 07:28 UTC, riodeuno commented on app/client/src/components/designSystems/appsmith/ChartComponent.tsx
> +);
I checked for that. Couldn't find the API to do so.

2021-03-09 05:11 UTC, riodeuno commented on app/client/src/components/designSystems/appsmith/ChartComponent.tsx
> +    let config = this.props.customFusionChartConfig as any;
This is done.

2021-03-09 05:20 UTC, hetunandu submitted a review, later dismissed

2021-03-22 05:16 UTC, hetunandu submitted a review, later dismissed

2021-03-22 05:16 UTC, hetunandu commented on app/client/src/components/designSystems/appsmith/ChartComponent.tsx
> +          log.debug(e);
Should be logged as an error

2021-03-24 08:32 UTC, hetunandu approved these changes

2021-03-24 09:19 UTC, hetunandu submitted a review, later dismissed

2021-03-24 12:33 UTC, hetunandu approved these changes

2021-03-24 22:05 UTC, merged