feat: git connect v2
appsmithorg/appsmith pull request #26725
Opened 2023-08-28 19:42 UTC by brayn003

## Description
UX improvements for Git Connect Flow
https://zpl.io/W4AQoek

#### PR fixes following issue(s)
Fixes #25588

#### Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video
>
>
#### Type of change
- New feature (non-breaking change which adds functionality)
- This change requires a documentation update
>
>
>
## Testing
>
#### How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Also list any relevant details for your test configuration.
> Delete anything that is not relevant
- [ ] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-09-01 20:31 UTC, brayn003 commented
/ok-to-test sha=d279cd2

2023-09-05 04:43 UTC, brayn003 commented
/build-deploy-preview

2023-09-05 11:49 UTC, hetunandu requested changes
Minor changes needed

2023-09-05 11:49 UTC, hetunandu commented on app/client/src/pages/Editor/gitSync/GitSyncModal/index.tsx
> +  const isGitConnectV2Enabled = useFeatureFlag(
💯

2023-09-05 11:49 UTC, hetunandu commented on app/client/src/pages/Editor/gitSync/Tabs/GitSettings/index.tsx
> +  // const globalGitConfig = useSelector(getGlobalGitConfig);
Remove comments if not needed

2023-09-05 11:49 UTC, hetunandu commented on app/client/src/pages/Editor/gitSync/constants.ts
> +// import {
Why add commented code?

2023-09-05 11:49 UTC, hetunandu commented on app/client/src/pages/Editor/gitSync/hooks/useSSHKeyPair.ts
> +const NOOP = () => {
You can use lodash noop instead to creating one for each file
`_.noop`

2023-09-05 13:22 UTC, brayn003 commented on app/client/src/pages/Editor/gitSync/hooks/useSSHKeyPair.ts
> +const NOOP = () => {
thanks, this makes life easier

2023-09-05 13:28 UTC, brayn003 commented
/build-deploy-preview

2023-09-07 05:42 UTC, Parthvi12 commented
/build-deploy-preview

2023-09-07 08:43 UTC, Parthvi12 commented
- [ ] @brayn003 Merge option doesn't show dropdown with all branches, can you please check:

https://github.com/appsmithorg/appsmith/assets/80334441/57a4805d-aa7a-4df9-b9a9-a7e99b57d710

2023-09-07 20:10 UTC, brayn003 commented
/ok-to-test sha=7ed082c

2023-09-07 20:10 UTC, brayn003 commented
/build-deploy-preview

2023-09-08 04:58 UTC, brayn003 commented
@Parthvi12 I have added the fixes. Can you please check again?

2023-09-08 06:30 UTC, brayn003 commented
> <img alt="Screenshot 2023-09-08 at 11 46 36 AM" width="1440" src="https://user-images.githubusercontent.com/80334441/266519303-90582be1-b10e-4eac-b153-ee91a58aa282.png">

@Parthvi12  This is already an existing component, I have borrowed it from the old flow

2023-09-08 06:54 UTC, brayn003 commented
> > <img alt="Screenshot 2023-09-08 at 11 46 36 AM" width="1440" src="https://user-images.githubusercontent.com/80334441/266519303-90582be1-b10e-4eac-b153-ee91a58aa282.png">
> 
> @Parthvi12 This is already an existing component, I have borrowed it from the old flow

Also, it is not currently possible to achieve this design using ADS input

2023-09-08 07:40 UTC, Parthvi12 commented
/build-deploy-preview

2023-09-08 10:52 UTC, Parthvi12 commented
@brayn003 Thanks! Verified the fixes there are couple of issues which exist, can you please check that:

- [ ] When git connection fails, the error is thrown but can't see the error until we scroll up, also there is grammatical error in msg, adding recording:

https://github.com/appsmithorg/appsmith/assets/80334441/e40facd5-62d9-4e83-9e73-26d3087eb77a

- [ ] When we try to import empty repo, the connect modal doesn't throw any error:

<img width="1440" alt="Screenshot 2023-09-08 at 4 14 54 PM" src="https://github.com/appsmithorg/appsmith/assets/80334441/e3f927ab-b057-46d2-9d42-fb1fd4cc1778">

- [ ] In Safari, the modal moves to top left for a moment and then come back to center

2023-09-08 12:04 UTC, brayn003 commented
/ok-to-test sha=b942b4e

2023-09-08 12:09 UTC, Parthvi12 commented
/build-deploy-preview

2023-09-08 13:32 UTC, Parthvi12 commented
/build-deploy-preview

2023-09-10 14:45 UTC, brayn003 commented
> * [x]  In Safari, the modal moves to top left for a moment and then come back to center , when we open it.

Tested on Safari, unable to replicate. I have added a fix for this issue. Can you please recheck with the most recent DP

2023-09-10 14:45 UTC, brayn003 commented
/ok-to-test sha=cee44db

2023-09-10 16:14 UTC, Parthvi12 commented
/build-deploy-preview

2023-09-10 17:04 UTC, Parthvi12 commented
@brayn003 Strange, Safari issue still happens for me, I will create a separate issue for it, not treating it as blocker for this PR


https://github.com/appsmithorg/appsmith/assets/80334441/4859fcef-d672-4a9a-8e1d-922d1a0dd4a4

2023-09-11 05:07 UTC, Parthvi12 commented on app/client/cypress/e2e/Regression/ClientSide/Git/GitSync/GitConnectV2_spec.ts
> +  after(() => {
@brayn003 Can we also add cypress tests for git import flow here, not a blocker for this PR.

2023-09-11 05:31 UTC, hetunandu approved these changes

2023-09-11 05:54 UTC, merged