feat: functionality to delete multiple apps at once
appsmithorg/appsmith pull request #26750
Opened 2023-08-29 11:27 UTC by AmanAgarwal041

## Description
Delete multiple applications at once. 
- Try going to `/applications` route and by clicking on application with `cmd` or `ctrl` key pressed. 
- After clicking applications you will start seeing selected applications shake and turn into grayscale. 
- Once all the applications are selected click on delete button (All the other buttons will be hidden once any application is selected)
- Confirm to delete in the modal. All the selected applications will be deleted now.

#### PR fixes following issue(s)
Fixes #26749 

#### Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video
>
>
#### Type of change
> Please delete options that are not relevant.
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
## Testing
>
#### How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Also list any relevant details for your test configuration.
> Delete anything that is not relevant
- [ ] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-08-29 11:28 UTC, ankitakinger commented on app/client/src/ce/constants/messages.ts
> +  `Deleting multiple application...`;
```suggestion
  `Deleting multiple applications...`;
```

2023-08-29 11:33 UTC, ankitakinger commented on app/client/src/pages/Applications/ApplicationCard.tsx
> +      transform: rotate(0eg);
```suggestion
      transform: rotate(0deg);
```

2023-08-29 11:33 UTC, ankitakinger commented on app/client/src/pages/Applications/ApplicationCard.tsx
> +      transform: rotate(0eg);
```suggestion
      transform: rotate(0deg);
```

2023-08-29 11:36 UTC, AmanAgarwal041 commented
/build-deploy-preview skip-tests=true

2023-08-29 11:40 UTC, ankitakinger commented on app/client/src/ce/reducers/uiReducers/applicationsReducer.tsx
> +        const deletedApplicationIds = map(
why do we need to use the map function from lodash here?

2023-08-29 11:47 UTC, AmanAgarwal041 commented on app/client/src/ce/reducers/uiReducers/applicationsReducer.tsx
> +        const deletedApplicationIds = map(
To pluck all the application ids as an array form from array of objects. We could have done it using our own method but it looked cleaner.

2023-08-29 11:51 UTC, ankitakinger commented on app/client/src/ce/reducers/uiReducers/applicationsReducer.tsx
> +        const deletedApplicationIds = map(
I would suggest not using lodash here. If the concern is to make it look cleaner then we can create a util function in our own code and simply use that function here, which internally will use javascript's in-built map function.

2023-08-29 12:40 UTC, AmanAgarwal041 commented
/build-deploy-preview skip-tests=true

2023-08-29 13:29 UTC, AmanAgarwal041 commented
/build-deploy-preview skip-tests=true

2023-08-29 13:51 UTC, AmanAgarwal041 commented on app/client/src/ce/reducers/uiReducers/applicationsReducer.tsx
> +        const deletedApplicationIds = map(
Done

2023-08-29 14:01 UTC, ankitakinger approved these changes
LGTM

2023-08-31 08:13 UTC, AmanAgarwal041 commented
/ok-to-test sha=16d8f3c

2023-09-01 04:55 UTC, ankitakinger commented
/build-deploy-preview skip-tests=true

2023-09-04 13:16 UTC, AmanAgarwal041 commented
/ok-to-test sha=8791226

2023-09-04 18:01 UTC, AmanAgarwal041 commented
/ok-to-test sha=8791226

2023-09-05 04:43 UTC, ankitakinger approved these changes

2023-09-05 10:31 UTC, sumitsum approved these changes

2023-09-05 10:33 UTC, sumitsum requested changes
@AmanAgarwal041 can you please add a cypress test case for this ?

2023-09-11 08:54 UTC, AmanAgarwal041 commented
/ok-to-test sha=c558c59

2023-09-11 11:16 UTC, AmanAgarwal041 commented
/ok-to-test sha=1a56ce4

2023-09-11 14:05 UTC, AmanAgarwal041 commented
/ok-to-test sha=0d10d53

2023-09-11 16:55 UTC, AmanAgarwal041 commented
/ok-to-test sha=bb5c10c

2023-09-11 18:29 UTC, AmanAgarwal041 commented
/build-deploy-preview skip-tests=true

2023-09-12 03:42 UTC, sumitsum approved these changes

2023-09-12 03:42 UTC, sumitsum commented
Server side changes LGTM.

2023-09-12 12:13 UTC, prapullc commented
Enhancement 
1) Discoverability issue for the feature 
2) Clicking on escape from the keyboard should activate "Cancel" and disable the feature

2023-09-12 13:23 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ClientSide/Workspace/DeleteMultipleApplications.ts
> +    agHelper.AssertElementAbsence(homePage._multipleSelectedApplication);
What is this asserting after Delete is clicked?

2023-09-12 13:28 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ClientSide/Workspace/DeleteMultipleApplications.ts
> +    });
Also check Application is removed from UI. `Element Absence`

2023-09-12 13:28 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ClientSide/Workspace/DeleteMultipleApplications.ts
> +    agHelper.AssertElementAbsence(homePage._multipleSelectedApplication);
Also add check to see Application is still visible aft delete cancel is clicked.

2023-09-12 13:28 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ClientSide/Workspace/DeleteMultipleApplications.ts
> +describe("Delete workspace test spec", function () {
Are these tests applicable to Airgap also? Assuming its applicable for EE.

2023-09-12 13:30 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ClientSide/Workspace/DeleteMultipleApplications.ts
> +    agHelper.GetNClick(homePage._deleteMultipleAppBtn);
Can `agHelper.ClickButton` be used here with button text as parameter - instead of 2 new locators?

2023-09-12 13:33 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ClientSide/Workspace/DeleteMultipleApplications.ts
> +describe("Delete workspace test spec", function () {
Also where is 3rd pointer from PR valiidated?
`Once all the applications are selected click on delete button (All the other buttons will be hidden once any application is selected)
`

2023-09-12 13:39 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ClientSide/Workspace/DeleteMultipleApplications.ts
> +describe("Delete workspace test spec", function () {
Its Delete multiple application spec right? Describe says - Delete workspace - please update it.

2023-09-12 13:39 UTC, Aishwarya-U-R requested changes
Its Delete multiple application spec right? Describe says - Delete workspace - please update it.

2023-09-12 14:01 UTC, AmanAgarwal041 commented on app/client/cypress/e2e/Regression/ClientSide/Workspace/DeleteMultipleApplications.ts
> +    agHelper.AssertElementAbsence(homePage._multipleSelectedApplication);
If cancel is clicked then it asserts whether the application card having class `t--application-card-selected` is present on the UI or not. As `cancel` is pressed then it shouldn't be present on the UI.

2023-09-12 14:41 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ClientSide/Workspace/DeleteMultipleApplications.ts
> +    agHelper.AssertElementAbsence(homePage._multipleSelectedApplication);
Means - if applications are unselected, is it?

2023-09-12 17:29 UTC, AmanAgarwal041 commented on app/client/cypress/e2e/Regression/ClientSide/Workspace/DeleteMultipleApplications.ts
> +describe("Delete workspace test spec", function () {
Delete multiple is just a wrapper over delete single application. So it will be available for airgap instance too.

2023-09-12 17:30 UTC, AmanAgarwal041 commented on app/client/cypress/e2e/Regression/ClientSide/Workspace/DeleteMultipleApplications.ts
> +    agHelper.GetNClick(locators._confirmationdialogbtn("Yes"));
Done

2023-09-12 17:30 UTC, AmanAgarwal041 commented on app/client/cypress/e2e/Regression/ClientSide/Workspace/DeleteMultipleApplications.ts
> +    agHelper.GetNClick(homePage._deleteMultipleAppBtn);
Done

2023-09-12 17:30 UTC, AmanAgarwal041 commented on app/client/cypress/e2e/Regression/ClientSide/Workspace/DeleteMultipleApplications.ts
> +    });
Done

2023-09-12 17:31 UTC, AmanAgarwal041 commented
/ok-to-test sha=85b0782

2023-09-13 06:54 UTC, AmanAgarwal041 commented on app/client/cypress/e2e/Regression/ClientSide/Workspace/DeleteMultipleApplications.ts
> +    agHelper.AssertElementAbsence(homePage._multipleSelectedApplication);
Yes

2023-09-13 07:08 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ClientSide/Workspace/DeleteMultipleApplications.ts
> +describe("Delete workspace test spec", function () {
Got it.

2023-09-13 07:10 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ClientSide/Workspace/DeleteMultipleApplications.ts
> +  it("2. Once the application is selected for multiple deletion, all the other buttons will be hidden once any application is selected)", function () {
Can test 1 & 2 be combined - with all validations done once for `Cancel` click?

2023-09-13 07:12 UTC, Aishwarya-U-R commented on app/client/cypress/support/Pages/HomePage.ts
> +  private _applicationEditedText = (applicationName: string) =>
Try adding new locators at end to avoid merge conflicts with EE sync.

2023-09-13 07:57 UTC, AmanAgarwal041 commented on app/client/cypress/support/Pages/HomePage.ts
> +  private _applicationEditedText = (applicationName: string) =>
Done

2023-09-13 07:58 UTC, Aishwarya-U-R reviewed
Approving Cypress changes.

2023-09-13 07:59 UTC, AmanAgarwal041 commented
/ok-to-test sha=ff168c3

2023-09-13 10:04 UTC, sumitsum approved these changes

2023-09-13 10:09 UTC, merged