chore: add TextInput component and InputWidgetV3
appsmithorg/appsmith pull request #26775
Opened 2023-08-30 07:57 UTC by jsartisan

Fixes #26039

2023-09-04 18:07 UTC, KelvinOm reviewed
Huge PR, thank you Pawan. 👍

2023-09-05 08:17 UTC, ichik commented on app/client/packages/design-system/widgets/src/components/TextArea/src/TextArea.stories.mdx
> +<Meta
Indeed.
Placeholder (and user input) should be aligned to the container start vertically. The resizing element should be in the bottom right corner.

2023-09-07 11:28 UTC, jsartisan commented on app/client/packages/design-system/headless/src/components/TextInput/src/TextArea.tsx
> +type MyOmit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>;
Hey sorry, this is for only debugging purposes. Removed it.

FYI. There is an issue with the Omit utility that it doesn't show autocomplete when you pass keys, nor does it complain if the key does not exists in the type.

2023-09-07 11:29 UTC, jsartisan commented on app/client/packages/design-system/headless/src/components/TextInput/src/TextArea.tsx
> +  // not in stately because this is so we know when to re-measure, which is a spectrum design
I just copied the textarea component from spectrum. Let me know if we should remove it.

2023-09-07 11:30 UTC, jsartisan commented on app/client/packages/design-system/widgets/src/components/TextArea/src/TextArea.tsx
> +// type MyOmit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>;
Not needed. Was just for debugging purposes. removed it.

2023-09-08 05:49 UTC, jsartisan commented on app/client/packages/design-system/headless/src/components/TextInput/src/TextInputBase.tsx
> +        ref={inputRef as any}
Not really sure. I tried to solve it but gave up at last. Also, the spectrum also does the same. They are also using any here.

2023-09-08 06:02 UTC, jsartisan commented on app/client/packages/design-system/widgets/src/components/Text/src/index.styled.tsx
> +  width: auto;
Yea. I also felt deja vu for this :P . here is the reason why width: auto is apt :

1. Using 100% pushes everything to the edges.
<img width="1226" alt="CleanShot 2023-09-08 at 11 30 54@2x" src="https://github.com/appsmithorg/appsmith/assets/6636360/5b6b5204-c76c-42f1-8ead-450aa3185625">

2. But when we use width auto, it makes sure the element takes the width it requires.
<img width="1226" alt="CleanShot 2023-09-08 at 11 29 23@2x" src="https://github.com/appsmithorg/appsmith/assets/6636360/a071001f-4568-4167-abc5-e886e412fb23">

2023-09-08 06:04 UTC, jsartisan commented on app/client/packages/design-system/widgets/src/styles/src/textInputStyles.ts
> +    &:-webkit-autofill,
My bad. I took some code from StackOverflow :P and didn't realize it was old.

2023-09-11 07:26 UTC, dhruvikn commented on app/client/src/widgets/BaseInputWidgetV2/widget/index.tsx
> +      // here. But the main part is the action execution payload.
nitpick - can we use multiline comment here instead?

2023-09-11 07:27 UTC, dhruvikn commented on app/client/src/widgets/InputWidgetV3/component/index.tsx
> +      return "off";
nit - can we wrap this return around braces?

2023-09-11 07:36 UTC, dhruvikn commented on app/client/src/widgets/InputWidgetV3/widget/derived.js
> +  //
let's remove this

2023-09-12 04:40 UTC, jsartisan commented on app/client/packages/design-system/headless/src/components/Field/src/HelpText.tsx
> +function HelpText(props: HelpTextProps, ref: DOMRef<HTMLDivElement>) {
✅

2023-09-12 04:40 UTC, jsartisan commented on app/client/packages/design-system/headless/src/components/Field/src/HelpText.tsx
> +const _HelpText = React.forwardRef(HelpText);
✅

2023-09-12 04:41 UTC, jsartisan commented on app/client/packages/design-system/widgets/src/components/Spinner/src/index.styled.tsx
>    height: 1.2rem;
✅

2023-09-12 04:55 UTC, jsartisan commented on app/client/src/widgets/BaseInputWidgetV2/component/types.ts
> +  defaultValue?: string | number;
These are supported. One difference for `onValueChange`, its called `onChange` on our component. Added examples in our stories too for these.

2023-09-12 04:57 UTC, jsartisan commented on app/client/src/widgets/BaseInputWidgetV2/widget/contentConfig.ts
> +          //should be shown for only inputWidgetV2 and for email or password input types
Removed it from baseinput as it is only required in the input widget.

2023-09-12 05:00 UTC, jsartisan commented on app/client/src/widgets/BaseInputWidgetV2/widget/index.tsx
> +export default BaseInputWidget;
Done.

2023-09-12 05:01 UTC, jsartisan commented on app/client/src/widgets/BaseInputWidgetV2/widget/index.tsx
> +    //
Not really. The function is defined as a abstract in base class.

2023-09-12 05:02 UTC, jsartisan commented on app/client/src/widgets/BaseInputWidgetV2/widget/types.ts
> +  tooltip?: string;
This was a miss on my end. Added it. One thing to note is it is called as contextualHelp in our component.

2023-09-12 05:02 UTC, jsartisan commented on app/client/src/widgets/InputWidgetV3/widget/helper.ts
> +  // console.log({ empty: isEmpty(value) });
Removed.

2023-09-12 05:03 UTC, jsartisan commented on app/client/src/widgets/InputWidgetV3/widget/index.tsx
> +        maxChars={this.props.maxChars}
These props are supported but are not visible in autolayout. Not sure why autolayout team hide them for autplayout mode. Will check with aswath but this is not a miss from our side.

2023-09-12 05:04 UTC, jsartisan commented on app/client/packages/design-system/widgets/src/components/TextArea/src/TextArea.stories.mdx
> +<Meta
Fixed.

2023-09-12 05:04 UTC, jsartisan commented on app/client/src/widgets/InputWidgetV3/widget/derived.js
> +  //
We can't. This is expected for derived properties to work.

2023-09-12 05:04 UTC, jsartisan commented on app/client/src/widgets/InputWidgetV3/component/index.tsx
> +      return "off";
Done.

2023-09-12 05:06 UTC, jsartisan commented on app/client/src/widgets/BaseInputWidgetV2/widget/index.tsx
> +      // here. But the main part is the action execution payload.
multiLine is expected to be used above functions. Since this is an inside function, this way is preferred.

2023-09-13 14:59 UTC, KelvinOm requested changes

2023-09-13 14:59 UTC, KelvinOm commented on app/client/packages/design-system/widgets/src/components/IconButton/src/IconButton.tsx
> +  "className" | "iconPosition" | "icon"
`className` can be useful

2023-09-13 14:59 UTC, KelvinOm commented on app/client/packages/design-system/widgets/src/components/TextArea/stories/TextArea.stories.mdx
> +    type: "email",
Why `email`?

2023-09-13 14:59 UTC, KelvinOm commented on app/client/packages/design-system/widgets/src/components/TextInput/stories/TextInput.stories.mdx
> +Switch is a component that allows the user to select one or more options from a set.
incorrect description

2023-09-13 14:59 UTC, KelvinOm commented on app/client/packages/design-system/widgets/src/styles/src/fieldStyles.ts
> +  & [data-field-contextual-help] button {
Let's encapsulate all these styles in a `IconButton`. This way, we will have two sizes(for now), a `small` one and a `large` one. The large size will be the default, the small one will be used together with the label. The way it is implemented now cannot be reused.

It also seems like the time has come to discuss naming for sizes. Will it be t-shirt sizes(s, m, l)? сс @ichik 

For a IconButton, I would expect to see such an interface.
```
        <IconButton icon={<EmotionHappyLineIcon />} size="m" color="neutral" onPress={onPressEyeIcon} variant="ghost" />
```

2023-09-13 14:59 UTC, KelvinOm commented on app/client/src/widgets/BaseInputWidgetV2/component/types.ts
> +  defaultValue?: string | number;
Can we make API the same for widget and for component?

2023-09-13 14:59 UTC, KelvinOm commented on app/client/src/widgets/InputWidgetV3/widget/derived.js
> +  //
Just wondering how it works?

2023-09-13 14:59 UTC, KelvinOm commented on app/client/src/widgets/InputWidgetV3/widget/index.tsx
> +        maxChars={this.props.maxChars}
But I don't see how we handled for example `maxNum` and `minNum` props it in our component. How does it work?

2023-09-13 14:59 UTC, KelvinOm commented on app/client/packages/design-system/widgets/src/styles/src/fieldStyles.ts
> +  & [data-field-contextual-help] {
let's remove this `data-field-contextual-help` wrapper from `Field.tsx`

2023-09-13 15:44 UTC, ichik commented on app/client/packages/design-system/widgets/src/styles/src/fieldStyles.ts
> +  & [data-field-contextual-help] button {
I wouldn't add individual sizing controls to any widgets, just the top-level theme sizing and spacing.

2023-09-14 06:05 UTC, jsartisan commented on app/client/packages/design-system/headless/src/components/Field/src/HelpText.tsx
> +import React, { forwardRef } from "react";
I was just wondering, why do we need stories for those components? They are not meant to be used individually. 🤔

Created the issue anyway - https://github.com/appsmithorg/appsmith/issues/27292

2023-09-14 06:07 UTC, jsartisan commented on app/client/packages/design-system/headless/src/components/TextInput/src/TextInputBase.tsx
> +function TextInputBase(props: TextInputBaseProps, ref: Ref<HTMLDivElement>) {
I actually created a separate folder for TextArea, but not for TextInputBase.

2023-09-14 06:09 UTC, jsartisan commented on app/client/packages/design-system/headless/src/components/TextInput/src/types.ts
> +  className?: string;
The structure of the component is like this 
<img width="806" alt="CleanShot 2023-09-14 at 11 38 47@2x" src="https://github.com/appsmithorg/appsmith/assets/6636360/fd0a74e0-ac15-4e5d-b35a-dccff4b16655">


The inputClassName applies the class to input

2023-09-14 06:17 UTC, jsartisan commented on app/client/packages/design-system/headless/src/components/TextInput/src/types.ts
> +  inputRef?: RefObject<HTMLInputElement | HTMLTextAreaElement>;
There are two refs, one for the wrapper and one for the input.

2023-09-14 06:49 UTC, jsartisan commented on app/client/src/widgets/InputWidgetV3/widget/index.tsx
> +        maxChars={this.props.maxChars}
we send `maxLength/max/min` to our component. Check `[app/client/src/widgets/InputWidgetV3/component/index.tsx`

2023-09-14 06:49 UTC, jsartisan commented on app/client/packages/design-system/headless/src/components/TextArea/src/TextArea.tsx
> +  }, [onHeightChange, inputValue, inputRef]);
✅

2023-09-14 06:50 UTC, jsartisan commented on app/client/packages/design-system/headless/src/components/TextArea/src/TextArea.tsx
> +function TextArea(props: TextAreaProps, ref: TextAreaRef) {
History as in? 🤔

2023-09-14 06:51 UTC, jsartisan commented on app/client/packages/design-system/headless/src/components/TextInput/stories/TextInput.stories.mdx
> +Switch is a component that allows the user to select one or more options from a set.
Copy-paste without using the mind. Sorry.. Won't happen again. Fixed

2023-09-14 07:05 UTC, jsartisan commented on app/client/packages/design-system/widgets/src/components/IconButton/src/IconButton.tsx
> +  "className" | "iconPosition" | "icon"
Fixed.

2023-09-14 07:06 UTC, jsartisan commented on app/client/packages/design-system/widgets/src/components/TextArea/stories/TextArea.stories.mdx
> +    type: "email",
Sorry. I was testing something. Removed.

2023-09-14 07:07 UTC, jsartisan commented on app/client/packages/design-system/widgets/src/components/TextInput/src/TextInput.tsx
> +      inputClassName="wds-body-text"
Thanks for this. I also felt i am doing something wrong with this.

2023-09-14 07:07 UTC, jsartisan commented on app/client/packages/design-system/widgets/src/components/Tooltip/src/Tooltip.tsx
> +    <TooltipRoot {...rest}>
So we can pass additional props like placement to the tooltip.

2023-09-14 07:08 UTC, KelvinOm commented on app/client/packages/design-system/widgets/src/styles/src/fieldStyles.ts
> +  & [data-field-contextual-help] button {
@ichik But we need it because we already have two sizes of IconButtons.
<img width="237" alt="Снимок экрана 2023-09-14 в 10 02 24" src="https://github.com/appsmithorg/appsmith/assets/11555074/89351896-34d2-46f2-a126-b7c621b0ed57">
<img width="97" alt="Снимок экрана 2023-09-14 в 10 06 03" src="https://github.com/appsmithorg/appsmith/assets/11555074/944d7c33-bf91-4d13-943f-2fb279d43469">

2023-09-14 07:09 UTC, jsartisan commented on app/client/src/widgets/InputWidgetV3/widget/derived.js
> +  //
This actually feels like a tech debt. @riodeuno can explain better why we need a `//` in derived.js files to separate functions.

2023-09-14 07:13 UTC, KelvinOm commented on app/client/src/widgets/InputWidgetV3/widget/index.tsx
> +        maxChars={this.props.maxChars}
Yeah, got it. It will be necessary to think about how to make the types more readable. Mb flat them?

2023-09-14 07:17 UTC, KelvinOm commented on app/client/packages/design-system/headless/src/components/Field/src/HelpText.tsx
> +import React, { forwardRef } from "react";
As documentation for internal use. I think it will be useful.

2023-09-14 07:20 UTC, KelvinOm commented on app/client/packages/design-system/headless/src/components/TextInput/src/TextInputBase.tsx
> +function TextInputBase(props: TextInputBaseProps, ref: Ref<HTMLDivElement>) {
Yes, I see. I think that's right. If you separate `TextInputBase` component, the code will be a bit clearer since you also split the interfaces, now the imports look a little strange.

2023-09-14 07:23 UTC, KelvinOm commented on app/client/packages/design-system/headless/src/components/TextInput/src/types.ts
> +  className?: string;
Then I think it should be like this `inputClassName`  and `wrapperClassName`. Same for refs naming and also it worth to write more clear comments for these props.

2023-09-14 07:36 UTC, riodeuno commented on app/client/src/widgets/InputWidgetV3/widget/derived.js
> +  //
Yes, this is a tech debt. It was added as a hack to be able to use regex and pass the stringified functions individually to `getDerivedProperties`. 

Before this, all functions in `getDerivedProperties` used to be written as a string. This was not easily unit-testable, and lead to extremely frequent errors.
As a part of another feature (2.5 years ago - Table Widget V1 bug bash), I wanted to be able to unit test these functions (as they were complex). In the interest of time, I created a new file called `derived.js` that would hold these functions in JS. I would write unit tests for these functions. 
A new parser in `parseDervied.js` would accept the `derived.js` file as a string, tokenize it using the `//`. This would then be assigned to the appropriate `getDerivedProperties` keys.

I admit that this is not the cleanest solution, but this is the rationale behind including the `//`. A side effect of this is that we must avoid inline comments in the functions in `derived.js`

2023-09-15 06:15 UTC, jsartisan commented on app/client/packages/design-system/widgets/src/styles/src/fieldStyles.ts
> +  & [data-field-contextual-help] {
Done.

2023-09-15 06:59 UTC, jsartisan commented on app/client/packages/design-system/headless/src/components/TextInput/src/types.ts
> +  className?: string;
Hey, I tried this but this is breaking how styling components apply styles. The thing is styled component uses className only to apply styles.

2023-09-18 05:43 UTC, jsartisan commented
/build-deploy-preview env=release

2023-09-18 06:55 UTC, jsartisan commented
/build-deploy-preview env=release

2023-09-18 13:41 UTC, KelvinOm commented on app/client/packages/design-system/headless/src/components/TextArea/src/TextArea.tsx
> +function TextArea(props: TextAreaProps, ref: TextAreaRef) {
I mean story :slightly_smiling_face:

2023-09-18 15:00 UTC, KelvinOm commented on app/client/packages/design-system/widgets/src/components/TextInput/src/TextInput.tsx
> +          <Icon size={ICON_SIZE} />
Why do we still use ICON_SIZE constant if we have a size prop in the IconButton?

2023-09-18 15:00 UTC, KelvinOm commented on app/client/src/widgets/BaseInputWidgetV2/component/types.ts
> +  defaultValue?: string | number;
@jsartisan WDYT?

2023-09-18 15:39 UTC, KelvinOm commented on app/client/packages/design-system/widgets/src/components/TextInput/src/Label.tsx
> +      *
@jsartisan Add `fg-negative` for `*` please. Agreed with Vadim.

2023-09-19 07:35 UTC, jsartisan commented on app/client/packages/design-system/widgets/src/components/Button/src/styles.module.css
> +    & svg {
used  `[data-icon]` for this. Since we are using IconButton, i could target it with just `[data-icon`

2023-09-19 07:35 UTC, jsartisan commented on app/client/packages/design-system/widgets/src/components/Button/src/styles.module.css
> +      width: 90cqw;
Fixed.

2023-09-19 07:35 UTC, jsartisan commented on app/client/packages/design-system/widgets/src/components/IconButton/src/IconButton.tsx
> +  const { children, size, ...rest } = props;
Done

2023-09-19 11:44 UTC, jsartisan commented
/ok-to-test

2023-09-20 05:46 UTC, jsartisan commented
/build-deploy-preview env=release



</details>

2023-09-20 06:56 UTC, merged