chore: url changes of mocking flagsmith
appsmithorg/appsmith pull request #26804
Opened 2023-08-30 14:46 UTC by sondermanish

## Description
> Add a TL;DR when description is extra long (helps content team)
>
> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change
>
> Links to Notion, Figma or any other documents that might be relevant to the PR
>
>
#### PR fixes following issue(s)
Fixes # (issue number)
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
#### Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video
>
>
#### Type of change
> Please delete options that are not relevant.
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
## Testing
>
#### How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Also list any relevant details for your test configuration.
> Delete anything that is not relevant
- [ ] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-08-30 15:24 UTC, abhvsn requested changes
Added minor comment

2023-08-30 15:24 UTC, abhvsn commented on .github/workflows/ci-test.yml
> +          ]
Can we revert if not intentional? Is this happening because of the pre commit hook for formatting?

2023-08-30 15:24 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/ce/CloudServicesConfigCE.java
> +    }
We ideally want to copy the changes from EE to CE in this case and code splitting should not be required.

2023-08-30 17:12 UTC, sondermanish commented on .github/workflows/ci-test.yml
> +          ]
reverting

2023-08-30 17:50 UTC, abhvsn submitted a review, later dismissed

2023-08-31 09:39 UTC, abhvsn commented on .github/workflows/ci-test.yml
> +            -e FLAGSMITH_URL=http://host.docker.internal:5001/flagsmith \
@manish535  I think we also have to add `FLAGSMITH_SERVER_KEY_BUSINESS_FEATURES` and `FLAGSMITH_SERVER_KEY`. Sorry for the late noticing this 😣

2023-08-31 10:10 UTC, sondermanish commented on .github/workflows/ci-test.yml
> +            -e FLAGSMITH_URL=http://host.docker.internal:5001/flagsmith \
Thanks for noticing this, made changes accordingly

2023-08-31 12:00 UTC, abhvsn submitted a review, later dismissed

2023-09-01 05:47 UTC, yatinappsmith requested changes
Please apply these changes to      ./.github/workflows/ci-test-custom-script.yml

2023-09-01 06:23 UTC, sondermanish commented
/ok-to-test

2023-09-04 13:07 UTC, merged