Avoid double evals
appsmithorg/appsmith pull request #2687
Opened 2021-01-22 12:44 UTC by ofpiyush

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.

## Description
> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation 
> and context. List any dependencies that are required for this change.

Fixes # (issue)
> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce. 
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-01-26 03:32 UTC, hetunandu requested changes

2021-01-26 03:32 UTC, hetunandu commented on app/client/src/workers/evaluation.worker.ts
> +    // );
Remove if not needed

2021-01-26 03:32 UTC, hetunandu commented on app/client/src/workers/evaluation.worker.ts
> +    const rgx = /^(.*)(\..*|\[.*\])$/;
Need some more documentation for `rgx`

2021-01-26 03:32 UTC, hetunandu commented on app/client/src/workers/evaluationUtils.ts
> +  );
We have a function to find children to a path.

2021-01-26 16:37 UTC, ofpiyush commented
@trishaanand the "make an api after it has been bound" case was getting hidden because we'd switch pages and it would work. Jest test caught it.

I've added `sortedDependencies` back for now.

Now we're looking at both:
- Dynamically bound properties from `sortedDependencies`.
- Static properties of the widget from `widgetValidationPaths`

2021-01-27 07:00 UTC, ofpiyush commented on app/client/src/workers/evaluation.worker.ts
> +          ["config", "isLoading", "data"].map((e) => `${entity.name}.${e}`),
@hetunandu can you suggest a good place to add this?

2021-01-27 07:34 UTC, trishaanand commented on app/client/src/utils/DynamicBindingUtils.ts
> +  childPropertyPath.startsWith(`${parentPropertyPath}.`) ||
I think we used to do what you have done here but had to replace with regex because it was not handling all the scenarios. We seem to be reverting back to the erroneous check. Could you please check?

2021-01-27 07:34 UTC, trishaanand commented on app/client/src/workers/evaluation.worker.ts
> +      if (!Array.isArray(d.path) || d.path.length === 0) continue;
Could you add a comment about the scenario that this line is handling?

2021-01-27 07:47 UTC, ofpiyush commented on app/client/src/utils/DynamicBindingUtils.ts
> +  childPropertyPath.startsWith(`${parentPropertyPath}.`) ||
Current behaviour
```
fn("Input1.text", "Input1.text") // true
fn("Table1.selectedRow", "Table1.selectedRow.email") // true
fn("Table1.selectedRow", "Table1.selectedRows") // false
fn("Dropdown1.options", "Dropdown1.options[1].value") // true
```
The regex did not handle the last case and there was a duplicate function that did most of the work, so I've merged the functions.

We can abstract out and use the regex we use to extract immediate parents from evaluationUtils, but that is unnecessary + error prone without proper escaping.

2021-01-27 08:38 UTC, hetunandu commented on app/client/src/utils/DynamicBindingUtils.ts
> +  childPropertyPath.startsWith(`${parentPropertyPath}.`) ||
Can we add this scenario in the test case of this function as well?

2021-01-27 08:48 UTC, hetunandu commented on app/client/src/workers/evaluation.test.ts
> -      Input1: ["Input1.text"],
How was this dependency removed?

2021-01-27 08:48 UTC, hetunandu commented on app/client/src/workers/evaluation.worker.ts
> +          ["config", "isLoading", "data"].map((e) => `${entity.name}.${e}`),
Why are action fields added for validation?

2021-01-27 08:48 UTC, hetunandu commented on app/client/src/workers/evaluation.worker.ts
> +        result[entity.widgetName] = new Set(
Since these are widget property paths, they will always be unique. Why use a set here?

2021-01-27 08:48 UTC, hetunandu commented on app/client/src/workers/evaluation.worker.ts
> +        }
Handle this in the DELETE case only

2021-01-27 08:51 UTC, ofpiyush commented on app/client/src/workers/evaluation.worker.ts
> +          ["config", "isLoading", "data"].map((e) => `${entity.name}.${e}`),
We've stopped looking at `sortedDependencies`, so a new Action created will not trigger an eval of anything bound to it.

2021-01-27 09:30 UTC, ofpiyush commented on app/client/src/workers/evaluation.test.ts
> -      Input1: ["Input1.text"],
This was a bad test case from the previous test case. This should have gotten deleted because the unevalTree no longer has this widget

2021-01-27 09:32 UTC, ofpiyush commented on app/client/src/workers/evaluation.worker.ts
> +        result[entity.widgetName] = new Set(
I think we'd added sets earlier because we needed a lookup. Right now we don't so we can use both arrays or sets.


if we eventually need lookup somewhere again, we'll have sets ready!

2021-01-27 09:34 UTC, ofpiyush commented on app/client/src/workers/evaluation.worker.ts
> +        }
that case wont get triggered if I don't change this (or change the check around switch case)

2021-01-27 09:36 UTC, ofpiyush commented on app/client/src/workers/evaluation.worker.ts
> +        }
The choices are one of:
* Do this here.
* Lookup `entity` and `entityType` from within the `case` in switch case.

2021-01-28 06:15 UTC, trishaanand commented on app/client/src/workers/evaluation.worker.ts
> +          ["config", "isLoading", "data"].map((e) => `${entity.name}.${e}`),
Adding to what @ofpiyush said, this is also done keeping in mind that tomorrow in the api and query panes, we would show the evaluated values. To achieve the same, we need to ensure that the config can be evaluated and set by simply also evaluating action fields (Today, it only evaluates and validates the widgets, which can be extrapolated to include actions). Also, when we make all the entities reactive, we wouldnt again have to make changes to this part of the code flow because action fields would get accounted in the complete sort order.

2021-01-28 06:19 UTC, trishaanand commented on app/client/src/workers/evaluation.worker.ts
> +        }
I would vote for this solution itself. The reason being that we would have to repeat the entity and entityType setting across all switch cases to ensure that we dont go into NOOP flow.

2021-01-29 06:02 UTC, hetunandu approved these changes

2021-01-29 06:04 UTC, merged