chore: Rename and cleanup of editor components
appsmithorg/appsmith pull request #26944
Opened 2023-09-04 16:52 UTC by rahulramesha

## Description
This PR is aimed at Renaming and cleanup of editor components. The changes include,
- Rename Editor components to reflect more of it's function as an editor component
- Rename all references of the container to wrapper so as to avoid confusion with Actual containers and canvases
- Pass down few instances of selected properties to children instead of reselecting the same in the children
- Remove all instances of `isAutolayout`, instead use `useLayoutSystemFeatures` to check if the particular feature is enabled in the particular layout type.

P.S. please feel free to suggest better names that define the function of the components.

#### PR fixes following issue(s)
Fixes #26571

#### Type of change
- Chore (housekeeping or task changes that don't impact user perception)

#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-09-04 16:53 UTC, rahulramesha commented
/build-deploy-preview skip-tests=true

2023-09-04 16:53 UTC, rahulramesha commented
/ok-to-test

2023-09-05 09:44 UTC, marks0351 requested changes

2023-09-05 09:44 UTC, marks0351 commented on app/client/src/pages/Editor/CanvasPropertyPane/index.tsx
> +    layoutSystemFeatures.ENABLE_LAYOUT_CONTROL,
can we rename it to ENABLE_CANVAS_LAYOUT_CONTROL

2023-09-05 09:44 UTC, marks0351 commented on app/client/src/pages/Editor/index.tsx
> +            <EditorWrapper />
I think we should make this component EditorWrapper and MainContainer to CanvasEditor or Editor. what do you think?

2023-09-05 09:44 UTC, marks0351 commented on app/client/src/pages/Editor/useLayoutSystemFeatures.ts
> +  [layoutSystemFeatures.ENABLE_FORKING_FROM_TEMPLATES]: true,
why cant we just use an array? why the object?

2023-09-05 10:43 UTC, rahulramesha commented on app/client/src/pages/Editor/index.tsx
> +            <EditorWrapper />
For `CanvasEditor`, wanted to not have any references of canvas/container for just wrappers... also since it would contain entityexplorer side bar, property pane etc..
For `Editor`, there is already a component by that name :)

2023-09-05 10:43 UTC, rahulramesha commented on app/client/src/pages/Editor/useLayoutSystemFeatures.ts
> +  [layoutSystemFeatures.ENABLE_FORKING_FROM_TEMPLATES]: true,
This is so that it is easy to check the features instead of looping through the list to check if each feature exists...

2023-09-05 10:55 UTC, rahulramesha commented
/build-deploy-preview skip-tests=true

2023-09-05 10:58 UTC, marks0351 requested changes

2023-09-05 10:58 UTC, marks0351 commented on app/client/src/pages/Editor/index.tsx
> +            <EditorWrapper />
I believe the `Editor` that ur r mentioning is the parent and `EditorWrapper` is the child in this current implementation.
My suggestion was to replace them for each other.

2023-09-06 22:06 UTC, prsidhu commented on app/client/src/widgets/mainCanvasResizer.tsx
File name change request: mainCanvasResizer could be MainCanvasResizer.

2023-09-06 22:14 UTC, prsidhu commented
@rahulramesha All the component and file name changes will confuse developers in the near future. Should we add comments of the following structure in each file / component where the changes have been introduced?

```
/**
 * Old name: MainContainer
 * New name: MainCanvas
 * /
```

This will ensure that if someone tries to search for the old name they would quickly end up in the right place. What do you think?

2023-09-08 11:42 UTC, riodeuno requested changes
I really appreciate the attempt to restructure and organize the nomenclature!

2023-09-08 11:42 UTC, riodeuno commented on app/client/src/pages/Editor/CanvasPropertyPane/index.tsx
> +              <MainCanvasLayoutControl />
Is the canvas width toggle that appears in the property pane of the MainContainer?
If so, shall we call it "canvas width toggles", "canvas viewport toggles", or something on these lines instead?

Please ignore this comment if I'm misunderstanding the intent of this component.

2023-09-08 11:42 UTC, riodeuno commented on app/client/src/pages/Editor/CanvasPropertyPane/index.tsx
> +              <MainCanvasLayoutControl />
Also the text "Canvas Size" should come from messages.to

2023-09-08 11:42 UTC, riodeuno commented on app/client/src/pages/Editor/WidgetsEditor/EmptyCanvasPrompts.tsx
> +function EmptyCanvasPrompts(props: EmptyCanvasPromptsProps) {
Please add a jsdoc describing what this component's responsibilities are.

2023-09-08 11:42 UTC, riodeuno commented on app/client/src/pages/Editor/WidgetsEditor/MainCanvasWrapper.tsx
> +function MainCanvasWrapper(props: MainCanvasWrapperProps) {
Please add a comment describing the responsibilities of this component.

2023-09-08 11:42 UTC, riodeuno commented on app/client/src/pages/Editor/WidgetsEditor/MainCanvasWrapper.tsx
> +import { MainCanvasResizer } from "widgets/mainCanvasResizer";
Shall we take this opportunity to standardize the nomenclature? 
Instead of calling it Main Canvas Resizer, shall we call it Main Container resizer?

If folks are more used to Main Canvas as the term for this, shall we rename what we call the "MainContainer" in the DSL?

2023-09-08 11:42 UTC, riodeuno commented on app/client/src/pages/Editor/WidgetsEditorWrapper.tsx
> +function WidgetsEditorWrapper() {
Since we're trying to standardize naming, shall we investigate whether calling anything "WidgetsEditor" as opposed to simply "Editor" make sense?

2023-09-08 11:42 UTC, riodeuno commented on app/client/src/pages/Editor/useLayoutSystemFeatures.ts
> +//This file will be eventually moved to layoutSystems folder once the base widget separation PR is merged
The Base Widget restructure PR is available. Can we create a path in which we expect to put this file, and put this file in there in this PR? That way we shouldn't be expecting any merge conflicts as well.

2023-09-08 11:42 UTC, riodeuno commented on app/client/src/pages/Editor/useLayoutSystemFeatures.ts
> +export const layoutSystemFeatures = {
Why did we choose constant object over enum?

2023-09-08 11:42 UTC, riodeuno commented on app/client/src/pages/Editor/useLayoutSystemFeatures.ts
> +const FIXED_LAYOUT_FEATURES = {
Let's type this correctly. The keys are not strings but type of entries of `layoutSystemFeatures`

2023-09-08 11:42 UTC, riodeuno commented on app/client/src/pages/Editor/useLayoutSystemFeatures.ts
> +    [x: string]: boolean;
`Record<layoutSystemFeatures, Boolean>`

2023-09-08 11:42 UTC, riodeuno commented on app/client/src/pages/Editor/useLayoutSystemFeatures.ts
> +  return (checkFeaturesArray: string[]) => {
`layoutSystemFeatures[]`

2023-09-08 11:42 UTC, riodeuno commented on app/client/src/pages/Editor/useLayoutSystemFeatures.ts
> +  return (checkFeaturesArray: string[]) => {
`layoutSystemFeatures[]`

2023-09-08 11:42 UTC, riodeuno commented on app/client/src/pages/Editor/useLayoutSystemFeatures.ts
> +      featuresArray.push(!!currentFeatureSet[checkFeature]);
Is this the same as `currentFeatureSet[checkFeature] === true`?

2023-09-08 11:42 UTC, riodeuno commented on app/client/src/pages/Editor/useLayoutSystemFeatures.ts
> +export const useLayoutSystemFeatures = () => {
Please add a comment to describe the responsibilities and outputs of this hook

2023-09-08 11:42 UTC, riodeuno commented on app/client/src/pages/Editor/useLayoutSystemFeatures.ts
> +  return (checkFeaturesArray: string[]) => {
`features` should be good enough for the argument name, if we make this a named function with appropriate details in comments.

2023-09-08 11:42 UTC, riodeuno commented on app/client/src/pages/Editor/useLayoutSystemFeatures.ts
> +import { useSelector } from "react-redux";
I like the intent behind this hook, where we're trying to abstract responsibilities to a central location.

2023-09-11 10:45 UTC, rahulramesha commented on app/client/src/pages/Editor/WidgetsEditorWrapper.tsx
> +function WidgetsEditorWrapper() {
Since we already have a component `Editor` in `Editor/index`. Since that is a folder that contains lots of components, changing that might cause lot of confusion...

2023-09-11 10:58 UTC, rahulramesha commented
/build-deploy-preview skip-tests=true

2023-09-11 11:14 UTC, rahulramesha commented
/ok-to-test

2023-09-11 16:35 UTC, rahulramesha commented
/build-deploy-preview skip-tests=true

2023-09-11 16:35 UTC, rahulramesha commented
/ok-to-test

2023-09-11 16:41 UTC, rahulramesha commented
/ok-to-test

2023-09-12 11:41 UTC, kamakshibhat-appsmith commented
sanity done, Looks good @rahulramesha

2023-09-12 11:58 UTC, rahulramesha commented
/ok-to-test

2023-09-12 11:59 UTC, rahulramesha commented on app/client/src/pages/Editor/CanvasPropertyPane/index.tsx
> +              <MainCanvasLayoutControl />
This seems to be happening in few other files as well, better to take them all up at once in a separate PR

2023-09-12 11:59 UTC, rahulramesha commented
@riodeuno @marks0351 @prsidhu could you please provide your final review for the PR.

2023-09-12 12:02 UTC, riodeuno approved these changes

2023-09-12 12:08 UTC, marks0351 approved these changes
Looks good. pls make sure these changes are captured on the system design doc.

2023-09-12 14:14 UTC, merged