fix: fix ds required fields
appsmithorg/appsmith pull request #26940
Opened 2023-09-04 13:00 UTC by Irongade

When user toggles between different datasource configuration options in S3, the required fields was not being updated which prevents the user from saving the datasource. This also solves this problem for all possible datasources that have different configuration options.

Fixes #26126 
> if no issue exists, please create an issue and ask the maintainers about this first

- Bug fix (non-breaking change which fixes an issue)

>
>
>
## Testing
>
#### How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Also list any relevant details for your test configuration.
> Delete anything that is not relevant
- [ ] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-09-04 13:01 UTC, Irongade commented
/ok-to-test

2023-09-06 14:46 UTC, Aishwarya-U-R commented on app/client/cypress/e2e/Regression/ClientSide/BugTests/Bug26126_spec.ts
> +  it("ensures save button is correctly updated when DS required fields change", function () {
Add Bug id to title.

2023-09-07 05:30 UTC, Aishwarya-U-R reviewed
Approving Cypress changes,

2023-09-07 10:06 UTC, Irongade commented
/ok-to-test

2023-09-07 10:28 UTC, sneha122 submitted a review, later dismissed

2023-09-08 05:20 UTC, ayushpahwa requested changes

2023-09-08 05:20 UTC, ayushpahwa commented on app/client/src/pages/Editor/DataSourceEditor/index.tsx
> +  currentEnvironment: string;
Is the requirement here to fetch the current environment of the app or the current editing environment. If viewmode is true, then it should be current environment, if not, then it should be current editing environment which in this case can be used from state.filterparams.id

2023-09-08 05:20 UTC, ayushpahwa commented on app/client/src/pages/Editor/DataSourceEditor/index.tsx
> +    // console.log("hereee", prevProps, this.props);
Please remove this

2023-09-08 08:28 UTC, Irongade commented
/ok-to-test

2023-09-11 03:57 UTC, ayushpahwa approved these changes

2023-09-11 09:54 UTC, merged