Chore: Remove position props from list widget
appsmithorg/appsmith pull request #27018
Opened 2023-09-06 07:02 UTC by aswathkk

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.
>
## Description
> Add a TL;DR when description is extra long (helps content team)
>
> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change
>
> Links to Notion, Figma or any other documents that might be relevant to the PR
>
>
#### PR fixes following issue(s)
Fixes #26981 
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
#### Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video
>
>
#### Type of change
> Please delete options that are not relevant.
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
## Testing
>
#### How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Also list any relevant details for your test configuration.
> Delete anything that is not relevant
- [ ] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-09-11 06:36 UTC, rahulramesha requested changes

2023-09-11 06:36 UTC, rahulramesha commented on app/client/src/selectors/widgetSelectors.ts
> +      parentRowSpace: childWidget.parentRowSpace
Could you please recheck this conditional logic? if it is correct could you make it more readable..

2023-09-11 10:57 UTC, rahulramesha submitted a review, later dismissed
@aswathkk looks good to me, please also get a review from List widget code owner for the list widget changes.

2023-09-13 04:58 UTC, sbalaji1192 approved these changes

2023-09-13 05:07 UTC, aswathkk commented
/ok-to-test

2023-09-13 05:48 UTC, aswathkk commented
/build-deploy-preview

2023-09-13 05:50 UTC, aswathkk commented
/ok-to-test

2023-09-13 08:36 UTC, aswathkk commented
/ok-to-test

2023-09-13 08:37 UTC, aswathkk commented
/build-deploy-preview

2023-09-14 03:17 UTC, aswathkk commented
/build-deploy-preview

2023-09-15 09:32 UTC, aswathkk commented
/ok-to-test

2023-09-15 11:26 UTC, aswathkk commented
/ok-to-test

2023-09-15 12:14 UTC, rahulramesha submitted a review, later dismissed

2023-09-15 12:28 UTC, aswathkk commented
/ok-to-test

2023-09-18 05:06 UTC, aswathkk commented
/ok-to-test

2023-09-18 12:13 UTC, aswathkk commented
/ok-to-test

2023-09-18 12:31 UTC, sbalaji1192 commented on app/client/src/layoutSystems/common/utils/ComponentSizeUtils.ts
> +export const getComponentDimensions = memoize(
nit: We can leverage the experimental decorator to implement the memorize as it's more readable.

2023-09-18 12:31 UTC, sbalaji1192 commented on app/client/src/layoutSystems/common/utils/ComponentSizeUtils.ts
> +export const getComponentDimensions = memoize(
By default, lodash memo only uses the first argument as the cache, you should use a resolver function to have more than one argument.
lets use `micro-memoize` across the board.

2023-09-18 14:45 UTC, aswathkk commented on app/client/src/layoutSystems/common/utils/ComponentSizeUtils.ts
> +export const getComponentDimensions = memoize(
decorators can be used only in the case of class methods. So, shall I use the mirco-memoize directly?

2023-09-18 14:54 UTC, aswathkk commented
/ok-to-test

2023-09-18 16:40 UTC, sbalaji1192 commented on app/client/src/layoutSystems/common/utils/ComponentSizeUtils.ts
> +export const getComponentDimensions = memoize(
Yeah. we can make these functions members of a class. But Feel free to ignore it if you think that would be too much

2023-09-18 16:40 UTC, sbalaji1192 commented on app/client/src/layoutSystems/common/utils/ComponentSizeUtils.ts
> +export const getComponentDimensions = memoize(
Yeah. let's use micro-memoize.

2023-09-18 20:12 UTC, prsidhu commented
/ok-to-test

2023-09-19 05:22 UTC, sbalaji1192 approved these changes

2023-09-19 05:22 UTC, merged