fix: Update render logic of switch environment component
appsmithorg/appsmith pull request #27043
Opened 2023-09-06 18:52 UTC by ChandanBalajiBP

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.
>
## Description
> Add a TL;DR when description is extra long (helps content team)
>
> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change
>
> Links to Notion, Figma or any other documents that might be relevant to the PR
>
>
#### PR fixes following issue(s)
Fixes #26880 
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
#### Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video
>
>
#### Type of change
> Please delete options that are not relevant.
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
## Testing
>
#### How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Also list any relevant details for your test configuration.
> Delete anything that is not relevant
- [ ] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-09-06 18:58 UTC, ankitakinger commented on app/client/src/ce/reducers/environmentReducer.ts
> +}
can we not add a type file instead of adding simply this in a reducer? We could re-use that type on EE as well.

2023-09-06 19:06 UTC, ChandanBalajiBP commented on app/client/src/ce/reducers/environmentReducer.ts
> +}
Yep this will be better implementation. I will update.

2023-09-08 05:10 UTC, ayushpahwa requested changes

2023-09-08 05:10 UTC, ayushpahwa commented on app/client/src/components/BottomBar/index.tsx
> +  // skip the render if no environments are present in view mode
The render logic is also handled in the appviewer file. We also need to account for the ramps visibility in case the feature is disabled. Will it make sense to collate everything in one place only. Since bottom bar is called in 2 places, it would be better to include that logic to this file only

2023-09-08 05:37 UTC, ChandanBalajiBP commented
/build-deploy-preview skip-tests=true

2023-09-12 14:13 UTC, ankitakinger commented on app/client/src/ee/reducers/environmentReducer.ts
> +export * from "ce/reducers/environmentReducer";
Why is this file not part of your CE PR? Your import will not work correctly on CE if this is not added there.

2023-09-12 14:14 UTC, ankitakinger requested changes
Comment added on one file

2023-09-13 06:13 UTC, ChandanBalajiBP commented
/ok-to-test

2023-09-13 10:20 UTC, ChandanBalajiBP commented on app/client/src/ee/reducers/environmentReducer.ts
> +export * from "ce/reducers/environmentReducer";
Updated

2023-09-13 10:20 UTC, ChandanBalajiBP commented on app/client/src/components/BottomBar/index.tsx
> +  // skip the render if no environments are present in view mode
Updated

2023-09-13 12:03 UTC, btsgh commented
1. When a non appsmith user logs in - this is what is observed. This behavior is incorrect
https://github.com/appsmithorg/appsmith/assets/101863839/24a91705-8acf-4e50-8f82-2b2d04875b17

2023-10-03 05:08 UTC, ankitakinger approved these changes

2023-10-06 04:01 UTC, ayushpahwa commented
/ok-to-test

2023-10-06 06:17 UTC, ayushpahwa approved these changes

2023-10-10 08:14 UTC, jsartisan submitted a review, later dismissed

2023-10-13 03:13 UTC, ayushpahwa commented
/build-deploy-preview skip-tests=true

2023-10-24 14:30 UTC, ayushpahwa commented
/build-deploy-preview skip-tests=true recreate=true

2023-10-24 14:30 UTC, ayushpahwa commented
/ok-to-test

2023-10-30 15:16 UTC, ayushpahwa approved these changes
Re-approving since last change was release merge

2023-10-30 15:20 UTC, ayushpahwa commented
Adding test plan label post testing by @riteshkew and me. cc: @btsgh

2023-10-30 15:34 UTC, merged