feat: only movies collection shown for mock DB A/B
appsmithorg/appsmith pull request #27049
Opened 2023-09-07 05:37 UTC by sneha122

## Description

This PR adds a new functionality, where in for mock DB movies, only movies collection will be shown for users who have ab_mock_mongo_schema_enabled flag enabled. This is an experimental feature, where in we want to check the relevance of mock DBs. Hence some users will only see movies collection where as others will continue to see all the collections.

#### PR fixes following issue(s)
Fixes #26937 
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
#### Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video
>
>
#### Type of change
- New feature (non-breaking change which adds functionality)
>
>
>
## Testing
>
#### How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Also list any relevant details for your test configuration.
> Delete anything that is not relevant
- [x] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-09-07 05:45 UTC, sneha122 commented
/ok-to-test

2023-09-07 05:45 UTC, sneha122 commented
/build-deploy-preview

2023-09-07 07:48 UTC, sumitsum requested changes

2023-09-07 09:37 UTC, sneha122 commented
/ok-to-test

2023-09-07 13:39 UTC, sneha122 commented
/build-deploy-preview

2023-09-07 14:21 UTC, NilanshBansal commented on app/server/appsmith-server/src/main/java/com/appsmith/server/featureflags/FeatureFlagEnum.java
> +    ab_mock_mongo_schema_enabled,
@sneha122 the usage looks good to me.

2023-09-07 15:09 UTC, sumitsum approved these changes

2023-09-07 15:15 UTC, sumitsum requested changes

2023-09-07 15:15 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/DatasourceStructureSolutionCEImpl.java
> +        Mono<Boolean> flagMono = featureFlagService.check(FeatureFlagEnum.ab_mock_mongo_schema_enabled);
Can you please rename this to something more informative e.g. `isMongoSchemaEnabledForMockDB` ?

2023-09-07 15:15 UTC, sumitsum commented on app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java
> +                        if (isMock != null && isMock && isFlagEnabled != null && isFlagEnabled) {
Could we replace the if condition logic with `isMock == true && isFlagEnabled == true` ?

2023-09-07 15:15 UTC, sumitsum commented on app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java
> +                Boolean isFlagEnabled) {
Instead of adding a boolean param named `isFlagEnabled` should we replace it with a list, because in future we could have more than one flag being passed to any function ? This list could have the names of all feature flags that are turned on.

2023-09-11 02:56 UTC, sneha122 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/DatasourceStructureSolutionCEImpl.java
> +        Mono<Boolean> flagMono = featureFlagService.check(FeatureFlagEnum.ab_mock_mongo_schema_enabled);
Done

2023-09-11 02:58 UTC, sneha122 commented on app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java
> +                        if (isMock != null && isMock && isFlagEnabled != null && isFlagEnabled) {
So for actual (non-mock) datasources, the value of datasourceStorage object does not have isMock key at all. Hence the check if `isMock != null` will account for such cases. Similarly second of `isFlagEnabled != null` is added to account for an edge case where the flag key is not present for any reason.

2023-09-11 03:02 UTC, sneha122 commented on app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java
> +                Boolean isFlagEnabled) {
Agreed, we can pass in the whole object of feature flags instead of a single flag, but right now FeatureFlagEnum.java file is located inside `/appsmith-server` module, if we want to use such object in mongoPlugin (which exists in `/appsmith-plugins`) we may have to shift FeatureFlagEnum.java to common module (`/appsmith-interfaces`). We can do that in a separate Github issue.

2023-09-11 03:17 UTC, sneha122 commented on app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java
> +                        if (isMock != null && isMock && isFlagEnabled != null && isFlagEnabled) {
Sorry I understood the comment now,. I will update the code accordingly

2023-09-11 04:21 UTC, sneha122 commented
/ok-to-test

2023-09-11 04:24 UTC, sneha122 commented
/build-deploy-preview

2023-09-11 06:11 UTC, sumitsum requested changes

2023-09-11 06:11 UTC, sumitsum commented on app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java
> +                        if (isMock != null
Hi @sneha122 do we need the `!=null` checks here ? Are they no implicitly checked as part of the `== true` check ?

2023-09-11 08:06 UTC, sneha122 commented on app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java
> +                        if (isMock != null
If we use isMock == true, it does not implicitly check for null case, instead it throws error. hence I have added null check explicitly

2023-09-11 08:23 UTC, sumitsum commented on app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java
> +                        if (isMock != null
Thanks @sneha122 for the clarification.

2023-09-11 08:23 UTC, sumitsum approved these changes

2023-09-12 05:22 UTC, sneha122 commented
/ok-to-test

2023-09-13 10:05 UTC, merged