Feat: Remove Action/Query/JS data from unevalTree
appsmithorg/appsmith pull request #27056
Opened 2023-09-07 07:26 UTC by ohansFavour

## Description

This PR reduces the size of the unevalTree by removing action/query/js function data from it. This improves the performance of Apps by

1. Reducing the overall time for generating dataTree diffs
2. Reducing the number of nodes in the dependency graph thereby improving dependency graph operations like

    -    Sorting dependencies
    -    Adding nodes to the dep graph
    

#### PR fixes following issue(s)

Fixes #23570

#### Type of change

- New feature (non-breaking change which adds functionality)

## Testing
WIP

#### How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Also list any relevant details for your test configuration.
> Delete anything that is not relevant
- [ ] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-09-07 07:28 UTC, ohansFavour commented
/ok-to-test

2023-09-07 07:29 UTC, ohansFavour commented
/build-deploy-preview skip-tests=true

2023-09-07 08:27 UTC, ohansFavour commented
/build-deploy-preview skip-tests=true

2023-09-07 10:10 UTC, ohansFavour commented
/ok-to-test

2023-09-07 10:11 UTC, ohansFavour commented
/build-deploy-preview skip-tests=true

2023-09-07 21:14 UTC, ohansFavour commented
/ok-to-test

2023-09-07 21:15 UTC, ohansFavour commented
/build-deploy-preview skip-tests=true

2023-09-08 05:07 UTC, ayushpahwa approved these changes

2023-09-11 09:50 UTC, ohansFavour commented
/build-deploy-preview skip-tests=true

2023-09-12 19:14 UTC, ohansFavour commented
/ok-to-test

2023-09-12 21:23 UTC, ohansFavour commented
/ok-to-test

2023-09-13 04:44 UTC, Rishabh-Rathod commented on app/client/src/workers/Evaluation/handlers/updateActionData.ts
> +    set(evalTree, `${entityName}.[${dataPath}]`, data);
We also need to update the global context here.

2023-09-13 08:19 UTC, ohansFavour commented on app/client/src/workers/Evaluation/handlers/updateActionData.ts
> +    set(evalTree, `${entityName}.[${dataPath}]`, data);
This has been updated

2023-09-13 09:48 UTC, Rishabh-Rathod reviewed
LGTM

2023-09-13 09:48 UTC, Rishabh-Rathod approved these changes

2023-09-17 12:09 UTC, ohansFavour commented
/ok-to-test

2023-09-17 12:09 UTC, ohansFavour commented
/build-deploy-preview skip-tests=true

2023-09-20 21:32 UTC, ohansFavour commented
/ok-to-test

2023-09-26 07:49 UTC, ohansFavour commented
/ok-to-test

2023-09-26 07:53 UTC, ohansFavour commented
/ok-to-test

2023-09-26 11:30 UTC, Rishabh-Rathod approved these changes
LGTM.

Small nit could be done later.

2023-09-26 11:30 UTC, Rishabh-Rathod commented on app/client/src/workers/Evaluation/dataStore/utils.ts
> +  }
nit:  Can we create a `getDataPathsForEntity` to have entity-specific logic to get path and then only set the data here?

2023-09-26 11:41 UTC, Rishabh-Rathod commented
/build-deploy-preview skip-tests=true env=release

2023-09-27 05:49 UTC, ohansFavour commented
/build-deploy-preview skip-tests=true

2023-09-27 06:06 UTC, ohansFavour commented
/build-deploy-preview skip-tests=true

2023-09-27 06:57 UTC, ohansFavour commented
/ok-to-test

2023-09-27 18:16 UTC, ohansFavour commented
/build-deploy-preview skip-tests=true

2023-09-27 19:41 UTC, Rishabh-Rathod requested changes

2023-09-27 19:41 UTC, Rishabh-Rathod commented on app/client/src/workers/common/DataTreeEvaluator/index.ts
> +    updateTreeWithData(tree, klona(DataStore.getDataStore()));
As the data would always be a valid JSON, it would be more efficient to use `klona/json` for dataStore cloning.

2023-09-27 19:43 UTC, Rishabh-Rathod commented on app/client/src/workers/common/DataTreeEvaluator/index.ts
> +    updateTreeWithData(tree, klona(DataStore.getDataStore()));
let's use alias as klonaJSON to avoid confusion.

2023-09-27 19:43 UTC, ohansFavour commented on app/client/src/workers/common/DataTreeEvaluator/index.ts
> +    updateTreeWithData(tree, klona(DataStore.getDataStore()));
Data can be anything. As anything can be returned from a js function's execution

2023-09-27 19:51 UTC, Rishabh-Rathod commented on app/client/src/workers/common/DataTreeEvaluator/index.ts
> +    updateTreeWithData(tree, klona(DataStore.getDataStore()));
1. In the case of API response data, it would always be a valid JSON.
2. Yes, the JS function can return invalid JSON values like a function or date object but these would anyway get stringified/removed when sending dataTree updates to mainThread. We are using the same `klona/JSON` for the serializing logic.  
Ref: https://github.com/appsmithorg/appsmith/pull/27319

2023-09-27 20:02 UTC, ohansFavour commented on app/client/src/workers/common/DataTreeEvaluator/index.ts
> +    updateTreeWithData(tree, klona(DataStore.getDataStore()));
This makes sense. I have updated the code

2023-09-27 20:03 UTC, ohansFavour commented
/ok-to-test

2023-09-27 20:03 UTC, ohansFavour commented
/build-deploy-preview skip-tests=true

2023-09-27 20:03 UTC, Rishabh-Rathod approved these changes

2023-09-27 22:03 UTC, merged