task: Calculate initial widget size in DataTreeFactory
appsmithorg/appsmith pull request #27073
Opened 2023-09-07 11:46 UTC by prsidhu

## Description

- Remove ```appPositioningType``` and ```isMobile``` props from widget
DataTree.
- Include width and height as ```derivedHeight and derivedWidth``` in
widget DataTree. Prefer width and height if available, else calculate
using position props.
- Update TableWidgetV2 to use the ```derivedHeight``` prop in
derivedProps calculation to get pageSize.

#### PR fixes following issue(s)
Fixes # [26629](https://github.com/appsmithorg/appsmith/issues/26629)

#### Type of change
> Please delete options that are not relevant.
- Bug fix (non-breaking change which fixes an issue)

## Testing
>
#### How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Also
list any relevant details for your test configuration.
> Delete anything that is not relevant
- [x] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress

#### Test Plan
> Add Testsmith test cases links that relate to this PR
1. Create an app.
2. Add a Table widget.
3. Connect the Table widget to a datasource.
4. Assert that the Table widget works as expected. The number of rows
per page are calculated accurately based on initial height of the
widget.

## Checklist:
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my
feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak
features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-)
have been covered
- [ ] Test plan covers all impacted features and [areas of
interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other
QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA
Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-09-07 12:01 UTC, marks0351 commented on app/client/src/utils/ComponentSizeUtils.ts
> +import type { BaseWidgetProps } from "widgets/BaseWidgetHOC/withBaseWidgetHOC";
lets move this file to the common folder of layoutSystems

2023-09-07 12:03 UTC, marks0351 requested changes
added just one minor nit.

2023-09-08 09:10 UTC, marks0351 submitted a review, later dismissed

2023-09-11 02:35 UTC, aswathkk commented
/ok-to-test

2023-09-11 04:37 UTC, aswathkk requested changes
There are some type issues due to which the client build fails. Can you check it @prsidhu?

2023-09-11 13:12 UTC, prsidhu commented
/ok-to-test

2023-09-12 08:12 UTC, aswathkk commented on app/client/src/layoutSystems/common/utils/ComponentSizeUtils.ts
> +export const getComponentDimensions = (
`isAutoLayout` and `isMobile` seems like a property of Auto Layout system.

Can we make `getComponentDimensions` to accept only `widgetProps` and `appPositioningType`?
Based on this prop, we can check what kind of layoutComponentDimensions method to be called.

2023-09-12 08:14 UTC, aswathkk requested changes

2023-09-12 08:14 UTC, aswathkk commented on app/client/src/layoutSystems/common/utils/ComponentSizeUtils.ts
> +export const getComponentDimensions = (
Also, can we memoize this function?
Seems like we would be calling it multiple times from DataTreeFactory

2023-09-12 11:29 UTC, marks0351 commented on app/client/src/layoutSystems/common/utils/ComponentSizeUtils.ts
> +export const getAutoLayoutComponentDimensions = ({
pls add the jsdocs from the actual functions, it was updated on the final version of the base widget pr.

2023-09-12 14:15 UTC, prsidhu commented
/ok-to-test

2023-09-12 15:58 UTC, prsidhu commented on app/client/src/layoutSystems/common/utils/ComponentSizeUtils.ts
> +export const getComponentDimensions = (
```isMobile``` dependency can not be removed yet. Auto Layout system needs it from the MainCanvas. It will be removed with the layout system.

2023-09-12 19:51 UTC, prsidhu commented
/ok-to-test

2023-09-13 06:57 UTC, aswathkk commented on app/client/src/utils/ComponentSizeUtils.ts
> +import type { BaseWidgetProps } from "widgets/BaseWidgetHOC/withBaseWidgetHOC";
@prsidhu Can we do it?

2023-09-13 09:18 UTC, riodeuno commented on app/client/src/entities/DataTree/dataTreeFactory.ts
> +        appPositioningType,
If I understand this correctly:
Instead of passing the `appPositioningType` and `isMobile` directly to the `dataTree` object, we're trying to derive the appropriate `componentHeight` and `componentWidth` to be included in the `dataTree` object.

2023-09-13 09:19 UTC, riodeuno commented on app/client/src/entities/DataTree/dataTreeWidget.ts
> +    isMobile,
We still have `isMobile` for backwards compatibility with Auto Layout, and we will not be relying on this in Anvil?
Is this assumption correct?

2023-09-13 09:22 UTC, riodeuno commented on app/client/src/selectors/dataTreeSelectors.ts
> +    state.ui.applications.currentApplication?.applicationDetail?.appPositioning
I'm assuming `appPositioning?.type` instead of `appPositioning.type` is for legacy applications that may not have the `appPositioning` object?

2023-09-13 09:22 UTC, riodeuno commented on app/client/src/selectors/dataTreeSelectors.ts
> +    state.ui.applications.currentApplication?.applicationDetail?.appPositioning
Let's add a comment to this, so that readers are aware of this fact and choice in the future.

2023-09-13 09:24 UTC, riodeuno commented on app/client/src/utils/ComponentSizeUtils.ts
> +import { AppPositioningTypes } from "reducers/entityReducers/pageListReducer";
I am wondering if the reducer is the right place for this type definition. Wouldn't a separate types or constants file in the layout system be a better spot?

2023-09-13 09:27 UTC, riodeuno commented on app/client/src/utils/ComponentSizeUtils.ts
> + * utility function to compute a widgets dimensions in Auto layout system
The Auto-Layout Layout system uses the mobile breakpoints for layouts. For this reason, the rows and columns occupied in the mobile breakpoint, and the rows and columns occupied in other viewport widths can be different. As a result, we check if we're in the mobile breakpoint using the `isMobile`, and use the appropriate `leftColumn`, `rightColumn`, `topRow` and `bottomRow` (with or without the `mobile` prefix depending on the `isMobile` value) to compute the component dimensions. The components here are the widgets.

2023-09-13 09:28 UTC, riodeuno commented on app/client/src/utils/ComponentSizeUtils.ts
> +      case AppPositioningTypes.AUTO:
I am assuming Anvil will not be relying on this, and will be using the absolute values from the `positionsReducer`?

2023-09-13 09:30 UTC, riodeuno commented on app/client/src/utils/ComponentSizeUtils.ts
> +export const getComponentDimensions = memoize(
Based on the Layout system we're using (`appPositioningType`) we use the widget properties to generate the component dimensions in pixels.
We memoize this function because?

2023-09-13 12:26 UTC, prsidhu commented on app/client/src/utils/ComponentSizeUtils.ts
> +      case AppPositioningTypes.AUTO:
@riodeuno Anvil will need initial position calculation when dropping a new widget. Position observer will execute and take over afterwards.

2023-09-13 12:27 UTC, prsidhu commented on app/client/src/entities/DataTree/dataTreeFactory.ts
> +        appPositioningType,
yes that's correct.

2023-09-13 12:28 UTC, prsidhu commented on app/client/src/entities/DataTree/dataTreeWidget.ts
> +    isMobile,
yes.

2023-09-13 12:31 UTC, prsidhu commented on app/client/src/utils/ComponentSizeUtils.ts
> +import type { BaseWidgetProps } from "widgets/BaseWidgetHOC/withBaseWidgetHOC";
@aswathkk This is what is causing the circular dependency.

2023-09-13 15:02 UTC, prsidhu commented on app/client/src/utils/ComponentSizeUtils.ts
> +import { AppPositioningTypes } from "reducers/entityReducers/pageListReducer";
It can be moved to the ```autoLayoutTypes.ts```. This is done in the Anvil layout structure PR that follows.

2023-09-13 15:07 UTC, prsidhu commented
/ok-to-test

2023-09-13 19:55 UTC, prsidhu commented on app/client/src/utils/ComponentSizeUtils.ts
> +export const getComponentDimensions = memoize(
To avoid re-computation if props for the widget haven't changed. What do you suggest?

2023-09-13 20:21 UTC, prsidhu commented
/ok-to-test

2023-09-13 21:59 UTC, prsidhu commented
/ok-to-test

2023-09-13 22:02 UTC, prsidhu commented
/ok-to-test

2023-09-13 22:51 UTC, prsidhu commented
/ok-to-test

2023-09-13 23:18 UTC, prsidhu commented
/ok-to-test

2023-09-14 03:06 UTC, merged