chore: Refactored on page load logic to allow different kinds of executables
appsmithorg/appsmith pull request #27112
Opened 2023-09-08 12:52 UTC by nidhi-nair

TBD

WIP, please do not merge or expend CI time on this

2023-09-11 08:19 UTC, subrata71 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/PageLoadActionsUtilCEImpl.java
> +                                    ActionDTO actionDTO = (ActionDTO) possibleEntity.getExecutable();
How does this piece of code allow different types of executables? It looks like it's tightly coupled with the `ActionDTO`. Please correct me if I am getting the wrong vibe.

2023-09-11 09:19 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/PageLoadActionsUtilCEImpl.java
> +    protected boolean isValidExecutableReferenceInBinding(EntityDependencyNode binding, Executable executable) {
This is the pending part I was talking about. I have only bunched up methods separately for now, they will move into separate files soon.

2023-09-11 09:19 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/LayoutActionServiceCEImpl.java
> +        List<Executable> flatmapPageLoadExecutables = new ArrayList<>();
I have used `calculated` and `provided` as prefixes. Does that work?

2023-09-11 09:20 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/PageLoadActionsUtilCEImpl.java
> +                                    ActionDTO actionDTO = (ActionDTO) possibleEntity.getExecutable();
No you're right, this is already a separate method, so haven't pulled it out. It'll separate when the interface is created.

2023-09-11 09:56 UTC, subrata71 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/LayoutActionServiceCEImpl.java
> +        List<Executable> flatmapPageLoadExecutables = new ArrayList<>();
@nidhi-nair 
Can we please stick to one convention? `Calculated` and `provided` don't seem to reflect the context that it's a call by ref variable, tbh.

I think a comment and a suffix/prefix together will give much better clarity. For example, adding `Ref` as suffix

```
/* 
* Variables having Ref at the end of their names denote they can be mutated
* if passed as arguments in functions.
* /

List<Executable> flatmapPageLoadExecutablesRef = new ArrayList<>();
```

We can also include this convention to our coding guideline in Appsmith.

2023-09-12 11:51 UTC, nidhi-nair commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/Executable.java
> +    Set<String> getSelfReferencingDataPaths();
Hey, looks like we can't. Self referencing applies to only action dto today, and has its own configuration paths to retrieve it from. I'll let this evolve as we encounter more types.

2023-09-12 18:36 UTC, subrata71 requested changes

2023-09-12 18:36 UTC, subrata71 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/onpageload/internal/PageLoadExecutablesUtilCEImpl.java
> +        Mono<List<Executable>> flatPageLoadERxecutablesMono = computeCompletePageLoadExecutableScheduleMono
Nit: Can you please fix the typo here `flatPageLoadERxecutablesMono`?

2023-09-12 18:36 UTC, subrata71 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/newaction/base/NewActionServiceCEImpl.java
> +                    layoutExecutableUpdateDTO.setDefaultActionId(
This function is still tightly coupled with ActionDTO. Can we implement it through `Executable` interface?

2023-09-12 18:36 UTC, subrata71 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/newaction/base/NewActionServiceCEImpl.java
> +            List<Executable> onLoadActions,
This function needs to be agnostic as it deals with list of Executables.

2023-09-12 18:36 UTC, subrata71 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/onpageload/internal/PageLoadExecutablesUtilCEImpl.java
> +    protected Set<EntityReferenceType> getExecutableTypes() {
QQ: This function needs to be overridden in the EEImpl for module instance. Is that correct?

2023-09-13 03:09 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/onpageload/internal/PageLoadExecutablesUtilCEImpl.java
> +    protected Set<EntityReferenceType> getExecutableTypes() {
That's correct.

2023-09-13 03:12 UTC, nidhi-nair commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/ActionDTO.java
> +        return this.getActionConfiguration();
It will need to return whatever it's implementation of `ExecutableConfiguration` is.

2023-09-13 03:13 UTC, nidhi-nair commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/MustacheHelper.java
>                      totalParents.addAll(MustacheHelper.getPossibleActions(reference));
That's correct, haven't code split yet because I am yet to get clarity on usage and differences.

2023-09-13 04:19 UTC, nidhi-nair commented
/ok-to-test

2023-09-13 04:48 UTC, nidhi-nair commented
/ok-to-test

2023-09-13 05:41 UTC, subrata71 commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/Executable.java
> +        layoutExecutableUpdateDTO.setDefaultActionId(this.getDefaultResources().getActionId());
I am wondering what would this function do `layoutExecutableUpdateDTO.setDefaultActionId` in case of ModuleInstance. 🤔

2023-09-13 05:59 UTC, nidhi-nair commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/Executable.java
> +        layoutExecutableUpdateDTO.setDefaultActionId(this.getDefaultResources().getActionId());
It's actually meant to point to default Id, which would be the module instance id.

2023-09-13 06:27 UTC, subrata71 commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/Executable.java
> +        layoutExecutableUpdateDTO.setDefaultActionId(this.getDefaultResources().getActionId());
ModuleInstance will introduce another field in the DefaultResources e.g. `moduleInstanceId`. In that sense, we need to introduce the respective `defaultModuelnstanceId` field in the `LayoutExecutableUpdateDTO` class.

2023-09-13 06:48 UTC, subrata71 submitted a review, later dismissed
@nidhi-nair 
The changes look good to me. I want you to think one more time from Git POV before merging this PR. Can any of these changes result in unwanted uncommitted changes?

2023-09-13 14:45 UTC, nidhi-nair commented
/ok-to-test

2023-09-13 17:56 UTC, merged