fix: Leave a role should be supported without permission as long as the role is directly assigned to the user
appsmithorg/appsmith pull request #27129
Opened 2023-09-09 14:14 UTC by trishaanand

Fixes https://github.com/appsmithorg/appsmith-ee/issues/2136

2023-09-09 14:32 UTC, trishaanand commented
/ok-to-test

2023-09-11 03:57 UTC, trishaanand commented on app/server/appsmith-server/src/test/java/com/appsmith/server/services/PermissionGroupServiceTest.java
Yes. This is in CE code repo and tests for common flow for leave role functionality. The EE file tests for EE only functionalities in EE repo

2023-09-11 03:58 UTC, trishaanand commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UserWorkspaceServiceCEImpl.java
> +                    if (assignedToUserIds.contains(currentUser.getId())) {
Not a big fan of ternary operator due to reduced code clarity for junior developers. If its not a big deal, I would like to leave this change as is.

2023-09-11 05:44 UTC, shubham7saxena7 submitted a review, later dismissed

2023-09-11 07:20 UTC, trishaanand commented
/ok-to-test

2023-09-12 08:07 UTC, trishaanand commented
/ok-to-test

2023-09-12 08:31 UTC, nsarupr requested changes
Added comments. Please check.

2023-09-12 08:31 UTC, nsarupr commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/PermissionGroupServiceCEImpl.java
> +                    String path = fieldName(QPermissionGroup.permissionGroup.assignedToUserIds);
Could this lead to a race condition, if two users try to leave the same Role simultaneously?

2023-09-12 08:31 UTC, nsarupr commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UserWorkspaceServiceCEImpl.java
>                  .single()
If the flux is empty, `single()` ends up throwing an error. Earlier, we were ensuring the same by throwing an error (Line#110-111).  Can we please take care of that?

2023-09-12 08:31 UTC, nsarupr commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/PermissionGroupServiceCEImpl.java
> +    public Mono<Boolean> leaveExplicitlyAssignedSelfRole(String permissionGroupId) {
Can you check if we need to send an event here?

2023-09-12 09:22 UTC, trishaanand commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/PermissionGroupServiceCEImpl.java
> +    public Mono<Boolean> leaveExplicitlyAssignedSelfRole(String permissionGroupId) {
No event needed till we actually use this for other functionalities.

2023-09-12 09:27 UTC, trishaanand commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UserWorkspaceServiceCEImpl.java
>                  .single()
Its already throwing an error if we don't find the user explicitly assigned to one of the default roles `getAllByAssignedToUserAndDefaultWorkspace`.  In fact I should remove this entire filtering logic since we would only get one default role from the query. I am removing the filtering mechanism right now.

2023-09-12 10:18 UTC, trishaanand commented
/ok-to-test

2023-09-12 10:19 UTC, trishaanand commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/PermissionGroupServiceCEImpl.java
> +                    String path = fieldName(QPermissionGroup.permissionGroup.assignedToUserIds);
Yes. Unfortunately this exists for all set operations today.

2023-09-15 09:45 UTC, nsarupr approved these changes
Changes look good to me .

2023-09-15 09:48 UTC, merged