[Task]: Create layout system structure for Anvil and AnvilFlexComponent.
appsmithorg/appsmith pull request #27178
Opened 2023-09-11 21:08 UTC by prsidhu

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.
>
## Description
1. Add new ```appPositioningType``` : ANVIL.
2. Create new code path and folder structure for Anvil layout system.
3. Move common pieces of functionalities between autoLayout and anvil to anvil folder structure (e.g. ```CanvasResizer```).
4. Create ```AnvilFlexComponent```.
5. Use WDS Flex component in AnvilFlexComponent.
6. Pass min max size props in a data structure that is supported by container queries in the Flex component.
    e.g. min-width: { base: "120px", "480px": "200px" }
7. Supply the following flex properties (flex-grow flex-shrink flex-basis) to widgets depending on their ```responsiveBehvaiour```:
    a) Fill: ```flex: 1 1 0%;```
    b) Hug: ```flex: 0 0 auto;```

#### PR fixes following issue(s)
Fixes # (issue number)
1. [#26987](https://github.com/appsmithorg/appsmith/issues/26987)
2. [#26609](https://github.com/appsmithorg/appsmith/issues/26609)
3. [#26611](https://github.com/appsmithorg/appsmith/issues/26611)

#### Type of change
- New feature (non-breaking change which adds functionality)

## Testing
>
#### How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Also list any relevant details for your test configuration.
> Delete anything that is not relevant
- [x] Manual
- [ ] JUnit
- [x] Jest
- [ ] Cypress

## Checklist:
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-09-12 11:58 UTC, marks0351 requested changes
Pls also add JS docs to elements in this pr.

2023-09-12 11:58 UTC, marks0351 commented on app/client/packages/design-system/widgets/src/components/Flex/src/index.styled.tsx
> +/* eslint-disable no-console */
placeholder to remove this.

2023-09-12 11:58 UTC, marks0351 commented on app/client/src/layoutSystems/anvil/canvasResizer/CanvasResizer.tsx
Regarding this file, I missed to point out during our discussion but I think we had some implementation changes to this component for anvil right?
Do you think we should have different versions of this component for Anvil vs Auto Layout.
cc: @rahulramesha

2023-09-12 11:58 UTC, marks0351 commented on app/client/src/layoutSystems/anvil/common/AnvilFlexComponent.tsx
> +      "480px": config["480px"] || minWidth,
can we add a meaningful constant name that describes how we arrived at 480

2023-09-12 11:58 UTC, marks0351 commented on app/client/src/layoutSystems/anvil/common/AnvilFlexComponent.tsx
> +      minWidth: updateMinWidth(props.widgetSize?.minWidth),
updateMinWidth isnt updating, so we could rename it to getMinWidth or anything that matches the implementation.

2023-09-12 11:58 UTC, marks0351 commented on app/client/src/layoutSystems/anvil/common/widgetComponent/AnvilWidgetComponent.tsx
> +  if (!detachFromLayout) return <div>{props.children}</div>;
do we need the additional div?

2023-09-12 11:58 UTC, marks0351 commented on app/client/src/layoutSystems/anvil/utils/constants.ts
> +export const defaultAutoLayoutWidgets = [
is this not obsolete in anvil

2023-09-12 11:58 UTC, marks0351 commented on app/client/src/layoutSystems/common/utils/commonUtils.ts
> +export const getAutoLayoutWidgetConfig = (
do we need this function?

2023-09-12 11:58 UTC, marks0351 commented on app/client/src/layoutSystems/withLayoutSystemHOC.tsx
> +  switch (appPositioningType) {
👍🏽

2023-09-12 11:58 UTC, marks0351 commented on app/client/src/layoutSystems/withLayoutSystemHOC.tsx
> +    AppPositioningTypes.ANVIL || appPositioningType,
is this added for local dev purpose?
if so adding a placeholder to remove it.

2023-09-12 11:58 UTC, marks0351 commented on app/client/src/widgets/BaseWidget.tsx
> +  width?: number;
I suggest we add layout system specific types and extend them, so that rest of the dev folks can see which property belongs to which layout system. and it is also easy to remove them when we deprecate.

2023-09-12 16:39 UTC, prsidhu commented on app/client/src/layoutSystems/common/utils/commonUtils.ts
> +export const getAutoLayoutWidgetConfig = (
Doesn't do any harm in having it.

2023-09-12 16:40 UTC, prsidhu commented on app/client/src/layoutSystems/withLayoutSystemHOC.tsx
> +    AppPositioningTypes.ANVIL || appPositioningType,
missed piece of hard coding. removed.

2023-09-12 19:47 UTC, prsidhu commented on app/client/src/layoutSystems/anvil/common/widgetComponent/AnvilWidgetComponent.tsx
> +  if (!detachFromLayout) return <div>{props.children}</div>;
errors out without the wrapping div

2023-09-13 05:22 UTC, marks0351 commented on app/client/src/layoutSystems/common/utils/commonUtils.ts
> +export const getAutoLayoutWidgetConfig = (
true, but when i try to describe this function, it takes `type` property of all the properties it receives and invokes another function. Is there any reason for not using the `WidgetFactory.getWidgetAutoLayoutConfig` function directly?.

2023-09-13 05:24 UTC, marks0351 commented on app/client/src/layoutSystems/anvil/common/AnvilFlexComponent.tsx
> +  // TODO: This wrapper was introduced to solve a bug with Map widget. Will be removed as part of a fix in another task.
Can we create a task instead coz its easy to track.

2023-09-13 20:04 UTC, prsidhu commented on app/client/src/layoutSystems/anvil/common/AnvilFlexComponent.tsx
> +  // TODO: This wrapper was introduced to solve a bug with Map widget. Will be removed as part of a fix in another task.
@marks0351 this task is in needs qa pipeline already:
https://app.zenhub.com/workspaces/ui-builders-pod-603e3779daa13d000e3b42be/issues/gh/appsmithorg/appsmith/27085

2023-09-18 21:43 UTC, prsidhu commented
/ok-to-test

2023-09-18 22:14 UTC, prsidhu commented
/ok-to-test

2023-09-19 09:32 UTC, aswathkk requested changes
I could see that we've moved some file & constants from `layoutSystem/autoLayout` to `layoutSystem/anvil`. This would create a tight coupling between these systems. It's better to make use of `layoutSystem/common` if you think there are some shared code between the layout systems. Otherwise, it's better to create duplicate files or constants that are specific for the layout System.

Also, added some other comments too. I merged the base brach with release today morning. Please pull from the latest release, merge it to this branch and resolve the conflicts.

2023-09-19 09:32 UTC, aswathkk commented on app/client/src/layoutSystems/anvil/common/AnvilFlexComponent.tsx
> +      <FlexComponentWrapper
Do we need `FlexComponentWrapper`?
Can't we attach the props like className, onClick, onClickCapture etc to the `Flex` itself?
Asking just to avoid an extra DOM element

2023-09-19 09:32 UTC, aswathkk commented on app/client/src/layoutSystems/anvil/common/AnvilFlexComponent.tsx
> +export type AnvilFlexComponentProps = FlexComponentProps & {
We should not extend this from `FlexComponentProps`. Instead, define `AnvilFlexComponentProps` from scratch.
FlexComponentProps has some required props like `isMobile` which is not required in `AnvilFlexComponentProps`

2023-09-19 09:32 UTC, aswathkk commented on app/client/src/layoutSystems/anvil/viewer/AnvilViewerWidgetOnion.tsx
> +      parentColumnSpace={props.parentColumnSpace}
`parentColumnSpace` and `isMobile` shouldn't be a part of Anvil.

2023-09-19 12:31 UTC, prsidhu commented on app/client/src/layoutSystems/anvil/common/AnvilFlexComponent.tsx
> +export type AnvilFlexComponentProps = FlexComponentProps & {
yeah, I had missed this. Will update.

2023-09-19 12:32 UTC, prsidhu commented on app/client/src/layoutSystems/anvil/common/AnvilFlexComponent.tsx
> +      <FlexComponentWrapper
Flex doesn't support click handlers.

2023-09-19 14:58 UTC, prsidhu commented on app/client/src/layoutSystems/anvil/common/AnvilFlexComponent.tsx
> +// Using a button to wrap the widget to ensure that accessibility features are included by default.
1. Flex (WDS) doesn't support click handlers.
2. Accessibility features like keyboard navigation can either be
   a) built into a div.
   b) or added by using a button stripped of default css.

There aren't any downsides to using a button here.

2023-09-19 15:44 UTC, aswathkk commented on app/client/src/layoutSystems/anvil/common/AnvilFlexComponent.tsx
> +      <FlexComponentWrapper
I've added support for id in https://github.com/appsmithorg/appsmith/pull/26190. Seems like it got removed recently. @jsartisan Any reason why we removed id from Flex component?

click handlers can be added using the `ref`.

2023-09-19 15:47 UTC, aswathkk commented on app/client/src/layoutSystems/anvil/common/AnvilFlexComponent.tsx
> +// Using a button to wrap the widget to ensure that accessibility features are included by default.
Why do we need to make these AnvilFlexComponent keyboard accessible? I don't see any point of these layout system component being keyboard accessible.

2023-09-19 15:49 UTC, aswathkk commented on app/client/src/layoutSystems/autolayout/utils/constants.ts
> -export const ROW_GAP = 12;
I would recommend re-creating these constants separately within anvil. If at a later point, we can be sure that the change in one variable doesn't affect the other layout system.

2023-09-19 16:04 UTC, prsidhu commented
@aswathkk It is okay for shared types, constants or files to reside in anvil directory. When autolayout has to removed, the folder can be deleted directly. If during our development, differences arise in values or types, then we can create duplicates and move them to appropriate folders.

2023-09-19 16:31 UTC, prsidhu commented on app/client/src/layoutSystems/anvil/common/AnvilFlexComponent.tsx
> +// Using a button to wrap the widget to ensure that accessibility features are included by default.
@KelvinOm What's your opinion? The alternatives are baking accessibility features into a div wrapper or adding it to the Flex component.

2023-09-19 17:43 UTC, prsidhu commented
/ok-to-test

2023-09-19 17:44 UTC, prsidhu commented on app/client/src/layoutSystems/autolayout/utils/constants.ts
> -export const ROW_GAP = 12;
moved to common.

2023-09-19 18:05 UTC, riodeuno commented on app/client/src/layoutSystems/anvil/common/AnvilFlexComponent.tsx
> +// Using a button to wrap the widget to ensure that accessibility features are included by default.
@prsidhu Could you point me to any reading material that goes in depth on the following topics:
1. Using button as a wrapper around a div for accessibility
2. Accessibility in layouts

I agree with the fact that even if we don't have users requesting accessibility, we must make sure our code is future thinking so as to support this when needed.

As I am not aware of the details of how the approach you've chosen works in favor of accessibility and how it may apply to screen readers. On the surface it seems like wrapping a button will allow the divs to be tabIndexed by default and help users navigate using tabs. Beyond this, I'm not sure I have anything to comment before I educate myself 😄

2023-09-19 19:03 UTC, riodeuno reviewed
@prsidhu I've reviewed the code and have added a few comments and discussion points. 

1. I appreciate the fact that we've described the components and functions at the top level. I will recommend that we review the code, and add comments in the hard to understand areas of the code. 

2. I also appreciate that we have added tests for most scenarios. I will once again recommend that we review the code, to identify any functions for whom we haven't added a unit test.

3. I have not reviewed the functions which have a "TODO" marker, as they are likely to change. I will recommend that we create associated tasks on GitHub such that they're tracked and handled so that we avoid tech debt or dangling functions.

2023-09-19 20:18 UTC, prsidhu commented on app/client/src/layoutSystems/anvil/common/AnvilFlexComponent.tsx
> +      maxHeight:
There is scope for the value to be an empty object, which is truthy. Hence the additional check.

2023-09-19 20:24 UTC, prsidhu commented on app/client/src/layoutSystems/anvil/common/resizer/AnvilResizableLayer.tsx
> +  // TODO: Does anvil need a new ResizableComponent?
@riodeuno yes, an agnostic resizable library would be a favourable solution here. For zones, however, we can do a quick POC on controlling their sizes using the flex property.

2023-09-19 20:25 UTC, prsidhu commented on app/client/src/layoutSystems/anvil/common/widgetComponent/AnvilWidgetComponent.tsx
> +  return (
yes, that's correct.

2023-09-19 20:27 UTC, prsidhu commented on app/client/src/layoutSystems/anvil/editor/AnvilEditorModalOnion.tsx
> +/**
https://app.zenhub.com/workspaces/ui-builders-pod-603e3779daa13d000e3b42be/issues/gh/appsmithorg/appsmith/27459

2023-09-19 20:30 UTC, prsidhu commented on app/client/src/layoutSystems/anvil/utils/constants.ts
> +export const ROW_GAP = 12;
yes, spacing tokens will be added in a separate task.

2023-09-19 21:38 UTC, prsidhu commented on app/client/src/layoutSystems/anvil/editor/AnvilEditorWidgetOnion.tsx
> +      widgetType={props.type}
Removed alignment, responsiveBehavior, focused and selected props.

hasAutoHeight / width and widgetSize require more props for proper calculation. For now, it is better to compute them outside and above FlexComponent.

2023-09-20 00:07 UTC, prsidhu commented on app/client/src/layoutSystems/anvil/common/AnvilFlexComponent.tsx
> +// Using a button to wrap the widget to ensure that accessibility features are included by default.
There are a few features to consider here:
1. Making elements navigable by keyboard.
2. Identifying an element as focusable.
3. Reading the contents of the element.

In Anvil, ```widgetNameComponent``` is drawn on a canvas. I don't, yet, know how to make it accessible.
So the widget has to be clicked upon to select it (_We may have to address selection of widget via selectors for the sake of cypress tests_). 
Using a button automatically solves for the first two features. We would need to add proper aria labels for the screen readers to read the inner content of the widget and to track changes in it. 
An alternative (less semantic way) is to use a div as
```
<div role="button" tabIndex="0" />
```
along with aria labels.

2023-09-20 00:51 UTC, prsidhu commented
/ok-to-test

2023-09-20 02:42 UTC, prsidhu commented on app/client/src/layoutSystems/anvil/common/AnvilFlexComponent.tsx
> +// Using a button to wrap the widget to ensure that accessibility features are included by default.
I don't want to add to the scope here and it doesn't make much sense to dwell on it. We can make a quick decision on it and revisit it later. The main reason for exploring accessibility here was drawing of ```WidgetNameComponent``` on a canvas.

2023-09-20 03:50 UTC, aswathkk commented on app/client/src/layoutSystems/anvil/common/AnvilFlexComponent.tsx
> +// Using a button to wrap the widget to ensure that accessibility features are included by default.
Think of a scenario where an input widget is going to be placed inside FlexComponentWrapper.
As a user, the expectation of keyboard accessibility is to access the input widget when I press `Tab` key. But since the wrapping element is also tabIndexed (a button), the focus will first go to the outermost element and then the user need to press the `Tab` key again to focus the input.

I would recommend to stick with `div` for now and revisit it later.

2023-09-20 04:01 UTC, riodeuno commented on app/client/src/layoutSystems/anvil/common/AnvilFlexComponent.tsx
> +      maxHeight:
I was wondering why typescript isn't taking care of the type safety by making sure the value is always in the expected object structure, otherwise `undefined`.

2023-09-20 12:34 UTC, prsidhu commented on app/client/src/layoutSystems/anvil/common/AnvilFlexComponent.tsx
> +// Using a button to wrap the widget to ensure that accessibility features are included by default.
you're right. While widget focus may still be an issue, it doesn't work as expected. I'll change it to a div.

2023-09-20 14:18 UTC, ankitakinger commented on app/client/cypress.config.ts
> +      PASSWORD: "XXX",
can we revert this file change?

2023-09-20 14:21 UTC, prsidhu commented
/ok-to-test

2023-09-20 14:38 UTC, prsidhu commented
/ok-to-test

2023-09-28 14:56 UTC, riodeuno reviewed
@prsidhu I have a few new comments.

2023-09-28 16:51 UTC, prsidhu commented on app/client/src/layoutSystems/anvil/common/AnvilFlexComponent.tsx
> +  }, [ref]);
@riodeuno I'm assuming that it should cause one re-render when ref is assigned to the flex component. Do you think it will change more often?
Another solution is to introduce another wrapping container that handles the click functionality.

2023-09-28 16:54 UTC, prsidhu commented on app/client/src/layoutSystems/anvil/viewer/AnvilViewerWrapper.tsx
> +  if (props.type === "CANVAS_WIDGET") {
will be resolved when the PRs are merged.

2023-09-28 17:26 UTC, prsidhu commented on app/client/src/layoutSystems/common/MainContainerResizer/MainContainerResizer.tsx
> +        top: "100%",
@riodeuno I'm unsure of how exactly this is working. However, it's purpose is to position the resizer to the right of canvas and **underneath the banner** at the top (for conversion messaging). Removing this value moves the resizer up and underneath the banner.

2023-09-28 17:27 UTC, prsidhu commented on app/client/src/layoutSystems/anvil/common/AnvilFlexComponent.tsx
> +  }, [ref]);
updated the dependancy to ```ref?.current```.

2023-09-28 17:28 UTC, prsidhu commented
/ok-to-test

2023-09-28 18:00 UTC, prsidhu commented on app/client/src/layoutSystems/anvil/common/AnvilFlexComponent.tsx
> +  }, [ref]);
@riodeuno replaced ref usage with a wrapping div that handles click functionality.

2023-09-28 18:00 UTC, prsidhu commented
/ok-to-test

2023-09-28 18:01 UTC, prsidhu commented
tested auto layout system on this PR locally. Seems to be working fine.

2023-10-02 10:30 UTC, riodeuno approved these changes
@prsidhu So far so good. Looks fine to me, let's merge this in and make changes in the subsequent tasks for Anvil.

2023-10-02 14:57 UTC, marks0351 approved these changes

2023-10-02 19:41 UTC, merged