feat: revamp welcome page feature
appsmithorg/appsmith pull request #27228
Opened 2023-09-12 14:11 UTC by Irongade

This PR introduces end to end implementation for the Welcome page revamp, as documented [here](https://www.figma.com/file/kbU9xPv44neCfv1FFo9Ndu/User-Activation?type=design&node-id=1900-48686&mode=design&t=BAR9OR7Wbaj2BUYw-0)

Fixes #27135 

#### How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Also list any relevant details for your test configuration.
> Delete anything that is not relevant
- [ ] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [x] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [x] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-09-12 14:36 UTC, Irongade commented
/ok-to-test

2023-09-12 16:34 UTC, Irongade commented
/ok-to-test

2023-09-13 06:45 UTC, ankitakinger approved these changes
LGTM

2023-09-13 15:56 UTC, AmanAgarwal041 commented on app/client/src/components/editorComponents/RadioButtonGroup.tsx
> +import { Text, Button } from "design-system";
Can we change the name of the file and the component as `design-system` also has `Radio` & `RadioGroup` components ?

2023-09-13 16:08 UTC, AmanAgarwal041 commented on app/client/src/pages/setup/SetupForm.tsx
> +    errors.proficiency = "Please select a proficiency level";
Can we use the same constant message variable to display the error text ?

2023-09-13 16:11 UTC, AmanAgarwal041 commented on app/client/src/pages/setup/constants.ts
> +export const proficiencyOptions = [
Shouldn't label and value be interchanged ? As we wan't to show the user the value on UI i.e. `Just dipping my toes 🌱 (Brand new to this)`

2023-09-14 09:01 UTC, Irongade commented on app/client/src/pages/setup/constants.ts
> +export const proficiencyOptions = [
Done

2023-09-14 09:01 UTC, Irongade commented on app/client/src/pages/setup/constants.ts
> +export const proficiencyOptions = [
Although now, the value sent to the server would be the "Beginner" value rather than the long text string. `Just dipping my toes 🌱 (Brand new to this)`

2023-09-14 09:04 UTC, Irongade commented
/ok-to-test

2023-09-14 13:37 UTC, AmanAgarwal041 submitted a review, later dismissed

2023-09-14 17:05 UTC, sumitsum requested changes

2023-09-14 17:05 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/domains/UserData.java
> +    private String proficiency;
Hi @Irongade APMU, we cannot remove a pre-existing variable from a class that is mapped to a Mongo collection because all the pre-existing Mongo documents in that collection would have a field called `role` which would now not exist in the Java class. This can cause application to break when reading older data. Hence, we should mark this field as deprecated using the `@deprecated` annotation. If required, please check for the usage of this annotation in the code to understand its usage better. So in summary: 
* please mark the `role` with `@deprecated` annotation
* create a new variable named `proficiency`

2023-09-14 17:05 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/UserSignupRequestDTO.java
> +    private String proficiency;
Please note that any DTO type of class e.g. this class is not supposed to be mapped to any collection in Mongo DB and hence we can delete the `role` variable here i.e. we don't have to go via the `@deprecated` route here. This usage should be correct.

2023-09-15 09:23 UTC, Irongade commented
/ok-to-test

2023-09-15 09:43 UTC, Irongade commented
/ok-to-test

2023-09-17 23:24 UTC, sumitsum approved these changes

2023-09-17 23:24 UTC, sumitsum commented
Server side changes LGTM.

2023-09-18 08:30 UTC, Irongade commented
/ok-to-test

2023-09-18 09:05 UTC, Irongade commented
/ok-to-test

2023-09-19 05:46 UTC, prapullc commented
/build-deploy-preview skip-tests=true

2023-09-19 09:44 UTC, prapullc commented
@Irongade 
1) the proficiency is not captured in the backend other details are being captured and attaching the screenshot for more clarity
<img width="1792" alt="Screenshot 2023-09-19 at 3 10 42 PM" src="https://github.com/appsmithorg/appsmith/assets/132243297/c8df4cee-5bba-4a83-913d-6d98b8325148">
cc: @rohan-arthur

2023-09-19 10:31 UTC, Irongade commented
/ok-to-test

2023-09-19 10:32 UTC, Irongade commented
/build-deploy-preview skip-tests=true

2023-09-19 13:07 UTC, sumitsum approved these changes

2023-09-20 10:02 UTC, Irongade commented
/build-deploy-preview skip-tests=true

2023-09-26 11:25 UTC, btsgh commented
/build-deploy-preview skip-tests=true recreate=true

2023-09-28 09:21 UTC, btsgh commented
/build-deploy-preview skip-tests=true recreate=true

2023-09-28 11:25 UTC, btsgh commented
/build-deploy-preview skip-tests=true recreate=true

2023-09-28 13:28 UTC, btsgh commented
Tested for proficiency Novice, the proficiency field is getting populated in the network tab payload section

2023-09-28 13:29 UTC, btsgh commented
/build-deploy-preview skip-tests=true recreate=true

2023-09-28 13:54 UTC, btsgh commented
/build-deploy-preview skip-tests=true recreate=true

2023-09-29 04:50 UTC, merged