feat: Add branch protection rules changes
appsmithorg/appsmith pull request #27246
Opened 2023-09-13 07:29 UTC by AnaghHegde

## Description
This PR adds check for handling the branch protection rules before performing the git commit, pull and delete ops. This is fall back for CE behaviour. This is paid feature and to keep the downgrade experience smoother, this change set is added. 

#### PR fixes following issue(s)
Fixes #26877

#### Type of change
- New feature (non-breaking change which adds functionality)

## Testing
#### How Has This Been Tested?
- [ ] Manual
- [ ] JUnit

#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-09-13 07:30 UTC, AnaghHegde commented
/ok-to-test

2023-09-14 05:12 UTC, nayan-rafiq requested changes

2023-09-14 05:12 UTC, nayan-rafiq commented on app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/ce/GitPrivateRepoHelperCEImpl.java
> +    public Mono<Boolean> isProtectedBranch(String branchName, GitApplicationMetadata gitApplicationMetadata) {
This method does not fit with the name of the class. I think we should move this to the `GitServiceCE`

2023-09-14 05:15 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/ce/GitPrivateRepoHelperCEImpl.java
> +    public Mono<Boolean> isProtectedBranch(String branchName, GitApplicationMetadata gitApplicationMetadata) {
@nayan-rafiq What do you mean by does not fit with the class? This is a CE fall back version when the feature flag is false.

2023-09-14 11:21 UTC, nayan-rafiq commented on app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/ce/GitPrivateRepoHelperCEImpl.java
> +    public Mono<Boolean> isProtectedBranch(String branchName, GitApplicationMetadata gitApplicationMetadata) {
The name of the class is PrivateRepoHelper but it's dealing with the protected branch logic. Hence I'm thinking that we can move the `isProtectedBranch` inside the GitServiceCE or rename this class to something like GitHelper.

2023-09-14 11:47 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/ce/GitPrivateRepoHelperCEImpl.java
> +    public Mono<Boolean> isProtectedBranch(String branchName, GitApplicationMetadata gitApplicationMetadata) {
Okay. But these are all paid features and hence grouping them in a single place would be helpful. I will rename this GitHelper.

2023-09-14 11:58 UTC, AnaghHegde commented
/ok-to-test

2023-09-18 06:59 UTC, AnaghHegde commented
/ok-to-test

2023-09-18 07:04 UTC, nayan-rafiq approved these changes

2023-09-18 10:49 UTC, merged