26736 feature password updation for supervisor basic auth
appsmithorg/appsmith pull request #27267
Opened 2023-09-13 12:42 UTC by sum35h

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.
>
## Description
> Add a TL;DR when description is extra long (helps content team)
>
> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change
>
> Links to Notion, Figma or any other documents that might be relevant to the PR
>
>
#### PR fixes following issue(s)
Fixes # (issue number)
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
#### Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video
>
>
#### Type of change
> Please delete options that are not relevant.
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
## Testing
>
#### How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Also list any relevant details for your test configuration.
> Delete anything that is not relevant
- [ ] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-09-13 12:42 UTC, sum35h commented
/ok-to-test

2023-09-14 11:04 UTC, sharat87 requested changes
There's also some conflicts in the PR, can you check please?

2023-09-14 11:04 UTC, sharat87 commented on deploy/docker/fs/opt/appsmith/templates/supervisord.conf.sh
Can we not use `%(ENV_APPSMITH_SUPERVISOR_USER)s` and similar for password in the existing `supervisor.conf` file instead of generating it with a shell script? Something like:

```ini
username=%(ENV_APPSMITH_SUPERVISOR_USER)s
password=%(ENV_APPSMITH_SUPERVISOR_PASSWORD)s
```

Just this change in the existing conf file should achieve the same thing, right?

2023-09-14 11:04 UTC, sharat87 commented on deploy/docker/fs/opt/appsmith/templates/nginx-app.conf.sh
> -    proxy_set_header  Connection        "";
Any reason we're removing these? Does the supervisor's web UI and logs watch pages work correctly without these?

2023-09-20 07:40 UTC, sum35h commented on deploy/docker/fs/opt/appsmith/templates/supervisord.conf.sh
That's cool, I was not aware that supervisord conf supported env var expansion. I'll try this out.

2023-09-20 08:06 UTC, sum35h commented on deploy/docker/fs/opt/appsmith/templates/nginx-app.conf.sh
> -    proxy_set_header  Connection        "";
Sorry, yes we need this.

2023-09-20 08:07 UTC, sum35h commented
/ok-to-test

2023-09-20 08:07 UTC, sum35h commented
/build-deploy-preview skipTests=True

2023-09-20 10:17 UTC, sharat87 commented on deploy/docker/fs/opt/appsmith/templates/supervisord.conf.sh
We use them in all the application config files, the `editor.conf`, `backend.conf` etc. 🙂

2023-09-20 10:22 UTC, sharat87 approved these changes

2023-09-20 10:22 UTC, merged