feat: add property showNoneIcon (defaults to true) to IconSelectControl
appsmithorg/appsmith pull request #27281
Opened 2023-09-13 17:08 UTC by dhruvikn

## Description

Add a new property `showNoneIcon` to IconSelectControl that defaults to `true`. When this property is `false`, the icon selector will not show `(none)` in the list and neither will search for it.

#### PR fixes following issue(s)
Fixes #26713

#### Type of change
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)

## Testing
>
#### How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Also list any relevant details for your test configuration.
> Delete anything that is not relevant
- [x] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-09-13 17:08 UTC, dhruvikn commented
/build-deploy-preview env=release

2023-09-13 18:08 UTC, dhruvikn commented
/build-deploy-preview skip-tests=true

2023-09-13 18:44 UTC, aswathkk requested changes
Added minor comment which I think would make the code a bit more readable.

Also, isn't it better to name this property `hideNoneIcon` rather than `showNoneIcon`?
Using that, we can also avoid making the default value as `true`

2023-09-13 18:44 UTC, aswathkk commented on app/client/src/components/propertyControls/IconSelectControl.tsx
> +    const noneIndex = ICON_NAMES.indexOf(NONE);
Do we really need to check the index of `NONE` since we are unshifting it and it would always be at 0th position?
We can just use the icon set to check if `NONE` is there or not.
How about the following change?

```suggestion
    const noneIconExists = icons.has(NONE);

    if (props.showNoneIcon && !noneIconExists) {
      ICON_NAMES.unshift(NONE);
      icons.add(NONE);
    } else if (!props.showNoneIcon && noneIconExists) {
      ICON_NAMES.shift();
      icons.delete(NONE);
    }
```

2023-09-13 18:44 UTC, aswathkk commented on app/client/src/components/propertyControls/IconSelectControl.tsx
> +    const noneIndex = ICON_NAMES.indexOf(NONE);
Multiple instances of the `IconSelectControl` class may be created, and each instance modifies the ICON_NAMES array and the icons set. Without this logic, the NONE icon may be added or removed multiple times, leading to unexpected behaviour. That's why you are adding and removing the NONE icon. Right?
Can you add a comment explaining the same?

2023-09-14 06:09 UTC, dhruvikn commented
/build-deploy-preview skip-tests=true

2023-09-14 11:25 UTC, dhruvikn commented
/ok-to-test

2023-09-14 14:03 UTC, aswathkk requested changes

2023-09-14 14:03 UTC, aswathkk commented on app/client/src/components/propertyControls/IconSelectControl.tsx
> +    if (!!!props.hideNoneIcon && !noneIconExists) {
Why do we need `!!!`?
Won't `!` be fine?

2023-09-14 14:03 UTC, aswathkk commented on app/client/src/components/propertyControls/IconSelectControl.tsx
> +    } else if (!!props.hideNoneIcon && noneIconExists) {
Similarly, do we need `!!`?

2023-09-15 06:32 UTC, dhruvikn commented on app/client/src/components/propertyControls/IconSelectControl.tsx
> +    if (!!!props.hideNoneIcon && !noneIconExists) {
Yes, you're right. Force typecasting here would be an overkill.

2023-09-15 06:32 UTC, dhruvikn commented on app/client/src/components/propertyControls/IconSelectControl.tsx
> +    } else if (!!props.hideNoneIcon && noneIconExists) {
Same as above. 🙏

2023-09-15 06:46 UTC, dhruvikn commented
/ok-to-test

2023-09-18 12:57 UTC, laveena-en commented
Tested & verified, changes look good to me!

2023-09-18 13:07 UTC, merged