add: maildev to the dps
appsmithorg/appsmith pull request #27340
Opened 2023-09-15 07:23 UTC by pratapaprasanna

2023-09-15 07:24 UTC, pratapaprasanna commented
/build-deploy-preview skip-tests=true

2023-09-15 10:56 UTC, sharat87 requested changes
This solves the problem, yes, but it's not overridable for individual PRs. Like described in the [linked issue's description](https://github.com/appsmithorg/cloud-deployment/issues/402#issue-1896524998).

Can we see if we can do something for that as well?

2023-09-15 10:58 UTC, sharat87 commented on scripts/deploy_preview.sh
> +  --set applicationConfig.APPSMITH_MAIL_SMTP_AUTH="false" --version $HELMCHART_VERSION
Can we please keep them on separate lines? It's _very_ hard to read. It looks like we're _deleting_ the `--version` argument and I was about to ask why we don't need it anymore. 🤦

Something like this:

```
  --set applicationConfig.APPSMITH_MAIL_ENABLED="true" \
  --set applicationConfig.APPSMITH_MAIL_FROM=$NAMESPACE@example.com \
  --set applicationConfig.APPSMITH_MAIL_HOST="maildev.default.svc.cluster.local" \
  --set applicationConfig.APPSMITH_MAIL_PORT="8025" \
  --set applicationConfig.APPSMITH_MAIL_SMTP_AUTH="false" \
```

I've also changed the domain in the from address. [Context Slack thread](https://theappsmith.slack.com/archives/CGBPVEJ5C/p1693998800614839). Also removed `hello-` so that the DP name shows up easy-to-read on Maildev's tiny tiny UI.

2023-09-27 09:17 UTC, pratapaprasanna commented on scripts/deploy_preview.sh
> +  --set applicationConfig.APPSMITH_MAIL_SMTP_AUTH="false" --version $HELMCHART_VERSION
@sharat87  let me know your thoughts about this approach ?

2023-10-03 07:51 UTC, sharat87 commented on scripts/deploy_preview.sh
> +   pod_name=$(kubectl get pods -n $NAMESPACE -o json | jq '.items[0].metadata.name' | tr -d '"')
```suggestion
   pod_name="$(kubectl get pods -n "$NAMESPACE" -o json | jq -r '.items[0].metadata.name')"
```

Or, with just `kubectl`: 🙂

```sh
   pod_name="$(kubectl get pods -n "$NAMESPACE" --template '{{(index .items 0).metadata.name}}')"
```

2023-10-03 07:51 UTC, sharat87 commented on scripts/deploy_preview.sh
> +   echo "modify docker.env to add maildev"
This block has three-space indentation. Can we fix it to two spaces please?

2023-10-03 07:51 UTC, sharat87 commented on scripts/deploy_preview.sh
> +   EOF"
I don't think this will work with this indentation. We have to remove the indentation in the command string for the `EOF` heredoc to work.

```suggestion
   kubectl exec -it $pod_name -n $NAMESPACE -- bash -c 'cat << EOF >> /appsmith-stacks/configuration/docker.env
APPSMITH_MAIL_FROM=hello@appsmith.com
APPSMITH_MAIL_ENABLED="true"
APPSMITH_MAIL_HOST="maildev.default.svc.cluster.local"
APPSMITH_MAIL_PORT="8025"
EOF'
```

Also changed to single-quotes, as otherwise the double-quotes will be lost.

2023-10-03 07:51 UTC, sharat87 commented on scripts/deploy_preview.sh
> +   kubectl exec -it $pod_name -n $NAMESPACE -- bash -c "supervisorctl restart backend"
Can may be be combined with the previous exec. Add `supervisorctl restart backend` right after `EOF`.

2023-10-21 16:34 UTC, closed without merging