Feature: API Pane Setting section redesign
appsmithorg/appsmith pull request #2738
Opened 2021-01-27 06:07 UTC by devrk96

2021-01-27 07:02 UTC, hetunandu requested changes

2021-01-27 07:02 UTC, hetunandu commented on app/client/src/pages/Editor/ActionSettings.tsx
> +          <div key={configProperty} style={{ marginBottom: "25px" }}>
Make this a styled component

2021-01-27 11:31 UTC, devrk96 commented on app/client/src/components/ads/TextInput.tsx
> +  defaultValue?: any;
Using a union type here is causing the type to change everywhere it is used as a text input like for the onChange method or validation functions. It is causing many conflicts like "number can't be defined for a name or email ".

2021-01-27 11:39 UTC, devrk96 commented on app/client/src/pages/Editor/ActionSettings.tsx
> +          <div key={configProperty} style={{ marginBottom: "25px" }}>
Resolved

2021-01-29 07:30 UTC, devrk96 commented on app/client/src/components/ads/TextInput.tsx
> +  onChange?: (value: any) => void;
Resolved

2021-01-29 07:46 UTC, merged