feat: refactored property name and added anvil type
appsmithorg/appsmith pull request #27397
Opened 2023-09-18 08:53 UTC by NilanshBansal

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.
>
## Description
> Add a TL;DR when description is extra long (helps content team)
>
> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change
>
> Links to Notion, Figma or any other documents that might be relevant to the PR
>
>
#### PR fixes following issue(s)
Fixes # (issue number)
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
#### Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video
>
>
#### Type of change
> Please delete options that are not relevant.
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
## Testing
>
#### How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Also list any relevant details for your test configuration.
> Delete anything that is not relevant
- [ ] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-09-20 17:02 UTC, rahulramesha commented
/ok-to-test

2023-09-20 17:09 UTC, rahulramesha commented
/build-deploy-preview skip-tests=true

2023-09-21 14:20 UTC, NilanshBansal commented
This PR is complete from the backend POV. Please proceed when the client changes are done.
cc: @somangshu @marks0351 @prsidhu @rahulramesha

2023-09-21 14:20 UTC, NilanshBansal commented
@AnaghHegde can you pls review the backend changes here.

2023-09-22 07:44 UTC, AnaghHegde requested changes
Since this is a change that affects git, can you update the `JsonSchemaMigration` class well?

2023-09-26 07:04 UTC, AnaghHegde reviewed
Minor comment rest looks good to me.

2023-09-26 07:04 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration025RenameAppPositioningProperty.java
> +        Criteria nonDeletedAppCriteria = where("deletedAt").is(null);
Can we use the query dsl instead of the hard coded string in the migration? I can see few places where this is doable.

2023-09-26 07:07 UTC, NilanshBansal commented on app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration025RenameAppPositioningProperty.java
> +        Criteria nonDeletedAppCriteria = where("deletedAt").is(null);
It is purposely done @AnaghHegde, so that in future we can deprecate and remove fields that are not required easily.

2023-09-26 07:12 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration025RenameAppPositioningProperty.java
> +        Criteria nonDeletedAppCriteria = where("deletedAt").is(null);
@NilanshBansal We will not be able to remove the fields completely due to the fact there could be exported app json and app synced to git repo out there. If we remove these and a user tried to import those backups, then the import will fail.

2023-09-26 08:31 UTC, marks0351 commented
/build-deploy-preview skip-tests=true

2023-09-26 08:31 UTC, marks0351 commented
/ok-to-test

2023-09-26 09:20 UTC, NilanshBansal commented
/ok-to-test

2023-09-26 09:20 UTC, NilanshBansal commented
/build-deploy-preview skip-tests=true recreate=true

2023-09-26 11:33 UTC, NilanshBansal commented
Closing this PR in lieu of https://github.com/appsmithorg/appsmith/pull/27633

2023-09-26 11:33 UTC, closed without merging