Do not show sections that are supposed to be hidden
appsmithorg/appsmith pull request #2746
Opened 2021-01-27 08:15 UTC by ofpiyush

## Description
Hides sections that have `hidden` set to true.

Fixes #2633

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Manually

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-01-27 08:50 UTC, hetunandu submitted a review, later dismissed

2021-01-28 06:05 UTC, hetunandu requested changes

2021-01-28 06:05 UTC, hetunandu commented on app/client/src/pages/Editor/DataSourceEditor/DBForm.tsx
> +    if (isHidden(this.props.formData, section.hidden)) return null;
Is this needed if you are already filtering out above in line 378? Can we filter hidden from there itself?

2021-01-28 06:05 UTC, hetunandu commented on app/client/src/pages/Editor/DataSourceEditor/DBForm.tsx
> +              console.log(e);
use log.error from "logLevel"

2021-01-28 06:06 UTC, ofpiyush commented on app/client/src/pages/Editor/DataSourceEditor/DBForm.tsx
> +    if (isHidden(this.props.formData, section.hidden)) return null;
It's the other way around, line 378 might not be required as React anyway handles `null` for rendering.

2021-01-28 08:56 UTC, hetunandu approved these changes

2021-01-28 08:56 UTC, merged