add submit action for input widget
appsmithorg/appsmith pull request #2749
Opened 2021-01-27 11:42 UTC by rishabhsaxena

## Description
Add a `onSubmit` action for the input widget

## Type of change
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
- todo

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-01-27 11:46 UTC, rishabhsaxena commented
@riodeuno should handle the case where the widget is a `textarea` instead of an input.
Would be good to have your inputs, how we can hide this action conditionally from the property pane.

2021-01-28 10:20 UTC, hetunandu requested changes

2021-01-28 10:20 UTC, hetunandu commented on app/client/src/widgets/InputWidget.tsx
> +      <div {...eventListeners}>
It is preferable to add this event listener directly on the input. There is a possibility in the future that someone could handle that event in the InputComponent itself and not let it bubble up

2021-01-28 11:03 UTC, hetunandu approved these changes

2021-01-28 11:15 UTC, merged