chore: Refactor styled component to css modules for checkbox/radio/switch
appsmithorg/appsmith pull request #27505
Opened 2023-09-20 12:12 UTC by jsartisan

Refactor css from styled component to css modules

Fixed #27386 
Fixed #27388
Fixed #27387

2023-09-20 12:17 UTC, jsartisan commented on app/client/packages/design-system/headless/src/components/Checkbox/src/Checkbox.tsx
> +      data-label-position={labelPosition}
note: this is required to position the inline label. Previously we were doing it with dynamic css.

2023-09-20 12:17 UTC, jsartisan commented on app/client/packages/design-system/headless/src/components/Switch/Switch.tsx
> -  icon?: React.ReactNode;
this was a miss on our end. this prop is not required.

2023-09-20 12:18 UTC, jsartisan commented on app/client/packages/design-system/widgets/src/components/Checkbox/stories/Checkbox.stories.mdx
> +    icon: EmotionHappyLineIcon,
This was a miss in my previous PR.

2023-09-20 12:37 UTC, jsartisan commented on app/client/packages/design-system/widgets/src/styles/src/field.module.css
> -    font-weight: ${({ isEmphasized }) => (isEmphasized ? "bold" : "normal")};
Note removing the code for the side label just for CSS, I'll raise another PR to remove the full support in types and component

2023-09-21 09:22 UTC, KelvinOm commented on app/client/packages/design-system/widgets/src/components/CheckboxGroup/stories/CheckboxGroup.stories.mdx
> -    labelWidth: "100px",
If we don't use such `labelPosition: "side"`, then we probably don't need `labelWidth` as a prop, right?

2023-09-21 09:28 UTC, KelvinOm requested changes
Please check the affected components once more time. For example, the input component has a broken label.

<img width="259" alt="Снимок экрана 2023-09-21 в 12 26 33" src="https://github.com/appsmithorg/appsmith/assets/11555074/67d0977d-45c0-4dd5-949e-1290ef2b38d5">

2023-09-21 09:28 UTC, KelvinOm commented on app/client/packages/design-system/headless/src/components/Checkbox/src/Checkbox.tsx
> +      data-label-position={labelPosition}
Seems like this doesn't work for switch. 
![Sep-21-2023 12-24-00](https://github.com/appsmithorg/appsmith/assets/11555074/5e0ec91b-ab3f-4204-b2e4-65987694352e)

2023-09-21 09:28 UTC, KelvinOm commented on app/client/packages/design-system/headless/src/components/Checkbox/src/Checkbox.tsx
> +      data-label-position={labelPosition}
Also do we need the same option for the radio?

2023-09-21 10:07 UTC, jsartisan commented on app/client/packages/design-system/widgets/src/components/CheckboxGroup/stories/CheckboxGroup.stories.mdx
> -    labelWidth: "100px",
Right.

2023-09-22 07:10 UTC, KelvinOm commented on app/client/packages/design-system/headless/src/components/Checkbox/src/Checkbox.tsx
> +      data-label-position={labelPosition}
Fixed

2023-09-22 07:11 UTC, KelvinOm commented on app/client/packages/design-system/widgets/src/components/CheckboxGroup/stories/CheckboxGroup.stories.mdx
> -    labelWidth: "100px",
Will be fixed [here](https://github.com/appsmithorg/appsmith/issues/27298).

2023-09-22 07:11 UTC, KelvinOm approved these changes

2023-09-22 07:14 UTC, merged