Implement new design for the builder page's navbar
appsmithorg/appsmith pull request #2750
Opened 2021-01-27 18:01 UTC by rishabhsaxena

## Description
Implement new design for the builder page's navbar

## Type of change
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
- manually

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-02-02 10:51 UTC, hetunandu requested changes

2021-02-02 10:51 UTC, hetunandu commented on app/client/src/pages/Editor/EditorHeader.tsx
> +        {currentApplication ? (
```suggestion
        {currentApplication && (
```

2021-02-02 10:51 UTC, hetunandu commented on app/client/src/pages/Editor/EditorHeader.tsx
> +        ) : null}
```suggestion
        )}
```

2021-02-02 10:51 UTC, hetunandu commented on app/client/src/pages/Editor/EditorHeader.tsx
> +        {currentApplication ? (
This is not getting "Boxed" anymore

2021-02-02 11:10 UTC, rishabhsaxena commented on app/client/src/pages/Editor/EditorHeader.tsx
> +        {currentApplication ? (
Should I remove the `Boxed` wrapper from the deploy button?

2021-02-02 11:13 UTC, hetunandu commented on app/client/src/pages/Editor/EditorHeader.tsx
> +        {currentApplication ? (
Looks like both need to be boxed. Can you confirm with Nikhil or Akash

2021-02-03 04:20 UTC, hetunandu submitted a review, later dismissed

2021-02-04 06:53 UTC, hetunandu approved these changes

2021-02-04 07:02 UTC, merged