fix: [one-click-binding] gsheets connection mode issue
appsmithorg/appsmith pull request #27613
Opened 2023-09-26 06:02 UTC by sbalaji1192

## Description
Updated the permission check on the Google sheet to look in the following path `atasourceConfiguration.authentication.scopeString`

#### PR fixes following issue(s)
Fixes https://github.com/appsmithorg/appsmith/issues/27102
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
#### Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video
>
>
#### Type of change
> Please delete options that are not relevant.
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
## Testing
>
#### How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Also list any relevant details for your test configuration.
> Delete anything that is not relevant
- [ ] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-09-26 09:01 UTC, sbalaji1192 commented
/ok-to-test

2023-09-26 09:09 UTC, sbalaji1192 commented
/ok-to-test

2023-09-26 09:10 UTC, sbalaji1192 commented
/build-deploy-preview skipTests=true

2023-09-29 05:39 UTC, sbalaji1192 commented
/ci-test-hosted

2023-10-02 03:58 UTC, sbalaji1192 commented
/ok-to-test

2023-10-05 01:51 UTC, rajatagrawal commented
@sbalaji1192 Is the PR ready for review ?

2023-10-05 09:03 UTC, laveena-en commented
/build-deploy-preview skipTests=true

2023-10-05 16:00 UTC, laveena-en commented
Tested the fix, changes look good to me.

2023-10-06 11:27 UTC, sbalaji1192 commented
/ok-to-test

2023-10-06 11:27 UTC, sbalaji1192 commented
@rajatagrawal This is ready for review.

2023-10-09 03:00 UTC, rajatagrawal commented on app/client/src/components/editorComponents/WidgetQueryGeneratorForm/utils.ts
> +export const getDatasourceConnectionMode = (
Is it possible to have a unit test for this function ?

2023-10-09 03:02 UTC, rajatagrawal commented on app/client/cypress/e2e/GSheet/WidgetBinding_AllAccess_Spec.ts
> +  it("3. One click binding to table widget functionality - GSheet", () => {
Is it possible to skip this cypress test ?

The code doesn't seem to add new user flow which hasn't been tested before using cypress. It seems like an additional feature is added to an existing functionality.

The existing functionality can be tested using only unit tests. It may be possible to be okay without a cypress test. Thoughts ?

2023-10-09 03:03 UTC, rajatagrawal requested changes
Left review comments. Please suggest your thoughts on the suggestions.

2023-10-09 04:49 UTC, sbalaji1192 commented
@rajatagrawal Made the changes you suggested. Please have a look.

2023-10-09 04:49 UTC, sbalaji1192 commented
/ok-to-test

2023-10-09 11:20 UTC, rajatagrawal approved these changes

2023-10-09 15:55 UTC, merged