fix for api-redirection
appsmithorg/appsmith pull request #27720
Opened 2023-09-29 12:18 UTC by sondermanish

## Description
> Fixes the API redirection problem where forwarding location only has uri path

This Pr adds null pointer checks for host address, adds stack trace in logging, and fixes the problem of erroring out when the  called endpoint redirection headers don't have full formed forwarding location

#### PR fixes following issue(s)
Fixes #25408 

#### Type of change
- Bug fix (non-breaking change which fixes an issue)

#### How Has This Been Tested?
- [ ] Manual
- [ ] JUnit

## Checklist:
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-10-03 06:12 UTC, nidhi-nair submitted a review, later dismissed

2023-10-03 07:29 UTC, sondermanish commented
/ok-to-test

2023-10-03 11:26 UTC, sondermanish commented
/build-deploy-preview skip-tests=true

2023-10-03 11:41 UTC, sharat87 requested changes

2023-10-03 11:41 UTC, sharat87 commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/RestAPIActivateUtils.java
> +    }
Can we use the [`URI.resolve`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/net/URI.html#resolve(java.lang.String)) method to do the resolution here instead of manually doing it please? It'll handle few other cases correctly, like `../redirect-path` etc.

```suggestion
    public URI createRedirectUrl(String redirectUrl, URI originalUrl) {
        return originalUrl.resolve(redirectUrl);
    }
```

2023-10-03 11:51 UTC, sondermanish commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/RestAPIActivateUtils.java
> +    }
got it, making the change

2023-10-03 12:37 UTC, sharat87 requested changes
Minor, but otherwise looks good. Thanks.

2023-10-03 12:37 UTC, sharat87 commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/RestAPIActivateUtils.java
> +    public URI createRedirectUrl(String redirectUrl, URI originalUrl) throws URISyntaxException {
I don't think this exception is being thrown in here.

```suggestion
    public URI createRedirectUrl(String redirectUrl, URI originalUrl) {
```

2023-10-03 12:37 UTC, sharat87 commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/RestAPIActivateUtils.java
> +                            //                            redirectUri = new URI(redirectUrl);
Can we remove this instead of commenting please?


```suggestion
```

2023-10-04 06:28 UTC, sharat87 approved these changes

2023-10-04 06:40 UTC, sondermanish commented
/build-deploy-preview skip-tests=true

2023-10-04 11:40 UTC, btsgh commented
Completed Manual testing of this PR. Works fine. @sondermanish  do let me know once your automation cases are added for this

2023-10-10 05:01 UTC, sondermanish commented
/ok-to-test

2023-10-10 08:54 UTC, nidhi-nair commented on app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java
> +                        error.printStackTrace();
Hey why are we printing stack trace like this?

2023-10-10 08:55 UTC, nidhi-nair commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/util/WebClientUtils.java
> +        request.url();
What does this line do?

2023-10-10 09:05 UTC, sondermanish commented on app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java
> +                        error.printStackTrace();
this is explicitly for debugging purpose, since this error is handled, it gets difficult to debug.

2023-10-10 09:11 UTC, sondermanish commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/util/WebClientUtils.java
> +        request.url();
was a typo, fixed that.

2023-10-10 10:24 UTC, nidhi-nair commented on app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java
> +                        error.printStackTrace();
Should we not log it using sl4j in that case?

2023-10-10 13:07 UTC, sondermanish commented on app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java
> +                        error.printStackTrace();
we don't get the complete trace on the error using, `error.getStackTrace()`

2023-10-11 06:31 UTC, nidhi-nair approved these changes

2023-10-11 08:46 UTC, btsgh commented
As per discussion with @sondermanish  - since junit tests are added, adding the test plan approved label.

2023-10-11 08:46 UTC, sondermanish commented
/ok-to-test

2023-10-11 16:24 UTC, merged