chore: Rate limiting datasource test api is added
appsmithorg/appsmith pull request #27777
Opened 2023-10-03 10:48 UTC by sneha122

## Description

This PR adds rate limiting functionality to datasource test API. The rate limiting configuration is added in such a way that if test API receives more than 3 failed authentication requests for the same host name within 5 seconds, It will block this hostname for the next 5 minutes, so that brute force attack can be stopped. 

Unit test for this will be covered in another PR. Refer #27742 

Currently this PR covers for postgres only, will need to extend the implementation for all plugins. Refer #27737 

#### PR fixes following issue(s)
Fixes #27736, #27739, #27744 
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
#### Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video
>
>
#### Type of change
- Chore (housekeeping or task changes that don't impact user perception)
>
>
>
## Testing
>
#### How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Also list any relevant details for your test configuration.
> Delete anything that is not relevant
- [x] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-10-03 10:49 UTC, sneha122 commented
/ok-to-test

2023-10-04 09:48 UTC, sneha122 commented
/ok-to-test

2023-10-04 09:48 UTC, sneha122 commented
/build-deploy-preview

2023-10-04 09:48 UTC, sumitsum requested changes

2023-10-04 09:48 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/ratelimiting/RateLimitService.java
> +    public Mono<Boolean> blockExecutionForPeriod(
QQ: Can you please explain the use of `apiIdentifier` param in both of the new added functions ?

2023-10-04 09:48 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/datasources/base/DatasourceServiceCEImpl.java
> +                    .isBlockingKeyPresent(RateLimitConstants.BUCKET_KEY_FOR_TEST_DATASOURCE_API, rateLimitIdentifier)
Can you please rename `isBlockingKeyPresent` to `isEndpointBlockedForRequest` ? in which case `isPresent` should change to `isBlocked`.

2023-10-04 09:48 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/datasources/base/DatasourceServiceCEImpl.java
> +                                            String datasourceId = datasourceStorage1.getDatasourceId();
Seems like `datasourceId` variable is not being used anywhere. Can you please check once ? If so, then should we remove it ?

2023-10-04 10:09 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/ratelimiting/RateLimitService.java
> +            String apiIdentifier, String userIdentifier, Duration timePeriod, AppsmithException exception) {
Would it be more meaningful to rename `userIdentifier` to `endpointIdentifier` because we are working with endpoints here ?

2023-10-04 12:06 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/datasources/base/DatasourceServiceCEImpl.java
> +    protected Mono<Boolean> shouldConsumeToken(DatasourceStorage datasourceStorage) {
Can you please rename this method to `consumeTokenIfAvailable` ?

2023-10-04 12:22 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/constants/RateLimitConstants.java
> +    public static final String BUCKET_KEY_FOR_TEST_DATASOURCE_API = "test";
Would it be meaningful to update it to `BUCKET_KEY_FOR_TEST_DATASOURCE_OR_EXECUTE_QUERY_API = "test_datasource_or_execute_query"` - because we want to add rate limit to both these APIs ?

2023-10-04 12:23 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/ratelimiting/RateLimitService.java
> +    public Mono<Boolean> blockExecutionForPeriod(
Can you please add comments explaining the usage of both of these functions ?

2023-10-04 14:30 UTC, sneha122 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/constants/RateLimitConstants.java
> +    public static final String BUCKET_KEY_FOR_TEST_DATASOURCE_API = "test";
Yes, if you check getOrCreateAPIUserSpecificBucket method of RateLimitConfig.java, it checks whether bucket already exists, if not it creates a new one. This variable is uniquely identifying that rate limiting needs to be applied for test api, this is added as prefix for the bucketIdentifier as well. Furthermore, if you check `apiConfigurations` map in RateLimitConfig.java, it is storing the configuration information for each API that is rate limited.

2023-10-04 14:36 UTC, sneha122 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/ratelimiting/RateLimitService.java
> +    public Mono<Boolean> blockExecutionForPeriod(
This `apiIdentifier` is added as part of blocked hostname in redis cache. So for hostname `example.com` and port of 5432, The blocked key in cache would look like `blockedtestexample.com5432`. This is simply denoting that its added because of rate limitation on test API. we can also remove it.

2023-10-04 14:41 UTC, sneha122 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/constants/RateLimitConstants.java
> +    public static final String BUCKET_KEY_FOR_TEST_DATASOURCE_API = "test";
Agreed, we can do that

2023-10-05 05:44 UTC, sneha122 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/datasources/base/DatasourceServiceCEImpl.java
> +                                            String datasourceId = datasourceStorage1.getDatasourceId();
Yeah looks like it is not being used anywhere, we can remove it

2023-10-05 10:51 UTC, sumitsum requested changes

2023-10-05 10:51 UTC, sumitsum commented on app/server/appsmith-plugins/postgresPlugin/src/main/java/com/external/plugins/PostgresPlugin.java
> +                } else if (port == null) {
Hi Sneha, for datsources, when the port value is null, we actually assume a default value for the port - so instead of only using the hostname, IMO, we should use hostname + defaultPort.

2023-10-05 10:51 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/datasources/base/DatasourceServiceCEImpl.java
> +    // This will block the execution for 5 minutes, in case of more than 3 failed connection attempts
Can you please update the comment to `... This will block the creation of datasource connection for 5 minutes ...` ?

2023-10-05 10:51 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/datasources/base/DatasourceServiceCEImpl.java
> +        return this.isEndpointBlockedForRequest(datasourceStorage).flatMap(isBlocked -> {
Sorry for asking this again - I know I asked for this change previously - can we please change the method name to `isEndpointBlockedForConnectionRequest` ?

2023-10-05 10:51 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/ratelimiting/RateLimitService.java
> +    public Mono<Boolean> blockExecutionForPeriod(
Can you please rename this method to `blockEndpointForConnectionRequest` ?

2023-10-05 10:56 UTC, sneha122 commented on app/server/appsmith-plugins/postgresPlugin/src/main/java/com/external/plugins/PostgresPlugin.java
> +                } else if (port == null) {
Agreed, we should combine default port in this case, but do we have default port for all the plugins? If yes can you please point me to where we save and use this default port?

2023-10-06 05:51 UTC, sumitsum commented on app/server/appsmith-plugins/postgresPlugin/src/main/java/com/external/plugins/PostgresPlugin.java
> +                } else if (port == null) {
Hi @sneha122 yes we have default port value for almost all the plugins. One way to find what value is being used would to be this : 
step1: check on Google what the default port for the database is e.g. this query on Google would work: default Postgres port 
step2: check if the same value has been used in the datasourceCreate function - this can be easily verified by searching the codebase (ctrl+f) for the value found in step1.

2023-10-06 06:16 UTC, sumitsum approved these changes

2023-10-06 07:42 UTC, sneha122 commented
/ok-to-test

2023-10-06 07:42 UTC, sneha122 commented
/build-deploy-preview

2023-10-06 12:13 UTC, sneha122 commented
/ok-to-test

2023-10-06 12:13 UTC, sneha122 commented
/build-deploy-preview

2023-10-06 13:23 UTC, sumitsum requested changes

2023-10-06 16:31 UTC, sumitsum submitted a review, later dismissed

2023-10-09 06:49 UTC, sneha122 commented
/ok-to-test

2023-10-09 06:53 UTC, sneha122 commented
/build-deploy-preview skip-tests=true

2023-10-09 11:05 UTC, sneha122 commented
/build-deploy-preview skip-tests=true

2023-10-09 14:54 UTC, sneha122 commented
/ok-to-test

2023-10-10 07:13 UTC, sumitsum approved these changes

2023-10-10 15:21 UTC, sneha122 commented
/build-deploy-preview skip-tests=true

2023-10-11 11:13 UTC, sumitsum approved these changes

2023-10-12 12:35 UTC, chandannkumar commented
Tested this PR and LGTM
- Tested for all mentioned Datasources:
Postgres
ArangoDB
Redshift
Redis
Oracle
SMTP
MySQL (with ssh and without ssh)
MSSQL
Elastic Search

2023-10-13 04:53 UTC, sneha122 commented
/ok-to-test

2023-10-13 12:55 UTC, sneha122 commented
/ok-to-test

2023-10-13 13:01 UTC, sumitsum submitted a review, later dismissed

2023-10-15 14:04 UTC, sneha122 commented
/ok-to-test

2023-10-15 14:07 UTC, sneha122 commented
/ok-to-test

2023-10-15 14:35 UTC, sneha122 commented
/ok-to-test

2023-10-16 06:18 UTC, sumitsum submitted a review, later dismissed

2023-10-17 06:31 UTC, sumitsum approved these changes

2023-10-17 09:38 UTC, merged