Fix: New widget and action name conflicts
appsmithorg/appsmith pull request #2778
Opened 2021-01-30 06:17 UTC by riodeuno

Fix widget add scenarios to make sure there are not conflicts between widget names and action names

## Description
When adding a new widget, the new widget's name should not conflict with an existing action name

Fixes #2773 
## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Manually

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-01-30 07:41 UTC, riodeuno commented
We should use the `evalTree` and `pageNames` for checking for conflicts as well.

2021-02-01 09:20 UTC, hetunandu requested changes

2021-02-01 09:20 UTC, hetunandu commented on app/client/src/sagas/WidgetOperationSagas.tsx
> +          ...entityNames,
Will the function be able to handle duplicate names in the array? `entityNames` here will also include most of `widgetNames`

2021-02-01 09:20 UTC, hetunandu commented on app/client/src/sagas/WidgetOperationSagas.tsx
> +    const widgetName = getNextWidgetName(widgets, "TABLE_WIDGET", evalTree);
Different way of getting a name here. Lets make a common function for this

2021-02-01 11:32 UTC, ofpiyush commented on app/client/src/sagas/WidgetOperationSagas.tsx
> +  const entityNames = Object.keys(evalTree);
Do we need `widgetNames` anymore?

can use `getEntityNames` at the caller.

2021-02-01 12:36 UTC, riodeuno commented on app/client/src/sagas/WidgetOperationSagas.tsx
> +          ...entityNames,
There will be redundant entries. But, this is faster than looping through the arrays to find uniq names.
The other approach is to keep track of the new widgets introduced so far in the loop. Which increases the complexity of the function. 
So, this should work out fine.

2021-02-01 12:37 UTC, riodeuno commented on app/client/src/sagas/WidgetOperationSagas.tsx
> +  const entityNames = Object.keys(evalTree);
These are being used in a loop where new widgets have been added. We need to make sure there are no conflicts with these new names as well.

2021-02-01 12:39 UTC, riodeuno commented on app/client/src/sagas/WidgetOperationSagas.tsx
> +  const entityNames = Object.keys(evalTree);
I'll update the code by using `getEntityNames`

2021-02-01 12:43 UTC, riodeuno commented on app/client/src/sagas/WidgetOperationSagas.tsx
> +    const entityNames = Object.keys(evalTree);
`getEntityNames` is a generator function. I can't use it a normal function inside a loop. Hence, the lack of re-use.

2021-02-01 12:46 UTC, riodeuno commented on app/client/src/sagas/WidgetOperationSagas.tsx
> +  const entityNames = Object.keys(evalTree);
Just realized, `getEntityNames` is a generator function, so I can't use that in loops. `getNextEntityName` is a function which can. I'll update this above where @hetunandu  mentioned it.

2021-02-01 12:47 UTC, riodeuno commented on app/client/src/sagas/WidgetOperationSagas.tsx
> +    const widgetName = getNextWidgetName(widgets, "TABLE_WIDGET", evalTree);
This is the common function `getNextWidgetName` which I've used in this file. It gets called within map functions, so I have to keep it as a `non-generator` function.

2021-02-01 14:32 UTC, hetunandu approved these changes

2021-02-01 14:32 UTC, merged