Bug automation
appsmithorg/appsmith pull request #2780
Opened 2021-01-31 08:16 UTC by NandanAnantharamu

Added test for Bugs related to renaming of tabs from Entity explorer

2021-02-01 05:11 UTC, hetunandu requested changes

2021-02-01 05:11 UTC, hetunandu commented on app/client/cypress/integration/Smoke_TestSuite/ExplorerTests/Entity_Explorer_Tab_rename_Delete_spec.js
> +    cy.RenameEntity("UpdatedTab");
After rename, refresh the browser and check for the name again

2021-02-01 07:00 UTC, mohanarpit commented on app/client/cypress/integration/Smoke_TestSuite/ExplorerTests/Entity_Explorer_Tab_rename_Delete_spec.js
> +    cy.RenameEntity("UpdatedTab");
For my understanding, why should the browser be refreshed to check for entity name updates? Shouldn't this happen without a refresh as well?

2021-02-01 07:38 UTC, NandanAnantharamu commented on app/client/cypress/integration/Smoke_TestSuite/ExplorerTests/Entity_Explorer_Tab_rename_Delete_spec.js
> +    cy.RenameEntity("UpdatedTab");
I did check with @riodeuno and taken the use-cases for these bugs, this is still WIP will update with further assertions. Do let me know if we need to refresh the page after changing the name.

2021-02-23 09:34 UTC, hetunandu approved these changes

2021-02-23 09:38 UTC, merged