feat: Table widget currency column
appsmithorg/appsmith pull request #27819
Opened 2023-10-04 10:42 UTC by sbalaji1192

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.
>
## Description
> Add a TL;DR when description is extra long (helps content team)
>
> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change
>
> Links to Notion, Figma or any other documents that might be relevant to the PR
>
>
#### PR fixes following issue(s)
Fixes # (issue number)
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
#### Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video
>
>
#### Type of change
> Please delete options that are not relevant.
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
## Testing
>
#### How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Also list any relevant details for your test configuration.
> Delete anything that is not relevant
- [ ] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-10-04 11:35 UTC, sbalaji1192 commented
/build-deploy-preview skipTests=true

2023-10-05 04:28 UTC, sbalaji1192 commented
/build-deploy-preview skipTests=true

2023-10-05 04:39 UTC, sbalaji1192 commented
/build-deploy-preview skipTests=true

2023-10-05 07:15 UTC, sbalaji1192 commented
/build-deploy-preview skipTests=true

2023-10-05 07:29 UTC, sbalaji1192 commented
/build-deploy-preview skipTests=true

2023-10-05 18:52 UTC, sbalaji1192 commented
/build-deploy-preview skipTests=true

2023-10-09 07:41 UTC, sbalaji1192 commented
/ok-to-test

2023-10-09 07:41 UTC, sbalaji1192 commented
/build-deploy-preview skipTests=true

2023-10-10 11:31 UTC, sbalaji1192 commented
/ok-to-test

2023-10-10 11:32 UTC, dhruvikn commented
If this PR is ready to review, can we revert the draft PR state? @sbalaji1192

2023-10-10 11:35 UTC, sbalaji1192 commented
@dhruvikn Yes. Its ready for review.

2023-10-11 04:23 UTC, sbalaji1192 commented
/ok-to-test

2023-10-11 06:27 UTC, sbalaji1192 commented
/ok-to-test

2023-10-11 10:21 UTC, dhruvikn commented
/build-deploy-preview skip-tests=true

2023-10-12 08:23 UTC, dhruvikn approved these changes

2023-10-12 10:42 UTC, sbalaji1192 commented
/build-deploy-preview skip-tests=true

2023-10-12 10:42 UTC, sbalaji1192 commented
/ok-to-test

2023-10-12 10:44 UTC, dhruvikn approved these changes

2023-10-16 06:38 UTC, laveena-en commented
@sbalaji1192 

Relevant Style properties as seen on the Number column aren’t present
<img width="341" alt="image" src="https://github.com/appsmithorg/appsmith/assets/109572422/90596d2d-8494-4142-80b9-2227ef7f27e1">


Cell wrapping isn't available

On adding a `-` sign before any digit, an error isn't being thrown as seen on the CurrencyInput widget
https://www.loom.com/share/f9569fee70c148b78244a869947cbc17?sid=044e032c-f155-471f-b2f9-3b0a9853cb3d

2023-10-30 07:16 UTC, sbalaji1192 commented
@laveena-en 
> Cell wrapping isn't available
Cell wrapping for the currency column is unnecessary since we have compact mode in the property pane.

>On adding a - sign before any digit, an error isn't being thrown as seen on the CurrencyInput widget
we are following the same behavior as the number column.
CC @dilippitchika

2023-10-30 07:17 UTC, sbalaji1192 commented
/ok-to-test

2023-11-01 04:51 UTC, sbalaji1192 commented
/build-deploy-preview skipTests=true

2023-11-01 04:52 UTC, sbalaji1192 commented
@KelvinOm Can you take a look at this PR? I have made a few changes in the forked WDSTable to update the references.

2023-11-01 14:04 UTC, KelvinOm commented
> @KelvinOm Can you take a look at this PR? I have made a few changes in the forked WDSTable to update the references.

I don't see the currency working in the WDS Table. You can simply copy-paste your changes from the original widget. We haven't made any functionality change yet. Now WDS Table is just a fork.

2023-11-01 14:04 UTC, KelvinOm requested changes

2023-11-02 12:57 UTC, sbalaji1192 commented on app/client/src/widgets/TableWidgetV2/component/cellComponents/InlineCellEditor.tsx
> +  if (isNaN(parsedValue) || inputValue.trim() === "" || isNil(inputValue)) {
just being extra cautious to avoid coercing `" "` as `0`.

2023-11-02 12:57 UTC, sbalaji1192 commented on app/client/src/widgets/TableWidgetV2/component/cellComponents/PlainTextCell.tsx
> +        inputHTMLType={inputHTMLType as InputHTMLType}
Updated the type upstream.

2023-11-02 12:59 UTC, sbalaji1192 commented
@KelvinOm Let's create an issue for the WDS table separately.
CC @somangshu

2023-11-03 08:22 UTC, KelvinOm commented
> @KelvinOm Let's create an issue for the WDS table separately. CC @somangshu

@sbalaji1192  We can do this as a separate task, but then please delete the changes in the WDS table. This not needed right?

2023-11-03 08:57 UTC, laveena-en commented
Tested and verified the feature in new and existing table widgets. PR looks good to me!

[Test plan](https://github.com/appsmithorg/TestSmith/issues/2447)

2023-11-03 09:07 UTC, sbalaji1192 commented
> @sbalaji1192 We can do this as a separate task, but please delete the changes in the WDS table. This not needed

@KelvinOm 
We need those changes. WDSTable refers to the constant `ColumnTypes` from the tableWidgetv2 when the same constant is available in its constants file. This was not a problem, since they were holding the same value. But as part of this PR, we added a new column type in the table widget v2, and this is causing type issues in the WDS table.

2023-11-03 10:49 UTC, sbalaji1192 commented
/ok-to-test

2023-11-03 15:15 UTC, KelvinOm approved these changes

2023-11-05 03:48 UTC, sbalaji1192 commented
/ok-to-test

2023-11-06 03:03 UTC, sbalaji1192 commented
/ok-to-test

2023-11-06 03:05 UTC, sbalaji1192 commented
/ok-to-test

2023-11-06 05:35 UTC, merged