chore: add strict-boolean-expressions rule
appsmithorg/appsmith pull request #27852
Opened 2023-10-05 18:38 UTC by KelvinOm

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.
>
## Description
> Add a TL;DR when description is extra long (helps content team)
>
> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change
>
> Links to Notion, Figma or any other documents that might be relevant to the PR
>
>
#### PR fixes following issue(s)
Fixes # (issue number)
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
#### Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video
>
>
#### Type of change
> Please delete options that are not relevant.
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
## Testing
>
#### How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Also list any relevant details for your test configuration.
> Delete anything that is not relevant
- [ ] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-10-05 18:38 UTC, KelvinOm commented
/ok-to-test

2023-10-06 08:30 UTC, KelvinOm commented on app/client/package.json
> +    "lint": "eslint --cache ./src && cd ./cypress && eslint -c .eslintrc.json --cache ./",
Removed the extension indication as it is covered by default. I also had to change the script for cypress checks, as I added a path to the `tsconfig` and because of this there were conflicts in the eslint configurations.

cc @Aishwarya-U-R

2023-10-06 08:30 UTC, KelvinOm commented on app/client/packages/rts/.eslintrc.json
> +  "ignorePatterns": ["dist", "server.test.ts"],
`server.test.ts` is excluded in `tsconfig` so we have to exclude it here as well.

2023-10-06 08:31 UTC, KelvinOm commented
/ok-to-test

2023-10-06 08:33 UTC, Aishwarya-U-R commented
> https://github.com/appsmithorg/appsmith/actions/runs/6429347315

@KelvinOm - Please always merge with latest release & then start run. AutoHeight_Form_spec.ts is fixed & merged now.

2023-10-06 08:45 UTC, dhruvikn requested changes

2023-10-06 08:45 UTC, dhruvikn commented on app/client/cypress/.eslintrc.json
> +  ],
Just wanted to understand why are we ignoring these files?

2023-10-06 09:06 UTC, KelvinOm commented
> > /ok-to-test
> 
> @KelvinOm - Please always merge with latest release & then start run. AutoHeight_Form_spec.ts is fixed & merged now.

@Aishwarya-U-R Yeah, I'm practicing it. The previous launch was yesterday.

2023-10-06 09:08 UTC, KelvinOm commented on app/client/cypress/.eslintrc.json
> +  ],
@dhruvikn Thanks for the question. I completely forgot about it.

@Aishwarya-U-R Lint can't handle the situation when we have .ts and .js files with same name. Can we remove the JS implementation?

![Снимок экрана 2023-10-06 в 12 07 01](https://github.com/appsmithorg/appsmith/assets/11555074/7db4b099-b9a0-468c-96e6-82de9cb4e57c)

2023-10-06 09:10 UTC, KelvinOm commented on app/client/package.json
> +    "lint": "eslint --cache ./src && cd ./cypress && eslint -c .eslintrc.json --cache ./",
I forgot to say that this is another reason to move the cypress to packages. There would be no such problem there.

2023-10-06 10:04 UTC, Aishwarya-U-R commented on app/client/cypress/.eslintrc.json
> +  ],
@KelvinOm - Can you rename .ts to `AudioRecorder_Spec.ts` - does this case account as different file? Else please rename Js to `AudioRecorder1_spec.js` & proceed.

2023-10-06 10:05 UTC, Aishwarya-U-R commented on app/client/cypress/.eslintrc.json
> +  ],
Same for Mongo_spec also.

2023-10-06 10:35 UTC, KelvinOm commented
/ok-to-test

2023-10-06 10:44 UTC, KelvinOm commented
/ok-to-test

2023-10-06 12:46 UTC, dhruvikn approved these changes

2023-10-06 12:49 UTC, jsartisan approved these changes

2023-10-06 13:05 UTC, merged