chore: remove xml parser v3 as a default library
appsmithorg/appsmith pull request #27857
Opened 2023-10-06 05:42 UTC by arunvjn

## Description
- Removes XML parser as a default library from Appsmith apps. 
- xmlParser v3 will continue to work in older apps and it would be installed in them as a custom JS library. 
- Removes namespace collision check on library. At the time of installation, if the library accessor has a collision with the already entities of the application, we simply determine a unique identifier and install the library under that namespace.
>
#### PR fixes following issue(s)
Fixes https://github.com/appsmithorg/appsmith-ee/issues/2073
Fixes https://github.com/appsmithorg/appsmith-ee/issues/2402
Fixes https://github.com/appsmithorg/appsmith-ee/issues/2403
Fixes https://github.com/appsmithorg/appsmith-ee/issues/2562
Fixes https://github.com/appsmithorg/appsmith-ee/issues/2563
>
>
#### Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video
>
>
#### Type of change
- Chore (housekeeping or task changes that don't impact user perception)
>
>
>
## Testing
>
#### How Has This Been Tested?
- [ ] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-10-06 08:41 UTC, KelvinOm commented on app/client/src/workers/Tern/tern.worker.ts
> +      // xmlJs,
Could you remove this?

2023-10-06 08:41 UTC, KelvinOm commented on app/client/src/workers/Evaluation/handlers/jsLibrary.ts
> +//   code = LibraryInstallError.NameCollisionError;
Could you remove this?

2023-10-06 08:41 UTC, KelvinOm commented on app/client/src/workers/Evaluation/handlers/jsLibrary.ts
> +      //@ts-expect-error no types
Could  you add correct typing here and in other places too?

2023-10-06 09:47 UTC, arunvjn commented
Marking this as draft since it is still a WIP. @KelvinOm

2023-10-09 15:41 UTC, arunvjn commented
/ok-to-test

2023-10-09 15:41 UTC, arunvjn commented
/build-deploy-preview skip-tests=true

2023-10-11 12:54 UTC, sondermanish commented
/ok-to-test

2023-10-11 15:04 UTC, arunvjn commented
/ok-to-test

2023-10-12 03:49 UTC, sumitsum requested changes

2023-10-12 03:49 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/domains/CustomJSLib.java
> +    public Set<Map<String, String>> transformAccessor(Set<String> accessorSet) {
Can you please add comment here explaining the context for this change i.e. why this change is required ?

2023-10-12 03:49 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/domains/CustomJSLib.java
> +    public void modifyAccessorValueForXMLParser() {
Can you please add comment here explaining what this method does ?

2023-10-12 03:49 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/domains/CustomJSLibCompatibilityDTO.java
> +public class CustomJSLibCompatibilityDTO extends BranchAwareDomain {
Hi Manish,
(1) Should this class be moved to `dtos/` directory ? 
(2) Can you please add a comment explaining why this class is required ?

2023-10-12 03:49 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/domains/CustomJSLibCompatibilityDTO.java
> +    public static Set<String> transformAccessor(Set<Map<String, String>> accessorMapSet, String accessorKey) {
Can you please rename this method to `transformAccessorToSetOfString` ?

2023-10-12 03:49 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/domains/CustomJSLib.java
> +    public Set<Map<String, String>> transformAccessor(Set<String> accessorSet) {
Can you please rename this method to `transformAccessorToSetOfMap` ?

2023-10-12 03:49 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/domains/CustomJSLib.java
> +                CustomJSLibCompatibilityDTO.transformAccessor(this.accessor, FieldName.MODIFIED_ACCESSOR_KEY));
Nit: Can you please write this as `transformAccessor(...)` and carry the class name to the import statement ?

2023-10-12 03:49 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration028ModifyingCustomJSLibSchema.java
> +public class Migration028ModifyingCustomJSLibSchema {
Can you please add a comment here explaining what this migration does ?

2023-10-12 03:49 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration029AddingXmlParserToApplicationLibraries.java
> +public class Migration029AddingXmlParserToApplicationLibraries {
Can you please add a comment here explaining what this migration does ?

2023-10-12 03:49 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration029AddingXmlParserToApplicationLibraries.java
> +    public static Criteria notDeleted() {
Can you please move it to `MigrationHelperMethods` class as a static method so that this may be re-used in future ?

2023-10-12 03:49 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
> +    private Mono<List<CustomJSLibApplicationDTO>> getCustomJslibImportMono(
Hi @sondermanish @arunvjn , not related to the code - general request to test once with all the import / export scenarios (with file, with git, import / export on different installations) if not already done.

2023-10-12 03:49 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
> +    private void ensureCustomJSLibHasXmlParser(List<CustomJSLibCompatibilityDTO> customJSLibList) {
Can you please add a comment explaining why this method is required ?

2023-10-13 12:18 UTC, arunvjn commented
Changes are tracked here https://github.com/appsmithorg/appsmith/pull/28012

2023-10-13 12:18 UTC, closed without merging