feat: WDS icon button widget integration
appsmithorg/appsmith pull request #27928
Opened 2023-10-10 23:31 UTC by dhruvikn

## Description
> Add a TL;DR when description is extra long (helps content team)
>
> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change
>
> Links to Notion, Figma or any other documents that might be relevant to the PR
>
>
#### PR fixes following issue(s)
Fixes #27538
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
#### Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video
>
>
#### Type of change
> Please delete options that are not relevant.
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
## Testing
>
#### How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Also list any relevant details for your test configuration.
> Delete anything that is not relevant
- [ ] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-10-10 23:32 UTC, dhruvikn commented
/build-deploy-preview skip-tests=true

2023-10-11 19:33 UTC, KelvinOm requested changes
Please check how visible and disabled properties work. How button is deployed as well. I also see something wrong with the color. For same color in the app and in storybook there is a different result.

2023-10-11 19:33 UTC, KelvinOm commented on app/client/src/widgets/wds/WDSCheckboxWidget/widget/index.tsx
> +import * as config from "./../config";
let's import each config directly this makes our code bit clear. Like this:
```
import {
  metaConfig,
  settersConfig,
  methodsConfig,
  defaultsConfig,
  featuresConfig,
  autocompleteConfig,
  propertyPaneContentConfig,
} from "../config";
```

2023-10-11 19:33 UTC, KelvinOm commented on app/client/src/widgets/wds/WDSCheckboxWidget/widget/types.ts
> +export interface CheckboxWidgetProps extends WidgetProps {
Can we extends from component interface here?

2023-10-11 19:33 UTC, KelvinOm commented on app/client/src/widgets/wds/WDSIconButtonWidget/component/index.tsx
> +export default IconButtonComponent;
Let's avoid default exports. https://google.github.io/styleguide/tsguide.html#exports

2023-10-11 19:33 UTC, KelvinOm commented on app/client/src/widgets/wds/WDSIconButtonWidget/config/autoLayoutConfig.ts
> +export const autoLayoutConfig = {
@jsartisan did you manage to get rid of this config? Can we delete it?

2023-10-11 19:33 UTC, KelvinOm commented on app/client/src/widgets/wds/WDSCheckboxWidget/widget/index.tsx
> +import * as config from "./../config";
same in `app/client/src/widgets/wds/WDSIconButtonWidget/widget/index.tsx`

2023-10-13 07:14 UTC, jsartisan commented on app/client/src/widgets/wds/WDSIconButtonWidget/config/autoLayoutConfig.ts
> +export const autoLayoutConfig = {
In the checkbox widget, i just returned an empty auto layout config like this. we can delete it.
![CleanShot 2023-10-13 at 12 43 40](https://github.com/appsmithorg/appsmith/assets/6636360/087ae774-e694-4397-ad3e-ea37987dade5)

2023-10-13 07:15 UTC, dhruvikn commented on app/client/src/widgets/wds/WDSIconButtonWidget/config/autoLayoutConfig.ts
> +export const autoLayoutConfig = {
Cool

2023-10-13 08:35 UTC, dhruvikn commented on app/client/src/widgets/wds/WDSCheckboxWidget/config/settersConfig.ts
> +export const settersConfig = {
Updated here - https://www.notion.so/appsmith/Widget-Development-Style-Guide-e97444305a6e48a39e3ce1a87d5e436c?pvs=4#b2d913cfd1aa435aa31ea0571224c324

2023-10-13 08:36 UTC, dhruvikn commented on app/client/src/widgets/wds/WDSIconButtonWidget/widget/types.ts
> +export interface IconButtonWidgetProps extends WidgetProps {
@KelvinOm - why do you think we should extend the component props here instead of WidgetProps.

2023-10-13 09:46 UTC, KelvinOm submitted a review, later dismissed

2023-10-13 09:46 UTC, KelvinOm commented on app/client/packages/design-system/widgets/src/components/Tooltip/src/Tooltip.tsx
> +  if (tooltip == null || tooltip == undefined || tooltip == "") return children;
(nitpick) You can write just `if (!Boolean(tooltip)) return children;`

Such a string `tooltip == null || tooltip == undefined` does not make a lot of sense since such string `tooltip == null` it already checks nullable values and equal to `tooltip === null || tooltip === undefined`.

2023-10-13 09:46 UTC, KelvinOm commented on app/client/src/widgets/wds/WDSIconButtonWidget/widget/types.ts
> +export interface IconButtonWidgetProps extends WidgetProps {
Yes. The props in the widget must be aligned with the props in the component.

2023-10-16 07:09 UTC, dhruvikn commented
/ok-to-test

2023-10-16 07:09 UTC, dhruvikn commented
/build-deploy-preview skip-tests=true

2023-10-16 08:16 UTC, KelvinOm submitted a review, later dismissed

2023-10-17 07:59 UTC, dhruvikn commented
/ok-to-test

2023-10-18 07:54 UTC, shadabbuchh commented
Bugs in this PR:

1. On DnD ing the widget icon color is incorrect & we can see it change when we switch to the `Style` tab.

https://github.com/appsmithorg/appsmith/assets/39921438/57498871-2608-4275-bf6c-108b354659db

2. The icon looks too big & the body of the icon button does not occupy all the space within the height/width handles on DnD. (Refer the above video).
3. Shouldn't the color of the icon button (& all widgets in general) change when it is disabled?
4. When we enter the `Button variant` starting with upper case letter, it throws an error. Same goes for `Button color` prop as well.

https://github.com/appsmithorg/appsmith/assets/39921438/785344af-9494-4fc0-92ff-29daca649e0f

2023-10-19 06:15 UTC, dhruvikn commented
@shadabbuchh  - 

> 1. On DnD ing the widget icon color is incorrect & we can see it change when we switch to the `Style` tab.

This is a known bug where blueprint's css is overriding. @albinAppsmith is aware of this.
 
> 2. The icon looks too big & the body of the icon button does not occupy all the space within the height/width handles on DnD. (Refer the above video).

I can see the same behavior with the button widget for now. I'll create a new issue and we'll track this there. Will update the link here.

> 3. Shouldn't the color of the icon button (& all widgets in general) change when it is disabled?

It does on my end. I'm not sure if I got what you mean.

![CleanShot 2023-10-19 at 11 42 20@2x](https://github.com/appsmithorg/appsmith/assets/22471214/42c77368-7409-4cec-b704-6d77d24becf3)

> 4. When we enter the `Button variant` starting with upper case letter, it throws an error. Same goes for `Button color` prop as well.

I feel this is a valid error as we have given the expected values list. What do you think @KelvinOm @jsartisan? 

![CleanShot 2023-10-19 at 11 43 50@2x](https://github.com/appsmithorg/appsmith/assets/22471214/95bde1c8-2123-4c27-a1cd-1fabdaa7d676)

2023-10-20 06:30 UTC, dhruvikn commented
@KelvinOm @jsartisan, need your thoughts here. 

> 4. When we enter the `Button variant` starting with upper case letter, it throws an error. Same goes for `Button color` prop as well.
> I feel this is a valid error as we have given the expected values list. What do you think @KelvinOm @jsartisan? 
> ![CleanShot 2023-10-19 at 11 43 50@2x](https://github.com/appsmithorg/appsmith/assets/22471214/95bde1c8-2123-4c27-a1cd-1fabdaa7d676)

Me and @shadabbuchh were discussing this callout when we realized that we needed to take a stand on this. While Shadab was testing the text widget he noticed that some properties' expected structure (such as text color) was showing just `string` in allowed values. We need to be consistent here. My take on this would be to show the user the list of allowed values in the expected structure like we are doing below and keep this field case-sensitive.

2023-10-20 11:43 UTC, dhruvikn commented
> We can leave everything as it is.

 Yep, let's leave it for now.

> But we can also make the user's life a bit easier and programmatically make the string lowercase. I.e., everything remains as it is in the input, but we send the correct prop to the component.

We can do this for sure, however, I think let's just stick to this being case-sensitive. The expected structure clearly defines what values are expected. If we were to make fields like these case-insensitive, we would also need to update the expected structure to all possible combinations or convey in some way that the field is case-insensitive. I might be overthinking here. 😅 @ichik penny for your thoughts?

2023-10-20 13:35 UTC, ichik commented
@dhruvikn as long as the autocomplete works / correct case is clearly shown I don't think there's genuine need to normalize user input.

2023-10-20 15:03 UTC, dhruvikn commented
/ok-to-test

2023-10-23 07:52 UTC, dhruvikn commented
/ok-to-test

2023-10-23 14:05 UTC, KelvinOm approved these changes

2023-10-23 16:21 UTC, merged