chore: action editors refactor
appsmithorg/appsmith pull request #27972
Opened 2023-10-11 13:56 UTC by ashit-rath

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.
>
## Description
> Add a TL;DR when description is extra long (helps content team)
>
> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change
>
> Links to Notion, Figma or any other documents that might be relevant to the PR
>
>
#### PR fixes following issue(s)
Fixes # (issue number)
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
#### Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video
>
>
#### Type of change
> Please delete options that are not relevant.
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
## Testing
>
#### How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Also list any relevant details for your test configuration.
> Delete anything that is not relevant
- [ ] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-10-12 05:51 UTC, ashit-rath commented
/ok-to-test

2023-10-12 10:49 UTC, ashit-rath commented
/build-deploy-preview skip-tests=true

2023-10-13 13:34 UTC, ashit-rath commented
/ok-to-test

2023-10-13 13:34 UTC, ashit-rath commented
/build-deploy-preview skip-tests=true

2023-10-13 13:47 UTC, ashit-rath commented
/ok-to-test

2023-10-16 02:28 UTC, ashit-rath commented
/ok-to-test

2023-10-16 05:05 UTC, ayushpahwa requested changes

2023-10-16 05:05 UTC, ayushpahwa commented on app/client/src/pages/Editor/APIEditor/index.tsx
> +import Editor from "./Editor";
Do you think we should maybe give all the editors more descriptive names so it is easier to find? Just an opinion.

2023-10-16 05:05 UTC, ayushpahwa commented on app/client/src/pages/Editor/APIEditor/index.tsx
> +import Editor from "./Editor";
Since all the new editors have the same name.

2023-10-16 05:05 UTC, ayushpahwa commented on app/client/src/pages/Editor/APIEditor/index.tsx
> +  const isFeatureEnabled = useFeatureFlag(FEATURE_FLAG.license_gac_enabled);
Which feature is this?

2023-10-16 05:23 UTC, ashit-rath commented on app/client/src/pages/Editor/APIEditor/index.tsx
> +  const isFeatureEnabled = useFeatureFlag(FEATURE_FLAG.license_gac_enabled);
This is part of the `<MoreActionsMenu>` component which was extracted out from the `CommonEditorForm` [here](https://github.com/appsmithorg/appsmith/blob/release/app/client/src/pages/Editor/APIEditor/CommonEditorForm.tsx#L545). This is existing code that I just refactored, haven't introduced anything new

2023-10-16 05:23 UTC, ashit-rath commented on app/client/src/components/editorComponents/ActionNameEditor.tsx
> +      dispatchAction={props.saveActionName || saveActionName}
Sure

2023-10-16 05:26 UTC, ashit-rath commented on app/client/src/pages/Editor/APIEditor/index.tsx
> +import Editor from "./Editor";
Since these are the primary entry Editor component so I named them as Editor so the path would come like `APIEditor/Editor`. The concern is valid and we can call this editor as APIEditor but the path would be `APIEditor/APIEditor`. What would you suggest the naming convention should be here?

2023-10-16 06:20 UTC, ayushpahwa commented on app/client/src/pages/Editor/APIEditor/index.tsx
> +  const isFeatureEnabled = useFeatureFlag(FEATURE_FLAG.license_gac_enabled);
Understood, thanks for the info

2023-10-16 06:22 UTC, ayushpahwa commented on app/client/src/pages/Editor/APIEditor/index.tsx
> +import Editor from "./Editor";
Yeah, I am myself not sure how to tackle this. But I am guessing we can consider it same way we do for index.tsx files. Closing it for now.

2023-10-16 06:23 UTC, ayushpahwa approved these changes

2023-10-16 06:29 UTC, ashit-rath commented
/ok-to-test

2023-10-16 06:29 UTC, ashit-rath commented
/build-deploy-preview skip-tests=true

2023-10-16 07:27 UTC, ashit-rath commented
/ok-to-test

2023-10-16 13:52 UTC, ashit-rath commented
/ok-to-test

2023-10-16 15:27 UTC, ashit-rath commented
/ok-to-test

2023-10-17 05:23 UTC, ayushpahwa approved these changes

2023-10-17 05:23 UTC, merged