Updates json input from typing to value setting
appsmithorg/appsmith pull request #2805
Opened 2021-02-01 16:00 UTC by osis

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.

## Description

Fixes https://github.com/appsmithorg/appsmith/issues/2804
Also, makes writing tests on this particular suite much quicker.

## Type of change

> Please delete options that are not relevant.

- Breaking change (fix or feature that would cause existing functionality to not work as expected)?

## How Has This Been Tested?

Running the test suite multiple times. Notice a speed increase from 20-30 seconds down to 5 per run for the Table display tests.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-02-02 04:50 UTC, hetunandu approved these changes

2021-02-02 04:54 UTC, hetunandu requested changes
This is a very useful PR! Seems to be working well but there is one issue.
If you look at this test `Smoke_TestSuite/ActionExecution/ExecutionParams_spec.js`
It relies on typing and auto closing of brackets in the code editor input and hence the test fails. This needs to be fixed as well.

2021-02-05 00:19 UTC, osis commented
Hmmmm I'll take a closer look. Thanks for the heads up!

2021-02-22 06:49 UTC, hetunandu commented
Hey @osis are you still working on this? This was a nice contribution we would like to merge but this the breaking test is a blocker

2021-02-22 13:10 UTC, osis commented
Sorry! Got bogged down with other projects. Will push this through tonight.

2021-03-03 05:04 UTC, hetunandu approved these changes

2021-03-03 05:04 UTC, merged

2021-03-03 05:05 UTC, hetunandu commented
Thanks for this awesome contribution @osis You rock 🤘

2021-03-03 05:06 UTC, hetunandu commented
@all-contributors please add @osis as a code and tests contributor

2021-03-03 05:12 UTC, hetunandu commented
@all-contributors please add @osis as a code and tests contributor