fix: exported datasource only sensitive fields set as null
appsmithorg/appsmith pull request #28146
Opened 2023-10-17 08:06 UTC by NilanshBansal

## Description
> This PR only sets the sensitive fields in datasource reconnection modal as null. 
Ref: https://www.notion.so/Datasource-Configuration-on-Exporting-App-924d18f1b0ec4451a482bc41d7271721

#### PR fixes following issue(s)
Fixes #20545 

#### Type of change
- Bug fix (non-breaking change which fixes an issue)

## Testing
>
#### How Has This Been Tested?
- [x] Manual
- [x] JUnit

#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-10-18 04:13 UTC, rahulbarwal commented
/build-deploy-preview

2023-10-18 04:47 UTC, sumitsum submitted a review, later dismissed

2023-10-18 04:50 UTC, AnaghHegde requested changes
Please verify the behaviour on git with multiple instances

2023-10-18 18:50 UTC, NilanshBansal commented
/ok-to-test

2023-10-18 18:50 UTC, NilanshBansal commented
/build-deploy-preview skip-tests=true recreate=true

2023-10-19 07:21 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/datasources/export/DatasourceExportableServiceCEImpl.java
> +    private void resetSensitiveFields(DatasourceStorage datasourceStorage) {
Can you change the name remove instead of reset?

2023-10-19 07:21 UTC, AnaghHegde requested changes
Minor nit, rest looks good.

2023-10-19 07:46 UTC, NilanshBansal commented
/ok-to-test

2023-10-19 09:57 UTC, AnaghHegde approved these changes

2023-10-19 10:37 UTC, merged