feat: manage env code split
appsmithorg/appsmith pull request #28215
Opened 2023-10-19 06:29 UTC by ayushpahwa

Coed split PR for custom environments [EE PR](https://github.com/appsmithorg/appsmith-ee/pull/2207)

2023-10-19 06:36 UTC, ankitakinger commented on app/client/src/ee/pages/Applications/WorkspaceMenu.tsx
> +export const EEWorkspaceMenuItems = ({}: { workspaceId: string }) => {
why is this required?

2023-10-19 06:38 UTC, ankitakinger commented on app/client/src/pages/workspace/settings.tsx
> +        <WorkspaceSettingsTabs
Could you handle the 3rd tab scenario in `shouldRedirect` inside this component?

Also, could we please test this out with GAC on EE? Considering when members tab should be visible, when none of the tabs have access so it should redirect? Also, if you manually type the URL you don't have access to, then that should redirect to homepage.

2023-10-23 13:17 UTC, ankitakinger commented on app/client/src/ee/pages/Applications/ManageEnvironmentsMenu.tsx
> +const ManageEnvironmentsMenu = ({}: { workspaceId: string }) => {
can this be split and added to `ce` folder with null?

2023-10-30 15:30 UTC, ayushpahwa commented
/ok-to-test

2023-10-30 16:24 UTC, ankitakinger commented
/build-deploy-preview skip-tests=true

2023-10-30 16:46 UTC, ankitakinger commented on app/client/src/ce/pages/workspace/Members.tsx
> +    height: 100%;
why exactly did we remove this for all tabs which was by default done earlier and added it separately for each tab?

2023-10-30 16:49 UTC, ankitakinger commented on app/client/src/ce/pages/workspace/Members.tsx
> +    height: 100%;
I feel this was better handled earlier because now each tab including the new one you added needs to handle this scrolling separately.

2023-10-30 16:50 UTC, ankitakinger requested changes
Added a comment on Members component. Please look at it.

2023-10-30 17:07 UTC, AmanAgarwal041 commented on app/client/src/pages/workspace/settings.tsx
> +      text: "Documentation",
Can we use `DOCUMENTATION` from message.ts file for text value here ?

2023-11-06 10:05 UTC, ayushpahwa commented
/ok-to-test

2023-11-06 10:47 UTC, ayushpahwa commented
Testing completed at EE PR. https://github.com/appsmithorg/appsmith-ee/pull/2209#issuecomment-1794541293

2023-11-06 18:38 UTC, ankitakinger approved these changes

2023-11-07 06:34 UTC, merged