feat: rate limiting added for connection creation during query execution
appsmithorg/appsmith pull request #28260
Opened 2023-10-20 07:29 UTC by sneha122

## Description

This PR adds rate limiting on connection creations. Connections with datasources are created in following situations:
- Whenever a query is executed, we create connection to datasource
- Whenever datasource structure is fetched
- Whenever trigger API is called in case of generate CRUD

In all above cases, if connection is successful, its context is saved in cache, but when the connection is unsuccessful, connection context is not saved in cache and connection creation is initiated every time. In such case, we need to apply rate limiting on connection creation, so that no brute force attacks can happen.

The code in this PR is written with the assumption that every time connection creation fails, each plugin throws an error, whenever we get this error, we consume token from bucket, if we exhaust this bucket, we block this IP for next 5 minutes. This error is thrown in following plugins:
- Postgres
- Oracle
- Redshift
- MsSQL

Other plugins like MySQL, SMTP, Elastic Search, ArangoDB, Redis, No such error is thrown, which can be caught and rate limiting applied, hence creating a different task to handle for these plugins. check #28259

Junit test cases will be covered in #27742 

#### PR fixes following issue(s)
Fixes #27738 , #27740 
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
#### Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video
>
>
#### Type of change
- New feature (non-breaking change which adds functionality)
>
>
>
## Testing
>
#### How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Also list any relevant details for your test configuration.
> Delete anything that is not relevant
- [x] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-10-23 10:26 UTC, sneha122 commented
/ok-to-test

2023-10-23 10:47 UTC, sumitsum requested changes

2023-10-23 10:47 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceContextServiceCEImpl.java
> +                .flatMap(isBlocked -> {
Hi Sneha, should this check be put after the following if else clause: 
```
if (datasourceId == null) {
            log.debug(
                    "This is a dry run or an embedded datasourceStorage. The datasourceStorage context would not exist in this "
                            + "scenario");
        } else {
            if (isValidDatasourceContextAvailable(datasourceStorage, datasourceContextIdentifier)) {
                log.debug("Resource context exists. Returning the same.");
                return Mono.just(datasourceContextMap.get(datasourceContextIdentifier));
            }
        }
```
This clause returns a valid connection if it already exists. If not, then the next line creates a new connection via `createNewDatasourceContext` - i.e. should the check be placed just before this line ?

2023-10-23 10:47 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceContextServiceCEImpl.java
> +                        return createNewDatasourceContext(datasourceStorage, datasourceContextIdentifier)
QQ: what happens for MySQL when connection fails ?

2023-10-23 10:47 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceContextServiceCEImpl.java
> +                                .flatMap(datasourceContext -> {
Is this line required ? 
`.flatMap(datasourceContext -> Mono.just(datasourceContext)` ?

2023-10-23 10:47 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceContextServiceCEImpl.java
> +                                                Boolean isSuccessful = tuple.getT1();
Can you please rename this to `wasTokenAvailable` ?

2023-10-23 12:37 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceContextServiceCEImpl.java
> +                                                if (!isSuccessful) {
The code block seems duplicate with the test datsource flow ? Can we refactor it into a common method for both ?

2023-10-23 12:39 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceContextServiceCEImpl.java
> +                .isEndpointBlockedForConnectionRequest(datasourceStorage)
Can you please add a comment here explaining (1)  the concept of rate limit (2) what plugins it would apply to right now and why it wouldn't work with other plugins (i.e. the connection pool issue).

2023-10-23 13:40 UTC, sneha122 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceContextServiceCEImpl.java
> +                        return createNewDatasourceContext(datasourceStorage, datasourceContextIdentifier)
In case of mysql, connection pool is created. We should handle that case separately as discussed

2023-10-24 09:25 UTC, sneha122 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceContextServiceCEImpl.java
> +                                                if (!isSuccessful) {
I have tried to refactor common code as much as possible in the recent commit, please check and let me know if further refactoring is required or not.

2023-10-24 09:25 UTC, sneha122 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceContextServiceCEImpl.java
> +                    if (isBlocked) {
I have tried to refactor common code as much as possible in the recent commit, please check and let me know if further refactoring is required or not.

2023-10-25 07:48 UTC, sumitsum requested changes

2023-10-25 07:48 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceContextServiceCEImpl.java
> +        // Instead of connection, connection pool is created, connection is created when we query execution happens
Minor correction here - for the plugins that return error, they may also be using connection pool - the difference being that in their case the connection pool is trying to establish connection right away vs in other cases where the connection pool attempts to create a connection only when the first query is run.

2023-10-25 09:14 UTC, sneha122 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/datasources/base/DatasourceServiceCEImpl.java
> +                                                            .flatMap(isAdded -> Mono.just(tooManyRequests))
So this function essentially adds a key in the redis with timeout and returns a Mono boolean, two things can happen here:
- Key is already present -> in this case we are throwing an error with too many requests from RedisUtils itself
- Key is absent -> we add the key and true is returned

I dont see a case where isAdded would be false, maybe in a case where the redis set operation itself fails due to connection or any other issue, in that case also we would need to return too many requests right or should we return the actual error to user (I feel actual error would be useless from user's perspective) and sending it as too many requests makes sense. Let me know what you think

2023-10-25 09:16 UTC, sneha122 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/datasources/base/DatasourceServiceCEImpl.java
> +                                                            .onErrorResume(error -> Mono.just(tooManyRequests));
But again sending that error to user, will it make sense for user to see such error? Error occurred due to our flow of rate limiting blockage?

2023-10-25 10:14 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/datasources/base/DatasourceServiceCEImpl.java
> +                                                            .onErrorResume(error -> Mono.just(tooManyRequests));
@sneha122 I think it would be good to do so, because then the user may report that issue to us or it may get logged via analytics - both of which may get lost if we mask the error.

2023-10-25 10:15 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/datasources/base/DatasourceServiceCEImpl.java
> +                                                            .flatMap(isAdded -> Mono.just(tooManyRequests))
Regardign `in that case also we would need to return too many requests right or should we return the actual error to user (I feel actual error would be useless from user's perspective) ` - I think it would be good to return the actual error, because then the user may report that issue to us or it may get logged via analytics - both of which may get lost if we mask the error.

2023-10-25 10:29 UTC, sneha122 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/datasources/base/DatasourceServiceCEImpl.java
> +                                                            .flatMap(isAdded -> Mono.just(tooManyRequests))
Makes sense, will make those changes, in case of false, no error would be thrown, so should we create a custom error for this? something like BLOCKING_FAILED?

2023-10-25 10:29 UTC, sneha122 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/datasources/base/DatasourceServiceCEImpl.java
> +                                                            .onErrorResume(error -> Mono.just(tooManyRequests));
Makes sense, will add it

2023-10-25 14:27 UTC, sumitsum requested changes

2023-10-25 14:27 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/exceptions/AppsmithError.java
> +            200,
QQ: why is the error code set to 200 ? Doesn't 200 stand for all ok ?

2023-10-26 05:49 UTC, sneha122 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/exceptions/AppsmithError.java
> +            200,
In case test and connection both, even though code is different the API says 200 and in the list of invalids, we get the error, so thought of keeping 200 itself

2023-10-26 06:16 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/exceptions/AppsmithError.java
> +            200,
Hi Sneha, can you please change the code ? This could be confusing to understand in future.

2023-10-26 06:26 UTC, sumitsum submitted a review, later dismissed

2023-10-26 09:28 UTC, sneha122 commented
/build-deploy-preview

2023-10-26 09:28 UTC, sneha122 commented
/ok-to-test

2023-10-27 00:49 UTC, sumitsum approved these changes

2023-10-27 04:55 UTC, chandannkumar commented
/build-deploy-preview skip-tests=true

2023-10-30 04:52 UTC, chandannkumar commented
Tested this PR and LGTM
- Tested for following Datasources 
Postgres
Oracle
Redshift
MsSQL
- Tested with Read/write and other connection types

2023-10-30 05:43 UTC, sneha122 commented
/ok-to-test

2023-10-30 10:30 UTC, sneha122 commented
/ok-to-test

2023-10-31 05:30 UTC, sumitsum approved these changes

2023-10-31 05:32 UTC, merged