chore: Adds logs messages for detailed debugging.
appsmithorg/appsmith pull request #28303
Opened 2023-10-23 11:58 UTC by rahulbarwal

## Description
This PR adds log messages to community templates publish flow to help erratic failures 

#### PR fixes following issue(s)
Fixes # (issue number)
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
#### Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video
>
>
#### Type of change
> Please delete options that are not relevant.
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
## Testing
>
#### How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Also list any relevant details for your test configuration.
> Delete anything that is not relevant
- [ ] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-10-23 11:58 UTC, rahulbarwal commented
/ok-to-test

2023-10-23 14:04 UTC, AnaghHegde requested changes
Nit - Can you please update the PR with meaningful information? And you can remove any section if it does not make sense. Thanks :)

2023-10-23 14:04 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationTemplateServiceCEImpl.java
> +                    log.info("CommunityTemplatePublish [{}] 2. uploaded to CS", resource.getApplicationId());
We need to handle the error from the CS API to get meaningful logs. Please add error handler in the the method `uploadCommunityTemplateToCS`

Refer this - https://github.com/appsmithorg/appsmith/blob/8b5269fef1f7a108e436bbf4ecf0d13e345877dc/app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationTemplateServiceCEImpl.java#L354

2023-10-24 07:11 UTC, rahulbarwal commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationTemplateServiceCEImpl.java
> +                .onErrorResume(WebClientResponseException.class, ex -> Mono.error(ex));
@AnaghHegde would this be sufficient to handle errors?

2023-10-24 07:12 UTC, rahulbarwal commented
/ok-to-test

2023-10-25 09:42 UTC, rahulbarwal commented
This PR is not required anymore. This https://github.com/appsmithorg/appsmith/pull/28347 handles it.

2023-10-25 09:42 UTC, closed without merging