fix: Move widget name overlay to WidgetsEditor
appsmithorg/appsmith pull request #28306
Opened 2023-10-23 13:49 UTC by riodeuno

## Description
- The first widget name in anvil was being cut-off due to the fact that the DOM grandparent of the widget name overlay canvas was not allowing children to be visible beyond bounds.
- In this PR, the widget name overlay canvas renders in the WidgetsEditor (earlier grandparent now parent) instead of MainContainerWrapper (earlier parent now sibling)
- Also, this PR removes the dependency on refs by the widget name overlay canvas

#### PR fixes following issue(s)
Fixes #28304

#### Type of change
- Bug fix (non-breaking change which fixes an issue)

## Testing
#### How Has This Been Tested?
- [x] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress 

## Checklist:
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-10-23 15:31 UTC, riodeuno commented
/ok-to-test

2023-10-24 00:44 UTC, prsidhu commented
@riodeuno WidgetNameComponent doesn't disappear on scroll and hence stays visible at an incorrect position, until re-draw is forced by focusing or selecting a widegt.

https://github.com/appsmithorg/appsmith/assets/5424788/8be5ca63-b8b5-455b-bdce-fb5a0de48796

2023-10-24 04:43 UTC, marks0351 requested changes

2023-10-24 04:43 UTC, marks0351 commented on app/client/src/layoutSystems/common/WidgetNamesCanvas/WidgetNameConstants.ts
> -  top: 0,
can we pls use the widget name height as a constant and use it here.

2023-10-24 10:48 UTC, riodeuno commented
@prsidhu The issue was that the scroll parent had changed. I've changed the scroll parent to be the WidgetsEditor.

2023-10-24 10:49 UTC, riodeuno commented
/ok-to-test

2023-10-24 12:22 UTC, riodeuno commented
/ok-to-test

2023-10-24 14:30 UTC, prsidhu approved these changes

2023-10-24 14:40 UTC, merged