New relic test
appsmithorg/appsmith pull request #28480
Opened 2023-10-30 12:43 UTC by vsvamsi1

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.
>
## Description
> Add a TL;DR when description is extra long (helps content team)
>
> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change
>
> Links to Notion, Figma or any other documents that might be relevant to the PR
>
>
#### PR fixes following issue(s)
Fixes # (issue number)
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
#### Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video
>
>
#### Type of change
> Please delete options that are not relevant.
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
## Testing
>
#### How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Also list any relevant details for your test configuration.
> Delete anything that is not relevant
- [ ] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-10-30 12:43 UTC, vsvamsi1 commented
/build-deploy-preview skip-tests=true

2023-10-31 07:23 UTC, vsvamsi1 commented
/build-deploy-preview skip-tests=true

2023-10-31 07:45 UTC, vsvamsi1 commented
/build-deploy-preview skip-tests=true

2023-11-01 12:10 UTC, vsvamsi1 commented
/build-deploy-preview skip-tests=true

2023-11-01 19:30 UTC, vsvamsi1 commented
/build-deploy-preview skip-tests=true

2023-11-01 19:47 UTC, vsvamsi1 commented
/build-deploy-preview skip-tests=true

2023-11-01 20:14 UTC, vsvamsi1 commented
/build-deploy-preview skip-tests=true

2023-11-01 20:42 UTC, vsvamsi1 commented
/build-deploy-preview skip-tests=true

2023-11-02 07:31 UTC, vsvamsi1 commented
/build-deploy-preview skip-tests=true

2023-11-02 08:38 UTC, SatishGandham commented on app/client/src/newRelicBrowserAgent.js
> +;NREUM.loader_config={accountID:newRelicAccountId,trustKey:newRelicAccountId,agentID:newRelicApplicationId,licenseKey:newRelicLicenseKey,applicationID:newRelicApplicationId};
This is an IIFE, why are you wrapping this in a function call?

2023-11-02 11:59 UTC, vsvamsi1 commented
/build-deploy-preview skip-tests=true

2023-11-02 12:01 UTC, vsvamsi1 commented on app/client/src/newRelicBrowserAgent.js
> +;NREUM.loader_config={accountID:newRelicAccountId,trustKey:newRelicAccountId,agentID:newRelicApplicationId,licenseKey:newRelicLicenseKey,applicationID:newRelicApplicationId};
Sure removed the wrapping function

2023-11-02 12:36 UTC, SatishGandham commented on app/client/src/index.tsx
> +      await import(
Can we load these two in parallel.

2023-11-02 12:38 UTC, SatishGandham requested changes
Please load OTLP and web vitals scripts in parallel.

2023-11-02 12:53 UTC, vsvamsi1 commented
/build-deploy-preview skip-tests=true

2023-11-02 13:17 UTC, vsvamsi1 commented
/build-deploy-preview skip-tests=true

2023-11-02 13:18 UTC, SatishGandham submitted a review, later dismissed

2023-11-03 05:16 UTC, vsvamsi1 commented
/build-deploy-preview skip-tests=true

2023-11-03 05:18 UTC, rajatagrawal approved these changes

2023-11-03 12:25 UTC, vsvamsi1 commented
/build-deploy-preview skip-tests=true

2023-11-03 12:50 UTC, vsvamsi1 commented
/build-deploy-preview skip-tests=true

2023-11-03 17:35 UTC, vsvamsi1 commented
/build-deploy-preview skip-tests=true

2023-11-03 18:59 UTC, vsvamsi1 commented
/ok-to-test sha=6b7ce8ee0ae79e96b78cdfea3965a530c9aeaecd

2023-11-04 02:25 UTC, rajatagrawal commented on app/client/public/index.html
> +        const enableNewRelic = true;
is this intended or it is supposed to be enabled for only cloud installations ?

2023-11-04 03:59 UTC, vsvamsi1 commented on app/client/public/index.html
> +        const enableNewRelic = true;
I have checked this in temporary to test if the CDN agent loads or not.  Its always based on the enable flag.

2023-11-04 04:00 UTC, vsvamsi1 commented
/build-deploy-preview skip-tests=true

2023-11-04 04:01 UTC, vsvamsi1 commented
/ok-to-test sha=c6f00231fc9f4d46d219f6d7ebf0383959cc1174

2023-11-04 04:03 UTC, vsvamsi1 commented
/build-deploy-preview skip-tests=true

2023-11-04 04:04 UTC, vsvamsi1 commented
/ok-to-test sha=e060f609bd516ce4e8003a9765efc120a9cda1f1

2023-11-04 06:05 UTC, rajatagrawal commented on app/client/src/auto-otel-web.js
> +const NEW_RELIC_OTLP_ENDPOINT = "https://otlp.nr-data.net:4318";
@vsvamsi1 

I feel that we should move this url to environment variables too. Not sure if hard coding it here is appropriate even though it may be harmless.

@trishaanand Can you please share your viewpoints on this ?

2023-11-04 06:16 UTC, rajatagrawal commented on app/client/public/index.html
> +            BROWSER_AGENT && BROWSER_AGENT.init([accountId,applicationId,browserAgentlicenseKey]);
Can we please add a comment here that newRelicBrowserAgent file gets loaded in BROWSER_AGENT env varialble ?

Also can BROWSER_AGENT be renamed to NEW_RELIC_BROWSER_AGENT ?

2023-11-04 06:18 UTC, rajatagrawal commented on app/client/public/index.html
> +            BROWSER_AGENT && BROWSER_AGENT.init([accountId,applicationId,browserAgentlicenseKey]);
or something else which is easy to deciper what this variable would be for ?

2023-11-04 06:38 UTC, rajatagrawal commented on app/client/src/utils/WorkerUtil.ts
> +import { trace } from "@opentelemetry/api";
Let's add a wrapper for any telemetry api calls, like AppsmithTelemetry. We may like to switch from NewRelic to something else and the wrapper gives us that flexibility.

2023-11-04 07:23 UTC, rajatagrawal commented on app/client/src/utils/WorkerUtil.ts
> +import { trace } from "@opentelemetry/api";
This can be done in the next PR

2023-11-05 11:30 UTC, vsvamsi1 commented on app/client/src/utils/WorkerUtil.ts
> +import { trace } from "@opentelemetry/api";
This package is generic enough that can be applied to any telemetry applicaiton, the only changes we have to make is in [exporter configuration]([app/client/src/auto-otel-web.js](https://github.com/appsmithorg/appsmith/pull/28480/files/e060f609bd516ce4e8003a9765efc120a9cda1f1#diff-e25dc881e9bd83954cab3c1f13bec157de6d37ae1a16035236d545b5a6094825)). The URL of the traces collector and the service name are the only aspects we need to change when switching applications. I don't think wrapper is necessary, let me know ur thoughts on this @rajatagrawal ?

2023-11-05 11:59 UTC, vsvamsi1 commented on app/client/public/index.html
> +            BROWSER_AGENT && BROWSER_AGENT.init([accountId,applicationId,browserAgentlicenseKey]);
Sure, I have updated the CDN file and the source code here. Need to reupload the updated file to the CDN and test it out. Currently blocked at this step since i have to delete the original file from the cdn server.

2023-11-05 12:22 UTC, vsvamsi1 commented on app/client/src/auto-otel-web.js
> +const NEW_RELIC_OTLP_ENDPOINT = "https://otlp.nr-data.net:4318";
These values will be fairly static, the collector endpoint is not dynamic and is available in new relic's documentation in the public domain. Its the same endpoint all new relic users need to export their telemetry information to.

If its necessary I can still do this but there are several places i need to update these vars, which i do not have to access to and will take some time to test it out. Let me know if we can defer this @rajatagrawal @trishaanand for now?

2023-11-05 12:23 UTC, vsvamsi1 commented
/build-deploy-preview skip-tests=true

2023-11-05 12:23 UTC, vsvamsi1 commented
/ok-to-test sha=f2385dfda12cac8739c217aa708a9dca86bbdb33

2023-11-06 07:44 UTC, vsvamsi1 commented
/build-deploy-preview skip-tests=true

2023-11-06 07:45 UTC, vsvamsi1 commented
/ok-to-test sha=435dc942ce15c92068c918dcad26e48b31d316b1

2023-11-06 08:10 UTC, rajatagrawal approved these changes

2023-11-06 09:35 UTC, merged

2023-11-06 10:49 UTC, rajatagrawal commented on app/client/src/auto-otel-web.js
> +const NEW_RELIC_OTLP_ENDPOINT = "https://otlp.nr-data.net:4318";
cc : @sharat87 FYI

2023-11-06 10:50 UTC, rajatagrawal commented on app/client/src/auto-otel-web.js
> +const NEW_RELIC_OTLP_ENDPOINT = "https://otlp.nr-data.net:4318";
If it is a common url for everyone using newrelic to post their OTLP metrics to, I think that we can keep it in frontend code only then.

2023-11-06 11:07 UTC, sharat87 commented on app/client/src/auto-otel-web.js
> +const NEW_RELIC_OTLP_ENDPOINT = "https://otlp.nr-data.net:4318";
I'd prefer to hard-code this, especially if it's going to be the same for everyone. Overall, my stance for taking decisions on things like this, is fewer configurable parameters on the system means fewer combinations of configurations that we need to test. Basically convention over configuration. 🙂