fix: use optional permission for forking enabled apps
appsmithorg/appsmith pull request #28489
Opened 2023-10-31 05:16 UTC by AnaghHegde

## Description

#### PR fixes following issue(s)
Fixes https://github.com/appsmithorg/appsmith/issues/27509

#### Type of change
- Bug fix (non-breaking change which fixes an issue)

## Testing

- [ ] Manual
- [ ] JUnit

## Checklist:
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-10-31 05:18 UTC, rahulbarwal submitted a review, later dismissed
Code changes look fine. How do we test this in release?

2023-10-31 05:19 UTC, AnaghHegde commented
@rahulbarwal We can manually set the forking enabled flag to a few apps and then test this. I will build a DP and then we can test this there.

2023-10-31 05:19 UTC, AnaghHegde commented
/ok-to-test

2023-10-31 05:19 UTC, AnaghHegde commented
/build-deploy-preview

2023-10-31 06:43 UTC, nsarupr commented on app/server/appsmith-server/src/main/java/com/appsmith/server/fork/internal/ApplicationForkingServiceCEImpl.java
> +        Optional<AclPermission> optionalAclPermission = Optional.ofNullable(null);
Let's use `Optional.empty()` here.
But I still have a question, that since the permissions will be the same on all the Git Connected applications, how does adding a non-permission check help here?

2023-10-31 07:01 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/fork/internal/ApplicationForkingServiceCEImpl.java
> +        Optional<AclPermission> optionalAclPermission = Optional.ofNullable(null);
This only fails when the user tries to fork app in the view mode. Not from the home page

2023-11-01 06:02 UTC, AnaghHegde commented
/ok-to-test

2023-11-01 06:20 UTC, rahulbarwal commented on app/server/appsmith-server/src/main/java/com/appsmith/server/fork/internal/ApplicationForkingServiceCEImpl.java
> +                .defaultIfEmpty(Boolean.FALSE);
Is this enough to say that an app is a sample app?
I mean any normal app(whether public or not) can be a forkable right?

2023-11-01 06:22 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/fork/internal/ApplicationForkingServiceCEImpl.java
> +                .defaultIfEmpty(Boolean.FALSE);
Correct but this flag is not enabled on all apps. This needs to be set manually and only then it becomes forkable from the view mode. 
Else forking is a developer action which is done from home page only.

2023-11-01 07:14 UTC, rahulbarwal commented on app/server/appsmith-server/src/main/java/com/appsmith/server/fork/internal/ApplicationForkingServiceCEImpl.java
> +                .defaultIfEmpty(Boolean.FALSE);
![Screenshot 2023-11-01 at 12 43 41 PM](https://github.com/appsmithorg/appsmith/assets/6761673/86af45c0-4585-448f-9c0e-6fd028789a0a)


an app can be made forkable via settings as well.

2023-11-01 08:38 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/fork/internal/ApplicationForkingServiceCEImpl.java
> +                .defaultIfEmpty(Boolean.FALSE);
Didn't know this. I though forking is present by default for all apps.

2023-11-02 07:24 UTC, AnaghHegde commented
/ok-to-test

2023-11-02 17:23 UTC, nsarupr requested changes
Please add test cases to assert the changes.

2023-11-02 17:23 UTC, nsarupr commented on app/server/appsmith-server/src/main/java/com/appsmith/server/fork/internal/ApplicationForkingServiceCEImpl.java
> +                        AppsmithError.ACL_NO_RESOURCE_FOUND, FieldName.APPLICATION, srcApplicationId)))
Since here, we are not checking for permission, please throw a `NO_RESOURCE_FOUND` error, instead of `ACL_NO_RESOURCE_FOUND`.

2023-11-02 17:23 UTC, nsarupr commented on app/server/appsmith-server/src/main/java/com/appsmith/server/fork/internal/ApplicationForkingServiceCEImpl.java
> +                .map(application -> application.getForkingEnabled() != null && application.getForkingEnabled())
Can we replace this with `Boolean.TRUE.equals(application.getForkingEnabled()`?

2023-11-02 17:23 UTC, nsarupr commented on app/server/appsmith-server/src/main/java/com/appsmith/server/fork/internal/ApplicationForkingServiceCEImpl.java
> +
Please check for the edit permission on Application as well.

2023-11-02 17:42 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/fork/internal/ApplicationForkingServiceCEImpl.java
> +
That is already done on the application mono. Why do we want to do this again?

2023-11-03 06:08 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/fork/internal/ApplicationForkingServiceCEImpl.java
> +                .map(application -> application.getForkingEnabled() != null && application.getForkingEnabled())
Wouldn't this cause NPE?

2023-11-03 06:11 UTC, AnaghHegde commented
/ok-to-test

2023-11-06 05:09 UTC, AnaghHegde commented
/ok-to-test

2023-11-06 07:10 UTC, nsarupr approved these changes
Changes look good to me.

2023-11-06 10:11 UTC, merged