chore: integrate currency input widget
appsmithorg/appsmith pull request #28566
Opened 2023-11-02 05:39 UTC by jsartisan

Fixes #27747

2023-11-02 06:50 UTC, jsartisan commented on app/client/packages/design-system/headless/src/components/Field/src/Label.tsx
> -  | "necessityIndicator"
Note: this is part of the refactoring I had to do to make the component little simpler. We were previously defining the necessityIndicator and a few other properties in the styled version of the component. It was creating confusion why few properties are in headless and few in styled. Main reason for it was that we couldn't styled text using className but now we can use `getTypographyClassName` to style any text using className.
Now we are moving these properties back to headless and we are styling description and label with LabelClassName and HelptextClassName

2023-11-02 06:50 UTC, jsartisan commented on app/client/packages/design-system/widgets/src/components/TextArea/src/TextArea.tsx
> -  const wrappedDescription = Boolean(description) && (
This was the main reason of separating few props in styled version and few in this headless. previously we have to use the text component to style the label and description, so we needed to wrap them. But now we can style them using classNames. so this is not needed anymore.

2023-11-02 11:17 UTC, jsartisan commented
/ok-to-test

2023-11-06 11:33 UTC, KelvinOm requested changes
Decimals allowed — seems like it doesn't work.
Required — doesn't add a mandatory attribute `*`

Do not forget to enable `release_anvil_enabled ` flag for testing.

2023-11-09 07:54 UTC, dhruvikn commented
/build-deploy-preview skip-tests=true

2023-11-09 08:34 UTC, dhruvikn requested changes
Found some issues while testing the widget. 

1. The currency icon is getting overflowed. Select AED and resize to reproduce.

<video src="https://github.com/appsmithorg/appsmith/assets/22471214/17643055-f2e8-4e85-a336-33bd5f2972a8"></video>

2. Allow currency change property doesn't do anything in both edit and deploy mode. Tried changing the currency by clicking the icon but nothing happened. Am I missing anything here?

2023-11-10 06:49 UTC, jsartisan commented on app/client/packages/design-system/widgets/src/styles/src/text-input.module.css
> +    box-shadow: inset 0 0 0 1px var(--color-bd-neutral);
The input was looking bigger when placed next to a button. so used the inset box shadow.

2023-11-10 06:50 UTC, jsartisan commented on app/client/packages/design-system/widgets/src/components/TextInput/stories/TextInput.stories.mdx
> +    startIcon: $,
thanks for catching this. it was not wokring. fixed it.

2023-11-10 06:51 UTC, jsartisan commented on app/client/src/widgets/wds/WDSCurrencyInputWidget/widget/index.tsx
> +      isValid: `{{(()=>{${derivedProperties.isValid}})()}}`,
This is how it is designed.

2023-11-10 06:52 UTC, jsartisan commented on app/client/src/widgets/wds/WDSCurrencyInputWidget/component/types.ts
> +  onCurrencyChange: (code?: any) => void;
✅

2023-11-10 09:59 UTC, KelvinOm submitted a review, later dismissed
Code is LGTM. One question about UX.

Previously, we didn't allow to enter anything other than numbers and comma, now we can enter anything, but the value is reset obBlur event. Is this expected/acceptable behavior?


https://github.com/appsmithorg/appsmith/assets/11555074/6f46ef98-ca21-43ea-bbed-2e797c0b88be

cc @ichik

2023-11-10 10:23 UTC, ichik commented
It's better to show an error than to erase user's input.

2023-11-10 10:25 UTC, dhruvikn commented
/build-deploy-preview skip-tests=true

2023-11-10 10:33 UTC, ichik commented
Why do we list Euro for each individual country that uses it?
Also, please be aware that not every convention uses comma, some use point: https://en.wikipedia.org/wiki/Decimal_separator#Hindu–Arabic_numerals

2023-11-10 10:43 UTC, dhruvikn commented
> Why do we list Euro for each individual country that uses it? Also, please be aware that not every convention uses comma, some use point: [https://en.wikipedia.org/wiki/Decimal_separator#Hindu–Arabic_numerals](https://en.wikipedia.org/wiki/Decimal_separator#Hindu%E2%80%93Arabic_numerals)

If we are solving for this, I think it's also worth mentioning that the place values used in the Indian numeral system are different than the International numeral system. 

Example - 1000000 would be 10,00,000 in the Indian system and 1,000,000 in the international one.

![image](https://github.com/appsmithorg/appsmith/assets/22471214/75d27600-b7eb-4ea8-a881-7b99d8a01c38)

2023-11-10 10:56 UTC, ichik commented
Yes, there's a huge variety with digit grouping too, but at least that is done automatically and doesn't interfere with user's input / result in an error unlike the decimal.

2023-11-15 06:20 UTC, jsartisan commented
> Why do we list Euro for each individual country that uses it?
I am also not sure about why did this way.

> Also, please be aware that not every convention uses comma, some use point:
Yes, that is handled with Intl class ( https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl )

2023-11-15 06:21 UTC, jsartisan commented
>  If we are solving for this, I think it's also worth mentioning that the place values used in the Indian numeral system are different than the International numeral system.

Very good catch. The current implementation is not solving this. But let me create an issue for this to track.

2023-11-15 06:32 UTC, jsartisan commented
@dhruvikn added the issue here - https://github.com/appsmithorg/appsmith/issues/28862

2023-11-15 06:36 UTC, jsartisan commented
/ok-to-test

2023-11-15 08:03 UTC, jsartisan commented
/ok-to-test

2023-11-15 08:46 UTC, ichik commented
> Yes, that is handled with Intl class ( https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl )

That seems unreliable, could we instead allow both comma and period as valid input?

2023-11-15 09:56 UTC, jsartisan commented
> That seems unreliable, could we instead allow both comma and period as valid input?
It should depend on the language the user is using. Allowing both will just create confusion.

2023-11-15 10:05 UTC, ichik commented
> It should depend on the language the user is using. Allowing both will just create confusion.

That is very unreliable, subject to a combination of many OS and browser settings. It is very likely therefore to not match what the user is expecting. Allowing both would only create confusion if user is trying to do digit grouping manually, but at least would allow decimal input.

2023-11-15 10:14 UTC, jsartisan commented
I feel you are mixing two things, Language and Currency. How we show the currency should depend on the language user is using. 🤔
Currency is just an number but the period and comma representation are the part of the language.

2023-11-15 12:51 UTC, KelvinOm approved these changes

2023-11-15 12:57 UTC, merged