chore: Modified refactor flow to use entity specific services
appsmithorg/appsmith pull request #28621
Opened 2023-11-03 08:08 UTC by nidhi-nair

2023-11-03 13:37 UTC, subrata71 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/RefactorEntityNameDTO.java
> +    String newFullyQualifiedName;
If these fields are meant for internal use can ww add `@JsonView(Views.Internal.class)` annotation on those?

2023-11-03 13:38 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/actioncollections/refactors/ActionCollectionRefactoringServiceCEImpl.java
> +                        actionIds.putAll(branchedActionCollection.getDefaultToBranchedArchivedActionIdsMap());
I do not want to make logical changes in this PR. I'll create an issue for this so we can pick this up separately

2023-11-03 13:49 UTC, sondermanish commented on app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/RefactoringMetaDTO.java
> +    Mono<Integer> evalVersionMono;
QQ: why are we storing a mono? Could we not store base values, reason for this doubt is that having a mono wrapper essentially means that it would be a java only DTO?

2023-11-03 13:54 UTC, sondermanish commented on app/server/appsmith-server/src/main/java/com/appsmith/server/refactors/applications/RefactoringSolution.java
> +package com.appsmith.server.refactors.applications;
Package hierarchy is diff compared to (/newActions/refactors) or (actionCollection/refactors). is that intended

2023-11-03 14:01 UTC, sondermanish commented on app/server/appsmith-server/src/main/java/com/appsmith/server/actioncollections/refactors/ActionCollectionRefactoringServiceCEImpl.java
> +        return Mono.just(Boolean.TRUE);
To be modified later?

2023-11-03 14:05 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/RefactoringMetaDTO.java
> +    Mono<Integer> evalVersionMono;
It is meant to be a Java only DTO, for feature implementation flows only.

2023-11-03 14:06 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/actioncollections/refactors/ActionCollectionRefactoringServiceCEImpl.java
> +        return Mono.just(Boolean.TRUE);
The existing code surprisingly does not have validation rules for anything other than action names. So yes, we would need to modify this later. Kept it the same as existing logic to ensure this PR only maintains compatibility.

2023-11-03 14:07 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/refactors/applications/RefactoringSolution.java
> +package com.appsmith.server.refactors.applications;
Every feature in the new structure would have a package of its own and then every implementing entity would implement it in a sub-package. The `applications` path here is meant to allow some leeway in starting to think about how this would extend for packages, workflows, etc. That part is tentative.

2023-11-03 14:20 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/actioncollections/refactors/ActionCollectionRefactoringServiceCEImpl.java
> +        return Mono.just(Boolean.TRUE);
Incidentally another difference I found in the handling of refactors across entities is the presence of "figure out which branched entity to use" logic. Also not touched this to maintain logical flows as they are today.

2023-11-03 14:22 UTC, nidhi-nair commented
/ok-to-test

2023-11-03 14:47 UTC, nidhi-nair commented
/ok-to-test

2023-11-03 14:47 UTC, sondermanish commented on app/server/appsmith-server/src/main/java/com/appsmith/server/refactors/utils/RefactoringUtils.java
> +                ? refactorEntityNameDTO.getCollectionName() + "." + oldName
does whitespaces qualify as names? if not then lets start using `StringUtils.hasText()`?

2023-11-04 08:01 UTC, sondermanish commented on app/server/appsmith-server/src/main/java/com/appsmith/server/refactors/utils/RefactoringUtils.java
> +                ? refactorEntityNameDTO.getCollectionName() + "." + oldName
Since this PR just refactors the code, resolving this thread.

2023-11-04 13:55 UTC, nidhi-nair commented
/ok-to-test

2023-11-05 10:40 UTC, nidhi-nair commented
/ok-to-test

2023-11-05 23:29 UTC, nidhi-nair commented
/ok-to-test

2023-11-05 23:47 UTC, nidhi-nair commented
/ok-to-test

2023-11-06 03:37 UTC, subrata71 requested changes

2023-11-06 03:37 UTC, subrata71 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/refactors/applications/RefactoringSolutionCEImpl.java
> +                            .as(transactionalOperator::transactional)
Please don't include network calls/API calls inside the transactional block. Ideally, the transactional block should include DB operations only. The `refactorName` function essentially makes the calls to the AST service.

2023-11-06 03:48 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/EntityType.java
> +    JS_OBJECT
No, for enums we'd end up declaring everything required on CE itself. That's the strategy used for all enums so far. We'll add it when we cover refactor for modules.

2023-11-06 03:48 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/newactions/refactors/JsActionRefactoringServiceCEImpl.java
> +        Mono<RefactorEntityNameDTO> branchedActionMono = newActionService
🤔 sorry what's the difference here?

2023-11-06 03:49 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/refactors/applications/RefactoringSolutionCEImpl.java
> +        Mono<Void> actionsAndCollectionsMono = actionsMono.then(Mono.defer(() -> collectionsMono));
collections needs to happen after actions, it is dependent on some updates within actions. This is to make sure this order is maintained irrespective of contents of the methods.

2023-11-06 04:24 UTC, subrata71 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/newactions/refactors/JsActionRefactoringServiceCEImpl.java
> +        Mono<RefactorEntityNameDTO> branchedActionMono = newActionService
It's returning Mono<RefactorEntityNameDTO> but the var name is branchedActionMono.

2023-11-06 04:25 UTC, subrata71 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/refactors/applications/RefactoringSolutionCEImpl.java
> +        Mono<Void> actionsAndCollectionsMono = actionsMono.then(Mono.defer(() -> collectionsMono));
But we have seen earlier that `.then` itself can maintain the order of execution. Do you think `Mono.defer` is redundant in that sense?

2023-11-06 13:34 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/newactions/refactors/JsActionRefactoringServiceCEImpl.java
> +        Mono<RefactorEntityNameDTO> branchedActionMono = newActionService
Sorry, I still don't see what is different? Isn't the var already called `branchedActionMono`?

2023-11-06 13:35 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/refactors/applications/RefactoringSolutionCEImpl.java
> +        Mono<Void> actionsAndCollectionsMono = actionsMono.then(Mono.defer(() -> collectionsMono));
If you remember what we discussed last time was that the `.then` call makes sure that the reactive part of the second call happens after the reactive part of the first call. But there might be non-reactive stuff in there that uses previously calculated values. Since we don't want to leak the underlying logic into this layer, I have deferred the method to take care of execution order regardless of internals.

2023-11-06 13:37 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/RefactorEntityNameDTO.java
> +    EntityType entityType;
Adding internal annotation

2023-11-06 13:40 UTC, subrata71 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/refactors/applications/RefactoringSolutionCEImpl.java
> +        Mono<Void> actionsAndCollectionsMono = actionsMono.then(Mono.defer(() -> collectionsMono));
makes sense.

2023-11-06 14:01 UTC, subrata71 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/refactors/applications/RefactoringSolutionCEImpl.java
> +                            .as(transactionalOperator::transactional)
Keeping the concern out of the scope of this PR:
The utlimate goal w.r.t. transaction is to bring all the DB operations that happen during the refactor of any entity into one single transaction. And the transactional block shouldn't have any network calls whatsoever.

2023-11-06 14:04 UTC, subrata71 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/newactions/refactors/JsActionRefactoringServiceCEImpl.java
> +        Mono<RefactorEntityNameDTO> branchedActionMono = newActionService
Let's ignore this. very minor.

2023-11-06 14:06 UTC, subrata71 approved these changes

2023-11-06 16:07 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/newactions/refactors/JsActionRefactoringServiceCEImpl.java
> +        Mono<RefactorEntityNameDTO> branchedActionMono = newActionService
Yeah I'm going to remember this still, feels like a really stupid thing I'm not seeing :P

2023-11-06 16:07 UTC, merged