chore: add configuration for large and small widgets
appsmithorg/appsmith pull request #28671
Opened 2023-11-06 19:24 UTC by prsidhu

## Description

Use case - Widgets need to be distinguished as large or small in Anvil.

1. Add property ``isLargeWidget`` to ``AnvilConfig`` interface.
2. Update AnvilConfig for all widget. Especially, WDS widgets.

#### Type of change
- Chore (housekeeping or task changes that don't impact user perception)

## Testing

#### How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Also list any relevant details for your test configuration.
> Delete anything that is not relevant
- [x] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress

## Checklist:
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-11-07 08:11 UTC, KelvinOm requested changes

2023-11-07 08:11 UTC, KelvinOm commented on app/client/src/WidgetProvider/constants.ts
> +export const largeWidgets: Record<WidgetType, boolean> = {
I really don't like the fact that we have everything stored in one place. Here we have  a FixedLayout and an AutoLayout, and now Anvil is beginning to spread. Let's think about how to separate Anvil from all this. Abstractions will start leak very soon and it will be quite difficult to work with the code.

cc @riodeuno

2023-11-07 08:11 UTC, KelvinOm commented on app/client/src/widgets/AudioWidget/widget/index.tsx
> +      isLargeWidget: !!largeWidgets[this.type],
Why is it so difficult? Why can't I just set `true` or `false` here? `isLargeWidget: false`?

2023-11-07 08:28 UTC, riodeuno commented on app/client/src/WidgetProvider/constants.ts
> +export const largeWidgets: Record<WidgetType, boolean> = {
@KelvinOm I'm not sure if I understand your point correctly. Could you suggest an alternative or point to an issue so that we can discuss this accordingly?

Are you suggesting that we should have one map for all widget configs regardless of the layout system?

I do agree with the fact that the knowledge of the current layout system shouldn't be present anywhere outside of the layout system's data flow.

Also, with Fixed and Auto Layout slated to be deprecated sometime in the future, references layout systems should also be deprecated.

2023-11-07 08:29 UTC, riodeuno commented on app/client/src/widgets/AudioWidget/widget/index.tsx
> +      isLargeWidget: !!largeWidgets[this.type],
@prsidhu Could you elaborate on the need for using an external map to describe this property?

2023-11-07 08:31 UTC, riodeuno commented on app/client/src/WidgetProvider/constants.ts
> +export const largeWidgets: Record<WidgetType, boolean> = {
If you're referring to the fact that a map like `largeWidgets` exists in this file, instead of having the widget define it statically. Let's wait for @prsidhu's response on the rationale.

2023-11-07 08:36 UTC, KelvinOm commented on app/client/src/WidgetProvider/constants.ts
> +export const largeWidgets: Record<WidgetType, boolean> = {
@riodeuno I'm not only talking about `largeWidgets` map, but also about the fact that everything related to Anvil engine should be separated. This will simplify the code and help with the deprivation of code in the future.

2023-11-07 14:45 UTC, prsidhu commented on app/client/src/widgets/AudioWidget/widget/index.tsx
> +      isLargeWidget: !!largeWidgets[this.type],
If we need to access all large widgets, we won't have to keep iterating over all widget types in real time.

2023-11-07 14:54 UTC, KelvinOm commented on app/client/src/widgets/AudioWidget/widget/index.tsx
> +      isLargeWidget: !!largeWidgets[this.type],
@prsidhu We don't need that map right now, right? If we need it, we can easily collect this information and make a map. Until then, I'd prefer to keep the code as simple as possible.

2023-11-07 16:34 UTC, prsidhu commented
/ok-to-test

2023-11-07 18:04 UTC, KelvinOm approved these changes

2023-11-09 04:31 UTC, prsidhu commented
/ok-to-test

2023-11-09 06:37 UTC, marks0351 submitted a review, later dismissed

2023-11-10 03:26 UTC, prsidhu commented
/ok-to-test

2023-11-10 11:28 UTC, marks0351 commented
/ok-to-test

2023-11-13 05:51 UTC, marks0351 commented
/ok-to-test

2023-11-13 09:21 UTC, marks0351 approved these changes

2023-11-14 05:25 UTC, merged