Add debugger CE changes
appsmithorg/appsmith pull request #28752
Opened 2023-11-08 19:11 UTC by Rishabh-Rathod

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.
>
## Description
> Add a TL;DR when description is extra long (helps content team)
>
> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change
>
> Links to Notion, Figma or any other documents that might be relevant to the PR
>
>
#### PR fixes following issue(s)
Fixes # (issue number)
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
#### Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video
>
>
#### Type of change
> Please delete options that are not relevant.
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
## Testing
>
#### How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Also list any relevant details for your test configuration.
> Delete anything that is not relevant
- [ ] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-11-09 06:25 UTC, Rishabh-Rathod commented
/ok-to-test sha=a5cdc84

2023-11-09 10:03 UTC, Rishabh-Rathod commented
/ok-to-test sha=e99f263

2023-11-09 11:51 UTC, ApekshaBhosale requested changes

2023-11-09 11:51 UTC, ApekshaBhosale commented on app/client/src/ce/components/editorComponents/Debugger/entityTypeLinkMap.tsx
> +import { PluginType } from "entities/Action";
is this required to move entire component to ce? what kind oc hangs are you planning to do for ee? @Rishabh-Rathod

2023-11-09 12:27 UTC, Rishabh-Rathod commented on app/client/src/ce/components/editorComponents/Debugger/entityTypeLinkMap.tsx
> +import { PluginType } from "entities/Action";
@ApekshaBhosale No it is not required. I will split this and only move actually required code to the CE folder. Thanks for the heads-up.

2023-11-09 12:36 UTC, Rishabh-Rathod commented on app/client/src/entities/DataTree/dataTreeWidget.ts
> +    configEntity: entityConfig,
Why this change?

widgetId was already present in the entityConfig of the data tree, but we were adding widgetId to the entityConfig later due to a type error. After this change, we could directly pass entityConfig.

2023-11-09 12:36 UTC, Rishabh-Rathod commented on app/client/src/ce/entities/DataTree/types.ts
> +  widgetId: string;
Why this change?

Check the comment here https://github.com/appsmithorg/appsmith/pull/28752/files#r1387941375

2023-11-09 13:09 UTC, ankitakinger commented on app/client/src/ce/utils/getEntityPayloadInfo.ts
> +    entityConfig: any,
can we use better types here instead of `any`?

2023-11-09 14:39 UTC, Rishabh-Rathod commented on app/client/src/ce/utils/getEntityPayloadInfo.ts
> +    entityConfig: any,
I tried using the `DataTreeEntity` and `DataTreeEntityConfig` but they don't work here due to the way we have implemented the types currently. The union of `CE_DataTreeEntity` and `EE_DataTreeEntity` doesn't accept `WidgetEntity` as type though `CE_DataTreeEntity` is union of `WidgetEntity | ActionEntity | JSActionEntity`.  I tried `unknown` too but also doesn't work. 
![image](https://github.com/appsmithorg/appsmith/assets/23132741/820145ea-fd7f-4718-837e-51a88b570338)

2023-11-14 05:06 UTC, Rishabh-Rathod commented
/ok-to-test sha=9f7270e

2023-11-14 11:03 UTC, Rishabh-Rathod commented
/ok-to-test sha=c0ef5c3

2023-11-16 09:35 UTC, Rishabh-Rathod commented
/ok-to-test sha=1d29416

2023-11-16 12:04 UTC, ankitakinger commented on app/client/src/ce/utils/getEntityPayloadInfo.ts
> +    pluginType?: PluginType;
I hope this works fine on EE and doesn't break anything.

2023-11-16 12:05 UTC, Rishabh-Rathod commented on app/client/src/ce/utils/getEntityPayloadInfo.ts
> +    pluginType?: PluginType;
Yes, this is only used in evalErrorHandler which is introduced in this PR. I don't foresee a reason for this to break anything.

2023-11-16 12:08 UTC, ankitakinger approved these changes
LGTM. @ApekshaBhosale Please review this PR from your end too once.

2023-11-16 12:27 UTC, ApekshaBhosale approved these changes

2023-11-16 13:54 UTC, merged

2023-11-27 13:12 UTC, Rishabh-Rathod commented on app/client/src/sagas/PostEvaluationSagas.ts
> -        : entity.type;
@ApekshaBhosale This is old code where we were already sending string earlier but it was not strictly typed code.