feat: added multipart app/json support
appsmithorg/appsmith pull request #28911
Opened 2023-11-16 13:10 UTC by sondermanish

## Description
> Added multi part form data application/json support

### PR fixes following issue(s)
Fixes #28419 

#### Type of change
- Feature Improvement

#### How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Also list any relevant details for your test configuration.
> Delete anything that is not relevant
- [ ] Manual
- [ ] JUnit

2023-11-17 08:57 UTC, sondermanish commented
/ok-to-test

2023-11-17 08:58 UTC, sondermanish commented
/build-deploy-preview skip-tests=true

2023-11-17 09:02 UTC, sondermanish commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/DataUtils.java
> +                            bodyBuilder.part(key, property.getValue());
Not sure whether to add the application/json media-type over here.

2023-11-17 09:03 UTC, sondermanish commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/DataUtils.java
> +                            bodyBuilder.part(key, property.getValue());
same question with empty strings? do we stop execution or should we do a soft pass

2023-11-20 06:42 UTC, sumitsum requested changes

2023-11-20 06:42 UTC, sumitsum commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/DataUtils.java
> +                        if (!(property.getValue() instanceof String jsonString)) {
Do we know what other type can the value be apart from a String ? If no, could we instead do this - convert the value to string first i.e. `property.getValue().toString()` - and then try to read this value back as JSON - would allow us to remove this `if` block ?

2023-11-20 06:42 UTC, sumitsum commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/DataUtils.java
> +                            bodyBuilder.part(key, "");
Is it possible for parsed JSON object to be null for a non-empty string ? If not, then should we remove this if condition because `null` and empty string case has been handled before this ?

2023-11-20 06:42 UTC, sumitsum commented on app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java
> +        String jsonString = " {\"id\": abcd,\"email\": \"abcd@xyz.mn\",\"userName\": \"Michael Law\"} ";
Can you please add an array of JSON as a another use case to check if that works ?

2023-11-20 06:42 UTC, sumitsum commented on app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java
> +    public void testMultipartFormDataWithJSON() {
Can you please add a test case with mustache binding in place of JSON value ?

2023-11-20 12:21 UTC, sondermanish commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/DataUtils.java
> +                            // Should we throw out an error over here?, We don't expect this to be the case
null is not a valid value in Multipart, I've added a check to skip the null values

2023-11-20 12:23 UTC, sondermanish commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/DataUtils.java
> +                        if (!(property.getValue() instanceof String jsonString)) {
I did not quite get the question, I've added it as a declaration for further use of the variable. Do you wan't to get rid of the declaration?

2023-11-20 12:27 UTC, sondermanish commented on app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java
> +        String jsonString = " {\"id\": abcd,\"email\": \"abcd@xyz.mn\",\"userName\": \"Michael Law\"} ";
added as suggested

2023-11-20 12:27 UTC, sondermanish commented on app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java
> +    public void testMultipartFormDataWithJSON() {
added as suggested

2023-11-20 12:43 UTC, sondermanish commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/DataUtils.java
> +                            bodyBuilder.part(key, "");
I'm not sure if this case will ever arise, however the multipart can't intake null, should we error out over here, or just skip it?

2023-11-20 12:43 UTC, sondermanish commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/DataUtils.java
> +                        if (!(property.getValue() instanceof String jsonString)) {
Although anything coming from client side should be effectively a string,  If we save the action config via postman, we might have some values which are not string.

2023-11-21 10:35 UTC, sondermanish commented
/ok-to-test

2023-11-22 10:30 UTC, sumitsum commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/DataUtils.java
> +                        if (!(property.getValue() instanceof String jsonString)) {
Hi @sondermanish yes, I was wonder if we can remove it because it is not used at the moment.

2023-11-22 10:33 UTC, sumitsum commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/DataUtils.java
> +                            bodyBuilder.part(key, "");
@sondermanish let us skip this change for now, because we don't know why this situation should arise. In case such a situation does come up, I think it is better to error out and find a proper fix for it then.

2023-11-22 10:45 UTC, sumitsum requested changes

2023-11-22 10:45 UTC, sumitsum commented on app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java
> +        String listString = "[\"a\",\"b\",\"c\"]";
Hi @sondermanish can you please add an array of JSON as value - e.g. [{...}, {...}] ?

2023-11-22 11:51 UTC, sumitsum commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/DataUtils.java
> +                        if (!(property.getValue() instanceof String jsonString)) {
Sorry, looks like it is being used. My mistake :)

2023-11-22 11:59 UTC, sumitsum commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/DataUtils.java
> +                        if (!(property.getValue() instanceof String jsonString)) {
Hi Manish, can you please add a comment here explaining why we need this check ?

2023-11-22 13:39 UTC, sondermanish commented on app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java
> +        String listString = "[\"a\",\"b\",\"c\"]";
Added as suggested

2023-11-22 13:39 UTC, sondermanish commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/DataUtils.java
> +                        if (!(property.getValue() instanceof String jsonString)) {
added as suggested

2023-11-22 13:56 UTC, sumitsum approved these changes

2023-11-22 14:14 UTC, sondermanish commented
/ok-to-test

2023-11-23 03:11 UTC, merged