feat: Added new pages pane with segmented navigation
appsmithorg/appsmith pull request #28927
Opened 2023-11-17 07:49 UTC by albinAppsmith

## Description

#### PR fixes following issue(s)
Fixes https://github.com/appsmithorg/appsmith/issues/28833
Fixes https://github.com/appsmithorg/appsmith/issues/28834
Fixes https://github.com/appsmithorg/appsmith/issues/28835
Fixes https://github.com/appsmithorg/appsmith/issues/28811

#### Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video
>
>
#### Type of change
> Please delete options that are not relevant.
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
## Testing
>
#### How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Also list any relevant details for your test configuration.
> Delete anything that is not relevant
- [ ] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-11-17 09:10 UTC, hetunandu requested changes

2023-11-17 09:10 UTC, hetunandu commented on app/client/src/pages/Editor/IDE/PagesPane/Queries_JS.tsx
> +    grid-template-columns: 4px auto 1fr auto auto auto auto auto;
Seems like there are a lot of columns. Is this because we are reusing existing components and needs an override?

2023-11-17 09:10 UTC, hetunandu commented on app/client/src/pages/Editor/IDE/PagesPane/index.tsx
> +  const [selected, setSelected] = useState<TabsType | undefined>(undefined);
Do not maintain any internal state. Make it completely derived via URL

2023-11-17 09:10 UTC, hetunandu commented on app/client/src/pages/Editor/IDE/PagesPane/index.tsx
> +        <SegmentedControl
Can we extract the Segmented Control and its logic into a different component?

2023-11-17 09:10 UTC, hetunandu commented on app/client/src/pages/Editor/IDE/PagesPane/index.tsx
> +  }, [location.pathname]);
This is not needed if we derive directly via URL.

2023-11-17 09:10 UTC, hetunandu commented on app/client/src/pages/Editor/IDE/PagesPane/Queries_JS.tsx
> +            <ExplorerActionEntity
Looks like we are using different components here anyways. Then we should be able to make Query Pane and JS pane into different files/components

2023-11-22 08:59 UTC, albinAppsmith commented on app/client/src/ce/RouteBuilder.ts
> +export const jsCollectionURL = (props: URLBuilderParams): string => {
Changed

2023-11-22 08:59 UTC, albinAppsmith commented on app/client/src/ce/RouteBuilder.ts
> +export const apiEditorURL = (props: URLBuilderParams): string =>
removed this... I was just trying something

2023-11-22 09:00 UTC, albinAppsmith commented on app/client/src/ce/RouteBuilder.ts
> +export const queryEditorURL = (props: URLBuilderParams): string =>
Done

2023-11-22 09:20 UTC, albinAppsmith commented on app/client/src/pages/Editor/IDE/LeftPane/index.tsx
> +        {/* <SentryRoute component={WidgetsEditorEntityExplorer} /> */}
Done

2023-11-22 09:21 UTC, albinAppsmith commented on app/client/src/pages/Editor/IDE/PagesPane/Queries_JS.tsx
> +    grid-template-columns: 4px auto 1fr auto auto auto auto auto;
Yeah since we are reusing entity this is needed

2023-11-22 09:26 UTC, albinAppsmith commented on app/client/src/pages/Editor/IDE/PagesPane/Queries_JS.tsx
> +            <ExplorerActionEntity
Since for the segments it is a single item, I added this same file. And even if I copy paste there won't be anything much in the new file.

2023-11-22 09:27 UTC, albinAppsmith commented on app/client/src/pages/Editor/IDE/PagesPane/index.tsx
> +  const [selected, setSelected] = useState<TabsType | undefined>(undefined);
will change it in the next PR once I complete the URL navigations

2023-11-22 09:28 UTC, albinAppsmith commented on app/client/src/pages/Editor/IDE/PagesPane/index.tsx
> +        <SegmentedControl
There will not be having much to extract once I switch to URL based route.

2023-11-22 09:34 UTC, albinAppsmith commented
/build-deploy-preview skip-test=true

2023-11-22 09:54 UTC, KelvinOm submitted a review, later dismissed

2023-11-22 10:06 UTC, albinAppsmith commented
/ok-to-test

2023-11-22 12:04 UTC, hetunandu approved these changes
Minor changes. Also fix the design system package. Since we are merging, we should not merge with a alpha version

2023-11-22 12:04 UTC, hetunandu commented on app/client/src/pages/Editor/IDE/LeftPane/index.tsx
> +        {isPagesPaneEnabled && <SentryRoute component={PagesPane} />}
```suggestion
        {isPagesPaneEnabled ? (<SentryRoute component={PagesPane} />) : 
          (<SentryRoute component={WidgetsEditorEntityExplorer} />)
        }
```

2023-11-23 06:03 UTC, albinAppsmith commented
/build-deploy-preview skip-test=true

2023-11-23 06:03 UTC, albinAppsmith commented
/ok-to-test

2023-11-23 07:14 UTC, albinAppsmith commented
/ok-to-test

2023-11-23 07:14 UTC, albinAppsmith commented
/build-deploy-preview skip-test=true

2023-11-23 09:12 UTC, hetunandu approved these changes

2023-11-23 09:23 UTC, merged