chore: frontend and backend telemetry updates for execute flow #28800 and #28805
appsmithorg/appsmith pull request #28936
Opened 2023-11-17 12:43 UTC by vsvamsi1

## Description
1. Added frontend and backend custom OTLP telemetry to track execute flow
2. Updated end vars in client side code to match with server sdk intialisation code.

#### PR fixes following issue(s)
Fixes #28800 and #28805

#### Type of change
- Chore (housekeeping or task changes that don't impact user perception)

#### How Has This Been Tested?
- [x] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-11-20 12:51 UTC, rajatagrawal commented on app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/ActionControllerCE.java
> +        Span span = this.otpTelemetry.startOtlpSpanFromTraceparent("action service execute", traceparent);
@sumitsum Can you please suggest a way to measure the actual time the mono will take to execute the action execute ?

2023-11-20 13:13 UTC, rajatagrawal commented on app/client/src/UITelemetry/generateTraces.ts
> +  if (!spanName) {
spanName isn't marked optional. It will always be there no ?

2023-11-20 13:16 UTC, rajatagrawal commented on app/client/src/UITelemetry/generateTraces.ts
> +  return tracer?.startSpan(spanName, { attributes: spanAttributes });
nit:

Can we do something similar to

```
if (!tracer) {
  return
}
const attributes = spanAttributes ?? {}
tracer.startSpan(spanName, attributes)
```

It may look cleaner.

2023-11-20 13:17 UTC, rajatagrawal commented on app/client/src/UITelemetry/generateTraces.ts
> +  if (!spanName || !parentSpan) {
spanName and parentSpan aren't marked optional in the arguments.

2023-11-20 13:18 UTC, rajatagrawal commented on app/client/src/UITelemetry/generateTraces.ts
> +export function setAttributesToSpan(span?: Span, spanAttributes?: Attributes) {
Why should span and spanAttributes be optional in the function arguments ?

2023-11-21 08:27 UTC, rajatagrawal requested changes

2023-11-21 08:27 UTC, rajatagrawal commented on app/client/src/UITelemetry/generateTraces.ts
> +function startTraceInNewRelicSession(span: any) {
Is it possible to use a defined type instead of any in the function argument ?

2023-11-21 08:27 UTC, rajatagrawal commented on app/client/src/UITelemetry/generateTraces.ts
> +  startTraceInNewRelicSession(span);
can we rename startTraceInNewRelicSession to something else that denotes that this function is used for both starting and ending traces in new relic ?

2023-11-21 08:27 UTC, rajatagrawal commented on app/client/src/api/ActionAPI.tsx
> +import type { Span } from "@opentelemetry/api";
Would it be possible to re export Span as another constant from generateTraces wrapper file that hides the current stack that is used for implementing telemetry ?

2023-11-21 08:30 UTC, rajatagrawal commented on app/client/src/api/ActionAPI.tsx
> +import type { Span } from "@opentelemetry/api";
And similar approach for any import from opentelemetry elsewhere in the code ? Ideally we would like to have telemetry wrapper that gets imported everywhere and abstracts the implementation of telemetry from rest of the code.

2023-11-21 18:53 UTC, vsvamsi1 commented on app/client/src/UITelemetry/generateTraces.ts
> +  if (!spanName || !parentSpan) {
This is also similar to the above comment i don't want telemetry with empty string names to be configured.

2023-11-22 04:44 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/ActionControllerCE.java
> +        Span span = this.otpTelemetry.startOtlpSpanFromTraceparent("action service execute", traceparent);
Continuing this conversation with Vamsi on Slack DM / meetings.

2023-11-22 04:59 UTC, sumitsum approved these changes

2023-11-22 04:59 UTC, sumitsum commented on app/server/appsmith-server/pom.xml
> +                <groupId>io.opentelemetry</groupId>
Hi Vamsi, as discussed, can you please remove the duplicated lines ?

2023-11-22 04:59 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/ActionControllerCE.java
> +        Span span = this.otpTelemetry.startOtlpSpanFromTraceparent("action service execute", traceparent);
As discussed, please check if there is a need to put a check for traceparent string being null - it should not be required if the `startOtlpSpanFromTraceparent` function handles it internally.

2023-11-22 04:59 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/ce/OtpTelemetry.java
> +package com.appsmith.server.helpers.ce;
Can you please move this file outside of the `ce` directory i.e. move it to `server/helpers` . APMU, the convention is to put those files in the CE directory that have a corresponding EE file. If this file is not going to change between CE and EE then we should move it outside the ce directory.

2023-11-22 04:59 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/ce/OtpTelemetry.java
> +import io.opentelemetry.api.OpenTelemetry;
QQ: Should the filename/classname be `OtlpTelemetry` or `OtpTelmetry` ?

2023-11-22 04:59 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/ce/OtpTelemetry.java
> +    private Context generateContextFromTraceHeader(String traceparent) {
Can you please add a comment to explain what this method does ?

2023-11-22 05:00 UTC, sumitsum commented
Can you please udpate the PR description ?

2023-11-22 05:05 UTC, sumitsum commented
Hi @vsvamsi1 just a minor info - as per convention when we raise a PR the branch name should either be fix/... or feat/... or chore/... .

2023-11-22 05:22 UTC, vsvamsi1 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/ce/OtpTelemetry.java
> +import io.opentelemetry.api.OpenTelemetry;
OTLP is the abbreviation they use...lets stick with that.

2023-11-22 12:52 UTC, vsvamsi1 commented on app/client/src/UITelemetry/generateTraces.ts
> +function startTraceInNewRelicSession(span: any) {
I could not an interface to match with it in opentelemetry/api, The sdkbase has a matching type but it does not have start trace. I will iterate over this in my next prs.

2023-11-22 13:24 UTC, rajatagrawal commented on app/client/src/UITelemetry/generateTraces.ts
> +function startTraceInNewRelicSession(span: any) {
works

2023-11-22 13:51 UTC, vsvamsi1 commented
/ok-to-test sha=583cf9412c80a437be3fc6698b4864ad25401c2c

2023-11-22 13:56 UTC, KelvinOm approved these changes

2023-11-22 14:00 UTC, sumitsum approved these changes

2023-11-22 14:02 UTC, sumitsum commented
Server side changes LGTM.

2023-11-22 22:34 UTC, rajatagrawal commented on app/client/src/workers/Evaluation/handlers/updateActionData.ts
> +  return true;
Is this change intended ?

2023-11-22 22:56 UTC, rajatagrawal requested changes
Raised a few discussion points and a few refactoring suggestions.

2023-11-22 22:56 UTC, rajatagrawal commented on app/server/appsmith-server/src/main/java/com/appsmith/server/constants/EnvVariables.java
> +    APPSMITH_NEW_RELIC_ACCOUNT_ENABLE
nit: Can be renamed to generic name : APPSMITH_SERVER_TELEMETRY_ENABLED

2023-11-22 22:56 UTC, rajatagrawal commented on app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/ActionControllerCE.java
> +import io.opentelemetry.api.trace.Span;
Can this be imported through helpers/OtlpTelemetry.java ? This will help us create an abstraction for the telemetry implementation and help us change telemetry implementations in the future if needed.

2023-11-22 22:56 UTC, rajatagrawal commented on app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/ActionControllerCE.java
> +        Span span = this.otlpTelemetry.startOtlpSpanFromTraceparent("action service execute", traceparent);
Would it be a good idea to have a naming convention for traces to helps us to search these traces in new relic ?

We could a prefix "frontend-" for all frontend traces and "backend-" for all backend traces;

2023-11-22 22:56 UTC, rajatagrawal commented on app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/ActionControllerCE.java
> +        Span span = this.otlpTelemetry.startOtlpSpanFromTraceparent("action service execute", traceparent);
Can we have metadata attributes in this span which tell us details about this action execute like which actionID, plugin etc.

2023-11-22 22:56 UTC, rajatagrawal commented on app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ActionController.java
> +        super(layoutActionService, newActionService, refactoringSolution, actionExecutionSolution, otlpTelemetry);
Sorry I am not aware the implementation works in Java.

I noticed that opentelemetry is initialized in ServerApplication.java. Where/How does it get passed to this constructor ?

Also, would it be a good idea to have helpers/OtlpTelemetry.java as a singleton and be imported anywhere telemetry needs to be enabled ?

In the current architecture, we will need to modify function signatures of any piece of code that needs telemetry in the future.

Just want to bounce off thoughts in terms of a solution which can scale with needs for more telemetry in the future and is easy to maintain.

2023-11-22 22:56 UTC, rajatagrawal commented on app/server/appsmith-server/src/main/java/com/appsmith/server/ServerApplication.java
> +            return AutoConfiguredOpenTelemetrySdk.initialize().getOpenTelemetrySdk();
Can this SDK be returned from helpers/OtlpTelemetry.java ? It will act as a wrapper all telemetry implementations and act as an abstraction from rest of the code.

2023-11-22 23:06 UTC, rajatagrawal commented on app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ActionController.java
> +        super(layoutActionService, newActionService, refactoringSolution, actionExecutionSolution, otlpTelemetry);
I think it is coming through `@Autowired`.

But would still like to know thoughts around using a singleton approach instead ?

2023-11-22 23:07 UTC, rajatagrawal commented on app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/OtlpTelemetry.java
> +            this.tracer = openTelemetry.getTracer("Server");
Does this get reinitialized everytime a new span needs to get sent ? Does it need to be initialized every time a new span needs to be sent or can it be reused across spans ?

2023-11-23 06:25 UTC, rajatagrawal commented on app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/OtlpTelemetry.java
> +            this.tracer = openTelemetry.getTracer("Server");
Had an async discussed with Vamsi and Sumit and we noted that Bean gets constructed only once and already follows the singleton pattern. Vamsi/Sumit will get back after verifying this.

2023-11-23 08:20 UTC, vsvamsi1 commented
/build-deploy-preview skip-tests=true

2023-11-23 10:18 UTC, vsvamsi1 commented
/build-deploy-preview skip-tests=true

2023-11-23 10:22 UTC, vsvamsi1 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/constants/EnvVariables.java
> +    APPSMITH_NEW_RELIC_ACCOUNT_ENABLE
Okay i can rename it to  APPSMITH_ENABLE_TELEMETRY ...since this flag applies to frontend and backend..

2023-11-23 10:24 UTC, vsvamsi1 commented
/ok-to-test sha=e50a50836d8955757000833b6724eb13dd0877ba

2023-11-23 10:30 UTC, vsvamsi1 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/constants/EnvVariables.java
> +    APPSMITH_NEW_RELIC_ACCOUNT_ENABLE
Hmm...most of the other properties do not make sense then they are prefixed with APPSMITH_NEW_RELIC....lets review them and we can decide a naming convention for all of them....Can we move this to another PR since its not very critical...

2023-11-23 10:33 UTC, vsvamsi1 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/ServerApplication.java
> +            return AutoConfiguredOpenTelemetrySdk.initialize().getOpenTelemetrySdk();
This is valid...I would like to take this up in another PR...

2023-11-23 11:25 UTC, vsvamsi1 commented on app/client/src/UITelemetry/generateTraces.ts
> +  const tracer = trace.getTracer(GENERATOR_TRACE);
Ueaj
/build-deploy-preview recreate=true

2023-11-23 11:25 UTC, vsvamsi1 commented
/build-deploy-preview recreate=true

2023-11-23 12:59 UTC, vsvamsi1 commented
/build-deploy-preview skip-tests=true

2023-11-23 15:51 UTC, vsvamsi1 commented
/build-deploy-preview skip-tests=true

2023-11-23 17:42 UTC, vsvamsi1 commented
/build-deploy-preview skip-tests=true

2023-11-23 19:38 UTC, vsvamsi1 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/ActionControllerCE.java
> +        Span span = this.otlpTelemetry.startOtlpSpanFromTraceparent("action service execute", traceparent);
Sure the kind will give the origin of the span....client or server. I have added the other attributes.
<img width="506" alt="Screenshot 2023-11-24 at 1 05 29 AM" src="https://github.com/appsmithorg/appsmith/assets/121419957/449efe25-fd04-46ba-8079-bb5ea7f2b381">

2023-11-23 19:54 UTC, vsvamsi1 commented
/build-deploy-preview skip-tests=true

2023-11-23 19:54 UTC, vsvamsi1 commented
/ok-to-test sha=9e5d108ba7a593144e7c692bdb83cf669616f508

2023-11-24 05:06 UTC, rajatagrawal submitted a review, later dismissed

2023-11-24 05:09 UTC, vsvamsi1 commented
/ok-to-test sha=bef3ffa1c1b856612235e0e1378da4e0122e16ac

2023-11-24 05:09 UTC, vsvamsi1 commented
/build-deploy-preview skip-tests=true

2023-11-24 06:34 UTC, vsvamsi1 commented
/ok-to-test sha=fbe45a959ad391087d6cf3878991efec07286a05

2023-11-24 06:35 UTC, vsvamsi1 commented
/build-deploy-preview skip-tests=true

2023-11-24 07:36 UTC, rajatagrawal approved these changes

2023-11-24 07:39 UTC, merged