chore: remove the redirection for mockdb to localhost
appsmithorg/appsmith pull request #28998
Opened 2023-11-21 08:28 UTC by AnaghHegde

## Description

#### PR fixes following issue(s)
Fixes https://github.com/appsmithorg/appsmith/issues/28924

#### Type of change
- Bug fix (non-breaking change which fixes an issue)

## Testing

#### How Has This Been Tested?
- [ ] Manual

#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-11-21 09:30 UTC, sharat87 requested changes

2023-11-21 09:30 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration035RemoveMockDbEndPointInDatasourceInSelfHostedInstance.java
> +                && envVariable.containsKey("APPSMITH_ENABLE_EMBEDDED_DB")) {
Please use `System.getenv("APPSMITH_ENABLE_EMBEDDED_DB")` to get this instead of parsing the `docker.env` directly. Environment variables can be set form many places other than `docker.env`.

2023-11-21 09:30 UTC, sharat87 commented on deploy/docker/fs/opt/appsmith/entrypoint.sh
>        # Update hosts lookup to resolve to embedded postgres
Should we remove this comment as well?

2023-11-21 09:30 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration035RemoveMockDbEndPointInDatasourceInSelfHostedInstance.java
> +            Update update = new Update().unset("structure");
Looks like we aren't using these. Can we remove them?

2023-11-23 04:59 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration035RemoveMockDbEndPointInDatasourceInSelfHostedInstance.java
> +        if (Boolean.FALSE.equals(commonConfig.isCloudHosting()) && StringUtils.isNotEmpty(envValue)) {
Only the value `0` will disable the embedded DB. Any other non empty string will enable it, which is also the default.

```suggestion
        boolean isEmbeddedDbEnabled = !"0".equals(System.getenv("APPSMITH_ENABLE_EMBEDDED_DB"));
        if (isEmbeddedDbEnabled && Boolean.FALSE.equals(commonConfig.isCloudHosting())) {
```

2023-11-23 05:42 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration035RemoveMockDbEndPointInDatasourceInSelfHostedInstance.java
> +        if (Boolean.FALSE.equals(commonConfig.isCloudHosting()) && StringUtils.isNotEmpty(envValue)) {
If the env itself is not set then wouldn't that be empty?

2023-11-24 07:30 UTC, sharat87 requested changes

2023-11-24 07:30 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration035RemoveMockDbEndPointInDatasourceInSelfHostedInstance.java
> +        if (Boolean.FALSE.equals(commonConfig.isCloudHosting()) && StringUtils.isNotEmpty(envValue)) {
Sorry, I'm talking about when it's not empty. The current logic treats the value `0` and `1` the same. We're only checking for a non-empty value. That's not the case in the `entrypoint.sh` script. There we check if this value is exactly `0`, and only then the embedded DB is disabled.

2023-11-24 08:58 UTC, sharat87 approved these changes

2023-11-24 12:02 UTC, merged