feat: update template screen UI and building blocks for new users in start from use case flow
appsmithorg/appsmith pull request #29020
Opened 2023-11-22 03:49 UTC by jacquesikot

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.
>
## Description
Updating the UI for the start from use case flow for new users + adding building blocks to the list of templates offered to new users in this flow.
>
> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change
>
> Links to Notion, Figma or any other documents that might be relevant to the PR
> https://www.figma.com/file/kbU9xPv44neCfv1FFo9Ndu/User-Activation?node-id=4293:41450&mode=dev
> https://www.notion.so/appsmith/Activation-experiment-2-Start-from-a-template-Offer-building-blocks-in-addition-to-templates-8986dfc3629041559c81b1650b3a5fe5?pvs=4
#### PR fixes following issue(s)
Fixes #28605 
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
#### Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video
>
>
#### Type of change
> Please delete options that are not relevant.
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
## Testing
>
#### How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Also list any relevant details for your test configuration.
> Delete anything that is not relevant
- [ ] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Test Plan
> Add Testsmith test cases links that relate to this PR
>
>
#### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)
>
>
>
## Checklist:
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

2023-11-22 03:51 UTC, jacquesikot commented
/build-deploy-preview skip-tests=true

2023-11-22 03:55 UTC, rahulbarwal commented
/ok-to-test

2023-11-22 08:07 UTC, rahulbarwal requested changes
Suggested some changes. If I skipped in some places, these are few pointers I want to suggest:
1. Separate files for styles
2. Explicit naming for files and variables. `onSelect`, `onClick` won't do.
3. Avoid using `revamp` in code. 6 months down the line when you are looking at this code, this is no more a revamp.

> In a separate PR, we should start adding jest tests for new components added.

2023-11-22 08:07 UTC, rahulbarwal commented on app/client/src/pages/setup/SignupSuccess.tsx
> +  useFeatureFlag(FEATURE_FLAG.ab_create_new_apps_enabled);
Mistakenly committed?

2023-11-22 08:07 UTC, rahulbarwal commented on app/client/src/pages/Templates/TemplatesHomeWrapper.tsx
> +    return template;
There is no need of a variable here.

2023-11-22 08:37 UTC, AmanAgarwal041 commented on app/client/src/ce/pages/Applications/CreateNewAppsOption.tsx
> +    onClickBack();
Does this not take directly to the application instead of clicking on back ?

2023-11-24 07:32 UTC, jacquesikot commented
/build-deploy-preview

2023-11-24 14:25 UTC, jacquesikot commented
/build-deploy-preview

2023-11-25 02:27 UTC, rahulbarwal approved these changes

2023-11-25 02:27 UTC, rahulbarwal commented on app/client/src/pages/Templates/StartWithTemplateFilter/index.tsx
> +  const onSelectFilter = (item: string, type: string) => {
Better types for `type` variable here.

2023-11-25 02:27 UTC, rahulbarwal commented on app/client/src/sagas/TemplatesSagas.ts
> +      });
I feel this is a crude way of selecting the new homepage. 
It works very well for building blocks, but not so much for templates with more than one page.

Although not a blocker, we should look out for a better way to decide what the new homepage should be.

2023-11-25 02:29 UTC, merged