Help modal
appsmithorg/appsmith pull request #2903
Opened 2021-02-08 08:24 UTC by rishabhsaxena

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.

## Description
> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation 
> and context. List any dependencies that are required for this change.

Fixes # (issue)
> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce. 
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-03-03 04:56 UTC, hetunandu requested changes

2021-03-03 04:56 UTC, hetunandu commented on app/client/src/components/editorComponents/GlobalSearch/Description.tsx
> +          ↵
use html entity for return key here `&#9166;`

2021-03-03 04:56 UTC, hetunandu commented on app/client/src/components/editorComponents/GlobalSearch/Description.tsx
> +          }}
Use styled components and get/define colors from default theme

2021-03-03 04:56 UTC, hetunandu commented on app/client/src/components/editorComponents/GlobalSearch/Description.tsx
> +const getDocumentationPreviewContent = (
Move markdown transformation to a different file and add unit tests. Keep this component simple

2021-03-03 04:56 UTC, hetunandu commented on app/client/src/components/editorComponents/GlobalSearch/GlobalSearchHotKeys.tsx
> +import React from "react";
This should be defined in Editor/index.ts Maybe we can define these(and existing) globally in some hotkeys file and then import

2021-03-03 04:56 UTC, hetunandu commented on app/client/src/components/editorComponents/GlobalSearch/HelpBar.tsx
> +const modText = () => (isMac() ? `⌘` : "ctrl");
Use html entities for the command key

2021-03-03 04:56 UTC, hetunandu commented on app/client/src/components/editorComponents/GlobalSearch/SearchBox.tsx
> +  }, [modalOpen]);
Compose as a single hook

2021-03-03 04:56 UTC, hetunandu commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/ActionExecutionRequest.java
> +import com.fasterxml.jackson.databind.JsonNode;
I think these changes are here by mistake, can we pull the latest release?

2021-03-03 04:56 UTC, hetunandu commented on app/client/src/sagas/InitSagas.ts
> +    takeLatest(ReduxActionTypes.RESET_EDITOR_REQUEST, resetEditorSaga),
Why is this needed? I could not find where this is called from

2021-03-03 10:30 UTC, rishabhsaxena commented on app/client/src/sagas/InitSagas.ts
> +    takeLatest(ReduxActionTypes.RESET_EDITOR_REQUEST, resetEditorSaga),
This is to reset `is editor initialized` and `are entities restored` while switching applications, call it from `componentWillMount` within the Editor

2021-03-08 02:31 UTC, hetunandu commented on app/client/src/components/editorComponents/GlobalSearch/GlobalSearchHotKeys.tsx
> +import React from "react";
This was not applied

2021-03-08 02:35 UTC, hetunandu reviewed
LGTM

2021-03-08 02:35 UTC, hetunandu approved these changes

2021-03-08 08:24 UTC, merged