Added defaultText and defaultHTML properties in RTE
appsmithorg/appsmith pull request #3055
Opened 2021-02-16 06:18 UTC by vicky-primathon

## Description
Added defaultText and defaultHTML properties in RTE to change newline to br tag only in case of default text value

Fixes #2852 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manually tested

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-02-18 14:15 UTC, riodeuno requested changes

2021-02-18 14:15 UTC, riodeuno commented on app/client/src/components/designSystems/appsmith/RichTextEditorComponent.tsx
> +      ? props.defaultValue
Instead of using `getContent`, can we just use `props.defaultValue`?

2021-02-22 16:36 UTC, riodeuno requested changes
One comment. The rest looks good.

2021-02-22 16:36 UTC, riodeuno commented on app/client/src/components/designSystems/appsmith/RichTextEditorComponent.tsx
> +        editor.setContent(content, { format: props.formatType });
This will always be `html` right? Because, the content is generated by parsing the Markdown using showdown and then passed to the component.

2021-03-03 06:51 UTC, riodeuno submitted a review, later dismissed

2021-03-12 12:08 UTC, Nikhil-Nandagopal approved these changes

2021-03-12 12:08 UTC, merged