add new property pane button and zoom button
appsmithorg/appsmith pull request #3076
Opened 2021-02-17 06:32 UTC by ram-primathon

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.

## Description
> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation 
> and context. List any dependencies that are required for this change.

Fixes # (issue)
> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce. 
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-02-17 07:06 UTC, hetunandu requested changes

2021-02-18 07:44 UTC, hetunandu requested changes

2021-02-18 07:44 UTC, hetunandu commented on app/client/src/components/designSystems/appsmith/StepComponent.tsx
>  import { ControlIcons } from "icons/ControlIcons";
Revert all changes in this file

2021-02-18 07:44 UTC, hetunandu commented on app/client/src/components/ads/StepComponent.tsx
> +  background: ${(props) => props.theme.ads.stepComponent[props.skin].stepBG};
Fix the place where this is imported from

2021-02-18 07:44 UTC, hetunandu commented on app/client/src/components/propertyControls/PrimaryColumnsControl.tsx
> +          // color="#FFFFFF"
Remove these lines

2021-02-18 07:44 UTC, hetunandu commented on app/client/src/components/propertyControls/StepControl.tsx
> +    console.log(this.props);
remove console.log

2021-02-18 07:44 UTC, hetunandu commented on app/client/src/components/propertyControls/StepControl.tsx
> +        skin={this.props.theme === EditorTheme.DARK ? Skin.DARK : Skin.LIGHT}
Dont pass skin or theme

2021-02-18 07:44 UTC, hetunandu commented on app/client/src/components/propertyControls/StyledControls.tsx
> +          ? props.theme.colors.jsButtonActiveColor
USe the correct colors

2021-02-18 07:44 UTC, hetunandu commented on app/client/src/constants/DefaultTheme.tsx
> +  },
ads does not need a new key. Add this inside light and dark const in DefaultTheme

2021-02-18 07:44 UTC, hetunandu commented on app/client/src/constants/DefaultTheme.tsx
> +    jsButtonColor: Colors.SILVER_CHALICE,
Add this under the propertyPane key in light and dark DefaultTheme

2021-02-18 13:18 UTC, ram-primathon commented on app/client/src/constants/DefaultTheme.tsx
> +    jsButtonColor: Colors.SILVER_CHALICE,
done

2021-02-18 13:18 UTC, ram-primathon commented on app/client/src/constants/DefaultTheme.tsx
> +  },
done

2021-02-18 18:09 UTC, hetunandu requested changes

2021-02-18 18:09 UTC, hetunandu commented on app/client/src/components/propertyControls/PrimaryColumnsControl.tsx
> -          className="t--add-column-btn"
Keep this class name. Classnames with `t--` prefix are used for automated testing

2021-02-18 18:09 UTC, hetunandu commented on app/client/src/components/propertyControls/StyledControls.tsx
> +    props.active ? "#6A86CE" : props.theme.colors.propertyPane.addButtonBG};
Add the active color as part of the theme as well

2021-02-18 18:09 UTC, hetunandu commented on app/client/src/constants/DefaultTheme.tsx
> +    zoomButtonBG: string;
Should be ShadeColor as well.

2021-02-18 18:09 UTC, hetunandu commented on app/client/src/constants/DefaultTheme.tsx
> +    addButtonBG: lightShades[11],
Use buttonText instead of addButtonBG.

2021-02-18 18:15 UTC, hetunandu requested changes

2021-02-18 18:15 UTC, hetunandu commented on app/client/src/components/propertyControls/KeyValueComponent.tsx
> -        icon={"plus"}
Add back icon. Icon is needed

2021-02-18 18:15 UTC, hetunandu commented on app/client/src/components/propertyControls/PrimaryColumnsControl.tsx
> -          icon="plus"
icon is still needed

2021-02-18 18:15 UTC, hetunandu commented on app/client/src/components/propertyControls/ColumnActionSelectorControl.tsx
> -          icon={"plus"}
icon is still needed

2021-02-19 05:26 UTC, ram-primathon commented on app/client/src/components/propertyControls/PrimaryColumnsControl.tsx
> -          className="t--add-column-btn"
done

2021-02-19 05:35 UTC, ram-primathon commented on app/client/src/components/propertyControls/StyledControls.tsx
> +    props.active ? "#6A86CE" : props.theme.colors.propertyPane.addButtonBG};
done

2021-02-19 05:36 UTC, ram-primathon commented on app/client/src/constants/DefaultTheme.tsx
> +    addButtonBG: lightShades[11],
done

2021-02-19 05:36 UTC, ram-primathon commented on app/client/src/constants/DefaultTheme.tsx
> +    zoomButtonBG: string;
nope

2021-02-19 05:37 UTC, ram-primathon commented on app/client/src/components/propertyControls/KeyValueComponent.tsx
> -        icon={"plus"}
done

2021-02-19 05:56 UTC, ram-primathon commented on app/client/src/components/propertyControls/PrimaryColumnsControl.tsx
> -          icon="plus"
done

2021-02-19 05:56 UTC, ram-primathon commented on app/client/src/components/propertyControls/ColumnActionSelectorControl.tsx
> -          icon={"plus"}
done

2021-02-19 06:03 UTC, hetunandu requested changes

2021-02-19 06:03 UTC, hetunandu commented on app/client/src/constants/DefaultTheme.tsx
> +    zoomButtonBG: string;
This is still string, should be of type ShadeColor

2021-02-19 06:03 UTC, hetunandu commented on app/client/src/constants/DefaultTheme.tsx
> +    activeButtonText: string;
Should be of type ShadeColor

2021-02-19 06:03 UTC, hetunandu commented on app/client/src/constants/DefaultTheme.tsx
> +    addButtonBG: lightShades[11],
Yes, what i meant was dont add this new key at all. Use the buttonText value everywhere instead

2021-02-19 06:09 UTC, hetunandu commented on app/client/src/constants/DefaultTheme.tsx
> +    zoomButtonBG: string;
This is still string, should be of type ShadeColor

2021-02-19 06:13 UTC, ram-primathon commented on app/client/src/constants/DefaultTheme.tsx
> +    zoomButtonBG: string;
One color is zoomButtonBG: "#E0DEDE" which is not present in type ShadeColor then how am I suppose to keep its type as ShadeColor

2021-02-19 06:16 UTC, ram-primathon commented on app/client/src/constants/DefaultTheme.tsx
> +    addButtonBG: lightShades[11],
done

2021-02-19 06:28 UTC, hetunandu commented on app/client/src/constants/DefaultTheme.tsx
> +    zoomButtonBG: string;
You will need to add the light and dark theme colour in `lightShades` and `darkShades` array and use that instead. That will fix the type issue

2021-02-19 06:46 UTC, ram-primathon commented on app/client/src/constants/DefaultTheme.tsx
> +    activeButtonText: string;
done

2021-02-19 06:46 UTC, ram-primathon commented on app/client/src/constants/DefaultTheme.tsx
> +    zoomButtonBG: string;
done

2021-02-19 07:06 UTC, hetunandu requested changes

2021-02-19 07:06 UTC, hetunandu commented on app/client/src/constants/Colors.tsx
> +  SILVER_CHALICE: "#A9A7A7",
Not used anymore. Remove

2021-02-19 07:06 UTC, hetunandu commented on app/client/src/components/propertyControls/StyledControls.tsx
> +      fill: ${(props) => (props.active ? "#ffffff" : "#6A86CE")};
Use theme colour here

2021-02-19 11:47 UTC, ram-primathon commented on app/client/src/components/propertyControls/StyledControls.tsx
> +      fill: ${(props) => (props.active ? "#ffffff" : "#6A86CE")};
done

2021-02-19 11:47 UTC, ram-primathon commented on app/client/src/constants/Colors.tsx
> +  SILVER_CHALICE: "#A9A7A7",
done

2021-02-22 04:52 UTC, hetunandu approved these changes

2021-02-22 04:52 UTC, merged