Fix execute action error message
appsmithorg/appsmith pull request #3077
Opened 2021-02-17 09:31 UTC by akash-codemonk

## Description

Fixes #2872 

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce. 
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-02-17 13:22 UTC, mohanarpit commented on app/client/src/api/Api.tsx
> +      error.response
@akash-codemonk So what error does the user see in this scenario?

2021-02-17 14:03 UTC, akash-codemonk commented on app/client/src/api/Api.tsx
> +      error.response
The unable to connect error. https://github.com/appsmithorg/appsmith/blob/release/app/client/src/constants/messages.ts#L86

2021-02-17 14:39 UTC, mohanarpit commented on app/client/src/api/Api.tsx
> +      error.response
While I don't see the weird error, I'm seeing [this error](https://github.com/appsmithorg/appsmith/blob/release/app/client/src/constants/messages.ts#L176) in the deploy preview instead of the one you mentioned. Is that intentional?

2021-02-18 02:51 UTC, hetunandu commented on app/client/src/api/Api.tsx
> +      error.response
How are you testing this @mohanarpit ?

2021-02-18 02:54 UTC, hetunandu requested changes

2021-02-18 02:54 UTC, hetunandu commented on app/client/src/api/Api.tsx
> +    // If error.response is undefined we proceed with the standard error flow
Instead we should catch this particular case before (internet not connected) and trigger an error with that message

2021-02-18 03:46 UTC, mohanarpit commented on app/client/src/api/Api.tsx
> +      error.response
As specified in the issue: 
1. Create an API
2. Turn off your internet
3. Hit Run

2021-02-18 10:09 UTC, akash-codemonk commented on app/client/src/api/Api.tsx
> +      error.response
That is weird. I get the unable to connect error message doing the same.

2021-02-18 12:37 UTC, hetunandu requested changes

2021-02-18 12:37 UTC, hetunandu commented on app/client/src/api/Api.tsx
> +      error.response
Revert this change please

2021-02-18 12:50 UTC, akash-codemonk commented on app/client/src/api/Api.tsx
> +      error.response
Should we be checking for this anyways since `makeExecuteActionResponse` expects `error.response` to be defined.

2021-02-18 12:52 UTC, hetunandu commented on app/client/src/api/Api.tsx
> +      error.response
axios will always have response object if i am not wrong

2021-02-18 13:02 UTC, akash-codemonk commented on app/client/src/api/Api.tsx
> +      error.response
We seem to be checking for the same [here](https://github.com/appsmithorg/appsmith/blob/release/app/client/src/api/Api.tsx#L75)

2021-02-19 05:33 UTC, hetunandu approved these changes

2021-02-19 05:46 UTC, merged