WIP: fix flaky test
appsmithorg/appsmith pull request #3081
Opened 2021-02-17 17:07 UTC by NandanAnantharamu

updated common method

2021-02-25 08:54 UTC, NandanAnantharamu commented
@hetunandu we can have multiple runs to see if the flaky thing is fixed, but I don't see the test being flaky after this push.

2021-03-16 04:59 UTC, hetunandu requested changes

2021-03-16 04:59 UTC, hetunandu commented on app/client/cypress/support/commands.js
> +    .type(apiname, { delay: 300 }, { force: true })
Let's avoid adding this delay.

2021-04-20 06:02 UTC, NandanAnantharamu commented
closing this PR as it's not required at this point in time.

2021-04-20 06:02 UTC, closed without merging