Fix app title widths for both viewer and editor
appsmithorg/appsmith pull request #3094
Opened 2021-02-18 14:43 UTC by rishabhsaxena

## Description
Increase allowed width for app title for both viewer and editor

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- manually

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-02-19 06:39 UTC, hetunandu requested changes

2021-02-19 06:39 UTC, hetunandu commented on app/client/src/pages/Editor/EditableAppName.tsx
> +    flex: 1;
Instead why dont we just set `flex: 1` whenever `fill=true` is passed in the props

2021-02-19 07:31 UTC, Nikhil-Nandagopal approved these changes

2021-02-19 09:33 UTC, rishabhsaxena commented on app/client/src/pages/Editor/EditableAppName.tsx
> +    flex: 1;
I guess there could be a case with `flex-direction: column`, where they would mean different

2021-02-22 05:04 UTC, hetunandu approved these changes

2021-02-22 05:32 UTC, merged