Feature: Canvas max width config(DIP)
appsmithorg/appsmith pull request #3141
Opened 2021-02-22 09:41 UTC by marks0351

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.

## Description
> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation 
> and context. List any dependencies that are required for this change.

Fixes # (issue)
> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce. 
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-02-26 09:26 UTC, riodeuno commented on app/client/src/pages/Editor/Explorer/hooks.ts
> +export const useDynamicAppLayout = () => {
Let's move the hooks to the `utils/hooks` folder.

2021-02-26 09:34 UTC, riodeuno commented on app/client/src/pages/Editor/MainContainerLayoutControl.tsx
> +    pointer-events: all;
Please figure out if we can avoid updating the styles of our components, as much as possible.

2021-02-26 09:45 UTC, riodeuno requested changes

2021-02-26 09:45 UTC, riodeuno commented on app/client/src/reducers/entityReducers/canvasWidgetsReducer.tsx
> +import defaultTemplate from "templates/default";
Let's use `MAIN_CONTAINER_WIDGET_ID` from `WidgetConstants`

2021-02-26 09:45 UTC, riodeuno commented on app/client/src/reducers/entityReducers/pageListReducer.tsx
> +type AppLayoutType = "FIXED" | "FLUID";
Is this the same as ContainerLayoutType?

2021-02-26 09:45 UTC, riodeuno commented on app/client/src/sagas/ApplicationSagas.tsx
> +function* updateApplicationLayout(
Let's rename this to updateApplicationLayoutSaga

2021-03-03 04:23 UTC, hetunandu approved these changes

2021-03-03 04:25 UTC, hetunandu approved these changes

2021-03-03 05:09 UTC, hetunandu approved these changes

2021-03-03 05:24 UTC, riodeuno commented on app/client/src/utils/hooks/useDynamicAppLayout.tsx
> +export const useDynamicAppLayout = () => {
Let's talk about how we can mock redux and sagas to write unit tests for these types of functions.

2021-03-03 05:24 UTC, riodeuno approved these changes
Looks good to me!

2021-03-03 05:26 UTC, merged