chore: WDS TextInput style
appsmithorg/appsmith pull request #31659
Opened 2024-03-11 11:58 UTC by ichik

Closes #31021

2024-03-13 10:15 UTC, ichik commented on app/client/packages/design-system/widgets/src/styles/src/text-input.module.css
>      box-shadow: 0 0 0 2px var(--color-bd-negative);
@jsartisan this doesn't seem to work (as in the main focus color supersedes the error, I'm not sure if that's even needed. Having a negative border in resting and hover only should be sufficient in most cases, the only exception I can think of would be runtime validation that runs without losing focus.
Let's maybe just remove this?

cc @tbrizitsky

2024-03-13 10:16 UTC, ichik commented on app/client/packages/design-system/widgets/src/styles/src/text-input.module.css
>      box-shadow: 0 0 0 2px var(--color-bd-negative);
@jsartisan this doesn't seem to work (as in the main focus color supersedes the error, I'm not sure if that's even needed. Having a negative border in resting and hover only should be sufficient in most cases, the only exception I can think of would be runtime validation that runs without losing focus.
Let's maybe just remove this?

cc @tbrizitsky

2024-03-13 10:16 UTC, ichik commented on app/client/packages/design-system/widgets/src/styles/src/text-input.module.css
>    }
@jsartisan this doesn't seem to work (as in the main focus color supersedes the error, I'm not sure if that's even needed. Having a negative border in resting and hover only should be sufficient in most cases, the only exception I can think of would be runtime validation that runs without losing focus.
Let's maybe just remove this?

cc @tbrizitsky

2024-03-14 11:37 UTC, jsartisan submitted a review, later dismissed

2024-03-15 13:49 UTC, KelvinOm requested changes
Vadim, you're cool! :) 

Few comments:
1. Subjectively, in the dark mode, input border become really contrast(bright).
![Снимок экрана 2024-03-15 в 16 42 40](https://github.com/appsmithorg/appsmith/assets/11555074/58fcf2ab-931a-4d14-ab82-c513fe2eeb6b)

2. It is necessary to remove the background for the readonly mode
![Снимок экрана 2024-03-15 в 16 46 16](https://github.com/appsmithorg/appsmith/assets/11555074/6baba594-c094-49f0-a764-e7755371b0b4)

2024-03-18 09:45 UTC, KelvinOm approved these changes

2024-03-18 10:06 UTC, merged