Feature/text widget style options
appsmithorg/appsmith pull request #3167
Opened 2021-02-23 10:32 UTC by vicky-primathon

## Description
Added styling options in text widget.

Fixes #1810 

## Type of change
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-03-11 00:11 UTC, riodeuno requested changes

2021-03-11 00:11 UTC, riodeuno commented on app/client/src/components/designSystems/blueprint/TextComponent.tsx
> +import { FontStyleTypes } from "../appsmith/TableComponent/Constants";
Let's move this to `WidgetConstants`

2021-03-11 00:11 UTC, riodeuno commented on app/client/src/widgets/TextWidget.tsx
> +          //       icon: "HEADING_ONE",
Let's remove these commented lines of code.

2021-03-11 00:11 UTC, riodeuno commented on app/client/src/widgets/TextWidget.tsx
> +  fontStyle?: string;
Let's make sure we have proper default values here: (WidgetConfigResponse)
<img width="1311" alt="Screenshot 2021-03-11 at 5 39 38 AM" src="https://user-images.githubusercontent.com/103687/110716024-5b7ca780-822c-11eb-81b9-b0d619e9f197.png">

Text color & font style values.

2021-03-11 00:13 UTC, riodeuno commented
- One of the tests are failing
- We need a migration for old "Text Style" property. Along with that we need to use the font sizes property and deprecate "Text Style". The old "Text Style" properties can all be defined using a combination of "Font Style" and "Font Size" properties.
<img width="390" alt="Screenshot 2021-03-11 at 5 39 55 AM" src="https://user-images.githubusercontent.com/103687/110716227-bc0be480-822c-11eb-914c-542669658e92.png">

2021-03-16 13:32 UTC, vicky-primathon commented on app/client/src/widgets/TextWidget.tsx
> +  fontStyle?: string;
Added default color, font style and font size.

2021-03-22 10:32 UTC, riodeuno commented on app/client/src/components/propertyControls/DropDownControl.tsx
>  import { StyledDropDown, StyledDropDownContainer } from "./StyledControls";
Please verify if this gives us an eslint warning about unused vars

2021-03-22 10:35 UTC, riodeuno requested changes

2021-03-22 10:35 UTC, riodeuno commented on app/client/src/utils/migrations/TextWidgetReplaceTextStyle.ts
> +    let child = cloneDeep(_child);
Let's add unit tests for this.

2021-03-23 07:05 UTC, riodeuno submitted a review, later dismissed

2021-03-24 08:55 UTC, riodeuno commented on app/client/src/constants/WidgetConstants.tsx
> +export enum FontStyleTypes {
We need to write tests for functions in which we're referring to these constants.

2021-03-24 12:54 UTC, riodeuno approved these changes

2021-03-26 12:35 UTC, riodeuno approved these changes

2021-03-29 12:15 UTC, riodeuno approved these changes

2021-03-31 18:43 UTC, riodeuno approved these changes

2021-04-01 08:30 UTC, merged