Feature/property pane renovate map search
appsmithorg/appsmith pull request #3170
Opened 2021-02-23 11:19 UTC by ram-primathon

## Description
> add new style to location search input box

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-02-24 05:12 UTC, hetunandu requested changes

2021-02-24 05:12 UTC, hetunandu commented on app/client/src/components/propertyControls/LocationSearchControl.tsx
>  const StyledInput = styled.input`
Looking at this again, I think we can use the ads text input here as well. Can we try that instead?

2021-02-24 05:51 UTC, ram-primathon commented on app/client/src/components/propertyControls/LocationSearchControl.tsx
>  const StyledInput = styled.input`
done

2021-02-25 06:55 UTC, hetunandu approved these changes

2021-02-25 06:55 UTC, merged