Add feature to simultaneously modify and remove property paths in a widget
appsmithorg/appsmith pull request #3227
Opened 2021-02-25 19:14 UTC by riodeuno

## Description
Add feature to simultaneously modify and remove property paths in a widget

## Type of change
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
Manually

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-02-26 05:27 UTC, hetunandu requested changes

2021-02-26 05:27 UTC, hetunandu commented on app/client/src/sagas/WidgetOperationSagas.tsx
> +  }
Do this after you have removed the properties as well. Remove any dynamicList handling in the removal function

2021-02-26 05:27 UTC, hetunandu commented on app/client/src/constants/WidgetConstants.tsx
> +}
Move this definition to control actions next to the action creator function

2021-02-26 05:27 UTC, hetunandu commented on app/client/src/sagas/WidgetOperationSagas.tsx
> +function* deleteWidgetPropertySaga(
Route this to the batch update saga as well.

2021-02-26 05:27 UTC, hetunandu commented on app/client/src/sagas/WidgetOperationSagas.tsx
> +  const widgets = { ...stateWidgets, [widgetId]: widget };
Since we are not using UPDATE_WIDGET_PROPERTY any more, lets create an UPDATE_WIDGET where we can just send a widget. Will avoid such things all over the codebase

2021-02-26 10:43 UTC, riodeuno commented on app/client/src/sagas/WidgetOperationSagas.tsx
> +  const widgets = { ...stateWidgets, [widgetId]: widget };
Added this as a task for a separate issue #3246

2021-02-26 10:43 UTC, riodeuno commented on app/client/src/sagas/WidgetOperationSagas.tsx
> +  }
Added this as a task for a separate issue #3246

2021-03-01 06:54 UTC, hetunandu approved these changes

2021-03-01 09:45 UTC, merged