Feature/property pane renovate multi dropdown
appsmithorg/appsmith pull request #3237
Opened 2021-02-26 06:40 UTC by ram-primathon

## Description
> add ads multi select dropdown in propertypane

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-02-26 07:26 UTC, hetunandu requested changes

2021-02-26 07:26 UTC, hetunandu commented on app/client/src/components/ads/Dropdown.tsx
> +export const DropdownContainer = styled.div<{ width?: string }>`
Dont export. Just copy

2021-02-26 07:26 UTC, hetunandu commented on app/client/src/components/propertyControls/MultiSelectControl.tsx
> +    const isStarPresent = this.props.propertyValue.includes("*");
Create a new entry in dropdown option called `selectsAll`

2021-02-28 11:52 UTC, ram-primathon commented on app/client/src/components/ads/Dropdown.tsx
> +export const DropdownContainer = styled.div<{ width?: string }>`
done

2021-03-01 07:01 UTC, merged