[wip]: add new relic agent to the container
appsmithorg/appsmith pull request #32613
Opened 2024-04-11 13:14 UTC by pratapaprasanna

Fixes: #29892

2024-04-29 11:36 UTC, rajatagrawal commented
Where does a fresh system get the newrelic.yml file from ?

2024-05-01 12:14 UTC, sharat87 requested changes

2024-05-01 12:14 UTC, sharat87 commented on deploy/docker/fs/opt/appsmith/entrypoint.sh
> +EOL
Let's use `EOF` or `END` as the marker. `EOL` sounds like end-of-line, which this isn't.

2024-05-01 12:14 UTC, sharat87 commented on deploy/docker/base.dockerfile
> +RUN curl -o /opt/appsmith/newrelic-java.zip https://download.newrelic.com/newrelic/java-agent/newrelic-agent/8.9.1/newrelic-java-8.9.1.zip ; unzip /opt/appsmith/newrelic-java.zip -d /opt/appsmith/ ;
Looks like we're only using `newrelic.jar` file out of this download. Can we not download just that then?

```suggestion
# Add NewRelic Java agent
RUN mkdir /opt/newrelic \
  && curl -o /opt/newrelic/newrelic.jar https://download.newrelic.com/newrelic/java-agent/newrelic-agent/8.9.1/newrelic-agent-8.9.1.jar
```

Then, in Java args, we change the path to `newrelic.jar` from `/opt/appsmith/newrelic/newrelic.jar` to `/opt/newrelic/newrelic.jar`, and we don't have to install `unzip` either.

2024-05-03 07:00 UTC, pratapaprasanna commented
> Where does a fresh system get the newrelic.yml file from ?
> Can we use a custom version of new relic that is tracked in our github repo instead of downloading a fresh newrelic.yml in the setup ?
we are generating the file and not downloading it from web

2024-05-07 02:40 UTC, sharat87 submitted a review, later dismissed

2024-05-07 07:11 UTC, rajatagrawal commented
> > Where does a fresh system get the newrelic.yml file from ?
> > Can we use a custom version of new relic that is tracked in our github repo instead of downloading a fresh newrelic.yml in the setup ?
> > we are generating the file and not downloading it from web

@pratapaprasanna 

Can we please generate the newrelic yml file from [here](https://github.com/appsmithorg/cloud-deployment/blob/master/newrelic/newrelic.yml) ?

2024-05-07 07:12 UTC, rajatagrawal requested changes
Left feedback.

2024-05-23 04:26 UTC, rajatagrawal approved these changes

2024-06-02 16:34 UTC, closed without merging