chore: Add a pre-push hook to fail push if ee changes are present in the branch
appsmithorg/appsmith pull request #32791
Opened 2024-04-18 13:39 UTC by rajatagrawal

## Description
This PR adds a pre-push hook that checks if the diff between remote and local commits contain any files in ee folder on client end.

If the user does want to push these changes, the user can pass an environment variable VERIFIED_EE_CHANGES=1 like this: `VERIFIED_EE_CHANGES=1 git push origin HEAD`

Fixes #`Issue Number`  
_or_  
Fixes `Issue URL`
> [!WARNING]  
> _If no issue exists, please create an issue first, and check with the maintainers if the issue is valid._

## Automation

/ok-to-test tags=""

### :mag: Cypress test results

> [!CAUTION]  
> If you modify the content in this section, you are likely to disrupt the CI result for your PR.

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [ ] No

2024-04-22 10:32 UTC, KelvinOm reviewed
Why are we checking this at the push stage and not at the commit stage?

2024-04-23 02:17 UTC, rajatagrawal commented
> Why are we checking this at the push stage and not at the commit stage?

@KelvinOm We are doing this at the push stage because many times devs can do commit with --no-verify and push the changes to wip branch. However the likelihood and the need of doing a --no-verify push is less. Hence the checks are made for pre-push hook

2024-05-08 04:31 UTC, mohanarpit commented
Closing this PR for now.

2024-07-06 01:57 UTC, sharat87 commented
@rajatagrawal @KelvinOm, I think the reason we need to do this at `pre-push` and not `pre-commit`, is because the commit happened on the EE repo. We pulled in EE commits into our CE repo folder, so the commits are already done. The `pre-commit` hook never gets a chance to prevent this. That's why we need to do this at `pre-push`.

2024-07-06 01:57 UTC, sharat87 commented
Reopening as we've had more occurrences of this recently.

2024-07-06 02:14 UTC, sharat87 requested changes

2024-07-06 02:14 UTC, sharat87 commented on app/client/.husky/pre-push
> +        fi
Not sure I understand this. If we found EE changes, shouldn't we immediately `exit 1`?

2024-07-06 02:14 UTC, sharat87 commented on app/client/.husky/pre-push
> +        echo -e "Didn't find ee changes in the commit\n"
```suggestion
        echo "Didn't find EE changes in any of the commits to be pushed"
```

2024-07-06 02:14 UTC, sharat87 commented on app/client/.husky/pre-push
> +    then
This can be simplified to this:

```suggestion
    if ! git diff --quiet "$remote_sha" "$local_sha" app/client/src/ee; then
```

2024-07-11 09:22 UTC, closed without merging