feat: On Canvas UI Colors and Widget API to consume these colors
appsmithorg/appsmith pull request #33013
Opened 2024-04-29 06:37 UTC by riodeuno

## Description
> [!TIP]  
> _Add a TL;DR when the description is longer than 500 words or extremely technical (helps the content, marketing, and DevRel team)._
>
> _Please also include relevant motivation and context. List any dependencies that are required for this change. Add links to Notion, Figma or any other documents that might be relevant to the PR._

Fixes #`Issue Number`  
_or_  
Fixes `Issue URL`
> [!WARNING]  
> _If no issue exists, please create an issue first, and check with the maintainers if the issue is valid._

## Automation

/ok-to-test tags=""

### :mag: Cypress test results

> [!CAUTION]  
> If you modify the content in this section, you are likely to disrupt the CI result for your PR.

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [ ] No

2024-04-29 06:44 UTC, riodeuno commented
@riodeuno 
Note: Due to the fact that we've updated the main container resizer z-index. Let's confirm if this works in the final PR.

2024-05-01 04:59 UTC, marks0351 requested changes

2024-05-01 04:59 UTC, marks0351 commented on app/client/src/WidgetProvider/factory/index.tsx
> +      onCanvasUI,
I wonder why do we want it to be a part of widget config. since the config is used only by an editor component.

2024-05-01 06:30 UTC, riodeuno commented on app/client/src/WidgetProvider/factory/index.tsx
> +     * We're going to prioritise #21825.
@marks0351

2024-05-01 06:31 UTC, riodeuno commented on app/client/src/WidgetProvider/factory/index.tsx
> +      onCanvasUI,
I'm not sure what your concern is. Widgets owning configurations specific to the editor seem like a perfectly fine approach.
If you can share an alternative, it will help me understand your viewpoint.

2024-05-01 07:14 UTC, marks0351 commented on app/client/src/WidgetProvider/factory/index.tsx
> +      onCanvasUI,
since the scope of using the config is only on the editor component and also for Anvil. The current widget name and how it figures out the parent all this will not be relavants with other layout systems which leads me to belive that we will keep widget name as is in those systems. which is why I think we should just use the `getWidgetHierarchy` to get the hierarchy of a widget and just set the color system of the widget name component.

2024-05-01 07:52 UTC, riodeuno commented on app/client/src/WidgetProvider/factory/index.tsx
> +      onCanvasUI,
Yes. WidgetHierarchy is the most straightforward change.
However, there are multiple reasons for using an API approach.
- It may be used by UI modules for module widgets.
- It loosely coupled and keeps the ownership of configurations with the widgets.

The only con that I see is that it will store this configurations in the DSL, but for that we'll be picking up #21825 in the upcoming sprint.

2024-05-01 08:26 UTC, marks0351 commented on app/client/src/WidgetProvider/factory/index.tsx
> +      onCanvasUI,
approving this. 
however I still think the change in color codes is not based on individual widgets but is clearly based on hierarchy which exclusively only makes sense in Anvil.

2024-05-01 08:26 UTC, marks0351 approved these changes

2024-05-01 08:27 UTC, merged