fix propertypane header
appsmithorg/appsmith pull request #3302
Opened 2021-03-02 03:43 UTC by ram-primathon

## Description
> fix propertypane header

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-03-04 04:46 UTC, hetunandu requested changes

2021-03-04 04:46 UTC, hetunandu commented on app/client/src/components/ads/EditableText.tsx
> +    width: 100%;
Why did we remove this? Api pane styles are affected by this

2021-03-04 04:46 UTC, hetunandu commented on app/client/src/components/ads/EditableText.tsx
> +        // onTextChanged && onTextChanged(finalVal);
Why is this not necessary anymore

2021-03-04 04:46 UTC, hetunandu commented on app/client/src/pages/Editor/PropertyPaneTitle.tsx
> +const Wrapper = styled.div<{ isPropertyTitle: boolean }>`
rename to `isPanelTitle`

2021-03-04 04:46 UTC, hetunandu commented on app/client/src/pages/Editor/PropertyPaneTitle.tsx
> +      )}
Not the correct way to handle this. You need to make this composable from outside

2021-03-04 04:46 UTC, hetunandu commented on app/client/src/pages/Editor/PropertyPaneTitle.tsx
> +  return props.widgetId || props.updatePropertyTitle ? (
`updatePropertyTitle` is a wrong way to handle this

2021-03-04 06:27 UTC, ram-primathon commented on app/client/src/components/ads/EditableText.tsx
> +        // onTextChanged && onTextChanged(finalVal);
this was responsible to start loader on enter of every character

2021-03-04 06:28 UTC, ram-primathon commented on app/client/src/pages/Editor/PropertyPaneTitle.tsx
> +const Wrapper = styled.div<{ isPropertyTitle: boolean }>`
done

2021-03-04 06:34 UTC, hetunandu commented on app/client/src/components/ads/EditableText.tsx
> +        // onTextChanged && onTextChanged(finalVal);
Revert this change. I have already fixed that on the main branch

2021-03-04 06:36 UTC, ram-primathon commented on app/client/src/pages/Editor/PropertyPaneTitle.tsx
> +      )}
added 4 different propps for each

2021-03-04 06:38 UTC, hetunandu commented on app/client/src/pages/Editor/PropertyPaneTitle.tsx
> +      )}
You need to make it composable. What this means it that you can add children from outside if you need more icons. 
```
<PropertyPaneTitle
   ....
   actions={(
     <DeleteIcon />
     <CopyIcon/>
   )}
/>
```

2021-03-04 06:38 UTC, ram-primathon commented on app/client/src/pages/Editor/PropertyPaneTitle.tsx
> +  return props.widgetId || props.updatePropertyTitle ? (
added a props 

isPanelTitle

2021-03-04 06:49 UTC, ram-primathon commented on app/client/src/components/ads/EditableText.tsx
> +    width: 100%;
revert back

2021-03-04 06:49 UTC, ram-primathon commented on app/client/src/components/ads/EditableText.tsx
> +        // onTextChanged && onTextChanged(finalVal);
done

2021-03-04 06:52 UTC, hetunandu requested changes

2021-03-04 06:52 UTC, hetunandu commented on app/client/src/pages/Editor/PropertyPaneTitle.tsx
> +  hideCloseIcon?: boolean;
Make this composable

2021-03-04 06:55 UTC, ram-primathon commented on app/client/src/pages/Editor/PropertyPaneTitle.tsx
> +      )}
How are we suppose to bind click method with it?

2021-03-05 04:41 UTC, hetunandu approved these changes

2021-03-05 04:41 UTC, merged