feat: Anvil Widget Name Component
appsmithorg/appsmith pull request #33062
Opened 2024-04-30 11:19 UTC by riodeuno

## Description
> [!TIP]  
> _Add a TL;DR when the description is longer than 500 words or extremely technical (helps the content, marketing, and DevRel team)._
>
> _Please also include relevant motivation and context. List any dependencies that are required for this change. Add links to Notion, Figma or any other documents that might be relevant to the PR._

Fixes #`Issue Number`  
_or_  
Fixes `Issue URL`
> [!WARNING]  
> _If no issue exists, please create an issue first, and check with the maintainers if the issue is valid._

## Automation

/ok-to-test tags=""

### :mag: Cypress test results

> [!CAUTION]  
> If you modify the content in this section, you are likely to disrupt the CI result for your PR.

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [x] No

2024-05-01 05:18 UTC, marks0351 requested changes

2024-05-01 05:18 UTC, marks0351 commented on app/client/src/layoutSystems/anvil/editor/widgetName/Component.tsx
> +    [widgetId],
don't think u need this dependency.

2024-05-01 05:18 UTC, marks0351 commented on app/client/src/layoutSystems/anvil/editor/widgetName/Component.tsx
> +  }, []);
widgetId seems to be a dependency here.

2024-05-01 05:18 UTC, marks0351 commented on app/client/src/layoutSystems/anvil/editor/widgetName/SplitButton.tsx
> +import ErrorIcon from "./error.svg";
should it be part of appsmith-icons?

2024-05-01 05:18 UTC, marks0351 commented on app/client/src/layoutSystems/anvil/editor/widgetName/index.tsx
> +export function useWidgetName(
This is a hook and yet it renders components.
Why is it not a Component?

2024-05-01 05:18 UTC, marks0351 commented on app/client/src/layoutSystems/anvil/editor/widgetName/index.tsx
> +  const widgetType = useSelector(
can we get widget type as well as a part of  props.

2024-05-01 05:18 UTC, marks0351 commented on app/client/src/layoutSystems/anvil/editor/widgetName/utils.ts
> +    "#anvil_widget_" + widgetId,
getAnvilWidgetDOMId should be used to form the selector.

2024-05-01 05:18 UTC, marks0351 commented on app/client/src/layoutSystems/anvil/messages.ts
> +export const ANVIL_WIDGET_NAME_TOGGLE_PARENT = () => "Select parent widget";
we have a messages file in app/client/src/layoutSystems/anvil/common lets use that.

2024-05-01 06:48 UTC, riodeuno commented on app/client/src/layoutSystems/anvil/editor/widgetName/SplitButton.tsx
> +import ErrorIcon from "./error.svg";
These actually belong in ADS. I need to find out where to put them. Creating an issue for this.

2024-05-01 07:36 UTC, marks0351 submitted a review, later dismissed

2024-05-01 08:43 UTC, marks0351 submitted a review, later dismissed

2024-05-01 10:23 UTC, riodeuno commented on app/client/src/layoutSystems/anvil/editor/widgetName/SplitButton.tsx
> +    border-inline-end: var(--ads-on-canvas-ui-border-radius);
Move these CSS to Editor styles.modules.css

2024-05-01 10:24 UTC, riodeuno commented on app/client/src/layoutSystems/anvil/editor/widgetName/Component.tsx
> +export function WidgetNameComponent(
Rename this file to WidgetNameComponent

2024-05-01 10:26 UTC, riodeuno commented on app/client/src/layoutSystems/anvil/editor/widgetName/Component.tsx
> +      id={`widget-name-${widgetId}`}
Confirm if this is being used, if not, remove it.

2024-05-01 10:27 UTC, riodeuno commented on app/client/src/layoutSystems/anvil/editor/widgetName/index.tsx
> +export function WidgetName(props: {
Rename folder to be `WidgetName`

2024-05-01 10:30 UTC, marks0351 commented on app/client/src/layoutSystems/anvil/editor/widgetName/Component.tsx
> +export function WidgetNameComponent(
lets prefix with Anvil we already have a WidgetNameComponent

2024-05-01 11:35 UTC, KelvinOm commented on app/client/package.json
> +    "@floating-ui/dom": "^1.6.4",
We already have `@floating-ui/react` library. It's same, but react related. You can use it.

2024-05-01 11:35 UTC, KelvinOm commented on app/client/src/layoutSystems/anvil/editor/widgetName/Component.tsx
> +    (state) => getWidgetErrorCount(state, widgetId) > 0,
I think we can just pass this as a prop into this component and untie it from the state. After all, we have everything for this at a higher level, don't we? This way the code turns out to be cleaner and more reliable.

2024-05-01 11:35 UTC, KelvinOm commented on app/client/src/layoutSystems/anvil/editor/widgetName/Component.tsx
> +      e.stopPropagation();
Could you leave a comment on why this is necessary? Limiting events is not a good practice.

2024-05-01 11:35 UTC, KelvinOm commented on app/client/src/layoutSystems/anvil/editor/widgetName/Component.tsx
> +  const handleDebugClick = useCallback((e: React.MouseEvent) => {
Why are we use `preventDefault` and `stopPropagation` this for `handleMouseOver` and `handleDebugClick` methods?

2024-05-01 11:35 UTC, KelvinOm commented on app/client/src/layoutSystems/anvil/editor/widgetName/Component.tsx
> +  let _bgCSSVar = props.bGCSSVar;
It is better to pass props that highlight what has changed and use CSS variables within the component. It's not obvious what's going on here right now.

2024-05-01 11:35 UTC, KelvinOm commented on app/client/src/layoutSystems/anvil/editor/widgetName/Component.tsx
> +const widgetNameStyles: CSSProperties = {
Why do we need to additionally send styles via a prop? I don't see them being applied conditionally. It seems they can simply be used directly in the component.

2024-05-01 11:35 UTC, KelvinOm commented on app/client/src/layoutSystems/anvil/editor/widgetName/SplitButton.tsx
> +      draggable
Why we need `draggable` here?

2024-05-01 11:35 UTC, KelvinOm commented on app/client/src/layoutSystems/anvil/editor/widgetName/SplitButton.tsx
> +      $disableLeftSpan={props.leftToggle.disable}
```suggestion
      $isLeftToggleDisabled={props.leftToggle.disable}
```

same for right

2024-05-01 11:35 UTC, KelvinOm commented on app/client/src/layoutSystems/anvil/editor/widgetName/SplitButton.tsx
> +          aria-expanded="false"
I believe that `floating-ui` should returns all the necessary arrts via the `getReferenceProps` and `getFloatingProps` methods.

2024-05-02 05:13 UTC, riodeuno commented on app/client/src/layoutSystems/anvil/editor/widgetName/Component.tsx
> +const widgetNameStyles: CSSProperties = {
Yep, I'll use styles via CSS instead of style prop.

2024-05-02 05:13 UTC, riodeuno commented on app/client/src/layoutSystems/anvil/editor/widgetName/Component.tsx
> +export function WidgetNameComponent(
Will do

2024-05-02 05:15 UTC, riodeuno commented on app/client/src/layoutSystems/anvil/editor/widgetName/Component.tsx
> +    (state) => getWidgetErrorCount(state, widgetId) > 0,
No, we actually don't have this state in the parent component. So, we'll have to add this selector there anyway.

2024-05-02 05:19 UTC, riodeuno commented on app/client/src/layoutSystems/anvil/editor/widgetName/SplitButton.tsx
> +      draggable
This enables the `dragStart` event for the widget. Allows us to move the widget using the widget name component as a handle.

2024-05-02 05:38 UTC, riodeuno commented on app/client/package.json
> +    "@floating-ui/dom": "^1.6.4",
I prefer the API for the @floating-ui/dom, it is a lower level API and easy for me to configure.

2024-05-02 06:14 UTC, riodeuno commented on app/client/src/layoutSystems/anvil/editor/widgetName/Component.tsx
> +      e.stopPropagation();
Removing for now. Will need it in the next PR. I'll add the comment then.

2024-05-02 06:14 UTC, riodeuno commented on app/client/src/layoutSystems/anvil/editor/widgetName/SplitButton.tsx
> +          aria-expanded="false"
I'm not sure I fully get this. Are you talking about the `ref`?

2024-05-02 07:04 UTC, riodeuno commented on app/client/src/layoutSystems/anvil/editor/widgetName/Component.tsx
> +    (state) => getWidgetErrorCount(state, widgetId) > 0,
I have nevertheless moved it to the parent.

2024-05-02 07:10 UTC, riodeuno commented on app/client/src/layoutSystems/anvil/editor/canvas/styles/anvilEditorVariables.css
> +  --on-canvas-ui-on-canvas-ui-zindex: 998;
I'll remove this duplicate in the next PR.

2024-05-02 08:51 UTC, riodeuno commented on app/client/src/layoutSystems/anvil/editor/canvas/styles/anvilEditorVariables.css
> +  --on-canvas-ui-on-canvas-ui-zindex: 998;
Done, it is fixed in the other PR #33128

2024-05-02 09:04 UTC, KelvinOm commented on app/client/package.json
> +    "@floating-ui/dom": "^1.6.4",
What is the difference in the API? In addition, with this approach, we will use two libraries that do the same thing, and these are unnecessary files in our final bundle. Also, for developers who will maintain the code, this will be an additional complexity.

2024-05-02 09:08 UTC, KelvinOm commented on app/client/src/layoutSystems/anvil/editor/widgetName/SplitButton.tsx
> +          aria-expanded="false"
Take a look at [this example](https://codesandbox.io/p/sandbox/cranky-river-ifx8s9?file=/src/App.tsx:53,1-54,1). If you call the getReferenceProps method on the trigger, it will return all the necessary properties. 

In addition, these attrs should change depending on whether the pop-up is open or not. This is not in your code.

2024-05-02 09:29 UTC, marks0351 approved these changes

2024-05-02 09:54 UTC, jsartisan commented on app/client/package.json
> +    "@floating-ui/dom": "^1.6.4",
> In addition, with this approach, we will use two libraries that do the same thing, and these are unnecessary files in our final bundle.

AFAIK `@floating-ui/react` just uses API of `@floating-ui/dom` only. So bundle size won't get impacted much. 
Using either `@floating-ui/react` or `@floating-ui/dom` depends on the use case IMO.
For e.g - `@floating-ui/react` is best when using it in components. We get hooks from the package to use directly.

2024-05-02 10:11 UTC, KelvinOm commented on app/client/package.json
> +    "@floating-ui/dom": "^1.6.4",
Anyway, I don't see the point of using a vanilla library in the context of a react when we have a react-specific library. API also should be the same as I see.

2024-05-02 10:42 UTC, riodeuno commented on app/client/src/layoutSystems/anvil/editor/widgetName/SplitButton.tsx
> +          aria-expanded="false"
I get it now. Thanks for sharing @KelvinOm . 
What I have used is the lower level `computePosition` API and haven't used the `React` APIs. I'll create a task to migrate to the React APIs, then I should be able to leverage these.

2024-05-02 10:46 UTC, riodeuno commented on app/client/src/layoutSystems/anvil/editor/widgetName/SplitButton.tsx
> +          aria-expanded="false"
Issue #33134

2024-05-02 10:47 UTC, riodeuno commented on app/client/package.json
> +    "@floating-ui/dom": "^1.6.4",
Issue #33134

2024-05-02 10:49 UTC, riodeuno commented on app/client/src/widgets/anvil/ZoneWidget/widget/config/baseConfig.ts
> +    focusColorCSSVar: "--on-canvas-ui-zone-selection",
This is intentional. The focus colors and selection colors for background and foreground get swapped.

2024-05-02 10:50 UTC, riodeuno commented
/build-deplooy-preview skip-tests=true

2024-05-02 10:51 UTC, riodeuno commented
/build-deploy-preview skip-tests=true

2024-05-02 12:22 UTC, KelvinOm approved these changes

2024-05-03 10:20 UTC, merged