Update profile name and photo
appsmithorg/appsmith pull request #3306
Opened 2021-03-02 05:34 UTC by akash-codemonk

## Description
> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation 
> and context. List any dependencies that are required for this change.

Fixes # (issue)
> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce. 
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-03-03 17:39 UTC, rishabhsaxena requested changes
Also we should remove `reset-password` route from redirecting to `/applications` when the user is logged in, since they might be logged in while following the reset password flow

2021-03-03 17:39 UTC, rishabhsaxena commented on app/client/src/AppRouter.tsx
> +    trimTrailingSlash(window.location.pathname) === "/profile"
We can probably use theme colors here as well instead of calling `changeAppBackground`?

2021-03-03 17:39 UTC, rishabhsaxena commented on app/client/src/pages/UserProfile/General.tsx
> +            cypressSelector="t--display-name"
Is there a diff b/w `cypressSelector` and `data-cy`, asking just out of curiosity?

2021-03-03 17:39 UTC, rishabhsaxena commented on app/client/src/pages/UserProfile/index.tsx
> +            color="#9F9F9F"
Should use colors via theme

2021-03-03 17:39 UTC, rishabhsaxena commented on app/client/src/pages/common/ProfileDropdown.tsx
>  import { CommonComponentProps, Classes } from "components/ads/common";
The name and email are not taking the full width of the container

2021-03-04 05:05 UTC, akash-codemonk commented
> Also we should remove `reset-password` route from redirecting to `/applications` when the user is logged in, since they might be logged in while following the reset password flow

I think it makes sense to logout the user here if they intend to change their password.

2021-03-04 06:10 UTC, akash-codemonk commented on app/client/src/AppRouter.tsx
> +    trimTrailingSlash(window.location.pathname) === "/profile"
Yes theme color is being used here in changeAppBackground.
I think this is required to set the background of the `<body>` https://github.com/appsmithorg/appsmith/blob/feat/user-profile/app/client/src/AppRouter.tsx#L78 in the home page screens.

2021-03-04 06:14 UTC, akash-codemonk commented on app/client/src/pages/UserProfile/General.tsx
> +            cypressSelector="t--display-name"
`cypressSelector` is a prop here for the `TextInput` which is being use to set the value of `data-cy`. I am guessing `data-cy` has effect only on html elements so it's being used internally in `TextInput` component.

2021-03-04 07:53 UTC, rishabhsaxena commented
Actually not sure about logging the user out here, one case I can think of is if somehow the token expires and the user is logged out he won't be able login if he forgot his password..

2021-03-04 07:58 UTC, akash-codemonk commented
> Actually not sure about logging the user out here, one case I can think of is if somehow the token expires and the user is logged out he won't be able login if he forgot his password..

In this scenario the user would be able to reset password from signup screen right?

2021-03-04 08:02 UTC, rishabhsaxena commented
ok yeah that can be done actually 😅
The flow still feels odd though since it's not necessary?

2021-03-04 08:07 UTC, rishabhsaxena commented
> > Also we should remove `reset-password` route from redirecting to `/applications` when the user is logged in, since they might be logged in while following the reset password flow
> 
> I think it makes sense to logout the user here if they intend to change their password.

Not sure, maybe @Nikhil-Nandagopal or @hetunandu can confirm?

2021-03-04 08:08 UTC, rishabhsaxena approved these changes

2021-03-04 09:33 UTC, akash-codemonk commented
Merging it for now after internal discussion.

2021-03-04 09:37 UTC, merged