test: Fix Partially import spec
appsmithorg/appsmith pull request #33090
Opened 2024-05-01 06:27 UTC by NandanAnantharamu

2024-05-01 06:27 UTC, NandanAnantharamu commented
/ci-test-limit

2024-05-01 09:02 UTC, NandanAnantharamu commented
/ci-test-limit runId=8906254185

2024-05-01 10:04 UTC, NandanAnantharamu commented
/ci-test-limit runId=8906254185

2024-05-01 10:27 UTC, NandanAnantharamu commented
/ci-test-limit runId=8906254185

2024-05-01 11:12 UTC, NandanAnantharamu commented
/ci-test-limit runId=8906254185

2024-05-01 11:12 UTC, NandanAnantharamu commented
/ci-test-limit runId=8906254185

2024-05-01 11:12 UTC, NandanAnantharamu commented
/ci-test-limit runId=8906254185

2024-05-01 11:12 UTC, NandanAnantharamu commented
/ci-test-limit runId=8906254185

2024-05-01 11:12 UTC, NandanAnantharamu commented
/ci-test-limit runId=8906254185

2024-05-01 11:12 UTC, NandanAnantharamu commented
/ci-test-limit runId=8906254185

2024-05-01 11:12 UTC, NandanAnantharamu commented
/ci-test-limit runId=8906254185

2024-05-01 11:12 UTC, NandanAnantharamu commented
/ci-test-limit runId=8906254185

2024-05-01 11:12 UTC, NandanAnantharamu commented
/ci-test-limit runId=8906254185

2024-05-01 11:12 UTC, NandanAnantharamu commented
/ci-test-limit runId=8906254185

2024-05-01 13:29 UTC, ApekshaBhosale requested changes

2024-05-01 13:29 UTC, ApekshaBhosale commented on app/client/cypress/support/Pages/HomePage.ts
> +    this.agHelper.Sleep(1500);
do we need this sleep here? @NandanAnantharamu can we not have this please

2024-05-01 14:33 UTC, mohanarpit commented on app/client/cypress/support/Pages/HomePage.ts
> +    this.agHelper.ValidateToastMessage("Application imported successfully");
@ApekshaBhosale @NandanAnantharamu Can we ensure we don't compare against raw strings like this? Can we refer to `messages.ts` constants file? If the string doesn't exist in `messages.ts`, it's an opportunity to do a minor refactor & add the raw string to the constants file.

2024-05-01 17:24 UTC, NandanAnantharamu commented on app/client/cypress/support/Pages/HomePage.ts
> +    this.agHelper.ValidateToastMessage("Application imported successfully");
@ApekshaBhosale i have added this message to messages.ts please check and let me know if its fine

2024-05-01 17:24 UTC, NandanAnantharamu commented
/ci-test-limit runId=8906254185

2024-05-01 17:25 UTC, NandanAnantharamu commented
/ci-test-limit runId=8906254185

2024-05-01 17:25 UTC, NandanAnantharamu commented
/ci-test-limit runId=8906254185

2024-05-01 17:36 UTC, NandanAnantharamu commented
/ci-test-limit runId=8906254185

2024-05-01 17:36 UTC, NandanAnantharamu commented
/ci-test-limit runId=8906254185

2024-05-01 17:36 UTC, NandanAnantharamu commented
/ci-test-limit runId=8906254185

2024-05-01 17:50 UTC, NandanAnantharamu commented
/ci-test-limit runId=8906254185

2024-05-01 17:50 UTC, NandanAnantharamu commented
/ci-test-limit runId=8906254185

2024-05-01 17:50 UTC, NandanAnantharamu commented
/ci-test-limit runId=8906254185

2024-05-01 17:51 UTC, NandanAnantharamu commented
/ci-test-limit runId=8906254185

2024-05-01 17:51 UTC, NandanAnantharamu commented
/ci-test-limit runId=8906254185

2024-05-02 06:43 UTC, NandanAnantharamu commented
/ci-test-limit

2024-05-02 08:56 UTC, NandanAnantharamu commented
/ci-test-limit runId=8919747385

2024-05-02 09:27 UTC, NandanAnantharamu commented
/ci-test-limit runId=8919747385

2024-05-02 09:27 UTC, NandanAnantharamu commented
/ci-test-limit runId=8919747385

2024-05-02 09:27 UTC, NandanAnantharamu commented
/ci-test-limit runId=8919747385

2024-05-02 10:36 UTC, NandanAnantharamu commented
/ci-test-limit runId=8919747385

2024-05-02 10:36 UTC, NandanAnantharamu commented
/ci-test-limit runId=8919747385

2024-05-02 10:36 UTC, NandanAnantharamu commented
/ci-test-limit runId=8919747385

2024-05-02 10:36 UTC, NandanAnantharamu commented
/ci-test-limit runId=8919747385

2024-05-02 11:57 UTC, NandanAnantharamu commented
/ok-to-test tags="@tag.Workspace @tag.ImportExport"

2024-05-02 13:40 UTC, NandanAnantharamu commented
/ok-to-test tags="@tag.Workspace @tag.ImportExport"

2024-05-03 09:37 UTC, NandanAnantharamu commented
/ok-to-test tags="@tag.Workspace @tag.ImportExport"

2024-05-03 09:51 UTC, NandanAnantharamu commented
/ok-to-test tags="@tag.Workspace,@tag.ImportExport"

2024-05-03 09:54 UTC, NandanAnantharamu commented
/ok-to-test tags="@tag.Workspace,@tag.ImportExport"

2024-05-03 16:09 UTC, NandanAnantharamu commented
/ok-to-test tags="@tag.Workspace,@tag.ImportExport"

2024-05-06 15:27 UTC, trishaanand approved these changes

2024-05-07 05:53 UTC, merged