chore: Add API for storing dependencyMap in page object
appsmithorg/appsmith pull request #33296
Opened 2024-05-08 14:57 UTC by AnaghHegde

## Description
The dependencyMap consumes considerable computation on the frontend. We would like to persist that in the backend for every page in an application.

For details on the signature and payload of the api calls please refer [this document](https://www.notion.so/appsmith/Solution-design-dependencyMap-0c031675f13140f7a433c731b3e45470?pvs=4#1ee6692b74804422a80cba86cc9ba87f)

Fixes https://github.com/appsmithorg/appsmith/issues/33030

## Automation

/ok-to-test tags=""

### :mag: Cypress test results

> [!CAUTION]  
> If you modify the content in this section, you are likely to disrupt the CI result for your PR.

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [ ] No

2024-05-08 15:01 UTC, AnaghHegde commented
/build-deploy-preview skip-tests=true

2024-05-10 09:29 UTC, dvj1988 commented
/build-deploy-preview skip-tests=true

2024-05-13 06:22 UTC, AnaghHegde commented
/build-deploy-preview skip-tests=true

2024-05-17 07:16 UTC, NilanshBansal requested changes

2024-05-17 07:16 UTC, NilanshBansal commented on app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewPageRepositoryCEImpl.java
> +        Criteria pageCriteria = where(NewPage.Fields.id).is(pageId);
Nit: can we use BridgeUpdate query here. Similar usage code ref below.
https://github.com/appsmithorg/appsmith/blob/3e06f1a5704d1303328751b0093663c14330d8ce/app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewActionRepositoryCEImpl.java#L376-L383

Why use Bridge APIs?
https://theappsmith.slack.com/archives/CPQNLFHTN/p1710836011164579

2024-05-17 07:44 UTC, NilanshBansal commented
@AnaghHegde since you are adding a new field `dependencyMap` in the PageDTO, can you please do a sanity check for the following cases. 
- Is this field exported to the git repository for git-connected apps?
- How will this work for import export? Can consider scenarios - an old JSON imported to the current version, what will be the value of these fields in the DB (I believe this should be null and should be okay but you can still check once).
- On exporting the current version JSON, is the `dependencyMap` field exported?

cc: @rahulbarwal

2024-05-17 09:45 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewPageRepositoryCEImpl.java
> +        Criteria pageCriteria = where(NewPage.Fields.id).is(pageId);
Thanks for flagging this ❤️

2024-05-20 04:10 UTC, NilanshBansal commented
> @AnaghHegde since you are adding a new field `dependencyMap` in the PageDTO, can you please do a sanity check for the following cases.
> 
> * Is this field exported to the git repository for git-connected apps?
> * How will this work for import export? Can consider scenarios - an old JSON imported to the current version, what will be the value of these fields in the DB (I believe this should be null and should be okay but you can still check once).
> * On exporting the current version JSON, is the `dependencyMap` field exported?
> 
> cc: @rahulbarwal

@AnaghHegde @rahulbarwal can you please confirm if you have checked this?

2024-05-20 05:39 UTC, mohanarpit commented on app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/PageControllerCE.java
> +    @PutMapping("/{defaultPageId}/dependencyMap")
For my information, any reason we chose to do this as a separate endpoint instead of part of update page layout? Would having a separate endpoint cause a race condition between saving the updated page and saving the new dependency map?

2024-05-22 05:11 UTC, dvj1988 commented
/build-deploy-preview skip-tests=true

2024-05-24 04:08 UTC, dvj1988 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/PageControllerCE.java
> +    @PutMapping("/{defaultPageId}/dependencyMap")
This is a valid concern and we don't have a robust approach at the moment. We are reducing the scope to use the dependency map cache only in the view mode for now. When a user publishes the application, we will trigger the updateDependencyMap API followed by the publish API. The dependency map in the unpublished version will reflect the last published version, and it will be updated with each publish.
We will get back to edit mode dependency maps later when we have a better approach for invalidation of older dependency maps.
@AnaghHegde For the time being we can go ahead with this approach.
cc: @rajatagrawal

2024-05-27 10:16 UTC, AnaghHegde commented
@NilanshBansal We are good from git and export point of view.

2024-05-27 10:34 UTC, NilanshBansal approved these changes
Considering @mohanarpit's comment [here](https://github.com/appsmithorg/appsmith/pull/33296#discussion_r1606271991) is addressed, this LGTM.

2024-05-27 11:27 UTC, dvj1988 commented
/build-deploy-preview skip-tests=true

2024-05-31 09:08 UTC, merged