WIP
appsmithorg/appsmith pull request #33306
Opened 2024-05-09 05:25 UTC by dvj1988

## Description
> [!TIP]  
> _Add a TL;DR when the description is longer than 500 words or extremely technical (helps the content, marketing, and DevRel team)._
>
> _Please also include relevant motivation and context. List any dependencies that are required for this change. Add links to Notion, Figma or any other documents that might be relevant to the PR._

Fixes #`Issue Number`  
_or_  
Fixes `Issue URL`
> [!WARNING]  
> _If no issue exists, please create an issue first, and check with the maintainers if the issue is valid._

## Automation

/ok-to-test tags=""

### :mag: Cypress test results

> [!CAUTION]  
> If you modify the content in this section, you are likely to disrupt the CI result for your PR.

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [ ] No

2024-05-09 05:25 UTC, dvj1988 commented
/build-deploy-preview skip-tests=true

2024-05-10 05:22 UTC, dvj1988 commented
/build-deploy-preview skip-tests=true

2024-05-10 05:30 UTC, dvj1988 commented on app/client/craco.dev.config.js
> +  webpack: {
Revert this. This change is required only for testing

2024-05-10 09:55 UTC, dvj1988 commented
/build-deploy-preview skip-tests=true

2024-05-12 18:10 UTC, dvj1988 commented
/build-deploy-preview skip-tests=true

2024-05-13 03:51 UTC, dvj1988 commented on app/client/src/App.css
> +  color: red;
Revert this change

2024-05-13 03:51 UTC, dvj1988 commented on app/client/src/ce/AppRouter.tsx
> +  useEffect(() => {}, [safeCrash]);
Revert this change

2024-05-13 03:51 UTC, dvj1988 commented
/build-deploy-preview skip-tests=true

2024-05-13 06:34 UTC, dvj1988 commented
/build-deploy-preview skip-tests=true

2024-05-13 09:52 UTC, dvj1988 commented
/build-deploy-preview skip-tests=true

2024-05-13 15:55 UTC, dvj1988 commented
/build-deploy-preview skip-tests=true

2024-05-13 16:49 UTC, dvj1988 commented
/build-deploy-preview skip-tests=true

2024-05-13 17:50 UTC, dvj1988 commented on app/client/src/ce/AppRouter.tsx
> +
This was a dummy commit. I have reverted this change

2024-05-13 17:51 UTC, dvj1988 commented on app/client/src/ce/AppRouter.tsx
> +
Can you review the PR again and update the summary?

2024-05-14 04:34 UTC, vsvamsi1 commented on app/client/src/utils/serviceWorkerUtils.js
> +          // Store in cache with expiration header
Why do we need to clone here? I thought the code will look like something like this.
`
    const fetchPromise = await fetch(request)
    if( response.ok){
              const resp = await response.json();

`

2024-05-14 04:57 UTC, rajatagrawal commented on app/client/src/utils/serviceWorkerUtils.js
> +      .then(async (response) => {
Would it be possible to use async-await here ?

2024-05-14 04:58 UTC, rajatagrawal commented on app/client/src/utils/serviceWorkerUtils.js
> +    this.pendingApiRequests = new Map();
Are there advantages of using Map over a simple javascript object ?

2024-05-14 04:58 UTC, dvj1988 commented on app/client/src/utils/serviceWorkerUtils.js
> +      .then(async (response) => {
This fn returns the promise and not its result. So the callback had to be defined by chaining.

2024-05-14 05:11 UTC, rajatagrawal commented on app/client/src/utils/serviceWorkerUtils.test.js
> +      const pathName = "/app/customSlug-custom-456";
Is `custom` part of `customSlug` ? Should it be included in result.params ?

2024-05-14 05:14 UTC, rajatagrawal commented on app/client/src/utils/serviceWorkerUtils.test.js
> +      expect(result.params).toHaveProperty("pageId", "123");
Can we have a test case where the pageId is alphanumeric ? It may already by working, but having a test case will just ensure that the code logic will not break for alphanumeric pageIds. The pageIDs would be alphanumeric on prod.

2024-05-14 05:16 UTC, rajatagrawal commented on app/client/src/utils/serviceWorkerUtils.test.js
> +    it("should not match when the path is edit widgets", () => {
Typo in the test description: `should not` -> `should`

2024-05-14 08:04 UTC, rajatagrawal commented on app/client/craco.dev.config.js
> +  webpack: {
Does this change need to be reverted ?

2024-05-14 08:20 UTC, rajatagrawal commented on app/client/src/serviceWorker.js
> +  const networkHandler = new NetworkOnly();
Is this supposed to be part of if/else above this line ?

2024-05-14 09:20 UTC, vsvamsi1 commented on app/client/src/utils/serviceWorkerUtils.test.js
> +
Can we have a set of test cases with "AppsmithApiCacheStrategy" integrated in our data layer?

2024-05-14 10:06 UTC, dvj1988 commented on app/client/src/utils/serviceWorkerUtils.test.js
> +
Main bundle (Redux sagas and other modules) do not interact with the service worker code and the integration is through the browser apis. To test the end to end flow we need a browser environment and hence cypress would be the best place for this.

2024-05-14 10:09 UTC, dvj1988 commented on app/client/src/serviceWorker.js
> +  const networkHandler = new NetworkOnly();
No. This is part of the normal fetch behaviour for all pages and the if block is only meant for edit and view page html requests.

2024-05-14 10:10 UTC, dvj1988 commented on app/client/src/utils/serviceWorkerUtils.js
> + */
Sure noted.

2024-05-14 10:17 UTC, dvj1988 commented on app/client/src/utils/serviceWorkerUtils.js
> +    this.pendingApiRequests = new Map();
There are some [advantages](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map#objects_vs._maps). In the current implementation I used it because of the helper methods to read, update and delete. These methods help manipulate the map easier and makes the code more readable.

2024-05-14 10:24 UTC, dvj1988 commented on app/client/src/utils/serviceWorkerUtils.js
> +          // Store in cache with expiration header
> Cloning the response is necessary because request and response streams can only be read once. In order to return the response to the browser and put it in the cache we have to clone it. So the original gets returned to the browser and the clone gets sent to the cache. They are each read once.

This is an excerpt from this [mdn reference](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers#the_premise_of_service_workers) which explains the reason for cloning.

2024-05-14 11:40 UTC, dvj1988 commented on app/client/craco.dev.config.js
> +  webpack: {
We can leave it as is and enable it for dev mode.

Just FYI there are some warnings that popup in the terminal as result of enabling WorkboxPlugin in dev mode. This is a known issue for webpack watch mode (InjectManifest has been called multiple times, perhaps due to running webpack in --watch mode.)

2024-05-14 11:42 UTC, dvj1988 commented
/build-deploy-preview skip-tests=true

2024-05-14 11:54 UTC, dvj1988 commented on app/client/src/utils/serviceWorkerUtils.test.js
> +    it("should not match when the path is edit widgets", () => {
Resolved

2024-05-14 11:54 UTC, dvj1988 commented on app/client/src/utils/serviceWorkerUtils.test.js
> +      expect(result.params).toHaveProperty("pageId", "123");
Resolved.

2024-05-14 12:29 UTC, dvj1988 commented
/build-deploy-preview skip-tests=true

2024-05-14 15:14 UTC, dvj1988 commented
/build-deploy-preview skip-tests=true

2024-05-14 15:47 UTC, dvj1988 commented on app/client/src/utils/serviceWorkerUtils.js
> +  return null;
Resolved.

2024-05-14 16:05 UTC, dvj1988 commented
/build-deploy-preview skip-tests=true

2024-05-14 16:17 UTC, dvj1988 commented
Running e2e test cases in [this PR](https://github.com/appsmithorg/appsmith-ee/pull/4175)

2024-05-15 05:30 UTC, dvj1988 commented
/build-deploy-preview skip-tests=true

2024-05-15 07:06 UTC, dvj1988 commented
/build-deploy-preview skip-tests=true

2024-05-15 09:23 UTC, dvj1988 commented
/build-deploy-preview skip-tests=true

2024-05-15 10:52 UTC, rajatagrawal commented
@dvj1988 

Can we please add a github issue for this PR before merging ?

2024-05-15 10:52 UTC, rajatagrawal commented
@dvj1988

Can we please add a github issue for this PR before merging ?

2024-05-15 18:01 UTC, dvj1988 commented
> @dvj1988
> 
> Can we please add a github issue for this PR before merging ?

Added an issue to the PR description.

2024-05-15 18:53 UTC, dvj1988 commented
/build-deploy-preview skip-tests=true

2024-05-16 02:53 UTC, rajatagrawal commented on app/client/src/utils/serviceWorkerUtils.js
> +    await this.consolidatedApiFetchmutex.acquire();
Should there be a check to ensure that cache is initialized before fetching as well as accessing cache ?

2024-05-16 02:56 UTC, rajatagrawal commented
Suggested refactor to comply with single responsibility principle and some suggested naming changes to make code more generic. The code logic is fine and untouched. Just a suggestion on an iteration of code organization. I have suggested the changes in a patch file. The patch can be applied locally to see the suggested changes.

[gitdiffpatch.zip](https://github.com/appsmithorg/appsmith/files/15329125/gitdiffpatch.zip)

2024-05-16 03:01 UTC, rajatagrawal commented on app/client/src/utils/serviceWorkerUtils.js
> +    await this.consolidatedApiFetchmutex.acquire();
Another suggested way to overcome this problem could be to add cache initialization in a mutex block

2024-05-16 03:02 UTC, rajatagrawal commented on app/client/src/utils/serviceWorkerUtils.js
> +    await this.consolidatedApiFetchmutex.waitForUnlock();
Should this be a mutex.acquire instead of waitForUnlock ? Theoretically, before the cache read finishes, another request can be made and the cache be updated, which could lead to corruption of cache data read by this function.

2024-05-16 04:34 UTC, dvj1988 commented on app/client/src/utils/serviceWorkerUtils.js
> +    await this.consolidatedApiFetchmutex.acquire();
That's a valid point. Will init the cache in the cacheConsolidatedApi fn rather than the constructor.

2024-05-16 04:36 UTC, dvj1988 commented on app/client/src/utils/serviceWorkerUtils.js
> +    await this.consolidatedApiFetchmutex.waitForUnlock();
The mutex was added to make sure no reads can happen when there is an ongoing write. 
> before the cache read finishes, another request can be made and the cache be updated
Can you give a scenario when this would happen?

2024-05-16 04:50 UTC, dvj1988 commented
> Suggested refactor to comply with single responsibility principle and some suggested naming changes to make code more generic. The code logic is fine and untouched. Just a suggestion on an iteration of code organization. I have suggested the changes in a patch file. The patch can be applied locally to see the suggested changes.
> 
> [gitdiffpatch.zip](https://github.com/appsmithorg/appsmith/files/15329125/gitdiffpatch.zip)

IMO all changes are nit picks which could go either way. But in any case I can apply the patch.

2024-05-16 05:11 UTC, rajatagrawal commented on app/client/src/utils/serviceWorkerUtils.js
> +    await this.consolidatedApiFetchmutex.waitForUnlock();
The read isn't complete but another fetch request comes to service worker

2024-05-16 05:12 UTC, dvj1988 commented on app/client/src/utils/serviceWorkerUtils.js
> +    await this.consolidatedApiFetchmutex.waitForUnlock();
Do you mean a fetch request for a html document?

2024-05-16 05:31 UTC, rajatagrawal commented on app/client/src/utils/serviceWorkerUtils.js
> +    await this.consolidatedApiFetchmutex.waitForUnlock();
or an ajax call for same api call.

2024-05-16 07:47 UTC, dvj1988 commented on app/client/src/serviceWorker.js
> +  },
Error handling on failure is handled in the main bundle. We just need to return the Network handler and the main thread code will take care of gracefully handling this.

2024-05-16 07:47 UTC, dvj1988 commented on app/client/src/serviceWorker.js
> +};
Resolved

2024-05-16 07:55 UTC, dvj1988 commented on app/client/src/utils/serviceWorkerUtils.js
> +    await this.consolidatedApiFetchmutex.waitForUnlock();
If it is an HTML fetch, it shouldn't be a problem as the main thread and service worker execution context are reinitialized.

We are defining this as a read-only-once cache to ensure there aren't any stale responses that might accidentally be served to the main thread. If multiple fetches for the consolidated API with the same pageId are initiated, the behavior will be that the first fetch will hit the cache while all others will miss it. In the case of a miss, we will fetch from the server. Locking the read wouldn't help here because we want it to be consumed only once, and all subsequent fetches should go to the network by design.

2024-05-16 08:16 UTC, dvj1988 commented
/build-deploy-preview skip-tests=true

2024-05-16 09:07 UTC, KelvinOm requested changes

2024-05-16 09:07 UTC, KelvinOm commented on app/client/craco.dev.config.js
> +  webpack: {
@dvj1988 Does it affect the build time somehow? Did you check it?

We have some issues with  building time, if it is not necessary, then I would prefer not to add anything here.

2024-05-16 09:13 UTC, dvj1988 commented on app/client/craco.dev.config.js
> +  webpack: {
I have not seen any issues with the dev server build time or hot reloads. Preferably we want to keep this so that we have the same behaviour of the service worker in the dev and prod modes. 
Earlier we were using service worker to cache the static assets but this PR is prefetching and caching one of the apis. If there are any main bundle changes that would affect the behaviour of the service worker or vice versa we want to start catching them in the dev mode itself.
After the merge I will keep a track of whether this is affecting any devs local setup and can take a measure accordingly.

2024-05-16 09:24 UTC, dvj1988 commented on app/client/craco.dev.config.js
> +  webpack: {
@KelvinOm Do you have any specific scenario in mind to test?

2024-05-16 10:19 UTC, dvj1988 commented on app/client/craco.dev.config.js
> +  webpack: {
@KelvinOm By cache do you mean lint cache? 
How do you propose I measure these?

2024-05-16 11:36 UTC, KelvinOm commented on app/client/craco.dev.config.js
> +  webpack: {
By cache I mean `babel-loader` cache it stored at `app/client/node_modules/.cache/babel-loader`. It is created when the webpack is running.

> How do you propose I measure these?
I do not know a good way to do this. I'm measuring the time in terminal. We can use `time` like `time yarn start`.  I couldn't run the webpack speed measure plugin because it doesn't work with `craco`.  So we have to measure it manually.

2024-05-16 12:20 UTC, dvj1988 commented on app/client/craco.dev.config.js
> +  webpack: {
I used the package called `gnomon`. And the time taken looks the same.

Start time without cache was replicated by following the steps
- Checkout the branch
- delete node_modules
- install deps
- comment out the cache settings in craco.dev.config
- start the server

```sh
yarn start | gnomon --type=elapsed-total
```

Tests done in: Apple M1 Pro, RAM 32 GB

|Branch|Start time without cache|Start time with cache |Recompilation Time
|-------------------|----------|----------|----------|
release|190-192s|12-13s|4-6s
chore/prefetch-consolidated-api|190-192s|12-13s|4-6s

Start time without cache - release
<img width="778" alt="Screenshot 2024-05-16 at 4 44 52 PM" src="https://github.com/appsmithorg/appsmith/assets/18716465/55ba6081-d6f5-4115-b7f2-4f5a84f7f0df">
Start time with cache - release
<img width="665" alt="Screenshot 2024-05-16 at 4 47 10 PM" src="https://github.com/appsmithorg/appsmith/assets/18716465/831a16a8-b9c6-4b3c-8028-5b4c5d884b62">
Start time without cache - chore/prefetch-consolidated-api
<img width="700" alt="Screenshot 2024-05-16 at 5 39 47 PM" src="https://github.com/appsmithorg/appsmith/assets/18716465/99559083-f420-4a2d-bb37-5c8212d18219">
Start time with cache - chore/prefetch-consolidated-api
<img width="699" alt="Screenshot 2024-05-16 at 5 12 39 PM" src="https://github.com/appsmithorg/appsmith/assets/18716465/a75e75c3-cc6e-4146-a30d-de3d55bcb63c">

2024-05-16 12:32 UTC, KelvinOm approved these changes

2024-05-16 12:33 UTC, merged