feat: Adding & Fetching Tenant Configuration to Redis
appsmithorg/appsmith pull request #33309
Opened 2024-05-09 06:19 UTC by NilanshBansal

## Description
> [!TIP]  
> _Add a TL;DR when the description is longer than 500 words or extremely technical (helps the content, marketing, and DevRel team)._
>
> _Please also include relevant motivation and context. List any dependencies that are required for this change. Add links to Notion, Figma or any other documents that might be relevant to the PR._

Fixes #`Issue Number`  
_or_  
Fixes `Issue URL`
> [!WARNING]  
> _If no issue exists, please create an issue first, and check with the maintainers if the issue is valid._

## Automation

/ok-to-test tags=""

### :mag: Cypress test results

> [!CAUTION]  
> If you modify the content in this section, you are likely to disrupt the CI result for your PR.

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [ ] No

2024-05-10 06:04 UTC, mohanarpit commented on app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CacheableRepositoryHelperCE.java
> +    Mono<Tenant> fetchCachedTenant(String tenantId);
Nit: Suggestion renaming this to `fetchTenant`. This is because the function is already in the class `CacheableRepositoryHelper`. Hence, we don't need to add cache to the function name as well.

2024-05-10 06:07 UTC, mohanarpit commented on app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/TenantRepositoryCE.java
> +    // Use tenantService.getDefaultTenant() instead of this method as it is cached to redis.
Are we deprecating `findBySlug()` function? If yes, I'd recommend either replacing the usage of `findBySlug()` in this PR or adding a `@Deprecated` annotation on this function so that it can be replaced across the board in another PR.

2024-05-10 06:08 UTC, mohanarpit commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/TenantServiceCEImpl.java
> +    private CacheableRepositoryHelper cacheableRepositoryHelper;
```suggestion
    private final CacheableRepositoryHelper cacheableRepositoryHelper;
```

2024-05-10 09:17 UTC, NilanshBansal commented
Test `updateTenantConfiguration_updateStrongPasswordPolicy_success` is failing weirdly with 2 different tenantIds getting populated in redis for a single test case. This is creating inconsistency and leading to failure of this test.

<img width="1440" alt="image" src="https://github.com/appsmithorg/appsmith/assets/25542733/ea5a89df-a7e3-4ceb-b390-eca539b38e8f">

2024-05-13 11:50 UTC, rajatagrawal commented
@NilanshBansal 

Would it be possible to cache tenant configuration as part of this request https://github.com/appsmithorg/appsmith/blob/217da70d9fd45b8aab3004d68b49d5e8a4087206/app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/TenantServiceCEImpl.java#L153 ?



This DB call is made the first time tenant id is needed. It fetches the tenant configuration but only persists id in redis cache. The code can be changed to persist the whole configuration. Thoughts ?

2024-05-13 12:08 UTC, NilanshBansal commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/TenantServiceCEImpl.java
> +        return getDefaultTenantId()
@rajatagrawal fetching the defaultTenantId is stored in the instance variable. It is not going to redis or to the database. This is the fastest call that is being made.

2024-05-13 12:10 UTC, NilanshBansal commented
> @NilanshBansal
> 
> Would it be possible to cache tenant configuration as part of this [request](https://github.com/appsmithorg/appsmith/blob/217da70d9fd45b8aab3004d68b49d5e8a4087206/app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/TenantServiceCEImpl.java#L56)
> 
> This DB call is made the first time tenant id is needed. It fetches the tenant configuration but only persists id in redis cache. The code can be changed to persist the whole configuration. Thoughts ?

@rajatagrawal It is already the fastest call that we are making even faster than redis. Since this is being fetched from the class instance variable and not from any network call. 
Saying that, there are a lot of code level/readability improvements that we can make to this piece of code but purely from a performance standpoint it will not give us any perf boost.

2024-05-13 15:55 UTC, abhvsn requested changes
@NilanshBansal added couple of minor comments. Also we are updating the tenant in `restartTenant` which is making a call to `BaseService` and not covered as a part of invalidation. I'm little concerned on invalidation part, let's make sure to override the base service and repository methods which are saving and updating the DB object.

2024-05-13 15:55 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CacheableRepositoryHelperCEImpl.java
> +        query.addCriteria(defaultTenantCriteria);
Let's also include notDeleted criteria to be on safer side.

2024-05-13 15:55 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CacheableRepositoryHelperCEImpl.java
> +    @Cache(cacheName = "defaultTenant", key = "{#tenantId}")
Considering there is going to be single defaultTenant does it make sense to remove the key altogether? Or even better have the `cacheName = "tenant" and key = "{#tenantId}"`, as this can be extended when we implement multi-tenancy in future.

2024-05-14 04:10 UTC, NilanshBansal commented on app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CacheableRepositoryHelperCEImpl.java
> +    @Cache(cacheName = "defaultTenant", key = "{#tenantId}")
Makes sense. Thanks @abhvsn!

2024-05-15 01:29 UTC, abhvsn approved these changes

2024-05-15 01:45 UTC, merged