[ops]: add warning for custom APPSMITH_GIT_ROOT
appsmithorg/appsmith pull request #33355
Opened 2024-05-10 11:45 UTC by pratapaprasanna

2024-05-10 11:48 UTC, pratapaprasanna commented
/build-deploy-preview skip-tests=true

2024-05-15 03:51 UTC, sharat87 approved these changes

2024-05-27 04:19 UTC, sharat87 requested changes

2024-05-27 04:19 UTC, sharat87 commented on deploy/docker/fs/opt/appsmith/utils/bin/backup.js
> +  if (gitRoot != "/appsmith-stacks/git-storage/"){
This condition will always fail, even if custom git root isn't set. If you see the function `getGitRoot`, we have:

![shot-2024-05-27-04-17-05](https://github.com/appsmithorg/appsmith/assets/120119/3baeb4e9-ce20-45c6-a0f3-428c9a934313)

The default value there doesn't have a trailing `/`. Can we test and verify this once please?

2024-05-27 09:43 UTC, pratapaprasanna commented on deploy/docker/fs/opt/appsmith/utils/bin/backup.js
> +  if (gitRoot != "/appsmith-stacks/git-storage/"){
Yea got it

2024-05-27 11:14 UTC, sharat87 approved these changes

2024-05-27 11:47 UTC, merged