test: exported file which is getting compared
appsmithorg/appsmith pull request #33371
Opened 2024-05-13 06:07 UTC by NandanAnantharamu

WidgetsExportedOnly.json needs update

RCA:
Comparision of this file post import is failing this file needed change.

2024-05-13 06:09 UTC, NandanAnantharamu commented
/ci-test-limit

2024-05-13 06:14 UTC, NandanAnantharamu commented
/ci-test-limit

2024-05-13 14:39 UTC, NandanAnantharamu commented
/ci-test-limit runId=9058124081

2024-05-13 14:39 UTC, NandanAnantharamu commented
/ci-test-limit runId=9058124081

2024-05-13 14:39 UTC, NandanAnantharamu commented
/ci-test-limit runId=9058124081

2024-05-13 14:39 UTC, NandanAnantharamu commented
/ci-test-limit runId=9058124081

2024-05-13 14:39 UTC, NandanAnantharamu commented
/ci-test-limit runId=9058124081

2024-05-13 14:39 UTC, NandanAnantharamu commented
/ci-test-limit runId=9058124081

2024-05-13 14:39 UTC, NandanAnantharamu commented
/ci-test-limit runId=9058124081

2024-05-13 14:39 UTC, NandanAnantharamu commented
/ci-test-limit runId=9058124081

2024-05-13 14:39 UTC, NandanAnantharamu commented
/ci-test-limit runId=9058124081

2024-05-13 14:39 UTC, NandanAnantharamu commented
/ci-test-limit runId=9058124081

2024-05-13 14:39 UTC, NandanAnantharamu commented
/ci-test-limit runId=9058124081

2024-05-13 14:39 UTC, NandanAnantharamu commented
/ci-test-limit runId=9058124081

2024-05-13 14:39 UTC, NandanAnantharamu commented
/ci-test-limit runId=9058124081

2024-05-13 14:39 UTC, NandanAnantharamu commented
/ci-test-limit runId=9058124081

2024-05-13 14:40 UTC, NandanAnantharamu commented
/ci-test-limit runId=9058124081

2024-05-13 14:40 UTC, NandanAnantharamu commented
/ci-test-limit runId=9058124081

2024-05-13 14:40 UTC, NandanAnantharamu commented
/ci-test-limit runId=9058124081

2024-05-13 14:40 UTC, NandanAnantharamu commented
/ci-test-limit runId=9058124081

2024-05-13 14:40 UTC, NandanAnantharamu commented
/ci-test-limit runId=9058124081

2024-05-13 14:40 UTC, NandanAnantharamu commented
/ci-test-limit runId=9058124081

2024-05-13 14:40 UTC, NandanAnantharamu commented
/ci-test-limit runId=9058124081

2024-05-14 02:11 UTC, NandanAnantharamu commented
/ci-test-limit runId=9058124081

2024-05-14 02:11 UTC, NandanAnantharamu commented
/ci-test-limit runId=9058124081

2024-05-14 02:12 UTC, NandanAnantharamu commented
/ci-test-limit runId=9058124081

2024-05-14 02:12 UTC, NandanAnantharamu commented
/ci-test-limit runId=9058124081

2024-05-14 02:12 UTC, NandanAnantharamu commented
/ci-test-limit runId=9058124081

2024-05-14 02:12 UTC, NandanAnantharamu commented
/ci-test-limit runId=9058124081

2024-05-14 02:12 UTC, NandanAnantharamu commented
/ci-test-limit runId=9058124081

2024-05-14 02:12 UTC, NandanAnantharamu commented
/ci-test-limit runId=9058124081

2024-05-14 02:12 UTC, NandanAnantharamu commented
/ci-test-limit runId=9058124081

2024-05-14 02:12 UTC, NandanAnantharamu commented
/ci-test-limit runId=9058124081

2024-05-20 11:30 UTC, NandanAnantharamu commented
/ci-test-limit

2024-05-20 14:51 UTC, NandanAnantharamu commented
/ci-test-limit

2024-05-20 15:24 UTC, NandanAnantharamu commented
/ci-test-limit runId=9160598937

2024-05-20 15:24 UTC, NandanAnantharamu commented
/ci-test-limit runId=9160598937

2024-05-20 15:24 UTC, NandanAnantharamu commented
/ci-test-limit runId=9160598937

2024-05-20 15:24 UTC, NandanAnantharamu commented
/ci-test-limit runId=9160598937

2024-05-20 15:24 UTC, NandanAnantharamu commented
/ci-test-limit runId=9160598937

2024-05-20 15:24 UTC, NandanAnantharamu commented
/ci-test-limit runId=9160598937

2024-05-20 15:24 UTC, NandanAnantharamu commented
/ci-test-limit runId=9160598937

2024-05-20 15:24 UTC, NandanAnantharamu commented
/ci-test-limit runId=9160598937

2024-05-20 15:24 UTC, NandanAnantharamu commented
/ci-test-limit runId=9160598937

2024-05-20 15:24 UTC, NandanAnantharamu commented
/ci-test-limit runId=9160598937

2024-05-20 15:24 UTC, NandanAnantharamu commented
/ci-test-limit runId=9160598937

2024-05-20 15:24 UTC, NandanAnantharamu commented
/ci-test-limit runId=9160598937

2024-05-20 15:25 UTC, NandanAnantharamu commented
/ci-test-limit runId=9160598937

2024-05-21 02:15 UTC, NandanAnantharamu commented
/ci-test-limit runId=9160598937

2024-05-21 04:49 UTC, trishaanand commented on app/client/cypress/e2e/Regression/ClientSide/PartialImportExport/PartialExport_Widgets_spec.ts
> +    it("1. Import Downloaded file and Verify all the widgets and its properties", () => {
```suggestion
    it("1. Import Downloaded file and Verify all the widgets and their properties", () => {
```

2024-05-21 04:50 UTC, trishaanand commented on app/client/cypress/e2e/Regression/ClientSide/PartialImportExport/PartialExport_Widgets_spec.ts
> +    it("1. Import Downloaded file and Verify all the widgets and their properties", () => {
Isnt the test case first exporting and then importing? The title seems to suggest that we already have a json file before we start the test.

2024-05-21 05:45 UTC, NandanAnantharamu commented on app/client/cypress/e2e/Regression/ClientSide/PartialImportExport/PartialExport_Widgets_spec.ts
> +    it("1. Import Downloaded file and Verify all the widgets and their properties", () => {
updated test name

2024-05-21 06:17 UTC, ApekshaBhosale requested changes

2024-05-21 06:17 UTC, ApekshaBhosale commented on app/client/cypress/support/Pages/PartialImportExport.ts
> +      "Error exporting application. Please try again.",
can we move this to messages file please? @NandanAnantharamu

2024-05-21 06:45 UTC, ApekshaBhosale requested changes

2024-05-21 06:45 UTC, ApekshaBhosale commented on app/client/cypress/fixtures/PartialImportExport/WidgetsExportedOnly.json
why do we need this file now? @NandanAnantharamu

2024-05-21 07:00 UTC, NandanAnantharamu commented on app/client/cypress/fixtures/PartialImportExport/WidgetsExportedOnly.json
this file is used in another test as well , i updated with latest json file after exporting the partial app.

2024-05-21 07:00 UTC, NandanAnantharamu commented on app/client/cypress/support/Pages/PartialImportExport.ts
> +      "Error exporting application. Please try again.",
done

2024-05-21 07:03 UTC, NandanAnantharamu commented
/ci-test-limit

2024-05-21 07:46 UTC, ApekshaBhosale submitted a review, later dismissed

2024-05-21 08:37 UTC, ApekshaBhosale approved these changes

2024-05-21 09:04 UTC, NandanAnantharamu commented
/ci-test-limit

2024-05-21 09:49 UTC, NandanAnantharamu commented
/ci-test-limit

2024-05-21 10:44 UTC, ApekshaBhosale approved these changes

2024-05-21 13:10 UTC, merged