[wip]: make xcaddy configurable based on env
appsmithorg/appsmith pull request #33387
Opened 2024-05-13 13:02 UTC by pratapaprasanna

2024-05-15 02:03 UTC, sharat87 requested changes
We need to reverse the boolean check we added in the reconfigure script, it's inverted currently. Rest are minor recommended fixes and we should be ready to merge.

2024-05-15 02:03 UTC, sharat87 commented on deploy/docker/fs/opt/appsmith/entrypoint.sh
> +  $_APPSMITH_CADDY start --config "$TMP/Caddyfile"
```suggestion
  "$_APPSMITH_CADDY" start --config "$TMP/Caddyfile"
```

2024-05-15 09:14 UTC, pratapaprasanna commented on deploy/docker/fs/opt/appsmith/run-caddy.sh
> +exec "$_APPSMITH_CADDY" run --config "$TMP/Caddyfile"
It is because of the vi editor I use. Let me take care going forward

2024-05-16 16:05 UTC, sharat87 requested changes

2024-05-16 16:05 UTC, sharat87 commented on deploy/docker/fs/opt/appsmith/caddy-reconfigure.mjs
Line 190 and 191 are still using hard-coded Caddy. Can we change them to use the env variable please?

Can we also test with if the container built with changes in this PR, starts when _all_ Docker capabilities are dropped please?

2024-05-16 17:02 UTC, pratapaprasanna commented on deploy/docker/fs/opt/appsmith/caddy-reconfigure.mjs
Yea my bad. Sorry

2024-05-17 02:27 UTC, sharat87 submitted a review, later dismissed
Looks good. Do you want to merge just the `base.dockerfile` first, let the base image be built, and then merge the rest of it? If yes, let me know and I'll pick just that file's changes and push to `release`.

2024-05-17 02:29 UTC, sharat87 commented
@pratapaprasanna, also, can we ensure the "Semantic PR" check passes on PRs please? It checks that PR titles should start with `feat:` or `fix:` or `chore:` or `test:` or `ci:`. Having this correct helps us generate our release notes correctly. Like, entries with `chore:` or `test:` or `ci:` will be automatically removed from release notes. So if we don't want our PR to show up for users reading release notes, we use one of those that's most appropriate.

I'm fixing the title for this PR, please feel free to change if you disagree. Thanks!

2024-05-23 02:12 UTC, sharat87 approved these changes

2024-05-24 07:41 UTC, merged