test: Enable server tests for the PRs with base PG branch
appsmithorg/appsmith pull request #33429
Opened 2024-05-14 08:56 UTC by abhvsn

## Description
1. PR to enable server tests on PRs with `pg` as the base branch. 
2. Replace the DB URI from `APPSMITH_MONGODB_URI` to `APPSMITH_DB_URL` 

## Automation

/ok-to-test tags="@tag.Sanity, @tag.GenerateCRUD, @tag.Fork"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9174148396>
> Commit: 762b4255f654946a1a47a196df5a1afae5be09f2
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9174148396&attempt=1" target="_blank">Click here!</a>

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [x] No

2024-05-15 06:27 UTC, mohanarpit commented on app/server/appsmith-server/src/main/resources/application-production.properties
> +spring.data.mongodb.uri=${APPSMITH_DB_URI:${APPSMITH_MONGODB_URI}}
This file is not used. We should make this change to `application.properties` only.

2024-05-16 06:32 UTC, sharat87 requested changes
1. I see both `APPSMITH_DB_URL` and `APPSMITH_DB_URI`. Can we fix this and use `APPSMITH_DB_URL` please?

2024-05-16 06:32 UTC, sharat87 commented on app/server/build.sh
> +
This is a runtime env variable, and shouldn't influence build. Can we instead change the condition to check if the `transform.py` exists?

```suggestion
if [[ -f tx/transform.py ]]; then
  python3 tx/transform.py
fi

```

2024-05-16 06:32 UTC, sharat87 commented on app/server/appsmith-server/src/main/resources/application.properties
> +spring.data.mongodb.uri=${APPSMITH_DB_URI:${APPSMITH_MONGODB_URI}}
Let's completely move awa from `APPSMITH_MONGODB_URI`. The backend server should _only_ look at the generic env variable, and the MongoDB specific one at all.

Instead, let's get this fallback functionality in the `entrypoint.sh`. There, we check if the new env variable has a value, otherwise, it's set to the MongoDB env variable's value, and the MongoDB env variable itself, is unset.

This way, we have consistent DB URL fallback implemented for all the services running the container, and not just for the backend.

2024-05-16 06:32 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration056UpdateDbUriEnvVariable.java
Any reason we need this migration, when we have a fallback to read the old env variable anyway?

2024-05-16 06:32 UTC, sharat87 commented on .github/workflows/server-build.yml
>            ./build.sh -DskipTests
We're building without tests here, right? Is the DB URL needed?

2024-05-16 06:32 UTC, sharat87 commented on app/server/appsmith-server/src/main/resources/application.properties
> +spring.data.mongodb.uri=${APPSMITH_DB_URI:${APPSMITH_MONGODB_URI}}
Additionally, let's have `entrypoint.sh` add the `jdbc:` prefix to the URL if missing.

2024-05-16 06:43 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration056UpdateDbUriEnvVariable.java
@sharat87 added this to avoid the confusion in future, such that after specific version everyone will be using same env for DB URI. Also will be easier to communicate in our docs.

2024-05-16 06:46 UTC, abhvsn commented on .github/workflows/server-build.yml
>            ./build.sh -DskipTests
Build will fail on pg branch is we don't run the transform script right? That's the hard requirement for now, but I think after reading [this comment](https://github.com/appsmithorg/appsmith/pull/33429/files#r1602687555) we don't have to rely on this at all.

2024-05-16 07:34 UTC, abhvsn commented on app/server/appsmith-server/src/main/resources/application.properties
> +spring.data.mongodb.uri=${APPSMITH_DB_URI:${APPSMITH_MONGODB_URI}}
@sharat87 updated the entrypoint.sh with the changes requested, can you please take a look. Also, I was thinking if this fallback will help us with local testing though or should we just update the `test.env.example` and ask devs to switch to the updated env manually as we don't run entrypoint for local testing.

2024-05-16 16:07 UTC, sharat87 commented on app/server/appsmith-server/src/main/resources/application.properties
> +spring.data.mongodb.uri=${APPSMITH_DB_URI:${APPSMITH_MONGODB_URI}}
I'm thinking let's change and announce. Announce to folks that **for local development only**, we need to use the new env variable, and the old one will not work anymore. But the container has backwards compatibility, in that **our users running the container**, don't have to do anything.

2024-05-16 16:10 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration056UpdateDbUriEnvVariable.java
I get the problem being solved, but I slightly disagree that it should be solved. The `docker.env` is just one place for env variables. They're also set from ConfigMaps for Kubernetes, in `docker-compose.yml` file, in ECS configuration on AWS console, etc. All we can do here, is update the `docker.env`, which doesn't afford us any comfort that everyone has moved on to the newer env variable.

We'll have to keep the fallback to the old env variable for a _long long_ time to come, anyway. 🙂

2024-05-16 16:18 UTC, sharat87 requested changes

2024-05-16 16:18 UTC, sharat87 commented on app/server/appsmith-server/src/main/resources/application.properties
> +spring.data.mongodb.uri=${APPSMITH_DB_URL:${APPSMITH_MONGODB_URI}}
Let's remove the fallback here, and not have a default value at all. Just like in the old `application-production-properties`.

Rationale at https://github.com/appsmithorg/appsmith/pull/33429#discussion_r1603660557.

2024-05-16 16:18 UTC, sharat87 commented on deploy/docker/fs/opt/appsmith/entrypoint.sh
> +configure_database_connection_url
Let's move this to above `chece_mongodb_uri`, so that, just in case, the new env variable is available before we do anything with the Database.

2024-05-16 16:19 UTC, abhvsn commented on app/server/appsmith-server/src/main/resources/application.properties
> +spring.data.mongodb.uri=${APPSMITH_DB_URI:${APPSMITH_MONGODB_URI}}
@sharat87 Does the change in `entrypoint.sh` looks good to you for backward compatibility? If we are aligned I'll remove the migration and rely on `APPSMITH_DB_URL` in `application.properties`.

2024-05-16 16:20 UTC, sharat87 commented on .github/workflows/server-build.yml
> +            docker run -d -p 5432:5432 postgres:alpine
Can we verify if this command is working? I tried locally and it doesn't seem to be.

![shot-2024-05-16-16-20-26](https://github.com/appsmithorg/appsmith/assets/120119/1be708b8-56e3-4655-b631-fc463aca9173)

2024-05-16 16:21 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration056UpdateDbUriEnvVariable.java
Got it aligned on the approach, I was looking from local dev perspective. I'll continue with the suggestion provided in other thread https://github.com/appsmithorg/appsmith/pull/33429#discussion_r1603660557.

2024-05-16 19:17 UTC, abhvsn commented on deploy/docker/fs/opt/appsmith/entrypoint.sh
> +configure_database_connection_url
Done, I have made updates in few other places.

2024-05-17 01:59 UTC, sharat87 requested changes

2024-05-17 01:59 UTC, sharat87 commented on .github/workflows/server-build.yml
> +            export APPSMITH_DB_URL="jdbc:postgresql://localhost:5432/postgres"
We'll need to set the username/password here now no? Something like:

```suggestion
            export APPSMITH_DB_URL="jdbc:postgresql://postgres:password@localhost:5432/postgres"
```

2024-05-17 01:59 UTC, sharat87 commented on app/server/appsmith-server/src/main/resources/application.properties
> +spring.data.mongodb.uri=${APPSMITH_DB_URL:}
Let's please not have a default value here. If this is empty, server startup will fail, so might as well fail earlier here itself. Just like how it was in `application-production.properties`.

```suggestion
spring.data.mongodb.uri=${APPSMITH_DB_URL}
```

2024-05-17 01:59 UTC, sharat87 commented on deploy/docker/fs/opt/appsmith/entrypoint.sh
> +  elif [ $isPostgresUrl -eq 1 ]; then
```suggestion
  elif [[ $isPostgresUrl -eq 1 ]]; then
```

2024-05-17 01:59 UTC, sharat87 commented on deploy/docker/fs/opt/appsmith/entrypoint.sh
> +  fi
Let's make this stricter and define a fallthrough `else` as well. Something like:

```suggestion
  if [[ "${APPSMITH_DB_URL}" == "jdbc:postgresql:"* ]]; then
    isPostgresUrl=1
  elif [[ "${APPSMITH_DB_URL}" == "postgresql:"* ]]; then
    isPostgresUrl=1
    export APPSMITH_DB_URL="jdbc:${APPSMITH_DB_URL}"
  elif [[ "${APPSMITH_DB_URL}" == "mongodb"* ]]; then
    isMongoUrl=1
  fi

```

2024-05-17 06:36 UTC, abhvsn commented on .github/workflows/server-build.yml
> +            export APPSMITH_DB_URL="jdbc:postgresql://localhost:5432/postgres"
@sharat87 it's failing for the above connection string in my local, but adding a separate username and password works. Let me add 
```
Connection Fail:
spring.datasource.url=jdbc:postgresql://postgres:password@localhost:5432/postgres

Connection successful:
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=password
```

From little search I think `jdbc:postgresql://hostname:port/database` is the valid format. I think we need to add more env variable to fix this issue.

2024-05-17 06:59 UTC, abhvsn commented on .github/workflows/server-build.yml
> +            export APPSMITH_DB_URL="jdbc:postgresql://localhost:5432/postgres"
Created another PR pointing to PG branch to address this issue https://github.com/appsmithorg/appsmith/pull/33543

2024-05-17 11:30 UTC, abhvsn commented on .github/workflows/server-build.yml
> +            export APPSMITH_DB_URL="jdbc:postgresql://localhost:5432/postgres"
@sharat87 extracting username and password worked in my local please check app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/CommonDBConfig.java, we can live with single env APPSMITH_DB_URL for both Mongo and Postgres.

2024-05-17 11:36 UTC, abhvsn commented
/build-deploy-preview skip-tests=true

2024-05-20 10:09 UTC, abhvsn commented
/build-deploy-preview skip-tests=true

2024-05-20 10:21 UTC, sharat87 requested changes
Looks good. One more small recommendation and let's get the DP ready. Thanks!

2024-05-20 10:21 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/CommonDBConfig.java
> +            URI uri = new URI(dbUrl.substring(5)); // remove "jdbc:" prefix
Looks like we're stripping the `jdbc:` prefix here, and aren't really using it. Perhaps we don't have to add it to the env variable in the first place? We didn't have it with MongoDB, we don't need it with Postgres, so might as well not add it, right? What say?

2024-05-20 18:17 UTC, abhvsn commented
/build-deploy-preview skip-tests=true recreate=true

2024-05-21 09:25 UTC, sharat87 requested changes

2024-05-21 09:25 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/CommonDBConfig.java
> +            URI uri = new URI(dbUrl.replaceFirst("^" + JDBC_PREFIX, ""));
Can we completely remove this? Do we expect cases where the `jdbc:` prefix might be there? We can fail in that case saying it's not a valid URL, right?

2024-05-21 09:25 UTC, sharat87 commented on deploy/docker/fs/opt/appsmith/utils/bin/backup.js
> +    if (!line.startsWith("APPSMITH_ENCRYPTION") && !line.startsWith("APPSMITH_MONGODB") && !line.startsWith("APPSMITH_DB")) {
For the other two, they're prefixes of _more than one_ env variable. But there's only one env variable that starts with `APPSMITH_DB`, so let's make it specific.

```suggestion
    if (!line.startsWith("APPSMITH_ENCRYPTION") && !line.startsWith("APPSMITH_MONGODB") && !line.startsWith("APPSMITH_DB_URL=")) {
```

2024-05-21 09:29 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/CommonDBConfig.java
> +            URI uri = new URI(dbUrl.replaceFirst("^" + JDBC_PREFIX, ""));
This was added just to support both the url format as I have seen some discussion in couple of threads, so thought of supporting this.

2024-05-21 09:33 UTC, abhvsn commented on deploy/docker/fs/opt/appsmith/utils/bin/backup.js
> +    if (!line.startsWith("APPSMITH_ENCRYPTION") && !line.startsWith("APPSMITH_MONGODB") && !line.startsWith("APPSMITH_DB")) {
I thought in future we may want to move common envs from `APPSMITH_MONGODB*` to more generic `APPSMITH_DB*` hence kept only the prefix. But let's come back to this when required.

2024-05-21 11:06 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/CommonDBConfig.java
> +            URI uri = new URI(dbUrl.replaceFirst("^" + JDBC_PREFIX, ""));
I'd say we add support for ignoring that prefix, if its needed in the future. It's _very_ hard to remove something once released, but we can always add support for this later. Since supporting URLs with that prefix isn't adding any value to us today (correct me if I'm wrong here), I'd rather we require URLs to not have `jdbc:` prefix, both for MongoDB and Postgres.

And besides, if we later add support for allowing the `jdbc:` prefix, we do it consistent. We allow it for _both_ Postgres and MongoDB URLs. But that's for later, I'd rather we don't allow it at all today.

Let me know if you disagree. 🙂

2024-05-21 11:37 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/CommonDBConfig.java
> +            URI uri = new URI(dbUrl.replaceFirst("^" + JDBC_PREFIX, ""));
Aligned, updated the implementation.

2024-05-22 10:24 UTC, sharat87 approved these changes

2024-05-22 10:25 UTC, merged