Test if constrained diff working
appsmithorg/appsmith pull request #33435
Opened 2024-05-14 11:13 UTC by vsvamsi1

## Description
> [!TIP]  
> _Add a TL;DR when the description is longer than 500 words or extremely technical (helps the content, marketing, and DevRel team)._
>
> _Please also include relevant motivation and context. List any dependencies that are required for this change. Add links to Notion, Figma or any other documents that might be relevant to the PR._

Fixes #`Issue Number`  
_or_  
Fixes `Issue URL`
> [!WARNING]  
> _If no issue exists, please create an issue first, and check with the maintainers if the issue is valid._

## Automation

/ok-to-test tags=""

### :mag: Cypress test results

> [!CAUTION]  
> If you modify the content in this section, you are likely to disrupt the CI result for your PR.

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [ ] No

2024-05-16 06:24 UTC, vsvamsi1 commented
/build-deploy-preview skip-tests=true

2024-05-16 08:26 UTC, vsvamsi1 commented
/ci-test-limit

2024-05-16 13:24 UTC, vsvamsi1 commented
/ci-test-limit

2024-05-20 07:10 UTC, rishabhrathod01 commented on app/client/src/workers/Evaluation/handlers/evalTree.ts
> +    affectedJSActionIds,
Did we explore using evalTreeWithChanges instead of evalTree here? We could skip sending JSActionIds and instead mention the paths updated.

2024-05-20 07:10 UTC, rishabhrathod01 commented on app/client/src/workers/common/DataTreeEvaluator/test.ts
> +import { getOnlyAffectJsWidgets, replaceThisDotParams } from "./utils";
What is `JSWidgets`? If we meant to use JSObject then would suggest to keep JSObject as the term here.

2024-05-20 07:27 UTC, rajatagrawal commented on app/client/src/workers/Evaluation/types.ts
> +  affectedJSActionIds?: AffectedJSActions;
1. name of the parameter is ends `actionIds` but the type ends with just `actions`. Is that a mismatch ?
2. Can we please avoid optional parameters. Let us pass an empty array if action ids is empty.

2024-05-20 07:27 UTC, rajatagrawal commented on app/client/src/sagas/EvaluationsSaga.ts
> +  affectedJSActionIds?: AffectedJSActions,
Can we please avoid optional type parameters ?

2024-05-20 07:27 UTC, rajatagrawal commented on app/client/src/sagas/EvaluationSaga.utils.ts
> +  affectedActionIds?: string[];
Can we please avoid optional types ?

2024-05-20 07:28 UTC, rajatagrawal commented on app/client/src/sagas/EvaluationSaga.utils.ts
> +  affectedActionIds?: string[];
Since this is part of AffectedJSActions interface, would it fine to just rename `affectedActionIds` to just `ids`

2024-05-20 07:28 UTC, rajatagrawal requested changes
Left feedback

2024-05-20 09:11 UTC, vsvamsi1 commented on app/client/src/workers/Evaluation/handlers/evalTree.ts
> +    affectedJSActionIds,
No we haven't because we haven't seen the evalAndLintingHandler code flow triggering an evalTreeWithChanges. To refactor the current flow to use will evalTreeWithChanges will increase the complexity of this project. This something we can add to the backlog and I will work with you get context to implementing.

2024-05-21 04:38 UTC, vsvamsi1 commented on app/client/src/workers/common/DataTreeEvaluator/test.ts
> +import { getOnlyAffectJsWidgets, replaceThisDotParams } from "./utils";
Renamed all JS actions to JS objects

2024-05-21 04:50 UTC, rajatagrawal commented on app/client/src/sagas/EvaluationSaga.utils.ts
> +  isAllAffected: boolean;
What does `isAllAffected` mean ?

2024-05-21 04:50 UTC, rajatagrawal commented on app/client/src/workers/common/DataTreeEvaluator/utils.ts
> +  affectedJSObjects?: AffectedJSObjects,
Can we please not have optional arguments ?

2024-05-21 04:56 UTC, rajatagrawal commented on app/client/src/ce/constants/ReduxActionConstants.tsx
> +  affectedJSObjects?: AffectedJSObjects;
Can we please not have optional arguments ?

2024-05-21 04:57 UTC, rajatagrawal commented on app/client/src/sagas/EvaluationsSaga.ts
> +  let collectedAffectedJSObjects: any = null;
Can we please avoid any ?

2024-05-21 05:25 UTC, rajatagrawal commented on app/client/src/ce/constants/ReduxActionConstants.tsx
> +  affectedJSObjects?: AffectedJSObjects;
From system architecture point of view, is affectedJSObject part of a buffered action ?

2024-05-21 07:45 UTC, vsvamsi1 commented on app/client/src/sagas/EvaluationSaga.utils.ts
> +  isAllAffected: boolean;
It means that all JSObjects are affected.

2024-05-21 08:45 UTC, rajatagrawal commented on app/client/src/workers/common/DataTreeEvaluator/index.ts
> +            getOnlyAffectedJsWidgets(
`getOnlyAffectedJSWidgets` -> `getOnlyAffectedJSActions`

2024-05-22 09:20 UTC, rajatagrawal submitted a review, later dismissed

2024-05-22 12:34 UTC, rishabhrathod01 submitted a review, later dismissed
LGTM, added few nits

2024-05-22 12:34 UTC, rishabhrathod01 commented on app/client/src/workers/Evaluation/handlers/evalTrigger.ts
> +      //TODO: the evalTrigger can be optimised to not diff all JS actions
Could we create a github task for this instead of a TODO comment.

2024-05-25 06:52 UTC, ankitakinger commented on app/client/src/sagas/EvaluationsSagaUtils.ts
> +        }
why do we have the same file name under `src/`, `src/ce` and `src/ee`? This will create confusion during importing things. Can we please rename this file to something else?

2024-05-27 02:13 UTC, vsvamsi1 commented on app/client/src/sagas/EvaluationsSagaUtils.ts
> +        }
Sure, this file is name correctly but I have renamed to the src/ee and src/ce to "InferAffectedJSObjects.ts".

2024-05-27 06:15 UTC, merged