fix: Modal Accessibility and copy paste.
appsmithorg/appsmith pull request #33509
Opened 2024-05-16 05:30 UTC by marks0351

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX14yqgk46bo7XRJuA90NLU3E993GRhVyI%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=u9xJeyE)
## Description

In this Pr we are tackling a few issues.
- disallow copy pasting modals into other widgets instead always paste them on the main canvas.
- disable modal header and footer accessibility in edit mode.
- make sure edit mode based wrappers are not wrapped for skeleton widget.
- make sure widget name is not shown for skeleton widget.
- fixed random errors in the withWidgetProps flow
- removed unwanted invocation of setting highlights.

Fixes #`Issue Number`  
_or_  
Fixes `Issue URL`
> [!WARNING]  
> _If no issue exists, please create an issue first, and check with the maintainers if the issue is valid._

## Automation

/ok-to-test tags=""

### :mag: Cypress test results

> [!CAUTION]  
> If you modify the content in this section, you are likely to disrupt the CI result for your PR.

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [ ] No

2024-05-16 07:18 UTC, marks0351 commented on app/client/src/layoutSystems/anvil/integrations/sagas/pasteSagas.ts
> +    }
there is already a try catch for the scope of pasteWidgetSagas.

2024-05-16 08:57 UTC, KelvinOm requested changes

2024-05-16 08:57 UTC, KelvinOm commented on app/client/packages/design-system/widgets/src/components/Modal/src/ModalFooter.tsx
> +    allowInteraction = true,
```suggestion
    excludeFromTabOrder = true,
```

I think having one name for things that do the same thing is a good idea.

2024-05-16 10:05 UTC, marks0351 commented
/build-deploy-preview skip-tests=true

2024-05-17 08:44 UTC, ramsaptami approved these changes

2024-05-17 08:52 UTC, KelvinOm approved these changes

2024-05-17 10:02 UTC, merged