feat: remove api call from building block loading skeleton
appsmithorg/appsmith pull request #33501
Opened 2024-05-15 22:26 UTC by jacquesikot

## Description
> [!TIP]  
> _Add a TL;DR when the description is longer than 500 words or extremely technical (helps the content, marketing, and DevRel team)._
>
> _Please also include relevant motivation and context. List any dependencies that are required for this change. Add links to Notion, Figma or any other documents that might be relevant to the PR._

Fixes #`Issue Number`  
_or_  
Fixes `Issue URL`
> [!WARNING]  
> _If no issue exists, please create an issue first, and check with the maintainers if the issue is valid._

## Automation

/ok-to-test tags=""

### :mag: Cypress test results

> [!CAUTION]  
> If you modify the content in this section, you are likely to disrupt the CI result for your PR.

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [ ] No

2024-05-16 06:11 UTC, jacquesikot commented
/build-deploy-preview skip-tests=true

2024-05-17 05:31 UTC, jacquesikot commented
/build-deploy-preview skip-tests=true

2024-05-17 05:32 UTC, jacquesikot commented
/build-deploy-preview skip-tests=true

2024-05-21 11:08 UTC, riodeuno requested changes
@jacquesikot Thanks for sharing this PR for review. I've not reviewed the files related to building blocks feature, and have added a few requests for changes in the rest.

2024-05-21 11:08 UTC, riodeuno commented on app/client/src/ce/constants/ReduxActionConstants.tsx
> +export interface UpdateBuildingBlockSkeletonLoaderPayload {
This is not the right place for these changes. I would suggest we take a look at folder `src/layoutSystems/anvil/integrations`, to see how we can keep this modular and maintainable.

2024-05-21 11:08 UTC, riodeuno commented on app/client/src/reducers/entityReducers/canvasWidgetsReducer.ts
> +  [ReduxActionTypes.ADD_LOCAL_SKELETON_LOADER]: (
Ideally we should be leveraging the `UPDATE_LAYOUT`. Adding new actions to consider will effect the whole system. This reducer is the source of truth for the whole page and multiple features use this, let's not modify it.

I will suggest that we handle `ADD_LOCAL_SKELETON_LOADER` in the building blocks module's sagas and call the `UPDATE_LAYOUT` action with the appropriate payload.

2024-05-21 11:08 UTC, riodeuno commented on app/client/src/reducers/entityReducers/canvasWidgetsStructureReducer.ts
> +  [ReduxActionTypes.ADD_LOCAL_SKELETON_LOADER]: (
I have the same comments as in the `canvasWidgetsReducer` file.

2024-05-21 11:08 UTC, riodeuno commented on app/client/src/sagas/WidgetDeletionSagas.ts
> +export function* removeSkeletonLoaderFromCanvas(widgetId: string) {
The same logic applies, we should call the saga that handles widget delete, instead of replicating code.

2024-05-23 07:33 UTC, jacquesikot commented on app/client/src/reducers/entityReducers/canvasWidgetsReducer.ts
> +  [ReduxActionTypes.ADD_LOCAL_SKELETON_LOADER]: (
Thanks Abhinav, some context for the problem being solved here. Previously, we used existing logic to add and remove the skeleton loader from the canvas while building blocks loaded, this step increased the number of API calls in an already convoluted process. 
The goal of this PR is to add and remove the skeleton loader locally, without making any api calls to update the layout on the backend.
With this in mind, the current action for the update layout reducer also has a saga tied to it, that handles other async processes like updating the layout, etc. Using this same action will trigger the saga too, and we do not want this to happen, hence we have created a new action that manages removing and adding the skeleton widget in the local state only.

2024-05-23 07:34 UTC, jacquesikot commented on app/client/src/reducers/entityReducers/canvasWidgetsReducer.ts
> +  [ReduxActionTypes.ADD_LOCAL_SKELETON_LOADER]: (
It makes sense however to move this action into the buildingBlocksSaga.

2024-05-23 07:36 UTC, jacquesikot commented on app/client/src/sagas/WidgetDeletionSagas.ts
> +export function* removeSkeletonLoaderFromCanvas(widgetId: string) {
Same thing like above, the already existing deleteWidget saga has other computations and logic not needed to remove a single skeleton widget from the local state only. There is also logic for updating layout, managing anvil, etc, which are all out of the scope of building blocks

2024-05-30 01:03 UTC, jacquesikot commented
/build-deploy-preview skip-tests=true

2024-05-30 06:02 UTC, ashit-rath commented on app/client/src/sagas/BuildingBlockSagas/BuildingBlockAdditionSagas.ts
> +    });
What is this for?

2024-05-30 06:02 UTC, ashit-rath commented on app/client/src/sagas/BuildingBlockSagas/BuildingBlockAdditionSagas.ts
> +    if (metaWidget) {
Why is this in the else condition?

2024-05-30 06:02 UTC, ashit-rath commented on app/client/src/sagas/BuildingBlockSagas/BuildingBlockAdditionSagas.ts
> +export function* addBuildingBlockSkeletonLoaderToCanvas(
Could you add jest tests for these sagas?

2024-05-30 06:02 UTC, ashit-rath commented on app/client/src/sagas/CanvasSagas/DraggingCanvasSagas.ts
> -    shouldReplay?: boolean;
Why is this typing removed?

2024-05-30 09:34 UTC, jacquesikot commented on app/client/src/sagas/BuildingBlockSagas/BuildingBlockAdditionSagas.ts
> +    });
There are two flows for dropping Building blocks, one with reflow and one without, for the flow without reflow, we are optimising using meta widgets for the skeleton, but for the flow that has reflow, we are using the default add child and move saga. This means we have to add and remove the skeleton loaders differently, based on the flow the user is using.

2024-05-30 09:35 UTC, jacquesikot commented on app/client/src/sagas/BuildingBlockSagas/BuildingBlockAdditionSagas.ts
> +    if (metaWidget) {
Same with the explanation above, we need to handle both removing meta skeleton widget when no reflow, and with no reflow, handle removing single skeleton widget from canvas

2024-05-30 09:37 UTC, jacquesikot commented on app/client/src/sagas/BuildingBlockSagas/BuildingBlockAdditionSagas.ts
> +            [newWidget.newWidgetId]: metaWidget as FlattenedWidgetProps,
Here, we are removing the already added skeleton meta widget. the addOrUpdate param needs to be passed, whether adding or removing a meta widget.

2024-05-30 09:47 UTC, jacquesikot commented on app/client/src/sagas/CanvasSagas/DraggingCanvasSagas.ts
> -    shouldReplay?: boolean;
I added it earlier with the first implementation of the skeleton loader, but now we don't need it anymore.

2024-05-31 04:35 UTC, rahulbarwal commented on app/client/src/sagas/BuildingBlockSagas/BuildingBlockAdditionSagas.ts
> +      if (typeof saveResult === "object" && "failure" in saveResult!) {
@jacquesikot this  seems like a good point. why do we have a non null assertion?

2024-05-31 09:13 UTC, ashit-rath commented on app/client/src/sagas/BuildingBlockSagas/BuildingBlockAdditionSagas.ts
> +            [newWidget.newWidgetId]: metaWidget as FlattenedWidgetProps,
Sorry I didn't understand, why is it `addOrUpdate` needs to be passed on removing a meta widget?

2024-05-31 09:15 UTC, ashit-rath commented on app/client/src/sagas/BuildingBlockSagas/BuildingBlockAdditionSagas.ts
> +    });
Can we add some comments to explain this optimization? It might not be so obvious to understand the reasoning behind it

2024-06-15 16:35 UTC, closed without merging