chore: Add new relic to self hosted image
appsmithorg/appsmith pull request #33689
Opened 2024-05-23 07:48 UTC by rajatagrawal

This PR adds new relic apm to self hosted images by default.

In order to enable new relic image for a self hosted instance, the user needs to set following environment variables

```
APPSMITH_NEW_RELIC_ENABLED=true // false by default
APPSMITH_NEW_RELIC_APM_LICENSE_KEY="<license key>" // empty by default
APPSMITH_NEW_RELIC_APM_NAME="<name of the apm app>" // empty by default
```

2024-05-23 07:58 UTC, rajatagrawal commented on deploy/docker/fs/opt/appsmith/run-java.sh
> +  -javaagent:/opt/newrelic/newrelic.jar
Noted. Thanks. Change made

2024-05-24 02:22 UTC, sharat87 requested changes

2024-05-24 02:22 UTC, sharat87 commented on deploy/docker/base.dockerfile
> +RUN curl -o /opt/newrelic/newrelic.jar https://download.newrelic.com/newrelic/java-agent/newrelic-agent/8.9.1/newrelic-agent-8.9.1.jar
Can we ensure the parent folder exists, or are we doing that somewhere already? 🤔

```suggestion
RUN mkdir -p /opt/newrelic \
  curl -o /opt/newrelic/newrelic.jar https://download.newrelic.com/newrelic/java-agent/newrelic-agent/8.9.1/newrelic-agent-8.9.1.jar
```

2024-05-24 02:22 UTC, sharat87 commented on deploy/docker/fs/opt/appsmith/newrelic-reconfigure.mjs
> +    if (!(process.env.APPSMITH_NEW_RELIC_ENABLED == true)) {
Can we fix this please?

2024-05-24 02:22 UTC, sharat87 commented on deploy/docker/fs/opt/appsmith/run-java.sh
> +  -javaagent:/opt/newrelic/newrelic.jar \
Adding this here would mean that these arguments are present even when NewRelic is not configured, right? Can we add something like this just above the `exec` command instead?

```
if [[ $APPSMITH_NEW_RELIC_ENABLED = true ]]; then
  export APPSMITH_JAVA_ARGS+=" -Dnewrelic.config.agent_enabled=true -javaagent:/opt/newrelic/newrelic.jar"
fi
```

Then those arguments will only be added to the `java` command, if NewRelic is enabled.

2024-05-24 02:22 UTC, sharat87 commented on deploy/docker/fs/opt/appsmith/templates/docker.env.sh
> +
Do we need to add these here? Can we not please?

This script is used to generate an initial `docker.env` for new Appsmith installations. Adding new env variables to this file, doesn't mean existing users get them in their `docker.env`.

I'd recommend adding new env variables to this file as much as possible. Instead, if we want these env variables to be set, let's add them to the `run-java.sh`, inside an `if` block that checks if NewRelic is enabled. We only need these env variables for the backend, right? Since that's where the agent is running?

2024-05-24 02:22 UTC, sharat87 commented on deploy/docker/fs/opt/newrelic/newrelic-template.yml
> +  license_key: $APPSMITH_NEW_RELIC_APM_LICENSE_KEY
Change to literal block so we don't have to add `'` in the script when doing the replacement. Its simpler and safer in most cases.

```suggestion
  license_key: |
    $APPSMITH_NEW_RELIC_APM_LICENSE_KEY
```

2024-05-24 02:22 UTC, sharat87 commented on deploy/docker/fs/opt/newrelic/newrelic-template.yml
> +  app_name: $APPSMITH_NEW_RELIC_APM_NAME
Same as above.

```suggestion
  app_name: |
    $APPSMITH_NEW_RELIC_APM_NAME
```

2024-05-24 02:22 UTC, sharat87 commented on deploy/docker/fs/opt/appsmith/newrelic-reconfigure.mjs
> +    }
By using literal blocks for these keys in the yaml file, we don't have to add explicit quotes.

```suggestion
    for (const [key, val] of Object.entries(values)) {
        data = data.replace(key, val)
    }
```

2024-05-24 05:06 UTC, rajatagrawal reviewed
Reverted to comments

2024-05-24 05:06 UTC, rajatagrawal commented on deploy/docker/fs/opt/appsmith/templates/docker.env.sh
> +
The user will need to override the value of these environment variables. Would that be possible if these variables are added in run-java.sh ?

2024-05-29 08:17 UTC, sharat87 commented on deploy/docker/base.dockerfile
> +RUN curl -o /opt/newrelic/newrelic.jar https://download.newrelic.com/newrelic/java-agent/newrelic-agent/8.9.1/newrelic-agent-8.9.1.jar
Ah I see, yeah that fine then. Thanks.

2024-05-29 08:17 UTC, sharat87 commented on deploy/docker/fs/opt/appsmith/newrelic-reconfigure.mjs
> +    if (!(process.env.APPSMITH_NEW_RELIC_ENABLED == true)) {
@rajatagrawal, environment variables _always_ come in as strings. They're never of any other type. We have to convert them to a type we need, and store them in a separate variable. The `process.env` is _always_ of type `Record<string, undefined | string>`.

2024-05-29 08:17 UTC, sharat87 commented on deploy/docker/fs/opt/appsmith/run-java.sh
> +fi
@rajatagrawal, this as well please.

2024-05-29 08:17 UTC, sharat87 commented on deploy/docker/fs/opt/appsmith/templates/docker.env.sh
> +
Do we expect them to be able to override _all_ of these? That feels like too much flexibility, no?

> Would that be possible if these variables are added in run-java.sh ?

I don't think overriding them in `run-java.sh` makes much sense. 🤔

Other than `OTEL_SERVICE_NAME`, all of them have an `APPSMITH_` prefix, so these are env variables that we own. So, is the backend using them? Isn't it needed by other processes, like Caddy, for example? I see these env variables mentioned in `index.html`, so I'm guessing we need them in Caddy, right?

A more appropriate place would be `entrupoint.sh` itself. Just before we run the script to generate the YAML configuration file, let's set those env variables, that we need to override, and they should be available to all the processes.

Like we won't set `APPSMITH_NEW_RELIC_APM_LICENSE_KEY` at all. Let it come from `docker.env` or some other place, we don't ever set it. We only look for it, and use it if it's set, but we don't ever set it.

Am I making sense?

2024-05-29 08:47 UTC, rajatagrawal commented on deploy/docker/fs/opt/appsmith/templates/docker.env.sh
> +
There are three kinds of telemetry that we have.

1. Backend telemetry (APM) - needs `APPSMITH_NEW_RELIC_ENABLED`, `APPSMITH_NEW_RELIC_APM_LICENSE_KEY` and `APPSMITH_NEW_RELIC_APM_NAME`

2. Frontend web vitals : Needs `APPSMITH_NEW_RELIC_ACCOUNT_ID`, `APPSMITH_NEW_RELIC_APPLICATION_ID`, `APPSMITH_NEW_RELIC_BROWSER_AGENT_LICENSE_KEY`

3. Frontend spans and traces: Needs APPSMITH_NEW_RELIC_OTEL_SERVICE_NAME and `APPSMITH_NEW_RELIC_OTLP_LICENSE_KEY`

4. Backend spans and traces: `OTEL_SERVICE_NAME`, `APPSMITH_MICROMETER_METRICS_ENABLED`, `APPSMITH_NEWRELIC_MICROMETER_SERVICE_NAME`

We want to fill these environment variables only if monitoring is required for self hosted instances and their values would be known only then, since I would manually generate apps/license key on newrelic before sharing them with the customer when a customer needs new relic monitoring.

`APPSMITH_NEW_RELIC_BROWSER_AGENT_ENDPOINT` and `APPSMITH_NEW_RELIC_OTEL_EXPORTER_OTLP_ENDPOINT` can be hard coded by us for now since they will always be constant for newrelic.

2024-05-29 08:48 UTC, rajatagrawal commented on deploy/docker/fs/opt/appsmith/templates/docker.env.sh
> +
There are four kinds of telemetry that we have.

Backend telemetry (APM) - needs APPSMITH_NEW_RELIC_ENABLED, APPSMITH_NEW_RELIC_APM_LICENSE_KEY and APPSMITH_NEW_RELIC_APM_NAME

Frontend web vitals : Needs APPSMITH_NEW_RELIC_ACCOUNT_ID, APPSMITH_NEW_RELIC_APPLICATION_ID, APPSMITH_NEW_RELIC_BROWSER_AGENT_LICENSE_KEY

Frontend spans and traces: Needs APPSMITH_NEW_RELIC_OTEL_SERVICE_NAME and APPSMITH_NEW_RELIC_OTLP_LICENSE_KEY

Backend spans and traces: OTEL_SERVICE_NAME, APPSMITH_MICROMETER_METRICS_ENABLED, APPSMITH_NEWRELIC_MICROMETER_SERVICE_NAME

We want to fill these environment variables only if monitoring is required for self hosted instances and their values would be known only then, since I would manually generate apps/license key on newrelic before sharing them with the customer when a customer needs new relic monitoring.

APPSMITH_NEW_RELIC_BROWSER_AGENT_ENDPOINT and APPSMITH_NEW_RELIC_OTEL_EXPORTER_OTLP_ENDPOINT can be hard coded by us for now since they will always be constant for newrelic.

2024-05-29 08:51 UTC, rajatagrawal commented on deploy/docker/fs/opt/appsmith/run-java.sh
> +fi
Done

2024-05-29 08:53 UTC, rajatagrawal commented on deploy/docker/fs/opt/appsmith/run-java.sh
> +fi
@coderabbitai you missed mentioning change true to 'true'

2024-05-29 09:01 UTC, rajatagrawal commented on deploy/docker/fs/opt/appsmith/run-java.sh
> +fi
Thanks @coderabbitai

2024-06-19 12:22 UTC, closed without merging