chore: stat widget polish
appsmithorg/appsmith pull request #33696
Opened 2024-05-23 11:02 UTC by jsartisan

Fixes #33397

2024-05-23 11:35 UTC, jsartisan commented
/build-deploy-preview skip-tests=true

2024-05-24 06:47 UTC, jsartisan commented
/build-deploy-preview skip-tests=true

2024-05-24 08:34 UTC, KelvinOm requested changes

2024-05-24 08:34 UTC, KelvinOm commented on app/client/src/widgets/wds/WDSStatsWidget/component/index.tsx
> +      data-clickable={onClick !== undefined ? "" : undefined}
🤨

2024-05-24 08:34 UTC, KelvinOm commented on app/client/src/widgets/wds/WDSStatsWidget/config/anvilConfig.ts
> +  isLargeWidget: false,
This is not enough because `ResponsiveBehavior` should be changed to `hug`. The idea here is to be able to have multiple `StatsWidget` in the same zone.

2024-05-24 08:34 UTC, KelvinOm commented on app/client/src/widgets/wds/WDSStatsWidget/config/metaConfig.ts
> +  name: "Stats",
I'm just wondering why the name was changed?

2024-05-24 08:39 UTC, jsartisan commented on app/client/src/widgets/wds/WDSStatsWidget/component/index.tsx
> +      data-clickable={onClick !== undefined ? "" : undefined}
removed`className={styles.statbox}` as styles from `src/layoutSystems/anvil/common/styles.module.css` were enough.

I added `data-clickable` just to add styles  ( like hover )based on if there is onClick handler available. Let me remove this as we will be doing it separately.

2024-05-24 08:41 UTC, jsartisan commented on app/client/src/widgets/wds/WDSStatsWidget/config/metaConfig.ts
> +  name: "Stats",
It was there in list of things we need to do in the polish.

2024-05-24 09:19 UTC, KelvinOm commented on app/client/src/widgets/wds/WDSStatsWidget/config/anvilConfig.ts
> +  isLargeWidget: false,
Sorry, I'm a little confused about the terminology. Fill widget is the correct behavior, but as far as I can see, it does not work correctly.
Here's what we have:
![Снимок экрана 2024-05-24 в 12 18 01](https://github.com/appsmithorg/appsmith/assets/11555074/52a8ea7b-1cde-4c0c-8712-d2863f98775d)

And for example, how inputs works:
![Снимок экрана 2024-05-24 в 12 17 44](https://github.com/appsmithorg/appsmith/assets/11555074/b550b5cf-a289-4efa-a5d2-9fd9f68f38dc)

So Stats should behave the same way.

2024-05-24 09:48 UTC, jsartisan commented on app/client/src/widgets/wds/WDSStatsWidget/component/index.tsx
> +      data-clickable={onClick !== undefined ? "" : undefined}
Removed this prop.

2024-05-24 09:48 UTC, KelvinOm commented
/build-deploy-preview skip-tests=true

2024-05-24 09:51 UTC, jsartisan commented
/build-deploy-preview skip-tests=true

2024-05-24 12:03 UTC, jsartisan commented
/build-deploy-preview skip-tests=true

2024-05-27 06:48 UTC, jsartisan commented
/build-deploy-preview skip-tests=true

2024-05-27 08:00 UTC, jsartisan commented
/build-deploy-preview skip-tests=true

2024-05-27 10:40 UTC, KelvinOm submitted a review, later dismissed

2024-05-27 13:08 UTC, KelvinOm approved these changes

2024-05-27 13:48 UTC, KelvinOm approved these changes

2024-05-27 16:54 UTC, merged