fix: removed unnecessary individual DB calls to plugin and fetched al…
appsmithorg/appsmith pull request #33712
Opened 2024-05-24 08:17 UTC by sneha122

…l at once

## Description

This PR adds:
- Additional instrumentation around `datasources` section of consolidated API

Datasources fetch process looks as below:
1. It first fetches all datasources belonging to a workspace
2. For each datasources, fetches its datasourceStorages
     a. Calls populateHintMessages to populate messages property in datasourceStorage
     b. Fetches plugin from DB
     c. Gets pluginExecutor from plugin
     d. calls getHintMessages on pluginExecutorMono
3. Marks recently used datasources (sorts all datasources based on createdAt in desc order and marks top 3 as recent)

This PR adds improvements around point 2.b so that we fetch all plugins at once in one DB call and then use that to process hint messages for all datasourceStorages, this avoiding multiple calls to DB

Fixes #33711 #33678
_or_  
Fixes `Issue URL`
> [!WARNING]  
> _If no issue exists, please create an issue first, and check with the maintainers if the issue is valid._

## Automation

/ok-to-test tags="@tag.Datasource"

### :mag: Cypress test results

> [!CAUTION]  
> If you modify the content in this section, you are likely to disrupt the CI result for your PR.

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [ ] No

2024-05-29 08:33 UTC, sneha122 commented
/build-deploy-preview skip-tests=true

2024-06-03 07:18 UTC, NilanshBansal requested changes

2024-06-03 07:18 UTC, NilanshBansal commented on app/server/appsmith-server/src/main/java/com/appsmith/server/datasourcestorages/base/DatasourceStorageServiceCEImpl.java
> -        final Mono<Plugin> pluginMono = pluginService.findById(datasourceStorage.getPluginId());
@sneha122 Nit: Is there any specific need to remove the final keyword?

2024-06-03 07:18 UTC, NilanshBansal commented on app/server/appsmith-server/src/main/java/com/appsmith/server/datasourcestorages/base/DatasourceStorageServiceCEImpl.java
> +
@sneha122 Can we please reduce the code duplication in the overloaded method populateHintMessages(). 
One way of doing this could be to invoke the `populateHintMessages(
            DatasourceStorage datasourceStorage, Map<String, Plugin> pluginsMap)` from `populateHintMessages(DatasourceStorage datasourceStorage)` with pluginsMap as null.

2024-06-03 07:18 UTC, NilanshBansal commented on app/server/appsmith-server/src/test/java/com/appsmith/server/services/DatasourceStorageServiceTest.java
> +        datasourceStorage.setWorkspaceId(workspace.getId());
Nit: @sneha122 why is this new LOC addition required for an existing test case?

2024-06-03 07:18 UTC, NilanshBansal commented on app/server/appsmith-server/src/test/java/com/appsmith/server/services/DatasourceStorageServiceTest.java
> +        datasourceStorage.setWorkspaceId(workspace.getId());
Same as L153.

2024-06-03 07:18 UTC, NilanshBansal commented on app/server/appsmith-server/src/test/java/com/appsmith/server/services/DatasourceStorageServiceTest.java
> +        datasourceStorage.setWorkspaceId(workspace.getId());
Same as L153.

2024-06-03 07:52 UTC, sneha122 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/datasourcestorages/base/DatasourceStorageServiceCEImpl.java
> -        final Mono<Plugin> pluginMono = pluginService.findById(datasourceStorage.getPluginId());
Thanks @NilanshBansal will add it back

2024-06-03 07:53 UTC, sneha122 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/datasourcestorages/base/DatasourceStorageServiceCEImpl.java
> +
@NilanshBansal Yes will do this, thanks for the suggestion!

2024-06-03 07:53 UTC, sneha122 commented on app/server/appsmith-server/src/test/java/com/appsmith/server/services/DatasourceStorageServiceTest.java
> +        datasourceStorage.setWorkspaceId(workspace.getId());
@NilanshBansal This is not required at all, will remove it

2024-06-03 09:15 UTC, NilanshBansal approved these changes
LGTM

2024-06-03 09:57 UTC, sneha122 commented
/build-deploy-preview skip-tests=true

2024-06-03 12:33 UTC, merged