test: updated tests with aghelper table methods
appsmithorg/appsmith pull request #33737
Opened 2024-05-27 05:51 UTC by NandanAnantharamu

updated isSelectedRow() with table_SelectedRow()

2024-05-27 05:52 UTC, NandanAnantharamu commented
/ci-test-limit

2024-05-29 11:41 UTC, ApekshaBhosale requested changes

2024-05-29 11:41 UTC, ApekshaBhosale commented on app/client/cypress/e2e/Regression/ClientSide/Binding/TextTableV2_spec.js
> +      // cy.isSelectRow(1);
remove commented code

2024-05-29 11:41 UTC, ApekshaBhosale commented on app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV1/Table_spec.js
> +    // cy.isSelectRow(1);
do we not need `_.table.SelectTableRow(1);` here?

remove commented code

2024-05-29 11:56 UTC, NandanAnantharamu commented on app/client/cypress/e2e/Regression/ClientSide/Binding/TextTableV2_spec.js
> +      // cy.isSelectRow(1);
done

2024-05-31 08:29 UTC, ApekshaBhosale approved these changes

2024-05-31 08:31 UTC, merged