feat: adding unique index to the slug field in tenant collection.
appsmithorg/appsmith pull request #33776
Opened 2024-05-28 03:01 UTC by Naveen-Goud

PR for **Task - #33377**  adding unique index to the slug field in tenant collection.
 
 **What I have done in this PR:**
 
 1.updated the **@unique** with **@Indexed(Unique=true)** in the tenant collection.
 2.added a changelog file for the migration of the data.
 3. the migration also  checks the slug ids are unique, and trying to insert with the same data also  returns a error message.
 
 thank you.

2024-05-30 08:01 UTC, nsarupr requested changes
HI @Naveen-Goud , thanks for taking out time to make contributions to `appsmith_`. I have reviewed the PR. Please go through the changes requested.

2024-06-03 08:03 UTC, NilanshBansal approved these changes
LGTM

2024-06-03 08:38 UTC, NilanshBansal requested changes
@Naveen-Goud can you please use makeIndex() method instead of creating index name.

2024-06-03 09:27 UTC, NilanshBansal commented on app/server/appsmith-server/src/main/java/com/appsmith/server/domains/Tenant.java
> +    @Indexed(Unique= true)
@Naveen-Goud this change is not required, only migration should be sufficient.
Also Unique = true returns a compilation error.

2024-06-03 09:54 UTC, NilanshBansal commented
@Naveen-Goud we might not need to implement this right now because we haven't yet moved to multi-tenancy fully. 
There is always one document in the database.
<img width="594" alt="image" src="https://github.com/appsmithorg/appsmith/assets/25542733/cd7bafb9-3027-4d58-93a4-047172935726">
Ref:https://github.com/appsmithorg/appsmith/issues/33377#issuecomment-2144763283

Apologies for the inconvenience, thank you for all your efforts in contributing to appsmith. You can continue contributing to appsmith by selecting issues from [this](https://github.com/appsmithorg/appsmith/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+First+Issue%22) list. Looking forward to your valuable contributions 🙏

2024-06-03 09:54 UTC, closed without merging