chore: Add override context during runtime params eval
appsmithorg/appsmith pull request #33809
Opened 2024-05-29 04:01 UTC by ashit-rath

## Description
Adds `overrideContent` to be set during the execution of actions during runtime with execution params. This features enables to override properties/paths of entities during runtime and not affecting the dataTree

Fixes #`Issue Number`  
_or_  
Fixes `Issue URL`
> [!WARNING]  
> _If no issue exists, please create an issue first, and check with the maintainers if the issue is valid._

## Automation

/ok-to-test tags="@tag.All"

### :mag: Cypress test results

> [!CAUTION]  
> If you modify the content in this section, you are likely to disrupt the CI result for your PR.

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [ ] No

2024-05-29 04:01 UTC, ashit-rath commented
/build-deploy-preview skip-tests=true

2024-05-30 04:49 UTC, ashit-rath commented on app/client/src/workers/Evaluation/evaluate.ts
> +    });
I prefer the readability of forEach and how much performance difference does it make? share numbers

2024-05-30 04:50 UTC, ashit-rath commented on app/client/src/workers/Evaluation/evaluate.ts
>    result: any;
Yes I agree but that can be a bigger change, I'll handle this in a different PR

2024-05-30 04:51 UTC, ashit-rath commented on app/client/src/workers/Evaluation/evaluate.ts
> +    });
That's alright, since the difference is negligible; it's not worth testing this out.

2024-05-30 04:52 UTC, ashit-rath commented on app/client/src/workers/Evaluation/evaluate.ts
> +};
I prefer forEach over for...of

2024-05-30 04:53 UTC, ashit-rath commented on app/client/src/workers/common/DataTreeEvaluator/test.ts
> +      const getDynamicValueCapturedParams: any[] = [];
I think this suggestion is incorrect since params are not always an object.

2024-05-30 04:53 UTC, ashit-rath commented on app/client/src/workers/common/DataTreeEvaluator/test.ts
> +      let generateOverrideContextParams;
I think this suggestion is incorrect since params are not always an object. So it's okay to have implicit any

2024-05-30 04:55 UTC, ashit-rath commented on app/client/src/workers/common/DataTreeEvaluator/test.ts
> +      const getDynamicValueCapturedParams: any[] = [];
We aren't looking at type safety much for this, since this is a test and the values matter much more here so it's okay to use any in this case.

2024-05-30 05:34 UTC, ashit-rath commented
/build-deploy-preview skip-tests=true

2024-05-30 09:13 UTC, ApekshaBhosale requested changes

2024-05-30 09:13 UTC, ApekshaBhosale commented on app/client/src/workers/Evaluation/evaluate.ts
> +      const [entityName] = path.split(".");
we have already function for this 'getEntityNameAndPropertyPath'

2024-05-30 09:13 UTC, ApekshaBhosale commented on app/client/src/workers/common/DataTreeEvaluator/index.ts
> +    const dataTree = klona(this.evalTree);
why do we need clone here @ashit-rath ?

2024-05-31 03:42 UTC, ashit-rath commented on app/client/src/workers/common/DataTreeEvaluator/index.ts
> +    const dataTree = klona(this.evalTree);
This was there from [before](https://github.com/appsmithorg/appsmith/pull/33809/files#diff-62e9fca197dd58701cbf3db59eff2820147b0384079b3507ead808a7e419a6d5L1731). I just moved it to the top to access. I don't exactly know why

2024-05-31 03:43 UTC, ashit-rath commented on app/client/src/workers/Evaluation/evaluate.ts
> +      const [entityName] = path.split(".");
Ahh Amazing

2024-05-31 06:19 UTC, ApekshaBhosale approved these changes

2024-05-31 07:29 UTC, merged