feat: tooltip message change of git pull button
appsmithorg/appsmith pull request #33820
Opened 2024-05-29 08:47 UTC by tavishbarua94

## Description
> [!TIP]  
> _User should be able to get correct tooltip message :
When the remote branch is ahead of the local branch along with the user is having some uncommitted changes.
Tooltip message should be “You have uncommitted changes, please commit or discard your changes before pulling the remote changes”._
>

![image](https://github.com/appsmithorg/appsmith/assets/164161467/25edc6b7-5361-44dd-a378-5c0822024bd2)

Fixes #`32973`  
_or_  
Fixes `https://github.com/appsmithorg/appsmith/issues/32973`
> [!WARNING]  
> _If no issue exists, please create an issue first, and check with the maintainers if the issue is valid._

## Automation

/ok-to-test tags=""

### :mag: Cypress test results

> [!CAUTION]  
> If you modify the content in this section, you are likely to disrupt the CI result for your PR.

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [ ] No

2024-05-31 02:39 UTC, akshayvijayjain commented
@RoopKrrish9696 , 
@infinitetrooper 
@brayn003 
Let us know your review on this pull request.

2024-05-31 06:39 UTC, brayn003 commented
Hey @tavishbarua94 thank you for raising this PR. I will help you to get this merged

2024-05-31 06:40 UTC, brayn003 requested changes
Minor change

2024-05-31 06:40 UTC, brayn003 commented on app/client/src/ce/constants/messages.ts
> +  "You have uncommitted changes. Please commit or discard your changes before pulling the remote changes.";
Can we please change this to -
```
You have uncommitted changes. Please commit or discard before pulling the remote changes.
```

2024-05-31 11:53 UTC, tavishbarua94 commented on app/client/src/ce/constants/messages.ts
> +  "You have uncommitted changes. Please commit or discard your changes before pulling the remote changes.";
Hey @brayn003 ,changes done in latest commit 130c1d698462aafdfc7d396a1b70ce0e8e93e99a


++ @akshayvijayjain

2024-06-03 11:31 UTC, brayn003 approved these changes

2024-06-04 09:55 UTC, merged