fix: ignore DSL parsing errors in the forking flow
appsmithorg/appsmith pull request #33831
Opened 2024-05-29 10:17 UTC by AnaghHegde

## Description
The expectation for any server side flow today that is using `updateLayout` exclusively is to ignore DSL parsing or similar kind of errors and proceed assuming that the next client side interaction will fix the problem. The actual DSL issue is a problem coming up from incorrectly written DSL migrations which for these apps won't make a difference even if we fix them retroactively. 

Fixes https://github.com/appsmithorg/appsmith/issues/33750

## Automation

/ok-to-test tags="@tag.Forking"

### :mag: Cypress test results

> [!CAUTION]  
> If you modify the content in this section, you are likely to disrupt the CI result for your PR.

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [ ] No

2024-05-29 11:36 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/fork/internal/ApplicationForkingServiceCEImpl.java
> +                    log.error("Error while parsing DSL {} ", throwable.getMessage());
Let's catch a more specific error, other kinds of failures shouldn't be ignored

2024-05-29 14:33 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/fork/internal/ApplicationForkingServiceCEImpl.java
> +                    log.error("Error while parsing DSL {} ", throwable.getMessage());
Done

2024-05-29 15:04 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/fork/internal/ApplicationForkingServiceCEImpl.java
>                  .onErrorResume(throwable -> {
Can we use a comparison by type instead of a string compare here please?

2024-05-29 15:16 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/fork/internal/ApplicationForkingServiceCEImpl.java
>                  .onErrorResume(throwable -> {
I thought of that but the type of exception will be same right? For example - if the DSL is corrupted or has a missing element still the parsing will fail. Only the message will be different. Hence i am doing comparison by string and not type.

2024-05-30 04:43 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/fork/internal/ApplicationForkingServiceCEImpl.java
>                  .onErrorResume(throwable -> {
I think it's safe to assume that the only kind of failures we expect to see here are incorrect bindingPaths. If there were other kinda of failures, they would surface in normal updateLayout calls as well.

2024-05-30 04:49 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/fork/internal/ApplicationForkingServiceCEImpl.java
>                  .onErrorResume(throwable -> {
If i have to filter by exception type it is going to be `AppsmithException` and even if this flow fails for any other reason also the exception type will still be same. Hence i am filtering via the error message.

2024-05-30 05:55 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/fork/internal/ApplicationForkingServiceCEImpl.java
>                  .onErrorResume(throwable -> {
I'm sorry, looks like we're misunderstanding what a type check means. An error type check in Appsmith is always meant to check for `AppsmithError` types, since all of our caught exceptions would be `AppsmithException` type. By making a string check here, we're making the code brittle because tomorrow when the error message copy is altered for any reason, this flow will stop catching that error. Is this making sense?

Let's also add a test case to avoid this breaking in the future.

2024-05-30 09:58 UTC, nidhi-nair commented on app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ForkingServiceTest.java
> +package com.appsmith.server.solutions;
Nit, this test belongs in the fork package since we have moved to structuring classes by features and domains

2024-05-30 09:58 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/fork/internal/ApplicationForkingServiceCEImpl.java
> +                    if (throwable instanceof AppsmithException e) {
Nit, this can be a single check instead of two successive checks.

2024-05-30 09:59 UTC, nidhi-nair requested changes
LGTM, needs a few nitpick changes.

2024-05-30 10:04 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/fork/internal/ApplicationForkingServiceCEImpl.java
> +                    if (throwable instanceof AppsmithException e) {
@nidhi-nair Done. Can you check the PR again?

2024-05-30 10:25 UTC, nidhi-nair approved these changes

2024-05-30 11:25 UTC, merged