Added date picker input field validation to have input as ISO string
appsmithorg/appsmith pull request #3397
Opened 2021-03-04 10:57 UTC by vicky-primathon

## Description
Added date picker input field validation to accept input as ISO string

Fixes #3297 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-03-04 12:55 UTC, riodeuno commented
https://github.com/appsmithorg/appsmith/issues/3297#issuecomment-790595073

2021-03-15 10:04 UTC, riodeuno commented
@vicky-primathon 
- Please resolve the merge conflicts
- Please update the validation message to specify the use of `ISO8601 string | null` instead of `string | null`.

2021-03-16 05:17 UTC, riodeuno requested changes

2021-03-16 05:17 UTC, riodeuno commented on app/client/src/constants/FieldExpectedValue.ts
> +    defaultDate: "string | null", //TODO:Vicky validate this property
This  does not mention ISO8601 date string.

2021-03-16 05:17 UTC, riodeuno commented on app/client/src/constants/FieldExpectedValue.ts
> +    defaultDate: "string | null", //TODO:Vicky validate this property
<img width="644" alt="Screenshot 2021-03-16 at 10 45 22 AM" src="https://user-images.githubusercontent.com/103687/111259453-e7d00580-8644-11eb-8860-5a1f6d237f9d.png">

2021-03-16 05:17 UTC, riodeuno commented on app/client/src/workers/validation.test.ts
> +describe("validateDateString test", () => {
We're not testing for `undefined` and `"abcd"` for format and date values. Let's make sure these do not break the app.

2021-03-17 08:01 UTC, vicky-primathon commented on app/client/src/constants/FieldExpectedValue.ts
> +    defaultDate: "string | null", //TODO:Vicky validate this property
@riodeuno made changes in CodeEditor and EvaluatedValuePopup to show message passed from validations. This could impact other areas. Need more manual testing around Evaluated Value popup.

2021-03-17 12:04 UTC, riodeuno approved these changes

2021-03-24 08:54 UTC, riodeuno approved these changes

2021-03-24 12:12 UTC, merged