chore: password encrypted value check test datasource
appsmithorg/appsmith pull request #34253
Opened 2024-06-14 11:19 UTC by vivonk

## Description
> [!TIP]  
> _Add a TL;DR when the description is longer than 500 words or extremely technical (helps the content, marketing, and DevRel team)._
>
> _Please also include relevant motivation and context. List any dependencies that are required for this change. Add links to Notion, Figma or any other documents that might be relevant to the PR._

Fixes https://github.com/appsmithorg/appsmith/issues/34041
_or_  
Fixes `Issue URL`
> [!WARNING]  
> _If no issue exists, please create an issue first, and check with the maintainers if the issue is valid._

## Automation

/ok-to-test tags=""

### :mag: Cypress test results

> [!CAUTION]  
> If you modify the content in this section, you are likely to disrupt the CI result for your PR.

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [ ] No

2024-06-15 06:58 UTC, sharat87 requested changes
Reporting a suggestion, let me know if you disagree. 🙂

2024-06-15 06:58 UTC, sharat87 commented on app/server/appsmith-server/src/test/java/com/appsmith/server/services/DatasourceServiceTest.java
> +    private DatasourceStorage getDatasourceStorage(String datasourceId, String envId) {
Instead of changing so much in the test, can we make a minimal and focused change please? Ideally, we don't want to touch the tests as much as possible between `release` and `pg` so we can be sure we're asserting the same way as much as possible.

So in this case, the problem is only the "password" assertion part of the whole test. So let's just get the password from the database, and assert just that. Something like this can get the password you need:

![shot-2024-06-15-06-54-50](https://github.com/appsmithorg/appsmith/assets/120119/2f533fbf-3a0c-4828-872f-90ce0b308d6d)

Then, only the password assertion needs to be changed to this:

```java
assertThat(EncryptionHelper.decrypt(getDatasourcePassword(savedDatasource.getId(), defaultEnvironmentId)))
                            .isEqualTo(password);
```

This way, we only fetch the very minimum piece of information we want from the database.

What do you think?

2024-06-17 11:58 UTC, vivonk commented on app/server/appsmith-server/src/test/java/com/appsmith/server/services/DatasourceServiceTest.java
> +    private DatasourceStorage getDatasourceStorage(String datasourceId, String envId) {
Agree, making these changes

2024-06-17 12:05 UTC, sharat87 requested changes
Looks good. One minor item and we should merge.

2024-06-17 12:05 UTC, sharat87 commented on app/server/appsmith-server/src/test/java/com/appsmith/server/services/DatasourceServiceTest.java
> +    ObjectMapper objectMapper = new ObjectMapper();
Looks like we don't need to add this.

2024-06-17 12:06 UTC, vivonk commented on app/server/appsmith-server/src/test/java/com/appsmith/server/services/DatasourceServiceTest.java
> +    ObjectMapper objectMapper = new ObjectMapper();
Agree

2024-06-17 12:08 UTC, sharat87 reviewed
❤️

2024-06-17 12:08 UTC, sharat87 approved these changes

2024-06-17 12:09 UTC, merged