Added tests for Oauth and Stubbed tests
appsmithorg/appsmith pull request #3463
Opened 2021-03-09 17:21 UTC by NandanAnantharamu

Oauth test
Stub Mongo DS tests
Updated DS tests by categorising the routes

2021-03-17 05:27 UTC, hetunandu requested changes
Minor

2021-03-17 05:27 UTC, hetunandu commented on app/client/cypress/fixtures/testdata.json
> +  "bindChardData": "{{Chart1.selectedDataPoint",
Spelling mistake
```suggestion
  "bindChartData": "{{Chart1.selectedDataPoint",
```

2021-03-19 13:23 UTC, hetunandu submitted a review, later dismissed

2021-03-23 09:08 UTC, hetunandu approved these changes

2021-03-25 12:56 UTC, NandanAnantharamu commented on app/client/cypress/fixtures/testdata.json
> +  "bindChardData": "{{Chart1.selectedDataPoint",
this is resolved

2021-03-25 13:31 UTC, hetunandu approved these changes

2021-03-26 09:11 UTC, hetunandu commented on app/client/cypress/support/commands.js
> +      accept: "application/json";
```suggestion
      accept: "application/json";
      origin: "dev.appsmith.com";
```

2021-03-26 09:12 UTC, hetunandu approved these changes

2021-04-06 11:41 UTC, hetunandu approved these changes

2021-04-06 13:29 UTC, merged