Feature/property pane renovate scroll fix
appsmithorg/appsmith pull request #3498
Opened 2021-03-11 14:59 UTC by ram-primathon

## Description
> remove scroll background color in property pane

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-03-12 04:53 UTC, hetunandu requested changes

2021-03-12 04:53 UTC, hetunandu commented on app/client/src/pages/Editor/PropertyPane/index.tsx
> +  }
Can we apply this in the scrollbar styles directly?

2021-03-12 05:33 UTC, ram-primathon commented on app/client/src/pages/Editor/PropertyPane/index.tsx
> +  }
done

2021-03-12 05:36 UTC, hetunandu requested changes

2021-03-12 05:36 UTC, hetunandu commented on app/client/src/pages/Editor/PropertyPane/index.tsx
> +        backgroundColor={Colors.TRANSPARENT}
this is a different fix. Why did we do it like this instead? That fix worked just needed to be part of the scrollbarLight

2021-03-15 07:31 UTC, hetunandu commented
This is rendering the scrollbar outside the property pane

2021-03-15 10:43 UTC, hetunandu approved these changes

2021-03-15 10:43 UTC, merged