SwitchWidget within FormWidget tests
appsmithorg/appsmith pull request #3501
Opened 2021-03-11 17:27 UTC by NandanAnantharamu

Switch Widget within farm widget test

2021-03-23 09:18 UTC, hetunandu requested changes

2021-03-23 09:18 UTC, hetunandu commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/FormWithSwitch_spec.js
> +    cy.wait(7000);
Remove this wait

2021-03-25 13:56 UTC, NandanAnantharamu commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/FormWithSwitch_spec.js
> +    cy.wait(7000);
This is taken care now with latest commit

2021-03-25 14:09 UTC, hetunandu approved these changes

2021-03-25 16:08 UTC, merged