Added test for tableWidget bug
appsmithorg/appsmith pull request #3528
Opened 2021-03-12 13:19 UTC by NandanAnantharamu

Test added for table widget bug related to derived column

2021-03-17 05:23 UTC, hetunandu requested changes
Minor change requested

2021-03-17 05:23 UTC, hetunandu commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/Table_Derived_Column_Data_validation_spec.js
> +    );
Is there a better way to do this? This seems very specific and might break in the future

2021-03-17 07:34 UTC, NandanAnantharamu commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/Table_Derived_Column_Data_validation_spec.js
> +    );
updated the way we handle this assert

2021-03-23 16:26 UTC, hetunandu approved these changes

2021-03-25 09:30 UTC, mohanarpit approved these changes

2021-03-25 10:31 UTC, hetunandu approved these changes

2021-03-25 11:01 UTC, merged