Remove unnecessary vertical scrollbar from inside table widget
appsmithorg/appsmith pull request #3535
Opened 2021-03-13 06:37 UTC by vicky-primathon

## Description
Remove unnecessary scrollbar from inside table widget

Fixes #2895 #3249 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-03-15 10:16 UTC, riodeuno commented
@vicky-primathon Let's make the scrollbar a virtual scrollbar, which will not take up space in the table itself.

2021-03-18 08:55 UTC, riodeuno commented
@vicky-primathon 
- Horizontal scrollbar never shows, it should always show for users with mouse
- Vertical scrollbar should show when scrolling
- Header scrollbar should also be virtual scrollbar

2021-03-22 10:18 UTC, riodeuno requested changes

2021-03-22 10:18 UTC, riodeuno commented on app/client/src/components/ads/HorizontalScrollIndicator.tsx
> +  left: ${(props) => (props.left ? props.left : "0")};
Let's move the common styles to `DefaultTheme.tsx`

2021-03-22 10:18 UTC, riodeuno commented on app/client/src/components/ads/HorizontalScrollIndicator.tsx
> +        className="scrollbar-thumb"
Let's remove this className

2021-03-22 10:18 UTC, riodeuno commented on app/client/src/components/designSystems/appsmith/TableComponent/Table.tsx
> +  // const tableWrapperRef = React.useRef<HTMLDivElement>(null);
Let's remove commented code.

2021-03-22 10:18 UTC, riodeuno commented on app/client/src/components/designSystems/appsmith/TableComponent/Table.tsx
> +        <ScrollIndicator
Let's rename this component to be `VerticalScrollIndicator`

2021-03-22 10:18 UTC, riodeuno commented on app/client/src/components/designSystems/appsmith/TableComponent/TableStyledWrappers.tsx
> +  scrollbar-width: none;
Let's create a css called `DisableNativeScrollbar` and use that.

2021-03-22 10:18 UTC, riodeuno commented
@vicky-primathon The horizontal scrollbar isn't showing. I'm on Mac, Chrome, external mouse and keyboard.

2021-03-31 05:23 UTC, riodeuno commented on app/client/src/pages/Editor/PropertyPane/index.tsx
> +// import VerticalScrollIndicator from "components/ads/VerticalScrollIndicator";
Let's remove this commented code.

2021-04-14 16:27 UTC, areyabhishek commented
@vicky-primathon @somangshu When can this PR be closed?

2021-04-15 07:35 UTC, somangshu commented
> @vicky-primathon @somangshu When can this PR be closed?

@areyabhishek we are now testing the deploy preview and should get merged max by mid next week.

2021-04-19 09:56 UTC, somangshu commented
#4006 is created on top of this.

2021-04-20 07:43 UTC, mohanarpit commented
@somangshu @vicky-primathon Can we close this in favour of #4006 then?

2021-04-20 10:48 UTC, riodeuno commented
Closing in favour of #4006

2021-04-20 10:48 UTC, closed without merging