add ellipsis to org name in settings
appsmithorg/appsmith pull request #3572
Opened 2021-03-16 07:54 UTC by kaushik94

## Description
Truncates org name in org settings

Fixes # (issue)
#3061 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-03-16 08:09 UTC, riodeuno requested changes
One minor change requested. Rest looks good.

2021-03-16 08:09 UTC, riodeuno commented on app/client/src/constants/DefaultTheme.tsx
> +export const addEllipsisToTextBlock = css`
Let's rename this to `truncateTextWithEllipsis` or `EllipsizeText`. First alternative is more informative.

2021-03-16 18:53 UTC, kaushik94 commented on app/client/src/constants/DefaultTheme.tsx
> +export const addEllipsisToTextBlock = css`
@riodeuno I made the requested changes as well as merged release into. Please take a look.

2021-03-18 06:19 UTC, riodeuno approved these changes
Nice PR!
- Modular code
- Includes Cypress tests
- Doesn't seem to require functional jest test

LGTM!

2021-03-18 07:09 UTC, merged