menu component implemented and tabs selected ui bug fixed
appsmithorg/appsmith pull request #358
Opened 2020-08-19 09:18 UTC by devrk96

2020-08-24 04:41 UTC, satbir121 commented on app/client/src/components/ads/Menu.tsx
> +const MenuOption = styled("div")`
Rename to `styled.div`

2020-08-24 06:55 UTC, riodeuno requested changes

2020-08-24 06:55 UTC, riodeuno commented on app/client/src/components/ads/Menu.tsx
> +                return props.onSelect(e.target);
`onClick` doesn't need to have a `return` statement.

2020-08-28 10:00 UTC, satbir121 approved these changes

2020-08-28 10:51 UTC, merged