add new querypane header
appsmithorg/appsmith pull request #3587
Opened 2021-03-16 16:55 UTC by ram-primathon

## Description
> add new querypane header

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-03-17 05:21 UTC, hetunandu requested changes

2021-03-17 05:21 UTC, hetunandu commented on app/client/src/pages/Editor/routes.tsx
> +    <DrawerWrapper {...props} isAPIPath={true}>
Why is this new prop needed?

2021-03-17 05:21 UTC, hetunandu commented on app/client/src/pages/Editor/QueryEditor/Form.tsx
> +                <ActionNameEditor page="API_PANE" />
Can we remove this page prop now? I don't think it is needed anymore

2021-03-18 07:50 UTC, ram-primathon commented on app/client/src/pages/Editor/routes.tsx
> +    <DrawerWrapper {...props} isAPIPath={true}>
this was to make container with 100%. removed

2021-03-18 07:52 UTC, ram-primathon commented on app/client/src/pages/Editor/QueryEditor/Form.tsx
> +                <ActionNameEditor page="API_PANE" />
it is getting used in RapidApiEditorForm

2021-03-19 10:03 UTC, hetunandu approved these changes

2021-03-19 10:03 UTC, merged