Make filteredTableData and computed columns as derived properties
appsmithorg/appsmith pull request #3607
Opened 2021-03-17 21:04 UTC by riodeuno

## Description
Make `filteredTableData` and computed `columns` as derived properties

Fixes #3335

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

All existing tests must pass

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-03-22 05:24 UTC, hetunandu requested changes
Really happy to see become a derived property. Table is less complex today thanks to this change 😁

2021-03-22 05:24 UTC, hetunandu commented on app/client/src/widgets/TableWidget/derived.js
> +  getTableColumns: (props) => {
Can we add some jest test for this?

2021-03-22 05:24 UTC, hetunandu commented on app/client/src/widgets/TableWidget/derived.js
> +  getTableColumns: (props) => {
Wondering why did we not make this file a typescript file

2021-03-22 05:24 UTC, hetunandu commented on app/client/src/widgets/TableWidget/index.tsx
> +              : []
Should be handled by the widget validations

2021-03-22 05:24 UTC, hetunandu commented on app/client/src/widgets/TableWidget/index.tsx
> +          pageNo={this.props.pageNo || 1}
Should be handled by the widget validations

2021-03-23 14:58 UTC, riodeuno commented on app/client/src/widgets/TableWidget/derived.js
> +  getTableColumns: (props) => {
This is technically loading this file as a raw string and then parsing the different functions in the `parsedDerivedProperties.ts`. These functions are then passed as is in the derivedPropertiesMap.

2021-03-23 15:00 UTC, riodeuno commented on app/client/src/widgets/TableWidget/derived.js
> +  getTableColumns: (props) => {
Yes, these are designed this way - pure functions using only props as an argument for this very reason. Complicated derived properties can now be tested avoiding issues we faced in the TextWidget.

2021-03-23 15:01 UTC, riodeuno commented on app/client/src/widgets/TableWidget/derived.js
> +  getTableColumns: (props) => {
We should also make the `parsedDerivedProperties.ts` a generic utility function to be used in other widgets. This is something we're getting done in the list widget project.

2021-03-24 08:34 UTC, hetunandu submitted a review, later dismissed

2021-03-24 18:29 UTC, areyabhishek approved these changes

2021-03-24 19:25 UTC, merged