Feature/ads editable text component
appsmithorg/appsmith pull request #362
Opened 2020-08-19 16:09 UTC by devrk96

2020-08-24 08:39 UTC, riodeuno requested changes

2020-08-24 08:39 UTC, riodeuno commented on app/client/src/components/ads/Icon.tsx
> +    case "edit":
I was wondering if we can get these values from an enum instead?

2020-08-24 08:39 UTC, riodeuno commented on app/client/src/components/ads/EditableText.tsx
> +          : _.noop
Please tree-shake the lodash module wherever possible. `import {noop} from "lodash"`

2020-08-24 08:39 UTC, riodeuno commented on app/client/src/components/ads/EditableText.tsx
> +        savingState.isSaving &&
`savingState.isSaving` should be `false` here or `true`? Please revisit this code.
`savingState.isSaving` check may not be required as we're doing the `savingState.name === SavingState.NOT_STARTED` above. Please check this part of the code.

2020-08-24 08:39 UTC, riodeuno commented on app/client/src/components/ads/EditableText.tsx
> +    isSaving: boolean;
`isSaving` seems to be a duplicate of `SavingState.STARTED`. Please confirm if we need both these properties in the state.

2020-08-24 08:39 UTC, riodeuno commented on app/client/src/components/ads/EditableText.tsx
> +  const editMode = (e: React.MouseEvent) => {
`editMode`, `onInputChange` may need to be wrapped in `useCallback` if the dependencies change frequently.

2020-08-26 07:33 UTC, satbir121 approved these changes

2020-08-26 07:34 UTC, satbir121 approved these changes

2020-08-26 09:04 UTC, satbir121 approved these changes

2020-08-26 09:04 UTC, merged