Debugger logs
appsmithorg/appsmith pull request #3633
Opened 2021-03-19 05:17 UTC by akash-codemonk

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.

## Description
> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation 
> and context. List any dependencies that are required for this change.

Fixes # (issue)
> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce. 
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-04-20 10:22 UTC, akash-codemonk commented
/ok-to-test sha=3a031cd

2021-04-20 11:14 UTC, rishabhsaxena requested changes
Mostly comments based on theme usage and defining functions instead of anonymous functions.

Other notes:
- Prop pane should z-index should be more than debugger
- Scroll with expanded state, doesn’t scroll to the extreme bottom, think this is due to height calculated before the log item is expanded, we could try using scrollIntoView / wrapping the logic to set the scroll position within setTimeout(()=>{}) w/o delay it might postpone height calc
- Empty results text doesn’t show for query results?

2021-04-20 11:14 UTC, rishabhsaxena commented on app/client/src/entities/AppsmithConsole/index.ts
> +  logType?: LOG_TYPE;
Should we make this mandatory, that way we'd have types for all log events? Also we could move all the log types to a single file like we have redux action constants.

2021-04-21 08:04 UTC, rishabhsaxena commented
@akash-codemonk we could also consider `react-window` for optimising the list instead of pagination, if that's the reason we're using pagination for?

2021-04-21 08:43 UTC, akash-codemonk commented
> @akash-codemonk we could also consider `react-window` for optimising the list instead of pagination, if that's the reason we're using pagination for?

Yeah I had a look at that. Dealing with dynamic heights(of the tab as well as individual logs) seemed cumbersome with react-window since it looks like the size dimensions are required as inputs for it to work.

2021-04-22 09:03 UTC, akash-codemonk commented
> * Prop pane z-index should be more than debugger

It was decided to have the debugger overlap the property pane, so debugger has a higher z index.

> * Empty results text doesn’t show for query results?

The shortcut to open debugger is only when in the widget editor. The message is different for api and query pane.

2021-04-22 09:05 UTC, akash-codemonk commented on app/client/src/components/editorComponents/Debugger/helpers.tsx
> +  const maxPage = Math.ceil(data.length / itemsPerPage);
You mean for the usePagination hook? It doesn't return any ui elements.

2021-04-22 09:06 UTC, akash-codemonk commented on app/client/src/components/editorComponents/Debugger/DebuggerMessage.tsx
> +      to open the issue in debugger
Not sure how do we do this here. Should we pass the button component as an argument here to the message function?

2021-04-22 09:11 UTC, akash-codemonk commented on app/client/src/pages/Editor/QueryEditor/Form.tsx
> +const TabbedViewContainer = styled.div`
This a wrapper div for the query response section here which whose content is different so they have different styles in api and query pane. So I guess it would be better to keep it separate.

2021-04-22 09:14 UTC, akash-codemonk commented on app/client/src/entities/AppsmithConsole/index.ts
> +  logType?: LOG_TYPE;
I think it is not required to be mandatory because currently they are only used for formatting the log content based on the event for a few of them. It would be another thing to specify among others.

2021-04-22 09:15 UTC, akash-codemonk commented
/ok-to-test sha=3ce10f0

2021-04-22 19:32 UTC, rishabhsaxena approved these changes
Few minor comments.

Also the advice to always use `useCallback` & `useMemo` wasn't correct. We should only use `useCallback` when we need to check referential equality, since a new var is created anyway. And `useMemo` should be used only when doing expensive calculations, should be measured.

Ref: https://kentcdodds.com/blog/usememo-and-usecallback/

2021-04-22 19:32 UTC, rishabhsaxena commented on app/client/src/components/editorComponents/Debugger/DebuggerMessage.tsx
> +      to open the issue in debugger
I don't see much harm in that, but to be safe we can split it into two strings

2021-04-22 19:32 UTC, rishabhsaxena commented on app/client/src/components/editorComponents/Debugger/EntityLink.tsx
> +};
NIT: we could also write it as:
```
const entityTypeLinkMap = {
    [ENTITY_TYPE.WIDGET]: WidgetLink,
    [ENTITY_TYPE.ACTION]: ActionLink,
    [ENTITY_TYPE.DATASOURCE]: DatasourceLink,
  };

const EntityLink = (props: EntityLinkProps) => {
  const Component = entityTypeLinkMap[props.type]
  return <Component {...props} />;
};
```
Ref: https://reactjs.org/docs/jsx-in-depth.html#choosing-the-type-at-runtime

2021-04-22 19:32 UTC, rishabhsaxena commented on app/client/src/components/editorComponents/Debugger/helpers.tsx
> +  const maxPage = Math.ceil(data.length / itemsPerPage);
Actually meant for the calculating the max page, but I think we can skip it. Doesn't seem like an expensive calculation.

2021-04-23 08:28 UTC, akash-codemonk commented
/ok-to-test sha=2c8ead2

2021-04-23 11:24 UTC, rishabhsaxena commented on app/client/src/pages/Editor/GlobalHotKeys.tsx
> +            this.props.openDebugger();
We could make this a toggle, so it closes the debugger when open

2021-04-23 11:31 UTC, rishabhsaxena submitted a review, later dismissed
- We could make the hotkey a toggle
- For resizing we could make the entire row as a target for resizing, so we don't have move the cursor to the edge, chrome console does it similarly

2021-04-23 11:47 UTC, akash-codemonk commented
> * For resizing we could make the entire row as a target for resizing, so we don't have move the cursor to the edge, chrome console does it similarly

This will need more work. We could consider this has an enhancement :sweat_smile:

2021-04-23 13:21 UTC, rishabhsaxena approved these changes

2021-04-23 13:50 UTC, merged

2021-04-23 13:55 UTC, hetunandu commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/ActionExecution/ExecutionParams_spec.js
> +      testdata.baseUrl,
@rishabhsaxena @akash-codemonk This change is no longer testing the functionality correctly. Please revert this change