Feature/query pane redesign tab
appsmithorg/appsmith pull request #3657
Opened 2021-03-22 04:56 UTC by ram-primathon

## Description
> add ads tab in query pane

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-03-22 05:09 UTC, hetunandu requested changes
Also create this for the response section of the query

2021-03-22 09:01 UTC, hetunandu requested changes

2021-03-23 03:13 UTC, ram-primathon commented on app/client/src/pages/Editor/QueryEditor/Form.tsx
> +const AddWidgetButton = styled.a`
done

2021-03-23 11:54 UTC, ram-primathon commented on app/client/src/pages/Editor/QueryEditor/Form.tsx
> +                      />
done

2021-03-23 11:54 UTC, ram-primathon commented on app/client/src/pages/Editor/QueryEditor/Form.tsx
> +                    <OutputTabWrapper>
done

2021-03-23 11:55 UTC, ram-primathon commented on app/client/src/pages/Editor/QueryEditor/Form.tsx
> +    border: none;
removed

2021-03-23 11:55 UTC, ram-primathon commented on app/client/src/pages/Editor/QueryEditor/Form.tsx
>  const OutputWrapper = styled.div``;
done

2021-03-24 08:54 UTC, hetunandu approved these changes

2021-03-24 08:55 UTC, merged