code folding in response and request
appsmithorg/appsmith pull request #3658
Opened 2021-03-22 06:48 UTC by ApekshaBhosale

## Description
Allow code folding in API response and request section

Fixes # (issue)
https://github.com/appsmithorg/appsmith/issues/2474

> Please delete options that are not relevant.
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce. 
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-03-22 07:01 UTC, hetunandu requested changes

2021-03-22 07:01 UTC, hetunandu commented on app/client/src/components/editorComponents/CodeEditor/index.tsx
> +        });
Manipulate the original options object itself instead of spreading this here

2021-03-22 07:01 UTC, hetunandu commented on app/client/src/components/editorComponents/CodeEditor/index.tsx
> +        });
Also a great candidate for a unit test

2021-03-22 07:01 UTC, hetunandu commented on app/client/src/components/editorComponents/CodeEditor/EditorConfig.ts
> +  folding: boolean;
Should be optional with false being the default

2021-03-22 07:07 UTC, ApekshaBhosale commented on app/client/src/components/editorComponents/CodeEditor/EditorConfig.ts
> +  folding: boolean;
Yes but I could not make this optional but I agree optional is better

2021-03-22 07:17 UTC, ApekshaBhosale commented on app/client/src/components/editorComponents/CodeEditor/index.tsx
> +        });
yes

2021-03-22 08:47 UTC, hetunandu commented on app/client/src/components/editorComponents/CodeEditor/EditorConfig.ts
> +  folding?: boolean | false;
Making it optional will work out. No value is considered falsy. If you want to set a default value, you need to do that in the `defaultProps` of this component

2021-03-23 11:29 UTC, hetunandu requested changes

2021-03-23 11:29 UTC, hetunandu commented on app/client/src/components/editorComponents/ReadOnlyEditor.tsx
> +import "codemirror/addon/fold/foldgutter.css";
We would need to move this to the code editor only, since we are allowing for folding in two places

2021-03-25 05:03 UTC, hetunandu approved these changes

2021-03-25 05:27 UTC, merged