Added index check to add content type in existing field
appsmithorg/appsmith pull request #3659
Opened 2021-03-22 06:50 UTC by ApekshaBhosale

## Description
Header gets added into extra field when API is converted into POST, PUT, DELETE, PATCH

Fixes # (https://github.com/appsmithorg/appsmith/issues/3169)
> 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-03-22 06:57 UTC, hetunandu requested changes

2021-03-22 06:57 UTC, hetunandu commented on app/client/src/sagas/ApiPaneSagas.ts
> +        }
extract and add a jest test for this functionality

2021-03-23 09:45 UTC, ApekshaBhosale commented on app/client/src/sagas/ApiPaneSagas.ts
> +        }
Yes

2021-03-23 10:00 UTC, hetunandu approved these changes

2021-03-23 13:08 UTC, hetunandu approved these changes

2021-03-26 09:59 UTC, mohanarpit approved these changes

2021-03-29 09:56 UTC, merged