Fix-date widget popup jump ondrag
appsmithorg/appsmith pull request #366
Opened 2020-08-20 07:24 UTC by vicky-primathon

2020-08-20 08:21 UTC, satbir121 commented on app/client/src/components/designSystems/blueprint/DatePickerComponent.tsx
> +                if (this.props.disableDrag) {
Why are we adding an if condition? Is it for preview mode?

2020-08-20 08:23 UTC, vicky-primathon commented on app/client/src/components/designSystems/blueprint/DatePickerComponent.tsx
> +                if (this.props.disableDrag) {
@satbir121  adding if since disableDrag function is not mandatory to be implemented for DatePickerComponent. Its required in widget only to disable dragging.

2020-08-20 08:26 UTC, satbir121 commented on app/client/src/components/designSystems/blueprint/DatePickerComponent.tsx
> +                if (this.props.disableDrag) {
Dropdown component should not know anything about drag. Dropdown component should allow configuring `onOpen` and `onClose`. And dropdown widget should disable the drag.

2020-08-26 05:11 UTC, hetunandu requested changes
Looks like we need a flag of "isDragging" that is passed down to all widgets to handle such behaviours

2020-12-17 07:09 UTC, hetunandu commented
Closing since it got fixed by #2168

2020-12-17 07:10 UTC, closed without merging