Bugfix/fetch error omnibar
appsmithorg/appsmith pull request #3665
Opened 2021-03-22 13:32 UTC by kaushik94

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.

## Description
> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation 
> and context. List any dependencies that are required for this change.

Fixes # (issue)
> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce. 
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-04-01 04:23 UTC, mohanarpit commented
@kaushik94 Can we prioritize merging this PR? There are quite a few errors that we are seeing in this flow. Merging this & promoting the fix to prod will do a world of good for our users.

2021-04-01 07:47 UTC, rishabhsaxena requested changes

2021-04-01 07:47 UTC, rishabhsaxena commented on app/client/src/components/editorComponents/GlobalSearch/utils.tsx
> +  if (maxRetries >= retries) {
Looks like a typo,  should be `maxRetries <= retries`?

2021-04-01 07:47 UTC, rishabhsaxena commented on app/client/src/components/editorComponents/GlobalSearch/utils.tsx
> +  (async () => {
We can do without an `iife` here

2021-04-01 07:47 UTC, rishabhsaxena commented on app/client/src/components/editorComponents/GlobalSearch/utils.tsx
> +      }
This seems a bit redundant, unless there's a failure to fetch the content due to network issues, we should always have data, otherwise retrying won't help much I suppose.

This should suffice?
```
setDefaultDocs(data);
updateIsFetching(false);
```

2021-04-01 07:47 UTC, rishabhsaxena commented on app/client/src/components/editorComponents/GlobalSearch/utils.tsx
> +      fetchDefaultDocs(
We should add some delay here before retrying.
Also should reset `isFetching` flag

```
updateIsFetching(false);
setTimeout(() => fetchDefaultDocs(), 500 * (retries));
```

2021-04-01 07:47 UTC, rishabhsaxena commented on app/client/src/components/editorComponents/GlobalSearch/utils.tsx
> +  // usestate
Not sure if this is still needed?

2021-04-01 08:09 UTC, rishabhsaxena commented on app/client/src/components/editorComponents/GlobalSearch/utils.tsx
> +      fetchDefaultDocs(
Hey @kaushik94 it just occurred to me, we should not reset `isFetching` flag here, instead we should reset when we're out of retry attempts, ie. within `if (maxRetries >= retries) {}`

2021-04-01 09:47 UTC, kaushik94 commented on app/client/src/components/editorComponents/GlobalSearch/utils.tsx
> +      fetchDefaultDocs(
I think you are right, we should set isFetching flag there since we are using setTimeout. When the function is run from the start again, it automatically sets isFetching to true.

2021-04-01 13:25 UTC, rishabhsaxena approved these changes

2021-04-01 16:16 UTC, rishabhsaxena requested changes

2021-04-01 16:16 UTC, rishabhsaxena commented on app/client/src/components/editorComponents/GlobalSearch/utils.test.ts
> +describe("globalsearch utils", () => {
Should mock `fetchRawGithubContentList` to return the docs results instead of making actual api calls.

2021-04-02 08:09 UTC, rishabhsaxena requested changes

2021-04-02 08:09 UTC, rishabhsaxena commented on app/client/src/components/editorComponents/GlobalSearch/utils.test.ts
> +        expect(documents.length).toEqual(4);
something looks off, since the mocked fn doesn't run the callback with the documents array, this should always fail?

2021-04-02 09:50 UTC, kaushik94 commented on app/client/src/components/editorComponents/GlobalSearch/utils.test.ts
> +        expect(documents.length).toEqual(4);
Yes, the tests pass which means the success callback was never called. Hmm.

2021-04-04 15:01 UTC, rishabhsaxena approved these changes

2021-04-05 07:56 UTC, rishabhsaxena approved these changes

2021-04-05 08:01 UTC, jsartisan approved these changes

2021-04-05 08:37 UTC, merged