feat: editable ide tabs
appsmithorg/appsmith pull request #36665
Opened 2024-10-02 20:49 UTC by alex-golovanov

## Description
Adds editable tab behavior for queries and JS objects.

Fixes #32440

/ok-to-test tags="@tag.All"

### :mag: Cypress test results

> [!CAUTION]  
> If you modify the content in this section, you are likely to disrupt the CI result for your PR.

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [ ] No

2024-10-02 20:54 UTC, alex-golovanov commented
/build-deploy-preview skip-tests=true

2024-10-07 08:12 UTC, sagar-qa007 requested changes

2024-10-07 08:12 UTC, sagar-qa007 commented on app/client/src/IDE/Components/FileTab/FileTab.tsx
> +  const attemptToSave = () => {
Did we considering adding unit test cases for this PR?

2024-10-07 09:48 UTC, alex-golovanov commented on app/client/src/IDE/Components/FileTab/FileTab.tsx
> +  const attemptToSave = () => {
Yes, there will be unit tests for this component.

2024-10-08 13:20 UTC, ankitakinger commented
/build-deploy-preview skip-tests=true

2024-10-08 16:44 UTC, KelvinOm submitted a review, later dismissed

2024-10-09 05:26 UTC, hetunandu submitted a review, later dismissed

2024-10-09 08:26 UTC, ankitakinger commented on app/client/src/selectors/ui.tsx
> +export const getJsObjectNameSavingStatuses = (state: AppState) =>
Just out of curiosity, why is the name ending in plural "statuses"? Shouldn't it be just "status"?

2024-10-09 08:51 UTC, alex-golovanov commented on app/client/src/selectors/ui.tsx
> +export const getJsObjectNameSavingStatuses = (state: AppState) =>
Well, there are plural statuses. If this is about plural form of the word `status`, then I feel that in this case explicit `statuses` is more fitting/descriptive and conveys the purpose of the variable without further need to investigate whether it's single or plural. Would you agree?

2024-10-09 08:56 UTC, ankitakinger commented on app/client/src/selectors/ui.tsx
> +export const getJsObjectNameSavingStatuses = (state: AppState) =>
Alright. Makes sense. I just checked the code to understand why this state is plural.

2024-10-09 09:47 UTC, ankitakinger submitted a review, later dismissed

2024-10-10 05:29 UTC, albinAppsmith approved these changes

2024-10-10 05:33 UTC, albinAppsmith commented
@alex-golovanov @momcilo-appsmith check this behaviour. Maybe we should cancel name edit if field is not valid and save it if field is valid.

https://github.com/user-attachments/assets/e37279d7-9f1f-4bf1-a22f-dda67e1b9502

2024-10-11 12:26 UTC, ankitakinger commented
/build-deploy-preview skip-tests=true

2024-10-11 12:57 UTC, hetunandu approved these changes

2024-10-11 18:03 UTC, albinAppsmith approved these changes

2024-10-13 17:38 UTC, ankitakinger approved these changes

2024-10-14 07:55 UTC, sagar-qa007 approved these changes

2024-10-14 08:05 UTC, merged