feat: Updated GraphQL form UI
appsmithorg/appsmith pull request #36728
Opened 2024-10-07 18:10 UTC by albinAppsmith

## Description

This PR has following new features and fixes
1. Feat: Update GraphQL to use form control dynamic text field instead of custom implementation.
2. Feat: Added full width support for section component in action form.
3. Fix: Rest API headers not scrollable if there are more number of items.

Fixes #35494
Fixes #36410
Fixes #36499

## Automation

/ok-to-test tags="@tag.All"

### :mag: Cypress test results

> [!CAUTION]  
> If you modify the content in this section, you are likely to disrupt the CI result for your PR.

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [x] No

2024-10-08 03:41 UTC, hetunandu requested changes

2024-10-08 03:41 UTC, hetunandu commented on app/client/src/pages/Editor/APIEditor/Editor.tsx
> +  height: `calc(100% - ${EDITOR_TABS_HEIGHT})`,
<img width="1227" alt="Screenshot 2024-10-08 at 9 10 14 AM" src="https://github.com/user-attachments/assets/1f2991cd-7f5a-41eb-a669-5eb04985567b">

This is from modules

2024-10-09 05:30 UTC, ashit-rath commented on app/client/src/pages/Editor/ActionForm/Section/index.tsx
> +      data-fullwidth={isFullWidth.toString()}
Any reason for not using classes to control css states?

2024-10-09 06:01 UTC, albinAppsmith commented on app/client/src/pages/Editor/ActionForm/Section/index.tsx
> +      data-fullwidth={isFullWidth.toString()}
Good point... This was a practise we used in ADS as well I see in WDS. @KelvinOm Do you see any specific reason we should stick to this? As I can see, class is better performant than data attributes.

2024-10-09 07:30 UTC, albinAppsmith commented
/build-deploy-preview skip-test=true

2024-10-09 10:01 UTC, hetunandu approved these changes

2024-10-10 09:46 UTC, merged