Fix spacing of fields in org settings: fixes (#3612)
appsmithorg/appsmith pull request #3681
Opened 2021-03-23 19:25 UTC by kaushik94

## Description
Fixes the misalignment of fields in organisation settings.

Fixes #3612 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Go to Org settings and check that the css for fields has "display: flex"

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-03-25 06:04 UTC, rishabhsaxena submitted a review, later dismissed
@kaushik94 Minor change: though the spacing looks consistent, we have increased the spacings from what they were before, think we should keep the original spacing here

2021-03-29 06:11 UTC, kaushik94 commented on app/client/src/pages/organization/General.tsx
> +  margin-right: -3em;
@hetunandu please check if this line is ok.

2021-03-29 06:16 UTC, hetunandu commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/OrganisationTests/OrgSettings_validation_spec.js
> +    });
Let's avoid doing a cypress test for style checks. Instead, do a jest test

2021-03-29 06:16 UTC, hetunandu commented on app/client/src/pages/organization/General.tsx
> +  margin-right: -3em;
Instead of minus margins, we should see which child component adds some margin/padding you are trying to negate and then handle that there. As a rule, I like to make each component's padding and margin be zero, and the container rendering the component should instead place it where it wants to. That ensures some separation of concerns in styling components.

2021-04-07 06:32 UTC, hetunandu commented on app/client/src/components/ads/FilePicker.tsx
> +        return;
```suggestion
      if (!files) {
        return;
      }
      handleFileUpload(files);
```

2021-04-07 06:32 UTC, hetunandu commented on app/client/src/components/ads/FilePicker.tsx
> +      return;
```suggestion
    if (!file) {
      return
    }
    fileSize = Math.floor(file.size / 1024);
    setFileInfo({ name: file.name, size: fileSize });
```

2021-04-07 06:33 UTC, hetunandu requested changes
Minor refacor suggestions

2021-04-07 07:23 UTC, rishabhsaxena reviewed
Couple of nitpicks

2021-04-07 07:23 UTC, rishabhsaxena commented on app/client/src/pages/Applications/__tests__/OrganizationSettingsForm.test.tsx
> +    const orgNameField = await getByText("Organization Name");
NIT: think `getByText` is a sync method, `findBy` queries are async

2021-04-07 07:23 UTC, rishabhsaxena commented on app/client/src/pages/Applications/__tests__/OrganizationSettingsForm.test.tsx
> +describe("Applications", () => {
NIT: Should update the desc to `Application Settings`?

2021-04-07 08:24 UTC, rishabhsaxena commented
IMHO not sure if this test helps us a lot. What do you guys think about jest snapshots with jest-styled-components 
as a practise. We could merge this and take it separately.

 @kaushik94 @hetunandu

2021-04-07 08:25 UTC, hetunandu commented
> IMHO not sure if this test helps us a lot. What do you guys think about jest snapshots with jest-styled-components
> as a practise. We could merge this and take it separately.
> 
> @kaushik94 @hetunandu

Makes sense. Lets start snapshot testing

2021-04-07 10:48 UTC, kaushik94 commented
@hetunandu @rishabhsaxena Snapshoting sounds good to me.

2021-04-07 11:02 UTC, hetunandu submitted a review, later dismissed

2021-04-08 04:46 UTC, hetunandu approved these changes

2021-04-08 05:49 UTC, kaushik94 commented
@hetunandu @rishabhsaxena merging this. Thanks.

2021-04-08 05:50 UTC, merged