chore: Split library side pane for adding package control section
appsmithorg/appsmith pull request #36926
Opened 2024-10-17 06:33 UTC by ashit-rath

## Description
Purpose of this PR is to split the Libraries section to extend it in EE and introduced a tab layout that has both js libraries and packages
Changes:
1. Increased width of Libraries pane to 384px
2. Added a route `/package` which opens the same as library 
3. Extracted the JSLibraries section to be reused as a tab panel body in EE
4. Created `SidePaneWrapper` common component to be reused in EE
5. Minor linting refactors.

[Figma](https://www.figma.com/design/Z0QsSdGOydURn6WIMQ3rHM/Appsmith-Reusability?node-id=6816-319511&node-type=frame&t=x0DzN9HIxjefe3J1-0)

PR for https://github.com/appsmithorg/appsmith-ee/pull/5362
## Automation

/ok-to-test tags=""

### :mag: Cypress test results

> [!CAUTION]  
> If you modify the content in this section, you are likely to disrupt the CI result for your PR.

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [ ] No

2024-10-17 06:53 UTC, ashit-rath commented
/build-deploy-preview skip-tests=true

2024-10-21 09:21 UTC, sagar-qa007 requested changes

2024-10-21 09:21 UTC, sagar-qa007 commented on app/client/src/IDE/Components/SidePaneWrapper.tsx
> +function SidePaneWrapper({ children, padded = false }: SidePaneContainerProps) {
Do we need add/update any e2e or unit test case here?

2024-10-21 09:40 UTC, ashit-rath commented on app/client/src/IDE/Components/SidePaneWrapper.tsx
> +function SidePaneWrapper({ children, padded = false }: SidePaneContainerProps) {
I don't believe that is required here. We do not check for css

2024-10-22 04:44 UTC, ashit-rath commented on app/client/src/ce/pages/Editor/IDE/Header/useLibraryHeaderTitle.ts
> +import { createMessage, HEADER_TITLES } from "ee/constants/messages";
This is a known pattern being followed here

2024-10-22 04:47 UTC, subrata71 approved these changes

2024-10-22 05:17 UTC, hetunandu approved these changes

2024-10-22 05:18 UTC, merged