showing save datasource option all time
appsmithorg/appsmith pull request #3695
Opened 2021-03-25 06:07 UTC by ApekshaBhosale

## Description
Exposing 'save as datasource' with empty path but in disable state till value is entered

Fixes # (issue)
> https://github.com/appsmithorg/appsmith/issues/3193

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-03-25 06:13 UTC, hetunandu requested changes

2021-03-25 06:13 UTC, hetunandu commented on app/client/src/components/editorComponents/form/fields/EmbeddedDatasourcePathField.tsx
> +          <StoreAsDatasource value={displayValue} />
Let's pass the disabled state from here only instead of passing the value

2021-03-25 08:22 UTC, ApekshaBhosale commented on app/client/src/components/editorComponents/form/fields/EmbeddedDatasourcePathField.tsx
> +          <StoreAsDatasource value={displayValue} />
okay

2021-03-25 08:24 UTC, hetunandu requested changes

2021-03-25 08:24 UTC, hetunandu commented on app/client/src/components/editorComponents/StoreAsDatasource.tsx
> +      className={`t--store-as-datasource ${props.enable ? "" : "disabled"}`}
Instead of className, you should just pass the prop as a prop and apply your styles based on that prop

2021-03-25 09:07 UTC, hetunandu approved these changes

2021-03-31 09:12 UTC, mohanarpit approved these changes

2021-03-31 09:12 UTC, mohanarpit commented
@ApekshaBhosale Is this PR good to merge? If yes, let's merge it in once the tests pass.

2021-03-31 10:39 UTC, merged