Added TLS support for Redis Datasource
appsmithorg/appsmith pull request #37106
Opened 2024-10-25 12:45 UTC by AnnaHariprasad5123

**Fixes**  26723 

**What's in this PR :**
- Added TlsConfiguration file for holding TLS properties.
- Added TlsConfiguration field to the DatasourceConfiguration file.
- Added Some constants in RedisErrorMessages file to show missing validation messages.
- Added SSL Redis URL to RedisTlsUtils file.
- Added some test cases in RedisPluginTest.

**For more clarity :** [Video about Redis connection with TLS enabled](https://drive.google.com/file/d/179iDhDSTctOW8AIDz0hsn5d_aYeFJA2Y/view?usp=sharing)

**Screenshots :**

**Before :** Unable to connect Redis via TLS
![image](/uploads/3d036223f4203f3021aadc875e1874d3/image.png)

**After :** Able to connect Redis via TLS with or without Client Authentication redis setup
![image](https://github.com/user-attachments/assets/c6478a06-c5db-404b-bc89-9287c4d81634)
![image](/uploads/c27b7d5d57d0afa57f3c134df8a50446/image.png)
![image](/uploads/46ecc76cb4a52365c790e53931612cbc/image.png)
![image](/uploads/c74b39da77db34811995a0910c76faf6/image.png)

**Added Test cases :**
- itShouldValidateDatasourceWithTlsEnabledAndMissingCACertificate
- itShouldValidateDatasourceWithTlsEnabledAndMissingClientCertificate
- itShouldValidateDatasourceWithTlsEnabledAndMissingKey
- itShouldPassValidationWithTlsEnabledAndValidCertificates
![image](https://github.com/user-attachments/assets/51adf969-1aaf-40ce-ab09-204196278ba3)

2024-10-28 10:31 UTC, NilanshBansal commented
Need to prioritise review for this PR. 
cc: @appsmithorg/query-js-pod @carinanfonseca

2024-11-04 07:49 UTC, AnnaHariprasad5123 commented
Hi Appsmith Team,

Could someone please review this PR when you have a chance? Your feedback would be greatly appreciated.

Thank you!

2024-11-05 08:34 UTC, NilanshBansal commented on app/server/appsmith-plugins/redisPlugin/src/main/java/com/external/utils/RedisTLSManager.java
> +    }
cc: @AnnaHariprasad5123 please check this suggestion

2024-11-05 08:36 UTC, NilanshBansal commented on app/server/appsmith-plugins/redisPlugin/src/main/java/com/external/utils/RedisTLSManager.java
> +                requiresClientAuth ? keyManagerFactory.getKeyManagers() : null, trustManagers, new SecureRandom());
cc: @AnnaHariprasad5123

2024-11-05 08:38 UTC, NilanshBansal commented on app/server/appsmith-plugins/redisPlugin/src/main/java/com/external/utils/RedisURIUtils.java
> +        }
cc: @AnnaHariprasad5123

2024-11-06 06:26 UTC, AnnaHariprasad5123 commented on app/server/appsmith-plugins/redisPlugin/src/main/resources/form.json
> +            }
It is not working.

2024-11-06 06:27 UTC, AnnaHariprasad5123 commented on app/server/appsmith-plugins/redisPlugin/src/main/java/com/external/utils/RedisTLSManager.java
> +        }
It is user preference to verify the CA certificate or not.

2024-11-06 06:28 UTC, AnnaHariprasad5123 commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/TlsConfiguration.java
> +    Boolean verifyTlsCertificate;
I will make some changes to avoid Null pointer exception. Instead of adding default values.

2024-11-06 06:31 UTC, AnnaHariprasad5123 commented
Hi @NilanshBansal. I've implemented most of the changes suggested by Code Rabbit and marked them with a thumbs-up. For some changes, I’ve added comments, and I’ll add the rest shortly. Meanwhile, could you please check the functionality of Redis TLS

2024-11-06 06:37 UTC, NilanshBansal commented
@carinanfonseca can you please check [this](https://ce-37106.dp.appsmith.com) DP from the design perspective?
You can go to Datasources page, click on Redis datasource -> Enable TLS to view the changes. 
You can add dummy credentials to proceed for design testing.

2024-11-06 09:49 UTC, carinanfonseca commented
Hi @AnnaHariprasad5123, thanks for your contribution. Can you check and ensure the spacing on the datasources page matches the attached screenshot? When I checked it after sign-up and on the regular datasources form, the spacing seemed off, with extra margins. Thank you! <img width="1210" alt="Screenshot 2024-11-06 at 09 40 26" src="https://github.com/user-attachments/assets/5200093c-2a1f-4354-83fd-b8a89229a82d">

2024-11-08 10:00 UTC, NilanshBansal commented on app/server/appsmith-plugins/redisPlugin/src/main/java/com/external/utils/RedisTLSManager.java
> +                    new String(tlsConfiguration.getClientKeyFile().getDecodedContent(), StandardCharsets.UTF_8);
@AnnaHariprasad5123 can you please add error handling here for exceptions that can come up from generateCertificate() etc. Adding a try-catch block should be good for handling exceptions for `CertificateException` and `IOException` type

2024-11-08 10:00 UTC, NilanshBansal commented on app/server/appsmith-plugins/redisPlugin/src/main/java/com/external/utils/RedisTLSManager.java
> +            X509Certificate caCert = (X509Certificate)
Similarly please add a try-catch exception handling here

2024-11-11 07:18 UTC, AnnaHariprasad5123 commented
Hi @carinanfonseca, it seems that every field in each datasource has a top margin of 16px. Everything appears the same to me.
**Redis datasource when SignUp :**
![image](https://github.com/user-attachments/assets/960c5aa1-8b42-48ef-a5ab-70fa84da688a)
**Redis datasource when SignIn :**
![image](https://github.com/user-attachments/assets/f3b9350b-3867-4387-8331-89d34c1c81fd)
**Postgres datasource when SignUp:**
![image](https://github.com/user-attachments/assets/865bf345-96a3-4499-8dfc-3b3282b40cf9)
**Postgres datasource when SignIn :**
![image](https://github.com/user-attachments/assets/cda4a889-5077-411c-8518-f56729f47746)

2024-11-13 10:26 UTC, carinanfonseca commented
All good, @AnnaHariprasad5123! Thank you

2024-11-18 06:54 UTC, NilanshBansal commented on app/server/appsmith-plugins/redisPlugin/src/main/java/com/external/plugins/RedisPlugin.java
> +                        }
@AnnaHariprasad5123 can you please check this.

2024-11-18 07:01 UTC, NilanshBansal commented on app/server/appsmith-plugins/redisPlugin/src/main/java/com/external/utils/RedisTLSManager.java
> +                PrivateKey privateKey = loadPrivateKey(clientKey);
@AnnaHariprasad5123 please check this

2024-11-18 07:13 UTC, NilanshBansal commented on app/server/appsmith-plugins/redisPlugin/src/main/java/com/external/utils/RedisTLSManager.java
> +    }
@AnnaHariprasad5123 please add this suggestion. This will check for EC algo keys as well and also clear the sensitive data from the memory.

2024-11-18 07:23 UTC, NilanshBansal requested changes
Added comments

2024-11-18 07:30 UTC, NilanshBansal commented on app/server/appsmith-plugins/redisPlugin/src/main/java/com/external/utils/RedisTLSManager.java
> +                requiresClientAuth ? keyManagerFactory.getKeyManagers() : null, trustManagers, new SecureRandom());
Please ignore this @AnnaHariprasad5123

2024-11-18 07:48 UTC, NilanshBansal commented
Tested the above changes on DP. Other than the comments above rest LGTM.

2024-11-18 08:50 UTC, AnnaHariprasad5123 commented on app/server/appsmith-plugins/redisPlugin/src/test/java/com/external/plugins/RedisPluginTest.java
> +
```
@Test
    public void itShouldTestDatasourceWithTlsEnabledAndValidCertificates() {
        DatasourceConfiguration datasourceConfiguration = createDatasourceConfigurationWithTLSEnabled();
        Mono<DatasourceTestResult> datasourceTestResultMono = pluginExecutor.testDatasource(datasourceConfiguration);

        StepVerifier.create(datasourceTestResultMono)
            .assertNext(datasourceTestResult -> {
                assertNotNull(datasourceTestResult);
            })
            .verifyComplete();
    }
    ```
    If this is ok, I will push this.

2024-11-18 08:58 UTC, NilanshBansal commented on app/server/appsmith-plugins/redisPlugin/src/test/java/com/external/plugins/RedisPluginTest.java
> +
Yes @AnnaHariprasad5123 please push the changes. I will review.

2024-11-18 10:23 UTC, AnnaHariprasad5123 commented
Hi @NilanshBansal , Could you review the changes

2024-11-18 10:26 UTC, NilanshBansal commented on app/server/appsmith-plugins/redisPlugin/src/main/java/com/external/utils/RedisTLSManager.java
> +                } finally {
@AnnaHariprasad5123 should we add a catch block also here which catches the CertificateException?

2024-11-18 10:28 UTC, NilanshBansal commented on app/server/appsmith-plugins/redisPlugin/src/main/java/com/external/utils/RedisTLSManager.java
> +            SecureRandom secureRandom = SecureRandom.getInstance("SHA1PRNG");
instead of this I think you can directly use new SecureRandom(). The earlier code was correct. 
Please check my comment [here](https://github.com/appsmithorg/appsmith/pull/37106#discussion_r1846008484)

2024-11-18 10:39 UTC, NilanshBansal commented on app/server/appsmith-plugins/redisPlugin/src/test/java/com/external/plugins/RedisPluginTest.java
> +    }
Not required as we are using mock certificates

2024-11-18 11:06 UTC, AnnaHariprasad5123 commented
Hi @NilanshBansal, Could you check now.

2024-11-18 11:58 UTC, NilanshBansal commented
/build-deploy-preview skip-tests=true recreate=true

2024-11-18 12:01 UTC, NilanshBansal approved these changes

2024-11-18 18:11 UTC, NilanshBansal commented on app/server/appsmith-plugins/redisPlugin/src/main/java/com/external/utils/RedisURIUtils.java
> +        if (datasourceConfiguration.getTlsConfiguration() != null
Nit: @AnnaHariprasad5123 can you please add a check for datasourceConfiguration to be not null. 
if (datasourceConfiguration != null && datasourceConfiguration.getTlsConfiguration() != null
                && datasourceConfiguration.getTlsConfiguration().getTlsEnabled())

2024-11-18 18:15 UTC, NilanshBansal commented on app/server/appsmith-plugins/redisPlugin/src/test/java/com/external/plugins/RedisPluginTest.java
> +    private TlsConfiguration addTLSConfiguration(DatasourceConfiguration datasourceConfiguration) {
@AnnaHariprasad5123 parameter datasourceConfiguration is not getting consumed for the function addTLSConfiguration(), can you check and remove if it is not required.

2024-11-19 02:43 UTC, NilanshBansal submitted a review, later dismissed

2024-11-19 03:08 UTC, NilanshBansal approved these changes

2024-11-19 12:02 UTC, AnnaHariprasad5123 commented
![image](https://github.com/user-attachments/assets/c52aa7ea-85ee-4302-9f68-e311c1a0e456)

2024-11-19 12:04 UTC, NilanshBansal commented
/build-deploy-preview skip-tests=true

2024-11-19 12:17 UTC, NilanshBansal commented
@AnnaHariprasad5123 I am getting this error on using my TLS configuration with Redis. The same configuration was working earlier when I uploaded the CA certificate file.
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/63e129f7-0755-4d5e-8a1b-029458bee93b">

2024-11-19 23:24 UTC, AnnaHariprasad5123 commented
Hi @NilanshBansal, 

Find the videos below
[In Local Setup](https://drive.google.com/file/d/1AVYovZVbKVs6iQqxxHv4Df7OPlZFYGh9/view?usp=sharing)
[In Deployed Setup](https://drive.google.com/file/d/1Jh9Lf962xMceiWg9GnSYoTR6FS0U1uQv/view?usp=sharing)

2024-12-08 16:38 UTC, closed without merging