chore: Removed manipulation for custom traceparent header
appsmithorg/appsmith pull request #37121
Opened 2024-10-29 06:20 UTC by nidhi-nair

## Description
All Appsmith systems should always rely on a single traceparent header to propagate traces, removing incorrect manipulation to bring back consistency.

## Automation

/ok-to-test tags=""

### :mag: Cypress test results

> [!CAUTION]  
> If you modify the content in this section, you are likely to disrupt the CI result for your PR.

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [ ] No

2024-10-29 06:20 UTC, nidhi-nair commented
/build-deploy-preview skip-tests=true

2024-10-29 07:09 UTC, nidhi-nair commented
/build-deploy-preview skip-tests=true

2024-10-29 08:49 UTC, nidhi-nair commented
/build-deploy-preview skip-tests=true

2024-10-29 10:38 UTC, nidhi-nair commented
/build-deploy-preview skip-tests=true

2024-10-30 03:57 UTC, nidhi-nair commented
/build-deploy-preview skip-tests=true

2024-10-30 05:07 UTC, ApekshaBhosale requested changes

2024-10-30 05:07 UTC, ApekshaBhosale commented on app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/TracingConfig.java
> -    SpanExportingPredicate onlyAppsmithSpans() {
@nidhi-nair now this has been removed. we will allow all spans? won't there be too many and cause clutter?

2024-10-30 05:27 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/TracingConfig.java
> -    SpanExportingPredicate onlyAppsmithSpans() {
I'd like to see if this is still true post spring upgrade since the DP is not showing as many spans anymore. We can revisit this if we see a spike perhaps? This allows us to fill the gaps in the trace lineage.

2024-10-30 05:56 UTC, ApekshaBhosale commented on app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/TracingConfig.java
> -    SpanExportingPredicate onlyAppsmithSpans() {
yes makes sense

2024-10-30 05:57 UTC, ApekshaBhosale approved these changes

2024-10-30 05:57 UTC, merged