removing new lines while showing url path field
appsmithorg/appsmith pull request #3717
Opened 2021-03-26 10:51 UTC by ApekshaBhosale

## Description
if url path contains '\n', field is not able to do line wrapping properly

Fixes # (issue)
>https://github.com/appsmithorg/appsmith/issues/1526
>https://github.com/appsmithorg/appsmith/issues/3621

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-03-26 11:01 UTC, hetunandu requested changes
Needs refactoring

2021-03-26 11:01 UTC, hetunandu commented on app/client/src/components/editorComponents/CodeEditor/index.tsx
> +        }
abstract this in a common function

2021-03-26 11:01 UTC, hetunandu commented on app/client/src/components/editorComponents/CodeEditor/index.tsx
> -      // Update the dynamic bindings for autocomplete
Revert deleting this comment

2021-03-26 11:02 UTC, hetunandu commented
> No changes to code coverage between the base branch and the head branch

Consider adding a jest test for this functionality. Mock the underlying code mirror or input props and assert if the right functions are called

2021-03-26 11:17 UTC, ApekshaBhosale commented on app/client/src/components/editorComponents/CodeEditor/index.tsx
> +        }
for this I have changed a condition a little bit so abstracting won't make much sense.

2021-03-26 11:26 UTC, ApekshaBhosale commented
> > No changes to code coverage between the base branch and the head branch
> 
> Consider adding a jest test for this functionality. Mock the underlying code mirror or input props and assert if the right functions are called

@hetunandu which functionality you are talking about? the whole thing or just particular function I created?

2021-03-26 11:31 UTC, hetunandu commented
> > > No changes to code coverage between the base branch and the head branch
> > 
> > 
> > Consider adding a jest test for this functionality. Mock the underlying code mirror or input props and assert if the right functions are called
> 
> @hetunandu which functionality you are talking about? the whole thing or just particular function I created?

Anything that can get us started with testing this component

2021-03-30 05:01 UTC, hetunandu commented on app/client/src/components/editorComponents/CodeEditor/index.tsx
> +          console.log(inputValue);
remove console.log
```suggestion

```

2021-03-30 05:02 UTC, hetunandu submitted a review, later dismissed

2021-03-31 07:45 UTC, hetunandu approved these changes

2021-03-31 12:28 UTC, merged