chore: add datepicker component
appsmithorg/appsmith pull request #37563
Opened 2024-11-19 11:38 UTC by jsartisan

2024-11-21 12:37 UTC, KelvinOm requested changes

2024-11-21 12:37 UTC, KelvinOm commented on app/client/packages/design-system/widgets/src/components/Calendar/src/CalendarHeading.tsx
> +const _CalendarHeading = forwardRef(CalendarHeading);
(nit) You can simplify the export a bit here if you do the same as in our other files.

2024-11-21 12:37 UTC, KelvinOm commented on app/client/packages/design-system/widgets/src/components/Calendar/src/styles.module.css
> +  border-color: var(--color-bd-accent);
It is unclear where the focus is now if the focus is on the selected date.

![Снимок экрана 2024-11-21 в 15 31 14](https://github.com/user-attachments/assets/d4c81bea-969f-4bbf-8317-93353e8b547b)

2024-11-21 12:37 UTC, KelvinOm commented on app/client/packages/design-system/widgets/src/components/Datepicker/stories/Datepicker.stories.tsx
> +export const Disabled: Story = {
Except for the main story, the datapicker does not work anywhere else.

2024-11-21 12:37 UTC, KelvinOm commented on app/client/packages/design-system/widgets/src/components/Datepicker/stories/Datepicker.stories.tsx
> +    isLoading: true,
I think we shouldn't be able to change the date during the loading.
![Снимок экрана 2024-11-21 в 15 36 57](https://github.com/user-attachments/assets/d476408d-036b-4dbe-9620-9c0642333954)

2024-11-22 05:01 UTC, jsartisan commented on app/client/packages/design-system/widgets/src/components/Calendar/src/Calendar.tsx
> +      <HeadlessCalendarGrid>
It's the storybook styles that we have applied on `td` and `tr`. :/

2024-11-22 05:02 UTC, jsartisan commented on app/client/packages/design-system/widgets/src/components/Datepicker/stories/Datepicker.stories.tsx
> +export const Disabled: Story = {
it's the same issue of storybook that we saw in select PR. I'll check again if there is a workaround for this.

2024-11-22 05:56 UTC, jsartisan commented on app/client/packages/design-system/widgets/src/components/Calendar/src/CalendarHeading.tsx
> +const _CalendarHeading = forwardRef(CalendarHeading);
I don't ge it. Did you mean to use like:

```jsx
const CalendarHeading = forwardRef((
  props: TextProps,
  ref: ForwardedRef<HTMLHeadingElement>,
) => {
  [props, ref] = useContextProps(props, ref, HeadingContext);
  const { children, ...domProps } = props;

  return (
    <Text {...domProps} color="neutral" ref={ref}>
      {children}
    </Text>
  );
});

export { CalendarHeading };
```

2024-11-22 06:42 UTC, jsartisan commented on app/client/packages/design-system/widgets/src/components/Datepicker/stories/Datepicker.stories.tsx
> +    isLoading: true,
so should we disable when loading is true? User can do it anyway like
```<Datepicke isDisabled={isDisabled || isLoading} />

2024-11-22 06:42 UTC, jsartisan commented on app/client/packages/design-system/widgets/src/components/Datepicker/stories/Datepicker.stories.tsx
> +export const Disabled: Story = {
Fixed this.

2024-11-22 06:42 UTC, jsartisan commented on app/client/packages/design-system/widgets/src/components/Calendar/src/styles.module.css
> +  border-color: var(--color-bd-accent);
Fixed

2024-11-22 08:42 UTC, KelvinOm commented on app/client/packages/design-system/widgets/src/components/Calendar/src/Calendar.tsx
> +      <HeadlessCalendarGrid>
Can we override it [here](https://github.com/appsmithorg/appsmith/blob/release/app/client/packages/storybook/.storybook/preview-head.html)?

2024-11-22 08:46 UTC, KelvinOm commented on app/client/packages/design-system/widgets/src/components/Datepicker/stories/Datepicker.stories.tsx
> +    isLoading: true,
I looked at how the textfield works and we can also change the value there during loading. Leave it as it is now.

2024-11-22 09:28 UTC, KelvinOm approved these changes

2024-11-22 10:20 UTC, merged