chore: Update size of sidebar + remove using sheet
appsmithorg/appsmith pull request #37638
Opened 2024-11-21 11:50 UTC by jsartisan

2024-11-21 12:04 UTC, ichik requested changes
1. With the default direction of opening the icons should reflect it, otherwise, they're pointing in the opposite direction now (the correct one for `side=end`)
2. Default position for sidebar expand button should be end/right

2024-11-21 12:49 UTC, KelvinOm approved these changes

2024-11-21 12:57 UTC, ichik approved these changes

2024-11-22 10:39 UTC, jsartisan commented
@KelvinOm @znamenskii-ilia I'll merge this on monday. I am expecting type issue on ee repo because of this PR. So will need to handle that as well once we merge this.

2024-11-25 09:37 UTC, merged