feat: add postgres data backup to appsmith ctl
appsmithorg/appsmith pull request #37837
Opened 2024-11-29 06:37 UTC by AnaghHegde

## Description

## Automation

/ok-to-test tags=""

### :mag: Cypress test results

> [!CAUTION]  
> If you modify the content in this section, you are likely to disrupt the CI result for your PR.

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [ ] No

2024-11-29 12:32 UTC, abhvsn commented on app/client/packages/rts/src/ctl/index.ts
> +} else if (["export_db_pg"].includes(command)) {
Does it make sense to make the command more explicit e.g `export-mongo-to-pg`?

2024-11-29 12:37 UTC, abhvsn requested changes
I'm seeing a lot of modifications in move-to-postgres.mjs can we please keep those?

2024-12-10 07:45 UTC, abhvsn reviewed
@AnaghHegde have we tested the https://github.com/appsmithorg/appsmith/blob/release/scripts/regen-baseline.sh with these changes?

2024-12-11 12:38 UTC, AnaghHegde commented
@abhvsn Why do you think baseline regen script will be affected? We are adding the command for backup of mongo data to stacks directory.

2024-12-19 05:38 UTC, abhvsn commented
@AnaghHegde that's because you have modified the move-to-postgres.mjs file to call `writeDataFromMongoToJsonlFiles` method to perform the migration which was not the case earlier.

2025-01-05 16:36 UTC, closed without merging