chore: Visual changes for core navigation elements on IDE
appsmithorg/appsmith pull request #37880
Opened 2024-12-02 10:37 UTC by hetunandu

## Description

Updates a few visual elements for better Navigational experience using the Segmented Controls

Fixes #`Issue Number`  
_or_  
Fixes `Issue URL`
> [!WARNING]  
> _If no issue exists, please create an issue first, and check with the maintainers if the issue is valid._

## Automation

/ok-to-test tags="@tag.Sanity"

### :mag: Cypress test results

> [!CAUTION]  
> If you modify the content in this section, you are likely to disrupt the CI result for your PR.

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [ ] No

2024-12-02 10:37 UTC, hetunandu commented
/build-deploy-preview

2024-12-02 10:50 UTC, hetunandu commented
/build-deploy-preview

2024-12-02 11:36 UTC, hetunandu commented
/build-deploy-preview

2024-12-02 12:33 UTC, ankitakinger submitted a review, later dismissed

2024-12-02 21:35 UTC, alex-golovanov requested changes

2024-12-02 21:35 UTC, alex-golovanov commented on app/client/src/pages/Editor/IDE/EditorPane/components/SegmentedHeader.tsx
>    #editor-pane-segment-control {
This looks like a bit of mess. Why is `SegmentedControl` being styled through a selector from a parent component and not directly? The hover selector also looks like something that should not exist.

2024-12-02 21:35 UTC, alex-golovanov commented on app/client/src/pages/Editor/IDE/EditorPane/components/SegmentedHeader.tsx
>          options={[
These options should be moved out of the render or placed in a useMemo, so that a new object is not created on every render.

2024-12-02 21:35 UTC, alex-golovanov commented on app/client/src/pages/Editor/IDE/EditorPane/components/SegmentedHeader.tsx
>  const Container = styled(Flex)`
Just for consistency, I'd move styles to a separate file. [nit]

2024-12-04 12:05 UTC, hetunandu commented
/build-deploy-preview

2024-12-18 08:50 UTC, hetunandu commented
/build-deploy-preview

2024-12-18 12:19 UTC, ankitakinger commented on app/client/packages/design-system/ads/src/Templates/EntityExplorer/EditorSegments/EditorSegments.styles.ts
> +      &[data-selected="true"] {
doing this only for Entity explorer? Why not Segmented control itself?

2024-12-19 08:38 UTC, ankitakinger approved these changes

2024-12-19 13:19 UTC, alex-golovanov commented on app/client/src/pages/Editor/IDE/EditorPane/components/SegmentSwitcher.tsx
> +  const segmentOptions = useMemo(() => {
Looks like this could just be moved to constants.

2024-12-19 13:27 UTC, merged