chore: Updating styles and adding docs link for REST API plugin for better UI/UX
appsmithorg/appsmith pull request #37941
Opened 2024-12-04 10:48 UTC by ankitakinger

## Description

Updating styles and adding docs link for REST API plugin for better UI/UX

Fixes [#37925](https://github.com/appsmithorg/appsmith/issues/37925) [#37928](https://github.com/appsmithorg/appsmith/issues/37928) [#37926](https://github.com/appsmithorg/appsmith/issues/37926)

## Automation

/ok-to-test tags="@tag.Sanity"

### :mag: Cypress test results

> [!CAUTION]  
> If you modify the content in this section, you are likely to disrupt the CI result for your PR.

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [ ] No

2024-12-06 08:38 UTC, ankitakinger commented
/build-deploy-preview skip-tests=true

2024-12-06 09:30 UTC, ankitakinger commented
/build-deploy-preview skip-tests=true

2024-12-06 12:14 UTC, hetunandu requested changes

2024-12-06 12:14 UTC, hetunandu commented on app/client/src/PluginActionEditor/components/PluginActionResponse/components/Schema/DatasourceSelector/index.tsx
> +    <QueryDatasourceSelector {...props} />
This is another if statement based on the same logic (API / Query) and can easily cause bugs if one is changed while other is left out. 

Lets update this so that at max we just have one if statement for this component. Would be much better if we dont have any at all.

2024-12-06 12:14 UTC, hetunandu commented on app/client/src/PluginActionEditor/components/PluginActionResponse/components/Schema/SchemaTables.tsx
> +    });
Saw this used twice now. Can we create a reusable hook?

2024-12-06 12:14 UTC, hetunandu commented on app/client/src/PluginActionEditor/components/PluginActionResponse/components/Schema/SchemaTables.tsx
> +        </Flex>
Should be extracted into a diff component since it is implemented twice

2024-12-06 12:14 UTC, hetunandu commented on app/client/src/PluginActionEditor/components/PluginActionResponse/components/Schema/Schema.tsx
Lets rename to "Datasource" now?

2024-12-06 12:30 UTC, ankitakinger commented on app/client/src/PluginActionEditor/components/PluginActionResponse/components/QueryResponseTab/styles.ts
> +  background: var(--ads-v2-color-bg);
I don't see a change in styled components in his PR. So shouldn't be overriden i guess.

2024-12-09 04:59 UTC, hetunandu submitted a review, later dismissed
LGTM

2024-12-09 12:40 UTC, hetunandu approved these changes

2024-12-09 12:42 UTC, merged