Rahulbarwal/Issue13681/Implementation/HTML-Column-type-in-table
appsmithorg/appsmith pull request #37997
Opened 2024-12-06 04:53 UTC by rahulbarwal

## Description

Adds support for rendering HTML content in Table Widget V2 columns with proper sanitization and filtering capabilities.

- Adds new HTML column type with support for:
  - Rendering sanitized HTML content using Interweave
  - Search/filter functionality that ignores HTML tags
  - Sort functionality based on text content
  - CSV export with proper HTML content handling
  - Added unit tests covering HTML column functionality

- Validated accessibility features
Fixes #13681
_or_  
Fixes `Issue URL`
> [!WARNING]  
> _If no issue exists, please create an issue first, and check with the maintainers if the issue is valid._

## Automation

/ok-to-test tags="@tag.Table"

### :mag: Cypress test results

> [!CAUTION]  
> If you modify the content in this section, you are likely to disrupt the CI result for your PR.

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [ ] No

2024-12-06 04:54 UTC, rahulbarwal commented
/build-deploy-preview skip-tests=true

2024-12-06 05:06 UTC, rahulbarwal commented
/build-deploy-preview skip-tests=true

2024-12-06 05:34 UTC, rahulbarwal commented on app/client/src/widgets/TableWidgetV2/component/cellComponents/HTMLCell.tsx
> +  ]);
Done.

2024-12-06 05:34 UTC, rahulbarwal commented
/build-deploy-preview skip-tests=true

2024-12-09 05:56 UTC, rahulbarwal commented
/build-deploy-preview skip-tests=true

2024-12-09 05:59 UTC, rahulbarwal commented
/build-deploy-preview skip-tests=true

2024-12-09 07:12 UTC, jsartisan reviewed
Overall looks ok. but left few comments that can improve the readability of code.

2024-12-09 07:12 UTC, jsartisan commented on app/client/src/widgets/TableWidgetV2/component/cellComponents/HTMLCell/utils.tsx
> +// Function to extract unique HTML tags from a string
I used to do same earlier 😅 but such comments are useless. It's already obvious you are extracting HTML tags from a string by looking at the definition of the function.

2024-12-09 07:12 UTC, jsartisan commented on app/client/src/widgets/TableWidgetV2/component/header/actions/Utilities.ts
> +        const shouldQuote =
What does "shouldQuote" means, it's hard to tell why here.

2024-12-09 07:12 UTC, jsartisan commented on app/client/src/widgets/TableWidgetV2/widget/derived.js
> +       * We don't want html tags and inline styles to match in search
Now this is a good comment, you are telling "why" you are doing this.

2024-12-09 07:12 UTC, jsartisan commented on app/client/src/widgets/TableWidgetV2/widget/derived.js
> +        const arr = [
const arr is not a good name. You can use `combinedRowContent or just do:

```js
isSearchKeyFound = [
  ...Object.values(_.omit(displayedRow, hiddenColumns)),
  ...Object.values(
    _.omit(originalRow, [...hiddenColumns, ...htmlColumns]),
  ),
].includes(searchKey)
```

2024-12-09 07:12 UTC, jsartisan commented on app/client/src/widgets/TableWidgetV2/widget/index.tsx
> +     * Why we are doing this?
💙

2024-12-09 07:12 UTC, jsartisan commented on app/client/src/widgets/TableWidgetV2/widget/propertyConfig/PanelConfig/Data/ColumnType.ts
> +  ...ColumnTypeOptions.slice(0, 4),
Why 4? or not 5 or 6? What is significance of 4 number? Maybe we can use a constant whose name tell the context a little better?

2024-12-09 11:20 UTC, jsartisan commented on app/client/src/widgets/TableWidgetV2/component/cellComponents/HTMLCell/index.tsx
> +const HTMLContainer = styled.div`
Btw, I am saying not to do this in this PR, this is just an FYI

2024-12-09 12:32 UTC, rahulbarwal commented on app/client/src/widgets/TableWidgetV2/component/cellComponents/HTMLCell/index.tsx
> +  const extractedTags = useMemo(() => {
Done.

2024-12-09 12:34 UTC, rahulbarwal commented on app/client/src/widgets/TableWidgetV2/component/cellComponents/HTMLCell/index.tsx
> +    );
Thanks! added changes.

2024-12-09 12:35 UTC, rahulbarwal commented on app/client/src/widgets/TableWidgetV2/component/cellComponents/HTMLCell/index.tsx
> +    const isRenderModeValid = ["DEPLOYED", "EDITOR"].includes(
Yes, makes sense. My bad, removing this piece of code.

2024-12-09 12:46 UTC, rahulbarwal commented on app/client/src/widgets/TableWidgetV2/component/header/actions/Utilities.ts
> +        const shouldQuote =
HTML values are interpreted as multiline strings. If they aren’t enclosed in backticks, the output can become disorganized and visually unappealing.
Adding a comment as well.

2024-12-09 12:51 UTC, rahulbarwal commented on app/client/src/widgets/TableWidgetV2/widget/propertyConfig/PanelConfig/Data/ColumnType.ts
> +  ...ColumnTypeOptions.slice(0, 4),
Alphabetically sorted! will add a comment.

2024-12-09 13:17 UTC, rahulbarwal commented on app/client/src/widgets/TableWidgetV2/widget/utilities.ts
> +      // Then check for date
Done.

2024-12-09 13:18 UTC, rahulbarwal commented
/build-deploy-preview skip-tests=true

2024-12-10 05:51 UTC, rahulbarwal commented
/build-deploy-preview skip-tests=true

2024-12-10 08:19 UTC, jacquesikot commented on app/client/src/widgets/TableWidgetV2/widget/utilities.ts
> +      const isHTML = /<[^>]*>/.test(columnValue as string);
This method doesn't seem exhaustive enough, there's a high chance of false positives with this, can we use something like this?

function detectHTML(input: string): boolean {
  const div = document.createElement("div");
  div.innerHTML = input;
  return div.innerHTML !== input; // If innerHTML modifies input, it's likely HTML
}

2024-12-10 08:20 UTC, jacquesikot commented on app/client/src/widgets/TableWidgetV2/widget/utilities.ts
> +      const isHTML = /<[^>]*>/.test(columnValue as string);
Or a stricter regex?

2024-12-10 10:37 UTC, rahulbarwal commented on app/client/src/widgets/TableWidgetV2/widget/utilities.ts
> +      const isHTML = /<[^>]*>/.test(columnValue as string);
We analyzed this, and the current check is sufficient to validate html. 
1. `Testing <span> text </text>`
2. `<strong> Rahul `

Invalid HTML, text not starting with a tag are all rendered by browser correctly and will not pass the aforementioned validity function. 
It's best to stay put with current implementation. Let me know if you disagree.

2024-12-10 13:13 UTC, sagar-qa007 requested changes

2024-12-10 13:13 UTC, sagar-qa007 commented on app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/columnTypes/HTMLCell_spec.ts
> +const htmlTableData = [
Can we please put this data in fixture folder as file?

2024-12-10 13:53 UTC, jsartisan submitted a review, later dismissed

2024-12-11 07:32 UTC, sagar-qa007 approved these changes

2024-12-11 07:37 UTC, merged