chore: extract search and add to ads
appsmithorg/appsmith pull request #38192
Opened 2024-12-16 14:36 UTC by alex-golovanov

## Description
Extract search and add to ADS.

Fixes [#37888](https://github.com/appsmithorg/appsmith/issues/37888)

## Automation

/ok-to-test tags="@tag.Sanity"

### :mag: Cypress test results

> [!CAUTION]  
> If you modify the content in this section, you are likely to disrupt the CI result for your PR.

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [x] No

2024-12-16 14:41 UTC, ankitakinger commented on app/client/packages/design-system/ads/src/Templates/EntityExplorer/SearchAndAdd/SearchAndAdd.tsx
> +            aria-label="Add"
should we add test ids for using it in cypress tests?

2024-12-16 14:43 UTC, ankitakinger commented on app/client/packages/design-system/ads/src/Templates/EntityExplorer/SearchAndAdd/SearchAndAdd.tsx
> +      <Styles.Root>
why not use the Flex component in ADS?

2024-12-16 14:51 UTC, ankitakinger commented on app/client/packages/design-system/ads/src/SearchInput/SearchInput.styles.tsx
> +    --input-padding-x: calc(var(--ads-v2-spaces-2)); // padding left and right
I don't think we should make style changes here or in Input component, as this will have impact all over the product. 

You may have to consult with Momcilo/Vinay first, before making these changes, as these were planned paddings added for inputs during the ADS 2.0 project. 

cc: @albinAppsmith

2024-12-16 15:02 UTC, ankitakinger commented on app/client/packages/design-system/ads/src/Templates/EntityExplorer/SearchAndAdd/SearchAndAdd.stories.tsx
> +
We don't need this story as such, as we plan to add story for the Entity explorer as a whole, showing different variations for the same.

Refer `IDEHeader` template on design-system.appsmith.com for context.

2024-12-16 19:07 UTC, alex-golovanov commented on app/client/packages/design-system/ads/src/Templates/EntityExplorer/SearchAndAdd/SearchAndAdd.tsx
> +            aria-label="Add"
Good call, will do. Btw, it's something that should be in the task.

2024-12-16 19:09 UTC, alex-golovanov commented on app/client/packages/design-system/ads/src/Templates/EntityExplorer/SearchAndAdd/SearchAndAdd.tsx
> +      <Styles.Root>
I don't like it, it's opaque and doesn't add any value to the standard flex box, as far as I see it.

2024-12-16 19:11 UTC, alex-golovanov commented on app/client/packages/design-system/ads/src/Templates/EntityExplorer/SearchAndAdd/SearchAndAdd.stories.tsx
> +
There must be some misunderstanding, in fact, **we need a story for every component**. This is the whole point of developing components in storybook.

2024-12-16 19:17 UTC, alex-golovanov commented on app/client/packages/design-system/ads/src/SearchInput/SearchInput.styles.tsx
> +    --input-padding-x: calc(var(--ads-v2-spaces-2)); // padding left and right
On contrary, we should change the component if it does not match the design. Search input depends on base input and icon alignments were off. I will run this by Momcillo, for sure.

2024-12-16 22:02 UTC, ankitakinger commented on app/client/packages/design-system/ads/src/Templates/EntityExplorer/SearchAndAdd/SearchAndAdd.stories.tsx
> +
Thats actually a discussion that I and Hetu had, sorry we should have posted about the same on channel later. But it made sense to me, as these will all be Entity Explorer template components so it makes sense to have a Entity Explorer story showing different variations of the same.

Also, for this component specifically, adding a story would rather be more confusing because this mostly looks quite similar to `SegmentedControl` component in ADS.

2024-12-16 22:05 UTC, ankitakinger commented on app/client/packages/design-system/ads/src/Templates/EntityExplorer/SearchAndAdd/SearchAndAdd.stories.tsx
> +
This is a conversation that I and Hetu had on our 1:1, sorry we should have posted about the same on channel later. But it made sense to me that we should have stories as a whole Entity Explorer variations that we can have. Similar to different variations in Miro board:
https://miro.com/app/board/uXjVL_l_VM8=/?moveToWidget=3458764608339172510&cot=14

2024-12-17 06:16 UTC, albinAppsmith commented on app/client/packages/design-system/ads/src/SearchInput/SearchInput.styles.tsx
> +    --input-padding-x: calc(var(--ads-v2-spaces-2)); // padding left and right
@alex-golovanov Make sure this change is not breaking anything else. Since we change padding, the height and width also changes. This should not break any UI. So please check the usage and ensure that it's intact.

2024-12-17 07:11 UTC, ankitakinger commented on app/client/packages/design-system/ads/src/Templates/EntityExplorer/SearchAndAdd/SearchAndAdd.tsx
> +            aria-label="Add"
Sure. Didn't add it as a point in the task as it was already used in the `AddAndSearchBar` component which we are referring to make this component, and removing this is going to break tests. Will take care of it next time.

2024-12-17 08:29 UTC, alex-golovanov commented on app/client/packages/design-system/ads/src/Templates/EntityExplorer/SearchAndAdd/SearchAndAdd.tsx
> +            aria-label="Add"
Done. I've kept the button selector the same, so that it does not break Cypress tests when we do the replacing part.

2024-12-17 08:30 UTC, ankitakinger commented on app/client/packages/design-system/ads/src/Templates/EntityExplorer/SearchAndAdd/SearchAndAdd.tsx
> +            aria-label="Add"
Why are we not doing the replacing part in the current PR?

2024-12-17 08:32 UTC, alex-golovanov commented on app/client/packages/design-system/ads/src/SearchInput/SearchInput.styles.tsx
> +    --input-padding-x: calc(var(--ads-v2-spaces-2)); // padding left and right
Synced with Momcilo, it appears that the new design is out of sync with ADS inputs, so I'm reverting these paddings. Designs will be updated accordingly. 

Thanks for pointing this out @ankitakinger.

@albinAppsmith It was only a horizontal value change (padding-x), so height would not be affected.

2024-12-17 08:40 UTC, alex-golovanov commented on app/client/packages/design-system/ads/src/Templates/EntityExplorer/SearchAndAdd/SearchAndAdd.tsx
> +            aria-label="Add"
It was never mentioned that the component needs to be replaced in the project.

2024-12-17 08:43 UTC, ankitakinger commented on app/client/packages/design-system/ads/src/Templates/EntityExplorer/SearchAndAdd/SearchAndAdd.tsx
> +            aria-label="Add"
This was discussed in one of the team calls that all tasks will be taking care of their respective replacements.

2024-12-17 08:52 UTC, alex-golovanov commented on app/client/packages/design-system/ads/src/Templates/EntityExplorer/SearchAndAdd/SearchAndAdd.tsx
> +            aria-label="Add"
Ankita, you keep referring to discussions that took place elsewhere, however anything that needs to be done has to be described in the task itself. Please, provide complete descriptions to avoid confusion.

2024-12-17 08:55 UTC, ankitakinger commented on app/client/packages/design-system/ads/src/Templates/EntityExplorer/SearchAndAdd/SearchAndAdd.tsx
> +            aria-label="Add"
Alex, if you check I have mentioned "team calls". This way none of the tasks mention about storybook yet we know that we have to do it right. The replacement also works the same way.

These are common points in all tasks. This was a common understanding to take care of things like storybook, replacing components and adding test ids if already present in current implementation.

2024-12-17 12:17 UTC, alex-golovanov commented on app/client/packages/design-system/ads/src/Templates/EntityExplorer/SearchAndAdd/SearchAndAdd.tsx
> +            aria-label="Add"
You've asked me why I have not replaced them, I've simply answered your question. Task needs to describe all things that have to be done. Both, stories and replacement of project components need to be in this task. 

Of course, I will replace project component with ADS one, but again, I did not consider this a step until you mentioned it.

2024-12-18 06:09 UTC, ankitakinger commented on app/client/packages/design-system/ads/src/Templates/EntityExplorer/SearchAndAdd/SearchAndAdd.stories.tsx
> +  title: "ADS/Templates/EntityExplorer/SearchAndAdd",
Can we add update `EntityExplorer` to `Entity Explorer`?

2024-12-18 06:12 UTC, ankitakinger commented on app/client/packages/design-system/ads/src/Templates/EntityExplorer/SearchAndAdd/SearchAndAdd.tsx
> +            aria-label="Add"
This also has a `className` that is getting used in some tests. Either we should update those tests to use `data-testid` or we should add the `className`. Referring to the class `t--add-item`.

2024-12-18 07:17 UTC, alex-golovanov commented on app/client/packages/design-system/ads/src/Templates/EntityExplorer/SearchAndAdd/SearchAndAdd.stories.tsx
> +  title: "ADS/Templates/EntityExplorer/SearchAndAdd",
> Can we add update `EntityExplorer` to `Entity Explorer`?

We can talk this over in slack. I'm used to naming stories with component names (without spaces), but it appears that in ADS there is no single approach to naming stories. So, let's decide on a single format.

2024-12-18 07:19 UTC, alex-golovanov commented on app/client/packages/design-system/ads/src/Templates/EntityExplorer/SearchAndAdd/SearchAndAdd.tsx
> +            aria-label="Add"
We should avoid using class names for tests and it's a duplicate as well. I will replace the selector in failing tests.

2024-12-18 09:01 UTC, alex-golovanov commented on app/client/packages/design-system/ads/src/Templates/EntityExplorer/SearchAndAdd/SearchAndAdd.stories.tsx
> +  title: "ADS/Templates/EntityExplorer/SearchAndAdd",
Changed to the most common format that you have suggested (and merged).

2024-12-18 09:07 UTC, ankitakinger submitted a review, later dismissed

2024-12-19 03:22 UTC, sagar-qa007 commented
@alex-golovanov Please run tag.Sanity as you have updated the common code.

2024-12-19 03:23 UTC, sagar-qa007 requested changes

2024-12-19 08:13 UTC, sagar-qa007 approved these changes

2024-12-19 08:13 UTC, merged