Add Tutorials to Readme
appsmithorg/appsmith pull request #3893
Opened 2021-04-06 16:01 UTC by vihar

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.

## Description
> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation 
> and context. List any dependencies that are required for this change.

Fixes # (issue)
> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce. 
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-04-06 17:38 UTC, akshayrangasaid commented
We'll need to add to the tutorials. Can you please look at confidence videos and put them? Appsmith needs to be front and center of the tutorials. Build Admin Panel without CSS and HTML is not front and center. They just use appsmith. 

For example:

https://www.youtube.com/watch?v=CYdeJcD4I8A -> Title in the commit is wrong.

https://www.youtube.com/watch?v=eYYYfuW-kEE -> Another example, this one mark as community

https://dev.to/pjmantoss/how-to-build-an-issue-tracker-with-appsmith-204e -> Another example. Mark it as community

Then the video of Nikhil should work along with the mongodb one

2021-04-07 16:31 UTC, akshayrangasaid approved these changes

2021-04-08 09:30 UTC, Nikhil-Nandagopal commented on README.md
> +   2. Write the query `select * from users limit 5;`.
This is a bug without the spaces, it won't show as sub steps when it renders

2021-04-08 09:31 UTC, Nikhil-Nandagopal commented on README.md
> +2. [Building a customer support dashboard in Appsmith](https://www.youtube.com/watch?v=-O_6OLREEzo&t=272s)
can we merge this with the demo section?

2021-04-08 09:32 UTC, Nikhil-Nandagopal requested changes
Just had one suggestion

2021-04-09 05:40 UTC, vihar commented on README.md
> +2. [Building a customer support dashboard in Appsmith](https://www.youtube.com/watch?v=-O_6OLREEzo&t=272s)
Yes, we could merge this and add a tag as `Demo`. @akshayrangasaid thoughts?

2021-04-09 07:51 UTC, akshayrangasaid commented on README.md
> +2. [Building a customer support dashboard in Appsmith](https://www.youtube.com/watch?v=-O_6OLREEzo&t=272s)
@Nikhil-Nandagopal Right now the demo apps and tutorials do not have the same flow, we'll either convert demo to tutorials or make them easier to grok and merge. Think for now, keeping them separate is best to maintain consistency.

2021-04-09 08:28 UTC, Nikhil-Nandagopal commented on README.md
> +2. [Building a customer support dashboard in Appsmith](https://www.youtube.com/watch?v=-O_6OLREEzo&t=272s)
@akshayrangasaid what if we kill the demo apps, show only tutorials but have a link to a forkable version of the tutorial app at the start of every tutorial?

2021-04-09 08:33 UTC, akshayrangasaid commented on README.md
> +2. [Building a customer support dashboard in Appsmith](https://www.youtube.com/watch?v=-O_6OLREEzo&t=272s)
@Nikhil-Nandagopal yep for sure. I like the keywords the demo apps show, thus want to keep them on while we get some content out, but not too fussed to just kill them now only and bring them back with a more solid onboarding/tutorial. 


Longer-term with collab + notes, we can just have forkable apps with notes in it without the overhead of a tut.

2021-04-09 11:06 UTC, Nikhil-Nandagopal approved these changes

2021-04-12 04:44 UTC, merged