Bugfix: omnibar issues : fixes #3742
appsmithorg/appsmith pull request #3998
Opened 2021-04-14 08:20 UTC by kaushik94

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.

## Description
> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation 
> and context. List any dependencies that are required for this change.

Fixes # (issue)
> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce. 
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-04-21 09:00 UTC, rishabhsaxena requested changes

2021-04-21 09:00 UTC, rishabhsaxena commented on app/client/src/components/editorComponents/GlobalSearch/HelpBar.tsx
> +    dispatch(setGlobalSearchQuery(""));
This does not reset the query? Also think should confirm this once, since we're preserving the prev state by design

2021-04-21 09:00 UTC, rishabhsaxena commented on app/client/src/components/editorComponents/GlobalSearch/HelpBar.tsx
> +  }
Should we add a transparent border here in the not hovered state, so that elements don't move on hover?

2021-04-21 09:00 UTC, rishabhsaxena commented on app/client/src/components/editorComponents/GlobalSearch/index.tsx
> +    selectedWidgetId &&
We're slicing the list to show n-1 latest entities (within: `useRecentEntites`), guess would need to update the logic there instead

2021-04-21 09:00 UTC, rishabhsaxena commented on app/client/src/pages/Editor/QueryEditor/OmnibarDocumentationHelper.ts
> +  console.log("linkURL: ", linkURL);
should remove/comment log

2021-04-21 09:00 UTC, rishabhsaxena commented on app/client/src/pages/Editor/QueryEditor/OmnibarDocumentationHelper.ts
> +  for (const headerItem of documentationHeaders) {
NIT: this could be a map instead of an array so we don't need to loop over it

2021-04-21 11:00 UTC, kaushik94 commented on app/client/src/components/editorComponents/GlobalSearch/HelpBar.tsx
> +    dispatch(setGlobalSearchQuery(""));
Yes I guess it does. It was a requirement by @Nikhil-Nandagopal . I believe it sets global query to "".

2021-04-21 11:04 UTC, kaushik94 commented on app/client/src/components/editorComponents/GlobalSearch/index.tsx
> +    selectedWidgetId &&
@rishabhsaxena I tried doing that, but then TS is complaining that `selectedWidgetId` could be null sometimes. So I added a check.

2021-04-21 11:13 UTC, rishabhsaxena commented on app/client/src/components/editorComponents/GlobalSearch/HelpBar.tsx
> +    dispatch(setGlobalSearchQuery(""));
Yeah let's reset it

2021-04-21 11:15 UTC, rishabhsaxena commented on app/client/src/components/editorComponents/GlobalSearch/index.tsx
> +    selectedWidgetId &&
Yeah as in, I meant we shouldn't need to explicitly `updateRecentEntity `
We don't see the latest entity is because we are slicing the list within `useRecentEntities` hook, so we'd to update that instead

2021-04-23 11:41 UTC, rishabhsaxena requested changes
LGTM
But the query still does not get cleared for me in the deploy preview, both while using the hotkey or clicking on the bar
https://deploy-preview-3998--appsmith-editor-ce.netlify.app/

The point about showing the cheat sheet is still pending, I suppose we should create another issue to track it. Since, we might fix it separately

2021-04-24 00:40 UTC, kaushik94 commented
@rishabhsaxena the first change has been addressed with the last commit. Regarding second point, I think @Nikhil-Nandagopal wants to track it separately. Please confirm.

2021-04-24 00:43 UTC, kaushik94 commented
@Nikhil-Nandagopal All changes are done except clicking "read more" on DB editor. I realized that `useDispatch()` cannot be called from a react class component. This might mean I have to change the component structure significantly. Therefore can we please track this in a separate issue? @rishabhsaxena can you please confirm that this is correct. Please suggest a better way if you can. Thank you so much.

2021-04-24 08:36 UTC, Nikhil-Nandagopal commented
@kaushik94 yes I'll track the docs changes separately. I don't see why the readmore is complicated. Can we just re-use a different component like the one that's in the api pane to show this message?

2021-04-25 17:52 UTC, kaushik94 commented
@Nikhil-Nandagopal yes you are right. Initially when I tried to do it, I forgot to pass `mapStateToProps` to it. Therefore I was failing. Now I could complete it easily.

2021-04-25 18:51 UTC, kaushik94 commented
@Nikhil-Nandagopal I committed the changes. Can you please check the deploy preview and confirm. Thanks so much.

2021-04-26 03:21 UTC, rishabhsaxena submitted a review, later dismissed
Just a couple minor comments

2021-04-26 03:21 UTC, rishabhsaxena commented on app/client/src/components/editorComponents/GlobalSearch/HelpBar.tsx
> +    dispatch(setGlobalSearchQuery(""));
I guess we're resetting it within the global search component. Just confirming do we need to reset it here as well?

2021-04-26 03:21 UTC, rishabhsaxena commented on app/client/src/components/editorComponents/GlobalSearch/index.tsx
> +    setQuery("");
I guess this won't be required here as well?

2021-04-26 06:00 UTC, rishabhsaxena approved these changes

2021-04-26 08:48 UTC, rishabhsaxena submitted a review, later dismissed

2021-04-26 14:24 UTC, Nikhil-Nandagopal approved these changes

2021-04-26 16:45 UTC, merged