Fix-Native scrollbar UX with custom scrollbars
appsmithorg/appsmith pull request #4006
Opened 2021-04-15 05:06 UTC by vicky-primathon

## Description
Native scrollbar UX with custom scrollbars

Fixes #2895 #3249 #3966

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-04-20 10:42 UTC, riodeuno requested changes

2021-04-20 10:42 UTC, riodeuno commented on app/client/src/components/designSystems/appsmith/TableComponent/Table.tsx
> +            <div {...props} className="thumb-vertical" />
Does this property need all the props?
Also, if this is a component, let's abstract it out and put it outside this component. Otherwise, this component will be created every time. Best case scenario is to make sure we only pass the props which are necessary.
Also, let's wrap the component in `React.memo`

2021-04-20 10:42 UTC, riodeuno commented on app/client/src/components/designSystems/appsmith/TableComponent/Table.tsx
> +                return column.accessor !== "actions";
Let's put this in a `useMemo` so that this is not computed on every render and only renders when the columns change.

2021-04-20 10:49 UTC, riodeuno commented
There are merge conflicts. Let's resolve those.

2021-04-20 10:49 UTC, riodeuno approved these changes
Approving for tests to run

2021-04-28 09:06 UTC, riodeuno submitted a review, later dismissed

2021-04-29 06:25 UTC, somangshu approved these changes

2021-04-29 10:57 UTC, merged

2021-05-04 21:36 UTC, areyabhishek commented
@vicky-primathon There's a weird case where there's a scrollbar visible. Could you fix this?
https://www.loom.com/share/a3f9926e9a8a487caea097d40317dae6