WIP : Replace route with intercept
appsmithorg/appsmith pull request #4042
Opened 2021-04-19 05:16 UTC by NandanAnantharamu

replacing route with intercept
Some tests modified to handle this change.

2021-04-19 05:21 UTC, hetunandu commented
/ok-to-test sha=776bace

2021-04-20 16:50 UTC, NandanAnantharamu commented
/ok-to-test sha=ee7b681

2021-04-21 08:54 UTC, NandanAnantharamu commented
/ok-to-test sha=2354c8b

2021-04-21 14:56 UTC, NandanAnantharamu commented
/ok-to-test sha=0e78cbf

2021-04-21 17:12 UTC, NandanAnantharamu commented
/ok-to-test sha=e29a4d0

2021-04-25 06:16 UTC, NandanAnantharamu commented
/ok-to-test sha=e46f76f

2021-04-25 07:26 UTC, NandanAnantharamu commented
/ok-to-test sha=fc90d69

2021-04-25 10:13 UTC, NandanAnantharamu commented
/ok-to-test sha=ab6e9db

2021-04-25 12:48 UTC, NandanAnantharamu commented
/ok-to-test sha=d32bbfd

2021-04-26 06:54 UTC, NandanAnantharamu commented
/ok-to-test sha=f1672a4

2021-04-26 08:07 UTC, NandanAnantharamu commented
/ok-to-test sha=2f81105

2021-04-27 07:48 UTC, NandanAnantharamu commented
/ok-to-test sha=c146950

2021-04-27 16:14 UTC, NandanAnantharamu commented
/ok-to-test sha=dd9455b

2021-04-27 17:18 UTC, NandanAnantharamu commented
/ok-to-test sha=9f3c558

2021-04-28 10:33 UTC, NandanAnantharamu commented
/ok-to-test sha=c33dc6f

2021-04-28 16:49 UTC, NandanAnantharamu commented
/ok-to-test sha=5f1b0c5

2021-04-29 06:49 UTC, NandanAnantharamu commented
/ok-to-test sha=8041ae9

2021-04-29 08:27 UTC, NandanAnantharamu commented
/ok-to-test sha=e323338

2021-04-29 12:41 UTC, NandanAnantharamu commented
/ok-to-test sha=a7b4132

2021-04-30 07:03 UTC, NandanAnantharamu commented
/ok-to-test sha=75bb759

2021-05-03 10:20 UTC, NandanAnantharamu commented
/ok-to-test sha=f999169

2021-05-04 05:15 UTC, NandanAnantharamu commented
/ok-to-test sha=c0c8cc2

2021-05-10 06:40 UTC, NandanAnantharamu commented
/ok-to-test sha=de02c7b

2021-05-14 09:59 UTC, hetunandu commented
@NandanAnantharamu Please resolve the conflicts and run the test suite again

2021-05-19 02:13 UTC, NandanAnantharamu commented
/ok-to-test sha=54d5587

2021-05-20 05:46 UTC, NandanAnantharamu commented
/ok-to-test sha=ed4564c

2021-05-20 08:58 UTC, NandanAnantharamu commented
/ok-to-test sha=da2c47a

2021-05-20 11:07 UTC, NandanAnantharamu commented
/ok-to-test sha=58b9188

2021-05-20 18:26 UTC, NandanAnantharamu commented
/ok-to-test sha=ab4a2f8

2021-05-20 18:48 UTC, NandanAnantharamu commented
/ok-to-test sha=2500aeb

2021-05-20 19:04 UTC, NandanAnantharamu commented
/ok-to-test sha=f31046c

2021-05-21 11:54 UTC, NandanAnantharamu commented
/ok-to-test sha=9821da8

2021-05-21 12:37 UTC, hetunandu requested changes
Minor change

2021-05-21 12:37 UTC, hetunandu commented on app/client/cypress/support/commands.js
> +function checkIfApiWasSuccessful(interception, statuscode) {
Rename to `assertApiResponseStatusCode`

2021-05-21 16:14 UTC, NandanAnantharamu commented
/ok-to-test sha=2e28490

2021-05-23 08:01 UTC, NandanAnantharamu commented
/ok-to-test sha=2e28490

2021-05-31 07:03 UTC, NandanAnantharamu commented
/ok-to-test sha = 7dce4e59

2021-05-31 07:15 UTC, NandanAnantharamu commented
/ok-to-test sha = 7dc4e59

2021-06-19 18:10 UTC, NandanAnantharamu commented
/ok-to-test sha = a510cfb

2021-06-20 06:06 UTC, NandanAnantharamu commented
/ok-to-test sha =a510cfb

2021-06-21 10:57 UTC, arslanhaiderbuttar approved these changes

2021-06-22 17:55 UTC, NandanAnantharamu commented
/ok-to-test sha=e660153

2021-06-27 16:16 UTC, NandanAnantharamu commented
/ok-to-test sha=4e2fe81

2021-06-27 17:46 UTC, NandanAnantharamu commented
/ok-to-test sha=3450f5e

2021-06-28 10:18 UTC, mohanarpit submitted a review, later dismissed

2021-06-28 10:18 UTC, mohanarpit commented
Approving to run the tests

2021-06-28 17:20 UTC, NandanAnantharamu commented
/ok-to-test sha=450ddeb

2021-07-02 17:59 UTC, NandanAnantharamu commented
/ok-to-test sha=034717c

2021-07-03 14:28 UTC, NandanAnantharamu commented
/ok-to-test sha=30392a3

2021-07-04 10:15 UTC, NandanAnantharamu commented
/ok-to-test sha=277df53

2021-07-04 16:35 UTC, NandanAnantharamu commented
/ok-to-test sha=056f34f

2021-07-05 05:52 UTC, NandanAnantharamu commented
/ok-to-test sha=056f34f

2021-07-06 07:17 UTC, NandanAnantharamu commented
/ok-to-test sha=8b05989

2021-07-15 08:48 UTC, NandanAnantharamu commented
/ok-to-test sha=6a3725e

2021-07-25 08:02 UTC, NandanAnantharamu commented
/ok-to-test sha=001490b

2021-07-30 15:05 UTC, NandanAnantharamu commented
/ok-to-test sha= 370be68

2021-07-30 16:42 UTC, NandanAnantharamu commented
/ok-to-test sha=370be68

2021-07-30 17:58 UTC, NandanAnantharamu commented
/ok-to-test sha=517c65e

2021-07-31 09:31 UTC, NandanAnantharamu commented
/ok-to-test sha=1b41bd6

2021-08-26 07:02 UTC, yatinappsmith submitted a review, later dismissed

2021-09-01 08:40 UTC, yatinappsmith approved these changes
LGTM

2021-12-22 05:00 UTC, NandanAnantharamu commented
closing this as its not relevant

2021-12-22 05:00 UTC, closed without merging