Fix: Return helpful error message when get structure fails for mongo db due to lack of read permission.
appsmithorg/appsmith pull request #4061
Opened 2021-04-20 02:36 UTC by sumitsum

## Description
- return helpful error message when get structure fails for mongo db due to lack of read permission. The message returned is: `Appsmith has failed to get database structure. Please provide read permission on the database to fix this.`
- Other changes:
  - stop logging `PLUGIN_GET_STRUCTURE_ERROR` externally, as this error is mostly triggered by credentials error or lack of read permission. 
  - start logging `PLUGIN_GET_STRUCTURE_TIMEOUT_ERROR` externally, because this is not a user error. 

Fixes 1479

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- manually 
- Test case

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-04-20 04:17 UTC, nidhi-nair commented on app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java
> +                            MongoCommandException.class,
@sumitsum Does this exception only wrap permission related issues for command execution? We might mistakenly classify other exceptions as permission issues as well with such a blanket capture.

2021-04-20 04:47 UTC, sumitsum commented on app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java
> +                            MongoCommandException.class,
Fixed this by adding a check for error code.

2021-04-20 05:44 UTC, nidhi-nair approved these changes

2021-04-20 06:30 UTC, nidhi-nair requested changes
Needs to not return this as an exception

2021-04-20 10:38 UTC, nidhi-nair commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/DatasourceStructure.java
> +    String errorMessage;
Hey @sumitsum, looks like this handling return all types of getStructure errors quietly, will client side be handling each type of error separately? Also, I'd suggest encapsulating the error fields in a common error object that can be used across all our response DTOs in the future.

2021-04-20 11:07 UTC, trishaanand commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/DatasourceStructure.java
> +    String errorMessage;
@nidhi-nair : Don't understand very well your recommendation. The client today ignores all datasource structure errors because it is not an essential operation. The idea is to display the error info in the entity pane when the user tries to expand the datasource.

2021-04-20 11:45 UTC, nidhi-nair commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/DatasourceStructure.java
> +    String errorMessage;
Adding info to my comment here as well. By "handling each type of error separately", I meant to ask whether we expect to return all datasource structure related errors in the same way. The encapsulated version of errors will be able to add structure to these errors better in that case because we may at some point want to differentiate between server and user errors, etc.

2021-04-21 01:47 UTC, sumitsum commented
Closing this in favor of https://github.com/appsmithorg/appsmith/pull/4077 because some unrelated commits have somehow crept in during rebase.

2021-04-21 01:47 UTC, closed without merging