Contribution doc
appsmithorg/appsmith pull request #408
Opened 2020-08-24 06:28 UTC by hetunandu

2020-08-24 09:22 UTC, riodeuno requested changes

2020-08-24 09:22 UTC, riodeuno commented on CONTRIBUTING.md
> +There are many places ways can contribute to Appsmith and all types of contributions are highly appreciated.
There are many ways in which we/one can to contribute to Appsmith.  All contributions are highly appreciated.

2020-08-24 09:22 UTC, riodeuno commented on CONTRIBUTING.md
> +First off, thanks for your interest in Appsmith and taking the time to contribute on this project. 🙌
Thank you for your interest..

2020-08-24 09:22 UTC, riodeuno commented on CONTRIBUTING.md
> +Our frontend client is written in ReactJS and Typescript. State management is done via Redux and workflows
Appsmith's client (UI/frontend) uses the ReactJS library and Typescript. The application also uses libraries like react-redux and redux-saga..

2020-08-24 09:22 UTC, riodeuno commented on CONTRIBUTING.md
> +
On the development/local machine, please make sure that:

2020-08-24 09:22 UTC, riodeuno commented on CONTRIBUTING.md
> +2. You have `mkcert` installed. Please visit: [https://github.com/FiloSottile/mkcert#installation](https://github.com/FiloSottile/mkcert#installation) for details.
(For `mkcert` to work with firefox `nss` may be required. Details are in the link)

2020-08-24 09:22 UTC, riodeuno commented on CONTRIBUTING.md
> +    - Change the API endpoint in the Nginx configuration available in `docker/templates/nginx-linux.conf.template` or `docker/templates/nginx-mac.conf.template`
We will have to run `start-https.sh` again.

2020-08-24 09:22 UTC, riodeuno commented on CONTRIBUTING.md
> +1. Make the values in `nginx-mac.conf.template` empty. None of those properties are required.
@hetunandu  Do you think the users will need a screencast for this troubleshooting. A youtube link maybe?

2020-08-25 03:44 UTC, mohanarpit approved these changes

2020-08-25 03:45 UTC, merged