Feature: fork apps across orgs
appsmithorg/appsmith pull request #4121
Opened 2021-04-23 09:31 UTC by kaushik94

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.

## Description
> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation 
> and context. List any dependencies that are required for this change.

Fixes # (issue)
> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce. 
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-04-26 19:48 UTC, rishabhsaxena requested changes
Works well, just a couple of points regarding some unused code and if we can reuse the existing fork app modal

2021-04-26 19:48 UTC, rishabhsaxena commented on app/client/src/actions/applicationActions.ts
> +export const forkApplication = (
I guess we could remove this, since we're not using this action

2021-04-26 19:48 UTC, rishabhsaxena commented on app/client/src/pages/Applications/ForkApplicationAcrossOrganisationsModal.tsx
> +import React, { useEffect, useMemo, useState } from "react";
Wondering can we reuse fork application modal that's already existing?

2021-04-26 19:48 UTC, rishabhsaxena commented on app/client/src/pages/Applications/index.tsx
> +  forkApplication,
I suppose we're not dispatching it from here, instead we're dispatching from within the modal, so we could remove this from here?

2021-04-26 19:48 UTC, rishabhsaxena commented on app/client/src/pages/Applications/ApplicationCard.tsx
> +    if (props.fork && hasEditPermission) {
We could just check for `hasEditPermission` here

2021-04-26 20:16 UTC, kaushik94 commented on app/client/src/actions/applicationActions.ts
> +export const forkApplication = (
I believe we are importing from `Applications/index.tsx` and wrapping it under `forkApplicationDispatch`

2021-04-26 20:22 UTC, kaushik94 commented on app/client/src/pages/Applications/ForkApplicationAcrossOrganisationsModal.tsx
> +import React, { useEffect, useMemo, useState } from "react";
You are right. We could have used the ForkApplicationModal that is existing. But I saw some parameters like `trigger`, some `useEffect` hooks that are causing side effects. So I felt it safer to create a new component. I will try reusing since most of this code is copy/pasted from there.

2021-04-26 20:24 UTC, kaushik94 commented on app/client/src/pages/Applications/index.tsx
> +  forkApplication,
So I will make the component `ForkApplicationAcrossOrganizationModal` connected and dispatch from there?

2021-04-26 20:26 UTC, kaushik94 commented on app/client/src/pages/Applications/ApplicationCard.tsx
> +    if (props.fork && hasEditPermission) {
I left this as a optional parameter. If the fork parameter is not present would it not fail?

2021-04-26 20:34 UTC, rishabhsaxena commented on app/client/src/pages/Applications/ApplicationCard.tsx
> +    if (props.fork && hasEditPermission) {
As in we could do without this check. Assuming if a user has edit permissions, an app can always be forked from here

2021-04-26 20:36 UTC, rishabhsaxena commented on app/client/src/actions/applicationActions.ts
> +export const forkApplication = (
I couldn't find where it's being called from, we're passing it as a prop but dispatching another action from the modal component

2021-04-26 21:09 UTC, kaushik94 commented
@rishabhsaxena you are right, we are not using the `forkApp` function. I updated the code regarding that. Please let me know if I missed something.

2021-04-27 03:50 UTC, kaushik94 commented
@rishabhsaxena I tried reusing the component, but I am getting errors like the following:
`React Hook "useEffect" is called conditionally. React Hooks must be called in the exact same order in every component render `
My implementation is like:
```
  if (isDeployedApp) {
    const currentPageId = useSelector(getCurrentPageId);
    const { pathname } = useLocation();
```
Also the implementation is not clean and it looks hacky. Can you please suggest a good way to reuse this component or should we go with the existing PR?

2021-04-27 08:43 UTC, rishabhsaxena approved these changes
Trigger tests

2021-04-28 17:19 UTC, kaushik94 commented
@rishabhsaxena I have refactored the code. Can you please review this PR. Thank you so much.

2021-04-29 09:49 UTC, rishabhsaxena requested changes
I think the following flow isn't working for the fork apps flow:
- Open a public forkable app (in logged out state)
- Click on fork -> we'd be redirected to the login page
- Post login we land on the correct page, but the fork modal doesn't show. We need to click on the fork btn.

Couple of points regarding the refactor:
- Think shouldn't call it an HOC, an HOC ideally accepts a component as an argument
- Can we pass the props `isOpen` & `trigger` (null in case of applications menu) as props to the modal component? So we can re-use the UI component as well. So we'd have just one component

2021-04-30 05:13 UTC, kaushik94 commented
@rishabhsaxena I am having difficulty organizing useEffect code in the same component. If I put an `if (isOpen)` above it, the compiler complains. Please help with this case. Thanks.

2021-05-03 12:10 UTC, kaushik94 commented
@rishabhsaxena @Nikhil-Nandagopal I believe it is ready for review. Please take a look. Thanks.

2021-05-03 17:05 UTC, rishabhsaxena submitted a review, later dismissed
Just a few minor comments

2021-05-03 17:05 UTC, rishabhsaxena commented on app/client/src/pages/Applications/ForkApplicationModal.tsx
> +    if (isDeployedApp) {
We should remove `isDeployedApp` check from across the modal

2021-05-03 17:05 UTC, rishabhsaxena commented on app/client/src/pages/Applications/ForkApplicationModal.tsx
> +  }, [isModalOpen]);
Should remove this snippet, instead update the `isOpen` prop to check for either `isOpen` or `showBasedOnUrl`

2021-05-03 17:05 UTC, rishabhsaxena commented on app/client/src/pages/Applications/ForkApplicationModal.tsx
> +        isDeployedApp ? (
```suggestion
        trigger && (
```

2021-05-03 17:05 UTC, rishabhsaxena commented on app/client/src/pages/Applications/ForkApplicationModal.tsx
> +      {isDeployedApp && isFetchingApplications && (
should remove check for `isDeployedApp`

2021-05-03 17:05 UTC, rishabhsaxena commented on app/client/src/pages/Applications/ForkApplicationModal.tsx
> +        isDeployedApp ? (
Assuming we can pass `trigger` as a prop instead

2021-05-03 18:07 UTC, kaushik94 commented
@rishabhsaxena I made the changes. Please take a look and let me know. Thanks.

2021-05-03 18:23 UTC, rishabhsaxena approved these changes
Few minor comments. Also I think should mention in the issue to test both fork options, from applications page and viewer

2021-05-03 18:23 UTC, rishabhsaxena commented on app/client/src/pages/AppViewer/viewer/AppViewerHeader.tsx
> +  const CTA = GetAppViewerHeaderCTA({
Any specific reason for capitalising? I guess by convention, components should be capitalised and not functions

2021-05-03 18:23 UTC, rishabhsaxena commented on app/client/src/pages/Applications/ForkApplicationModal.tsx
> +      trigger={props.trigger ? props.trigger : null}
NIT: `trigger ={props.trigger}` should suffice?

2021-05-03 18:23 UTC, rishabhsaxena commented on app/client/src/pages/Applications/ForkApplicationModal.tsx
> +  }, [isModalOpen]);
I think should remove these lines

2021-05-03 18:23 UTC, rishabhsaxena commented on app/client/src/pages/Applications/ForkApplicationModal.tsx
> +  console.log("user orgs: ", userOrgs);
Should remove/comment out logs

2021-05-03 18:23 UTC, rishabhsaxena commented on app/client/src/pages/Applications/ForkApplicationModal.tsx
> +  trigger?: any;
```suggestion
  trigger?: React.ReactNode;
```

2021-05-03 18:30 UTC, kaushik94 commented on app/client/src/pages/Applications/ForkApplicationModal.tsx
> +  trigger?: any;
on it. 5 minutes please.

2021-05-03 18:37 UTC, kaushik94 commented
@rishabhsaxena I am trying to rename `GetAppViewerHeaderCTA` but it is not reflected in the PR.

2021-05-03 18:40 UTC, rishabhsaxena commented
> @rishabhsaxena I am trying to rename `GetAppViewerHeaderCTA` but it is not reflected in the PR.

Can use `git mv oldName newName` in case we're just changing the case

2021-05-03 18:47 UTC, kaushik94 commented
@rishabhsaxena thanks so much for this. Done. Please check. Thanks.

2021-05-03 18:53 UTC, rishabhsaxena commented on app/client/src/pages/Applications/ForkApplicationModal.tsx
> +  }, [isModalOpen]);
This still needs to be removed? Should use `isOpen = {isModalOpen || showBasedOnURL}`

2021-05-03 18:56 UTC, kaushik94 commented on app/client/src/pages/AppViewer/viewer/AppViewerHeader.tsx
> +  const CTA = GetAppViewerHeaderCTA({
@rishabhsaxena ok I understand now. But I was going by the convention in our codebase, for example `ForkApplicationModal`

2021-05-03 18:56 UTC, rishabhsaxena commented on app/client/src/pages/Applications/ForkApplicationModal.tsx
> +  const showForkModal = isModalOpen;
Should use `isModalOpen` instead of a new var?

2021-05-03 18:59 UTC, rishabhsaxena commented on app/client/src/pages/AppViewer/viewer/AppViewerHeader.tsx
> +  const CTA = GetAppViewerHeaderCTA({
Yeah that's a react functional component, this is a normal function, since we're not using it as
`< GetAppViewerHeaderCTA  />`

2021-05-03 19:02 UTC, kaushik94 commented on app/client/src/pages/Applications/ForkApplicationModal.tsx
> +  const showForkModal = isModalOpen;
done

2021-05-03 19:32 UTC, kaushik94 commented
@rishabhsaxena the test is failing because I have to pass a mocked jest function for dispatch. I am updating the tests.

2021-05-03 19:55 UTC, kaushik94 commented
@rishabhsaxena can you please help with this. I am trying to mock dispatch but it is throwing th following error:
```
  if (state && state.initialState) {
    reduxStore = testStore(state.initialState || {});
  }
  const origDispatch = reduxStore.dispatch;
  reduxStore.dispatch = jest.fn(origDispatch);
```
```
Type 'Mock<AnyAction[], [actions: AnyAction[]]>' is not assignable to type 'Dispatch<ReduxAction<any> | AnyAction> & ((actions: AnyAction[]) => AnyAction[])'.
  Type 'Mock<AnyAction[], [actions: AnyAction[]]>' is not assignable to type 'Dispatch<ReduxAction<any> | AnyAction>'.
    Types of parameters 'actions' and 'action' are incompatible.
      Type 'T' is not assignable to type 'AnyAction[]'.
        Type 'ReduxAction<any> | AnyAction' is not assignable to type 'AnyAction[]'.
          Type 'ReduxAction<any>' is missing the following properties from type 'AnyAction[]': length, pop, push, concat, and 28 more.ts(2322)
```

2021-05-03 21:02 UTC, kaushik94 commented
@rishabhsaxena it is clear now. I just had to retain the rest of `react-redux` as is when mocking.

2021-05-04 05:08 UTC, rishabhsaxena approved these changes

2021-05-04 06:04 UTC, merged