WIP: added delay after typing
appsmithorg/appsmith pull request #4168
Opened 2021-04-26 14:25 UTC by NandanAnantharamu

addd delay after typing a character to avoid falky tests

2021-04-26 14:27 UTC, NandanAnantharamu commented
/ok-to-test sha=870de7e

2021-04-27 13:36 UTC, hetunandu requested changes

2021-04-27 13:36 UTC, hetunandu commented on app/client/cypress/support/commands.js
> +    .type(apiname, { delay: 500 })
The unique name test failed in the last run. I don't think this fix is working

2021-04-28 06:43 UTC, NandanAnantharamu commented
/ok-to-test sha=ac7122e

2021-04-28 10:32 UTC, NandanAnantharamu commented
/ok-to-test sha=a5c7ccd

2021-04-30 07:36 UTC, NandanAnantharamu commented
/ok-to-test sha=f407b3f

2021-04-30 10:49 UTC, NandanAnantharamu commented
/ok-to-test sha=ace9500

2021-05-03 09:49 UTC, NandanAnantharamu commented
/ok-to-test sha=2d0d4ff

2021-05-04 05:05 UTC, NandanAnantharamu commented on app/client/cypress/support/commands.js
> +    .type(apiname, { delay: 500 })
The latest code update is working can you check once

2021-05-28 11:48 UTC, NandanAnantharamu commented
/ok-to-test sha=c080731

2021-05-31 05:29 UTC, NandanAnantharamu commented
/ok-to-test sha=c080731

2021-05-31 07:00 UTC, NandanAnantharamu commented
/ok-to-test sha = 15c8da3

2021-06-01 11:49 UTC, arslanhaiderbuttar commented
@NandanAnantharamu I ran the test cases and I am still having the stale exception on my local. Instead the putting the wait in the command, I have added the 3 seconds delay between CreationOfUniqueAPIcheck() in spec file "API_Unique_name_spec.js". This fixed the issue.

2021-06-01 12:55 UTC, NandanAnantharamu commented
> @NandanAnantharamu I ran the test cases and I am still having the stale exception on my local. Instead the putting the wait in the command, I have added the 3 seconds delay between CreationOfUniqueAPIcheck() in spec file "API_Unique_name_spec.js". This fixed the issue.

The standard is to try not to add hard waits as much as possible, this test is working as is with current changes. Even in CI the test worked, we should check and then add hard waits.

2021-06-02 04:48 UTC, NandanAnantharamu commented
/ok-to-test sha=03323f8

2021-06-02 05:24 UTC, arslanhaiderbuttar approved these changes

2021-06-05 17:44 UTC, NandanAnantharamu commented
/ok-to-test sha=fefe5b1

2021-06-10 09:12 UTC, arslanhaiderbuttar approved these changes

2021-06-10 09:16 UTC, hetunandu approved these changes

2021-06-14 06:20 UTC, arslanhaiderbuttar approved these changes

2021-06-15 08:00 UTC, arslanhaiderbuttar submitted a review, later dismissed

2021-06-15 08:25 UTC, yatinappsmith submitted a review, later dismissed

2021-06-23 13:35 UTC, mohanarpit commented
@NandanAnantharamu Is this PR still valid?

2021-06-23 15:10 UTC, NandanAnantharamu commented
> @NandanAnantharamu Is this PR still valid?

This was to fix a flaky test, right now the test is working without a fix so we haven't pushed this PR. I will check once with the team and then take a call whether to close or push this one.

2021-06-29 10:36 UTC, arslanhaiderbuttar approved these changes

2021-06-29 11:31 UTC, merged