separate js error and validation error
appsmithorg/appsmith pull request #4196
Opened 2021-04-28 11:19 UTC by ApekshaBhosale

## Description
Show js error during evaluation and send error it to debugger

Fixes #822 
> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-04-28 13:42 UTC, hetunandu requested changes
Minor changes

2021-04-28 13:42 UTC, hetunandu commented on app/client/src/components/propertyControls/InputTextControl.tsx
> +          isJsError: jsErrorMessage && jsErrorMessage.length > 0 ? true : false,
```suggestion
          isJsError: jsErrorMessage && jsErrorMessage.length,
```

2021-04-28 13:42 UTC, hetunandu commented on app/client/src/workers/DataTreeEvaluator.ts
> +        if (isWidget(entity)) {
Should happen for actions as well

2021-04-28 13:42 UTC, hetunandu commented on app/client/src/components/propertyControls/InputTextControl.tsx
> +          isJsError: jsErrorMessage && jsErrorMessage.length > 0 ? true : false,
We can also avoid this check here completely and just pass the message. Do this check in the evaluated value popup

2021-04-29 07:42 UTC, ApekshaBhosale commented on app/client/src/workers/DataTreeEvaluator.ts
> +        if (isWidget(entity)) {
Action has taken care in actionssaga @hetunandu i am adding action error to debugger on page load only

2021-05-04 06:51 UTC, rishabhsaxena approved these changes
LGTM

2021-05-04 12:59 UTC, rishabhsaxena submitted a review, later dismissed

2021-05-06 05:29 UTC, rishabhsaxena approved these changes

2021-05-07 05:55 UTC, closed without merging