Allow table data to download as Excel
appsmithorg/appsmith pull request #4199
Opened 2021-04-28 13:11 UTC by vicky-primathon

## Description
Allow table data to download as Excel

Fixes #3822 

## Type of change
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-04-28 15:14 UTC, somangshu requested changes
@vicky-primathon the package you have used `xlxs` is very heavy for the use case we have right now. I suggest we use like [zipcelx](https://github.com/egeriis/zipcelx), which is lightweight and performant.

2021-04-29 09:47 UTC, somangshu submitted a review, later dismissed
Approval for running test

2021-04-29 15:44 UTC, somangshu approved these changes

2021-05-06 11:35 UTC, somangshu commented
Tested on DP

2021-05-06 13:22 UTC, marks0351 commented
@vicky-primathon the excel version seems to have extra empty columns and rows if some table columns are hidden.
<img width="543" alt="Screenshot 2021-05-06 at 6 51 36 PM" src="https://user-images.githubusercontent.com/35134347/117305180-21cac480-ae9c-11eb-8587-114508bfc0b3.png">

2021-05-07 12:13 UTC, marks0351 commented
Just a suggestion, I feel like the download options are disabled coz of the color. make sure u guys run it by UX.
<img width="598" alt="Screenshot 2021-05-07 at 5 42 36 PM" src="https://user-images.githubusercontent.com/35134347/117447828-9e70a800-af5b-11eb-9f20-325f00b7607a.png">

2021-05-07 12:13 UTC, marks0351 approved these changes

2021-05-10 05:27 UTC, somangshu commented
> Just a suggestion, I feel like the download options are disabled coz of the color. make sure u guys run it by UX.
> <img alt="Screenshot 2021-05-07 at 5 42 36 PM" width="598" src="https://user-images.githubusercontent.com/35134347/117447828-9e70a800-af5b-11eb-9f20-325f00b7607a.png">

@momcilo-appsmith can you help us out with this?

2021-05-10 08:59 UTC, somangshu requested changes
@vicky-primathon the developer handoff design is quite different from what you have made as @marks0351 has pointed out. Kindly check the design and specs for more details
![Screenshot 2021-05-10 at 2 27 47 PM](https://user-images.githubusercontent.com/11089579/117633943-1f1de700-b19c-11eb-86ec-dff9580727b5.png)

2021-05-11 01:11 UTC, riodeuno commented on app/client/src/components/designSystems/appsmith/TableComponent/TableAction.tsx
> +        props.selectMenu(!props.selected);
Let's useCallback for this.

2021-05-11 01:16 UTC, riodeuno requested changes
Some comments to remove inline arrow function props.

2021-05-14 08:02 UTC, riodeuno approved these changes

2021-05-18 14:47 UTC, merged