Feature/scaled grid
appsmithorg/appsmith pull request #4219
Opened 2021-04-29 13:50 UTC by marks0351

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.

## Description
> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation 
> and context. List any dependencies that are required for this change.

Fixes # (issue)
> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce. 
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-05-12 06:58 UTC, jsartisan submitted a review, later dismissed

2021-05-12 11:21 UTC, riodeuno requested changes

2021-05-12 11:21 UTC, riodeuno commented on app/client/src/sagas/selectors.tsx
> +  getWidget,
Let's add a toast when we select all `All widgets in this page including modals have been selected`

2021-05-12 11:21 UTC, riodeuno commented on app/client/src/selectors/ui.tsx
>  export const getSelectedWidget = (state: AppState) =>
Let's rename this to .ts

2021-05-12 11:21 UTC, riodeuno commented on app/client/src/utils/hooks/useClickOpenPropPane.tsx
> +      const isMultiSelect = e.metaKey || e.ctrlKey;
Let's see if we can make this very specific when identifying.

2021-05-12 11:21 UTC, riodeuno commented on app/client/src/widgets/ModalWidget.tsx
> +    height: GridDefaults.DEFAULT_GRID_ROW_HEIGHT * 24,
Let's verify this.

2021-05-12 14:20 UTC, jsartisan approved these changes

2021-05-13 05:06 UTC, jsartisan approved these changes

2021-05-13 08:04 UTC, riodeuno submitted a review, later dismissed

2021-05-13 08:33 UTC, marks0351 commented
/ok-to-test sha= 56704fe

2021-05-13 09:41 UTC, marks0351 commented
/ok-to-test sha=f0f279

2021-05-13 09:52 UTC, marks0351 commented
/ok-to-test sha

2021-05-13 09:53 UTC, marks0351 commented
/ok-to-test

2021-05-13 10:03 UTC, marks0351 commented
/ok-to-test sha=f0f2791

2021-05-13 10:12 UTC, jsartisan approved these changes

2021-05-14 07:41 UTC, NandanAnantharamu commented
/ok-to-test sha=597c823

2021-05-14 09:42 UTC, jsartisan approved these changes

2021-05-17 07:07 UTC, jsartisan approved these changes

2021-05-17 13:40 UTC, SatishGandham approved these changes
Approving to run tests.

2021-05-18 09:30 UTC, riodeuno approved these changes

2021-05-18 14:05 UTC, riodeuno submitted a review, later dismissed

2021-05-18 14:23 UTC, riodeuno submitted a review, later dismissed

2021-05-18 14:26 UTC, riodeuno approved these changes

2021-05-18 15:03 UTC, riodeuno approved these changes

2021-05-18 18:29 UTC, merged