query and datasource related tests
appsmithorg/appsmith pull request #423
Opened 2020-08-25 13:37 UTC by NandanAnantharamu

2020-08-26 05:14 UTC, hetunandu commented on app/client/cypress/integration/Smoke_TestSuite/ExplorerTests/Entity_Explorer_CopyQuery_RenameDatasource_spec.js
> +describe("Entity explorer tests related to copy query", function() {
Can we break this up into smaller cases. Such long methods tend to fail often than smaller ones

2020-08-26 05:15 UTC, hetunandu requested changes
Needs refactor

2020-09-02 10:43 UTC, NandanAnantharamu commented
> Needs refactor

This is has been addressed, and the current PR has tests related to table search/ table filter / table compact mode / table view mode tests as well

2020-09-02 13:10 UTC, hetunandu approved these changes

2020-09-02 13:13 UTC, merged