@satbir121 Members and org settings page
appsmithorg/appsmith pull request #424
Opened 2020-08-26 04:27 UTC by satbir121

2020-08-27 08:41 UTC, riodeuno requested changes

2020-08-27 08:41 UTC, riodeuno commented on app/client/src/components/ads/Icon.tsx
> +  onClick?: () => void;
In the future we may need to `stopPropagation` of events so let us make it a point to always include the event parameter to the mouse event handlers

2020-08-27 08:41 UTC, riodeuno commented on app/client/src/components/ads/Icon.tsx
> +      onClick={() => props.onClick && props.onClick()}
Does it make more sense to do a `props.onClick || noop` here?

2020-08-27 08:41 UTC, riodeuno commented on app/client/src/components/ads/TableDropdown.tsx
> +          <DropdownOption
It is possible that React would complain here. does the `DropdownOption` come with a unique `id` property or another unique property (compared to its siblings), if so, let us use that for the `key`?

2020-08-27 08:41 UTC, riodeuno commented on app/client/src/components/ads/TextInput.tsx
> +          key={props.defaultValue}
Is a `key` needed here?

2020-08-28 14:25 UTC, riodeuno requested changes

2020-08-28 14:25 UTC, riodeuno commented on app/client/src/components/ads/TextInput.tsx
> +  const re = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
We have an email validation regex somewhere in the utils. Let us use that, so that if an email is valid in one part of appsmith, it is also valid in other parts, if an email is invalid in one part of the application it is invalid in others as well.

2020-08-28 14:25 UTC, riodeuno commented on app/client/src/pages/organization/General.tsx
> +  console.log({ isFetchingOrg });
missed console.log

2020-08-28 14:25 UTC, riodeuno commented on app/client/src/pages/organization/Members.tsx
> +import { Classes } from "@blueprintjs/core";
If we're using Appsmith Design System, should we refrain from including blueprint in the application?
I mean, can we use a separate ADS component which details with the `Classes.SKELETON` here? I believe we have a `Skeleton` component somewhere in the codebase.

2020-08-28 14:25 UTC, riodeuno commented on app/client/src/reducers/uiReducers/orgReducer.ts
> +      ...state,
We have `immer` as a dependency in appsmith now. So this could be re-written as 

``` 
     return produce(state, draft => {
          draft.loadingStats.isFetching = true;
      })
```

2020-08-28 14:25 UTC, riodeuno commented on app/client/src/reducers/uiReducers/orgReducer.ts
> +    ...state,
Same as above, immer can make this code much cleaner.

2020-08-28 14:28 UTC, riodeuno requested changes

2020-08-28 14:28 UTC, riodeuno commented on app/client/src/components/ads/TextInput.tsx
>            placeholder={props.placeholder ? props.placeholder : ""}
`placeholder` can accept `undefined`, I believe, so we don't need to pass `""` explicitly.
Also, we are spreading `{...props}` above, but also using `props.defaultValue` and `props.placeholder` individually, which may not be needed.

2020-08-28 18:46 UTC, satbir121 commented on app/client/src/pages/organization/Members.tsx
> +import { Classes } from "@blueprintjs/core";
We are already using blueprint extensively in ads.

2020-08-28 18:51 UTC, merged