Memoize CurrentValueViewer to prevent expensive rerenders of react JSON viewer
appsmithorg/appsmith pull request #4240
Opened 2021-04-30 09:43 UTC by SatishGandham

## Description
Memoize CurrentValueViewer to prevent expensive rerenders of react JSON viewer

Fixes #4239 

## Type of change
- UI Performance improvements (non-breaking change which fixes an issue)

## How Has This Been Tested?
Profiling before and after.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

![CleanShot_2021-04-02_at_02 47 282x](https://user-images.githubusercontent.com/441914/116678052-854d8180-a9c6-11eb-8bb4-61133956e4ae.png)
![Screen_Shot_2021-04-02_at_04 26 54](https://user-images.githubusercontent.com/441914/116678060-87afdb80-a9c6-11eb-8068-b87c6ae2eb21.png)

2021-05-03 10:15 UTC, riodeuno requested changes

2021-05-03 10:15 UTC, riodeuno commented on app/client/src/components/editorComponents/CodeEditor/EvaluatedValuePopup.tsx
> +            name: null,
Let's make these a constant or `useMemo` to avoid creating this object everytime.

2021-05-03 10:15 UTC, riodeuno commented on app/client/src/components/editorComponents/CodeEditor/EvaluatedValuePopup.tsx
> +        {"undefined"}
Will it make a difference if we just pass `undefined` as a string instead of wrapping it in `{}`?

2021-05-03 17:11 UTC, SatishGandham commented on app/client/src/components/editorComponents/CodeEditor/EvaluatedValuePopup.tsx
> +            name: null,
We are not actually using the object. We are spreading that in line 221.
Here we are preventing the re-render a step higher

2021-05-03 17:16 UTC, SatishGandham commented on app/client/src/components/editorComponents/CodeEditor/EvaluatedValuePopup.tsx
> +        {"undefined"}
Not sure why undefined string is placed there, but its wrapped in `{}` to satisfy this eslint rule
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-unescaped-entities.md

2021-05-05 10:29 UTC, riodeuno approved these changes

2021-05-05 12:48 UTC, merged