Fix email parsing issue in text widget
appsmithorg/appsmith pull request #4309
Opened 2021-05-05 05:31 UTC by vicky-primathon

## Description
Fix email parsing issue in text widget

Fixes #4101 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
-

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-05-05 09:59 UTC, somangshu submitted a review, later dismissed
Approving for test run

2021-05-07 09:49 UTC, somangshu commented
Tested on deploy preview.

2021-05-11 01:20 UTC, riodeuno requested changes

2021-05-11 01:20 UTC, riodeuno commented on app/client/src/components/designSystems/blueprint/EmailMatcher.tsx
> +function combinePatterns(
Let's add unit tests for this file.

2021-05-11 01:20 UTC, riodeuno commented on app/client/src/components/designSystems/blueprint/TextComponent.tsx
> +    if (text && EMAIL_PATTERN.test(text)) {
What happens when the content has both URL and emails?

2021-05-26 11:21 UTC, riodeuno requested changes

2021-05-26 11:21 UTC, riodeuno commented on app/client/src/components/designSystems/blueprint/TextComponent.tsx
> +import Interweave, { Node } from "interweave";
I don't see the use of `Node` which is imported here.

2021-05-26 11:22 UTC, riodeuno commented on app/client/src/components/designSystems/blueprint/TextComponent.tsx
> +import Interweave, { Node } from "interweave";
Also, the deploy preview failed to build. can we see what went wrong?

2021-06-02 22:06 UTC, riodeuno approved these changes
Looks good to me.

2021-06-04 10:36 UTC, merged