fix: Dropdown option gets overlapped on the ModalComponent
appsmithorg/appsmith pull request #4341
Opened 2021-05-06 07:28 UTC by Tooluloope

## Description
> Dropdown option getting overlapped on the modal. 
By reducing the portal z-index and increasing that of the Modal solved the issue

Fixes #1000 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-05-06 14:03 UTC, marks0351 commented
@Tooluloope looks like when the modal is open, the user cannot get to the entity explorer to add widgets to the modal.
also, u cud try the usePortal option provided by blueprint to fix this problem.

2021-05-09 12:49 UTC, Tooluloope commented
> @Tooluloope looks like when the modal is open, the user cannot get to the entity explorer to add widgets to the modal.
> also, u cud try the usePortal option provided by blueprint to fix this problem.

@marks0351 to get you straight, the modal isn't meant to cover the sidebar(Entity Explorer) when the modal is opened?
<img width="2377" alt="Screenshot 2021-05-09 at 13 48 36" src="https://user-images.githubusercontent.com/31691737/117572954-37054600-b08a-11eb-81db-4528993d7ccf.png">

2021-05-10 05:25 UTC, somangshu commented
> > @Tooluloope looks like when the modal is open, the user cannot get to the entity explorer to add widgets to the modal.
> > also, u cud try the usePortal option provided by blueprint to fix this problem.
> 
> @marks0351 to get you straight, the modal isn't meant to cover the sidebar(Entity Explorer) when the modal is opened?
> <img alt="Screenshot 2021-05-09 at 13 48 36" width="2000" src="https://user-images.githubusercontent.com/31691737/117572954-37054600-b08a-11eb-81db-4528993d7ccf.png">

@Tooluloope that is right! As @marks0351 mentioned, the ability to drag new widgets inside the modal widget viewport is required. If the entity explorer is covered by the modal overlay, this won't be possible.

2021-05-11 10:23 UTC, somangshu requested changes
@Tooluloope this doesn't seem right, The overlay is now only covering half the canvas and also allows scroll. @marks0351 kindly look into this and help up out with the right direction.

Also @Tooluloope we need to link the issue which has additionally been merged here.

2021-05-19 07:57 UTC, marks0351 requested changes

2021-05-19 07:57 UTC, marks0351 commented on app/client/src/components/designSystems/blueprint/DropdownComponent.tsx
> +    if (Boolean(this._menu.current?.closest(".bp3-modal-widget"))) {
Context about other widgets should not be present in the design system. u can add portalContainer as an input prop for this component and set it from the place where dropdown is used(DropdownWidget).

2021-05-19 07:57 UTC, marks0351 commented on app/client/src/components/designSystems/blueprint/ModalComponent.tsx
> +  console.log(props.height, props.width, props.left, props.top);
remove console.log

2021-05-19 07:57 UTC, marks0351 commented on app/client/src/components/designSystems/blueprint/ModalComponent.tsx
> +    <Overlay
I'd suggest not to make changes to the modal. I think the modal portal can still stay at the body level. But the dropdown widget inside a modal should make use of the modal as the portal. let me know if that doesn't make any sense.

2021-05-20 05:04 UTC, Tooluloope commented on app/client/src/components/designSystems/blueprint/ModalComponent.tsx
> +    <Overlay
Moved this to document.body

2021-05-21 09:18 UTC, somangshu submitted a review, later dismissed
LGTM, Tested on Deploy preview as well. 

@marks0351 Kindly review.

2021-05-25 05:32 UTC, marks0351 requested changes

2021-05-25 05:32 UTC, marks0351 commented on app/client/src/index.css
> +  z-index: 2 !important;
@Tooluloope can u pls add these z-index's to the layers as well.

2021-05-26 14:03 UTC, Tooluloope commented on app/client/src/index.css
> +  z-index: 2 !important;
Done

2021-06-01 06:30 UTC, marks0351 approved these changes

2021-06-02 06:57 UTC, somangshu commented
This PR is blocked because of unrelated failing test

2021-06-03 06:24 UTC, somangshu commented
/ok-to-test sha=d794cbb

2021-06-07 07:59 UTC, riodeuno approved these changes

2021-06-07 14:25 UTC, somangshu commented
@Tooluloope related test failing here!

2021-06-08 09:08 UTC, somangshu commented
/ok-to-test sha=b0c7c1c

2021-06-15 05:11 UTC, somangshu commented
@marks0351 need you approval here

2021-06-15 05:22 UTC, marks0351 approved these changes

2021-06-15 07:12 UTC, somangshu commented
@Tooluloope please resolve the merge conflicts 👆

2021-06-15 14:14 UTC, somangshu approved these changes

2021-06-18 05:40 UTC, somangshu commented
@Tooluloope merge required to fix failing tests

2021-06-21 05:28 UTC, somangshu approved these changes
Approving to run tests

2021-06-22 10:07 UTC, merged