Fix: List Widget crashes on null empty object in data
appsmithorg/appsmith pull request #4349
Opened 2021-05-06 13:24 UTC by jsartisan

This PR fixes the crash happening due to an empty data objects passed to the list widget.

Fixes #4346 

- Bugfix

## How Has This Been Tested?
- Manually tested

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-05-07 07:54 UTC, marks0351 submitted a review, later dismissed

2021-05-26 06:15 UTC, marks0351 requested changes

2021-05-26 06:15 UTC, marks0351 commented on app/client/src/utils/hooks/useClickOpenPropPane.tsx
> +  const focusedWidget = getParentToOpenIfAny(focusedWidgetId, widgets);
can we rename focusedWidget to something more relevant?

2021-05-26 06:15 UTC, marks0351 commented on app/client/src/widgets/BaseWidget.tsx
> +        selected={this.props.selected}
is there a way to handle selected based styles within the ListComponent, I am assuming this is the style that we add when a list widget item is clicked?

2021-05-26 06:15 UTC, marks0351 commented on app/client/src/widgets/ListWidget/ListComponent.tsx
> +  border: ${(props) => getBorderCSSShorthand(props.theme.borders[2])};
can we use box-shadow instead of border to help save width?

2021-05-26 13:03 UTC, jsartisan commented on app/client/src/widgets/BaseWidget.tsx
> +        selected={this.props.selected}
@marks0351 No actually. All the styling is done in the individual widgets. ListWidget can only pass/modify props from top.

2021-05-27 04:58 UTC, marks0351 submitted a review, later dismissed

2021-05-27 06:04 UTC, marks0351 approved these changes

2021-05-27 06:41 UTC, merged