fix: set default format in table date type cell
appsmithorg/appsmith pull request #4350
Opened 2021-05-06 14:08 UTC by techbhavin

## Description
> set default format `YYYY-MM-DD HH:mm` in `Orignal Date Format` and `Display Date Format` in table widget cell type **Date**. 
add `No Selection` additional option in date format 

>  In DropDownControl add support for set defaultValue.

Fixes # (#3318)

## Type of change

> Please delete options that are not relevant.

- Bugfix (non-breaking change which fixes an issue)
- Breaking change (fix that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ]  I have commented my code, particularly in hard-to-understand areas
- [ ]  I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ]  I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-05-07 05:23 UTC, somangshu commented
/ok-to-test sha=9b91a09

2021-05-07 10:05 UTC, somangshu commented
Tested and Works on deploy preview.

2021-05-12 13:26 UTC, somangshu commented
@SatishGandham kindly review

2021-05-18 15:19 UTC, SatishGandham approved these changes
Looks good.

@somangshu , What does "No result" mean? Shouldn't that be **no selection** or **please select**

2021-05-19 06:10 UTC, somangshu commented
> @somangshu , What does "No result" mean? Shouldn't that be **no selection** or **please select**

@SatishGandham that makes sense. Can you point out where do you see this? On the deploy preview, I see it as `no selection`

<img width="510" alt="Screenshot 2021-05-19 at 11 40 12 AM" src="https://user-images.githubusercontent.com/11089579/118764364-00ec7100-b897-11eb-83e9-c00d720802b3.png">

2021-05-20 06:37 UTC, somangshu commented on app/client/src/widgets/TableWidget/TablePropertyPaneConfig.ts
> +                  defaultValue: "YYYY-MM-DD HH:mm",
If we are always going to have a default date format, do we really need the `No Selection` option here. 

@riodeuno could you give feedback here?

2021-05-20 08:14 UTC, SatishGandham requested changes

2021-05-20 08:14 UTC, SatishGandham commented on app/client/src/components/propertyControls/DropDownControl.tsx
>        label: "No results.",
Can you change this to "No selection" instead of "No results".

2021-05-20 08:14 UTC, SatishGandham commented on app/client/src/widgets/TableWidget/TablePropertyPaneConfig.ts
> +                    {
Since this value can never be empty, we should not have the `no selection` option

2021-05-20 09:26 UTC, somangshu approved these changes

2021-05-31 12:24 UTC, SatishGandham approved these changes

2021-05-31 14:38 UTC, merged