Select default values on resetting the select dropdown of a form widget
appsmithorg/appsmith pull request #4358
Opened 2021-05-07 05:35 UTC by vicky-primathon

## Description
Select default values on resetting the select dropdown of a form widget

Fixes #4230 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce. 
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-05-10 09:48 UTC, somangshu commented
The bug is resolved on the deploy preview, but another sentry issue is causing a crash here. @jsartisan is working on that


`[Error] Object

error: TypeError: undefined is not an object (evaluating 'e.label')

column: 72039

line: 1

message: "undefined is not an object (evaluating 'e.label')"

sourceURL: "https://deploy-preview-4358--appsmith-editor-ce.netlify.app/static/js/2.2163c9a0.chunk.js"

stack: "https://deploy-preview-4358--appsmith-editor-ce.netlify.app/static/js/2.2163c9a0.chunk.js:1:72039↵map@[native code…"

TypeError Prototype

errorInfo: Object

componentStack: "↵ in Blueprint3.QueryList↵ in Blueprint3.MultiSelect↵ in Styled(Blueprint3.MultiSelect)↵ in div↵ in Blueprint3.ControlGroup…"

Object Prototype

Object Prototype

	componentDidCatch (main.7a0af8b6.chunk.js:1:1280060)

2021-05-10 09:55 UTC, somangshu commented
/ok-to-test sha=a2d539a

2021-05-10 14:06 UTC, somangshu commented
@jsartisan @vicky-primathon every time I enter an integer value in the default value of dropdown the widget crashes and does not reload/rectify until the int value is removed from the default value.

2021-05-10 14:06 UTC, somangshu requested changes
Check the above comment

2021-05-17 06:54 UTC, vicky-primathon commented
- Adding validations for dropdown options to have all values as string or numbers
- When switching select type the default value should be applied
- Default dropdown value to be validated 
- Default dropdown value to accept number as valid options

2021-05-26 22:24 UTC, Tooluloope commented on app/client/src/widgets/DropdownWidget.tsx
> +          const seletedOptionValue = this.selectedOptionValue !== undefined ? this.selectedOptionValue : this.defaultOptionValue;
There's a typo here `selectedOptionValue`

2021-06-02 10:42 UTC, vivekverma2312 commented
@vicky-primathon Tested and working fine.

2021-06-02 22:14 UTC, riodeuno approved these changes
@somangshu @vivekverma2312 please verify this in the deploy preview, the code looks fine.

2021-06-02 22:16 UTC, riodeuno commented on app/client/src/widgets/DropdownWidget.tsx
> +      selectedOption: `{{(() => {
Since it has come to such a complicated state, let's extract this like we did in the table widget. This will allow us to add unit tests for each of these functions.

2021-06-03 08:26 UTC, vicky-primathon commented
/ok-to-test sha=25e8408

2021-06-04 05:16 UTC, somangshu submitted a review, later dismissed
Approving to run tests!

2021-06-04 11:22 UTC, somangshu commented
@vicky-primathon please check the related tests failing!

2021-06-04 11:46 UTC, vicky-primathon commented
/ok-to-test sha=6b20455

2021-06-05 08:43 UTC, vicky-primathon commented
/ok-to-test sha=6b20455

2021-06-08 11:53 UTC, somangshu commented
@vicky-primathon there is a merge conflict. Please clear this out

2021-06-08 12:30 UTC, somangshu approved these changes

2021-06-11 07:16 UTC, somangshu commented
Closing this in favour of separating mutiselect widget from the select widget

2021-06-11 07:16 UTC, closed without merging