show pre-filled values for autocomplete
appsmithorg/appsmith pull request #4400
Opened 2021-05-10 08:37 UTC by ApekshaBhosale

## Description
Autocomplete needs to show the next list even when the user hasn't type a '.'

Fixes #1844 

## Type of change
- New feature (non-breaking change which adds functionality)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: invisble-dot 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 51.6 **(-0.01)** | 32.51 **(0.08)** | 29.83 **(0.01)** | 52.09 **(0)**
 :green_circle: | app/client/src/components/editorComponents/CodeEditor/index.tsx | 73.68 **(0.14)** | 53.98 **(0.83)** | 56.67 **(0)** | 73.74 **(0.14)**
 :green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 44.78 **(0.3)** | 30 **(3.26)** | 31.48 **(-1.17)** | 49.84 **(0.37)**
 :red_circle: | app/client/src/utils/autocomplete/dataTreeTypeDefCreator.ts | 62.37 **(-18.58)** | 67.86 **(8.77)** | 100 **(0)** | 69.7 **(-10.79)**</details>

2021-05-21 12:03 UTC, hetunandu commented
The styling needs to be better. Long result names are very close to the data type on the left
<img width="349" alt="Screenshot 2021-05-21 at 5 32 46 PM" src="https://user-images.githubusercontent.com/12022471/119134282-92581080-ba5a-11eb-8cc8-5b72057b3ab4.png">

2021-05-21 12:14 UTC, hetunandu requested changes
Minor refactors and tests needed. Also improve styling

2021-05-21 12:14 UTC, hetunandu commented on app/client/src/utils/autocomplete/TernServer.ts
> +    expected?: string,
Can we pass this in the showHint function instead?

2021-05-21 12:14 UTC, hetunandu commented on app/client/src/utils/autocomplete/TernServer.ts
> +    expected?: string,
We eventually want to have just one Tern Server instance instead of new ones for every input

2021-05-21 12:14 UTC, hetunandu commented on app/client/src/utils/autocomplete/dataTreeTypeDefCreator.ts
> +            const data = definition(entity);
Update tests for these changes

2021-05-21 12:53 UTC, ApekshaBhosale commented on app/client/src/utils/autocomplete/TernServer.ts
> +    expected?: string,
yes makes sense. i will add it there

2021-05-21 13:44 UTC, ApekshaBhosale commented on app/client/src/utils/autocomplete/dataTreeTypeDefCreator.ts
> +            const data = definition(entity);
yeah was waiting on go for logic. will add these now

2021-05-24 09:22 UTC, ApekshaBhosale commented
/ok-to-test sha=590b463

2021-05-25 15:18 UTC, hetunandu approved these changes

2021-05-26 07:56 UTC, ApekshaBhosale commented
/ok-to-test sha=d4da16c

2021-05-27 10:01 UTC, merged