fix: update JS optiuons
appsmithorg/appsmith pull request #4475
Opened 2021-05-14 03:04 UTC by Tooluloope

## Description
> Update JS options for widgets

Fixes #2907 

## Type of change

- Update (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>
No changes to code coverage between the base branch and the head branch</details>

2021-05-17 14:58 UTC, somangshu commented
@vivekverma2312 kindly test this deploy preview

2021-05-17 15:00 UTC, somangshu commented
/ok-to-test sha=196e8ff

2021-05-18 09:45 UTC, riodeuno commented on app/client/src/widgets/DropdownWidget.tsx
> +            isJSConvertible: true,
I believe we can already add bindings here so  `isJSconvertible` may not be needed. Same goes for `Default Option`. Sorry, I did not take into account the fact the `input_text` control type by default supports bindings. Please make changes accordingly. Whenever, we see `isBindProperty` as `true`, it usually means that we don't need to add `isJSConvertible` as it would either already be added or may not be needed.

2021-05-18 09:46 UTC, riodeuno commented on app/client/src/widgets/TextWidget.tsx
>              isBindProperty: false,
Here when we added `isJSConvertible` to `true`, `isBindProperty` should also become `true`, as we should now be able to add bindings to this property.

2021-05-18 09:46 UTC, riodeuno commented on app/client/src/widgets/TextWidget.tsx
> +            isJSConvertible: true,
Here when we added isJSConvertible to true, isBindProperty should also become true, as we should now be able to add bindings to this property.

2021-05-18 09:47 UTC, riodeuno requested changes
Please update the properties based on the comments.

2021-05-18 17:37 UTC, Tooluloope commented on app/client/src/widgets/DropdownWidget.tsx
> +            isJSConvertible: true,
Noted 👍

2021-06-02 22:09 UTC, riodeuno approved these changes
Looks good to me!

2021-06-07 07:54 UTC, riodeuno approved these changes

2021-06-07 12:47 UTC, somangshu commented
@Tooluloope please checkout the failing tests

2021-06-08 07:02 UTC, somangshu submitted a review, later dismissed
Approving to run tests

2021-06-08 11:56 UTC, somangshu commented
@Tooluloope please check the failing test!

2021-06-08 13:37 UTC, Tooluloope commented
> @Tooluloope please check the failing test!

Passes Locally and its unrelated
<img width="568" alt="Screenshot 2021-06-08 at 14 34 56" src="https://user-images.githubusercontent.com/31691737/121194670-cfc2e900-c823-11eb-9ce9-b6f709433ed4.png">

2021-06-14 05:30 UTC, somangshu commented
@yatinappsmith @NandanAnantharamu need you to respond here, Why are these tests failing?

2021-06-14 06:02 UTC, NandanAnantharamu commented
> @yatinappsmith @NandanAnantharamu need you to respond here, Why are these tests failing?

@Tooluloope can pull the latest release and check if it's still failing

2021-06-14 06:36 UTC, riodeuno approved these changes

2021-06-18 05:42 UTC, somangshu commented
@Tooluloope latest release merge required for failing tests

2021-06-23 13:30 UTC, mohanarpit commented
/ok-to-test sha=eb26730

2021-06-28 14:10 UTC, somangshu commented
Re-running jobs dont work, all tests failing. @Tooluloope merge the latest release once again. I dont see this failing anywhere else

2021-06-28 19:46 UTC, mohanarpit submitted a review, later dismissed

2021-06-28 19:48 UTC, mohanarpit commented
The earlier failures seen were related to Netlify. I've merged the latest release & re-ran the build on Netlify as well.

2021-06-28 20:13 UTC, mohanarpit commented
@Tooluloope @somangshu All the tests are passing now. Please merge this if all looks good to you.

2021-06-29 07:31 UTC, Tooluloope commented
> @Tooluloope @somangshu All the tests are passing now. Please merge this if all looks good to you.

Thanks @mohanarpit

2021-07-06 09:49 UTC, YogeshJayaseelan commented
@Tooluloope Verified this feature and Js option is available for all the above mentioned widgets except 'Container' and 'Form' - Background colour

<img width="1280" alt="Screenshot 2021-07-06 at 3 14 28 PM" src="https://user-images.githubusercontent.com/35128442/124580149-7a531980-de6d-11eb-96c5-cbe747844d15.png">

2021-07-08 10:40 UTC, Tooluloope commented
> @Tooluloope Verified this feature and Js option is available for all the above mentioned widgets except 'Container' and 'Form' - Background colour
> 
> <img alt="Screenshot 2021-07-06 at 3 14 28 PM" width="1280" src="https://user-images.githubusercontent.com/35128442/124580149-7a531980-de6d-11eb-96c5-cbe747844d15.png">

@YogeshJayaseelan Fixed the issue

2021-07-12 13:28 UTC, somangshu approved these changes

2021-07-14 06:49 UTC, somangshu commented
Rerunning all jobs, tests are failing

2021-07-16 12:29 UTC, merged