r.match on API pane error
appsmithorg/appsmith pull request #4497
Opened 2021-05-16 08:28 UTC by ApekshaBhosale

## Description
r.match is not a function

Reason - when adding/updating API url which doesn't have datasource, 'value'(shown in sentry) is an Object but when updating/adding url which has datasource 'value' is a string. 

Fixes #4496 4496

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-05-16 08:31 UTC, hetunandu requested changes

2021-05-16 08:31 UTC, hetunandu commented on app/client/src/sagas/ApiPaneSagas.ts
> +import cloneDeep from "lodash/cloneDeep";
Can all be imported from 'lodash'

2021-05-16 08:31 UTC, hetunandu commented on app/client/src/sagas/ApiPaneSagas.ts
> +  if (isObject(value)) {
I don't think this check is needed because lodash.get will handle undefined

2021-05-16 08:31 UTC, hetunandu commented on app/client/src/sagas/ApiPaneSagas.ts
> +    value = get(value, "datasourceConfiguration.url") || "";
The third argument of get is the default return value. Use that instead of `||`

2021-05-16 09:24 UTC, ApekshaBhosale commented on app/client/src/sagas/ApiPaneSagas.ts
> +import cloneDeep from "lodash/cloneDeep";
we can but size is a lot so did this.

2021-05-16 09:25 UTC, ApekshaBhosale commented on app/client/src/sagas/ApiPaneSagas.ts
> +  if (isObject(value)) {
we need this because we don't do this only when payload is object else it send just string i.e. path

2021-05-16 10:18 UTC, hetunandu commented on app/client/src/sagas/ApiPaneSagas.ts
> +import cloneDeep from "lodash/cloneDeep";
import { a, b, c } from 'lodash' has the same effect

2021-05-16 10:26 UTC, ApekshaBhosale commented
/ok-to-test sha=3aedc8d

2021-05-17 01:45 UTC, arunvjn approved these changes

2021-05-17 06:28 UTC, ApekshaBhosale commented on app/client/src/sagas/ApiPaneSagas.ts
> +import cloneDeep from "lodash/cloneDeep";
no this was it is less size overall

2021-05-17 06:29 UTC, hetunandu approved these changes

2021-05-17 07:21 UTC, merged