Feature/2111 toggle header options
appsmithorg/appsmith pull request #4580
Opened 2021-05-19 11:08 UTC by wmdev0808

## Description
- Add the header options section for the visibility on the property pane
- Render conditionally the header part based on the setting

Fixes #2111 

## Type of change

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

## How Has This Been Tested?

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-05-19 14:31 UTC, somangshu commented
The feature works now. But there is an issue with old tables. There are too many extra rows. This doesn't happen for the new table widgets dropped on the canvas. @riodeuno Don't know if some kinda migration is required here.

@vivekverma2312 can we test this Deploy preview thoroughly.

2021-05-19 14:38 UTC, somangshu commented
/ok-to-test sha=c1557c1

2021-05-20 05:59 UTC, vivekverma2312 commented
sure @somangshu I will start testing this now.

2021-05-20 08:57 UTC, vivekverma2312 commented
@somangshu Issues observed so far:
1. By default Header is showing disabled for old tables
2. Extra rows are coming in the table for the below cases:
  -Existing table in the preview
  -If I create a table on release env and check on preview
3. First row height changes when all the header property is in disabled state

Screenshots for Issue 3:
<img width="1619" alt="Screenshot 2021-05-20 at 2 17 47 PM" src="https://user-images.githubusercontent.com/83569920/118949895-4c764c00-b977-11eb-8a27-40d61d486954.png">
<img width="1610" alt="Screenshot 2021-05-20 at 2 16 31 PM" src="https://user-images.githubusercontent.com/83569920/118949945-57c97780-b977-11eb-9c10-911b32cb185a.png">

2021-05-21 11:08 UTC, somangshu commented
> 1. By default Header is showing disabled for old tables

@riodeuno will need some help here. How do we migrate the old table for this case?

2021-05-27 08:25 UTC, SatishGandham requested changes
Looks good except for the small change requested.

2021-05-27 08:25 UTC, SatishGandham commented on app/client/src/components/designSystems/appsmith/TableComponent/Table.tsx
> +      {(props.isVisibleSearch ||
Can we use isHeaderVisible here?

2021-06-03 07:51 UTC, wmdev0808 commented on app/client/src/components/designSystems/appsmith/TableComponent/Table.tsx
> +      {(props.isVisibleSearch ||
I've made a new PR for your comment

2021-06-03 18:02 UTC, somangshu submitted a review, later dismissed
Approve to run test

2021-06-04 11:25 UTC, somangshu commented
@wmdev0808 some related tests are failing here! Can you check

2021-06-04 14:46 UTC, wmdev0808 commented
> @wmdev0808 some related tests are failing here! Can you check

Hi @somangshu, I've reviewed, but I don't think it is directly related to the current PR.
I can see a few failing cypress tests, but I can't get the point

2021-06-07 05:41 UTC, somangshu commented
@wmdev0808 some test fails here because the tests cannot find the table header. [Check this out](https://dashboard.cypress.io/projects/eyxvp8/runs/6555/overview). 

@vicky-primathon can you take a look?

2021-06-07 05:55 UTC, vicky-primathon commented
Sure @somangshu looking into it

2021-06-07 06:32 UTC, SatishGandham submitted a review, later dismissed

2021-06-07 06:35 UTC, vicky-primathon commented
@wmdev0808  @somangshu  we are hiding table header section by default, this is causing table test cases to fail. Can we enable the table header toggles by default

2021-06-07 14:38 UTC, somangshu commented
@vicky-primathon this needs migration I believe. For an old table widget, the header options are hidden by default.

Please help @wmdev0808 with this!

2021-06-08 06:29 UTC, vicky-primathon commented
Okay @somangshu

2021-06-09 10:34 UTC, vicky-primathon approved these changes
Looks good to me

2021-06-10 09:02 UTC, vivekverma2312 commented
Tested Deploy Preview and working fine. Good to merge into release.

2021-06-11 07:00 UTC, somangshu commented
@yatinappsmith @NandanAnantharamu tests failing here! `ForkApplication_spec.js` is not related. The last release merge was two days ago.

2021-06-14 05:37 UTC, somangshu approved these changes

2021-06-15 05:56 UTC, merged