Feature/datasource list in api editor
appsmithorg/appsmith pull request #4587
Opened 2021-05-20 05:30 UTC by arunvjn

## Description
API pane improvements

- Showing a list of datasources to allow users to navigate to it and make changes
- Enhance datasource autocomplete in API pane 

Fixes #4567 

## Type of change
- New feature (non-breaking change which adds functionality)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-05-20 08:27 UTC, hetunandu commented
Deleting a rest datasource takes me to query datasource screen

![recording](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiZTVmZjliMzYtMjgzZS00MTU5LWE2ZjUtMTZiMjQyODA0M2E4IiwiZGVwbG95X2lkIjoiNjBhNjA3YjA4ZGZlZGEwMDA3ZjkyMGFiIiwiaWQiOiIwNTViNjE4YS1jOGRlLTQ4MzMtYTlkOC1lYWY4ZDUwNmRhYmIifQ==)


<details><summary>Browser metadata</summary>





```
Path:      /applications/6034d9f5438ec90ecf230a5c/pages/6034d9f5438ec90ecf230a5e/edit/api/6034da0c438ec90ecf230a5f
Browser:   Chrome 90.0.4430.212 on Mac OS 10.15.7
Viewport:  1680 x 939 @2x
Language:  en-GB
Cookies:   Enabled
```

[View on BrowserStack](https://live.browserstack.com/dashboard#url=https%3A%2F%2Fdeploy-preview-4587--appsmith-editor-ce.netlify.app%2Fapplications%2F6034d9f5438ec90ecf230a5c%2Fpages%2F6034d9f5438ec90ecf230a5e%2Fedit%2Fapi%2F6034da0c438ec90ecf230a5f&os=OS+X&os_version=Catalina&browser=Chrome&browser_version=90.0&resolution=1680x939&speed=1&start=true)



</details>

[Open Deploy Preview](https://deploy-preview-4587--appsmith-editor-ce.netlify.app/applications/6034d9f5438ec90ecf230a5c/pages/6034d9f5438ec90ecf230a5e/edit/api/6034da0c438ec90ecf230a5f) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=60a607b08dfeda0007f920ab&commentID=60a61d5490bb9ce1e5e2d2e0&resolution=resolved)

2021-05-20 08:28 UTC, hetunandu commented
Clicking on the datasource does not apply it on the api instead navigates me to that datasource

![recording](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiZTVmZjliMzYtMjgzZS00MTU5LWE2ZjUtMTZiMjQyODA0M2E4IiwiZGVwbG95X2lkIjoiNjBhNjA3YjA4ZGZlZGEwMDA3ZjkyMGFiIiwiaWQiOiJlMmU1ODMyMy0zNzA2LTQ2Y2ItOTBkZi0zYzdhM2FkMWM1YmYifQ==)


<details><summary>Browser metadata</summary>





```
Path:      /applications/6034d9f5438ec90ecf230a5c/pages/6034d9f5438ec90ecf230a5e/edit/queries?importTo=6034d9f5438ec90ecf230a5e
Browser:   Chrome 90.0.4430.212 on Mac OS 10.15.7
Viewport:  1680 x 939 @2x
Language:  en-GB
Cookies:   Enabled
```

[View on BrowserStack](https://live.browserstack.com/dashboard#url=https%3A%2F%2Fdeploy-preview-4587--appsmith-editor-ce.netlify.app%2Fapplications%2F6034d9f5438ec90ecf230a5c%2Fpages%2F6034d9f5438ec90ecf230a5e%2Fedit%2Fqueries%3FimportTo%3D6034d9f5438ec90ecf230a5e&os=OS+X&os_version=Catalina&browser=Chrome&browser_version=90.0&resolution=1680x939&speed=1&start=true)



</details>

[Open Deploy Preview](https://deploy-preview-4587--appsmith-editor-ce.netlify.app/applications/6034d9f5438ec90ecf230a5c/pages/6034d9f5438ec90ecf230a5e/edit/queries?importTo=6034d9f5438ec90ecf230a5e) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=60a607b08dfeda0007f920ab&commentID=60a61dc24e1e4e0301ecafca&resolution=resolved)

2021-05-20 11:23 UTC, arunvjn commented
> Clicking on the datasource does not apply it on the api instead navigates me to that datasource
> 
> ![recording](https://camo.githubusercontent.com/908ee799259778937f86abafa7630e650a309c543161a1c20cdf44dc8abd179f/68747470733a2f2f6e65746c6966792d636f636f6f6e2e6e65746c6966792e6170702f2e6e65746c6966792f66756e6374696f6e732f66657463683f636f64653d33303726706174683d65794a7a6158526c58326c6b496a6f695a54566d5a6a6c694d7a59744d6a677a5a5330304d5455354c5745325a6a55744d545a694d6a51794f4441304d324534496977695a4756776247393558326c6b496a6f694e6a42684e6a4133596a41345a475a6c5a4745774d4441335a6a6b794d47466949697769615751694f694a6c4d6d55314f444d794d79307a4e7a41324c545132593249744f54426b5a69307a597a64684d32466b4d574d31596d596966513d3d)
> 
> Browser metadata
> [Open Deploy Preview](https://deploy-preview-4587--appsmith-editor-ce.netlify.app/applications/6034d9f5438ec90ecf230a5c/pages/6034d9f5438ec90ecf230a5e/edit/queries?importTo=6034d9f5438ec90ecf230a5e) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=60a607b08dfeda0007f920ab&commentID=60a61dc24e1e4e0301ecafca&resolution=resolved)

This is the expected behaviour. The users will now be able to see a list of datasource without having to use them.
This would also let them delete datasource.

2021-05-21 12:29 UTC, hetunandu requested changes
Needs refactor

2021-05-21 12:29 UTC, hetunandu commented on app/client/src/pages/Editor/APIEditor/Form.tsx
> +      {hintMessages && (
This component is getting too huge. Lets split it up into smaller components

2021-05-21 12:29 UTC, hetunandu commented on app/client/src/pages/Editor/DataSourceEditor/RestAPIDatasourceForm.tsx
> +        <BackButton onClick={history.goBack} />
If I come here after deleting a datasource, clicking back will take me to the deleted datasource?

2021-05-24 08:37 UTC, arunvjn commented on app/client/src/pages/Editor/DataSourceEditor/RestAPIDatasourceForm.tsx
> +        <BackButton onClick={history.goBack} />
This is the back button you see datasource form page. Clicking the back button will take you back to which ever screen you were on. The use case of taking the user back to the previous page on datasource delete is not handled here. @hetunandu

2021-05-24 10:56 UTC, arunvjn commented on app/client/src/pages/Editor/APIEditor/Form.tsx
> +      {hintMessages && (
Separated out imported headers from headers component.

2021-05-25 05:16 UTC, arunvjn commented
> Deleting a rest datasource takes me to query datasource screen
> 
> ![recording](https://camo.githubusercontent.com/35bf971ef86f359c816a3a94ea1405e875e037aeba2b53c82d60bd660486c6cf/68747470733a2f2f6e65746c6966792d636f636f6f6e2e6e65746c6966792e6170702f2e6e65746c6966792f66756e6374696f6e732f66657463683f636f64653d33303726706174683d65794a7a6158526c58326c6b496a6f695a54566d5a6a6c694d7a59744d6a677a5a5330304d5455354c5745325a6a55744d545a694d6a51794f4441304d324534496977695a4756776247393558326c6b496a6f694e6a42684e6a4133596a41345a475a6c5a4745774d4441335a6a6b794d47466949697769615751694f6949774e5456694e6a45345953316a4f47526c4c5451344d7a4d7459546c6b4f43316c595759345a4455774e6d5268596d496966513d3d)
> 
> Browser metadata
> [Open Deploy Preview](https://deploy-preview-4587--appsmith-editor-ce.netlify.app/applications/6034d9f5438ec90ecf230a5c/pages/6034d9f5438ec90ecf230a5e/edit/api/6034da0c438ec90ecf230a5f) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=60a607b08dfeda0007f920ab&commentID=60a61d5490bb9ce1e5e2d2e0&resolution=resolved)

I haven't modified this behaviour. Shall we take this up in a separate issue ?

2021-05-26 11:19 UTC, hetunandu approved these changes

2021-05-27 03:05 UTC, merged