pull request template updated for title standardization
appsmithorg/appsmith pull request #4597
Opened 2021-05-20 10:13 UTC by somangshu

## Description
Suggestion - The PR title can be standardized to include the issue id and type to get a better context of the PR

Fixes # (issue)

> not yet created

## Type of change

- New feature

## How Has This Been Tested?

- None required - making template changes

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-05-20 10:13 UTC, somangshu commented
Will this work?

2021-05-21 12:25 UTC, hetunandu requested changes

2021-05-21 12:25 UTC, hetunandu commented on .github/pull_request_template.md
> +title: "[FIX/FEATURE - ID]"
Let's not add the issue id in the PR title itself

2021-05-21 13:25 UTC, somangshu commented on .github/pull_request_template.md
> +title: "[FIX/FEATURE - ID]"
Any particular reason? 
I thought it becomes a quick reference point to the original issue and hence added it!

2021-05-24 06:48 UTC, hetunandu commented on .github/pull_request_template.md
> +title: "[FIX/FEATURE - ID]"
I personally feel that these numbers get very hard to track, especially for external users. Using a more descriptive title is more useful for everyone as you can get a better idea of the change in the PR. We have the ability to tag/link the issue(s) in the PR description so that should be preferred

2021-05-25 10:17 UTC, hetunandu approved these changes

2021-05-25 11:21 UTC, somangshu commented
/ok-to-test sha=45cda3b

2021-06-08 13:53 UTC, merged