[Fixed #4520] - Remove Entity Explorer Search
appsmithorg/appsmith pull request #4600
Opened 2021-05-20 12:24 UTC by pskanade

## Description
Hiding the entity explorer search bar

Fixes # (issue)
#4520
This PR makes #4370 irrelevant

## Type of change

> Please delete options that are not relevant.
- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

## How Has This Been Tested?
Updated the testcases to support hidden search bar

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-05-20 13:36 UTC, rishabhsaxena submitted a review, later dismissed

2021-05-20 22:52 UTC, areyabhishek commented
@pskanade is this your first PR 😀

could you fix an associated issue? Today CMD+F searches through the entity explorer. Since there's no search bar in the entity explorer, CMD+F doesn't work anymore. Could you remove the keyboard shortcut so that CMD+F can start working again.

2021-05-21 03:57 UTC, pskanade commented
@areyabhishek this is second.

Okay will remove the `cmd+f` binding.

2021-05-24 15:33 UTC, rishabhsaxena approved these changes

2021-05-24 15:33 UTC, rishabhsaxena commented on app/client/src/pages/Editor/GlobalHotKeys.tsx
>              e.stopPropagation();
Minor change here: so `cmd+f` works when the widget search does not exist

```suggestion
            if (widgetSearchInput) {
              widgetSearchInput.focus();
              e.preventDefault();
              e.stopPropagation();
            }
```

2021-05-27 14:21 UTC, rishabhsaxena submitted a review, later dismissed

2021-06-03 10:01 UTC, somangshu commented
Hey Please close #4370 when this PR is merged

2021-06-04 05:46 UTC, pranavkanade commented
/ok-to-test sha=64bbcd3

2021-06-04 09:41 UTC, pranavkanade commented
/ok-to-test sha=64bbcd3

2021-06-04 10:47 UTC, nayan-rafiq approved these changes
LGTM. Please check the comment. I'm not sure about it.

2021-06-04 10:47 UTC, nayan-rafiq commented on app/client/src/pages/Editor/Explorer/EntityExplorer.tsx
> +      <Search clear={clearSearch} isHidden ref={searchInputRef} />
Not sure about this, but shouldn't it be `isHidden={isHidden}` or something like that?

2021-06-05 06:25 UTC, pranavkanade commented
/ok-to-test sha=64bbcd3

2021-06-07 05:22 UTC, rishabhsaxena requested changes

2021-06-07 05:22 UTC, rishabhsaxena commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/Table_spec.js
> -  it("Table Widget Functionality To Search The Data", function() {
It looks like it's invoking the entity explorer search instead of the table search, think we should update the selector to use the table search here

2021-06-08 05:49 UTC, pranavkanade commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/Table_spec.js
> -  it("Table Widget Functionality To Search The Data", function() {
yes, I noticed that. Though, I thought user could search the data from entity search as well (And it works too). Fixing it

2021-06-09 08:34 UTC, rishabhsaxena approved these changes

2021-06-09 12:19 UTC, pranavkanade commented
@rishabhsaxena all test cases passed except `ExecutionParams_spec.js` which timed out - https://dashboard.cypress.io/projects/eyxvp8/runs/6706/specs. As per internal discussions we can ignore it. I'm merging this PR.

2021-06-09 12:20 UTC, merged

2021-06-09 12:20 UTC, pranavkanade commented
@RakshaKShetty you can take this up for QA.