[Issue #4572]-Added API to leave organisation by any user
appsmithorg/appsmith pull request #4634
Opened 2021-05-22 18:25 UTC by nayan-appsmith

## Description
Currently, an admin user can not remove himself from an organization. He can only remove other members. After this change, admin users will be able to remove themselves also if there is minimum one admin.

Also added an API so that any user can leave an organization no matter what role he has. Currently only admin users can access the members page and hence can leave an organization.

Fixes # (issue)
Issue #4572 

## Type of change
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
- Unit tests
- Tested on local machine

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-05-27 09:14 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/UserController.java
> +    @DeleteMapping("/organization/{orgId}")
We are currently using the `@DeleteMapping` only for delete/archive operations right? So this feels a little inconsistent. This feels like a _change_ to the organization, and the organization itself doesn't disappear for everyone. I feel a `PUT` request with an endpoint like `/leaveOrganization/{orgId}` is more consistent, and is very similar to the method just above, which defines `PUT /addOrganization/{orgId}`.

2021-05-27 13:08 UTC, pskanade requested changes

2021-05-27 13:08 UTC, pskanade commented on app/client/src/pages/Applications/index.tsx
> +                      />
For consistency `OrgName` should be shown to all users. And it should be editable only for user with `hasManageOrgPermissions: true`

2021-05-28 01:05 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/UserOrganizationServiceImpl.java
> +                            .removeOrgFromRecentlyUsedList(user.getId(), organization.getId())::thenReturn)
Minor refactoring to read this better.

```suggestion
                    finalUpdatedOrganizationMono = userDataRepository
                            .removeOrgFromRecentlyUsedList(user.getId(), organization.getId())
                            .then(userRemovedOrganizationMono)
```

2021-05-28 01:06 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/UserOrganizationServiceImpl.java
> +                                    return Mono.just(user).thenReturn(organization1);
```suggestion
                                    return Mono.just(organization1);
```

2021-05-28 01:17 UTC, sharat87 commented
@nayan-rafiq, looks good. Just a few minor things and then we should be able to merge this in. Thanks!

2021-05-30 09:55 UTC, nayan-rafiq commented on app/client/src/pages/Applications/index.tsx
> +                      />
The user has just clicked on the org name and a popup is shown. Showing the orgname again as first option in the popup without the edit button will be confusing IMO.

2021-05-30 16:46 UTC, nayan-rafiq commented on app/client/src/constants/ReduxActionConstants.tsx
> +  DELETE_ORG_USER_ERROR: "DELETE_ORG_USER_ERROR",
Got it.

2021-05-30 17:23 UTC, nayan-rafiq commented on app/client/src/pages/Applications/index.tsx
> +                  {hasManageOrgPermissions && (
Added cypress test for the feature

2021-05-30 17:26 UTC, nayan-rafiq commented
> @nayan-rafiq, looks good. Just a few minor things and then we should be able to merge this in. Thanks!

@sharat87 I've applied the requested changes. Would you please have a look again?

2021-05-31 06:58 UTC, pranavkanade approved these changes
FE LGTM! Approving for tests

2021-05-31 07:26 UTC, sharat87 approved these changes

2021-06-02 09:56 UTC, merged