[ISSUE#4524]Fix: Added a check in else block too and assigned default…
appsmithorg/appsmith pull request #4641
Opened 2021-05-24 07:06 UTC by vibhandikyash

… config

## Description
Toggling dynamic property field to a normal field was not resetting the value to a boolean.

Fixes #4524 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
> Tested on local machine.
> Can be easily reproduced as shown in the video

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-05-25 11:28 UTC, somangshu approved these changes
LGTM

2021-05-25 11:34 UTC, hetunandu requested changes

2021-05-25 11:34 UTC, hetunandu commented on app/client/src/sagas/WidgetOperationSagas.tsx
> +      propertyValue = defaultConfig[propertyPath];
This will reset the value to the default value of a widget but that seems like an incorrect solution. Instead, we should improve the validation function of BOOLEAN type to make sure it always returns a true or false. You can find that function [here](https://github.com/appsmithorg/appsmith/blob/release/app/client/src/workers/validations.ts#L142-L163)

2021-05-26 12:25 UTC, hetunandu approved these changes

2021-06-08 12:26 UTC, merged