fix: filterable default value
appsmithorg/appsmith pull request #4657
Opened 2021-05-24 14:52 UTC by Tooluloope

## Description
> fix filter default value for Select widget

Fixes #4612  

## Type of change

- Update (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>
No changes to code coverage between the base branch and the head branch</details>

2021-05-25 11:06 UTC, somangshu commented
I still don't see it fixed on the Deploy preview 

![Screenshot 2021-05-25 at 4 35 44 PM](https://user-images.githubusercontent.com/11089579/119487737-5fbe5880-bd77-11eb-9f64-6495521d230a.png)

This probably requires a migration.

2021-05-26 20:53 UTC, Tooluloope commented
> This probably requires a migration.

@somangshu added migrations.
Do confirm if it's optimal

2021-05-27 06:06 UTC, somangshu submitted a review, later dismissed
Approving to run tests, Works on deploy preview

2021-05-27 06:31 UTC, riodeuno commented on app/client/src/utils/WidgetPropsUtils.tsx
> +    currentDSL.version = 21;
Let's update the LATEST_PAGE_VERSION here by updating the value of LATEST_PAGE_VERSION.
@marks0351 Please advice on how this is to be done.

2021-05-27 06:32 UTC, riodeuno requested changes
One comment, the rest looks good.

2021-05-27 07:11 UTC, marks0351 requested changes

2021-05-27 07:11 UTC, marks0351 commented on app/client/src/utils/WidgetPropsUtils.tsx
> +    currentDSL.version = 21;
@Tooluloope can u pls increment LATEST_PAGE_VERSION to 21. the idea is to have a constant that holds the latest page version.

2021-05-27 07:23 UTC, somangshu approved these changes

2021-06-02 22:10 UTC, riodeuno approved these changes
Approving for tests to run.

2021-06-03 05:47 UTC, somangshu commented
@riodeuno is the code looks fine, Kindly let me know. We need to push this into the release as the feature has already gone to prod a couple weeks ago

2021-06-07 09:19 UTC, somangshu approved these changes
Approving to run tests

2021-06-08 05:41 UTC, marks0351 commented on app/client/src/utils/WidgetPropsUtils.tsx
> +  if (currentDSL.version === 24) {
Thanks for cleaning this up @Tooluloope .

2021-06-08 05:41 UTC, marks0351 approved these changes

2021-06-08 07:15 UTC, somangshu commented
@Tooluloope is the latest release merged, Some failing test fixes are available.

2021-06-11 07:14 UTC, somangshu approved these changes

2021-06-14 05:25 UTC, somangshu commented
@Tooluloope latest merge required here, Tests fixes are available

2021-06-15 05:39 UTC, somangshu approved these changes

2021-06-15 06:52 UTC, somangshu commented
@Tooluloope please fix these merge conflicts and merge latest release here!

2021-06-15 07:06 UTC, somangshu approved these changes

2021-06-18 05:42 UTC, somangshu commented
@Tooluloope latest release merge required for failing tests

2021-06-29 13:40 UTC, somangshu submitted a review, later dismissed

2021-06-30 09:30 UTC, somangshu approved these changes

2021-07-08 10:23 UTC, merged