FIX #4573 : added custom fusion chart config to override default message
appsmithorg/appsmith pull request #4660
Opened 2021-05-25 02:36 UTC by vibhandikyash

## Description
When the User drag and drop the Chart widget->and select the custom chart from chart type->the "chart type not supported text" is displayed. Added a default config to resolve it.

Fixes #4573 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
> tested locally.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-05-25 10:37 UTC, somangshu requested changes

2021-05-25 10:37 UTC, somangshu commented on app/client/src/mockResponses/WidgetConfigResponse.tsx
> +        config: {
Today, the custom chart data does not have a config property in the object.

2021-05-25 10:37 UTC, somangshu commented on app/client/src/mockResponses/WidgetConfigResponse.tsx
> +          type: "",
Even if we add the empty object like this, the message `chart data is not supported` will still exist, We could add a sample config here like other chart types to show an example of usage. Check out the [docs](https://docs.appsmith.com/widget-reference/chart)

@riodeuno thoughts?

2021-05-31 05:40 UTC, somangshu commented
Does not work on the old app charts!

@riodeuno does this change work according to you? We are now showing an example config preloaded in the custom chart data field.

2021-06-02 21:59 UTC, riodeuno commented on app/client/src/mockResponses/WidgetConfigResponse.tsx
> +          type: "",
Yes, at the very least we should include the `type` property to make sure a chart is visible. We can also copy the data from the `chartData` property's default and use it here in the `dataSource` property.

2021-06-02 22:00 UTC, riodeuno commented on app/client/src/mockResponses/WidgetConfigResponse.tsx
> +              label: "Jan",
Shall we make this data and the data above in the `chartData` property consistent?

2021-06-03 05:51 UTC, somangshu commented on app/client/src/mockResponses/WidgetConfigResponse.tsx
> +              label: "Jan",
@vibhandikyash can you look into this

2021-06-04 05:56 UTC, somangshu approved these changes

2021-06-04 11:31 UTC, somangshu commented
Rerunning jobs, Failing for some reason

2021-06-07 13:39 UTC, merged