Feature/image rotation
appsmithorg/appsmith pull request #4674
Opened 2021-05-25 12:45 UTC by techbhavin

## Description
> Image rotation feature implemented in image widget.
Fixes # (#2751)

## Type of change
- New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ]  I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ]  I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-05-25 15:21 UTC, somangshu requested changes
@techbhavin 
- An overlay is required between the image and the rotate buttons as defined in the original issue
- The rotation of each step needs to be 90deg
- The functionality does not work on the view mode.

2021-05-26 07:22 UTC, somangshu requested changes
@techbhavin 
- The image/overlay needs to be container inside the widget boundary
- Increase the size of the icon to 24px.
- This change is throwing an error for already existing widgets

2021-05-26 14:37 UTC, somangshu requested changes

2021-05-26 14:37 UTC, somangshu commented on app/client/src/mockResponses/WidgetConfigResponse.tsx
> +      enableRotation: false,
This still throws an error for the older widgets. @riodeuno any insight how can this be resolved?

2021-05-26 14:53 UTC, somangshu commented
/ok-to-test sha=6b8102b

2021-06-02 21:56 UTC, riodeuno commented on app/client/src/mockResponses/WidgetConfigResponse.tsx
> +      enableRotation: false,
Yes, we need to migrate all previous image widgets to have the `enableRotation: false` property. The debugger sees `undefined` while it tries to validate a `Boolean` field, resulting in this error.

2021-06-02 22:17 UTC, riodeuno approved these changes
Approving for tests to run.

2021-06-03 05:40 UTC, somangshu commented on app/client/src/mockResponses/WidgetConfigResponse.tsx
> +      enableRotation: false,
@techbhavin we need to take care of this!

2021-06-03 12:12 UTC, techbhavin commented
/ok-to-test sha=25931cd

2021-06-04 08:47 UTC, somangshu approved these changes
Approving to run tests

2021-06-07 07:26 UTC, somangshu commented
Rr-running all jobs. Unrelated tests are always failing!

2021-06-07 08:02 UTC, riodeuno approved these changes

2021-06-09 07:10 UTC, vivekverma2312 commented
Observed that if zoom is set and rotation is enabled in property pane then I am not able to zoom the image in both edit and deployed mode.
cc: @somangshu @momcilo-appsmith

2021-06-09 07:33 UTC, somangshu commented
> Observed that if zoom is set and rotation is enabled in the property pane then I am not able to zoom the image in both edit and deployed mode.

@techbhavin for this we need to enable zoom functionality on the overlay in case the rotation property is enabled.

2021-06-09 07:37 UTC, somangshu requested changes
Changes as above ☝️

2021-06-11 07:05 UTC, somangshu commented
@areyabhishek need some help here, The problem is that when the rotate feature is enabled, we cannot access the zoom functionality. We wanted to enable the zoom feature in click on the the overlay, the problem is 
- bad UX
- difficult Implementation

Can you give us a solution from the design point of view

2021-06-11 11:26 UTC, somangshu commented
@techbhavin here are the [new design](https://www.figma.com/file/w9CaXHF5iYcrLtiEbAHcFu/Widgets-Library?node-id=106%3A5453). Kindly let me know if you have any queries about the implementation/design.

2021-06-22 14:27 UTC, techbhavin commented
/ok-to-test sha=a6a351d

2021-06-22 14:52 UTC, somangshu approved these changes
Approving for tests to run.

Looks great.

@techbhavin helper text should change to `controls if the image is allowed to rotate`

2021-06-23 05:56 UTC, techbhavin commented
/ok-to-test sha=5e1de7a

2021-06-23 06:27 UTC, techbhavin commented
the document is also updated in [appsmith-doc-pr-163](https://github.com/appsmithorg/appsmith-docs/pull/163).

@marks0351

2021-06-23 14:02 UTC, techbhavin commented
Fixed #5337

2021-06-28 05:34 UTC, SatishGandham requested changes

2021-06-28 05:34 UTC, SatishGandham commented on app/client/src/widgets/ImageWidget.tsx
> +            helpText: "controls if the image is allowed to rotate",
Capitalize controls.

2021-06-28 05:34 UTC, SatishGandham commented on app/client/src/components/designSystems/appsmith/ImageComponent.tsx
> +    border-right: 1px solid #e0dede;
Do we have these colors in the theme? If yes, please use them from the theme.

2021-06-28 11:01 UTC, somangshu submitted a review, later dismissed

2021-06-29 10:27 UTC, vivekverma2312 commented
@techbhavin Few issue with dragging the image after zoom is enabled.
1. Able to drag the image out of the image widget
Edit mode - > https://www.loom.com/share/6fc5fd73f01243f68ffe1849df72221f
Deployed mode - > https://www.loom.com/share/b716fd573a1a4488bdefa500d477cb0f

2021-06-29 13:58 UTC, somangshu commented
@vivekverma2312 the issue you are pointing out is with the zoom functionality and not related to this. Suggest we create new issues for that. 

@techbhavin please resolve the conflict

@SatishGandham Kindly review changes.

2021-06-30 05:24 UTC, vivekverma2312 commented
@techbhavin Rotation is working fine in deploy preview.

2021-06-30 07:40 UTC, techbhavin commented
fixed #5155

2021-06-30 09:46 UTC, somangshu approved these changes
Looks great. 

@techbhavin documentation change will be required here

2021-07-01 09:19 UTC, somangshu commented
Rerunning failed tests

2021-07-04 04:21 UTC, SatishGandham commented on app/client/test/factories/Widgets/ImageFactory.ts
>      "https://res.cloudinary.com/drako999/image/upload/v1589196259/default.png",
@somangshu Can we use a local image instead of hotlinking a remote image?

2021-07-05 10:35 UTC, somangshu commented on app/client/test/factories/Widgets/ImageFactory.ts
>      "https://res.cloudinary.com/drako999/image/upload/v1589196259/default.png",
That does make sense. I am not sure how it would affect the tests though or why was this done in the first place. 

@techbhavin lets import the image locally

2021-07-05 10:39 UTC, somangshu commented on app/client/test/factories/Widgets/ImageFactory.ts
>      "https://res.cloudinary.com/drako999/image/upload/v1589196259/default.png",
Does it make a difference @SatishGandham, I would say loading from a CDN should be better choice. .

2021-07-06 04:32 UTC, SatishGandham commented on app/client/test/factories/Widgets/ImageFactory.ts
>      "https://res.cloudinary.com/drako999/image/upload/v1589196259/default.png",
Is that CDN used by appsmith?

2021-07-06 05:01 UTC, somangshu commented on app/client/test/factories/Widgets/ImageFactory.ts
>      "https://res.cloudinary.com/drako999/image/upload/v1589196259/default.png",
@SatishGandham this is an Appsmith member account. We can rely on it.

2021-07-06 14:48 UTC, SatishGandham approved these changes

2021-07-08 10:40 UTC, merged