FIX #4413 : changed color picker popover source to color palette
appsmithorg/appsmith pull request #4685
Opened 2021-05-26 08:57 UTC by vibhandikyash

## Description
The Color picker popover was covering up the textbox. Fixed by changing the popover target on click of the color palette.

Fixes #4413 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Tested locally

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-05-31 10:51 UTC, hetunandu commented
Created a new issue [Consistency in color codes of the color picker #4802](https://github.com/appsmithorg/appsmith/issues/4802) in GitHub

2021-05-31 10:54 UTC, hetunandu commented
This fix does not seem to work for container widget

![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiZTVmZjliMzYtMjgzZS00MTU5LWE2ZjUtMTZiMjQyODA0M2E4IiwiZGVwbG95X2lkIjoiNjBhZTBkODFhNzk3YTMwMDA3ODYxNWM4IiwiaWQiOiJjNjBhMGRhNS02NTBjLTQ2ZTktYjBmNy00NzQzNzcxMmY3YTEifQ==)


<details><summary>Browser metadata</summary>





```
Path:      /applications/6013cb2f1ef9d52f963c7768/pages/60379b2e02c7cd7b260da470/edit
Browser:   Chrome 90.0.4430.212 on Mac OS 10.15.7
Viewport:  1680 x 914 @2x
Language:  en-GB
Cookies:   Enabled
```

[View on BrowserStack](https://live.browserstack.com/dashboard#url=https%3A%2F%2Fdeploy-preview-4685--appsmith-editor-ce.netlify.app%2Fapplications%2F6013cb2f1ef9d52f963c7768%2Fpages%2F60379b2e02c7cd7b260da470%2Fedit&os=OS+X&os_version=Catalina&browser=Chrome&browser_version=90.0&resolution=1680x914&speed=1&start=true)



</details>

[Open Deploy Preview](https://deploy-preview-4685--appsmith-editor-ce.netlify.app/applications/6013cb2f1ef9d52f963c7768/pages/60379b2e02c7cd7b260da470/edit) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=60ae0d81a797a300078615c8&commentID=60b4c063be5f6c870b683d75&resolution=resolved)

2021-05-31 10:54 UTC, hetunandu requested changes
Fix does not seem to work

2021-05-31 11:21 UTC, somangshu commented
@hetunandu this seems to be working. Do you mean on clicking the input field the colour picker shows up?


https://user-images.githubusercontent.com/11089579/120185790-4b270800-c230-11eb-96e0-b4ba4891ac3a.mov

2021-05-31 11:22 UTC, hetunandu commented
Got it. Looks like I did not understand the solution earlier

2021-05-31 11:23 UTC, hetunandu submitted a review, later dismissed

2021-05-31 14:00 UTC, somangshu commented
@vibhandikyash some test cases are failing here, Please check!

2021-06-15 05:26 UTC, somangshu commented
@vibhandikyash the tests failing here are again related to the changes. It's been too much time since this has been open. Please look into this and get this fixed ASAP. Take help from @arslanhaiderbuttar if required.

Here is the [dashboard URL](https://dashboard.cypress.io/projects/eyxvp8/runs/6446/overview)

2021-06-30 08:02 UTC, vibhandikyash commented
/ok-to-test sha=25b01af

2021-06-30 13:32 UTC, mohanarpit approved these changes

2021-07-01 07:13 UTC, somangshu requested changes
Check the failing tests, they still refer to the old RGB values. Please update them.

2021-07-01 10:53 UTC, somangshu approved these changes

2021-07-02 07:17 UTC, somangshu commented
Text failing again, Give it the hex code, Dynamic variable might not be available

2021-07-02 12:43 UTC, vibhandikyash commented
/ok-to-test sha=867fa93

2021-07-05 10:11 UTC, somangshu submitted a review, later dismissed
Approving to re-run the tests

2021-07-06 06:32 UTC, somangshu commented
@vibhandikyash the tests are failing because of changes here. Please run the tests locally to see if they are passing

2021-07-06 18:41 UTC, vibhandikyash commented
/ok-to-test sha=67bcd14

2021-07-08 05:43 UTC, vibhandikyash commented
/ok-to-test sha=72e3fdd

2021-07-08 06:59 UTC, somangshu requested changes

2021-07-08 06:59 UTC, somangshu commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/Table_GeneralProperty_spec.js
> +    // cy.openPropertyPane("tablewidget");
@vibhandikyash why is this done? Please uncomment and push

2021-07-08 07:36 UTC, vibhandikyash commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/Table_GeneralProperty_spec.js
> +    // cy.openPropertyPane("tablewidget");
@somangshu This is because the openPropertyPane function works as a toggle. The previous test case if also running the same function so that keeps it open. If I enable this one it will close and the next test case will start throwing error so just to maintain the sequence I've commented this one!!

2021-07-08 08:38 UTC, somangshu commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/Table_GeneralProperty_spec.js
> +    // cy.openPropertyPane("tablewidget");
In that case how has this been working till now? @arslanhaiderbuttar @NandanAnantharamu some help please

2021-07-09 10:50 UTC, somangshu approved these changes

2021-07-09 12:14 UTC, vibhandikyash commented
/ok-to-test sha=fdbef89

2021-07-12 13:14 UTC, somangshu commented
Closing this branch. The issue and code is stale. We will pick this up in a separate branch

2021-07-12 13:14 UTC, closed without merging