New Readme Design
appsmithorg/appsmith pull request #4692
Opened 2021-05-26 12:20 UTC by vihar

New Readme Design

- New Hero Image
- Added all Social Links
- Update Content
- Update Images and GIFs
- Add New Features
- Updated Demo's and Tutorials
- New Contributors List Design

2021-05-26 13:58 UTC, Nikhil-Nandagopal commented on README.md
> +All parts of your app can be referenced as JavaScript objects. Code interactions between elements, update datasources or manipulate SQL queries—[we'll parse JS anywhere](https://docs.appsmith.com/cor
Change to "we'll run JS anywhere"

2021-05-26 14:01 UTC, Nikhil-Nandagopal commented on README.md
> +- 👩‍💻 [Customer Support Dashboard](https://app.appsmith.com/applications/5f2aeb2580ca1f6faaed4e4a/pages/5f2d61b580ca1f6faaed4e79/?utm_source=github&utm_medium=direct&utm_content=appsmith_apps&utm_cam
Can we add the other templates at appsmith.com/templates

2021-05-26 14:01 UTC, Nikhil-Nandagopal commented on README.md
> +6. [Building Internal Tools with Appsmith](https://youtu.be/eYYYfuW-kEE) `Community`
what does the community tag signify here?

2021-05-26 14:02 UTC, Nikhil-Nandagopal commented on README.md
> +  <img src="static/images/animations/selections.gif" width="32%">
All 3 images are doing the same thing. Can we get one around writing JS and one around running an API

2021-05-26 14:03 UTC, Nikhil-Nandagopal requested changes
@vihar @akshayrangasaid I've suggested a few changes

2021-05-27 05:08 UTC, vihar commented on README.md
> +6. [Building Internal Tools with Appsmith](https://youtu.be/eYYYfuW-kEE) `Community`
We add a `Community` tag when our Community creates the content. These are published on their own blog/youtube channels, not on Appsmith websites.

2021-05-27 05:14 UTC, vihar commented on README.md
> +  <img src="static/images/animations/selections.gif" width="32%">
Updated, thanks for the suggestion!

2021-05-27 05:20 UTC, vihar commented
@akshayrangasaid and @Nikhil-Nandagopal, I've updated based on the feedback. Let me know if we have to make any additional changes.

2021-05-27 05:40 UTC, Nikhil-Nandagopal approved these changes

2021-05-27 06:45 UTC, akshayrangasaid approved these changes

2021-05-27 06:48 UTC, Nikhil-Nandagopal approved these changes

2021-05-27 06:48 UTC, merged