Add more options to action settings
appsmithorg/appsmith pull request #473
Opened 2020-09-01 05:19 UTC by akash-codemonk

2020-09-02 05:10 UTC, hetunandu requested changes

2020-09-02 05:10 UTC, hetunandu commented on app/client/src/pages/Editor/ConfirmRunModal.tsx
> +
Why are two actions needed to close this modal?

2020-09-02 05:10 UTC, hetunandu commented on app/client/src/sagas/ActionExecutionSagas.ts
> +        return;
You might have to dispatch a failure action here so that loading states can go back to false

2020-09-02 05:10 UTC, hetunandu commented
Needs tests

2020-09-02 05:27 UTC, akash-codemonk commented on app/client/src/pages/Editor/ConfirmRunModal.tsx
> +
`showRunActionConfirmModal` is for setting the `isOpen` state of the dialog. `acceptRunActionConfirmModal ` is called when `Confirm` is clicked by the user. `cancelRunActionConfirmModal ` is called when the user clicks on `Cancel` or when the user clicks outside the dialog which will close the modal.

Here while closing I am calling  `cancelRunActionConfirmModal` to handle the scenario when user clicks outside.

2020-09-02 05:33 UTC, akash-codemonk commented on app/client/src/sagas/ActionExecutionSagas.ts
> +        return;
Loading is being set by `yield put(executeApiActionRequest({ id: apiAction.actionId }));` which is called after the  `requestConfirmation` check only.

2020-09-08 04:42 UTC, hetunandu approved these changes

2020-09-08 04:57 UTC, merged