added string check on options props
appsmithorg/appsmith pull request #4734
Opened 2021-05-27 12:45 UTC by techbhavin

## Description
> This issue arises due to DropDown getting string prop  "options" even when validator detected this string input ( i.e. "{{ \n _.chain() \n}}" ) as invalid and returned parsed value as empty Array. I have handled the current scenario, but if I get more insights into how prop value can be different from the value returned by a validated function, there can be a better solution.

Fixes # (#4146)

## Type of change
- Bugfix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ]  I have commented on my code, particularly in hard-to-understand areas
- [ ]  I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ]  I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-05-28 06:51 UTC, somangshu commented on app/client/src/widgets/DropdownWidget.tsx
> +    const options = this.props.options
Would something like this work? 
`this.props.options  &&  typeof this.props.options === "string"   ? [] : this.props.options `

2021-05-28 09:15 UTC, techbhavin commented on app/client/src/widgets/DropdownWidget.tsx
> +    const options = this.props.options
@somangshu I also try with this but it shows a parsing error. 

![image](https://user-images.githubusercontent.com/58818598/119961041-3b56bc00-bfc3-11eb-9019-25ef032c914c.png)

2021-05-31 12:20 UTC, SatishGandham requested changes
@techbhavin  Can we not just check if it is an array or not?

2021-06-01 04:11 UTC, techbhavin commented
> @techbhavin Can we not just check if it is an array or not?

@SatishGandham  this solution is working fine.

2021-06-02 07:00 UTC, SatishGandham approved these changes

2021-06-07 09:15 UTC, merged