Comments feature fixes
appsmithorg/appsmith pull request #4738
Opened 2021-05-27 14:25 UTC by rishabhsaxena

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.

## Description
> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation 
> and context. List any dependencies that are required for this change.

Fixes # (issue)
> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce. 
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-05-31 08:17 UTC, hetunandu requested changes

2021-05-31 08:25 UTC, hetunandu submitted a review, later dismissed

2021-05-31 08:26 UTC, rishabhsaxena commented on app/client/src/components/ads/DisplayImageUpload.tsx
> +  }, [value]);
Actually it won't try to render the image in this case since we check for the value but I guess this is more explicit

2021-05-31 12:44 UTC, rishabhsaxena commented
/ok-to-test sha=fb0e7ed

2021-05-31 17:37 UTC, rishabhsaxena commented
/ok-to-test sha=fb0e7ed

2021-06-01 17:36 UTC, rishabhsaxena commented
/ok-to-test sha=96164fe

2021-06-02 05:07 UTC, rishabhsaxena commented
/ok-to-test sha=021a62e

2021-06-03 19:02 UTC, rishabhsaxena commented
/ok-to-test sha=a73fc3a

2021-06-03 19:44 UTC, rishabhsaxena commented
/ok-to-test sha=9533190

2021-06-04 06:50 UTC, rishabhsaxena commented
/ok-to-test sha=6736673

2021-06-09 05:02 UTC, jsartisan approved these changes

2021-06-09 10:35 UTC, merged