FIX #1983 : Updated Css to move disabled button smoothly
appsmithorg/appsmith pull request #4744
Opened 2021-05-27 17:33 UTC by vibhandikyash

## Description
Moving a disabled button was difficult. Replaced css. Tested in firefox.

Fixes #1983 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Tested locally.
> Tested in Firefox and Chrome (Mac).

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-05-28 06:28 UTC, somangshu submitted a review, later dismissed

2021-05-28 06:28 UTC, somangshu commented
@vivekverma2312 please test this out properly.

2021-05-28 07:36 UTC, vivekverma2312 commented
@vibhandikyash Currently I am not able to drag and drop any widget on another widget. If we drag and drop container widget on canvas then I am not allowed to drag and drop any other widget on top of it. Similarly the button on Forms are also not clickable and can not be moved.

https://www.loom.com/share/41098cb5b3604a56a005175beba8c75a

2021-05-31 05:56 UTC, marks0351 requested changes

2021-05-31 05:56 UTC, marks0351 commented on app/client/src/components/editorComponents/DraggableComponent.tsx
> +        pointerEvents:
We should be handling this scenario in the button widget itself. use the disabled state to disable button actions(click or submit) without setting the CSS styles like pointer-events and button attributes like [disabled].

2021-06-02 07:34 UTC, marks0351 submitted a review, later dismissed

2021-06-03 06:41 UTC, somangshu commented
Flaky test fail, Re-ran the jobs

2021-06-08 11:36 UTC, somangshu commented
@vibhandikyash merge latest release here

2021-06-09 10:23 UTC, somangshu approved these changes

2021-06-09 12:26 UTC, somangshu commented
Tests still failing

2021-06-11 07:17 UTC, somangshu commented
@vibhandikyash any update here?

2021-06-11 07:25 UTC, vibhandikyash commented
/ok-to-test sha=b9d16d4

2021-06-11 08:35 UTC, somangshu approved these changes
Approving to run test, Need to check if this is the right way to change the test

2021-06-14 05:36 UTC, somangshu commented
@vibhandikyash latest release merge required here!

2021-06-16 09:32 UTC, vibhandikyash commented
/ok-to-test sha=3293d41

2021-06-18 05:49 UTC, somangshu commented
@vibhandikyash latest merge required here for fix failing tests.

2021-06-30 08:11 UTC, vibhandikyash commented
/ok-to-test sha=dd8e5fe

2021-06-30 09:07 UTC, somangshu approved these changes

2021-07-06 05:59 UTC, vivekverma2312 commented
@vibhandikyash Deploy preview is tested and it's working fine.

2021-07-07 05:14 UTC, merged