Feature: Toast component
appsmithorg/appsmith pull request #476
Opened 2020-09-01 08:12 UTC by devrk96

Toast component with UI and functionalities implemented.

2020-09-03 04:35 UTC, satbir121 approved these changes

2020-11-16 10:33 UTC, hetunandu commented on app/client/src/components/ads/common.tsx
> +  warning = "warning",
Warning is still showing in dark background in the editor

2020-11-16 12:40 UTC, hetunandu commented on app/client/src/components/ads/common.tsx
> +  warning = "warning",
Width should be fixed and longer text should be wrapped

2020-11-19 08:26 UTC, hetunandu requested changes

2020-11-19 08:26 UTC, hetunandu commented on app/client/src/components/ads/Toast.tsx
> +  max-width: 300px;
Set constant width and not max width

2020-11-23 06:22 UTC, hetunandu submitted a review, later dismissed

2020-11-24 07:01 UTC, hetunandu approved these changes

2020-11-24 07:01 UTC, merged