Feature/cmd enter to execute actions
appsmithorg/appsmith pull request #4774
Opened 2021-05-28 11:23 UTC by arunvjn

## Description
Enable API/DB query execution on cmd+enter

Fixes #4334 

## Type of change
- New feature (non-breaking change which adds functionality)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-05-29 05:37 UTC, hetunandu commented on app/client/src/pages/Editor/GlobalHotKeys.tsx
> +          onKeyDown={(e) => {
```suggestion
          onKeyDown={() => {
```

2021-05-29 05:39 UTC, hetunandu requested changes

2021-05-29 05:39 UTC, hetunandu commented on app/client/src/pages/Editor/GlobalHotKeys.tsx
> +            if (QueryFormRunBtn) QueryFormRunBtn.click();
Instead of simulating a click why don't we call the `executeAction` function

2021-05-29 06:07 UTC, arunvjn commented on app/client/src/pages/Editor/GlobalHotKeys.tsx
> +            if (QueryFormRunBtn) QueryFormRunBtn.click();
I preferred triggering click over calling executeAction, since we can achieve the same UI state in both cases. (loading/disabled Run btn)

2021-05-29 06:10 UTC, hetunandu commented on app/client/src/pages/Editor/GlobalHotKeys.tsx
> +            if (QueryFormRunBtn) QueryFormRunBtn.click();
The button would still go into loading if you call executeAction because those ui is driven by states

2021-05-29 06:15 UTC, arunvjn commented on app/client/src/pages/Editor/GlobalHotKeys.tsx
> +            if (QueryFormRunBtn) QueryFormRunBtn.click();
Ok, that means that I should verify the current route to be one of API/DB query editor before I call executeAction ?

2021-05-29 06:16 UTC, hetunandu commented on app/client/src/pages/Editor/GlobalHotKeys.tsx
> +            if (QueryFormRunBtn) QueryFormRunBtn.click();
Ohh, definitely! We only one to execute via hotkeys when we are on the api or query pane

2021-05-30 12:50 UTC, hetunandu submitted a review, later dismissed

2021-05-31 07:19 UTC, hetunandu submitted a review, later dismissed

2021-05-31 13:56 UTC, NandanAnantharamu approved these changes

2021-05-31 15:40 UTC, merged