Profile image updates
appsmithorg/appsmith pull request #4783
Opened 2021-05-29 13:52 UTC by rishabhsaxena

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.

## Description
> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation 
> and context. List any dependencies that are required for this change.

Fixes # (issue)
> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce. 
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-06-11 10:22 UTC, kaushik94 approved these changes
LGTM

2021-06-11 10:28 UTC, pranavkanade requested changes
one change

2021-06-11 10:28 UTC, pranavkanade commented on app/client/src/pages/common/ProfileDropdown.tsx
> +      source={`/api/${UserApi.photoURL}`}
Minor problem - this one or other one is problematic
```
# app/client/src/pages/organization/OrgInviteUsersForm.tsx
source={`/api/${UserApi.photoURL}/${user.username}`}
```

2021-06-11 10:28 UTC, pranavkanade commented on app/client/src/pages/organization/OrgInviteUsersForm.tsx
> +                            source={`/api/${UserApi.photoURL}/${user.username}`}
check above comment

2021-06-11 10:30 UTC, akash-codemonk commented
<img width="773" alt="upload" src="https://user-images.githubusercontent.com/67054171/121672686-b5139d00-cacd-11eb-855b-ad0f9cf54068.png">

Could be an unrelated issue. For some images the save button seems to go out of view, also it doesn't scroll here to see the button.

2021-06-11 14:25 UTC, rishabhsaxena commented on app/client/src/pages/common/ProfileDropdown.tsx
> +      source={`/api/${UserApi.photoURL}`}
Actually here both urls are supported, by default it would return the current users profile image

2021-06-11 14:28 UTC, rishabhsaxena commented
> <img alt="upload" width="773" src="https://user-images.githubusercontent.com/67054171/121672686-b5139d00-cacd-11eb-855b-ad0f9cf54068.png">
> 
> Could be an unrelated issue. For some images the save button seems to go out of view, also it doesn't scroll here to see the button.

I'll try and check if we can fix this as a separate issue since it would involve working around uppy's image editor styles

2021-06-11 15:02 UTC, rishabhsaxena commented
/ok-to-test sha=1f4bdd1

2021-06-14 06:44 UTC, pranavkanade approved these changes
LGTM!

2021-06-14 10:09 UTC, RakshaKShetty commented
hi @rishabhsaxena the profile images looks fine

2021-06-14 18:15 UTC, rishabhsaxena commented
/ok-to-test sha=136644e

2021-06-15 06:28 UTC, rishabhsaxena commented
/ok-to-test sha=123f61e

2021-06-15 07:24 UTC, akash-codemonk submitted a review, later dismissed

2021-06-16 17:23 UTC, kaushik94 approved these changes
run tests

2021-06-16 18:36 UTC, merged