Update format of evaluated value shown in the debugger
appsmithorg/appsmith pull request #4804
Opened 2021-05-31 11:15 UTC by akash-codemonk

## Description
The error messages shown for widget property validation errors has been formatted.

Fixes #4761 

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Manually

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-06-07 05:30 UTC, rishabhsaxena requested changes

2021-06-07 05:30 UTC, rishabhsaxena commented on app/client/src/components/editorComponents/Debugger/LogItem.tsx
> +  switch (getType(props.value)) {
Can we add comments here as examples for cases where this is applicable?

2021-06-16 09:20 UTC, rishabhsaxena approved these changes
![image](https://user-images.githubusercontent.com/1944800/122193447-2084b280-ceb2-11eb-8820-f6c1c4ebbd22.png)

This looks a bit redundant since we already have the path in the message currently?

2021-06-16 09:21 UTC, rishabhsaxena commented on app/client/src/components/editorComponents/Debugger/LogItem.tsx
> +  console.log(props.state, "props.state");
Should rm log

2021-06-24 11:04 UTC, akash-codemonk commented
Closing this as requirement was updated. Doing the necessary change in #5144

2021-06-24 11:04 UTC, closed without merging