feat: Add isDisabled to Button column and isVisible to all Table widget Columns
appsmithorg/appsmith pull request #4819
Opened 2021-05-31 20:00 UTC by Tooluloope

## Description

> Add new column properties to Table

Fixes  #3250 

## Type of change

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-06-04 05:20 UTC, hetunandu commented on app/client/src/constants/WidgetConstants.tsx
> +export const LATEST_PAGE_VERSION = 24;
We would need to update the tests again right @marks0351?

2021-06-04 05:24 UTC, marks0351 commented on app/client/src/constants/WidgetConstants.tsx
> +export const LATEST_PAGE_VERSION = 24;
thanks for reminding, that's true. @Tooluloope make sure to update the dsl versions in https://github.com/appsmithorg/appsmith/blob/release/app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Applications/ForkApplication_spec.js#L8
and 
https://github.com/appsmithorg/appsmith/blob/release/app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Applications/DuplicateApplication_spec.js#L9

2021-06-04 06:39 UTC, hetunandu commented on app/client/src/constants/WidgetConstants.tsx
> +export const LATEST_PAGE_VERSION = 24;
@marks0351 When will we make the change we discussed to avoid such problems?

2021-06-04 07:26 UTC, marks0351 commented on app/client/src/constants/WidgetConstants.tsx
> +export const LATEST_PAGE_VERSION = 24;
@NandanAnantharamu u r working on this already right?

2021-06-04 07:38 UTC, NandanAnantharamu commented on app/client/src/constants/WidgetConstants.tsx
> +export const LATEST_PAGE_VERSION = 24;
@marks0351 facing some network issue will update this spec asap once my network is stable

2021-06-07 07:40 UTC, Tooluloope commented on app/client/src/constants/WidgetConstants.tsx
> +export const LATEST_PAGE_VERSION = 24;
Any update @NandanAnantharamu , I’ve update the version also.

2021-06-08 04:16 UTC, Tooluloope commented
Re-running test cause it's failing

2021-06-08 07:06 UTC, somangshu approved these changes
Approving to run tests

2021-06-11 07:14 UTC, somangshu submitted a review, later dismissed

2021-06-14 05:24 UTC, somangshu commented
@Tooluloope please merge the latest release and resolve the above conflicts, Let me know if any help is required!

2021-06-14 12:27 UTC, somangshu approved these changes

2021-06-23 12:49 UTC, mohanarpit commented
@Tooluloope Please merge the latest release into this branch and try to close this PR. The flaky tests should have been fixed now.

2021-06-28 14:11 UTC, somangshu commented
@Tooluloope need to resolve the conflict and.

2021-06-29 14:41 UTC, somangshu approved these changes

2021-06-29 14:42 UTC, somangshu commented on app/client/cypress/manual_TestSuite/GoogleSheet_API_Spec.js
> -    it("Add a Datasource", function() {
hey @Tooluloope if i am not wrong, Was the conflict because of the indentation.

2021-06-29 14:46 UTC, Tooluloope commented on app/client/cypress/manual_TestSuite/GoogleSheet_API_Spec.js
> -    it("Add a Datasource", function() {
No, it wasn't.
Nope, here was the Conflict.

<img width="632" alt="Screenshot 2021-06-29 at 15 43 47" src="https://user-images.githubusercontent.com/31691737/123818718-126d6380-d8ae-11eb-8439-ad620462e3f6.png">

2021-07-01 09:09 UTC, somangshu commented
@marks0351 kindly review

2021-07-01 12:38 UTC, marks0351 approved these changes

2021-07-01 12:38 UTC, marks0351 commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Applications/DuplicateApplication_spec.js
> +    dsl.dsl.version = 27; // latest migrated version
i dont think this is needed now. pls remove and test it out. same goes for ForkApplication_spec.js

2021-07-02 06:48 UTC, somangshu commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Applications/DuplicateApplication_spec.js
> +    dsl.dsl.version = 27; // latest migrated version
@NandanAnantharamu @yatinappsmith can this is handled separately?

2021-07-02 08:06 UTC, NandanAnantharamu commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Applications/DuplicateApplication_spec.js
> +    dsl.dsl.version = 27; // latest migrated version
i think @marks0351 has rightly said he has fixed this issue this is not needed anymore for both fork / duplicate

2021-07-02 08:51 UTC, somangshu commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Applications/DuplicateApplication_spec.js
> +    dsl.dsl.version = 27; // latest migrated version
My question is is we need to remove it in this PR or do it seperately?

2021-07-02 10:12 UTC, marks0351 requested changes

2021-07-02 10:12 UTC, marks0351 commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Applications/DuplicateApplication_spec.js
> +    dsl.dsl.version = 27; // latest migrated version
we need to remove them @somangshu

2021-07-05 10:42 UTC, somangshu submitted a review, later dismissed
Running tests

2021-07-05 17:00 UTC, marks0351 submitted a review, later dismissed

2021-07-06 10:04 UTC, vivekverma2312 commented
@Tooluloope Observations on deploy preview:
1. Enabling `Disable` property in column property pane do not make the button grey in colour
2. Binding with `currentRow` is throwing error for visible and disable property

https://www.loom.com/share/35e877a3f66944139e929ba2b3c58937

2021-07-12 11:51 UTC, vivekverma2312 commented
@Tooluloope Above issues still exist.

2021-07-12 22:32 UTC, Tooluloope commented
> @Tooluloope Above issues still exist.

@vivekverma2312, the Button issue has been fixed.
As for the currentRow binding, I think it's a general Table issue.

CurrentRow binding shows undefined for all other fields except computed value

2021-07-13 05:39 UTC, somangshu commented on app/client/src/components/designSystems/appsmith/TableComponent/TableStyledWrappers.tsx
> +      color: #768896;
Can we get these from the default theme?

2021-07-13 05:59 UTC, Tooluloope commented on app/client/src/components/designSystems/appsmith/TableComponent/TableStyledWrappers.tsx
> +      color: #768896;
Fixed

2021-07-13 12:54 UTC, vivekverma2312 commented
> > @Tooluloope Above issues still exist.
> 
> @vivekverma2312, the Button issue has been fixed.
> As for the currentRow binding, I think it's a general Table issue.
> 
> CurrentRow binding shows undefined for all other fields except computed value

@Tooluloope Button issue is working fine.
Checked currentRow for Button and label colour property and it worked.
<img width="1039" alt="Screenshot 2021-07-13 at 6 21 56 PM" src="https://user-images.githubusercontent.com/83569920/125454924-54d160ec-f696-4db7-b682-afa34aa7aa07.png">

2021-07-14 05:37 UTC, somangshu approved these changes

2021-07-16 10:59 UTC, somangshu commented
@Tooluloope please resolve the conflicts here

2021-07-19 13:11 UTC, somangshu commented
@marks0351 need you review here!

2021-07-19 13:13 UTC, marks0351 commented
@Tooluloope can u fix the jest test that are failing?

2021-07-21 04:52 UTC, marks0351 submitted a review, later dismissed

2021-07-21 06:25 UTC, somangshu commented
@Tooluloope related test failing here

2021-07-21 07:41 UTC, Tooluloope commented
> @Tooluloope related test failing here

Fixed @somangshu

2021-07-21 08:06 UTC, somangshu approved these changes
Approving to run tests

2021-07-22 05:20 UTC, marks0351 submitted a review, later dismissed

2021-07-22 08:14 UTC, somangshu commented
Quoting here for [ref](https://github.com/appsmithorg/appsmith/issues/5943#issuecomment-884703527)

2021-08-09 10:45 UTC, somangshu approved these changes
approving for tests to run

2021-08-12 13:43 UTC, Tooluloope commented on app/client/src/components/designSystems/appsmith/TableComponent/Constants.ts
> -  isColumnVisible?: boolean;
@marks0351 Some updates were made to the issue,
See Ref here https://github.com/appsmithorg/appsmith/issues/5943

2021-08-13 05:41 UTC, marks0351 commented on app/client/src/entities/Widget/utils.test.ts
> +        // "primaryColumns.status.isVisible": EvaluationSubstitutionType.TEMPLATE,
can u pls remove comments if they are unnecessary.

2021-08-13 05:42 UTC, marks0351 approved these changes

2021-08-13 06:58 UTC, somangshu commented
Re-running all tests once.

@Tooluloope there is a migration required here, The old table shows visible as false by default and the column remains visible, This will need to be fixed.

2021-08-16 11:35 UTC, somangshu approved these changes
LGTM

Deploy preview tested

2021-08-17 12:54 UTC, merged

2021-09-05 08:10 UTC, areyabhishek commented
@Tooluloope @vivekverma2312 The eye icon is off-center and it's smaller in size that it is supposed to be:
<img width="255" alt="Screen Shot 2021-09-05 at 1 21 47 PM" src="https://user-images.githubusercontent.com/30255708/132120020-2fed04a1-3584-4041-b7c7-34855c55751c.png">

Link to Figma file of the table property pane: https://www.figma.com/file/1G9ShIQgRloGvcS6kLgw2O/Table-widget-property-pane?node-id=1%3A3

2021-09-05 08:13 UTC, Tooluloope commented
> @Tooluloope @vivekverma2312 The eye icon is off-center and it's smaller in size that it is supposed to be:
> <img alt="Screen Shot 2021-09-05 at 1 21 47 PM" width="255" src="https://user-images.githubusercontent.com/30255708/132120020-2fed04a1-3584-4041-b7c7-34855c55751c.png">
> 
> Link to Figma file of the table property pane: https://www.figma.com/file/1G9ShIQgRloGvcS6kLgw2O/Table-widget-property-pane?node-id=1%3A3

@areyabhishek Currently not on my PC, could you create an issue for it and assign me.