FIX #2587 : added more style support in container property pane
appsmithorg/appsmith pull request #4821
Opened 2021-06-01 05:22 UTC by vibhandikyash

## Description
> Added more styling for for container pane as per below:
- Outline colour / Border colour: Should have the colour picker
- Outline stoke / Border width: The width of border used
- Corner radius / Border radius: The radius/curve on each corner of the container
- Fill Colour / Background colour: Should have the colour picker

Fixes #2587 

## Type of change
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
> Tested locally.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-06-02 12:12 UTC, somangshu commented
/ok-to-test sha=f093e31

2021-06-02 14:21 UTC, somangshu requested changes
Hey I think we should be using developer savvy terminologies like:
- Outline colour -> Border colour
- Outline stoke -> Border width
- Corner radius -> Border radius
- Fill Colour -> Background colour

@riodeuno thoughts?

2021-06-02 21:49 UTC, riodeuno requested changes

2021-06-02 21:49 UTC, riodeuno commented on app/client/src/widgets/ContainerWidget.tsx
> +            helpText: "enter value for outline strock",
Let's fix the spelling and the casing here.

2021-06-02 21:49 UTC, riodeuno commented on app/client/src/widgets/ContainerWidget.tsx
> +            label: "Outline Strock",
Same typo here.

2021-06-02 21:49 UTC, riodeuno commented on app/client/src/widgets/ContainerWidget.tsx
> +            validation: VALIDATION_TYPES.TEXT,
@somangshu 
Are we expecting users to enter the `px` suffix as well? If that's the case users can potentially use `cm` as a suffix as well. Do we want this? Also what happens when users don't add a suffix at all and just a number? Can we detail these in the `helpText` and `placeholderText` fields of this property?

2021-06-02 21:49 UTC, riodeuno commented on app/client/src/widgets/ContainerWidget.tsx
> +            placeholderText: "Enter value",
The placeholder needs to be quite specific here. Users can possibly use `%`, `px`, `cm`, etc

2021-06-03 05:53 UTC, somangshu commented on app/client/src/widgets/ContainerWidget.tsx
> +            validation: VALIDATION_TYPES.TEXT,
@riodeuno now I feel we should do something like the list widget, and fix the unit to `px` and let only integer be allowed

2021-06-03 17:58 UTC, somangshu submitted a review, later dismissed
LGTM

2021-06-04 11:28 UTC, somangshu commented
@vibhandikyash related cypress tests are failing here, Can you check?

2021-06-10 10:48 UTC, vibhandikyash commented
/ok-to-test sha=f26300d

2021-06-10 12:13 UTC, vibhandikyash commented
/ok-to-test sha=3ad24e3

2021-06-14 04:41 UTC, vibhandikyash commented
/ok-to-test sha=c0e074d

2021-06-14 04:56 UTC, somangshu submitted a review, later dismissed

2021-06-15 05:54 UTC, somangshu commented
@riodeuno is the failing test case related to some drag & drop change

2021-07-26 10:21 UTC, somangshu commented
@vibhandikyash we need to have a discussion here to understand if this can be taken forward now. @marks0351 will be able to provide us some clarity

2021-07-28 10:55 UTC, marks0351 commented
@vibhandikyash just mentioning that we had discussed this.
cc: @somangshu

2021-08-09 09:32 UTC, vibhandikyash commented
Will close this and continue it futher at #6476

2021-08-09 09:32 UTC, closed without merging