Feature/widget grouping 2
appsmithorg/appsmith pull request #4825
Opened 2021-06-01 06:15 UTC by marks0351

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.

## Description
> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation 
> and context. List any dependencies that are required for this change.

Fixes # (issue)
> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce. 
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-06-10 06:41 UTC, jsartisan submitted a review, later dismissed

2021-06-14 05:02 UTC, jsartisan approved these changes

2021-06-14 11:21 UTC, jsartisan submitted a review, later dismissed

2021-06-14 12:13 UTC, riodeuno commented on app/client/src/actions/widgetSelectionActions.ts
> +  widgetIds?: string[],
Didn't we move this to a saga instead of passing the values in the action?

2021-06-14 12:50 UTC, riodeuno requested changes

2021-06-14 12:50 UTC, riodeuno commented on app/client/src/actions/widgetSelectionActions.ts
> +export const shiftSelectWidgetsInitAction = (
Let's specify this in the action name, that this action is for entity explorer.

2021-06-14 12:50 UTC, riodeuno commented on app/client/src/components/designSystems/appsmith/ContainerComponent.tsx
> +  box-shadow: 0px 0px 0px 1px #E7E7E7;
Let's check with #4821 for the container styles.

2021-06-14 12:50 UTC, riodeuno commented on app/client/src/components/designSystems/appsmith/TabsComponent.tsx
> +  box-shadow: 0px 0px 0px 1px #e7e7e7;
Same for the container widget styling #4821

2021-06-14 12:50 UTC, riodeuno commented on app/client/src/sagas/SelectionCanvasSagas.ts
> +interface StartingSelectionSate {
Typo here.

2021-06-14 12:51 UTC, riodeuno approved these changes

2021-06-15 07:36 UTC, riodeuno submitted a review, later dismissed

2021-06-16 09:35 UTC, vivekverma2312 commented
@marks0351 
Few Observations on widget grouping:
1. cmd + click — able to select widget from multiple pages on entity explorer but shift + click is allowed only inside one page
2. Entity explorer is not clickable near the netlify drawer— Should not happen on prod 
3. Alignment at the bottom of the container is not fixed as now table and container widget from bottom overlaps.
4. cmd + click widgets on entity explorer and delete. Now undo delete functionality. Now do shift + click for other widgets after restoring of undo delete observe that wrong widgets get selected (https://www.loom.com/share/6b627492862146788c0b66cdd6ba9363)
5. If we delete any widget from entity explorer and undo delete then these widgets restore at top of the entity explorer- Sequence is not same : Will discuss this in undo/redo
6. The widget got unselected but in entity explorer it is still showing as selected. (https://www.loom.com/share/34250df86fe84df2a0db47d3792deb33)
7. Drag and Drop a widget and open property pane and click on Debugger and observe the property pane closes
https://www.loom.com/share/0f037dc290a24545ad86190c5adf5be3
8. Drag and Drop a widget and open debugger and click on property pane and move the property pane to the left side and observe the UI
https://www.loom.com/share/a041b92db6fd47b6ae62eac41ddd717d
9. Multi select Delete option can be implement in the Entity explorer as well. Currently multi select delete can be performed only via keyboard key - delete

2021-06-17 07:04 UTC, jsartisan submitted a review, later dismissed

2021-06-17 08:48 UTC, riodeuno approved these changes

2021-06-17 13:26 UTC, merged