added onclose property and handlers on ModalWidget
appsmithorg/appsmith pull request #4834
Opened 2021-06-01 09:31 UTC by techbhavin

## Description
>  Add `onModelClose` proerty to model widget.

Fixes # (#3639)

## Type of change

- Bugfix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ]  I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ]  I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-06-01 13:22 UTC, somangshu requested changes
Looks good and works as intended!
Can we add a test to cover this use case?

2021-06-02 06:58 UTC, SatishGandham commented on app/client/src/components/designSystems/blueprint/ModalComponent.tsx
>    onClose: (e: any) => void;
What is onClose and onModalClose?

2021-06-02 11:01 UTC, techbhavin commented on app/client/src/components/designSystems/blueprint/ModalComponent.tsx
>    onClose: (e: any) => void;
onClose is the handler passed to Overlay of the modal, which is used to close modal through Overlay interaction. onClose handler runs the code to close modal. This will not be called if modal was closed from external event .i.e. a button click.
onModalClose is the new handler prop added for current update which fires required actions if user have selected to run on Modal's "onCLose" property from property pane.

2021-06-02 12:15 UTC, techbhavin commented
Hello @SatishGandham  @somangshu 

can we consider  `onModalClose` property feature in happy path testing? 

if we consider it a happy path testing feature, I will write a test case in cypress.

2021-06-07 06:30 UTC, SatishGandham approved these changes

2021-06-07 14:31 UTC, somangshu approved these changes

2021-06-08 07:13 UTC, merged