Changes js error show with logblacklist
appsmithorg/appsmith pull request #4854
Opened 2021-06-02 07:52 UTC by ApekshaBhosale

## Description
Refactor code to shos js erros in debugger

Fixes #4711 
Fixes #4720 
Fixes #4773
Fixes #4820 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: changes-js-error-show-with-logblacklist 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 51.59 **(0.01)** | 32.7 **(0.05)** | 29.72 **(-0.02)** | 52.1 **(0)**
 :green_circle: | app/client/src/components/editorComponents/CodeEditor/index.tsx | 75.23 **(0.96)** | 52.94 **(1.64)** | 58.06 **(0)** | 75.88 **(0.75)**
 :green_circle: | app/client/src/entities/DataTree/dataTreeWidget.ts | 84.85 **(1.52)** | 25 **(0)** | 80 **(5)** | 84.38 **(1.62)**
 :red_circle: | app/client/src/mockResponses/WidgetConfigResponse.tsx | 12.09 **(-1.83)** | 0 **(0)** | 0 **(0)** | 12.5 **(-1.97)**
 :red_circle: | app/client/src/sagas/ActionSagas.ts | 12.01 **(-0.05)** | 1.06 **(0)** | 4.55 **(0)** | 14.59 **(-0.07)**
 :green_circle: | app/client/src/sagas/DebuggerSagas.ts | 18.06 **(4.01)** | 4.35 **(1.36)** | 33.33 **(8.33)** | 19.12 **(3.52)**
 :red_circle: | app/client/src/sagas/EvaluationsSaga.ts | 19.19 **(-1.5)** | 1.56 **(0)** | 9.09 **(-0.91)** | 22.15 **(-1.29)**
 :red_circle: | app/client/src/utils/DynamicBindingUtils.ts | 88.24 **(-0.22)** | 75.41 **(0)** | 78.57 **(0)** | 86.81 **(-0.29)**
 :red_circle: | app/client/src/utils/WidgetPropsUtils.tsx | 63.98 **(-1.62)** | 52.32 **(-1.06)** | 54.17 **(-3.18)** | 63.34 **(-1.68)**
 :green_circle: | app/client/src/workers/DataTreeEvaluator.ts | 88.71 **(0.34)** | 78.38 **(1.42)** | 87.32 **(0)** | 88.79 **(0.37)**</details>

2021-06-02 13:14 UTC, ApekshaBhosale commented
/ok-to-test sha=c1eb123

2021-06-03 07:57 UTC, hetunandu requested changes

2021-06-03 07:57 UTC, hetunandu commented on app/client/src/sagas/EvaluationsSaga.ts
> +  if (!finalErrors) return;
Dont return here. We still want to process other errors

2021-06-03 07:57 UTC, hetunandu commented on app/client/src/sagas/EvaluationsSaga.ts
> +  finalErrors.forEach((error) => {
Loop through original errors and not final errors

2021-06-03 07:57 UTC, hetunandu commented on app/client/src/sagas/EvaluationsSaga.ts
> +      // step 3 : remove these
Forgot this step

2021-06-03 07:57 UTC, hetunandu commented on app/client/src/sagas/EvaluationsSaga.ts
> +  // step 7: get evaluationOrder
Remove the step comments

2021-06-03 07:57 UTC, hetunandu commented on app/client/src/workers/DataTreeEvaluator.ts
> +    return false;
Unused function

2021-06-03 08:59 UTC, ApekshaBhosale commented on app/client/src/sagas/EvaluationsSaga.ts
> +  // step 7: get evaluationOrder
i will remove once we are done with all the changes

2021-06-04 04:53 UTC, hetunandu submitted a review, later dismissed

2021-06-04 06:16 UTC, hetunandu approved these changes

2021-06-04 07:09 UTC, merged