Feature/3357 rate widget
appsmithorg/appsmith pull request #4891
Opened 2021-06-03 07:36 UTC by wmdev0808

## Description
- Create the first MVP of rate widget

Fixes #3357 

## Type of change

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

## How Has This Been Tested?

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-06-03 08:44 UTC, somangshu commented
@pawan we need an icon for the rating widget! @momcilo-appsmith can you help?

2021-06-03 08:56 UTC, somangshu commented
@wmdev0808 Great work, The widget looks great.
- Disabled state needs to have the not allowed pointer
- Right now for the count higher than 20 the UI overflows the parent container. @jsartisan any suggestion around that?

@prapullac let's get this tested!

2021-06-03 08:57 UTC, somangshu approved these changes
Approving to run tests

2021-06-03 11:35 UTC, prapullac commented
Issues identified:
1. Default Rate is (0) it is displayed on the widget and
2. When the Default Rate is (0)  the user can not add stars further 
3. Resizing the widget does not increase the star size but only increases the border/Area. As increasing the borders only occupies the canvas and does not allow any other widget to be placed
4. Text widget and Rate widget have same Widget logo
5. Widget breaks or becomes inactive when max count is large
6. When the Default Rate is higher then the Max rate error or a red highlighter must be displayed to the user
7. When the widget bounder is vertical the stars go out of the canvas 
8. Decimal value is allowed on Default Rate  and Max Count
9. Default Rate can be 1 or 0.5 and 0.5 only when “Allow Half“ is true 
10. Enhancement: Adding full colour would confuse the user and hence we can  add borders and provide colour palette as well

2021-06-04 01:39 UTC, wmdev0808 commented
> @wmdev0808 Great work, The widget looks great.
> 
> * Call it `rating` instead of `rate`
> * ~Disabled state needs to have the not allowed pointer~
> * Right now for the count higher than 20 the UI overflows the parent container. @jsartisan any suggestion around that? - **Resolve this by adding `overflow: scroll`**
> 
> @prapullac let's get this tested!

got it

2021-06-04 05:47 UTC, somangshu requested changes
The `overflow: auto` cuts the top layer of stars

<img width="248" alt="Screenshot 2021-06-04 at 11 16 49 AM" src="https://user-images.githubusercontent.com/11089579/120751906-693d8280-c526-11eb-9f98-46e47975c9ef.png">
<img width="219" alt="Screenshot 2021-06-04 at 11 17 04 AM" src="https://user-images.githubusercontent.com/11089579/120751916-6b9fdc80-c526-11eb-8de7-ceb5d143a3d7.png">

2021-06-04 05:52 UTC, somangshu requested changes

2021-06-04 05:52 UTC, somangshu commented on app/client/src/workers/validations.ts
> +  [VALIDATION_TYPES.RATE_DEFAULT_RATE]: (
@wmdev0808  Lets add tests for these

2021-06-04 09:51 UTC, wmdev0808 commented on app/client/src/workers/validations.ts
> +  [VALIDATION_TYPES.RATE_DEFAULT_RATE]: (
I've done with two things above

2021-06-04 10:12 UTC, somangshu commented on app/client/src/workers/validations.ts
> -    return { isValid, parsed, message };
Why did we remove the message from here! It was showing up well on the debugger

2021-06-04 10:19 UTC, somangshu approved these changes
LGTM

2021-06-04 15:07 UTC, somangshu approved these changes
LGTM

2021-06-07 05:42 UTC, somangshu commented
Re-running jobs for flaky test fail

2021-06-07 05:50 UTC, somangshu commented
@wmdev0808 merge the latest release here, there is a fix for a test failure in this PR

2021-06-07 14:29 UTC, somangshu approved these changes
Running tests

2021-06-07 22:43 UTC, areyabhishek commented
@wmdev0808 Small grammar errors:
1. It should say 'allow half stars'. It should also say 
<img width="345" alt="Screen Shot 2021-06-08 at 4 12 50 AM" src="https://user-images.githubusercontent.com/30255708/121096438-d8a9bf80-c80f-11eb-80cf-c69f13795188.png">

2021-06-08 05:23 UTC, wmdev0808 commented
> @wmdev0808 Small grammar errors:
> 
> 1. It should say 'allow half stars'.
> 2. Tooltip should also say "Controls if user can submit half stars'
> 
> <img alt="Screen Shot 2021-06-08 at 4 12 50 AM" width="345" src="https://user-images.githubusercontent.com/30255708/121096438-d8a9bf80-c80f-11eb-80cf-c69f13795188.png">
> 
> Some small changes required:
> 
> 1. When I choose small or medium size stars, the stars should be centered in the widget instead of being top aligned.
> 2. There's a minimum size for the widget border, can that be smaller? Today that border is too big for the small sized star

Confirmation is required for the above

2021-06-08 05:43 UTC, somangshu commented
@wmdev0808 
- let's make changes to the content!
- See if we can find a better solution to have the stars aligned centre in the default state.

@areyabhishek w.r.t. to the border you are talking about, Are you suggesting something like 👇 

![Screenshot 2021-06-08 at 11 08 49 AM](https://user-images.githubusercontent.com/11089579/121129326-6a362300-c84a-11eb-8ac3-b8b69ea4820e.png)

We cannot dynamically change the widget border when the size is changed, That would involve a whole lot of complexities.

2021-06-08 05:54 UTC, somangshu commented
@vihar need help with documentation here.

2021-06-08 11:27 UTC, vihar commented
Do we have any initial documentation for this @jsartisan?

2021-06-09 05:04 UTC, jsartisan commented
> Do we have any initial documentation for this @jsartisan?

not yet. I'll create one today.

2021-06-09 06:46 UTC, jsartisan approved these changes

2021-06-09 09:01 UTC, somangshu commented
@vihar has added the documentation in the draft, @vivekverma2312 we have to make sure that the documentation is released in tandem to the rating widget in prod.

2021-06-10 05:06 UTC, somangshu approved these changes
LGTM, Approving for test run

2021-06-10 09:28 UTC, jsartisan approved these changes

2021-06-10 09:28 UTC, jsartisan commented
LGTM.

2021-06-11 06:57 UTC, somangshu commented
@yatinappsmith @NandanAnantharamu flaky tests failing here! Merged release two days ago

2021-06-14 05:37 UTC, somangshu approved these changes

2021-06-15 05:55 UTC, somangshu commented
@wmdev0808 latest release merge will fix the failing test here

2021-06-15 09:18 UTC, somangshu approved these changes

2021-06-18 05:41 UTC, somangshu commented
@wmdev0808 latest release merge required for failing tests

2021-06-21 05:32 UTC, somangshu approved these changes
Approving to run tests

2021-06-29 13:26 UTC, somangshu commented
@wmdev0808 Kindly clear merge conflicts here

2021-06-29 14:13 UTC, somangshu submitted a review, later dismissed

2021-06-30 05:54 UTC, jsartisan submitted a review, later dismissed

2021-06-30 05:54 UTC, jsartisan commented on app/client/src/components/designSystems/blueprint/RateComponent.tsx
> +    props.iconSize === 12 ? 2.92 : props.iconSize === 16 ? 4.37 : 4.93}px;
Not sure but these values look weird. Any reason for using specific values like those?

2021-06-30 05:54 UTC, jsartisan commented on app/client/src/components/designSystems/blueprint/RateComponent.tsx
> +/*
not sure why there is a comment regarding line clamp here :|

2021-06-30 07:30 UTC, wmdev0808 commented on app/client/src/components/designSystems/blueprint/RateComponent.tsx
> +    props.iconSize === 12 ? 2.92 : props.iconSize === 16 ? 4.37 : 4.93}px;
@jsartisan It is just for the wider space between stars because @somangshu ask for that.
Those specific values are following the design spec

2021-06-30 07:31 UTC, wmdev0808 commented on app/client/src/components/designSystems/blueprint/RateComponent.tsx
> +/*
It should be removed

2021-06-30 09:48 UTC, somangshu approved these changes

2021-07-02 07:39 UTC, somangshu commented
@wmdev0808 kindly clear out these merge conflicts

2021-07-02 08:49 UTC, somangshu approved these changes
Approving to run tests

2021-07-02 09:54 UTC, jsartisan approved these changes

2021-07-02 09:55 UTC, merged