Improve autocomplete
appsmithorg/appsmith pull request #4898
Opened 2021-06-03 08:43 UTC by ApekshaBhosale

## Description
small improvements for autocomplete 

Fixes #4770

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-06-03 10:19 UTC, hetunandu requested changes
Minor changes

2021-06-03 10:19 UTC, hetunandu commented on app/client/src/components/editorComponents/CodeEditor/EditorConfig.ts
> +    entity: string,
rename to entityName

2021-06-03 10:19 UTC, hetunandu commented on app/client/src/utils/autocomplete/TernServer.ts
> +      type === "Array<{ label: string, value: string }>"
Does not handle `Array<x:string, y:number>` for chart data type.
This method does not seem scalable

2021-06-03 10:19 UTC, hetunandu commented on app/client/src/utils/autocomplete/TernServer.ts
> +      if (!entity || !completion.name.includes(entity)) {
This check should only be applied when the input is empty. Once the user has written say {{Api1.}} in a API1 field, we should show the correct results then.

2021-06-03 10:19 UTC, hetunandu commented on app/client/src/components/editorComponents/CodeEditor/EditorConfig.ts
> +    entity: string,
Also this is optional

2021-06-03 10:22 UTC, ApekshaBhosale commented on app/client/src/utils/autocomplete/TernServer.ts
> +      type === "Array<{ label: string, value: string }>"
i will add Array<x:string, y:number> for now we need to change this anyways to take into array<object>

2021-06-03 10:25 UTC, ApekshaBhosale commented on app/client/src/utils/autocomplete/TernServer.ts
> +      if (!entity || !completion.name.includes(entity)) {
this is to remove cyclic dependency we won't show Api1 on Api1

2021-06-04 04:52 UTC, hetunandu approved these changes

2021-06-04 05:25 UTC, hetunandu commented on app/client/src/pages/Editor/APIEditor/Form.tsx
> +              dataTreePath={`${actionName}.config.url`}
```suggestion

```

2021-06-04 05:25 UTC, hetunandu approved these changes

2021-06-04 06:22 UTC, hetunandu approved these changes

2021-06-04 07:33 UTC, merged