FIX #4813 : display filter count and highlighted filter button
appsmithorg/appsmith pull request #4916
Opened 2021-06-03 15:16 UTC by vibhandikyash

## Description
> Displaying number of filters applied in Table Widget. 

Fixes #4813 

## Type of change
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
> Tested locally.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-06-03 15:16 UTC, vibhandikyash commented
/ok-to-test sha=b7dcb03

2021-06-04 06:00 UTC, somangshu commented
@prapullac please test this out!
<details><summary>Browser metadata</summary>





```
Path:      /applications/60a4f4981f2eef5dc53d3754/pages/60a4f4981f2eef5dc53d3756/edit
Browser:   Chrome 91.0.4472.77 on Mac OS 10.15.7
Viewport:  1387 x 796 @2x
Language:  en-GB
Cookies:   Enabled
```

[View on BrowserStack](https://live.browserstack.com/dashboard#url=https%3A%2F%2Fdeploy-preview-4916--appsmith-editor-ce.netlify.app%2Fapplications%2F60a4f4981f2eef5dc53d3754%2Fpages%2F60a4f4981f2eef5dc53d3756%2Fedit&os=OS+X&os_version=Catalina&browser=Chrome&browser_version=91.0&resolution=1387x796&speed=1&start=true)



</details>

[Open Deploy Preview](https://deploy-preview-4916--appsmith-editor-ce.netlify.app/applications/60a4f4981f2eef5dc53d3754/pages/60a4f4981f2eef5dc53d3756/edit) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=60b8f232572b7f00088b6869&commentID=60b9c19b1861d3b129d8e898&resolution=resolved)

2021-06-04 07:00 UTC, vicky-primathon requested changes

2021-06-04 07:00 UTC, vicky-primathon commented on app/client/src/components/designSystems/appsmith/TableComponent/TableFilters.tsx
> +        filterApplied={hasAnyFilters}
Instead of passing filterApplied to TableAction component, we can pass icon color since we are only changing color based on filterApplied property.

2021-06-04 08:36 UTC, somangshu commented on app/client/src/components/designSystems/appsmith/TableComponent/TableFilters.tsx
> +        filterApplied={hasAnyFilters}
@vicky-primathon Check the new design, We need a count of filters next to the icon.

2021-06-04 08:39 UTC, vicky-primathon commented on app/client/src/components/designSystems/appsmith/TableComponent/TableFilters.tsx
> +        filterApplied={hasAnyFilters}
Yes @somangshu , i have that figured. But since we are only changing icon color by passing filterApplied property we can instead pass the icon color property. That will keep our component generalised.

2021-06-04 08:52 UTC, somangshu commented on app/client/src/components/designSystems/appsmith/TableComponent/TableFilters.tsx
> +        filterApplied={hasAnyFilters}
@vibhandikyash ☝️

2021-06-07 09:27 UTC, vivekverma2312 commented
@vibhandikyash Tested and working fine on deploy preview. Good to be merged into release.

2021-06-08 13:45 UTC, vibhandikyash commented on app/client/src/components/designSystems/appsmith/TableComponent/TableFilters.tsx
> +        filterApplied={hasAnyFilters}
Yes, this is a good suggestion. Implemented it.

2021-06-09 10:34 UTC, somangshu approved these changes
Approving to run tests

@vicky-primathon please check the changes requested

@vivekverma2312 some changes here, Please test them out again!

2021-06-11 08:45 UTC, vicky-primathon approved these changes
Looks good to me

2021-06-14 05:28 UTC, somangshu commented
@vibhandikyash merge the latest release here. Failing test fixes are available!

2021-06-16 08:56 UTC, vibhandikyash commented
/ok-to-test sha=1d93dd4

2021-06-29 13:42 UTC, somangshu approved these changes

2021-07-05 05:26 UTC, merged