Updated fork/duplicate test
appsmithorg/appsmith pull request #4923
Opened 2021-06-04 08:21 UTC by NandanAnantharamu

updated test to replace the version in the test which is hardcoded

2021-06-04 08:29 UTC, marks0351 submitted a review, later dismissed

2021-06-04 11:55 UTC, marks0351 submitted a review, later dismissed

2021-06-05 16:00 UTC, NandanAnantharamu commented
/ok-to-test sha=5a3db58

2021-06-06 07:05 UTC, marks0351 approved these changes

2021-06-06 10:38 UTC, NandanAnantharamu commented
/ok-to-test sha=7043913

2021-06-06 11:12 UTC, NandanAnantharamu commented
/ok-to-test sha=d20ff0e

2021-06-07 07:26 UTC, hetunandu requested changes

2021-06-07 07:26 UTC, hetunandu commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Applications/DuplicateApplication_spec.js
> +    cy.get("@getPage").then((httpResponse) => {
Look at the save page response here instead of get page. At this point, the dsl has still not migrated.

2021-06-07 12:22 UTC, hetunandu commented
/ok-to-test sha=50aeb89

2021-06-07 14:44 UTC, NandanAnantharamu commented
/ok-to-test sha=f358d7d

2021-06-07 16:40 UTC, hetunandu approved these changes
Approving for test run

2021-06-08 08:55 UTC, NandanAnantharamu commented
/ok-to-test sha=722ca5f

2021-06-09 05:27 UTC, NandanAnantharamu commented
/ok-to-test sha=ad88956

2021-06-09 16:17 UTC, NandanAnantharamu commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Applications/DuplicateApplication_spec.js
> +    cy.get("@getPage").then((httpResponse) => {
Looks like even though we have taken dsl data after update layout its not working. How about validing the widget data from UI after fork/Duplicate action as this test continues to fail.

2021-06-10 09:04 UTC, hetunandu approved these changes
Approving for test run

2021-06-11 07:57 UTC, NandanAnantharamu commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Applications/DuplicateApplication_spec.js
> +    cy.get("@getPage").then((httpResponse) => {
@hetunandu let me know your feedback, this is still failing with our new approach, should I add test validation for widget instead of dsl?

2021-06-14 11:17 UTC, hetunandu approved these changes

2021-06-14 12:24 UTC, hetunandu approved these changes

2021-06-14 13:59 UTC, merged