[Feature #4542] : simple nav unify api/datasource (WIP)
appsmithorg/appsmith pull request #4987
Opened 2021-06-08 18:24 UTC by pranavkanade

# WIP
> Note: the nav links for api/datasources might be problematic. This is just to share a preview of the UI elements. More polished and bug free previews will be out soon.

## Description
Simplifies the navigation experience of a user when creating new integrations by unifying apis/datasources tabs.

Fixes # (issue)
#4542 

## Type of change
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested? (WIP)

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist: (WIP)

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-06-14 10:02 UTC, pranavkanade commented
/ok-to-test sha=64bbcd3

2021-06-15 08:23 UTC, Nikhil-Nandagopal approved these changes

2021-06-22 17:31 UTC, trishaanand submitted a review, later dismissed

2021-06-22 17:31 UTC, trishaanand commented
Approved for tests.

2021-06-23 04:21 UTC, sharat87 approved these changes

2021-06-23 04:22 UTC, RakshaKShetty commented
Approved for tests.

2021-06-23 04:27 UTC, RakshaKShetty submitted a review, later dismissed
approved for tests

2021-06-23 07:04 UTC, rishabhsaxena submitted a review, later dismissed
trigger tests

2021-06-23 08:53 UTC, pranavkanade commented
/ok-to-test sha=7aba024

2021-06-23 09:02 UTC, Nikhil-Nandagopal approved these changes

2021-06-23 12:00 UTC, pranavkanade commented
/ok-to-test sha=6e93a4e

2021-06-23 14:12 UTC, pranavkanade commented
/ok-to-test sha=a75c5fa

2021-06-25 05:23 UTC, pranavkanade commented
/ok-to-test sha=25e2380

2021-06-25 06:53 UTC, akash-codemonk requested changes

2021-06-25 06:53 UTC, akash-codemonk commented on app/client/src/components/editorComponents/Debugger/helpers.tsx
> +  INTEGRATION_TABS,
I think we can still use API_EDITOR_URL, QUERIES_EDITOR_URL here, so these changes could be reverted. This will also fix the issue with `Inspect Entity` showing the `Select an entity to inspect` state when we are on a query or api.

2021-06-25 07:57 UTC, pranavkanade commented
/ok-to-test sha=3d79e2f

2021-06-25 08:01 UTC, akash-codemonk approved these changes
Approving for tests

2021-06-27 14:48 UTC, rishabhsaxena approved these changes
Just few minor points
Also, a nitpick - noticed we navigate to canvas on deleting any api from explorer, we could check if we're on the api page

2021-06-27 14:48 UTC, rishabhsaxena commented on app/client/src/pages/Editor/IntegrationEditor/IntegrationsHomeScreen.tsx
> +  max-height: calc(100vh - 160px);
Should define a constant here

2021-06-27 14:48 UTC, rishabhsaxena commented on app/client/src/pages/Editor/IntegrationEditor/IntegrationsHomeScreen.tsx
> +          )}
```suggestion
          {activePrimaryMenuId === PRIMARY_MENU_IDS.CREATE_NEW && (
            <TabComponent
              onSelect={this.onSelectSecondaryMenu}
              selectedIndex={this.state.activeSecondaryMenuId}
              tabs={SECONDARY_MENU}
              vertical
            />
          )}
```

2021-06-27 14:48 UTC, rishabhsaxena commented on app/client/src/pages/Editor/IntegrationEditor/NewApi.tsx
> +const newApiScreen = (props: Props) => {
Components names should be in `TitleCase`

2021-06-27 14:48 UTC, rishabhsaxena commented on app/client/src/pages/Editor/IntegrationEditor/index.tsx
> +  console.log("integrations editor");
should remove logs

2021-06-27 14:48 UTC, rishabhsaxena commented on app/client/src/pages/Editor/IntegrationEditor/index.tsx
> +const integrationsEditor = (props: Props) => {
`TitleCase` for component names

2021-06-28 06:15 UTC, pranavkanade commented on app/client/cypress/support/commands.js
>      200,
This does not impact other test cases - https://dashboard.cypress.io/projects/eyxvp8/runs/7148/overview (This is the latest cypress test run, all tests pass + 1 flaky)

2021-06-28 06:42 UTC, pranavkanade commented on app/client/src/pages/Editor/IntegrationEditor/DatasourceCard.tsx
> +    border: 1.2px solid ${Colors.HIT_GRAY};
copied this from the mocks directly 🥴

2021-06-28 07:36 UTC, pranavkanade commented on app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/ExplorerTests/Entity_Explorer_Datasource_Structure_spec.js
> -  it("Entity explorer datasource structure", function() {
this was already there, I just changed the parts that were blocked by UI changes. Ultimately, by doing so, the complete flow of simple nav gets tested

2021-06-28 09:46 UTC, rishabhsaxena commented on app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/ExplorerTests/Entity_Explorer_Datasource_Structure_spec.js
> -  it("Entity explorer datasource structure", function() {
Actually I was referring to the commented out block. So this also tests for creating queries from the datasource structure. We might be missing this scenario after commenting out the block.

![image](https://user-images.githubusercontent.com/1944800/123616030-80207d80-d823-11eb-97f4-7b0d82c73cab.png)

2021-06-28 09:59 UTC, rishabhsaxena commented on app/client/cypress/support/commands.js
>      200,
Got it, basically since this test is being called by `MongoDatasource_spec`, which tests for deleting the datasource, I guess we should keep the delete step as well

2021-06-28 10:07 UTC, rishabhsaxena commented
![image](https://user-images.githubusercontent.com/1944800/123619030-65033d00-d826-11eb-8803-8065174f95f5.png)

I think we updated this icon in the omnibar search, we should keep the old one, also we could the same one for `actions` within property pane

@pranavkanade

2021-06-28 10:11 UTC, rishabhsaxena commented on app/client/cypress/support/commands.js
>      200,
Think we should keep the delete datasource part as well, since another spec `MongoDatasource_spec`, tests for the deletion using this command

2021-06-28 10:19 UTC, rishabhsaxena submitted a review, later dismissed
Hey just a couple of points regarding the test cases

2021-06-29 10:29 UTC, pranavkanade commented
> ![image](https://user-images.githubusercontent.com/1944800/123619030-65033d00-d826-11eb-8803-8065174f95f5.png)
> 
> I think we updated this icon in the omnibar search, we should keep the old one, also we could the same one for `actions` within property pane
> 
> @pranavkanade 

@rishabhsaxena now using `red` api icon in global search and action selector

2021-06-29 10:33 UTC, pranavkanade commented
/ok-to-test sha=027ad64

2021-06-29 11:40 UTC, pranavkanade commented
/ok-to-test sha=0c44691

2021-06-29 12:13 UTC, rishabhsaxena approved these changes
Hey just checking these couple of points:

Regarding the test case for creating queries from the explorer:
https://github.com/appsmithorg/appsmith/pull/4987/files#r659290348

Regarding the delete step for this test case
https://github.com/appsmithorg/appsmith/pull/4987/files#r659293293

Also I suppose we might have to wait for the mock datasources apis to be merge, so we can verify with the deploy preview

2021-06-29 12:18 UTC, pranavkanade commented on app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/ExplorerTests/Entity_Explorer_Datasource_Structure_spec.js
> -  it("Entity explorer datasource structure", function() {
checking

2021-06-29 13:36 UTC, pranavkanade commented on app/client/cypress/support/commands.js
>      200,
pushed a fix

2021-06-29 13:37 UTC, pranavkanade commented
@rishabhsaxena 
Added fixes for both mentioned instances

2021-06-29 13:42 UTC, rishabhsaxena submitted a review, later dismissed

2021-06-29 15:03 UTC, pranavkanade commented
Tests failed due to mock data resources are not up yet. Deployment is in progress for release BE. Will rerun the flow once the expected BE changes are up

2021-06-30 07:04 UTC, rishabhsaxena submitted a review, later dismissed

2021-06-30 09:17 UTC, pranavkanade commented
/ok-to-test sha=d54734a

2021-06-30 11:28 UTC, pranavkanade commented
/ok-to-test sha=1b2819f

2021-06-30 11:32 UTC, rishabhsaxena submitted a review, later dismissed
nitpick: we could define common styles for the scroll bar and use them across

2021-06-30 11:39 UTC, rishabhsaxena commented
@pranavkanade I suppose should also confirm it the api itself doesn't throw an error for self hosted instances

2021-06-30 11:42 UTC, rishabhsaxena submitted a review, later dismissed

2021-06-30 13:39 UTC, rishabhsaxena approved these changes

2021-06-30 18:21 UTC, merged