[WIP] Page Properties
appsmithorg/appsmith pull request #4989
Opened 2021-06-09 06:38 UTC by jsartisan

Page to manage pages

2021-07-23 11:44 UTC, riodeuno approved these changes
Approve for tests

2021-07-27 13:19 UTC, riodeuno requested changes

2021-07-27 13:19 UTC, riodeuno commented on app/client/src/pages/Editor/Explorer/Pages/PageGroup.tsx
> +        history.push(PAGE_LIST_EDITOR_URL(params.applicationId, params.pageId))
Let's useCallback

2021-07-27 13:19 UTC, riodeuno commented on app/client/src/pages/Editor/Explorer/Pages/PageGroup.tsx
> +        history.push(PAGE_LIST_EDITOR_URL(params.applicationId, params.pageId));
Let's useCallback

2021-07-27 13:19 UTC, riodeuno commented on app/client/src/pages/Editor/PagesEditor/ContextMenu.tsx
> +                  color={get(theme, "colors.propertyPane.iconColor")}
Let's make it a constant, or in a `useMemo`

2021-07-27 13:19 UTC, riodeuno commented on app/client/src/pages/Editor/PagesEditor/ContextMenu.tsx
> +                  onClick={() => onCopy(page.pageId)}
Let's useCallback

2021-07-27 13:19 UTC, riodeuno commented on app/client/src/pages/Editor/PagesEditor/ContextMenu.tsx
> +    <Popover2
Lets split Popover2 as an appsmith component. Also, content should be a new memoized component

2021-07-27 13:19 UTC, riodeuno commented on app/client/src/pages/Editor/PagesEditor/ContextMenu.tsx
> +              <div>IsVisible</div>
Let's follow the labels we have in the property pane.

2021-07-27 13:19 UTC, riodeuno commented on app/client/src/pages/Editor/PagesEditor/ContextMenu.tsx
> +          onClick={() => {
Let's remove this if it is not needed. or we can use `noop`

2021-07-27 13:19 UTC, riodeuno commented on app/client/src/pages/Editor/PagesEditor/ContextMenu.tsx
> +      placement={"bottom-start"}
We don't need `{}` for a string prop

2021-07-27 13:19 UTC, riodeuno commented on app/client/src/pages/Editor/PagesEditor/index.tsx
> +        onUpdate={(newOrder: any, originalIndex: number, newIndex: number) => {
Let's see if we need useCallback here.

2021-07-27 13:19 UTC, riodeuno commented on app/client/src/sagas/PageSagas.tsx
> +      console.log({ pages: response.data });
missed console.log

2021-07-30 09:59 UTC, somangshu commented
@jsartisan can you link the issue to this PR?

2021-08-03 09:47 UTC, marks0351 commented
@jsartisan  deleting from the context menu works fine but doesn't seem to work on the page list item. code looks good.

2021-08-03 10:03 UTC, marks0351 commented
> @jsartisan deleting from the context menu works fine but doesn't seem to work on the page list item. code looks good.

my bad forgot to move the netlify draw out of the way. works fine!!

2021-08-05 05:40 UTC, jsartisan commented
@vivekverma2312 this PR is ready for QA.

2021-08-09 08:09 UTC, vivekverma2312 commented
@jsartisan 
1. Home page can be changed to invisible and deploy which launch blank app
https://www.loom.com/share/473b0fdf72d04ca3a70aa12d0053f903
2. Not able to move page at bottom due to page scroll on page orderhttps://www.loom.com/share/fee3e22afb054c7b86eb9104b5c5379c
3. Unable to find page error on deploy
<img width="428" alt="Screenshot 2021-08-09 at 1 35 02 PM" src="https://user-images.githubusercontent.com/83569920/128676222-9755052f-4c1f-416d-9ebf-c3d9a4094610.png">
[app](https://deploy-preview-4989--appsmith-editor-ce.netlify.app/applications/6110d46cfd54bb5f65658ca0/pages/6110d46cfd54bb5f65658ca2) for repro
4. Page1 is set as Homepage but post deployment page 2 is selected by default
https://www.loom.com/share/7008eec025a04b4cbaaba5e575abea2f

5. Visible property is available as per mock it is invisible with JS option
6. URL property is not available on property pane
for 5 and 6  -- 
<img width="1786" alt="Screenshot 2021-08-09 at 1 21 11 PM" src="https://user-images.githubusercontent.com/83569920/128676271-38d0140d-a971-48fb-825e-9fdd1f46eb75.png">

2021-08-13 09:52 UTC, vivekverma2312 commented
@jsartisan This looks fine. For issue2 I will test in different PR. Good to be merged in release.

2021-08-13 11:38 UTC, merged