Bug/onload apis entity explorer
appsmithorg/appsmith pull request #4991
Opened 2021-06-09 09:53 UTC by kaushik94

---
name: "Pull Request"
about: Create a pull request to submit new contributions to appsmith
title: "[FIX/FEATURE]"
labels:
assignees:
---

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.

## Description

> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change.

Fixes # (issue)

> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-06-11 05:20 UTC, hetunandu commented on app/client/src/pages/Editor/Explorer/EntityExplorer.tsx
> +        (actions: any) => actions && actions.length > 0,
Don't use any

2021-06-11 05:20 UTC, hetunandu commented on app/client/src/pages/Editor/Explorer/hooks.ts
> +      (entity: any) => entity.ENTITY_TYPE && entity.ENTITY_TYPE === "ACTION",
Use the `isAction` function here

2021-06-11 05:20 UTC, hetunandu commented on app/client/src/pages/Editor/Explorer/hooks.ts
> +  const updatedActions = {} as Record<string, any[]>;
What is the goal of this function?

2021-06-11 05:23 UTC, kaushik94 commented on app/client/src/pages/Editor/Explorer/hooks.ts
> +  const updatedActions = {} as Record<string, any[]>;
Oh previously I kept this for optimising, but later I did not go with that approach.

2021-06-11 09:36 UTC, kaushik94 commented
@hetunandu can you please review this again at your convenience.

2021-06-11 10:28 UTC, kaushik94 commented
/ok-to-test sha=b26675159fabe3b6b5460b8d81176c1b7ad94f18

2021-06-12 10:08 UTC, kaushik94 commented
/ok-to-test sha=b26675159fabe3b6b5460b8d81176c1b7ad94f18

2021-06-13 19:18 UTC, kaushik94 commented
/ok-to-test sha=b26675159fabe3b6b5460b8d81176c1b7ad94f18

2021-06-13 19:20 UTC, kaushik94 commented on app/client/src/pages/Editor/Explorer/hooks.ts
> +  const updatedActions = {} as Record<string, any[]>;
Oh hey my bad. It is actually not a function, it is a variable to keep all the actions with new values instead of modifying the existing actions. This looks much more readable IMO.

2021-06-16 13:27 UTC, rishabhsaxena requested changes
@kaushik94 Just checking if I got this correct, we'd like to ref the data property from the evaluated tree instead of referencing from `entities.actions[key].config`?

So ideally should we just subscribe to the dataTree value for the action within the component where we are rendering the data?

2021-07-12 12:25 UTC, ayushpahwa commented
Branch too much behind prod, Bug closed with new PR

https://github.com/appsmithorg/appsmith/pull/5646

2021-07-12 12:25 UTC, closed without merging