Feature/page order api
appsmithorg/appsmith pull request #5020
Opened 2021-06-10 06:59 UTC by AnaghHegde

## Description
Ability to reorder Pages

Fixes #2786 

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
- Test A

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-06-10 11:02 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/domains/ApplicationPage.java
> +    public ApplicationPage(String id, boolean isDefault){
Can we have the constructor be the first method in the class please? It keeps the code predictable and consistent across classes.

2021-06-11 11:53 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ApplicationPageServiceImpl.java
> +                        foundPage.setOrder(0);
We should set the given `order` for the page we found no?

```suggestion
                        foundPage.setOrder(order);
```

2021-06-11 11:55 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ApplicationPageServiceImpl.java
> +                            if (page.getOrder() < foundPage.getOrder()) {
For pages that have the order number `>=` the given `order`, we should increment those right?

```suggestion
                            if (page.getOrder() >= order) {
```

For example, among pages ordered `1, 2, 3, 4`, if the page ordered at 4 is to be set to 2, that means the current 2 and 3 should be moved to 3 and 4 right?

2021-06-11 11:55 UTC, sharat87 commented
@AnaghHegde, can we also set the order numbers in all pages when we are creating a page as well?

2021-06-11 12:01 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ApplicationPageServiceImpl.java
> +                            if (page.getOrder() < foundPage.getOrder()) {
Let's consider the above example. What i am doing is that, First increase the order of the pages, which means `2-->3` and `3-->4`. Once this process is done, i will set the value of the page `foundPage` to the requested order. 

The idea is that suppose there 10 pages and the user re-ordered a page from 5--->2, we don't have to touch the order that is greater than 5 right ? Does it make sense ?

2021-06-11 12:02 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ApplicationPageServiceImpl.java
> +                        foundPage.setOrder(0);
This is bad, i missed this. I will change this.

2021-06-11 12:10 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ApplicationPageServiceImpl.java
> +                            if (page.getOrder() < foundPage.getOrder()) {
Ah yes, good point. In that case, the condition is actually a bit more complicated. In your example, moving page from order 5 to order 2, that means `foundPage.getOrder()` is going to return 5. So in current implementation, we are incrementing _every_ page order that's less than 5, although, we shouldn't increment 1, since are moving to 2 right?

So, I think it should be something more like: `page.getOrder() >= foundPage.getOrder() && page.getOrder() < order`.

```suggestion
                            boolean isMovingUp = order < foundPage.getOrder();
                            if (isMovingUp ? (page.getOrder() >= order && page.getOrder() < foundPage.getOrder()) : (page.getOrder() < order && page.getOrder() >= foundPage.getOrder())) {
```

This will work when the page at 5 is moving to 2 among 10 pages, or when the page at 2 is moving to 5 among 10 pages. I wrote in a horribly unreadable way, please refactor it to use some local variables and also put in some comments or I'll have no idea what's happening there in a week or two. 😅

Also, let's add some tests to this logic please 😬

2021-06-14 10:15 UTC, AnaghHegde commented
@sharat87 The expectation is that whenever the page is created the order will also come from the UI. The reason is instead of making db call, lets have a logic in frontend which will send the order based on number of pages.

2021-06-14 18:08 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ApplicationPageServiceImpl.java
> +                    for (int i = 1; i <= pages.size(); i++) {
IMO we can optimise this by writing migration and ensuring every new page has order. The idea is to remove this loop completely. What are your thoughts?

2021-06-15 01:35 UTC, sharat87 commented on app/server/appsmith-server/src/test/java/com/appsmith/server/services/PageServiceTest.java
> +                            assertTrue(page.getOrder() == 0);
Let's use `assertThat` type of assertions since they report failing assertions in a much better way. The `assertTrue` will only tell that the condition is not true. But this will tell us that the expected value is `0`, but the actual value is `<something else>`. Makes it easier to troubleshoot failing tests.

```suggestion
                            assertThat(page.getOrder()).isEqualTo(0);
```

2021-06-15 01:35 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ApplicationPageServiceImpl.java
> +                        foundPage.setOrder(order);
🙂 

```suggestion
                        // Set the selected page order to the given order.
                        foundPage.setOrder(order);
```

2021-06-15 01:40 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ApplicationPageServiceImpl.java
> +                    for (int i = 1; i <= pages.size(); i++) {
I was of the opinion that we should do less of migrations and make our system tolerant to missing fields, so I pushed for this although I think Anagh suggested we do a migration. Thinking back, now I'm also increasingly of the opinion that adding a migration might be simpler. Reason is I'm thinking there'll be a lot of places where we'll need to do this null check both on the backend and the frontend and it just might not be worth it. Does that make sense?

@AnaghHegde, sorry to be going back on this, can we do a migration in the DatabaseChangelog class that adds the `order` field to all page objects inside `.pages` for applications?

2021-06-15 04:15 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ApplicationPageServiceImpl.java
> +                    for (int i = 1; i <= pages.size(); i++) {
I agree with you guys. I was favouring the migration over making changes in the code.  I will make the necessary changes.

2021-06-16 08:44 UTC, somangshu commented
[This] is dependent on the feature, @jsartisan will pick this up once this is merged into release.

2021-06-16 10:24 UTC, AnaghHegde commented
This file was not at all changed. And when i run the tests in local, all the tests are passing. 
![image](https://user-images.githubusercontent.com/12005551/122202760-f97eae80-ceba-11eb-8fdd-a25ed13b5bba.png)

@sharat87 @abhvsn AM i missing something here ?

2021-06-16 13:14 UTC, abhvsn commented
Yeah as we have included the order field we need to fix these testcases.

2021-06-18 15:40 UTC, nayan-rafiq requested changes

2021-06-18 15:40 UTC, nayan-rafiq commented on app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ApplicationController.java
> +    @PutMapping("/{applicationId}/page/{pageId}/reorder")
@AnaghHegde This type of path naming convention is standard in REST. Unfortunately in spring security, it's tough to set access control in this type of path. Hence I think it would be better if we can put the parameters at last i.e. `/page/reorder/{applicationId}/{pageId}`

2021-06-18 15:40 UTC, nayan-rafiq commented on app/server/appsmith-server/src/test/java/com/appsmith/server/services/PageServiceTest.java
> +    public void reOrderPageMovingUp() {
This test method name should reflect what it's going to test and what is the expected behavior. I personally prefer the [first approach here ](https://dzone.com/articles/7-popular-unit-test-naming). [Some more examples here](https://stackoverflow.com/questions/155436/unit-test-naming-best-practices)

2021-06-18 15:40 UTC, nayan-rafiq commented on app/server/appsmith-server/src/test/java/com/appsmith/server/services/PageServiceTest.java
> +    public void reOrderPageMovingDown() {
Same as above: this test method name should reflect what it's going to test and what is the expected behavior. I personally prefer the [first approach here ](https://dzone.com/articles/7-popular-unit-test-naming). [Some more examples here](https://stackoverflow.com/questions/155436/unit-test-naming-best-practices)

2021-06-18 15:40 UTC, nayan-rafiq commented on app/server/appsmith-server/src/main/java/com/appsmith/server/constants/FieldName.java
> +    public static Integer DEFAULT_PAGE_ORDER = 0;
Do we need a constant for this?

2021-06-18 15:40 UTC, nayan-rafiq commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ApplicationPageServiceImpl.java
> +                    if(foundPage != null){
I request to add an extra space before the starting curly brace

2021-06-18 15:40 UTC, nayan-rafiq commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ApplicationPageServiceImpl.java
> +                        } else{
Same as above and also some other places: I request to add an extra space before the starting curly brace

2021-06-18 15:40 UTC, nayan-rafiq commented on app/server/appsmith-server/src/test/java/com/appsmith/server/services/ApplicationServiceTest.java
> +                        if(page.getId().equals(unpublishedEditedPage.getId()) && page.getIsDefault() == unpublishedEditedPage.getIsDefault()) {
Please use equals for the boolean checks also as they are `Boolean` type and not a primitive. `page.getIsDefault() == unpublishedEditedPage.getIsDefault()` should be `page.getIsDefault().equals(unpublishedEditedPage.getIsDefault())`

2021-06-18 15:56 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/constants/FieldName.java
> +    public static Integer DEFAULT_PAGE_ORDER = 0;
Instead of directly using the hardcoded values, I thought of having a constant for this. I will remove this.

2021-06-18 15:58 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ApplicationPageServiceImpl.java
> +                        } else{
I missed these 🙃. It's on me. I will correct this.

2021-06-18 16:35 UTC, AnaghHegde commented on app/server/appsmith-server/src/test/java/com/appsmith/server/services/PageServiceTest.java
> +    public void reOrderPageMovingUp() {
I agree with you. Following the name convention is definitely helpful. I will definitely follow this :)

2021-06-18 16:37 UTC, AnaghHegde commented on app/server/appsmith-server/src/test/java/com/appsmith/server/services/ApplicationServiceTest.java
> +                        if(page.getId().equals(unpublishedEditedPage.getId()) && page.getIsDefault() == unpublishedEditedPage.getIsDefault()) {
Yes. You are right. This is not the right way to check `Boolean` objects 🙃. I will correct this. Thank you :)

2021-06-18 16:42 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ApplicationController.java
> +    @PutMapping("/{applicationId}/page/{pageId}/reorder")
But in the `ApplicationController` class, many of the path follows standard REST. Should i change the mapping ?

2021-06-18 17:01 UTC, nayan-rafiq commented on app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ApplicationController.java
> +    @PutMapping("/{applicationId}/page/{pageId}/reorder")
This is OK then, no need to change. I didn't check it well. I'm sure the issue is somehow handled and it wouldn't be a problem.

2021-06-18 17:11 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/constants/FieldName.java
> +    public static Integer DEFAULT_PAGE_ORDER = 0;
I think what @nayan-rafiq wanted to mention here is `DEFAULT_PAGE_ORDER` doesn't seem to be a FieldName. We generally put string conversion of fields like page, organization etc in this file. You can keep this private constant in the respective file where you need this variable.

2021-06-21 18:09 UTC, nayan-rafiq approved these changes
LGTM

2021-06-22 05:56 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog.java
> +                        }
We are searching for the page in the `.getPages` list and using the page number from there right? What happens if the page is not there in that list? For example, I have created an application with two pages, with ids `a` and `b`. I publish this application, so `.getPublishedPages` now has `a` and `b`. Now I go delete the `b` page and so `.getPages` only has `a` page. If this migration runs in this situation, it won't set the order number for the `b` page in `.getPublishedPages`, because it can't find the corresponding page in `.getPages`. Does that make sense?

It might just be simpler to set the index as the order number for `.getPublishedPages` as well, just like we are doing for `.getPages`. What say?

2021-06-22 06:48 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog.java
> +                        }
If the page is deleted from pages list(this happens only in edit mode if i am correct) it is automatically deleted from `publishedPages` when the delete action is executed right?

2021-06-22 06:52 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog.java
> +                        }
If a page is deleted in the edit mode, it gets deleted only in the `pages` list. Once the user clicks on the `Deploy` button, then that page is also deleted from `publishedPages`. The idea is that the user performed a delete-page operation, but hasn't deployed the change, so viewers of the application should still see that page, until the application has been deployed again.

2021-06-22 06:53 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog.java
> +                        }
If a page is deleted in the edit mode, it gets deleted only in the `pages` list. Once the user clicks on the `Deploy` button, then that page is also deleted from `publishedPages`. The idea is that the user performed a delete-page operation, but hasn't deployed the change, so viewers of the application should still see that page, until the application has been deployed again.

2021-06-22 06:54 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog.java
> +                        }
oh `publish` action is the trigger. Got it. I will change this right away

2021-06-23 05:47 UTC, AnaghHegde commented
@sharat87 Ready for review. I have made changes accordingly.

2021-06-23 06:08 UTC, sharat87 approved these changes
Looks good man. Let's get this in.

2021-06-23 06:59 UTC, merged