Feature/1726 iframe widget
appsmithorg/appsmith pull request #5026
Opened 2021-06-10 08:23 UTC by wmdev0808

---
name: "Pull Request"
about: Create a pull request to submit new contributions to appsmith
title: "[FIX/FEATURE]"
labels:
assignees:
---

## Description
- Create an iframe widget

Fixes #1726 

## Type of change

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

## How Has This Been Tested?

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-06-10 10:00 UTC, somangshu approved these changes
approving for tests to run.

2021-06-11 10:13 UTC, SatishGandham requested changes
Please check the review comments.

2021-06-11 10:13 UTC, SatishGandham commented on app/client/src/utils/autocomplete/EntityDefinitions.ts
> +  IFRAME_WIDGET: {
Documentation needs to be updated.

2021-06-11 10:13 UTC, SatishGandham commented on app/client/src/components/designSystems/blueprint/IframeComponent.tsx
> +  return <iframe {...props} src={props.source} />;
Do not spread the props, you will be passing down unnecessary values. There are 3-4 instances of it.

2021-06-11 10:13 UTC, SatishGandham commented on app/client/src/components/designSystems/blueprint/IframeComponent.tsx
> +      props.borderColor || "#f2f2f2",
Use the color from the default theme instead of #f2f2f2

2021-06-11 10:27 UTC, wmdev0808 commented on app/client/src/utils/autocomplete/EntityDefinitions.ts
> +  IFRAME_WIDGET: {
@somangshu How can I do this?

2021-06-11 14:46 UTC, somangshu commented on app/client/src/utils/autocomplete/EntityDefinitions.ts
> +  IFRAME_WIDGET: {
@wmdev0808 here are the steps:
- check out an existing [widget documentation](https://docs.appsmith.com/widget-reference/container)
- Clone our [documentation repository](https://github.com/appsmithorg/appsmith-docs)
- Checkout the [widget documentation readme](https://github.com/appsmithorg/appsmith/blob/release/contributions/docs/Widgets.md)
- Create a PR and tag @SatishGandham again.
- Don't worry about creating the video/gif of the widget

Take any help from @vihar or me if required.

2021-06-11 14:47 UTC, somangshu approved these changes
Approving to run tests

2021-06-11 15:45 UTC, wmdev0808 commented on app/client/src/utils/autocomplete/EntityDefinitions.ts
> +  IFRAME_WIDGET: {
> Documentation needs to be updated.

Made a PR on doc repo

2021-06-12 03:36 UTC, riodeuno commented on app/client/src/widgets/IframeWidget.tsx
> +        {...this.props}
Is it possible to avoid this spread as well?

2021-06-12 03:37 UTC, riodeuno commented on app/client/src/constants/HelpConstants.ts
> +    path: "/widget-reference/text",
@wmdev0808 @somangshu let's work on the documentation for this as well, so that we can safely release this as soon as this passes all the tests.

2021-06-12 03:50 UTC, riodeuno commented
We don't have the `Visible` property in the property pane. However, it shows up in the autocomplete. We should also include the `source` and `title` properties in the autocomplete.
<img width="258" alt="Screenshot 2021-06-12 at 9 18 45 AM" src="https://user-images.githubusercontent.com/103687/121764158-63b3ee00-cb5f-11eb-9566-181fcffe7341.png">
<img width="248" alt="Screenshot 2021-06-12 at 9 18 40 AM" src="https://user-images.githubusercontent.com/103687/121764160-64e51b00-cb5f-11eb-8f1c-7601671119a7.png">

2021-06-12 03:51 UTC, riodeuno commented on app/client/src/widgets/IframeWidget.tsx
> +export const ProfiledIframeWidget = Sentry.withProfiler(withMeta(IframeWidget));
We don't need to use `withMeta` here, as we're not including any `meta` properties in this widget.

2021-06-12 05:26 UTC, somangshu commented on app/client/src/constants/HelpConstants.ts
> +    path: "/widget-reference/text",
@wmdev0808 completed the documentation himself yesterday 🎉 , we will update this with the new link as `"/widget-reference/iframe"`

2021-06-14 04:59 UTC, somangshu approved these changes
Approving to run tests after changes

2021-06-14 06:32 UTC, riodeuno submitted a review, later dismissed

2021-06-14 12:29 UTC, somangshu commented
@yatinappsmith @NandanAnantharamu tests are failing here 😞

2021-06-15 05:39 UTC, NandanAnantharamu commented
> @yatinappsmith @NandanAnantharamu tests are failing here 😞

https://github.com/appsmithorg/appsmith/pull/5118  this has fixed this issue

2021-06-15 05:46 UTC, somangshu commented
@wmdev0808 please merge the latest relase here!

2021-06-15 07:07 UTC, somangshu submitted a review, later dismissed

2021-06-15 12:21 UTC, YogeshJayaseelan commented
@wmdev0808  Tested iframe widget in Deploy Preview and please find our observations below,

1.Default iframe should be displayed 

2. The text url in the OnChangedURL tool tip message should be displayed in Capital letters 

<img width="1280" alt="Screenshot 2021-06-15 at 4 54 05 PM" src="https://user-images.githubusercontent.com/35128442/122044724-7433c500-cdfa-11eb-8446-bbfd16cb4a70.png">


3.Green Border colour is not applied - Choose Green border colour and click on deploy and observe

4. iframe size is reduced in the Deploy Mode compared to the editor mode 

https://www.loom.com/share/8413e74df2904c24b4bb761cbbb1bc3e

5. Border Opacity is not functional 

6. Drag and Drop any widgets nearby iframe and set the iframe Border Width to 150 and then click on deploy and observe the widgets placed nearby iframe are shown within iframe container in the deploy mode

https://www.loom.com/share/f3bd9c172f3647bcaf4799eba8024219

7. The query value truncates/breaks on selecting Reset option with widget - Widget name and Reset Children - Yes on OnURLChanged field 

<img width="1280" alt="Screenshot 2021-06-15 at 5 00 33 PM" src="https://user-images.githubusercontent.com/35128442/122051191-ee1b7c80-ce01-11eb-91c4-d186f1041a36.png">


8.Expected DataType field is not displayed for Border Opacity and Border Width fields

<img width="1280" alt="Screenshot 2021-06-15 at 4 54 05 PM" src="https://user-images.githubusercontent.com/35128442/122045972-f670b900-cdfb-11eb-9e16-c8dd67103dd3.png">

9.Application Crashes when the user passes invalid page name in the Navigate option on OnURLChanged actions

https://www.loom.com/share/801fee21324c42789563ee67372358ce

2021-06-15 13:11 UTC, somangshu commented
Re-ran all tests, `Forkapplication.spec.js` was failing, Not related to this

2021-06-15 14:17 UTC, somangshu commented
Re-ran tests, Other tests are failing now!

2021-06-15 16:17 UTC, NandanAnantharamu commented
> Re-ran tests, Other tests are failing now!

we have to work on a fork/duplicate app the current solution is not working, we will et back to you. @hetunandu should we validate the widget instead of dsl validation ? this is failing again

2021-06-15 16:24 UTC, hetunandu commented
> Re-ran tests, Other tests are failing now!

We have been playing catchup with this test for 3 weeks now. I had pushed a fixed that seemed to pass at the PR level but failed once merged. Will try again tomorrow. @NandanAnantharamu @somangshu

2021-06-21 11:21 UTC, somangshu approved these changes
LGTM.

@YogeshJayaseelan, please re-verify

2021-06-23 05:27 UTC, SatishGandham approved these changes

2021-06-23 07:24 UTC, YogeshJayaseelan commented
We have retested iframe in deploy preview and find the status below,

Issues fixed - 1,2,3,4,8

**Issues still open**
5 - Border Opacity is not functional - **This is still not functional** 
6-Drag and Drop any widgets nearby iframe and set the iframe Border Width to 150 and then click on deploy and observe the widgets placed nearby iframe are shown within iframe container in the deploy mode > - **This issue is fixed for border width 150 but this issue is still reproducible for border width above 170**
7-The query value truncates/breaks on selecting Reset option with widget - Widget name and Reset Children - Yes on OnURLChanged field - **This issue still exists**

**New observations:**
10) For any invalid source url app smith deploy page is displayed in iframe
https://www.loom.com/share/563cedf38ad646e3b2870a21c1d5d0ee

11) Is there any restrictions for source url - Most of the source url’s are not loaded in iframe - For Example - LinkedIn, Google, Stack-overflow
https://www.loom.com/share/21838a9c44e243c1b17157091b2ec864

12)Some of the tooltip message inside iframe content are breaking
https://www.loom.com/share/bf946d1c70494ae4ba081045995185fb

Note: OnMessageReceived Action scenario is still pending

2021-06-23 07:31 UTC, merged