Report linting errors via JSHint
appsmithorg/appsmith pull request #5034
Opened 2021-06-10 09:47 UTC by hetunandu

2021-06-14 09:41 UTC, SatishGandham commented
Looks good wrt to my performance related changes.

2021-06-14 12:55 UTC, ApekshaBhosale requested changes

2021-06-14 12:55 UTC, ApekshaBhosale commented on app/client/src/components/editorComponents/CodeEditor/EvaluatedValuePopup.tsx
> +          {error.errorType.toLowerCase()} error:&nbsp;
remove this

2021-06-14 13:18 UTC, ApekshaBhosale submitted a review, later dismissed

2021-06-17 06:51 UTC, ApekshaBhosale approved these changes

2021-06-17 09:26 UTC, hetunandu commented
/ok-to-test sha=d6a3779

2021-06-17 11:53 UTC, hetunandu commented
/ok-to-test sha=b14523f

2021-06-17 16:53 UTC, hetunandu commented
/ok-to-test sha=ad0387e

2021-06-17 17:20 UTC, hetunandu commented
/ok-to-test sha=3b701c2

2021-06-18 05:27 UTC, hetunandu commented
/ok-to-test sha=e648f90

2021-06-18 10:54 UTC, hetunandu commented
/ok-to-test sha=4800799

2021-06-18 11:43 UTC, hetunandu commented
/ok-to-test sha=99eaa82

2021-06-18 14:11 UTC, hetunandu commented
/ok-to-test sha=0464e61

2021-06-18 15:24 UTC, hetunandu commented
/ok-to-test sha=128feb6

2021-06-18 15:58 UTC, hetunandu commented
/ok-to-test sha=0dd70f1

2021-06-18 16:19 UTC, hetunandu commented
/ok-to-test sha=0dd70f1

2021-06-18 19:05 UTC, hetunandu commented
/ok-to-test sha=dcbadb8

2021-06-21 05:37 UTC, ApekshaBhosale approved these changes

2021-06-21 07:54 UTC, ApekshaBhosale submitted a review, later dismissed

2021-06-21 09:54 UTC, hetunandu commented
/ok-to-test sha=07dc83e

2021-06-21 11:09 UTC, merged