Currency datatype in Input Widget
appsmithorg/appsmith pull request #5049
Opened 2021-06-11 07:12 UTC by vicky-primathon

## Description
Support currency datatype in Input Widget

Fixes #1904 

## Type of change
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
- Cypress test that validates currency datatype 

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-06-11 07:50 UTC, vicky-primathon commented
/ok-to-test sha=ac8dd2d

2021-06-11 11:39 UTC, vicky-primathon commented
/ok-to-test sha=768be59

2021-06-11 15:04 UTC, somangshu commented
Great work @vicky-primathon.

2021-06-11 15:12 UTC, somangshu requested changes
@vicky-primathon Some UI level feedback:
- The currency popper list inside the property pane should look similar to the one which is used on the input widget
- The popper design does not match the Figma designs (lets discuss if required)

2021-06-14 11:40 UTC, somangshu commented
@vicky-primathon 2 changes

1. The dropdown value when multiline cover the field underneath 
![Screenshot 2021-06-14 at 5 05 11 PM](https://user-images.githubusercontent.com/11089579/121886597-33bd4400-cd33-11eb-9177-bffd79f5e668.png)

2. The margin between the flag icon and text needs to be more than 15px.
![Screenshot 2021-06-14 at 5 07 35 PM](https://user-images.githubusercontent.com/11089579/121886680-50f21280-cd33-11eb-8cf7-44cb66adb3f2.png)

2021-06-14 12:43 UTC, hetunandu requested changes

2021-06-14 12:43 UTC, hetunandu commented on app/client/src/constants/Currency.tsx
> +export interface CurrencyOptionProps {
Can't we get this via an API?

2021-06-14 12:43 UTC, hetunandu commented on app/client/src/widgets/InputWidget.tsx
> +    this.props.updateWidgetMetaProperty("currencyType", code || "USD");
A property cannot be a meta property if it is also a widget persisted property (in the property pane config)

2021-06-14 14:23 UTC, somangshu commented on app/client/src/constants/Currency.tsx
> +export interface CurrencyOptionProps {
@vicky-primathon 👆

2021-06-15 12:10 UTC, vicky-primathon commented on app/client/src/constants/Currency.tsx
> +export interface CurrencyOptionProps {
@hetunandu @somangshu, will need help in integrating it through an API

2021-06-15 12:21 UTC, somangshu commented on app/client/src/constants/Currency.tsx
> +export interface CurrencyOptionProps {
@ajinkyakulkarni we need some help from the backend team here, Low effort! Let us know how and when we could take this up.

2021-06-30 13:29 UTC, vicky-primathon commented
/ok-to-test sha=7417828

2021-07-01 07:26 UTC, somangshu commented on app/client/src/constants/Currency.tsx
> +export interface CurrencyOptionProps {
@hetunandu we have decided against the API and are keeping this in the codebase

2021-07-01 09:43 UTC, vicky-primathon commented
/ok-to-test sha=6ee0f0b

2021-07-02 05:04 UTC, hetunandu approved these changes

2021-07-02 09:50 UTC, hetunandu requested changes
Need to fix unit tests

2021-07-02 10:40 UTC, hetunandu submitted a review, later dismissed

2021-07-02 11:58 UTC, vicky-primathon commented
/ok-to-test sha=7bc0190

2021-07-02 16:15 UTC, vicky-primathon commented
/ok-to-test sha=4f91044

2021-07-05 07:10 UTC, YogeshJayaseelan commented
@vicky-primathon @somangshu Tested this feature and came up with the below issues 

1) The the currency type is not selected the mouse insertion point is not at the beginning - So the default currency type can be displayed 

https://loom.com/share/aa681474e4d24648929da846cd8b7845

2) When the user removes the number from the currency field Nan is displayed and which is not removable and once when NaN occurs user will not be able to type or choose numbers from up/down arrow button

https://loom.com/share/6f4f54ed19b34bfd9cbcea91d9a77ce8

3) Unable to type abbreviations k or m

4) When the currency field is bind-ed to text widget only the numbers are displayed and the currency symbol is not displayed

https://loom.com/share/eaf1cc098f5c4b0eab9db94e00440c4f

5) The decimal selection automatically redirects to 'No selection' when 0 decimal is chosen and . is typed in the currency field 

https://loom.com/share/4140872ced394321b59d4c99486a85e8

2021-07-07 10:02 UTC, somangshu approved these changes
Looks good, Approving to run tests

@YogeshJayaseelan kindly reverify

2021-07-07 13:20 UTC, vicky-primathon commented
/ok-to-test sha=cb455f8

2021-07-07 18:52 UTC, vicky-primathon commented
/ok-to-test sha=2e5ce92

2021-07-08 07:23 UTC, hetunandu approved these changes

2021-07-08 08:42 UTC, somangshu approved these changes

2021-07-12 09:25 UTC, YogeshJayaseelan commented
@vicky-primathon @somangshu Retested this feature and please find the status below

**Issues Fixed:**
1,2,5

**New issues found:**
6) The value at allow currency field is invalid error occurs when the user deletes and undo deletion
https://loom.com/share/d03e000ab6fb4590b0258721f9a43357

7) 0 is not accepted for both 1 and 2 decimal options. When the 0 is entered after decimal the decimal pointer disappears and also it is noticed that 15.30 , 111.90 will not work because of 0 but 15.31 or 111.98 works 
https://loom.com/share/1883ce1b3c9b40b9842f5c6f5acb3dad

2021-07-12 11:20 UTC, somangshu commented
Rerunning tests here, Unrelated failing test `SwitchDatasource_spec.js`

2021-07-13 09:15 UTC, YogeshJayaseelan commented
@vicky-primathon Retested this and please find the status below,

Issues Fixed:
1,2,5,6,7

New issue:
8) For one decimal or two decimal the values are rounded off. For example selecting two decimal user types 34.67 and when agin 7 is pressed then it becomes 34.8 and changes randomly 
https://www.loom.com/share/dd42d4ffa1e3443ea3e84c590595a1af

2021-07-13 11:27 UTC, YogeshJayaseelan commented
@vicky-primathon Rested the fixes and now looks good.

2021-07-14 06:08 UTC, somangshu approved these changes

2021-07-15 05:05 UTC, hetunandu approved these changes

2021-07-15 08:29 UTC, vicky-primathon commented
/ok-to-test sha=d5a004f

2021-07-15 12:50 UTC, merged