Feature/table multi select
appsmithorg/appsmith pull request #5074
Opened 2021-06-11 12:35 UTC by techbhavin

## Description

> Here we add a multi-select feature in the table widget.

Fixes #2281 

## Type of change
- New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [  ] I have commented my code, particularly in hard-to-understand areas
- [  ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [  ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-06-11 14:55 UTC, somangshu commented
@techbhavin this looks great 👍 

Some alignment issue with the checkbox icon.

2021-06-11 14:55 UTC, somangshu submitted a review, later dismissed
Approving to run tests

2021-06-14 07:55 UTC, SatishGandham requested changes
Please check the review comments and tick and - in checkboxes are not centre aligned please.

2021-06-14 07:55 UTC, SatishGandham commented on app/client/src/components/designSystems/appsmith/TableComponent/TableStyledWrappers.tsx
> +  border: 0.5px solid #e7e7e7;
See if you can pick the color from theme.

2021-06-14 07:55 UTC, SatishGandham commented on app/client/src/components/designSystems/appsmith/TableComponent/Table.tsx
> +    if (every(subPage, (row) => !selectedRowIndices.includes(row.index))) {
This can be done without running the loop twice.

2021-06-15 12:04 UTC, techbhavin commented
/ok-to-test sha=8e3ac92

2021-06-16 12:08 UTC, techbhavin commented
/ok-to-test sha=e476aca

2021-06-17 06:15 UTC, SatishGandham submitted a review, later dismissed
Checkbox alignment looks good to.

2021-06-17 11:26 UTC, techbhavin commented
/ok-to-test sha=51f75cb

2021-06-18 05:06 UTC, somangshu commented
Re-ran all jobs because flaky tests are failing

2021-06-21 12:45 UTC, techbhavin commented
/ok-to-test sha=20ba276

2021-06-22 10:44 UTC, somangshu approved these changes

2021-06-29 13:27 UTC, somangshu commented
@techbhavin kindly clear all merge conflicts here

2021-06-30 10:35 UTC, somangshu approved these changes

2021-06-30 12:00 UTC, YogeshJayaseelan commented
@techbhavin We have tested this feature in deploy preview and please find our observations below 

1) Hovering on Checkbox is not highlighted 

https://loom.com/share/64a1fa3d5ef743f892b056140686346a

2) Checkbox is displayed for empty rows

https://loom.com/share/bea85813986f4d0281a3ec91ac1daba7

2021-07-01 07:37 UTC, somangshu commented
@techbhavin Kindly also check the failing tests with resize and hide column.

2021-07-01 12:20 UTC, vicky-primathon commented
Sure @somangshu

2021-07-02 06:50 UTC, somangshu submitted a review, later dismissed

2021-07-05 11:27 UTC, somangshu submitted a review, later dismissed

2021-07-05 13:34 UTC, somangshu commented
@techbhavin can you check the related test failing?

2021-07-06 04:50 UTC, somangshu approved these changes
Approving to re-run tests after fix

2021-07-06 06:01 UTC, somangshu commented
Rerunning jobs > `LeaveOrganizationTest_spec.js` is now failing. Unrelated

2021-07-06 10:23 UTC, YogeshJayaseelan commented
@techbhavin Tested this feature and still the issue exists - 1)Hovering on Checkbox is not highlighted - https://loom.com/share/64a1fa3d5ef743f892b056140686346a

2021-07-07 03:53 UTC, YogeshJayaseelan commented
@somangshu @techbhavin closing this as the issue 1 is expected behaviour

2021-07-07 05:52 UTC, merged