Fix to enable scroll in sql query results.
appsmithorg/appsmith pull request #5091
Opened 2021-06-13 17:30 UTC by arunvjn

## Description
Fix to enable scroll in sql query results and disappearing scroll bar.
Dynamically adjust table virtualiser's height according to re-sizer's.

Fixes #5042 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-06-16 12:32 UTC, hetunandu requested changes

2021-06-16 12:32 UTC, hetunandu commented on app/client/src/pages/Editor/QueryEditor/EditorJSONtoForm.tsx
> +              (height: number) => setTableBodyHeightHeight(height - 115) //accounts for the tab containers height and the table header.
Let's not hard code the height of the tabs here. If you cant derive it dynamically here, you can declare it as a variable and use that in the styles for the tab as well. Avoids confusion when this number changes for some reason

2021-06-16 12:32 UTC, hetunandu commented on app/client/src/pages/Editor/QueryEditor/Table.tsx
> +      height: calc(100% - 38px);
Don't hard code the 38px.

2021-06-21 03:32 UTC, arunvjn commented on app/client/src/pages/Editor/QueryEditor/EditorJSONtoForm.tsx
> +              (height: number) => setTableBodyHeightHeight(height - 115) //accounts for the tab containers height and the table header.
Removed hardcoding here. Table component will now compute the height it needs to set to the virtualised list it contains.

2021-06-22 03:13 UTC, hetunandu approved these changes

2021-06-22 03:53 UTC, merged