Fix-Input widget with text area expands over boundaries
appsmithorg/appsmith pull request #5114
Opened 2021-06-14 13:20 UTC by vicky-primathon

## Description
Fix Input widget with text area expands over boundaries

Fixes #1001 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Cypress test that validates resize property is fixed

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-06-14 14:28 UTC, somangshu approved these changes
Approving to run tests, Looks good on Deploy preview

2021-06-15 04:47 UTC, hetunandu requested changes

2021-06-15 04:47 UTC, hetunandu commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/Input_textarea_spec.js
> +const dsl = require("../../../../fixtures/InputTextAreaDsl.json");
Please don't test for CSS in cypress tests. Use jest tests instead

2021-06-15 14:13 UTC, somangshu approved these changes

2021-06-16 07:55 UTC, vicky-primathon commented
/ok-to-test sha=2cb984c

2021-06-16 09:10 UTC, somangshu commented
Unrelated tests failing here again!

2021-06-16 12:35 UTC, hetunandu approved these changes

2021-06-18 04:47 UTC, vicky-primathon commented
/ok-to-test sha=9ca7011

2021-06-23 12:59 UTC, mohanarpit approved these changes

2021-06-23 16:25 UTC, vicky-primathon commented
/ok-to-test sha=77daedc

2021-06-28 14:04 UTC, somangshu commented
Rerunning all jobs - Unrelated tests failing

2021-06-29 13:31 UTC, somangshu approved these changes

2021-06-30 13:29 UTC, vicky-primathon commented
/ok-to-test sha=de2e74c

2021-07-02 11:23 UTC, merged