[Bug] Navigate to issues 3125
appsmithorg/appsmith pull request #5140
Opened 2021-06-15 12:56 UTC by kaushik94

---
name: "Pull Request"
about: Create a pull request to submit new contributions to appsmith
title: "[FIX/FEATURE]"
labels:
assignees:
---

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.

## Description

> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change.

Fixes # (issue)

> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-06-17 06:33 UTC, hetunandu requested changes

2021-06-17 06:33 UTC, hetunandu commented on app/client/src/components/editorComponents/ActionCreator.tsx
> +        value = " ";
need to set undefined here

2021-06-17 11:15 UTC, hetunandu commented
This fix is not working

![recording](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiZTVmZjliMzYtMjgzZS00MTU5LWE2ZjUtMTZiMjQyODA0M2E4IiwiZGVwbG95X2lkIjoiNjBjYWYxNmVjMWNiZTMwMDA3YWYyZWE4IiwiaWQiOiI5MDkzMDNhZC1jZWQzLTQ3MTEtYTRmOS1hZTY0Yjc0MWY0NmMifQ==)


<details><summary>Browser metadata</summary>





```
Path:      /applications/60067b0a65f65e25ea829159/pages/60067b0a65f65e25ea82915b/edit
Browser:   Chrome 91.0.4472.101 on Mac OS 10.15.7
Viewport:  1680 x 946 @2x
Language:  en-GB
Cookies:   Enabled
```

[View on BrowserStack](https://live.browserstack.com/dashboard#url=https%3A%2F%2Fdeploy-preview-5140--appsmith-editor-ce.netlify.app%2Fapplications%2F60067b0a65f65e25ea829159%2Fpages%2F60067b0a65f65e25ea82915b%2Fedit&os=OS+X&os_version=Catalina&browser=Chrome&browser_version=91.0&resolution=1680x946&speed=1&start=true)



</details>

[Open Deploy Preview](https://deploy-preview-5140--appsmith-editor-ce.netlify.app/applications/60067b0a65f65e25ea829159/pages/60067b0a65f65e25ea82915b/edit) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=60caf16ec1cbe30007af2ea8&commentID=60cb2ebbccff5fdd0eeeef7b&resolution=resolved)

2021-06-17 11:15 UTC, hetunandu requested changes
Fix does not work

2021-07-01 11:00 UTC, closed without merging

2021-07-01 11:09 UTC, ayushpahwa commented
PR is too old, causing breaking changes when merging. New PR with the same changes with the latest release raised.

https://github.com/appsmithorg/appsmith/pull/5532