upated test for Data change
appsmithorg/appsmith pull request #5158
Opened 2021-06-16 06:18 UTC by NandanAnantharamu

Data from backend changed hence updated the test

2021-06-16 06:31 UTC, mohanarpit approved these changes

2021-06-16 06:44 UTC, hetunandu requested changes
Read the API response and assert that instead of hard coding the name

2021-06-16 06:45 UTC, mohanarpit commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Binding/Bind_API_with_List_Widget_spec.js
> +        expect(text).to.equal("Barty Crouch Jr");
Can we do `contains` instead of actual equals for now?

2021-06-16 06:54 UTC, hetunandu commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Binding/Bind_API_with_List_Widget_spec.js
> +        expect(text).to.equal("Barty Crouch Jr");
That wont work if someone completely changes the name

2021-06-16 07:16 UTC, arslanhaiderbuttar approved these changes

2021-06-16 07:30 UTC, mohanarpit commented
I've marked this PR as draft so that it doesn't get merged by mistake as it'll cause test failures to happen on our main branches.

2021-06-16 11:21 UTC, yatinappsmith approved these changes

2021-06-21 06:08 UTC, mohanarpit commented
@NandanAnantharamu Closing this PR as it's not the right solve for the problem. Instead of asserting a hard-coded response, we should assert the API response directly.

2021-06-21 06:08 UTC, closed without merging