fix: fixed bindings
appsmithorg/appsmith pull request #5228
Opened 2021-06-17 12:36 UTC by Tooluloope

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.

## Description

> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change.

Fixes # (issue)

> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-06-21 10:07 UTC, riodeuno requested changes

2021-06-21 10:07 UTC, riodeuno commented on app/client/src/components/designSystems/appsmith/MultiSelectComponent.tsx/index.tsx
> +          <svg
Let's make this a separate component and use it here.

2021-06-21 10:07 UTC, riodeuno commented on app/client/src/components/designSystems/appsmith/MultiSelectComponent.tsx/index.tsx
> +          document.getElementsByClassName("appsmith_widget_0")[0] as HTMLElement
Let's declare this function outside the component and use it here, so that it is not created on every component update.

2021-06-21 10:07 UTC, riodeuno commented on app/client/src/components/designSystems/appsmith/MultiSelectComponent.tsx/index.tsx
> +          zIndex: layer.portals,
Let's make this a constant outside the component and use it as a static value, so that this object is not created on every update.

2021-06-21 10:07 UTC, riodeuno commented on app/client/src/components/designSystems/appsmith/MultiSelectComponent.tsx/index.tsx
> +          <>
Let's useCallback for this function.

2021-06-21 10:07 UTC, riodeuno commented on app/client/src/components/designSystems/appsmith/MultiSelectComponent.tsx/index.tsx
> +                  paddingBottom: "10px",
Let's make this a constant outside the component so that it isn't recreated on every render.

2021-06-21 10:07 UTC, riodeuno commented on app/client/src/components/designSystems/appsmith/MultiSelectComponent.tsx/index.tsx
> +const MultiSelectContainer = styled.div``;
Let's use this wrapper for the `index.css` styles.

2021-06-21 19:45 UTC, Tooluloope commented on app/client/src/constants/AppsmithActionConstants/ActionConstants.tsx
> +  ON_MULTI_SELECT = "ON_MULTI_SELECT",
I'll remove it in the meantime.
Once we have a request for this, I'd work on it.

2021-06-23 10:33 UTC, vivekverma2312 commented
@Tooluloope Please find some observations related to select and multiselect widgets. Testing is still in progress.
Observation:
1. "Either" should not be available in select widget now
<img width="705" alt="Screenshot 2021-06-23 at 3 46 19 PM" src="https://user-images.githubusercontent.com/83569920/123080439-8b963200-d43a-11eb-95ba-d69405cd0cf6.png">

2. No error when same label is repeated
<img width="710" alt="Screenshot 2021-06-23 at 3 50 28 PM" src="https://user-images.githubusercontent.com/83569920/123080648-c8fabf80-d43a-11eb-8d8d-113bb77e2418.png">

3. Default data style in option is different for single and multi select. In case of select widget it is in form of array but for multi-select it like like radioButton widget
<img width="268" alt="Screenshot 2021-06-23 at 3 52 58 PM" src="https://user-images.githubusercontent.com/83569920/123080992-1d05a400-d43b-11eb-93c0-708bcb75fdd5.png">
<img width="273" alt="Screenshot 2021-06-23 at 3 52 46 PM" src="https://user-images.githubusercontent.com/83569920/123081006-1f67fe00-d43b-11eb-9e57-9c9cacfaab16.png">

4. Hovering of mouse on multi-select dropdown do not change the cursor properly. Can we make this similar to prod.
https://www.loom.com/share/6a43b066cdf640238aaac6e6dde7147e

5. Search is allowed but not functional in case of multi-select.
https://www.loom.com/share/ec8b89ddc8054b559c6896b1b0e33534

6. When we remove default value and placeHolder from multi-select widget then it is showing as blank
<img width="726" alt="Screenshot 2021-06-23 at 3 59 22 PM" src="https://user-images.githubusercontent.com/83569920/123081818-001da080-d43c-11eb-9d24-2a7a03cfdb07.png">

2021-06-23 11:11 UTC, somangshu commented
@vivekverma2312 please check all the linked issues, replicated/fixed for the multi-select, What you dont see in the single select should be created as a new issue and added to the `Dropdown widget` epic

2021-06-23 12:42 UTC, Tooluloope commented
@somangshu @vivekverma2312 Should we allow the same Label.
The main issue is allowing the same value which would cause an evaluation error

2021-06-23 13:11 UTC, Tooluloope commented
@vivekverma2312 All issues outlined have been resolved.
Do let me know if there are other issues. 

Thanks for spotting them.👍

2021-06-23 15:21 UTC, Tooluloope commented
@vivekverma2312 Could you explain No.6

Didn't understand the issue.

2021-06-24 06:21 UTC, vivekverma2312 commented
> @vivekverma2312 Could you explain No.6
> 
> Didn't understand the issue.

Issue 6: In case of multi-select if we remove both default value and place holder then only drop-down icon is coming. In case of select widget if we remove default value then select along with drop-down icon is displayed.

2021-06-24 06:57 UTC, vivekverma2312 commented
@Tooluloope Few more observations:
7. Place holder is not coming in option field after user clear the default data
<img width="290" alt="Screenshot 2021-06-24 at 11 34 53 AM" src="https://user-images.githubusercontent.com/83569920/123216432-28aea480-d4e7-11eb-8393-68c7dd97bba7.png">


8. Default data is not showing in options for existing widgets

<img width="722" alt="Screenshot 2021-06-24 at 12 11 57 PM" src="https://user-images.githubusercontent.com/83569920/123216359-12084d80-d4e7-11eb-9821-5442e6300357.png">

9. Select all is not coming in some cases
<img width="722" alt="Screenshot 2021-06-24 at 12 11 57 PM" src="https://user-images.githubusercontent.com/83569920/123216508-3e23ce80-d4e7-11eb-83d6-624709f5f8c2.png">

2021-06-25 18:39 UTC, Tooluloope commented
@vivekverma2312, All issues have been fixed, except No 7. The JS Convertible Editor doesn't use Placeholders

2021-06-28 09:12 UTC, vivekverma2312 commented
@Tooluloope New observations:
10. Default Input place holder for multi select  should be changed from `Favorite Hokage` to may be `--Select-- `
<img width="280" alt="Screenshot 2021-06-28 at 1 54 28 PM" src="https://user-images.githubusercontent.com/83569920/123611099-df2fc380-d81e-11eb-87e7-59af15dbf22f.png">

11. #995 Is working fine for multi-select but it is not handled for select widget

2021-06-28 09:20 UTC, Tooluloope commented
> @Tooluloope New observations:
> 
> 10. Default Input place holder for multi select  should be changed from `Favorite Hokage` to may be `--Select-- `
> 
> <img width="280" alt="Screenshot 2021-06-28 at 1 54 28 PM" src="https://user-images.githubusercontent.com/83569920/123611099-df2fc380-d81e-11eb-87e7-59af15dbf22f.png">
> 
> 
> 
> 11. #995 Is working fine for multi-select but it is not handled for select widget
> 
> 
> 
> 

@vivekverma2312 So, The Default Place holder is ```Select a Value```.
Favourite Hokage was a custom Placeholder.

For 11, A different PR is meant to be used to fix it.

2021-06-28 09:30 UTC, vivekverma2312 commented
@Tooluloope For issue 10
Please make the property name as `Placeholder`
and the default should be `select option(s)`

2021-06-28 09:58 UTC, somangshu approved these changes

2021-06-29 07:08 UTC, YogeshJayaseelan commented
@Tooluloope  we have found few more issues 

12.Click on +Option throws error 'The value at the option is invalid' for both select and multi-select widget 

https://loom.com/share/e5f3fd1eeb554be88758c80631f3854c

13. Multi-select - The default value 'Forth' should be replaced with 'Fourth' and 'Six' to be 'Sixth'

<img width="1280" alt="Screenshot 2021-06-29 at 12 33 12 PM" src="https://user-images.githubusercontent.com/35128442/123752258-3fce0780-d8d6-11eb-8e3a-0ee2afedaad1.png">

14. Multi-select -When the user tries to add new label and value to the options fields the mouse insertion pointer points to placeholder field instead of options field and whatever user types the values are directly typed into placeholder filed. (This is also applicable for the Default value field)

https://www.loom.com/share/2964b249b87c486c8d777ccc0034d23d

2021-06-29 07:29 UTC, Tooluloope commented
> 1. Fourth

All fixed, for No. 12, the Control type needs both input field filled, i.e. the Label and Value cannot be empty

2021-06-30 10:14 UTC, YogeshJayaseelan commented
@Tooluloope - verified issue 13 and 14 they are working as expected now

2021-06-30 10:37 UTC, Tooluloope commented
> @Tooluloope - verified issue 13 and 14 they are working as expected now

@YogeshJayaseelan do let me know if you require further clarification for No.12

2021-06-30 10:46 UTC, Tooluloope commented on app/client/src/utils/autocomplete/EntityDefinitions.ts
> +      "!url": "https://docs.appsmith.com/widget-reference/dropdown",
@somangshu, Do we need to separate the widgets also in the Docs  
https://docs.appsmith.com/widget-reference/dropdown

2021-06-30 12:07 UTC, vivekverma2312 commented
@Tooluloope #2733 was working before but now that is not working. Every-time we make any change in the value the option selected gets reset. Same behaviour for both select and multi-select.

2021-06-30 12:12 UTC, Tooluloope commented
> @Tooluloope #2733 was working before but now that is not working. Every-time we make any change in the value the option selected gets reset. Same behaviour for both select and multi-select.

Could you make a loom video for me to understand the issue better

2021-06-30 12:24 UTC, vivekverma2312 commented
@Tooluloope Loom video for #2733 ->  https://www.loom.com/share/2283be0339e04744af8cf33e6ecf8d0e

I also checked that #4629 is working fine for multi-select but not for select widget
https://www.loom.com/share/f762dc7736554f48806f9ddae8535f5a

2021-06-30 20:54 UTC, riodeuno requested changes

2021-06-30 20:54 UTC, riodeuno commented on app/client/src/components/designSystems/appsmith/MultiSelectComponent.tsx
> +const inputIcon = (): JSX.Element => (
Let us organize this file. We can create a folder called `MultiSelectComponent` and move the styles to a file `MultiSelectStyles`, `InputIcon`, etc. It will make this file cleaner.

2021-06-30 20:54 UTC, riodeuno commented on app/client/src/components/designSystems/appsmith/MultiSelectComponent.tsx
> +    if (Boolean(node?.closest(".bp3-modal-widget"))) {
Is this a blueprint class? If so, let us use `Classes` from `@blueprint/core` instead of `.bp3-modal-widget`

2021-06-30 20:54 UTC, riodeuno commented on app/client/src/utils/WidgetPropsUtils.tsx
>      currentDSL.version = LATEST_PAGE_VERSION;
Here we are not updating the DSL version, which will result in this migration running everytime the page loads.

2021-07-01 06:54 UTC, Tooluloope commented
> @Tooluloope Loom video for #2733 ->
> 
> https://www.loom.com/share/2283be0339e04744af8cf33e6ecf8d0e
> 
> I also checked that #4629 is working fine for multi-select but not for select widget
> 
> https://www.loom.com/share/f762dc7736554f48806f9ddae8535f5a

@vivekverma2312 , Could you confirm the issues now?

2021-07-01 07:41 UTC, riodeuno requested changes

2021-07-01 07:41 UTC, riodeuno commented on app/client/src/components/designSystems/blueprint/DropdownComponent.tsx
> +    console.log(Classes.DIALOG, "NOOOOOOOODAL");
Missed cosole.log

2021-07-01 10:12 UTC, vivekverma2312 commented
@Tooluloope Issue #2733 and #4629 is fixed.

Able to see migration issue again: For old apps the noting is coming below Option property for both select and multiselect widget.
<img width="724" alt="Screenshot 2021-07-01 at 3 39 55 PM" src="https://user-images.githubusercontent.com/83569920/124107464-e0f9c100-da82-11eb-9435-fed614f9d392.png">

2021-07-01 10:27 UTC, Tooluloope commented
> @Tooluloope Issue #2733 and #4629 is fixed.
> 
> 
> 
> Able to see migration issue again: For old apps the noting is coming below Option property for both select and multiselect widget.
> 
> <img width="724" alt="Screenshot 2021-07-01 at 3 39 55 PM" src="https://user-images.githubusercontent.com/83569920/124107464-e0f9c100-da82-11eb-9435-fed614f9d392.png">
> 
> 

Sorry didn't get that clearly

2021-07-02 12:24 UTC, riodeuno submitted a review, later dismissed

2021-07-05 12:24 UTC, somangshu approved these changes
Running tests

2021-07-06 05:05 UTC, somangshu approved these changes

2021-07-07 10:59 UTC, somangshu approved these changes

2021-07-08 08:59 UTC, somangshu approved these changes
Approving to run tests

2021-07-12 13:21 UTC, vivekverma2312 commented
@Tooluloope Can you please remove the JS beside options property for both select and multi-select widget.

<img width="715" alt="Screenshot 2021-07-12 at 5 47 46 PM" src="https://user-images.githubusercontent.com/83569920/125294690-1be0dc00-e342-11eb-856e-75dcdb107574.png">
<img width="734" alt="Screenshot 2021-07-12 at 5 42 20 PM" src="https://user-images.githubusercontent.com/83569920/125294698-1e433600-e342-11eb-9f9d-5131df5f71e1.png">

2021-07-12 20:43 UTC, Tooluloope commented
> @Tooluloope Can you please remove the JS beside options property for both select and multi-select widget.
> 
> <img alt="Screenshot 2021-07-12 at 5 47 46 PM" width="715" src="https://user-images.githubusercontent.com/83569920/125294690-1be0dc00-e342-11eb-856e-75dcdb107574.png">
> 
> <img alt="Screenshot 2021-07-12 at 5 42 20 PM" width="734" src="https://user-images.githubusercontent.com/83569920/125294698-1e433600-e342-11eb-9f9d-5131df5f71e1.png">

@vivekverma2312 Fixed

2021-07-13 10:14 UTC, vivekverma2312 commented
@Tooluloope Above issues are fixed. Please remove #4416 as this is not going in this PR.

2021-07-13 10:22 UTC, Tooluloope commented
> @Tooluloope Above issues are fixed. Please remove #4416 as this is not going in this PR.

For some reasons, I can't, Its greyed out when I try to remove it

2021-07-13 10:36 UTC, mohanarpit commented
> > @Tooluloope Above issues are fixed. Please remove #4416 as this is not going in this PR.
> 
> For some reasons, I can't, Its greyed out when I try to remove it

I've removed #4416 from this PR.

2021-07-14 05:45 UTC, riodeuno commented on app/client/src/reducers/entityReducers/widgetConfigReducer.tsx
> +import { DividerWidgetProps } from "../../widgets/DividerWidget";
We could import from absolute paths `widgets/DividerWidget`

2021-07-14 05:45 UTC, riodeuno commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/Dropdown_spec.js
> -  it("Dropdown Widget Functionality", function() {
@Tooluloope  There are multiple tests removed. I was wondering if they were added in another file?

2021-07-14 05:46 UTC, riodeuno commented on app/client/src/widgets/DropdownWidget.tsx
> +            isJSConvertible: false,
We could just remove it, if it isn't needed. But, this works as well.

2021-07-14 05:46 UTC, riodeuno approved these changes

2021-07-14 05:47 UTC, riodeuno commented
@Tooluloope I've added a couple of nit-picky comments. Please feel free to respond to them, or deal with them either in this PR or another PR.

2021-07-14 05:50 UTC, riodeuno commented on app/client/src/components/designSystems/appsmith/MultiSelectComponent/index.tsx
> +  CANVAS_CLASSNAME,
If we need the class name for a widget, we can use `generateClassName` from `src/utils/generators`

2021-07-14 05:51 UTC, riodeuno commented on app/client/src/components/designSystems/appsmith/MultiSelectComponent/index.tsx
> +  CANVAS_CLASSNAME,
Using it this way, will break things if we decided to change the way `generateClassName` prefixes the widgetIds.

2021-07-14 07:06 UTC, Tooluloope commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/Dropdown_spec.js
> -  it("Dropdown Widget Functionality", function() {
They were for the Dropdown widget.
The test just included switching selection types from single select to Multiselect which we are no longer doing, since they are now separate

2021-07-14 07:27 UTC, Tooluloope commented on app/client/src/components/designSystems/appsmith/MultiSelectComponent/index.tsx
> +  CANVAS_CLASSNAME,
Would resolve this in the serverSide PR

2021-07-14 10:33 UTC, riodeuno submitted a review, later dismissed

2021-07-14 11:46 UTC, Tooluloope commented
<img width="568" alt="Screenshot 2021-07-14 at 12 36 03" src="https://user-images.githubusercontent.com/31691737/125616789-84903349-d9f2-4fac-a129-0497525ea089.png">
<img width="561" alt="Screenshot 2021-07-14 at 12 45 29" src="https://user-images.githubusercontent.com/31691737/125616802-72d77073-4a2f-4b76-815c-7e48bf0ddbfb.png">


Tests are passing on local

2021-07-16 09:04 UTC, somangshu approved these changes
Approving to run failing tests.

@YogeshJayaseelan please check the widget icon and give the final sign off to close this

2021-07-16 09:36 UTC, somangshu commented
@Tooluloope related tests failing again, Please test locally as well

2021-07-16 09:54 UTC, Tooluloope commented
> @Tooluloope related tests failing again, Please test locally as well

@somangshu both tests are passing
<img width="662" alt="Screenshot 2021-07-16 at 10 45 28" src="https://user-images.githubusercontent.com/31691737/125929512-a6fb2283-6095-4d46-9536-4a010c3d8401.png">
<img width="686" alt="Screenshot 2021-07-16 at 10 53 38" src="https://user-images.githubusercontent.com/31691737/125929524-7523320b-3e38-43b2-b692-8d1e3cbb6ecb.png">

2021-07-19 04:05 UTC, riodeuno approved these changes

2021-07-19 10:18 UTC, somangshu approved these changes

2021-07-20 06:35 UTC, somangshu approved these changes

2021-07-21 06:22 UTC, somangshu commented on app/client/src/constants/Colors.tsx
> +  SELECT_DISABLED: "#ced9e080",
Why are we not using the generic disable colour used everywhere else. Do we really need a new variable?

2021-07-21 12:48 UTC, trishaanand approved these changes

2021-07-21 12:48 UTC, trishaanand commented
Approved for the tests to run. Not a real code review :)

2021-07-21 15:27 UTC, Tooluloope commented
/ok-to-test sha=a75672fb7bb30f9fdeafba1c3246e8d51ae35202

2021-07-22 05:05 UTC, Tooluloope commented on app/client/src/constants/Colors.tsx
> +  SELECT_DISABLED: "#ced9e080",
It was overwritten when customizing the Select Component.

2021-07-22 12:49 UTC, somangshu commented
@vivekverma2312 is there an update here, Have we tested all scenarios. 

@riodeuno can you provide a final review. We should be able to push this into the next release.

2021-07-23 05:56 UTC, riodeuno requested changes

2021-07-23 05:56 UTC, riodeuno commented on app/client/src/utils/WidgetPropsUtils.tsx
> +    currentDSL.version = 28;
The version set above is 28. This migration will never run.

2021-07-23 06:23 UTC, Tooluloope commented on app/client/src/utils/WidgetPropsUtils.tsx
> +    currentDSL.version = 28;
Fixed

2021-07-23 06:25 UTC, riodeuno approved these changes

2021-07-23 07:43 UTC, riodeuno submitted a review, later dismissed

2021-07-26 05:40 UTC, Tooluloope commented
/ok-to-test sha=fbd1d24694211797e4cb7a41c2bc83925341c75f

2021-07-26 06:53 UTC, somangshu commented
@Tooluloope if this is complete please merge it ASAP to release

2021-07-26 06:56 UTC, Tooluloope commented
> @Tooluloope if this is complete please merge it ASAP to release

Just merged @riodeuno Widget Validation Changes to this PR.
Quite a lot of conflicts 🥲🥲🥲

2021-07-26 06:58 UTC, somangshu approved these changes
Approving to run tests here. 

@riodeuno @vivekverma2312 @Tooluloope do we need another round of sanity testing here?

2021-07-26 06:58 UTC, Tooluloope commented
/ok-to-test sha=2ac599de310591fdb8db7fefd866a0b0ecc79d3d

2021-07-26 09:39 UTC, vivekverma2312 commented
@Tooluloope Observed this issue around select and multi-select widget
Now we can have duplicate data
https://www.loom.com/share/93d52abd1df0424cb2ae083cc1d48a16

Multi-select-> 
https://www.loom.com/share/d3544cb50c2643c3927d865fb0adc9fe

2021-07-26 09:48 UTC, Tooluloope commented
> @Tooluloope Observed this issue around select and multi-select widget
> Now we can have duplicate data
> 
> https://www.loom.com/share/93d52abd1df0424cb2ae083cc1d48a16
> 
> Multi-select->
> 
> https://www.loom.com/share/d3544cb50c2643c3927d865fb0adc9fe

I think it's related to the Widget Validation

2021-07-26 09:58 UTC, somangshu submitted a review, later dismissed
Running tests again.

@vivekverma2312 please confirm with @riodeuno and create new issues as required.

2021-07-27 07:26 UTC, Tooluloope commented
/ok-to-test sha=ef0f0158ed1b38aa8d669e7c26dcde7d5fae3c81

2021-07-27 13:20 UTC, riodeuno submitted a review, later dismissed

2021-07-27 18:05 UTC, Tooluloope commented
/ok-to-test sha=19745b9

2021-07-28 05:11 UTC, vivekverma2312 commented
@Tooluloope @riodeuno Duplicate label issue is fixed but there is some issue on search. After every search the drop-down options are getting repeated. It is happening for both select and multi-select.
https://www.loom.com/share/9c7b30137d49455cbadd35e56b615826

2021-07-28 05:22 UTC, Tooluloope commented
> @Tooluloope @riodeuno Duplicate label issue is fixed but there is some issue on search. After every search the drop-down options are getting repeated. It is happening for both select and multi-select.
> 
> https://www.loom.com/share/9c7b30137d49455cbadd35e56b615826

@riodeuno I think having both label and value unique is meant to be the ideal behavior?

2021-07-28 05:34 UTC, riodeuno commented
@Tooluloope The uniqueness check is for the `JSON.stringify({"label": "something", "value": "something"})` 
So, one pair of label and value should be unique. We can have the same label in two different entries. Is this the issue?

2021-07-28 05:39 UTC, Tooluloope commented
> @Tooluloope The uniqueness check is for the `JSON.stringify({"label": "something", "value": "something"})`
> So, one pair of label and value should be unique. We can have the same label in two different entries. Is this the issue?

Yeah, that's the issue
I think that's why this issue was closed https://github.com/appsmithorg/appsmith/issues/4966

2021-07-28 09:10 UTC, riodeuno submitted a review, later dismissed

2021-07-30 06:19 UTC, riodeuno approved these changes

2021-08-02 14:34 UTC, somangshu approved these changes

2021-08-02 16:32 UTC, somangshu commented
Re Ran all jobs > `Smoke_TestSuite/ClientSideTests/GenerateCRUD/GenerateCRUDPage_Spec.js` failed

2021-08-03 06:32 UTC, somangshu commented
Force merging this into release, the above test is failing consistently.

2021-08-03 06:38 UTC, merged