Feature/4088 draggable filterpane in table widget
appsmithorg/appsmith pull request #5257
Opened 2021-06-18 12:22 UTC by vibhandikyash

## Description

> As a user, I should be able to drag the filter pane on the table widget anywhere on the canvas, just like how I can do with the property pane.

Fixes #4088 

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

> Tested locally.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-06-21 05:11 UTC, somangshu commented
@vibhandikyash too many conflicts here, Kindly resolve

2021-06-21 05:15 UTC, somangshu requested changes
- The filter-pane should load inside the table view on the first load
- On click of apply do not close the filter-pane

2021-06-21 05:16 UTC, somangshu commented
@vivekverma2312 please leave your comments here. 

@vibhandikyash lets wait for the feedback and then pick everything up together

2021-06-22 11:19 UTC, YogeshJayaseelan commented
@vibhandikyash @somangshu Tested Table filter pane drag and drop functionality and raised the below bugs

#5329 and #5332

2021-06-25 07:57 UTC, vibhandikyash commented
> @vibhandikyash @somangshu Tested Table filter pane drag and drop functionality and raised the below bugs
> 
> #5329 and #5332
@YogeshJayaseelan  I've fixed both of these issues(#5329 and #5332) and committed them here.

2021-06-28 13:48 UTC, somangshu commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Binding/Widgets_form_input_table_default_validation.js
> +      //       cy.get(publish.inputWidget + " " + "input")
Please remove this if not required!

2021-06-28 13:49 UTC, somangshu commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Binding/Widgets_form_input_table_default_validation.js
> +      //       cy.get(publish.inputWidget + " " + "input")
Need to resolve the conflict as well

2021-06-28 13:52 UTC, somangshu commented
@vibhandikyash please link additional issues fixed under the same PR

2021-07-01 10:23 UTC, somangshu commented
@vibhandikyash resolve the conflicts

2021-07-06 05:35 UTC, YogeshJayaseelan commented
@vibhandikyash Verified bug fixes 5332 and 5329 and they are working as expected.

2021-07-06 18:36 UTC, vibhandikyash commented
/ok-to-test sha=0e9d7a3

2021-07-07 05:38 UTC, somangshu submitted a review, later dismissed

2021-07-07 05:44 UTC, somangshu approved these changes

2021-07-07 07:04 UTC, marks0351 commented
<img width="594" alt="Screenshot 2021-07-07 at 12 31 41 PM" src="https://user-images.githubusercontent.com/35134347/124714497-7a135680-df1f-11eb-8ea3-38e01c0bd751.png">
The move icon covers the help text. can u pls check @vibhandikyash

2021-07-07 07:41 UTC, marks0351 commented
I have reviewed the code @vibhandikyash it looks great. 

Code solution feedback:
I think that having the tab filter pane movements on the app state might not be recommended. Do you think we can handle all this within the table widget by creating an internal state instead?

Bugs I found: 
 - Help text overlap which I have commented
 - Not able to select any other widget when table filter pane is open.

also cud u get the filter utils part reviewed from @riodeuno 
pls do resolve the conflicts as well.

2021-07-07 07:43 UTC, marks0351 requested changes
Added review comments, pls check.

2021-07-07 07:54 UTC, marks0351 commented
@vibhandikyash pls do add jest and cypress tests validating the feature.

2021-07-07 08:22 UTC, vivekverma2312 commented
> <img alt="Screenshot 2021-07-07 at 12 31 41 PM" width="594" src="https://user-images.githubusercontent.com/35134347/124714497-7a135680-df1f-11eb-8ea3-38e01c0bd751.png">
> 
> The move icon covers the help text. can u pls check @vibhandikyash

Looked at the loom video of issues #5329 & #5332 reported by yogesh and observed that this was working fine when @YogeshJayaseelan was testing this. Can we figure out how this issue got introduced and is there any way we can catch such issues which got introduced after giving signoff.
cc: @somangshu

2021-07-07 08:43 UTC, somangshu commented
@vivekverma2312 the change probably was introduced because of the a merge conflict resolution. @vibhandikyash we need to verify this

2021-07-08 10:42 UTC, somangshu approved these changes

2021-07-12 13:55 UTC, somangshu commented
@vicky-primathon need your help to fix failing test and merge conflict, we need to close this, @vibhandikyash is not available for a couple weeks.

2021-07-15 11:42 UTC, closed without merging

2021-07-15 12:09 UTC, vicky-primathon commented
Continuing the feature here https://github.com/appsmithorg/appsmith/pull/5886

2021-07-17 13:52 UTC, YogeshJayaseelan commented
@vibhandikyash @vicky-primathon @somangshu 
Verified the fixes and the following issues are working as expected

1) #5329 - Verified
2) #5332 - Verified
3) Help text overlap - Verified
4) Not able to select(by clicking on the widget) any other widget when table filter pane is open - Verified

**New issue:**
5) Filter functionality is not working as expected - ID ends with 1 or First-name ends with e

For the above table data use the following sample api and bind with the table data - https://reqres.in/api/users?page=2

https://loom.com/share/1514c5e725b343c290e65b82cd478f6c

6) Can we have clear button inside the filter pane so that without removing the existing filter user can clear the data

2021-07-19 09:46 UTC, somangshu commented
@YogeshJayaseelan please continue the conversation in the main/new thread/PR