Issue 5040 - Server Readme Update for new intellij version
appsmithorg/appsmith pull request #5263
Opened 2021-06-19 23:46 UTC by alzaar

## Description
When setting up the local server setup, the setup fails to run on Intellij and requires additional configuration on Intellij for the server to start.

Fixes # (issue)
This PR is in regards to this issue - [Issue](https://github.com/appsmithorg/appsmith/issues/5040)

## Type of change
ServerSetup.md  has been modified as this contains the server setup instructions for running the server locally on Intellij.  The screen grabs regarding the additional intellij configuration are also added. No information has been removed.

- This change requires a documentation update

## How Has This Been Tested?
Emulation of the entire local sever setup has been done a few times in order record any missing steps and no further issue was found.

2021-06-21 05:03 UTC, abhvsn requested changes
Can we point the branch to **appsmithorg:release** instead of **appsmithorg:master**? 
We follow this practice in Appsmith to avoid pushing bugs in production 🙂

2021-06-21 05:07 UTC, nayan-rafiq commented
@alzaar I've updated the target branch to `release` from `master`. Would you please rebase from `release` and push it again?

2021-06-27 01:35 UTC, alzaar commented on contributions/ServerSetup.md
> +Here is the configuration settings for new intellij versions. After configuring settings as mentioned above, please also add the following to your intellij setup.
Thanks for pointing it out. I added the version and edited it :)

2021-06-27 01:37 UTC, alzaar commented on contributions/ServerSetup.md
> +In case ther server doesn't work with the above config then one may try the following and thrn try running the server locally.
I agree, however initially when I followed the instructions and ran the commands it didn't work for me. I added the note in case anyone wants to try this and then try running the server locally. For now, I have removed it.

2021-06-27 01:41 UTC, alzaar commented
@nayan-rafiq Hey! Could please help me out with a rebase walk through ? I have not used it often. I tried following the git docs and ran `git rebase release` which made me go through the conflicts manually. Then I ran `git rebase -Xtheirs release` which added the incoming code automatically. Hence, we see the above commits. Worst case, we can close this PR and I can open a new one.

2021-06-29 09:33 UTC, nayan-rafiq commented
@alzaar For a small change like this, I think it would be eaiser to create a new branch from release, cherry pick the commit for the documentation changes and send a new PR.

2021-07-01 12:04 UTC, mohanarpit commented
I'm closing this PR because I think it's easier to open another PR by forking from release and just copying the README changes over. This PR has too many conflicts and changes in it.

2021-07-01 12:04 UTC, closed without merging