Feature/create page from db table
appsmithorg/appsmith pull request #5269
Opened 2021-06-20 17:38 UTC by abhvsn

Keeping this in the draft state as TCs are still pending

## Description

Using this feature user can create an admin panel page with a single click after the user has connected the datasource in Appsmith

Fix #4649 

## Type of change

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

## How Has This Been Tested?

> Tested manually with the rest API.
> TCs are pending

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Existing unit tests pass locally with my changes

2021-06-22 09:54 UTC, nayan-rafiq requested changes

2021-06-22 09:54 UTC, nayan-rafiq commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/CreateDBTablePageSolution.java
> +    public CreateDBTablePageSolution(NewPageService newPageService,
Same here. I suggest to use `@RequiredArgsConstructor`

2021-06-23 10:35 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/CreateDBTablePageSolution.java
> +    public CreateDBTablePageSolution(NewPageService newPageService,
Yeah also, you'll need to mark all those private service variables in this class as `final` or the `RequiredArgsConstructor` annotation won't work 😄

2021-06-23 10:38 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/PageController.java
> +    public Mono<ResponseDTO<PageDTO>> createCRUDPage(@RequestBody Object resource) {
I see that we are casting this to a `HashMap` in the service method. Does it not work if we set the type of `resource` as `Map` here, instead of Object? If we set it as `Object`, I suspect arrays, strings and numbers (which are all valid JSON) will also be sent to the service method where it'll throw a class cast exception resulting in a 500 error.

If it doesn't work with using `Map` here (I have a small feeling it might not), then let's do a check for `resource instanceof Map` before proceeding to casting it into a `HashMap`. (Also, may be we can just cast it to `Map`?).

2021-06-23 10:49 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/PageController.java
> +    public Mono<ResponseDTO<PageDTO>> createCRUDPage(@RequestBody Object resource) {
Actually, looks like we'll be better off here with a small DTO class. Please create a DTO class with just `applicationId`, `tableName` and `datasourceName` fields and use that DTO class here instead of `Object` or `Map`. Then you can check if `applicationId` is null or the others are null and act accordingly. This way, Spring will validate that these fields, if present in the payload JSON, are indeed strings and not some nasty things that'll cause our API to break. It'll also make it easier to read, since when we see an Object here, it can hold anything so it doesn't convey anything to the reader. If we specify a DTO object, it'll explicitly state what we are expecting and what types the fields need to be.

2021-06-23 10:55 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/CreateDBTablePageSolution.java
> +    private Mono<NewPage> getPage(String applicationId, String pageId, String tableName) {
Can we name this method `getOrCreatePage`? I _almost_ misunderstood its purpose and _almost_ lost my sanity over it. 😉

2021-06-23 11:01 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/CreateDBTablePageSolution.java
> +                    .filter(datasource -> datasource.getStructure() != null && !datasource.getStructure().getTables().isEmpty())
Just so we don't get an NPE when `.getTables` is `null`.

```suggestion
                    .filter(datasource -> datasource.getStructure() != null && !CollectionUtils.isEmpty(datasource.getStructure().getTables()))
```

2021-06-23 11:02 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/CreateDBTablePageSolution.java
> +        if (tableObject.get("tableName") == null || tableObject.get("datasourceName") == null) {
Is there a reason we are getting the datasource name from the client instead of the datasource ID? The ID would be simpler to deal with no?

2021-06-23 11:05 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/CreateDBTablePageSolution.java
> +    private Mono<NewPage> getPage(String applicationId, String pageId, String tableName) {
Yes already done that. I realised that after pushing the code, my bad!

2021-06-23 11:05 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/CreateDBTablePageSolution.java
> +                    .next()
If the table is not found in the datasource structure, are we sending a `Table not found` error? Sorry if we are, I couldn't find it.

2021-06-23 11:13 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/CreateDBTablePageSolution.java
> +                Map data = (Map) obj;
Along with the `isEmpty` check we are doing just below, can we do an `obj instanceof Map` check as well?

2021-06-23 11:16 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/CreateDBTablePageSolution.java
> +        final Pattern pattern = Pattern.compile(fieldRegex);
Let's make this pattern a static constant in the clas.

2021-06-23 11:20 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/CreateDBTablePageSolution.java
> +                    if (pageDTO.getName().matches("^" + pageName + ".*")) {
If we are creating a page for the table `products`, we are trying to name the page as `Products`, correct? So we are checking if a page by that name already exists and adding a numerical suffix, if it does.

If my understanding above is correct, then this regex is a bit too lax. It'll match the page named `Products Main` also, which we don't want. Something like the below might work better?

```suggestion
                    if (pageDTO.getName().matches("^" + Pattern.quote(pageName) + "\d*$")) {
```

2021-06-23 11:22 UTC, sharat87 commented
@abhvsn, I haven't delved into the depths of the implementation and the logic, but from what I see, I like this. I've put some comments for a few things that I consider only minor quibbles. Please take a look and let me know again so I can mark as approved. Thanks!

2021-06-23 11:23 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/CreateDBTablePageSolution.java
> +        if (tableObject.get("tableName") == null || tableObject.get("datasourceName") == null) {
Yeah seems like a good option. Somewhere in my mind I was thinking of moving away from Ids.

2021-06-23 19:08 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/CreateDBTablePageSolution.java
> +                Map data = (Map) obj;
I didn't get you here. Do you mean like this
```
for (Object obj : children) {
                Map data = (Map) obj;
                JSONObject object = new JSONObject();
                // If the children tag exists and there are entries within it
                if (!CollectionUtils.isEmpty(data) && obj instanceof Map) {
                    object.putAll(data);


```
If yes wouldn't be the obj will always be the instanceof Map only at that line, which makes it true always.

2021-06-23 19:09 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/CreateDBTablePageSolution.java
> +    public CreateDBTablePageSolution(NewPageService newPageService,
So `final` is what I was missing. Thanks didn't know this. I'll update the code

2021-06-23 19:11 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/PageController.java
> +    public Mono<ResponseDTO<PageDTO>> createCRUDPage(@RequestBody Object resource) {
Creating a separate DTO makes sense here. Updating the code as per suggestion.

2021-06-24 07:09 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/CreateDBTablePageSolution.java
> +                Map data = (Map) obj;
I was thinking more about checking *before* the typecast, like:

```suggestion
                if (!(obj instanceof Map)) {
                    log.error("Non-map item in DSL Children");
                    continue;
                }
                Map data = (Map) obj;
```

2021-06-24 07:58 UTC, sharat87 approved these changes
Looks good, please squash merge once CI is done. Thanks!

2021-06-24 09:28 UTC, merged