Widget Property Validation structure
appsmithorg/appsmith pull request #5270
Opened 2021-06-20 20:49 UTC by riodeuno

## Description
Add platform feature to use configurations for simple and complex validations. Allows use of functions by widget developers to validate complex properties.

Fixes #5054 

Todo: #5065 

## Type of change

- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How Has This Been Tested?

In progress: Unit tests for new validations

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-06-28 06:05 UTC, riodeuno commented
/ok-to-test sha=748019b

2021-06-29 07:23 UTC, vivekverma2312 commented
@riodeuno Please check #5465 for issues on this deploy preview.

2021-06-30 06:59 UTC, hetunandu requested changes

2021-06-30 06:59 UTC, hetunandu commented on app/client/src/components/editorComponents/CodeEditor/EvaluatedValuePopup.tsx
> +  expected?: { type: string; example: any };
Use unknown instead of any

2021-06-30 06:59 UTC, hetunandu commented on app/client/src/components/editorComponents/CodeEditor/EvaluatedValuePopup.tsx
> +  expected?: { type: string; example: any };
Use unknown instead of any

2021-06-30 06:59 UTC, hetunandu commented on app/client/src/components/editorComponents/CodeEditor/index.tsx
> +  expected?: { type: string; example: any };
Use unknown instead of any

2021-06-30 06:59 UTC, hetunandu commented on app/client/src/components/propertyControls/ComputeTablePropertyControl.tsx
> +  expected?: { type: string; example: any };
Use unknown instead of any

2021-06-30 06:59 UTC, hetunandu commented on app/client/src/components/propertyControls/InputTextControl.tsx
> +  expected?: { type: string; example: any };
Use unknown instead of any

2021-06-30 06:59 UTC, hetunandu commented on app/client/src/constants/PropertyControlConstants.tsx
> +  expected?: { type: string; example: any };
Use unknown instead of any

2021-06-30 06:59 UTC, hetunandu commented on app/client/src/utils/WidgetFactory.tsx
> +function validatePropertyPaneConfig(config: PropertyPaneConfig[]) {
Can we make this generic so that actions can also use this?

2021-06-30 06:59 UTC, hetunandu commented on app/client/src/utils/validation/common.ts
> +};
Since we already have this, let's use the type everywhere we have set `example` to any

2021-06-30 06:59 UTC, hetunandu commented on app/client/src/utils/validation/common.ts
> +        example: config.params?.expected?.example || "No Example available",
Let's set a constant and a top level default here when no example or type is available so that it can be read in the Evaluated value. We can then not show those collapsed views itself

2021-06-30 06:59 UTC, hetunandu commented on app/client/src/utils/validation/common.ts
> +        // console.log(JSON.parse(unescape(type)));
Left out comments

2021-06-30 06:59 UTC, hetunandu commented on app/client/src/workers/DataTreeEvaluator.ts
> +      console.log({ e });
Remove console log from here

2021-06-30 06:59 UTC, hetunandu commented on app/client/src/workers/DataTreeEvaluator.ts
> +    const start = performance.now();
We are already tracking time taken by all of validation

2021-06-30 06:59 UTC, hetunandu commented on app/client/src/workers/evaluationUtils.ts
> +    console.log("Trying to validate property without existing validation:", {
Should be an error

2021-06-30 06:59 UTC, hetunandu commented on app/client/src/workers/validations.ts
> +        console.log("Validation function error: --", { e });
Should be an error

2021-06-30 06:59 UTC, hetunandu commented on app/client/src/workers/validations.ts
> +        console.log("Error when validating: ", { e });
Should be logged as an error

2021-07-08 20:18 UTC, riodeuno commented on app/client/src/utils/WidgetFactory.tsx
> +function validatePropertyPaneConfig(config: PropertyPaneConfig[]) {
I'm not sure what you mean by making this generic. Please move these functions as necessary for the changes in the actions validations.

2021-07-08 20:34 UTC, riodeuno commented
/ok-to-test sha=ae53c2d

2021-07-09 06:20 UTC, riodeuno commented
/ok-to-test sha=8197dd4

2021-07-11 02:43 UTC, riodeuno commented
/ok-to-test sha=eee7583

2021-07-12 12:16 UTC, riodeuno commented on app/client/src/components/editorComponents/CodeEditor/CodeEditor.test.tsx
> +// // import CodeEditor from "./index";
Re-enable this test.

2021-07-12 12:19 UTC, jsartisan submitted a review, later dismissed

2021-07-12 12:32 UTC, marks0351 submitted a review, later dismissed

2021-07-13 05:07 UTC, marks0351 approved these changes

2021-07-13 05:35 UTC, marks0351 submitted a review, later dismissed

2021-07-13 06:25 UTC, hetunandu approved these changes

2021-07-16 05:39 UTC, marks0351 approved these changes

2021-07-16 05:49 UTC, marks0351 approved these changes

2021-07-19 14:44 UTC, marks0351 approved these changes

2021-07-20 06:02 UTC, somangshu submitted a review, later dismissed

2021-07-21 05:55 UTC, SatishGandham approved these changes
Approving for tests.

2021-07-22 17:25 UTC, mohanarpit submitted a review, later dismissed

2021-07-22 19:56 UTC, riodeuno commented
/ok-to-test sha=ff3414a

2021-07-23 04:56 UTC, jsartisan approved these changes

2021-07-23 08:17 UTC, YogeshJayaseelan commented
@riodeuno Retested this feature and all the issues are fixed and working as expected.

2021-07-26 05:50 UTC, merged