FIX #3229 : added new props shortcuts and closeOnSelection for smooth interactions
appsmithorg/appsmith pull request #5276
Opened 2021-06-21 07:51 UTC by vibhandikyash

## Description
> Added new options for shortcuts and closeOnSelection for smooth interactions

Fixes #3229 

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

> Tested locally.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-06-21 08:55 UTC, somangshu approved these changes
Approving for tests to run

2021-06-23 12:53 UTC, mohanarpit commented
@vibhandikyash Can you please check if this test failure is legitimate? Also, please merge the latest release into your branch to ensure that you have all the test fixes available to you. Let's get this PR merged!

2021-06-28 05:25 UTC, SatishGandham submitted a review, later dismissed

2021-06-28 07:58 UTC, somangshu commented
@mohanarpit the failing test is not related. @NandanAnantharamu can you confirm. Rerunning it also failed

2021-06-28 07:59 UTC, mohanarpit commented
> @mohanarpit the failing test is not related. @NandanAnantharamu can you confirm. Rerunning it also failed

Nandan is working on this on #5441

2021-06-28 08:35 UTC, NandanAnantharamu commented
> > @mohanarpit the failing test is not related. @NandanAnantharamu can you confirm. Rerunning it also failed
> 
> Nandan is working on this on #5441

this is merged now , can you try again and check

2021-06-28 11:21 UTC, somangshu submitted a review, later dismissed

2021-06-30 12:44 UTC, vivekverma2312 commented
@vibhandikyash Please check the issues observed in the deploy preview:
1. Clicking on shortcut options close the calendar irrespective of `closeOnSelection` toggle
https://www.loom.com/share/23ca4f54847b4915a53ac5a1dd0afa8d

2. Calendar do not close when `closeOnSelection` is enabled and user click on Today or Clear
https://www.loom.com/share/e5e707e2835d4e01a7395abe828e06fa

2021-07-08 10:28 UTC, somangshu commented
@vibhandikyash please update us here about this

2021-07-14 12:30 UTC, somangshu commented
@vivekverma2312 @techbhavin 
- Regardless of the `closeOnSelection` clicking on shortcuts should close the calendar.  This is blueprint default as well. So consider this as **intended behaviour** 
- Since clear is not a date selection we have go with the blueprint default of keeping the datepicker open. When it comes to `today`, This seems like a bug, the datepicker popover only closes when the datepicker input is empty. 

Kindle discuss this to clear all confusion so that we can close this feature.

2021-07-15 11:46 UTC, techbhavin commented
@somangshu  @vivekverma2312  

In my Observation `today` button click popover is not the closed reason behind this; we set props `timePrecision`.  when we removed it, the popover is working fine.

please let me know your thoughts on it so I can make changes accordingly.

2021-07-16 10:31 UTC, somangshu commented
This seems to be the default behaviour now, @vivekverma2312 can we have a chat to understand what is right here and take the final call

2021-07-16 10:55 UTC, somangshu approved these changes

2021-07-19 07:40 UTC, SatishGandham requested changes

2021-07-19 07:40 UTC, SatishGandham commented on app/client/src/components/designSystems/blueprint/DatePickerComponent2.tsx
> +    const clickedContent = get(e, "target.innerText");
This check is not correct. The date picker will not close if we click on any widget instead of empty space.

2021-07-20 03:40 UTC, SatishGandham requested changes

2021-07-20 03:40 UTC, SatishGandham commented on app/client/src/components/designSystems/blueprint/DatePickerComponent2.tsx
> +      const $parent = document.getElementsByClassName(
This would fail if there are two datepickers.
You should do the reverse. First get the target, and check if target has darange-picker as target.

2021-07-20 03:40 UTC, SatishGandham commented on app/client/src/widgets/DatePickerWidget2.tsx
> +            helpText: "Decide to show shortcuts menu",
@somangshu , Should this be decide or choose?

2021-07-20 05:31 UTC, somangshu commented on app/client/src/widgets/DatePickerWidget2.tsx
> +            helpText: "Decide to show shortcuts menu",
@techbhavin we can change this to > `Choose to show shortcut menu`

2021-07-20 12:53 UTC, SatishGandham approved these changes

2021-07-22 10:44 UTC, vivekverma2312 commented
@vibhandikyash Deploy preview tested and working as expected.

2021-07-22 12:46 UTC, merged