[WIP] - Widget Grouping Context Menu
appsmithorg/appsmith pull request #5284
Opened 2021-06-21 11:03 UTC by jsartisan

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.

## Description

> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change.

Fixes # (issue)

> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-06-28 07:44 UTC, marks0351 requested changes

2021-06-28 07:44 UTC, marks0351 commented on app/client/src/pages/Editor/WidgetsMultiSelectBox.tsx
> +  z-index: 4;
Can we have this added to layers constant?

2021-06-28 07:44 UTC, marks0351 commented on app/client/src/pages/Editor/WidgetsMultiSelectBox.tsx
> +              onClick={stopEventPropagation}
is this needed for the other actions as well?

2021-06-30 05:37 UTC, marks0351 submitted a review, later dismissed

2021-06-30 11:38 UTC, vivekverma2312 commented
@jsartisan 
1. Cut widgets in container and then paste it — it is getting pasted outside the container
https://www.loom.com/share/134d01dcc29b43e9836618a4a70fc901

2. Context menu is not visible if widgets are selected inside container/Form which at the corner and scroll is enabled
<img width="752" alt="Screenshot 2021-06-30 at 4 16 47 PM" src="https://user-images.githubusercontent.com/83569920/123954130-a716b500-d9c5-11eb-89bf-786ab36790ad.png">

2021-07-07 05:25 UTC, vivekverma2312 commented
@jsartisan Deploy preview has been tested and working fine.

2021-07-08 06:30 UTC, merged