Full entity name will shown in a popover, when user hovers on it.
appsmithorg/appsmith pull request #5315
Opened 2021-06-21 18:05 UTC by pranavkanade

## Description
Currently we only shorten the entity name before listing it in entity pane. This adds a functionality to show its full name if user hovers on it.

Fixes # (issue)
#4764 

## Type of change
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
Manually

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-06-22 04:59 UTC, RakshaKShetty commented
@pranavkanade the tooltip looks fine but if you see the screen shot there is space displayed before the page name 
![image](https://user-images.githubusercontent.com/45958978/122865706-7048fb00-d344-11eb-8107-a8575acddbf7.png)

2021-06-22 06:21 UTC, rishabhsaxena requested changes
@pranavkanade 
I remembered we have a util: `utils/helpers/isEllipsisActive`

```
/**
 * checks if ellipsis is active
 * this function is meant for checking the existence of ellipsis by CSS.
 * Since ellipsis by CSS are not part of DOM, we are checking with scroll width\height and offsetidth\height.
 * ScrollWidth\ScrollHeight is always greater than the offsetWidth\OffsetHeight when ellipsis made by CSS is active.
 *
 * @param element
 */
export const isEllipsisActive = (element: HTMLElement | null) => {
  return (
    element &&
    (element.offsetWidth < element.scrollWidth ||
      element.offsetHeight < element.scrollHeight)
  );
};
```

I guess we could use this to conditionally show the tooltip instead?

2021-06-27 14:49 UTC, rishabhsaxena approved these changes

2021-06-27 22:27 UTC, pranavkanade commented
@Rishabh-Rathod extracted tooltip wrapped entity name component. Please review once.

2021-06-27 22:27 UTC, pranavkanade commented
/ok-to-test=a10d488

2021-06-27 22:29 UTC, pranavkanade commented
/ok-to-test sha=a10d488

2021-06-28 04:58 UTC, rishabhsaxena approved these changes

2021-06-28 05:50 UTC, pranavkanade commented
/ok-to-test sha=a10d488

2021-06-28 09:58 UTC, Rishabh-Rathod commented on app/client/src/pages/Editor/Explorer/Entity/index.tsx
> +const EntityNameWithTooltip = React.memo(function(
As all the props of `<Entity />` are passed to `<EntityNameWithTooltip {...props} />`, React.memo won't we able to avoid re-render of `<EntityNameWithTooltip />` whenever a function passed as a props to `<Entity />` is redefined which is not actually consumed also.

It would be better to only pass parent props that are consumed inside `<EntityNameWithTooltip />`

2021-06-28 09:58 UTC, Rishabh-Rathod commented on app/client/src/pages/Editor/Explorer/Entity/index.tsx
>      const handleClick = (e: any) => {
small suggestion, instead of `(e: any)`, we could use `(e: React.MouseEvent)`.

2021-07-21 11:31 UTC, pranavkanade commented
PR has gone stale. Will fix the issue with different PR.

2021-07-21 11:31 UTC, closed without merging