FIX #4676 : added onclick handler and update property pane config to table widget for column type image
appsmithorg/appsmith pull request #5331
Opened 2021-06-22 10:38 UTC by vibhandikyash

## Description

> Added onclick handler and update property pane config to table widget for column type image

Fixes #4676 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Tested locally.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-06-28 05:03 UTC, SatishGandham commented
@techbhavin , What is the purpose of isSelected? Why we don't want click on a selected row?

2021-06-28 06:34 UTC, vibhandikyash commented
@SatishGandham When the row is selected and user clicks on the image at that time onRowSelected handler was getting called unnecessarily and used stoppropogation to handle that.

2021-07-01 02:33 UTC, SatishGandham requested changes

2021-07-01 02:33 UTC, SatishGandham commented on app/client/src/components/designSystems/appsmith/TableComponent/TableUtilities.tsx
> +                      !!onClick && onClick();
We don't need this check here as we have set a default for onclick.
Looks good otherwise.

2021-07-02 11:29 UTC, vibhandikyash commented
/ok-to-test sha=748e38d

2021-07-06 05:00 UTC, YogeshJayaseelan commented
@vibhandikyash Tested this feature and it is working as expected

2021-07-06 18:34 UTC, vibhandikyash commented
/ok-to-test sha=1f81b6d

2021-07-07 05:54 UTC, SatishGandham approved these changes

2021-07-07 06:12 UTC, somangshu commented
@vibhandikyash related jest tests are failing. Kindly look into this

2021-07-08 05:36 UTC, vibhandikyash commented
/ok-to-test sha=2c77baf

2021-07-09 07:06 UTC, somangshu approved these changes
Approving to rerun the tests now

2021-07-09 10:49 UTC, somangshu approved these changes

2021-07-09 12:21 UTC, merged