Feature/widget grouping 4
appsmithorg/appsmith pull request #5389
Opened 2021-06-24 12:10 UTC by marks0351

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.

## Description

> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change.

Fixes # (issue)

> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-07-20 04:51 UTC, marks0351 commented
/ok-to-test sha=cee27ea

2021-07-20 04:53 UTC, marks0351 commented
/ok-to-test sha=cee27ea4bec945d5dc413da25a3bad6602998192

2021-07-20 04:55 UTC, riodeuno approved these changes
Approving for cypress tests

2021-07-20 11:56 UTC, riodeuno approved these changes
Approved for tests to run.

2021-07-23 07:57 UTC, riodeuno submitted a review, later dismissed
Approving for tests

2021-07-23 09:55 UTC, riodeuno approved these changes

2021-07-23 12:25 UTC, jsartisan approved these changes

2021-07-26 11:40 UTC, riodeuno requested changes

2021-07-26 11:40 UTC, riodeuno commented on app/client/src/utils/hooks/useCanvasDragToScroll.ts
> +      const checkIfNeedsScroll = (e: any) => {
Let's move these functions outside of `useEffect` and  wrap them in `useCallback`. No point re-creating functions within a useEffect.

2021-07-26 11:40 UTC, riodeuno commented on app/client/src/sagas/DraggingCanvasSagas.ts
> +  const widgets = cloneDeep(allWidgets);
Can we use immer to produce immutable objects, instead of cloning the whole widgets list. This seems quite inefficient. We can pick this up in a separate PR, if it is lengthy.

2021-07-26 11:40 UTC, riodeuno commented on app/client/src/sagas/DraggingCanvasSagas.ts
> +  const stateWidgets: CanvasWidgetsReduxState = cloneDeep(allWidgets);
Once again, can we pick up the task of using immer instead?

2021-07-26 11:40 UTC, riodeuno commented on app/client/src/sagas/DraggingCanvasSagas.ts
> +  const stateWidgets: CanvasWidgetsReduxState = cloneDeep(allWidgets);
Also, for some reason we're cloning all widgets in `moveWidgetSaga` as well as `moveWidget` which is run in a loop inside a `reduce` call.

2021-07-26 11:40 UTC, riodeuno commented on app/client/src/pages/common/CanvasSelectionArena.tsx
> +        props.id === "canvas-0" ? props.theme.canvasBottomPadding : 0}px
Is `canvasBottomPadding` used somewhere else? If not, can we simply use it here as a constant?

2021-07-26 11:40 UTC, riodeuno commented on app/client/src/pages/common/CanvasSelectionArena.tsx
> +      const init = () => {
Let's try to move function definitions outside of the `useEffect` block

2021-07-26 11:40 UTC, riodeuno commented on app/client/src/pages/common/CanvasSelectionArena.tsx
> +            console.count("onScroll");
Let's remove this `console.count`.

2021-07-28 05:27 UTC, marks0351 commented on app/client/src/components/editorComponents/WidgetNameComponent/index.tsx
> +    selectedWidgets.includes(props.widgetId);
This selectedWidgets state changes a lot so i thought performance will degrade if we add memoize.

2021-07-28 05:29 UTC, marks0351 commented on app/client/src/components/editorComponents/ResizableComponent.tsx
> +      updated = !!updateDropTargetRows(props.widgetId, bottom);
so post-updating new rows we do further collision checks, so not sure how to go about this. we might need a separate on demand collision check in case of rowUpdates not sure if I can pick that up in this PR.

2021-07-28 05:32 UTC, marks0351 commented on app/client/src/constants/WidgetConstants.tsx
> +export const DroppableWidgets: WidgetType[] = [
yea widget config was my first thought, the reason i chose to have it as a constant is that i cud avoid a migration. is there a way I cud add it as part of config without a migration?

2021-07-28 05:36 UTC, marks0351 commented on app/client/src/reducers/uiReducers/dragResizeReducer.ts
> +    state.dragDetails = {
there are some additional keys that we have in dragDetails when we do a new widget drag so to avoid carefully updating them I have updated the entire object.

2021-07-28 06:09 UTC, marks0351 commented on app/client/src/pages/common/CanvasSelectionArena.tsx
> +        props.id === "canvas-0" ? props.theme.canvasBottomPadding : 0}px
it is used in widget editor as well, this the extra padding that we give to widgets editor.

2021-07-28 07:00 UTC, marks0351 commented on app/client/src/constants/WidgetConstants.tsx
> +export const DroppableWidgets: WidgetType[] = [
Added isDroppableWidget as a meta property now. removed the constant.

2021-07-28 07:01 UTC, marks0351 commented on app/client/src/utils/helpers.tsx
> +  const scrollChildBounds = child.getBoundingClientRect();
I have a solution thought of using resize observer like the way we do for dynamic layout update. I can create a task for this.

2021-07-28 09:36 UTC, riodeuno submitted a review, later dismissed

2021-07-29 06:09 UTC, marks0351 commented on app/client/src/constants/WidgetConstants.tsx
> +export const DroppableWidgets: WidgetType[] = [
reverted the meta property change for now to handle it in widget api.

2021-07-29 13:13 UTC, jsartisan submitted a review, later dismissed

2021-07-30 04:05 UTC, YogeshJayaseelan commented
@marks0351 verified the bug fix 5541 and now user is able to place table inside tabs and move within tabs - working as expected

2021-07-30 06:30 UTC, riodeuno approved these changes

2021-07-30 09:15 UTC, YogeshJayaseelan commented
@marks0351 Verified this fix - Now the cursor pointer is placed appropriately so that the big widgets can be placed inside container

2021-08-02 05:45 UTC, riodeuno approved these changes

2021-08-02 05:59 UTC, YogeshJayaseelan commented
@marks0351 Verified the fix for #4100 generated table widget from api doesn't break but still the generated list widget from API breaks page

<img width="1680" alt="Screenshot 2021-08-02 at 11 03 18 AM" src="https://user-images.githubusercontent.com/35128442/127811282-3a1dd577-0ec0-4d39-bca5-cf028bd60f41.png">

2021-08-02 07:19 UTC, YogeshJayaseelan commented
@marks0351 Verified the fix for #2035 and it is working as expected

2021-08-02 09:01 UTC, YogeshJayaseelan commented
@marks0351 Verified the fix for #3730 and it is working as expected now

2021-08-03 05:25 UTC, riodeuno submitted a review, later dismissed

2021-08-03 10:32 UTC, jsartisan submitted a review, later dismissed

2021-08-03 11:49 UTC, jsartisan approved these changes

2021-08-04 05:02 UTC, jsartisan approved these changes

2021-08-04 10:44 UTC, jsartisan approved these changes

2021-08-06 05:26 UTC, jsartisan submitted a review, later dismissed

2021-08-08 14:32 UTC, jsartisan submitted a review, later dismissed

2021-08-09 06:21 UTC, YogeshJayaseelan commented
@marks0351 verified the fix for #4100 - Now the page doesn't breaks on generating List, Table, Chart widgets from API. But while generating list widget from API the generated list widget focus on canvas is not happening whereas the focus is happening for table or chart widget 

https://loom.com/share/a1dd3cef8eff4ba78c05fc0de3f95a0a

2021-08-09 07:19 UTC, YogeshJayaseelan commented
@marks0351 Added new issue #6469 - https://github.com/appsmithorg/appsmith/issues/6469

2021-08-09 11:17 UTC, YogeshJayaseelan commented
@marks0351 - Sometimes the non selected widgets disappears when few of the widgets are selected and moved out of canvas

https://www.loom.com/share/a3558507105e44f59b0c74c7c4711913

2021-08-10 11:21 UTC, YogeshJayaseelan commented
> https://loom.com/share/a1dd3cef8eff4ba78c05fc0de3f95a0a

@marks0351 raised separate issue for auto focus #6511 and hence closing #4100

2021-08-10 11:24 UTC, YogeshJayaseelan commented
@marks0351 verified issues #4100 , #6469, #6263, #6504 and they are working as expected now

2021-08-12 05:15 UTC, jsartisan approved these changes

2021-08-12 05:17 UTC, YogeshJayaseelan commented
@marks0351 @somangshu Verified this feature and related bug fixes and this is good to go

2021-08-12 05:45 UTC, merged