Update email notification template when there is comment
appsmithorg/appsmith pull request #5392
Opened 2021-06-24 13:09 UTC by nayan-rafiq

## Description
When an user adds a new comment or mentions other users, an email is sent to the subscribers of the thread. This PR changes the html template of the email message. It also fixes the comment thread url that's included in the email.

Fixes #5349 

## Type of change
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
- Unit tests
- Tested on local dev machine

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-06-24 14:07 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/resources/email/commentAddedTemplate.html
> +																		{{^Resolved}}a comment on <br />{{/Resolved}}
There should be a space between these two `{{#NewComment}}added `  right ? 

I have noticed that instead `<br>` you are using `<br />` in the new template. Just curious to know the intention behind that.

2021-06-25 05:47 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/EmailEventHandler.java
> +        if(userRole.getRole().equals(AppsmithRole.ORGANIZATION_VIEWER)) {
On the rare off chance that we'll have to deal with unnecessary NPE's, when using `.equals` with a constant, let's have the constant on the left. This way, even if `.getRole` starts returning `null` next year, it'll just be false and not throw an NPE.

```suggestion
        if (AppsmithRole.ORGANIZATION_VIEWER.equals(userRole.getRole()) {
```

2021-06-25 05:52 UTC, sharat87 commented on app/server/appsmith-server/src/main/resources/email/commentAddedTemplate.html
> +																		{{^Resolved}}a comment on <br />{{/Resolved}}
I'm _thinking_, the reason is for mail-client compatibility? The situation with mail clients is much _much_ worse than the situation of browser compatibility. I'm guessing there's some crazy mail client out there like Outlook Web Mail or Thunderbird or Apple Mail even, that doesn't understand `<br>` well enough? Just hypothesizing though, I'll let Nayan respond to this 😄

2021-06-25 06:09 UTC, nayan-rafiq commented on app/server/appsmith-server/src/main/resources/email/commentAddedTemplate.html
> +																		{{^Resolved}}a comment on <br />{{/Resolved}}
No specific reason for using `<br />`, it should be `<br>`.

2021-06-25 06:37 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/resources/email/userTaggedInCommentTemplate.html
> +																		<b>{{Commenter_Name}}</b>, mentioned you in a comment on <br />
I missed to highlight this. Sorry 😞 . Except this everything LGTM

2021-06-25 10:05 UTC, nayan-rafiq commented on app/server/appsmith-server/src/main/resources/email/userTaggedInCommentTemplate.html
> +																		<b>{{Commenter_Name}}</b>, mentioned you in a comment on <br />
This is not used though. I'll delete the file instead.

2021-06-25 10:10 UTC, AnaghHegde approved these changes
LGTM

2021-06-25 11:03 UTC, sharat87 approved these changes
Looks good to be merged. Please squash merge once the CI is finished. Thanks!

2021-06-25 11:05 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/EmailEventHandler.java
> +        if (AppsmithRole.ORGANIZATION_VIEWER.equals(userRole.getRole()) {
```suggestion
        if (AppsmithRole.ORGANIZATION_VIEWER.equals(userRole.getRole())) {
```

2021-06-25 11:06 UTC, sharat87 requested changes
@nayan-rafiq Looks like there's a compile error. Please push a fix and I'll approve again :)

2021-06-25 11:31 UTC, nayan-rafiq commented
> @nayan-rafiq Looks like there's a compile error. Please push a fix and I'll approve again :)

Fixed the compile error

2021-06-25 11:34 UTC, mohanarpit commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/EmailEventHandler.java
> +        if (AppsmithRole.ORGANIZATION_VIEWER.equals(userRole.getRole())) {
Quick question: Why are we checking against the user's role rather than their permission? I'm asking this because if we ever move permissions around between roles, this check will fail. Please correct me if my assumption is wrong here.

2021-06-25 11:47 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/EmailEventHandler.java
> +        if (AppsmithRole.ORGANIZATION_VIEWER.equals(userRole.getRole())) {
I'd say the reason is simplicity of the implementation. For instance, if we were to check the policy, let's say we check if the user has the manage policy on the application. Do we also check the manage policy on the page? On the comment thread in particular also? What if we check only the application, and turns out we introduce page-level access control. Policies felt too granular for this and this user role seemed to capture the spirit of what we needed here. Which is essentially, _can this user open edit mode_. Does that make sense?

Although, after reading your comment, I don't feel as strongly here. I'm okay with doing policy checks instead of this.

2021-06-25 11:57 UTC, mohanarpit commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/EmailEventHandler.java
> +        if (AppsmithRole.ORGANIZATION_VIEWER.equals(userRole.getRole())) {
We should stay away from role checks as a thumb rule. This ensures that we can create more granular roles, custom roles etc in the future. Doing checks like this prevents us from extending this in the future.

2021-06-25 12:12 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/EmailEventHandler.java
> +        if (AppsmithRole.ORGANIZATION_VIEWER.equals(userRole.getRole())) {
Understood. In that case, @nayan-rafiq, can we check for the manage policy on this application here instead of the role?

2021-06-25 19:07 UTC, nayan-rafiq commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/EmailEventHandler.java
> +        if (AppsmithRole.ORGANIZATION_VIEWER.equals(userRole.getRole())) {
@sharat87 @mohanarpit I've updated the PR and checked the application policy here. Would you please have a look again?

2021-06-29 07:24 UTC, sharat87 submitted a review, later dismissed
Looks good to be merged. Please squash merge once the CI is finished. Thanks!

2021-06-29 08:58 UTC, mohanarpit reviewed
A couple of nitpicks from my side. None of these comments are a blocker.

2021-06-29 08:58 UTC, mohanarpit commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/EmailEventHandler.java
> +        templateParams.put("inviteUrl", getCommentThreadLink(
Nitpick: Can we rename the variable in the template from `inviteUrl` to `commentUrl` ? Makes it clear in the template & code what it's being used for.

2021-06-29 08:58 UTC, mohanarpit commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/EmailEventHandler.java
> +                    emailMonos.add(getEmailSenderMono(userRole, commentThread, originHeader, organization, application));
Nitpick: We have overloaded functions that send different emails templates. One sends emails when a thread is resolved while the other sends for comment updates. Can we name the functions as such to describe that they are actually different functions?

2021-06-29 09:39 UTC, mohanarpit approved these changes

2021-06-30 10:36 UTC, nayan-rafiq commented
@sharat87 I just rebased from release to fix the failing tests. Need approval again.

2021-06-30 11:41 UTC, sharat87 approved these changes
Looks good to be merged. Please squash merge once the CI is finished. Thanks!

2021-06-30 14:46 UTC, merged