datepicker 2 migration 27 added, default response udpated
appsmithorg/appsmith pull request #5393
Opened 2021-06-24 13:30 UTC by techbhavin

## Description

>  add iso date formate for default min and max date and add migration script for change default min and max date for already exists component

Fixes #4945 

## Type of change

- Bugfix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [  ] I have commented my code, particularly in hard-to-understand areas
- [  ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [  ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-06-28 13:53 UTC, somangshu commented
/ok-to-test sha=26c654c

2021-06-30 19:00 UTC, riodeuno requested changes

2021-06-30 19:00 UTC, riodeuno commented on app/client/src/utils/WidgetPropsUtils.tsx
> +    currentDSL.type === WidgetTypes.DATE_PICKER_WIDGET2 &&
@techbhavin This does not go into the children. the first `currentDSL` here will be the `widgetId: "0"` entry, which will never be a datepicker widget. We need to add a recursion here for the `currentDSL.children`. Please check out the other migrations.

2021-07-06 07:36 UTC, riodeuno commented on app/client/src/utils/WidgetPropsUtils.tsx
> +        migrateDatePickerMinMaxDate(eachWidgetDSL);
Does this function mutate the DSL in the argument? If this is not mutating, but returning, then this won't work. We will need to use `map` instead of `forEach`

2021-07-06 07:37 UTC, riodeuno requested changes

2021-07-06 07:37 UTC, riodeuno commented on app/client/src/utils/WidgetPropsUtils.tsx
> +        migrateDatePickerMinMaxDate(eachWidgetDSL);
Does this function mutate the DSL in the argument? If this is not mutating, but returning, then this won't work. We will need to use `map` instead of `forEach`

2021-07-07 09:35 UTC, vivekverma2312 commented
@techbhavin Please rebuild the deploy preview after taking latest pull from release branch. Currently we are not able to open applications on safari due to issue #5480

2021-07-08 09:36 UTC, somangshu approved these changes

2021-07-09 11:02 UTC, YogeshJayaseelan commented
@somangshu Verified this and working as expected

2021-07-11 02:01 UTC, riodeuno commented on app/client/src/utils/WidgetPropsUtils.tsx
> +        migrateDatePickerMinMaxDate(eachWidgetDSL);
I believe this function is mutating, as we have confirmed that this migration is working. So we have two options. We revert back to `forEach` as it is mutating, or continue using `map` and not assume that this function will always mutate the DSL.

``` 
currentDSL.children = currentDSL.children.map(
      (eachWidgetDSL: ContainerWidgetProps<WidgetProps>) => {
        return migrateDatePickerMinMaxDate(eachWidgetDSL);
      },
    );

2021-07-14 07:34 UTC, riodeuno approved these changes

2021-07-16 07:04 UTC, merged