Triggers post page load actions in the editor
appsmithorg/appsmith pull request #5430
Opened 2021-06-26 10:20 UTC by aswathkk

## Description

After fetching the page, the necessary actions such as loading the data were done only for published pages. In this PR, I've added the support for the unpublished pages to do the same.

Fixes #5247 

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Manually verified by switching the pages in the editor view and confirmed that the API calls to get data were being made or not.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-06-28 05:12 UTC, hetunandu requested changes
Thanks for your contribution! You are on the right track but need to handle another case.

2021-06-28 05:12 UTC, hetunandu commented on app/client/src/sagas/PageSagas.tsx
> +      );
This will end up executing page load action twice when first starting an app on the first page. This is because we already call this action when initializing the editor. Check [here](https://github.com/appsmithorg/appsmith/blob/9c75596957323aa05c91c5762cabf9887dc456dc/app/client/src/sagas/InitSagas.ts#L137). 

If we can pass some payload indicating if this fetchPage is the first or consequent, we can conditionally add this postEvalAction to make it work as expected

2021-06-29 15:48 UTC, aswathkk commented on app/client/src/sagas/PageSagas.tsx
> +      );
@hetunandu  Great finding.
To implement what you suggested, I think we need to keep track of whether it is first or consequent fetchPage somewhere. (Is there any simple way to do that in ReduxSaga?)

How about removing `executePageLoadActions` from `initializeEditorSaga`?
We are anyways calling `executePageLoadActions` after loading the page via `fetchPageSaga`. Am I correct?

2021-06-29 15:52 UTC, hetunandu commented on app/client/src/sagas/PageSagas.tsx
> +      );
You can pass isFirstLoad boolean in the payload of the action which you would get in the saga. Pass it when calling from the initEditorSaga

I had added it in the initialisation flow because we wanted to wait for some configs before we execute the first onPageLoad actions. For page switch, these configs would already be present

2021-06-30 06:01 UTC, hetunandu approved these changes

2021-06-30 06:52 UTC, hetunandu commented
/ok-to-test sha=5a89db1

2021-06-30 07:19 UTC, hetunandu commented
Everything looks good @aswathkk! Thanks for this contribution 😁

2021-06-30 07:19 UTC, merged

2021-06-30 07:20 UTC, hetunandu commented
@all-contributors please add @aswathkk as a contributor for code