Updating state on componentDidUpdate
appsmithorg/appsmith pull request #5476
Opened 2021-06-29 14:11 UTC by ayushpahwa

## Description

The `Add To` dropdown that appears when auth type is chosen as `API Key` for a `REST API` datasource, the default value was not being displayed. The issue was with `componentDidUpdate` call. It was only updating the initial values for the drop downs that were displayed when `OAuth2` was selected. Added the same check for `API Key` too.

Fixes #5406 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-06-29 18:55 UTC, hetunandu requested changes
Refactor needed

2021-06-29 18:55 UTC, hetunandu commented on app/client/src/pages/Editor/DataSourceEditor/RestAPIDatasourceForm.tsx
> +    console.log("Ayush", authentication);
Missed console log

2021-06-29 18:55 UTC, hetunandu commented on app/client/src/pages/Editor/DataSourceEditor/RestAPIDatasourceForm.tsx
> +      this.props.change("authentication.addTo", "header");
Use an enum for header. I think this is already defined somewhere

2021-06-29 18:55 UTC, hetunandu commented on app/client/src/pages/Editor/DataSourceEditor/RestAPIDatasourceForm.tsx
> +      return false;
Why return false or true

2021-06-29 18:55 UTC, hetunandu commented on app/client/src/pages/Editor/DataSourceEditor/RestAPIDatasourceForm.tsx
> +      return true;
No need to return here as well

2021-06-30 05:51 UTC, ayushpahwa commented on app/client/src/pages/Editor/DataSourceEditor/RestAPIDatasourceForm.tsx
> +      return false;
I followed the codebase that was here before. I just assumed this to be a requirement for the redux form. Also, from the behaviour I noticed, when we do call the props.change function, the redux-form libraries itself re-renders the form. This is why the return false was added.

2021-06-30 05:52 UTC, ayushpahwa commented on app/client/src/pages/Editor/DataSourceEditor/RestAPIDatasourceForm.tsx
> +      return true;
This was done because I did not want to block the lifecycle of any other update. componentDidUpdate should return true or false when update is happening. If the update is not related to our test cases, it should be returning true, right?

2021-06-30 06:01 UTC, ayushpahwa commented on app/client/src/pages/Editor/DataSourceEditor/RestAPIDatasourceForm.tsx
> +    console.log("Ayush", authentication);
Fixed with new commit.

2021-06-30 06:01 UTC, ayushpahwa commented on app/client/src/pages/Editor/DataSourceEditor/RestAPIDatasourceForm.tsx
> +      this.props.change("authentication.addTo", "header");
Fixed with new commit.

2021-06-30 06:12 UTC, hetunandu commented on app/client/src/pages/Editor/DataSourceEditor/RestAPIDatasourceForm.tsx
> +      return true;
You are thinking of `shouldComponentUpdate`.  It does not matter what you return from `componentDidUpdate`. I think we should remove this as it confuses

2021-06-30 06:13 UTC, hetunandu commented on app/client/src/pages/Editor/DataSourceEditor/RestAPIDatasourceForm.tsx
> +    console.log("Ayush", authentication);
Still see it in the diff. Not pushed yet?

2021-06-30 09:30 UTC, ayushpahwa commented on app/client/src/pages/Editor/DataSourceEditor/RestAPIDatasourceForm.tsx
> +      return true;
Oh damn, yes you are right. Have fixed this!

2021-06-30 09:33 UTC, hetunandu approved these changes

2021-07-05 06:21 UTC, merged