Feature/page order - Include order in get pages API
appsmithorg/appsmith pull request #5477
Opened 2021-06-29 14:20 UTC by AnaghHegde

## Description

This adds the `order` filed to the getPages API to support page reorder persistence. 

Fixes #2786

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Manually via postman
- Unit Tests

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

2021-06-29 14:29 UTC, sharat87 requested changes

2021-06-29 14:29 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/NewPageServiceImpl.java
> +                            List<ApplicationPage> currentPage = pages.stream().filter(page -> page.getId().equals(pageNameIdDTO.getId())).collect(Collectors.toList());
The user is in the view mode here, so we should get page information from `.getPublishedPages` instead of `.getPages`, which is what we seem to be doing here. In the `else` clause below, we should be using `.getPages`, which is correct. Can we change to using `.getPublishedPages` here?

2021-06-29 14:37 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/NewPageServiceImpl.java
> +                            List<ApplicationPage> currentPage = pages.stream().filter(page -> page.getId().equals(pageNameIdDTO.getId())).collect(Collectors.toList());
Yes, thats correct. My bad 🤦‍♂️

2021-06-29 19:00 UTC, trishaanand commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/NewPageServiceImpl.java
> +                    List<ApplicationPage> publishedPages = tuple.getT3().getPublishedPages();
Since pagesFromDb field would be published pages in case of view mode and unpublished pages in case of edit mode, do we need to read publishedPages again when it is being used only in case of view mode? pagesFromDb would have the published pages in that case.

2021-06-29 19:03 UTC, trishaanand commented
A general question around introduction of order field (and something which can totally be ignored). We, today, store all the pages of an application inside the application object as a List which means that the order of the items would be preserved.  Could we not use the index of each page in this list as an indication of the order?

2021-06-30 04:42 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/NewPageServiceImpl.java
> +                    List<ApplicationPage> publishedPages = tuple.getT3().getPublishedPages();
@sharat87 Correct me if i am wrong. You are right. Based on the view mode respective set of pages are fetched from db. But the reason behind using `publishedPages` and `pages` is for the `order` field, which is available only in `Application` collection. And the order can be different in view and edit mode. Does that make sense ?

2021-06-30 04:57 UTC, AnaghHegde commented
@trishaanand Didn't think of this - Using the index of the pages stored inside the Application object. But the only question is does mongo preserve the order ? What i meant is -  if i just reorder the page objects and try to update the document, does mongo consider it as an update ? because except the order/index of those objects nothing else is changed right ?

2021-06-30 06:43 UTC, trishaanand commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/NewPageServiceImpl.java
> +                    List<ApplicationPage> publishedPages = tuple.getT3().getPublishedPages();
Actually if you check lines 203-208, you would see that we are returning either the published pages or the unpublished ones from the application object depending on the view mode requested. So pagesFromDb would contain either published or unpublished pages depending on the view mode.

2021-06-30 06:50 UTC, sharat87 commented
@trishaanand, hey, good question, thanks for asking. I actually started the implementation this way with the hope that MongoDB's native queries will let me do atomic operations to increment and decrement the order numbers, as opposed to requiring the whole list to be updated in the DB. I wasn't able to figure out a way to do that, although I still think its possible. If we use the index for ordering, we'll need to reorder the entries in the list and MongoDB doesn't have queries to do that natively, so I chose this way in hopes that we might be able to send inc and dec instructions to MongoDB to change the order numbers. 😄

2021-06-30 06:53 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/NewPageServiceImpl.java
> +                    List<ApplicationPage> publishedPages = tuple.getT3().getPublishedPages();
The `pagesFromDb` field comes from the `newPage` collection, those objects don't have the order number with them. We need the `ApplicationPage` objects which contain the order information and put those into the page objects in `pagesFromDb`.

2021-06-30 06:57 UTC, trishaanand commented
> @trishaanand, hey, good question, thanks for asking. I actually started the implementation this way with the hope that MongoDB's native queries will let me do atomic operations to increment and decrement the order numbers, as opposed to requiring the whole list to be updated in the DB. I wasn't able to figure out a way to do that, although I still think its possible. If we use the index for ordering, we'll need to reorder the entries in the list and MongoDB doesn't have queries to do that natively, so I chose this way in hopes that we might be able to send inc and dec instructions to MongoDB to change the order numbers. 😄

That sounds fair except that changing the order number would require updates to all the other pages as well whose order would be after the updated page's order. That could mean multiple database updates. If we are able to figure out a db query which would update the order of the page in question as well as all the others, then that would be the best. But the problem with this approach is all the post processing that we need to be doing instead of just moving an entry in a list to the appropriate position and let the List data structure take care of everything else. That might make the code easy to read/debug. Just a thought.

2021-06-30 07:23 UTC, sharat87 commented
@trishaanand, yeah, just thinking about this more and more, it feels like just using the indexes might be simpler for what we need here. I must say I was suffering from an acute case of over-engineering syndrome there. 😞

Thanks for sharing though.

2021-06-30 07:52 UTC, sharat87 approved these changes

2021-06-30 07:54 UTC, sharat87 reviewed
@AnaghHegde, the tests seem to be failing due to an NPE. Please take a look.

Regarding having a separate `order` field or leveraging the order of pages in the list, I'll leave the call to you. If it's a simple change to switch to using the indices, feel free to make the change. I'm fine with either implementation at this point, in the interest of time.

2021-06-30 08:14 UTC, AnaghHegde commented
> @AnaghHegde, the tests seem to be failing due to an NPE. Please take a look.
> 
> Regarding having a separate `order` field or leveraging the order of pages in the list, I'll leave the call to you. If it's a simple change to switch to using the indices, feel free to make the change. I'm fine with either implementation at this point, in the interest of time.

This test is failing for all the PR's. Abhijeet is working on that. 
W.r.t `order` field, This requires some effort both on UI and backend and its not a small change. I am afraid i cant spend time on this right now, i am occupied with other tasks.

2021-07-19 12:40 UTC, closed without merging