Improved label, updating navigateTo default prams when action type is changed to navigateTo in JS actions
appsmithorg/appsmith pull request #5532
Opened 2021-07-01 11:05 UTC by ayushpahwa

## Description

Resolution for Issues with NavigateTo functionality
- Changed label to improve clarity that the input can be either page name or external URL
- Added default string `'{}'` to Query Params field since without it if navigation target is selected

Fixes #3125 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-07-01 12:53 UTC, hetunandu requested changes
<img width="484" alt="Screenshot 2021-07-01 at 6 20 23 PM" src="https://user-images.githubusercontent.com/12022471/124127352-40fb6200-da99-11eb-94fb-017ed978123a.png">

- The name would also need a default since now the function is invalid with a default in the second parameter onwards
- The format of query parameters is wrong. It is `"{}"` but it should be `{}`

2021-07-01 13:21 UTC, ayushpahwa commented
> * The name would also need a default since now the function is invalid with a default in the second parameter onwards
Should I set the default as Page1? I was thinking of setting it but then felt it was out of place in the rest of the system.

> * The format of query parameters is wrong. It is `"{}"` but it should be `{}`
I tested it with how it is being saved before this. It copied how the system is storing it. Also, I am storing it with single quotes

![image](https://user-images.githubusercontent.com/8526215/124131253-3e027080-da9d-11eb-9101-c0d7e006d644.png)

2021-07-09 11:12 UTC, ayushpahwa commented
@hetunandu for the requested changes
1) Adding hashbang as the default value works as intended
2) I changed the default value of query params to `{}` but didn't remove the extra curly braces because they were causing confusion and autocomplete was not working

2021-07-12 07:04 UTC, hetunandu approved these changes

2021-07-12 07:52 UTC, merged