Task/5463 Navigation Bar menu Dropdown
appsmithorg/appsmith pull request #5575
Opened 2021-07-04 17:24 UTC by rahulramesha

## Description

This includes navigation bar dropdown changes

Fixes #5463 

## Type of change

> Please delete options that are not relevant.

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Manual UI Verification

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-07-05 05:31 UTC, rahulramesha commented
/ok-to-test sha=78f869c

2021-07-05 11:16 UTC, rahulramesha commented
/ok-to-test sha=29dd30b

2021-07-05 15:23 UTC, rahulramesha commented
/ok-to-test sha=cc74a3c

2021-07-06 10:25 UTC, rahulramesha commented
/ok-to-test sha=4758bad

2021-07-06 16:22 UTC, rahulramesha commented
/ok-to-test sha=b2753d1

2021-07-08 06:34 UTC, rishabhsaxena requested changes
Few minor comments, rest LGTM!

2021-07-08 06:34 UTC, rishabhsaxena commented on app/client/src/index.css
> +
Is there any workaround apart from using `!important`? I think there's an issue that is solved with `Popover2`, setting a `className` directly to the portal is fixed, we could try that as well

also just for ref: we also have some popover related styles within `globalStyles`

2021-07-08 06:34 UTC, rishabhsaxena commented on app/client/src/pages/Editor/EditorAppName/NavigationMenuData.ts
> +          text: "Current Deploy Version",
```suggestion
          text: "Current Deployed Version",
```

2021-07-08 06:34 UTC, rishabhsaxena commented on app/client/src/pages/Editor/EditorAppName/NavigationMenuData.ts
> +      style: { color: "#F22B2B" },
nitpick: we could use a color constant here

2021-07-08 06:34 UTC, rishabhsaxena commented on app/client/src/pages/Editor/EditorAppName/index.tsx
> +  font-size: 14px;
nitpick: we can use `getTypographyByKey` from `DefaultTheme` here instead of using the `font-size`

2021-07-08 06:34 UTC, rishabhsaxena commented on app/client/src/pages/Editor/EditorAppName/index.tsx
> +            fillColor="#858282"
nitpick: could use a color constant or theme variable

2021-07-08 14:18 UTC, rahulramesha commented on app/client/src/index.css
> +
Was able to add a different classname to the portal with Popover2

2021-07-08 14:21 UTC, rahulramesha commented on app/client/src/pages/Editor/EditorAppName/index.tsx
> +            fillColor="#858282"
Changed

2021-07-08 14:21 UTC, rahulramesha commented on app/client/src/pages/Editor/EditorAppName/index.tsx
> +  font-size: 14px;
Changed

2021-07-09 06:30 UTC, rishabhsaxena approved these changes
LGTM!

2021-07-09 06:30 UTC, rishabhsaxena commented on app/client/src/components/ads/EditableTextSubComponent.tsx
> +    min-width: auto !important;
nitpick: here does increasing the priority remove the need for `!important`, using multiple `&&&&` ?

2021-07-09 06:44 UTC, rahulramesha commented on app/client/src/components/ads/EditableTextSubComponent.tsx
> +    min-width: auto !important;
It should work and actually works for my usecase without the `!important`. But this component was originally part of EditableText.tsx, I simply broke it down into two for reusability and did not touch what was originally present. Since it is being used in other places, I'm not aware under what circumstances the original author intended it.

2021-07-12 06:53 UTC, rahulramesha commented
/ok-to-test sha=705178d

2021-07-13 13:17 UTC, rahulramesha commented
/ok-to-test sha=b9194ba

2021-07-13 13:26 UTC, rishabhsaxena submitted a review, later dismissed

2021-07-14 06:58 UTC, rahulramesha commented
/ok-to-test sha=950e20e

2021-07-15 06:07 UTC, rahulramesha commented
/ok-to-test sha=0d40a46

2021-07-15 06:08 UTC, rishabhsaxena approved these changes

2021-07-15 08:03 UTC, YogeshJayaseelan commented
@rahulramesha We have retested the fix and navigations are working as expected.

We have tested the below following navigations

Rename
Deploy --> Deploy -->Current Deploy Version
Shortcuts
Help -->Community forum --> Discord Channel --> Github --> Documentation
Delete
Edit and toggle

2021-07-15 10:56 UTC, merged