Refactor Get mock-data set API
appsmithorg/appsmith pull request #5620
Opened 2021-07-05 16:49 UTC by AnaghHegde

## Description

We need to support the on prem instances as well for mock data set workflow. The main problem in achieving this with migration script is that DatabaseChangelog class doesn’t have access to any of the spring services. Hence we will not be able to create a template datasource for these mock datasets using datasourceService.create. Directly inserting them in the datasource collection in a migration would mean hardcoding the datasource structure in a migration, as well as including the passwords of mock databases in plaintext in the migration’s source code.
So we had to involve cloud service where we store the mock database credentials and available mock datasets in its database.
Right now the GET mocks on the backend-server gets these info from appsmith mongo database. With the new flow this will call cloud service API and cache this info for 2hrs approximately. Now when the user clicks on create mock data -
Current flow clones the datasource from the template datasource.
New flow will fetch the necessary credentials from the cloud services API and then calls create method of datasource service class

Fixes #5582 

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Unit Tests
- Manual Test via postman

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-07-07 07:37 UTC, AnaghHegde commented
@nayan-rafiq @sharat87 Ready for review. Want to get this to merged to release tomorrow :)

2021-07-07 08:19 UTC, sharat87 requested changes
In addition to the comments, can we add tests for the creation of mock datasources?

2021-07-07 08:19 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/DatasourceServiceImpl.java
> +        if (name.equals("movies")) {
Is there a reason we are hardcoding the database name here? Can we instead use the plugin package name to identify if this is MongoDB or Postgres?

2021-07-07 08:19 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/DatasourceServiceImpl.java
> +            getMockDataSet().block();
Calling `.block` in a reactive flow will cause the threads to hold up waiting for a resource and will lose all benefits of reactive code. Lets refactor this to not need the call to `.block`.

2021-07-07 08:19 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/DatasourceServiceImpl.java
> +    public Mono<List<MockDataSet>> getMockDataSet() {
Is it possible move the code dealing with mock datasets to a separate service/solution, instead of using the `DatasourceService` for this? It feels like a distinct functionality and this service can focus on CRUD functionality for datasources. It'll also be easier to navigate since this class is already quite big.

2021-07-07 08:19 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/MockDataSet.java
> +    String datasource;
Can we change the name of the variable here? It's named `datasource`, but the type is `String`, so, is it the datasource name or the datasource id or something else?

2021-07-07 08:19 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/MockDataCredentials.java
> +    String dbname;
We don't seem to have a way to differentiate mock datasets that talk to a database vs an API. Can we add a field like plugin type to this class or the `MockDataSet` class?

2021-07-07 08:22 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/DatasourceServiceImpl.java
> +        if (name.equals("movies")) {
This change is already done. I was waiting to push it along with unblocking call.

2021-07-07 08:23 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/DatasourceServiceImpl.java
> +    public Mono<List<MockDataSet>> getMockDataSet() {
But this is also creating datasource right ? Hence i thought of adding it here. I will move this to a different service class.

2021-07-07 09:16 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/DatasourceServiceImpl.java
> +    public Mono<List<MockDataSet>> getMockDataSet() {
Indeed it does. In fact, so does the `cloneDatasource` method we were previously using. But since they form a distinct feature, it helps to have them in separate files.

Besides, this method falls back to the `create` method of Datasource service to create the datasource, instead of doing it by itself, so I think it's okay. Does that make sense?

2021-07-07 09:18 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/DatasourceServiceImpl.java
> +    public Mono<List<MockDataSet>> getMockDataSet() {
Yeah i agree with you on that.

2021-07-07 11:24 UTC, AnaghHegde commented
@sharat87 Ready for review.

2021-07-07 20:39 UTC, rishabhsaxena submitted a review, later dismissed
Frontend changes LGTM!

2021-07-08 04:26 UTC, AnaghHegde commented
@sharat87 Ready for review :)

2021-07-08 05:19 UTC, sharat87 approved these changes
Looks good to be merged. Please squash merge once the CI is finished. Thanks!

2021-07-08 05:59 UTC, merged