Support for Google reCaptcha v2 in Button Widget
appsmithorg/appsmith pull request #5638
Opened 2021-07-06 10:38 UTC by vicky-primathon

## Description
Added support for Google reCaptcha v2 in Button Widget

Fixes #5553 

## Type of change
- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How Has This Been Tested?

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-07-06 12:47 UTC, somangshu commented
Notes for testing:
- Sample site key: `6LcdjnsbAAAAAMyz2ExbRfNjI509ZRpbiLQz8agp` (V3) (works on the this deploy preview)
- The `button.recaptchaToken` should be available once the captcha verification has completed
- Check the same for **V2**

2021-07-06 12:53 UTC, somangshu approved these changes
@vicky-primathon Looks good functionally, Please check the above comments.

Approving to run the tests.

@vivekverma2312 we need sign off on this urgently, this will be shipped outside the release cycle.

2021-07-06 12:53 UTC, somangshu commented on app/client/src/components/designSystems/blueprint/ButtonComponent.tsx
> +const RecaptchButtonWrapper = styled.div`
What is this required for?

2021-07-06 12:53 UTC, somangshu commented on app/client/src/components/designSystems/blueprint/ButtonComponent.tsx
> +              // Handle corrent key with wrong
Rectify comments to says what is exactly handled

2021-07-07 06:07 UTC, vicky-primathon commented on app/client/src/components/designSystems/blueprint/ButtonComponent.tsx
> +const RecaptchButtonWrapper = styled.div`
To wrap google recaptcha element with button element

2021-07-07 06:15 UTC, somangshu approved these changes

2021-07-07 07:38 UTC, vivekverma2312 commented
@vicky-primathon `recaptchaToken` is not getting created for reCaptha v2 on deploy preview. Can you please check.

2021-07-07 12:13 UTC, vicky-primathon commented
@vivekverma2312  issue is fixed can you review again. Also pls enable Google reCAPTCHA v2 toggle in Button widget to test for Google reCAPTCHA v2.

2021-07-07 13:20 UTC, vicky-primathon commented
/ok-to-test sha=7791aeb

2021-07-07 13:35 UTC, somangshu submitted a review, later dismissed
Looks good, Running tests.

One change required > The captcha UI should be in the bottom right corner!
<img width="362" alt="Screenshot 2021-07-07 at 7 03 07 PM" src="https://user-images.githubusercontent.com/11089579/124768351-3851d280-df56-11eb-8d40-2180b1f7e6e1.png">

2021-07-07 13:38 UTC, somangshu commented
@vivekverma2312 can you check this again on an urgent basis?

2021-07-07 13:42 UTC, vicky-primathon commented
> Looks good, Running tests.
> 
> One change required > The captcha UI should be in the bottom right corner!
> <img alt="Screenshot 2021-07-07 at 7 03 07 PM" width="362" src="https://user-images.githubusercontent.com/11089579/124768351-3851d280-df56-11eb-8d40-2180b1f7e6e1.png">

@somangshu  did you test this on latest deploy preview ? Working fine for me on editor and deploy preview.

2021-07-07 14:00 UTC, vivekverma2312 commented
@vicky-primathon @somangshu Deploy preview is working fine with google reCaptcha v2. The captha UI is coming at the rightside bottom of the page. But debugger icon overlaps the captcha UI.
<img width="1787" alt="Screenshot 2021-07-07 at 7 23 00 PM" src="https://user-images.githubusercontent.com/83569920/124772266-82888300-df59-11eb-9fa0-9a27d807aeb4.png">

2021-07-07 14:01 UTC, vivekverma2312 commented
It is displayed as below and on hovering cursor it expands.
<img width="369" alt="Screenshot 2021-07-07 at 7 31 00 PM" src="https://user-images.githubusercontent.com/83569920/124772687-df843900-df59-11eb-991f-2c79b96453a9.png">

2021-07-07 14:13 UTC, somangshu commented
@vivekverma2312 is the position is alright we need not bother about the captcha UI, Our UI is primary here.

2021-07-07 14:27 UTC, somangshu commented
We need documentation change here @vihar @vicky-primathon

2021-07-07 17:38 UTC, vicky-primathon commented
/ok-to-test sha=e118096

2021-07-08 04:25 UTC, vivekverma2312 commented
@vicky-primathon Deploy preview is tested and it's working fine.

2021-07-08 05:22 UTC, somangshu approved these changes
Looks good, Approving to run tests after changes

2021-07-08 05:22 UTC, somangshu commented on app/client/src/components/designSystems/blueprint/ButtonComponent.tsx
> -  const checkValidJson = (inputString: string): boolean => {
This was introduced so that the button widget does not crash while loading an invalid captcha.

@vivekverma2312 can we check to see if this is handled.

2021-07-08 05:32 UTC, vicky-primathon commented on app/client/src/components/designSystems/blueprint/ButtonComponent.tsx
> -  const checkValidJson = (inputString: string): boolean => {
@somangshu  this code is not removed. We are still checking the key for Google recaptcha v3

2021-07-08 05:39 UTC, somangshu commented on app/client/src/components/designSystems/blueprint/ButtonComponent.tsx
> -  const checkValidJson = (inputString: string): boolean => {
Want about V2?

2021-07-08 05:42 UTC, SatishGandham requested changes
Hi @vicky-primathon , The change I asked for was related to the click handler.
In v3 it is a inline function, and in v2 it's different.

Can you extract the clickhandler in v3 to its own function instead of inline.

Thank you :)

2021-07-08 06:09 UTC, SatishGandham approved these changes

2021-07-08 06:19 UTC, vicky-primathon commented on app/client/src/components/designSystems/blueprint/ButtonComponent.tsx
> -  const checkValidJson = (inputString: string): boolean => {
For v2, we are using react-google-recaptcha npm library

2021-07-08 06:51 UTC, vivekverma2312 commented
@vicky-primathon If we enter any random text in google recatcha property and enable Google reCAPTCHA v2 property the recatcha ui is displayed overlapping button widget and throws error.
https://www.loom.com/share/bc93c6b524d84d43b530b06d1f5f643e

2021-07-08 10:05 UTC, somangshu commented on app/client/src/components/designSystems/blueprint/ButtonComponent.tsx
> +  const [isInValidKey, setInvalidKey] = useState(false);
should be `isInvalidKey`

2021-07-08 10:05 UTC, somangshu approved these changes

2021-07-08 10:36 UTC, somangshu approved these changes

2021-07-08 11:08 UTC, vivekverma2312 commented
@vicky-primathon Issue related to invalid captcha is also fixed for reCaptcha v2. It's looks good to be merged in release.
cc: @somangshu

2021-07-08 12:02 UTC, merged