Increased maxium image size to be uploaded as profile picture
appsmithorg/appsmith pull request #5641
Opened 2021-07-06 10:51 UTC by nayan-rafiq

## Description
We had a limit on the image size that can be uploaded as profile picture. The maximum allowed size is 244KB. This PR increases the allowed image size to 3MB in frontend and 1MB in backend.  

Fixes #5041 

## Type of change
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
- Unit tests
- Tested on local machine

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-07-06 11:45 UTC, pranavkanade requested changes

2021-07-06 11:45 UTC, pranavkanade commented on app/client/src/components/ads/DisplayImageUpload.tsx
> +        maxFileSize: 3145728, // 3 MB
@nayan-rafiq as suggested in https://github.com/appsmithorg/appsmith/issues/5041 can we show the file size limit warning?

2021-07-06 11:57 UTC, mohanarpit commented on app/client/src/components/ads/DisplayImageUpload.tsx
> +        maxFileSize: 3145728, // 3 MB
Why have different values for image size in the client & server?

2021-07-06 12:17 UTC, nayan-rafiq commented on app/client/src/components/ads/DisplayImageUpload.tsx
> +        maxFileSize: 3145728, // 3 MB
@mohanarpit We've an option to crop the selected image before uploading and we're also reducing the image quality before uploading. So a larger limit on front end will allow users to select larger images than the actual file that'll be uploaded.

2021-07-06 12:30 UTC, mohanarpit commented on app/client/src/components/ads/DisplayImageUpload.tsx
> +        maxFileSize: 3145728, // 3 MB
But if the user doesn't crop the image, what will the image size end up being post compression? If we can predict that, it's OK to have separate limits. If we can't, then we'll run into issues where the user uploads a file within the client limits but the server rejects the HTTP request.

2021-07-06 13:27 UTC, nayan-rafiq commented on app/client/src/components/ads/DisplayImageUpload.tsx
> +        maxFileSize: 3145728, // 3 MB
@mohanarpit Yeah, I've considered this. Uploaded image is 30% of the actual selected image. So if a 3MB file is selected, maximum uploaded file will be less than 1 MB. We've set 1MB limit on backend so it'll not be a problem.

2021-07-06 13:42 UTC, nayan-rafiq commented
@pranavkanade I've added a message to show maximum allowed file size. It look like this one: https://uppy.io/examples/dashboard/
Would you please have a look on this?

2021-07-09 09:02 UTC, pranavkanade approved these changes
FE changes LGTM!

2021-07-09 09:38 UTC, merged