Fix: Value of API's data is different in widgets and entity explorer. Showing curly brackets when empty data is received
appsmithorg/appsmith pull request #5646
Opened 2021-07-06 13:22 UTC by ayushpahwa

## Description

Value of API's data was different in widgets and entity explorer. 

1. Create an API Api1
2. Drop a text widget and bind text to the API data.
3. Now disable the on-page loading of Api1
4. Reload the page.
5. See entity explorer value of Api1 and the value widget is getting. Both are different

When the API is run, the data is properly loaded and the same in both locations. The issue was only when the data was empty or the API was not yet run. For this case, I added a test to check if the data is undefined and set the value as `"{}"`. This way, the data shown at both the places is the same.

Fixes #4991 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-07-06 17:50 UTC, rishabhsaxena submitted a review, later dismissed

2021-07-07 07:50 UTC, hetunandu requested changes

2021-07-07 07:50 UTC, hetunandu commented on app/client/src/pages/Editor/Explorer/Entity/EntityProperties.tsx
> +                  entity.data?.body === undefined ? "{}" : entity.data?.body;
The type protection is not done correctly over here.
Instead try doing something like this.
```suggestion
                if(!entity.data.body) {
                  value = undefined
                } else {
                  value = entity.data.body
                }
```

2021-07-09 08:58 UTC, ayushpahwa commented on app/client/src/pages/Editor/Explorer/Entity/EntityProperties.tsx
> +                  entity.data?.body === undefined ? "{}" : entity.data?.body;
I did the changes for adding type protection, can you please re-check?

2021-07-09 09:11 UTC, rishabhsaxena approved these changes

2021-07-12 06:51 UTC, hetunandu approved these changes

2021-07-12 11:31 UTC, merged