Add Tooltip box in InputBox
appsmithorg/appsmith pull request #5670
Opened 2021-07-07 11:50 UTC by techbhavin

## Description

>  Add Tooltip on an Input box

Fixes #5525

> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

- Bugfix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [ ]  I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ]  I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-07-08 09:14 UTC, somangshu approved these changes

2021-07-08 09:19 UTC, somangshu commented
@techbhavin note:

- `Label text` should be `label`
- `Label text` & `tooltip` should be below the placeholder field

2021-07-08 14:01 UTC, somangshu approved these changes

2021-07-09 04:58 UTC, hetunandu requested changes

2021-07-09 04:58 UTC, hetunandu commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/InputWidget_spec.js
> +const dsl = require("../../../../fixtures/inputdsl.json");
There is already a input widget spec in ClientSideTests/FormWidgets/ 
Please add this test there instead

2021-07-09 04:58 UTC, hetunandu commented on app/client/src/mockResponses/WidgetConfigResponse.tsx
> +      label: "Default",
Use a better label message here

2021-07-09 05:23 UTC, techbhavin commented
/ok-to-test sha=71a1456

2021-07-09 06:47 UTC, somangshu commented on app/client/src/mockResponses/WidgetConfigResponse.tsx
> +      label: "Default",
@techbhavin `"Label"` should be better here.

2021-07-13 05:16 UTC, hetunandu requested changes

2021-07-13 05:16 UTC, hetunandu commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/InputWidget_spec.js
> +const dsl = require("../../../../fixtures/inputdsl.json");
This is still not moved

2021-07-15 05:02 UTC, hetunandu approved these changes

2021-07-16 06:19 UTC, somangshu commented
@techbhavin resolve conflicts

2021-07-19 07:18 UTC, hetunandu submitted a review, later dismissed

2021-07-19 10:58 UTC, somangshu commented
re-ran all jobs, All tests failed

2021-07-19 11:53 UTC, somangshu submitted a review, later dismissed

2021-07-21 05:48 UTC, somangshu submitted a review, later dismissed
Approving to run tests

2021-07-22 13:07 UTC, techbhavin commented
/ok-to-test sha=c10eb4c

2021-07-23 05:22 UTC, YogeshJayaseelan commented
@techbhavin Tested this feature and verified the below scenarios,

Verified:
1)Tooltip text | Helper for input
2)Label text | This text appears beside or on the top of the input widget
3)Auto Focus | This can be a switch and will determine whether the input text will automatically bring up the keyboard and gain focus on load
4)Icon | Choose an icon to show in the input field
5)Icon alignment | left or right

Not verified:
6) Max Chars - This number specifies the maximum number of characters - **There is no options currently to set Max Chars**

2021-07-28 08:40 UTC, hetunandu requested changes

2021-07-28 08:40 UTC, hetunandu commented on app/client/src/components/designSystems/blueprint/InputComponent.tsx
> +const ToolTipContent = styled.div`
Can we set this in the tooltip component itself?

2021-07-28 09:29 UTC, YogeshJayaseelan commented
@techbhavin Re-Tested this feature and verified the below scenarios,

Verified:
1)Tooltip text | Helper for input
2)Label text | This text appears beside or on the top of the input widget
3)Auto Focus | This can be a switch and will determine whether the input text will automatically bring up the keyboard and gain focus on load
4)Icon | Choose an icon to show in the input field
5)Icon alignment | left or right
6) Max Character - **Field is available**

**Issue still need fix:**
7)Tool Tip with larger characters goes out of the canvas both in edit and deploy mode - Now the tool tip popup height is increased but the issue is still reproducible when the input widget is placed near the canvas left and right sides ****

<img width="1680" alt="Screenshot 2021-07-28 at 2 50 42 PM" src="https://user-images.githubusercontent.com/35128442/127298736-faaae0cb-0707-4d85-99f1-7228bf1053ee.png">

**New issue:**
8) Max character is not applied for the default text - When the max character value is lower than the default text character size than the max character value is not applied. 

https://loom.com/share/a9280581e9924e43aca305f5dd81ef28

2021-08-02 02:38 UTC, techbhavin commented
/ok-to-test sha= 1a06004

2021-08-02 04:02 UTC, techbhavin commented
/ok-to-test sha= fcbf6cb

2021-08-02 12:49 UTC, somangshu commented
@hetunandu can you review the changes?

@YogeshJayaseelan for point 8, we will show a validation error on the field in such case

2021-08-03 05:40 UTC, hetunandu requested changes

2021-08-03 05:40 UTC, hetunandu commented on app/client/src/components/designSystems/blueprint/InputComponent.tsx
> +                  <div style={{ maxWidth: "350px" }}>{this.props.tooltip}</div>
This is not right. What i meant was to apply this styling directly in the tooltip component for all tooltips

2021-08-03 12:31 UTC, techbhavin commented
/ok-to-test sha= 5977fa7

2021-08-04 04:55 UTC, hetunandu approved these changes

2021-08-04 06:37 UTC, somangshu commented
Unrelated test > `Button_spec.js` failed

2021-08-06 05:46 UTC, hetunandu commented on app/client/src/widgets/InputWidget.tsx
> -      isValid: `{{
Why are we doing this? This has the potential to break existing widgets. Why is user responsible for setting this now?

2021-08-09 11:25 UTC, techbhavin commented
/ok-to-test sha= dc7e938

2021-08-10 05:53 UTC, hetunandu requested changes

2021-08-10 05:53 UTC, hetunandu commented on app/client/src/widgets/InputWidget.tsx
> +      !this.props.validation;
the isValid property is used in the form widget to see if the form is valid. So that reason, validation property should be checked in the isValid property itself

2021-08-13 07:33 UTC, hetunandu commented on app/client/src/components/editorComponents/CodeEditor/index.tsx
> +    this.editor.focus();
Why are we setting focus twice?

2021-08-13 09:12 UTC, techbhavin commented on app/client/src/components/editorComponents/CodeEditor/index.tsx
> +    this.editor.focus();
Here I am not change anything i don't know why it showing here. 
but I removed  line please check @hetunandu.

2021-08-13 09:14 UTC, hetunandu approved these changes

2021-08-17 10:22 UTC, YogeshJayaseelan commented
@techbhavin verified this PR and the functionalities are working as expected

2021-08-17 11:08 UTC, merged