FIX #4419 : added margin support in text widget
appsmithorg/appsmith pull request #5672
Opened 2021-07-07 12:08 UTC by vibhandikyash

## Description

> Added margin support in text widget.

Fixes #4419 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Tested Locally.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-07-08 09:30 UTC, somangshu requested changes

2021-07-08 09:30 UTC, somangshu commented on app/client/src/widgets/TextWidget.tsx
> +            helpText: "Enter value for margin",
Margin allows clean space between text and widget boundary

2021-07-08 09:30 UTC, somangshu commented on app/client/src/components/designSystems/blueprint/TextComponent.tsx
> +  margin?: string;
This dosent work, I was wrong here, `Padding` will work here. Please check the image in original issue to get clarity.

2021-07-08 09:30 UTC, somangshu commented on app/client/src/widgets/TextWidget.tsx
> +            label: "Margin",
This should finally be `padding (px)` and the value should be an integer which works without px

2021-07-09 08:00 UTC, somangshu approved these changes

2021-07-09 08:02 UTC, somangshu commented on app/client/src/widgets/TextWidget.tsx
> +            helpText: "Enter value for padding (px)",
Change to > "Controls clean space between text and widget boundary"

2021-07-09 10:20 UTC, vibhandikyash commented
/ok-to-test sha=2545bc2

2021-07-09 10:50 UTC, somangshu approved these changes

2021-07-09 11:05 UTC, somangshu requested changes
Change order of `Padding` > above `font style`

2021-07-09 11:05 UTC, somangshu commented on app/client/src/widgets/TextWidget.tsx
> +            label: "Padding",
change to > "Padding (px)"

2021-07-12 13:21 UTC, somangshu approved these changes

2021-07-15 09:18 UTC, vivekverma2312 commented
@vibhandikyash If I use bigger padding then the text is displayed out of the widget due to this it overlaps the below widget.
<img width="722" alt="Screenshot 2021-07-15 at 2 19 33 PM" src="https://user-images.githubusercontent.com/83569920/125759177-947ed300-9865-470b-b061-45b41343a0a3.png">

2021-07-15 11:31 UTC, somangshu commented
@marks0351 any solutions around this?

2021-07-19 05:03 UTC, marks0351 commented
> @marks0351 any solutions around this?

we should be decreasing the height of widget based on the padding added. widget content should not be overflowing its borders it can overflow within it selves like we do with containers.

2021-07-22 05:30 UTC, marks0351 commented
@somangshu should we temporarily close this PR?

2021-07-26 09:55 UTC, somangshu commented
@vibhandikyash please have a discussion with @marks0351 and take this forward.

2021-08-11 09:58 UTC, vibhandikyash commented
@marks0351 As we discussed. This is dependent on #2587. Once that is merged. We can take this further.
cc: @somangshu

2021-08-11 09:59 UTC, somangshu commented
This will be picked up after the container widget branch is merged, Closing this for now

2021-08-11 09:59 UTC, closed without merging