[Fix] create new api not working from saved google sheet state
appsmithorg/appsmith pull request #5681
Opened 2021-07-07 17:21 UTC by pranavkanade

## Description
Fixed the bug, by using action creator which does not require URL to be provided at start. For datasources of pluginType `API` added a fix to properly set action config.

Fixes #5680 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manually

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-07-07 17:21 UTC, pranavkanade commented
/ok-to-test sha=9215a79

2021-07-07 19:00 UTC, pranavkanade commented
/ok-to-test sha=4ef8f0b

2021-07-07 20:33 UTC, rishabhsaxena requested changes
![image](https://user-images.githubusercontent.com/1944800/124824412-f80f4600-df8f-11eb-961a-457a81db6528.png)
I think the `New Api` button is now missing?
Also should we redirect away from this page on save?

2021-07-07 20:33 UTC, rishabhsaxena commented on app/client/src/pages/Editor/DataSourceEditor/Connected.tsx
>  import { AppState } from "reducers";
Just checking if we're removing the handling for api actions here, since we've disabled the view mode for `api datasources`?

2021-07-07 20:33 UTC, rishabhsaxena commented on app/client/src/pages/Editor/IntegrationEditor/DatasourceCard.tsx
> +  }, []);
Just checking, should we add the dependencies here?

2021-07-08 04:40 UTC, pranavkanade commented on app/client/src/pages/Editor/IntegrationEditor/DatasourceCard.tsx
> +  }, []);
plugins are fetched once and do not change throughout the use. Moreover, datasources also don't change their plugins in their lifecycle. So, no dependencies needed.

2021-07-08 06:11 UTC, pranavkanade commented on app/client/src/pages/Editor/DataSourceEditor/Connected.tsx
>  import { AppState } from "reducers";
modified the function to handle generic action creation, so that if in future we add new SAAS/API solutions, it'll work as it is

2021-07-08 06:12 UTC, pranavkanade commented
> ![image](https://user-images.githubusercontent.com/1944800/124824412-f80f4600-df8f-11eb-961a-457a81db6528.png)
> I think the `New Api` button is now missing?
> Also should we redirect away from this page on save?

Re introduced the `New API` btn. (With text change to `New Query`)

2021-07-08 06:12 UTC, pranavkanade commented
/ok-to-test sha=ceddadf

2021-07-08 06:18 UTC, rishabhsaxena approved these changes

2021-07-08 07:17 UTC, merged

2021-07-08 07:18 UTC, pranavkanade commented
unrelated test case failing.