[WIP] Grouping widgets into container
appsmithorg/appsmith pull request #5704
Opened 2021-07-08 07:47 UTC by jsartisan

Allow users to group selected widgets into a container widget

Fixes #5016 

## Type of change
- New feature

## How Has This Been Tested?

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-07-19 05:56 UTC, marks0351 requested changes

2021-07-19 05:56 UTC, marks0351 commented on app/client/src/constants/messages.ts
> +export const WIDGET_CUT_GROUPING = (widgetName: string) =>
guess we can remove this

2021-07-19 05:56 UTC, marks0351 commented on app/client/src/sagas/WidgetOperationUtils.ts
> +export const getTopMostSelectedWidget = function(
should we have a common function instead of four individual functions?

2021-07-19 05:56 UTC, marks0351 commented on app/client/src/sagas/WidgetOperationUtils.ts
> +  const widthPerColumn =
I have observed that widgets that we create using generate widget(after running a query) dont have proper parentColumnSpace and parentRowSpace. try grouping such widget.

2021-07-19 05:56 UTC, marks0351 commented on app/client/src/sagas/WidgetOperationUtils.ts
> +  const newCanvasWidget: FlattenedWidgetProps = {
can we get this from widget config response and then make changes else if someone else adds a new attribute they might miss it here.

2021-07-19 05:56 UTC, marks0351 commented on app/client/src/sagas/WidgetOperationUtils.ts
> +  const parentColumSpace = copiedWidgetGroups[0].list[0].parentColumnSpace;
we can `copiedWidgetGroups[0].list[0].parentColumnSpace` get this reference stored and use it. we seem  to be using it in multiple places.

2021-07-19 05:56 UTC, marks0351 commented on app/client/src/sagas/WidgetOperationSagas.tsx
> +        AnalyticsUtil.logEvent("WIDGET_PASTE", {
can we differentiate paste and grouping analytics?

2021-07-19 05:56 UTC, marks0351 commented on app/client/src/sagas/WidgetOperationSagas.tsx
> +        // goToNextAvailableRow = true,
my old dead comments. would you mind removing them.

2021-07-20 05:02 UTC, marks0351 submitted a review, later dismissed

2021-07-20 05:12 UTC, jsartisan commented
@vivekverma2312 this PR is ready for the QA,

2021-07-30 13:23 UTC, YogeshJayaseelan commented
@jsartisan Verified this feature and came up with the below issues 

1. When the container within the container are grouped the inner container is not displayed in the deploy mode 

https://www.loom.com/share/c33d173a5b034904b83d5c2c21ddf5c6

2. User is not able draw(Mouse click and draw around widgets) and select inside container or form - Where Cmd+click is working so that user can group 

https://loom.com/share/05a5ac30513641f8ac3093d2df1a6a5d

3.Group multiple widgets into a container and try to select widgets inside container using cmd+click and try to group another container and observe the last grouped container is hiding on back of original container 

https://loom.com/share/445300210ce3457b9e63b9749b9ec2e1

4. when there are multiple widgets user unable to draw and select all the widgets and form them as a group - Whereas this is working fine with CMD+A and group 

https://loom.com/share/12c149196276447cafc93f612248e99a

2021-08-10 06:45 UTC, YogeshJayaseelan commented
@jsartisan Tested the fix and came up with the below issue

5. Not able to group widgets as container - Click or command+G is not working - Hence unable to test other issues

https://loom.com/share/23809b88c6954fb5906b78e49c936819

2021-08-10 10:26 UTC, marks0351 submitted a review, later dismissed

2021-08-11 08:46 UTC, jsartisan commented
@YogeshJayaseelan For the 1st you raised, that is being fixed in different PR. We will be adding the ability to add box-shadow in a container that will solve that issue.

2021-08-12 06:49 UTC, marks0351 approved these changes

2021-08-12 08:53 UTC, marks0351 submitted a review, later dismissed

2021-08-16 10:10 UTC, YogeshJayaseelan commented
@jsartisan Issue 5 is still happening

2021-08-20 07:13 UTC, YogeshJayaseelan commented
@jsartisan Verified the fix and they are working as expected.

2021-08-20 10:08 UTC, somangshu approved these changes

2021-08-24 11:32 UTC, marks0351 approved these changes

2021-08-25 05:00 UTC, merged