Feat/server side filtering multiselect
appsmithorg/appsmith pull request #5737
Opened 2021-07-08 12:42 UTC by Tooluloope

## Description

Add support for Server Side Filtering on MultiSelect

Fixes #5018 

## Type of change

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-07-09 05:44 UTC, somangshu requested changes
- ~~Order of the new props need to change~~
    - ~~`Server side filtering` after `disabled`~~
    - ~~`onFilterUpdate` the first under actions~~
- ~~`onFilterUpdate` should be a dropdown to bind actions which should called when filter is updated~~
- The data once reloaded should update. 
- ~~The `filterText` prop does not reset on blur whereas the searchText does.~~
- Same changes should be applied to the select widget too
- The action is not triggered on filterText update

2021-07-12 12:30 UTC, somangshu commented
@Tooluloope ☝️

2021-07-14 05:27 UTC, somangshu requested changes

2021-07-14 05:27 UTC, somangshu commented on app/client/src/widgets/DropdownWidget.tsx
> +            helpText: "Controls the Remote Data/ Server Side Filtering",
Change to > "Enables server side filtering of the data"

2021-07-14 05:27 UTC, somangshu commented on app/client/src/components/designSystems/blueprint/DropdownComponent.tsx
> +import _, { debounce } from "lodash";
Why do we need to import `debounce` separately, And if there are no other references the `_` ref should be removed.

2021-07-14 05:27 UTC, somangshu commented on app/client/src/widgets/DropdownWidget.tsx
> +            helpText: "Filter options using filterText",
change to > Trigger an action on change of `filterText`

2021-07-16 11:14 UTC, somangshu requested changes
@Tooluloope please resolve conflict. Have some feedback from the deploy preview:
- The filterText in the multi-select widget does not call the onFilterUpdate action when the filter is completely remove (cmd + A and Backspace)
- The select widget does not have the filterText api exposed

2021-07-16 11:29 UTC, somangshu commented
@Tooluloope please note that documentation changes are required here

2021-07-16 12:04 UTC, Tooluloope commented
> @Tooluloope please resolve conflict. Have some feedback from the deploy preview:
> 
> * The filterText in the multi-select widget does not call the onFilterUpdate action when the filter is completely remove (cmd + A and Backspace)
> * The select widget does not have the filterText api exposed
> * error seen > Could not parse the binding `onFilterUpdate`

I realized there are some queries that wont work or throw some error if filterText is empty.
Also, I saw it as an extra network request that might not be used, so it only works when It has a value(filterText)
> The filterText in the multi-select widget does not call the onFilterUpdate action when the filter is completely remove (cmd + A and Backspace)

For the rest, I've fixed it.
@somangshu

2021-07-16 12:48 UTC, Tooluloope commented
> @Tooluloope please note that documentation changes are required here

@somangshu I've created a PR for this on the docs repo, you could review that

2021-07-19 12:43 UTC, somangshu commented
> > The filterText in the multi-select widget does not call the onFilterUpdate action when the filter is completely remove 
(cmd + A and Backspace)

We need a find a solution to this @Tooluloope, With this the widget will never we able to come to its initial state in case of server side filtering.

2021-07-19 18:33 UTC, Tooluloope commented
> > > The filterText in the multi-select widget does not call the onFilterUpdate action when the filter is completely remove
> > > (cmd + A and Backspace)
> 
> We need a find a solution to this @Tooluloope, With this the widget will never we able to come to its initial state in case of server side filtering.

@somangshu  Fixed it

2021-07-21 07:24 UTC, somangshu approved these changes
Approving to run tests

2021-07-21 09:40 UTC, somangshu submitted a review, later dismissed
Running tests

2021-07-23 05:58 UTC, riodeuno commented
@Tooluloope Let's get the multiselect widget merged into release, so that the diff in this PR will be smaller. That way it will be easier to review.

2021-08-03 16:34 UTC, Tooluloope commented
/ok-to-test sha=172a1fb

2021-08-04 06:55 UTC, somangshu approved these changes
Approving to run tests

2021-08-04 11:00 UTC, somangshu submitted a review, later dismissed

2021-08-10 07:54 UTC, riodeuno commented
@somangshu Can we verify the UI/UX?

2021-08-10 14:01 UTC, somangshu commented
Checked the deploy preview, Something is wrong. @Tooluloope the filter after completing the query run is reseting the select options, Also the server side filtering is overridden by the client side filter. 👇 

Uploading Screen Recording 2021-08-10 at 7.29.20 PM.mov…

2021-08-13 08:05 UTC, somangshu approved these changes
LGTM, Deploy preview also tested

2021-08-16 05:04 UTC, riodeuno approved these changes

2021-08-16 06:56 UTC, merged