[Enhancement] Add link to unsubscribe from email notification for comments
appsmithorg/appsmith pull request #5769
Opened 2021-07-11 05:43 UTC by nayan-rafiq

## Description
Users who've participated in a comment thread or tagged by someone in a message in that thread - get an email for each comment. This PR will add a unsubscribe link to the email body. Clicking on the link will take user to a page where they can confirm their the action and will be unsubscribed from the thread notifications.

Fixes #5351 

## Type of change
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
- Unit tests
- Cypress tests
- Tested on local dev machine

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-07-12 05:56 UTC, pranavkanade requested changes

2021-07-12 05:56 UTC, pranavkanade commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Comments/UnsubscribeEmail_spec.js
> +    cy.visit("/unsubscribe/discussion/123456");
@nayan-rafiq Just to double check, static URL with `123456` at the end will work every time we run the spec, right?

2021-07-12 05:56 UTC, pranavkanade commented on app/client/src/reducers/uiReducers/commentsReducer/commentsReducer.ts
> +    unsubscribed: true,
We need another reducer to reset `unsubscribed` state. In case user wants un unsubscribe from two different threads one after the other, we won't be able to show proper UI.

2021-07-12 06:01 UTC, nayan-rafiq commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Comments/UnsubscribeEmail_spec.js
> +    cy.visit("/unsubscribe/discussion/123456");
Yeah, it'll call the API and API will actually do nothing in this case.

2021-07-12 06:05 UTC, nayan-rafiq commented on app/client/src/reducers/uiReducers/commentsReducer/commentsReducer.ts
> +    unsubscribed: true,
Users goes to this page by clicking a link from email. Considering this, do we need a reducer?

2021-07-12 12:50 UTC, pranavkanade commented on app/client/src/reducers/uiReducers/commentsReducer/commentsReducer.ts
> +    unsubscribed: true,
Nope. Assuming, the link will always open in a new window

2021-07-14 05:06 UTC, pranavkanade approved these changes
FE LGTM!

Please wait for @sharat87's review

2021-07-16 17:48 UTC, mohanarpit commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Comments/UnsubscribeEmail_spec.js
> +describe("Ubsubscribe comment email test spec", function() {
```suggestion
describe("Unsubscribe comment email test spec", function() {
```
Super minor typo fix.

2021-07-16 17:48 UTC, mohanarpit commented on app/client/src/pages/common/UnsubscribeEmail.tsx
> +              corresponding comment thread.
```suggestion
              You won't receive any more email notifications for the
              corresponding comment thread.
```
Nit: The wording was very awkward. 

Also, is it possible for us to save all these strings in the file [messages.ts](https://github.com/appsmithorg/appsmith/blob/release/app/client/src/constants/messages.ts)? Will make future i18n easier.

2021-07-16 17:48 UTC, mohanarpit commented on app/client/src/pages/common/UnsubscribeEmail.tsx
> +              in a comment or you reply to a comment.
```suggestion
              Please note that you&apos;ll be subscribed again if someone tags you
              in a comment or you reply to a comment.
```

2021-07-16 17:48 UTC, mohanarpit commented on app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/BaseAppsmithRepositoryImpl.java
> +                            .matching(createQueryWithPermission(criterias, (User) auth.getPrincipal(), aclPermission))
```suggestion
                            .matching(createQueryWithPermission(criterias, user, aclPermission))
```
Nit: We have already created an object for `User`. Should we be using that object itself?

2021-07-19 08:23 UTC, mohanarpit commented
@nayan-rafiq Please merge the latest release into your branch to solve the failing test case.

2021-07-19 10:48 UTC, mohanarpit commented on app/client/src/pages/common/UnsubscribeEmail.tsx
> +            You have successfully unsubscribed from the corresponding comment
Is it possible to move all these string to `messages.ts`? Will ensure a slightly smoother i18n implementation if we have most strings in a single file that can be translated into other languages. While this is not mandatory, it's highly recommended.

2021-07-19 17:14 UTC, nayan-rafiq commented on app/client/src/pages/common/UnsubscribeEmail.tsx
> +            You have successfully unsubscribed from the corresponding comment
@mohanarpit I've moved the texts to `message.ts`. Would you please review again?

2021-07-19 17:35 UTC, mohanarpit approved these changes

2021-07-19 18:14 UTC, merged