Improve autocomplete sorting
appsmithorg/appsmith pull request #5798
Opened 2021-07-12 13:17 UTC by hetunandu

2021-07-15 10:42 UTC, hetunandu commented
/ok-to-test sha=35cc1ce

2021-07-16 10:19 UTC, hetunandu commented
/ok-to-test sha=8bc69fa

2021-07-16 18:04 UTC, hetunandu commented
/ok-to-test sha=d8acdab

2021-07-19 07:13 UTC, ApekshaBhosale requested changes

2021-07-19 07:17 UTC, hetunandu commented on app/client/src/utils/autocomplete/dataTypeSortRules.ts
> +    "TEXT_WIDGET.text",
Since it is easier to convert strings to numbers, these are still kept here

2021-07-19 11:12 UTC, ApekshaBhosale approved these changes

2021-07-20 10:02 UTC, merged