Fix/slash commands bugs
appsmithorg/appsmith pull request #5847
Opened 2021-07-14 07:16 UTC by arunvjn

## Description
Fixes a lot of minor bugs around slash commands

Fixes #5825 #5742 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-07-14 08:05 UTC, Nikhil-Nandagopal commented on app/client/src/components/editorComponents/CodeEditor/generateQuickCommands.tsx
> +    displayText: "New Integration",
@arunvjn this should be New Datasource

2021-07-14 11:03 UTC, ApekshaBhosale requested changes

2021-07-14 11:03 UTC, ApekshaBhosale commented on app/client/src/components/editorComponents/CodeEditor/commandsHelper.ts
> +              setTimeout(() => {
why setTimeout needed here?

2021-07-14 11:05 UTC, arunvjn commented on app/client/src/components/editorComponents/CodeEditor/commandsHelper.ts
> +              setTimeout(() => {
We need a delay for the editor's value to update before changing the position of the cursor and execute the subsequent action.

2021-07-14 11:24 UTC, ApekshaBhosale commented
Approving for deploy review for now @arunvjn

2021-07-14 11:25 UTC, ApekshaBhosale submitted a review, later dismissed

2021-07-15 09:37 UTC, arunvjn commented on app/client/src/components/editorComponents/CodeEditor/commandsHelper.ts
> +              setTimeout(() => {
Removed dependency on timeout

2021-07-15 12:24 UTC, ApekshaBhosale submitted a review, later dismissed

2021-07-15 12:26 UTC, hetunandu commented on app/client/src/utils/autocomplete/TernServer.ts
> +    );
Remove this change

2021-07-15 12:47 UTC, ApekshaBhosale approved these changes

2021-07-15 13:01 UTC, ApekshaBhosale approved these changes

2021-07-15 14:38 UTC, merged