Table widget: default selected row, 0th
appsmithorg/appsmith pull request #5930
Opened 2021-07-19 03:57 UTC by techbhavin

## Description

> Table widget: default selected row, 0th

Fixes #5892

## Type of change

- New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ]  I have commented my code, particularly in hard-to-understand areas
- [ ]  I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- []  I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-07-19 11:58 UTC, somangshu approved these changes
LGTM, @vivekverma2312 lets check if this caused any problem in old widgets, We will need to write migrations accordingly.

2021-08-02 02:37 UTC, techbhavin commented
/ok-to-test sha= fa6c643

2021-08-02 07:40 UTC, vivekverma2312 commented
@techbhavin Couple of observations:
1. Default selected row property is still showing as blank, if default value is 0 then we should also mention it in the property
<img width="799" alt="Screenshot 2021-08-02 at 12 25 48 PM" src="https://user-images.githubusercontent.com/83569920/127822321-4f5a6283-a55c-43e0-950f-7085d678a30f.png">


2. By default row is not selected for old tables.

2021-08-03 11:11 UTC, techbhavin commented
@somangshu  @vivekverma2312  
> Point 1

There is an issue when propertyPane INPUT_TEXT type control has validation on Number. For default props and prop change from external source ( i.e. a btn click ) and new value of prop is "0" it is not reflected in propertyPane input field but new value of prop does reach out to component and it is updated as expected.

> Point 2 
we need to add migrations for this. let me add it

2021-08-04 06:14 UTC, techbhavin commented
/ok-to-test sha= 7deaf92

2021-08-04 06:16 UTC, techbhavin commented
> By default row is not selected for old tables.

@somangshu  @vivekverma2312   migration test was added so please test point 2.

2021-08-04 06:26 UTC, somangshu approved these changes
Approving for the tests to run.

@marks0351 can you please verify the migrations?

2021-08-04 06:28 UTC, marks0351 approved these changes

2021-08-09 09:43 UTC, vivekverma2312 commented
@techbhavin Migration issue is fixed and working fine. Issue 1 still exists.

2021-08-10 08:06 UTC, marks0351 commented
@techbhavin defaultSelectedRowValidation is the validation that runs to evaluate. so this doesn't work because by default the evaluated value will be returned as 0 and a check in the input text control to check value truthness fails. so we need to return out strings instead of numbers in defaultSelectedRowValidation. this doesnot happen when the user types the input because it is always handled as strings. let me know if you want to discuss this.

2021-08-10 12:06 UTC, marks0351 requested changes
Please do add cypress or jest test cases as well.

2021-08-10 12:06 UTC, marks0351 commented on app/client/src/mockResponses/WidgetConfigResponse.tsx
> +      defaultSelectedRow: "0" as any,
can u pls change the interface instead, wud help catch errors in other areas of code flow.

2021-08-13 05:02 UTC, marks0351 approved these changes

2021-08-13 07:04 UTC, somangshu commented
Upon testing the deploy preview, I see that the old tables do not have the change. I think we should write migration for this as well if not already done. @marks0351 what is your thought?

The feature otherwise works well for the new tables and the above mentioned issues from the QA are fixed, Once we discuss the aforementioned point we can take this ahead

2021-08-13 07:06 UTC, marks0351 requested changes

2021-08-13 07:06 UTC, marks0351 commented on app/client/src/utils/WidgetPropsUtils.tsx
> +    if (!currentDSL.defaultSelectedRow) currentDSL.defaultSelectedRow = 0;
can u change the zero to a string and check if the migration works?

2021-08-16 11:08 UTC, somangshu commented
@techbhavin @marks0351 this still doesn't work of the older tables. Here is my [app](https://deploy-preview-5930--appsmith-editor-ce.netlify.app/applications/60aba4455123fa30d6c393f7/pages/60aba4455123fa30d6c393f9/edit)

2021-08-16 11:14 UTC, marks0351 commented
> @techbhavin @marks0351 this still doesn't work of the older tables. Here is my [app](https://deploy-preview-5930--appsmith-editor-ce.netlify.app/applications/60aba4455123fa30d6c393f7/pages/60aba4455123fa30d6c393f9/edit)

looks to be working for me. any chance you are using the same app as before to check this?

2021-08-16 11:17 UTC, somangshu commented
@marks0351 its the same app as before, Should the old tables have default 0th key selected?

2021-08-16 11:21 UTC, marks0351 commented
> @marks0351 its the same app as before, Should the old tables have default 0th key selected?

by setting default selected row to 0, i thought that was what we are going for else there is no need for migration.
also if you are trying on the same app the old migration should have already run and this updated migration will not run on it, re create the app on release again and then check it on the dp if you wish to test.

2021-08-16 11:26 UTC, somangshu commented
Thanks for the pro tip @marks0351, That worked!

2021-08-16 11:26 UTC, somangshu submitted a review, later dismissed
Approving for the tests to run

2021-08-17 12:01 UTC, marks0351 submitted a review, later dismissed

2021-08-17 12:55 UTC, somangshu commented
@techbhavin can you resolve this conflict soon?

2021-08-18 06:37 UTC, somangshu approved these changes

2021-08-20 07:20 UTC, somangshu approved these changes

2021-08-25 14:05 UTC, somangshu commented
@techbhavin this issue is fixed, Can you please merge the latest release here?

2021-08-28 06:18 UTC, somangshu approved these changes

2021-08-30 06:58 UTC, merged