[perf] propertyControl re-rendering
appsmithorg/appsmith pull request #5941
Opened 2021-07-19 06:03 UTC by rahulramesha

## Description

This PR addresses unnecessary re-rendering of propertyControl.
This PR is for reference and will be raised against release post complete development.

Fixes # (issue)

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-07-23 09:58 UTC, SatishGandham submitted a review, later dismissed
Approving for tests

2021-07-23 09:59 UTC, rahulramesha commented
/ok-to-test sha=e15c973

2021-07-26 09:42 UTC, rahulramesha commented
/ok-to-test sha=fc97287

2021-07-26 11:07 UTC, SatishGandham approved these changes
Approving for tests.

2021-07-27 06:58 UTC, SatishGandham commented on app/client/src/selectors/propertyPaneSelectors.tsx
> +  if (value === null || value === undefined) return;
Do we need this check?

2021-07-27 10:33 UTC, rahulramesha commented on app/client/src/selectors/propertyPaneSelectors.tsx
> +  if (value === null || value === undefined) return;
`value` is being set later on to the target object and get returns undefined if the path does not exist. So this check prevents setiing paths that does not exist on from `object`.

2021-07-27 10:39 UTC, rahulramesha commented
/ok-to-test sha=e52e993

2021-07-27 10:42 UTC, SatishGandham approved these changes

2021-07-28 08:36 UTC, hetunandu requested changes

2021-07-28 08:36 UTC, hetunandu commented on app/client/src/sagas/WidgetEnhancementHelpers.ts
> +export function* getChildWidgetEnhancementF(
i think this was renamed by mistake

2021-07-28 08:36 UTC, hetunandu commented on app/client/src/selectors/propertyPaneSelectors.tsx
> +      widgetProperties[EVALUATION_PATH] = populateEvaluatedWidgetProperties(
EVALUATION_PATH could have `.` in them. This should be done via `_.set`

2021-07-28 08:36 UTC, hetunandu commented on app/client/src/widgets/ChartWidget/propertyConfig.ts
> +        dependencies: ["chartType"],
Is there a better way to infer these dependencies? hard coding them is not a good idea

2021-07-28 11:40 UTC, rahulramesha commented on app/client/src/pages/Editor/PropertyPane/PropertyControl.tsx
> +  const widgetProperties: any = useSelector(propsSelector, isEqual);
It previously was also `any`, but changed it now

2021-07-28 11:40 UTC, rahulramesha commented on app/client/src/sagas/WidgetEnhancementHelpers.ts
> +export function* getChildWidgetEnhancementF(
yes, missed that

2021-07-28 11:41 UTC, rahulramesha commented on app/client/src/selectors/propertyPaneSelectors.tsx
> +      widgetProperties[EVALUATION_PATH] = populateEvaluatedWidgetProperties(
EVALUATION_PATH actually resolves to a hard Coded constant without any `.` , So this is Safe

2021-07-28 11:47 UTC, rahulramesha commented on app/client/src/widgets/ChartWidget/propertyConfig.ts
> +        dependencies: ["chartType"],
`dependencies` are basically PropertyNames defined inside propertyConfig and these are different per different PropertyConfig. Currently even the propertyNames are also hardcoded. Changing these will also need moving them(PropertyNames) all to a different Constants file.

2021-07-28 12:05 UTC, SatishGandham approved these changes
Approving for tests.

2021-07-29 06:02 UTC, hetunandu commented on app/client/src/widgets/ChartWidget/propertyConfig.ts
> +        dependencies: ["chartType"],
The problem is that it is not very obvious that these dependencies array would need to change or be added whenever the hidden function needs to change. This might re-introduce our perf issues. @riodeuno could you suggest a better approach for this?

2021-07-30 06:35 UTC, rahulramesha commented
/ok-to-test sha=901235c

2021-07-30 06:35 UTC, SatishGandham approved these changes
Approving for tests.

2021-07-30 10:51 UTC, riodeuno commented on app/client/src/widgets/ChartWidget/propertyConfig.ts
> +        dependencies: ["chartType"],
@hetunandu I concur with your concerns. 

However, based on the priorities, we need to improve performance. We have some leeway at the moment, until the widget development API is done for making things easier for widget developers. 

I will look into an alternative where we can avoid adding dependencies to the property pane while keeping the performance stable.

For now, I suggest we move ahead with this approach for performance improvements.

2021-07-30 10:59 UTC, hetunandu commented on app/client/src/widgets/ChartWidget/propertyConfig.ts
> +        dependencies: ["chartType"],
Sounds good 👍🏻

2021-07-30 10:59 UTC, hetunandu approved these changes

2021-07-30 12:15 UTC, riodeuno approved these changes

2021-08-02 09:36 UTC, somangshu approved these changes
Approving to run tests

2021-08-02 13:06 UTC, merged