Feature/js collection eval
appsmithorg/appsmith pull request #6003
Opened 2021-07-20 12:20 UTC by ApekshaBhosale

## Description
Js collection

Fixes #1751

## Type of change
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-07-21 08:49 UTC, hetunandu requested changes

2021-07-21 08:49 UTC, hetunandu commented on app/client/src/pages/Editor/QueryEditor/EditorJSONtoForm.tsx
> +export const TabbedViewContainer = styled.div`
Can we move this to the components folder if it is getting resued

2021-07-21 08:49 UTC, hetunandu commented on app/client/src/pages/Editor/SaaSEditor/DatasourceCard.tsx
> +      "datasource" in action.config &&
Plugin type check needed

2021-07-21 08:49 UTC, hetunandu commented on app/client/src/reducers/entityReducers/jsActionsReducer.tsx
> +export type JSActionDataState = JSActionData[];
Can we make it objects with ids as key instead of an array

2021-07-21 08:49 UTC, hetunandu commented on app/client/src/reducers/uiReducers/jsPaneReducer.ts
> +  isRunning: Record<string, boolean>;
Needs to be based on sub actions

2021-07-21 08:49 UTC, hetunandu commented on app/client/src/sagas/JSPaneSagas.ts
> +export const JS_PLUGIN_PACKAGE_NAME = "js-plugin";
Declare this in the plugins file

2021-07-21 08:49 UTC, hetunandu commented on app/client/src/sagas/JSPaneSagas.ts
> +      2000,
Reduce this debounce

2021-07-21 08:49 UTC, hetunandu commented on app/client/src/utils/autocomplete/dataTreeTypeDefCreator.ts
> +export const getPropsForJSActionEntity = (entity: any): any => {
Define this in the Entity Definations file

2021-07-21 08:49 UTC, hetunandu commented on app/client/src/utils/DynamicBindingUtils.ts
> +  entity?: any,
Dont use any

2021-07-21 08:49 UTC, hetunandu commented on app/client/src/utils/JSPaneUtils.tsx
> +  parsedBody: any,
remove any

2021-07-21 08:49 UTC, hetunandu commented on app/client/src/utils/JSPaneUtils.tsx
> +export const getDifferenceInJSAction = (
Only do this check if the JS collection is valid

2021-07-21 08:49 UTC, hetunandu commented on app/client/src/workers/DataTreeEvaluator.ts
> +  evalTree: Readonly<DataTree> = {};
Revert this change

2021-07-21 08:49 UTC, hetunandu commented on app/client/src/workers/DataTreeEvaluator.ts
> +        if (!_.isFunction(_.get(this.evalTree, propertyPath))) {
Can we resolve actions after this step to avoid this check

2021-07-21 08:49 UTC, hetunandu commented on app/client/src/workers/evaluation.worker.ts
> +          //error
Handle and pass error back

2021-07-22 06:54 UTC, ApekshaBhosale commented on app/client/src/actions/jsActionActions.ts
> +export const deleteJSActionSuccess = (payload: { id: string }) => {
it is already done

2021-07-22 06:58 UTC, ApekshaBhosale commented on app/client/src/actions/jsPaneActions.ts
> +import { ReduxAction, ReduxActionTypes } from "constants/ReduxActionConstants";
i didn't get it. What am i missing here?

2021-07-22 07:05 UTC, ApekshaBhosale commented on app/client/src/api/JSActionAPI.tsx
> +export interface ActionApiResponseReq {
removed this we need won't need this for now

2021-07-22 07:13 UTC, ApekshaBhosale commented on app/client/src/components/editorComponents/CodeEditor/EditorConfig.ts
> -  mode: EditorModes;
will make new mode

2021-07-22 07:26 UTC, ApekshaBhosale commented on app/client/src/pages/Editor/JSEditor/Form.tsx
> +      panelComponent: <div />,
yes i am aware of that after design is done i will implement it

2021-07-22 13:46 UTC, ApekshaBhosale commented on app/client/src/pages/Editor/JSEditor/JSActionNameEditor.tsx
> +import React, { useEffect, useState, useCallback } from "react";
Because too many things happening and we want to separate that

2021-07-22 14:09 UTC, ApekshaBhosale commented on app/client/src/workers/DataTreeEvaluator.ts
> +        if (!_.isFunction(_.get(this.evalTree, propertyPath))) {
yes changed

2021-07-22 14:16 UTC, ApekshaBhosale commented on app/client/src/reducers/uiReducers/jsPaneReducer.ts
> +  isRunning: Record<string, boolean>;
this needs to be on collection as well except isRunning

2021-07-22 14:36 UTC, ApekshaBhosale commented on app/client/src/pages/Editor/QueryEditor/EditorJSONtoForm.tsx
> +export const TabbedViewContainer = styled.div`
i will do this later i still need to make css changes

2021-08-19 08:57 UTC, hetunandu commented on app/client/src/actions/jsPaneActions.ts
> +import { ReduxAction, ReduxActionTypes } from "constants/ReduxActionConstants";
There are two different action files called `jsActionActions` and `jsPaneActions`

this seems unnecessary as they both seem to define similar actions. Am i missing something here?

2021-08-19 09:07 UTC, ApekshaBhosale commented on app/client/src/actions/jsPaneActions.ts
> +import { ReduxAction, ReduxActionTypes } from "constants/ReduxActionConstants";
yes so jsActionActions has create delete etc and jsPane has parsing, update etc exactly like APIs

2021-08-30 11:57 UTC, hetunandu requested changes

2021-08-30 11:57 UTC, hetunandu commented on app/client/src/workers/DataTreeEvaluator.ts
> +    const localUnEvalTree = Object.assign({}, unEvalTree);
Dont copy at all

2021-08-30 11:57 UTC, hetunandu commented on app/client/src/workers/DataTreeEvaluator.ts
> +        }
Remove this

2021-08-30 11:57 UTC, hetunandu commented on app/client/src/workers/DataTreeEvaluator.ts
> +          );
Move it to generateDataTreeJSAction step

2021-08-30 11:57 UTC, hetunandu commented on app/client/src/workers/DataTreeEvaluator.ts
> +              );
Move it to generateDataTreeJSAction step

2021-08-30 11:57 UTC, hetunandu commented on app/client/src/workers/DataTreeEvaluator.ts
> +          const newUnEvalValue = unEvalValue.replaceAll(reg, entity.name + ".");
Move it to generateDataTreeJSAction step

2021-08-30 11:57 UTC, hetunandu commented on app/client/src/workers/evaluate.ts
> +  resolvedFunctions: Record<string, any>,
Make this optional or default to = {}

2021-08-30 11:57 UTC, hetunandu commented on app/client/src/workers/evaluate.ts
> +    // debugger;
Remove comment

2021-08-30 11:57 UTC, hetunandu commented on app/client/src/workers/evaluation.worker.ts
> +          const parsedLength = Object.keys(parsed).length;
check for `isTrueObject`

2021-08-30 11:57 UTC, hetunandu commented on app/client/src/workers/evaluation.worker.ts
> +          const parsed = body && eval("(" + body + ")");
Do a regex check for `export default { ... }` before evaling

2021-08-30 11:57 UTC, hetunandu commented on app/client/src/workers/evaluationUtils.ts
> +  // add all js action paths
Remove comment

2021-08-30 12:52 UTC, ApekshaBhosale commented on app/client/src/actions/jsPaneActions.ts
> +  type: ReduxActionTypes.CREATE_NEW_JS_ACTION,
it is i will rename this

2021-08-30 12:52 UTC, ApekshaBhosale commented on app/client/src/workers/evaluationUtils.ts
> +  // add all js action paths
removed

2021-08-30 12:53 UTC, ApekshaBhosale commented on app/client/src/workers/evaluate.ts
> +    // debugger;
removed

2021-08-30 12:54 UTC, ApekshaBhosale commented on app/client/src/pages/Editor/JSEditor/JSObjectNameEditor.tsx
> +const ApiNameWrapper = styled.div<{ page?: string }>`
done

2021-08-30 12:56 UTC, ApekshaBhosale commented on app/client/src/pages/Editor/Explorer/JSActions/JSActionEntity.tsx
> +        className="jsaction"
done

2021-08-30 13:00 UTC, ApekshaBhosale commented on app/client/src/entities/JSAction/index.ts
> +export type variable = {
changed everywhere

2021-08-30 13:01 UTC, ApekshaBhosale commented on app/client/src/entities/DataTree/dataTreeFactory.ts
> +  meta: Record<string, MetaArgs>;
this is implementation change will take care of this later

2021-08-30 13:01 UTC, ApekshaBhosale commented on app/client/src/constants/ReduxActionConstants.tsx
> +  CREATE_JS_ACTION_INIT: "CREATE_JS_ACTION_INIT",
these are different will rename them better

2021-08-30 13:03 UTC, ApekshaBhosale commented on app/client/src/api/JSActionAPI.tsx
> +export interface JSActionCreateUpdateResponse extends ApiResponse {
added

2021-08-30 13:05 UTC, ApekshaBhosale commented on app/client/src/reducers/uiReducers/jsPaneReducer.ts
> +  isCreating: boolean; // RR
removed

2021-08-30 13:20 UTC, ApekshaBhosale commented on app/client/src/pages/Editor/Explorer/Datasources/DatasourceEntity.tsx
> +    "datasource" in queryAction &&
don't need this anymore. reverting

2021-08-30 13:24 UTC, ApekshaBhosale commented on app/client/src/pages/Editor/Explorer/hooks.ts
> +          "datasource" in action.config &&
doesn't need this anymore removing

2021-08-30 13:27 UTC, ApekshaBhosale commented on app/client/src/pages/Editor/IntegrationEditor/DatasourceCard.tsx
> +      "datasource" in action.config &&
not needed anymore removed

2021-08-30 13:48 UTC, ApekshaBhosale commented on app/client/src/pages/Editor/SaaSEditor/DatasourceCard.tsx
> +      "datasource" in action.config &&
removed

2021-08-30 14:10 UTC, ApekshaBhosale commented on app/client/src/components/editorComponents/ActionCreator/index.tsx
> +        label: "Execute a JS Function",
Added

2021-08-30 14:26 UTC, ApekshaBhosale commented on app/client/src/components/editorComponents/JSResponseView.tsx
> +                    Executing function
added

2021-08-30 14:26 UTC, ApekshaBhosale commented on app/client/src/components/editorComponents/JSResponseView.tsx
> +              Nothing to show, write some code to get response{" "}
added

2021-08-30 14:34 UTC, ApekshaBhosale commented on app/client/src/sagas/JSActionSagas.ts
> +        const jsSubAction = JSON.parse(JSON.stringify(action));
this doesn't allow me to remove ids for API

2021-08-30 15:23 UTC, ApekshaBhosale commented on app/client/src/workers/DataTreeEvaluator.ts
> +          const newUnEvalValue = unEvalValue.replaceAll(reg, entity.name + ".");
added to generateDataTreeJSAction

2021-08-30 15:23 UTC, ApekshaBhosale commented on app/client/src/workers/DataTreeEvaluator.ts
> +              );
added to generateDataTreeJSAction

2021-08-30 15:23 UTC, ApekshaBhosale commented on app/client/src/workers/DataTreeEvaluator.ts
> +          );
added to generateDataTreeJSAction

2021-08-30 16:06 UTC, ApekshaBhosale commented on app/client/src/actions/jsActionActions.ts
> +export const deleteJSActionSuccess = (payload: { id: string }) => {
added

2021-08-30 16:08 UTC, ApekshaBhosale commented on app/client/src/reducers/entityReducers/jsActionsReducer.tsx
> +export type JSActionDataState = JSActionData[];
yes i will take this up as part of next refactor

2021-08-31 08:06 UTC, ApekshaBhosale commented on app/client/src/constants/AppsmithActionConstants/formConfig/JSEditorConfigs.ts
> +export default [
removed

2021-08-31 08:07 UTC, ApekshaBhosale commented on app/client/src/components/editorComponents/JSResponseView.tsx
> +    jsObject: JSAction | undefined;
removed

2021-08-31 08:08 UTC, ApekshaBhosale commented on app/client/src/constants/forms.ts
> +export const JS_EDITOR_FORM = "jsEditorForm";
removed as this is not needed anymore

2021-08-31 08:09 UTC, ApekshaBhosale commented on app/client/src/pages/Editor/JSEditor/Form.tsx
> +  const jsActions: JSAction[] = useSelector((state: AppState) =>
removed

2021-08-31 08:13 UTC, ApekshaBhosale commented on app/client/src/entities/DataTree/dataTreeJSAction.ts
> +  const variables = js?.config?.variables;
removed

2021-08-31 08:13 UTC, ApekshaBhosale commented on app/client/src/entities/DataTree/dataTreeJSAction.ts
> +  const actions = js?.config?.actions;
removed

2021-09-01 07:34 UTC, hetunandu approved these changes

2021-09-02 10:14 UTC, ApekshaBhosale commented
some bugs are fixed here https://github.com/appsmithorg/appsmith/pull/7056

2021-09-08 11:53 UTC, hetunandu submitted a review, later dismissed

2021-09-08 12:38 UTC, hetunandu approved these changes

2021-09-08 13:53 UTC, nidhi-nair submitted a review, later dismissed

2021-09-08 16:11 UTC, nidhi-nair approved these changes

2021-09-08 17:32 UTC, merged