Show lint errors in the debugger
appsmithorg/appsmith pull request #6006
Opened 2021-07-20 13:36 UTC by vnodecg

## Description
We are not showing lint errors in the debugger. This MR addresses this issue

Fixes #5661 

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
This has been manually tested

![Screen Shot 2021-07-20 at 8 05 39 AM](https://user-images.githubusercontent.com/4994565/126331058-f7b227fe-b25e-4ad8-b183-8100c640f15e.png)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-07-21 06:48 UTC, hetunandu requested changes

2021-07-21 06:48 UTC, hetunandu commented on app/client/src/sagas/PostEvaluationSagas.ts
> +          const error = errors[0];
Why do we need the first error now

2021-07-21 06:48 UTC, hetunandu commented on app/client/src/sagas/PostEvaluationSagas.ts
> +            !debuggerKey.endsWith("warning") &&
Needs a better check than just `endsWith("warning")`

2021-07-21 06:48 UTC, hetunandu commented on app/client/src/sagas/PostEvaluationSagas.ts
> +            text: PropertyEvalErrorTypeDebugMessage[error.errorType](
Need a seperate error message for warnings

2021-07-27 22:19 UTC, vnodecg commented on app/client/src/sagas/PostEvaluationSagas.ts
> +          const error = errors[0];
We are using it to set errorType text.

```
            text: PropertyEvalErrorTypeDebugMessage[error.errorType](
              propertyPath,
            ),
```

2021-07-27 22:19 UTC, vnodecg commented on app/client/src/sagas/PostEvaluationSagas.ts
> +            !debuggerKey.endsWith("warning") &&
`warning` here is hardcode so it serves the purpose

2021-07-27 22:20 UTC, vnodecg commented on app/client/src/sagas/PostEvaluationSagas.ts
> +            text: PropertyEvalErrorTypeDebugMessage[error.errorType](
done

2021-07-28 09:34 UTC, hetunandu commented on app/client/src/sagas/PostEvaluationSagas.ts
> +            text: PropertyEvalErrorTypeDebugMessage[error.errorType](
I dont see the update. Did you push your changes?

2021-07-28 09:34 UTC, hetunandu commented on app/client/src/sagas/PostEvaluationSagas.ts
> +          const error = errors[0];
Just extract the error type in this case

2021-07-29 15:37 UTC, vnodecg commented on app/client/src/sagas/PostEvaluationSagas.ts
> +            text: PropertyEvalErrorTypeDebugMessage[error.errorType](
I have pushed the changes

2021-07-30 07:16 UTC, hetunandu requested changes

2021-07-30 07:16 UTC, hetunandu commented on app/client/src/sagas/PostEvaluationSagas.ts
> +            severity: isWarning ? Severity.WARNING : Severity.ERROR,
`error.severity` should have this right?

2021-07-30 07:16 UTC, hetunandu commented on app/client/src/sagas/PostEvaluationSagas.ts
> +      };
This structure does not work because you end up checking for key anyways to see if a given errors severity

2021-07-30 07:16 UTC, hetunandu commented on app/client/src/sagas/PostEvaluationSagas.ts
> +            logType: isWarning ? LOG_TYPE.EVAL_WARNING : LOG_TYPE.EVAL_ERROR,
<img width="1187" alt="Screenshot 2021-07-30 at 12 41 36 PM" src="https://user-images.githubusercontent.com/12022471/127615664-ae893388-8776-428f-86e9-8e873109004b.png">

This still says error instead of warning.

<img width="125" alt="Screenshot 2021-07-30 at 12 45 29 PM" src="https://user-images.githubusercontent.com/12022471/127615717-23e3f86d-211f-4496-acfe-51fde814ffbd.png">

The badge color should be yellow if it is only errors

2021-08-02 05:23 UTC, vnodecg commented on app/client/src/sagas/PostEvaluationSagas.ts
> +            severity: isWarning ? Severity.WARNING : Severity.ERROR,
Yea

2021-08-02 05:51 UTC, vnodecg commented on app/client/src/sagas/PostEvaluationSagas.ts
> +      };
updated structure

2021-08-02 05:55 UTC, vnodecg commented on app/client/src/sagas/PostEvaluationSagas.ts
> +            logType: isWarning ? LOG_TYPE.EVAL_WARNING : LOG_TYPE.EVAL_ERROR,
https://www.loom.com/share/518cd14124754164b804abadb55c9bb9

2021-08-02 08:51 UTC, vnodecg commented on app/client/src/sagas/PostEvaluationSagas.ts
> +            logType: isWarning ? LOG_TYPE.EVAL_WARNING : LOG_TYPE.EVAL_ERROR,
https://www.loom.com/share/0f7c0cb00bef4aa98e666182b95e26dd

2021-08-03 06:09 UTC, akash-codemonk commented
<img width="732" alt="duplicate" src="https://user-images.githubusercontent.com/67054171/127966152-5686f61d-4837-4bab-a8a0-a925eb983224.png">

There are two logs for the same error

2021-08-06 05:20 UTC, hetunandu commented
> <img alt="duplicate" width="732" src="https://user-images.githubusercontent.com/67054171/127966152-5686f61d-4837-4bab-a8a0-a925eb983224.png">
> 
> There are two logs for the same error

Can we do something about this @vnodecg ? I think it is because one is a PARSE error and another is a LINT error

2021-08-10 12:01 UTC, vnodecg commented
> > <img alt="duplicate" width="732" src="https://user-images.githubusercontent.com/67054171/127966152-5686f61d-4837-4bab-a8a0-a925eb983224.png">
> > There are two logs for the same error
> 
> Can we do something about this @vnodecg ? I think it is because one is a PARSE error and another is a LINT error

We need to pick out the parse errors. We don't have an automated way right now. We can blacklist some parse errors that are duplicated

2021-08-10 12:05 UTC, vnodecg commented
Accidentally closed it

2021-08-12 05:56 UTC, vnodecg commented
Closing this since we are merging this with #6265

2021-08-12 05:56 UTC, closed without merging