Feature : Style customization in the button widget
appsmithorg/appsmith pull request #6052
Opened 2021-07-21 12:08 UTC by wmdev0808

## Description

- Add relevant properties for style customization
- Complete the first MVP of the button widget with the newly added style properties

Fixes #4149 

## Type of change
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?

- Test A
- Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-07-22 12:10 UTC, somangshu submitted a review, later dismissed
Approving to run tests

2021-07-23 06:16 UTC, somangshu commented
Rerunning tests because of unexpected failures

2021-07-23 06:54 UTC, somangshu commented
@wmdev0808 feedback from the deploy preview.
- The border radius in the rounded corner mode should be reduced to 5px.
- The automated dark font colour is right now `rgb(169, 167, 167) !important`, should change to `#333`.
- Icon colour should inherit the colour from parent text, Icon colour prop should be removed
- Icon alignment should be should be set to default when an icon is set for the first time.
- In the icon control `none` should always be the first selection as there is no other way to remove the icon. This will have a global effect
- Reordering sections: 
    - General
        - Label, Visible, Disable, Google recaptcha key, Google recaptcha V2
    - Actions (All properties)
    - Style (The rest of the style attributes)

2021-07-23 10:39 UTC, somangshu submitted a review, later dismissed
Approving to run tests.

@wmdev0808 please check the pending comments

2021-07-26 10:37 UTC, somangshu approved these changes
LGTM

2021-07-27 05:30 UTC, SatishGandham requested changes

2021-07-27 05:30 UTC, SatishGandham commented on app/client/src/constants/DefaultTheme.tsx
> +      solid: {
Can you extra button properties to a separate type and use it.

2021-07-30 05:23 UTC, SatishGandham submitted a review, later dismissed

2021-07-30 06:22 UTC, somangshu commented
Rerunning all tests, Many unrelated tests are failing

2021-08-05 05:24 UTC, somangshu commented
@wmdev0808 please merge latest release, resolve conflicts and push back to done

2021-08-05 10:10 UTC, somangshu submitted a review, later dismissed

2021-08-09 07:05 UTC, somangshu approved these changes

2021-08-09 12:21 UTC, somangshu commented
Rerunning all jobs, Everything failed in the last run

2021-08-09 17:08 UTC, somangshu submitted a review, later dismissed

2021-08-11 12:03 UTC, somangshu commented
@arslanhaiderbuttar can you drop an update here

2021-08-16 06:32 UTC, somangshu commented
@vivekverma2312 I see some functionalities not working here any more, Can you verify all the [requested changes](https://github.com/appsmithorg/appsmith/pull/6052#issuecomment-885438739) again. Moving this back to QA pipeline.

2021-08-18 05:50 UTC, vivekverma2312 commented
@wmdev0808 On selecting custom in Button style the Background change property is not coming. Basically there is no change if user selects custom button style.
<img width="551" alt="Screenshot 2021-08-18 at 11 19 25 AM" src="https://user-images.githubusercontent.com/83569920/129844424-2eb392d9-e9d2-4163-9f99-34f91574b8ae.png">

2021-08-18 05:56 UTC, vivekverma2312 commented
@wmdev0808 Oops something went wrong on widget and getting `Cannot read property 'hoverColor' of undefined` in console error on button variant JS property.
https://www.loom.com/share/47e67a41a7d74e9b85e7ca27d80a8edd

2021-08-19 15:04 UTC, somangshu approved these changes
Approving for tests to run

2021-08-20 08:55 UTC, somangshu commented
@vivekverma2312 we need to recheck if the widget has the missing functionalities now

2021-08-23 12:48 UTC, vivekverma2312 commented
@wmdev0808 Deploy preview is tested and all the bugs are fixed. Good to go to release.

2021-08-24 06:02 UTC, somangshu approved these changes
Approving to run tests

2021-08-24 11:07 UTC, somangshu commented
Rerunning all tests here, `LoginFromUIApp_spec.js` failed

2021-08-24 13:00 UTC, somangshu approved these changes
LGTM, Changes related to the security issue where the package.json and yarn.json had a diff.

2021-08-24 13:53 UTC, merged