Table sort column APIs
appsmithorg/appsmith pull request #6068
Opened 2021-07-22 08:47 UTC by vicky-primathon

## Description
Sorted column can be accessed using sortOrder table widget api. Add onSort action that lets user trigger an action whenever column sorting is changed

Fixes #5906 

## Type of change
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-07-26 11:41 UTC, vivekverma2312 commented
@vicky-primathon Functionality is working fine but can you please add tooltip for sort property.

2021-07-26 12:19 UTC, somangshu requested changes

2021-07-26 12:19 UTC, somangshu commented on app/client/src/widgets/TableWidget/TablePropertyPaneConfig.ts
> +        helpText: "Triggers an action when a table is sorted on a column",
Change to "Triggers an action when a table column is sorted"

2021-07-27 05:22 UTC, SatishGandham approved these changes

2021-07-27 06:26 UTC, somangshu commented
@vicky-primathon can you merge the latest release as well and check for the the failing test cases?

2021-07-27 07:15 UTC, somangshu approved these changes

2021-07-28 05:25 UTC, vivekverma2312 commented
@vicky-primathon Tooltip is also fixed.

2021-07-28 06:20 UTC, somangshu commented
Rerunning all tests, Unrelated failures found. 

@vicky-primathon please assert.

2021-08-11 09:42 UTC, somangshu approved these changes

2021-08-12 09:37 UTC, vicky-primathon commented
/ok-to-test sha=a8e98c2

2021-08-12 12:13 UTC, somangshu submitted a review, later dismissed
Approving to run tests

2021-08-12 12:58 UTC, SatishGandham requested changes

2021-08-12 12:58 UTC, SatishGandham commented on app/client/src/utils/autocomplete/EntityDefinitions.ts
> +      column: "string",
Sort order should be a enum, not boolean.
['ASC','DESC']

2021-08-13 11:34 UTC, YogeshJayaseelan commented
@vicky-primathon Testing in-progress for this feature and please find the observations below

1. asc:true or asc:false key and value should not be displayed when the table column is bind-ed with text widget 

Text Widget - Label field - {{JSON.stringify(Table1.sortOrder)}}

<img width="1680" alt="Screenshot 2021-08-13 at 4 58 01 PM" src="https://user-images.githubusercontent.com/35128442/129350869-d344ebca-265d-4a7f-b941-99ceacbe5fa8.png">

2.By default when the table's column and order is sorted and stored in a text widget - 'undefined, undefined' key and value is displayed 

<img width="1680" alt="Screenshot 2021-08-13 at 5 02 15 PM" src="https://user-images.githubusercontent.com/35128442/129351151-d9bc6446-b49a-493e-9741-f8cad7f02cb3.png">

2021-08-18 10:05 UTC, YogeshJayaseelan commented
@vicky-primathon Verified this PR and it is working as expected

2021-08-19 03:51 UTC, SatishGandham approved these changes

2021-08-24 05:23 UTC, somangshu approved these changes

2021-08-25 13:20 UTC, merged

2021-09-03 05:53 UTC, YogeshJayaseelan commented
@vicky-primathon Issue 1 and 2 now exists in release environment