chart added series title
appsmithorg/appsmith pull request #6104
Opened 2021-07-23 12:53 UTC by techbhavin

## Description

> Add seriesTitle in selectedDataPoint

Fixes #5793

## Type of change
- Bugfix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ]  I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-07-27 12:21 UTC, riodeuno requested changes
One comment. Rest looks good. 
Can we add a cypress test for this scenario? Click on chart, check if the bound value in a text widget has the `seriesTitle`.

2021-07-27 12:21 UTC, riodeuno commented on app/client/src/components/designSystems/appsmith/ChartComponent.tsx
> +    } else {
No need for `else` here. Also, what happens when `data` is `undefined`? It seems like it will throw an error.

2021-07-28 06:59 UTC, vivekverma2312 commented
@techbhavin This is working fine on the deploy preview.

2021-08-02 02:35 UTC, techbhavin commented
/ok-to-test sha= 443045b

2021-08-02 12:53 UTC, somangshu commented
@techbhavin if you have made changes as per the review request kindly re-request for review and update the pipeline accordingly

2021-08-02 13:08 UTC, techbhavin commented on app/client/src/components/designSystems/appsmith/ChartComponent.tsx
> +    } else {
@riodeuno  here we use lodash get function and its 3rd param is  default return if there is data is null or selected key is not found. so we are not required `try...catch`.

we can't remove `else` because `CUSTOM_FUSION_CHART` and `PIE_CHART` have different data sources so I add `else` blog. 

can you please give me more detail so I can remove else blog

2021-08-13 05:16 UTC, riodeuno approved these changes
LGTM

2021-08-13 05:16 UTC, riodeuno commented on app/client/src/components/designSystems/appsmith/ChartComponent.tsx
> +    } else {
The `if` and `else` blocks both seem to have a `return`, which is why I thought that the `else` block isn't necessary. Does not make a big difference in the maintainability of the code. We can keep it as it is.

@techbhavin @vivekverma2312 We just need to make sure that odd and unexpected values like `[]`, `{}`, `undefined`, etc, do not circumvent validations to cause issues here.

2021-08-18 06:47 UTC, vivekverma2312 commented
@techbhavin Tested and looks good to me.

2021-08-18 07:11 UTC, merged