added tooltip icon and hover functionality
appsmithorg/appsmith pull request #6105
Opened 2021-07-23 12:53 UTC by techbhavin

## Description

> Add tooltip text on Button Widgets

Fixes #5192

> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

- Bugfix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ]  I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-08-02 02:35 UTC, techbhavin commented
/ok-to-test sha= 86db1d7

2021-08-05 05:52 UTC, somangshu commented on app/client/src/widgets/ButtonWidget.tsx
> +            helpText: "Show help text or details about current button",
Change this to > "Show helper text with button on hover"

2021-08-05 05:56 UTC, somangshu commented on app/client/src/components/designSystems/blueprint/ButtonComponent.tsx
> +const ToolTipIcon = styled(IconWrapper)`
We dont need a tooltip icon. A hover on anywhere in the button should show the tooltip. Remove all related code

2021-08-05 05:56 UTC, somangshu requested changes
Changes as requested

2021-08-06 09:26 UTC, techbhavin commented
/ok-to-test sha= 454c391

2021-08-09 10:02 UTC, somangshu requested changes
This is causing a problem to the button skeleton in the loading state. @techbhavin

2021-08-09 10:02 UTC, somangshu commented on app/client/src/components/designSystems/blueprint/ButtonComponent.tsx
> +        icon={props.icon}
Why is this required?

2021-08-09 10:54 UTC, techbhavin commented on app/client/src/components/designSystems/blueprint/ButtonComponent.tsx
> +        icon={props.icon}
@somangshu  here we revert code with same as original code (before we add hover tooltip on the icon but after change request, we change to button hover ) so. you can check with the PR file compare.

2021-08-09 11:03 UTC, somangshu commented on app/client/src/components/designSystems/blueprint/ButtonComponent.tsx
> +        icon={props.icon}
Please check the loading issue otherwise

2021-08-10 06:04 UTC, techbhavin commented
/ok-to-test sha= 01de502

2021-08-16 14:27 UTC, somangshu approved these changes

2021-08-16 14:27 UTC, somangshu commented
Deploy preview looks good as well

2021-08-17 11:26 UTC, merged

2021-09-03 04:57 UTC, YogeshJayaseelan commented
@techbhavin @somangshu - is this applicable for table button type column as well? currently i could see this applicable for button and not for table column button types

2021-09-03 05:07 UTC, somangshu commented
This is only for the button widget @YogeshJayaseelan