Add analytics event for mock-data creation
appsmithorg/appsmith pull request #6136
Opened 2021-07-26 11:04 UTC by AnaghHegde

## Description

> Added analytics event for mockdata creation

Fixes #5427 

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Test A
- Test B

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

2021-07-26 12:12 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/MockDataServiceImpl.java
> +            addAnalyticsForMockDataCreation(mockDataSource.getName(), mockDataSource.getOrganizationId());
If I'm getting this correct name for mockDataSource might be altered in _**createSuffixedDatasource**_ which might result in an incorrect DB name for analytics datapoint. My proposal would be to chain this function after creating the suffixed DB and return _Mono< Datasource >_ from the **_addAnalyticsForMockDataCreation_** function.

2021-07-26 12:20 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/MockDataServiceImpl.java
> +    private Mono<Void> addAnalyticsForMockDataCreation(String name, String orgId) {
Can we directly use **_analyticsService.sendCreateEvent(object, props)_** ?

2021-07-26 12:47 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/MockDataServiceImpl.java
> +            addAnalyticsForMockDataCreation(mockDataSource.getName(), mockDataSource.getOrganizationId());
Since the name is affected in the createDataSource method, it wouldn't be affected right. The name issue will be there even if i chain it after creating the suffixed DB.

2021-07-26 12:52 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/MockDataServiceImpl.java
> +    private Mono<Void> addAnalyticsForMockDataCreation(String name, String orgId) {
It would be good to separate it out, since the method does a separate functionalities

2021-07-26 12:53 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/MockDataServiceImpl.java
> +            addAnalyticsForMockDataCreation(mockDataSource.getName(), mockDataSource.getOrganizationId());
I mean something like : 

```
return  createSuffixedDatasource(datasource)
                .flatMap(analyticsService::sendCreateEvent);

```

2021-07-26 12:57 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/MockDataServiceImpl.java
> +            addAnalyticsForMockDataCreation(mockDataSource.getName(), mockDataSource.getOrganizationId());
But if i do that, i would need to have the user info. But since i dont have that, i thought of creating new method would be good.

2021-07-28 07:03 UTC, rishabhsaxena approved these changes

2021-07-28 07:03 UTC, rishabhsaxena commented on app/client/src/pages/Editor/IntegrationEditor/MockDataSources.tsx
> +      datasourceName: datasource.name,
just to check: should we add null checks here just as a precaution: `datasource?.name`

2021-07-28 07:04 UTC, nayan-rafiq requested changes

2021-07-28 07:04 UTC, nayan-rafiq commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/MockDataServiceImpl.java
> +                .flatMap(user -> {
As this function does not return a reactive producer, please use `map` instead of `flatMap` here.

2021-07-28 07:04 UTC, nayan-rafiq commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/MockDataServiceImpl.java
> +            addAnalyticsForMockDataCreation(name, mockDataSource.getOrganizationId());
`addAnalyticsForMockDataCreation` will never be called as it's not chained to current pipeline. It should be something like the following:
`return addAnalyticsForMockDataCreation(name, mockDataSource.getOrganizationId()).then(createSuffixedDatasource(datasource))`

2021-07-28 07:10 UTC, pranavkanade commented on app/client/src/pages/Editor/IntegrationEditor/MockDataSources.tsx
> +      datasourceName: datasource.name,
there is no need, this `datasource` comes from something like - `{props.mockDatasources.map((datasource: MockDatasource,`. As `mockDatasources` is fetched from an api, it is bullet proof.

2021-07-28 07:24 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/MockDataServiceImpl.java
> +                    then(createSuffixedDatasource(datasource));
Minor refactor here : 
`return addAnalyticsForMockDataCreation(name, mockDataSource.getOrganizationId())
                    .then(createSuffixedDatasource(datasource));`

2021-07-28 07:27 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/MockDataServiceImpl.java
> +                    then(createSuffixedDatasource(datasource));
I just realised that i forgot to remove it. Just pushed the change

2021-07-28 08:42 UTC, abhvsn submitted a review, later dismissed
LGTM

2021-07-28 08:42 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/MockDataServiceImpl.java
> +                    .then(createSuffixedDatasource(datasource));
It's good practice to create a resource and then chain it to analytics. I might be wrong here but chaining can be `return createResource().then(analyticsEvent());`

2021-08-02 03:00 UTC, merged