Feature: controller and test API for JS snippets
appsmithorg/appsmith pull request #6139
Opened 2021-07-26 11:40 UTC by sumitsum

## Description
- add controller for JS snippets
- add a dummy api to return dummy data for client to test
- add DTOs for JS snippet

Fixes # (issue)

## Type of change
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
- using Postman

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-07-26 13:33 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/JsSnippetsController.java
> +    public JsSnippetsController() {}
This seems extraneous

2021-07-26 13:38 UTC, nidhi-nair requested changes

2021-07-26 13:38 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/JsSnippetsController.java
> +    @PostMapping("getDummy")
Should this be a GET request?

2021-07-26 13:38 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/JsSnippetsController.java
> +        JsSnippetDTO testResponse1 = new JsSnippetDTO();
Just a suggestion that might come in handy. If these dummy requests are going to go through iterations, you might find it easier to read this from a static json file.

2021-07-26 13:38 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/JsSnippetDTO.java
> +    List<String> args;
For arguments, do you want to represent these using another DTO? It is possible that arguments have description for their type, the use case for that argument, and default values as well.

2021-07-26 13:38 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/JsSnippetsRequestDTO.java
> +    List<String> entity; // e.g. table
Could you please explain what each of these fields represents?

2021-07-26 13:44 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/JsSnippetDTO.java
> +    List<String> args;
The way we are modelling it currently, each argument is a text description. It is as per the design we decided for it: https://www.figma.com/file/uuOCKMSD7WdqUDbS0dfBYM/Snippets-%2B-OmniBar-V2---Navigate%2CSnippets%2CDocumentation?node-id=91%3A493

2021-07-26 13:46 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/JsSnippetsController.java
> +        JsSnippetDTO testResponse1 = new JsSnippetDTO();
Thanks. I also thought about it but went for this for the time being since the actual API may be available soon.

2021-07-30 14:51 UTC, sumitsum commented
Closing it since we have decided go with Algolia search for search queries. As of now there is no requirement for any server side APIs. Client will directly call Algolia's API's for search query.

2021-07-30 14:51 UTC, closed without merging