Remove autogenerate column from insert query for generate CRUD page from DB table
appsmithorg/appsmith pull request #6183
Opened 2021-07-27 07:54 UTC by abhvsn

## Description

> When DB table has autogenerate field in the structure InsertQuery is failing if we try to overwrite the value. Also if the page already have widgets page creation flow should throw error to try this flow on empty canvas.  

Fixes #6128 #6182

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Manually on local instance
> Update TCs accordingly

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-07-27 09:47 UTC, nayan-rafiq requested changes

2021-07-27 09:47 UTC, nayan-rafiq commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/CreateDBTablePageSolution.java
> +                .flatMap(newPage -> {
Seems we can use `map` instead of `flatMap` here as it's not calling any reactive code.

2021-07-27 09:47 UTC, nayan-rafiq commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/CreateDBTablePageSolution.java
> +    private String templateAutogeneratedKey = null;
I'm not sure about how this field is used so I may be wrong. Seems this field may create problems when concurrent users are accessing this bean. As this bean is created with default scope, there'll be a single instance of `CreateDBTablePageSolution`. What will happen if at any point two threads simultaneously access this field? 

Consider a case:
- thread1 and thread2 accessing the object aka bean simultaneously
- thread1 found it null and set a value which is specific to thread1
- thread2 also found it null and set another value which overrides the value from thread1
- thread1 uses the value but it's actually set from thread2

2021-07-27 09:47 UTC, nayan-rafiq commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/CreateDBTablePageSolution.java
> +        AtomicReference<String> sourceKey = new AtomicReference<>();
What is the purpose of using `AtomicReference`? I've no idea on this so curious to learn their purpose.

2021-07-27 10:29 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/CreateDBTablePageSolution.java
> +                .flatMap(newPage -> {
Yes, I first used the map but for throwing the exception where we are generating the exception like Mono.error it requires the flatmap? Is there a better way to throw error without the need for flatmap?

2021-07-27 13:47 UTC, nayan-rafiq commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/CreateDBTablePageSolution.java
> +                .flatMap(newPage -> {
Just throwing the exception from map function should work in this case I guess.

2021-07-28 06:41 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/CreateDBTablePageSolution.java
> +    private String templateAutogeneratedKey = null;
Changing this to function scope instead of class

2021-07-28 06:49 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/CreateDBTablePageSolution.java
> +                .flatMap(newPage -> {
Sorry my bad, updated code pushed!

2021-07-28 06:55 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/CreateDBTablePageSolution.java
> +        AtomicReference<String> sourceKey = new AtomicReference<>();
Removed the AtomicReference for this particular case as it's not required here but in general it's generally used to have thread safe operations on variables. With AtomicReference you can have methods like compareAndSet() etc to make sure current and updated values match. You can find more about it [here](https://dzone.com/articles/java-concurrency-atomicreference)

2021-07-28 07:39 UTC, nayan-rafiq approved these changes
LGTM

2021-07-28 07:44 UTC, merged