FIX #4955 : updated page count on enter key press
appsmithorg/appsmith pull request #6196
Opened 2021-07-27 11:40 UTC by vibhandikyash

## Description

> updated page count on enter key press

Fixes #4955 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Tested locally.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-07-30 05:26 UTC, SatishGandham commented on app/client/src/components/designSystems/appsmith/TableComponent/TableHeader.tsx
> +      if (oldPageNo < page) {
Less than or greater than doesn't mean previous or next page.
I can go from 20->21 or 20->40.

Please check if 20->40 should trigger next page event.

2021-07-30 05:28 UTC, SatishGandham requested changes

2021-07-30 05:28 UTC, SatishGandham commented on app/client/src/components/designSystems/appsmith/TableComponent/TableHeader.tsx
> +      const value = e.target.value;
Can we combine these two lines.?

2021-08-04 06:01 UTC, SatishGandham approved these changes

2021-08-10 13:09 UTC, somangshu approved these changes

2021-08-12 04:44 UTC, vibhandikyash commented
> @vibhandikyash In above deploy preview I am not able to edit the page no properly
> 
> 1. Delete button navigate to page no-1
> 2. Entering page no-5 shows page no-15
> 3. Enter button does nothing until user click somewhere on the canvas
> 
> https://www.loom.com/share/9b4480d2976d4910b31d73d96335a2b4

@vivekverma2312 According to the validations placed any pagenumber more than the max is not allowed I am not sure how does that appear for you. Are you using the deploy preview link?

2021-08-17 07:07 UTC, somangshu commented
@vibhandikyash @vivekverma2312 here is my observation:
- The single digit page numbers can only be reached with the arrow keys and not the numbers directly, ex 1 > 5 > 8
- Pressing enter key works correctly for me
- Pagination result is not lost until the enter key is pressed or input is blurred

2021-08-20 07:24 UTC, somangshu approved these changes
LGTM, Deploy preview tested as well

2021-08-23 11:07 UTC, somangshu approved these changes

2021-08-25 07:20 UTC, vivekverma2312 commented
DP is tested and working fine.

2021-08-25 14:10 UTC, merged