Feature : Checkbox Group widget
appsmithorg/appsmith pull request #6199
Opened 2021-07-27 12:41 UTC by wmdev0808

## Description

- Build the first MVP of the widget
Fixes #3344 

## Type of change

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

## How Has This Been Tested?

- Test A
- Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-07-29 05:02 UTC, marks0351 commented
@wmdev0808 
Comments after looking at the deploy preview:

- Each checkbox inside a checkbox group should be the height of each row else in most cases the group alignment will not be symmetrical. 
- The required border takes up the width of the widget so when its enabled u can see the widget moving coz of decrease in space. try using box-show instead.
- Also with the default dimensions of the dropped widget when required is enabled the widget looks weird.

One weird bug:
- Open prop pane
- Remove value for one of the options(Lemon) keep it empty.
- Then remove value for another(Orange)
- Now add a value for Orange you will see a new entry for Orange. 
This seems to happen with radio group as well.
cc: @somangshu

2021-07-29 05:10 UTC, marks0351 requested changes

2021-07-29 05:10 UTC, marks0351 commented on app/client/src/utils/autocomplete/EntityDefinitions.ts
> +    "!url": "https://docs.appsmith.com/widget-reference/checkbox-group",
Is there a appsmith docs PR for this?

2021-07-29 05:10 UTC, marks0351 commented on app/client/src/mockResponses/WidgetConfigResponse.tsx
> +      isDisabled: false,
should we have a default inline value as well?

2021-07-29 05:10 UTC, marks0351 commented on app/client/src/widgets/CheckboxGroupWidget.tsx
> +            propertyName: "onCheckChanged",
can u change this to onSelectionChange

2021-07-29 05:11 UTC, marks0351 commented
@wmdev0808 Can u also add jest and cypress tests for this widget.

2021-07-29 09:08 UTC, YogeshJayaseelan commented
@wmdev0808 @jsartisan Tested this feature and came up with the below issues 

1. Option label and values cannot be duplicated 

<img width="1680" alt="Screenshot 2021-07-29 at 1 08 13 PM" src="https://user-images.githubusercontent.com/35128442/127452958-54a7a3b6-780a-44e4-aebf-4518f9de1c9b.png">

2. When you decrease the size of the widget the checkbox value should not go out of the widget 

<img width="1680" alt="Screenshot 2021-07-29 at 1 08 36 PM" src="https://user-images.githubusercontent.com/35128442/127453118-34d9594c-a76a-4540-89cd-bcb7bfc6783b.png">

3. Executing an api and creating map function in the checkbox widget - option JS field and clicking on options the value disappears and the widget is shown empty 

Note: You can use any api and based on the output map functions needs to be created 

API used - https://reqres.in/api/users?page=2 

MapFunction - {{ Api1.data.data.map((row) => {
      return { label: row.first_name, value: row.first_name }
   })
}}

https://loom.com/share/5d85272fead043f8baf9cd8441e181d1 


4. When the default option is deleted and bind-ed with text widget {{checkbox1.Selectedvalue}} the deleted option value is displayed in the text widget 

https://loom.com/share/181798e515ea4321aae8d323ed899792

5. By default user is unable to check and uncheck checkbox and it is observed that only when the default value selected value is passed user is able to check/uncheck 

https://loom.com/share/c2391558567941b08e9f8ad0deb86af9

6. The Default selected value design is not matching the figma design 

<img width="1680" alt="Screenshot 2021-07-29 at 2 28 33 PM" src="https://user-images.githubusercontent.com/35128442/127463453-d9d44a8d-440e-4de5-b58a-aa1b565797cf.png">

7. When the incorrect JS option map function is passed the checkbox widget crashes 

https://www.loom.com/share/db6eb1503aa34f37b3a068bff80b02e5

8. when you added multiple labels and when you delete labels the widget size can be enlarged when added more that default size and reduced whenever an label is removed 

https://www.loom.com/share/f6b9a4229a954169acfc05f17d8b712b

9. Suggestion - For the default selected value - The expected structure can be 'Value or Value of array' similar to select widget 

https://www.loom.com/share/3855037811e141109642dc3d15dff671

2021-07-30 07:05 UTC, wmdev0808 commented
> @wmdev0808 @jsartisan Tested this feature and came up with the below issues
> 
> 1. Option label and values cannot be duplicated
> 
> <img alt="Screenshot 2021-07-29 at 1 08 13 PM" width="1680" src="https://user-images.githubusercontent.com/35128442/127452958-54a7a3b6-780a-44e4-aebf-4518f9de1c9b.png">
> 
> 1. When you decrease the size of the widget the checkbox value should not go out of the widget
> 
> <img alt="Screenshot 2021-07-29 at 1 08 36 PM" width="1680" src="https://user-images.githubusercontent.com/35128442/127453118-34d9594c-a76a-4540-89cd-bcb7bfc6783b.png">
> 
> 1. Executing an api and creating map function in the checkbox widget - option JS field and clicking on options the value disappears and the widget is shown empty
> 
> Note: You can use any api and based on the output map functions needs to be created
> 
> API used - https://reqres.in/api/users?page=2
> 
> MapFunction - {{ Api1.data.data.map((row) => {
> return { label: row.first_name, value: row.first_name }
> })
> }}
> 
> https://loom.com/share/5d85272fead043f8baf9cd8441e181d1
> 
> 1. When the default option is deleted and bind-ed with text widget {{checkbox1.Selectedvalue}} the deleted option value is displayed in the text widget
> 
> https://loom.com/share/181798e515ea4321aae8d323ed899792
> 
> 1. By default user is unable to check and uncheck checkbox and it is observed that only when the default value selected value is passed user is able to check/uncheck
> 
> https://loom.com/share/c2391558567941b08e9f8ad0deb86af9
> 
> 1. The Default selected value design is not matching the figma design
> 
> <img alt="Screenshot 2021-07-29 at 2 28 33 PM" width="1680" src="https://user-images.githubusercontent.com/35128442/127463453-d9d44a8d-440e-4de5-b58a-aa1b565797cf.png">
> 
> 1. When the incorrect JS option map function is passed the checkbox widget crashes
> 
> https://www.loom.com/share/db6eb1503aa34f37b3a068bff80b02e5
> 
> 1. when you added multiple labels and when you delete labels the widget size can be enlarged when added more that default size and reduced whenever an label is removed
> 
> https://www.loom.com/share/f6b9a4229a954169acfc05f17d8b712b
> 
> 1. Suggestion - For the default selected value - The expected structure can be 'Value or Value of array' similar to select widget
> 
> https://www.loom.com/share/3855037811e141109642dc3d15dff671

@

> @wmdev0808 @jsartisan Tested this feature and came up with the below issues
> 
> 1. Option label and values cannot be duplicated
> 
> <img alt="Screenshot 2021-07-29 at 1 08 13 PM" width="1680" src="https://user-images.githubusercontent.com/35128442/127452958-54a7a3b6-780a-44e4-aebf-4518f9de1c9b.png">
> 
> 1. When you decrease the size of the widget the checkbox value should not go out of the widget
> 
> <img alt="Screenshot 2021-07-29 at 1 08 36 PM" width="1680" src="https://user-images.githubusercontent.com/35128442/127453118-34d9594c-a76a-4540-89cd-bcb7bfc6783b.png">
> 
> 1. Executing an api and creating map function in the checkbox widget - option JS field and clicking on options the value disappears and the widget is shown empty
> 
> Note: You can use any api and based on the output map functions needs to be created
> 
> API used - https://reqres.in/api/users?page=2
> 
> MapFunction - {{ Api1.data.data.map((row) => {
> return { label: row.first_name, value: row.first_name }
> })
> }}
> 
> https://loom.com/share/5d85272fead043f8baf9cd8441e181d1
> 
> 1. When the default option is deleted and bind-ed with text widget {{checkbox1.Selectedvalue}} the deleted option value is displayed in the text widget
> 
> https://loom.com/share/181798e515ea4321aae8d323ed899792
> 
> 1. By default user is unable to check and uncheck checkbox and it is observed that only when the default value selected value is passed user is able to check/uncheck
> 
> https://loom.com/share/c2391558567941b08e9f8ad0deb86af9
> 
> 1. The Default selected value design is not matching the figma design
> 
> <img alt="Screenshot 2021-07-29 at 2 28 33 PM" width="1680" src="https://user-images.githubusercontent.com/35128442/127463453-d9d44a8d-440e-4de5-b58a-aa1b565797cf.png">
> 
> 1. When the incorrect JS option map function is passed the checkbox widget crashes
> 
> https://www.loom.com/share/db6eb1503aa34f37b3a068bff80b02e5
> 
> 1. when you added multiple labels and when you delete labels the widget size can be enlarged when added more that default size and reduced whenever an label is removed
> 
> https://www.loom.com/share/f6b9a4229a954169acfc05f17d8b712b
> 
> 1. Suggestion - For the default selected value - The expected structure can be 'Value or Value of array' similar to select widget
> 
> https://www.loom.com/share/3855037811e141109642dc3d15dff671

2021-08-04 08:31 UTC, wmdev0808 commented on app/client/src/mockResponses/WidgetConfigResponse.tsx
> +      isDisabled: false,
No

2021-08-05 12:44 UTC, wmdev0808 commented on app/client/src/utils/autocomplete/EntityDefinitions.ts
> +    "!url": "https://docs.appsmith.com/widget-reference/checkbox-group",
I will make it soon

2021-08-05 12:44 UTC, wmdev0808 commented on app/client/src/widgets/CheckboxGroupWidget.tsx
> +            propertyName: "onCheckChanged",
done

2021-08-05 12:47 UTC, wmdev0808 commented
> @wmdev0808 @jsartisan Tested this feature and came up with the below issues
> 
> 1. Option label and values cannot be duplicated
> 
> <img alt="Screenshot 2021-07-29 at 1 08 13 PM" width="1680" src="https://user-images.githubusercontent.com/35128442/127452958-54a7a3b6-780a-44e4-aebf-4518f9de1c9b.png">
> 
> 1. When you decrease the size of the widget the checkbox value should not go out of the widget
> 
> <img alt="Screenshot 2021-07-29 at 1 08 36 PM" width="1680" src="https://user-images.githubusercontent.com/35128442/127453118-34d9594c-a76a-4540-89cd-bcb7bfc6783b.png">
> 
> 1. ~Executing an api and creating map function in the checkbox widget - option JS field and clicking on options the value disappears and the widget is shown empty~ Issue is not related
> 
> Note: You can use any api and based on the output map functions needs to be created
> 
> API used - https://reqres.in/api/users?page=2
> 
> MapFunction - {{ Api1.data.data.map((row) => {
> return { label: row.first_name, value: row.first_name }
> })
> }}
> 
> https://loom.com/share/5d85272fead043f8baf9cd8441e181d1
> 
> 1. When the default option is deleted and bind-ed with text widget {{checkbox1.Selectedvalue}} the deleted option value is displayed in the text widget - this seems like an issue with the evaluation
> 
> https://loom.com/share/181798e515ea4321aae8d323ed899792
> 
> 1. By default user is unable to check and uncheck checkbox and it is observed that only when the default value selected value is passed user is able to check/uncheck
> 
> https://loom.com/share/c2391558567941b08e9f8ad0deb86af9
> 
> 1. The Default selected value design is not matching the figma design
> 
> <img alt="Screenshot 2021-07-29 at 2 28 33 PM" width="1680" src="https://user-images.githubusercontent.com/35128442/127463453-d9d44a8d-440e-4de5-b58a-aa1b565797cf.png">
> 
> 1. When the incorrect JS option map function is passed the checkbox widget crashes
> 
> https://www.loom.com/share/db6eb1503aa34f37b3a068bff80b02e5
> 
> 1. when you added multiple labels and when you delete labels the widget size can be enlarged when added more that default size and reduced whenever an label is removed
> 
> https://www.loom.com/share/f6b9a4229a954169acfc05f17d8b712b
> 
> 1. Suggestion - For the default selected value - The expected structure can be 'Value or Value of array' similar to select widget
> 
> https://www.loom.com/share/3855037811e141109642dc3d15dff671

2021-08-05 18:09 UTC, wmdev0808 commented on app/client/src/utils/autocomplete/EntityDefinitions.ts
> +    "!url": "https://docs.appsmith.com/widget-reference/checkbox-group",
I've made a PR for docs

2021-08-06 09:11 UTC, wmdev0808 commented
> @wmdev0808 Can u also add jest and cypress tests for this widget.

added cypress test

2021-08-09 06:35 UTC, marks0351 approved these changes

2021-08-09 07:07 UTC, somangshu commented
@wmdev0808 please check, `CheckboxGroup_spec.js` failed

2021-08-09 09:07 UTC, somangshu submitted a review, later dismissed
Approving to run tests

2021-08-10 04:57 UTC, YogeshJayaseelan commented
@wmdev0808 @somangshu Tested the fix and please find the status below,

**Issues Fixed:**
1,2,4,5,9

**Issues Reopened:**

3 - This is still happening - need confirmation that this is related to checkbox grouping widget. If not we can raise an separate issue 

6. Need confirmation here - Still the Default value doesn't match figma design 

7. This is still happening - But this time the app itself crashes by passing invalid Map function. 

https://www.loom.com/share/02363befef634d658e8626623c35a555

**Steps:**
**7.a)** Copy paste the following map function directly into the option JS field and observe- 
{{ Api1.data.data.map((row) => {
return { label: row.first_name, value: row.first_name }
})
}}
**7.b)** Or execute the following API - https://reqres.in/api/users?page=2 and pass the following valid map function 
{{ Api1.data.data.map((row) => {
return { label: row.first_name, value: row.first_name }
})
}} then modify the map function to invalid 

8) This is fixed - When user adds more options the widget has scroll options. But when the options are deleted the widget size still remains bigger 

https://www.loom.com/share/9f792acfd00c4e48afa23635731e2c6a

**New issue:**
10. 'The value does not evaluate to type string' error occurs when the checkbox selected value is bind-ed to the text widget 
https://loom.com/share/bbbb56bb4cf24629b2aab6e9da7cdd97

2021-08-10 08:31 UTC, somangshu commented
@YogeshJayaseelan I have updated your comment above. It was causing confusions. Let me know if you think something is not right

2021-08-12 04:45 UTC, YogeshJayaseelan commented
@wmdev0808 @somangshu Retested the fix and please find the status below,

**Issues Fixed :**
2,4,5,9 
3 - Will raise an separate issue 
6 - Expected behaviour 
8- Expected behaviour 
10 - Expected behaviour

**Issues reopened:**

1 - The option and values are non-case sensitive - If the existing option is 'Lemon' and its value is 'lemon' user is able to enter options and value as 'lemon' and 'Lemon' 

https://loom.com/share/db25aa3fd7874a3d872c3c717348a1b9 

7 - When the invalid map function is called - Now 'Reference not found' error is displayed. But still the app crashes when the user removes the values in the options field after getting (Referenced not found or illegal argument errors)

https://loom.com/share/e85769a1e3c94f97b9e6d3037c7d84f8

7.a) Copy paste the following map function directly into the option JS field and observe- {{ Api1.data.data.map((row) => { return { label: row.first_name, value: row.first_name } }) }} - Reference not found error will occur and remove the entire value from option field and observe
or 
7.b) Without any existing api - pass the following value inside option field - {{api1.data}} - Reference not found error wil occur and remove the entire value from option field and observe
or
7.c)execute the following API - https://reqres.in/api/users?page=2 and pass the following valid map function
{{ Api1.data.data.map((row) => { return { label: row.first_name, value: row.first_name } }) }} then modify the map function to invalid - Illegal argument error will occur and removed the value from the option field and observe

2021-08-13 07:15 UTC, somangshu commented
@YogeshJayaseelan please retest the changes here

2021-08-13 07:15 UTC, somangshu submitted a review, later dismissed
Approving to run tests

2021-08-16 11:47 UTC, YogeshJayaseelan commented
@wmdev0808 Verified the bug fixes and they are working as expected.

2021-08-16 14:09 UTC, somangshu commented
@wmdev0808 the `CheckboxGroup_spec.js` is still failing, Please look into this

2021-08-17 06:32 UTC, somangshu approved these changes
Approving to run tests

2021-08-17 07:01 UTC, somangshu commented
@marks0351 all done here, Can you give one sign-off on the review

2021-08-17 07:06 UTC, marks0351 approved these changes

2021-08-17 09:11 UTC, merged

2021-08-20 19:37 UTC, areyabhishek commented
@wmdev0808 Some comments:
1. The design of the checkbox doesn't match the Figma designs. 
<img width="244" alt="Screen Shot 2021-08-21 at 12 39 12 AM" src="https://user-images.githubusercontent.com/30255708/130284135-eb2e2564-9237-4668-909b-48c7727d88da.png">
2. The checkbox group isn't centered when there's just one option
<img width="248" alt="Screen Shot 2021-08-21 at 12 54 49 AM" src="https://user-images.githubusercontent.com/30255708/130284206-7406ffa9-5c0f-4617-83eb-e32d98c57a96.png">
3. The minimum gap between items when resized should be 15px like in the Figma files. When you resize the boundaries to smaller than this, then let the items overflow like in the image below for radio buttons.
<img width="244" alt="Screen Shot 2021-08-21 at 1 06 15 AM" src="https://user-images.githubusercontent.com/30255708/130285044-bc6fd9d8-2a73-44fe-bd6d-6b33592defad.png">

@somangshu @wmdev0808 @jsartisan What does the inline option do? The checkbox group moves around when it's resized and it doesn't have a minimum gap.

2021-08-23 05:55 UTC, somangshu commented
@areyabhishek
3. The min gap between the items are the min row height in which one item fits, Unlike Radio group we dont let the widget content overflow, rather add a scroll. 

The inline option give a flex wrap like behaviour, which could be a default. 

We will look into the rest.