Fix: List Widget issues
appsmithorg/appsmith pull request #6226
Opened 2021-07-28 12:28 UTC by jsartisan

Fixes #5730

2021-08-06 05:25 UTC, marks0351 approved these changes

2021-08-06 07:08 UTC, marks0351 approved these changes

2021-08-06 10:32 UTC, marks0351 requested changes

2021-08-06 10:32 UTC, marks0351 commented on app/client/src/sagas/WidgetOperationUtils.ts
> +          const js = stringSegments
can we extract these utils

2021-08-06 10:32 UTC, marks0351 commented on app/client/src/widgets/DropdownWidget.tsx
> +      isChanged = !(this.props.selectedOptionValue === selectedOption.value);
issue: not able to select same option in all items of list widget.

2021-08-06 10:32 UTC, marks0351 commented on app/client/src/widgets/ListWidget/ListWidget.tsx
> +    childWidgetData.bottomRow = shouldPaginate
lets have a constant for 34

2021-08-06 11:07 UTC, jsartisan commented on app/client/src/components/designSystems/appsmith/PositionedContainer.tsx
> +      zIndex: props.focused
This was needed because when resizing the template widget, I wanted to show it over the other container

2021-08-06 11:10 UTC, jsartisan commented on app/client/src/components/editorComponents/ResizableComponent.tsx
> +      parentWidgetToSelect?.widgetId !== props.widgetId &&
Not needed. Reverted this as we will be doing this as a separate feature.

2021-08-06 11:36 UTC, jsartisan commented on app/client/src/widgets/ListWidget/ListWidget.tsx
> +    childWidgetData.bottomRow = shouldPaginate
Done.

2021-08-06 11:37 UTC, jsartisan commented on app/client/src/sagas/WidgetOperationUtils.ts
> +          const js = stringSegments
Done.

2021-08-06 11:37 UTC, jsartisan commented on app/client/src/components/editorComponents/DraggableComponent.tsx
> +    if (parentWidgetToOpen && !propertyPaneState.isVisible) {
Reverted this.

2021-08-09 04:52 UTC, marks0351 approved these changes

2021-08-09 05:35 UTC, merged