Hotfix/trailing white spaces in mysql datasource configuration
appsmithorg/appsmith pull request #6227
Opened 2021-07-28 13:00 UTC by ohansFavour

## Description

## Changes made

- Added a new method for trimming input values on the JSONtoForm class
- Triggered the method when saving and testing the datasource connection
- Added cypress tests 

Fixes #6066 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

I ran all datasources tests and added a new test (app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/Datasources/MySQLDatasource_spec.js)

New configuration details were added

<img width="629" alt="Screenshot 2021-07-28 at 13 54 59" src="https://user-images.githubusercontent.com/46670083/127325668-a5575a96-7603-4e33-a554-7828e6c21db8.png">

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-07-29 06:08 UTC, hetunandu requested changes

2021-07-29 06:08 UTC, hetunandu commented on app/client/src/pages/Editor/DataSourceEditor/JSONtoForm.tsx
> +    if (formData && typeof formData === "object") {
use the [getType](https://github.com/appsmithorg/appsmith/blob/release/app/client/src/utils/TypeHelpers.ts#L16) function here

2021-08-03 10:43 UTC, ohansFavour commented on app/client/src/pages/Editor/DataSourceEditor/JSONtoForm.tsx
> +    if (formData && typeof formData === "object") {
All right. Fixed in latest commit.

2021-08-03 10:46 UTC, hetunandu approved these changes

2021-08-04 08:59 UTC, hetunandu approved these changes

2021-08-13 07:34 UTC, hetunandu approved these changes

2021-08-13 08:42 UTC, merged