menu style customization
appsmithorg/appsmith pull request #6237
Opened 2021-07-29 07:19 UTC by wmdev0808

## Description
- Make background none in case of choosing the transparent option
- Adopt new button style mechanism

Fixes #6117 

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

## How Has This Been Tested?

- Test A
- Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-07-30 05:12 UTC, somangshu approved these changes
Approving for tests to run. Please review the comments.

2021-07-30 05:12 UTC, somangshu commented on app/client/src/assets/icons/control/border-radius-rounded.svg
> +<svg width="16" height="15" viewBox="0 0 16 15" fill="none" xmlns="http://www.w3.org/2000/svg">
These files are already added in the button customisation PR? Just want to confirm we are using the same assets here

2021-07-30 05:12 UTC, somangshu commented on app/client/src/components/propertyControls/ButtonBorderRadiusControl.tsx
> +import * as React from "react";
These controls were introduced in the FAB/Button customisation, Are we reusing the control components here?

2021-07-30 05:12 UTC, somangshu commented on app/client/src/constants/Colors.tsx
> +  ICON_BUTTON_WARNING_SOLID: "#FEB811",
Can these names be more generic so that it's easier to reuse them? ex: `WARNING_SOLID`

2021-07-30 05:17 UTC, somangshu commented
Deploy preview look good. One thing I have noticed is that in the min width the icon is cut from the side, Can we handle this @wmdev0808?

2021-07-30 05:40 UTC, wmdev0808 commented on app/client/src/assets/icons/control/border-radius-rounded.svg
> +<svg width="16" height="15" viewBox="0 0 16 15" fill="none" xmlns="http://www.w3.org/2000/svg">
yes

2021-07-30 05:42 UTC, wmdev0808 commented on app/client/src/assets/icons/control/border-radius-rounded.svg
> +<svg width="16" height="15" viewBox="0 0 16 15" fill="none" xmlns="http://www.w3.org/2000/svg">
However, includes a few enhancements, including types.
So it will be the latest one

2021-07-30 05:43 UTC, wmdev0808 commented on app/client/src/components/propertyControls/ButtonBorderRadiusControl.tsx
> +import * as React from "react";
yes, but it also includes latest changes

2021-07-30 08:16 UTC, somangshu approved these changes

2021-08-02 08:33 UTC, vivekverma2312 commented
@wmdev0808 
1. Background is not becoming transparent on choosing the transparent option in background property for menu options.
<img width="601" alt="Screenshot 2021-08-02 at 1 47 19 PM" src="https://user-images.githubusercontent.com/83569920/127828243-0fb6ea71-4e8e-4bcf-998a-f82882ef0f60.png">

2. Migration issues: Old Menu widget are not showing properly.
<img width="816" alt="Screenshot 2021-08-02 at 1 48 07 PM" src="https://user-images.githubusercontent.com/83569920/127828407-0df620d2-7ba3-4f93-aec4-a7763f9ac026.png">

2021-08-03 07:37 UTC, marks0351 requested changes

2021-08-03 07:37 UTC, marks0351 commented on app/client/src/components/propertyControls/BoxShadowOptionsControl.tsx
> +        <StyledButton
can you add a constant with a button config and iterate through it to show button types?
wud be more readable and would be easy to add new variants.

2021-08-03 09:34 UTC, marks0351 submitted a review, later dismissed

2021-08-04 14:36 UTC, somangshu commented
@wmdev0808 please merge the latest release here, Failing test has been fixed

2021-08-18 05:38 UTC, somangshu commented
@wmdev0808 please resolve the conflicts here, @vivekverma2312 once that is done please test this at priority

2021-08-20 07:18 UTC, vivekverma2312 commented
@wmdev0808 Menu button for older app is not proper.
1. Menu style and Menu variants is not selected by default
<img width="342" alt="Screenshot 2021-08-20 at 12 40 54 PM" src="https://user-images.githubusercontent.com/83569920/130195358-4ef34e19-febc-44dc-a151-7ed4a70c9edd.png">

2. Default button is not looking proper
<img width="601" alt="Screenshot 2021-08-20 at 12 40 35 PM" src="https://user-images.githubusercontent.com/83569920/130195305-510e3a6a-2b97-4833-a19b-99450ce435ea.png">
<img width="1514" alt="Screenshot 2021-08-20 at 12 39 45 PM" src="https://user-images.githubusercontent.com/83569920/130195320-f1532b4c-cab8-426f-a027-cd1da994d81e.png">

2021-08-20 08:52 UTC, somangshu submitted a review, later dismissed
LGTM

2021-08-23 08:28 UTC, vivekverma2312 commented
@wmdev0808 Migration issue is fixed. 
Issue Observed:
Menu button do not have any different behaviour on changing menu style to Custom. User is not getting option to change the background colour.
<img width="502" alt="Screenshot 2021-08-23 at 1 54 37 PM" src="https://user-images.githubusercontent.com/83569920/130415738-0bfb5e96-6ddc-4c10-a13b-893963aceba2.png">

2021-08-23 14:27 UTC, somangshu approved these changes
LGTM, Deploy preview works well

2021-08-24 05:32 UTC, vivekverma2312 commented
Tested deploy preview and working fine now.

2021-08-24 05:37 UTC, merged