FIX #3123 : added csvSeparator property in table widget for csv download
appsmithorg/appsmith pull request #6291
Opened 2021-07-30 11:37 UTC by vibhandikyash

## Description

> Added Download Config for downloading CSV data of the table. Added option for separator configuration.

Fixes #3123 

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

> Tested locally.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-07-30 11:38 UTC, vibhandikyash commented
/ok-to-test sha=b6acca3

2021-08-03 04:38 UTC, SatishGandham requested changes

2021-08-03 04:38 UTC, SatishGandham commented on app/client/src/entities/Widget/utils.test.ts
> +            allowedValues: [",", ";"],
Why are we restricting on the values they can use?
If we are for some reason, pipe (|) is also commonly used.

2021-08-03 04:38 UTC, SatishGandham commented on app/client/src/components/designSystems/appsmith/TableComponent/Table.tsx
> +  csvSeparator: string;
csv is comma separated values. Can we have a more accurate name?
CC: @somangshu

2021-08-04 14:23 UTC, somangshu commented on app/client/src/entities/Widget/utils.test.ts
> +            allowedValues: [",", ";"],
@vibhandikyash please explain this

2021-08-04 14:24 UTC, somangshu commented on app/client/src/components/designSystems/appsmith/TableComponent/Table.tsx
> +  csvSeparator: string;
Maybe `csvDelimiter`?

2021-08-05 12:06 UTC, vibhandikyash commented on app/client/src/components/designSystems/appsmith/TableComponent/Table.tsx
> +  csvSeparator: string;
+1 for @somangshu Maybe we can go with this one. @SatishGandham kindly confirm.

2021-08-05 12:07 UTC, vibhandikyash commented on app/client/src/entities/Widget/utils.test.ts
> +            allowedValues: [",", ";"],
@SatishGandham Usually for CSV internal formats are only two of them comma (,) and semicolon(;). If you want we can remove the validation.

2021-08-05 12:51 UTC, somangshu commented on app/client/src/entities/Widget/utils.test.ts
> +            allowedValues: [",", ";"],
Rather, can we include the Pipe ( | ) as well? @vibhandikyash

2021-08-06 11:56 UTC, SatishGandham commented on app/client/src/components/designSystems/appsmith/TableComponent/Table.tsx
> +  csvSeparator: string;
How about just delimiter, if that doesn't work we can go with csvDelimiter

2021-08-06 11:58 UTC, SatishGandham commented on app/client/src/entities/Widget/utils.test.ts
> +            allowedValues: [",", ";"],
I think we should remove the limitation. Sometime they may use || or completely different delimiter when , ; or | is part of the data.

2021-08-09 06:29 UTC, vibhandikyash commented on app/client/src/components/designSystems/appsmith/TableComponent/Table.tsx
> +  csvSeparator: string;
@somangshu Thoughts?

2021-08-09 06:30 UTC, vibhandikyash commented on app/client/src/entities/Widget/utils.test.ts
> +            allowedValues: [",", ";"],
okay @SatishGandham, Noted. Will remove the validation completely.
cc: @somangshu

2021-08-09 07:09 UTC, somangshu commented on app/client/src/components/designSystems/appsmith/TableComponent/Table.tsx
> +  csvSeparator: string;
@vibhandikyash going with ☝️

2021-08-10 11:31 UTC, somangshu submitted a review, later dismissed
LGTM

2021-08-10 12:35 UTC, somangshu commented
From the deploy preview:
- The helper text for the new field needs to change to > The character used for separating the CSV download file. 
- For older widgets the evaluated value does not show up, Neither does the download format right. **(Migrations issues)**
- Merge the CSV separator field to the header option section and get rid of the download config section

@vibhandikyash please resolve the above

2021-08-10 14:06 UTC, somangshu commented
Updated the above comment @vibhandikyash

2021-08-10 14:07 UTC, somangshu commented on app/client/src/utils/migrations/TableWidget.ts
> +        child.delimeter = ",";
Do we also need to upgrade the version?

2021-08-13 07:24 UTC, somangshu commented
@vibhandikyash the jest tests have failed here because the table widget property do not match, Please fix this.

2021-08-13 07:28 UTC, somangshu commented
On the deploy preview I still see the migration issue, The default value for the property is not evaluated
![Screenshot 2021-08-13 at 12 57 52 PM](https://user-images.githubusercontent.com/11089579/129320582-0534312c-6ab7-465b-a960-a61512883f95.png)

2021-08-13 10:10 UTC, vibhandikyash commented
/ok-to-test sha= e01ad83

2021-08-16 10:41 UTC, somangshu approved these changes
Approving for re-running the tests

2021-08-16 10:43 UTC, somangshu commented
@vibhandikyash the migration issue on DP still exists, Check [this](https://deploy-preview-6291--appsmith-editor-ce.netlify.app/applications/60aba4455123fa30d6c393f7/pages/60aba4455123fa30d6c393f9/edit) app

2021-08-16 12:18 UTC, somangshu approved these changes

2021-08-16 14:05 UTC, somangshu commented
> @vibhandikyash the migration issue on DP still exists, Check [this](https://deploy-preview-6291--appsmith-editor-ce.netlify.app/applications/60aba4455123fa30d6c393f7/pages/60aba4455123fa30d6c393f9/edit) app

This works fine, Migration works correctly

2021-08-17 07:21 UTC, SatishGandham requested changes

2021-08-17 07:21 UTC, SatishGandham commented on app/client/src/entities/Widget/utils.test.ts
> +        delimeter: EvaluationSubstitutionType.TEMPLATE,
Its delimiter, not delimeter

2021-08-18 07:27 UTC, SatishGandham approved these changes

2021-08-18 09:09 UTC, somangshu approved these changes

2021-08-18 10:33 UTC, merged