FIX #6193 : bind enter and tab key on color picker input to close color board
appsmithorg/appsmith pull request #6305
Opened 2021-07-31 14:38 UTC by vibhandikyash

## Description

> Binding Enter and Tab Key on color picker and close color popup.

Fixes #6193 

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

> Tested locally.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-08-02 15:00 UTC, somangshu commented
@ramsaptami can you test this deploy preview and give us a signoff

2021-08-03 04:33 UTC, SatishGandham requested changes

2021-08-03 04:33 UTC, SatishGandham commented on app/client/src/components/ads/ColorPickerComponent.tsx
> +          if ((e.key === "Enter" || e.key === "Tab") && isPopoverOpen) {
isPopoverOpen check in the if is not required. Since it is a primitive value change from false -> false doesn't trigger a render as well.

2021-08-03 05:56 UTC, ramsaptami commented
Tested and ok on deploy preview

2021-08-03 08:44 UTC, vibhandikyash commented
/ok-to-test sha=bcd1188

2021-08-03 08:57 UTC, SatishGandham submitted a review, later dismissed

2021-08-03 12:45 UTC, vibhandikyash commented
/ok-to-test sha=bcd1188

2021-08-04 10:41 UTC, somangshu commented
@vibhandikyash please merge latest release here, Failing test fix is available here.

Also do request for a review as /ok-to-test is not fully functional right now

2021-08-05 12:04 UTC, somangshu approved these changes

2021-08-05 13:32 UTC, somangshu commented
There is an issue in the DP
- Focus on the colour picker field
- type a colour ex: red
- Press tab

It is observed that the colour picker of the previous input/field opens, and then if we press shift + tab another colour picker opens.


https://user-images.githubusercontent.com/11089579/128358463-5437baf8-4b0d-4363-b030-351363f4634e.mov

2021-08-10 13:20 UTC, somangshu approved these changes
LGTM, Deploy preview also works well now

2021-08-11 05:19 UTC, SatishGandham requested changes

2021-08-11 05:19 UTC, SatishGandham commented on app/client/src/components/ads/ColorPickerComponent.tsx
> +          // if user clicks on ColorBoard blur is called first and color is not updated
I don't see why this is required. Looks like a hacky solution to whatever problem we are solving.

2021-08-11 05:19 UTC, SatishGandham commented on app/client/src/components/ads/ColorPickerComponent.tsx
> +          if (e.key === "Enter") {
@somangshu  Should we also include tab here?
If I focus a color picker input and use tab to navigate to next input, the picker is not closed.

2021-08-11 06:18 UTC, vibhandikyash commented on app/client/src/components/ads/ColorPickerComponent.tsx
> +          // if user clicks on ColorBoard blur is called first and color is not updated
@SatishGandham This is because when we click on the popover to pick a color the blur function is called first and then the click event which prevents it from setting the color. That's why I had to put this setTimeout which allows the click event to set it first and then close.

2021-08-12 04:47 UTC, vibhandikyash commented
@SatishGandham As discussed yesterday on the call. Can you pl. update here?

2021-08-16 14:15 UTC, somangshu commented on app/client/src/components/ads/ColorPickerComponent.tsx
> +          if (e.key === "Enter") {
@SatishGandham that sounds right. As far as the deploy preview is concerned the color picker closes where the next input is focused using tab, Do you see some other behaviour? I am not sure if i am getting this correctly

2021-08-18 11:04 UTC, vibhandikyash commented on app/client/src/components/ads/ColorPickerComponent.tsx
> +          if (e.key === "Enter") {
@somangshu I had a word with @SatishGandham about the same. The Keyup will not detect tab because its not happening no its focus. That's why we have to use the onBlur event.

2021-08-19 03:50 UTC, SatishGandham approved these changes

2021-08-20 09:27 UTC, somangshu commented
@SatishGandham what is pending here? I have missed the trail

2021-08-23 11:06 UTC, somangshu approved these changes

2021-08-24 11:22 UTC, vivekverma2312 commented
@vibhandikyash Tested the DP and working fine

2021-08-24 11:25 UTC, merged