Use feature flag api comments
appsmithorg/appsmith pull request #6322
Opened 2021-08-02 07:58 UTC by rishabhsaxena

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.

## Description

> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change.

Fixes # (issue)

> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-08-02 09:40 UTC, rishabhsaxena commented
/ok-to-test sha=fe72a70

2021-08-03 05:43 UTC, hetunandu requested changes

2021-08-03 05:43 UTC, hetunandu commented on app/client/src/actions/userActions.ts
> +});
We don't need to add these values to the redux state. Just keep it in memory so that any piece of code can access this without going through redux

2021-08-03 05:43 UTC, hetunandu commented on app/client/src/reducers/uiReducers/usersReducer.ts
> +  featureFlags: {},
Client should always have an enum of feature flags possible. Make sure this is typed properly

2021-08-03 08:52 UTC, rishabhsaxena commented on app/client/src/actions/userActions.ts
> +});
I guess it makes sense to keep it as a global or localStorage, that way we could override it easily as well, like we can for logs. But keeping it in the store also has the benefit of it being reactive. Should we do both (assign it to the window object as well as the store)?

2021-08-03 08:55 UTC, hetunandu commented on app/client/src/actions/userActions.ts
> +});
This would never change in a session, hence we would not need reactivity. Fetching from localStorage still has a perf hit every time we check for this. There is also a problem of cache busting. I think a simple in memory object is all we need

2021-08-03 08:58 UTC, rishabhsaxena commented on app/client/src/actions/userActions.ts
> +});
Got it. The reactivity bit is currently needed just for the initial load, so for example by the time we fetch the feature flags the component might already be mounted

2021-08-03 09:55 UTC, hetunandu commented on app/client/src/actions/userActions.ts
> +});
Can we ensure this api and resolved and set before that component renders?

2021-08-03 10:05 UTC, rishabhsaxena commented on app/client/src/actions/userActions.ts
> +});
One alternative way I can think of is keeping a flag in the reducer to check if feature flags are populated, so the info won't be duplicated still.
So the selector could look like:

```
export const areCommentsEnabledForUserAndApp = (state: AppState) =>
  state.ui.users.featureFlagsInitiated && window.FEATURE_FLAGS?.COMMENT;
```

2021-08-03 10:07 UTC, hetunandu commented on app/client/src/actions/userActions.ts
> +});
This would then need to be done for any component that would render on load

2021-08-03 10:50 UTC, rishabhsaxena commented on app/client/src/actions/userActions.ts
> +});
Got it, have pushed a commit to wait for rendering until we fetch the feature flags

2021-08-03 10:54 UTC, rishabhsaxena commented
/ok-to-test sha=e856c12

2021-08-03 12:19 UTC, rishabhsaxena commented
/ok-to-test sha=e856c12

2021-08-03 13:08 UTC, hetunandu approved these changes

2021-08-03 15:07 UTC, rishabhsaxena commented
/ok-to-test sha=ee89688

2021-08-04 05:19 UTC, rishabhsaxena commented
/ok-to-test sha=c242960

2021-08-05 06:10 UTC, hetunandu approved these changes

2021-08-05 06:10 UTC, merged