changed default divider color
appsmithorg/appsmith pull request #6335
Opened 2021-08-02 13:35 UTC by techbhavin

## Description

> Default color for divider widget is bad, should be a softer grey

Fixes #6272 

## Type of change
- Bugfix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ]  I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ]  I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-08-02 13:38 UTC, somangshu commented on app/client/src/mockResponses/WidgetConfigResponse.tsx
> +      dividerColor: "#C4C4C4",
Can we reference this from the theme?

2021-08-02 13:38 UTC, somangshu requested changes
Changes as mentioned

2021-08-03 11:02 UTC, techbhavin commented on app/client/src/mockResponses/WidgetConfigResponse.tsx
> +      dividerColor: "#C4C4C4",
@somangshu  here this color is not present in the theme.

2021-08-04 13:30 UTC, somangshu commented on app/client/src/mockResponses/WidgetConfigResponse.tsx
> +      dividerColor: "#C4C4C4",
Please add it in the theme grey scale then

2021-08-05 07:17 UTC, techbhavin commented
/ok-to-test sha= 983ca9a

2021-08-05 10:03 UTC, somangshu commented on app/client/src/constants/Colors.tsx
> +  GREY_SCALE: "#C4C4C4",
Please use LIGHT_GREY2 for the variable name

2021-08-05 10:04 UTC, somangshu submitted a review, later dismissed
Approving for tests to run

2021-08-09 07:01 UTC, somangshu approved these changes
LGTM

2021-08-09 12:22 UTC, merged