added cell background of empty rows
appsmithorg/appsmith pull request #6353
Opened 2021-08-03 09:57 UTC by haojin111

## Description

> When apply cell background of table property, it should be applied to empty row's cells.

Fixes #2868 

> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Please refer attached issue

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-08-03 10:25 UTC, SatishGandham requested changes

2021-08-03 10:25 UTC, SatishGandham commented on app/client/src/components/designSystems/appsmith/TableComponent/TableUtilities.tsx
> +              };
change this to `cellProps.style.background:background`, creating a new style object will cause extra renders.

2021-08-04 05:57 UTC, SatishGandham requested changes

2021-08-04 05:57 UTC, SatishGandham commented on app/client/src/components/designSystems/appsmith/TableComponent/TableUtilities.tsx
> +            return <div {...cellProps} className="td" key={cellIndex} />;
Can you write it like this. saves extra call to getCellProps.
`if(columns[0]?.columnProperties?.cellBackground){
const cellProps = cell.getCellProps();
            cellProps.style.background =
              columns[0]?.columnProperties?.cellBackground
}`

2021-08-04 06:38 UTC, haojin111 commented on app/client/src/components/designSystems/appsmith/TableComponent/TableUtilities.tsx
> +            return <div {...cellProps} className="td" key={cellIndex} />;
`const cellProps = cell.getCellProps();
 if (columns[0]?.columnProperties?.cellBackground) {
    cellProps.style.background =
      columns[0].columnProperties.cellBackground;
 }
 return <div {...cellProps} className="td" key={cellIndex} />;`
How about this?

2021-08-04 06:39 UTC, SatishGandham commented on app/client/src/components/designSystems/appsmith/TableComponent/TableUtilities.tsx
> +            return <div {...cellProps} className="td" key={cellIndex} />;
Works. I didn't notice cellprops was used below.

2021-08-04 06:58 UTC, SatishGandham approved these changes

2021-08-30 06:51 UTC, riodeuno approved these changes

2021-08-30 06:56 UTC, riodeuno commented
@somangshu This was reprioritised to a lower priority deferring to other issues, which were more critical at the time.
@haojin111 Thanks a lot for picking this up! The code looks fine to me.  Tested this update on the deploy preview as well.

2021-08-30 07:48 UTC, merged