Minor fixes for comments on the modal widget
appsmithorg/appsmith pull request #6368
Opened 2021-08-03 16:18 UTC by rishabhsaxena

## Description
Fixes: #6367

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manually

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: comment-fixes-modal-widget 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 53.39 **(0)** | 34.99 **(0)** | 31.53 **(0.02)** | 53.94 **(0)**
 :green_circle: | app/client/src/comments/inlineComments/OverlayCommentsWrapper.tsx | 96.77 **(0.1)** | 83.33 **(0)** | 100 **(0)** | 100 **(0)**
 :sparkles: :new: | **app/client/src/entities/App.ts** | **100** | **100** | **100** | **100**
 :red_circle: | app/client/src/reducers/entityReducers/appReducer.ts | 70 **(-6.92)** | 100 **(0)** | 40 **(-10)** | 70 **(-6.92)**
 :green_circle: | app/client/src/selectors/entitiesSelector.ts | 51.62 **(0.47)** | 6.33 **(1.14)** | 28.3 **(1.83)** | 49.27 **(0.57)**</details>

2021-08-04 04:34 UTC, hetunandu requested changes

2021-08-04 04:34 UTC, hetunandu commented on app/client/src/comments/CommentCard/CommentCard.tsx
> +  const canvasWidgetMap: Record<string, any> = useSelector(
Is it possible to use canvasWidgetMap all the time? Using both will lead to unnecessary renders

2021-08-04 04:34 UTC, hetunandu commented on app/client/src/selectors/entitiesSelector.ts
> +  while (parentId && parentId !== MAIN_CONTAINER_WIDGET_ID) {
Avoid while loop here. Probably forEach each pageWidget? Better is to just use Array.find

2021-08-04 04:56 UTC, rishabhsaxena commented on app/client/src/comments/CommentCard/CommentCard.tsx
> +  const canvasWidgetMap: Record<string, any> = useSelector(
Actually, the issue is in the view mode we don't fetch widgets for all the pages. `canvasWidgetMap` just contains widgets for the current page.

2021-08-04 05:00 UTC, hetunandu commented on app/client/src/comments/CommentCard/CommentCard.tsx
> +  const canvasWidgetMap: Record<string, any> = useSelector(
Then we can probably just use the same selector and return different sets of widgets depending on the APP_MODE

2021-08-04 05:32 UTC, rishabhsaxena commented on app/client/src/selectors/entitiesSelector.ts
> +  while (parentId && parentId !== MAIN_CONTAINER_WIDGET_ID) {
Here actually, the parent modal might not be the immediate parent, so we walk up the parents using the parent id. I guess this might be safe since we won't have a circular parent-child connection?

2021-08-05 15:05 UTC, rishabhsaxena commented
/ok-to-test sha=d9b5af6

2021-08-06 05:16 UTC, hetunandu approved these changes

2021-08-06 07:23 UTC, rishabhsaxena commented
/ok-to-test sha=8342409

2021-08-06 08:47 UTC, pranavkanade approved these changes
approving for tests

2021-08-06 09:17 UTC, merged