Add errorType to Categorise Debugger Errors
appsmithorg/appsmith pull request #6413
Opened 2021-08-05 12:37 UTC by AnaghHegde

## Description

> Plugin execution Errors: These errors occur during action execution and can be due to the following reasons
Incorrect Datasource Configuration: This error is due to incorrect data source configuration and should trigger an intercom message with the error
User action config Errors: This error is due to an incorrect configuration in the query and should search the omnibar for the solution

Fixes #6320 

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Local via postman
- Test B

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

2021-08-05 12:52 UTC, AnaghHegde commented
@akash-codemonk Let me know if this looks good. I will request for review after your confirmation.

2021-08-06 06:48 UTC, sharat87 reviewed
If I understand this correctly, we are passing on the error's enum name as is to the client right? So the client will look at the error name (called `errorType` for the client), and decide whether this error should open the Omnibar or a support conversation, correct?

If this is correct, can we do that logic in the backend instead? Let's only pass information to the client that'll help determine what to do with the error. Something like `errorType: "NEED_SUPPORT"` and `errorType: "SHOW_DOCS"` or similar.

The reason I'm inclined towards that is, one, it will avoid having the error names hard-coded in the client code. Otherwise, refactoring error names in the future will become fragile. Two, client has less intelligence to deal with, which is always desirable.

What say? Sorry if I'm misunderstanding the problem being solved here.

2021-08-12 11:52 UTC, sharat87 requested changes
Looks good. Just a couple of things before we can put this in.

2021-08-12 11:52 UTC, sharat87 commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/ActionExecutionResult.java
> +            this.errorType = ((AppsmithPluginException) error).getErrorType();
Did you mean to use `BaseException` here?

```suggestion
            this.errorType = ((BaseException) error).getErrorType();
```

2021-08-12 11:52 UTC, sharat87 commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/exceptions/pluginExceptions/AppsmithPluginException.java
> +    public String getErrorType() { return this.error.name(); }
The conversion of an `ErrorType` enum value to a `String` is being done by calling `.name()` here, and by calling `.toString()` in `AppsmithPluginError` enum. Is this difference intentional? If not, can we use the same method to stay consistent?

2021-08-12 13:36 UTC, AnaghHegde commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/ActionExecutionResult.java
> +            this.errorType = ((AppsmithPluginException) error).getErrorType();
@sharat87 `BaseException` class doesnt have the getErrorType(). Maybe its good to leave the errorType to empty when the exception is not of `Appsmith` type.

2021-08-12 14:59 UTC, sharat87 commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/ActionExecutionResult.java
> +            this.errorType = ((AppsmithPluginException) error).getErrorType();
That may be but if the code flow has arrived at this point, that means `error instanceof AppsmithPluginException` was `false`, which means this typecast would definitely throw a `ClassCastException`. That was why I was concerned with this line. 😄

2021-08-12 14:59 UTC, sharat87 submitted a review, later dismissed

2021-08-17 12:46 UTC, sharat87 approved these changes

2021-08-17 12:46 UTC, sharat87 commented
Looks good to be merged. Please squash merge once the CI is finished. Thanks!

2021-08-18 04:59 UTC, AnaghHegde commented
@sharat87 Please approve again. Just fixed the merge conflicts :)

2021-08-18 05:00 UTC, sharat87 approved these changes

2021-08-18 05:13 UTC, mohanarpit commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/ErrorType.java
> +    ARGUMENT_ERROR, CONFIGURATION_ERROR, CONNECTIVITY_ERROR, AUTHENTICATION_ERROR, API_ERROR, BAD_REQUEST, INTERNAL_ERROR
Super minor formatting nit: Please define enum values in new lines. Makes it readable & parseable to the naked eye.

2021-08-18 05:13 UTC, mohanarpit commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/ActionExecutionResult.java
> +        else if (error instanceof BaseException) {
Super minor nit: Always have the else clause at the end of the if-block. This ensures that as a reader, I notice the else immediately. If the else block is removed from the if block, it makes code slightly harder to read.
```suggestion
        } else if (error instanceof BaseException) {
```

2021-08-19 10:31 UTC, AnaghHegde commented
@mohanarpit ready for review

2021-08-19 10:35 UTC, mohanarpit approved these changes

2021-08-19 14:29 UTC, merged