FIX #6127 - Entity explorer - cloned page widget highlight
appsmithorg/appsmith pull request #6441
Opened 2021-08-06 15:51 UTC by ashit-rath

Fixes #6127 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Tested locally.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-08-09 06:42 UTC, marks0351 approved these changes

2021-08-11 11:54 UTC, YogeshJayaseelan commented
@marks0351 Tested this fix - on selecting a single widget and on cloning the page the clone functionality is working as expected. But if the user selected multiple widget and when the page is cloned the Copy, Cut and Delete button goes out of the canvas 

https://www.loom.com/share/aba9249e475b4f53b109b5a6042136e8

2021-08-11 12:00 UTC, marks0351 commented
@YogeshJayaseelan I think it is a bug in prod too and is not linked to this bug but let's fix it with this PR.
@ashit-rath can u clear selected widgets when we are done cloning a page?

2021-08-17 12:03 UTC, marks0351 requested changes
changes look good @ashit-rath can u pls clean up the conflicts.

2021-08-17 12:38 UTC, marks0351 approved these changes

2021-08-17 13:23 UTC, merged