FIX #2587 : added container wrapper component to handle styles
appsmithorg/appsmith pull request #6476
Opened 2021-08-09 09:31 UTC by vibhandikyash

## Description

> Added container wrapper for styling

Fixes #2587 

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

> Tested locally.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-08-11 04:57 UTC, marks0351 requested changes
Great job on adding the style features!!
Pls add a docs update PR for these changes.
when border is more than a certain value the widget overflows widget boundaries. it should not be the case.

2021-08-20 07:05 UTC, vibhandikyash commented
@marks0351 Here also updated Border styles for Text Widget for issue #4419

2021-08-23 05:42 UTC, marks0351 commented
@vibhandikyash when a container radius is set very large the container goes away which is fine and is expected but the area below container becomes unaccessible because of the div overflow. 
Also when border radius is set to a large number it does not work as expected with text widget. text widget starts to overflow.

2021-08-23 05:43 UTC, marks0351 requested changes
@vibhandikyash when a container radius is set very large the container goes away which is fine and is expected but the area below container becomes unaccessible because of the div overflow. 
Also when border radius is set to a large number it does not work as expected with text widget. text widget starts to overflow.

2021-08-27 13:00 UTC, somangshu submitted a review, later dismissed
Approving to run tests

2021-08-30 12:03 UTC, somangshu commented
@vibhandikyash related test has failed, Please check

2021-09-01 04:52 UTC, marks0351 approved these changes

2021-09-01 06:36 UTC, somangshu commented
Rerunning all jobs here, `Draggable_PropertyPane_Widgets_spec.js` failed because the property pane moved while widget is dragged down. Not related to the PR

2021-09-01 07:49 UTC, somangshu commented
Failed again, @vibhandikyash please check this locally and let me know

2021-09-03 05:48 UTC, somangshu submitted a review, later dismissed
LGTM, @rishabhsaxena thanks for the help here. 

Approving to run the tests

2021-09-03 07:13 UTC, somangshu commented
@marks0351 @vibhandikyash here is my feedback

### Container widget:
1. The old property `background-colour` should be above the new styles
2. All the properties should be under the style section
3. Same for for the form widget
4. The border is always cut from the side where there is a border radius ![Screenshot 2021-09-03 at 12 36 37 PM](https://user-images.githubusercontent.com/11089579/131965326-1ebb3ea7-8c72-445e-b0cb-c05870decce0.png)
5. For older container / creating apps from DB the new properties are undefined which other wise is 0 when initially dragged and dropped


### Text widget:
1. OP requested for the margin property, which is not implemented (is this intended)
2. Other properties were not requested in the text widget, today placing the text widget in the container widget get you the attributes you need. So in my view, these new properties are not required in the text widget

2021-09-03 10:11 UTC, YogeshJayaseelan commented
@vibhandikyash Currently all the border style related properties comes under general section and it is be separated and placed under style property 

<img width="1680" alt="Screenshot 2021-09-03 at 3 38 57 PM" src="https://user-images.githubusercontent.com/35128442/131989076-b28e9996-0f87-470d-a03c-4b84cb74a597.png">

2021-09-08 05:10 UTC, marks0351 commented
@vibhandikyash the text widget and container still overflows when border width given is high.

2021-09-08 05:11 UTC, marks0351 requested changes
@vibhandikyash  the text widget and container still overflows when border width given is high.

2021-09-09 05:11 UTC, marks0351 commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/PropertyPane/Draggable_PropertyPane_Widgets_spec.js
> -        .trigger("mousemove", { clientX: 400, clientY: 500 })
@NandanAnantharamu can you pls review/validate this change?

2021-09-09 05:11 UTC, marks0351 submitted a review, later dismissed

2021-09-09 12:55 UTC, NandanAnantharamu submitted a review, later dismissed
LGTM

2021-09-14 06:04 UTC, marks0351 approved these changes

2021-09-15 04:48 UTC, YogeshJayaseelan commented
@vibhandikyash Verified the container style functionality and looks good to me

2021-09-15 06:46 UTC, vivekverma2312 commented
@vibhandikyash Working fine for text widget too.

2021-09-16 04:21 UTC, merged