Change the name of the mock datasource
appsmithorg/appsmith pull request #6498
Opened 2021-08-10 06:07 UTC by AnaghHegde

## Description

> Change the mock database name. 

Fixes

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Unit Tests
- Manually

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

2021-08-11 06:12 UTC, mohanarpit commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/MockDataServiceImpl.java
> +                return Mono.error(new AppsmithException(AppsmithError.INVALID_DATASOURCE, mockDataSource.getName(), mockDataDTO.getName()));
Why will we encounter this exception? Which object in this list will throw the exception? Can we not validate the object before accessing the content? 

Using try-catch to control business logic flow is an anti-pattern. We should be validating objects before using them instead of relying on exceptions.

2021-08-12 05:03 UTC, mohanarpit commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/MockDataServiceImpl.java
> +            return datasourceConfiguration;
Instead of collecting into a list, I would suggest using `findFirst()`. An example is given below

```suggestion
        Optional<MockDataCredentials> credentials = mockDataSet.getCredentials().stream().filter(cred -> cred.getDbname().equalsIgnoreCase(name)).findFirst();
        // Check if credentials is available & not null
```

2021-08-12 05:04 UTC, mohanarpit commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/MockDataServiceImpl.java
> +            if( datasourceConfiguration.getAuthentication() == null) {
Sorry, I didn't understand this condition. Why are we checking the authentication object to return an error saying that we couldn't find any mock datasource?

2021-08-12 08:06 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/MockDataServiceImpl.java
> +            if( datasourceConfiguration.getAuthentication() == null) {
Suppose if someone had modified the config object in Cloud service - either they deleted the entry or changed the name to something else, in such scenarios the credentials wont match right ? Thats why i am returning this error.

2021-08-18 05:01 UTC, AnaghHegde commented
@mohanarpit Ready for review

2021-08-18 07:04 UTC, mohanarpit approved these changes

2021-08-18 18:09 UTC, mohanarpit approved these changes

2021-08-19 06:41 UTC, pranavkanade approved these changes
cypress locator change looks good.

2021-08-19 09:14 UTC, nayan-rafiq submitted a review, later dismissed

2021-08-19 10:36 UTC, ohansFavour approved these changes

2021-08-19 11:08 UTC, ohansFavour requested changes

2021-08-19 11:08 UTC, ohansFavour commented on app/client/cypress/locators/DatasourcesEditor.json
> +  "mockUserDatasources":".t--datasource-name:contains('users')"
Kindly change "users" to "Users"

2021-08-19 11:13 UTC, ohansFavour approved these changes

2021-08-19 12:23 UTC, merged