Feature/option to upload file or text in multipart form
appsmithorg/appsmith pull request #6534
Opened 2021-08-11 11:03 UTC by ohansFavour

## Description
Added option to upload file or text in multipart form

<img width="1184" alt="Screenshot 2021-08-11 at 11 59 50" src="https://user-images.githubusercontent.com/46670083/129017983-a91d0688-68c2-4e75-8b8f-e68f3ac16595.png">

Fixes # (5547)

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
Cypress tests were written

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-08-13 08:04 UTC, hetunandu requested changes
Minor refactor

2021-08-13 08:04 UTC, hetunandu commented on app/client/src/components/editorComponents/form/fields/KeyValueFieldArray.tsx
> +
Move to APIEditorConstants

2021-08-13 08:30 UTC, ohansFavour commented on app/client/src/components/editorComponents/form/fields/KeyValueFieldArray.tsx
> +
All right. Fixed in new commit

2021-08-16 09:54 UTC, hetunandu approved these changes

2021-08-16 12:00 UTC, merged

2021-09-02 20:59 UTC, 96imranahmed commented
Hey, do we know which release this has been packaged into? We just installed via the docker script, but this feature doesn't seem to be available.