fix: update color picker property control interaction
appsmithorg/appsmith pull request #6536
Opened 2021-08-11 12:12 UTC by vibhandikyash

## Description

> The Color picker popover was covering up the textbox. Fixed by changing the popover target on click of the color palette.

Fixes #6978  
~~Fixes #4413~~

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Tested locally.
- Added Test cases.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: FIX/4413-color-picker-interaction-update 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 54.94 **(0.02)** | 36.83 **(0)** | 33.66 **(0.02)** | 55.48 **(0.01)**
 :green_circle: | app/client/src/components/ads/ColorPickerComponent.tsx | 37.84 **(9.27)** | 63.64 **(5.31)** | 0 **(0)** | 40 **(8.18)**</details>

2021-08-23 05:33 UTC, riodeuno requested changes
Code looks fine to me. Please resolve the merge conflicts.

2021-08-23 11:07 UTC, somangshu submitted a review, later dismissed
Approving to run tests after conflicts are resolved

2021-08-23 12:52 UTC, somangshu commented
The Deploy preview LGTM, The only change I see is that while the inputs are navigated based on the tab key, the colour poper does not come up, We have just fixed this somewhere else

2021-08-23 12:52 UTC, somangshu commented
@vibhandikyash please confirm if this failing test case is related

2021-08-23 13:22 UTC, vibhandikyash commented
@somangshu No, this is unrelated to my changes.

2021-08-31 05:49 UTC, somangshu commented
@vibhandikyash please clear this conflict and merge the latest release here

2021-08-31 09:32 UTC, somangshu commented on app/client/src/components/ads/ColorPickerComponent.tsx
> -  const [isOpen, setOpen] = React.useState(false);
@vibhandikyash What about the rest of the changes added with this commit?

2021-08-31 09:34 UTC, somangshu approved these changes
Approving to run tests

2021-08-31 11:05 UTC, vibhandikyash commented on app/client/src/components/ads/ColorPickerComponent.tsx
> -  const [isOpen, setOpen] = React.useState(false);
@somangshu  Removed this as there was some code related to picker open and close on tab.

2021-08-31 11:07 UTC, somangshu commented
@vibhandikyash we only want to fix #6978 now not go ahead with this behaviour

2021-09-01 05:18 UTC, riodeuno approved these changes
Approving for tests

2021-09-01 06:31 UTC, somangshu commented
@vibhandikyash we only need to fix #6978 and revert the current changes in this PR

2021-09-03 05:53 UTC, closed without merging