Feature/table widget label type columns
appsmithorg/appsmith pull request #6590
Opened 2021-08-13 09:47 UTC by vicky-primathon

## Description
Label styles for column in table widget

Fixes #4333

## Type of change
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-09-01 05:18 UTC, SatishGandham requested changes

2021-09-01 05:18 UTC, SatishGandham commented on app/client/src/components/designSystems/appsmith/TableComponent/Constants.ts
> +  tagSize?: string;
Shouldn't these be combined into an object?

2021-09-01 05:18 UTC, SatishGandham commented on app/client/src/components/propertyControls/LabelColorPickerControl.tsx
> +  "#F0F0F0",
I think you forgot transparent here?

2021-09-01 12:20 UTC, vicky-primathon commented on app/client/src/components/propertyControls/LabelColorPickerControl.tsx
> +  "#F0F0F0",
@SatishGandham  Labels cannot be transparent

2021-09-02 06:32 UTC, vicky-primathon commented on app/client/src/components/designSystems/appsmith/TableComponent/Constants.ts
> +  tagSize?: string;
@SatishGandham these are column level properties and not table level properties. Column properties are created based on these props. So if i combined these into an object, accessing these properties while rendering property pane will not be possible.

2021-09-02 08:45 UTC, SatishGandham approved these changes

2021-09-02 12:17 UTC, vivekverma2312 commented
@vicky-primathon Observations so far:
1. Column type name is Label. As per the design it should be Tag
2. Other properties are not coming in property pane - I am not able to test other flows due to this.
3. After selecting Label for an column, the column data is coming as +3
<img width="456" alt="Screenshot 2021-09-02 at 5 18 09 PM" src="https://user-images.githubusercontent.com/83569920/131841811-6224614f-ebdd-4748-ab00-8f157d602490.png">

2021-09-06 16:39 UTC, vicky-primathon commented
> @vicky-primathon Observations so far:
> 
> 1. Column type name is Label. As per the design it should be Tag
> 2. Other properties are not coming in property pane - I am not able to test other flows due to this.
> 3. After selecting Label for an column, the column data is coming as +3
> 
> <img alt="Screenshot 2021-09-02 at 5 18 09 PM" width="456" src="https://user-images.githubusercontent.com/83569920/131841811-6224614f-ebdd-4748-ab00-8f157d602490.png">

1. Issue is fixed
3. If the column size is smaller than we show the tag with tooltip. To see the tags, increase the size of column.

2021-09-09 12:25 UTC, vicky-primathon commented on app/client/src/components/propertyControls/LabelColorPickerControl.tsx
> +    const { tableData } = this.props.widgetProperties;
@somangshu  this property is not accessible anymore

2021-09-09 12:29 UTC, somangshu commented on app/client/src/components/propertyControls/LabelColorPickerControl.tsx
> +    const { tableData } = this.props.widgetProperties;
@riodeuno will need your help here with the feature design

2021-09-27 08:36 UTC, somangshu commented
@vicky-primathon lets plan a meeting around this with the stakeholders so that we have what we need, Kindly let me know what help you might need here

2021-11-12 10:30 UTC, closed without merging

2021-11-12 10:31 UTC, somangshu commented
Closed this for now