Feat/icon button as column type
appsmithorg/appsmith pull request #6598
Opened 2021-08-13 11:38 UTC by Tooluloope

## Description

> Add IconButton as column type

Fixes #5635 

## Type of change

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-08-17 12:13 UTC, marks0351 requested changes
Pls add jest or cypress tests as well.
Also do we need a docs PR update for this feature?

2021-08-17 12:13 UTC, marks0351 commented on app/client/src/components/designSystems/appsmith/TableComponent/TableUtilities.tsx
> +      onClick={(e) => {
pls declare the inline function.

2021-08-17 12:13 UTC, marks0351 commented on app/client/src/components/propertyControls/ColumnActionSelectorControl.tsx
> +                    label={columnAction.label as string}
```suggestion
                    label={columnAction.label || ''}
```

2021-08-17 12:13 UTC, marks0351 commented on app/client/src/widgets/TableWidget/TablePropertyPaneConfig.ts
> +                  hidden: (props: TableWidgetProps, propertyPath: string) => {
is there a way to declare and reuse this function it seems to have been used in multiple places

2021-08-17 12:13 UTC, marks0351 commented on app/client/src/widgets/TableWidget/TablePropertyPaneConfig.ts
>                  return (
u cud create an array constant of all these types with a meaningful name which wud give more readability.
use the Array.includes function to check instead.

2021-08-22 08:38 UTC, Tooluloope commented
> Pls add jest or cypress tests as well.
> Also do we need a docs PR update for this feature?

<img width="678" alt="Screenshot 2021-08-22 at 09 36 38" src="https://user-images.githubusercontent.com/31691737/130348093-4f0a0c44-4672-483d-8ab0-490b1fe28be2.png">

@somangshu @marks0351 this is the only reference to columnType i saw on the docs.
Not sure  there's anywhere to update this on the docs

2021-08-23 05:37 UTC, marks0351 requested changes

2021-08-23 05:37 UTC, marks0351 commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/Table_Widget_Add_button_spec.js
> +  // it("Table widget with Add button test and validation", function() {
why have we commented these tests?

2021-08-23 06:45 UTC, Tooluloope commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/Table_Widget_Add_button_spec.js
> +  // it("Table widget with Add button test and validation", function() {
Fixed, I guess I skipped it during my review

2021-08-23 06:57 UTC, marks0351 approved these changes

2021-08-23 11:22 UTC, YogeshJayaseelan commented
@marks0351 Tested this PR and please find the status below,

1.Click on any o the icon in the table throws the following 'Cannot read property 'replace' of undefined' 

https://www.loom.com/share/b2ca756a61f64451a813cd806707691b

2021-08-23 11:25 UTC, somangshu commented
@YogeshJayaseelan please leave all feedback together if possible. This will help us minimize the to and fro

2021-08-24 16:07 UTC, Tooluloope commented
@YogeshJayaseelan, Fixed the first issue, the same thing happens when you change to a Button type, You can open an issue for that and assign it to me

2. @somangshu, I felt it should have a JS option, since its on a Table, and Each row could have different icons and styles based on some other logic.

2021-08-27 11:13 UTC, somangshu submitted a review, later dismissed
Approving to run tests

@marks0351 can you check the code and take a call once

2021-08-30 13:17 UTC, marks0351 submitted a review, later dismissed

2021-08-31 04:47 UTC, YogeshJayaseelan commented
@Tooluloope Verified the fix for 6th point and it is working as expected.

Suggestion:
7. Can we remove the icon columns in filter pane options as we ignored buttons in the filter pane option - clicking on icons in the filter pane throws - oops try again something went wrong error

https://www.loom.com/share/aa71b1d39a484bfcb97f7c16159eff81

2021-08-31 10:21 UTC, YogeshJayaseelan commented
@Tooluloope Verified this PR and it is working as expected

2021-08-31 10:30 UTC, somangshu approved these changes
LGTM

2021-09-01 04:52 UTC, marks0351 approved these changes

2021-09-01 09:50 UTC, merged