FEAT: compact mode in property pane
appsmithorg/appsmith pull request #6637
Opened 2021-08-16 14:28 UTC by Tooluloope

## Description

Select compact Mode only in property pane

Fixes #5633 

## Type of change

> Please delete options that are not relevant.

- New feature (non-breaking change which adds functionality)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-08-17 12:23 UTC, marks0351 requested changes
I think we should use the word Row height  instead of compact mode in the property pane.
Also the toggle for row height visibility is still present in property pane.

cc: @somangshu @Tooluloope

2021-08-17 12:23 UTC, marks0351 commented on app/client/src/widgets/TableWidget/TablePropertyPaneConfig.ts
> +        options: [
should the values be all caps?

2021-08-18 08:23 UTC, Tooluloope commented on app/client/src/widgets/TableWidget/TablePropertyPaneConfig.ts
> +        options: [
@marks0351 , yeah that's the accepted value type.

I'd change it to Row height

2021-08-18 09:08 UTC, marks0351 commented on app/client/src/widgets/TableWidget/TablePropertyPaneConfig.ts
> +        options: [
@Tooluloope I was asking about the labels also being all caps.

2021-08-18 09:12 UTC, marks0351 commented
@Tooluloope pls do add test cases(jest/cypress) as well.

2021-08-18 10:04 UTC, somangshu commented on app/client/src/widgets/TableWidget/TablePropertyPaneConfig.ts
> +        options: [
If we are talking about the dropdown options then they should be First letter caps which is consistent to the rest of the widgets @marks0351 @Tooluloope

2021-08-19 05:09 UTC, marks0351 approved these changes

2021-08-20 09:26 UTC, somangshu commented
@marks0351 can you take a call on if this needs testing and move it to the required pipeline further?

2021-08-24 05:23 UTC, marks0351 submitted a review, later dismissed

2021-08-24 05:32 UTC, marks0351 commented
dp LGTM. we can merge this to release.

2021-08-24 11:21 UTC, somangshu commented
Rerunning all jobs here, `Table_GeneralProperty_spec.js` failed

2021-08-24 11:24 UTC, somangshu commented
Apologies, the failing test is related to the PR, Please check [here](https://dashboard.cypress.io/projects/eyxvp8/runs/9169/test-results/19ee81da-4394-4aed-ab94-127ee000fb5f?statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D), The test cannot find the row height property. @Tooluloope please fix this

2021-08-24 11:29 UTC, Tooluloope commented
> Apologies, the failing test is related to the PR, Please check [here](https://dashboard.cypress.io/projects/eyxvp8/runs/9169/test-results/19ee81da-4394-4aed-ab94-127ee000fb5f?statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D), The test cannot find the row height property. @Tooluloope please fix this

Fixed it already.

2021-08-24 13:29 UTC, jsartisan submitted a review, later dismissed

2021-08-27 09:25 UTC, somangshu submitted a review, later dismissed

2021-09-02 12:59 UTC, somangshu commented
@Tooluloope please clear out the merge conflict, get and approval and merge this ASAP

2021-09-03 07:56 UTC, somangshu submitted a review, later dismissed

2021-09-03 08:02 UTC, somangshu commented
@Tooluloope please bring the row-height property below the Default selected row

2021-09-03 08:58 UTC, somangshu approved these changes
LGTM

2021-09-06 07:05 UTC, merged