Undo/Redo POC
appsmithorg/appsmith pull request #6654
Opened 2021-08-17 09:28 UTC by rahulramesha

## Description

POC for Undo redo project

Fixes # (issue)

> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-08-17 10:14 UTC, rahulramesha commented
/ok-to-test sha=3a450c8

2021-09-01 06:23 UTC, jsartisan submitted a review, later dismissed

2021-09-01 11:52 UTC, rahulramesha commented on app/client/src/components/ads/Toast.tsx
> +  color: #f8682b !important;
move to theme file

2021-09-01 11:52 UTC, rahulramesha commented on app/client/src/sagas/ReplaySaga.ts
> +  if (!replayWidgetId || !replay.widgets[replayWidgetId].propertyUpdates)
Add comments

2021-09-01 11:52 UTC, rahulramesha commented on app/client/src/sagas/ReplaySaga.ts
> +  const isPropertyPaneVisible = yield select(getIsPropertyPaneVisible);
add types

2021-09-01 11:52 UTC, rahulramesha commented on app/client/src/sagas/WidgetOperationSagas.tsx
> +// Page load -> DSL -> unevalTree -> yjs structure
Remove this

2021-09-01 11:52 UTC, rahulramesha commented on app/client/src/utils/replayHelpers.tsx
> +  const actionDescription = isCreated
move to diff function and use switch case

2021-09-01 11:52 UTC, rahulramesha commented on app/client/src/utils/replayHelpers.tsx
> +    scrollIntoView(el, {
use element's methopd instead

2021-09-01 11:52 UTC, rahulramesha commented on app/client/src/workers/ReplayDSL.ts
> +  diffMap: any;
convert to private whereever reqd

2021-09-01 11:52 UTC, rahulramesha commented on app/client/src/workers/ReplayDSL.ts
> +      this.logs.push({
convert to a perf log

2021-09-01 11:52 UTC, rahulramesha commented on app/client/src/workers/ReplayDSL.ts
> +    const diffUpdate = isUndo ? revertChange : applyChange;
change name

2021-09-01 11:52 UTC, rahulramesha commented on app/client/src/workers/dslReplay.worker.ts
> +export enum ReplayOperation {
remove file

2021-09-01 11:52 UTC, rahulramesha commented on app/client/src/workers/replayUtils.ts
> +  switch (diff.kind) {
add comments to understand better

2021-09-01 12:01 UTC, jsartisan approved these changes

2021-09-02 08:00 UTC, rahulramesha commented on app/client/src/utils/replayHelpers.tsx
> +    scrollIntoView(el, {
turns out element's `scrollIntoViewIfNeeded` is not supported in firefox so we'll still be using third party library

2021-09-03 13:22 UTC, rahulramesha commented
/ok-to-test sha=28b3b5c

2021-09-03 14:26 UTC, jsartisan submitted a review, later dismissed

2021-09-04 06:14 UTC, riodeuno commented on app/client/src/components/ads/TextInput.tsx
> +  onBlur?: typeof noop;
Are these necessary changes for this project?

2021-09-07 06:44 UTC, marks0351 approved these changes
approving to run cypress tests.

2021-09-07 08:03 UTC, marks0351 requested changes

2021-09-07 08:04 UTC, marks0351 approved these changes

2021-09-07 10:16 UTC, marks0351 approved these changes

2021-09-07 10:36 UTC, marks0351 submitted a review, later dismissed
approving for tests

2021-09-07 12:02 UTC, marks0351 approved these changes

2021-09-08 05:42 UTC, marks0351 approved these changes

2021-09-09 08:21 UTC, jsartisan submitted a review, later dismissed

2021-09-17 07:16 UTC, YogeshJayaseelan commented
@rahulramesha We have identified the below issues and still testing in-progress

1.Adding two widgets to canvas and renaming one of the widget and keeping the property pane open and press cmd+z to undo and cmd+shift+z to redo then close the property pane and press cmd+z - The widgets get selected and ready to be grouped

https://www.loom.com/share/90ae610db24b4a2d8fca55c4ed20400b

2. Choosing any of the options in checkbox group widget individually and clicking on cmd+z doesn't undo the last selection in the checkbox group widget. whereas if the user drags few widgets along with checkbox group widget to canvas and then grouping all the widget to an container and making selections in the checkbox group and clicking on cmd+d undo's the checkbox group selection

https://www.loom.com/share/4e2f9de2a1784b20bcabce291dc285d3

2021-09-17 14:41 UTC, rahulramesha commented
@YogeshJayaseelan pushed a fix for the first issue, 
for second issue, we don't have support for undo-redo for widget meta properties as it is meant for end users

2021-09-20 14:25 UTC, rahulramesha commented
@YogeshJayaseelan
issue 3, Whenever Input field is in focus, undo-redo is handled by that particular input field itself, this is as expected.
issue 4, Undo-redo does not work on widget meta properties. I agree that the UX in this corner case is not great but we don't have a readily available solution for this.
issues 5 and 6 were fixed.

2021-09-20 16:36 UTC, YogeshJayaseelan commented
@rahulramesha Verified the fixes and please find the status below,

Issues fixed:
1,5

Agreed on :
2 - Meta property is not included
3 - Undo/Redo will focus on input field change 
4- Meta property is not included

Reopen:
6 - Still exists - Changing the modal type to form and using cmd+z for the first time the modal is not defaulted to alert modal 

https://www.loom.com/share/4cc6171018834fb29df1285dd7ad99a9

Suggestion:
7 - Can we implement this feature for API and Datasource

2021-09-20 17:29 UTC, rahulramesha commented
@YogeshJayaseelan please test 6 again, with the latest resizable modal gone in, this wont be a problem anymore.

2021-09-21 04:52 UTC, YogeshJayaseelan commented
@rahulramesha Verified the issue 6 and now there is no options to change modal type and problem is resolved. We can proceed further

2021-09-21 05:20 UTC, jsartisan submitted a review, later dismissed

2021-09-21 06:14 UTC, marks0351 approved these changes

2021-09-21 06:17 UTC, jsartisan approved these changes

2021-09-21 07:55 UTC, merged