FIX #6615 : added check for open filter pane and close if before property pane open
appsmithorg/appsmith pull request #6662
Opened 2021-08-17 14:50 UTC by vibhandikyash

## Description

> It is observed that when the user keeps the table filter open and drags and drops any other widgets to the canvas the app crashes. So, added check for open filter pane and close if before property pane open.

Fixes #6615 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Tested locally.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-08-17 14:53 UTC, somangshu submitted a review, later dismissed
Approving for the tests to run.

@SatishGandham Can you check the code on a priority, This is a hotfix which is blocking the RC

2021-08-18 04:09 UTC, YogeshJayaseelan commented
@vibhandikyash @somangshu Tested the bug fix and now keeping the filter pane open and dragging and dropping any other widgets to canvas the app doesn't crash. 
But, in the table filter pane the columns or operator are not selectable - **Should i raise an separate issue for this**

https://www.loom.com/share/b9a9f71192c644d5b9ed83a044b883f1

2021-08-18 05:36 UTC, somangshu commented
@vibhandikyash please look into the above issue, We cant ship the widget in this state

2021-08-18 05:40 UTC, vibhandikyash commented
> @vibhandikyash @somangshu Tested the bug fix and now keeping the filter pane open and dragging and dropping any other widgets to canvas the app doesn't crash.
> But, in the table filter pane the columns or operator are not selectable - **Should i raise an separate issue for this**
> 
> https://www.loom.com/share/b9a9f71192c644d5b9ed83a044b883f1

Yes, @YogeshJayaseelan Pl. create a new issue for the same. Will take this too

2021-08-18 05:41 UTC, SatishGandham approved these changes

2021-08-18 05:52 UTC, SatishGandham requested changes
Why should the filter be closed before drag and drop.

2021-08-18 05:58 UTC, YogeshJayaseelan commented
@vibhandikyash Created new issue for the filter pane column and operator select - #6673

2021-08-18 08:13 UTC, vibhandikyash commented
> Why should the filter be closed before drag and drop.

@SatishGandham  There is Popper component used by property pane and filter pane in that there is a function draggableElement which makes our component draggable, uses createDragHandler func, it raises error "NotFoundError: Failed to execute 'replaceChild' on 'Node': The node to be replaced is not a child of this node" if already one draggable element present in dom.

2021-08-18 08:14 UTC, vibhandikyash commented
> @vibhandikyash Created new issue for the filter pane column and operator select - #6673

@YogeshJayaseelan I've fixed the above issue here itself. Kindly test it again. Will reference this issue in the same PR.

2021-08-18 09:43 UTC, YogeshJayaseelan commented
@vibhandikyash Verified this fix and it is working as expected

2021-08-18 09:53 UTC, SatishGandham approved these changes

2021-08-18 10:31 UTC, merged