Fix: load main container without waiting for evaluations to complete.
appsmithorg/appsmith pull request #6669
Opened 2021-08-18 05:05 UTC by marks0351

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.

## Description

> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change.

Fixes # (issue)

> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-08-19 07:00 UTC, hetunandu requested changes

2021-08-19 07:00 UTC, hetunandu commented on app/client/src/selectors/editorSelectors.tsx
> +      if (evaluatedWidget || widgetKey === MAIN_CONTAINER_WIDGET_ID) {
Instead of manipulating this if statement. Always add this widget by default before looping through other evaluated widgets

2021-08-23 05:28 UTC, marks0351 commented on app/client/src/selectors/editorSelectors.tsx
> +      if (evaluatedWidget || widgetKey === MAIN_CONTAINER_WIDGET_ID) {
if we do that we have to add if else statement to not add loading state for maincontainer or filter maincontainer from canvasWidgets before iterating. thoughts?

2021-08-24 11:08 UTC, riodeuno commented on app/client/src/selectors/editorSelectors.tsx
> +      if (evaluatedWidget || widgetKey === MAIN_CONTAINER_WIDGET_ID) {
If we have to have this check in either case, then let's just go with this approach. @hetunandu Let us know if there is reason for the approach you suggested.

2021-08-24 11:21 UTC, hetunandu commented on app/client/src/selectors/editorSelectors.tsx
> +      if (evaluatedWidget || widgetKey === MAIN_CONTAINER_WIDGET_ID) {
We should then add it by default and filter it from the list before looping.

2021-08-25 07:50 UTC, hetunandu approved these changes

2021-08-25 09:09 UTC, merged