Implement fat container for appsmith application
appsmithorg/appsmith pull request #6678
Opened 2021-08-18 07:53 UTC by geekup-legodevops

## Description

- Implement fat container for Appsmith ( include all service: redis, mongodb, rts, backend, editor app)
- Util command in fat container with 2 command export_db & import_db to export & restore database in fat container
- Fat container run without external docker.env configuration file

## Type of change
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-08-24 10:57 UTC, sharat87 requested changes
I've put in comments to a few clarifications and some changes. But it looks quite close to getting merged. Awesome work! 🎉

2021-08-24 10:57 UTC, sharat87 commented on deploy/fat_container/README.md
> +    driver: bridge
Do we need the explicit network configuration here? Considering these two containers don't actually talk to each other at all?

```suggestion

  auto_update:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # Update check interval in seconds.
    command: --interval 300 --label-enable --cleanup
```

2021-08-24 10:57 UTC, sharat87 commented on deploy/fat_container/README.md
> +## 4. Utils Script
How about?

```suggestion
## 4. Instance Management Utilities
```

2021-08-24 10:57 UTC, sharat87 commented on deploy/fat_container/docker-compose.yml
> +    driver: bridge
Same as from README, if we don't need the explicit network configuration, I think we can remove it:

```suggestion

  auto_update:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # Update check interval in seconds.
    command: --interval 300 --label-enable --cleanup

```

2021-08-24 10:57 UTC, sharat87 commented on deploy/fat_container/README.md
> +  <img src="./images/appsmith_supervisord_ui.png" width="80%">
Lets use an absolute URL to the image here instead of a relative path. The reason I say this is because GitHub will render this README at the URL `/appsmithorg/appsmith/deploy/fat_container`, as well as on `/appsmithorg/appsmith/deploy/fac_container/README.md`. But the way this relative link is resolved will be different in these two cases. In the first, it will resolve to `/appsmithorg/appsmith/deploy/images/appsmith_supervisord_ui.png` and in the second, to `/appsmithorg/appsmith/deploy/fat_container/images/appsmith_supervisord_ui.png`.

So its always best to use absolute links (not just for images) in README files on GitHub.

```suggestion
  <img src="https://raw.githubusercontent.com/appsmithorg/appsmith/release/deploy/fat_container/images/appsmith_supervisord_ui.png" width="80%">
```

2021-08-24 10:57 UTC, sharat87 commented on deploy/fat_container/entrypoint.sh
> +set +o allexport
Should we check the existence of this file?

```suggestion
if [[ -f /opt/appsmith/configuration/docker.env ]]; then
  echo 'Load environment configuration'
  set -o allexport
  . /opt/appsmith/configuration/docker.env
  set +o allexport
fi
```

2021-08-24 10:57 UTC, sharat87 commented on deploy/fat_container/entrypoint.sh
> +#!/usr/bin/env bash
The indentation in this file seems inconsistent in several places, making it hard to follow the logic. Can we fix to using one indentation style (2-space or 4-space) and reformat this file please?

2021-08-24 10:57 UTC, sharat87 commented on deploy/fat_container/scripts/renew-certificate.sh
> +fi
Let's add a little note when custom domain is not configured, since this script effectively won't do anything in that case. When we have more docs on this topic, we can even share link to the relevant page in the output here.

```suggestion
else
  echo 'Custom domain not configured. Cannot enable SSL without a custom domain.' >&2
fi

```

2021-08-24 10:57 UTC, sharat87 commented on deploy/fat_container/scripts/renew-certificate.sh
> +if [[ -n $CUSTOM_DOMAIN ]]; then
Minor check.

```suggestion
if [[ -f /opt/appsmith/docker.env ]]; then
  set -o allexport
  . /opt/appsmith/docker.env
  set +o allexport
fi

if [[ -n $CUSTOM_DOMAIN ]]; then
```

2021-08-24 10:57 UTC, sharat87 commented on deploy/fat_container/templates/docker.env.sh
> +# APPSMITH_DISABLE_TELEMETRY=false
Let's uncomment env variables, where the value is a valid value (instead of an empty string). We've seen in the past where folks would change the value of an env variable, but forget to uncomment, and then come complaining on Discord that it doesn't work. Since the value `false` here is a valid value here, let's uncomment this proactively.

```suggestion
APPSMITH_DISABLE_TELEMETRY=false
```

2021-08-24 10:57 UTC, sharat87 commented on deploy/fat_container/templates/mongo-init.js.sh
> +    db.group.insert({
@mohanarpit, can we take this opportunity to remove the `group` and `propertyPane` inserts from this file? 😄

2021-08-24 10:57 UTC, sharat87 commented on deploy/fat_container/templates/nginx_app.conf.sh
> +		root /opt/appsmith/data/certificate/certbot;
If the commented line is not required, or is unused, can we remove it? Let's try to avoid commented code where possible.

```suggestion
		root /opt/appsmith/data/certificate/certbot;
```

2021-08-24 10:57 UTC, sharat87 commented on deploy/fat_container/templates/supervisord/application_process/cron.conf
> +[program:cron]
QQ, are we running our own cron daemon? Doesn't Debian come with one by default?

2021-08-24 10:57 UTC, sharat87 commented on deploy/fat_container/utils/package.json
> +  "license": "ISC",
Small adjustments.

```suggestion
  "license": "Apache-2.0",
  "private": true,
  "repository": {
    "type": "git",
    "url": "https://github.com/appsmithorg/appsmith.git",
    "directory": "deploy/fat_container"
  },
```

2021-08-24 10:57 UTC, sharat87 commented on deploy/fat_container/utils/bin/import_db.js
> +// Init function export mongodb
Can we reformat this file? The indentation isn't consistent and it makes it hard to follow the logic and identify where a particular brace is closing etc.

2021-08-24 10:57 UTC, sharat87 commented on deploy/fat_container/utils/bin/import_db.js
> +		start_application()
If there is an exception in `import_database`, that means the control flow will jump into the `catch` block, and this line for `start_application` will never be called right? Can we instead add a `finally` block and call `start_application()` inside the `finally` block? That way, the application will restart even if the import process failed or succeeded.

2021-08-24 10:57 UTC, sharat87 commented on deploy/fat_container/utils/bin/export_db.js
> +    start_application()
Same as my comment for import_db script, can we call `start_application()` from a `finally` block?

2021-08-24 10:58 UTC, sharat87 commented
Also, can we use a smaller, more focused image for the screenshot instead of the whole browser? Something like just:

![Screenshot 2021-08-24 at 16 26 33](https://user-images.githubusercontent.com/120119/130605093-b5e3530c-1b13-4c56-bb1b-ff41cd7f4602.png)

2021-08-24 10:58 UTC, mohanarpit commented on deploy/fat_container/templates/mongo-init.js.sh
> +    db.group.insert({
Yes please. Those are redundant now. Can remove.

2021-08-25 00:27 UTC, sharat87 commented on deploy/fat_container/templates/mongo-init.js.sh
> +    db.group.insert({
@geekup-legodevops We can remove all the calls to `db.group.insert` and `db.config.insert` in this file.

2021-08-28 11:53 UTC, sharat87 requested changes
Looks good. Just one more comment.

2021-08-28 11:53 UTC, sharat87 commented on Dockerfile
> +VOLUME [ "/opt/appsmith/stacks" ]
This makes for slightly internal-looking path name. Do we require this to be under `/opt/appsmith`? Can we change this to something like `/appsmith-data`? It'll be shorter, and it'll be more memorable when people are writing docker-compose files.

2021-08-30 01:53 UTC, geekup-legodevops commented on Dockerfile
> +VOLUME [ "/opt/appsmith/stacks" ]
1/ For the prefix path `/opt/appsmith` , we do not require this to be under this path, we only want to store all resources in the same work directory to keep folder structure clean. We can remove it.
2/ Actually, we have more things in this folder rather than only data. We also have configuration files and SSL certificate under this folder. We suggest that we can make it like `/stacks` or `/appsmith-stacks` to keep it memorable but still match with folder purpose

2021-08-30 04:25 UTC, sharat87 commented on Dockerfile
> +VOLUME [ "/opt/appsmith/stacks" ]
Alright, makes sense. Yeah lets go with `/appsmith-stacks`.

2021-08-31 02:20 UTC, sharat87 approved these changes

2021-09-01 05:32 UTC, merged