FIX - Firefox input widget text selection
appsmithorg/appsmith pull request #6832
Opened 2021-08-24 13:03 UTC by ashit-rath

## Description

Fixes #6723 

Cause - This is a very old issue that yet to be resolved by Mozilla
https://bugzilla.mozilla.org/show_bug.cgi?id=800050
https://bugzilla.mozilla.org/show_bug.cgi?id=1189486

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
Manual

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-08-25 05:38 UTC, marks0351 requested changes

2021-08-25 05:38 UTC, marks0351 commented on app/client/src/widgets/InputWidget.tsx
> +    super.updateWidgetProperty("dragDisabled", focusState);
i think this calls an api to update DSL. doesn't seem like a good way to solve this issue.

2021-08-25 09:51 UTC, ashit-rath commented on app/client/src/widgets/InputWidget.tsx
> +    super.updateWidgetProperty("dragDisabled", focusState);
So should I be using `updateWidgetMetaProperty` here? that would just update the local state
```
this.props.updateWidgetMetaProperty("dragDisabled", focusState);
```

2021-09-01 04:53 UTC, marks0351 approved these changes

2021-09-02 13:33 UTC, vivekverma2312 commented
Working fine on deploy preview.

2021-09-03 04:49 UTC, merged