feat: Map Chart widget
appsmithorg/appsmith pull request #6929
Opened 2021-08-27 09:30 UTC by wmdev0808

## Description
- The first MVP of the Map Chart widget
- Fixes #6314 

## Type of change

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

## How Has This Been Tested?

- Test A
- Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: feature/6314-map-chart-widget 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 55.07 **(0.03)** | 36.57 **(0.01)** | 34.5 **(0.01)** | 55.59 **(0.03)**
 :red_circle: | app/client/src/icons/WidgetIcons.tsx | 61.45 **(-0.28)** | 100 **(0)** | 17.95 **(-0.47)** | 61.45 **(-0.28)**
 :green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.94 **(0.23)** | 41.67 **(0.84)** | 36.21 **(0)** | 56.99 **(0.25)**
 :sparkles: :new: | **app/client/src/widgets/MapChartWidget/constants.ts** | **100** | **100** | **100** | **100**
 :sparkles: :new: | **app/client/src/widgets/MapChartWidget/index.ts** | **100** | **100** | **100** | **100**
 :sparkles: :new: | **app/client/src/widgets/MapChartWidget/widget/index.tsx** | **58.97** | **0** | **40** | **59.46**</details>

2021-08-28 06:17 UTC, somangshu approved these changes
Approving to run tests and build DP

2021-09-01 04:35 UTC, jsartisan commented
The current build is failing due to some console statements.

2021-09-01 12:13 UTC, somangshu approved these changes
Approving to run build

2021-09-02 04:39 UTC, jsartisan commented
![Screenshot_32](https://user-images.githubusercontent.com/6636360/131782715-a0e3f4c2-3f7d-455f-845a-d77309bfe298.png)
Build failing due to this error.

An easy way to track this is by checking the console on your local before pushing.

2021-09-02 12:08 UTC, somangshu approved these changes
Approving to run tests

2021-09-06 04:51 UTC, jsartisan commented
DP build still failing :/.

2021-09-06 12:12 UTC, somangshu approved these changes

2021-09-06 13:05 UTC, somangshu commented
@wmdev0808 can you run `yarn install` and push again

2021-09-06 13:56 UTC, somangshu approved these changes

2021-09-07 11:59 UTC, jsartisan commented
@somangshu something weird with this PR. the build does not get build.
@ashit-rath I remember this happened with you too. what did you do to resolve this?

2021-09-07 12:28 UTC, ashit-rath commented
@jsartisan IIRC I was importing an enum from `ChartComponent` and that kind of made the whole component load in the main chunk. 
I think that [this](https://github.com/appsmithorg/appsmith/pull/6929/files?file-filters%5B%5D=.json&file-filters%5B%5D=.svg&file-filters%5B%5D=.ts&file-filters%5B%5D=.tsx#diff-015d25078665de72b86b48e0a50f40e09f3c4abd62203382bca9e0a911ce000cR24) might cause this issue. Can you comment that import, try building it locally and see i that reduces the bundle size?

2021-09-07 14:30 UTC, somangshu commented
@ashit-rath that's exactly what is happening right now. The chunk size has increased to 9.12 MB and that more than the limit, this is happening because there are multiple map files included for the map chart data. Ideally chunk optimisation takes care of this.

We are still not sure what the solution is here. @wmdev0808 please add anything I might have missed

2021-09-08 07:38 UTC, somangshu submitted a review, later dismissed
Approving to rerun the build again

2021-09-08 08:12 UTC, somangshu commented
@jsartisan @ashit-rath @wmdev0808 the build pass on increasing the cache size in the build config. My question now is that if the chunk size is acceptable?

@wmdev0808 we also need to check if we are doing the imports correctly and not loading any files which might not be required. 

cc @riodeuno @SatishGandham

2021-09-08 09:18 UTC, wmdev0808 commented
> @jsartisan @ashit-rath @wmdev0808 the build pass on increasing the cache size in the build config. My question now is that if the chunk size is acceptable?
> 
> @wmdev0808 we also need to check if we are doing the imports correctly and not loading any files which might not be required.
> 
> cc @riodeuno @SatishGandham

@somangshu I've reviewed the existing code base and I couldn't find any code mess.
In addition, I've analyzed the chunk and here are results:
- FusionCharts: 2.49MB
- FusionMaps: 1.52MB
Currently, we are statically importing 8 map definition files(every definition file has size of 50KB ~ 461.91KB). 
To sum up, 
- We can consider the dynamic import way of these definition files when they are required, I am not sure with the solution yet.
- Increased chunk size due to introducing FusionCharts, FusionMaps is inevitable, I guess.

2021-09-08 09:26 UTC, ashit-rath commented
@somangshu @wmdev0808 My suggestion here would be to move out the typings and the constants (dataSetForWorld/dataSetForWorldWithAntarctica) from the `MapChartComponent` to its separate files.
It would do 2 things
1. Moving the constants to a separate file would make the component leaner.
2. As the typings are referred to in another component, webpack is picking up the whole and putting it in the main bundle thus increase the size. Thus having the typings in a separate file would make webpack not touch the main component (MapChartComponent).

2021-09-10 05:12 UTC, jsartisan approved these changes

2021-09-10 07:22 UTC, riodeuno requested changes

2021-09-10 07:22 UTC, riodeuno commented on app/client/src/components/designSystems/appsmith/MapChartComponent.tsx
> +  },
These constants will go into the `constants.ts` file of the widget folder.

2021-09-10 07:22 UTC, riodeuno commented on app/client/src/components/designSystems/appsmith/MapChartComponent.tsx
> +    newChartConfigs["events"]["entityClick"] = (evt: any) => {
If there is an API to detach event handlers let's add this in the `return` of the `useEffect` for a cleanup of event handlers.

2021-09-10 07:22 UTC, riodeuno commented on app/client/src/mockResponses/WidgetConfigResponse.tsx
> +      rows: 8 * GRID_DENSITY_MIGRATION_V1,
These will go in the `index.ts` file of the widget folder. To generate the widget folder please use `yarn generate:widget`

2021-09-10 07:22 UTC, riodeuno commented on app/client/src/widgets/MapChartWidget.tsx
> +import * as Sentry from "@sentry/react";
`sentry` and `MetaHOC` don't need to be imported. Please see other widgets like `input widget`. We just need to add `needsMeta` in the `index.ts` file.

2021-09-10 07:22 UTC, riodeuno commented on app/client/src/widgets/MapChartWidget.tsx
> +      /* webpackPrefetch: true, webpackChunkName: "charts" */ "components/designSystems/appsmith/MapChartComponent"
Let's name the chunks `mapCharts`, as `charts` should already be used in the ChartWidget.

2021-09-10 07:22 UTC, riodeuno commented on app/client/src/widgets/MapChartWidget.tsx
> +              const propertiesToUpdate = [{ propertyPath, propertyValue }];
Please create a separate function outside of the widget class and use it here. Please check Table widget's property config file for reference. When adding the function, please add a function comment describing what other properties the updateHook is updating.

2021-09-10 07:22 UTC, riodeuno commented on app/client/src/widgets/MapChartWidget.tsx
> +                          // required: true,
If these are not required, please remove the `params` property.

2021-09-13 05:50 UTC, riodeuno requested changes

2021-09-13 05:50 UTC, riodeuno commented on app/client/src/assets/icons/widget/map-chart.svg
> +<path fill-rule="evenodd" clip-rule="evenodd" d="M9.50001 11.8034V18.5L14.5 21V11.55L12 15C11.3917 14.2179 10.4119 12.9626 9.50001 11.8034Z" fill="#EAEAEA"/>
We don't need this file anymore.

2021-09-13 05:50 UTC, riodeuno commented on app/client/src/constants/CustomMapConstants .ts
> +export const CUSTOM_MAP_TYPES = [
This filename has a space in it. Also, this will now go into the widgets/MapChartWidget folder.

2021-09-13 05:50 UTC, riodeuno commented on app/client/src/widgets/MapChartWidget/index.ts
> +    mapType: MapTypes.WORLD,
Please move MapTypes to the constants.ts file. Let's not import from the component.

2021-09-13 05:50 UTC, riodeuno commented on app/client/src/widgets/MapChartWidget/constants.ts
> +export const MAPCHART_WIDGET_CONSTANT = "";
We can remove this constant.

2021-09-16 09:32 UTC, riodeuno submitted a review, later dismissed
Code looks good to me. Needs QA.

2021-09-16 09:37 UTC, riodeuno commented
@wmdev0808 We will need cypress tests for the regular workflows here.

- onEntityClick workflow
- switch map type workflow
- Add title workflow
- Hide/show labels workflow
- Custom map config workflow.

These are quite similar to the chart widget tests. You could take inspiration from there.

2021-09-22 06:34 UTC, riodeuno approved these changes

2021-10-04 04:53 UTC, somangshu commented
@jsartisan @riodeuno need to know what is pending here, This is stuck for quiet a while now

2021-10-04 04:58 UTC, riodeuno reviewed
Code has been reviewed. One comment about allowing larger bundle sizes. @marks0351 @SatishGandham Can we verify if this is necessary?

2021-10-04 04:58 UTC, riodeuno commented on app/client/craco.build.config.js
> +    maximumFileSizeToCacheInBytes: 10 * 1024 * 1024,
Is this change still needed? Did the optimizations help?

2021-10-04 05:04 UTC, somangshu commented on app/client/craco.build.config.js
> +    maximumFileSizeToCacheInBytes: 10 * 1024 * 1024,
Not sure about that, This was done because there are separate definition files for different map charts, hence the build size is increasing. @wmdev0808 can you tell if this is not required any more?

2021-10-04 05:28 UTC, wmdev0808 commented on app/client/craco.build.config.js
> +    maximumFileSizeToCacheInBytes: 10 * 1024 * 1024,
@somangshu, it is still required to custom map type

2021-10-04 05:45 UTC, marks0351 commented on app/client/craco.build.config.js
> +    maximumFileSizeToCacheInBytes: 10 * 1024 * 1024,
can we try lazy loading fusion map charts only when there is a map chart widget and see if that gives a new chunk?
if this works we can do the same with chart widget.

2021-10-06 09:55 UTC, somangshu commented
@marks0351 can you review the change

2021-10-07 22:52 UTC, riodeuno submitted a review, later dismissed

2021-11-02 13:11 UTC, somangshu commented
@wmdev0808 related tests have failed here

2021-11-04 09:39 UTC, wmdev0808 commented
> @wmdev0808 related tests have failed here

@somangshu , I've reviewed the test cases, it is failing on calling `createModal` cypress command.
It happens in all the cypress test cases using the above command, so it's not the issue specific to this PR

2021-11-04 12:11 UTC, wmdev0808 commented
/ok-to-test sha=bc17ffd

2021-11-04 12:12 UTC, wmdev0808 commented
https://github.com/appsmithorg/appsmith/actions/runs/1421167047

2021-11-05 06:32 UTC, somangshu commented
The same test only present in this branch is failing, Please check `Smoke_TestSuite/ClientSideTests/DisplayWidgets/MapChart_spec.js` line no `:106`, I dont really understand what are we trying to achieve here. Do try to remove this, And run locally, we should see the error go away

2021-11-05 08:14 UTC, wmdev0808 commented
> @wmdev0808 The same test only present in this branch is failing, Please check `Smoke_TestSuite/ClientSideTests/DisplayWidgets/MapChart_spec.js` line no `:106`, I dont really understand what are we trying to achieve here. Do try to remove this, And run locally, we should see the error go away

@somangshu ,
That test case is for ensuring onEntityClick action, that is, when the user click on the map's entity, it should popup a modal.
It was working before.
At the moment, I will just comment it out

2021-11-05 08:16 UTC, wmdev0808 commented
/ok-to-test sha=67c4714

2021-11-05 08:17 UTC, wmdev0808 commented
https://github.com/appsmithorg/appsmith/actions/runs/1424887995

2021-11-05 08:21 UTC, somangshu commented
Understood, that makes sense. @wmdev0808 can we replace the action executed onEntityClick

@rahulramesha this might be related to the modal widget. Do you mind taking a look at the problem here.

2021-11-05 08:24 UTC, wmdev0808 commented
> Understood, that makes sense. @wmdev0808 can we replace the action executed onEntityClick
> 
> @rahulramesha this might be related to the modal widget. Do you mind taking a look at the problem here.

@somangshu , I can see it is not working in other places using common cypress command `createModal` , so it would be better if someone who wrote that command look into the issue

2021-11-08 05:42 UTC, marks0351 commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/MapChart_spec.js
> +  //   cy.createModal("Alert Modal", this.data.AlertModalName);
is this test failing on your local as well? make sure the property pane is open before we call this command.

2021-11-08 05:47 UTC, wmdev0808 commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/MapChart_spec.js
> +  //   cy.createModal("Alert Modal", this.data.AlertModalName);
@marks0351 , Yes, it fails.
It is just because of using createModal cypress method.
As you look into its usage over the codebase, all of the test cases using it are failing.
Of course, it was working correctly, so it would be better if you can just ask the guy who wrote that command to look into the issue

2021-11-08 07:40 UTC, rahulramesha commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/MapChart_spec.js
> +  //   cy.createModal("Alert Modal", this.data.AlertModalName);
@wmdev0808,
- AFAIK, `createModal` accepts only one argument, so the second one i feel is not required.
- `this.data.AlertModalName` does not seem to be defined, you can try defining this in example.json or you can just use the String alone and use it to verify in line: 116.
- Since, the argument is also used as name of the widget, it should not have space character in it, please change from "Alert Modal" to something like "Alert_Modal".

2021-11-08 09:23 UTC, wmdev0808 commented
https://github.com/appsmithorg/appsmith/actions/runs/1434063353

2021-11-17 20:03 UTC, wmdev0808 commented
/ok-to-test sha=409a8fd

2021-11-22 04:45 UTC, marks0351 requested changes
@wmdev0808 If i want to show a toast of the clicked data point I am unable to do that, we have to expose a widget property to read the selected/clicked data point like we provide in chart widget, right now in there is no property to work with. 
pls change the onEntityClick to onDataPointClick to maintain consistency with Chart widget.
can u add more tests to check the functionality of the widget along with actions like toast or showing modal.

2021-11-22 04:59 UTC, marks0351 requested changes

2021-11-22 04:59 UTC, marks0351 commented on app/client/src/constants/HelpConstants.ts
> +  MAP_CHART_WIDGET: {
we wud need to documentation completed as well 
cc: @vihar @somangshu

2021-11-22 04:59 UTC, marks0351 commented on app/client/src/widgets/MapChartWidget/component/index.tsx
> +    switch (type) {
do we need this switch?
can we not just use CUSTOM_MAP_PLUGINS

2021-11-22 04:59 UTC, marks0351 commented on app/client/src/widgets/MapChartWidget/constants.ts
> +export const colorRange = {
can you pls rename this to mapChartColorRange

2021-11-22 04:59 UTC, marks0351 commented on app/client/src/widgets/MapChartWidget/constants.ts
> +export const colorRange = {
also this being a constant will restrict the colour customisation of the widget. can we provide the user a way to customise colour range.

2021-11-22 05:53 UTC, marks0351 commented
@momcilo-appsmith @vasanth-appsmith can u guys have a look of the widget icon in the deploy preview.

2021-11-22 07:48 UTC, momcilo-appsmith commented
@marks0351 Please use this icon: https://www.figma.com/file/ATfTB5F9Q7ZiI0yYckuXW7/Deprecated-Design-System?node-id=72%3A8484

2021-11-24 09:03 UTC, wmdev0808 commented on app/client/src/widgets/MapChartWidget/component/index.tsx
> +    switch (type) {
Sure.
It is required to inject appropriate `type` in config object.
After that, it will be used to extract alias so that we can select map definition files accordingly.

2021-11-24 22:11 UTC, wmdev0808 commented
/ok-to-test sha=e504459

2021-11-25 08:55 UTC, marks0351 requested changes
When I change the colour, it is not updated in the widget unless i move  the widget or refresh the page.
selectedDatapoint value is still not available. I can see the autocomplete but there is no value output. 
Pls add test cases around using selectedDatapoint to show a message or toggle another widget.

2021-11-25 12:42 UTC, wmdev0808 commented
> When I change the colour, it is not updated in the widget unless i move the widget or refresh the page. selectedDatapoint value is still not available. I can see the autocomplete but there is no value output. Pls add test cases around using selectedDatapoint to show a message or toggle another widget.

Hi @marks0351 , 
Unfortunately, The above comments does not make sense for me.
I'd like to confirm it

2021-11-25 13:26 UTC, wmdev0808 commented
/ok-to-test sha=cb2a5c9

2021-11-29 07:01 UTC, marks0351 submitted a review, later dismissed

2021-12-16 08:42 UTC, YogeshJayaseelan commented
@wmdev0808 Started testing this feature and please find the issues below,

Issue 1 - Choosing any of the map type (ex - Asia ) and changing the position of the widgets - Reloads the map to the 'world map' but still the map type is Asia in the property pane

https://www.loom.com/share/1d45780eba774cf297d52d57c2a2e5bc

Issue 2 - Map chart icon is not displayed in the entity explorer 

https://www.loom.com/share/af32d8793a8d4ad99d28016bc546e5ac

Issue 3 - Colour range and data field accepts duplicate value and no validation message is displayed

<img width="1680" alt="Screenshot 2021-12-16 at 12 59 54 PM" src="https://user-images.githubusercontent.com/35128442/146327232-7b860b09-4a7c-4574-981c-0b3a4cab347e.png">

Issue 4 - Choosing any of the map (Ex- Europe) and clicking on deploy initially loads the world map in the deploy mode and double clicking on any of the region on the map reloads the widget to Europe 

https://www.loom.com/share/478ac8e5125549f699655f5660afb825

2021-12-16 10:29 UTC, YogeshJayaseelan commented
@somangshu The figma link attached to this feature does not have design related to Map chart. Can you help me with the valid figma design

2021-12-16 10:39 UTC, somangshu commented
The design attached it only for the icon @YogeshJayaseelan,

Please test this widget out similar to the chart widget. Testing out various configuration is more important

2021-12-21 19:12 UTC, wmdev0808 commented
> Issue 10 - Question - For each map type the colour code can be different right? currently the colour code added for one map type is applicable for other map types too

No, color range array are widget-scoped, not map type based one

2021-12-21 19:47 UTC, wmdev0808 commented
/ok-to-test sha=894544a

2021-12-23 06:56 UTC, marks0351 requested changes

2021-12-23 06:56 UTC, marks0351 commented on app/client/src/widgets/MapChartWidget/component/index.tsx
> +  }, [JSON.stringify(data), type]);
why are we stringifying this?

2021-12-23 06:56 UTC, marks0351 commented on app/client/src/widgets/MapChartWidget/index.ts
> +    rows: 8 * GRID_DENSITY_MIGRATION_V1,
this is just a general comment, we can just remove GRID_DENSITY_MIGRATION_V1 and use 32, 24 values directly.

2021-12-23 06:56 UTC, marks0351 commented on app/client/src/widgets/MapChartWidget/widget/index.tsx
> +  switch (propertyValue) {
can we just use an object and map instead of adding switch case the code will looks simpler and more readable.

2021-12-23 07:57 UTC, wmdev0808 commented on app/client/src/widgets/MapChartWidget/component/index.tsx
> +  }, [JSON.stringify(data), type]);
Data is an object array, so its changes can only be captured if its size changed, not detecting changes of any existing element.
In order to have the effect always run when any changes happen to the array, stringifying the array works well

2021-12-23 09:25 UTC, wmdev0808 commented
/ok-to-test sha=c6ad1f2

2021-12-23 09:51 UTC, marks0351 requested changes

2021-12-23 09:51 UTC, marks0351 commented on app/client/src/widgets/MapChartWidget/widget/index.tsx
> +  const dataSetMapping: Record<MapType, any> = {
can u move this mapping out of the function so that it doesn't get created every time the update function is run.

2021-12-23 10:00 UTC, wmdev0808 commented
/ok-to-test sha=58166c4

2021-12-23 11:30 UTC, marks0351 approved these changes

2021-12-24 10:05 UTC, somangshu commented
@wmdev0808 related test is failing here

2021-12-27 15:12 UTC, wmdev0808 commented
/ok-to-test sha=74f7339

2021-12-28 05:05 UTC, wmdev0808 commented
/ok-to-test sha=74f7339

2021-12-29 17:11 UTC, wmdev0808 commented
/ok-to-test sha=59d9f99

2021-12-30 08:44 UTC, YogeshJayaseelan commented
@wmdev0808 Re-Tested this PR and please find the status below,

Issue 1 - Fixed
Issue 2 - Fixed,
**Issue 3 - Reopen - with following steps - Add two or three duplicate values - And changing one of the duplicated values to any existing value and observe - Refer video below**

https://loom.com/share/50b6e8e340eb41c08fa61c65a60095af


Issue 4 - Fixed
Issue 5 - Fixed
Issue 6 - Reopen - With following steps - Disable the colour code and reposition the widget and observe

https://www.loom.com/share/c43ad44af72d467c8463b327fb7d8ce5

Issue 7 - Fixed
Issue 8 - Fixed
Issue 9 - Fixed
Issue 10 - Accepted as Default Behaviour 

**New issues** 
Issue 11 - In the colour code option if the Min and max value are reversed for any the new value with an existing value then duplicate color code is displayed don the widget 

https://www.loom.com/share/92a7f7120e9a43758ebb144e468af3cf

Issue 12 - Colour code option - Min and Max value cannot be same - No validation error is displayed 

https://loom.com/share/b377a85ace7247eca5b07fbb55fcd1c5

2021-12-31 10:38 UTC, somangshu commented
@YogeshJayaseelan here is my observation:
- **ISSUE 3** - This is a non issue as the object you are considering is not unique and hence showing up properly on the widget component, Otherwise this is of low priority and does not need solving right now
- **ISSUE 6** - invalid issue, mix of user input and dev experience
- **ISSUE 11** - low priority, can be a separate issue
- **ISSUE 12** - According to me in a range the low and high can both be the same, This is a valid case and not a bug, the component is also handling it well

Kindly give a sign off if the above is acceptable

cc @wmdev0808

2022-01-04 08:10 UTC, YogeshJayaseelan commented
@wmdev0808 Tested this PR and please find the status below,

Issue 1 - Fixed
Issue 2 - Fixed,
Issue 3 - **Not in scope** 
Issue 4 - Fixed
Issue 5 - Fixed
Issue 6 - **Not an issue**
Issue 7 - Fixed
Issue 8 - Fixed
Issue 9 - Fixed
Issue 10 - **Accepted as Default Behaviour**
Issue 11 - **Will raise an separate issue** 
Issue 12 - **Not an issue** 

New issues:

Issue 13 - TypeError: Cannot read properties of undefined (reading 'paper')  occurs in console when the widget is repositioned 

https://loom.com/share/ae27b6ba16da44b3b494d4f45cf8309c

Issue 14 - Resizing of widget. Widget border moves without the content inside

https://loom.com/share/d6b60d8bd6ad4e2ea15d36ddfccf0c50

2022-01-04 10:40 UTC, wmdev0808 commented
/ok-to-test sha=f55a5d0

2022-01-06 07:21 UTC, shwetha-ramesh commented
@wmdev0808 Tested this PR. 
Issue 14 still exists partially when widget is moved to the left
https://loom.com/share/b17d7b18ae104d3fbe7ad63b04bd057e

New issues observed

15. When display value is long the Color range looks bigger than the chart itself. Ideally it should be the other way round
![image](https://user-images.githubusercontent.com/92293815/148341539-88f12123-dfcf-434c-89a3-bc0d5666bbd4.png)

16. With map type ```Ocenia```, there is slight overlapping on values with display values and without display values.
![image](https://user-images.githubusercontent.com/92293815/148341884-a4fc7802-7bec-4575-bc4f-f8baf327face.png)
![image](https://user-images.githubusercontent.com/92293815/148344485-d0428ec6-8d20-4f7a-844b-d82d50d113e7.png)

17. Expected structure and example for ```Map chart data``` shows _string_ but accepts _numbers._
![image](https://user-images.githubusercontent.com/92293815/148343454-a5afaa84-8c12-413d-a834-1a903d5efff0.png)

18. Scroll is not smooth, when clicked on the scroll bar the widget moves, user has to use the arrow keys to move in edit mode.
https://loom.com/share/23f6ad91915045f09e5bb480e0fd8e35

2022-01-07 09:05 UTC, wmdev0808 commented
@shwetha-ramesh ,
I've walked through the whole issues with @somangshu.

- 14, 17, 18: They are not issues, so you can just ignore
- 15, 16: You can create new issues

2022-01-07 09:09 UTC, wmdev0808 commented
/ok-to-test sha=263c7a9

2022-01-07 09:27 UTC, shwetha-ramesh commented
> @shwetha-ramesh , I've walked through the whole issues with @somangshu.
> 
> * 14, 17, 18: They are not issues, so you can just ignore
> * 15, 16: You can create new issues

Will be creating separate issues for 15 & 16. Rest looks good.
cc: @YogeshJayaseelan

2022-01-07 09:57 UTC, merged