feat: API to save git config data
appsmithorg/appsmith pull request #6930
Opened 2021-08-27 09:40 UTC by AnaghHegde

## Description

> API to save git config related data in userData. 

Fixes #6751 

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Locally via postman
- Unit test

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

2021-08-31 04:25 UTC, mohanarpit commented on app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/GitController.java
> +    public Mono<ResponseDTO<String>> saveGitConfigData(@RequestBody GitConfig gitGlobalConfigDTO) {
Minor: Suggestion to rename the variable to reflect the object. I was confused & was looking for the class `GitGlobalConfigDTO` for 2 mins before I realized that the object class is `GitConfig`.

2021-08-31 04:25 UTC, mohanarpit commented on app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog.java
> +    public void addGitConfigToUserObject(MongockTemplate mongockTemplate) {
Any particular reason we are creating an empty Git config object list for all users? Can we not do this at runtime for users setting their Git config for the first time?

2021-08-31 04:25 UTC, mohanarpit commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/GitServiceImpl.java
> +                            GitConfig gitLocalConfig = new GitConfig();
If we use the object being passed to us in the request, do we still need to create a `gitLocalConfig` object & copy all the values over?

2021-08-31 04:25 UTC, mohanarpit commented on app/server/appsmith-server/src/main/java/com/appsmith/server/domains/UserData.java
> +    private List<GitConfig> gitLocalConfigData;
Instead of a list of GitConfig objects, is it possible for us to maintain a map between the `profileName` & `GitConfig` data? Will be easier to find in MongoDB & also easier to update specific fields. We will not need to iterate through all the Git configurations for the user to find the relevant one.

2021-08-31 04:25 UTC, mohanarpit commented on app/server/appsmith-server/src/test/java/com/appsmith/server/services/GitServiceTest.java
> +    String url = "https://github.com/AnaghHegde/Enigma-Reborn.git";
Suggestion to use random test values in test cases instead of actual values. Ensures that future contributors clearly know that this is a test value & don't read too much into it.

2021-08-31 04:25 UTC, mohanarpit commented on app/server/appsmith-server/src/test/java/com/appsmith/server/services/GitServiceTest.java
> +    String orgId = "";
Are we using these values in any test case? I wasn't able to find their usage. If not, suggestion to please remove them.

2021-08-31 05:33 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/GitServiceImpl.java
> +                            GitConfig gitLocalConfig = new GitConfig();
This was created earlier under the impression that request and response obj will be different. I will remove this now.

2021-08-31 07:07 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog.java
> +    public void addGitConfigToUserObject(MongockTemplate mongockTemplate) {
1. That would mean that some documents will have gitConfig fields and some don't. Is that okay - inconsistent fields?
2. If we are to do this at run time, we need to check whether the field exists already and then run the `$update` to add field. The check will run every single time the profile related operation is run. Hence i thought its better to go through with the migration.

2021-08-31 07:14 UTC, mohanarpit commented on app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog.java
> +    public void addGitConfigToUserObject(MongockTemplate mongockTemplate) {
It's not inconsistent fields. In MongoDB, not having a field is equivalent to null values for a column in SQL. Also, even if we run the migration, what happens for new users? Do we set an empty array field for them? 

Can we use `$set` command in MongoDB to update a nested field in the document? If we change the implementation from a list to a map & use `$set` , I think we won't need to necessarily check for null each time.

Lastly, since Git configurations will happen very few times, we shouldn't be looking to optimize a flow with such low usage. We are ending up bloating the DB with more empty data for an operation that the user will probably perform once per application. It's a trade-off that we make.

2021-09-02 09:32 UTC, abhvsn requested changes

2021-09-02 11:52 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/GitServiceImpl.java
> +        return userService.findByEmail(gitConfig.getUserName())
This is to get the userID through which we can access `userData` object where we are storing the `author`, `authorName` and `profileName`.  We are not storing the userName anywhere.

2021-09-02 11:55 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/domains/GitConfig.java
> +
This is to access the `userData` object where we store the profile info. UserName is appsmith login email/id. `user` collection and `userData` is linked via userId field. 
First get the userId from user collection and then get userObject for the user using userId.

2021-09-05 19:13 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/GitController.java
> +        this.gitService = gitService;
If we are passing the instance to parent class do we still require this?

2021-09-05 19:25 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/GitServiceImpl.java
> +                .flatMap(user -> userService.findByEmail(user.getEmail()))
Is there any reason we are asking for the same user?

2021-09-05 19:32 UTC, abhvsn commented on app/server/appsmith-server/src/test/java/com/appsmith/server/services/GitServiceTest.java
> +                .assertNext(userData -> {
Are we expecting a duplicate key error here?

2021-09-05 19:35 UTC, abhvsn commented on app/server/appsmith-server/src/test/java/com/appsmith/server/services/GitServiceTest.java
> +        Mockito.when(userService.findByEmail(Mockito.anyString())).thenReturn(Mono.just(new User()));
Can we remove the duplicated code here if it's not doing anything?

2021-09-05 19:42 UTC, abhvsn commented on app/server/appsmith-server/src/test/java/com/appsmith/server/services/GitServiceTest.java
> +                .assertNext(userData -> {
Should we add a condition with invalid parameter profile name here, as the profile doesn't exists?

2021-09-05 19:45 UTC, abhvsn reviewed
Put some minor comments, but looks good to be merged after minor refactor

2021-09-06 04:44 UTC, AnaghHegde commented on app/server/appsmith-server/src/test/java/com/appsmith/server/services/GitServiceTest.java
> +                .assertNext(userData -> {
thats a good idea. I didnt think of that. I will make this change.

2021-09-06 06:38 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/GitServiceImpl.java
> +                .flatMap(user -> userService.findByEmail(user.getEmail()))
I did try with that but `userId` was null and later found that this is how it is used in `UserDataService` class.

2021-09-06 09:10 UTC, AnaghHegde commented
@abhvsn Ready for review. I have changed the implementation as per our latest discussion.
1. `UserData` object will contains the default/global config data and this will copied to every new application created
2.  If the user intends to edit these he/she can edit it at the application level and changes are applicable to that application object only.
3. If the user edits the default config values then the existing application config objects will not be updated.

2021-09-06 09:24 UTC, abhvsn submitted a review, later dismissed
LGTM 

There are some unnecessary imports because of earlier code please remove this in the next PR: 
UserDataService.java => GitConfig
CustomUserDataRepositoryImpl.java => Criteria, Query, GitConfig
UserDataServiceImpl.java => GitConfig
UserData.java => Map

2021-09-06 09:41 UTC, abhvsn submitted a review, later dismissed

2021-09-06 12:58 UTC, abhvsn approved these changes

2021-09-06 14:20 UTC, merged