Fix : checkbox group feedback
appsmithorg/appsmith pull request #6959
Opened 2021-08-30 09:23 UTC by wmdev0808

## Description
- Add default border for a checkbox icon and color for a label
- Align the option to the center if its options count is one or inline
- Set isInline to true by default in widget config

Fixes #6783 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Test A
- Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-09-01 08:10 UTC, somangshu requested changes
Everything looks good apart from the inline prop being true by default. Requested changes as above

2021-09-01 08:10 UTC, somangshu commented on app/client/src/mockResponses/WidgetConfigResponse.tsx
> +      isInline: true,
Old apps need migration for this, The new widgets have inline true by default

2021-09-01 08:10 UTC, somangshu commented on app/client/src/mockResponses/WidgetConfigResponse.tsx
> +      rows: 1 * GRID_DENSITY_MIGRATION_V1,
We did not need to change this, Only inline needs to be enabled and the default size should not show scroll. 

If there is a problem in writing migration for this, please revert to old value

2021-09-01 09:44 UTC, somangshu commented on app/client/src/mockResponses/WidgetConfigResponse.tsx
> +      rows: 1 * GRID_DENSITY_MIGRATION_V1,
My bad, Since this cant be migrated, the widget from old apps will only have `inline` true and the widget boundaries / size will remain as it is, For the new widget the above change made by @wmdev0808 will work 👍

2021-09-03 07:00 UTC, marks0351 submitted a review, later dismissed

2021-09-03 07:03 UTC, marks0351 commented
@wmdev0808 the default checkbox group when dragged and dropped doesn't look good. pls check.

2021-09-06 05:06 UTC, marks0351 requested changes

2021-09-06 05:06 UTC, marks0351 commented on app/client/src/utils/WidgetPropsUtils.tsx
>      currentDSL.version = LATEST_PAGE_VERSION;
pls change this to 34

2021-09-06 05:08 UTC, marks0351 commented
@wmdev0808 @somangshu when I drop a new checkbox group i see two entries, the third one is hidden coz of space constraint. pls check if that is acceptable.

2021-09-06 05:47 UTC, somangshu commented
@marks0351 on first D&D I see it like this 👇 

![Screenshot 2021-09-06 at 11 16 45 AM](https://user-images.githubusercontent.com/11089579/132166759-ff1e3ff1-9e5c-428d-8353-ffee088cd07e.png)

Can you please share what issue you are seeing?

2021-09-06 05:52 UTC, marks0351 commented
<img width="532" alt="cbgrp" src="https://user-images.githubusercontent.com/35134347/132167087-f2c04e47-a36d-4f98-a931-1f2b111b5bdc.png">
this is how it looks for me. when i decrease zoom percentage to 90% i can see all three options.

2021-09-06 14:55 UTC, somangshu commented
@wmdev0808 can you look into this, See if we can reproduce it

2021-09-06 14:56 UTC, somangshu commented
@vivekverma2312 @YogeshJayaseelan can you guys help us verify the problem here

2021-09-06 15:46 UTC, wmdev0808 commented
> @wmdev0808 can you look into this, See if we can reproduce it

Hi @somangshu , I've confirmed with @marks0351 and then made appropriate changes on this PR

2021-09-07 06:41 UTC, marks0351 commented on app/client/src/utils/WidgetPropsUtils.tsx
>      currentDSL.version = LATEST_PAGE_VERSION;
```suggestion
    currentDSL.version = 36;
```

2021-09-07 06:42 UTC, marks0351 requested changes

2021-09-07 06:42 UTC, marks0351 commented on app/client/src/utils/WidgetPropsUtils.tsx
>      currentDSL.version = LATEST_PAGE_VERSION;
```suggestion
    currentDSL.version = 36;
```

2021-09-07 11:56 UTC, marks0351 submitted a review, later dismissed

2021-09-13 10:40 UTC, YogeshJayaseelan commented
@wmdev0808 Verified this PR. Now By default the inline option is enabled and for the D&D the widget looks like below,

<img width="477" alt="Screenshot 2021-09-13 at 4 08 37 PM" src="https://user-images.githubusercontent.com/35128442/133069787-2b96f79d-7472-4e62-9f31-faa00d6d2ceb.png">

and the option is center alined when only one option is available

2021-09-16 06:57 UTC, marks0351 approved these changes

2021-09-20 06:38 UTC, somangshu commented
@wmdev0808 please merge the latest release here

2021-09-20 07:14 UTC, somangshu submitted a review, later dismissed

2021-09-21 05:52 UTC, somangshu commented on app/client/src/utils/DSLMigrations.ts
>      currentDSL.version = LATEST_PAGE_VERSION;
@marks0351 this should update to 38? Can you please check

2021-09-21 07:35 UTC, marks0351 requested changes

2021-09-21 07:35 UTC, marks0351 commented on app/client/src/utils/DSLMigrations.ts
>      currentDSL.version = LATEST_PAGE_VERSION;
this looks fine.

2021-09-21 07:35 UTC, marks0351 commented on app/client/src/widgets/CheckboxGroupWidget/component/index.tsx
> +// import { StyledCheckbox } from "widgets/CheckboxWidget/component";
remove unwanted comments

2021-09-21 07:36 UTC, marks0351 requested changes

2021-09-21 07:36 UTC, marks0351 commented on app/client/src/utils/migrations/CheckboxGroupWidget.ts
> +        child.isInline = true;
pls update widget version which wud make it easy to reverse migrate.

2021-09-21 10:36 UTC, marks0351 approved these changes

2021-11-03 19:18 UTC, wmdev0808 commented
/ok-to-test sha=77beb0b

2021-11-03 19:19 UTC, wmdev0808 commented
https://github.com/appsmithorg/appsmith/actions/runs/1418332469

2021-11-12 04:53 UTC, marks0351 requested changes

2021-11-12 04:53 UTC, marks0351 commented on app/client/src/utils/DSLMigrations.ts
>      currentDSL.version = LATEST_PAGE_VERSION;
pls change this to 44.

2021-11-12 04:54 UTC, marks0351 commented
@wmdev0808 pls resolve conflicts.

2021-11-12 05:36 UTC, marks0351 commented on app/client/src/utils/DSLMigrations.ts
>      currentDSL.version = LATEST_PAGE_VERSION;
@wmdev0808 pls fix this.

2021-11-15 05:09 UTC, marks0351 approved these changes

2021-11-17 16:08 UTC, wmdev0808 commented
/ok-to-test sha=cebfd17

2021-11-19 06:58 UTC, somangshu commented
@wmdev0808 related tests failing here, Please check

2021-11-19 09:10 UTC, wmdev0808 commented
/ok-to-test sha=530f209

2021-11-23 16:22 UTC, wmdev0808 commented
/ok-to-test sha=75f93d0

2021-11-26 04:41 UTC, marks0351 submitted a review, later dismissed

2021-11-30 07:13 UTC, shwetha-ramesh commented
@wmdev0808 tested this on DP
Feedback 2 & 3 are working as expected.

However Feedback 1 - **"The design of the checkbox doesn't match the Figma designs."**
1) The document shows a darker grey border for a checkbox icon whereas in DP the checkbox icon is a lighter version.
2) Also on Windows OS the drag and drop of a checkbox group only two options are showed and for the third option user needs to scroll (as observed in the video)
![image](https://user-images.githubusercontent.com/92293815/144002056-1c1593ad-1b11-42a0-8426-cfff996dedbd.png)

https://loom.com/share/736088d07eb043bab72c34c982421db5

For a better comparison I have attached the screenshot on all three platforms notice at the moment.
![image](https://user-images.githubusercontent.com/92293815/144001976-bbe11f7c-5f60-4a51-85a2-2285df58d0db.png)

2021-11-30 22:06 UTC, wmdev0808 commented
> 2\. Also on Windows OS the drag and drop of a checkbox group only two options are showed and for the third option user needs to scroll (as observed in the video)

@shwetha-ramesh , I noticed you found this issue on Fluid mode.
In that mode, all the widgets' sizes are decreased, that's why having scrollbar is normal behavior.
I think you can ignore this.

2021-11-30 22:28 UTC, wmdev0808 commented
/ok-to-test sha=5a4fe12

2021-12-02 06:58 UTC, marks0351 submitted a review, later dismissed

2021-12-02 10:16 UTC, shwetha-ramesh commented
@wmdev0808 retested this PR. 
There is still a mismatch of color from [figma](https://www.figma.com/file/u0IE1Vqr2MKcQcQKCpHO4O/Checkbox-Group-Widget?node-id=2%3A3) to DP. As seen in below image in DP the checkbox has a light grey outline inside which is not noticed in figma.

![image](https://user-images.githubusercontent.com/92293815/144402445-ddda6317-f0f0-4716-bc78-df5f501ab5ae.png)

2021-12-02 12:15 UTC, wmdev0808 commented
/ok-to-test sha=58d52d1

2021-12-03 07:21 UTC, marks0351 approved these changes

2021-12-06 06:15 UTC, shwetha-ramesh commented
@wmdev0808 working as expected. Moving to DONE.

2021-12-09 10:19 UTC, wmdev0808 commented
/ok-to-test sha=e6b0e5f

2021-12-09 10:26 UTC, wmdev0808 commented
/ok-to-test sha=1babf6c

2021-12-15 10:33 UTC, wmdev0808 commented
/ok-to-test sha=98effe5

2021-12-15 10:33 UTC, somangshu approved these changes

2021-12-16 09:59 UTC, wmdev0808 commented
/ok-to-test sha=5f9348f

2021-12-16 14:24 UTC, merged