fix: caret color light theme
appsmithorg/appsmith pull request #6973
Opened 2021-08-30 13:38 UTC by rishabhsaxena

## Description

Fixes #6969

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- manually

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-08-31 05:16 UTC, Rishabh-Rathod approved these changes

2021-08-31 05:17 UTC, ramsaptami approved these changes
Verified and tested ok

2021-08-31 05:50 UTC, Rishabh-Rathod requested changes
~This leads to the issue #6969~

2021-09-01 05:43 UTC, Rishabh-Rathod approved these changes

2021-09-01 08:54 UTC, merged