chore: Minor refactoring changes for RTS
appsmithorg/appsmith pull request #7011
Opened 2021-08-31 12:52 UTC by mohanarpit

## Description

* Adding logLevel library to RTS. Helps us control the logging level for RTS in different environments. 
* Moving the session login check to `/users/me` API instead of the data heavy `/applications/new`
* Removing the information about express header. This is a security loophole.

## Type of change

Chore PR

## How Has This Been Tested?

Manual

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-08-31 13:06 UTC, nayan-rafiq requested changes

2021-08-31 13:06 UTC, nayan-rafiq commented on app/rts/src/server.ts
> +					url: API_BASE_URL + "/users/me",
If we use `/users/me` to authenticate, we need to check the response to make sure user is not anonymous when a successful response is received. I think we should use `/users/me` because that makes more sense and the response size is much smaller than `/applications/new`

2021-08-31 13:09 UTC, mohanarpit commented on app/rts/src/server.ts
> +					url: API_BASE_URL + "/users/me",
Sorry, my bad. I'll make that change.

2021-08-31 13:28 UTC, nayan-rafiq submitted a review, later dismissed

2021-09-01 15:01 UTC, nayan-rafiq approved these changes

2021-09-02 03:17 UTC, merged