fix: empty form data in API pane
appsmithorg/appsmith pull request #7019
Opened 2021-09-01 08:17 UTC by arunvjn

## Description
Removes empty key value pair from headers, query parameters and form data thereby avoid execution failures from this.

Fixes #5756 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-09-02 07:48 UTC, ApekshaBhosale requested changes

2021-09-02 07:48 UTC, ApekshaBhosale commented on app/client/src/transformers/RestActionTransformer.ts
> +import _, { isEmpty } from "lodash";
remove _ or remove isEmpty, _ has already isEmpty

2021-09-02 10:46 UTC, arunvjn commented on app/client/src/transformers/RestActionTransformer.ts
> +import _, { isEmpty } from "lodash";
Done

2021-09-02 12:15 UTC, arunvjn commented on app/client/src/transformers/RestActionTransformer.ts
> +    (data: any) => !_.isEmpty(data.key) || !_.isEmpty(data.value),
In a scenario where the user fills in the 'key' and navigates away from the page to look up a widget from where needs the data, he might loose the entry he has made against the key property.

2021-09-03 10:29 UTC, hetunandu approved these changes

2021-09-03 11:07 UTC, ApekshaBhosale approved these changes

2021-09-03 11:43 UTC, merged