Feature/json view widget
appsmithorg/appsmith pull request #7030
Opened 2021-09-01 11:39 UTC by asmiller

## Description

Adds a read-only JSON view widget. Uses the same `json-view` component as the query editor, so no external dependencies were added, and it should match existing Appsmith styles.

This component is particularly useful for NoSQL data sources like MongoDB, where collections tend to have nested properties that are not easy to read in the default table view. It can also be used to view a single record in detail, without having to print out every key and value into separate labels.

It works both individual objects and arrays as inputs

## Type of change

- New feature (non-breaking change which adds functionality)
- 
## How Has This Been Tested?

I ran the client locally, while pointed at the Appsmith remote server. I added the component, saved / reloaded, and changed the configurations.
This was my first time in the Appsmith codebase, so I'm not 100% positive that I did the property validation correctly.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-09-01 12:42 UTC, somangshu commented
@asmiller please clear out the merge conflicts

2021-09-01 12:43 UTC, asmiller commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Comments/AddComments_spec.js
> -      console.log("Error loading database", event);
I had to comment these out for the commit hooks to pass...

2021-09-01 12:45 UTC, asmiller commented on app/client/src/pages/Editor/QueryEditor/JSONViewer.tsx
> +    const { collapsed = 1, src } = this.props;
Not sure how you feel about adding some additional properties to the `JSONViewer.tsx` component?

We could also use `react-json-view` directly... but the styling wouldn't match.

2021-09-01 12:46 UTC, asmiller commented on app/client/src/utils/WidgetRegistry.tsx
> +      JsonViewWidget.getPropertyValidationMap(),
Somewhat confused by WidgetFactory - some of these might be unnecessary

2021-09-01 12:46 UTC, asmiller commented on app/client/src/utils/autocomplete/EntityDefinitions.ts
> +    "!url": "https://docs.appsmith.com/widget-reference/jsonview",
TODO
or should we jsut remove it?

2021-09-01 13:49 UTC, somangshu commented
Hi @asmiller, This is a widget which we have already picked up for implementation and right now @wmdev0808 is working towards this. Our scope might not fit in with the library you have used for the widget implementation. We will look into this and get back to you. However in the meantime, let me know if you would be interested in some other widget implementation, I could assign you one from our backlog

2021-09-01 15:58 UTC, asmiller commented
> Hi @asmiller, This is a widget which we have already picked up for implementation in #3360 and right now @wmdev0808 is working towards this. Our scope might not fit in with the library you have used for the widget implementation. We will look into this and get back to you. However in the meantime, let me know if you would be interested in some other widget implementation, I could assign you one from our backlog
> 
> cc @riodeuno

From what I could tell #3360 was about an _editor_ - which is a more complex (and dangerous) component for most business circumstances. 
This PR reuses the JSON components designed the "Database Preview" page, so it doesn't add any new libraries to the project.

@wmdev0808 it should actually be pretty simple to add an "Editable" toggle to this - if you pass a function `onEdit` into the JSONView component like I did for `collapsed`, you can enable the edit functions of the `react-json-view`

https://www.npmjs.com/package/react-json-view

2021-09-02 05:42 UTC, marks0351 commented on app/client/src/widgets/JsonView.tsx
> +    debugger;
pls remove debugger

2021-09-02 05:44 UTC, marks0351 commented on app/server/yarn.lock
> +# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
lets remove this file from the commit.

2021-09-02 05:57 UTC, marks0351 commented on app/client/src/widgets/JsonView.tsx
> +            propertyName: "source",
we need to add validation for JSON data just like for collapsed input.
we don't have a validation already written for JSON types but you can check 
https://github.com/appsmithorg/appsmith/blob/release/app/client/src/workers/validations.ts#L550
https://github.com/appsmithorg/appsmith/blob/release/app/client/src/workers/validations.ts#L459
combining these validations can help you build validation for a JSON.

2021-09-02 05:58 UTC, marks0351 commented on app/client/src/widgets/JsonView.tsx
> +            validation: { type: ValidationTypes.TEXT },
validation: { type: ValidationTypes.TEXT } should be changed to { type: ValidationTypes.NUMBER }

2021-09-02 06:01 UTC, marks0351 commented on app/client/src/widgets/JsonView.tsx
> +    return <JSONViewer collapsed={this.props.collapsed} src={displayData} />;
the widget doesn't occupy the entire space within the widget boundary by default. Need to adjust css or add a wrapping div to occupy entire space and scroll within that div.
<img width="782" alt="jsonview" src="https://user-images.githubusercontent.com/35134347/131790135-8f1757f4-55da-4367-bb45-3f729da14d8d.png">

2021-09-02 06:03 UTC, marks0351 commented on app/client/src/widgets/JsonView.tsx
> +    }
you can also use this code block to write a validation for JSON type. once you have written that you will not be needing this code block. this.props.source will have proper parsed value.

2021-09-02 06:04 UTC, marks0351 commented on app/client/src/widgets/JsonView.tsx
> +    return "JSON_VIEW_WIDGET";
```suggestion
    return WidgetTypes.JSON_VIEW_WIDGET;
```

2021-09-02 06:13 UTC, marks0351 requested changes
Great work @asmiller !!! Thanks for the contribution.

I have added a few comments for your PR.
pls do address them.
Let me know if you need a discussion around the requested changes.

2021-09-02 08:12 UTC, wmdev0808 commented
> > Hi @asmiller, This is a widget which we have already picked up for implementation in #3360 and right now @wmdev0808 is working towards this. Our scope might not fit in with the library you have used for the widget implementation. We will look into this and get back to you. However in the meantime, let me know if you would be interested in some other widget implementation, I could assign you one from our backlog
> > cc @riodeuno
> 
> From what I could tell #3360 was about an _editor_ - which is a more complex (and dangerous) component for most business circumstances.
> This PR reuses the JSON components designed the "Database Preview" page, so it doesn't add any new libraries to the project.
> 
> @wmdev0808 it should actually be pretty simple to add an "Editable" toggle to this - if you pass a function `onEdit` into the JSONView component like I did for `collapsed`, you can enable the edit functions of the `react-json-view`
> 
> https://www.npmjs.com/package/react-json-view

@asmiller and @marks0351:
- First, @asmiller, thank you very much for your care.
- Second, of course `react-json-view` can easily be integrated into #3360 , but I am going to choose `jsoneditor` for its full-features and future scalability.

Hope to hear from you guys soon
Thank you again

2021-09-02 09:35 UTC, somangshu commented
We want to use the `jsoneditor` package which provides a very similar implementation to https://jsoneditoronline.org, The problem right now is that this particular package does not support typescript, We need to understand if our implementation scope can complete going forward with this package. 

We need to find out any other equivalent packages which provide such functionality or if there is a better way to move ahead.

cc: @marks0351 @asmiller

2021-09-03 10:40 UTC, riodeuno requested changes
I'm super excited for this sparkling new widget to come into the Appsmith ecosystem! This is really impactful.

2021-09-03 10:40 UTC, riodeuno commented on app/client/src/pages/Editor/QueryEditor/JSONViewer.tsx
> +    const { collapsed = 1, src } = this.props;
@asmiller I agree with you. We would ideally like the widgets to be separate from the platform, so that they can be maintained and updated independently according to the UI and UX. 
As a result, I would suggest just using `react-json-view` directly in the JsonViewer widget's component.

2021-09-03 10:40 UTC, riodeuno commented on app/client/src/pages/Editor/QueryEditor/JSONViewer.tsx
> +    const { collapsed = 1, src } = this.props;
We're also compartmentalising widget development in their respective folders in this PR #6405 . This will make sure that we don't have to update so many files for the widgets.

2021-09-03 10:40 UTC, riodeuno commented on app/client/src/utils/autocomplete/EntityDefinitions.ts
> +    "!url": "https://docs.appsmith.com/widget-reference/jsonview",
@somangshu Could we help out here?

2021-09-03 10:40 UTC, riodeuno commented on app/client/src/widgets/JsonView.tsx
> +    return "JSON_VIEW_WIDGET";
@asmiller @marks0351 I would suggest leaving this as is. Please refer to #6405 This is needed to decouple widgets from the platform.

2021-09-03 10:49 UTC, riodeuno commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Comments/AddComments_spec.js
> -      console.log("Error loading database", event);
😅 Sorry about that, we had made console.logs in the codebase illegal recently. These must have escaped the checks in the code setup we use. We should remove them.

2021-09-03 11:03 UTC, riodeuno commented on app/client/src/utils/WidgetRegistry.tsx
> +      JsonViewWidget.getPropertyValidationMap(),
@asmiller This is correct. We can remove `JsonViewWidget.getTriggerPropertyMap()`, as they're not used anymore.

2021-09-04 06:44 UTC, somangshu commented
@asmiller @riodeuno I have linked a new issue here, This can be a separate widget and go in

2021-09-19 18:16 UTC, mohanarpit commented
Reopening this PR so that we can take a decision how we will merge this widget into our main branch.

2021-09-20 09:51 UTC, somangshu commented
@mohanarpit we also have #7087 being worked on. Suggest we drop this

2021-09-20 09:57 UTC, mohanarpit commented
Closing in favour of #7087

2021-09-20 09:57 UTC, closed without merging