Fix: Table widget migration to sanitize keys and binding paths
appsmithorg/appsmith pull request #7037
Opened 2021-09-01 17:32 UTC by ashit-rath

## Description
This PR adds a new migration to mitigate the issue due to bad merge in CE and EE which resulted into inconsistent table widget dsl where the the table keys were not sanitized properly.

Fixes #6897

#### Steps to reproduce.
>To reproduce this, local environment setup is required
1. Checkout to the `master` branch
2. Create a new application
3. Add a table widget
4. Add some datasource (eg. users)
5. Open table widget property pane and add the following to the data property 
   ```
    {{users.data.concat({ "'new header": 100})}}
   ```
6. Export the application
7. Checkout to release branch
8. Import the application

After importing the application should ideally crash.

#### Reason for the crash - 
Background - Due to some recent bad merge from release to master, certain pieces of code got reverted. CE master has the bad code but release has the appropriate changes.

Now when the application is exported while being on the `master` branch, the bad dsl (due to bad code) goes out and the dsl is on the latest version (migration wise).  When this code is imported while being on the `release` branch, the code sees that the dsl is on the latest migration version, it does not try to fix the issue present on the dsl (even though previous migration can somewhat fix the dsl). The bad un-sanitized DSL goes in and crashes the application.

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Manual

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-09-02 05:31 UTC, ashit-rath commented on app/client/src/utils/migrations/TableWidget.ts
> +      child.dynamicBindingPathList = (child.dynamicBindingPathList || []).map(
I am bit concerned about this block of code. If the DSL runs from old migration i.e before 27 then the `primaryColumn` keys would already be sanitized and `primaryColumnKeyTuples` wouldn't have any entries
Check -> https://github.com/appsmithorg/appsmith/pull/7037/files#diff-3381042113ebd91605a3f90f24317750e0433d3408fe8717b036ae612c8c7f27R342

Basically for `primaryColumns.$$$random_header.computedValue` we need to sanitize `$$$random_header`.  We cannot split the string using `split('.')` and apply sanitization on the index[1] as the the bad key could be something like `.random_header` and that would lead to `primaryColumns..random_header.computedValue` and would break the code.

We could grab everything in between `primaryColumns` and `computedValue` and sanitize but I'm not sure if the path would always have the same pattern or may change.

@riodeuno Please advice.

2021-09-02 05:50 UTC, somangshu approved these changes
Approving to run the tests

2021-09-02 07:08 UTC, ashit-rath commented
Note: This issue can now only be reproduced on master on commit: `6754cc01d2e54db072cc8f181895a9775aa09f5e`. Latest master has code discrepancy fixes.

2021-09-03 08:11 UTC, riodeuno commented on app/client/src/utils/migrations/TableWidget.ts
> +      child.dynamicBindingPathList = (child.dynamicBindingPathList || []).map(
@ashit-rath You're right, when sanitisations were happening with `\W+`, we could be certain that `primaryColumns..random_header.computedvalue` could not be the case. However, now that we've used `/\s+` we might see these scenarios as we've seen users using keys in their data like `Employee.id` which would make this `primaryColumns.Employee.id.computedValue`. 

For now, we can assume that `primaryColumns.xxxx.yyyy`, where xxxx is the pattern which we will need to sanitize.

2021-09-03 08:14 UTC, riodeuno commented on app/client/src/utils/migrations/TableWidget.test.ts
> +            { key: "primaryColumns.'random_header.computedValue" },
Let's add another unit test to test the `primaryColumns.Employee.id.computedValue` scenario.

2021-09-03 08:15 UTC, riodeuno requested changes
Nice work considering all the scenarios. Please add that one more test case. The rest looks good.

2021-09-03 10:37 UTC, somangshu submitted a review, later dismissed
Approving for the tests to run

2021-09-06 14:33 UTC, somangshu commented
@riodeuno please look into this, This should get merged into release soon.

2021-09-08 07:24 UTC, riodeuno approved these changes

2021-09-08 09:58 UTC, somangshu submitted a review, later dismissed

2021-09-08 11:38 UTC, ashit-rath commented
@vivekverma2312 You can now test the DP

2021-09-10 07:24 UTC, riodeuno commented on app/client/src/utils/WidgetPropsUtils.tsx
> -const updateContainers = (dsl: ContainerWidgetProps<WidgetProps>) => {
This diff should not show up here, as the `release` branch already has these changes. Any idea about what happened here?

2021-09-10 07:25 UTC, riodeuno commented on app/client/src/utils/helpers.test.ts
> +describe("#getSubstringBetweenTwoWords", () => {
Beautiful! This is how we should validate our functions.

2021-09-10 07:25 UTC, riodeuno commented on app/client/src/utils/helpers.tsx
> + * eg ->
Another nice detail. These function comments will help in the long run.

2021-09-10 07:33 UTC, riodeuno commented on app/client/src/utils/migrations/TableWidget.ts
> + * columnOrder
💯

2021-09-10 07:33 UTC, riodeuno approved these changes

2021-09-13 12:00 UTC, vivekverma2312 commented
Tested on Deploy Preview and working fine.

2021-09-13 12:03 UTC, merged