Feat/menu button as column type
appsmithorg/appsmith pull request #7039
Opened 2021-09-01 20:50 UTC by Tooluloope

## Description
Add menu Button as a Column type
Fixes #5636  (issue)

## Type of change
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-09-02 03:21 UTC, mohanarpit commented on app/client/src/entities/Widget/utils.ts
> +                            // Having an extra layer of config
Request to please add comments in this function explaining what all these conditions are for. From just the code, I couldn't understand the flow at all. Hence, requesting for code comments here.

2021-09-03 09:32 UTC, riodeuno requested changes
@Tooluloope Nice work! The new menu button type will be quite useful.

A few things to keep in mind - I believe you are, but adding here just for future reference - about the Table Widget code.
- As the TableWidget changes can have cascading effects across the feature, we need to be cognisant of any side-effects of our code.
- We need to keep in mind the data flow across the table widget, as there will be scenarios where we have `undefined` values, and referring to an `undefined` object property can lead to a crash.
- Widgets should be standalone, it is needed for the long term decoupling of the platform from the widgets.

2021-09-03 09:32 UTC, riodeuno commented on app/client/src/entities/Widget/utils.ts
> +/**
@hetunandu Please review the changes in the file, and let us know if this will effect any computations in validations and/or evaluations.

2021-09-03 09:32 UTC, riodeuno commented on app/client/src/entities/Widget/utils.ts
> +/**
For context, we've made this change to allow for bindings with deeper nesting. `primaryColumns.xxx.xxx.xxx.xxx`

2021-09-03 09:32 UTC, riodeuno commented on app/client/src/widgets/TableWidget/TablePropertyPaneConfig.ts
> +                  ) => {
Please move this to a named function. A description of what it does will be helpful in code maintenance.

2021-09-03 09:32 UTC, riodeuno commented on app/client/src/widgets/TableWidget/TablePropertyPaneConfig.ts
> +                    const property = getBasePropertyPath(propertyPath);
Same as above comment.

2021-09-03 09:32 UTC, riodeuno commented on app/client/src/widgets/TableWidget/TablePropertyPaneConfig.ts
> +                              let propertiesToUpdate = [
same as the above comment.

2021-09-03 09:32 UTC, riodeuno commented on app/client/src/widgets/TableWidget/index.tsx
> +          } else if (columnProperties.columnType === "menuButton") {
Let's move this getTableColumns function to a separate file. We should also add comment annotations to the code. This will help us in maintaining the table widget code.

2021-09-08 10:15 UTC, riodeuno requested changes
The code is now compartmentalised well. Thanks for the updates!

2021-09-08 10:15 UTC, riodeuno commented on app/client/src/widgets/TableWidget/TablePropertyPaneConfig.ts
> +                  updateHook: function updateHook(
Let's make this into a separate hook function. It makes it difficult to read the property config if we have this here. A simple comment here in the property config, about what the hook does would be best.

2021-09-08 10:15 UTC, riodeuno commented on app/client/src/widgets/TableWidget/getTableColumns.tsx
> +export const getPropertyValue = (
Nice! This should have shaved off a good 100 lines from the TableWidget code.

2021-09-08 10:17 UTC, riodeuno commented on app/client/src/entities/Widget/utils.ts
> +/**
@Tooluloope According to @hetunandu as long as we set the `bindingPath` for the properties correctly, it would work fine, irrespective the path depth.

2021-09-16 07:16 UTC, rahulramesha requested changes

2021-09-16 07:16 UTC, rahulramesha commented on app/client/src/widgets/TableWidget/component/components/menuButtonTableComponent.tsx
> +        <BaseMenuItem
nit-pick: Since both the Components look similar, i feel it will look better if we just conditionally modify the props as an object, rather than returning two similar react nodes.

2021-09-16 07:16 UTC, rahulramesha commented on app/client/src/widgets/TableWidget/component/components/menuButtonTableComponent.tsx
> +      <BaseButton
nit-pick: same here for returning two similiar react Nodes

2021-09-16 07:16 UTC, rahulramesha commented on app/client/src/widgets/TableWidget/widget/getTableColumns.tsx
> +  return {
null check missing on `columnProperties`

2021-09-20 07:26 UTC, Tooluloope commented on app/client/src/widgets/TableWidget/component/components/menuButtonTableComponent.tsx
> +        buttonStyle === ButtonStyleTypes.WARNING
Nope, switch statement won't be ideal.
cos of the different conditions needed to ascertain the colors

2021-09-20 14:29 UTC, rahulramesha approved these changes

2021-09-21 06:12 UTC, rahulramesha submitted a review, later dismissed

2021-09-22 06:16 UTC, riodeuno commented on app/client/src/AppRouter.tsx
> +      this.props;
There are a lot of changes which seems to be due to changes in the prettier or eslint config. Probably the characters per line.

2021-09-27 09:26 UTC, YogeshJayaseelan commented
@Tooluloope Verified this PR and please find the issues below - Testing in-progress will update further 

1.Disabled , Visible and Compact toggle should be displayed one by one 

<img width="1680" alt="Screenshot 2021-09-27 at 11 49 32 AM" src="https://user-images.githubusercontent.com/35128442/134854804-556166ff-9cff-4e92-8f02-cf6733bee313.png">

2.Sub menu's are overlapping with the table rows and columns

<img width="1680" alt="Screenshot 2021-09-27 at 11 52 11 AM" src="https://user-images.githubusercontent.com/35128442/134854950-740e4beb-e472-4d84-b8e4-b2da586e61ec.png">

2021-09-27 10:37 UTC, Tooluloope commented
@YogeshJayaseelan No.2 requires you to set a background color for the Menu buttons. It's currently on transparent thats why it looks like they overlap

2021-09-28 12:21 UTC, riodeuno submitted a review, later dismissed
Approving for tests

2021-09-28 12:40 UTC, SatishGandham submitted a review, later dismissed
Approving for tests

2021-09-29 10:56 UTC, YogeshJayaseelan commented
@Tooluloope Verified the fix for the issue 1 and it is working fine now.

Please find the additional issues below,

2. Re-open - By default the sub menu's are transparent - There needs to be default colour for the sub menu items

3. The order of items in property pane of Menu Button slightly differs with the Menu button column - The order of items in property pane should match 

**Menu Button:**
* Label
* Menu Item
     Menu 1
     Menu 2
     Menu 3
* Visible Toggle
* Disable Toggle 
* Compact Toggle
* Styles
       Menu Style 
       Menu Variant 
       Border Radius
       Box Shadow
       Shadow Colour
* Icon
* Icon Alignment 

Menu Button Column
* Visible Toggle
* Disabled Toggle
* Compact Toggle
* Button Properties 
        Icon
        Icon Alignment
*Label
*Menu Colour
*Menu Variant 
*Border Radius
*Box Shadow
*Shadow Colour 
* Menu Items
     Menu 1
     Menu 2
     Menu 3

4.By default the Menu Button column looks like disabled - This is due to Default menu colour is not set

<img width="1680" alt="Screenshot 2021-09-29 at 4 00 29 PM" src="https://user-images.githubusercontent.com/35128442/135252010-a6267673-6640-43b5-91e8-e74552f0186d.png">

5.By default the label field - Evaluated value is undefined 

<img width="1680" alt="Screenshot 2021-09-29 at 4 26 03 PM" src="https://user-images.githubusercontent.com/35128442/135255558-68d3c182-b1c4-4490-acce-d33703b1e1ab.png">

2021-10-01 09:17 UTC, YogeshJayaseelan commented
@Tooluloope Verified the fixes for issues 2,4,5 and they are working as expected 

New issues:

6) By Default the Menu button column's colour is 'Not Selected' and it should be Green - #03B365

<img width="1680" alt="Screenshot 2021-10-01 at 2 40 07 PM" src="https://user-images.githubusercontent.com/35128442/135596118-c43688a0-4de6-4279-9ca0-98aa6379f24d.png">

7) Can we rename the Menu Button Column Default label to 'Open Menu' instead of Action. Currently Both Button and Menu Button shows the Label name as 'Action'

<img width="1680" alt="Screenshot 2021-10-01 at 2 41 39 PM" src="https://user-images.githubusercontent.com/35128442/135596299-a3ea9b68-03cb-43fe-8156-a7b9152724de.png">

2021-10-01 10:12 UTC, Tooluloope commented
@YogeshJayaseelan 
Issue 3. This isn't an issue, We're making the table widget property pane consistent.
issue 6 and 7 have been fixed

2021-10-04 04:49 UTC, YogeshJayaseelan commented
@Tooluloope Verified all the issues and they are working as expected. we can proceed further

2021-10-04 13:39 UTC, aswathkk approved these changes
Approving to run tests

2021-10-05 10:29 UTC, rahulramesha approved these changes
Approving for tests

2021-10-06 12:57 UTC, merged