Feature/infinite scroll table
appsmithorg/appsmith pull request #7047
Opened 2021-09-02 07:50 UTC by vicky-primathon

## Description
Allow table to scroll infinite when infinite scroll property is enabled

Fixes #2896 

## Type of change
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-09-08 10:11 UTC, riodeuno requested changes

2021-09-08 10:11 UTC, riodeuno commented on app/client/src/widgets/TableWidget/TablePropertyPaneConfig.ts
> +          "Allow table to have infinite scroll, bind the Table.pageNo property in your API and call it onPageChange",
Let's change the text to :
Allow Table  to scroll infinitely.  Scrolling to a different page will trigger `onPageChange` and update the `pageNo` property.

2021-09-08 10:11 UTC, riodeuno commented on app/client/src/components/designSystems/appsmith/TableComponent/TableHeader.tsx
> +              onClick={() => {
Can we use `useCallback` here?

2021-09-08 10:11 UTC, riodeuno commented on app/client/src/components/designSystems/appsmith/TableComponent/TableHeader.tsx
> +          <PaginationWrapper>
Let's make this into a different component. 
Let's put the condition here into a different variable. 
This is for cleaner code.

2021-09-09 10:13 UTC, SatishGandham commented on app/client/src/components/designSystems/appsmith/TableComponent/index.tsx
> +    prev.infiniteScroll === next.infiniteScroll &&
@riodeuno with optimisations to how we update the redux store, this custom equality check is no longer required. Should we get rid of it in this PR?

2021-09-09 10:15 UTC, riodeuno commented on app/client/src/components/designSystems/appsmith/TableComponent/index.tsx
> +    prev.infiniteScroll === next.infiniteScroll &&
@SatishGandham Let's do this in a separate PR. This will keep the context of the PR and the changes mapped correctly.

2021-09-09 10:17 UTC, riodeuno submitted a review, later dismissed

2021-09-13 05:01 UTC, riodeuno approved these changes

2021-09-16 09:44 UTC, riodeuno commented
@vicky-primathon we have a failing test here. Can we look into this?

2021-09-17 04:24 UTC, vicky-primathon commented
> @vicky-primathon we have a failing test here. Can we look into this?

Failing test on re-running test pipelines

2021-10-05 11:29 UTC, somangshu commented
Feedback: 
- When this is enabled, the filter and download option should be right aligned (where page control existed) > 
![Screenshot 2021-10-05 at 4 31 54 PM](https://user-images.githubusercontent.com/11089579/136012096-bb2f755b-b22a-4874-94a4-ef862033d9bd.png)
- There is a wired behaviour while scrolling the table view this specifically happens when the onPageChange is not set
- the loading state is very confusing @momcilo-appsmith 
- Should we have the items in the next page load as a threshold, Right now, the smallest scroll, Loads more data, And the data on top is also gone, This is not such a great UX, While going down some items should already be loaded, On reaching the threshold (number of items available underneath) the more data should append, And scrolling upward should already have the data available (@areyabhishek @Nikhil-Nandagopal @riodeuno need your feedback here)
- Have me updated documentation for this

2021-10-07 23:32 UTC, riodeuno commented
@somangshu I agree.
- The goal of infinite scroll table to show all data in one place without having to click on pagination controls
- The `onPageChange` is usually used to fetch new data, it doesn't or shouldn't be used for actions which modify data. I don't think it would be a good practice. 
- Option 1: When scrolling to a new page, we should give it a threshold and not change the page in the smallest scroll. This makes for clear user intent. Many social media applications use this mechanism. For example the twitter refresh interaction.

- Option 2: This is the better UX. When scrolling to a new page, we trigger `onPageChange`, however, we still 'virtualize' all available data. This means the data on the page is not replaced, but appended. Allowing for a state where users are between two pages with the upper half showing data from the previous page and the lower half showing data from the current page.

The limitations of option 2 show when the `tableData` is bound to a query which utilises the `pageSize` and `pageNo`. In this scenario, the `tableData` at any point, contains data for just one page. Making option 2 work in such scenarios, is not something that can be done quickly, as we have no mechanisms for caching data at the moment. Appsmith is agnostic of how and when to cache any data. We will need to device a new feature which allows developers to make Appsmith 'aware' of what and when to cache.

2021-10-08 05:47 UTC, somangshu commented
@riodeuno I totally agree to this. 

Here is how I think we could move forward:
- I am contemplating the v2 now for this, i.e. we resolve this and other problems with the table widget and deprecate the old table over a period of time. I am assuming the infinite scrolling will change the way the widget functions
- We create a new widget, This was bought up before, as virtualisation can provide the best experience here, and in the current implementation its difficult. One suitable package I had found is [react-infinite-table](https://nicoladefranceschi.github.io/react-infinite-table/), Here we also need to make sure that all older features can be bought here, Plus what ever best we can support from the pending feature requests.
-

2022-01-25 06:27 UTC, closed without merging