Add consumption of UQI UI templates
appsmithorg/appsmith pull request #7082
Opened 2021-09-03 06:42 UTC by trishaanand

2021-09-08 10:07 UTC, nidhi-nair commented on app/server/appsmith-plugins/mongoPluginUqi/src/main/resources/editor/find.json
> +  "conditionals": {
Do we need this check here? Wouldn't we use a map to guide us to the right file ?

2021-09-08 10:08 UTC, nidhi-nair commented on app/server/appsmith-plugins/mongoPluginUqi/src/main/resources/editor/find.json
> +      "controlType": "SECTION",
Why is this a section type? Is that the new name for entity selector?

2021-09-08 10:10 UTC, nidhi-nair commented on app/server/appsmith-plugins/mongoPluginUqi/src/main/resources/editor/find.json
> +          "configProperty": "actionConfiguration.formData.findCmdForm.query",
Are you doing this to maintain different copies of values for different rendered forms? If we're re-rendering the form on the basis of json file map we might not need this. Reason to avoid this is that it will make code sharing difficult

2021-09-08 10:11 UTC, nidhi-nair commented on app/server/appsmith-plugins/mongoPluginUqi/src/main/resources/editor/find.json
> +          "controlType": "QUERY_DYNAMIC_INPUT_TEXT",
Just a `prettier` thing maybe, but can we order all these keys so it's easier to read? 😛

2021-09-08 10:18 UTC, trishaanand commented
@nidhi-nair : I would recommend ignoring the `.json` files because they were simply added for testing. I have actually deleted the entire mongo uqi plugin in the upcoming PR. Please review the final `json` files as part of that PR. In this PR, I would recommend reviewing the java code for parsing the JSON files for UQI.

2021-09-08 10:36 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/PluginServiceImpl.java
> +    public Map loadEditorPluginResourceUqi(Plugin plugin) {
Okay I apologize in advance if this comment is going to cause a major redo. But it looks like the end product of this call is result in one json object that looks pretty much the same as our older editor json with multiple section control types. Instead, can we make the end json look something like the following:
```
{
  "commands": {...},
  "templates" : {
    "FETCH": {...},
    "INSERT": {...}, ...
  },
  "commons": {...} // or whatever other field we might need here
}
```

We don't really need to programatically create a section here because this being the starting point we can configure the form to populate the form template inside a parent section. Plus keeping the templates accessible as a map keeps access time to O(1). Let me know if I misinterpretted the code here, really wild all the stuff happening here. :)

2021-09-08 10:38 UTC, nidhi-nair requested changes
Just one comment on the end json produced. Please remove the extra files and add a sample of the final json for readability if possible 😀

2021-09-09 15:37 UTC, trishaanand commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/PluginServiceImpl.java
> +    public Map loadEditorPluginResourceUqi(Plugin plugin) {
Resolving this post conversation on Slack

2021-09-09 15:39 UTC, trishaanand commented
> Just one comment on the end json produced. Please remove the extra files and add a sample of the final json for readability if possible 😀

@nidhi-nair : I have removed the test files. The sample output final json can be found here :
`https://github.com/appsmithorg/uqi-json-rules/blob/main/samples/mongo/query/output.json`

2021-09-09 16:01 UTC, nidhi-nair approved these changes

2021-09-09 16:39 UTC, merged