Feat: JSON Editor Widget
appsmithorg/appsmith pull request #7087
Opened 2021-09-03 10:13 UTC by wmdev0808

## Description
The POC of JSON Editor based on [jsoneditor](https://github.com/josdejong/jsoneditor)

Fixes #3360 

## Type of change

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

## How Has This Been Tested?

- Test A
- Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-09-08 08:05 UTC, riodeuno requested changes
@wmdev0808 Nice work with the widget! 

I have a few queries and suggestions.

2021-09-08 08:05 UTC, riodeuno commented on app/client/src/widgets/JsonEditorWidget.tsx
> +      json: undefined,
The way we're handling this, according to my understanding is as follows:
- `json` is the parsed value of `text`
- `text` is the default which is defined by the developer in the property pane.
- Since, we cannot directly use `getDefaultPropertiesMap`, we're passing the `text` value to the `JsonEditorComponent` and letting it update the `json` property here using `onChangeJson`

Here is the alternative I would suggest (mostly for consistency with other widgets)
- The property in the property pane can be called `defaultText`
- The property which is stored in the meta properties is called `jsonString`
- `jsonString` is mapped to `defaultText` using `getDefaultPropertiesMap`
- We create `parsedJSON` instead of `json` as a derivedProperty using `getDerivedPropertiesMap`

This way, we will have `defaultText`, `jsonString`, and finally `parsedJSON`. We will also be able to remove one of the `useEffect` code in `JsonEditorComponent`

2021-09-08 13:25 UTC, wmdev0808 commented on app/client/src/components/designSystems/appsmith/JsonEditorComponent.tsx
> +  onChangeJSON: (json: any) => void;
No, it is plain object parsed from JSON, not string

2021-09-08 14:03 UTC, wmdev0808 commented on app/client/src/components/designSystems/appsmith/JsonEditorComponent.tsx
> +  }, []);
No, containerRef is always available in this hook.
If statement in question is just for avoid type error because the constructor for JSON editor is only accepting valid HTMLElement

2021-09-08 14:11 UTC, wmdev0808 commented on app/client/src/components/designSystems/appsmith/JsonEditorComponent.tsx
> +        onChangeText(text);
Yes, it is necessary for update meta property, "json", which will be referenced by others.
In addition, it can't go into infinite loop, because onChangeText passed into editor object is only triggered by user action, not programmatically, such as setText

2021-09-08 14:49 UTC, wmdev0808 commented on app/client/src/components/designSystems/appsmith/JsonEditorComponent.tsx
> +  const handleCopyToClipboard = () => {
Yes, you're right. For avoiding unnecessary re-render, we should use it, thanks

2021-09-08 14:55 UTC, wmdev0808 commented on app/client/src/components/designSystems/appsmith/JsonEditorComponent.tsx
> +    const options = Object.assign({}, { modes, onChangeJSON, onChangeText });
No, you're right, thanks

2021-09-08 14:58 UTC, wmdev0808 commented on app/client/src/widgets/JsonEditorWidget.tsx
> +import React from "react";
Got it

2021-09-08 15:00 UTC, wmdev0808 commented on app/client/src/widgets/JsonEditorWidget.tsx
> +function isValidJSON(
Got it, makes sense

2021-09-08 15:02 UTC, wmdev0808 commented on app/client/src/widgets/JsonEditorWidget.tsx
> +    const { text, widgetId } = this.props;
got it

2021-09-08 15:05 UTC, wmdev0808 commented on app/client/src/widgets/JsonEditorWidget.tsx
> +      json: undefined,
Definitely makes sense. I will refactor

2021-09-10 11:20 UTC, riodeuno requested changes

2021-09-10 11:20 UTC, riodeuno commented on app/client/src/assets/icons/widget/json-editor.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="20" height="26" fill="none" viewBox="0 0 20 26"><path fill="#F1F7FC" d="M12.1996 0H1.48041C0.664088 0 0 0.637982 0 1.42222V24.5778C0 25.362 0.664088 26
We don't need this file anymore.

2021-09-10 11:20 UTC, riodeuno commented on app/client/src/icons/WidgetIcons.tsx
> +  JSON_EDITOR_WIDGET: (props: IconProps) => (
We don't need this entry here anymore.

2021-09-10 11:20 UTC, riodeuno commented on app/client/src/widgets/JsonEditorWidget/widget/index.tsx
> +      parsedJSON: `{{ JSON.parse(this.jsonString) }}`,
Have we tested this by passing a bad `jsonString` value? Does this break the widget?

2021-09-10 11:20 UTC, riodeuno commented on app/client/src/workers/validations.ts
> +  [ValidationTypes.JSON]: (
We need to add an entry in the `common.ts` file as well. This will generate the expected structure in the property pane.

2021-09-10 11:20 UTC, riodeuno commented on app/client/src/widgets/JsonEditorWidget/constants.ts
> +// This file contains common constants which can be used across the widget configuration file (index.ts), widget and component folders.
We can remove this file, if it is not needed.

2021-09-10 13:46 UTC, wmdev0808 commented on app/client/src/widgets/JsonEditorWidget/widget/index.tsx
> +      parsedJSON: `{{ JSON.parse(this.jsonString) }}`,
I've tested it, it doesn't break the widget

2021-09-13 04:44 UTC, riodeuno approved these changes
Nice work! From the code's perspective, this looks to be fine. Moving this to the QA pipeline.

2021-09-13 04:56 UTC, riodeuno commented
@wmdev0808 Please look into the following
- Cypress test which test whether the defaultText updates the JSON correctly.
- Cypress test which test whether the user can edit the JSON in view mode


The following features are missing here:
- `onSave` action trigger (Please see the original issue description) Without this feature, this doesn't seem useful at all.
- `allow copy` property.
- `isDisabled` property

Bug:
<img width="1537" alt="Screenshot 2021-09-13 at 10 21 33 AM" src="https://user-images.githubusercontent.com/103687/133026048-85a8bd67-c31c-46f5-82fc-1b44ac3c955f.png">

2021-09-13 12:41 UTC, jsartisan commented
@riodeuno

> Cypress test which test whether the user can edit the JSON in view mode

View mode here is deploy mode right? because there is view option in the json editor as well.

2021-09-16 09:39 UTC, riodeuno approved these changes
Looks good to me. Quick check on the deploy preview did not help me spot any obvious issues.
However, we should be confirming the look and feel with the designs. @somangshu

2021-09-16 09:39 UTC, riodeuno commented
@momcilo-appsmith  This will need a design check as well.

2021-09-16 09:41 UTC, somangshu commented
Thats right @riodeuno, the feature is not inline to PRD, we need some design inputs here, I am not sure how much of the constrain is placed by the component used here. All features are not available as of now

2021-09-18 11:28 UTC, wmdev0808 commented
> Thats right @riodeuno, the feature is not inline to PRD, we need some design inputs here, I am not sure how much of the constrain is placed by the component used here. All features are not available as of now.
> 
> @wmdev0808 can you comment on that

@somangshu First, provide the design on desirable properties so I can just confirm if they are possible with the current underlying package.

2021-09-22 06:03 UTC, somangshu commented
moving this to needs more info until we have @momcilo-appsmith back with the base design

2023-01-20 13:29 UTC, closed without merging