feat: Support body in GET API requests
appsmithorg/appsmith pull request #7127
Opened 2021-09-05 15:00 UTC by mohanarpit

## Description

Fixes #6668

Now all HTTP methods support a body in the HTTP request.

This PR adds another tab in the Rest API plugin called `None`. This will be used by users to define HTTP requests that don't have a body. In the Body field, clicking on `None` will remove the `content-type` header while clicking on `RAW` will keep any existing `content-type` header. 

_Current problem which still needs to be resolved:_ In non-GET requests (POST, PUT etc), clicking on the None tab still sends the body. This is because the body is stored in the `actionConfiguration.body` field which is still non-null. If we delete the body data, then mistakenly clicking on `None` will erase all the work put in by a user. 

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Manual
- 
## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-09-05 18:28 UTC, arunvjn commented on app/client/src/constants/ApiEditorConstants.ts
> +export const HTTP_METHODS_ENUM: Record<
This Object doesn't behave like an enum. For Eg. 
`HTTPS_METHODS_ENUM.GET = 1` will modify its value. We can work around this by using `Object.freeze` or the modifier `as const`. Alternatively, I think we should use 2 enums

`enum HTTP_METHOD {
    GET = "GET", POST = "POST" //And more
}`
And 
`
enum HTTP_COLOR {
    GET = "GET", POST = "POST"
}
`

2021-09-05 20:36 UTC, mohanarpit commented on app/client/src/constants/ApiEditorConstants.ts
> +export const HTTP_METHODS_ENUM: Record<
I've added `Object.freeze`. Can you verify if that's the correct way of doing it? 

Also, any reason you are splitting this object into 2 enums? The reason I added the value & color to a single object was to ensure that if we add another HTTP method in the future, it's clear that we need to add a color as well. Reducing the possibility of developer error from happening.

2021-09-06 03:53 UTC, arunvjn commented on app/client/src/constants/ApiEditorConstants.ts
> +export const HTTP_METHODS_ENUM: Record<
There are a few reasons why having 2 constants help.

Consider the following code.
`export enum HTTP_METHOD {
  GET = "GET",
  POST = "POST",
  DELETE = "DELETE" //New method added 
}

//Compilation error here
export const HTTP_COLOR: { [key in keyof typeof HTTP_METHOD]: string } = {
  GET: "#457AE6",
  POST: "#EABB0C",
};`

As soon the method DELETE is added, typescript will give us a compilation error on `HTTP_COLOR`, thereby preventing developer errors. 

Code completion: If you type in `HTTP_METHODS_ENUM.`, you will not get the right autocomplete since it's a record of <string, ...>

Readability: `HTTP_METHOD.GET` is more concise that `HTTPS_METHODS_ENUM.GET.value`

2021-09-06 07:32 UTC, arunvjn commented on app/client/src/constants/ApiEditorConstants.ts
> +export const POST_BODY_FORMAT_OPTIONS: Record<
Removing Record type here will help with code completion. Accidental typos in property access of an object with Record<string,.. > as type would be really difficult to find. Alternatively, we can add types using ApiContentTypes but it could be an overkill

2021-12-08 16:02 UTC, Irongade commented
/ok-to-test sha=8469113

2022-02-07 09:38 UTC, Irongade commented
/ok-to-test sha=90a928f

2022-02-09 15:00 UTC, arunvjn requested changes
Left some minor feedback mostly around naming convention, readability and types

2022-02-14 09:15 UTC, arunvjn approved these changes
LGTM!

2022-02-14 13:19 UTC, Irongade commented
/ok-to-test sha=749e703

2022-02-14 20:51 UTC, Irongade commented
/ok-to-test sha=aa7f66c

2022-02-15 09:33 UTC, Irongade commented
/ok-to-test sha=cad46d3

2022-02-15 09:58 UTC, Irongade commented
/ok-to-test sha=cad46d3

2022-02-15 11:13 UTC, merged