Fix retention issues #3862 and #6466
appsmithorg/appsmith pull request #7159
Opened 2021-09-06 11:42 UTC by vnodecg

## Description

> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change.

Fixes #3862 
Fixes #6466 

## Type of change

- Bug fix (non-breaking change which fixes an issue) #6466 
- New feature (non-breaking change which adds functionality) #3862

## How Has This Been Tested?

Manually 

https://www.loom.com/share/2bb83e69790e4e8bab50e1e525f1b586

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-09-06 14:06 UTC, hetunandu requested changes

2021-09-06 14:06 UTC, hetunandu commented on app/client/src/components/editorComponents/ActionCreator/Fields.tsx
> +          defaultParams = `{}`;
This is going to cause issues and reintroduce #3125
Specifically: 

> The action selector does not add an undefined directly when skipping the query params argument

2021-09-09 07:26 UTC, vnodecg commented on app/client/src/components/editorComponents/ActionCreator/Fields.tsx
> +          defaultParams = `{}`;
I reverted this change

2021-09-09 07:44 UTC, hetunandu approved these changes

2021-09-16 06:26 UTC, hetunandu approved these changes

2021-09-17 11:02 UTC, merged