feat: Classify the error messages to validation or plugin errors
appsmithorg/appsmith pull request #7161
Opened 2021-09-06 12:14 UTC by AnaghHegde

## Description

> 

Fixes # (issue)

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Locally via postman

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

2021-09-07 04:55 UTC, nidhi-nair commented
@AnaghHegde are these changes comprehensive across requests?

2021-09-07 04:56 UTC, nidhi-nair requested changes
Can you confirm whether these changes need to be made for other methods as well?

2021-09-07 05:31 UTC, AnaghHegde commented
@nidhi-nair So in previous PR, i had made changes at the method level. But i missed only the `Fetch` command implementation.

2021-09-13 09:58 UTC, nidhi-nair approved these changes

2021-09-13 10:46 UTC, merged