feat: API to connect application to git
appsmithorg/appsmith pull request #7202
Opened 2021-09-07 11:11 UTC by AnaghHegde

## Description

> 

Fixes #7199 

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Locally via Postman
- JUnit Tests

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

2021-09-07 13:08 UTC, sharat87 submitted a review, later dismissed
Looks good. Just a few things before we bring this in.

2021-09-07 13:08 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/GitServiceImpl.java
> +        if(!Optional.ofNullable(gitConnectDTO.getAuthorEmail()).isEmpty()) {
Same as above. Let's use `StringUtils.isEmpty`.

2021-09-07 13:08 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/GitServiceImpl.java
> +    public void updateGitApplicationMetadata(GitConnectDTO gitConnectDTO) {
Is this going to be implemented in a future PR? Can we add it then, along with an implementation?

2021-09-07 13:08 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/GitServiceImpl.java
> +        return applicationService.update(gitConnectDTO.getApplicationId(), application);
Since we are updating based on an `Application` object, can you confirm if none of the fields except for `gitApplicationMetadata` on `Application` are updated in the database? I'm suspecting fields that have a default value in the `Application` class, like `isPublic`.

2021-09-07 13:08 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/GitServiceImpl.java
> +        gitApplicationMetadata.setBranchName(defaultBranchName);
Since we have a `remoteURL` here, should we connect to it and check what the default branch is? Instead of assuming it is `master`? Like, for our own appsmith repo, default branch is `release`, not `master`. I'm wondering if it is possible to find this information quickly using the remote URL and just use that here. We can treat `master` as a fallback if contacting the remote URL fails for whatever reason. What say?

2021-09-07 13:32 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/domains/GitApplicationMetadata.java
> +@Setter
I wasnt aware of this. I will revert this.

2021-09-07 13:35 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/GitServiceImpl.java
> +    *  We are implementing the deployKeys approach and since the deploy-keys are repo level these keys are store under application.
I will change the comments, my bad.

2021-09-07 13:37 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/GitServiceImpl.java
> +    *  @param gitConfig - user can chose to have a different authorName & Email for a specific repo if not set then the default from the userData will be used
Yeah thats correct, the reason i kept them like that is because the meaning of each of this fields in the object is not documented anywhere else.

2021-09-07 13:43 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/GitServiceImpl.java
> +    public void updateGitApplicationMetadata(GitConnectDTO gitConnectDTO) {
Oh dont know what i was thinking while pushing the code 😒

2021-09-07 13:47 UTC, abhvsn requested changes

2021-09-07 13:47 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/domains/GitApplicationMetadata.java
> +    String authorEmail;
I think I'm missing something here, can you explain what will happen when we have multiple developers and want separate author details? I was of the opinion of saving a Map<userId, GitConfig>. This will be user + application specific, and only be created if the devs or admins want a separate profile for this specific repo. Thoughts on this?

2021-09-07 13:47 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/GitServiceImpl.java
> +    *  Each application is equal to a repo in the git
This might not be relevant here but after reading above comment I got an impression that each application will be mapped to separate repo which is not the case, each application is mapped to a branch in the repo

2021-09-07 13:47 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/GitServiceImpl.java
> +        String encryptedKey = encryptionService.encryptString(gitConnectDTO.getGitAuth().getPrivateKey());
Is this required, IIRC our @Encrypted annotation takes care of this under the hood

2021-09-07 13:47 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/GitServiceImpl.java
> +        }
privateKey will not be sent to FE in any case, we will be baking the SSH key in BE and then will be sending the public key as a part of separate API. Can we take care of that scenario here?

2021-09-07 13:49 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/GitServiceImpl.java
> +        return applicationService.update(gitConnectDTO.getApplicationId(), application);
This method is used for all the updates. Ex - application name change and i didn't observe any inconsistency.

2021-09-07 13:54 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/GitServiceImpl.java
> +        gitApplicationMetadata.setBranchName(defaultBranchName);
I did thought of this but this API is used for the case when you want to push an existing application in Appsmith to a git repo. The only way to achieve this via JGit is to clone that repo and then get the default branch.
The flow that we had in mind was - `git init` and then `git commit` and last `git push`. 
I guess we can achieve this by `git clone` --> `git add -A` --> `git commit` --> `git push`
What do you think ?

2021-09-07 13:59 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/GitServiceImpl.java
> +    *  Each application is equal to a repo in the git
From UI perspective its just a dropdown with which they can switch branch. Keeping that as reference i wrote this. I will add this note as well to avoid confusion.

2021-09-07 14:04 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/GitServiceImpl.java
> +        String encryptedKey = encryptionService.encryptString(gitConnectDTO.getGitAuth().getPrivateKey());
I did notice that but its not encrypting the string hence i added this change.

2021-09-07 14:07 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/GitServiceImpl.java
> +        }
Generate Key is a separate API and keys generated are directly sent to FE. How can i get that information @BE?
We can store it in cache and then retrieve it. I cant think of anything else here.

2021-09-08 02:16 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/GitServiceImpl.java
> +        }
IMO you can just expect the keys are already present while connect api is called. Check if the keys are present and send the error msg back mentioning please configure the keys in case keys are not present

2021-09-08 06:16 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/GitServiceImpl.java
> +        gitApplicationMetadata.setBranchName(defaultBranchName);
Ah I see, so the remote repo is expected to be empty since we are pushing the application anew. Got it.

2021-09-08 08:40 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/GitServiceImpl.java
> +                    }
Due to the fact that private and public key can consume more than 4kB of space we have decided to keep the keys in defaultApplication only. Can we make that change here

2021-09-08 08:45 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/GitServiceImpl.java
> +                                "SSH Key is empty. Please reach out to Appsmith support"));
Due to the fact that private and public key can consume more than 4kB of space we have decided to keep the keys in defaultApplication only. Can we make that check here? Also can we update the implementation if we are showing the same error for all the if conditions

2021-09-08 09:00 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/GitServiceImpl.java
> +                                "SSH Key is empty. Please reach out to Appsmith support"));
Just to be on the same page we can hit this API from child application as well

2021-09-08 09:08 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/domains/GitApplicationMetadata.java
> +    String authorEmail;
The assumption here is that - each user will use a different branch and each branch has a different application object where we can update it. I hope this solves the issue. 99% of the cases users will use their own branch.

2021-09-09 04:03 UTC, abhvsn approved these changes
LGTM 
Added few comments which needs to be taken care of in future PRs

2021-09-09 04:03 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/GitServiceImpl.java
> +        return saveGitConfigData(gitConnectDTO.getGitConfig())
Let's have a repo level user profiles in the subsequent PRs

2021-09-09 04:03 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/GitServiceImpl.java
> +                                gitApplicationMetadata.setBranchName(DEFAULT_BRANCH_NAME);
After the remote repo connection check using the clone flow is checked let's have a default branch as per remote only and not impose the **_master_**

2021-09-09 04:06 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/GitServiceImpl.java
> +                                gitApplicationMetadata.setBranchName(DEFAULT_BRANCH_NAME);
Yes, i will be adding this change in the next PR - Clone API.

2021-09-09 04:07 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/GitServiceImpl.java
> +        return saveGitConfigData(gitConnectDTO.getGitConfig())
Yess 💯

2021-09-09 11:21 UTC, merged