Feature/6766 new column type select
appsmithorg/appsmith pull request #7206
Opened 2021-09-07 11:50 UTC by vibhandikyash

## Description

> Enabled a new Column type select where the user can setup a select widget in a column.

Fixes #6766 

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

> Tested locally.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-09-07 11:52 UTC, somangshu commented
@vibhandikyash semantics are not right!

2021-09-08 05:14 UTC, marks0351 requested changes
@vibhandikyash pls add test cases and check if docs need update.
cc: @somangshu

2021-09-13 09:20 UTC, marks0351 approved these changes

2021-09-28 05:23 UTC, marks0351 approved these changes

2021-09-29 04:54 UTC, riodeuno commented
UX Issues
- When selecting an option from the select cell, the row gets selected, and triggers the onRowSelected. Let's not propagate these events.
- `currentRow` is not accessible in the property controls of the select type columns
- Server side filtering doesn't need to be in the list of property controls for now. Please remove all references to this control and any functionality which has been added related to this.
- Even if `currentRow` is available to bind, it is not defined when evaluating triggers.
- In all select components, the first option is always shown as highlighted in the list, while there is no selection @Tooluloope 
<img width="718" alt="Screenshot 2021-09-29 at 10 22 57 AM" src="https://user-images.githubusercontent.com/103687/135205491-25e127bc-019d-49cb-a632-aeb448a97a2d.png">

2021-09-29 05:04 UTC, riodeuno requested changes

2021-09-29 05:04 UTC, riodeuno commented on app/client/src/widgets/TableWidget/component/Constants.ts
> +  defaultOptionValue?: string;
Please verify if `options` needs to be here.

2021-09-29 05:04 UTC, riodeuno commented on app/client/src/widgets/TableWidget/component/TableUtilities.tsx
> +export function SelectCell(props: {
Please add a detailed comment at the top of this function describing what this does.

2021-09-29 05:04 UTC, riodeuno commented on app/client/src/widgets/TableWidget/component/TableUtilities.tsx
> +          onOptionSelected={(optionSelected) => {
Let's use `useCallback` here.

2021-09-29 05:04 UTC, riodeuno commented on app/client/src/widgets/TableWidget/widget/derived.js
> +          if (_.has(props.editedColumnData, `${sanitizedKey}.${index}`)) {
Let's add comments to describe what is being computed here.
Let's also add jest tests for those computations in the `derived.test.js` file.

2021-09-29 06:11 UTC, Tooluloope commented
> UX Issues
> - In all select components, the first option is always shown as highlighted in the list, while there is no selection @Tooluloope 
> 

@riodeuno The reason for that is for keyboard accessibility. So when the dropdown is active, the first item is auto focused. There is a difference between the focused state and the select state of the options.

2021-10-05 05:46 UTC, YogeshJayaseelan commented
@vibhandikyash Tested this PR and Please find the status below,

1.The order in the Select Column Property pane should match the Select widget order 

* Options
*  Default Options
*  Placeholder
* Required Toggle 
* Visible Toggle 
* Disabled Toggle 
* Filterable Toggle 
* OnOption Change Action

2.  Required Toggle is not available 

3. Filterable Toggle is not available 

4. Once when the disabled toggle is enabled and disabled - Then the select column is in disabled mode 

https://loom.com/share/3d22bc4621064815a20da68fed699d8d

5.By Default - Options, Default Options and PlaceHolder are empty - Due to which empty checkbox is displayed on the select column - **Default values can be displayed** 

https://www.loom.com/share/c581beefec334a05954e9393bf7e1fae

2021-10-07 10:34 UTC, somangshu commented
Feedback @vibhandikyash:
- Default value needs to change to computed value and should be re-ordered below column type
- Just like in the button column type we have the button properties separated, we will do the same for this column type
- Point 4 from @YogeshJayaseelan feedback is true
- Point 5 from @YogeshJayaseelan feedback should be looked into, Set the defaults as per other column types
- Re-order the disable property to the top of Select properties 
- Documentation changes required here
- Do we have the basic cypress and jest tests for this?


Revert on the above feedback:
- @YogeshJayaseelan since this is in a table and the value is bound the query I dont see the case of using `required` (please explain if required), However in extension to the inline edit in table widget we could introduce some validation here. 
- @YogeshJayaseelan lets raise filterable as a separate requirement later, I would like to see some request around this before taking it up

2021-11-03 09:53 UTC, Nikhil-Nandagopal commented
- Triggered row didn't work for me
- The select option was very slow to update
- There were options missing like server side filtering

2021-11-03 10:45 UTC, riodeuno commented
@vibhandikyash Let's implement the `triggeredRow` feature here. We populate the `triggeredRow` when we a button cell is clicked. The same should happen for the onOptionChange of the select column type.

We should also include the description of `triggeredRow` in the documentation

2021-11-03 10:52 UTC, riodeuno commented
Here are two issues I found. I'm not sure if this is related to the changes in this PR. Please verify.
-  [ ] Math.random(), triggers updates repeatedly
-  [ ] `currentRow` works in an unexpected manner in the onOptionChange binding.
https://user-images.githubusercontent.com/103687/140047799-9913a714-c024-496e-b738-b6605eb4ba1d.mov

https://user-images.githubusercontent.com/103687/140047816-2c7b9d67-70ed-4c67-b30f-36756e7f3902.mov

2021-11-03 10:53 UTC, riodeuno requested changes
Please refer to the comments for the requested changes.

2021-11-24 10:20 UTC, vibhandikyash commented
/ok-to-test sha=0ab5a42

2021-11-25 11:46 UTC, riodeuno commented
@vibhandikyash  Nice work! This is close to completion. Quite a few problems have been resolved, however, one issue remains. Please see attached screen recording.
I'll get back to you on the debugger issue.

https://user-images.githubusercontent.com/103687/143436046-c2249924-f4b9-4ee1-a6c6-51f39a6d2a71.mov

2021-11-30 10:58 UTC, vibhandikyash commented
/ok-to-test sha=647ed3a

2021-11-30 16:37 UTC, riodeuno commented
@vibhandikyash I'm not able to check the deploy preview as there is a typescript error while led to a failed build. Please fix this and pull the latest release to see if there are any updates to the binding issue.

2021-12-01 10:26 UTC, vibhandikyash commented
/ok-to-test sha=3cfd653

2021-12-07 11:54 UTC, riodeuno submitted a review, later dismissed
Looks good to me. We can go ahead with the QA. I'm looking into the debugger issue w.r.t `derivedColumns`

2021-12-13 06:45 UTC, riodeuno approved these changes

2021-12-14 08:38 UTC, YogeshJayaseelan commented
@vibhandikyash Tested this feature and please find the status below,

Issue 1 - Property fields order will be based on table widget
Issue 2 - Not in scope
Issue 3 - Not in scope
Issue 4 - Fixed,
Issue 5 - **Not Fixed - Default value is not displayed - The select column is empty by default**

Issue 6 - Math.random(), triggers updates repeatedly - This is still happening and what is expected behaviour here @riodeuno - https://loom.com/share/8a9c157790714f1a879c9edc1163bb7b

New issue :

Issue 7 - Text alignment and vertical alignment is not working for select column type - Should alignment work for select column too? @somangshu @vibhandikyash 
https://www.loom.com/share/b1acdfd665e3442db8a9a62cf977fe45

2021-12-14 09:25 UTC, somangshu commented
> Issue 7 - Text alignment and vertical alignment is not working for select column type - Should alignment work for select column too? @somangshu @vibhandikyash

@YogeshJayaseelan yes that should be the case

2021-12-16 10:16 UTC, vibhandikyash commented
ok-to-test sha=2e5f161

2021-12-17 09:01 UTC, somangshu commented
/ok-to-test sha=2e5f161

2022-01-24 10:44 UTC, vibhandikyash commented
Closing this PR. Feature will be reopened with TableV2.

2022-01-24 10:44 UTC, closed without merging