Feat: Image Annotator
appsmithorg/appsmith pull request #7234
Opened 2021-09-08 08:49 UTC by wmdev0808

## Description
A widget that can be used for labelling objects inside images. 
Features:
- Ability to draw inside image using a polygon
- Store coordinates of the box and send it an API request

Fixes #3362 

## Type of change

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

## How Has This Been Tested?

- Test A
- Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-09-08 09:26 UTC, somangshu commented
@wmdev0808 jest tests failing because of related changes please check and fix

2021-09-08 13:39 UTC, somangshu approved these changes
Approving to run the tests. @SatishGandham will review the code

2021-09-08 14:09 UTC, SatishGandham approved these changes

2021-10-13 12:38 UTC, somangshu commented
@wmdev0808 can you clear the merge conflicts

@vivekverma2312 @YogeshJayaseelan you guys need to prioritise tasks properly here, this PR got closed due to inactivity. We now have to go through the whole flow. the icon will need to change, There might me new reviews required. Lets catchup to strategise this

cc @yatinappsmith

2021-10-19 06:29 UTC, somangshu commented
/ok-to-test sha=4f6e7cd

2021-11-03 11:24 UTC, wmdev0808 commented
/ok-to-test sha=b75e426

2021-11-03 12:44 UTC, wmdev0808 commented
/ok-to-test sha=93686db

2021-11-03 13:25 UTC, wmdev0808 commented
/ok-to-test sha=6fb17ba

2021-11-03 13:26 UTC, wmdev0808 commented
https://github.com/appsmithorg/appsmith/actions/runs/1416920477

2021-11-04 08:34 UTC, somangshu reviewed
Good work @wmdev0808,
Feedback on the deploy preview:
- The onAnnotationChange is called every-time the mouse hovers on the widget, this is not desired, If we cant make this appear only when the annotation changes, Which is probably not offered as a functionality, we should remove this
- Provide all selectors available by default in the package: `[RectangleSelector, PointSelector, OvalSelector]`, Expose the API to user for choosing one
- There is a property available annotations & activeAnnotations, if this lets the dev place annotation programmatically, we should expose this API (use case: re-enforcement learning) 
- Provide disableAnnotation API for the dev to disable creating annotations
- @momcilo-appsmith @UXFalcon we can change the way the input looks, Please take a look an let us know if that is required
- expose `alt` API for the user


@SatishGandham kindly review the code, I also have the following question, Let me know what are your thoughts
- Is it wise to connect selector logic to redux? https://github.com/RobinNagpal/react-image-annotation-ts#connecting-selector-logic-to-reduxmobx
- We should probably fork the repo, Since is is not a very popular package

2021-11-10 09:48 UTC, SatishGandham requested changes

2021-11-10 09:48 UTC, SatishGandham commented on app/client/src/widgets/ImageAnnotatorWidget/widget/index.tsx
> +            helpText: "Disables input to the widget",
Do you mean disable annotations?

2021-11-10 09:48 UTC, SatishGandham commented on app/client/src/widgets/ImageAnnotatorWidget/component/index.tsx
> +  const handleChange = useCallback(
We are not doing any additional work on handleChange and submit, why not pass these props directly to Annotation?

2021-11-10 09:48 UTC, SatishGandham commented on app/client/src/widgets/ImageAnnotatorWidget/component/index.tsx
> +      {disabled && <DisabledOverlay />}
What does disabled mean?

2021-11-10 09:51 UTC, wmdev0808 commented on app/client/src/widgets/ImageAnnotatorWidget/widget/index.tsx
> +            helpText: "Disables input to the widget",
No, it is just for disabling widget as we did with other widgets

2021-11-10 09:53 UTC, wmdev0808 commented on app/client/src/widgets/ImageAnnotatorWidget/component/index.tsx
> +  const handleChange = useCallback(
It is just for avoid unnecessary re-render

2021-11-10 09:54 UTC, wmdev0808 commented on app/client/src/widgets/ImageAnnotatorWidget/component/index.tsx
> +      {disabled && <DisabledOverlay />}
It means if user disabled the widget from the property pane

2021-11-10 10:26 UTC, SatishGandham commented
@somangshu @wmdev0808 ,

- How does the user show these saved annotations?
- _Provide all selectors available by default in the package: [RectangleSelector, PointSelector, OvalSelector], Expose the API to user for choosing one_. To which user, Appsmith dev or end user? I think we will need designs to expose to end user.
- Connecting to the store is not required, state can be maintained in the component itself.

2021-11-10 10:45 UTC, somangshu commented
> @somangshu @wmdev0808 ,
> 
> * How does the user show these saved annotations? @wmdev0808 _**does activeAnnotation / Annotation API allow us to do the same**_
> * _Provide all selectors available by default in the package: [RectangleSelector, PointSelector, OvalSelector], Expose the API to user for choosing one_. To which user, Appsmith dev or end user? I think we will need designs to expose to end user. @SatishGandham _**this is only for the dev right now**_
> * Connecting to the store is not required, state can be maintained in the component itself. 👍

2021-11-10 14:48 UTC, wmdev0808 commented
/ok-to-test sha=5f54d53

2021-11-10 14:48 UTC, wmdev0808 commented
https://github.com/appsmithorg/appsmith/actions/runs/1444698732

2021-11-11 06:27 UTC, somangshu commented
Great value add with the default annotation feature. This will be helpful for the devs and makes the feature more complete. My feedback around it is:
- The property should be below the `alt text` property
- I was thinking about having the actual object separated like how we are trying to doing in the chart widget, But this is not a good idea because the input / output of the annotation object is same here. We need to do a real good job in create a documentation around this. @wmdev0808 can you draft the initial version of that. @Pranay105 we will need your help to polish this further. 

**_Issue_**:
- the widget is not working on the view mode. seeing a console error
- once we create an annotation We can see the widget grouping boundary enabled until the canvas is clicked again

https://user-images.githubusercontent.com/11089579/141248801-0f8dd708-c9cc-4ef0-8640-d55a5ed55aaa.mov

2021-11-11 06:28 UTC, somangshu submitted a review, later dismissed
Left comment

2021-11-11 07:35 UTC, SatishGandham commented on app/client/src/widgets/ImageAnnotatorWidget/component/index.tsx
> +  const handleChange = useCallback(
It doesn't solve the re-render issue.
It has to re-render anyway if onChange/onSubmit change.

2021-11-11 13:35 UTC, wmdev0808 commented
/ok-to-test sha=5883ac9

2021-11-11 13:36 UTC, wmdev0808 commented
https://github.com/appsmithorg/appsmith/actions/runs/1448986612

2021-11-11 14:52 UTC, somangshu commented on app/client/src/widgets/ImageAnnotatorWidget/widget/index.tsx
> +            helpText: "Set to true to disable creating of annotations",
Change to `Controls if user is allowed to draw annotations`

2021-11-11 14:55 UTC, somangshu commented on app/client/src/widgets/ImageAnnotatorWidget/icon.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="none" viewBox="0 0 32 32"><path fill="#F2FAFF" fill-opacity=".9" d="M28 25.3333V6.66667C28 5.2 26.8 4 25.3333 4H6.66667C5.2 4 4 5.
@momcilo-appsmith @UXFalcon need help with the new icon

2021-11-11 14:57 UTC, somangshu commented
@SatishGandham @wmdev0808 this is not covered by test, Do you think anything is required?

@wmdev0808 have we created documentation for this?

2021-11-11 17:01 UTC, wmdev0808 commented
> @SatishGandham @wmdev0808 this is not covered by test, Do you think anything is required?
> 
> @wmdev0808 have we created documentation for this?

@somangshu, I didn't care about the test at the moment.
I've already created the basic documentation of the widget

2021-11-12 08:14 UTC, SatishGandham commented on app/client/src/widgets/ImageAnnotatorWidget/widget/index.tsx
> +            helpText: "Set to true to disable creating of annotations",
@somangshu should we call this property `isAnnotationDisabled`? Isn't `isDisabled` better and consistent with other widgets?

cc: @wmdev0808

2021-11-12 08:16 UTC, SatishGandham requested changes
@wmdev0808  Looks good apart from the disabled property name.
Please add some test cases.

2021-11-12 08:30 UTC, Pranay105 commented
Draft an initial version of the doc. Just make sure it covers everything - functionality, behavior, exceptions, etc. I'll work on that. @somangshu @wmdev0808

2021-11-12 09:41 UTC, somangshu commented on app/client/src/widgets/ImageAnnotatorWidget/widget/index.tsx
> +            helpText: "Set to true to disable creating of annotations",
totally agree to that, @wmdev0808 we will need to make this chagne

2021-11-12 09:42 UTC, somangshu commented
> Draft an initial version of the doc. Just make sure it covers everything - functionality, behavior, exceptions, etc. I'll work on that. @somangshu @wmdev0808

@Pranay105 https://github.com/appsmithorg/appsmith-docs/pull/294

2021-11-21 17:50 UTC, wmdev0808 commented
/ok-to-test sha=e98182f

2021-11-22 06:18 UTC, SatishGandham commented on app/client/src/widgets/ImageAnnotatorWidget/widget/index.tsx
> +            helpText: "Sets image alt attribute",
@vihar , Is the language correct?

2021-11-22 06:21 UTC, SatishGandham commented on app/client/src/widgets/ImageAnnotatorWidget/widget/index.tsx
> +            helpText: "Sets to true to disable creating of annotations",
@vihar , The language doesn't seem right. Please check.

2021-11-29 13:09 UTC, wmdev0808 commented
/ok-to-test sha=6dd0cae

2021-11-30 06:16 UTC, SatishGandham commented
@Pranay105 Can you go through the property descriptions in this file once and suggest the changes
https://github.com/appsmithorg/appsmith/pull/7234/files/e98182fe7485778323753bc6633bdc559229a77c#diff-9baf5fca6574099827df5155a9dcd05166eae3d459c589936685c5f5836ce626

2021-12-06 07:49 UTC, Pranay105 commented on app/client/src/widgets/ImageAnnotatorWidget/widget/index.tsx
> +            helpText: "Url of the image to be annotated",
To add an image to the canvas, enter its URL here.

2021-12-06 07:49 UTC, Pranay105 commented on app/client/src/widgets/ImageAnnotatorWidget/widget/index.tsx
> +            helpText: "Sets image alt attribute",
Enter the alternative text for the image here, giving a short description of it.

2021-12-06 07:49 UTC, Pranay105 commented on app/client/src/widgets/ImageAnnotatorWidget/widget/index.tsx
> +            helpText: "Array of annotations",
I'm not able to understand what this property is. Can someone please explain this?

2021-12-06 07:49 UTC, Pranay105 commented on app/client/src/widgets/ImageAnnotatorWidget/widget/index.tsx
> +            helpText: "Controls the visibility of the widget",
Controls widget's visibility on the page. When turned off, the widget will not be visible when the app is published.

2021-12-06 07:49 UTC, Pranay105 commented on app/client/src/widgets/ImageAnnotatorWidget/widget/index.tsx
> +            helpText: "Sets to true to disable creating of annotations",
It enables or disables the annotation. If turned on, the user cannot annotate the image.

2021-12-06 07:49 UTC, Pranay105 commented on app/client/src/widgets/ImageAnnotatorWidget/widget/index.tsx
> +            helpText: "Sets the selector of the widget",
It allows you to choose the type of selector for the annotation.

2021-12-06 16:01 UTC, wmdev0808 commented on app/client/src/widgets/ImageAnnotatorWidget/widget/index.tsx
> +            helpText: "Array of annotations",
@Pranay105 ,
This property is for setting default annotations array which will be used as underlying data for annotations in the first place

2021-12-06 16:06 UTC, wmdev0808 commented
/ok-to-test sha=3bb9091

2021-12-13 05:18 UTC, wmdev0808 commented
/ok-to-test sha=b7a17bb

2021-12-14 07:59 UTC, SatishGandham approved these changes

2021-12-15 09:40 UTC, somangshu commented
@wmdev0808 related tests have failed. Please check!

2021-12-15 15:04 UTC, wmdev0808 commented
/ok-to-test sha=258b601

2021-12-16 06:22 UTC, somangshu approved these changes

2022-02-14 05:20 UTC, closed without merging