feat: Table selected row and action trigger UX improvement
appsmithorg/appsmith pull request #7310
Opened 2021-09-09 12:35 UTC by vicky-primathon

## Description
Table selected row and action trigger UX improvement

Fixes #3407 
Fixes #2444
Fixes #2313
Fixes #6636

## Type of change
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How Has This Been Tested?

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-09-10 07:48 UTC, riodeuno requested changes

2021-09-10 07:48 UTC, riodeuno commented on app/client/src/utils/migrations/TableWidget.test.ts
> +    const outputDsl: ContainerWidgetProps<WidgetProps> = {
Let's use DSLWidget instead of `ContainerWidgetProps<WidgetProps>`

2021-09-10 07:48 UTC, riodeuno commented on app/client/src/widgets/TableWidget/component/TableUtilities.tsx
> +        // if (props.isSelected) {
Let's remove the commented file. Also, let's create a generic function called `stopPropagation` in the helpers, then use that function here directly.

2021-09-10 08:53 UTC, riodeuno submitted a review, later dismissed

2021-09-16 06:48 UTC, riodeuno requested changes

2021-09-16 06:48 UTC, riodeuno commented on app/client/src/widgets/TableWidget/widget/index.tsx
> +      this.props.updateWidgetMetaProperty("triggeredRow", rowData);
I can't seem to bind to this property. It also doesn't show up in the autocomplete. Let's fix this and add a cypress test for this scenario.

2021-09-16 06:49 UTC, riodeuno commented
@somangshu `onRowSelected` doesn't work for multi select table. Should that be a part of this PR?

2021-09-16 08:50 UTC, somangshu commented
> @somangshu `onRowSelected` doesn't work for multi select table. Should that be a part of this PR?

@riodeuno @vicky-primathon I am going to say yes, It definitely  a part of the same epic.

2021-09-17 05:23 UTC, riodeuno commented on app/client/src/widgets/TableWidget/widget/derived.js
> +  getTriggeredRow: (props, moment, _) => {
Can we verify that filters, searchText and sorting, doesn't effect the triggeredRow value? What will happen when we trigger an action and then sort, filter or search for something, will this still work? I am not sure if it will.

2021-09-17 05:25 UTC, riodeuno requested changes

2021-09-17 05:25 UTC, riodeuno commented on app/client/src/widgets/TableWidget/widget/index.tsx
> +          triggerPropertyName: "onRowSelected",
This should not be triggered on un select of rows. Can we confirm that it doesn't?

2021-09-17 06:29 UTC, vicky-primathon commented on app/client/src/widgets/TableWidget/widget/derived.js
> +  getTriggeredRow: (props, moment, _) => {
Handled using originalIndex property of table row data

2021-09-17 07:00 UTC, riodeuno commented on app/client/src/widgets/TableWidget/widget/derived.js
> +  getTriggeredRow: (props, moment, _) => {
Nice idea! Let's add a cypress test for this scenario, as using `__originalndex__` can be fragile. Let's trigger an action, then sort, or filter, to make sure that the `triggeredRow` doesn't change.

2021-09-17 07:00 UTC, riodeuno commented on app/client/src/widgets/TableWidget/widget/index.tsx
> +          triggerPropertyName: "onRowSelected",
👍🏼 Let's add a cypress test for onRowSelected on multi select tables as well.

2021-09-17 08:44 UTC, vicky-primathon commented on app/client/src/widgets/TableWidget/widget/derived.js
> +  getTriggeredRow: (props, moment, _) => {
@riodeuno, add cypress test for the same

2021-09-17 08:44 UTC, vicky-primathon commented on app/client/src/widgets/TableWidget/widget/index.tsx
> +          triggerPropertyName: "onRowSelected",
@riodeuno, add cypress test for the same

2021-09-17 09:51 UTC, riodeuno submitted a review, later dismissed

2021-09-20 10:59 UTC, vivekverma2312 commented
@vicky-primathon Deploy preview is tested and working fine.

2021-09-20 11:01 UTC, somangshu commented
@vivekverma2312 we need to be careful with this change. Are we aware of all the scenarios we are covering here.

2021-09-21 05:48 UTC, pranavkanade commented
@vicky-primathon Is this PR ready to go to release?

2021-09-21 06:30 UTC, riodeuno submitted a review, later dismissed

2021-09-21 06:36 UTC, vivekverma2312 commented
@vicky-primathon Discussed with Somangshu and figured one more issue
In case of the multi-select mode, the last selected row is not updating on `Table.selectedRow`

2021-09-21 08:40 UTC, riodeuno commented
@vivekverma2312 @somangshu @vicky-primathon Let's pick this scenario of `selectedRow` in multi select tables separately. 

Scenario: User unselects the latest selection in multi-select table. Now, we need to have the `selectedRow` contain the last selected row. Which is an involved implementation.

2021-09-21 09:23 UTC, vicky-primathon commented
> @vivekverma2312 @somangshu @vicky-primathon Let's pick this scenario of `selectedRow` in multi select tables separately.
> 
> Scenario: User unselects the latest selection in multi-select table. Now, we need to have the `selectedRow` contain the last selected row. Which is an involved implementation.

@somangshu  @vivekverma2312  pls let me know if we are good to go with current implementation and we can pickup updating selectedRow in multi row selection as a separate issue.

2021-09-21 10:55 UTC, somangshu commented
@vicky-primathon sure. For the sake of closure we can do this. 

@vivekverma2312 can you create the issue to address the pending issue here and assign it to Vicky. Otherwise we can close this PR if the rest looks fine to you

cc @riodeuno

2021-09-21 12:20 UTC, somangshu submitted a review, later dismissed
Approving to run tests

2021-09-21 13:57 UTC, vivekverma2312 commented
@somangshu  I have a raised #7696 separately and assigned to @vicky-primathon

2021-09-22 06:13 UTC, somangshu commented
Reran all tests, Unrelated failure.

@vicky-primathon is the code review complete? Close this once everything done. We have a sign off from @vivekverma2312

2021-09-22 06:24 UTC, vicky-primathon commented
> Reran all tests, Unrelated failure.
> 
> @vicky-primathon is the code review complete? Close this once everything done. We have a sign off from @vivekverma2312

Sure, will do. Code was reviewed by Abhinav. After that we have only merged release branch here.

2021-09-22 06:43 UTC, riodeuno approved these changes

2021-09-22 08:11 UTC, riodeuno approved these changes

2021-09-23 06:42 UTC, somangshu approved these changes

2021-09-23 11:46 UTC, merged