feat: resizable modal
appsmithorg/appsmith pull request #7312
Opened 2021-09-09 12:47 UTC by rahulramesha

## Description

feature for resizable modal

Fixes #3850 

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-09-09 12:48 UTC, rahulramesha commented
/ok-to-test sha=bd9b882

2021-09-17 05:43 UTC, marks0351 requested changes

2021-09-17 05:43 UTC, marks0351 commented on app/client/src/sagas/WidgetOperationSagas.tsx
> +const getModalCanvasBottomRow = (
Can you check this resizeCanvasToLowestWidget coz getModalCanvasBottomRow looks like it can be extracted out of it. if not we can have two functions dedicated.

2021-09-17 05:43 UTC, marks0351 commented on app/client/src/sagas/WidgetOperationSagas.tsx
> +    takeLatest(WidgetReduxActionTypes.WIDGET_MODAL_RESIZE, resizeModalSaga),
Also can we move this ModalSagas. it wud be more relevant.

2021-09-17 05:47 UTC, marks0351 commented
@rahulramesha also for some weird reason even in prod i cannot move a widget to the last column of modal canvas. can you check that too? as it moves to the last column it shows that the widget is out of bounds(red).

2021-09-20 07:09 UTC, rahulramesha commented on app/client/src/sagas/WidgetOperationSagas.tsx
> +const getModalCanvasBottomRow = (
@marks0351 yes, i Initailly tried using that method but needed some changes specific to modal resize on `getModalCanvasBottomRow`. So I decided to have a dedicated method for that.

2021-09-20 08:04 UTC, vivekverma2312 commented
@rahulramesha Issue1 : Modal size changes but the widget size on Modal do not change on changing the view mode
https://www.loom.com/share/f33feb8ec7dd41a18f79dc52cac66e42

2021-09-20 08:31 UTC, vivekverma2312 commented
@rahulramesha 2. Confirm and cancel button is not of same size -- Is this expected (cc: @somangshu)
3. After disabling quick dismiss “on close “ property do not work

2021-09-20 09:54 UTC, vivekverma2312 commented
4. Not able to resize modal widget after placing List widget
https://www.loom.com/share/5459514765fa4c279e0c1a58b5e44aad

2021-09-20 11:17 UTC, rahulramesha commented
@marks0351 I have fixed the last column issue, please re-review
@vivekverma2312 fixed issues 1 and 4, 
issue 2, seems that it was part of configuration, i have modified it to have equal width from now on in new Modals
issue 3, seems to be an unrelated bug that is reproducible in production

2021-09-20 13:16 UTC, vivekverma2312 commented
@rahulramesha Above issues are verified and working fine. For issue 3 I have raised a separate git issue #7628

2021-09-20 13:51 UTC, marks0351 approved these changes

2021-09-20 16:27 UTC, Tooluloope approved these changes

2021-09-20 17:06 UTC, merged