fix: radio group widget options
appsmithorg/appsmith pull request #7313
Opened 2021-09-09 13:43 UTC by Tooluloope

## Description

Fix undefined options of Radio group widget

Fixes #6967  (issue)

> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-09-10 11:04 UTC, somangshu commented
@Tooluloope please add the reproducible steps here for any one to verify

2021-09-10 11:06 UTC, riodeuno requested changes

2021-09-10 11:06 UTC, riodeuno commented on app/client/src/components/designSystems/blueprint/RadioGroupComponent.tsx
> +          {this.props.options &&
I believe the validations should automatically send in a default `[]` instead of us having to handle this here.

2021-09-10 11:07 UTC, Tooluloope commented on app/client/src/components/designSystems/blueprint/RadioGroupComponent.tsx
> +          {this.props.options &&
Yeah, I'd remove that

2021-09-10 11:07 UTC, Tooluloope commented on app/client/src/components/designSystems/blueprint/RadioGroupComponent.tsx
> +          {this.props.options &&
@somangshu We could just delete the PR, I believe the issue has been fixed already

2021-09-10 11:08 UTC, riodeuno commented on app/client/src/components/designSystems/blueprint/RadioGroupComponent.tsx
> +          {this.props.options &&
Let's update the validations configuration and try to resolve it there. Let's bind the `options` to something which results in `false` or `undefined` and test with the updated validation configurations.

2021-09-16 07:15 UTC, riodeuno commented on app/client/src/workers/validations.ts
> +        !isArray(config.params.default)
This will effect the whole application. So we should test this using strings as well. For example if we get `'[]'` instead of `[]`, what would happen?

We should also add this to the unit tests if it isn't already there.

2021-09-17 08:41 UTC, Tooluloope commented on app/client/src/workers/validations.ts
> +        !isArray(config.params.default)
Added unit test

2021-09-17 09:52 UTC, riodeuno approved these changes

2021-09-20 07:12 UTC, vivekverma2312 commented
@Tooluloope Not able to repro the issue did a round of sanity as per the smartlook video and is working fine.

2021-09-20 07:13 UTC, merged

2021-09-20 09:44 UTC, somangshu commented
@Tooluloope why didnt we add a test around this?

2021-09-20 09:45 UTC, Tooluloope commented on app/client/src/workers/validations.test.ts
> +  it("correctly validates array when default is given", () => {
@somangshu Added Validation test here

2021-09-20 09:47 UTC, somangshu commented on app/client/src/workers/validations.test.ts
> +  it("correctly validates array when default is given", () => {
Perfect, Apologies for missing this