feat: property pane docking
appsmithorg/appsmith pull request #7361
Opened 2021-09-13 04:29 UTC by jsartisan

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.

## Description

> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change.

Fixes # (issue)

> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-09-15 07:13 UTC, LizHamburger commented
Something odd looks like it's happening here, is this the edge of the canvas? Also there is a blueish line there that doesn't match the height of the grey box. 

![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiZTVmZjliMzYtMjgzZS00MTU5LWE2ZjUtMTZiMjQyODA0M2E4IiwiZGVwbG95X2lkIjoiNjE0MTkyZmVhY2RhZWMwMDA3MDFlOGQyIiwiaWQiOiIwMjc5YjRhNi1mNWI4LTRlNWItODBjOS03NjE0YWU5MTY5MjcifQ==)


<details><summary>Browser metadata</summary>





```
Path:      /applications/61419cbd740775297f87aa63/pages/61419cbd740775297f87aa65/edit
Browser:   Chrome 93.0.4577.63 on Mac OS 10.15.7
Viewport:  1815 x 1209 @2x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-7361--appsmith-editor-ce.netlify.app%2Fapplications%2F61419cbd740775297f87aa63%2Fpages%2F61419cbd740775297f87aa65%2Fedit&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=93.0&resolution=1815x1209&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-7361--appsmith-editor-ce.netlify.app/applications/61419cbd740775297f87aa63/pages/61419cbd740775297f87aa65/edit) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=614192feacdaec000701e8d2&commentID=61419d2f749edf53d4c7804e&resolution=resolved)

2021-09-15 07:15 UTC, LizHamburger commented
@aakashDesign there are two ipad icons, how can a user tell which on is landscape and which is portrait? 

Also when selecting the canvas size nothing is changing on the canvas.  ![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiZTVmZjliMzYtMjgzZS00MTU5LWE2ZjUtMTZiMjQyODA0M2E4IiwiZGVwbG95X2lkIjoiNjE0MTkyZmVhY2RhZWMwMDA3MDFlOGQyIiwiaWQiOiJjMTg3YjZlOC03MmY4LTRiN2YtYmM3MC1lYmViNWI5MGExYjUifQ==)


<details><summary>Browser metadata</summary>





```
Path:      /applications/61419cbd740775297f87aa63/pages/61419cbd740775297f87aa65/edit
Browser:   Chrome 93.0.4577.63 on Mac OS 10.15.7
Viewport:  1815 x 1209 @2x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-7361--appsmith-editor-ce.netlify.app%2Fapplications%2F61419cbd740775297f87aa63%2Fpages%2F61419cbd740775297f87aa65%2Fedit&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=93.0&resolution=1815x1209&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-7361--appsmith-editor-ce.netlify.app/applications/61419cbd740775297f87aa63/pages/61419cbd740775297f87aa65/edit) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=614192feacdaec000701e8d2&commentID=61419da554aaf0526dcf2b8e&resolution=resolved)

2021-09-15 07:17 UTC, LizHamburger commented
@aakashDesign 
Does it make sense here to have the properties pane open. What affects would this have is I start changing the screen size?
Would a user want to be able to change the screen size while they are adding a data source?

![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiZTVmZjliMzYtMjgzZS00MTU5LWE2ZjUtMTZiMjQyODA0M2E4IiwiZGVwbG95X2lkIjoiNjE0MTkyZmVhY2RhZWMwMDA3MDFlOGQyIiwiaWQiOiJhODZiZTMwYi0wYzQwLTQzZmUtOTA1Ny05ZWRkMmQyN2QwMDUifQ==)


<details><summary>Browser metadata</summary>





```
Path:      /applications/61419cbd740775297f87aa63/pages/61419cbd740775297f87aa65/edit/datasources/ACTIVE
Browser:   Chrome 93.0.4577.63 on Mac OS 10.15.7
Viewport:  1815 x 1209 @2x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-7361--appsmith-editor-ce.netlify.app%2Fapplications%2F61419cbd740775297f87aa63%2Fpages%2F61419cbd740775297f87aa65%2Fedit%2Fdatasources%2FACTIVE&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=93.0&resolution=1815x1209&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-7361--appsmith-editor-ce.netlify.app/applications/61419cbd740775297f87aa63/pages/61419cbd740775297f87aa65/edit/datasources/ACTIVE) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=614192feacdaec000701e8d2&commentID=61419dfd8d0dfa537ae4403f&resolution=resolved)

2021-09-15 07:24 UTC, LizHamburger commented
Couple of things on this page:
1. The drag drop text is not in the centre of the canvas.
2. The canvas is now a different colour / has a background to show the width and so the property pane stands out, this is better and should be used across. 
3. The search has an X but no text has been input. There are a lot of icons on that side. 
4. Is there hover states for the pin icon? 
5. Is a pin icon the best icon to have for this? Is an eye or something else better that suggests viewing/hiding? 
5. Can there be a message for first time users that when the entity explore is hidden how they get it back. I wasn't sure what I needed to do. 

@aakashDesign 

![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiZTVmZjliMzYtMjgzZS00MTU5LWE2ZjUtMTZiMjQyODA0M2E4IiwiZGVwbG95X2lkIjoiNjE0MTkyZmVhY2RhZWMwMDA3MDFlOGQyIiwiaWQiOiI2MzhkYTBjMi1iNjg0LTRhN2UtOWRlNy1mNWUwODM0MTliNzcifQ==)


<details><summary>Browser metadata</summary>





```
Path:      /applications/61419cbd740775297f87aa63/pages/61419cbd740775297f87aa65/edit
Browser:   Chrome 93.0.4577.63 on Mac OS 10.15.7
Viewport:  1815 x 1209 @2x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-7361--appsmith-editor-ce.netlify.app%2Fapplications%2F61419cbd740775297f87aa63%2Fpages%2F61419cbd740775297f87aa65%2Fedit&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=93.0&resolution=1815x1209&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-7361--appsmith-editor-ce.netlify.app/applications/61419cbd740775297f87aa63/pages/61419cbd740775297f87aa65/edit) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=614192feacdaec000701e8d2&commentID=61419f91ed68166691a90814&resolution=resolved)

2021-09-15 07:31 UTC, LizHamburger commented
A few issues here:
1. When I add a widget I would expect the property pane to open instantly.
2. It feels strange that I'm clicking the button and the property pane isn't showing. It's not clear I have to specifically click the cog icon.
3. Selecting a datasource/query surprised me that it took me to that page but that maybe my lack of understanding in process.
4. Again having the canvas size present when you can't see the canvas doesn't feel like it makes sense.
5. When the entity explorer is unpinned having a back button in the top left makes it incredibly hard to get back quickly due to the hover area. I had to slow right down and then careful click the back button. 

![recording](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiZTVmZjliMzYtMjgzZS00MTU5LWE2ZjUtMTZiMjQyODA0M2E4IiwiZGVwbG95X2lkIjoiNjE0MTkyZmVhY2RhZWMwMDA3MDFlOGQyIiwiaWQiOiI3MTQzNmEyMi04MzJkLTRiMjAtODg1Ni1iNDY5MmY0NDI2MjQifQ==)


<details><summary>Browser metadata</summary>





```
Path:      /applications/61419cbd740775297f87aa63/pages/61419cbd740775297f87aa65/edit
Browser:   Chrome 93.0.4577.63 on Mac OS 10.15.7
Viewport:  1815 x 1209 @2x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-7361--appsmith-editor-ce.netlify.app%2Fapplications%2F61419cbd740775297f87aa63%2Fpages%2F61419cbd740775297f87aa65%2Fedit&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=93.0&resolution=1815x1209&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-7361--appsmith-editor-ce.netlify.app/applications/61419cbd740775297f87aa63/pages/61419cbd740775297f87aa65/edit) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=614192feacdaec000701e8d2&commentID=6141a14bddfc8d5defe97970&resolution=resolved)

2021-09-16 11:14 UTC, rahulramesha submitted a review, later dismissed
Approving for tests

2021-09-17 03:21 UTC, birrin-lgtm commented
> A few issues here:
> 
> 1. When I add a widget I would expect the property pane to open instantly.
> 2. It feels strange that I'm clicking the button and the property pane isn't showing. It's not clear I have to specifically click the cog icon.
> 3. Selecting a datasource/query surprised me that it took me to that page but that maybe my lack of understanding in process.
> 4. Again having the canvas size present when you can't see the canvas doesn't feel like it makes sense.
> 5. When the entity explorer is unpinned having a back button in the top left makes it incredibly hard to get back quickly due to the hover area. I had to slow right down and then careful click the back button.
> 
> ![recording](https://camo.githubusercontent.com/459ce3206f253de391e41a14eaf82a123ebc3de07963c449c625d9e24004ab6a/68747470733a2f2f6e65746c6966792d636f636f6f6e2e6e65746c6966792e6170702f2e6e65746c6966792f66756e6374696f6e732f66657463683f636f64653d33303726706174683d65794a7a6158526c58326c6b496a6f695a54566d5a6a6c694d7a59744d6a677a5a5330304d5455354c5745325a6a55744d545a694d6a51794f4441304d324534496977695a4756776247393558326c6b496a6f694e6a45304d546b795a6d5668593252685a574d774d4441334d44466c4f47517949697769615751694f6949334d54517a4e6d45794d6930344d7a4a6b4c5452694d6a41744f4467314e6931694e4459354d6d59304e4449324d6a516966513d3d)
> 
> Browser metadata
> [Open Deploy Preview](https://deploy-preview-7361--appsmith-editor-ce.netlify.app/applications/61419cbd740775297f87aa63/pages/61419cbd740775297f87aa65/edit) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=614192feacdaec000701e8d2&commentID=6141a14bddfc8d5defe97970&resolution=resolved)

Completely agreed. @LizHamburger has described the behavior missing in the current implementation which would make this property pane useful.

2021-09-29 07:03 UTC, marks0351 approved these changes

2021-09-29 10:00 UTC, marks0351 approved these changes

2021-09-29 10:32 UTC, rahulramesha submitted a review, later dismissed
Approving for tests

2021-10-01 05:59 UTC, aswathkk approved these changes
Approving to run tests

2021-10-01 06:00 UTC, marks0351 approved these changes

2021-10-01 09:54 UTC, marks0351 submitted a review, later dismissed

2021-10-04 12:07 UTC, marks0351 approved these changes

2021-10-06 05:42 UTC, marks0351 approved these changes

2021-11-01 12:27 UTC, riodeuno requested changes

2021-11-01 12:27 UTC, riodeuno commented on app/client/src/pages/AppViewer/viewer/PageTabs.tsx
> +  const getPageURL = (page: Page) => {
Let's move this out of the component.

2021-11-01 12:27 UTC, riodeuno commented on app/client/src/pages/Applications/index.tsx
> +    <LeftPaneWrapper className="">
Let's remove this className

2021-11-01 12:27 UTC, riodeuno commented on app/client/src/pages/Editor/CanvasPropertyPane/index.tsx
> +export const CanvasPropertyPane = memo(() => {
Let's remove memo here.

2021-11-01 12:27 UTC, riodeuno commented on app/client/src/pages/Editor/EditorHeader.tsx
> +                <div className="flex items-center justify-between">
Let's use messages.ts

2021-11-01 12:27 UTC, riodeuno commented on app/client/src/pages/Editor/GlobalHotKeys.tsx
> +  explorerPinned: boolean;
Let's rename this to isExplorerPinned

2021-11-01 12:27 UTC, riodeuno commented on app/client/src/pages/Editor/MainContainer.tsx
> +  const [sidebarWidth, setSidebarWidth] = useState(256);
Let's explain the constant, better yet, let's create a constant and use that.

2021-11-01 12:27 UTC, riodeuno commented on app/client/src/pages/Editor/MultiSelectPropertyPane/index.tsx
> +          Select a widget to see it&apos;s propertyies
Let's move this to messages.ts

2021-11-01 12:27 UTC, riodeuno commented on app/client/src/pages/Editor/PropertyPane/PropertyPaneConnections.tsx
> +        width={`100%`}
Let's remove the `{}`

2021-11-01 12:27 UTC, riodeuno commented on app/client/src/pages/Editor/PropertyPane/PropertyPaneConnections.tsx
>          selected={{ label: "", value: "" }}
Let's move this to a constant. This is creating a new object on every render.

2021-11-03 07:06 UTC, vivekverma2312 commented
@jsartisan 
1. Canvas size is big. By default we can not see “Drag and drop a widget” text on canvas
https://www.loom.com/share/69bdaf61d72f41a79106e91926471c4a

2. Underline below all property text is not proper
<img width="293" alt="Screenshot 2021-11-03 at 12 25 54 PM" src="https://user-images.githubusercontent.com/83569920/140020579-baf66cd9-2b55-41bd-a26c-e8e4165b86b7.png">

3. Columns name fields are not proper in table widget property pane
4. Drag icon and text is overlapping for column name fields on property pane

<img width="298" alt="Screenshot 2021-11-03 at 12 28 05 PM" src="https://user-images.githubusercontent.com/83569920/140020606-97cc66e1-49ec-483d-8043-4b8e9483a06a.png">

Testing is still in progress....

2021-11-04 06:45 UTC, vivekverma2312 commented
5. On hovering out going connections message complete message is not showing

<img width="200" alt="Screenshot 2021-11-03 at 12 37 36 PM" src="https://user-images.githubusercontent.com/83569920/140267254-dac8b57d-b020-47c2-816d-f4cb9690a5b4.png">

6. Dropdown at the bottom of the property pane should open from top of the field

<img width="348" alt="Screenshot 2021-11-03 at 12 39 41 PM" src="https://user-images.githubusercontent.com/83569920/140267280-e6a05470-022c-4db7-8b61-ebf58f6c9b73.png">

7. Resizing property pane do not show property pane
https://www.loom.com/share/ff7543f367e0431395158f4ad9bccf01

8. Toggle visible for column and then the data disappears from edit mode and complete table disappears in view mode
https://www.loom.com/share/66e0adc061b14f589f0361010404a261

2021-11-09 05:59 UTC, jsartisan commented
/ok-to-test sha=c238bbe

2021-11-09 06:00 UTC, jsartisan commented
action: https://github.com/appsmithorg/appsmith/runs/4148492651?check_suite_focus=true

2021-11-10 13:04 UTC, jsartisan commented
/ok-to-test sha=3885e6b

2021-11-10 13:04 UTC, jsartisan commented
https://github.com/appsmithorg/appsmith/actions/runs/1444262923

2021-11-11 05:00 UTC, jsartisan commented
/ok-to-test sha=771e12d

2021-11-11 05:00 UTC, jsartisan commented
https://github.com/appsmithorg/appsmith/actions/runs/1447408964

2021-11-15 07:23 UTC, jsartisan commented
/ok-to-test sha=a15826e

2021-11-16 06:27 UTC, YogeshJayaseelan commented
@jsartisan @vivekverma2312 

Issue 9 : When the widget name is longer then the copy and delete button in the property pane are hidden 

<img width="1680" alt="Screenshot 2021-11-16 at 11 50 52 AM" src="https://user-images.githubusercontent.com/35128442/141932936-dea1927b-4272-4a53-943f-88e450bd04f9.png">

2021-11-16 07:48 UTC, vivekverma2312 commented
@mohanarpit Is there any workaround that I can test the feature if build is failing? Please let us know if there is any way we can get unblocked with testing.
cc: @jsartisan

2021-11-16 07:56 UTC, vivekverma2312 commented
@jsartisan Few more know issues:
10. "OX" is displayed beside Text size property for all the widgets
<img width="349" alt="Screenshot 2021-11-16 at 1 26 17 PM" src="https://user-images.githubusercontent.com/83569920/141943944-025a1250-2476-4b78-8ad6-b7d641db1f3b.png">


11. On drag and multi select wrong message is displayed on docked pane
<img width="307" alt="Screenshot 2021-11-16 at 11 19 59 AM" src="https://user-images.githubusercontent.com/83569920/141943874-a3acd59e-f939-47ac-ba68-741ed4881c80.png">

2021-11-16 07:59 UTC, mohanarpit commented
> @mohanarpit Is there any workaround that I can test the feature if build is failing? Please let us know if there is any way we can get unblocked with testing. cc: @jsartisan

@vivekverma2312 I've raised a support ticket with Netlify to increase our build times. In the meantime, unfortunately, there is no other workaround apart from retrying the build and hoping that it completes in time.

2021-11-16 12:50 UTC, somangshu commented
/ok-to-test sha=7fe7510

2021-11-18 05:49 UTC, jsartisan commented
/ok-to-test sha=60d1350

2021-11-18 06:48 UTC, vivekverma2312 commented
@jsartisan 
14. While editing the JS query property pane flickers
15. No suggestion pop up is getting cropped
For issue 14 and 15 -> https://www.loom.com/share/4d8f648ae82843e3a00f5c75ad98ad28

2021-11-18 07:28 UTC, YogeshJayaseelan commented
@jsartisan Raised separate enhancement for issue 12 - #9227

2021-11-18 09:04 UTC, vivekverma2312 commented
@jsartisan 17. Properties for Video widget is only displayed when user clicks on Widget name
https://www.loom.com/share/f86563b9b96a42a4bca26bff4f43f1c8

2021-11-18 10:47 UTC, YogeshJayaseelan commented
@jsartisan Issue 18 - When the user tries to place any of the widget on the left or right side edges when the horizontal scroll is available the widget DND positioning/scrolling left and right is not happening 

https://www.loom.com/share/4af8ae27f4ff44068cd90792580bf72c

2021-11-18 10:52 UTC, YogeshJayaseelan commented
@jsartisan Raised separate issue for point 13 - #9237

2021-11-19 05:22 UTC, jsartisan commented
/ok-to-test sha=f8b8f59

2021-11-19 05:32 UTC, jsartisan commented
/ok-to-test sha=a0abe79

2021-11-19 10:37 UTC, vivekverma2312 commented
@jsartisan We have raised separate issue for issue 15 & 18. Rest of the issues are fixed.

2021-11-19 12:59 UTC, jsartisan commented
/ok-to-test sha=b31e9fb

2021-11-19 15:08 UTC, NandanAnantharamu commented
/ok-to-test sha=b31e9fb

2021-11-19 15:23 UTC, NandanAnantharamu commented
/ok-to-test sha=b31e9fb

2021-11-22 05:18 UTC, jsartisan commented
/ok-to-test sha=b31e9fb

2021-11-22 05:19 UTC, jsartisan commented
/ok-to-test sha=b31e9fb

2021-11-23 04:47 UTC, jsartisan commented
/ok-to-test sha=d6ee214

2021-11-23 06:14 UTC, jsartisan commented
/ok-to-test sha=4ae1724

2021-11-23 07:59 UTC, riodeuno approved these changes

2021-11-23 08:01 UTC, merged