feature: 6770 new column type switch
appsmithorg/appsmith pull request #7364
Opened 2021-09-13 06:07 UTC by vibhandikyash

## Description

> Enable New Column type switch in table

Fixes #6770 

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

> Tested locally.
> Added test cases.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-09-15 06:06 UTC, SatishGandham requested changes
Issue only talks about adding the switch column type.
Are we doing the select as well?

2021-09-15 06:06 UTC, SatishGandham commented on app/client/src/widgets/TableWidget/widget/index.tsx
> +    const editedColumnData = cloneDeep(this.props.editedColumnData);
Is cloneDeep required here, as long as the evaluation is triggered immer will take care of this.

2021-09-16 04:20 UTC, vibhandikyash commented
@SatishGandham Actually that is another ticket but since we need some common code to be used we are merging that branch here.

2021-09-21 06:22 UTC, SatishGandham submitted a review, later dismissed

2022-01-24 10:44 UTC, vibhandikyash commented
Closing this PR. Feature will be reopened with TableV2.

2022-01-24 10:44 UTC, closed without merging