fix: disable sorting in view mode
appsmithorg/appsmith pull request #7387
Opened 2021-09-13 14:32 UTC by Tooluloope

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.

## Description

disable sorting in view mode

Fixes #5640

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-09-15 05:59 UTC, SatishGandham requested changes

2021-09-15 05:59 UTC, SatishGandham commented on app/client/src/widgets/TableWidget/component/TableUtilities.tsx
> +      onClick={props.editMode !== false ? handleSortColumn : undefined}
Can we not write this as       `onClick={props.editMode ? handleSortColumn : undefined}`

Also, won't this disable sorting in view mode completely?

2021-09-15 06:12 UTC, Tooluloope commented on app/client/src/widgets/TableWidget/component/TableUtilities.tsx
> +      onClick={props.editMode !== false ? handleSortColumn : undefined}
@SatishGandham , I think the issue is to disable sorting in view mode.

2021-09-15 07:29 UTC, SatishGandham commented on app/client/src/widgets/TableWidget/component/TableUtilities.tsx
> +      onClick={props.editMode !== false ? handleSortColumn : undefined}
Issue says when it can break the table, so there should be an option to disable sorting.
Do we store sorting state in the edit mode when we sort columns?

2021-09-15 07:33 UTC, Tooluloope commented on app/client/src/widgets/TableWidget/component/TableUtilities.tsx
> +      onClick={props.editMode !== false ? handleSortColumn : undefined}
Oh, So just a switch in the property pane.
Shouldn't we just tackle why the table breaks, cos users might not know the real reason for disabling sorting

2021-09-16 05:51 UTC, somangshu commented
@Tooluloope the sorting disabled needs to be a configurable option, The dev can choose to do so for the end user. Hence, we need to provide the option to do so from the property pane

2021-09-30 07:55 UTC, SatishGandham commented on app/client/src/widgets/TableWidget/component/TableUtilities.tsx
> +  const disableSort = useMemo(() => {
We don't need a memo here. It is only required it is going to return a new object with same value or if we are doing expensive calculations. 
Here it is a primitive value.

2021-10-01 05:59 UTC, SatishGandham requested changes

2021-10-01 05:59 UTC, SatishGandham commented on app/client/src/widgets/TableWidget/component/TableUtilities.tsx
> +  const disableSort = useMemo(() => {
I don't see any changes?

2021-10-01 06:51 UTC, Tooluloope commented on app/client/src/widgets/TableWidget/component/TableUtilities.tsx
> +  const disableSort = useMemo(() => {
@SatishGandham I have removed it.
Not sure why github still showing this on your end
<img width="1047" alt="Screenshot 2021-10-01 at 07 49 50" src="https://user-images.githubusercontent.com/31691737/135577807-4f7db5dd-b0ba-4551-93e8-1d82ac87404b.png">

2021-10-01 09:20 UTC, SatishGandham submitted a review, later dismissed

2021-10-09 10:17 UTC, Tooluloope commented
@YogeshJayaseelan Fixed

2021-10-19 05:05 UTC, YogeshJayaseelan commented
@Tooluloope Verified the fix and the sorting toggle is working as expected

2021-10-29 04:54 UTC, SatishGandham submitted a review, later dismissed

2021-11-01 04:52 UTC, Tooluloope commented
/ok-to-test sha=29d0784

2021-11-01 12:04 UTC, Tooluloope commented
/ok-to-test sha=7141CC5

2021-11-03 10:56 UTC, Tooluloope commented
/ok-to-test sha=7141CC5

2021-11-03 11:17 UTC, riodeuno requested changes

2021-11-03 11:17 UTC, riodeuno commented on app/client/src/utils/DSLMigrations.ts
>      currentDSL.version = LATEST_PAGE_VERSION;
This needs to change to 44 from `LATEST_PAGE_VERSION`

2021-11-03 11:17 UTC, riodeuno commented
@Tooluloope I have one change requested. I believe @SatishGandham has already reviewed, this so I'll remove myself from the reviewers list.

2021-11-04 09:43 UTC, Tooluloope commented on app/client/src/utils/DSLMigrations.ts
> +  if (currentDSL.version === 44) {
@riodeuno we're using 44 here already

2021-11-04 09:43 UTC, Tooluloope commented
/ok-to-test sha=33b65f0

2021-11-09 04:50 UTC, SatishGandham approved these changes

2021-11-09 05:08 UTC, merged