feat: Added new column type in table for checkbox
appsmithorg/appsmith pull request #7409
Opened 2021-09-14 09:19 UTC by vibhandikyash

## Description

> Added new column type for to support checkbox

Fixes #7338 

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Tested locally.
- Added test cases.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-09-16 07:18 UTC, marks0351 requested changes

2021-09-16 07:18 UTC, marks0351 commented on app/client/src/widgets/TableWidget/component/TableUtilities.tsx
> +        label={props.label || "Label"}
wouldn't it restrict the user from not setting a label?

2021-09-16 07:18 UTC, marks0351 commented on app/client/src/widgets/TableWidget/component/TableUtilities.tsx
> +        onChange={(isSwitchedOn: boolean) => {
pls add this as a function instead of keeping it anonymous.

2021-09-16 07:18 UTC, marks0351 commented on app/client/src/widgets/TableWidget/component/TableUtilities.tsx
> +        label={props.label || "Label"}
same as switch. label cannot be removed.

2021-09-16 07:18 UTC, marks0351 commented on app/client/src/widgets/TableWidget/component/TableUtilities.tsx
> +        onCheckChange={(isChecked: boolean) => {
declare the function

2021-09-16 07:18 UTC, marks0351 commented on app/client/src/widgets/TableWidget/widget/index.tsx
> +      // shape : { [columnId]: { [rowIndex]: value, ... }, ...}
remove comments unless they explain something.

2021-09-16 07:19 UTC, marks0351 commented
@vibhandikyash The checkbox in the table is not centered. also in short height mode it is seen cutoff.  Text font size styles of table dont seem to be applying on checkbox but works on switch need to be consistent.

2021-09-23 15:12 UTC, somangshu approved these changes
Approving to run tests

2021-10-13 05:27 UTC, riodeuno commented
- [ ] The checkbox and switch values are not getting updated correctly.
- [ ] Clicking on the checkbox selects the row

https://user-images.githubusercontent.com/103687/137072540-3cab263f-478e-4a60-9921-8d35b0bb73ee.mov

2022-01-24 10:44 UTC, vibhandikyash commented
Closing this PR. Feature will be reopened with TableV2.

2022-01-24 10:44 UTC, closed without merging