feat: Added new column type for rating
appsmithorg/appsmith pull request #7489
Opened 2021-09-16 04:34 UTC by vibhandikyash

## Description

> Added new column type for a rating in the table.

Fixes #6764

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

> Tested locally.
> Added Test Cases.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-09-21 06:24 UTC, SatishGandham commented on app/client/src/widgets/TableWidget/component/Constants.ts
> +  defaultOptionValue?: string;
What is default option value?

2021-09-21 06:26 UTC, SatishGandham requested changes
Shouldn't the switch just be a boolean? Why does it have a value?

2021-09-21 10:33 UTC, vibhandikyash commented on app/client/src/widgets/TableWidget/component/Constants.ts
> +  defaultOptionValue?: string;
Its for select not related to rating. Since the Select PR is merged here you are seeing that changes.

2021-09-22 06:01 UTC, riodeuno commented on app/client/src/widgets/TableWidget/component/Constants.ts
> +  defaultOptionValue?: string;
@vibhandikyash Have we merged the selected PR into this PR? If it is merged into `release` we shouldn't be seeing this change here. Are these changes fixing something on release?

2021-09-22 06:12 UTC, riodeuno requested changes

2021-09-22 06:12 UTC, riodeuno commented on app/client/src/widgets/TableWidget/component/TableUtilities.tsx
> +          onOptionSelected={(optionSelected) => {
Let's `useCallback` here

2021-09-22 06:12 UTC, riodeuno commented on app/client/src/widgets/TableWidget/component/TableUtilities.tsx
> +        onChange={(isSwitchedOn: boolean) => {
Let's `useCallback` here.

2021-09-22 06:12 UTC, riodeuno commented on app/client/src/widgets/TableWidget/component/TableUtilities.tsx
> +      onClick={(e) => {
Here and in the following function props, let's use `useCallback`.

2021-09-22 06:12 UTC, riodeuno commented on app/client/src/widgets/TableWidget/widget/derived.js
> +            sanitizedData[sanitizedKey] =
Please add a jest test in the `derived.test.js` file so that I can understand what we're doing here.

2021-10-13 05:37 UTC, riodeuno commented
- [ ] Table crashes when filtering with the rate column. Please verify this with other column types as well.
<img width="982" alt="Screenshot 2021-10-13 at 11 05 56 AM" src="https://user-images.githubusercontent.com/103687/137073474-ca429e52-5864-4789-ae24-a411730ed33f.png">

- [ ] Rating options do not show until we provide it with a value.
- [ ] Selecting a rating seems to select the row as well. @somangshu Is this feature intentional across all column types?
<img width="982" alt="Screenshot 2021-10-13 at 11 04 40 AM" src="https://user-images.githubusercontent.com/103687/137073457-e192b9e0-99d9-4645-9d95-0950c3fc041d.png">

2022-01-24 10:44 UTC, vibhandikyash commented
Closing this PR. Feature will be reopened with TableV2.

2022-01-24 10:44 UTC, closed without merging