Fix/popups same width as parent
appsmithorg/appsmith pull request #7499
Opened 2021-09-16 06:42 UTC by Tooluloope

## Description

Make popups have a min-width as the Parent Container

Fixes #6609 

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-09-17 06:18 UTC, somangshu submitted a review, later dismissed
Approving to run tests

2021-09-17 06:18 UTC, somangshu commented on app/client/src/widgets/DropdownWidget/component/index.tsx
> +        <DropdownStyles parentWidth={this.props.width - 7} />
Why do we subtract a hardcoded value here?

2021-09-17 06:18 UTC, somangshu commented on app/client/src/widgets/MenuButtonWidget/component/index.tsx
> +       parentWidth > 180 ? `${parentWidth}px` : "180px"} ;
For the sake of consistency, we should have min width consistent for all the widget popups

@jsartisan @momcilo-appsmith need your help reviewing this.

2021-09-17 06:18 UTC, somangshu commented on app/client/src/widgets/DropdownWidget/component/index.tsx
> +      parentWidth > 269 ? `${parentWidth}px` : "269px"} ;
The behaviour is still different for the multi-select widget.

@marks0351 does this look like the right way to move forward?

2021-09-17 06:19 UTC, somangshu commented
@Tooluloope can we add cypress tests for these?

2021-09-17 06:25 UTC, marks0351 requested changes

2021-09-17 06:25 UTC, marks0351 commented on app/client/src/widgets/DropdownWidget/component/index.tsx
> +      parentWidth > 269 ? `${parentWidth}px` : "269px"} ;
@Tooluloope what does the value 269 indicate?

2021-09-17 06:25 UTC, marks0351 commented on app/client/src/widgets/MenuButtonWidget/component/index.tsx
> +       parentWidth > 180 ? `${parentWidth}px` : "180px"} ;
@Tooluloope what does 180 indicate?

2021-09-17 06:37 UTC, Tooluloope commented on app/client/src/widgets/MenuButtonWidget/component/index.tsx
> +       parentWidth > 180 ? `${parentWidth}px` : "180px"} ;
Current min-width of the popups

2021-09-17 06:37 UTC, Tooluloope commented on app/client/src/widgets/DropdownWidget/component/index.tsx
> +      parentWidth > 269 ? `${parentWidth}px` : "269px"} ;
Current min-width of the popups

2021-09-17 06:38 UTC, Tooluloope commented on app/client/src/widgets/DropdownWidget/component/index.tsx
> +      parentWidth > 269 ? `${parentWidth}px` : "269px"} ;
We could have a consistent value, but I'm not sure it would valid for all popups

2021-09-18 00:03 UTC, momcilo-appsmith commented
@somangshu the latest deploy preview is not working for me.

2021-09-20 06:43 UTC, Tooluloope commented
@momcilo-appsmith here the [link](https://deploy-preview-7499--appsmith-editor-ce.netlify.app/user/login)

2021-09-28 12:34 UTC, Tooluloope commented on app/client/src/widgets/DropdownWidget/component/index.tsx
> +        <DropdownStyles parentWidth={this.props.width - 7} />
@somangshu The space between the Component itself and the Widget Container

![Screenshot 2021-09-28 at 13 32 32](https://user-images.githubusercontent.com/31691737/135087498-d82e9a1e-8fc5-429b-a217-83d986df5ec9.png)

2021-09-28 12:39 UTC, Tooluloope commented
@momcilo-appsmith have you been able to use the Deploy preview link?

2021-10-04 08:34 UTC, Tooluloope commented
@somangshu @marks0351 Here's an update on the Dropdown https://www.figma.com/file/w9CaXHF5iYcrLtiEbAHcFu/Original-Theme-Widgets-Library?node-id=428%3A3414

2021-10-04 08:34 UTC, Tooluloope commented
@somangshu @marks0351 Here's an update on the Dropdown https://www.figma.com/file/w9CaXHF5iYcrLtiEbAHcFu/Original-Theme-Widgets-Library?node-id=428%3A3414

2021-11-01 06:15 UTC, marks0351 approved these changes

2021-11-01 06:36 UTC, Tooluloope commented
/ok-to-test sha=db26952

2021-11-01 08:30 UTC, vivekverma2312 commented
@Tooluloope 1. Minimum width of pop up for different widget is different (In screenshot I have set the widget size to there minimum width)
<img width="343" alt="Screenshot 2021-11-01 at 1 45 28 PM" src="https://user-images.githubusercontent.com/83569920/139641973-c87ed13e-1f47-4214-a5ed-a3eb590fa272.png">

2. Pop up size for menu button changes after we drag and drop another Menu button widget on canvas
<img width="1289" alt="Screenshot 2021-11-01 at 1 47 56 PM" src="https://user-images.githubusercontent.com/83569920/139642407-b1c5c3d2-de65-4965-a8a6-858ac1d1d4c7.png">
<img width="1322" alt="Screenshot 2021-11-01 at 1 47 39 PM" src="https://user-images.githubusercontent.com/83569920/139642415-b7d5b455-f153-400f-b2f0-71892426094c.png">

3. Pop up is of not the same size as widget when  placed in any container

<img width="492" alt="Screenshot 2021-11-01 at 1 51 34 PM" src="https://user-images.githubusercontent.com/83569920/139643178-e438e030-bda0-409e-b39a-e22108b814e8.png">

2021-11-01 15:18 UTC, Tooluloope commented
@vivekverma2312 Fixed ALL

2021-11-02 05:58 UTC, Tooluloope commented
/ok-to-test sha=de79b52

2021-11-02 06:38 UTC, marks0351 commented
> @Tooluloope 1. Minimum width of pop up for different widget is different (In screenshot I have set the widget size to there minimum width) <img alt="Screenshot 2021-11-01 at 1 45 28 PM" width="343" src="https://user-images.githubusercontent.com/83569920/139641973-c87ed13e-1f47-4214-a5ed-a3eb590fa272.png">
> 
> 1. Pop up size for menu button changes after we drag and drop another Menu button widget on canvas
> 
> <img alt="Screenshot 2021-11-01 at 1 47 56 PM" width="1289" src="https://user-images.githubusercontent.com/83569920/139642407-b1c5c3d2-de65-4965-a8a6-858ac1d1d4c7.png">
> 
> <img alt="Screenshot 2021-11-01 at 1 47 39 PM" width="1322" src="https://user-images.githubusercontent.com/83569920/139642415-b7d5b455-f153-400f-b2f0-71892426094c.png">
> 
> 1. Pop up is of not the same size as widget when  placed in any container
> 
> <img alt="Screenshot 2021-11-01 at 1 51 34 PM" width="492" src="https://user-images.githubusercontent.com/83569920/139643178-e438e030-bda0-409e-b39a-e22108b814e8.png">

@Tooluloope were these not tested in the test cases?

2021-11-02 06:42 UTC, Tooluloope commented
I tested for only Select and Menu button, DIdn't know MUltiSelect, MultiTreeSelect, and TreeSelect was to be covered.

PR description states only Select and Menubutton

2021-11-02 06:45 UTC, marks0351 commented
> I tested for only Select and Menu button, DIdn't know MUltiSelect, MultiTreeSelect, and TreeSelect was to be covered.
> 
> PR description states only Select and Menubutton

got it. can we pls add tests for them as well, will make sure we have protection over these widgets as well.

2021-11-03 06:47 UTC, vivekverma2312 commented
@Tooluloope  Above issues are fixed but observed other issues now
4. Pop up size is not same for Menu Button widget inside the container by default
<img width="552" alt="Screenshot 2021-11-03 at 12 10 22 PM" src="https://user-images.githubusercontent.com/83569920/140018624-0469b027-4130-4d0b-9faf-f6118786fbe1.png">

5. The drop down options for multi-select widget inside container is not coming proper
<img width="177" alt="Screenshot 2021-11-03 at 12 09 45 PM" src="https://user-images.githubusercontent.com/83569920/140018724-1ebdf07b-f378-43d9-90e2-02bf8c15242c.png">

2021-11-04 10:42 UTC, Tooluloope commented
/ok-to-test sha=9bc41eb

2021-11-09 07:46 UTC, vivekverma2312 commented
@Tooluloope Fix are working fine on Deploy Preview.

2021-11-10 16:39 UTC, Tooluloope commented
/ok-to-test sha=9bc41eb

2021-11-13 07:17 UTC, Tooluloope commented
/ok-to-test sha=f5e3f77

2021-11-14 09:08 UTC, Tooluloope commented
/ok-to-test sha=a811fd3

2021-11-17 08:00 UTC, marks0351 submitted a review, later dismissed

2021-11-17 11:01 UTC, Tooluloope commented
/ok-to-test sha=8133d04

2021-11-17 11:27 UTC, marks0351 submitted a review, later dismissed

2021-11-22 05:16 UTC, marks0351 commented
@Tooluloope can you pls resolve conflicts

2021-11-22 19:17 UTC, Tooluloope commented
/ok-to-test sha=d4ee816

2021-11-25 08:56 UTC, marks0351 approved these changes

2021-11-25 09:56 UTC, Tooluloope commented
/ok-to-test sha=dd4a878

2021-11-29 07:48 UTC, Tooluloope commented
/ok-to-test sha=b580a10

2021-11-30 06:55 UTC, marks0351 approved these changes

2021-11-30 10:38 UTC, merged