Feat: switch group widget
appsmithorg/appsmith pull request #7590
Opened 2021-09-18 11:22 UTC by wmdev0808

## Description
Allow users to create a list of switch widgets so that they can easily use them in a form.

Fixes #3350

## Type of change

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

## How Has This Been Tested?

- Test A
- Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-09-20 06:22 UTC, riodeuno requested changes
@wmdev0808 Nice work with this widget! I've partially reviewed this. I'll review the rest of the files today.

2021-09-20 06:22 UTC, riodeuno commented on app/client/src/widgets/SwitchGroupWidget/widget/index.tsx
> +        sectionName: "General",
@wmdev0808 Let's add a cypress test case to test each of the following properties.

2021-09-20 06:22 UTC, riodeuno commented on app/client/src/widgets/SwitchGroupWidget/widget/index.tsx
> +      widgetId: string;
Let's create a new type called `SwtichItemConfig`. And let's configure this `groupItems: Record<string, SwitchItemConfig>`

2021-09-21 05:45 UTC, somangshu commented
@wmdev0808 feedback from the deploy preview:

- The switch widget does not function, cant change value (happens until we add a new option)
- The default widget size on drag and drop should be minimum rows
- Adding new item crashes the app (critical issue)
- The accessibility to the key / value pair should be similar compared to the checkbox group / radio group
- A default selected option should be provided
- The icon for the widget needs to be created
- Expose `required` API
- Maintain the property order (consistent to other group widgets)

2021-09-21 13:22 UTC, somangshu requested changes

2021-09-21 13:22 UTC, somangshu commented on app/client/src/widgets/SwitchGroupWidget/widget/index.tsx
> +            helpText: "Selects values of the options checked by default",
Add here > `Enter comma separated values for multiple selected`

2021-09-21 13:54 UTC, somangshu submitted a review, later dismissed

2021-09-21 23:48 UTC, momcilo-appsmith commented
Here is the icon design: https://www.figma.com/file/i80YbQLLs5mXthjIHclPpX/Appsmith-Design-System?node-id=3172%3A13666

2021-09-22 05:59 UTC, riodeuno requested changes
A few changes requested. We need comprehensive cypress tests here for the following:
- All properties of the widget
- The new property control

2021-09-22 05:59 UTC, riodeuno commented on app/client/src/components/propertyControls/ItemsControl.tsx
> +          debouncedUpdate(index, value);
Let's use `useCallback` here as well as the `deleteOption` on line 99.

2021-09-22 05:59 UTC, riodeuno commented on app/client/src/components/propertyControls/ItemsControl.tsx
> +    this.updateProperty(this.props.propertyName, updatedObj);
The look and feel of this control is not consistent with the other controls. 
@momcilo-appsmith @somangshu Is there a reason why we're adding a new control here and not going with what we have in the select widget?
<img width="250" alt="Screenshot 2021-09-22 at 11 21 13 AM" src="https://user-images.githubusercontent.com/103687/134290180-b2eb6b99-946c-4c87-8ac1-cfd4abf01ee4.png">

2021-09-22 05:59 UTC, riodeuno commented on app/client/src/widgets/SwitchGroupWidget/component/index.tsx
> +        [...options].map((option: OptionProps) => (
Is there a reason we have to spread this here? I believe we can do without the spread.

2021-09-22 05:59 UTC, riodeuno commented on app/client/src/widgets/SwitchGroupWidget/component/index.tsx
> +            key={generateReactKey()}
These keys will be different for every render. Can we make this consistent until the options change? For example, use the options value or any other value which will be unique among siblings but consistent across renders if the values don't change?

2021-09-22 05:59 UTC, riodeuno commented on app/client/src/widgets/SwitchGroupWidget/component/index.tsx
> +            checked={(selectedValues || []).includes(option.value)}
Is it possible to have a default for the `selectedValues`? That way we won't have to do `selectedValues || []`

2021-09-22 05:59 UTC, riodeuno commented on app/client/src/widgets/SwitchGroupWidget/icon.svg
> +<path fill-rule="evenodd" clip-rule="evenodd" d="M11 12C11 10.8954 10.1046 10 9 10H6C4.89543 10 4 10.8954 4 12C4 13.1046 4.89543 14 6 14H9C10.1046 14 11 13.1046 11 12ZM9 13C9.55228 13 10 12.5523 10 1
Please use an online SVG optimiser to create a smaller SVG file here.

2021-09-22 06:02 UTC, somangshu commented on app/client/src/components/propertyControls/ItemsControl.tsx
> +    this.updateProperty(this.props.propertyName, updatedObj);
@riodeuno for all group widgets this has been the default. In case we take a call to remove this control then it can be taken up separately considering all widgets

2021-09-22 12:05 UTC, wmdev0808 commented on app/client/src/components/propertyControls/ItemsControl.tsx
> +          debouncedUpdate(index, value);
This control should be removed

2021-09-22 12:06 UTC, wmdev0808 commented on app/client/src/components/propertyControls/ItemsControl.tsx
> +    this.updateProperty(this.props.propertyName, updatedObj);
This control should be removed because the current implementation does not use this control anymore

2021-09-22 13:32 UTC, wmdev0808 commented on app/client/src/widgets/SwitchGroupWidget/component/index.tsx
> +        [...options].map((option: OptionProps) => (
You're right, thank you

2021-09-22 13:43 UTC, somangshu commented on app/client/src/components/propertyControls/ItemsControl.tsx
> +    this.updateProperty(this.props.propertyName, updatedObj);
@wmdev0808 what do you mean by "current implementation does not use this control anymore"?

2021-09-22 14:02 UTC, wmdev0808 commented on app/client/src/widgets/SwitchGroupWidget/component/index.tsx
> +        [...options].map((option: OptionProps) => (
You're right, thank you

2021-09-22 14:18 UTC, wmdev0808 commented on app/client/src/widgets/SwitchGroupWidget/component/index.tsx
> +            key={generateReactKey()}
Agree with you, thank you

2021-09-22 14:21 UTC, wmdev0808 commented on app/client/src/widgets/SwitchGroupWidget/component/index.tsx
> +            checked={(selectedValues || []).includes(option.value)}
It was just my mess, selectedValues are always an array, thank you

2021-09-22 14:26 UTC, wmdev0808 commented on app/client/src/widgets/SwitchGroupWidget/icon.svg
> +<path fill-rule="evenodd" clip-rule="evenodd" d="M11 12C11 10.8954 10.1046 10 9 10H6C4.89543 10 4 10.8954 4 12C4 13.1046 4.89543 14 6 14H9C10.1046 14 11 13.1046 11 12ZM9 13C9.55228 13 10 12.5523 10 1
I am just using the svg from the design which is provided by other guys.
That's why, it would be better if any designer can provide me with the new optimized one

2021-09-23 10:43 UTC, somangshu commented
@momcilo-appsmith i think we need the light version of the icon, the color doesn't match others, From the same file attached can you create the light version, Like done for others?

2021-09-23 10:45 UTC, momcilo-appsmith commented
Here is the light version: https://www.figma.com/file/i80YbQLLs5mXthjIHclPpX/Appsmith-Design-System?node-id=3253%3A13655. Attached to the issue as well.

2021-09-23 10:53 UTC, somangshu commented on app/client/src/widgets/SwitchGroupWidget/icon.svg
> +<path fill-rule="evenodd" clip-rule="evenodd" d="M11 12C11 10.8954 10.1046 10 9 10H6C4.89543 10 4 10.8954 4 12C4 13.1046 4.89543 14 6 14H9C10.1046 14 11 13.1046 11 12ZM9 13C9.55228 13 10 12.5523 10 1
This is done

2021-09-23 10:54 UTC, somangshu submitted a review, later dismissed
Icon replaced, Approving to run tests

2021-09-23 15:21 UTC, riodeuno requested changes
Everything looks great! We have cypress tests, the code hierarchy is good.

I have one comment about the `defaultSelectedValues` property, as well as a request for unit tests for a function.

2021-09-23 15:21 UTC, riodeuno commented on app/client/src/widgets/SwitchGroupWidget/widget/index.tsx
> +                  example: `value1 | ['value1', 'value2']`,
@wmdev0808 I was wondering if the defaultSelectedValues would always be an array? Is there a scenario where `value1` in the example make sense?

If this is always going to be an array, then we don't need to use `ValidationTypes.FUNCTION` and we can use a standard `ValidationTypes.ARRAY` with detailed configurations.

I'm asking this because, we want to avoid `ValidationTypes.FUNCTION` where possible.

2021-09-23 20:10 UTC, wmdev0808 commented on app/client/src/widgets/SwitchGroupWidget/widget/index.tsx
> +                  example: `value1 | ['value1', 'value2']`,
Users are allowed to input string or array for this field like this: 
- value1[, value2, ... value_n]
- [value1[, value2, ...value_n]
=> This means that neither ValidationTypes.TEXT nor ValidationTypes.ARRAY is fit for this scenario.

defaultSelectedValues are always evaluated as an array by that validation function, I think.

2021-09-23 21:07 UTC, riodeuno commented on app/client/src/widgets/SwitchGroupWidget/widget/index.tsx
> +                  example: `value1 | ['value1', 'value2']`,
Hmm, maybe I'm missing something here. @somangshu I believe the Switch Widget should work with `defaultSelected` while, Switch Group Widget should work with only arrays `defaultSelectedValues`. Can you let me know if there is a reason for this to not be the case?

2021-09-24 09:42 UTC, somangshu commented on app/client/src/widgets/SwitchGroupWidget/widget/index.tsx
> +                  example: `value1 | ['value1', 'value2']`,
I agree that the default can we the array in case of switch / checkbox group. However even comma separated string works. 
I will support the argument to have default as array here! @wmdev0808 what do you think? I dont see any specific use case of this to be string

2021-09-24 09:48 UTC, wmdev0808 commented on app/client/src/widgets/SwitchGroupWidget/widget/index.tsx
> +                  example: `value1 | ['value1', 'value2']`,
@somangshu I think it is just for UX
My concern is how we can handle the validation without using function.
We are required to refer to `options` property for validation.
@riodeuno , What's your solution for the above?

2021-09-24 10:11 UTC, riodeuno commented on app/client/src/widgets/SwitchGroupWidget/widget/index.tsx
> +                  example: `value1 | ['value1', 'value2']`,
@wmdev0808 I was wondering if we can remove the need for the `defaultSelectedValues` to be a string. This way, we can use `ValidationTypes.ARRAY` to validate `defaultSelectedValues`.

@somangshu I believe the same applies for the select widget, however, i believe we still support arrays in the Select Widget for backwards compatibility. Here, we'd like to get this right from the get go.

2021-09-24 10:13 UTC, wmdev0808 commented on app/client/src/widgets/SwitchGroupWidget/widget/index.tsx
> +                  example: `value1 | ['value1', 'value2']`,
@riodeuno Please provide me with the validation config parameters for better understanding

2021-09-24 10:18 UTC, riodeuno commented on app/client/src/widgets/SwitchGroupWidget/widget/index.tsx
> +                  example: `value1 | ['value1', 'value2']`,
This means that the expected value will be `['value1', 'value2']` or `Array<string>`
`{ type: ValidationTypes.ARRAY, params: { default: [], children: { type: ValidationTypes.TEXT } }` 
Something like this? This will make the expected value `Array<string>`

If we really want to validate by checking if the `defaultSelectedValues` exist in the `options`, at runtime, then we can still use `ValidationTypes.FUNCTION` but validate only array. This will make the expected value `['value1', 'value2']`

2021-09-24 10:19 UTC, riodeuno commented on app/client/src/widgets/SwitchGroupWidget/widget/index.tsx
> +                  example: `value1 | ['value1', 'value2']`,
Please let me know if these will not work.

2021-09-24 10:27 UTC, wmdev0808 commented on app/client/src/widgets/SwitchGroupWidget/widget/index.tsx
> +                  example: `value1 | ['value1', 'value2']`,
@riodeuno Got it.
After all, you just want to validate Array<string>.
Now, am I required to revise the code base for your suggestion?

2021-09-27 05:51 UTC, riodeuno commented on app/client/src/widgets/SwitchGroupWidget/widget/index.tsx
> +                  example: `value1 | ['value1', 'value2']`,
According to the example in the current validation function, we're validating `string[]` as the type. 
The question is, are we trying to validate if the `defaultSelectedValues` exist in the `options` as well, or are we simply validating if the value is a `string[]`. If it is the latter, then we can go with the validation configuration instead of function. If it is the former, we can update the function to make such checks, and still keep the expected value as `string[]`

2021-09-29 06:53 UTC, somangshu commented
@riodeuno kindly review the changes here

2021-09-29 07:02 UTC, riodeuno requested changes

2021-09-29 07:02 UTC, riodeuno commented on app/client/src/widgets/SwitchGroupWidget/widget/index.tsx
> +            helpText: "Makes input to the widget mandatory",
Does this property mean that this switch has to be turned "on" when inside a form? If that is the case, can we change the helpText like so:

`Turning this property on is mandatory for this field to be valid, inside a form widget`

2021-09-29 07:02 UTC, riodeuno commented
@vivekverma2312 we might want to start QA for this widget.

2021-09-29 07:03 UTC, riodeuno commented on app/client/src/utils/AppsmithUtils.tsx
> +export const getCamelCaseString = (sourceString: string) => {
I don't see the jest test for this. Can we add this?

2021-09-29 08:09 UTC, wmdev0808 commented on app/client/src/widgets/SwitchGroupWidget/widget/index.tsx
> +              "Selects values of the options checked by default. Enter comma separated values for multiple selected",
> We're validating an array here. Will comma separated values work?

No, it is just validating string[]

2021-09-29 08:11 UTC, wmdev0808 commented on app/client/src/widgets/SwitchGroupWidget/widget/index.tsx
> +              type: ValidationTypes.BOOLEAN,
done

2021-09-29 08:13 UTC, wmdev0808 commented on app/client/src/widgets/SwitchGroupWidget/widget/index.tsx
> +            helpText: "Makes input to the widget mandatory",
I think so. @somangshu Please confirm this

2021-09-29 08:34 UTC, Tooluloope commented on app/client/src/widgets/SwitchGroupWidget/widget/index.tsx
> +              "Selects values of the options checked by default. Enter comma separated values for multiple selected",
@riodeuno  Here the validation would pass, but the component would fail, cos the Component expects `Array<{ "label": "string", "value": "string" }>`

So it's either we handle it Validation Level or Handle it component level

![Screenshot 2021-09-29 at 09 31 06](https://user-images.githubusercontent.com/31691737/135232503-9bbad1d1-06b6-4f43-993e-a77a937e373e.png)
![Screenshot 2021-09-29 at 09 30 25](https://user-images.githubusercontent.com/31691737/135232490-488bab2c-fd7b-4957-a2ab-658ae8a28e5d.png)

2021-09-29 08:54 UTC, Tooluloope commented on app/client/src/widgets/SwitchGroupWidget/widget/index.tsx
> +            controlType: "OPTION_INPUT",
This Control type still has this issue https://www.loom.com/share/f32e748f48754b768df2ccc22eb148d5 
@riodeuno, should we still use this?

2021-09-29 09:13 UTC, somangshu commented on app/client/src/widgets/SwitchGroupWidget/widget/index.tsx
> +            helpText: "Makes input to the widget mandatory",
@riodeuno I believe the UX right now is currently inline to what already happens on Appsmith right now. I see that none of the widget inside the form widget automatically turn required in the form widget so the above message change should not be required.

2021-10-21 06:59 UTC, riodeuno commented
@wmdev0808 @somangshu Found some issues with the widget, some of these could exist in other widgets as well. These need triaging.

- [ ] When we have the same or empty values for two options, the widget goes blank
<img width="782" alt="Screenshot 2021-10-21 at 12 18 24 PM" src="https://user-images.githubusercontent.com/103687/138226576-87d1f4b4-4f29-4660-889b-27821a6fe26f.png">
<img width="789" alt="Screenshot 2021-10-21 at 12 19 42 PM" src="https://user-images.githubusercontent.com/103687/138226583-7cd49092-43a7-4be3-803a-35d92d8cb25a.png">

- [ ] When we start typing in the options' JS input, the widget crashes.
<img width="792" alt="Screenshot 2021-10-21 at 12 21 16 PM" src="https://user-images.githubusercontent.com/103687/138226644-81ec5f4c-4443-49f6-9811-aaffaf089efd.png">


- [ ] Due to the string validation special chars are not accepted in the validation of the default values. We can either update the validation to allow for these characters or disallow these types of values to be set in the options.

<img width="839" alt="Screenshot 2021-10-21 at 12 20 10 PM" src="https://user-images.githubusercontent.com/103687/138226772-41415d33-9054-47a3-8a76-96c710c64afc.png">

- [ ] The icon needs to be updated
<img width="77" alt="Screenshot 2021-10-21 at 12 16 20 PM" src="https://user-images.githubusercontent.com/103687/138226842-f7a64c6c-ff69-45ca-b1c4-5121071dc1d7.png">

- [ ] There is some strange background in the options fields
<img width="263" alt="Screenshot 2021-10-21 at 12 17 15 PM" src="https://user-images.githubusercontent.com/103687/138226911-775de37a-babe-453b-806d-b5afd7e53c7e.png">

2021-11-05 08:04 UTC, wmdev0808 commented
/ok-to-test sha=55f79ec

2021-11-05 08:05 UTC, wmdev0808 commented
https://github.com/appsmithorg/appsmith/actions/runs/1424854034

2021-11-05 08:54 UTC, riodeuno requested changes

2021-11-05 08:54 UTC, riodeuno commented on app/client/src/utils/AppsmithUtils.tsx
> +export const isArrayEqual = (array1: any[] = [], array2: any[] = []) => {
@wmdev0808 These functions are available in `lodash` we can use that instead of maintaining custom functions in our codebase.

2021-11-05 09:15 UTC, wmdev0808 commented
/ok-to-test sha=89bbda1

2021-11-05 09:16 UTC, wmdev0808 commented
https://github.com/appsmithorg/appsmith/actions/runs/1425066219

2021-11-05 09:47 UTC, riodeuno requested changes

2021-11-05 09:47 UTC, riodeuno commented on app/client/src/widgets/SwitchGroupWidget/widget/index.tsx
> +      this.props.updateWidgetMetaProperty("selectedValues", selectedValues, {
@wmdev0808 I was wondering if we can make the `selectedValues` a derived property? For example, in the table widget we store `selectedRowIndices` in the meta, and use this to compute `selectedRows` array. 

There are a couple of reasons I was wondering about this.
- There is quite a bit of computations happening in `componentDidUpdate`. 
- `options` will be available correctly in the evaluations, which means that the `selectedValues` can be computed without figuring out if the options have changed. So, we will have smaller amount of code to maintain.

If we implement this, in the manner I am requesting --
- What will happen to the bindings to `selectedValues` when called in `onSelectionChange` trigger? Will it still give us the correct values?

2021-11-05 09:47 UTC, riodeuno commented on app/client/src/widgets/SwitchGroupWidget/widget/index.tsx
> +      if (optionsLength >= prevOptionsLength) {
@wmdev0808 What happens if the `optionsLength` is smaller than `prevOptionsLength`?

2021-11-05 09:47 UTC, riodeuno commented on app/client/src/widgets/SwitchGroupWidget/widget/index.tsx
> +      optionsLength !== prevOptionsLength ||
@wmdev0808 I find that this code is difficult to follow. Would you mind adding comments to the code to help me understand how we're dealing with the following scenarios:
- [ ] When new options are added.
- [ ] When one or more option value(s) have changed
- [ ] When a selected option is deleted.
- [ ] When `defaultValues` have a value which no longer exists in the `options`

2021-11-08 20:32 UTC, wmdev0808 commented
/ok-to-test sha=30cd610

2021-11-08 20:32 UTC, wmdev0808 commented
https://github.com/appsmithorg/appsmith/actions/runs/1436590807

2021-11-16 05:42 UTC, riodeuno commented
The icon needs to be updated. @somangshu Please help out with the icon.

<img width="75" alt="Screenshot 2021-11-16 at 11 01 10 AM" src="https://user-images.githubusercontent.com/103687/141926679-ad2c70a5-a550-4373-a32d-b4a834dcfc9a.png">

The code overall looks fine to me.

@YogeshJayaseelan Please test this widget out thoroughly. We will want to provide odd values to the options and default values and find expected results. Another approach for testing would be to bind the `defaultValues` of the switch widget with a multi-select or checkboxgroup widget, to see if the switch widget reacts accordingly.

2021-11-16 07:16 UTC, somangshu commented
@riodeuno please approve the code if it looks good

@momcilo-appsmith @UXFalcon we need to the icon for this

2021-11-16 07:17 UTC, riodeuno commented
@somangshu There are merge conflicts and the icon needs to be updated. These changes are needed before approval.

2021-11-17 12:26 UTC, wmdev0808 commented
/ok-to-test sha=1384ca3

2021-11-17 12:27 UTC, wmdev0808 commented
https://github.com/appsmithorg/appsmith/actions/runs/1471539634

2021-11-17 13:43 UTC, momcilo-appsmith commented
New link for the icon: https://www.figma.com/file/ATfTB5F9Q7ZiI0yYckuXW7/Deprecated-Design-System?node-id=72%3A8452

2021-11-17 13:52 UTC, wmdev0808 commented
/ok-to-test sha=bd54e9e

2021-11-17 13:53 UTC, wmdev0808 commented
https://github.com/appsmithorg/appsmith/actions/runs/1471936874

2021-11-17 18:00 UTC, wmdev0808 commented
/ok-to-test sha=3cc00af

2021-11-17 19:08 UTC, wmdev0808 commented
/ok-to-test sha=a52cc59

2021-11-17 20:20 UTC, wmdev0808 commented
/ok-to-test sha=c6167d4

2021-11-18 06:58 UTC, wmdev0808 commented
/ok-to-test sha=e3709ed

2021-11-18 07:16 UTC, wmdev0808 commented
/ok-to-test sha=1e6e865

2021-11-18 09:29 UTC, somangshu commented
@wmdev0808 we have the icon from the design system. Kindly replace the old one
https://www.figma.com/file/ATfTB5F9Q7ZiI0yYckuXW7/Deprecated-Design-System?node-id=72%3A8452

Let me know if you have a problem accessing

2021-11-18 09:31 UTC, wmdev0808 commented
> @wmdev0808 we have the icon from the design system. Kindly replace the old one https://www.figma.com/file/ATfTB5F9Q7ZiI0yYckuXW7/Deprecated-Design-System?node-id=72%3A8452
> 
> Let me know if you have a problem accessing

@somangshu I've already replaced it in the previous commit

2021-11-18 09:32 UTC, somangshu commented
@wmdev0808 related test is failing, [check this out](https://dashboard.cypress.io/projects/eyxvp8/runs/12061/test-results/30783d6a-1a84-4bc1-b038-f93471af73da?statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D)

2021-11-18 10:16 UTC, somangshu commented
Icon change verified and looks good to me. 

@riodeuno I am moving this to needsQA, will need one final approval from you before merging

2021-11-18 12:57 UTC, wmdev0808 commented
/ok-to-test sha=facdec4

2021-11-19 06:25 UTC, somangshu submitted a review, later dismissed

2021-11-25 05:06 UTC, YogeshJayaseelan commented
@wmdev0808 - Started testing this feature and came up with the below issues and testing is in-progress 

Issue 1 - When the user starts typing in the Option JS the widget crashes and throws - **Cannot read properties of undefined (reading,'length') in the console log** 

when {{null}} value is passed in option - **Cannot read properties of null (reading,'length') in the console log** 

https://www.loom.com/share/2dabe9e331794625842dc1b3b94d5fef

Issue 2 - Icon is not displayed in the entity explorer when the switch widget is dragged and dropped to the canvas

https://loom.com/share/10d9b7a939194301b9ed4b7e393efe10

2021-11-25 14:51 UTC, wmdev0808 commented
> @wmdev0808 - Started testing this feature and came up with the below issues and testing is in-progress
> 
> Issue 1 - When the user starts typing in the Option JS the widget crashes and throws - **Cannot read properties of undefined (reading,'length') in the console log**
> 
> when {{null}} value is passed in option - **Cannot read properties of null (reading,'length') in the console log**
> 
> [![LOOM DEMO](https://camo.githubusercontent.com/12b6ff2153280c86b0da0ad20e138e36ca3299abee92d242b925b4091d200c30/687474703a2f2f63646e2e6c6f6f6d2e636f6d2f73657373696f6e732f7468756d626e61696c732f32646162653965333331373934363235383432646331623362393464356665662d30303030312e676966)](https://www.loom.com/share/2dabe9e331794625842dc1b3b94d5fef)
> 
> Issue 2 - Icon is not displayed in the entity explorer when the switch widget is dragged and dropped to the canvas
> 
> https://loom.com/share/10d9b7a939194301b9ed4b7e393efe10
> 
> Issue 3 - The evaluated values are not aligned properly when the default option values ate not separated by a comma
> 
> <img alt="Screenshot 2021-11-25 at 4 46 13 PM" width="1680" src="https://user-images.githubusercontent.com/35128442/143432077-1ddaaa91-6b0e-4bf2-a81a-369671be47bc.png">
> 
> Issue 4 - Disabling the switch button - the toggle appears in blue colour
> 
> [![LOOM DEMO](https://camo.githubusercontent.com/c66d4e8d2d521893fabce17a7cd3df21d036cd685ebe95129f0f307071981582/687474703a2f2f63646e2e6c6f6f6d2e636f6d2f73657373696f6e732f7468756d626e61696c732f37626439656437333932646134633466616631336630353130356135663637312d30303030312e676966)](https://www.loom.com/share/7bd9ed7392da4c4faf13f05105a5f671)

@YogeshJayaseelan , 
- Issue 3: I think Evaluated value is only aligned properly if the evaluation of the value is done without error.
If you don't agree on it, please provide any other widget example with the same use case
- Issue 4: I cannot reproduce it

2021-11-25 14:55 UTC, wmdev0808 commented
/ok-to-test sha=136216b

2021-11-26 05:12 UTC, YogeshJayaseelan commented
@wmdev0808 For issue 4 - When you mouse hover on the switch toggle then the mouse pointer icon will be displayed then click on the toggle to observe the blue colour 

Issue 5 - Switch button left and Right Alignment functionality is not available  - comparing with switch widget

2021-11-29 12:58 UTC, wmdev0808 commented
/ok-to-test sha=b007f8f

2021-11-30 16:43 UTC, riodeuno approved these changes
Looks good to me! It took some time, but we seem to have a robust widget. Nice work @wmdev0808 !

2021-12-02 06:41 UTC, YogeshJayaseelan commented
@wmdev0808 Verified the issue fix and they are working as expected.

Issue 1 - Fixed,
Issue 2 - Fixed,
Issue 3 - Fixed,
Issue 4 - Not in scope 
Issue 5 - Fixed

2021-12-09 10:24 UTC, wmdev0808 commented
/ok-to-test sha=d2ad822

2021-12-09 10:29 UTC, riodeuno approved these changes

2021-12-09 12:02 UTC, merged