fix: Added a condition to json stringify values if they are js objects
appsmithorg/appsmith pull request #7656
Opened 2021-09-21 06:36 UTC by ayushpahwa

## Description

When showing evaluated values for substitutionType `TEMPLATE` the evaluated value popup shows JSON which is not valid. If the type is changed to `SMART_SUBSTITUTE`, the evaluated values are shown correctly. This is because when replacing the values in the final step, proper JSON stringify was not happening. Fixed the same with this PR

Fixes #7539 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-09-21 06:38 UTC, hetunandu requested changes

2021-09-21 06:38 UTC, hetunandu commented on app/client/src/workers/evaluationSubstitution.ts
> +    if (b.includes("{{")) value = JSON.stringify(value);
Add a test case for this

2021-09-28 17:32 UTC, Nikhil-Nandagopal commented
@ayushpahwa can we get this merged?

2021-10-06 09:52 UTC, ayushpahwa commented on app/client/src/workers/evaluationSubstitution.ts
> +    if (b.includes("{{")) value = JSON.stringify(value);
Currently stuck in the new where clause implementation for UQI. Have raised a new [issue](8243) and assigned it to me for the same. Will work on it after the current tasks.

2021-10-06 09:54 UTC, Nikhil-Nandagopal submitted a review, later dismissed

2023-09-08 05:02 UTC, closed without merging