feat: add document viewer widget
appsmithorg/appsmith pull request #7666
Opened 2021-09-21 08:51 UTC by techbhavin

## Description

> document view widget add 

Fixes #3358 

## Type of change

- Bugfix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-09-24 11:37 UTC, somangshu requested changes
@techbhavin there is a build error, Please fix

2021-09-24 11:48 UTC, somangshu approved these changes
Approving to run the tests once

2021-09-24 12:14 UTC, somangshu commented
Checked out the deploy preview and the changes as per the discussion seem to reflect

2021-09-28 05:11 UTC, jsartisan submitted a review, later dismissed

2021-09-28 05:11 UTC, jsartisan commented on app/client/src/widgets/DocumentViewerWidget/component/index.tsx
> +const getSettings = (docUrl: string) => {
hey, paul, possible to add comments on these functions? for e.g - from the function name, I am not sure what settings we are talking about. I would suggest adding a brief note about what function is doing.

2021-09-28 05:11 UTC, jsartisan commented
LGTM! just left a small comment.

2021-09-28 05:13 UTC, jsartisan commented
One more thing, the buttons in the PDF view looks odd one out. I guess we can't really do anything about that since we are using third-library to render the pdf viewer.

@somangshu What do you think? is that okay right?

2021-09-28 06:42 UTC, somangshu commented on app/client/src/widgets/DocumentViewerWidget/component/index.tsx
> +const getSettings = (docUrl: string) => {
Another point, we should write jest test for this

2021-09-28 06:44 UTC, somangshu commented
@jsartisan the button is part of the browser default, we are using iframe from the PDF, you are right that its not in our control, We can leave it as it is.

2021-09-28 06:44 UTC, somangshu commented
@techbhavin is the documentation done for this widget

2021-09-28 08:41 UTC, techbhavin commented
Document is update [Here](https://github.com/appsmithorg/appsmith-docs/pull/206)

cc: @somangshu

2021-09-29 04:47 UTC, somangshu commented on app/client/src/widgets/DocumentViewerWidget/component/index.tsx
> +   *  All other urls will be either Google Preview or urls with file extentions ( e.x. from aws s3 )
Here we could tell the dev about the file extensions we allow as well. Not very important

2021-09-29 04:47 UTC, somangshu approved these changes
LGTM, Approving to run tests

2021-09-30 05:00 UTC, jsartisan submitted a review, later dismissed

2021-10-01 09:06 UTC, somangshu commented
@techbhavin as mentioned, can you check if We could use the file-picker to upload the PDF and use the base64 format. Basically need the base64 URL to work here

2021-10-04 06:50 UTC, techbhavin commented
@somangshu  @Nikhil-Nandagopal  

Current Implementation is supported base64  URL 
![image](https://user-images.githubusercontent.com/58818598/135805769-a6471491-e5e3-44ed-b203-58c0072e1d37.png)

2021-10-04 07:17 UTC, Nikhil-Nandagopal commented
@techbhavin how will a user know that URL supports base64? Please change the field name and placeholder like in the image widget

2021-10-07 05:35 UTC, somangshu commented
@vibhandikyash merge the latest changes here and see if the icon is still valid, We will get in touch with design again otherwise

@vivekverma2312 this widget is done, Can we test this out

2021-10-12 05:11 UTC, YogeshJayaseelan commented
@techbhavin Tested this PR and please find the observations below,

Issue 1 : The Icon of Document viewer in entity explorer is not visible clearly 

<img width="1680" alt="Screenshot 2021-10-12 at 10 04 20 AM" src="https://user-images.githubusercontent.com/35128442/136892129-132ddeec-0383-46ce-b91d-08ef5b134445.png">

Issue 2 : The Expected Structure should be URL instead of String in the - Document link field 

<img width="1680" alt="Screenshot 2021-10-12 at 10 06 37 AM" src="https://user-images.githubusercontent.com/35128442/136892326-bc0b13ea-0ad2-4599-9f4b-0889ccef6f01.png">

Issue 3 : Passing some of the sample pdf url does not load

Url that doesn't load:

http://www.africau.edu/images/default/sample.pdf
http://www.pdf995.com/samples/pdf.pdf

<img width="1680" alt="Screenshot 2021-10-12 at 10 20 30 AM" src="https://user-images.githubusercontent.com/35128442/136893357-45797ca3-bbe7-4c53-979b-adeeda0a1902.png">

Issue 4 : PDF uploaded via file picker and binded with document viewer does not work

https://www.loom.com/share/f76fdaaf19db418ab5dc149f7f6bf32d

Issue 5: Some of the pdf urls are 'refused to connect' not sure if this is an expected behaviour 

https://github.com/tpn/pdfs/blob/master/A%20Brief%20Tutorial%20on%20Database%20Queries%2C%20Data%20Mining%2C%20and%20OLAP%20(hamel-197-manuscript-final).pdf

<img width="1680" alt="Screenshot 2021-10-12 at 10 31 41 AM" src="https://user-images.githubusercontent.com/35128442/136894596-996ca5f4-85ff-42f7-b9c1-dae7d3f53454.png">

Suggestion 1 : To have Widget wise download toggle - Though we have page wise download option we can have download toggle from widget level

Suggestion : To have search toggle - so that user will be able to search content from the PDF

Suggestion 3 : To have 'Pop up and Text notes' so that whenever user select some text - with the help of pop up user can highlight particular content on the PDF and add notes

Suggestion 4 :

2021-10-12 06:25 UTC, somangshu commented
@YogeshJayaseelan this is document viewer which mean its can also load docx, xlsx, ppt. Do check them out

2021-10-12 07:26 UTC, somangshu commented
@techbhavin looks like there is a related test case also failing

2021-10-19 09:29 UTC, YogeshJayaseelan commented
@techbhavin - Tested this PR and found issue 6 is still not working 

New issue:

Issue 7 - By editing the document url to any single character - Appmsith page is loaded inside Document viewer widget 

https://www.loom.com/share/575267f7d1744409a1cac7d602c1d9f8

2021-11-08 11:16 UTC, techbhavin commented
/ok-to-test sha=166bd84

2021-11-08 11:18 UTC, techbhavin commented
https://github.com/appsmithorg/appsmith/actions/runs/1434479479

2021-11-09 12:09 UTC, jsartisan approved these changes

2021-11-09 12:09 UTC, jsartisan commented on app/client/src/widgets/DocumentViewerWidget/component/DocViewer.tsx
> +  useEffect(() => {
can we add some comments above useffect what we are doing in thr. just some brief info would be fine.

2021-11-10 12:03 UTC, techbhavin commented
/ok-to-test sha=ddb6294

2021-11-10 12:05 UTC, techbhavin commented
https://github.com/appsmithorg/appsmith/actions/runs/1444044157

2021-11-11 11:04 UTC, techbhavin commented
/ok-to-test sha=02ebede

2021-11-12 08:13 UTC, techbhavin commented
/ok-to-test sha=5697d66

2021-11-12 08:15 UTC, techbhavin commented
https://github.com/appsmithorg/appsmith/actions/runs/1452231048

2021-11-12 10:05 UTC, techbhavin commented
/ok-to-test sha=5697d66

2021-11-15 07:22 UTC, shwetha-ramesh commented
@techbhavin retested all the issues again. Here are the few things noticed.
Issue6 :  CSV, PPT, files are uploaded via file picker and binded with Document viewer - does not load the files
Currently only pdf, doc and xlxs files are supported. 
For PPT
https://loom.com/share/44e5cfb0924e46bf981c0e0eb67ddb15

For CSV
https://www.loom.com/share/c856c6b1d53747d2a180677b87864bfb

Issue 7: Still exists
https://www.loom.com/share/fe0ab983afee4ae985b8c68085d1a21a

**New Issue**
Issue 8: When visible is Enabled it becomes greyed out again disable it and the document viewer doesnt appear bold, only when the user clicks on the canvas the widget appears (refer video)

https://loom.com/share/4c05c74aa7a84a84bf11473796d2a5b6

2021-11-15 07:24 UTC, shwetha-ramesh commented
> @YogeshJayaseelan this is document viewer which mean its can also load docx, xlsx, ppt. Do check them out

@somangshu Can you please re-confirm all the supported files. Currently only pdf, doc and xlxs files are supported. CSV and PPT are not supported.

2021-11-15 09:35 UTC, somangshu commented
@shwetha-ramesh they should still be supported with the URL format, Maybe base64 can be a problem.

@techbhavin for issue 7 listed above, I think we should handle it, Could the widget can show that its an invalid URL?

2021-11-17 08:00 UTC, techbhavin commented
/ok-to-test sha=d43323b

2021-11-17 11:17 UTC, somangshu commented
@techbhavin could you check the failing tests

2021-11-17 11:55 UTC, techbhavin commented
/ok-to-test sha=d43323b

2021-11-17 14:05 UTC, techbhavin commented
/ok-to-test sha=04a9e96

2021-11-18 09:26 UTC, somangshu approved these changes
Failing test resolve, @jsartisan please check the code change

2021-11-18 09:31 UTC, somangshu commented
@wmdev0808 related test is failing, [check this out](https://dashboard.cypress.io/projects/eyxvp8/runs/12061/test-results/30783d6a-1a84-4bc1-b038-f93471af73da?statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D)

2021-11-18 10:32 UTC, jsartisan commented
@NandanAnantharamu Asked nandan about the change. If the tests are working fine, then it's okay.

2021-11-18 10:32 UTC, jsartisan approved these changes

2021-11-19 08:13 UTC, YogeshJayaseelan commented
@techbhavin Please find the testing status 

QA Comment
Issue 1 - Fixed
Issue 2 -Not in Scope for now
Issue 3 - Agreed that http is not allowed and only https are considered
Issue 4 - Verified with the right syntax Filepicker1.files[0].data and working as expected
Issue 5 - Invalid URL

Issue 6 - **Still CSV and PPT are not supported** - **Can you help us with CSV and PPT url link?**

Issue 7 - **Issue still exists** 

7.A) - Removing the // next to https or removing https still loads the appmsith site 

https://www.loom.com/share/1d5f4cb185ff424db57c7b8977781cc9

Issue 8 - **Fixed**

2021-11-19 09:50 UTC, YogeshJayaseelan commented
@techbhavin Please find the updated status

QA Comment
Issue 1 - Fixed
Issue 2 -Not in Scope for now
Issue 3 - Agreed that http is not allowed and only https are considered
Issue 4 - Verified with the right syntax Filepicker1.files[0].data and working as expected
Issue 5 - Invalid URL
Issue 6 - **PPT is supported with the following url you have provided** 

https://roteemealplancover.s3.ap-south-1.amazonaws.com/sample/2038800838373569079sample.ppt

**But ppt file uploaded via file-picker and binded with document viewer is not supporting 

CSV - Not is scope now** 

Issue 7 - Issue still exists

7.A) - Removing the // next to https or removing https still loads the appmsith site
https://loom.com/share/1d5f4cb185ff424db57c7b8977781cc9

Issue 8 - Fixed

2021-11-22 11:03 UTC, techbhavin commented
/ok-to-test sha=1ac9646

2021-11-23 08:59 UTC, techbhavin commented
/ok-to-test sha=51b5d0c

2021-11-23 09:10 UTC, jsartisan approved these changes

2021-11-24 09:38 UTC, techbhavin commented
/ok-to-test sha=d4f31b1

2021-11-25 09:58 UTC, techbhavin commented
/ok-to-test sha=a1f6882

2021-11-25 12:08 UTC, jsartisan approved these changes

2021-11-29 05:39 UTC, YogeshJayaseelan commented
@techbhavin Verified the fix of rissue 7 and please find the status below,

QA Comment
Issue 1 - Fixed
Issue 2 -Not in Scope for now
Issue 3 - Agreed that http is not allowed and only https are considered
Issue 4 - Verified with the right syntax Filepicker1.files[0].data and working as expected
Issue 5 - Invalid URL
Issue 6 - **PPT is supported with the following url you have provided**

https://roteemealplancover.s3.ap-south-1.amazonaws.com/sample/2038800838373569079sample.ppt

**But ppt file uploaded via file-picker and binded with document viewer is not supporting**

**CSV - Not is scope now**

Issue 7 - Fixed
Issue 8 - Fixed

2021-11-29 06:34 UTC, techbhavin commented
/ok-to-test sha=4cb2d73

2021-11-29 09:14 UTC, jsartisan approved these changes

2021-11-29 15:37 UTC, merged

2021-12-05 05:40 UTC, Frederyuyyhj approved these changes
app/client/cypress/fixtures/DocumentViewerDsl.json

2021-12-05 05:42 UTC, Frederyuyyhj commented
> app/client/cypress/fixtures/DocumentViewerDsl.json

2021-12-05 10:06 UTC, wealthz01 commented
You guys keep mute when j needs you