feat: added migration for old app colors to new colors
appsmithorg/appsmith pull request #7679
Opened 2021-09-21 10:05 UTC by nayan-rafiq

## Description
Updates old app background colors to new colors.

Fixes #7609

## Type of change
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
- Tested on local machine

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-09-22 10:24 UTC, abhvsn requested changes

2021-09-22 10:24 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog.java
> +    public void migrateOldAppColorsToNewColors(MongoTemplate mongoTemplate) {
Can we use `MongockTemplate` as `MongoTemplate` is deprecated AFAIK

2021-09-22 10:31 UTC, abhvsn approved these changes
LGTM

2021-09-29 06:57 UTC, nayan-rafiq commented
Waiting for the FE changes to be merged first.

2021-10-04 09:23 UTC, nayan-rafiq commented
Closing this because this commit has been added to the branch: `epic/appsmith-design-system-v2` so that FE and BE changes are live together.

2021-10-04 09:23 UTC, closed without merging