fix: countryCode property in Input type phone number
appsmithorg/appsmith pull request #7684
Opened 2021-09-21 10:39 UTC by vicky-primathon

## Description
Fix countryCode property in Input type phone number

Fixes #7475 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-09-23 06:50 UTC, riodeuno commented
@somangshu I don't think this completely solve the issue here. When I try to bind the `Input1.text` I don't get the country code. There is also no other property which has the country code. Not sure, if this was a part of the original issue. Please review the deploy preview.

2021-09-23 07:06 UTC, somangshu commented
@riodeuno I can see that for the type phone number the `{{input.countryCode}}` works and returns the short code, This however should return the int code and not the short code. 

@vicky-primathon I see that this does not function well in case of the currency as well. We need to fix the issue.

2021-09-23 07:24 UTC, somangshu requested changes
Change as mentioned above

2021-09-23 10:27 UTC, vicky-primathon commented
> @riodeuno I can see that for the type phone number the `{{input.countryCode}}` works and returns the short code, This however should return the int code and not the short code.
> 
> @vicky-primathon I see that this does not function well in case of the currency as well. We need to fix the issue.

@somangshu  in case of currency, selected country code can be accessed as {{input.currencyCountryCode}} 
Should we expose single api i.e {{input.countryCode}} for both phone number and currency selected country code.

2021-09-23 10:34 UTC, somangshu commented
> @somangshu in case of currency, selected country code can be accessed as {{input.currencyCountryCode}}
> Should we expose single api i.e {{input.countryCode}} for both phone number and currency selected country code.

@vicky-primathon when I check:
- `currencyCountryCode` does not return anything. It should return the ISO code  ![Screenshot 2021-09-23 at 4 02 14 PM](https://user-images.githubusercontent.com/11089579/134492614-643caa7f-5dac-4e63-a993-aeb50e085acd.png)
- `currencyCountryCode` should be changed to `currencyCode`.
- The `countryCode` should return the phone extension ex: +91

Let me know if you have any doubts

2021-09-23 15:17 UTC, somangshu submitted a review, later dismissed
Deploy preview looks good to me, All changes as requested are updated.

@riodeuno can you please verify the code changes

2021-09-23 15:24 UTC, riodeuno commented on app/client/src/widgets/InputWidget/component/ISDCodeDropdown.tsx
> +      value: item.dial_code,
@vicky-primathon Will these changes effect existing users? How do we verify this in the UI?

2021-09-29 07:35 UTC, vicky-primathon commented on app/client/src/widgets/InputWidget/component/ISDCodeDropdown.tsx
> +      value: item.dial_code,
Will have to write migrations to update default selected code value from country code to dial_code

2021-09-29 08:17 UTC, vicky-primathon commented on app/client/src/widgets/InputWidget/component/ISDCodeDropdown.tsx
> +      value: item.dial_code,
@riodeuno added migrations for this

2021-10-04 05:29 UTC, riodeuno commented on app/client/src/widgets/InputWidget/component/ISDCodeDropdown.tsx
> +      value: item.dial_code,
@vivekverma2312 We will need to verify the migrations during QA. The approach would be open a bound input widget in this deploy preview, which was created in release.

2021-10-04 05:51 UTC, riodeuno requested changes

2021-10-04 05:51 UTC, riodeuno commented on app/client/src/utils/migrations/InputWidget.ts
> +        console.log({ ISDCodeOption });
We have a console log left over here.

2021-10-04 11:25 UTC, riodeuno approved these changes

2021-10-04 11:26 UTC, riodeuno commented
Note for QA: We need a regression test for these types of input widgets.
cc @YogeshJayaseelan @vivekverma2312

2021-10-11 10:35 UTC, vivekverma2312 commented
@vicky-primathon 
1. If input field is empty then `{{Input1.countryCode}}  - {{Input1.text}}` is showing undefined in text box.

<img width="998" alt="Screenshot 2021-10-11 at 3 48 20 PM" src="https://user-images.githubusercontent.com/83569920/136776346-81adb6ed-8091-4589-9f09-bf98b6e90663.png">

2. During migration `{{Input2.currencyCountryCode}}{{Input2.text}}` is not migrating to `{{Input2.currencyCode}} {{Input2.text}}`. Due to this changing currency in Input widget do not change the currency in text widget.

2021-11-09 09:19 UTC, somangshu commented
@vicky-primathon @riodeuno I disagree to CountryCode changing to DialCode, this is not the generic convention. 

cc @Nikhil-Nandagopal 

Also since this is blocked by the backend migration, should we close this or draft it until unblocked

2021-11-09 11:36 UTC, riodeuno commented
@somangshu I don't have strong opinions on this. `countryCode` works. 
@vicky-primathon Let's make this into a draft for now.

2021-11-09 12:30 UTC, somangshu commented
@riodeuno I said that because the name used in the first release used `countryCode` and if we continue with it we will not need any migrations.

2021-11-12 10:19 UTC, sbalaji1192 commented
@vicky-primathon Lets close this PR since we're gonna introduce a v2 of input widget. We will do these changes on the v2.

2021-11-12 10:23 UTC, closed without merging