fix: added SAAS plugin check in getQueryActionsForCurrentPage
appsmithorg/appsmith pull request #7694
Opened 2021-09-21 13:09 UTC by rashmi-rai

## Description

Added check in `PluginType.SAAS` in `getQueryActionsForCurrentPage`

Fixes #7645 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Tested Manually with google sheets.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-09-22 08:49 UTC, mohanarpit commented
@rashmi-rai Is it possible to add a check in Cypress test case to assert that the number of queries is always showing up for all SaaS datasources?

2021-09-24 05:16 UTC, trishaanand commented on app/client/src/selectors/entitiesSelector.ts
> +        action.config.pluginType === PluginType.DB ||
Would we have to handle separately for any new type of plugin we introduce? Is this because rest api is handled separately? If that is the case, could we instead filter on the basis of NOT rest?

2021-09-24 05:19 UTC, trishaanand commented on app/client/src/selectors/entitiesSelector.ts
> +        action.config.pluginType === PluginType.DB ||
Actually just checked. This is broken for REST API datasource as well.

2021-10-01 05:04 UTC, trishaanand commented
@rashmi-rai : Since you are not actively working on fixing this and we keep getting notified every day for this, I am marking this as draft.

2021-11-29 14:58 UTC, rashmi-rai commented
> @rashmi-rai Is it possible to add a check in Cypress test case to assert that the number of queries is always showing up for all SaaS datasources?

Done

2021-11-29 15:13 UTC, rashmi-rai commented on app/client/src/selectors/entitiesSelector.ts
> +        action.config.pluginType === PluginType.DB ||
Fixed for both. 
Changed selector here which works like Not `PluginType.JS`

2021-11-30 06:48 UTC, ApekshaBhosale requested changes

2021-11-30 06:48 UTC, ApekshaBhosale commented on app/client/src/pages/Editor/IntegrationEditor/DatasourceCard.tsx
> -  getQueryActionsForCurrentPage,
getQueryActionsForCurrentPage only used here. If we are not using this anymore please remove the code

2021-11-30 06:54 UTC, rashmi-rai commented on app/client/src/pages/Editor/IntegrationEditor/DatasourceCard.tsx
> -  getQueryActionsForCurrentPage,
done

2021-11-30 06:56 UTC, ApekshaBhosale approved these changes

2021-11-30 06:57 UTC, rashmi-rai commented
/ok-to-test sha=ae7f101d4ff97893ce8ef4b3298ace8872a319a4

2021-11-30 09:21 UTC, rashmi-rai commented
/ok-to-test sha=ae7f101d4ff97893ce8ef4b3298ace8872a319a4

2021-11-30 10:11 UTC, merged