feat: remove linting feature flag
appsmithorg/appsmith pull request #7736
Opened 2021-09-22 13:05 UTC by vnodecg

## Description
Removes linting feature flag

2021-09-23 05:51 UTC, hetunandu requested changes

2021-09-23 05:51 UTC, hetunandu commented on app/client/src/components/editorComponents/CodeEditor/index.tsx
> -        if (getFeatureFlags().LINTING) {
forgot to remove imports here

2021-09-23 09:43 UTC, vnodecg commented on app/client/src/components/editorComponents/CodeEditor/index.tsx
> -        if (getFeatureFlags().LINTING) {
Done

2021-09-23 11:22 UTC, hetunandu approved these changes

2021-09-27 06:23 UTC, hetunandu approved these changes

2021-10-04 06:07 UTC, hetunandu approved these changes

2021-10-04 06:41 UTC, merged