Feature/skip botcomment when onboarding skipped
appsmithorg/appsmith pull request #7816
Opened 2021-09-24 10:53 UTC by nayan-rafiq

## Description
Skips the bot comments if user has skipped the on-boarding flow during their first comment.

Fixes #7281

## Type of change
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
- Tested on local machine
- Unit tests

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-09-24 11:16 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/UserController.java
> +    public Mono<ResponseDTO<CommentState>> getCommentState() {
Is the client going to call this API on every page load? Can we put this information as part of user profile itself? That is anyway being fetched, so we save on an extra API call no?

Also, if we do that, then the client will need to make sure this field is **not** passed on to `appsmith.user` object, or folks will be able to see this in auto-complete when writing JS in Appsmith.

2021-09-24 11:16 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/constants/CommentState.java
> +public enum CommentState {
If this is going to be _only_ about onboarding, can we name it `CommentOnboardingState`? Right now this name feels like the _state of a comment_, with options like `RESOLVED` meaning that the comment is _in a resolved state_, etc.

2021-09-24 11:30 UTC, nayan-rafiq commented on app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/UserController.java
> +    public Mono<ResponseDTO<CommentState>> getCommentState() {
@sharat87 I thought about that but currently, we don't return any properties of `UserData` to any API e.g. `/me`. If I return `userData` contents as part of the `/me` API, other properties of the `UserData` will be exposed and many of them are for internal use. That's why I came up with a new API. After reading your comment, I think I can expose this property only in `me` API. Do you think that'll be a better idea? 

To avoid an API call each time, client will cache this value and only make an API call when cache is empty. Client will use this value to decide whether to show the on-boarding flow to user or not.

2021-09-25 18:01 UTC, nayan-rafiq commented on app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/UserController.java
> +    public Mono<ResponseDTO<CommentState>> getCommentState() {
@sharat87 I've updated the PR. Now the `commentOnboardingState` is returned in the response of `/me` API.

2021-09-27 13:08 UTC, sharat87 approved these changes
Looks good, so approving. However, note that once this goes in, the `appsmith.user` object will have a `commentOnboardingState` field for all users to see and use. The client code needs to not expose that field to user-written Javascript. That change can go along with this PR togather, or soon after, but needs to go soon.

2021-09-27 14:16 UTC, sharat87 approved these changes

2021-09-27 14:20 UTC, mohanarpit commented on app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/UserController.java
> +                .zipWith(userDataService.getForCurrentUser())
Any particular reason that we are doing this logic in the controller & not the service method itself?

2021-09-27 14:20 UTC, mohanarpit commented on app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/UserController.java
> +        return userDataService.setCommentState(userData.getCommentOnboardingState())
Quick question: Do these DB calls not require any ACL? Just checking.

2021-09-27 14:41 UTC, nayan-rafiq commented on app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/UserController.java
> +        return userDataService.setCommentState(userData.getCommentOnboardingState())
We don't set policies to `UserData` and there is no ACL check anywhere for `UserData`. Should we change that?

2021-09-28 06:51 UTC, mohanarpit commented on app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/UserController.java
> +                .zipWith(userDataService.getForCurrentUser())
Yes please. If we need to refactor, lets do that. Adding such logic in a controller makes it virtually untestable since we don't have any controller level tests in the code base.

2021-09-29 06:17 UTC, sharat87 requested changes
Looks good. It looks like all tests have a `@WithUserDetails(value = "api_user")` above them. Considering the error we saw recently, can we add a test where no one is logged in, and ensure that we get a profile object, instead of an empty Mono?

2021-09-29 06:55 UTC, nayan-rafiq commented
> Looks good. It looks like all tests have a `@WithUserDetails(value = "api_user")` above them. Considering the error we saw recently, can we add a test where no one is logged in, and ensure that we get a profile object, instead of an empty Mono?

@sharat87 I've added a unit test to test profile is returned when user is anonymous.

2021-09-29 08:52 UTC, sharat87 approved these changes
Looks good to be merged. Please:

1. Edit the merge commit's detail to the PR description, or otherwise more details about the change.
1. Squash merge once the CI is finished. Thanks!

2021-09-29 09:50 UTC, merged