fix: Effect the telemetry choice in welcome page
appsmithorg/appsmith pull request #7902
Opened 2021-09-28 14:01 UTC by sharat87

2021-09-29 13:17 UTC, abhvsn requested changes
Tiny suggestion 

Looks good to be merged after that

2021-09-29 13:17 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/AnalyticsService.java
> +        if (hashUserId
Considering hashUserId can be false in some scenarios 
`(!CollectionUtils.isEmpty(analyticsProperties) && commonConfig.isCloudHosting())` check should be handled as for self hosted instances `commonConfig.isCloudHosting()` will be false which may result in having null values for `analyticsProperties`

2021-09-29 14:58 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/AnalyticsService.java
> +        if (hashUserId
That's actually a good catch. I'm wondering why we even have that check at all at this point. No matter what, we should never send `null` to Segment, or it'll throw up right away.

Just pushed a commit to always clean that map up before moving on.

2021-09-30 07:21 UTC, abhvsn submitted a review, later dismissed

2021-09-30 07:23 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/AnalyticsService.java
> +        for (final Map.Entry<String, Object> entry : analyticsProperties.entrySet()) {
I was thinking instead of checking this here can we do it just after `Map<String, Object> analyticsProperties = properties == null ? new HashMap<>() : new HashMap<>(properties);` that way we can make sure this will be executed only once in any case

2021-09-30 09:46 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/AnalyticsService.java
> +        for (final Map.Entry<String, Object> entry : analyticsProperties.entrySet()) {
Hey I didn't notice this was being done twice. Just fixed and pushed. :)

2021-09-30 13:23 UTC, abhvsn approved these changes
LGTM

2021-10-02 06:15 UTC, merged