Remove all preloaded query templates
appsmithorg/appsmith pull request #7927
Opened 2021-09-29 08:37 UTC by arunvjn

## Description
Removes all query templates

Fixes #7926 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manual

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-09-30 06:25 UTC, akash-codemonk submitted a review, later dismissed

2021-10-01 09:49 UTC, akash-codemonk requested changes

2021-10-01 09:49 UTC, akash-codemonk commented on app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/QueryPane/AddWidget_spec.js
> +    //cy.get(queryLocators.templateMenu).click();
Looks like these statements are in several files. Can we remove them altogether instead of commenting since the locators will still be there?

2021-10-01 09:49 UTC, akash-codemonk commented on app/client/src/components/editorComponents/GlobalSearch/SnippetsDescription.tsx
> +            {args.map((arg: SnippetArgument) => (
Just being sure are these changes intentional as it is unrelated?

2021-10-04 07:31 UTC, arunvjn commented on app/client/src/components/editorComponents/GlobalSearch/SnippetsDescription.tsx
> +            {args.map((arg: SnippetArgument) => (
This is unintentional. Removing this change

2021-10-04 08:00 UTC, akash-codemonk approved these changes

2021-12-29 13:57 UTC, closed without merging