wip: add extra fields to chart widget propertypane
appsmithorg/appsmith pull request #7953
Opened 2021-09-29 18:29 UTC by aswathkk

## Description

Adds chart type and chart config options for custom chart

Fixes #7263 

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?

Manually tested as of now. Planning to add test cases and steps to test soon.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-10-12 12:28 UTC, rahulramesha commented
@aswathkk not sure the migration is working for custom Chart type, could you please verify?
![image](https://user-images.githubusercontent.com/71900764/136956029-a84ae170-89f2-43f7-a4a8-b04302d67ec9.png)

2021-10-12 15:52 UTC, aswathkk commented
@rahulramesha That was due to the merge conflict that came today.
It should work now as I resolved conflicts.

2021-10-21 11:46 UTC, aswathkk commented
conclusion after the discussion:
Let the custom config field accept both types of configs so that the old application will also work.

2021-11-01 07:23 UTC, rahulramesha requested changes

2021-11-01 07:23 UTC, rahulramesha commented on app/client/src/widgets/ChartWidget/widget/propertyConfig.ts
> +        validation: {
This validation does not seem to be working. Could you make it work like, it does not validate the custom Chart type, if it is of older config and validates it if it is the newer custom config

2021-11-01 07:23 UTC, rahulramesha commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/Custom_Chart_spec.js
> +    cy.get(viewWidgetsPage.customChartType)
could you please cover both the scenarios

2021-11-08 11:06 UTC, aswathkk commented
This requires maintaining a complex codebase to support existing users of the widget. It's better to do this in a separate version of the widget.
Closing this PR since we will be doing it in v2 of the widget.

2021-11-08 11:06 UTC, closed without merging