using let instead of var and all var declarations at top
appsmithorg/appsmith pull request #8026
Opened 2021-09-30 18:13 UTC by samyakjain10

## Description

Fixes #7941 

## Type of change

> Please delete options that are not relevant.
- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-10-02 11:33 UTC, Rishabh-Rathod requested changes

2021-10-02 11:33 UTC, Rishabh-Rathod commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Comments/AddComments_spec.js
> +    var textEvent = document.createEvent("TextEvent");
All the variables, declared using `var` are expected to be converted to `let` or `const`, please do change in mentioned lines also.

2021-10-04 05:16 UTC, samyakjain10 commented
I have made the required changes. Please review them

2021-10-05 17:08 UTC, Rishabh-Rathod requested changes
@samyakjain10 Seems like there is one more `var`  occurrence as per the issue in https://github.com/appsmithorg/appsmith/blob/release/app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Comments/utils.js#L6-L6

2021-10-05 17:24 UTC, Rishabh-Rathod approved these changes
Seems like this was due to merge with release branch, Hence approving your PR

2021-10-05 17:25 UTC, merged