bug:removed unused States
appsmithorg/appsmith pull request #8033
Opened 2021-10-01 01:50 UTC by Hard-Coder05

## Description

Removed all the unused states as mentioned in the Issue.

Fixes #7943 

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-10-01 04:42 UTC, mohanarpit approved these changes

2021-10-01 04:58 UTC, mohanarpit commented
@Hard-Coder05 The client code base isn't compiling. Would request you to please check our contribution guide & how to setup & build the client on your local machine. Please fix this.

2021-10-01 05:05 UTC, Hard-Coder05 commented
> @Hard-Coder05 The client code base isn't compiling. Would request you to please check our contribution guide & how to setup & build the client on your local machine. Please fix this.

Yeah sure! I am working on it!

2021-10-01 05:55 UTC, Rishabh-Rathod commented on app/client/src/components/editorComponents/CodeEditor/index.tsx
> -      autoCompleteVisible: false,
here, only `autoCompleteVisible` is the unused state to check that you can search in the same file if it is being used somewhere else or not. 
```
isFocused: false,
isOpened: false,
hinterOpen: false,
```
are used state. @Hard-Coder05 
Can you check the same for other files also, where changes are made.

2021-10-01 05:58 UTC, Rishabh-Rathod requested changes

2021-10-01 06:01 UTC, Hard-Coder05 commented on app/client/src/components/editorComponents/CodeEditor/index.tsx
> -      autoCompleteVisible: false,
@Rishabh-Rathod sure!

2021-10-01 10:04 UTC, Hard-Coder05 commented
@Rishabh-Rathod You can review this PR now!

2021-10-05 15:54 UTC, Rishabh-Rathod commented on app/client/src/components/formControls/FilePickerControl.tsx
> -      text: "Select file to upload",
Please Also remove the particular state from `FieldFileInputState`

2021-10-05 15:54 UTC, Rishabh-Rathod commented on app/client/src/pages/Applications/index.tsx
> -      selectedOrgId: "",
Also remove the type from Applications state

2022-09-08 20:34 UTC, closed without merging