Remove symbol to open in new tab from intercom tab on sidebar
appsmithorg/appsmith pull request #8084
Opened 2021-10-01 15:02 UTC by rafaeelaudibert

Fixes #4911

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-10-04 07:33 UTC, Rishabh-Rathod requested changes

2021-10-04 07:33 UTC, Rishabh-Rathod commented on app/client/src/components/designSystems/appsmith/help/DocumentationSearch.tsx
> -          <StyledOpenLinkIcon
This changes will remove icon for all the HelpMenuItem instead of just intercom. 

I would suggest 

```
const HELP_MENU_ITEMS: HelpItem[] = [
  {
    icon: <StyledDocumentIcon color="#181F24" height={14} width={11.2} />,
    label: "Documentation",
    link: "https://docs.appsmith.com/",
    showLinkIcon: true
  },
  {
    icon: <StyledGithubIcon color="#fff" height={14} width={11.2} />,
    label: "Report a bug",
    link: "https://github.com/appsmithorg/appsmith/issues/new/choose",
    showLinkIcon: true
  },
  {
    icon: <StyledDiscordIcon height={16} width={16} />,
    label: "Join our Discord",
    link: "https://discord.gg/rBTTVJp",
    showLinkIcon: true
  },
];

if (intercomAppID && window.Intercom) {
  HELP_MENU_ITEMS.push({
    icon: <StyledChatIcon color="#fff" height={14} width={11.2} />,
    label: "Chat with us",
    id: "intercom-trigger",
    showLinkIcon: false
  });
}
```
Adding `showLinkIcon` to the data and adding a condition for 
`<StyledOpenLinkIcon/>` to only show when `showLinkIcon` is true

2021-11-06 03:44 UTC, rafaeelaudibert commented
@Rishabh-Rathod Is there something I need to do from those test results?

2021-11-09 11:28 UTC, Rishabh-Rathod commented
> @Rishabh-Rathod Is there something I need to do from those test results?

test failures could be due to your fork branch not having the latest appsmith's `release` branch changes.
You might need to rebase again.

2021-11-28 10:41 UTC, rafaeelaudibert commented
I sadly won't have the time to keep working on this. I'll be closing it.

2021-11-28 10:41 UTC, closed without merging