fix: Enhance sort icon layout in Table
appsmithorg/appsmith pull request #8140
Opened 2021-10-04 02:10 UTC by Cool-Runningz

## Description

This PR address the shifting layout display issue that would occur when clicking through the sorting options within the Table header. It also addresses the low contrast icon color for better accessibility.

Fixes #6905 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- This has been tested manually by adding a Table widget and sorting within the Table header(s).

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-10-05 05:52 UTC, somangshu approved these changes
Some changes requested in the comments 👇 

Approving to run the workflow

2021-10-05 05:52 UTC, somangshu commented on app/client/src/widgets/TableWidget/component/TableUtilities.tsx
> +      ) : (
Moving the text like this is not the right way to go, We should rather place it on the right end of the cell.

2021-10-05 05:52 UTC, somangshu commented on app/client/src/widgets/TableWidget/component/TableUtilities.tsx
> +      fill: ${Colors.OXFORD_BLUE};
Use `LIGHT_GREYISH_BLUE` instead, the same for the above

2021-10-05 22:39 UTC, Cool-Runningz commented
@somangshu I have addressed the comments and this PR is ready for another review at your earliest convenience. Thanks!

2021-10-06 06:16 UTC, somangshu requested changes
One small change, The rest looks good to me.

2021-10-06 06:16 UTC, somangshu commented on app/client/src/widgets/TableWidget/component/TableUtilities.tsx
>          <SortIconWrapper>
I see another challenge stemming from this, The icon alignment is not Appropriate because of this, Check this out, The header is hidden right now, And the header row height is more that before! 
<img width="441" alt="Screenshot 2021-10-06 at 11 42 11 AM" src="https://user-images.githubusercontent.com/11089579/136149915-e79e9e69-5630-4fb6-afa7-6f7863979004.png">

Simply removing this style resolves the challenge, Lets clean the code here, Replace this with a simple `div`

2021-10-08 14:38 UTC, Cool-Runningz commented
@somangshu I have addressed the changes you requested so this is ready for another review whenever you get the chance.

2021-10-08 16:38 UTC, Cool-Runningz commented
@somangshu Thank you for that information. I have updated my branch with the latest from the `release` branch so this should be ready for another review/pass through the tests.

2021-10-10 06:13 UTC, somangshu commented
/ok-to-test sha=e988b51

2021-10-12 01:55 UTC, Cool-Runningz commented
@somangshu I noticed that the build had failed again so I pulled in the latest changes from the `release` branch so hopefully it will actually work this time and can get moved along. Thank you for your help throughout this.

2021-10-12 04:55 UTC, somangshu commented
/ok-to-test sha=d835657

2021-10-12 14:57 UTC, Cool-Runningz commented
@somangshu Sorry to keep bugging you about this but do you have any idea as to why the tests keep failing? I didn't think my changes were that destructive but for some reason the tests don't pass 😞

2021-10-13 05:10 UTC, somangshu commented
@Cool-Runningz please dont worry about that, Happy to help 🙂 

We are currently facing some issues on the PRs from external contributors, Our team is looking into this. Since your code is already approved, This will be counted in the hacktoberfest, We have created [an app](https://app.appsmith.com/applications/61628980ea18372f051057a6/pages/61628980ea18372f051057aa) for our contributor to submit these entries, Kindly do so, And it will considered by out team.

Meanwhile Ill look into what needs to be done here.

2021-11-03 10:44 UTC, somangshu commented
Merging this as its working fine here

2021-11-03 10:45 UTC, merged