feat: Table widget row selection using primary column
appsmithorg/appsmith pull request #8156
Opened 2021-10-04 09:47 UTC by vicky-primathon

## Description
Allow users to select a column as primary columns and row selection using the primary column

Fixes #4990
Fixes #7920 

## Type of change
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-10-07 23:08 UTC, riodeuno commented
@vicky-primathon Could you describe how this feature works? I don't understand the part about how we select a row after one of the selected rows is deleted.

2021-10-08 08:43 UTC, vicky-primathon commented
> @vicky-primathon Could you describe how this feature works? I don't understand the part about how we select a row after one of the selected rows is deleted.

To update selected rows, we use primaryKeys of old data and filter that against the new table data whenever row(s) are deleted by user.

2021-11-02 08:45 UTC, riodeuno commented
@vicky-primathon Please look into the multi-select table's interaction in this feature. We seem to have regressed. 
- [ ] Please add a cypress test for this scenario.

https://user-images.githubusercontent.com/103687/139814096-83f8341f-6ac6-4de3-a778-2d14766be82a.mov

2021-11-02 08:45 UTC, riodeuno requested changes
Please add a cypress test after fixing the multi-select table scenario.

2021-11-03 10:10 UTC, vicky-primathon commented
/ok-to-test sha=145867f

2021-11-09 04:56 UTC, riodeuno submitted a review, later dismissed

2021-11-09 12:18 UTC, jsartisan commented
@Tooluloope assigning you as the reviewer.

2021-11-10 09:15 UTC, vicky-primathon commented
/ok-to-test sha=0bcf14c

2021-11-10 09:18 UTC, vicky-primathon commented
https://github.com/appsmithorg/appsmith/actions/runs/1443422600

2021-11-14 18:08 UTC, Tooluloope reviewed
Hi @vicky-primathon 
Doesn't look like it fixes #4990 
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/799f86d81ff045b3ad2f17c51066a584-00001.gif)](https://www.loom.com/share/799f86d81ff045b3ad2f17c51066a584)


Also Going by @somangshu [comment](https://github.com/appsmithorg/appsmith/issues/7920#issuecomment-929862100), triggered row is meant to be unset

https://www.loom.com/share/b338028b4de34767adfc7e35eab844f6

2021-11-14 23:30 UTC, Tooluloope commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/Table_MultiRowSelect_dataUpdation_spec.js
> +});
@vicky-primathon, I noticed there was no cypress test for the feature or any of the bugs fixed.

2021-11-14 23:31 UTC, Tooluloope commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/Table_MultiRowSelect_dataUpdation_spec.js
> +});
Lastly, I'm not sure I understand the feature totally, Because I noticed I was able to update the selectedRows using any of the column apart from the the primaryColumn

2021-11-15 01:08 UTC, Tooluloope requested changes

2021-11-15 01:08 UTC, Tooluloope commented on app/client/src/widgets/TableWidget/widget/index.tsx
> +    if (!this.props.multiRowSelection) {
There are so many inconsistencies when updating `selectedRowIndices` and `selectedRowIndex` in this file,
is it possible to make a general function for them.

2021-11-19 12:04 UTC, vicky-primathon commented
/ok-to-test sha=d325600

2021-11-24 04:26 UTC, vicky-primathon commented
/ok-to-test sha=b01a7ff

2021-12-01 08:14 UTC, vicky-primathon commented on app/client/src/widgets/TableWidget/widget/utilities.test.ts
> +  it("With no new data", () => {
This was intentional

2021-12-03 07:28 UTC, YogeshJayaseelan commented
@vicky-primathon Verified the fix for #7920 and #4990 and please find the status below,

#7920 - **is fixed**
#4990 - **Not fixed** - Update any particular row updates the row but the row selection navigates to the default selected row

https://www.loom.com/share/c7766a799fee4314b5bd6fd73acf486d

2021-12-03 07:42 UTC, Tooluloope approved these changes

2021-12-03 10:03 UTC, vicky-primathon commented
> @vicky-primathon Verified the fix for #7920 and #4990 and please find the status below,
> 
> #7920 - **is fixed** #4990 - **Not fixed** - Update any particular row updates the row but the row selection navigates to the default selected row
> 
> [![LOOM DEMO](https://camo.githubusercontent.com/10b5e71f8a8d42fca779deaef06153d1de4d2ad37df16c7775ceebf081325b55/687474703a2f2f63646e2e6c6f6f6d2e636f6d2f73657373696f6e732f7468756d626e61696c732f63373736366137393966656534333134623562643666643733616366343836642d30303030312e676966)](https://www.loom.com/share/c7766a799fee4314b5bd6fd73acf486d)

@vivekverma2312 primary key property in Table widget configuration needs to be configured to a column which will not change and which has a unique value (eg _id)

2021-12-07 09:01 UTC, vicky-primathon commented
/ok-to-test sha=d2fdf56

2021-12-07 09:48 UTC, YogeshJayaseelan commented
@vicky-primathon Tested fix for #4990 after configuring the table primary key the updated row functionality works as expected and verified the fix for #7920 triggered row is also working fine

2021-12-07 11:05 UTC, vicky-primathon commented
/ok-to-test sha=e1f41f9

2021-12-08 12:32 UTC, vicky-primathon commented
/ok-to-test sha=955f064

2021-12-08 14:06 UTC, merged