feat: JSON Form widget
appsmithorg/appsmith pull request #8472
Opened 2021-10-12 14:02 UTC by ashit-rath

## Description
This widget generates forms with input fields automatically from any JSON data source. Generated form field's properties can be modified to cater to the form's functionality. 
It supports arrays and objects with n-level depth but the property pane can show properties of nested fields up to 5 levels of depth only, beyond that the configuration object has to be edited manually.

### Nomenclature
- Field - A field is an input entity on the form. It can be a multi-select, radio input, text input, etc.
- Schema - This is a representation of the form that is generated from the JSON. It holds every configuration for every field and it can be considered as the source of truth for the form. 
- SchemaItem - Each individual field's state in the schema is a schema item.
- Source data - It is the JSON input that is provided by the Appsmith user from which the form fields are generated.

### Sample source data and corresponding schema structure:
```JSON
{
  "name": "John",
  "age": 10
}
```

Schema
```js
{
  __root_schema__: {
    isDisabled: false,
    isRequired: false,
    label: "",
    isVisible: true,
    children: {
      name: {
        isDisabled: false,
        isRequired: false,
        label: "Name",
        isVisible: true,
        isSpellCheck: false,
        children: {},
        dataType: DataType.STRING,
        defaultValue:
          "{{((sourceData, formData, fieldState) => (sourceData.name))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
        fieldType: FieldType.TEXT,
        sourceData: "Test name",
        isCustomField: false,
        name: "name",
        accessor: "name",
        identifier: "name",
        originalIdentifier: "name",
        position: 0,
      },
      age: {
        isDisabled: false,
        isRequired: false,
        label: "Age",
        isVisible: true,
        isSpellCheck: false,
        children: {},
        dataType: DataType.NUMBER,
        defaultValue:
          "{{((sourceData, formData, fieldState) => (sourceData.age))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
        fieldType: FieldType.NUMBER,
        sourceData: 20,
        isCustomField: false,
        name: "age",
        accessor: "age",
        identifier: "age",
        originalIdentifier: "age",
        position: 1,
      },
    isCustomField: false,
    name: "",
    accessor: "",
    identifier: "",
    originalIdentifier: "",
    position: -1,
  },
}
```

Fixes #2504 

https://miro.com/app/board/uXjVOXio8tY=/

## Type of change
- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

## How Has This Been Tested?

- Cypress Tests
- Jest Tests
- Manual testing

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: feature/form-builder-widget 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 55.4 **(-0.23)** | 36.87 **(0.01)** | 34.94 **(0)** | 55.7 **(-0.24)**
 :red_circle: | app/client/src/components/ads/DraggableListCard.tsx | 13.46 **(-0.83)** | 3.28 **(-0.17)** | 0 **(0)** | 15.56 **(-1.11)**
 :green_circle: | app/client/src/components/ads/DraggableListComponent.tsx | 41.03 **(0)** | 18.18 **(0)** | 33.33 **(0)** | 44.12 **(1.7)**
 :sparkles: :new: | **app/client/src/components/editorComponents/Tooltip.tsx** | **100** | **100** | **100** | **100**
 :red_circle: | app/client/src/components/propertyControls/BaseControl.tsx | 75 **(-8.33)** | 44.44 **(19.44)** | 50 **(-16.67)** | 71.43 **(-10.39)**
 :sparkles: :new: | **app/client/src/components/propertyControls/ButtonControl.tsx** | **46.43** | **11.76** | **33.33** | **57.14**
 :green_circle: | app/client/src/components/propertyControls/DropDownControl.tsx | 89.29 **(0.4)** | 64.71 **(1.07)** | 71.43 **(0)** | 88 **(0.5)**
 :sparkles: :new: | **app/client/src/components/propertyControls/FieldConfigurationControl.tsx** | **18.8** | **8.33** | **10** | **21.82**
 :sparkles: :new: | **app/client/src/components/propertyControls/JSONFormComputeControl.tsx** | **24.47** | **9.76** | **11.76** | **24.1**
 :red_circle: | app/client/src/components/propertyControls/PrimaryColumnsControl.tsx | 36 **(0)** | 11.94 **(-0.37)** | 19.23 **(0)** | 34.97 **(0)**
 :green_circle: | app/client/src/components/propertyControls/index.ts | 86.49 **(1.2)** | 100 **(0)** | 0 **(0)** | 86.11 **(1.26)**
 :green_circle: | app/client/src/entities/Widget/utils.ts | 93 **(0.14)** | 89.13 **(0)** | 100 **(0)** | 92.86 **(0.15)**
 :red_circle: | app/client/src/icons/WidgetIcons.tsx | 58.76 **(-0.19)** | 100 **(0)** | 14.89 **(-0.33)** | 58.76 **(-0.19)**
 :green_circle: | app/client/src/pages/Editor/PropertyPane/PropertySection.tsx | 90.32 **(0.66)** | 56.25 **(-0.89)** | 83.33 **(0)** | 89.29 **(0.4)**
 :red_circle: | app/client/src/sagas/SnipingModeSagas.ts | 19.44 **(-0.56)** | 3.03 **(-0.1)** | 40 **(0)** | 20.19 **(-0.6)**
 :red_circle: | app/client/src/selectors/propertyPaneSelectors.tsx | 88.89 **(-0.97)** | 70.37 **(-1.63)** | 91.67 **(-8.33)** | 88.71 **(-1.12)**
 :green_circle: | app/client/src/utils/WidgetFactory.tsx | 74.47 **(0.56)** | 72.22 **(1.63)** | 64.71 **(0)** | 74.47 **(0.56)**
 :red_circle: | app/client/src/utils/autocomplete/EntityDefinitions.ts | 26.32 **(-0.71)** | 0 **(0)** | 12.5 **(-1.79)** | 25.71 **(-0.76)**
 :sparkles: :new: | **app/client/src/utils/hooks/useDeepEffect.ts** | **100** | **100** | **100** | **100**
 :green_circle: | app/client/src/widgets/WidgetUtils.ts | 86.27 **(6.9)** | 61.9 **(11.9)** | 62.5 **(8.65)** | 83.33 **(8.82)**
 :red_circle: | app/client/src/widgets/BaseInputWidget/component/index.tsx | 62.6 **(-0.97)** | 44.85 **(-1.11)** | 60 **(-1.36)** | 61.6 **(-1)**
 :red_circle: | app/client/src/widgets/CheckboxWidget/component/index.tsx | 95 **(-1.97)** | 65.71 **(-2.03)** | 92.31 **(1.4)** | 93.75 **(-2.4)**
 :sparkles: :new: | **app/client/src/widgets/JSONFormWidget/FormContext.tsx** | **100** | **100** | **100** | **100**
 :sparkles: :new: | **app/client/src/widgets/JSONFormWidget/constants.ts** | **100** | **100** | **100** | **100**
 :sparkles: :new: | **app/client/src/widgets/JSONFormWidget/helper.ts** | **97.03** | **91.23** | **100** | **96.47**
 :sparkles: :new: | **app/client/src/widgets/JSONFormWidget/index.ts** | **100** | **100** | **100** | **100**
 :sparkles: :new: | **app/client/src/widgets/JSONFormWidget/schemaParser.ts** | **98.17** | **90.3** | **100** | **98.74**
 :sparkles: :new: | **app/client/src/widgets/JSONFormWidget/schemaTestData.ts** | **100** | **100** | **100** | **100**
 :sparkles: :new: | **app/client/src/widgets/JSONFormWidget/component/Accordion.tsx** | **33.33** | **30** | **0** | **41.38**
 :sparkles: :new: | **app/client/src/widgets/JSONFormWidget/component/Field.tsx** | **27.78** | **16.67** | **0** | **29.41**
 :sparkles: :new: | **app/client/src/widgets/JSONFormWidget/component/FieldLabel.tsx** | **35.19** | **20.69** | **0** | **44.19**
 :sparkles: :new: | **app/client/src/widgets/JSONFormWidget/component/Form.tsx** | **29.35** | **20** | **0** | **30.68**
 :sparkles: :new: | **app/client/src/widgets/JSONFormWidget/component/NestedFormWrapper.tsx** | **55.56** | **33.33** | **0** | **55.56**
 :sparkles: :new: | **app/client/src/widgets/JSONFormWidget/component/index.tsx** | **27.08** | **33.33** | **0** | **27.66**
 :sparkles: :new: | **app/client/src/widgets/JSONFormWidget/com [...]

2022-01-25 05:38 UTC, ashit-rath commented
/ok-to-test sha=95d6518

2022-01-27 06:31 UTC, sbalaji1192 reviewed
Notes till widget/utils

2022-01-27 06:31 UTC, sbalaji1192 commented on app/client/src/components/propertyControls/DropDownControl.tsx
> +
Need to move this to validations function itself

2022-01-27 06:31 UTC, sbalaji1192 commented on app/client/src/components/propertyControls/SwitchControl.tsx
> +    const evaluatedValue = get(
Need to reevaluate this

2022-01-27 06:31 UTC, sbalaji1192 commented on app/client/src/entities/DataTree/dataTreeWidget.ts
> +  return _.merge(
Add benchmarks

2022-01-27 06:31 UTC, sbalaji1192 commented on app/client/src/entities/DataTree/dataTreeWidget.ts
> +  return _.merge(
Need fe coders pod signoff. @ApekshaBhosale

2022-01-27 06:31 UTC, sbalaji1192 commented on app/client/src/entities/Widget/utils.ts
> +// "originalWidget" param here always contains the complete widget props
Need clarification

2022-01-27 12:57 UTC, ashit-rath commented
/ok-to-test sha=5768cd5

2022-01-28 07:54 UTC, ashit-rath commented
/ok-to-test sha=f378e2e

2022-01-28 14:10 UTC, ashit-rath commented
/ok-to-test sha=3ebbedf

2022-01-31 11:11 UTC, ashit-rath commented
/ok-to-test sha=dc3b903

2022-02-01 11:11 UTC, sbalaji1192 commented on app/client/src/widgets/JSONFormWidget/widget/propertyConfig/helper.ts
> +export const fieldTypeUpdateHook = (
Add function comments

2022-02-02 10:28 UTC, riodeuno requested changes

2022-02-02 10:28 UTC, riodeuno commented on app/client/src/entities/Widget/utils.ts
> +  originalWidget: WidgetProps,
Please verify if the Table Widget, Menu Button Widget, Tabs Widget, Button Group widget, etc, are working correctly, w.r.t the `hidden` property. Because, we were passing a subset of the original props earlier. Now that we're passing the full widget, maybe the path computations would result in incorrect values and incorrect hidden states as a result.

2022-02-04 03:33 UTC, ashit-rath commented on app/client/src/entities/Widget/utils.ts
> +  originalWidget: WidgetProps,
@riodeuno Tested all the widgets where `panelConfig` is used and they all work fine.

2022-02-04 12:33 UTC, ashit-rath commented
/ok-to-test sha=191be47

2022-02-05 09:45 UTC, ashit-rath commented
/ok-to-test sha=7bcf124

2022-02-07 05:59 UTC, ashit-rath commented
/ok-to-test sha=641dca2

2022-02-11 05:40 UTC, ashit-rath commented
/ok-to-test sha=dc50cc1

2022-02-11 10:41 UTC, ashit-rath commented
/ok-to-test sha=efe0836

2022-02-14 08:18 UTC, ashit-rath commented
/ok-to-test sha=7d37f1f

2022-02-15 12:37 UTC, vivekverma2312 commented
@ashit-rath Please look into few observations, I am still testing the feature.
1. Connect data message is displayed on widget for a sec before loading the default data
2. Removing sample data do not make the widget blank
https://www.loom.com/share/3e8e343aec264f33af079963960b9885
3. Writing source code for multi-select widget still shows default data in drop-down https://www.loom.com/share/83c03bae8ce6473bb9d8618d02dd73b1
4. After I make any change in the form like delete or add and then refresh the page the source code data is updated https://www.loom.com/share/47dcd16b8e5344c48d5b901d3c5c6ac4
5. Sequence of form changes when we make any change in source data https://www.loom.com/share/2ef1480fb3d54a66b013fc6caea50093
6. Changing widget type to Text input displays object by default in field https://www.loom.com/share/9deb7d0a66d04cc5b24a108fb162fa8e

2022-02-15 12:56 UTC, ashit-rath commented
@vivekverma2312 
>1 Connect data message is displayed on widget for a sec before loading the default data

I'll fix this

>2. Removing sample data do not make the widget blank

It's a safety mechanism, there would be cases where the `source data` might get undefiend or empty object from an API that is still fetching the data. If we try to process `undefined` or empty data then the user might lose field configuration.

>3. Writing source code for multi-select widget still shows default data in drop-down

The multi-select field gets default options, that have to be modified by the user. We do not process the default value as options as that might be destructive as the default value might change and we would have to update the options which can get messy.

>4. After I make any change in the form like delete or add and then refresh the page the source code data is updated

Whatever you enter in the form is metadata i.e it is only persisted until you are active on the page. It's similar to the input widget having some default data and upon refresh that is again set.
Similarly array field as some default value i.e 2 entries `curefit` and `appsmith`. 
So on refresh, the same default value of the array is applied.

>5 Sequence of form changes when we make any change in source data

Yeah, it is considered as a new entry (as the property name changes) and get's added at the end. You can reposition is in the property pane `Field Configuration`

>6 Changing widget type to Text input displays object by default in field

This seems to be a bug

2022-02-16 12:11 UTC, vivekverma2312 commented
@ashit-rath 
7. After clicking on add new and deploy the new fields are not displayed. similar behaviour for delete. it deploys the source code data.
https://www.loom.com/share/17ca6ef8f58e4f03920d6e900c764b53
8. Date widget is getting highlighted in blue colour but all other fields ate highlighted in green colour.
<img width="465" alt="Screenshot 2022-02-16 at 5 32 02 PM" src="https://user-images.githubusercontent.com/83569920/154262065-e2b47388-54cf-4144-9299-c0382c100136.png">
<img width="492" alt="Screenshot 2022-02-16 at 5 31 56 PM" src="https://user-images.githubusercontent.com/83569920/154262073-4799d68b-929f-4ae9-b752-973d571a3203.png">

2022-02-17 05:34 UTC, ashit-rath commented
/ok-to-test sha=d11fa49

2022-02-17 06:46 UTC, ashit-rath commented
> 7. After clicking on add new and deploy the new fields are not displayed. similar behaviour for delete. it deploys the source code data.
For arrays using the `Add New` button won't  define how many entries you would have in the deploy mode. It is similar to how entering some text in an input field won't define what the value of that input field would be in the deploy mode.

For changing how many entires show up, you would have to change the default value of the array field in the property pane.

>8. Date widget is getting highlighted in blue colour but all other fields ate highlighted in green colour.
This has to be fixed in the individual widgets itself.

2022-02-17 08:12 UTC, ashit-rath commented
/ok-to-test sha=b90a57d

2022-02-20 17:59 UTC, sbalaji1192 reviewed
Great work !! Have provided some minor callouts and suggestions. please go through them !

2022-02-20 17:59 UTC, sbalaji1192 commented on app/client/src/widgets/JSONFormWidget/fields/MultiSelectField.tsx
> +        schemaItem.defaultValue !== undefined &&
Suggestion: Can use lodash's isNil

2022-02-20 17:59 UTC, sbalaji1192 commented on app/client/src/widgets/JSONFormWidget/fields/RadioGroupField.tsx
> +) => (schemaItem.isRequired ? Boolean(value) : true);
Can this be moved to a common file and be used across multiple fields?

2022-02-20 17:59 UTC, sbalaji1192 commented on app/client/src/widgets/JSONFormWidget/fields/SelectField.tsx
> +
remove empty line

2022-02-20 17:59 UTC, sbalaji1192 commented on app/client/src/widgets/JSONFormWidget/fields/useEvents.ts
> +function useEvents<TElement extends BaseEvents>({
Suggestion: Since its only handling focus and blur, we can rename accordingly.

2022-02-20 17:59 UTC, sbalaji1192 commented on app/client/src/widgets/JSONFormWidget/helper.ts
> +    if (value === undefined || value === null || Number.isNaN(value)) {
use _.isNil

2022-02-20 17:59 UTC, sbalaji1192 commented on app/client/src/widgets/JSONFormWidget/schemaParser.ts
> +  // only for the array level and keep every every field below it as empty default.
typo `every`

2022-02-20 17:59 UTC, sbalaji1192 commented on app/client/src/widgets/JSONFormWidget/schemaParser.ts
> +    const sanitizedName = typeof name === "string" && sanitizeKey(name);
no need to check again `typeof name === "string"`

2022-02-20 17:59 UTC, sbalaji1192 commented on app/client/src/widgets/JSONFormWidget/widget/propertyConfig/generatePanePropertyConfig.ts
> +import { get, isEmpty } from "lodash";
typo in file name. panel is missing `l`

2022-02-20 17:59 UTC, sbalaji1192 commented on app/client/src/widgets/MultiSelectWidgetV2/component/index.tsx
> +  console.log("MULTI WIDGET values", value);
remove

2022-02-20 17:59 UTC, sbalaji1192 commented on app/client/src/widgets/WidgetUtils.ts
> +  let sanitizedKey = key.replace(/[^\w]/gi, "_");
We have started allowing (not merged to release yet) non - ASCII characters in the table column.  we need to start doing same thing in the JSON form as well.

2022-02-21 04:34 UTC, ashit-rath commented on app/client/src/widgets/JSONFormWidget/widget/propertyConfig/generatePanePropertyConfig.ts
> +import { get, isEmpty } from "lodash";
Nice  catch!

2022-02-21 04:42 UTC, ashit-rath commented on app/client/src/components/propertyControls/FieldConfigurationControl.tsx
> +
This new line actually separates node_modules imports from local imports. I know we don't have such conventions but this really helps to identify where things are coming from with a quick glance.

2022-02-21 04:46 UTC, ashit-rath commented on app/client/src/components/propertyControls/JSONFormComputeControl.tsx
> +  if (schemaItem.dataType === DataType.ARRAY) {
I would differ a bit here. As we are returning from the first if condition, else-if is not necessary.

2022-02-21 05:10 UTC, ashit-rath commented on app/client/cypress/support/commands.js
>      .click({ force: true });
Ahh yes, my bad

2022-02-21 06:09 UTC, ashit-rath commented on app/client/cypress/support/commands.js
>      .click({ force: true });
Tested by removing the `wait` in the original command. It doesn't load the panels properly so I think the wait seems to be necessary here.

2022-02-21 07:15 UTC, ashit-rath commented on app/client/src/widgets/JSONFormWidget/fields/BaseInputField.tsx
> +          triggerPropertyName: "onEnterKeyPress",
Actually the event name here is `onEnterKeyPress` which is different to `onSubmit` as in the context of JSONForm `onSubmit` would be a form level-event and `onEnterKeyPress` would be a field level event.
So in order to get proper logs we need to pass `onEnterKeyPress` as the triggerPropertyName, otherwise it might give out incorrect result.

2022-02-21 07:16 UTC, sbalaji1192 commented on app/client/src/widgets/JSONFormWidget/fields/BaseInputField.tsx
> +          triggerPropertyName: "onEnterKeyPress",
sounds good!

2022-02-21 07:25 UTC, ashit-rath commented on app/client/src/widgets/JSONFormWidget/fields/MultiSelectField.tsx
> +    if (option) return option;
Makes sense!

2022-02-28 05:14 UTC, vivekverma2312 commented
@ashit-rath 
9. Fixed footer in view mode is not proper. It is showing outside the form and at bottom of the page. In case of multiple forms also only one button is displayed.
<img width="1777" alt="Screenshot 2022-02-25 at 3 52 03 PM" src="https://user-images.githubusercontent.com/83569920/155698614-96ed8a3f-3c82-4ea5-8967-45ae91da9b6a.png">

10. Valid property is throwing error 
<img width="651" alt="Screenshot 2022-02-28 at 10 42 53 AM" src="https://user-images.githubusercontent.com/83569920/155927774-2ef30a4c-60f2-415a-90da-9572b7c4213b.png">

2022-02-28 07:23 UTC, chandannkumar commented
@ashit-rath I am also testing this PR and have few observations to share

1. Phone Number Input is accepting Characters
https://www.loom.com/share/8d41c59a86c248da9fa37c3320fcce67

2. There is no scroll in dropdown of Field type and Date format dropdown(Select field type as date and see option of Date format)
https://www.loom.com/share/f5aed183405e46e1ae3a750ee64a711f

3. Convert to ISO isn't working for Date Picker field type
https://www.loom.com/share/9dbce6206c9c485dac5eb35059e50154

4. While adding Date picker inside Array displays "Invalid date" by default
https://www.loom.com/share/fb982b15a35d46a49249e1c2cfa12ffe

5. Delete Button doesn't work when Array item of an Array is invisible
https://www.loom.com/share/5c1b9c9d1d094ac08da8759e7738a52b

2022-02-28 11:59 UTC, ashit-rath commented
> @ashit-rath 9. Fixed footer in view mode is not proper. It is showing outside the form and at bottom of the page. In case of multiple forms also only one button is displayed. <img alt="Screenshot 2022-02-25 at 3 52 03 PM" width="1777" src="https://user-images.githubusercontent.com/83569920/155698614-96ed8a3f-3c82-4ea5-8967-45ae91da9b6a.png">
> 
> 10. Valid property is throwing error
> 
> <img alt="Screenshot 2022-02-28 at 10 42 53 AM" width="651" src="https://user-images.githubusercontent.com/83569920/155927774-2ef30a4c-60f2-415a-90da-9572b7c4213b.png">

For 10. There is a `()` after name
Should the binding look like this?
```
{{formData.name.FirstName.length > 5}}
```

2022-02-28 13:54 UTC, ashit-rath commented
@chandannkumar 
>1. Phone Number Input is accepting Characters

I'll look into this

>2. There is no scroll in dropdown of Field type and Date format dropdown(Select field type as date and see option of Date format)

This is an issue with every dropdown field in the property pane and I think the UI builders pod are looking into it.

>3. Convert to ISO isn't working for Date Picker field type

The convert to ISO does not change the value that you see in the input to ISO but changes the value of that particular field in the `formData` property. Try binding `JSONForm1.formData` to a text widget and toggle this.
Do you think we should update the hint of this property in some way to help user understand this better.

>4 While adding Date picker inside Array displays "Invalid date" by default

I will check this

>5 Delete Button doesn't work when Array item of an Array is invisible

Nice catch! I'll look into this as well

2022-03-07 02:44 UTC, ashit-rath commented
/ok-to-test sha=060283b

2022-03-07 05:32 UTC, ashit-rath commented
/ok-to-test sha=384e28f

2022-03-08 05:01 UTC, ashit-rath commented
/ok-to-test sha=8bafdd4

2022-03-09 18:46 UTC, sbalaji1192 commented on app/client/src/widgets/WidgetUtils.ts
> +  sanitizedKey = sanitizedKey.replace(/[^\w]/gi, "_");
both `$test` and `#test` will converted to `_test`. This was the original problem with sanitizeKey function. But I guess there is no way to avoid that situation.

2022-03-09 18:46 UTC, sbalaji1192 commented on app/client/src/widgets/WidgetUtils.ts
> +    const keyToIndexMap = generateKeyToIndexMap(existingKeys);
Move this declaration after L236

2022-03-09 18:46 UTC, sbalaji1192 commented on app/client/src/widgets/JSONFormWidget/widget/propertyConfig/helper.ts
> +  return;
not necessary

2022-03-09 18:46 UTC, sbalaji1192 commented on app/client/src/widgets/JSONFormWidget/widget/propertyConfig/helper.ts
> +  const then = (cb: (props: TSchemaItem) => any) => cb(schemaItem);
Could we come up with a better name instead of `then` ?

2022-03-09 18:46 UTC, sbalaji1192 commented on app/client/src/widgets/JSONFormWidget/helper.ts
> +  if (hasPrimitive && hasObject) return false;
return !(hasPrimitive && hasObject) should suffice.

2022-03-09 18:50 UTC, sbalaji1192 commented on app/client/src/widgets/WidgetUtils.ts
> +const punycode = require("punycode/");
can't we use import syntax ?

2022-03-11 03:07 UTC, ashit-rath commented on app/client/src/components/propertyControls/JSONFormComputeControl.tsx
> +      obj = processSchemaItem(schemaItem, defaultValue);
Removed the function, was unecessary

2022-03-11 03:10 UTC, ashit-rath commented on app/client/src/components/ads/DraggableListCard.tsx
> +  const renderVisibilityIcon = () => {
Why do we need to use `useMemo` here? It's not being used for referential equality and there is no heavy computation. Can you think of a reason of using it?

2022-03-11 03:14 UTC, ashit-rath commented on app/client/src/widgets/JSONFormWidget/fields/ArrayField.tsx
> +  const add = () => {
Same here as well, I don't see the point of using `useCallback` here, won't seem to improve any perf gain as this is not being passed as a prop to a heavy component or a part of another effect or callback. Please do let me know if I'm missing something here.

2022-03-11 03:15 UTC, ashit-rath commented on app/client/src/widgets/JSONFormWidget/component/FieldLabel.tsx
> +  // If field and label are to be displayed horizontally then we consider the alignField
Force of habit 😅. I'll make sure to use multi-line

2022-03-11 03:17 UTC, ashit-rath commented on app/client/src/widgets/WidgetUtils.ts
> +  sanitizedKey = sanitizedKey.replace(/[^\w]/gi, "_");
Yes, it will get converted but the second `_test` would get converted to `_test1` if we pass our `existingKeys` with correct previous generated keys.

2022-03-11 03:53 UTC, ashit-rath commented on app/client/src/widgets/WidgetUtils.ts
> +const punycode = require("punycode/");
There is a soft deprecation warning in the esm syntax import and they recommend 
```
Use require('punycode/') to import userland modules rather than core modules.
```

2022-03-11 04:57 UTC, sbalaji1192 commented on app/client/src/widgets/WidgetUtils.ts
> +  sanitizedKey = sanitizedKey.replace(/[^\w]/gi, "_");
The problem is finding which one is $test and #test.

2022-03-11 04:58 UTC, sbalaji1192 commented on app/client/src/widgets/WidgetUtils.ts
> +  sanitizedKey = sanitizedKey.replace(/[^\w]/gi, "_");
But We got to live with it.

2022-03-11 04:58 UTC, sbalaji1192 commented on app/client/src/widgets/WidgetUtils.ts
> +const punycode = require("punycode/");
Sounds good. Could you add comment for future references?

2022-03-11 05:17 UTC, ashit-rath commented
/ok-to-test sha=17f43c3

2022-03-11 05:22 UTC, ashit-rath commented on app/client/src/widgets/WidgetUtils.ts
> +  sanitizedKey = sanitizedKey.replace(/[^\w]/gi, "_");
Yeah, we have to. It's a trade-off

2022-03-11 06:40 UTC, sbalaji1192 commented on app/client/src/entities/DataTree/dataTreeWidget.ts
> +    defaultMetaProps,
Any Updates on this?

2022-03-11 07:44 UTC, ashit-rath commented on app/client/src/entities/DataTree/dataTreeWidget.ts
> +    defaultMetaProps,
Yeah, I'm actually looking into this right now. 
I re-arranged it for a reason but I do now feel like it's an unnecessary change but need to verify.
I'll update once I check

2022-03-11 07:50 UTC, ashit-rath commented on app/client/src/components/ads/DraggableListCard.tsx
> +  const renderVisibilityIcon = () => {
I don't think the perf gain that we would get here would be significant as we would pass some dependencies to the `useMemo` which we need to make sure that they have referentially equal. 
With this ordeal, the number of comparisons we would be doing would probably nullify the difference we would have otherwise.

2022-03-11 07:52 UTC, ashit-rath commented on app/client/src/widgets/JSONFormWidget/fields/ArrayField.tsx
> +  const add = () => {
I would differ here we shouldn't just do such optimizations as they come at a cost.  React is very fast and we shouldn't pre-optimize it like this, eventually, it would just cause degradation in performance due to the no of comparisons that would be happening all over the place.

2022-03-11 07:55 UTC, ashit-rath commented on app/client/src/widgets/JSONFormWidget/fields/ArrayField.tsx
> +  const add = () => {
There is a great article for when using useMemo and useCallback makes sense
https://kentcdodds.com/blog/usememo-and-usecallback

2022-03-11 08:32 UTC, ashit-rath commented on app/client/src/entities/DataTree/dataTreeWidget.ts
> +    defaultMetaProps,
@sbalaji1192 Reverted the order change.

2022-03-11 09:04 UTC, chandannkumar commented
@ashit-rath Please look into these observations also:

12. App crash right after adding Json form widget onto canvas
https://www.loom.com/share/10950135f2444eb6a49fe42b84d5cf43

13. App crash when using array at starting of the source code in view and edit mode
https://www.loom.com/share/bb7b5420861744d48a28d7e88ee46349

14. App crash after changing the existing Input type field to Array field
https://www.loom.com/share/2f203737cf9f4bf29fe6162a313ca10f

15. Behavior on adding multiple objects in an array. In video it shows: when we add objects with same name, its creates 1 Array items and only 1 field configuration, but when i tried to add new object with same name but in lower case, a new field got added inside the array item
https://www.loom.com/share/449d0f20c1b24d26a9607283afc99371 

16.  Unable to view icon dropdown after click on icon field of submit and reset button
![image](https://user-images.githubusercontent.com/95341241/157836070-80a17a25-0b1d-4a78-9b51-2cb664bc9ae3.png)

2022-03-11 10:36 UTC, ashit-rath commented
/ok-to-test sha=c8ec98d

2022-03-11 17:27 UTC, ashit-rath commented
@chandannkumar 
> 15. Behavior on adding multiple objects in an array. In video it shows: when we add objects with same name, its creates 1 Array items and only 1 field configuration, but when i tried to add new object with same name but in lower case, a new field got added inside the array item

Yes the keys are case sensitive so the behaviour you are seeing is valid.

> 16. Unable to view icon dropdown after click on icon field of submit and reset button

This is being fixed in another PR #11736

2022-03-12 07:37 UTC, ashit-rath commented
/ok-to-test sha=ba1aad4

2022-03-14 06:11 UTC, ashit-rath commented
/ok-to-test sha=a359612

2022-03-14 15:09 UTC, ashit-rath commented
/ok-to-test sha=162ccae

2022-03-16 09:05 UTC, ashit-rath commented
/ok-to-test sha=230dba0

2022-03-17 05:58 UTC, ashit-rath commented
/ok-to-test sha=230dba0

2022-03-18 05:38 UTC, ashit-rath commented
/ok-to-test sha=bad7ecf

2022-03-21 05:23 UTC, chandannkumar commented
@ashit-rath 
This feature PR has been Tested and working as expected.
Also all the reported bugs are fixed and verified.

2022-03-21 05:27 UTC, ashit-rath commented
/ok-to-test sha=59ab73e

2022-03-21 08:09 UTC, ashit-rath commented
/ok-to-test sha=59ab73e

2022-03-21 19:10 UTC, sbalaji1192 approved these changes
Great Work!. Had few minor comments.

2022-03-22 06:02 UTC, ashit-rath commented on app/client/src/widgets/JSONFormWidget/widget/propertyConfig.ts
> +  if (_.isNil(value)) {
JSON.parse in line 45 would throw an error for an empty value and hence we would show an error.

2022-03-22 06:06 UTC, sbalaji1192 commented on app/client/src/widgets/JSONFormWidget/widget/propertyConfig.ts
> +  if (_.isNil(value)) {
Let's explicitly handle the empty value.

2022-03-22 07:30 UTC, ashit-rath commented on app/client/src/widgets/JSONFormWidget/widget/propertyConfig.ts
> +  if (_.isNil(value)) {
Okay

2022-03-22 08:58 UTC, sbalaji1192 approved these changes
LGTM!

2022-03-22 13:09 UTC, ashit-rath commented
/ok-to-test sha=6b0bb00

2022-03-24 07:13 UTC, merged

2022-04-05 14:04 UTC, Rishabh-Rathod commented on app/client/src/components/ads/DraggableListCard.tsx
> +        }}
shouldn't we avoid each time re-creation of a function instead use `useCallback` here, this also makes sure the children won't re-render due to a change of the `onClick` function reference.
@ashit-rath

2022-04-05 14:17 UTC, Rishabh-Rathod commented on app/client/src/entities/DataTree/dataTreeWidget.ts
> +   * Spread operator does not merge deep objects properly.
The spread operator doesn't recursively merge objects, I believe that is known behavior and worked as expected. Did we face any issue for which we added lodash merge? 

@ashit-rath

2022-04-06 06:55 UTC, ashit-rath commented on app/client/src/entities/DataTree/dataTreeWidget.ts
> +   * Spread operator does not merge deep objects properly.
With the JSONForm, we started dealing we deeply nested objects and during an update, it failed to merge the old properties with the new ones.

2022-04-06 07:05 UTC, ashit-rath commented on app/client/src/components/ads/DraggableListCard.tsx
> +        }}
I'm not 100% sure if that would give us a significant perf gain as this is just an icon component (pretty light). Do we see a perf drop here?

2022-04-06 15:46 UTC, Rishabh-Rathod commented on app/client/src/entities/DataTree/dataTreeWidget.ts
> +   * Spread operator does not merge deep objects properly.
Got it. Thanks.

2022-06-07 19:09 UTC, Rishabh-Rathod commented on app/client/src/widgets/JSONFormWidget/fields/BaseInputField.tsx
> +        executeAction({
Any reason why we trigger `executeAction` onTextChange here asking as normally in input widget we trigger `updateWidgetMetaProperty` which triggers `onTextChange` with debounce.

2022-06-08 05:19 UTC, ashit-rath commented on app/client/src/widgets/JSONFormWidget/fields/BaseInputField.tsx
> +        executeAction({
@Rishabh-Rathod If you see the Input widget we have a similar `onTextChange` event and the json form's input field replicates that behavior. This will only run if the user has set this action up in the property pane.

Regarding how the value updates, we use the `updateWidgetMetaProperty` but in a different way. You won't find it in this file though.