feat: Tab widget should have navigation arrows when the tabs don't fit
appsmithorg/appsmith pull request #8630
Opened 2021-10-20 05:42 UTC by wmdev0808

## Description
When a tab widget has many pages and not enough space to show all of them, there need to be arrows that allow the user to navigate the list and find the tab they need.
A search for tabs could be optional and useful too.

Fixes #3429 

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Test A
- Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: feat/3429-tab-add-nav-arrows 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 55.1 **(0.04)** | 36.58 **(0.02)** | 34.54 **(0.03)** | 55.6 **(0.03)**
 :sparkles: :new: | **app/client/src/widgets/TabsWidget/constants.ts** | **100** | **100** | **100** | **100**
 :red_circle: | app/client/src/widgets/TabsWidget/component/index.tsx | 89.11 **(-10.89)** | 65 **(-18.33)** | 81.82 **(-18.18)** | 90.7 **(-9.3)**
 :green_circle: | app/client/src/widgets/TabsWidget/widget/index.tsx | 78.57 **(1.15)** | 47.14 **(0)** | 78.95 **(0)** | 77.78 **(0.51)**</details>

2021-10-20 08:48 UTC, wmdev0808 commented
> @wmdev0808 both arrows are on the same side of the tabs was this the requirement?
> 
> <img alt="tabs" width="507" src="https://user-images.githubusercontent.com/35134347/138047137-a8fbce08-0a1b-4c6c-8cd9-f66e30a11dc9.png">
> 
> @momcilo-appsmith cud you pls do a design review of this scrollable tab header?

@marks0351 , there is no any specific requirements on the design, so it has been implemented by my own decision

2021-12-25 11:58 UTC, wmdev0808 commented
/ok-to-test sha=53617fe

2021-12-27 05:36 UTC, marks0351 requested changes
resizing widget doesn't seem to properly show scrollable indicators. pls check.
Pls add test cases around this feature.

2021-12-27 05:36 UTC, marks0351 commented on app/client/src/widgets/TabsWidget/component/index.tsx
> +    if (isFirstRender.current) {
why do we need this isFirstRender ref?

2021-12-27 05:36 UTC, marks0351 commented on app/client/src/widgets/TabsWidget/component/index.tsx
> +        return;
pls remove return statement and use an if else for readability and consistency.

2021-12-27 05:36 UTC, marks0351 commented on app/client/src/widgets/TabsWidget/component/index.tsx
> +  }, [tabScrollIndex, tabRefs]);
tabRefs refs don't trigger effect, remove it as dependency and check if the code performs as expected.

2021-12-27 09:08 UTC, wmdev0808 commented on app/client/src/widgets/TabsWidget/component/index.tsx
> +    if (isFirstRender.current) {
You're right, that was just dead code, thank you

2021-12-27 10:11 UTC, wmdev0808 commented on app/client/src/widgets/TabsWidget/component/index.tsx
> +  }, [tabScrollIndex, tabRefs]);
No, it is required, we are keeping the refs as a state, we  need to calculate visible tabs width based on updated tabRefs state

2021-12-27 10:41 UTC, jsartisan commented on app/client/src/widgets/TabsWidget/component/index.tsx
> +    if (isFirstRender.current) {
@marks0351 resizing/dragging are very flaky with cypress. In the past, I tried adding a few tests related to dragging/resizing but they were flaky. In the end, had to comment out those tests.

2021-12-27 10:47 UTC, marks0351 commented on app/client/src/widgets/TabsWidget/component/index.tsx
> +    if (isFirstRender.current) {
my bad...i meant to write test cases for the enhancement. we can skip resize cases if it is going to introduce flakiness.

2021-12-27 10:50 UTC, wmdev0808 commented on app/client/src/widgets/TabsWidget/component/index.tsx
> +  }, [tabScrollIndex, tabRefs]);
No, it triggers effect.
tabRefs is not a ref, it's just a state(an array of refs), it is required to properly set `isMaxScrolled` state

2021-12-27 14:50 UTC, wmdev0808 commented
/ok-to-test sha=f1fd1ef

2021-12-29 17:58 UTC, marks0351 requested changes
code looks fine to me. 
have a minor comment about the yarn.lock file.
pls move this to QA.

2021-12-29 17:58 UTC, marks0351 commented on app/client/yarn.lock
> +ansi-escapes@^4.1.0, ansi-escapes@^4.3.0:
can u pls check why these yarn dependencies have changed now?

2022-01-04 20:18 UTC, wmdev0808 commented
/ok-to-test sha=7499680

2022-01-05 06:59 UTC, somangshu commented
@yatinappsmith @Aishwarya-U-R the Table_Widget_Add_button_spec.js is still failing, Can you guys tell us how to move forward?

2022-01-05 07:01 UTC, yatinappsmith commented
@NandanAnantharamu Can you review this failure

2022-01-05 07:28 UTC, NandanAnantharamu commented
> @NandanAnantharamu Can you review this failure

@somangshu latest run i see this test is working, i checked failure run looks like intermittent

2022-01-05 07:30 UTC, somangshu commented
@NandanAnantharamu can you point where are you seeing the tests passing, I can see the failure in all above actions

2022-01-05 07:39 UTC, NandanAnantharamu commented
> @NandanAnantharamu can you point where are you seeing the tests passing, I can see the failure in all above actions

@somangshu https://dashboard.cypress.io/projects/eyxvp8/runs/13594/overview

2022-01-05 08:41 UTC, somangshu commented
> https://dashboard.cypress.io/projects/eyxvp8/runs/13594/overview

I see failures here too!

2022-01-05 09:16 UTC, NandanAnantharamu commented
> > https://dashboard.cypress.io/projects/eyxvp8/runs/13594/overview
> 
> I see failures here too!

yeah, this is a different failure, looks intermittent . These are not seen in other PR though

2022-01-05 09:18 UTC, somangshu commented
RE-running tests in that case

2022-01-06 11:49 UTC, marks0351 approved these changes

2022-01-11 13:28 UTC, wmdev0808 commented
/ok-to-test sha=07aabb3

2022-01-11 19:48 UTC, wmdev0808 commented
/ok-to-test sha=a6608e7

2022-01-12 05:04 UTC, merged