fix: Table Widget Icon Button should be having a default variant
appsmithorg/appsmith pull request #8664
Opened 2021-10-20 15:08 UTC by wmdev0808

## Description
Icon Button in the table widget should be having a default button variant selection.
It should be selected as PRIMARY by default and the Icon button should look like a PRIMARY button.
Right now, the variant selection is empty and the icon button is behaving like a TERTIARY button.
This is going to create inconsistencies in the future.

Fixes #8527 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Test A
- Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/8527-table-icon-button-default-variant 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 54.64 **(0.01)** | 36.37 **(0.02)** | 33.1 **(0.01)** | 55.16 **(0.01)**
 :green_circle: | app/client/src/utils/DSLMigrations.ts | 73.74 **(0.12)** | 65.09 **(-0.05)** | 70.21 **(0)** | 73.55 **(0.12)**
 :green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.26 **(0.22)** | 41.25 **(0.83)** | 34.48 **(0)** | 56.22 **(0.26)**
 :red_circle: | app/client/src/utils/migrations/TableWidget.ts | 84.03 **(-0.79)** | 75 **(-0.76)** | 90 **(-2.59)** | 85.65 **(-1.08)**
 :red_circle: | app/client/src/widgets/TableWidget/widget/index.tsx | 26.67 **(0)** | 6.02 **(-0.03)** | 28 **(0)** | 26.56 **(0)**</details>

2021-10-20 15:09 UTC, wmdev0808 commented
/ok-to-test sha=f196ff9

2021-11-02 04:59 UTC, aswathkk requested changes
@wmdev0808 I've discussed with @riodeuno and found that the ideal way to provide default value for buttonVariant would be to provide it inside [`getTableColumns()`](https://github.com/appsmithorg/appsmith/blob/77e3c4f4db24fa65a05aa834902d9bd7a66e89a0/app/client/src/widgets/TableWidget/widget/index.tsx#L243) function.

2021-11-18 20:03 UTC, wmdev0808 commented
/ok-to-test sha=01072d0

2021-11-19 07:00 UTC, aswathkk requested changes
I think we need a migration here

Release:
![Screenshot 2021-11-19 at 12 26 45 PM](https://user-images.githubusercontent.com/10436935/142579028-273df0d0-345e-4ed2-8d79-6ea98f513212.png)

After this PR:
![Screenshot 2021-11-19 at 12 26 55 PM](https://user-images.githubusercontent.com/10436935/142578993-a5e58d13-36f5-4f28-b837-acf2baebe94c.png)

2021-11-19 10:43 UTC, wmdev0808 commented
/ok-to-test sha=b9fa0c3

2021-11-19 11:29 UTC, aswathkk requested changes
@wmdev0808 Have you tried to see the Deploy preview?
It is throwing errors on migration.

2021-11-19 11:29 UTC, aswathkk commented on app/client/src/utils/migrations/TableWidget.ts
> +      child.primaryColumns.forEach((accessor: string) => {
`child.primaryColumns` is an object and it doesn't have `forEach` method.

2021-11-19 11:29 UTC, aswathkk commented on app/client/src/utils/migrations/TableWidget.ts
> +      child.primaryColumns.forEach((accessor: string) => {
This error is being thrown at Deploy preview

2021-11-19 12:36 UTC, wmdev0808 commented
/ok-to-test sha=2ac0aab

2021-11-19 13:01 UTC, aswathkk requested changes
@wmdev0808 If you do not alter buttonVariant of an icon button on release, you will see it will be styled as "TERTIARY" button. We want to keep that behaviour for existing users. That's why migration is required.

For more info, check out the [previous comment](https://github.com/appsmithorg/appsmith/pull/8664#pullrequestreview-810814808) to see how my application's icon button behaved when I switched from release to this PR.

2021-11-19 13:15 UTC, wmdev0808 commented on app/client/src/utils/migrations/TableWidget.ts
> +            primaryColumn.buttonVariant = "PRIMARY";
I can't understand your point.
My code is just applying changes if the current table column has no buttonVariant property, so it should be PRIMARY by default

2021-11-19 13:28 UTC, wmdev0808 commented
/ok-to-test sha=a699ab4

2021-11-19 13:54 UTC, aswathkk approved these changes

2021-11-23 14:10 UTC, merged