Fix SQL typo
appsmithorg/appsmith pull request #871
Opened 2020-10-01 16:21 UTC by alphaX86

I've found typo in your README file and got it covered! Let me know if I need to make any changes! :)

2020-10-01 16:21 UTC, alphaX86 commented on README.md
> +* **Works with existing, live databases**: Connect directly to any PostgreSQL, MySQL, MongoDB and with any SQL Databases
Changes made...

2020-10-01 16:32 UTC, Nikhil-Nandagopal requested changes
Hi, we don't support all SQL databases. Please keep the sentence the same with only the typo changes 🙂

2020-10-01 16:34 UTC, alphaX86 commented
Got it! Wait a sec....

2020-10-01 16:36 UTC, alphaX86 commented on README.md
> +* **Query data**: Query & update your database directly from the UI. Connect to **PostgreSQL, MongoDB, MySQL, REST & GraphQL APIs**.
Typos fixed

2020-10-01 16:37 UTC, alphaX86 commented on README.md
> +* **Works with existing, live databases**: Connect directly to any PostgreSQL, MySQL & MongoDB
As you've requested! :)

2020-10-02 06:20 UTC, Nikhil-Nandagopal approved these changes

2020-10-08 02:36 UTC, merged