fix: button variant table binding
appsmithorg/appsmith pull request #8712
Opened 2021-10-21 19:04 UTC by Tooluloope

## Description

Button variant binded with text widget does not populate on the table icon column 

Fixes #8529

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>
No changes to code coverage between the base branch and the head branch</details>

2021-11-16 05:37 UTC, riodeuno requested changes

2021-11-16 05:37 UTC, riodeuno commented on app/client/src/workers/validations.ts
> +  [ValidationTypes.TEXT_OR_ARRAY]: (
Please add unit tests for this validation.

2021-11-16 05:38 UTC, riodeuno commented
An ideal solution here would be to disallow multiple types of values for a property. If it is text or array , it can be only array with single or more values.

2021-11-29 10:29 UTC, Tooluloope commented
/ok-to-test sha=1468a96

2021-11-29 12:23 UTC, Tooluloope commented
/ok-to-test sha=8d243f1

2021-11-30 16:44 UTC, riodeuno submitted a review, later dismissed

2021-11-30 16:46 UTC, riodeuno commented
@aswathkk Please review this change. Adding you as a reviewer. Looks good from my end.

2021-11-30 17:27 UTC, aswathkk commented
@riodeuno I found some issues in the DP.
What I would suggest is to wait for #9396 to be merged so that we can use `ValidationTypes.TABLE_PROPERTY` to write a simple validation that is going to fix #8529

2021-12-09 08:35 UTC, Tooluloope commented
/ok-to-test sha=6a84110

2021-12-09 09:10 UTC, aswathkk approved these changes
LGTM

2021-12-09 09:50 UTC, YogeshJayaseelan commented
@Tooluloope Verified this fix and it is working as expected

2021-12-09 09:53 UTC, wealthz01 commented
Hello there ... pls can i know how to get started with this online chat or trading

2021-12-09 10:42 UTC, riodeuno approved these changes

2021-12-09 12:12 UTC, merged