feat: Checkbox group should have a select all option
appsmithorg/appsmith pull request #8744
Opened 2021-10-22 19:49 UTC by wmdev0808

## Description

Checkbox group should provide an option for user to add a select all option in the property itself

In a scenario there might be a large number of option to select in the checkbox group, so user should have an option to select all instead of selecting it one by one. A property can be implemented in the checkbox group itself which on set true can add a select all checkbox at the top of the checkbox group to select all checkboxes in the group

Fixes #7275 

## Type of change

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

## How Has This Been Tested?

- Test A
- Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>

    // Code coverage diff between base branch:release and head branch: feat/7275-checkboxgroup-add-select-all 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 55.14 **(0)** | 36.64 **(-0.01)** | 34.58 **(0.01)** | 55.67 **(0)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.71 **(-0.23)** | 40.83 **(-0.84)** | 36.21 **(0)** | 56.74 **(-0.25)**
 :sparkles: :new: | **app/client/src/widgets/CheckboxGroupWidget/constants.ts** | **100** | **100** | **100** | **100**
 :red_circle: | app/client/src/widgets/CheckboxGroupWidget/component/index.tsx | 29.03 **(4.03)** | 5.56 **(-6.94)** | 0 **(0)** | 36 **(2.67)**
 :red_circle: | app/client/src/widgets/CheckboxGroupWidget/widget/index.tsx | 51.35 **(-7.38)** | 26.92 **(-2.25)** | 38.1 **(-6.34)** | 52.17 **(-7.15)**
 :green_circle: | app/client/src/widgets/CheckboxWidget/component/index.tsx | 96.97 **(0.42)** | 67.74 **(3.74)** | 90.91 **(0.91)** | 96.15 **(0.32)**</details>

2021-10-25 11:00 UTC, somangshu requested changes
LGTM, I have tested the Deploy preview and it works well, Left a couple of comments here.
- When the space is less the select all option collides with the option underneath 
 ![Screenshot 2021-10-25 at 4 16 09 PM](https://user-images.githubusercontent.com/11089579/138683675-8f549c54-fe80-42cd-ba8a-a59bfacb53e5.png)
- ~~The options should go below disabled~~ 
 ![Screenshot 2021-10-25 at 4 26 26 PM](https://user-images.githubusercontent.com/11089579/138683681-b2e7ffe4-310f-4ee4-adb9-f4df507833b1.png)
- ~~The select all option and not selected checkbox color should be `grey-9`~~
- ~~The selected option colour should be `grey-10`~~
 

Documentation change will be required

2021-10-29 19:33 UTC, wmdev0808 commented
/ok-to-test sha=e3e5907

2021-10-29 19:35 UTC, wmdev0808 commented
https://github.com/appsmithorg/appsmith/actions/runs/1400349497

2021-11-02 06:17 UTC, somangshu submitted a review, later dismissed

2021-11-02 06:22 UTC, somangshu commented
@wmdev0808 The solution to first issue is not apt, The additional gap below the select option seem to be mis-aligned in the inline more 
![Screenshot 2021-11-02 at 11 49 20 AM](https://user-images.githubusercontent.com/11089579/139796277-1ba10ef1-0323-407b-ac78-b04596a88e74.png)

Also the cypress test have failed due to the relevant change you have made, Kindly check

2021-11-02 10:50 UTC, wmdev0808 commented
/ok-to-test sha=d9cfb4f

2021-11-02 10:52 UTC, wmdev0808 commented
https://github.com/appsmithorg/appsmith/actions/runs/1411916481

2021-11-10 09:13 UTC, somangshu commented
> * When the space is less the select all option collides with the option underneath
>   ![Screenshot 2021-10-25 at 4 16 09 PM](https://user-images.githubusercontent.com/11089579/138683675-8f549c54-fe80-42cd-ba8a-a59bfacb53e5.png)

@wmdev0808 the previous issue has resurfaced because of the change, Kindly check. 

My analysis of the problem.
- When inline is true, there is additional space underneath 
<img width="235" alt="Screenshot 2021-11-10 at 2 40 41 PM" src="https://user-images.githubusercontent.com/11089579/141084120-a10a3555-b02a-42af-90cf-ce67e15d0d0c.png">
- When inline is false, the space is gone because of the recent change and this way the text collides 
<img width="234" alt="Screenshot 2021-11-10 at 2 41 41 PM" src="https://user-images.githubusercontent.com/11089579/141084281-1a724b47-ea9b-4645-b078-0ecd1080cca7.png">
- The solution could be to persist the select all option in one line, Let it overflow.

2021-11-10 09:15 UTC, somangshu requested changes
As per the above comment

2021-11-10 09:32 UTC, wmdev0808 commented
/ok-to-test sha=8f5452d

2021-11-10 09:33 UTC, wmdev0808 commented
https://github.com/appsmithorg/appsmith/actions/runs/1443487133

2021-11-10 09:57 UTC, somangshu commented on app/client/src/widgets/CheckboxGroupWidget/widget/index.tsx
> +            helpText: "Controls whether select all control is shown",
@wmdev0808 can you make a small change here > `Controls whether select all option is shown`

2021-11-10 09:57 UTC, somangshu submitted a review, later dismissed
Change LGTM

2021-11-10 10:11 UTC, wmdev0808 commented
/ok-to-test sha=0faacd3

2021-11-10 10:12 UTC, somangshu approved these changes

2021-11-10 10:12 UTC, wmdev0808 commented
https://github.com/appsmithorg/appsmith/actions/runs/1443627099

2021-11-23 15:59 UTC, wmdev0808 commented
/ok-to-test sha=9a0f418

2021-12-20 13:17 UTC, wmdev0808 commented
/ok-to-test sha=1bcc716

2021-12-22 09:15 UTC, somangshu commented
@wmdev0808 please update this with the latest release! Check other PR too

2021-12-22 10:09 UTC, somangshu commented
@wmdev0808 the tests have passed, You can close this is you have the QA sign off

2021-12-22 10:10 UTC, somangshu approved these changes

2021-12-22 11:46 UTC, wmdev0808 commented
/ok-to-test sha=a7ef2ec

2022-01-04 20:34 UTC, wmdev0808 commented
/ok-to-test sha=e3eef86

2022-01-11 13:26 UTC, merged