fix: #8591 number input widget support space
appsmithorg/appsmith pull request #8817
Opened 2021-10-26 10:07 UTC by vibhandikyash

## Description

> Added space support in Phone Number 

Fixes #8591 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Tested locally.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/8591-number-input-widget-support-space 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 54.61 **(0.03)** | 36.47 **(0.02)** | 33.22 **(0.01)** | 55.14 **(0.04)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.04 **(-0.22)** | 40.42 **(-0.83)** | 34.48 **(0)** | 55.96 **(-0.26)**
 :red_circle: | app/client/src/widgets/InputWidget/component/ISDCodeDropdown.tsx | 53.33 **(-3.81)** | 18.18 **(-4.04)** | 22.22 **(-6.35)** | 51.72 **(-3.84)**
 :green_circle: | app/client/src/widgets/InputWidget/component/index.tsx | 62.69 **(3.91)** | 45.71 **(1.33)** | 64.29 **(2.39)** | 61.54 **(4.06)**
 :green_circle: | app/client/src/widgets/InputWidget/widget/index.tsx | 70.91 **(8.77)** | 50.63 **(8.96)** | 69.57 **(0)** | 73.33 **(9.04)**</details>

2021-11-03 06:52 UTC, ashit-rath requested changes

2021-11-03 06:52 UTC, ashit-rath commented on app/client/src/widgets/InputWidget/widget/index.tsx
> +            const phoneNumberRegex = new RegExp(/^(?:[0-9 ]+$)/);
Can we use the regex defined [here](https://github.com/appsmithorg/appsmith/pull/8817/files#diff-435db47a7e43e5306935a785171106216772e130ed50bd5470e5ab4a7e7b1425R11)?

2021-11-03 06:52 UTC, ashit-rath commented on app/client/src/widgets/InputWidget/component/index.tsx
> +          this.props.inputType !== InputTypes.PHONE_NUMBER
Shouldn't we be using TextInput instead of the NumericInput for the `PHONE_NUMBER` type as it is a string?

2021-11-03 06:52 UTC, ashit-rath commented
@vibhandikyash 
 As I hit backspace, the last digit does not get removed.
https://www.loom.com/share/1888671f53244e7cb7f2b4088eaf2131

2021-11-03 06:53 UTC, ashit-rath commented
Also, please resolve conflicts.

2021-11-12 07:02 UTC, vibhandikyash commented
/ok-to-test sha=526d1a7

2021-11-12 07:03 UTC, vibhandikyash commented
https://github.com/appsmithorg/appsmith/actions/runs/1452033040

2021-11-15 07:36 UTC, vibhandikyash commented
/ok-to-test sha=26862ec

2021-11-15 08:17 UTC, ashit-rath commented
Noticed a couple of tiny issues here
1. https://www.loom.com/share/b350586cc2f04b419a13a31d483a8f89
  When hovered over a line appears on the input's left and disappears.
2. In the disabled state there is a difference in the styling
In production -
<img width="539" alt="Screenshot 2021-11-15 at 1 45 03 PM" src="https://user-images.githubusercontent.com/88306433/141745832-688938e1-8a76-4949-9431-033d4a1f6ff4.png">

In this PR
<img width="452" alt="Screenshot 2021-11-15 at 1 46 10 PM" src="https://user-images.githubusercontent.com/88306433/141745979-b05c5430-e9a2-4a13-b63d-595e461bfce4.png">

Notice the borders and the country selector.

2021-11-15 08:18 UTC, ashit-rath requested changes

2021-11-15 11:47 UTC, vibhandikyash commented on app/client/src/widgets/InputWidget/widget/index.tsx
> +            const phoneNumberRegex = new RegExp(/^(?:[0-9 ]+$)/);
@ashit-rath, seems like on line 583 its an evaluation text so we can't use variable from this file.

2021-11-16 11:00 UTC, closed without merging