Fix/img widget
appsmithorg/appsmith pull request #882
Opened 2020-10-02 14:17 UTC by visibleajay

2020-10-03 09:04 UTC, hetunandu requested changes
Minor changes required

2020-10-03 09:04 UTC, hetunandu commented on app/client/test/__mocks__/fileMock.js
> +module.exports = {};
This should not be needed

2020-10-03 09:04 UTC, hetunandu commented on app/client/src/widgets/__tests__/ImageWidget.test.tsx
> +import React from "react";
We need to have this file next to ImageWidget instead of in the `__tests__` directory. Currently our CI is not picking up this test

2020-10-03 09:12 UTC, visibleajay commented on app/client/test/__mocks__/fileMock.js
> +module.exports = {};
Jest is thowing an error for PlayIcon`png` file when `fileMock.js` is absent

2020-10-03 09:18 UTC, visibleajay commented on app/client/src/widgets/__tests__/ImageWidget.test.tsx
> +import React from "react";
Done. Also, receiving `cypress` error for few specs (14 out of 52). Haven't made any changes to `cypress` and `errors` seems to be related to already present code.

2020-10-03 09:23 UTC, hetunandu commented on app/client/src/widgets/__tests__/ImageWidget.test.tsx
> +import React from "react";
Sometimes cypress does do that. Lets hope the rerun is fine🤞🏼

2020-10-03 09:59 UTC, hetunandu commented
@visibleajay Still not able to see your new test in our CI test run. Can you figure out what is going wrong?

https://github.com/appsmithorg/appsmith/pull/882/checks?check_run_id=1202445036

2020-10-03 10:47 UTC, visibleajay commented
@hetunandu CI seems to be ignoring all newly added test files irrespective of the extension (.ts/.tsx) or test case.

2020-10-05 08:10 UTC, visibleajay commented
> @hetunandu CI seems to be ignoring all newly added test files irrespective of the extension (.ts/.tsx) or test case.

Hey @hetunandu, Any hints on this?

2020-10-05 14:40 UTC, hetunandu commented
@visibleajay There seems to be an issue with our CI where it is not checking out the right code for testing. Because of this, we cannot verify these tests. I will have to hold merging of this branch till we fix that issue.

2020-10-05 14:45 UTC, visibleajay commented
Cool @hetunandu... I have pushed 2 sample test files to confirm this issue. Would like to remove only after the CI issue gets resolved.

2020-10-05 16:47 UTC, hetunandu commented
@visibleajay We might have a fix working. Can you push a dummy commit on your branch?

2020-10-05 16:55 UTC, hetunandu commented
Sorry i forgot to mention, you need to merge the latest release into your branch @visibleajay

2020-10-05 17:06 UTC, hetunandu commented
@visibleajay It Worked! 🎉 Thanks for helping us uncover this bug in our CI. You can remove the dummy test files now. Ill do a final review and then we can merge

2020-10-06 06:35 UTC, hetunandu approved these changes

2020-10-06 06:36 UTC, merged

2020-10-06 06:38 UTC, hetunandu commented
@visibleajay This was a really good contribution! Thanks a lot for your patience in this whole process. You rock 🙏

2020-10-06 06:41 UTC, visibleajay commented
@hetunandu Thank You for the opportunity to contribute. AppSmith Rocks :raised_hands:.