fix: The value is always empty object in AudioRecorder Widget
appsmithorg/appsmith pull request #8868
Opened 2021-10-27 20:51 UTC by wmdev0808

## Description
The evaluated value of value prop always shows an empty object whenever we record audio with the audio recorder widget.

Fixes #8855 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Test A
- Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/8855-audiorecorder-value-empty 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 54.56 **(-0.01)** | 36.43 **(-0.01)** | 33.17 **(0)** | 55.08 **(-0.01)**
 :red_circle: | app/client/src/widgets/AudioRecorderWidget/component/index.tsx | 13.98 **(0)** | 13.46 **(-0.13)** | 6.25 **(0)** | 16.18 **(0)**
 :red_circle: | app/client/src/widgets/AudioRecorderWidget/widget/index.tsx | 38.46 **(-6.54)** | 0 **(0)** | 62.5 **(0)** | 38 **(-6.74)**</details>

2021-11-03 05:12 UTC, SatishGandham requested changes

2021-11-03 05:12 UTC, SatishGandham commented on app/client/src/widgets/AudioRecorderWidget/widget/index.tsx
> +    if (blob) {
You already have a blob URL. Why are you creating it again?
You can use code form `createBlobUrl` directly here instead of making another blob url.

2021-11-03 05:12 UTC, SatishGandham commented on app/client/src/widgets/AudioRecorderWidget/widget/index.tsx
> +      this.props.updateWidgetMetaProperty("dataAsDataURL", undefined);
@somangshu Names `dataAsDataURL` and `dataAsRawBinary` doesn't feel right to me. Any suggestions?

2021-11-03 06:30 UTC, somangshu commented on app/client/src/widgets/AudioRecorderWidget/widget/index.tsx
> +      this.props.updateWidgetMetaProperty("dataAsDataURL", undefined);
@SatishGandham you are right, thanks for bringing this up. We could use:
- just `dataURL` : This is a very common term generically used
- `rawBinary` / `rawData` : Are the most commonly used 

Let me know what you think.

cc @Nikhil-Nandagopal

2021-11-08 09:26 UTC, somangshu commented
@wmdev0808 are the above comments resolved?

2021-11-08 09:28 UTC, wmdev0808 commented
> @wmdev0808 are the above comments resolved?

Not yet, I will make changes

2021-11-08 09:29 UTC, somangshu commented
Also @SatishGandham @wmdev0808 please see if we need tests here.

@YogeshJayaseelan this is a critical issue and should have bee tested by now, Please look into this.

2021-11-08 09:58 UTC, wmdev0808 commented
/ok-to-test sha=5a89c13

2021-11-09 11:16 UTC, vivekverma2312 commented
@wmdev0808 Tested on deploy preview, Now we are able to store the recording files to S3.

2021-11-09 12:26 UTC, SatishGandham requested changes

2021-11-09 12:26 UTC, SatishGandham commented on app/client/src/widgets/AudioRecorderWidget/constants.ts
> +  TEXT = "TEXT",
Audio is never going to be text.

2021-11-09 12:44 UTC, wmdev0808 commented
/ok-to-test sha=7d7d3ad

2021-11-09 12:51 UTC, wmdev0808 commented
https://github.com/appsmithorg/appsmith/actions/runs/1439521092

2021-11-10 07:20 UTC, SatishGandham approved these changes

2021-11-11 08:37 UTC, somangshu commented
@wmdev0808 this PR is failing the server build repeatedly, Let try running the CI after updating the branch with the latest release

2021-11-11 13:38 UTC, wmdev0808 commented
/ok-to-test sha=c0587e1

2021-11-11 13:39 UTC, wmdev0808 commented
https://github.com/appsmithorg/appsmith/actions/runs/1448997667

2021-11-11 14:46 UTC, merged