fix: implement getStructure method for S3 plugin
appsmithorg/appsmith pull request #8919
Opened 2021-10-29 08:57 UTC by sumitsum

## Description
- Add `getStructure` implementation for S3 to return a list of accessible buckets. 
- Add command templates for S3. 
  - List files
  - Read file
  - Create file
  - Delete file
- Remove `getDatasourceMetadata` implementation as `getStructure` method can be directly used now. 
- TBD: Some client side implementations / fixes are required before this code can be merged:
  - Currently the template is rendered correctly but the default value for `command` UQI attribute is not picked up by the client. 
  - Need to support picking up values from `ActionConfiguration` object in the `Template` object. 
  - Update client to use `getStructure` method call for S3 plugin instead of `getDatasourceMetadata`.

Fixes #8857 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- JUnit TC
- Manual

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-11-02 09:42 UTC, nidhi-nair commented on app/server/appsmith-plugins/amazons3Plugin/src/main/java/com/external/plugins/AmazonS3Plugin.java
> -                    case LIST_BUCKETS:
Why are we removing this @sumitsum

2021-11-11 05:55 UTC, nidhi-nair approved these changes

2021-11-24 06:26 UTC, nidhi-nair commented
Reopening because this was being worked on actively. @Irongade can you confirm whether the changes on your end are ready to be reviewed?

2021-11-25 06:51 UTC, sumitsum commented
Thanks @nidhi-nair . This is being worked upon actively. @Irongade had added some changes for this earlier. We need to do integration testing for this now.

2021-11-25 08:26 UTC, Irongade commented
> Reopening because this was being worked on actively. @Irongade can you confirm whether the changes on your end are ready to be reviewed?

Yes they are.

2021-11-30 09:25 UTC, nidhi-nair approved these changes

2021-12-03 09:54 UTC, ayushpahwa requested changes

2021-12-03 09:54 UTC, ayushpahwa commented on app/client/src/entities/Datasource/index.ts
> +  actionConfiguration?: Record<string, unknown>;
Use 'ActionConfig' as Type instead on this

2021-12-03 10:47 UTC, Irongade commented on app/client/src/entities/Datasource/index.ts
> +  actionConfiguration?: Record<string, unknown>;
Done.

2021-12-03 11:02 UTC, ayushpahwa requested changes

2021-12-03 11:02 UTC, ayushpahwa commented on app/client/src/pages/Editor/GeneratePage/components/GeneratePageForm/GeneratePageForm.tsx
> +    // fetchBucketList,
Remove this if it is not needed.

2021-12-03 11:08 UTC, Irongade commented on app/client/src/pages/Editor/GeneratePage/components/GeneratePageForm/GeneratePageForm.tsx
> +    // fetchBucketList,
Done.

2021-12-03 11:10 UTC, ayushpahwa approved these changes

2021-12-03 11:14 UTC, sumitsum commented
/ok-to-test sha=d540650

2021-12-03 11:16 UTC, nidhi-nair submitted a review, later dismissed

2021-12-06 15:51 UTC, sumitsum commented
/ok-to-test sha=ed04b20

2021-12-06 17:08 UTC, sumitsum commented
/ok-to-test sha=ed04b20

2021-12-08 11:08 UTC, sumitsum commented
/ok-to-test sha=ed04b20

2021-12-09 14:28 UTC, sumitsum commented
/ok-to-test sha=ed04b20

2021-12-21 15:15 UTC, sumitsum commented
/ok-to-test sha=905984b

2021-12-21 17:03 UTC, sumitsum commented
/ok-to-test sha=905984b

2021-12-24 07:37 UTC, sumitsum commented
/ok-to-test sha=6068ba0

2021-12-28 11:22 UTC, sumitsum commented
/ok-to-test sha=48a2b03

2021-12-28 21:23 UTC, sumitsum commented
/ok-to-test sha=48a2b03

2022-01-12 08:24 UTC, sumitsum commented
/ok-to-test sha=e6129fb

2022-01-13 06:03 UTC, nidhi-nair approved these changes

2022-01-13 06:03 UTC, merged