fix: null check in Table widget
appsmithorg/appsmith pull request #8979
Opened 2021-11-02 10:36 UTC by Tooluloope

## Description

> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change.

Fixes #8229

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-11-02 10:38 UTC, Tooluloope commented on app/client/src/utils/migrations/TableWidget.ts
> +            id = removeSpecialChars(value.id, 200);
@riodeuno Could you help look at this, I'm trying to bring the Column property one level up

2021-11-03 10:58 UTC, Tooluloope commented
/ok-to-test sha=5c2461b

2021-11-03 11:13 UTC, riodeuno requested changes

2021-11-03 11:13 UTC, riodeuno commented on app/client/src/utils/migrations/TableWidget.ts
> +        for (let [key, value] of primaryColumnEntries) {
Let's not manipulate the `key` and `value` in this iteration and use other variables for this.

2021-11-03 11:13 UTC, riodeuno commented on app/client/src/utils/migrations/TableWidget.ts
> +            const onlyKey = Object.keys(value)[0] as keyof ColumnProperties;
Here I believe we're assuming that there is only one key, can we verify this, before using the nested object. Also, we can do some basic checks. For example, id, type, etc should be available in the column properties, otherwise, even if we migrate it wouldn't work.

2021-11-08 10:54 UTC, Tooluloope commented on app/client/src/utils/migrations/TableWidget.ts
> +        for (let [key, value] of primaryColumnEntries) {
@riodeuno What do you mean here?
I think `value` is where the faulty object lies.

2021-11-08 10:58 UTC, riodeuno commented on app/client/src/utils/migrations/TableWidget.ts
> +        for (let [key, value] of primaryColumnEntries) {
@Tooluloope This was just a code comment from a readability standpoint. Since, we're in control of the whole migration, we can assign a different variable here. I just wanted to avoid the `//eslint-disable-next-line prefer-const`. Updating the `value` or `key` here, would make this function difficult to read and maintain.

2021-11-09 06:30 UTC, riodeuno approved these changes
@Tooluloope Looks good to me! Let's try to reproduce the issue, and make sure that this fixes it.

2021-11-09 07:00 UTC, Tooluloope commented
/ok-to-test sha=0388302

2021-11-09 08:24 UTC, vivekverma2312 commented
@Tooluloope I tried importing the application and it's not throwing error on deploy preview.

2021-11-10 11:50 UTC, Tooluloope commented
/ok-to-test sha=0388302

2021-11-10 16:18 UTC, Tooluloope commented
/ok-to-test sha=0388302

2021-11-12 09:33 UTC, merged