chore: Removes incorrect trigger paths from list widget via database migrations
appsmithorg/appsmith pull request #8989
Opened 2021-11-03 06:44 UTC by trishaanand

2021-11-05 10:24 UTC, sumitsum requested changes

2021-11-05 10:24 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog.java
> +        String widgetType = dsl.getAsString(FieldName.WIDGET_TYPE);
I encountered a `null` value for `wigetType` identifier when `dsl` is:
```
{
  "key": "dsl",
  "value": {
    "name": "MainContainer",
    ...... 
    "type": ....
  }
}
```

2021-11-05 10:24 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog.java
> +    }
QQ: This migration change seems to remove the trigger paths which are no longer valid. Is it because the widget has changed ? If so, then what would happen to the JS code written in the older trigger paths ?

2021-11-09 06:55 UTC, trishaanand commented on app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog.java
> +        Boolean updated = dslUpdateDto.getUpdated();
Quoting from line 3802 :
```
            if (dslUpdateDto.getUpdated().equals(TRUE)) {
                mongockTemplate.save(page);
            }

2021-11-09 06:56 UTC, trishaanand commented on app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog.java
> +        String widgetType = dsl.getAsString(FieldName.WIDGET_TYPE);
Is that a valid DSL?  And in case of invalid DSL, and there is no widget type, the check `if (widgetType.equals("LIST_WIDGET"))` ensures that we dont do anything for such a scenario/

2021-11-09 06:58 UTC, trishaanand commented on app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog.java
> +    }
We are removing trigger paths which either dont exist or no longer have JS code written in it. This is because of a client bug where they werent computing the dynamic trigger paths correctly. The client has fixed the bug for future edits. This ensures that the existing pages have correct paths without requiring any new edits.

2021-11-09 10:07 UTC, sumitsum approved these changes

2021-11-09 10:32 UTC, merged