Solving #662 , Radio Button Empty Value problem
appsmithorg/appsmith pull request #900
Opened 2020-10-03 09:37 UTC by Jain-Sanchit

Previously there was no check for empty value of radio button . It was being processes as there was no check for empty string .
I have applied a check condition for empty string now . If string would be empty , it will return false.
Thus this solves issue #662 .

2020-10-03 09:56 UTC, Jain-Sanchit commented
@hetunandu Sir , Please have a look and let me know if something is needed to be changed.

2020-10-03 10:15 UTC, hetunandu requested changes

2020-10-03 10:15 UTC, hetunandu commented on app/client/src/utils/Validators.ts
>          return _.isString(datum.label) && _.isString(datum.value);
This is correct but the condition can be more readable as so

```suggestion
        return (
            _.isString(datum.label) 
            && _.isString(datum.value) 
            && !_.isEmpty(datum.label) 
            && !_.isEmpty(datum.value)
        );
```

2020-10-03 10:34 UTC, Jain-Sanchit commented
@hetunandu  Changes have been made Sir . I hope it's okay now.

2020-10-03 10:39 UTC, hetunandu commented
Awesome! This works. Can you add a cypress test to assert this functionality? The input should have a red border now whenever any option is an empty string.

2020-10-03 10:41 UTC, Jain-Sanchit commented
@hetunandu  I have to give it a try , I will try to implement this .

2020-10-03 12:35 UTC, Jain-Sanchit commented
Now after updating if the value is empty , the blocks go red and shows error .
I think this was needed , please review @hetunandu 
![radioError](https://user-images.githubusercontent.com/31254015/94991793-f4830480-05a2-11eb-9e4e-e079d03aac85.png)

2020-10-05 05:17 UTC, hetunandu approved these changes
LGTM

2020-10-05 05:18 UTC, merged