fix: Add support for content type in create file for S3 plugin
appsmithorg/appsmith pull request #9021
Opened 2021-11-06 13:30 UTC by nidhi-nair

Fixes #7308 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- JUnit test case
- Manually tested

2021-11-08 08:46 UTC, sumitsum requested changes

2021-11-08 08:46 UTC, sumitsum commented on app/server/appsmith-plugins/amazons3Plugin/src/main/java/com/external/plugins/AmazonS3Plugin.java
> +            MultipartFormDataDTO multipartFormDataDTO = null;
I think there is one corner case that is not handled here that we have been supporting so far i.e. when user wants to upload a file - not via `filepicker` but by writing the content in the body. In this case the body content will not map to a `MultipartFormDataDTO` object but will remain as a normal string. Whether `filepicker` is used or not should be decided by the boolean param `usingFilePicker`.

2021-11-08 08:46 UTC, sumitsum commented on app/server/appsmith-plugins/amazons3Plugin/src/test/java/com/external/plugins/AmazonS3PluginTest.java
> +        String dummyBody = "{\"data\": \"\"}";
Could be related to the first comment.

2021-11-08 08:46 UTC, sumitsum commented on app/server/appsmith-plugins/amazons3Plugin/src/test/java/com/external/plugins/AmazonS3PluginTest.java
> +        String dummyBody = "{\"data\": \"\"}";
Could be related to the first comment.

2021-11-08 08:46 UTC, sumitsum commented on app/server/appsmith-plugins/amazons3Plugin/src/test/java/com/external/plugins/AmazonS3PluginTest.java
> +        setValueSafelyInFormData(configMap, CREATE_EXPIRY, "100000");
I think we should also set the `using file picker` attribute to `yes` here.

2021-11-08 08:46 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog.java
> +    @ChangeSet(order = "095", id = "update-s3-action-configuration-for-type", author = "")
Please add a comment explaining why this migration is done and what it does.

2021-11-08 08:46 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog.java
> +    public void updateS3ActionConfigurationForType(MongockTemplate mongockTemplate) {
Can you please update the method name as it is a bit confusing ?

2021-11-08 08:46 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog.java
> +        // Find all S3 actions
Can you please move this comment to the next line ? - since the current code fetchs S3 plugin object.

2021-11-08 08:46 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog.java
> +            final String newUnpublishedBody = "{\n\t\"data\": \"" + oldUnpublishedBody + "\"\n}";
Should we check for `using filepicker` attribute value as well ? - please check the first comment for context.

2021-11-08 08:46 UTC, sumitsum commented on app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog.java
> +            if (unpublishedAction == null || unpublishedAction.getActionConfiguration() == null) {
not sure about this - should we check for `publishedAction` even if the `unpublishedAction` does not exist ?

2021-11-08 09:05 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog.java
> +            if (unpublishedAction == null || unpublishedAction.getActionConfiguration() == null) {
Published actions would never exist if unpublished actions do not. It is mandated by our creation and publish flow.

2021-11-08 09:13 UTC, nidhi-nair commented on app/server/appsmith-plugins/amazons3Plugin/src/main/java/com/external/plugins/AmazonS3Plugin.java
> +            MultipartFormDataDTO multipartFormDataDTO = null;
@sumitsum I've maintained the same type so that users are made to manually create the filepicker-like objet even when they don't use the file picker. This makes sure that they are using the content type functionality. And even if they don't, the minimum criteria is for their data to be in a prop called data. It makes for similarity in behaviour.

2021-11-08 09:16 UTC, nidhi-nair commented on app/server/appsmith-plugins/amazons3Plugin/src/test/java/com/external/plugins/AmazonS3PluginTest.java
> +        setValueSafelyInFormData(configMap, CREATE_EXPIRY, "100000");
@sumitsum Sorry, but I did not understand this

2021-11-09 09:49 UTC, nidhi-nair commented
/ok-to-test sha=f755399

2021-11-09 10:01 UTC, sumitsum submitted a review, later dismissed

2021-11-09 10:05 UTC, sumitsum commented
Tracking the required documentation changes here: https://github.com/appsmithorg/appsmith/issues/9056

2021-11-09 10:37 UTC, nidhi-nair commented
/ok-to-test sha=47f42f5

2021-11-09 10:38 UTC, sumitsum approved these changes

2021-11-09 11:49 UTC, nidhi-nair commented
/ok-to-test sha=47f42f5

2021-11-09 12:20 UTC, nidhi-nair commented
https://github.com/appsmithorg/appsmith/actions/runs/1439308229

2021-11-10 02:14 UTC, merged