fix: Unable to group widgets
appsmithorg/appsmith pull request #9043
Opened 2021-11-08 16:37 UTC by aswathkk

## Description

While working on #8954, I didn't realise `pasteWidgetSaga` is being used for widget grouping also. That caused this issue.
The issue is fixed and a test is added to avoid regression.

Fixes #9032

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Open editor on an incognito window. Make sure you didn't copied any widget.
Try grouping a couple of widgets

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-11-08 17:02 UTC, aswathkk commented
test run: https://github.com/appsmithorg/appsmith/actions/runs/1435824246

2021-11-09 05:40 UTC, vivekverma2312 commented
@aswathkk Tested the DP and it's working fine now.

2021-11-09 05:55 UTC, aswathkk commented
/ok-to-test sha=ae97a22

2021-11-09 05:57 UTC, aswathkk commented
https://github.com/appsmithorg/appsmith/actions/runs/1438152875

2021-11-09 06:41 UTC, aswathkk commented
/ok-to-test sha=ae97a22

2021-11-09 06:42 UTC, aswathkk commented
https://github.com/appsmithorg/appsmith/actions/runs/1438268907

2021-11-09 07:38 UTC, marks0351 requested changes

2021-11-09 07:38 UTC, marks0351 commented on app/client/src/sagas/WidgetOperationSagas.tsx
> -  if (!Array.isArray(copiedWidgetGroups)) return;
this code was to avoid using old copied widgets which were an array of objects, cud you add the new condition with an OR and retain the older condition as well.

2021-11-09 07:38 UTC, marks0351 commented on app/client/src/sagas/WidgetOperationSagas.tsx
> -  if (!Array.isArray(copiedWidgetGroups)) return;
old as in old way of implementation...used be an array and now its an object.

2021-11-09 08:07 UTC, aswathkk commented
/ok-to-test sha=2cf5f29

2021-11-09 08:08 UTC, aswathkk commented
test run: https://github.com/appsmithorg/appsmith/actions/runs/1438509334

2021-11-09 09:41 UTC, marks0351 approved these changes

2021-11-09 09:42 UTC, merged