Action undo redo
appsmithorg/appsmith pull request #9045
Opened 2021-11-09 07:35 UTC by arunvjn

## Description
Extends undo/redo feature across all pages in the application.

Fixes 

## Type of change
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
-Manual

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-11-19 10:00 UTC, Parthvi12 commented
Bugs:
- [ ] Host/port field duplicates on revisiting the database form page for Postgres, MongoDb,MySQL, Elastic Search, Redis, MsSQL, RedShift and ArangoDB.
- [ ] In database forms , when non focused undo/redo is performed, on revisiting the page changes are not reflected.
- [ ] For Use Prepared Statement Switch in query editor, if on settings tab , the tab switches from settings to query tab on undo/redo.
- [ ] Undo/redo doesn't work for curl import.
- [ ] For settings tab of API pane, API timeout doesn't have undo/redo.
- [ ] Dropdown undo/redo works only when not in focus.

2021-11-23 05:42 UTC, arunvjn commented
https://docs.google.com/spreadsheets/d/18Bm1J-sefTWvAYMtcm7KUyFhG2ojao6rH2uOoI_apSc/edit#gid=86430196
Test plan for undo/redo

2021-11-25 07:20 UTC, rahulramesha requested changes
The code for the most part looks good to me and seems to be very well written. I would still request to get another review as i am not familiar with the actions and query page code changes.

2021-11-25 07:20 UTC, rahulramesha commented on app/client/src/entities/Replay/ReplayEntity/ReplayEditor.ts
> +  public getChanges(diff: Diff<T, T>, isUndo: boolean): ReplayEditorUpdate<T> {
Minor NIT: It would be great if you could add comments for the methods

2021-11-25 07:20 UTC, rahulramesha commented on app/client/src/sagas/EvaluationsSaga.ts
> +  yield delay(REPLAY_DELAY);
what was the logic behind the delay?

2021-11-25 07:20 UTC, rahulramesha commented on app/client/src/sagas/ReplaySaga.ts
> +  yield delay(100);
same with delay here

2021-11-25 07:20 UTC, rahulramesha commented on app/client/src/utils/helpers.tsx
> +      if (el) flashElement(el, flashTimeout, flashClass);
The `flash` class doesn't seem to change any color.

2021-11-25 08:02 UTC, arunvjn commented on app/client/src/utils/helpers.tsx
> +      if (el) flashElement(el, flashTimeout, flashClass);
You can find the css for "flash" in portals.ts

2021-11-25 08:08 UTC, rahulramesha commented on app/client/src/utils/helpers.tsx
> +      if (el) flashElement(el, flashTimeout, flashClass);
yes, This code was being used to flash, propertyPane changes or when widgets are added back to the canvas with redo. That does not seem to be work now.

2021-11-25 08:10 UTC, arunvjn commented on app/client/src/sagas/EvaluationsSaga.ts
> +  yield delay(REPLAY_DELAY);
The delay is prevent updates on every keystroke. There are components with built in delays like codeeditor but for rest of the components like Input box, select etc, we use this delay to batch updates.

2021-11-25 08:12 UTC, arunvjn commented on app/client/src/sagas/ReplaySaga.ts
> +  yield delay(100);
The delay here to wait for sometime before applying the updates. Any undo/redo operation which needs tab switching or accordion expand/close would require this.

2021-11-25 08:25 UTC, arunvjn commented on app/client/src/utils/helpers.tsx
> +      if (el) flashElement(el, flashTimeout, flashClass);
Oh damn! Will fix this

2021-11-25 14:55 UTC, rahulramesha commented on app/client/src/sagas/EvaluationsSaga.ts
> +  yield delay(REPLAY_DELAY);
Nice, didn't realize we can debounce like this. Alternatively, you can try this as well next time, https://redux-saga.js.org/docs/api/#debouncems-pattern-saga-args

2021-11-25 15:00 UTC, arunvjn commented on app/client/src/sagas/EvaluationsSaga.ts
> +  yield delay(REPLAY_DELAY);
Neat. Delay effect is combined with takeLatest effect (updateReplayEnitiySaga) to achieve debounce here.

2021-11-30 05:04 UTC, akash-codemonk requested changes

2021-11-30 05:04 UTC, akash-codemonk commented on app/client/src/components/ads/ColorPickerComponent.tsx
> +        className="ur--has-border"
Can we make this class a constant?

2021-11-30 05:12 UTC, akash-codemonk requested changes

2021-11-30 05:12 UTC, akash-codemonk commented on app/client/src/actions/apiPaneActions.ts
> +  action?: any;
Can we add a type here?

2021-11-30 05:12 UTC, akash-codemonk commented on app/client/src/actions/queryPaneActions.ts
> +  action?: any,
same

2021-11-30 05:12 UTC, akash-codemonk commented on app/client/src/entities/Replay/ReplayEntity/ReplayCanvas.ts
> +  public processDiff(diff: DSLDiff, replay: any, isUndo: boolean) {
not sure whether we know the type of `replay` here

2021-11-30 05:12 UTC, akash-codemonk commented on app/client/src/entities/Replay/replayUtils.ts
> +export function getPathsFromDiff(diffs: any) {
is `diffs` going to be an array of some type?

2021-11-30 05:12 UTC, akash-codemonk commented on app/client/src/sagas/ReplaySaga.ts
> +  replayEntity: any,
Not sure it looks like we know the type here as we seem to access the pluginId from `replayEntity` below.

2021-11-30 05:24 UTC, akash-codemonk reviewed
Just a question is there a way to reset the undo/redo history programmatically?

2021-11-30 06:00 UTC, arunvjn commented on app/client/src/entities/Replay/ReplayEntity/ReplayCanvas.ts
> +  public processDiff(diff: DSLDiff, replay: any, isUndo: boolean) {
Replay is an empty object initially that we populate with meta data to fulfill post processing tasks like highlighting, switching tabs etc.

2021-11-30 06:10 UTC, arunvjn commented on app/client/src/sagas/ReplaySaga.ts
> +  replayEntity: any,
Added type

2021-11-30 06:10 UTC, arunvjn commented on app/client/src/entities/Replay/replayUtils.ts
> +export function getPathsFromDiff(diffs: any) {
Added type

2021-11-30 06:10 UTC, arunvjn commented on app/client/src/actions/queryPaneActions.ts
> +  action?: any,
Added type

2021-11-30 06:10 UTC, arunvjn commented on app/client/src/actions/apiPaneActions.ts
> +  action?: any;
Added type

2021-11-30 06:15 UTC, arunvjn commented
> Just a question is there a way to reset the undo/redo history programmatically?

We don't have a class method to reset change history, but we can easily do so by resetting the yjs diff map we use in our class instances

2021-11-30 07:36 UTC, arunvjn commented on app/client/src/components/ads/ColorPickerComponent.tsx
> +        className="ur--has-border"
Done

2021-11-30 07:38 UTC, akash-codemonk submitted a review, later dismissed

2021-11-30 08:19 UTC, rishabhsaxena reviewed
Hey @arunvjn have put a few queries/comments. Apart from those LGTM!
Though I feel it would be great to have someone from the BE Coder's pod to have a look as well

2021-11-30 08:19 UTC, rishabhsaxena commented on app/client/src/sagas/ReplaySaga.ts
> +  const { modifiedProperty } = updates[updates.length - 1] || {};
QQ: Are there any exceptions to having a single diff in the updates array?

2021-11-30 08:19 UTC, rishabhsaxena commented on app/client/src/sagas/ReplaySaga.ts
> +  yield put(updateAction({ id: replayEntity.id, action: replayEntity }));
It seemed we listen to redux form events to track changes, so was wondering if just re-initing the form values would  work?

2021-11-30 08:19 UTC, rishabhsaxena commented on app/client/src/sagas/ReplaySaga.ts
> +function* getEditorFieldConfig(replayEntity: Action, modifiedProperty: string) {
Refactor: I was wondering instead of deriving the values from the `modifiedProperty`, if we could send some metadata along with the diff objects. So we could declaratively send these values. But yeah this could be a slightly larger change

2021-11-30 08:19 UTC, rishabhsaxena commented on app/client/src/sagas/ReplaySaga.ts
> +  yield put(changeDatasource({ datasource: replayEntity, isReplay: true }));
QQ: Should we instead just re-init the forms instead of re-using the `changeEntity` methods?

2021-11-30 20:08 UTC, arunvjn commented on app/client/src/utils/helpers.tsx
> +}
FIxed

2021-12-01 03:03 UTC, arunvjn commented on app/client/src/selectors/entitiesSelector.ts
> +    type?: string;
Remove this method since it is not being used

2021-12-01 03:06 UTC, arunvjn commented on app/client/src/sagas/ReplaySaga.ts
> +  const { modifiedProperty } = updates[updates.length - 1] || {};
I don't understand. Can you elaborate ?

2021-12-01 03:08 UTC, arunvjn commented on app/client/src/sagas/ReplaySaga.ts
> +  yield put(updateAction({ id: replayEntity.id, action: replayEntity }));
We trigger updateAction only on form change, array_push and array_remove events. Reinitializing will dispatch a form init event which doesn't trigger the save call.

2021-12-01 03:47 UTC, arunvjn commented on app/client/src/sagas/ReplaySaga.ts
> +  yield put(changeDatasource({ datasource: replayEntity, isReplay: true }));
I have made some modifications to implement this.

2021-12-01 03:55 UTC, arunvjn commented on app/client/src/sagas/ReplaySaga.ts
> +function* getEditorFieldConfig(replayEntity: Action, modifiedProperty: string) {
This is a large refactor and I am not sure if we can work this out for all cases.We could persist current tab info in redux state and update the replay object with it but storing the accordion state is not possible without a lookup.

2021-12-01 03:56 UTC, arunvjn commented on app/client/src/sagas/DatasourcesSagas.ts
> +  }
I have made some refactors, we will not be using changeEntity to reset forms anymore

2021-12-01 04:58 UTC, arunvjn commented on app/client/src/sagas/DatasourcesSagas.ts
> +    takeEvery(ReduxFormActionTypes.ARRAY_REMOVE, formValueChangeSaga),
We generate draft versions that persists changes to datasource forms since we do not have autosave there.
Draft isn't updated on array remove and push.
Removed this code for now since it is unrelated.

2021-12-01 12:50 UTC, arunvjn commented on app/client/src/sagas/SaaSPaneSagas.ts
> +  yield put(updateReplayEntity(values.id, values, ENTITY_TYPE.ACTION));
There are times when the initial form values are empty inside componentDidMount. I have seen this inside db query editor pages. Hence doing this inside saga

2021-12-01 12:55 UTC, arunvjn commented on app/client/src/workers/evaluation.worker.ts
>        case EVAL_WORKER_ACTIONS.UNDO: {
I was wondering the same but according to @rahulramesha , replay operations on canvas could be expensive and blocking at times if put on the main thread. Added the replay object for editors here to maintain a single place.

2021-12-02 06:16 UTC, arunvjn commented on app/client/src/sagas/DatasourcesSagas.ts
> +  if (datasource.hasOwnProperty("datasourceId") && isReplay) {
Removed this. We no longer use changeEntity to reset forms

2021-12-02 06:20 UTC, arunvjn commented on app/client/src/sagas/SaaSPaneSagas.ts
> +  yield put(updateReplayEntity(values.id, values, ENTITY_TYPE.ACTION));
There are evaluations associated with determining what fields need to be show. We use the following steps to render form today.
History.push to change the URL followed changeEntitySaga in componentDidMount which takes care of the form initialization.
So form values are empty in componentDidMount in queryEditor page.
Some place where this works in RestApiDatasourceForm since we set initial values in mapStateToProps

2021-12-02 06:20 UTC, arunvjn commented on app/client/src/components/formControls/KeyValueArrayControl.tsx
> +      }
Removed this code since we no longer need it

2021-12-02 06:21 UTC, arunvjn commented on app/client/src/actions/pluginActionActions.ts
> +  skipSave?: boolean;
Added comment for skipSave

2021-12-02 06:23 UTC, arunvjn commented on app/client/src/sagas/ReplaySaga.ts
> +  yield put(updateAction({ id: replayEntity.id, action: replayEntity }));
Pushed refactors to reinit form using initialize API. We would still need this explicit save call though

2021-12-02 08:52 UTC, albinAppsmith submitted a review, later dismissed
Approving for test

2021-12-02 08:53 UTC, arunvjn commented
/ok-to-test sha=2aacd05

2021-12-03 05:20 UTC, arunvjn commented
/ok-to-test sha=eac6c56

2021-12-03 08:39 UTC, arunvjn commented
/ok-to-test sha=ef46b71

2021-12-03 10:07 UTC, ayushpahwa requested changes

2021-12-03 10:07 UTC, ayushpahwa commented on app/client/src/actions/apiPaneActions.ts
> +  action?: any;
I can't see the type for action here. `Action` is the type that can be used here. Please check file `/entities/Action`

2021-12-03 10:15 UTC, albinAppsmith approved these changes

2021-12-03 10:20 UTC, arunvjn commented
/ok-to-test sha=9c2a3cf

2021-12-03 15:51 UTC, albinAppsmith submitted a review, later dismissed

2021-12-03 15:53 UTC, arunvjn commented
/ok-to-test sha=c244fd8

2021-12-07 03:48 UTC, arunvjn commented
/ok-to-test sha=397d533

2021-12-07 08:13 UTC, albinAppsmith approved these changes

2021-12-07 08:16 UTC, arunvjn commented
/ok-to-test sha=6393a82

2021-12-07 09:45 UTC, merged