fix(forms): don't allow to use only spaces in names
appsmithorg/appsmith pull request #913
Opened 2020-10-04 00:29 UTC by daniloff200

fixes https://github.com/appsmithorg/appsmith/issues/807

also, can be a fix for https://github.com/appsmithorg/appsmith/issues/621

2020-10-04 06:07 UTC, jyash97 commented on app/client/src/pages/organization/CreateOrganizationForm.tsx
> +  const onlySpaces = value => (!value.trim().length)
Hey @daniloff200  

Is this code not throwing error for you? As `value` will be `undefined` initially which should throw an error.

2020-10-04 06:07 UTC, jyash97 commented on app/client/src/pages/organization/CreateOrganizationForm.tsx
> +        disabled={invalid}
There is no prop called `disabled` defined in `FormFooter` hence TypeScript will break the build, you can make use of `canSubmit` prop instead.
```suggestion
        canSubmit={!invalid}
```

2020-10-04 21:11 UTC, daniloff200 commented
I need some help with that
Now, while typing a space,  I've got a `Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.`  and can't fix it correctly.

Something wrong in my validation function

2020-10-05 06:58 UTC, hetunandu requested changes

2020-10-05 06:58 UTC, hetunandu commented on app/client/src/pages/organization/CreateOrganizationForm.tsx
> +  const onlySpaces = useCallback(
You are getting into a render loop because of useCallback. When you don't pass the second arg of dependencies inside the useCallback, it will cause it to keep rendering. More so, using this hook is not needed since simple inline functions are pretty cheap and replacing them with hooks is not needed.

Please create this function inside this file `app/client/src/utils/formhelpers.ts` and rename this function to `noSpaces`.

2020-10-05 15:14 UTC, daniloff200 commented on app/client/src/pages/organization/CreateOrganizationForm.tsx
> +  const onlySpaces = useCallback(
Thanks for help, @hetunandu 
Now, that error is fixed and functionality works as expected

2020-10-06 06:03 UTC, hetunandu commented
Hey @daniloff200 we had an issue with our CI runs which did not run the tests properly. Can you rebase/merge the latest release branch into your branch to fix this?

2020-10-06 20:21 UTC, daniloff200 commented
@hetunandu  done

2020-10-07 06:43 UTC, hetunandu approved these changes

2020-10-07 06:44 UTC, merged

2020-10-07 06:46 UTC, hetunandu commented
This was a good PR @daniloff200 ! 🙏 Thanks for your patience and promptness with this process. Looking forward to seeing more contributions from you in the coming days. Keep rocking 🤘🏻

2020-10-07 11:20 UTC, jyash97 commented on app/client/src/utils/formhelpers.ts
>  export const isEmptyString = (value: string) => {
Hey @daniloff200 @hetunandu sorry to add noise in the PR, but I have few questions -

What is the difference between `noSpaces` and `isEmptyString` ?

Plus in `isEmptyString` the last condition is redundant IMO.