feat: Trigger framework with default implementation for entity selector for UQI
appsmithorg/appsmith pull request #9142
Opened 2021-11-12 13:33 UTC by trishaanand

2021-11-19 12:05 UTC, nidhi-nair requested changes

2021-11-19 12:05 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/DatasourceStructureSolution.java
> +    private Mono<Set<String>> entitySelectorTriggerSolution(Datasource datasource, TriggerRequestDTO request) {
Can we add tests for this?

2021-11-19 12:05 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/DatasourceStructureSolution.java
> +        Mono<TriggerResultDTO> defaultResultMono = datasourceMono
Is there any particular reason we are using a method here instead of the default implementation in the executor?

2021-11-22 09:21 UTC, trishaanand commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/DatasourceStructureSolution.java
> +        Mono<Datasource> datasourceMono = datasourceService.findById(datasourceId, READ_DATASOURCES)
Execute is for view mode only. Should I then change this to MANAGE_DATASOURCES permission since this is used during edit mode? Or keep it as READ_DATASOURCES for future where developers can read the datasource but not edit them but still create queries on top of it?

2021-11-22 09:22 UTC, trishaanand commented on app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/DatasourceController.java
> +                                                       @RequestParam MultiValueMap<String, Object> params) {
I had a DTO when I was making a POST call. But I changed this to GET since trigger functionality is being used for reading data and request body is not the recommended part of GET function call.

2021-11-22 09:22 UTC, trishaanand commented on app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/DatasourceController.java
> +    @GetMapping("/{datasourceId}/trigger")
Execute could be making changes to the user's data and hence it was kept as POST call. The idea of trigger is to fetch data and hence I kept it as GET mapping. Let me know if you disagree.

2021-11-22 09:23 UTC, trishaanand commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/DatasourceStructureSolution.java
> +    private Mono<Set<String>> entitySelectorTriggerSolution(Datasource datasource, TriggerRequestDTO request) {
Added post review. Please check.

2021-11-22 09:23 UTC, trishaanand commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/DatasourceStructureSolution.java
> +        Mono<TriggerResultDTO> defaultResultMono = datasourceMono
This is because I am using the datasource structure here and there is no default implementation for the same.

2021-11-23 01:42 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/DatasourceStructureSolution.java
> +        Mono<Datasource> datasourceMono = datasourceService.findById(datasourceId, READ_DATASOURCES)
Yes this makes sense.

2021-11-23 01:46 UTC, nidhi-nair commented on app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/DatasourceController.java
> +                                                       @RequestParam MultiValueMap<String, Object> params) {
What scenarios do we expect execute to be updating data for? I can think of authentication which applies for both scenarios, which would imply we'd need a POST for both 😬

2021-11-24 07:29 UTC, trishaanand commented
/ok-to-test sha=e9c801e

2021-11-24 07:30 UTC, nidhi-nair approved these changes
Need a future refactor for converting to POST and to create types that have behaviour for each client display type.

2021-11-25 07:05 UTC, merged