fix: PageLoad - action.data implicitly depends on action.actionConfiguration. Added this relationship to dag
appsmithorg/appsmith pull request #9178
Opened 2021-11-16 09:43 UTC by trishaanand

2021-11-17 08:43 UTC, sumitsum submitted a review, later dismissed

2021-11-18 10:16 UTC, trishaanand commented
/ok-to-test sha=1200125

2021-11-19 08:36 UTC, trishaanand commented
/ok-to-test sha=af3f199

2021-11-19 16:02 UTC, trishaanand commented
/ok-to-test sha=92d83b7

2021-11-22 09:15 UTC, trishaanand commented
/ok-to-test sha=92d83b7

2021-12-06 08:12 UTC, trishaanand commented
/ok-to-test sha=d87bcdb

2021-12-06 12:09 UTC, trishaanand commented
/ok-to-test sha=d87bcdb

2021-12-06 14:19 UTC, nidhi-nair commented on app/server/appsmith-server/src/test/java/com/appsmith/server/services/ActionServiceTest.java
> +                    // TODO: This is an incorrect expectation, it should be 8 actions in the first set
This doesn't seem valid

2021-12-06 14:22 UTC, nidhi-nair commented on app/server/appsmith-server/src/test/java/com/appsmith/server/services/LayoutServiceTest.java
> +                            "aTableAction",
I know we've been through this 100 times, but do you think there's a scenario where Api1 gets pushed here to the second set because of that logical gap, and an Api2 from another dependency chain also ends up in the second set. The result of this being that the chronology as the user's server expects it to be is affected and breaks something that works today?

2021-12-06 14:23 UTC, nidhi-nair requested changes
Just a few comments related changes and a big one 😛

2021-12-09 08:01 UTC, trishaanand commented on app/server/appsmith-server/src/test/java/com/appsmith/server/services/LayoutServiceTest.java
> +                            "aTableAction",
Because of the addition of actionConfiguration -> data relationship, only a single level would exist for action.data and hence the above scenario would not exist. But I have added a comment in the code where this gets handled.

2021-12-09 08:02 UTC, trishaanand commented on app/server/appsmith-server/src/test/java/com/appsmith/server/services/LayoutServiceTest.java
> +                            "hiddenAction4"
Added comment in the code.

2021-12-09 08:04 UTC, trishaanand commented
/ok-to-test sha=813683f

2021-12-09 12:15 UTC, nidhi-nair approved these changes

2021-12-09 12:16 UTC, trishaanand commented
/ok-to-test sha=813683f

2021-12-09 13:45 UTC, trishaanand commented
/ok-to-test sha=813683f

2021-12-09 14:34 UTC, merged