fix: long dropdown popup truncates items
appsmithorg/appsmith pull request #9187
Opened 2021-11-16 18:27 UTC by aswathkk

> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.

## Description

> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change.

Fixes #8008 

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-11-17 18:49 UTC, aswathkk commented
/ok-to-test sha=2db593a

2021-11-18 04:38 UTC, aswathkk commented
/ok-to-test sha=aa0c338

2021-11-18 06:35 UTC, somangshu reviewed
I find the change alright. I have two concerns though:
1. With the docked property pane would this still be required @jsartisan 
2. This is an ADS component and may have a cascading effect. @marks0351 would you be able to confirm

2021-11-18 06:47 UTC, aswathkk commented
@somangshu I also had the same concerns that you had.
1. I checked the DP for docked property pane and found that this is still required
2. I checked other places where `TreeDropdown` is used and found that this change is not affecting anywhere else

@marks0351 @jsartisan Let me know if I'm wrong.

2021-11-22 05:14 UTC, marks0351 commented
@aswathkk can u pls have a work with @Tooluloope he was working on pop up fixes #7499 , not sure if he has catered to this issue.

2021-11-22 11:57 UTC, Tooluloope commented
> @aswathkk can u pls have a word with @Tooluloope he was working on pop up fixes #7499 , not sure if he has catered to this issue.

@marks0351 The other PR was for widget popup/dropdown, this PR is tailored towards the PropertyPane dropdown

2021-11-22 11:58 UTC, Tooluloope requested changes

2021-11-22 11:58 UTC, Tooluloope commented on app/client/src/components/ads/TreeDropdown.tsx
> +  max-height: calc(100vh - 64px);
@aswathkk whats the 64px for?
Could you leave a comment, and writing test would be ideal as well

2021-11-23 15:06 UTC, aswathkk commented on app/client/src/components/ads/TreeDropdown.tsx
> +  max-height: calc(100vh - 64px);
@Tooluloope It should've been 68px instead which is the total height of top bar and bottom bar.
I will update it and make it more readable.

2021-11-29 05:38 UTC, Tooluloope submitted a review, later dismissed

2021-11-29 05:38 UTC, Tooluloope commented on app/client/src/components/ads/TreeDropdown.tsx
> +  );
```suggestion
 max-height: ${(props) =>
    `calc( 100vh - ${props.theme.smallHeaderHeight} - ${props.theme.bottomBarHeight})`};
```

2021-11-29 05:38 UTC, Tooluloope commented on app/client/src/components/ads/TreeDropdown.tsx
> +  );
Might be better this way.

2021-11-29 06:22 UTC, Tooluloope approved these changes

2021-11-29 06:23 UTC, aswathkk commented
/ok-to-test sha=691553c

2021-11-30 11:34 UTC, aswathkk commented
/ok-to-test sha=691553c

2021-11-30 14:39 UTC, aswathkk commented
I'm facing an issue with testing this in cypress.
This is related to a [resolved cypress issue](https://github.com/cypress-io/cypress/issues/4395) I guess.

@NandanAnantharamu Can you help me with this?

2021-12-01 07:10 UTC, aswathkk commented
/ok-to-test sha=f1c4209

2021-12-01 08:28 UTC, NandanAnantharamu commented
> resolved cypress issue

this is has been resolved now

2021-12-02 07:03 UTC, vivekverma2312 commented
@aswathkk Tested and working fine now.

2021-12-02 07:28 UTC, Tooluloope approved these changes

2021-12-02 07:28 UTC, merged