feat: Show evaluated value in embeddedDatasource url
appsmithorg/appsmith pull request #9198
Opened 2021-11-17 09:15 UTC by ohansFavour

## Description

PR to show evaluated value in embedded datasource URL. 

Fixes #821

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
Cypress

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-11-24 08:48 UTC, hetunandu requested changes
Don't create a new path to create this. Instead just read all the evaluated values in the EmbeddedDatasourceField and pass that to the evaluated value pane

2021-11-24 08:48 UTC, hetunandu commented on app/client/src/entities/DataTree/dataTreeAction.ts
> +  // update datasource url for embedded datasource action
This is not the right place to do this

2021-11-24 11:17 UTC, ohansFavour commented on app/client/src/entities/DataTree/dataTreeAction.ts
> +  // update datasource url for embedded datasource action
Could you kindly suggest where this should happen?

2021-11-24 11:24 UTC, hetunandu commented on app/client/src/entities/DataTree/dataTreeAction.ts
> +  // update datasource url for embedded datasource action
`EmbeddedDatasourceField`

2021-11-30 12:59 UTC, ohansFavour commented
/ok-to-test sha=208f776

2021-11-30 14:00 UTC, ohansFavour commented
/ok-to-test sha=0a59108

2021-11-30 15:50 UTC, ohansFavour commented
/ok-to-test sha=9a7bda6

2021-12-01 03:57 UTC, ohansFavour commented
/ok-to-test sha=8210bfe

2021-12-02 06:05 UTC, ohansFavour commented
/ok-to-test sha=3afc622

2021-12-12 07:29 UTC, ohansFavour commented
/ok-to-test sha=84a3634

2021-12-20 09:26 UTC, ohansFavour commented
/ok-to-test sha=9fc0f01

2021-12-20 11:08 UTC, ohansFavour commented
/ok-to-test sha=05d6578

2021-12-20 12:34 UTC, ohansFavour commented
/ok-to-test sha=2bd4d3d

2021-12-21 14:16 UTC, ohansFavour commented
/ok-to-test sha=9b9196b

2021-12-27 05:02 UTC, hetunandu approved these changes

2021-12-28 12:14 UTC, merged