fix: #5915 Added JSConvertible to access the row background color.
appsmithorg/appsmith pull request #9238
Opened 2021-11-18 10:52 UTC by vibhandikyash

## Description

> Enable the JS convertible options for handling row background color.

Fixes #5915

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Tested locally.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-11-22 11:26 UTC, vibhandikyash commented
/ok-to-test sha=09f3180

2021-11-22 18:56 UTC, Tooluloope reviewed
LGTM
Could you add cypress test for these Enhancements

2021-11-25 08:36 UTC, aswathkk requested changes
@vibhandikyash We need to write validations for all the properties which has `isJSConvertible` as `true`

2021-11-25 11:58 UTC, vibhandikyash commented
/ok-to-test sha=b2cb553

2021-11-25 12:21 UTC, aswathkk requested changes

2021-11-25 12:21 UTC, aswathkk commented on app/client/src/widgets/TableWidget/widget/propertyConfig.ts
> +        isJSConvertible: true,
Since JSConvertible is true, users can type anything. Add validation here

2021-11-25 12:21 UTC, aswathkk commented on app/client/src/widgets/TableWidget/widget/propertyConfig.ts
> +        isJSConvertible: true,
Add validation here

2021-11-25 12:21 UTC, aswathkk commented on app/client/src/widgets/TableWidget/widget/propertyConfig.ts
> +        isJSConvertible: true,
Add validation here

2021-11-25 14:24 UTC, aswathkk requested changes

2021-11-25 14:24 UTC, aswathkk commented on app/client/src/widgets/TableWidget/widget/propertyConfig.ts
>                    isBindProperty: false,
`isBindProperty` has to be `true`. Then only the validation will be evaluated.

2021-11-26 05:51 UTC, vibhandikyash commented
/ok-to-test sha=7125bab

2021-11-29 07:44 UTC, vibhandikyash commented
/ok-to-test sha=0202dc3

2021-11-30 10:19 UTC, vibhandikyash commented
/ok-to-test sha=210ef14

2021-12-06 08:36 UTC, vibhandikyash commented
/ok-to-test sha=4ae2345

2021-12-09 07:27 UTC, aswathkk reviewed
Hi @vibhandikyash 
There are some problem with the validation of Table properties. Look at the video provided in [this](https://github.com/appsmithorg/appsmith/pull/9396#issue-1064264316) PR description.
Can you try using `ValidationTypes.TABLE_PROPERTY` for the validation?

2021-12-10 14:02 UTC, vibhandikyash commented
/ok-to-test sha=f21876b

2021-12-13 10:01 UTC, aswathkk requested changes

2021-12-14 05:31 UTC, aswathkk submitted a review, later dismissed
LGTM

2021-12-14 12:01 UTC, vibhandikyash commented
/ok-to-test sha=95f8163

2021-12-14 14:49 UTC, aswathkk commented
Hi @vibhandikyash The tests are failing since we are validating `fontStyle`.
There's an issue with BUTTON_TABS property control. I'm working on it while resolving #6797 
Can you remove validation for `fontStyle` in this PR for the time being?

2021-12-15 16:06 UTC, aswathkk requested changes
There are 2 places in the code where we uses "BUTTON_TABS".
In both these places, remove the entire validation object for now.

If you wanted to see the problem, go to deploy preview and edit the font Style option to have multiple styles BOLD and ITALIC together.

2021-12-16 10:07 UTC, vibhandikyash commented
/ok-to-test sha=bded580

2021-12-16 10:27 UTC, aswathkk approved these changes
LGTM.
Let's make sure to do a manual regression for all the modified table columns

cc: @vivekverma2312

2021-12-16 10:29 UTC, shwetha-ramesh commented
@vibhandikyash while testing this PR I've noticed that when cell background is set to any color light/dark the hover on any row is not visible.  Only when cell background is empty on hover the rows are highlighted. Without the hover action I wouldn't be able to continue testing this DP. Also one more observation is when the cell background is set to any color light/dark the selected rows are not visible. Please refer video

https://loom.com/share/ebd364a83f5648aabfd94c8f864b19d2

2022-01-18 11:54 UTC, somangshu commented
@vibhandikyash I am not getting the context right, 
- What is the issue here? 
- What is your fix? 
- why was this not taken forward up-till now?

2022-01-19 11:51 UTC, vibhandikyash commented
/ok-to-test sha=fb96fe6

2022-01-19 12:38 UTC, vibhandikyash commented
Closing this for now until we have a solution for perfect hover background.

2022-01-19 12:38 UTC, closed without merging