feat: Added action to upload multiple files in S3
appsmithorg/appsmith pull request #9337
Opened 2021-11-24 09:56 UTC by nidhi-nair

Fixes #6737

2021-12-07 09:00 UTC, sumitsum requested changes

2021-12-07 09:06 UTC, nidhi-nair commented on app/server/appsmith-plugins/amazons3Plugin/src/main/java/com/external/plugins/constants/AmazonS3Action.java
> +    UPLOAD_MULTIPLE_FILES_FROM_BODY,
From our list of UQI methods that we want plugins to support, CRUD and multi CRUD are separated out into separate methods, which is why I created a separate action.

2021-12-09 06:13 UTC, sumitsum approved these changes

2021-12-09 06:18 UTC, nidhi-nair commented
/ok-to-test sha=f0a0676

2021-12-10 04:17 UTC, nidhi-nair commented
/ok-to-test sha=f0a0676

2021-12-10 05:14 UTC, nidhi-nair commented
/ok-to-test sha=f0a0676

2021-12-10 10:05 UTC, nidhi-nair commented
/ok-to-test sha=f0a0676

2021-12-10 10:43 UTC, merged