wip(run-hot-key): Correcting the execution of query with the latest values when run shortcut is pressed
appsmithorg/appsmith pull request #9363
Opened 2021-11-25 06:12 UTC by AmanAgarwal041

## Description

Pressing cmd+enter while continuously typing the query executes the query with the stale value updated in the redux store.

Fixes #7754 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Type in the query in the query editor of the datasource and then while typing the query continuously press CMD+ENTER to execute the query. After the fix the query should execute with the latest value in the editor after updating the values in the redux store as well.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-11-25 15:12 UTC, ayushpahwa requested changes
Please update the description to give an overview of the fix.

2021-11-25 15:12 UTC, ayushpahwa commented on app/client/src/constants/ReduxActionConstants.tsx
> +  /* This action constants is for identifying the starting of the updates */
Please change this name to something like PRE_INIT or something that mentions that it is called before INIT

2021-11-25 15:12 UTC, ayushpahwa commented on app/client/src/actions/queryPaneActions.ts
> +});
Please update the name here too.

2021-11-30 04:56 UTC, hetunandu submitted a review, later dismissed
LGTM. Just update the names

2021-12-08 08:31 UTC, AmanAgarwal041 commented
/ok-to-test sha=eb56c3b

2021-12-09 05:59 UTC, rashmi-rai approved these changes

2021-12-09 06:13 UTC, hetunandu requested changes
Can't name the action INIT_UPDATE_ACTION because UPDATE_ACTION_INIT already exists.

2021-12-16 02:52 UTC, hetunandu requested changes

2021-12-16 02:52 UTC, hetunandu commented on app/client/src/components/editorComponents/CodeEditor/index.tsx
> +  startHandleChange = (instance?: any, changeObj?: any) => {
rename to startChange

2021-12-16 02:52 UTC, hetunandu commented on app/client/src/components/editorComponents/CodeEditor/index.tsx
> +    }
This needs to be generic. Dispatch an action called: `ENTITY_UPDATE_STARTED` with entity type and id. We should not handle actions separately in a generic component

2021-12-16 02:52 UTC, hetunandu commented on app/client/src/reducers/uiReducers/queryPaneReducer.ts
> +  [ReduxActionTypes.PREPARING_UPDATE_ACTION]: (
Use `ENTITY_UPDATE_STARTED` here and look for your entity type and id. Only update if it is an action

2021-12-17 12:43 UTC, hetunandu approved these changes

2021-12-20 13:33 UTC, hetunandu approved these changes

2021-12-20 13:46 UTC, AmanAgarwal041 commented
/ok-to-test sha=76a28b7

2021-12-22 08:04 UTC, AmanAgarwal041 commented
/ok-to-test sha=e727c41

2021-12-22 14:06 UTC, AmanAgarwal041 commented
/ok-to-test sha=83e13f2

2021-12-23 06:35 UTC, AmanAgarwal041 commented
/ok-to-test sha=d309055

2021-12-23 16:51 UTC, AmanAgarwal041 commented
ok-to-test sha=896025a

2021-12-23 16:52 UTC, AmanAgarwal041 commented
/ok-to-test sha=896025a

2021-12-24 13:57 UTC, mohanarpit approved these changes

2021-12-24 13:59 UTC, merged