fix: table icon selector js mode toggle issue
appsmithorg/appsmith pull request #9396
Opened 2021-11-26 09:32 UTC by aswathkk

## Description

The issue was happening since there was no proper validation.
As part of this added a new validation type to validate the properties of table.

Fixes #8250 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Manually tested

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-11-26 10:01 UTC, riodeuno submitted a review, later dismissed

2021-11-26 11:10 UTC, aswathkk commented
/ok-to-test sha=45e31ec

2021-11-26 12:25 UTC, aswathkk commented
/ok-to-test sha=1a1b297

2021-11-26 12:30 UTC, riodeuno approved these changes

2021-11-26 14:25 UTC, aswathkk commented
/ok-to-test sha=1a1b297

2021-11-26 19:53 UTC, aswathkk commented
/ok-to-test sha=609e939

2021-11-29 05:51 UTC, vivekverma2312 commented
@aswathkk It's working fine for icon type property but I observe issue for button colour and shadow colour properties.
https://www.loom.com/share/89301957c9a14a75acd64157b67578f1

2021-11-30 06:33 UTC, aswathkk commented
/ok-to-test sha=a112c98

2021-11-30 10:38 UTC, aswathkk commented
/ok-to-test sha=739d608

2021-11-30 16:51 UTC, riodeuno requested changes
One concern about the color validation. The rest looks good.

2021-11-30 16:51 UTC, riodeuno commented on app/client/src/utils/validation/common.ts
> +    case ValidationTypes.COLOR:
Can we use a text validation with regex for color here? The video demo for widget development uses this.

2021-11-30 17:01 UTC, aswathkk commented on app/client/src/utils/validation/common.ts
> +    case ValidationTypes.COLOR:
I thought color can be any color value that we use in CSS.
Should we restrict to only hex?

2021-11-30 17:56 UTC, riodeuno commented on app/client/src/entities/Widget/utils.test.ts
> +            type: ValidationTypes.COLOR,
We should remove this now, or the tests should fail. Is that correct?

2021-11-30 17:59 UTC, aswathkk commented on app/client/src/entities/Widget/utils.test.ts
> +            type: ValidationTypes.COLOR,
my bad. Will update it now

2021-11-30 18:13 UTC, riodeuno submitted a review, later dismissed

2021-11-30 18:26 UTC, aswathkk commented
/ok-to-test sha=1802938

2021-12-01 04:39 UTC, vivekverma2312 commented
@aswathkk Thanks for the fix, it's working fine on deploy preview.

2021-12-01 09:19 UTC, aswathkk commented
/ok-to-test sha=a313866

2021-12-01 11:15 UTC, aswathkk commented
/ok-to-test sha=a313866

2021-12-01 12:09 UTC, riodeuno commented on app/client/src/widgets/constants.ts
> +export const COLOR_REGEX = /^(#([0-9a-f]{2}){2,4}|#[0-9a-f]{3}|(rgb)\((\s*\d+\s*,){2}\s*\d+\s*\)|(rgba)\((\s*\d+\s*,){3}\s*[\d.]+\s*\))$/i;
We need tests for this regex. Let's add some jest tests which validate different types of colour inputs with this regex.

2021-12-01 12:09 UTC, riodeuno submitted a review, later dismissed

2021-12-01 12:10 UTC, aswathkk commented on app/client/src/widgets/constants.ts
> +export const COLOR_REGEX = /^(#([0-9a-f]{2}){2,4}|#[0-9a-f]{3}|(rgb)\((\s*\d+\s*,){2}\s*\d+\s*\)|(rgba)\((\s*\d+\s*,){3}\s*[\d.]+\s*\))$/i;
@riodeuno Its available at app/client/src/widgets/constants.test.ts

2021-12-01 12:11 UTC, riodeuno commented
Ah sorry, I didn't see that

2021-12-02 05:37 UTC, aswathkk commented
/ok-to-test sha=eb65e99

2021-12-02 07:48 UTC, aswathkk commented
/ok-to-test sha=eb65e99

2021-12-02 09:11 UTC, aswathkk commented
/ok-to-test sha=eb65e99

2021-12-03 05:23 UTC, aswathkk commented
/ok-to-test sha=8f25b8a

2021-12-03 06:15 UTC, riodeuno submitted a review, later dismissed
LGTM!
Let's make sure to go through a manual regression for all table columns

2021-12-03 07:21 UTC, vivekverma2312 commented
@aswathkk The issue exist for Text colour and Cell back ground property for Plain text, URL, Number and Date types.
https://www.loom.com/share/532e4255d8d14726a2a1b6eac90ee426

2021-12-03 09:28 UTC, aswathkk commented
/ok-to-test sha=9cbce3b

2021-12-07 07:05 UTC, aswathkk commented
/ok-to-test sha=682c62d

2021-12-07 08:47 UTC, aswathkk commented
/ok-to-test sha=b646c30

2021-12-08 05:16 UTC, riodeuno approved these changes

2021-12-09 06:12 UTC, vivekverma2312 commented
@aswathkk It's working fine for Icon selector.

2021-12-09 06:15 UTC, merged