fix: 8336 updated isLoading property in all widgets
appsmithorg/appsmith pull request #9409
Opened 2021-11-26 13:18 UTC by techbhavin

## Description

> Add an Animate Loading property for all widgets

Fixes #8336

## Type of change

- New feature (non-breaking change which adds functionality)
## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-11-26 13:20 UTC, techbhavin commented
/ok-to-test sha=42e146b

2021-11-29 04:40 UTC, jsartisan approved these changes

2021-11-29 06:32 UTC, techbhavin commented
/ok-to-test sha=bbeb6f1

2021-11-30 08:10 UTC, YogeshJayaseelan commented
@techbhavin Verified this PR and please find the testing status below,

Issue 1 - Disabling the loading toggle for button widget and OnClick is binded to execute an API - Still the loading animation is displayed for button widget 

https://www.loom.com/share/c379da8ba7dd42e993182b6b67150f9f

Issue 2 - Loading animation does not happen for most of the widgets - ButtonGroup Widget, Icon Widget, Menu Button Widget, Image , Select , MultiSelect, MultiTreeSelect, TreeSelect, Switch, Radio, Ratting Widget 

https://www.loom.com/share/1e5b2d63d8864e32897c74ed16f4da62

2021-11-30 13:51 UTC, jsartisan submitted a review, later dismissed

2021-12-03 09:51 UTC, hetunandu requested changes

2021-12-03 09:51 UTC, hetunandu commented on app/client/src/sagas/WidgetLoadingSaga.ts
> +  });
You need to check the `animateLoading` property and if it is false, remove it from the `loadingEntities` list.

2021-12-03 15:52 UTC, techbhavin commented
/ok-to-test sha=1760f25

2021-12-04 07:43 UTC, hetunandu requested changes

2021-12-04 07:43 UTC, hetunandu commented on app/client/src/sagas/WidgetLoadingSaga.ts
> +      if (get(dataTree, [entityName, "animateLoading"])) {
```suggestion
      if (get(dataTree, [entityName, "animateLoading"]) === false) {
```

2021-12-04 07:43 UTC, hetunandu commented on app/client/src/sagas/WidgetLoadingSaga.ts
> +      } else {
```suggestion

```

2021-12-06 05:34 UTC, hetunandu requested changes
By default, all animateLoading should be `true`

2021-12-06 13:45 UTC, techbhavin commented
/ok-to-test sha=718a6c4

2021-12-10 03:45 UTC, techbhavin commented
/ok-to-test sha=f32fd32

2021-12-10 04:18 UTC, YogeshJayaseelan commented
@techbhavin Tested this PR and please find the testing status below,

Issue 1 - Not a valid scenario,
Issue 2 - Not a valid Scenario,

**New issue:**

Issue 3 - when the button group widget any of the button label name is binded with {{Query1.data.length}} and the same query is executed by clicking on the button widget - Button widget OnClick is binded to execute {{Query1.run()}} the animate loading is not happening for the button group widget.

https://www.loom.com/share/b4a599f520d44edcbbf57da057b29dfa

**Note : The above issue happens for Button group widget, Menu Widget**

Issue 4 - Animate loading toggle is not available for Switch group widget

<img width="1680" alt="Screenshot 2021-12-10 at 9 42 56 AM" src="https://user-images.githubusercontent.com/35128442/145516224-fe293d60-9c50-40fc-8a4a-0130bde63e57.png">

2021-12-10 08:37 UTC, techbhavin commented
/ok-to-test sha=c3d6de2

2021-12-10 08:39 UTC, techbhavin commented
@hetunandu  @YogeshJayaseelan  

issue 3: loading UI is not supported for Button group widget and Menu Widget
issue 4:   done

2021-12-13 05:38 UTC, techbhavin commented
/ok-to-test sha=953e76d

2021-12-14 04:27 UTC, YogeshJayaseelan commented
@techbhavin Verified the fix and it is working as expected and we can proceed further

2021-12-14 06:21 UTC, hetunandu approved these changes

2021-12-14 07:55 UTC, merged