fix:added support for timePrecision
appsmithorg/appsmith pull request #9423
Opened 2021-11-29 06:41 UTC by techbhavin

## Description

> Allow users to insert hour:time: seconds in date-time-picker widget

Fixes #9100 

## Type of change

- New feature (non-breaking change which adds functionality)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-11-30 05:55 UTC, techbhavin commented
/ok-to-test sha=c781f1f

2021-11-30 13:51 UTC, jsartisan submitted a review, later dismissed

2021-12-02 09:25 UTC, shwetha-ramesh commented
@techbhavin tested this PR
1. the time slot input box appears only when the input is dropped on the canvas. When the user changes from the default format to any other format and moved back to the default format the time slot input disappears. (refer video)
2. Time slot input not available for any of the format that.

https://loom.com/share/406044fb99a4403489afcc487dd83ed2

2021-12-02 13:08 UTC, techbhavin commented
/ok-to-test sha=8fbf0d4

2021-12-06 04:33 UTC, jsartisan submitted a review, later dismissed

2021-12-07 03:46 UTC, techbhavin commented
/ok-to-test sha=e9bc116

2021-12-07 09:59 UTC, shwetha-ramesh commented
@techbhavin tested this PR. Below are the points.
1) The seconds field must not be shown for _YYYY-MM-DD HH:mm_ format or any format that does not have _ss_ mentioned, irrespective of what 'time precision' is set
https://loom.com/share/0f9adc6e148d42fda0c96a5a7842c068

2) _Clear_ must clear the timeslot values also.
![image](https://user-images.githubusercontent.com/92293815/145007362-4c26fc1b-469c-41ea-a8a9-9aaa0f045763.png)

https://loom.com/share/b10f5565f2b74c7ea760de1d7db4c492

3) Since the _Time precision_ field is placed at the end of General settings, the user might not know a field as such exists and when changes the format which has hh:mm:ss and not be able to change the seconds field.

2021-12-07 12:37 UTC, techbhavin commented
> The seconds field must not be shown for `YYYY-MM-DD HH:mm` format or any format that does not have ss mentioned, irrespective of what 'time precision' is set

In a current implementation, we show `hh:mm`  in every format. did we want to do as per @shwetha-ramesh  mention?

ALSO NEED FEEDBACK about point 2 , 3
  
@somangshu  @sbalaji1192  @riodeuno

2021-12-09 10:00 UTC, sbalaji1192 commented
@techbhavin @shwetha-ramesh @Tooluloope 
WRT,
#1, Current implementation seems good as it's not leading to any bug. Having two configs controlling the same field is bit much to maintain.
#2, Agreed on the callout. we need to clear the time as well. since closing and opening the popup resets the time.
#3, Let's move the time precision right below to the time format.

2021-12-10 07:48 UTC, techbhavin commented
/ok-to-test sha=e0c5d8a

2021-12-10 07:54 UTC, techbhavin commented
@sbalaji1192  @shwetha-ramesh  @Tooluloope 

point 3: updated 
point 2: here we have a limitation in the library we can’t reset the time picker value. 

![image](https://user-images.githubusercontent.com/58818598/145537532-8b812f50-3ba6-488d-b178-dfa43a1051cb.png)

2021-12-13 06:49 UTC, riodeuno requested changes

2021-12-13 06:49 UTC, riodeuno commented on app/client/src/widgets/DatePickerWidget2/widget/index.tsx
> +                  "None",
Let's include this in the TimePrecision enum. `TimePrecision.NONE`. 
One way to achieve this is to create a TimePrecision enum by ourselves.
This helps with maintaining integrity across the codebase regarding time precision values.

2021-12-14 06:54 UTC, techbhavin commented
/ok-to-test sha=d6c4a99

2021-12-14 07:10 UTC, riodeuno commented on app/client/src/widgets/DatePickerWidget2/constants.ts
> +export declare const TimePrecision: {
Is there a reason we used `declare const` instead of an `enum`?

2021-12-14 07:11 UTC, riodeuno submitted a review, later dismissed

2021-12-14 07:13 UTC, riodeuno commented
@sbalaji1192 I've checked the code. Please verify the issue resolution in your review. @shwetha-ramesh Moved this to the QA pipeline.

2021-12-14 08:23 UTC, techbhavin commented
/ok-to-test sha=235e8cb

2021-12-14 10:39 UTC, shwetha-ramesh commented
> @sbalaji1192 @shwetha-ramesh @Tooluloope
> 
> point 3: updated point 2: here we have a limitation in the library we can’t reset the time picker value.
> 
> ![image](https://user-images.githubusercontent.com/58818598/145537532-8b812f50-3ba6-488d-b178-dfa43a1051cb.png)

@techbhavin @sbalaji1192 Are we not clearing the time ?

2021-12-14 11:00 UTC, shwetha-ramesh commented
@techbhavin tested this PR. Found the below issue.

1. When the user clicks on _Clear_ , the field gets empty and no selection is seen on the calendar however the previous time still remains on the time slot field. Only when the user clicks on the canvas and then back on the widget the time slot field will be cleared (Refer video)
https://loom.com/share/6933df7b7d7f44b085884950866af58c

2. After _Clear_ the timeslot field must display 00:00:00 / 00:00 and not 0:00:00 / 0:00
![image](https://user-images.githubusercontent.com/92293815/145984979-b3dbaf36-a47c-465d-8206-1f8f8cc973ce.png)

Ideal behavior would be : On _Clear_ both time and date must be cleared without the user having to go back and forth on the widget and 00:00:00 format must be displayed in timeslot field after clear.

Moving to Inprogress.

2021-12-14 11:57 UTC, techbhavin commented
Above issue 1 and 2 is Out of scope issues. for reference, 
  I am please refer [blueprintjs-datepicker](https://blueprintjs.com/docs/#datetime/datepicker) 
  
@shwetha-ramesh  @sbalaji1192  @Tooluloope  @somangshu

2021-12-15 09:37 UTC, somangshu commented
@techbhavin can we solve for the issue 1 reported above by @shwetha-ramesh. I think its valid to see the correct state, Can we set it on clear? Cause rerendering the widget cause it to show default

2021-12-15 10:45 UTC, techbhavin commented
@somangshu  this is not possible reason is time picker is controlled by the date-picker. here showing `0:00` reason is component is re-render on date-picker popover closed that why the state is re-set. 

we don't have a clear `onClick` handler.

2021-12-15 11:50 UTC, somangshu commented
@jsartisan can you think of a way to re-render the component so that we see the update

2021-12-17 11:20 UTC, jsartisan commented
@somangshu We can't do anything if library is not giving any callback handler :/

cc: @techbhavin

2021-12-17 11:29 UTC, somangshu commented
@shwetha-ramesh @techbhavin we can proceed then

2021-12-17 11:34 UTC, techbhavin commented
/ok-to-test sha=db2e9ec

2021-12-21 07:20 UTC, shwetha-ramesh commented
As agreed upon with above comments. Moving to DONE.

2021-12-21 09:17 UTC, techbhavin commented
/ok-to-test sha=705c400

2021-12-21 12:50 UTC, techbhavin commented
/ok-to-test sha=1fa162c

2021-12-22 06:34 UTC, techbhavin commented
/ok-to-test sha=1fa162c

2021-12-22 17:09 UTC, sbalaji1192 commented on app/client/src/widgets/DatePickerWidget2/index.ts
> +import { TimePrecision } from "@blueprintjs/datetime";
Lets use our TimePrecision

2021-12-23 06:58 UTC, techbhavin commented
/ok-to-test sha=bd8d93a

2021-12-23 09:53 UTC, sbalaji1192 approved these changes

2021-12-23 14:17 UTC, merged