Fix/unexpected return error
appsmithorg/appsmith pull request #9432
Opened 2021-11-29 11:31 UTC by eco-monk

## Description

Handle empty new lines in fields

Fixes #8658

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- unit tests
- enter only new line in any js field with {{}} binding 
```
{{

}}
```
- notice "Unexpected return error" doesn't show up anymore

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-11-29 13:28 UTC, eco-monk commented
/ok-to-test sha=96e3198

2021-11-30 05:05 UTC, hetunandu commented on app/client/src/workers/evaluate.test.ts
> +import { PropertyEvaluationErrorType } from "utils/DynamicBindingUtils";
```suggestion
```

2021-11-30 07:01 UTC, hetunandu approved these changes

2021-11-30 08:47 UTC, eco-monk commented
/ok-to-test sha=1635e1d

2021-11-30 12:13 UTC, eco-monk commented
/ok-to-test sha=32b2322

2021-12-02 06:06 UTC, eco-monk commented
/ok-to-test sha=a23f3b4

2021-12-02 10:40 UTC, eco-monk commented
/ok-to-test sha=d4d2073

2021-12-03 06:47 UTC, eco-monk commented
/ok-to-test sha=1b8a1b5

2021-12-03 07:18 UTC, eco-monk commented
/ok-to-test sha=730d90c

2021-12-03 08:36 UTC, eco-monk commented
/ok-to-test sha=9409209

2021-12-08 01:32 UTC, eco-monk commented
/ok-to-test sha=853adef

2021-12-09 05:58 UTC, hetunandu requested changes

2021-12-09 05:58 UTC, hetunandu commented on app/client/src/workers/evaluate.ts
> +    scriptToLint = "";
```suggestion
  let script = "";
  let scriptToLint = "";
```

2021-12-09 05:58 UTC, hetunandu commented on app/client/src/workers/evaluate.ts
> +  if (unescapedJS.length > 0) {
Explain in comments why this if statement is needed

2021-12-09 05:58 UTC, hetunandu commented on app/client/src/workers/evaluate.ts
> +  if (unescapedJS.length > 0) {
If nothing is present to evaluate, lets just return back instead of evaluating

2021-12-09 06:27 UTC, eco-monk commented
/ok-to-test sha=3f67036

2021-12-09 07:12 UTC, eco-monk commented on app/client/src/workers/evaluate.ts
> +  if (unescapedJS.length > 0) {
Returning an empty response now
```
{
      errors: [],
      result: undefined,
      triggers: [],
};
```
---

Tried just `undefined`. Had to add null check in too many other places, as a consequence.

This is simpler.

2021-12-09 07:13 UTC, hetunandu commented on app/client/src/workers/evaluate.ts
> +  if (!(unescapedJS.length > 0)) {
```suggestion
  if (!unescapedJS.length) {
```

2021-12-09 07:13 UTC, hetunandu submitted a review, later dismissed

2021-12-09 07:17 UTC, eco-monk commented
/ok-to-test sha=dd2805a

2021-12-15 07:24 UTC, eco-monk commented
/ok-to-test sha=a754f9b

2021-12-21 12:35 UTC, ApekshaBhosale approved these changes

2021-12-21 14:30 UTC, merged