fix: default tab validation in tabs widget
appsmithorg/appsmith pull request #9433
Opened 2021-11-29 11:43 UTC by vicky-primathon

## Description

Default tab validation when updating or adding tabs after mentioning them in default tab.

Fixes #8465 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-11-29 12:05 UTC, vicky-primathon commented
/ok-to-test sha=ced6c8c

2021-12-01 22:14 UTC, Tooluloope approved these changes
LGTM
@rahulramesha could you help look at the Sagas changes.

2021-12-02 08:26 UTC, rahulramesha commented
@vicky-primathon, this seems to have broken adding new tabs to Tab Widget. After adding a new tab can't seem to open the new tab. Also, I believe @marks0351 wrote that saga, best if he reviews it.

2021-12-02 08:58 UTC, marks0351 requested changes
pls add test cases for the fix as well as to check if undo redo also works as expected.

2021-12-02 08:58 UTC, marks0351 commented on app/client/src/components/propertyControls/TabControl.tsx
>      dispatch({
send them to the saga and handle it there, you should not be doing a double update since undo redo feature will not work as expected.

2021-12-02 09:10 UTC, YogeshJayaseelan commented
@vicky-primathon Tested this PR now the default validation works but as mentioned by @rahulramesha new tabs are not accessible and as mentioned by @marks0351 undo and redo are not working as expected and moving this to in-progress state

2021-12-15 02:02 UTC, Tooluloope commented
@vicky-primathon Could you check this PR?

2022-03-14 08:45 UTC, closed without merging