Feat: Moving form evaluations to separate thread (8051)
appsmithorg/appsmith pull request #9437
Opened 2021-11-29 13:32 UTC by ayushpahwa

## Description

Evaluations are currently in the main thread which is a bad practice. Used the GracefulServiceWorker implementation here.

Fixes #8051

## Type of change

- New feature (non-breaking change which adds functionality)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-11-29 13:33 UTC, ayushpahwa commented
/ok-to-test sha=82e4347

2021-11-29 13:34 UTC, ayushpahwa reviewed
Add comments to the file

2021-11-30 05:27 UTC, hetunandu requested changes

2021-11-30 05:27 UTC, hetunandu commented on app/client/src/workers/formEval.ts
> +      Sentry.captureException(e);
Sentry and loglevel do not work in the worker

2021-11-30 05:27 UTC, hetunandu commented on app/client/src/sagas/FormEvaluationSaga.ts
> +export function* setFormEvaluationSagaAsync(action: any): any {
Add types

2021-11-30 05:27 UTC, hetunandu commented on app/client/src/sagas/FormEvaluationSaga.ts
> +const worker = new GracefulWorkerService(Worker);
Why are we creating a new worker service? Use the same one that exists

2021-11-30 05:27 UTC, hetunandu commented on app/client/src/sagas/FormEvaluationSaga.ts
> +const evalQueue: any[] = [];
Considering that we will eval the whole form every time, why are we maintaining a queue?

2021-11-30 05:27 UTC, hetunandu commented on app/client/src/workers/formEval.ts
> +  if (type === ReduxActionTypes.INIT_FORM_EVALUATION) {
```suggestion
  if (type === EVAL_WORKER_ACTIONS.INIT_FORM_EVALUATION) {
```

Why is this check needed?

2021-11-30 05:27 UTC, hetunandu commented on app/client/src/workers/formEval.ts
> +  currentEvalState: any,
Add types

2021-11-30 05:27 UTC, hetunandu commented on app/client/src/workers/formEval.ts
> +  actionConfiguration: any,
missing types

2021-11-30 06:09 UTC, ayushpahwa commented on app/client/src/sagas/FormEvaluationSaga.ts
> +const evalQueue: any[] = [];
This is because there is a race condition that is happening. Before any eval can be run, the eval structure has to be extracted from the JSON. If an eval is run before eval structure is extracted, the output will be blank for the whole form.

2021-11-30 06:12 UTC, ayushpahwa commented on app/client/src/workers/formEval.ts
> +  if (type === ReduxActionTypes.INIT_FORM_EVALUATION) {
This is because there are two stages to eval. At first, the eval structure is extracted from the JSON forms, then the evals are run in the next step. This check is for that purpose only.

2021-12-01 06:17 UTC, ayushpahwa commented on app/client/src/sagas/FormEvaluationSaga.ts
> +const worker = new GracefulWorkerService(Worker);
If I remember correctly, we discussed creating a new one because the logic is self-contained. Can you help here?

2021-12-01 06:17 UTC, ayushpahwa commented on app/client/src/sagas/FormEvaluationSaga.ts
> +export function* setFormEvaluationSagaAsync(action: any): any {
Done

2021-12-01 06:17 UTC, ayushpahwa commented on app/client/src/workers/formEval.ts
> +      Sentry.captureException(e);
Removed

2021-12-01 06:17 UTC, ayushpahwa commented on app/client/src/workers/formEval.ts
> +  currentEvalState: any,
Done

2021-12-01 06:18 UTC, ayushpahwa commented on app/client/src/workers/formEval.ts
> +  actionConfiguration: any,
Done

2021-12-29 19:23 UTC, ayushpahwa commented
/ok-to-test sha=8d89de2

2021-12-29 19:26 UTC, ayushpahwa commented on app/client/src/sagas/FormEvaluationSaga.ts
> +const worker = new GracefulWorkerService(Worker);
Changed to using the same thread only.

2021-12-30 03:41 UTC, ayushpahwa commented
/ok-to-test sha=8d89de2

2022-01-04 06:20 UTC, hetunandu requested changes

2022-01-04 06:20 UTC, hetunandu commented on app/client/src/sagas/FormEvaluationSaga.ts
>  const FORM_EVALUATION_REDUX_ACTIONS = [
move to actions/evaluationActions

2022-01-04 06:20 UTC, hetunandu commented on app/client/src/pages/Editor/QueryEditor/EditorJSONtoForm.tsx
> +  const checkIfSectionCanRender = (section: any) => {
You need to add types for section config

2022-01-04 06:20 UTC, hetunandu commented on app/client/src/sagas/EvaluationsSaga.ts
> +export function* workerComputeFormEvals(
rename: evalFormConfig

2022-01-04 06:20 UTC, hetunandu commented on app/client/src/sagas/EvaluationsSaga.ts
> +  operation: string,
Need types of operations allowed

2022-01-04 06:20 UTC, hetunandu commented on app/client/src/sagas/FormEvaluationSaga.ts
> +function* setFormEvaluationSagaAsync(action: ReduxAction<any>): any {
Add types for which redux action is allowed

2022-01-04 06:20 UTC, hetunandu commented on app/client/src/workers/formEval.ts
> +let finalEvalObj: { [x: string]: { visible: boolean; conditionals: any } };
Needs types for conditionals

2022-01-04 06:20 UTC, hetunandu commented on app/client/src/workers/formEval.ts
> +const generateInitialEvalState = (formConfig: any) => {
Form config types

2022-01-04 09:03 UTC, ayushpahwa commented on app/client/src/sagas/FormEvaluationSaga.ts
>  const FORM_EVALUATION_REDUX_ACTIONS = [
Done

2022-01-04 09:03 UTC, ayushpahwa commented on app/client/src/pages/Editor/QueryEditor/EditorJSONtoForm.tsx
> +  const checkIfSectionCanRender = (section: any) => {
Done

2022-01-04 09:03 UTC, ayushpahwa commented on app/client/src/sagas/EvaluationsSaga.ts
> +export function* workerComputeFormEvals(
Done

2022-01-04 09:03 UTC, ayushpahwa commented on app/client/src/sagas/EvaluationsSaga.ts
> +  operation: string,
Done

2022-01-04 09:03 UTC, ayushpahwa commented on app/client/src/sagas/FormEvaluationSaga.ts
> +function* setFormEvaluationSagaAsync(action: ReduxAction<any>): any {
Done

2022-01-04 09:03 UTC, ayushpahwa commented on app/client/src/workers/formEval.ts
> +let finalEvalObj: { [x: string]: { visible: boolean; conditionals: any } };
Done

2022-01-04 09:03 UTC, ayushpahwa commented on app/client/src/workers/formEval.ts
> +const generateInitialEvalState = (formConfig: any) => {
Done

2022-01-04 09:03 UTC, ayushpahwa commented
/ok-to-test sha=2678949

2022-01-04 09:20 UTC, hetunandu requested changes

2022-01-04 09:20 UTC, hetunandu commented on app/client/src/actions/evaluationActions.ts
> +// All the topics this saga listens to
Improve comment

2022-01-04 09:20 UTC, hetunandu commented on app/client/src/pages/Editor/DataSourceEditor/RestAPIDatasourceForm.tsx
> +          conditionals: { "": "" },
Not a good idea to keep this as a default. If this is happening for types, improve the types

2022-01-04 09:20 UTC, hetunandu commented on app/client/src/sagas/EvaluationsSaga.ts
> +export function* workerComputeFormEvals(
Not seeing this

2022-01-04 09:20 UTC, hetunandu commented on app/client/src/sagas/EvaluationsSaga.ts
> +  operation: string,
Not seeing this

2022-01-04 10:29 UTC, ayushpahwa commented on app/client/src/actions/evaluationActions.ts
> +// All the topics this saga listens to
Done

2022-01-04 10:29 UTC, ayushpahwa commented on app/client/src/pages/Editor/DataSourceEditor/RestAPIDatasourceForm.tsx
> +          conditionals: { "": "" },
Done, chaged to just `{}`

2022-01-04 10:30 UTC, ayushpahwa commented
/ok-to-test sha=3906d53

2022-01-04 11:17 UTC, ayushpahwa commented
/ok-to-test sha=c57a972

2022-01-06 08:38 UTC, ayushpahwa commented
/ok-to-test sha=54a6e8f

2022-01-06 09:18 UTC, ayushpahwa commented
/ok-to-test sha=54a6e8f

2022-01-06 10:49 UTC, merged