fix(query-keys-map): Adding empty array check for mapping keys
appsmithorg/appsmith pull request #9459
Opened 2021-11-30 07:55 UTC by AmanAgarwal041

## Description

Adding an empty array check before mapping for keys for the query data. An array of keys is being created by looping the data there was no check added if there was empty data being returned for the query.

Fixes #9425 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Steps to reproduce :

1. Go to datasource
2.  Add a Select Query in Postgres Database
3.  Add A query as SELECT * FROM Company WHERE NAME LIKE 'Sh%';
4.  Run the query Or Copy the query from other Datasource and forget to change the Table name Run the query the application breaks
5. Previously it was breaking the application.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-11-30 08:17 UTC, ayushpahwa requested changes
Add comments please

2021-11-30 08:36 UTC, AmanAgarwal041 commented
> Add comments please

Done

2021-11-30 09:10 UTC, ayushpahwa approved these changes

2021-12-01 09:59 UTC, RakshaKShetty commented
The issue is fixed

2021-12-01 11:17 UTC, yatinappsmith commented
/ok-to-test sha=33d98ad

2021-12-01 13:06 UTC, merged