fix: disable submit button when date is out of bounds
appsmithorg/appsmith pull request #9552
Opened 2021-12-03 08:19 UTC by vicky-primathon

## Description
DatePicker isvalid property checks for if the date is out of bounds or invalid.

Fixes #9099 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Added unit test for the validation.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-12-03 08:26 UTC, vicky-primathon commented
/ok-to-test sha=4b6a314

2021-12-09 09:05 UTC, vicky-primathon commented
/ok-to-test sha=d37c987

2021-12-09 09:15 UTC, Tooluloope requested changes
The submit button is valid even when there's no selected date

![Screenshot 2021-12-09 at 10 12 03](https://user-images.githubusercontent.com/31691737/145367585-00bdd185-d06e-4dae-8ffe-8452486dafbc.png)

2021-12-09 09:18 UTC, Tooluloope requested changes

2021-12-09 09:18 UTC, Tooluloope commented on app/client/src/widgets/DatePickerWidget2/widget/derived.js
> +      const isValid = moment(selectedDate).isBetween(minDate, maxDate);
What would happen if there's either no minDate or Max Date or if both aren't given?

2021-12-09 09:18 UTC, Tooluloope commented on app/client/src/widgets/DatePickerWidget2/widget/derived.js
> +      const isValid = moment(selectedDate).isBetween(minDate, maxDate);
could we also add cypress test

2021-12-15 02:45 UTC, Tooluloope commented
@vicky-primathon Any update on this as well?

2021-12-15 05:28 UTC, vicky-primathon commented on app/client/src/widgets/DatePickerWidget2/widget/derived.js
> +      const isValid = moment(selectedDate).isBetween(minDate, maxDate);
@Tooluloope  we have added unit tests for this function

2021-12-15 05:29 UTC, vicky-primathon commented
> The submit button is valid even when there's no selected date
> 
> ![Screenshot 2021-12-09 at 10 12 03](https://user-images.githubusercontent.com/31691737/145367585-00bdd185-d06e-4dae-8ffe-8452486dafbc.png)

This issue is fixed

2021-12-15 05:30 UTC, vicky-primathon commented
/ok-to-test sha=efdfa5c

2021-12-15 15:59 UTC, Tooluloope commented
The max date isn't validating

![Screenshot 2021-12-15 at 16 59 05](https://user-images.githubusercontent.com/31691737/146220530-47a4194b-5830-4a0d-a69c-c5f847424762.png)

2021-12-16 05:32 UTC, vicky-primathon commented
> The max date isn't validating
> 
> ![Screenshot 2021-12-15 at 16 59 05](https://user-images.githubusercontent.com/31691737/146220530-47a4194b-5830-4a0d-a69c-c5f847424762.png)

@Tooluloope 
Max date validation is working in above screenshot. In above screenshot Min date is 29/12/2000 and Max date is 31/12/2121  and the selected date is 26/12/2025 which is between min and max date.

2021-12-16 06:38 UTC, vicky-primathon commented
> The max date isn't validating
> 
> ![Screenshot 2021-12-15 at 16 59 05](https://user-images.githubusercontent.com/31691737/146220530-47a4194b-5830-4a0d-a69c-c5f847424762.png)

@Tooluloope the screenshot you shared has selected date falling between min date and max date. That is why submit button is enabled.

2021-12-16 07:35 UTC, Tooluloope commented
Oh my mistake @vicky-primathon 😅

2021-12-16 07:36 UTC, Tooluloope submitted a review, later dismissed

2021-12-21 09:15 UTC, YogeshJayaseelan commented
@vicky-primathon Verified this fix and it is working as expected.

2021-12-23 05:43 UTC, vicky-primathon commented
/ok-to-test sha=0dd11c2

2021-12-23 09:28 UTC, vicky-primathon commented
/ok-to-test sha=0fdbe65

2021-12-23 16:05 UTC, vicky-primathon commented
/ok-to-test sha=55a560b

2021-12-24 09:26 UTC, vicky-primathon commented
/ok-to-test sha=60d8d1e

2021-12-24 09:47 UTC, Aishwarya-U-R reviewed
Approving!

2021-12-27 19:52 UTC, vicky-primathon commented
/ok-to-test sha=60d8d1e

2021-12-27 20:31 UTC, vicky-primathon commented
/ok-to-test sha=1c3609f

2021-12-28 11:43 UTC, vicky-primathon commented
/ok-to-test sha=9210fe9

2021-12-28 12:07 UTC, Aishwarya-U-R reviewed
Approving!

2021-12-28 12:22 UTC, techbhavin approved these changes

2021-12-29 06:00 UTC, somangshu commented
@vicky-primathon please get a review here from the internal team

cc @sbalaji1192

2021-12-29 09:12 UTC, sbalaji1192 commented on app/client/src/widgets/DatePickerWidget2/widget/derived.js
> +      const isValid = moment(selectedDate).isBetween(minDate, maxDate);
+1 tolu's comment above

2021-12-29 09:12 UTC, sbalaji1192 commented on app/client/src/widgets/DatePickerWidget2/widget/derived.js
> +      const isValid = moment(selectedDate).isBetween(minDate, maxDate);
return moment(selectedDate).isBetween(minDate, maxDate);
no need to create a const.

2021-12-29 09:12 UTC, sbalaji1192 commented on app/client/src/widgets/DatePickerWidget2/widget/derived.js
> +      const isValid = moment(selectedDate).isBetween(minDate, maxDate);
Why are we making the min max validation dependent on the isRequired property?

2021-12-30 06:57 UTC, Tooluloope approved these changes

2021-12-30 06:58 UTC, Tooluloope commented
/ok-to-test sha=0a7eaab

2021-12-30 08:38 UTC, merged