Feat/custom domain settings
appsmithorg/appsmith pull request #9633
Opened 2021-12-08 05:55 UTC by nayan-rafiq

## Description
Custom domain should be configurable from admin settings UI

Fixes #9377

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
- Manually

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-12-08 05:58 UTC, sharat87 commented on app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/EnvManager.java
> +        APPSMITH_CUSTOM_DOMAIN
```suggestion
        APPSMITH_CUSTOM_DOMAIN,
```

2021-12-08 06:39 UTC, pranavkanade requested changes
one comment

2021-12-08 06:39 UTC, pranavkanade commented on app/client/src/pages/Settings/SettingsConfig.ts
> +  label: "Custom Domain",
can we please add validation here?

2021-12-08 06:39 UTC, pranavkanade commented on app/client/src/pages/Settings/SettingsConfig.ts
> +  label: "Custom Domain",
please add a placeholder as well

2021-12-08 07:39 UTC, sharat87 commented
Backend changes look ready to be merged.

2021-12-08 07:47 UTC, nayan-rafiq commented on app/client/src/pages/Settings/SettingsConfig.ts
> +  label: "Custom Domain",
@sbalaji1192 please check this

2021-12-09 05:40 UTC, sbalaji1192 commented on app/client/src/pages/Settings/SettingsConfig.ts
> +  label: "Custom Domain",
@pranavkanade Shri and I decided to not have validation. since it's really hard to validate a valid domain name.
regarding placeholder, I have added subtext.

2021-12-09 05:41 UTC, sbalaji1192 commented
/ok-to-test sha=a51fb7d

2021-12-09 05:43 UTC, pranavkanade approved these changes
LGTM

2021-12-09 06:58 UTC, sbalaji1192 commented
/ok-to-test sha=a51fb7d

2021-12-09 09:10 UTC, merged