fix: Regex to detect function args
appsmithorg/appsmith pull request #9634
Opened 2021-12-08 05:58 UTC by aswathkk

## Description

Regex was not working with whitespace characters since we are using `.*`
Replaced it with `[\s\S]*` to include whitespace characters as well.

Fixes #8169

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Tested this manually by providing whitespace characters into the argument fields of action selectors.
Planning to add a jest unit test for this fix. Facing some technical issues right now.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-12-08 06:14 UTC, aswathkk commented
/ok-to-test sha=f5b3fe7

2021-12-08 07:24 UTC, hetunandu requested changes

2021-12-08 07:24 UTC, hetunandu commented on app/client/src/components/editorComponents/ActionCreator/Fields.tsx
> +export const FUNC_ARGS_REGEX = /((["][^"]*["])|([\[][\s\S]*[\]])|([\{][\s\S]*[\}])|(['][^']*['])|([\(][\s\S]*[\)[=][>][{][\s\S]*[}])|([^'",][^,"+]*[^'",]*))*/gi;
Needs a test

2021-12-08 15:31 UTC, aswathkk commented
/ok-to-test sha=d85f92f

2021-12-09 04:42 UTC, aswathkk commented
/ok-to-test sha=d85f92f

2021-12-09 05:25 UTC, aswathkk commented
/ok-to-test sha=d85f92f

2021-12-09 06:07 UTC, aswathkk commented
/ok-to-test sha=7794d49

2021-12-09 06:10 UTC, hetunandu approved these changes

2021-12-09 10:22 UTC, aswathkk commented
/ok-to-test sha=7794d49

2021-12-09 12:45 UTC, aswathkk commented
/ok-to-test sha=7794d49

2021-12-13 09:15 UTC, aswathkk commented
/ok-to-test sha=9cd6736

2021-12-14 07:54 UTC, vivekverma2312 commented
@aswathkk Deploy preview is tested and working fine.

2021-12-14 07:57 UTC, hetunandu approved these changes

2021-12-14 07:58 UTC, merged