Feat: Support OAuth for all plugin types
appsmithorg/appsmith pull request #9657
Opened 2021-12-08 11:56 UTC by ohansFavour

## Description

Fixes

## Type of change

> Please delete options that are not relevant.

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Manual

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-12-08 12:34 UTC, ohansFavour commented
/ok-to-test sha=cdf328a

2021-12-12 18:50 UTC, ohansFavour commented
/ok-to-test sha=6d1d7ff

2021-12-12 19:55 UTC, ohansFavour commented
/ok-to-test sha=344336c

2021-12-20 11:54 UTC, ohansFavour commented
/ok-to-test sha=2fe15cd

2021-12-26 09:49 UTC, Irongade commented on app/client/src/pages/Editor/DataSourceEditor/DBForm.tsx
> +    const { datasource, formData, messages, pluginType } = this.props;
Can we add viewMode prop to this line as well?

2021-12-26 10:11 UTC, Irongade commented
can we add a short description of what this feature is about for more context?

2021-12-28 18:32 UTC, ayushpahwa requested changes
The code looks good. Please add some comments here for ease of understanding in the future.

2021-12-29 01:13 UTC, Irongade approved these changes

2022-01-02 23:14 UTC, ohansFavour commented
/ok-to-test sha=24b8c9c

2022-01-10 05:35 UTC, ohansFavour commented
/ok-to-test sha=bf5dfdd

2022-01-10 07:45 UTC, ohansFavour commented
/ok-to-test sha=53b66fe

2022-01-13 11:24 UTC, ohansFavour commented
/ok-to-test sha=7736c9f

2022-01-13 19:44 UTC, Irongade approved these changes

2022-01-13 19:47 UTC, ohansFavour commented
> The code looks good. Please add some comments here for ease of understanding in the future.

Done

2022-01-14 06:31 UTC, ayushpahwa approved these changes

2022-01-14 06:31 UTC, merged