Feature : Add support to send arbitrary form values to oAuth server during Datasource authentication
appsmithorg/appsmith pull request #9660
Opened 2021-12-08 12:57 UTC by leotom2000

## Description

> Add support to send arbitrary form values to oAuth server during Datasource authentication.

Fixes #9389

## Type of change

> New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Debugged during development and ensured that the Custom Client Parameters are sent to the back-end and is available as a property known as customTokenParameters of oAuth object 
- Also added those value as a property to the bodyInserters for the next level of processing.
- No unit tests implemented at this time
- To be tested with the specific client requirement which requested this feature that is not available at the time of this implementation.

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

2021-12-08 12:59 UTC, leotom2000 commented
/ok-to-test sha=f85e52a

2021-12-08 13:04 UTC, nidhi-nair commented on app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/connections/OAuth2ClientCredentials.java
> +            body.with(Authentication.CUSTOM_TOKEN_PARAMETER, StringUtils.collectionToDelimitedString(customProps,""));
This would not use our own definition of a key to stringify the token parameters. Please convert this into separate keys on the body.
```
oAuth2.getCustomTokenParameters().forEach(x -> body.with(x.getKey(), x.getValue());
```

2021-12-08 13:05 UTC, nidhi-nair commented on app/client/src/pages/Editor/DataSourceEditor/RestAPIDatasourceForm.tsx
> +            label="Custom Client Credentials"
Please call this `Custom Token Parameters`

2021-12-08 13:06 UTC, nidhi-nair requested changes
Please also attach a screenshot of how this looks on the UI for QA's reference.

2021-12-08 13:19 UTC, leotom2000 commented on app/client/src/pages/Editor/DataSourceEditor/RestAPIDatasourceForm.tsx
> +            label="Custom Client Credentials"
Changed

2021-12-08 16:40 UTC, leotom2000 commented on app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/connections/OAuth2ClientCredentials.java
> +            body.with(Authentication.CUSTOM_TOKEN_PARAMETER, StringUtils.collectionToDelimitedString(customProps,""));
resolved - StringUtils.collectionToDelimitedString is able to parse the  List<Property> and set it to body

2021-12-08 17:25 UTC, leotom2000 commented
The modified UI changes 

![Custom Token Parameters](https://user-images.githubusercontent.com/8027694/145254536-f72178e1-bfd8-47ec-8a77-b07d372fa0a2.png)

2021-12-08 17:27 UTC, leotom2000 commented
/ok-to-test sha=56028da

2021-12-09 04:02 UTC, nidhi-nair commented on app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/connections/OAuth2ClientCredentials.java
> +            body.with(Authentication.CUSTOM_TOKEN_PARAMETER, StringUtils.collectionToDelimitedString(oAuth2.getCustomTokenParameters(),""));
@leotom2000 You may have misunderstood what I said here. We cannot arbitrarily add our own value of `custom_token_parameter` here. We need to loop through all the user's values and add them as keys and values.

2021-12-09 05:04 UTC, nidhi-nair commented on app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/connections/OAuth2ClientCredentials.java
> +            body.with(Authentication.CUSTOM_TOKEN_PARAMETER, StringUtils.collectionToDelimitedString(oAuth2.getCustomTokenParameters(),""));
```
{
  "clientId": "abc",
  "clientSercret": "xyz",
  "key1": "value1",
  "key2": "value2"
}
```

2021-12-13 11:57 UTC, leotom2000 commented on app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/connections/OAuth2ClientCredentials.java
> +            body.with(Authentication.CUSTOM_TOKEN_PARAMETER, StringUtils.collectionToDelimitedString(oAuth2.getCustomTokenParameters(),""));
Yes got it, this is being resolved and code changes applied

2021-12-13 12:07 UTC, leotom2000 commented on app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/connections/OAuth2ClientCredentials.java
> +            body.with(Authentication.CUSTOM_TOKEN_PARAMETER, StringUtils.collectionToDelimitedString(oAuth2.getCustomTokenParameters(),""));
Here is the input in the UI page 
vs
the pairs set to body like another parameter like "scope'

![image](https://user-images.githubusercontent.com/8027694/145802661-0c84ccc5-1517-4985-9c20-1631c760868d.png)


![image](https://user-images.githubusercontent.com/8027694/145802312-685a6ec6-4fd9-4586-959c-85ec951ecfee.png)

2021-12-14 05:49 UTC, nidhi-nair commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/constants/Authentication.java
> +    public static final String CUSTOM_TOKEN_PARAMETER = "custom_token_parameter";
This is unnecessary now.

2021-12-14 05:51 UTC, nidhi-nair commented on app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/connections/OAuth2ClientCredentials.java
> +import com.appsmith.external.models.*;
We try to avoid importing complete folders and limit imports to specific files. This keeps our usage specific to the type we are using. Please convert this import to be type specific.

2021-12-14 05:51 UTC, nidhi-nair commented on app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/connections/OAuth2ClientCredentials.java
> +import java.util.HashSet;
Please check if these imports are redundant. In general, before committing code, please perform an autoformat to the files you have touched to take care of these rules.

2021-12-14 05:53 UTC, nidhi-nair requested changes
Some more clean up required on this PR

2021-12-14 06:39 UTC, leotom2000 commented on app/server/appsmith-interfaces/src/main/java/com/appsmith/external/constants/Authentication.java
> +    public static final String CUSTOM_TOKEN_PARAMETER = "custom_token_parameter";
updated

2021-12-14 06:41 UTC, leotom2000 commented on app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/connections/OAuth2ClientCredentials.java
> +import com.appsmith.external.models.*;
updated

2021-12-14 06:42 UTC, leotom2000 commented on app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/connections/OAuth2ClientCredentials.java
> +import java.util.HashSet;
resolved

2021-12-14 06:55 UTC, leotom2000 commented
/ok-to-test sha=4cdf9ee

2021-12-14 09:35 UTC, leotom2000 commented
> Please also attach a screenshot of how this looks on the UI for QA's reference.

Here is the input in the UI page 
vs
the pairs set to body like another parameter like "scope'

![image](https://user-images.githubusercontent.com/8027694/145802661-0c84ccc5-1517-4985-9c20-1631c760868d.png)


![image](https://user-images.githubusercontent.com/8027694/145802312-685a6ec6-4fd9-4586-959c-85ec951ecfee.png)

2021-12-14 11:18 UTC, nidhi-nair approved these changes

2021-12-17 04:56 UTC, nidhi-nair commented
/ok-to-test sha=4cdf9ee

2021-12-20 06:11 UTC, leotom2000 commented
/ok-to-test sha=789dcd2

2021-12-21 04:42 UTC, merged