feature: Theming
appsmithorg/appsmith pull request #9714
Opened 2021-12-13 04:56 UTC by jsartisan

Fixes #9404

2021-12-15 11:30 UTC, Rishabh-Rathod commented
Tried the DP, grouping feature seems to crash the application for some reason.

2021-12-15 13:16 UTC, jsartisan commented
> Tried the DP, grouping feature seems to crash the application for some reason. @jsartisan

Hey yes, pasting is failing on the DP right now. I have fixed it on my local. Will push a fix. Thanks for pointing it though :)

2022-01-10 06:00 UTC, jsartisan commented
/ok-to-test sha=26614d9

2022-01-10 08:44 UTC, jsartisan commented
/ok-to-test sha=38136ff

2022-01-11 07:46 UTC, jsartisan commented
/ok-to-test sha=8201d66

2022-01-12 05:42 UTC, jsartisan commented
/ok-to-test sha=453ecbf

2022-01-12 07:52 UTC, jsartisan commented
/ok-to-test sha=848619d

2022-01-18 10:07 UTC, keyurparalkar commented on app/client/src/entities/AppTheming/index.ts
> +  config: {
@jsartisan can you add a comment for the `config` section about its intention i.e. What's the purpose of it.

2022-01-18 10:07 UTC, keyurparalkar commented on app/client/src/entities/AppTheming/index.ts
> +  properties: {
@jsartisan can you add a comment for the `properties` section about its intention i.e. What's the purpose of it.

2022-01-18 11:27 UTC, YogeshJayaseelan commented
@jsartisan Tested the fix for issue #8393 and there is not space in the JS environment

2022-01-19 12:45 UTC, jsartisan commented
/ok-to-test sha=fb47e25

2022-01-20 05:47 UTC, keyurparalkar commented
/ok-to-test sha=8b572f9

2022-01-25 08:17 UTC, keyurparalkar commented
/ok-to-test sha=3cb1112

2022-01-25 09:47 UTC, keyurparalkar commented
/ok-to-test sha=3cb1112

2022-01-25 10:12 UTC, keyurparalkar commented
/ok-to-test sha=e7b09f5

2022-01-25 13:17 UTC, keyurparalkar commented
/ok-to-test sha=648f8fd

2022-01-26 08:19 UTC, keyurparalkar commented
/ok-to-test sha=6873cf3

2022-02-03 10:52 UTC, keyurparalkar commented
/ok-to-test sha=74b792b

2022-02-03 12:14 UTC, keyurparalkar commented
/ok-to-test sha=437c31a

2022-02-04 07:04 UTC, keyurparalkar commented
/ok-to-test sha=ad69704

2022-02-04 12:18 UTC, keyurparalkar commented
/ok-to-test sha=f40b7d2

2022-02-07 06:06 UTC, keyurparalkar commented
/ok-to-test sha=89e9139

2022-02-07 10:27 UTC, keyurparalkar commented
/ok-to-test sha=8557107

2022-02-07 10:55 UTC, keyurparalkar commented
/ok-to-test sha=d4bbde6

2022-02-07 11:26 UTC, keyurparalkar commented
/ok-to-test sha=b5c4765

2022-02-08 13:02 UTC, keyurparalkar commented
/ok-to-test sha=dc54293

2022-02-18 07:30 UTC, ashit-rath commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Binding/Bind_JSObject_Postgress_Table_spec.js
> +          .first()
Please add specific selector to revert `.first()` change

2022-02-18 07:30 UTC, ashit-rath commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/LayoutWidgets/Container_spec.js
> +      .type("#FFC13D");
Put magic numbers/texts in a constant to give the value some context.

2022-02-18 07:30 UTC, ashit-rath commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/LayoutWidgets/List_spec.js
> +    cy.testJsontext("background", "#FFC13D");
Double-check label name change for this proeprty

2022-02-18 07:30 UTC, ashit-rath commented on app/client/cypress/support/commands.js
> +  cy.get(`${widgetsPage.colorPickerV2Color}`)
`cy.get(widgetsPage.colorPickerV2Color)`

2022-02-18 07:30 UTC, ashit-rath commented on app/client/package.json
> +    "react-hook-form": "^7.24.2",
Remove `react-hook-form` and `yup`.

2022-02-18 07:30 UTC, ashit-rath commented on app/client/src/actions/appThemingActions.test.ts
> +import { ReduxActionTypes } from "constants/ReduxActionConstants";
IF this file is not required then please remove it.

2022-02-23 07:37 UTC, keyurparalkar commented on app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/LayoutWidgets/List_spec.js
> +    cy.testJsontext("background", "#FFC13D");
@ashit-rath sure, the label name is changed to `background`. PFB screenshot of the property class:
![Screenshot 2022-02-23 at 1 07 23 PM](https://user-images.githubusercontent.com/14138515/155277945-e3c0c6f0-314f-4c94-8c26-8d04a52b1f4b.png)

2022-02-23 09:06 UTC, arunvjn commented on app/client/src/entities/Replay/ReplayEntity/ReplayCanvas.ts
> +  /**
LGTM!

2022-02-23 09:53 UTC, keyurparalkar commented on app/client/src/actions/appThemingActions.test.ts
> +import { ReduxActionTypes } from "constants/ReduxActionConstants";
Removed this file, along with `ColorsPickerComponentV2.test.tsx` since the cases are handled by cypress test: `App_theming_spec.js`

2022-02-24 11:43 UTC, ashit-rath commented on app/client/src/pages/Editor/ThemePropertyPane/ThemeEditor.tsx
> +              <div className="py-0.5 px-1 text-xs font-semibold text-gray-700 uppercase border border-gray-700">
Move this to `editorComponents` and use it in `app/client/src/pages/Editor/ReflowBetaCard.tsx`

2022-02-24 11:43 UTC, ashit-rath commented on app/client/src/pages/Editor/ThemePropertyPane/ThemeEditor.tsx
> +                return (
Make this and the subsequent sections DRY

2022-02-24 11:43 UTC, ashit-rath commented on app/client/src/pages/Editor/ThemePropertyPane/ThemeList.tsx
> +          key={index}
Use theme `id` here

2022-02-24 11:43 UTC, ashit-rath commented on app/client/src/pages/Editor/ThemePropertyPane/ThemeList.tsx
> +function ThemeList(props: ThemeListProps) {
Can we remove this and use the loop directly to render the `ThemeCard` component.

2022-02-24 11:43 UTC, ashit-rath commented on app/client/src/pages/Editor/ThemePropertyPane/ThemeSelector.tsx
> +        <header className="relative px-3 py-3 space-y-3">
`header` -> `section`

2022-02-24 11:43 UTC, ashit-rath commented on app/client/src/pages/Editor/ThemePropertyPane/controls/ThemeFontControl.tsx
> +        renderOption={({ isSelectedNode, option }) => (
Move inline function out and make the return statement lean.

2022-02-24 11:43 UTC, ashit-rath commented on app/client/src/pages/Editor/ToggleModeButton.tsx
> +        <div className="relative">
Check if we need to revert this

2022-02-25 06:30 UTC, ashit-rath commented on app/client/src/utils/DSLMigrations.ts
> +export const migrateStylingPropertiesForTheming = (
Reminder: @jsartisan We need to go through this!

2022-02-25 06:30 UTC, ashit-rath commented on app/client/src/widgets/WidgetUtils.ts
> +export const lightenColor = (color = "#fff") => {
Can we have tests for these?

2022-02-25 06:30 UTC, ashit-rath commented on app/client/src/utils/helpers.tsx
> +export function extractColorsFromString(text: string) {
Let's add a jest test for this

2022-02-25 06:30 UTC, ashit-rath commented on app/client/src/widgets/BaseInputWidget/widget/index.tsx
> +          {
Question: @jsartisan When do we add the font family as a property to a widget? Like the Text widget now has the font family so what are the criteria to add this to any widget?

2022-02-28 06:22 UTC, ashit-rath requested changes

2022-02-28 06:22 UTC, ashit-rath commented on app/client/src/widgets/ImageWidget/widget/index.tsx
> +          {
I think we are repeating this config with `helpText` change everywhere. If tomorrow we need to change the validation or some other thing, we have to change it everywhere and there is a probability of inconsistency.

Let's create a property config utility file and put these there
something like
```js
export const borderRadiusPropertyConfig = (config: PropertyConfig = {})  => {
            propertyName: "borderRadius",
            label: "Border Radius",
            helpText:
              "Rounds the corners of the icon button's outer border edge",
            controlType: "BORDER_RADIUS_OPTIONS",
            isJSConvertible: true,
            isBindProperty: true,
            isTriggerProperty: false,
            validation: { type: ValidationTypes.TEXT },
           ...config,
}
export const boxShadowPropertyConfig = (config) => {
...
}
```

2022-02-28 06:22 UTC, ashit-rath commented on app/client/src/widgets/FormWidget/index.ts
> +                    fontSize: "1.25rem",
Magic number, use const/enum

2022-02-28 06:22 UTC, ashit-rath commented on app/client/src/widgets/FormButtonWidget/widget/index.tsx
> +
Remove new line

2022-02-28 06:22 UTC, ashit-rath commented on app/client/src/widgets/FilePickerWidgetV2/component/index.tsx
> +  }, [props.uppy, props.isDisabled]);
Remove `useCallback`

2022-02-28 06:22 UTC, ashit-rath commented on app/client/src/widgets/FilePickerWidgetV2/component/index.tsx
> +  }, [props.label, props.files]);
Remove `useMemo`

2022-02-28 06:22 UTC, ashit-rath commented on app/client/src/widgets/DropdownWidget/component/index.tsx
> +        &:hover { border: 1px solid ${Colors.GREY_5}; }
We are changing this `1.2px` `1px` at a lot of places, This is an indication that the code isn't DRY enough and would lead to inconsistency. This PR gives us a good opportunity to tackle these.

2022-02-28 06:22 UTC, ashit-rath commented on app/client/src/widgets/DropdownWidget/component/index.styled.tsx
> +    props.compactMode ? "&&& {margin-right: 0px;}" : "width: 100%;"}
Drop `px` from `0px`

2022-02-28 06:22 UTC, ashit-rath commented on app/client/src/widgets/CheckboxWidget/component/index.tsx
> +  }, [props.isChecked, props.onCheckChange]);
No `useCallback` is needed.

2022-02-28 06:22 UTC, ashit-rath commented on app/client/src/widgets/CheckboxWidget/component/index.tsx
> +import { Checkbox } from "components/wds";
Should we start using `wds`?

2022-03-01 10:11 UTC, ashit-rath commented on app/client/src/utils/DSLMigrations.ts
> -const addPrivateWidgetsToAllListWidgets = (
revert `export`

2022-03-01 10:11 UTC, ashit-rath commented on app/client/src/sagas/EvaluationsSaga.ts
>  import { updateMetaState } from "actions/metaActions";
Need FE Coders pod signoff for any such changes! @jsartisan @keyurparalkar

2022-03-01 10:11 UTC, ashit-rath commented on app/client/src/workers/evaluation.worker.ts
> -            replayMap[CANVAS] = new ReplayCanvas(widgets);
FE Coders signoff!

2022-03-01 12:23 UTC, keyurparalkar commented on app/client/src/widgets/WidgetUtils.ts
> +export const lightenColor = (color = "#fff") => {
Added test case for this inside the `WidgetUtils.test.ts`

2022-03-01 14:22 UTC, keyurparalkar commented on app/client/src/utils/helpers.tsx
> +export function extractColorsFromString(text: string) {
Added a test case in file `helper.test.ts`

2022-03-02 06:55 UTC, arunvjn commented on app/client/src/workers/evaluation.worker.ts
> -            replayMap[CANVAS] = new ReplayCanvas(widgets);
Changes on this file looks good.

2022-03-02 06:57 UTC, arunvjn reviewed
Changes around undo/redo looks good.

2022-03-03 05:23 UTC, YogeshJayaseelan commented
@jsartisan Tested issue #10052 and it is working as expected

2022-03-10 06:52 UTC, rahulramesha commented on app/client/src/widgets/ContainerWidget/component/index.tsx
> +  overflow: hidden;
@jsartisan , This overflow: hidden; is interfering with the IntersectionObserver API. That is causing the canvas to not render with wrong height. Removing this seems to fix the issue.

2022-03-28 02:56 UTC, sbalaji1192 commented on app/client/src/utils/DSLMigrations.ts
> +        const primaryColumn = child.primaryColumns[key];
call this `column`

2022-03-28 02:56 UTC, sbalaji1192 commented on app/client/src/utils/DSLMigrations.ts
> +        const derivedColumnCheck =
call this `isDerivedColumn`

2022-03-28 02:56 UTC, sbalaji1192 commented on app/client/src/utils/DSLMigrations.ts
> +      switch (child.textSize) {
This should be moved outside the enclosing if block

2022-03-28 02:56 UTC, sbalaji1192 commented on app/client/src/utils/DSLMigrations.ts
> +              child.derivedColumns[key].textSize = "0.75rem";
store `child.derivedColumns[key]` in variable

2022-03-28 13:49 UTC, ashit-rath commented
@keyurparalkar @jsartisan The theme config has a missing stylesheet config for `MULTI_SELECT_WIDGET_V2`.

2022-04-04 09:49 UTC, sbalaji1192 commented on app/client/src/widgets/WidgetUtils.ts
> +    return boxShadow.replace(
please use boxShadow.replace("rgba(0, 0, 0, 0.25)", boxShadowColor)

2022-04-04 09:49 UTC, sbalaji1192 commented on app/client/src/widgets/WidgetUtils.ts
> +
remove this line

2022-04-04 09:49 UTC, sbalaji1192 commented on app/client/src/widgets/TableWidget/widget/propertyUtils.ts
> +    const boxShadowColorPath = propertyPath.replace(
const  path = propertyPath.split(".")
path.pop()
const newPath = path.join(".")

2022-04-04 09:49 UTC, sbalaji1192 commented on app/client/src/widgets/TableWidget/widget/propertyUtils.ts
> +  if (has(props, propertyPath)) {
remove this condition

2022-04-04 09:49 UTC, sbalaji1192 commented on app/client/src/widgets/TableWidget/widget/propertyUtils.ts
> +export const boxShadowHook = (
Give it better name that states what it does

2022-04-04 09:49 UTC, sbalaji1192 commented on app/client/src/widgets/TableWidget/widget/index.tsx
> +                borderRadiusUtility(cellProperties.borderRadius) ||
conditionally call this

2022-04-04 09:49 UTC, sbalaji1192 commented on app/client/src/utils/DSLMigrations.ts
> +            if (!DATA_BIND_REGEX.test(column.boxShadowColor)) {
use `isDynamicValue` from `utils/DynamicBindingUtils.ts`

2022-04-04 09:49 UTC, sbalaji1192 commented on app/client/src/utils/DSLMigrations.ts
> +            if (!DATA_BIND_REGEX.test(column.boxShadowColor)) {
extract the boxShadowColor related conditions outside the switch cases.

2022-04-06 06:52 UTC, ashit-rath reviewed
@keyurparalkar Couple of tiny comments! The rest looks fine to me.

2022-04-06 06:52 UTC, ashit-rath commented on app/client/src/utils/DSLMigrations.ts
> +            set(schemaItem, "accentColor", Colors.GREEN);
Put values like `Colors.GREEN` / `"none"` / `"0px"` etc in a const like `DEFAULT_ACCENT_COLOR`, `DEFAULT_BORDER_RADIUS`.

2022-04-06 11:54 UTC, keyurparalkar commented on app/client/src/widgets/WidgetUtils.ts
> +    default:
@sbalaji1192 I have removed the default case from here.

2022-04-07 05:58 UTC, ashit-rath commented on app/client/src/utils/DSLMigrations.ts
> +        child.fontSize = "0.75rem";
Do we have a mapping of these values? (0.75rem, 0.875rem) If so use that mapping instead of actual values as having it like this may cause mistyping

2022-04-07 05:58 UTC, ashit-rath commented on app/client/src/utils/DSLMigrations.ts
> +    switch (child.labelTextSize) {
This logic for migrating text size is being repeated in other places with a slight twist.
Can we create a helper function to migrate text size

```js
function migrateTextSize(propertyName: string, child: WidgetProps, propertyPath?: string) {
 // if propertyPath is present, use that in dynamic trigger path list else use the `propertyName`
 // rest of the code switch code
  ...
  ...
}
```

2022-04-07 05:58 UTC, ashit-rath commented on app/client/src/utils/DSLMigrations.ts
> +      child.backgroundColor = Colors.GREEN;
Is it still `backgroundColor`? or are you waiting for the new theme config to be up on release to make this change?

2022-04-07 05:58 UTC, ashit-rath commented on app/client/src/utils/DSLMigrations.ts
> +    "MULTI_SELECT_WIDGET_V2",
What about multiselect v1? they don't have primary color?

2022-04-07 10:17 UTC, keyurparalkar commented on app/client/src/utils/DSLMigrations.ts
> +            set(schemaItem, "accentColor", Colors.GREEN);
Replaced all the string values with constants. Except for the Colors.GREEN since it is already one of the constants.

2022-04-07 10:17 UTC, keyurparalkar commented on app/client/src/utils/DSLMigrations.ts
> +    switch (child.labelTextSize) {
As discussed, not required right now therefore resolving this comment

2022-04-08 06:30 UTC, ashit-rath commented on app/client/src/widgets/PhoneInputWidget/component/ISDCodeDropdown.tsx
> +  margin-right: 0.625rem;
At some places, we are using px and some rem. Can we use standard `px` to avoid confusion?

2022-04-08 06:30 UTC, ashit-rath commented on app/client/src/widgets/SingleSelectTreeWidget/component/index.tsx
> +  const id = widgetId;
Please address this comment

2022-04-08 06:30 UTC, ashit-rath commented on app/client/src/widgets/StatboxWidget/index.ts
> +                    fontSize: "1.5rem",
Please address this comment

2022-04-08 06:30 UTC, ashit-rath commented on app/client/src/widgets/TableWidget/component/CascadeFields.tsx
> +            accentColor="blue"
Should this be hard-coded?

2022-04-08 06:30 UTC, ashit-rath commented on app/client/src/widgets/TableWidget/component/TableUtilities.tsx
> +
Can we remove this commented out code?

2022-04-08 06:30 UTC, ashit-rath commented on app/client/src/widgets/constants.ts
> +};
Why do we have these here?

2022-04-11 05:41 UTC, ashit-rath reviewed
@keyurparalkar

2022-04-11 05:41 UTC, ashit-rath commented on app/client/src/widgets/WidgetUtils.test.ts
> +const tableWidgetProps = {
You can provide a trimmed down version of this table widget props. As we are using this object for utility function testing, it cannot be targetted to a single widget. So have only those parts that are required by the utility functions testing like `dynamicBIndingPathList`

2022-04-11 05:41 UTC, ashit-rath commented on app/client/src/widgets/WidgetUtils.test.ts
> +      tableWidgetProps.primaryColumns.action.boxShadow,
These are generic functions so don't pull from the tableWidgetProps but rather provide from a const. Think of it like independent testing.

2022-04-11 06:38 UTC, ashit-rath commented on app/client/src/widgets/TableWidget/widget/index.tsx
> +                  : cellProperties.boxShadow,
We are repeating this twice.

2022-04-11 06:38 UTC, ashit-rath commented on app/client/src/widgets/WidgetUtils.ts
> +  child: WidgetProps,
Any particular reason to pass the whole widget props rather than the `dynamicBindingPathList` as we are not using anything else from the props?

2022-04-11 06:38 UTC, ashit-rath commented on app/client/src/widgets/WidgetUtils.ts
> +    (value: { key: string }) => boxShadowRegex.test(value.key),
Do we need to add  `: { key: string }` typing? I am guessing there would be auto-typing from typescript

2022-04-12 18:12 UTC, sbalaji1192 commented on app/client/src/utils/migrations/ThemingMigrations.ts
> +    switch (child.boxShadow) {
is there a widget which has either boxShadow or boxShadowColor as a  dynamic value?

2022-04-12 18:12 UTC, sbalaji1192 commented on app/client/src/utils/migrations/ThemingMigrations.ts
> +     * Migrates the textSize property present at the table level.
the comment says it migrates at table level, but this will be run for all widgets.

2022-04-12 18:12 UTC, sbalaji1192 commented on app/client/src/utils/migrations/ThemingMigrations.ts
> +    if (child.hasOwnProperty("primaryColumns")) {
can check type of the child

2022-04-12 18:12 UTC, sbalaji1192 commented on app/client/src/utils/migrations/ThemingMigrations.ts
> +        const newBoxShadowColor =
might need to use the migration version in the constant name `rgbaMigrationConstantV56`

2022-04-12 18:12 UTC, sbalaji1192 commented on app/client/src/utils/migrations/ThemingMigrations.ts
> +      if (has(child, "schema")) {
need to check the widget type

2022-04-12 18:12 UTC, sbalaji1192 commented on app/client/src/utils/migrations/ThemingMigrations.ts
> +      const resultantElement = (child.dynamicBindingPathList || []).find(
we're introducing this new property , right ? Then we don;t need this check,

2022-04-12 18:12 UTC, sbalaji1192 commented on app/client/src/utils/migrations/ThemingMigrations.ts
> +  const resultantDynamicProp = (child.dynamicPropertyPathList || []).find(
use isPropertyPathPresent

2022-04-13 05:26 UTC, keyurparalkar commented on app/client/src/utils/DSLMigrations.ts
> +  if (currentDSL.version === 56) {
@sbalaji1192 New migrations got introduced in the release recently. But at this time the release branch was not merged into this PR due to merged conflicts therefore to make it work locally I needed to version 56. You can find latest changes to this line over here: https://github.com/appsmithorg/appsmith/blob/2d811c84b4f70f1ba608ac2634359b79c6ce2f9f/app/client/src/utils/DSLMigrations.ts#L1086

2022-04-13 05:28 UTC, keyurparalkar commented on app/client/src/utils/migrations/ThemingMigrations.ts
> +    switch (child.boxShadow) {
@sbalaji1192 yes table widget's Icon button has boxShadow and boxShadowColor has JS toggle so they have dynamic values

2022-04-13 07:11 UTC, keyurparalkar commented on app/client/src/utils/migrations/ThemingMigrations.ts
> +      if (has(child, "schema")) {
@sbalaji1192 the widget type check is already applied at line here:
https://github.com/appsmithorg/appsmith/blob/754a258b00de34a67765ee1fb9aa6fd1c1c58245/app/client/src/utils/migrations/ThemingMigrations.ts#L304

2022-04-13 07:14 UTC, keyurparalkar commented on app/client/src/widgets/WidgetUtils.ts
> +export const boxShadowUtility = (boxShadow: string, boxShadowColor: string) => {
Yes, the tests are added for this

2022-04-19 09:56 UTC, jsartisan commented
/ok-to-test sha=700af88

2022-04-19 10:04 UTC, jsartisan commented
/ok-to-test sha=700af88

2022-04-19 11:00 UTC, nidhi-nair commented
/ok-to-test sha=700af88

2022-04-19 11:05 UTC, keyurparalkar commented on app/client/src/widgets/AudioRecorderWidget/widget/index.tsx
> +            propertyName: "accentColor",
@ashit-rath yes we have migration for this in place.

2022-04-19 11:08 UTC, keyurparalkar commented on app/client/src/widgets/constants.ts
> +};
@ashit-rath this has been added into this file so that It can be later used in the theming migration.

2022-04-19 11:11 UTC, keyurparalkar commented on app/client/src/widgets/WidgetUtils.ts
> +  child: WidgetProps,
@ashit-rath earlier thought to use other properties of the widget in the logic, that is why I kept all the widgetProps.

2022-04-19 11:12 UTC, keyurparalkar commented on app/client/src/widgets/WidgetUtils.ts
> +    (value: { key: string }) => boxShadowRegex.test(value.key),
@ashit-rath I have removed these typings

2022-04-19 11:53 UTC, jsartisan commented
/ok-to-test sha=700af88

2022-04-20 10:46 UTC, keyurparalkar commented on app/client/src/widgets/WidgetUtils.test.ts
> +const tableWidgetProps = {
@ashit-rath I have trimmed this tableWidgetProps down to minimum.

2022-04-20 10:53 UTC, keyurparalkar commented on app/client/src/widgets/WidgetUtils.test.ts
> +      tableWidgetProps.primaryColumns.action.boxShadow,
@ashit-rath I am using the same properties because I am modifying it based on the different scenarios.

2022-04-21 11:55 UTC, jsartisan commented
/ok-to-test sha=3806dd2

2022-04-22 05:47 UTC, jsartisan commented
/ok-to-test sha=f08575f

2022-04-22 05:50 UTC, jsartisan commented
/ok-to-test sha=f08575f

2022-04-22 11:49 UTC, jsartisan commented
/ok-to-test sha=d751d70

2022-04-22 14:25 UTC, jsartisan commented
/ok-to-test sha=86e2c4e

2022-04-22 14:26 UTC, jsartisan commented
/ok-to-test sha=86e2c4e

2022-04-23 14:25 UTC, Aishwarya-U-R commented
/ok-to-test sha=cbbb3d8

2022-04-23 14:53 UTC, Aishwarya-U-R commented
/ok-to-test sha=cbbb3d8

2022-04-23 16:41 UTC, jsartisan commented
/ok-to-test sha=cbbb3d8

2022-04-25 05:24 UTC, jsartisan commented
/ok-to-test sha=0bf6d65

2022-04-25 08:27 UTC, jsartisan commented
/ok-to-test sha=8fd72cc

2022-04-25 10:55 UTC, jsartisan commented
/ok-to-test sha=053cc63

2022-04-25 13:43 UTC, jsartisan commented
/ok-to-test sha=2a94bca

2022-04-25 15:23 UTC, jsartisan commented
/ok-to-test sha=9140fd8

2022-04-26 04:49 UTC, jsartisan commented
/ok-to-test sha=166c7f9

2022-04-26 06:00 UTC, jsartisan commented
/ok-to-test sha=166c7f9

2022-04-26 12:53 UTC, jsartisan commented
/ok-to-test sha=ef53da9

2022-04-26 14:20 UTC, jsartisan commented
/ok-to-test sha=8cb900

2022-04-26 15:10 UTC, jsartisan commented
/ok-to-test sha=8cb900

2022-04-26 17:00 UTC, jsartisan commented
/ok-to-test sha=7c522e0

2022-04-27 11:54 UTC, jsartisan commented
/ok-to-test sha=21de8db

2022-04-28 06:56 UTC, jsartisan commented
/ok-to-test sha=11708ee

2022-04-29 07:40 UTC, jsartisan commented
/ok-to-test sha=53bdba2

2022-05-01 05:00 UTC, jsartisan commented
/ok-to-test sha=d9db1fd

2022-05-01 08:19 UTC, jsartisan commented
/ok-to-test sha=f7cc243

2022-05-01 11:53 UTC, jsartisan commented
/ok-to-test sha=f6b10ee

2022-05-01 13:26 UTC, jsartisan commented
/ok-to-test sha=da09453

2022-05-02 05:59 UTC, jsartisan commented
/ok-to-test sha=789eab5

2022-05-02 10:08 UTC, keyurparalkar commented on app/client/src/widgets/WidgetUtils.ts
> +  child: WidgetProps,
@ashit-rath done the above mentioned changes. Now, the above function will only recevie `dynamicBindingPathList` as argument.

2022-05-02 10:20 UTC, jsartisan commented
/ok-to-test sha=493891e

2022-05-02 10:20 UTC, jsartisan commented
/ok-to-test sha=493891e

2022-05-02 11:38 UTC, keyurparalkar commented on app/client/src/components/ads/ColorPickerComponentV2.tsx
> +  const handleKeydown = (e: KeyboardEvent) => {
Resolving it as it was pushed from another PR.

2022-05-02 11:40 UTC, keyurparalkar commented on app/client/src/components/ads/ColorPickerComponentV2.tsx
> +    debouncedOnChange(value);
We need the debounce because we use this function inside an input which calls it at every keypress event.

2022-05-02 11:47 UTC, keyurparalkar commented on app/client/src/pages/AppViewer/AppViewerPageContainer.tsx
> +  }, [pageId, location.pathname]);
We were doing this previously when this component was class based as well. This is done so to maintain the condition which was present in the class based component. Also we are keeping the consistency so that the component does not break.

2022-05-02 11:49 UTC, keyurparalkar commented on app/client/src/pages/AppViewer/AppViewerPageContainer.tsx
> +  }, [currentApplication?.userPermissions]);
To maintain the same logic therefore, code along with it's condition is kept as is.

2022-05-03 06:12 UTC, jsartisan commented
/ok-to-test sha=0722364

2022-05-03 07:19 UTC, jsartisan commented
/ok-to-test sha=7142075

2022-05-03 10:09 UTC, jsartisan commented
/ok-to-test sha=41e53a7

2022-05-03 12:05 UTC, ashit-rath submitted a review, later dismissed

2022-05-03 14:21 UTC, jsartisan commented
/ok-to-test sha=ed2099b

2022-05-03 16:27 UTC, jsartisan commented
/ok-to-test sha=ed2099b

2022-05-03 16:28 UTC, jsartisan commented
/ok-to-test sha=ed2099b

2022-05-04 09:23 UTC, somangshu approved these changes

2022-05-04 09:44 UTC, somangshu approved these changes

2022-05-04 09:45 UTC, merged