Fix/8924 gs plugin error on empty row data6
appsmithorg/appsmith pull request #9725
Opened 2021-12-13 09:54 UTC by leotom2000

## Description

> When executing a Google sheets Bulk insert rows query, an error is returned if the data array is empty.

Fixes #8924

## Type of change
- Bug fix (non-breaking change which fixes an issue)   

## How Has This Been Tested?
> Tested manually with different inputs of empty data
> JUnit Test implemented
 
## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

2021-12-13 10:05 UTC, leotom2000 commented
/ok-to-test sha=a99d90f

2021-12-14 05:57 UTC, nidhi-nair commented on app/server/appsmith-plugins/googleSheetsPlugin/src/test/java/com/external/config/BulkAppendMethodTest.java
> +    public void testBulkAppendHandleNonEmptyMonoExecutePrerequisites() {
We can get rid of this test. Here we seem to be testing for assertion error, which is so generic in nature that every failure would cause this test to pass. The other tests that test for behaviour automatically ake care of this scenario.

2021-12-14 05:58 UTC, nidhi-nair requested changes

2021-12-14 05:58 UTC, nidhi-nair commented on app/server/appsmith-plugins/googleSheetsPlugin/src/test/java/com/external/config/BulkAppendMethodTest.java
> +        DBAuth authDTO = new DBAuth();
Please use the correct type here, since this is specifically meant for OAuth2

2021-12-14 09:10 UTC, leotom2000 commented on app/server/appsmith-plugins/googleSheetsPlugin/src/test/java/com/external/config/BulkAppendMethodTest.java
> +    public void testBulkAppendHandleNonEmptyMonoExecutePrerequisites() {
removed

2021-12-14 09:11 UTC, leotom2000 commented on app/server/appsmith-plugins/googleSheetsPlugin/src/test/java/com/external/config/BulkAppendMethodTest.java
> +        DBAuth authDTO = new DBAuth();
fixed this, by removing DBAuth related items

2021-12-14 09:25 UTC, leotom2000 commented
/ok-to-test sha=263f7f4

2021-12-14 11:14 UTC, nidhi-nair approved these changes

2021-12-17 04:43 UTC, merged