feat: Feat/uqi sorting component
appsmithorg/appsmith pull request #9775
Opened 2021-12-14 22:29 UTC by Irongade

This adds a Sorting Form Control component in accordance with the new UQI Format.

Fixes #9655

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

Manual Tests.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-12-14 22:33 UTC, Irongade commented
/ok-to-test sha=c8fc3db

2021-12-14 22:33 UTC, Irongade commented
/ok-to-test sha=27aa2a1

2021-12-15 06:17 UTC, Irongade commented
/ok-to-test sha=a4378ce

2021-12-16 04:57 UTC, ayushpahwa requested changes

2021-12-16 04:57 UTC, ayushpahwa commented on app/client/public/sample-jsons/mongo-dependency.json
> +{
This file is not needed, please remove this.

2021-12-16 04:57 UTC, ayushpahwa commented on app/client/public/sample-jsons/mongo-editor.json
> +{
This file is not needed, please remove this.

2021-12-16 04:57 UTC, ayushpahwa commented on app/client/public/sample-jsons/mongo-settings.json
> +{
This file is not needed, please remove this.

2021-12-16 04:57 UTC, ayushpahwa commented on app/client/src/components/designSystems/appsmith/Dropdown.tsx
> +  const { customSelectStyles, input, placeholder } = props;
Why is placeholder needed for dropdown? Just set a default value here.

2021-12-16 04:57 UTC, ayushpahwa commented on app/client/src/components/formControls/SortingControl.tsx
> +                  // initialValue: props.comparisonTypes[0].value,
Please remove unused comments.

2021-12-16 04:57 UTC, ayushpahwa commented on app/client/src/components/formControls/SortingControl.tsx
> +            order: "Ascending",
Please use enums here instead of strings

2021-12-16 04:57 UTC, ayushpahwa commented on app/client/src/workers/ReplayDSL.test.js
> +import ReplayDSL from "./ReplayDSL";
This file is not needed, please remove this.

2021-12-16 04:57 UTC, ayushpahwa commented on app/client/src/workers/ReplayDSL.ts
> +import { Doc, Map, UndoManager } from "yjs";
This file is not needed, please remove this.

2021-12-16 04:57 UTC, ayushpahwa commented on app/client/src/workers/replayUtils.test.js
> +import { processDiff, TOASTS, FOCUSES, UPDATES, WIDGETS } from "./replayUtils";
This file is not needed, please remove this.

2021-12-16 04:57 UTC, ayushpahwa commented on app/client/src/workers/replayUtils.ts
> +import { get, set } from "lodash";
This file is not needed, please remove this.

2021-12-16 06:24 UTC, Irongade commented on app/client/src/components/designSystems/appsmith/Dropdown.tsx
> +  const { customSelectStyles, input, placeholder } = props;
1) the design specified a placeholder, 2) I suspect the Sorting's Column dropdown won't have any default values but rather dynmaic triggers.

2021-12-16 06:56 UTC, Irongade commented
/ok-to-test sha=c17e96d

2022-01-05 06:10 UTC, ayushpahwa approved these changes

2022-01-05 13:52 UTC, Irongade commented
/ok-to-test sha=d904707

2022-01-05 17:35 UTC, ayushpahwa approved these changes

2022-01-05 17:35 UTC, ayushpahwa commented on app/client/src/components/designSystems/appsmith/Dropdown.tsx
> +  const { customSelectStyles, input, placeholder } = props;
Let's keep triggers as V2 for sorting component. For now, let's use the text field for the same.

2022-01-05 17:36 UTC, ayushpahwa commented
/ok-to-test sha=d904707

2022-01-05 18:59 UTC, merged