feat: Entity explorer revamp
appsmithorg/appsmith pull request #9811
Opened 2021-12-15 22:21 UTC by albinAppsmith

## Description

 Revamped UI and entity arrangements

Fixes #9689, #9671, #9672, #9688

## Type of change

- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?

- Tested locally

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-12-16 05:28 UTC, arunvjn approved these changes
Approving for tests

2021-12-16 06:35 UTC, arunvjn approved these changes

2021-12-16 06:36 UTC, arunvjn commented
/ok-to-test sha=68c43f1

2021-12-17 13:18 UTC, arunvjn submitted a review, later dismissed

2021-12-20 08:16 UTC, akash-codemonk requested changes
https://user-images.githubusercontent.com/67054171/146734466-b4b565e9-7da2-4b82-a4fb-ff7fcd8b233a.mov

Could be some memoization issue.

2021-12-20 08:25 UTC, arunvjn commented
> ds-name.mov
> 
> Could be some memoization issue.

Nice catch. Fixed this bug

2021-12-23 09:39 UTC, arunvjn approved these changes
Approving for tests

2021-12-26 04:48 UTC, arunvjn approved these changes

2021-12-26 04:48 UTC, arunvjn commented
/ok-to-test sha=b21d360

2021-12-26 04:52 UTC, arunvjn commented
/ok-to-test sha=de26190

2021-12-27 05:57 UTC, SatishGandham commented
@arunvjn Did you check the re-renders of the name component?

2021-12-27 06:18 UTC, arunvjn commented
> @arunvjn Did you check the re-renders of the name component?

@SatishGandham There are multiple selectors looking for existing entity names, which are the cause of re-renders. Eg. 
_getExistingActionNames_ will re-render anytime the actions array in state changes. This is because anytime we update an aciton we get a new reference to the actions array in the state. We can work around this by maintaining a list of used entity names in the state and updating it only when a rename or new entity gets added.

2021-12-28 12:06 UTC, SatishGandham commented
@arunvjn 
If something is rendering when it doesn't have to we have to fix it. We can prioritise which gets fixed first after running a profile. 
Entity explorer should not re-render every-time the state changes (which very frequent). This will impact the editing experience.

Regarding `existingActionNames` selector, it is only used to check if something is a valid name and not used in render. In such cases, we can directly access the store so that we don't trigger a render.

2021-12-29 05:23 UTC, Parthvi12 commented
/ok-to-test sha=0ff3462

2021-12-31 05:28 UTC, arunvjn approved these changes
Rerun tests

2021-12-31 05:28 UTC, arunvjn commented
/ok-to-test sha=ea4340b

2022-01-04 06:26 UTC, arunvjn approved these changes
Rerun tests

2022-01-04 06:27 UTC, arunvjn commented
/ok-to-test sha=fd73807

2022-01-04 08:29 UTC, SatishGandham commented
/ok-to-test sha=fd73807

2022-01-07 04:50 UTC, arunvjn approved these changes
Rerun tests

2022-01-07 04:51 UTC, albinAppsmith commented
/ok-to-test sha=532c401

2022-01-09 03:52 UTC, arunvjn approved these changes
Tests rerun

2022-01-09 03:53 UTC, arunvjn commented
/ok-to-test sha=9c1e577

2022-01-10 08:39 UTC, arunvjn approved these changes
Rerun tests

2022-01-10 08:40 UTC, arunvjn commented
/ok-to-test sha=416b78a

2022-01-10 17:34 UTC, NandanAnantharamu commented
/ok-to-test sha=d345537

2022-01-10 18:29 UTC, NandanAnantharamu commented
/ok-to-test sha=09e47b4

2022-01-11 16:27 UTC, NandanAnantharamu commented
/ok-to-test sha=240c1c4

2022-01-11 17:26 UTC, NandanAnantharamu commented
/ok-to-test sha=1224fc4

2022-01-11 18:23 UTC, NandanAnantharamu commented
/ok-to-test sha=1224fc4

2022-01-12 03:11 UTC, NandanAnantharamu commented
/ok-to-test sha=6411b30

2022-01-12 03:11 UTC, NandanAnantharamu commented
/ok-to-test sha=6411b30

2022-01-12 06:34 UTC, NandanAnantharamu commented
/ok-to-test sha=832d506

2022-01-12 11:51 UTC, albinAppsmith commented
/ok-to-test sha=b36b806

2022-01-12 18:11 UTC, NandanAnantharamu commented
/ok-to-test sha=1fac08c

2022-01-13 10:00 UTC, arunvjn commented
/ok-to-test sha=ee3b95d

2022-01-13 17:01 UTC, arunvjn commented
/ok-to-test sha=7ad5328

2022-01-13 20:56 UTC, albinAppsmith commented
/ok-to-test sha=dcbfbb7

2022-01-14 07:00 UTC, arunvjn commented
/ok-to-test sha=f444467

2022-01-14 08:13 UTC, albinAppsmith commented
/ok-to-test sha=69e3698

2022-01-17 09:34 UTC, albinAppsmith commented
/ok-to-test sha=6e8afea

2022-01-17 14:40 UTC, arunvjn commented
/ok-to-test sha=beb72a7

2022-01-17 16:29 UTC, arunvjn commented
/ok-to-test sha=ad5536f

2022-01-17 18:54 UTC, arunvjn commented
/ok-to-test sha=03eea96

2022-01-17 20:58 UTC, albinAppsmith commented
/ok-to-test sha=10572c6

2022-01-18 03:16 UTC, arunvjn commented
/ok-to-test sha=72e9520

2022-01-18 06:24 UTC, arunvjn commented
/ok-to-test sha=b4542a1

2022-01-18 19:09 UTC, albinAppsmith commented
/ok-to-test sha=186b0fb

2022-01-19 03:39 UTC, arunvjn commented
/ok-to-test sha = 66725ec

2022-01-19 05:48 UTC, albinAppsmith commented
/ok-to-test sha=2b509be

2022-01-19 06:44 UTC, albinAppsmith commented
/ok-to-test sha=968cced

2022-01-19 10:31 UTC, albinAppsmith commented
/ok-to-test sha=0a16a05

2022-01-19 14:56 UTC, albinAppsmith commented
/ok-to-tes sha=7ed7189

2022-01-19 14:56 UTC, albinAppsmith commented
/ok-to-test sha=7ed7189

2022-01-20 07:23 UTC, Aishwarya-U-R commented
/ok-to-test sha=98d6b3e

2022-01-20 10:41 UTC, Aishwarya-U-R commented
/ok-to-test sha=34228c0

2022-01-20 10:53 UTC, Aishwarya-U-R commented
/ok-to-test sha=ef5918c

2022-01-20 11:51 UTC, Aishwarya-U-R commented
/ok-to-test sha=74b42c7

2022-01-20 11:55 UTC, Aishwarya-U-R commented
/ok-to-test sha=54e9ca1

2022-01-20 13:45 UTC, Aishwarya-U-R commented
/ok-to-test sha=a8b936b

2022-01-21 05:00 UTC, arunvjn commented
/ok-to-test sha=a8b936b

2022-01-24 05:41 UTC, arunvjn commented
/ok-to-test sha=f52e6bf

2022-01-24 09:14 UTC, arunvjn commented
/ok-to-test sha=315a275

2022-01-24 17:56 UTC, arunvjn commented
/ok-to-test sha=3875850

2022-01-25 03:48 UTC, arunvjn commented
/ok-to-test sha=3875850

2022-01-25 10:47 UTC, arunvjn commented
/ok-to-test sha=7f46310

2022-01-26 04:53 UTC, arunvjn commented
/ok-to-test sha=15ab573

2022-01-26 06:04 UTC, arunvjn commented
/ok-to-test sha=c047be2

2022-01-28 04:39 UTC, arunvjn commented
/ok-to-test sha=f857a40

2022-01-28 06:43 UTC, arunvjn commented
/ok-to-test sha=c991efb

2022-01-28 08:09 UTC, akash-codemonk requested changes

2022-01-28 08:09 UTC, akash-codemonk commented on app/client/src/pages/Editor/Explorer/JSActions/JSActionContextMenu.tsx
> +          label: "Show Bindings",
Can we move this static string to constants/messages.

2022-01-28 08:09 UTC, akash-codemonk commented on app/client/src/pages/Editor/Explorer/Widgets/WidgetEntity.tsx
> +// import { getCurrentPageId } from "selectors/editorSelectors";
Can we remove these commented out imports?

2022-01-28 08:55 UTC, akash-codemonk approved these changes

2022-01-28 09:04 UTC, arunvjn commented
/ok-to-test sha=ea07fdb

2022-01-28 10:48 UTC, arunvjn commented
/ok-to-test sha=89d9227

2022-01-28 11:31 UTC, arunvjn commented
/ok-to-test sha=36ad8fa

2022-01-28 14:32 UTC, arunvjn commented
/ok-to-test sha=c3f5262

2022-01-29 03:22 UTC, arunvjn commented
/ok-to-test sha=c3f5262

2022-01-29 04:34 UTC, arunvjn commented
/ok-to-test sha=c3f5262

2022-01-29 05:48 UTC, arunvjn commented
/ok-to-test sha=c3f5262

2022-01-29 07:26 UTC, merged