Adding Template request file
appsmithorg/appsmith pull request #9897
Opened 2021-12-21 06:10 UTC by kocharrahul7

> Pull Request Template
>
> 

## Description

>Adding in an issue template for Template requests. This is just to allow a user to request a template is created

Fixes # (issue)

## Type of change

> Please delete options that are not relevant.

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Checked the file on another directory

## Checklist:

- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-12-21 07:00 UTC, mohanarpit commented on .github/ISSUE_TEMPLATE/Templates.yaml
> +description: Request a template you would like us to make
Minor: can we call them app templates? Or something slightly more descriptive. I read the whole text but it wasn't very clear to me that we were talking about app templates till much later.

2021-12-21 13:57 UTC, Nikhil-Nandagopal requested changes

2021-12-21 13:57 UTC, Nikhil-Nandagopal commented on .github/ISSUE_TEMPLATE/Templates.yaml
> +description: Request a template you would like us to make
+1 App template makes sense

2021-12-21 13:57 UTC, Nikhil-Nandagopal commented on .github/ISSUE_TEMPLATE/Templates.yaml
> +    label: Wireframes
I think a single line input is enough for title & wireframes

2021-12-21 13:57 UTC, Nikhil-Nandagopal commented on .github/ISSUE_TEMPLATE/Templates.yaml
> +    value: |
We should have separate dropdowns/inputs for 
- Widgets used
- Use case
- Industry
- Data sources used

2021-12-22 05:36 UTC, kocharrahul7 reviewed
Made all the requested changes

2021-12-22 05:36 UTC, kocharrahul7 commented on .github/ISSUE_TEMPLATE/Templates.yaml
> +    label: Wireframes
Made all the requested changes

2021-12-30 06:06 UTC, Nikhil-Nandagopal requested changes

2021-12-30 06:06 UTC, Nikhil-Nandagopal commented on .github/ISSUE_TEMPLATE/Templates.yaml
> +    description: Name your templte, and make sure it is descriptive, so we make what you need
@kocharrahul7 there's a typo in template here

2021-12-30 06:25 UTC, merged