feat: Add analytics for BE git events
appsmithorg/appsmith pull request #9899
Opened 2021-12-21 07:02 UTC by AnaghHegde

## Description

> Analytics events for git flows BE. 

Fixes # (issue)

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-12-21 07:05 UTC, AnaghHegde commented
@vuiets Do we need analytics event for checkout branch as well ?

2021-12-21 07:48 UTC, abhvsn requested changes
I can see some repetitive code here. Can we have a separate function for analytics event. Also, why are we not sending orgIds in all the events, this way we might be able to collect more info and don't see any harm in doing so?

2021-12-21 09:33 UTC, AnaghHegde commented
@abhvsn I will refactor the code for analytics creation part. Before that i need @vuiets approval on if more data points are needed.

2021-12-21 12:43 UTC, AnaghHegde commented
/ok-to-test sha=6d046c4

2021-12-22 11:39 UTC, AnaghHegde commented
/ok-to-test sha=4406b38

2021-12-23 04:33 UTC, AnaghHegde commented
/ok-to-test sha=1f66456

2021-12-23 05:14 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java
> +                .flatMap(application -> addAnalyticsForGitOperation(
`responseUtils.updateApplicationWithDefaultResources(application)` this will update the application object. Can we send the analytics event just before this method, otherwise `application.getId()` might be incorrect for `branchedApplication`

2021-12-23 05:15 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java
> +                .flatMap(application -> addAnalyticsForGitOperation(
Yeah since it updates the `id` i thought the analytics function should have the correct id.

2021-12-23 05:19 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java
> +                            AnalyticsEvents.GIT_PRUNE.getEventName(),
Is this just pruning the branch or synching with the remote? Asking this because we also update the defaultBranch with this call.

2021-12-23 05:26 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java
> +                            AnalyticsEvents.GIT_PRUNE.getEventName(),
We are doing both, before the prune operation we are also updating the defaultBranch in db.

2021-12-24 07:48 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java
> +                        application.getId(),
As I said earlier `application.getId()` and `defaultApplicationId` will be same here

2021-12-24 07:51 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java
> +                        application.getId(),
Same is true here as well

2021-12-24 07:51 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java
> +                        application.getId(),
Same here

2021-12-24 07:53 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java
> +                        AnalyticsEvents.GIT_CREATE_BRANCH.getEventName(),
Should we have a separate event to create a branch from remote? That way we can track more info which will be useful once we have import from git flow.

2021-12-24 07:56 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java
> +                            gitPullDTO.getApplication().getOrganizationId(),
Again application is getting modified in `getPullDTO`

2021-12-24 07:56 UTC, abhvsn approved these changes

2021-12-24 09:26 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java
> +                        AnalyticsEvents.GIT_CREATE_BRANCH.getEventName(),
Yeah makes sense to have a separate event.

2021-12-24 10:02 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java
> +                            gitPullDTO.getApplication().getOrganizationId(),
No here we are just formatting the application to response format.

2021-12-24 10:04 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java
> +                        application.getId(),
yeah thats correct but since the analytics looks for git branches, the defaultApplication is also a branch. Does that make sense?

2021-12-24 11:09 UTC, AnaghHegde commented
/ok-to-test sha=848cc0a

2021-12-24 13:31 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java
> +                                AppsmithError.INVALID_GIT_CONFIGURATION.getMessage(),
Are we setting the message correctly before sending to the analytics service? Like the one we are doing just below
```
new AppsmithException(AppsmithError.INVALID_GIT_CONFIGURATION, "Unable to find the git " +
                                "configuration, please configure the your application to use version control service")
```

2021-12-24 13:32 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java
> +                                AppsmithError.INVALID_GIT_CONFIGURATION.getMessage(),
Same here

2021-12-24 13:39 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java
> +                        application.getId(),
What will happen to the data related to rest of the branches? This way all the datapoints will be gathered for the defaultBranch only

2021-12-24 13:45 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java
> +                                                    AppsmithError.DUPLICATE_KEY_USER_ERROR.getMessage("remotes/origin/"),
What error message are we expecting here?

2021-12-24 13:46 UTC, abhvsn commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java
> +                            gitPullDTO.getApplication().getOrganizationId(),
The response format expects all the default Ids, because the client only knows about the default resource ids and not the actual ids if resources are branched from default resource

2021-12-27 05:27 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java
> +                                AppsmithError.INVALID_GIT_CONFIGURATION.getMessage(),
yeah its correct

2021-12-27 05:28 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java
> +                            gitPullDTO.getApplication().getOrganizationId(),
does sanitising the response will help ?

2021-12-27 05:32 UTC, AnaghHegde commented on app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java
> +                                                    AppsmithError.DUPLICATE_KEY_USER_ERROR.getMessage("remotes/origin/"),
The duplicate branch error

2021-12-27 05:39 UTC, AnaghHegde commented
/ok-to-test sha=1455a51

2021-12-27 10:37 UTC, abhvsn approved these changes

2021-12-28 05:23 UTC, AnaghHegde commented
/ok-to-test sha=1455a51

2021-12-28 05:39 UTC, abhvsn approved these changes

2021-12-28 05:40 UTC, AnaghHegde commented
/ok-to-test sha=9c16be3

2021-12-29 05:32 UTC, abhvsn approved these changes

2021-12-29 05:41 UTC, AnaghHegde commented
/ok-to-test sha=8202a7e

2021-12-29 07:23 UTC, merged